### ISSUE TITLE
Running mocha suites in series

### ISSUE THREAD

**Issue by cbebry** [mochajs/mocha#1000]
I am trying to run tests using mocha with what probably is a weird use case, so I'll provide a bit of backstory.
A project I am working on comes with different database configurations which result in a different table structure being created. I would like to be able to test each configuration in the same database in series, but that requires dropping and recreating tables.

Fast forward to using mocha. I love the product and it has been nice to me up until today. Since I need to drop and recreate tables, I have to choose between running each test suite in series, or setup multiple databases for each test suite. Ideally I want to keep a single database for the test process.

This is the style of testing I have been doing now (innards stripped for easier reading)

```
describe('withConfig1', function() {
    before(function(done) {
        //setup including drop/create tables
        done()
    }
    describe('#someFunction()', function() {

    })
}

describe('withConfig2', function() {
    before(function(done) {
        //setup including drop/create tables
        done()
    }
    describe('#someOtherFunction()', function() {

    })
}

```

The problem with this approach, is that `withConfig1` and `withConfig2` get started at the same time and basically try to drop/create the tables at the same time, which leads to several issues.

Is there a way to run these two suites in series? I have tried asyncjs' series method, but it seems that mocha does not pick up the suites when they are enclosed within another function.

It's very possible I'm just doing this wrong, but I searched the issue list and couldn't find much on this topic -- so any help would be very much appreciated. Thank you for your time.

**Comment by Antonius-S** [comment]
I've came here from search but found no solution so had to sort things out by myself.
I achieved serial run by async setup function (TDD interface; `sleep` works as a stub for any useful async function / Promise to wait)
```js
function sleep(timeout)
{
	return new Promise((resolve) => { setTimeout(resolve, timeout); });
}

suite('S1', function()
{
	suiteSetup(async function()
	{
		console.log('## S1 started at', new Date());
		await sleep(200);
	});

	test('Test S1.1', async function()
	{
		await sleep(20);
	});

	suiteTeardown(function(done)
	{
		console.log('## S1 finished at', new Date());
		done();
	});
});

suite('S2', function()
{
	suiteSetup(async function()
	{
		console.log('## S2 started at', new Date());
		await sleep(200);
	});

	test('Test S2.1', async function()
	{
		await sleep(20);
	});

	suiteTeardown(function(done)
	{
		console.log('## S2 finished at', new Date());
		done();
	});
});
```

Output is as below:
```
> mocha --ui tdd

  S1
## S1 started at 2019-12-24T09:23:41.173Z
    √ Test S1.1
## S1 finished at 2019-12-24T09:23:41.403Z

  S2
## S2 started at 2019-12-24T09:23:41.406Z
    √ Test S2.1
## S2 finished at 2019-12-24T09:23:41.630Z

  2 passing (459ms)
```
