### ISSUE TITLE
Assertion Error reports are truncated to not show the error.

### ISSUE THREAD

**Issue by chrisdew** [mochajs/mocha#1007]
Assertion Error reports are truncated so as to not show the difference between the asserted and actual values.

For example:

AssertionError: {"xfer":{"seq":1,"data":{"resupd":{"tom":"2013-10-15T15:28:23Z","reason":{"code":127,"device":109},"pos":{"tof":"2013-10-15T15:2 deepEqual {"xfer":{"seq":1,"data":{"resupd":{"tom":"2013-10-15T15:28:23Z","reason":{"code":127,"device":109},"pos":{"tof":"2013-10-15T15:2

Is there a way of turning the truncation off?

**Comment by boneskull** [comment]
old

**Comment by dlants** [comment]
Not an issue with mocha, but rather node's assert:
https://github.com/nodejs/node-v0.x-archive/issues/7538
