### ISSUE TITLE
wrong async tests with disabled timeout

### ISSUE THREAD

**Issue by segrey** [mochajs/mocha#1027]
Let's consider the following test:
```
var assert = require('assert');

describe('suite', function () {
  it('should be unfinished', function (done) {
  });
  it('should be passed', function () {
    assert.equal(1, 1);
  });
});
```
Test `should be unfinished` is wrong, because `done` callback  isn't called.

Running the test with `mocha --timeout 0 test/` outputs nothing.

Expected behavior: `should be unfinished` should be reported as failed and `should be passed` as passed.

**Comment by boneskull** [comment]
closing as old

**Comment by sam-github** [comment]
https://github.com/mochajs/mocha/issues/1027#issuecomment-28661588

^-- was the problem described above actually fixed? Possibly using an approach like @Schoonology was trying? If not, I don't think this should be closed, its still an open bug, and easy to repro.

**Comment by segrey** [comment]
Can we reopen the issue as the problem is not fixed? Passing `--timeout <big number>` to workaround the issue looks a bit strange as any large magic number looks suspicious.
