### ISSUE TITLE
Add support for "expected" failures

### ISSUE THREAD

**Issue by strk** [mochajs/mocha#1048]
Expected failures are known failures that you want to write a testcase for before having an actual fix. The desired behaviour is that the test exist successfully to signal "everything is ok" until the bug is actually fixed, in which case the test exits with a failure to signal "you need to update the test to stop expecting a failure".

Dejagnu uses X prefix for expected failures, as in "xcheck(...)" or "xcheck_equals(...)", and outputs XFAIL for expected failures (everything ok) and XPASS for unexpected successes (need to update the test).

For mocha I've been thinking this could be implemented in terms of an .expected attributes attached to the exception passed to the "done" function, so that you could write a test like:

  try {
    assert.ok(thisShouldBeTrue);
  } catch (e) {
     e.expected = true;
     throw e;
  }

Or, even better, some extension to the assertion class to do this automatically (but that'd be outside the scope of mocha)

**Comment by graingert** [comment]
@tj it would be really great to have the xfail test tag. I use it all the time in pytest as a better skip.

http://doc.pytest.org/en/latest/skipping.html#mark-a-test-function-as-expected-to-fail

**Comment by graingert** [comment]
I say this as I recently forgot to unskip some tests that now pass.

**Comment by graingert** [comment]
@tj I also had to implement the feature in a half-assed way here: https://github.com/cst/cst/pull/146/files#diff-34468083d0a6e7b743e38f7c1f5783d0R39
