### ISSUE TITLE
Recursive / Sub-Folders

### ISSUE THREAD

**Issue by quangv** [mochajs/mocha#106]
So what's Mocha's philosophy on sub-folders ?

I notice right now that sub-folders for instance  _./test/bugs/*_ would not be run with your standard `./mocha` command...

Is it best practice not to use sub-folders? Or it just a feature that hasn't been implement yet?

Or is there a recommended work-around to make `-r` recursive support unnecessary ?

**Comment by rdsubhas** [comment]
@xpepermint yes `--recursive` ignores `*.coffee` files. A temporary fix is to **not** use globbing when running mocha. e.g. Instead of `mocha ./test/**/*.coffee` just run `mocha ./test` and it works with recursive flag.

**Comment by coryhouse** [comment]
I'm trying to create a cross-platform compatible command line call that runs all tests within a given directory. The problem is, --recursive only applies to the /test folder. I'm placing tests alongside the file under test. 

This glob approach works, but only to one level of depth:

mocha src/**/*.test.js 

I can add another set of asterisks to go one level deeper, but that's obviously not ideal:

mocha src/**/**/*.test.js 

It would be great if Mocha's recursive flag would apply to folders outside of /test.

**Comment by KingScooty** [comment]
+1 @coryhouse!

**Comment by szkrd** [comment]
Can this be done in a cross platform fashion at all? I too would love to keep things "unixy", but that's hardly possible in a cross platform environment.

**Comment by LukasBombach** [comment]
Not sure if `--recursive` is broken when used with a file pattern. If I do this

    mocha --recursive --compilers js:babel-core/register --colors ./server/test/*.spec.js

it will only check files that are direct children of the test folder. Same behavior as without `--recursive`. Doing

    mocha --recursive --compilers js:babel-core/register --colors ./server/test/*.spec.js ./server/test/**/*.spec.js

works though

**Comment by coryhouse** [comment]
@LukasBombach Two tweaks:
1. Add a wildcard under the base dir.
2. Wrap your path in double quotes. You'll likely need to escape the double quotes if you're running this in an npm script.

Final suggestion:

mocha --recursive --compilers js:babel-core/register --colors \"./server/test/**/*.spec.js\"

**Comment by boneskull** [comment]
@LukasBombach @coryhouse 

You want `--recursive` *or* a glob, generally.  Depending on whether your shell expands globs, you may want to put the globspec in double quotes.

```shell
# this should work fine in bash
$ mocha --require babel-register ./server/test/**/*.spec.js
```

```shell
# windows; this causes the globspec to be interpreted by the "glob" module
mocha --require babel-register "./server/test/**/*.spec.js"
```

or

```shell
$ mocha --recursive --require babel-register ./server/test
```

**Comment by boneskull** [comment]
(`--compiler` is generally only necessary if you're working with files that don't have the `.js` extension; it was written with `.coffee` in mind.)
