### ISSUE TITLE
describe.only runs multiple unrelated tests

### ISSUE THREAD

**Issue by lobodpav** [mochajs/mocha#1060]
When multiple unit tests have same name in `describe`, mocha ignores the `.only` setting.

Steps to reproduce:
* Create test1.js and test2.js as per template below
* Run `mocha test1.js test2.js -R spec`
* Expected result
    * You should see only the test1 to get run
* Actual result
    * Both test1 and test2 get run

**test1.js**
```javascript
describe.only('Test', function () {
        it('Should run test1 only', function() {});
});
```

**test2.js**
```javascript
describe('Test', function () {
        it('Should run test2', function() {});
});
```

**Comment by demisx** [comment]
This substring matching is a pain in the rear for us as well. When we mark describe as `.only` we'd expect that only that particular describe block will run. I understand maybe running another describe if the string matches 100%, but substring matches should be excluded IMHO.

**Comment by BobbieBarker** [comment]
+1, I think this issue is sabotaging my tests right now as well.

**Comment by dominataa** [comment]
+1 this is really needs fixing. I would consider this a bug fix, the documented behaviour is:

> The exclusivity feature allows you to run **only the specified suite or test-case** by appending .only() to the function.

I don't think prioritising upsetting someone relying on a bug over everyone else expecting documented behaviour is a good reason to not fix it.

**Comment by boneskull** [comment]
if @mochajs/mocha can agree it's a bug, then it could go into a minor

**Comment by jbnicolai** [comment]
@boneskull rather than discuss that (although I could be convinced to go put it in a minor [that sounds worrying]), how about we change #1782 to become a release of v3.0.0 in stead, merge #1632 and #1481 asap, lift the rest of [milestone V3.0.0](https://github.com/mochajs/mocha/milestones/v3.0.0) to the next major release and ship v3.0.0? :)

**Comment by aft-luke** [comment]
This has bitten me multiple times and kind of stinks. Is there a better way we could do preprocessing of all .only() and build out a tree? The desired behavior is such that I can mark a 'top level' suite with only, then as I work through sub-level describes I can attach another only without having to remove the top-level marker.

**Comment by PerlPong** [comment]
This issue is causing problems for me because I want to describe my tests in a hierarchical structure like below, but then it is not possible to run one suite exclusively.

````
describe('components/Form', function() { ... })
describe('components/FormField', function() { ... })
describe('components/FormControls', function() { ... })
````

**Comment by demisx** [comment]
@PerlPong Why not restructure the specs to be something like this:

```js
context('components', function () {
  describe('Form', function () {...});
  describe('FormField', function () {...});
  describe('FormControls', function () {...});
});
```

**Comment by PerlPong** [comment]
@demisx thanks for the tip, but unfortunately it does not work around this bug. If you execute the following with mocha, both suites will run:

````javascript
var expect = require('chai').expect;

context('components', function() {
    describe.only('Form', function() {
        it('should be true', function () {
            expect(true).to.be.true;
        });
    });
    describe('FormField', function() {
        it('should be false', function () {
            expect(false).to.be.false;
        });
    });
});
````

````
  components
    Form
      ✓ should be true
    FormField
      ✓ should be false
````

**Comment by demisx** [comment]
@PerlPong  I see. Yeah, I believe if the spec `describe` string matches or starts with the string that you set `.only` on, it will run that test too. Ran into this inconvenience in the past myself and had to ensure my describes always start with a unique string.

**Comment by dasilvacontin** [comment]
Closing in favor of #1481. PR #1807 (referencing that other issues) is in the works .
