### ISSUE TITLE
Add Support for dependency injection

### ISSUE THREAD

**Issue by jsdevel** [mochajs/mocha#1074]
It would be really nice to support dependency injection.  On the command line, you could add a flag for a provider module path.  In a browser you could load a provider before your test scripts.  It would probably look like angular's factory pattern.

``` javascript
mocha.factory('someDep', function(){return a;});

//later in my test
describe(function(someDep){
//tests here
});
```

**Comment by ORESoftware** [comment]
DI would be a good replacement for the current --delay functionality which is hacky, no?

**Comment by jsdevel** [comment]
I could see DI saving a lot of `reuiqre('../../../../bla')` in tests though, considering that you could wire up mocks globally with DI.

```
it('should do something asynchronously', function(done, myDbMock) {
  sut(myDbMock).should.eventually.equal(/* user object */).and.notify(done);
});`

**Comment by ORESoftware** [comment]
yeah...saving require verbiage is not so useful, but I think if you could replace --delay option (see mocha homepage) with DI/IoC that would very cool
