### ISSUE TITLE
Correctly handling Mocha timeouts for reporting errors

### ISSUE THREAD

**Issue by whitfin** [mochajs/mocha#1085]
Hi,

I'm in search of a way to call action when the timeout hits. For example, right now I get a timeout error but I'd like to log some text somewhere (as a basic). What is the correct way to catch and process this error?

From what I've seen so far, Mocha just sticks it out in a console, which is fine except I don't want to be monitoring my console the entire time. 

My desired workflow:

```
// Set timeout
this.timeout(10000);

// Actions taking > 10 seconds
setTimeout(function(){
    console.log("Test causing an error");
}, 11000);

// Catch error somehow
console.log("The tests timed out after 10 seconds")
```

Is there a known/good way to do this? If not, is this something which may be added in future?

Thanks in advance.

**Comment by juanmiguelRuaDev** [comment]
Hello, 
Could you tell me if there are any solution to this issue?

Thank you.

**Comment by zackehh** [comment]
@juanmiguelRuaDev a typical way would be to put that setup in an if and make it async - but better still is to just try avoid that requirement and do it in a `before` block.

**Comment by juanmiguelRuaDev** [comment]
@zackehh Thanks, 
The solution has been easier than I had expected.
I had this problem: How to do unit test with a "socket.io-client" if you don't know how long it take to respond?.
I've solved so:

`       var os = require('os')
        var socketio_client = require('socket.io-client');

    var end_point = 'http://' + os.hostname() + ':8081';
    var opts = {forceNew: true};

    describe("async test with socket.io", function () {
    this.timeout(10000);

    it('Response should be an object', function (done) {
        setTimeout(function () {
            var socket_client = socketio_client(end_point, opts);  

            socket_client.emit('event', 'ABCDEF');

            socket_client.on('event response', function (data) {
                data.should.be.an('object');
                socket_client.disconnect();
                done();
            });

            socket_client.on('event response error', function (data) {
                console.error(data);
                socket_client.disconnect();
                done();
                });
            }, 4000);
        });
    });
`

**Comment by zackehh** [comment]
@juanmiguelRuaDev you can remove the `setTimeout`, that won't help anything there. The way you have done it should be good enough I think.

**Comment by juanmiguelRuaDev** [comment]
At first instance I thought like you; but I don't know why without the setTimeout when I have several describe in defined the `this.timeout(1000)` is overcome.
