### ISSUE TITLE
Reporter: TDD+json not showing expected and actual values

### ISSUE THREAD

**Issue by nriesco** [mochajs/mocha#1088]
When the following is ran:
mocha --ui tdd --reporter json /path/to/test.js

Then no expected/actual values information is generated

Whereas these two "reporters" do provide that information:
  - mocha --ui tdd --reporter nyan /path/to/test.js
  - mocha --ui tdd --reporter list /path/to/test.js

![image](https://f.cloud.github.com/assets/1995514/1819947/a21de9e6-70bf-11e3-9e67-f3664547216e.png)

**Comment by jbnicolai** [comment]
I believe this is no longer an issue. Please correct me if I'm wrong and I'll reopen :)
