### ISSUE TITLE
Can tests be marked as Pending at runtime?

### ISSUE THREAD

**Issue by cressie176** [mochajs/mocha#1101]
Is it possible to mark a test as pending while it's being executed? Something like `this.emit('pending')` or `this.pending = true`?

The reason for this is that [yadda](https://github.com/acuminous/yadda) executes multiple bdd steps per mocha test, and I've had a [feature request](https://github.com/acuminous/yadda/issues/32) to change the test to pending if one of the bdd steps hasn't been implemented.

Thanks.

**Comment by molmedoz** [comment]
Hi,
I had the same problem. I could resolve this, storing result of test and before execute each test read if this test is blocked.
Each test knows that tests will be blocked if fails. If the current test is blocked, the test will be skipped.

```javascript
var featuresFiles = new Yadda.FeatureFileSearch('./test/features');
var nFeaturesFiles = featuresFiles.list().length;
featuresFiles.each(function(file, nFile) {
	//console.log('Iniciamos el test');
	featureFile(file, function(feature) {
	scenarios(feature.scenarios, function(scenario) {
		describe(scenario.title, function() {
			before(function() {
				if(infoTest[scenario.annotations.cp] && infoTest[scenario.annotations.cp].blocked){
					this.pending = true;
					this.skip();
				}
				//do staffs
			});
			//code
			after(function(done){
				if(this.failed || this.pending){
					var blocked = (scenario.annotations.blocking)?JSON.parse(scenario.annotations.blocking) : [];
					if(blocked.length){
						blocked.map(function(test){
							infoTest[test.cp].blocked = true;
						});
					}
				}
			}
			//do staffs
		}
	}
}
```
I hope this will help you

**Comment by danielstjules** [comment]
Sounds like https://github.com/mochajs/mocha/pull/1618 would work
