### ISSUE TITLE
Support --harmony in mocha.opts

### ISSUE THREAD

**Issue by kornelski** [mochajs/mocha#1109]
My code works only with `node --harmony`, so I can't run my tests simply by running `mocha`.

```
$ mocha

  error: unknown option `--harmony'
```

**Comment by jonathanconway** [comment]
Not working for me.

**Comment by boneskull** [comment]
@jonathanconway need more information... what version of Mocha, how are you running it, in which way does it "not work", etc.

**Comment by jonathanconway** [comment]
@boneskull Sorry about that. Mocha version is 2.2.5. Node version is v12.0.5. I did an `npm install mocha --save-dev`.

I have a `tests` folder, containing `index.test.js` shown below:

`var project = require('../index.js');

describe('project', function () {
  it('should work as expected', function (done) {
  	project();

    done();
  });
});`

My `mocha.opts` file (in the same folder):

`--harmony
--harmony-proxies`

The project being tests contains a reference to Proxy.

When I run `./node_modules/.bin/_mocha` it outputs:

`    1) should work as expected


  0 passing (11ms)
  1 failing

  1) project should work as expected:
     ReferenceError: Proxy is not defined
      at project (index.js:5:18)
      at Context.<anonymous> (test/index.test.js:8:28)`

**Comment by boneskull** [comment]
this should be closed by #1519

**Comment by boneskull** [comment]
(you do indeed need `--harmony-proxies`, not just `--harmony`)

**Comment by jonathanconway** [comment]
Thanks @boneskull! That's awesome!
