### ISSUE TITLE
Documentation around glob patterns and shell expansion

### ISSUE THREAD

**Issue by jsdevel** [mochajs/mocha#1115]
Not sure if it is needed, but it may be worth noting that due to shell expansion, glob patterns should be wrapped in single quotes on unix shells.

`mocha -w -r should 'test/**/*.js'`

Using that would render the --recursive flag useless.

**Comment by jbnicolai** [comment]
Anyone willing to create a PR for this?

**Comment by boneskull** [comment]
continue in mochajs/mochajs.github.io#8

**Comment by boneskull** [comment]
nope. see #3136
