### ISSUE TITLE
Docs should make clear that the use of done(); does not make further test wait for completion.

### ISSUE THREAD

**Issue by cndreiter** [mochajs/mocha#1126]
The documention states: "By adding a callback (usually named done) to it() Mocha will know that it should wait for completion."

This sounds like: "All tests that succeed in the code will wait until the `done` of this test is called" to me. At least it can be interpreted in that way, which I did. It confused me a lot.

Please make this unambiguous.

**Comment by jbnicolai** [comment]
I disagree that there's any ambiguity.

If anyone else feels this way, please drop a comment and we'll consider changing it.
