### ISSUE TITLE
path.resolve is not a function

### ISSUE THREAD

**Issue by pocesar** [mochajs/mocha#1148]
```
TypeError: path.resolve is not a function
file = path.resolve(file);
```

trying to run the test on the browser "manually" (without using karma). tried to locate `path`, it's trying to `require('browser/path')` but:

``` js
require.register("browser/fs.js", function(module, exports, require){

}); // module: browser/fs.js

require.register("browser/path.js", function(module, exports, require){

}); // module: browser/path.js
```

it's empty. my build is borked? (installed through bower)

**Comment by gene1974** [comment]
> ah heh, the line is in here: https://github.com/visionmedia/mocha/blob/master/mocha.js#L1534 and requiring in here https://github.com/visionmedia/mocha/blob/master/mocha.js#L1375

I cannot open the links
