### ISSUE TITLE
Add 'around' and 'aroundEach'

### ISSUE THREAD

**Issue by adamhooper** [mochajs/mocha#1153]
Right now, we can enhance our suites with `before`, `beforeEach`, `after`, and `afterEach`.

That ignores a whole class of helper function: those that temporarily modify global state. (You know they exist!)

For instance, take this CoffeeScript function:

```
withAnimationsDisabled = (code) ->
  x = jQuery.fx.off
  jQuery.fx.off = true
  code()
  jQuery.fx.off = x
```

I'd find value if Mocha would let me do this:

```
aroundEach(withAnimationsDisabled)
```

Without `aroundEach` or `around`, there's no way to use a function such as `withAnimationsDisabled`. You can _test_ it, but you can't use it as a helper unless you write it in every test.

I feel that `around` and `aroundEach` promote good test suite hygiene, so I think Mocha should support them.

Precedents:
- RSpec: `around(:each)` and `around(:all)`: https://www.relishapp.com/rspec/rspec-core/v/3-0/docs/hooks/around-hooks
- ScalaTest `withFixture()`: http://www.scalatest.org/user_guide/sharing_fixtures#withFixtureNoArgTest
- Specs2 `Around`: http://etorreborre.github.io/specs2/guide/org.specs2.guide.Structure.html#Around

I know, I know, you can bend `beforeEach` and `afterEach` to come close to what `aroundEach` would do. But `aroundEach` is better:
- `aroundEach` separates concerns. Every `aroundEach` can be independent of every other `aroundEach`. That's not the case with `beforeEach` and `afterEach`, which are often intertwined.
- `aroundEach` implicitly does things in the correct order. If a `beforeEach` initializes 1. a database connection, and 2. some global variable pulled from the database, then code in `afterEach` sometimes needs to be written "backwards". (2. remove global variable; 1. kill database connection.) `aroundEach` makes the _correct_ ordering the _obvious_ ordering.
- `aroundEach` provides a friendly interface for coding test helpers (like my `withAnimationsDisabled` example).

Of course, async support would be amazing. It seems straightforward, right?

I'd be happy to contribute lots of feedback and maybe some code, if this feature is a welcome one. I'm using Mocha for an integration-test suite, and it needs lots of this sort of helper (e.g., "create user / drop user").

**Comment by yevhene** [comment]
@kwarunek @travisjeffery I need to implement something like Ruby's (database_cleaner)[https://github.com/DatabaseCleaner/database_cleaner], for sequelize. Can you suggest, how I can  wrap each test case in separate sequelize transaction without `aroundEach`?
