### ISSUE TITLE
There is no `require` interface

### ISSUE THREAD

**Issue by xcvz** [mochajs/mocha#1160]
The [homepage](http://visionmedia.github.io/mocha/) mentions a `require` interface:

> The `require` interface allows you to require the `describe` and friend words directly using `require` and call them whatever you want. This interface is also useful if you want to avoid global variables in your tests.
## The issue:

Unfortunately, I get the following error when I run `mocha` using `--ui require`:

> Error: invalid interface "require"

The error comes from [this code](https://github.com/visionmedia/mocha/blob/master/lib/mocha.js#L154):

``` javascript
this._ui = exports.interfaces[name];
if (!this._ui) try { this._ui = require(name); } catch (err) {};
if (!this._ui) throw new Error('invalid interface "' + name + '"');
```

Sure enough, [`lib/interfaces/`](https://github.com/visionmedia/mocha/tree/master/lib/interfaces) doesn't contain `require.js`, and [`lib/interfaces/index.js`](https://github.com/visionmedia/mocha/blob/c493d449f7c95ac5274ebbeffb2987b95e141aec/lib/interfaces/index.js) doesn't export `require`.
## Background:

Overall, I want to use the `bdd` interface. However, at the top of each test file, I want to use the `suite` function to prevent excessive indentation.

Obviously, I have an easy workaround—not indenting the contents of the top-level `describe` callback.

**Comment by ELLIOTTCABLE** [comment]
Hi! I hope necro'ing this Issue isn't a huge deal; but I'm running into exactly this problem.

There's a pull-request merged above that claims to solve this by making the documentation clearer, except … the documentation still isn't clear, at least to me?

The documentation currently states:

> *Note:* The require interface cannot be run via the `node` executable, and must be run via `mocha`.

Except, I *am* invoking via the `mocha` executable, and I'm still seeing the same error:

```sh
$ mocha --ui require # ...
/Users/ec/Desktop/test_power_assert/node_modules/mocha/lib/mocha.js:195
      throw new Error('invalid interface "' + name + '"');
      ^

Error: invalid interface "require"
    at Mocha.ui (/Users/ec/Desktop/test_power_assert/node_modules/mocha/lib/mocha.js:195:13)
    # ...
```

How, precisely, is one to invoke `mocha` in such a way that it won't expose any globals whatsoever, and will only be available exactly as required / as a module? `(=`

**Comment by ScottFreeCode** [comment]
Unfortunately, the "require interface" is an option to avoid *using* global variables in the tests, but not to avoid *creating* them in the first place -- in fact, if I recall correctly, what you can `require` is just references to the global variables from whichever interface was selected. I tried to come up with a fix for this -- a way to assign the globals to a dummy object and then still export them, or something along those lines -- but I couldn't get it to work due to obscure logic in Mocha's underbelly. See issue #2765 for a timeline of my investigation.

**Comment by ELLIOTTCABLE** [comment]
Thanks, @ScottFreeCode — keeping my eye on that Issue; I'll leave this issue be, as work progresses on #2765.

<3

**Comment by myuseringithub** [comment]
I would like to use mocha as a module with the `require interface` not through `mocha` cli. Any chance this behavior will change ?

**Comment by plroebuck** [comment]
@myuseringithub, [knock yourself out](https://mochajs.org/#require) then...
However poorly described, don't try to specify `--ui require` as that won't fly.

But I don't think this really buys you anything as opposed to just using the BDD-default interface.

**Comment by myuseringithub** [comment]
@plroebuck Already tried and got upset. Abstracting the Mocha functionality onto `module` globally doesn't benefit much either, why choose it over the native approach ? 
```
import { describe, it, assert } from 'mocha'
```

It even removes the need for an `ui` option: 
```
import { describe as suite, it as test, assert as 🛑 } from 'mocha'
```

**Comment by plroebuck** [comment]
_Somewhere_ in one of these issues, someone gave the correct syntax for `importing` Mocha's globals. You didn't mention ES6 earlier.
