### ISSUE TITLE
HTMLCov should include test failures

### ISSUE THREAD

**Issue by sgilroy** [mochajs/mocha#1166]
We currently have some tests that are only failing when we run the tests with coverage on our CI server. That is, all tests pass with the spec reporter, but when we subsequently re-run the tests with the HTMLCov reporter, one or more of the tests occasionally fails. We can't figure out which test is failing because HTMLCov does not include details about test failures (unlike JSONCov).

**Comment by jbnicolai** [comment]
@cscott how about you create a PR for this, since you've already implemented it?

**Comment by jeversmann** [comment]
It looks like this issue is about code that has since been rewritten, and it can probably be closed.

**Comment by dasilvacontin** [comment]
@jeversmann Right there. HTMLCov/JSONCov no longer in the codebase. Closing.
