### ISSUE TITLE
EventEmitter leak

### ISSUE THREAD

**Issue by tj** [mochajs/mocha#117]
```

  ..........(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace: 
    at Hook.<anonymous> (events.js:133:17)
    at next (/Users/tj/projects/express-resource/node_modules/mocha/lib/runner.js:157:10)
    at Array.0 (/Users/tj/projects/express-resource/node_modules/mocha/lib/runner.js:169:5)
    at EventEmitter._tickCallback (node.js:192:40)
.....

```

due to the hook error event. we exit currently anyway so it's not a big deal but the warning is annoying

**Comment by RavenHursT** [comment]
Awesome.. this is still around 2 years later and hasn't been addressed.  I'm on 2.2.5 and I'm seeing the same error, which is causing my test server to skip tests...  Can we get this addressed?

**Comment by boneskull** [comment]
@RavenHursT sure!  My rate is $150/hr. 

Maybe it hasn't been addressed because it was closed, and nobody sent any sort of reproduction plan. So, you could start there. otherwise I'm afraid your chances are slim-to-none

**Comment by TheDataDesigner** [comment]
Not sure if it matters, but I'm getting this error on Mocha 5.0.4

**Comment by g1eny0ung** [comment]
This warning also appears in Mocha 5.2.0.

**Comment by boneskull** [comment]
if someone has a [MCVE](https://stackoverflow.com/help/mcve), please provide one in  a [new issue](/mochajs/mocha/issues/new).  Locking this issue.
