### ISSUE TITLE
Mocha aliased via `npm test` fails to glob all files

### ISSUE THREAD

**Issue by OliverJAsh** [mochajs/mocha#1175]
In the example enclosed, I have this tree:

```
.
├── package.json
└── test
    ├── foo.js
    └── lib
        └── bar.js

2 directories, 3 files
```

Setup:

```
npm install
```

Run the tests:

```
./node_modules/.bin/mocha --reporter spec test/**/*.js
```

Both `test/foo.js` and `test/lib/bar.js` are ran. Now run the tests via the same command, but aliased using npm:

```
npm test
```

Only `test/lib/bar.js` is ran. The glob fails to detect `test/foo.js`, despite it being the same command.

Example: http://cl.ly/0M130n2u1t40

**Comment by christiansakai** [comment]
Hello, I have this file structure
+-- common
|   +-- foo
|   +--+-- foo.js
|   +--+-- foo.spec.js
|   +-- bar
|   +--+--baz
|   +--+--+-- baz.js
|   +--+--+-- baz.spec.js

when i do 
```
./node_modules/.bin/mocha ./common/**/*spec.js
```
only foo.spec.js run

but when I do
```
./node_modules/.bin/mocha './common/**/*spec.js'
```
only baz.spec.js run

is there a way to run all of them?

**Comment by thalesfsp** [comment]
@mrjoelkemp Where it is mentioned in the Mocha docs?

**Comment by mrjoelkemp** [comment]
@thalesfsp no idea anymore. This discussion happened ages ago; I'm sure the docs have changed a lot by now :)
