### ISSUE TITLE
done() invoked with non-Error

### ISSUE THREAD

**Issue by stevenvachon** [mochajs/mocha#1187]
Using `done()` as a callback for other libraries that add their own argument data results in errors thrown.

``` js
something().then(done);
```

The only way around it is:

``` js
something().then( function(){ done() } );
```

It'd be great if Mocha accepted and ignored non-Error arguments to avoid the extra code.

**Comment by enthal** [comment]
But there has never been a requirement for Error class when the `err` object is not thrown as an exception.  It's just a parameter.  If mocha is throwing the object itself for flow control, then wrapping is mocha's concern, not the client code.

**Comment by Nate-Wilkins** [comment]
I agree with @enthal considering I'm trying to queue promises up and execute a done callback like so:

```js
Q.all(promises).then(done);
```
But when done is supplied an array of undefined errors it throws because it's testing to see if the first argument is `!undefined` instead of checking if it's an error or rather is an array that contains errors. 

Concluding: Does mocha currently support promises? And if not is it at some point?

**Comment by boneskull** [comment]
@enthal The first parameter to the `err, res` pattern is implied to be an error.  So, I disagree that it's "just" a parameter; it has a type.

@Nate-Wilkins It occurs to me we need better documentation about how to do this, but yes, it supports promises.

```js
// note lack of `done` parameter
it('should support promises', function() {
  return Q.all(promises)
    .then(function(res) { 
      // make some assertions
    });
});
```

**Comment by Nate-Wilkins** [comment]
@boneskull ingenious thanks!

**Comment by jtara1** [comment]
So what's the convention if the error isn't a type of `Error`? I'm using mocha to test my rest api and it returns some json object in all responses.

So I guess I'll just do this, but it feels weird

```
describe('have james, a user, leave the game', () => {
  it('should remove james from the game then delete the empty game', function(done) {
    game.leave(user.id)
      .then(json => {
        assert(true);
        done();
      })
      .catch(err => {
        done(new Error(err.message));
      })
  });
});
```

It'd probably be better to throw in a check for `err instanceof Error` then make a new error object if it's not an `Error`

This particular test func should be using the expect func and `to` and `throw` method from mocha instead of what's there.

**Comment by outsideris** [comment]
@jtara1 Why doesn't `game.leave()` throw `Error` instance? And how do you throw your error?

**Comment by boneskull** [comment]
@jtara1 [boom](https://npm.im/boom) might help you.

`to` and `throw` are (likely) [Chai](https://npm.im/chai) methods.

Also, try this sort of thing instead of combining `Promise`s with `done()`:

```js
describe('have james, a user, leave the game', () => {
  it('should remove james from the game then delete the empty game', function() {
    return game.leave(user.id)
      .then(json => {
        assert(true);
      })
      .catch(err => {
        throw new Error(err.message);
      });
  });
});
```

**Comment by iqianxing** [comment]
I wrote some code to test this problem.
```
var request = require('request');

function httpCallback(data, callback) {

  if (!data.ip || !data.port) {
    getProvider(data, function (provider) {
      data.ip = provider.ip || "192.24.7.021";
      data.port = provider.port || 80;
      httpCallback(data, callback);
    });

    return;
  }

  var reqData = {
    body: data,
    json: true,
  }

  request.post('https://github.githubassets.com/apple-touch-icon-114x114.png', reqData, function (err, response, body) {
    if (callback && callback.length) {
      callback && callback(body);
    } else {
      callback && callback();
    }
  });

  function getProvider(opts, callback) {

    request.get("https://github.com/manifest.json", {
      json: true,
    }, function (error, response, body) {
      if (callback && callback.length) {
        var provider = body;
        callback && callback(provider);
      } else {
        callback && callback();
      }
    });
  }
}
if (module.parent && /mocha\.js/.test(module.parent.id)) {
  describe("# Mocha callback", function () {
    this.timeout(0);

    it("## Http callback", function (done) {
      var data = {
        ip: '192.24.7.021',
      }
      httpCallback(data, function(){
        done();
      });
    });

    it("## Http callback", function (done) {
      var data = {
        ip: '192.24.7.021',
      }
      httpCallback(data, done);
    });
  })
}

```
Run `mocha` command, the test output:
![image](https://user-images.githubusercontent.com/2938263/61994229-a9ba5280-b0aa-11e9-8510-db1cf08b9df2.png)
