### ISSUE TITLE
#1164 breaks before-each blocks' contexts

### ISSUE THREAD

**Issue by moll** [mochajs/mocha#1195]
v1.18.2 passes, yet the latest change (#1164) to fix context leak breaks the following:

``` javascript
describe("Outer", function() {
  beforeEach(function() { this.context = this })

  describe("Inner", function() {
    beforeEach(function() { this.context.must.equal(this) })
    it("must not fail", function() {})
  })
})
```

**Comment by moll** [comment]
Could this issue be looked again please?

I occasionally use the following pattern (https://github.com/moll/node-mitm/blob/7469b18f89c5d5f2016ef7b940323ad9c0ecea2b/test/index_test.js#L126) to reset and replace an object that was set in a `beforeEach` block. If the before blocks didn't use inheritance like I've proposed, this wouldn't be an issue. Currently, however, it is, as the replacement `this.mitm = Mitm()` won't visible to the `afterEach` and it therefore calls `this.mitm.disable`, again, on the old object.

**Comment by jupiter** [comment]
I used to use context in the same way as you @moll, and reluctantly changed all my tests to what is generally considered best practice, i.e. creating a var in the describe scope. It did mean that devs need to be careful not to set these values outside a beforeEach block, and to only use the value set in the beforeEach, which is why I hated it to start out with. But now, the pattern is fairly well established, and (hopefully) doesn't get missed by anyone.

**Comment by moll** [comment]
Thanks for the explanation. I can't say I agree with it being a best practice though. I think it's _not_ a practice worth following regardless of its popularity and I'd rather avoid it to work around what I described here as a bug. Why else does this context feature exists then. :-)

**Comment by jupiter** [comment]
True, I don't agree with the isolation of contexts, but if you want to change the value set in a higher-up context, this is the only way to do it.

**Comment by moll** [comment]
> but if you want to change the value set in a higher-up context, this is the only way to do it.

That's true. Right now. ^_^ Hence my revival of this thread.

**Comment by jupiter** [comment]
It seems to me someone found they liked isolated contexts and because it is a philosophical improvement rather than an actual one, it seems like a battle not worth fighting. :)

**Comment by moll** [comment]
Well, I too think contexts need to be isolated from test cases, but trying to protect contexts from each-blocks is a fool's errand. Any more complex object beyond a primitive won't be shadowed. I might've already described it fully above.

**Comment by jupiter** [comment]
I agree.
