### ISSUE TITLE
html-cov add markers or special text for missed lines

### ISSUE THREAD

**Issue by SheetJSDev** [mochajs/mocha#1196]
To find missed lines in the html coverage reporter, you have to scroll down and find the lines in red.  There is no easy way to find the first missed line -- you have to scroll down

gcov solves this by writing `#####` rather than `0` for lines that are never hit, which is a good solution (then I can search for "#####" in the browser and find the misses quickly)

Alternatively, the page could be designed so that there are links in the overview area that jump to the missing lines/blocks.

**Comment by jbnicolai** [comment]
Don't feel strongly about this, and closing as this issue hasn't been commented on in a year.

If anyone has the same issue: feel free to comment and we'll consider re-opening/implementing the feature. A PR always helps, of course ;-)
