### ISSUE TITLE
Node Built-in debug in api call?

### ISSUE THREAD

**Issue by nicosommi** [mochajs/mocha#1203]
Hello, I'm asking for this because it can be very useful to configure node built-in debug modes on tasks runners like gulp or grunt through the gulp-mocha plugin for example.

Or there is already some way to do it already? (I tried passing different options to Mocha constructor but they didn't work and I can't find how it works looking at the code)
Or maybe gulp/grunt has to support this?

Currently I can do this by using nodemon like this:
nodemon({script: '/home/usuario/.nvm/v0.10.26/lib/node_modules/mocha/bin/_mocha',
    nodeArgs: ['debug']});

(Also I think it can be done with exec/child_process but I cannot get it to work with that, it's a stdin mapping issue. It works with nodemon because it uses fork and that maps automatically stdin and stdout from the parent)

I came to this because I wanted to clean all worflow paths to built in debugger.
For more info: http://nicosommi.com/?p=284

Thanks

**Comment by jbnicolai** [comment]
There's already `mocha -d|--debug` http://mochajs.org/#usage
