### ISSUE TITLE
Ability to skip tests in beforeEach

### ISSUE THREAD

**Issue by daleharvey** [mochajs/mocha#1208]
We have a bunch of tests that we only run optionally based on the environment, we use various ways to do if (build time flags, just putting tests inside an if), but the best place for us to do it would be inside `beforeEach`, it would be nice if there was a way to provide something to done that indicated the test should be skipped

Can try coming up with a patch if that seems like something likely to be merged?

**Comment by dangerbacon** [comment]
For anyone finding this issue:  this little snippet of code should help you work around the issue:
`beforeEach(function()
{
  if (YOUR_CONDITION_HERE) this.currentTest.fn = function() { this.skip(); }
});`

**Comment by artyomtrityak** [comment]
you can also just use this.skip ie
```
beforeEach(function() {
  if (FAILED_TESTS[this.currentTest.file]) {
    this.skip();
  }
});
```
