### ISSUE TITLE
TODO tests

### ISSUE THREAD

**Issue by arodland** [mochajs/mocha#1236]
TODO tests are like pending tests, but better. Perl has them. They're used for tests that are aspirational — a feature hasn't been implemented yet, a bug hasn't been fixed yet, etc. and that's okay, but we know how we _want_ it to be.

When you declare a test as TODO it is still run (unlike an `xit` or giving `it` no function at all). When it fails, that's okay — if we're being verbose we report the fact that it "failed" but with a note that it's TODO, and it doesn't increase the failure count or make the whole suite fail. If we're not being verbose then the effect is very similar to the test not existing at all (maybe a TODO counter gets incremented).

When a TODO test _passes_, it's added to a list of "unexpectedly passing TODO tests" and generates output that gets the developer's attention. The idea is: great, you tested ahead, you wrote a test for how this thing should work, but you admitted it wasn't working yet and you didn't want to enforce that it passed. But now it **is** working, so remove the TODO flag so you can commit to not breaking it in the future!

**Comment by Slayer95** [comment]
+1
