### ISSUE TITLE
Including files with 0% coverage in report

### ISSUE THREAD

**Issue by Irialad** [mochajs/mocha#1249]
I have an issue where I'm trying to get accurate code coverage numbers for a node package. However, after a test run, files that aren't covered are missing from the report.

At the moment, I'm trying to force them to be there by recursing through the directory which contains the source instrumented by jscoverage and in each instrumented file calling the first three lines after the anonymous function at the beginning which initializes the global jscoverage objects/functions.

In order to do this, I've copied+pasted that anonymous function into my module which is -r required from the mocha command line. This all seems like some dangerous black magic which is destined to break at the first change in any of these tools.

Is there an established way of accomplishing this which will accurately report on source files with 0% coverage?

**Comment by jbnicolai** [comment]
I'm afraid there's no other way to do this, as the files aren't even loaded and so there's no way to know about them. 

Apologies for the late response.
