### ISSUE TITLE
setTimeout inside async test not behaving correctly

### ISSUE THREAD

**Issue by vernak2539** [mochajs/mocha#1252]
I'm having a problem with a timeout inside an async test. I'm using mocha ~1.20.1 and chai ~1.9.1. 

I have other async tests running and they work, but they do not use setTimeout. I've tried changing the duration, but that hasn't worked also.

I would expect the output to be something like this

```
✓ should deliver successful response (291ms)
```

but it just gives me a line as if it was ran synchronously

```
1) should return true when token is expired based on time
```

**test**

``` js
it( 'should return true when token is expired based on time', function( done ) {
    var AuthClient = new Client({
        clientId: 'test'
        , clientSecret: 'test'
        , expiration: 1
    });

    setTimeout( function() {
        expect( AuthClient.checkExpired() ).to.be.true;
        done();
    }, 1000 );
});
```

**Error**

```
Error: timeout of 2000ms exceeded
      at null.<anonymous> (/usr/local/lib/node_modules/mocha/lib/runnable.js:139:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by wenwuwu** [comment]
I had the same problem. Finally I found setTimeout() does not work properly with fake timer: 

`var clock  = sinon.useFakeTimers(); // Remove this line. `

**Comment by DominicTobias** [comment]
I made a Promise function which does the delay as promises work better with async/await:

```js
function timeout(fn, delay) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      try {
        fn();
        resolve();
      } catch(err) {
        reject(err);
      } 
    }, delay);
  });
}
```

And using it:

```js
it('resolves new value from cache after expiry time', async () => {
    const cacheFn = () => cache.resolve('asyncItem', () => Math.random(), '1s');
    const firstValue = await cacheFn();
    const cachedValueBefore = await cacheFn();

    expect(firstValue).to.eql(cachedValueBefore);

    return await timeout(async () => {
      const cachedValueAfter = await cacheFn();
      expect(firstValue).to.not.eql(cachedValueAfter);
    }, 1100);
  });
```

**Comment by SergiuToporjinschi** [comment]
> useFakeTimers

YOU SAVED ME

**Comment by frrahat** [comment]
> I had the same problem. It drove me damn crazy. Finally I found setTimeout() does not work properly while you have fake timer in your code, simply remove sinon.useFakeTimers() :
> 
> `var clock = sinon.useFakeTimers(); // Remove this line.`

That was my case as well. In case you can't find where this faking is happening, you can just use
```js
sinon.clock.restore();
```
to teardown the fake timers.
