### ISSUE TITLE
Better error reporting for stupid developers :)

### ISSUE THREAD

**Issue by bennidi** [mochajs/mocha#1259]
Being new to mocha, in one of my early test cases I wrote

```
describe('Composed DSM', function(){
            expect(dsm.state().sid.observable()).to.be(32133);
            expect(dsm.sid).to.be(32133);
        });

// instead of
describe('Composed DSM', function(){
        it('should have the required public interface', function(){
            expect(dsm.state().sid.observable()).to.be(32133);
            expect(dsm.sid).to.be(32133);
        });
    })
```

Although this is clearly a stupid mistake, mochas error message kind of also was:
`expected undefined to not equal undefined`

I think: something like: "Missing specification of it()" would have spared me half an hour of looking through all the code changes I had made before"

**Comment by ghostsquad** [comment]
I don't think this issue should be closed. The seems very legitimate, and I too have spent more time than I'd like trying to figure out exactly what it is that is "undefined".

**Comment by danielstjules** [comment]
Sorry, but there's no reason you can't have assertions outside of a spec. It's completely valid code. Some developers even use assertions within their src, outside tests.
