### ISSUE TITLE
--compilers coffee:coffee-script not working?

### ISSUE THREAD

**Issue by xpepermint** [mochajs/mocha#1275]
``` javascript
// test/mocha.opts
--compilers coffee:coffee-script
--reporter spec
--recursive
--watch
--check-leaks
```

``` javascript
// test/upstart.coffee
process.env.NODE_ENV = 'test'
process.env.PORT = 1338

Sails = require('sails/lib/app')
app = Sails()

before (done) ->
  app.lift({ globals: false }, done)

after (done) ->
  app.lower(done)
```

If I run `mocha` I get

``` javascript
/Users/me/Work/proj/test/upstart.coffee:7
before (done) ->
               ^
SyntaxError: Unexpected token >
  at exports.runInThisContext (vm.js:69:16)
  at Module._compile (module.js:432:25)
  at Object.Module._extensions..js (module.js:467:10)
```

**Comment by ringods** [comment]
While trying to create a pull request for webdriver-sizzle, I also bump into this. I know nothing about mocha or coffeescript, so I could use a helping hand here.

https://github.com/ringods/webdriver-sizzle/commit/e3db75cd250d7d20258796c90483597df5a590c2

@TheLudd I added the `--require coffee-script` to `test/mocha.opts` but this doesn't resolve this. What now?

**Comment by TheLudd** [comment]
@ringods In your commit the dependency name has changed from `coffee-script` to `coffeescript`. You probably need to change this in your mocha.opts file as well.

**Comment by ringods** [comment]
@TheLudd that was indeed the problem. 

After updating the name, I now bump in a failing test with promises and callbacks... *sigh*

**Comment by boneskull** [comment]
Mocha only looks for `test/mocha.opts`.  if it's not there, you must use `--opts /wherever/it/is`.
