### ISSUE TITLE
done() not working inside promise

### ISSUE THREAD

**Issue by GamingCoder** [mochajs/mocha#1283]
I use mocha and chai to test my AngularJS frontend. My problem is that done does`nt seem to end the test and gives me a timeout error.

``` coffeescript
it 'should save test if channel exists', (done) - > test = {
    title: 'found'
    keywords: []
}
$httpBackend.when 'GET', url + test.title.respond {
    "pageInfo": {
        "totalResults": 1,
            "resultsPerPage": 5
    },
        "items": [{
        "id": "id_found",
            "snippet": {
            "title": "Found",
                "thumbnails": {
                "default": {
                    "url": "http://example.com/thumbnail.png"
                }
            }
        }
    }]
}
factory.add test.then(r) - > expect(r.ok).to.equal true
expect(r.id).to.equal 'id_found'
done()
    .
catch (err) -> done err
$httpBackend.flush()
```

**Comment by majidhassan** [comment]
I'm having the same issue using mochajs and chai.expect. And I tried both approaches mentioned here.

@travisjeffery's approach:

```javascript
it ("Test", function(done) {
    return Promise.resolve()
    .then(function() {
        expect(1).to.equal(2);
    });
});
```

@jonathanong's approach:

```javascript
it ("Test", function(done) {
    Promise.resolve()
    .then(function() {
        expect(1).to.equal(2);
        done();
    }, done);
});
```

I'm getting the exact same error mentioned here for both approaches:

![screen shot 2017-03-29 at 7 08 35 pm](https://cloud.githubusercontent.com/assets/18425522/24467018/261bc066-14b3-11e7-9584-f627c55abfbd.png)

Any ideas?

**Comment by ScottFreeCode** [comment]
If you're using the current version of Mocha, the first one should give you a different error about not being allowed to both return a promise and use `done` (there were cases where we could not detect mistakes with both used in combination and the previous behavior when both were used was never correct anyway [it ignored one of them, I forget which]). **Changing `(done)` to `()` should fix it.**

If that does not work, the second one should work if `, done);` is changed to `).catch(done);` -- the second handler passed to `then` does not handle exceptions thrown by the first handler passed to `then`.

**Comment by majidhassan** [comment]
@ScottFreeCode Great! Thanks, I tried both approaches you suggested and they both work. However, for the first approach I did indeed get a timeout error rather than not being allowed to return a promise and use done. For the record, I'm using gulp-mocha. So, not sure if this would handle things differently.

Thanks again for the quick reply :)
