### ISSUE TITLE
customFds deprecated

### ISSUE THREAD

**Issue by taddei** [mochajs/mocha#1286]
I'm using node version v0.11.14-pre with mocha version 1.21.1.
No tests are running as I get a "deprecated" error:

```
child_process: customFds option is deprecated, use stdio instead.
```

Reading in the nodejs documentation http://nodejs.org/api/child_process.html this option has been deprecated.

**Comment by davestream** [comment]
Hi everyone I am sorry but I am missing some details. Could someone explain this common error with Node js ver 0.12

**Comment by davestream** [comment]
I am running ver Nodejs 0.12 and npm 2.5.1 and I am trying to install express web framework and the all gems and I have the same issue when I run mocha tests command line, there is some incompatibilities version?

**Comment by martinhbramwell** [comment]
+1

**Comment by boneskull** [comment]
@davestream @martinhbramwell this fix was merged in #1287 which probably has not been released, so if you want it, clone this repo

**Comment by hechangmin** [comment]
[root@yw-0-0 server]# sudo npm install canvas
npm WARN package.json motor@1.0.1 No repository field.
npm WARN package.json motor@1.0.1 No README data
|
> canvas@1.2.1 install /data/app/smart.cmcm.com/server/node_modules/canvas
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/data/nodejs/node-v0.12.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 2.6.32-504.el6.x86_64
gyp ERR! command "node" "/data/nodejs/node-v0.12.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/app/smart.cmcm.com/server/node_modules/canvas
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 2.6.32-504.el6.x86_64
npm ERR! argv "/usr/sbin/node" "/usr/sbin/npm" "install" "canvas"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/app/smart.cmcm.com/server/npm-debug.log

**Comment by boneskull** [comment]
this has been resolved; not sure why people are posting here. locking
