### ISSUE TITLE
Enable debug mode

### ISSUE THREAD

**Issue by diogogmt** [mochajs/mocha#1293]
We should be able to enable mocha debug mode from the command line interface.
For example, when running a mocha test it should be possible to turn that running instance of mocha into debug mode:
$: mocha mytest.js --debug

Browsing through the source I can see that the library debug() is being used - https://github.com/visionmedia/debug
After adding the following statement to the /mocha.js file I was able to get the debug logs:

``` javascript
require('debug').enable('mocha:*');
```

I would assume that the option to flag debug on/off already exists but it is not documented.
If it does exists, a link in the docs page should be added describing how to enable debug mode.
If it doesn't exists I would suggest that the feature be added to the code base.

**Comment by togakangaroo** [comment]
This never got added. Can it get added?
