### ISSUE TITLE
update Programmatic API documentation

### ISSUE THREAD

**Issue by DepthDeluxe** [mochajs/mocha#1298]
There is very little information that explains how to use the programmatic interface.  All that is really mentioned is this [wiki page](https://github.com/visionmedia/mocha/wiki/Using-mocha-programmatically) that provides an example.  It would be nice to see explicitly what is available like [this](http://stackoverflow.com/questions/18660916/how-can-i-subscribe-to-mocha-suite-events) (for example).

**Comment by boneskull** [comment]
continue in mochajs/mochajs.github.io#6
