### ISSUE TITLE
Can I wrap tests inside a callback? (i.e. an around hook)

### ISSUE THREAD

**Issue by d11wtq** [mochajs/mocha#1303]
For my tests that write to a database, I want to run each example inside a transaction. This cleanest way to do this is to use a callback-driven approach in Sequelize. But in order for that to work, I'd need an around hook in Mocha. Is it possible?

**Comment by wexoni** [comment]
I have series of the test inside on describe block. Some of the test might dynamically generate other tests as well. After all tests are run, I have an array of dynamic tests. How can I execute them at the end? I tried using **after**, but mocha is not generating tests inside it. Any idea?
