### ISSUE TITLE
afterFailure hook

### ISSUE THREAD

**Issue by kelveden** [mochajs/mocha#1318]
It would be useful to have a hook that could be leveraged to (say) dump out diagnostic information for a failed test. So, something like:

```
describe("something", function () {
    afterFailure(function (testDescription) {
        // testDescription would just be the text from the "it".

        // Dump out diagnostics
    });

    it("does something", function () {
        // test stuff
    });
});
```

To give some context: the specific use case I'm thinking of is during a mocha-driven casper test suite - the `afterFailure` function could dump a screenshot (under a filename derived from the testDescription) from casper so that there is some context to the test failure.

**Comment by wernight** [comment]
+1 for screenshot and/or current page's source code (Zombie.js doesn't support screenshots). Also useful to be able to retrieve a website error log during system tests and include them in the outputs.

**Comment by boneskull** [comment]
*now* I am familiar with the reporter architecture, and I recommend implementing a custom reporter.
