### ISSUE TITLE
Share a standard Reporter interface?

### ISSUE THREAD

**Issue by JamesMGreene** [mochajs/mocha#1326]
We on the [QUnit](http://qunitjs.com/) team have been [discussing](https://github.com/jquery/qunit/issues/531) the possibility of working with other JS test frameworks (e.g. Mocha, Jasmine, Intern, etc.) to agree upon a standard Reporter interface so that we could hopefully share Reporter plugins between testing frameworks.

This would most likely come in the form of an EventEmitter interface with an agreed upon minimum viable set of standardly-named events and associated standard set of data/details provided to each.

Would you guys be interested in discussing this further with us?

Cross-reference issues:
- https://github.com/jquery/qunit/issues/531  (original discussion)
- https://github.com/pivotal/jasmine/issues/659
- https://github.com/theintern/intern/issues/257

cc: @jzaefferer @Krinkle @leobalter

**Comment by Dinuka2013513** [comment]
Hi, 

I would like contributing to https://github.com/js-reporters/js-reporters in anyway I can. Can anyone help me, from where I can start? 
Since I'm more familiar with Jasmin and mocha also, I thought of contributing to this.

I have already built the repository and fairly gone through the code base.

**Comment by jzaefferer** [comment]
@Dinuka2013513 there's several open issues that you could help with: https://github.com/js-reporters/js-reporters/issues

You could also help finish the mocha adapter: https://github.com/js-reporters/js-reporters/pull/28
