### ISSUE TITLE
Running mocha tests from inside node?

### ISSUE THREAD

**Issue by Qard** [mochajs/mocha#136]
I've got a whole tree of test files to run and want to be able select which ones to run using some console commands. I tried using a sort of bootstrap file that mocha would load and it would load the other files depending one what console commands I pass through mocha, but apparently commander just complains when you use a command that hasn't been defined.

What I'd really like is to be able to just require mocha in my code and run tests from there. At the moment I'm just using child_process.spawn and piping it's output to the console, which is kind of hacky and doesn't have the pretty colors. :(

**Comment by evan-king** [comment]
This old thread is the top Google result, instead of the real answer:

https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically

**Comment by mikemaccana** [comment]
+1 @evan-king you are a gentleman and a scholar.
