### ISSUE TITLE
parallel test suites

### ISSUE THREAD

**Issue by jonathanong** [mochajs/mocha#1373]
i have some tests i want to run in parallel, basically all the permutations of a certain function that are all completely independent from each other. it seems all the "parallel" issues and PRs are now closed. anyone interested in doing this now?

**Comment by robpolak** [comment]
Why was this ticket closed?  Is this something that is going to be rolled into a future PR?

**Comment by justspamjustin** [comment]
@travisjeffery I'm also interested to hear the reason why this was closed.  Running tests in parallel would be extremely helpful for me.

**Comment by travisjeffery** [comment]
same reasons given last times

https://github.com/mochajs/mocha/pull/849#issuecomment-18255189
https://github.com/mochajs/mocha/issues/1011#issuecomment-26660002
https://github.com/mochajs/mocha/issues/1011#issuecomment-27838420

**Comment by puzrin** [comment]
@theghostbel whyle automating everything in paralel is really bad, i'd suggest to discuss more explicit case like:

```js
describe.parallel('run in parallel this section', function () {
  ...
});
```

This can be very useful sometime. For example, when one need to ping hundreds of remote services.

Is such idea acceptable?

**Comment by boneskull** [comment]
Likely not. I don't see parallel execution in the future of Mocha's core. 

You could create a wrapper leveraging `child_process` or even `cluster` with `async` which launched several `mocha` processes.  If you have some sort of directory or naming convention, I don't see this being incredibly difficult to pull off. There are also a few modules which purport to do this--search npm

**Comment by puzrin** [comment]
@boneskull i understand. Just wished to suggest one more cool (probably) built-in feature, like `.skip()`, to simplify life.

No problem, that's not critical for me.

**Comment by danielstjules** [comment]
I needed parallel execution, but only for a subset of suites. Released a small module to help with this: https://github.com/danielstjules/mocha.parallel I'd maybe only use it for specs that would really benefit from parallel execution, as it can make debugging errors more difficult.

``` javascript
var parallel = require('../index.js');
var Promise  = require('bluebird');

parallel('delays', function() {
  it('test1', function(done) {
    setTimeout(done, 500);
  });

  it('test2', function(done) {
    setTimeout(done, 500);
  });

  it('test3', function() {
    return Promise.delay(500);
  });
});
```

```
  ✓ test1 (506ms)
  ✓ test2
  ✓ test3

  3 passing (516ms)
```

**Comment by puzrin** [comment]
@danielstjules at first glance, that looks exactly as i wished. Thanks a lot!

**Comment by danielstjules** [comment]
It needs a lot of work to become a full solution, but I should be able to invest some time into it this week. :)

**Comment by danielstjules** [comment]
@puzrin I've added support for hooks, and I should be able to get nested suites working as well. However, without the use of domains, error handling with this type of execution may be a bit difficult. It might be ok as a lightweight solution though.

**Comment by puzrin** [comment]
@danielstjules anyway, sometime that's better than nothing :)
