### ISSUE TITLE
silent option (reporter)

### ISSUE THREAD

**Issue by orlin** [mochajs/mocha#138]
It would be nice to have a `--quiet` option or `--reporter silent` or something to indicate no output is wanted unless there are errors.  I guess it must be a reporter modifier and not a reporter itself -- we still want the errors in a certain reporter format...  Anyway, it's not unusual for commands to have some such option.  Often, passing tests can just `--shut-up` :)  `--shush`?

**Comment by IanVS** [comment]
@tj I have the same question as @cybertk, I am running mocha [programmatically](https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically), and want to capture the stdio without printing to screen.  Is there a way to do this?

**Comment by danielstjules** [comment]
@cybertk @IanVS We don't currently inject the function or stream to be used for output by reporters. As a result, they all currently use process.stdout.write or console.log. You can get around this by overwriting process.stdout.write prior to running mocha. Since console.log calls it, that'll handle both cases, but only if no other code is trying to write to stdout at the same time. Example:

```javascript
var output, originalWrite;
output = [];
originalWrite = process.stdout.write;

process.stdout.write = function(str) {
  output.push(str);
};

mocha.run(function(failures) {
  // Restore original stdout.write
  proess.stdout.write = originalWrite;

  // ...
});
```

**Comment by IanVS** [comment]
@tj awesome, thanks,  I think that's just what I needed. I want to run a mocha test inside a mocha test, and so far this is the best way I've come up with to do that.  (I'm trying to test a module I wrote for running ESLint as a mocha test.)

**Comment by Cactusbone** [comment]
looks like this works : 
```
 var mocha = new Mocha({
        reporter: function () {
            //avoid logs
        },
    });
```

**Comment by jonstuebe** [comment]
@Cactusbone had the same issue and that worked for me. thanks

**Comment by abdulmoizeng** [comment]
I think any option that can be given from cli is better like `--quiet` flag

**Comment by theKashey** [comment]
When you are using mocha with nyc - you can't control only mocha output. We need `--quiet` flag.

**Comment by ToJen** [comment]
How would you make this support ES6? I have a cli that checks the current directory for mocha test files and run them. If the test file is in a newer JS version, how do I add support programmatically for those files?

**Comment by phil294** [comment]
redirecting to `/dev/null is not enough`. This leads to error output like

```
Error Response text: 
error Command failed with exit code 1.  
```

When I would expect the entire error stack trace to be shown, as in

```
  1 test failing

  1) Client Router
       afterEach Client.clear() works:
     AssertionError: expected [] not to be empty
      at Context.it (dist/routers/client-router.test.js:44:48)
      at processTicksAndRejections (internal/process/task_queues.js:86:5)
```
(made with Chai)
