### ISSUE TITLE
Front Page Makes No Mention of non-Node Mocha Use

### ISSUE THREAD

**Issue by machineghost** [mochajs/mocha#1387]
Mocha is a great test framework for Node projects, but it's also a great test framework of web projects.  However, the front page of the Mocha site makes no mention whatsoever of the web-based usage, which is somewhat confusing for non-Node users:

    Installation

    Install with npm:

    $ npm install -g mocha

If you just took a few lines to say something to the effect of "download mocha.js and mocha.css from the GitHub page *here*, then include both files on an HTML page before including your test files" I think it would be really helpful to non-Node users.

**Comment by boneskull** [comment]
continue in mochajs/mocha.github.io#5
