### ISSUE TITLE
Exiting successfully without running tests in node 0.8

### ISSUE THREAD

**Issue by Qard** [mochajs/mocha#1389]
For some bizarre reason mocha seems to exit successfully without running any of my tests in node 0.8.

I'm seeing this behaviour on the "cassandra" branch of the traceview module here: https://github.com/appneta/node-traceview/tree/cassandra. Oddly, master seems to work fine.

It might be helpful to look at the changes for the pull request of that branch here: https://github.com/appneta/node-traceview/pull/19/files.

**Comment by jbnicolai** [comment]
Unable to reproduce myself. Closing as this issue has been inactive for most of the year.

Feel free to comment if you feel this is still an issue, and we'll consider re-opening.
