### ISSUE TITLE
Watch what the tests require?

### ISSUE THREAD

**Issue by orlin** [mochajs/mocha#139]
A common mantra for tdd / bdd is: "write some tests that fail, make them pass", aka test-first.  The current implementation of `--watch` just sits idle in this case.  It's often hard to get the tests wrong, what's being tested is more in need of watching than the code that's testing it.  I think node reloaders have already solved catching this.  I haven't checked how, but if I had to guess: it's by checking what's `require`d...  For simplicity sake (and to avoid circular requires) just one level deep is all that's needed in most test cases.  If what's tested changes, the tests run again.

**Comment by amfarrell** [comment]
One way to solve this problem is to use the `watch-run` package.

`npm install --save-dev watch-run`
Then, add the following line to your package.json:
```
    "test:watch": "watch-run -p 'glob/for/js/**/*.js' npm run test",
```
And you can do `npm run watch:test`. It doesn't seem to preserve the coloring of the output though.

**Comment by revolunet** [comment]
Thanks @amfarrell this works great.

here's an example with `--colors` and es6

```json
"test"      : "mocha --colors --compilers js:babel/register ./tests/index.js",
"test:watch": "watch-run -i -p 'src/**/*,tests/**/*' npm run test"
```

**Comment by FuzzySockets** [comment]
@amfarrell Thanks for that solution!

**Comment by AshCoolman** [comment]
`<HailMary>`
Does anyone have a solution for passing params to mocha, via `watch-run ...` via `npm test ...`?

e.g. previously i could do `npm run test-watch -- --grep "MyTest1"`

Thanks

`</HailMary>`
