### ISSUE TITLE
Pass arguments to compilers

### ISSUE THREAD

**Issue by amsul** [mochajs/mocha#1408]
My source code is written using the [6to5](https://github.com/sebmck/6to5) compiler on Node Harmony. And to test with mocha, I need to pass the argument `--blacklist=generators` to the 6to5 compiler, however it doesn't seem like there's any straightforward way to do this through the mocha CLI.

This definitely doesn't work:

``` bash
mocha --compilers 6to5:6to5/register --blacklist=generators
```

Any suggestions here?

Thanks.

**Comment by andrastothtw** [comment]
Compilers got deprecated. (Currently I'm figuring out how to achieve passing a different config file to `ts-node` that's how I found this question)...
https://github.com/mochajs/mocha/wiki/compilers-deprecation
