### ISSUE TITLE
Error in "done() called multiple times" assumptions

### ISSUE THREAD

**Issue by Qard** [mochajs/mocha#1417]
This code here will hide the true error of certain failed async tests:

https://github.com/mochajs/mocha/blob/master/lib/runnable.js#L216-L230

To reproduce, try this:
```
it('should work', function (done) {
  setImmediate(done)
  throw new Error('hidden')
})
```

You will never see the error with the "hidden" message. It will just tell you done was called twice, which is terribly misleading, as the user code only called it once.

**Comment by LeonFedotov** [comment]
:+1:

**Comment by victorbadila** [comment]
+1 got the same error in a very similar case. tested this particular case and it happened just as described, I can confirm the behaviour.

**Comment by davija** [comment]
I am seeing the same behavior.  Has this been researched yet?  This is almost a year old now.

**Comment by kenr** [comment]
I'm also experiencing the same problem. Lost about an hour of work figuring out this was a bug in mocha and not my tests.
