### ISSUE TITLE
Sharing context between tests

### ISSUE THREAD

**Issue by marcelerz** [mochajs/mocha#1441]
I was working on some tests and noticed a strange behavior where a test was modifying the context of another test. When I looked at the code, I saw that this is intentional; there are even tests that check for this "feature".

From the [`context.js`](https://github.com/mochajs/mocha/blob/master/test/acceptance/context.js#L48) in `test/acceptance`:

``` javascript
    it('should not have value set within a sibling describe', function(){
      'This should be hidden'.should.not.eql(this.hiddenFromSibling);
      this.visibleFromTestSibling = 'Visible from test sibling';
    })

    it('should allow test siblings to modify shared context', function(){
      'Visible from test sibling'.should.eql(this.visibleFromTestSibling);
    })
```

I think I understand why this is implemented that way. With this, a test can share values it created with other tests without the sibling needing to re-create it or even needing code for that.
However, I believe that this is a really bad idea. This feature fosters bad testing practices since tests should be independent and should not have dependencies to other tests. If it is about code duplication, then just create a new describe context with a beforeEach, and that should be it. If the creation of the value that is shared is really soo costly that it needs to be shared, then it shouldn't be in a unit-test to begin with. And if someone REALLY wants to share values between tests, then a variable in the parent scope could be used:

``` javascript
describe('Whatever', function () {
    var sharedValue;

    it('should do something', function () {
        ...
        sharedValue = 'This value is shared';
    });
    it('should do something else', function () {
        fnCall(sharedValue);
        ...
    });
});
```

What I propose is to have a new context for each test that uses the parentContext for the prototype, just as `describe`s use of the parent context. This will make the tests really independent.

In `suite.js` in `lib`:

``` javascript
  ...
  test.slow(this.slow());

  var context = function() {};
  context.prototype = this.ctx;
  test.ctx = new context();

  this.tests.push(test);
  ...
```

That's exactly how [describe](https://github.com/mochajs/mocha/blob/master/lib/suite.js#L50) does it.

[Currently](https://github.com/mochajs/mocha/blob/master/lib/suite.js#L294), this is:

``` javascript
  ...
  test.slow(this.slow());
  test.ctx = this.ctx;
  this.tests.push(test);
  ...
```

Is there something I misunderstood? May be there is a legitimate reason for this, but I don't get it right now.
Any thoughts?

**Comment by Haisum92** [comment]
I did something like below 
```
describe('Authentication', () => {
    
    
    before(async () => {
        let adminO = await admin.newAdmin();
        this.username = adminO.login; 
        this.password = adminO.password;
    });

    it('Verifying User.', (done) => {
        chai.request(server)
        .post("/authenticate")
        .set("Content-Type", "application/x-www-form-urlencoded")
        .send({username: this.username,password:this.password})
        .end((err, res) => {
            this.token = res.body;
            res.should.have.status(200);
            res.body.should.be.a("string");
            done();
        });
    });


    it('List of Admin Books.', (done) => {
        chai.request(server)
        .get("/books")
        .set("Content-Type", "application/json")
        .set("access_token", this.token)
        .end((err, res) => {
            console.log(res.body);
            res.should.have.status(200);
            res.should.be.an("object");
            res.should.have.property('body').should.be.an('object')
            // res.body.should.be.an('object')
            res.body.should.have.property('results')
            res.body.results.should.be.an('array').to.not.equal(0)
            // res.body.results.should.to.not.equal(0)
            res.body.should.have.property('total').not.equal(0)
            // res.body.total.should.not.equal(0)
            
            done();
        });
    });

});

```
