### ISSUE TITLE
Want overridable default glob pattern in mocha.opts

### ISSUE THREAD

**Issue by KylePDavis** [mochajs/mocha#1444]
I'd like a mechanism for setting an overridable default test file glob pattern so that I can configure `mocha.opts` to run all test files but also `mocha foo_test.js` could be used to run a single test file. 

The `mocha.opts` file allows for setting any valid command line arguments so it's nice and simple. For options that can be set more than once these act like default settings since they can be given again on the command line. Unfortunately not everything works this way. In my case the fact that there's no overridable glob pattern is a bit of an issue.

Here are a few ways that we might solve this that I'll toss out for discussion:
1. also look for a `require`-able config file by default (e.g., `test/mocha.opts.js`)
   - it would export an `Array` of args but unlike the regular `mocha.opts` this one could conditionally change the returned options based on the current state of `process.env`, `process.argv`, etc.
2. support a `--default-pattern` option to set a glob pattern to be used only if no other pattern was given.

Once we've settled on a preferred method I'll be more than happy to submit a PR to make it happen.

I think option 1 is more flexible but option 2 is more straight-foward. Thoughts?

**Comment by rauschma** [comment]
Just in case (I agree with “if you can trivially get a shell script, make, grunt or gulp to do it for you, it's not an essential feature”): I have the same use case.

At the moment, I have two scripts in `package.json`:

```
"testall": "mocha --ui qunit --require ts-node/register 'exercises/**/*{_test,_exrc}.{js,ts,tsx}'",
"test": "mocha --ui qunit --require ts-node/register",
```

I’d prefer to have a single script. For example:

```
"test": "mocha --ui qunit --require ts-node/register --default 'exercises/**/*{_test,_exrc}.{js,ts,tsx}'",
```

**Comment by medikoo** [comment]
I approached same issue, and solution where two scripts should be configured, doesn't sound good.

It seems unnecessarily verbose, and error-prone (same set of options needs to be maintained in two places)
