### ISSUE TITLE
after hook is not called when before hook times out

### ISSUE THREAD

**Issue by mnylen** [mochajs/mocha#1456]
Simple test case:

    var assert = require('assert')

    describe('mocha after not being called', function() {
        before(function(done) {
            console.log("before callback")
           // never call done
        })

        it('should add two numbers together', function() {
            assert.equal(2, 1+1)
        })

        after(function() {
            console.log("after callback")
        })
    })

Expected output: 'before callback\nafter callback'
Actual output: 'before callback'

Shouldn't after hook be always called? In my case, before hook is leaving files behind which I'm trying to clean up in the after hook, but if the before hook times out, after callback is not called at all.

**Comment by dasilvacontin** [comment]
This works in the current version.
