### ISSUE TITLE
Feature proposal: global setup and teardown

### ISSUE THREAD

**Issue by freeformsystems** [mochajs/mocha#1460]
When testing a server code base and wishing to generate code coverage via an external tool such as `istanbul` it does not make sense to start and stop the server for every test suite using `before` and `after` - especially if there are a lot of test suites and the server performs various operations when starting.

I propose adding the ability to configure a `setup` function to be invoked asynchronously before any tests are executed and a `teardown` function after all test suites have been executed.

Whilst I have read CONTRIBUTING.md and imagine this feature is unlikely to be accepted as it may not be a common use case, I have implemented, tested and integrated this functionality with a real project, full details are in the (squashed) commit:

https://github.com/socialally/mocha/commit/fd744e480fa4acbc0846cdaa41f866034bdd38ab

If the consensus is that this feature would be useful to other people and a PR would be accepted then I will issue a PR with the linked commit.

**Comment by danielstjules** [comment]
Isn't this functionality already possible using the global suite's hooks?

``` javascript
$ cat test.js
before(function() {
  console.log('global setup');
});

after(function() {
  console.log('global teardown');
});

$ cat test2.js
describe('suite', function() {
  it('test', function() {});
});

dstjules:~/git/mocha (master=)
$ mocha test2.js test.js

global setup

  ․global teardown


  1 passing (10ms)
```

**Comment by freeformsystems** [comment]
@danielstjules,

That looks good if it works, I'll check it out. Interestingly your example output does not show the test suite being executed (`test.js`)? Does mocha accept multiple [file] arguments i think it is a single glob pattern?

**Comment by danielstjules** [comment]
Mocha handles both glob patterns and explicitly listing file arguments.

And the output above is showing the test suite being executed, but I used the dot reporter. Note the dot before the second "global". Here's with the spec reporter:

```
$ mocha --reporter spec test.js setup.js


global setup
  suite
    ✓ test

global teardown

  1 passing (10ms)
```

**Comment by boneskull** [comment]
@danielstjules I think I saw that in there the other night when I was working on the jekyll stuff.

**Comment by danielstjules** [comment]
![screen shot 2015-04-18 at 10 51 25 am](https://cloud.githubusercontent.com/assets/817212/7216573/e6209d5e-e5b8-11e4-874f-24aeaa55221c.png)

You're right - just found it under the asynchronous code section. It might be worth emphasizing in another section, or in the wiki somewhere.

**Comment by danielstjules** [comment]
Closing for now, as the root `before()` and `after()` hooks seem to satisfy the requirements. :)

**Comment by danawoodman** [comment]
If I'm not mistaken, having a global `before`/`after` will get called for each `describe` block, is that correct? If so, how could one run something once before and once after the test suite runs? Eg connect to a db when the suite starts (and block until connected) and disconnect after done

**Comment by danielstjules** [comment]
> If I'm not mistaken, having a global before/after will get called for each describe block, is that correct?

Nope, just at the start/end of the test suite :)

``` javascript
before(function() {
  console.log('before');
});

after(function() {
  console.log('after');
});

describe('suite1', function() {
  it('test', function() {});
});

describe('suite2', function() {
  it('test', function() {});
});
```

```
before
  suite1
    ✓ test

  suite2
    ✓ test

after

  2 passing (9ms)
```

**Comment by colinjoy** [comment]
@danielstjules sorry for necromancing on this issue: 
is this behaviour specific to the bdd interface? using tdd (loaded via karma-mocha) I observe that setup/teardown at the root level are invoked for every suite and every test. Quite the opposite of what is desired here.

**Comment by JamesMcMahon** [comment]
> Isn't this functionality already possible using the global suite's hooks?
> 
> ```js
> $ cat setup.js
> before(function() {
>   console.log('global setup');
> });
> 
> after(function() {
>   console.log('global teardown');
> });
> 
> $ cat test.js
> describe('suite', function() {
>   it('test', function() {});
> });
> 
> dstjules:~/git/mocha (master=)
> $ mocha test.js setup.js
> 
> global setup
> 
>   ․global teardown
> 
> 
>   1 passing (10ms)
> ```

That works pretty well in most scenarios, anyone have any idea how to run those `before` and `after` hooks in watch mode?
