### ISSUE TITLE
_name variable conflict with commander.js

### ISSUE THREAD

**Issue by DinisCruz** [mochajs/mocha#1462]
Please see this issue [_name variable conflict with mocha](https://github.com/tj/commander.js/issues/297) on the commander.js Issues list, for a conflict caused by the overwrite of the **_name** value

**Comment by boneskull** [comment]
I'm not sure what's going on here (still), but it's definitely related to the `mocha`/`_mocha` thing.  we should look into it if we end up consolidating the files.  I'm still behind consolidating them, because if you need node/iojs flags, you have the option of using your `node`/`iojs` executable.

**Comment by jbnicolai** [comment]
@boneskull I agree wrt consolidating them

**Comment by boneskull** [comment]
this looks to be a non-mocha problem per the linked issue
