### ISSUE TITLE
tests fail in latest version of mozilla firefox (ver 34.0.5) only

### ISSUE THREAD

**Issue by dshrestha** [mochajs/mocha#1463]
We have been running unit tests for our ember application using testem(2.0.1) and everything was running fine until we upgraded our firefox version to 34.0.5. We get this error on random tests ::

process.on/global.onerror@http://localhost:7359/7167/tests/lib/scripts/mocha.js:5964:20

which points to this function 

    /**
     * Implements uncaughtException listener.
     */

    process.on = function(e, fn){
        if ('uncaughtException' == e) {
            global.onerror = function(err, url, line){
                fn(new Error(err + ' (' + url + ':' + line + ')'));
                return true;
            };
            uncaughtExceptionHandlers.push(fn);
        }
    };

At this point I am not sure if there is fault in our project code but its just weird that things would run in chrome/FF ver 33 but not in ver 34. Also to note that when I manually ran the tests in the latest FF, all the tests ran successfully without any issues!
I am really sorry if this is not a mocha issue but rather something to do with testem. I was not sure so I just raised a bug here too.(https://github.com/airportyh/testem/issues/442)

**Comment by dshrestha** [comment]
Finally figured out the issue finally :). We were using grunt-contrib-testem to run our ember integration tests and even when I put in the debugger in the script it was not getting exercised. So instead I configured and ran the testem manually with debugger placed in the error points. It turned out there were events attached to multiple DOM elements of a component which were not destroyed when the component was destroyed and these events were getting triggered when running the test causing the errors(was calling method on a destroyed object). It was bad programming on our side but well something on GC collection of the firefox must have changed too since we were not getting this issue in older version. Thanks.

**Comment by dasilvacontin** [comment]
Thanks for coming back and letting us know the actual reason. :)
