### ISSUE TITLE
xunit reporter should fill classname with relative path to test file

### ISSUE THREAD

**Issue by Chcap** [mochajs/mocha#1466]
Hi,

currently, the xunit reporter generate test case with test full title in classname attribute.
Example:

``` xml
<testcase classname="Foo #hello" name="should return hello $name" time="0"/>
```

It would be great, especially for [Sonar](sonarqube.org) compatibility, to have a path to test file instead.

``` xml
<testcase classname="toto/foo-spec" name="Foo #hello should return hello $name" time="0"/>
```

The [mocha-sonar-reporter](https://github.com/pghalliday/mocha-sonar-reporter) is a clone of the xunit reporter already solving this issue.

Best regards

**Comment by ScottFreeCode** [comment]
For the record (with apologies for digging this up -- although it was referenced in a recent issue), if this is still the case, I think we should add that info somehow, but we should do it without losing info (i.e. which portion of the name belongs to the test per se as opposed to the combination of suite[s] and test), and if we could do it without breaking backwards compatibility with Mocha that'd be best.

**Comment by JoshuaKGoldberg** [comment]
There's been very little discussion on the xunit reporter in the last few years. Closing this out as it doesn't look like many users need this functionality still. Someone please yell at me if I'm wrong!

If you do want this, it'd also be helpful to post a comparison list of other xunit reporters in equivalent tools. We should see what they generally do and consider mirroring that behavior.
