### ISSUE TITLE
False positives when mocha allowes async execution between "before" and test

### ISSUE THREAD

**Issue by TheLudd** [mochajs/mocha#1468]
Below are 3 examples of tests that all pass but as far as I can see, they should not. The tests all go through a ```before``` or ```beforeEach``` function that performs changes necessary for the tests to pass, but they all do it on the next tick and without telling mocha to wait. 

It appears that mocha allows at least one tick between the ```before``` functions and the tests. Is this correct? I would have expected it to run synchronously. 

```
var chai = require('chai');
var Promise = require('bluebird');
chai.should()

describe('test', function() {
  var changedInBefore = 0;
  var changedInBeforeEach = 0;
  var nextTick = 0;

  before(function() {
    //Not returning promise, expecting the tests to run before setting changedInBefore to 1
    Promise.resolve().then(function() {
      changedInBefore = 1
    });
  });

  beforeEach(function() {
    //Not returning promise, expecting the tests to run before setting changedInBeforeEach to 1
    Promise.resolve().then(function() {
      changedInBeforeEach = 1
    });
  });

  beforeEach(function(done) {
    process.nextTick(function() {
      nextTick = 1;
    });
    done(); //Calling done before nextTick is set to 1, expecting tests to run before this happens
  });

  it('before with promise', function() {
    changedInBefore.should.equal(1);
  });

  it('beforeEach with promise', function() {
    changedInBeforeEach.should.equal(1);
  });

  it('beforeEach with next tick', function() {
    nextTick.should.equal(1);
  });

}
```

**Comment by jbnicolai** [comment]
You seem to misunderstand how `process.nextTick` and `Promise.resolve()` work. Both will call their callback after the function (before/beforeEach) they are in, but before the next `it` block.

**Comment by TheLudd** [comment]
@jbnicolai No, there is no misunderstanding of `process.nextTick` and `Promise.resolve`. The question was about mocha. The clarification I still lack is about this:

> It appears that mocha allows at least one tick between the before functions and the tests. Is this correct? I would have expected it to run synchronously.
