### ISSUE TITLE
AfterAll hook doesn't run when 'bail' is set

### ISSUE THREAD

**Issue by myndzi** [mochajs/mocha#1489]
This appears intentional, but has some unfortunate unintentional consequences, the most obvious of which I'm currently encountering.

I need to run some tests against an instantiated application; when the tests are done, I want to shut down the application gracefully. Before and After hooks make sense for this, right? Wrong! The application will never get cleaned up if there is an error because the after hook doesn't run!

I'm not sure why hooks are treated the same as test suites; the intent of the 'bail' option is just to stop running tests, but cleanup should still happen; that is, 'after' hooks that apply to tests that did run should be executed.

**Comment by dasilvacontin** [comment]
Hi @myndzi, what version of mocha are you running? I supposedly fixed that bug recently.

**Comment by dasilvacontin** [comment]
The bugfix was released on version 2.1.0.

**Comment by myndzi** [comment]
Figures, haha. I had to avoid version 2.1.0 because of the other change which destroyed color support by binding mocha's reporters tightly to the native tty module. I haven't had time to work out a workaround yet, I only noted that no matter what I did (setting the use color property directly, environment variable, etc.) I couldn't get color out a stream.

**Comment by myndzi** [comment]
I'll take your word that this is fixed and close this; I'll open another one for the color thing if/when I've managed to look into it enough to say something useful
