### ISSUE TITLE
Execute suites (bdd) when needed

### ISSUE THREAD

**Issue by crishushu** [mochajs/mocha#1491]
Hi, is there a way to execute suites ('describe') on demand. I am running a server using node and all test suites are supposed to be generated when the client connects, so they are not visible by the mocha executable when starting the program.

Thanks for some help!

**Comment by jasonkarns** [comment]
I would love some insight into this as well. I'm trying to merge multiple suites such that some use bdd, while others use mocha-given or mocha-gwt. I'm assuming that however one can execute the suites programmatically would also enable per-suite interfaces.

**Comment by crishushu** [comment]
I wrote this mocha interface which was the missing link I was looking for:

https://gist.github.com/crishushu/fda1efac7badf9b27a3b <https://gist.github.com/crishushu/fda1efac7badf9b27a3b>

**Comment by boneskull** [comment]
see `--delay` 

[example](https://github.com/mochajs/mocha/blob/master/test/delay/delay.js)
