### ISSUE TITLE
HTML reporter retains old 'grep=' querystrings when changing suites

### ISSUE THREAD

**Issue by callmevlad** [mochajs/mocha#1494]
Currently, if you use the `http://localhost/tests.html?grep=MySuite` format for limiting Mocha tests in the browser, all the suite/test links in the report get additional `grep=` params. Clicking on them retains older (ignored) values in the URL:

`http://localhost/tests.html?grep=MySuite&grep=MySuite%20%23someMethod`

Switching back to the higher suite will tack on yet another param:

`http://localhost/tests.html?grep=MySuite&grep=MySuite%20%23someMethod&grep=MySuite`

Ideally, switching to a new `grep` setting should clear the existing one in the URL. I'll submit a PR which implements this desired behavior.

**Comment by kristoferjoseph** [comment]
:+1:

**Comment by travisjeffery** [comment]
Thanks
