### ISSUE TITLE
io.js support

### ISSUE THREAD

**Issue by mathiasbynens** [mochajs/mocha#1498]
What is the recommended way of running mocha tests in io.js given an `iojs` binary (i.e. assuming `node` isn’t symlinked to `iojs`)? `alias node=iojs; mocha`? Or is there a command-line flag that instructs `mocha` to use the `node` binary at a given location?

(Asking because it would be useful to run continuous integration tests in both Node and io.js.)

**Comment by edi9999** [comment]
Same question for me. I'm pretty sure they is no command line flag to execute with iojs instead. 

The [shebang syntax](https://en.wikipedia.org/wiki/Shebang_%28Unix%29) used here: https://github.com/mochajs/mocha/blob/master/bin/mocha#L1:

`#!/usr/bin/env node`

makes it not possible to run with iojs. Unless you alias iojs to node.

There must be some kind of solution, but I'm not so sure what.

**Comment by mathiasbynens** [comment]
> […] makes it not possible to run with iojs. Unless you alias iojs to node.

On IRC, @domenic made the point that not aliasing `iojs` to `node` could be considered a “non-standard” `iojs` setup. Therefore it might seem far-fetched to add a CLI flag to `mocha` that accepts a binary path _just for this specific use case_.

**Comment by edi9999** [comment]
I agree with with @domenic said, its true that it would be quite a hassle for all cli based programs that depend on node to add such an option.

**Comment by boneskull** [comment]
You could try

```shell
alias mocha="iojs /node_modules/mocha/bin/_mocha"
```

Dunno if that will work.  Otherwise you'll probably want a symlink.

Given that `mocha` executes `node` itself (which is strange to me; if you want `node` flags, why not just run `node /path/to/mocha`?), if a non-symlinked setup becomes more prevalent, maybe it's a good idea to ditch support for `node` flags.

**Comment by herkyl** [comment]
This issue was closed but is there a clean fix?

**Comment by jereme-leandev** [comment]
I hope there would be a command-line flag. I might as well be opening this as a new issue
