### ISSUE TITLE
Feature: signal from a test code to abort the current running suite

### ISSUE THREAD

**Issue by osher** [mochajs/mocha#1500]
Hi.

I need some help and i did not know where to turn to. The question is: 
Do we have this functionality in mocha, or is this a new feature?

More details: 
I'm trying to use mocha to code some DB tests. Assume the following structure

```
migrate db to current version:
    setup:  
        - connect as admin 
        - create test db as target db
        - close admin connection
        - run 'create-db' of previous version
    the migration flow:
        setup: connect to target db
        should pass with no errors:
            setup: begin transaction
            - alter tables & SPs
            - add built-in records to root tables
            teardown: decide if to commit or rollback AND ABORT SUITE
        run of sanity test sqls should pass with no errors:
            setup: begin transaction
            - insert demi data
            - execute some ETL sp
            teardown: decide if to pass or fail, but ALWAYS rollback
        teardown: db close connection
    teardown:
        - connect as admin 
        - connect to main db
        - close connection
```

Now, this flow makes great sense.
In fact, all the `the migration flow` section is a code that if we could abort it on first error, and take decisions on the teardown - it would even be safe enough to run as part of rollout to production db itself.

Now since a DB rollout happens on some DevOps machine that would talk to the db, there's no problem running mocha there, and have the communication with the db a side-effect of running the suite, and enjoying the explicitness of the spec reporter, the well-programmed waterfall, and all the rest :)

But - for that, I should be able to *abort* a suite with all it's yet-to-be-exectuted steps, *without skipping hooks* like teardown/afterall hooks.

I found the `Runner.prototype.abort` API and it looks almost like what I need - except for the fact it aborts the entire execution, and not only the current suite - but if it works I might be able to live with that.
But I did not find a way to access the runner from code of user-function for test or for a hook...

Do we have this functionality in mocha, or is this a new feature?

P.S
The only place I saw `runner.abort()` used is the `process.on('SIGINT', function() { runner.abort(); })` on the CLI file in bin. 
Is this how it's intended to be used? sounds hacky to me...
I need some confirmation that I'm not abusing this whole thing before I'll feel good with harsh statements like `process.emit('SIGINT')` ...

Any word would be a help :)

Thanks for bearing with me

**Comment by jonathandelgado** [comment]
You can just replace the logic that would call the `runner.abort()` to run a teardown function and then call the abort, or just end the process.

You shouldn't have your setup/teardown functions as tests, rather a utility that is called prior/post running your tests.

**Comment by osher** [comment]
@jonathandelgado - 
you're right about setup / teardown - that's where im going, I suppose I wrote it there for verbosity.

terminating the process is not considerable - we will lose the teardown...

about replacing the logic that would call runner.abort - that's the problem:
I can't find the access to runner from user-code - it looks like intentionally decoupled
maybe I don't understand what you say, but if I wanted to do that I would need to manipulate Runner.prototype.abort - which sounds to me worse than emitting SIGINT...

**Comment by jonathandelgado** [comment]
Wait for the teardown to finish, then run the SIGINT. There shouldn't be any issues.

**Comment by boneskull** [comment]
going to assume this has worked as per @jonathandelgado 's advice
