### ISSUE TITLE
Remind to call "done()" on test timeouts

### ISSUE THREAD

**Issue by Soviut** [mochajs/mocha#1503]
I understand the reason the `done()` callback is required, but I've tripped myself up multiple times forgetting to add it to the end of a test. In each case, I assumed it was an issue with my code, not the test itself.

It would be nice if the test timeout error message had some kind of reminder to make sure `done()` was somewhere in the test.

**Comment by DanielApt** [comment]
And this should also be stressed in the documentation as well!

**Comment by dasilvacontin** [comment]
I see. Would a reminder message in the error be good enough, or would you suggest scanning the code for the use of the callback?

**Comment by Soviut** [comment]
I think a reminder is easier to implement immediately. Digging through the stack to ensure a callback would be more foolproof, but would it catch every case?

**Comment by dasilvacontin** [comment]
Digging through the stack? But the problem is detecting if the code has any line that executes the callback, right?
On Feb 1, 2015 10:21 PM, Soviut <notifications@github.com> wrote:I think a reminder is easier to implement immediately. Digging through the stack to ensure a callback would be more foolproof, but would it catch every case?

**Comment by Soviut** [comment]
Yes, verifying that a callback exists somewhere in each test. To be honest, I was guessing about "checking the stack" since I didn't think it would be done via actual source.

**Comment by dasilvacontin** [comment]
I think there is no other way to discern between an actual timeout vs forgetting to execute the callback if you don't scan the code.

**Comment by dasilvacontin** [comment]
We can easily get the file and line number in which the test's function was declared.

**Comment by Soviut** [comment]
It might be even easier to just use `function.toString()` to get the function code for each test and scan it for the callback.

**Comment by dasilvacontin** [comment]
I feel so fool about missing that since it's one of the functions I checked today...

This will be a cool and useful addition, I'll add the labels. Let us know if anyone cares to prepare a PR!

**Comment by Soviut** [comment]
In the mean time, perhaps just updating the timeout messaged would be a good stopgap measure. A reminder like "Timeout 2000ms. Is the done() callback being called?" or "Ensure the done() callback is called in your test".

**Comment by dasilvacontin** [comment]
I will do so asap.

**Comment by Soviut** [comment]
I could do a PR.

**Comment by Soviut** [comment]
PR ready to go https://github.com/mochajs/mocha/pull/1523

**Comment by dasilvacontin** [comment]
Merged, lacking the actual check.

**Comment by Soviut** [comment]
Yeah, that PR satisfies this current issue. I'll create another issue about checking for the done() method within tests.
