### ISSUE TITLE
mocha.opts folder placement

### ISSUE THREAD

**Issue by ayuwono** [mochajs/mocha#1504]
Hi, I have a question on using mocha.opts

This is my folder structure:

node-client-api
            |__ test-complete
                            |__ some-test.js

All my tests are under "test-complete" folder and I run the test on my test in this way:
mocha node-client-api/test-complete/some-test.js

Where do I put my test/mocha.opts? Putting the test/ under node-client-api/test-complete is not working

**Comment by TheLudd** [comment]
You need to put it on the path `./test/mocha.opts` where `.` is the folder you are running mocha from.

**Comment by TheLudd** [comment]
I also noticed you can specify the path #1277

**Comment by dasilvacontin** [comment]
Thanks @TheLudd! I'll close this issue, as there shouldn't be any problem after that answer.
