### ISSUE TITLE
Configuring context for test execution from command line

### ISSUE THREAD

**Issue by nikita-leonov** [mochajs/mocha#1509]
I was looking a way to provide additional context for a tests during a run. Something  like following:
```
mocha --configure KEY=VALUE
```

Is it possible with Mocha? I think it is valuable option, as it is pretty often that scripts differ only by configuration, but not by logic and depends on a stage you want to execute them differently.

**Comment by jonathandelgado** [comment]
Yeah, just grab the process arguments like usual.

**Comment by nikita-leonov** [comment]
I did some homework before asking this question and saw this SO answer. I believe environment variables are serve different purpose in compare with command line arguments. Use of environment variables will be inappropriate scenario.

**Comment by jonathandelgado** [comment]
@nikita-leonov Take a look at the other two solutions, they do exactly what you ask.

**Comment by nikita-leonov** [comment]
It is actually interesting. I was looking into it but didn't find a way how and why it should work, as mocha command does not accept any extra options and returns an error. However if options provided after list of files it accepts any list of parameters. So I used nconf to extract variables. Thanks for direction.
