### ISSUE TITLE
request: `it.todo`

### ISSUE THREAD

**Issue by gregglind** [mochajs/mocha#1510]
### Use case:
- tests that can't be yet implemented, but should be. 
- 'remind' the author, be grepabble.

### benefit
- more literate programming.
- "todo" lives in the code.

### why not use  `it.skip`.
- like `it.skip` should 'orange' a bug tracking / code review board.
- `it.skip` should be reserved for "commenting" out tests (during an active session). 
- `it.todo` is more forceful / intentional.  

### Costs to implement
- more readme, docs work.
- yet another state, that all reporters must know about.  (only if `todo` is a new state, per proposal 2 following).

### possible implementations
1. alias `todo` to `it.skip`, which preserves the distinction in the code, even if 
2. new function `todo` that can be logged in reporters as distinct from pending.

**Comment by gregglind** [comment]
(maybe rehash of #1236, but with a simple proposed implementation)

**Comment by travisjeffery** [comment]
thanks for the issue. still not convinced this is a good idea.

**Comment by gregglind** [comment]
Fair enough :)  For future reference, here is an example shim that shows some of these ideas in action.

Thanks for making 'it' flexible and simple enough to modify in this way!

https://gist.github.com/gregglind/ff9ce0c2c3aeacc783b9

```javascript

// license: Public Domain

//it.todo = it.skip;
it.todo = function (title, callback) {
  return it.skip("TODO: " + title, callback)
}

describe("todo vs skip", function () {
  it.skip("skipped test", function () {
    // hard to test this without shims
  });
  it.todo("this test wants to be todo'd", function () {
    // hard to test this without shims
  })
});
```

**Comment by tarun** [comment]
:+1:

**Comment by boneskull** [comment]
```js
describe('something', function() {
  it('should be implemented at some point'); // this is a "pending" test
});
```
