### ISSUE TITLE
Browser mocha use nyan reporter error

### ISSUE THREAD

**Issue by chunpu** [mochajs/mocha#1513]
other reporters are quite ok, howerver I get a `undefined is not a function` error when using nyan reporter in browser mocha

I find that Nyan constructor is rewrited by Hook

```js
function F(){};
F.prototype = Base.prototype;
NyanCat.prototype = new F;
NyanCat.prototype.constructor = NyanCat;
```

so it will panic when init the rainbowcolors

```js
 var self = this
    , stats = this.stats
    , width = Base.window.width * .75 | 0
      // Panic here ! self is the F above, without generateColors
    , rainbowColors = this.rainbowColors = self.generateColors() 
```

cannot understand why browser mocha rewrite all reporters constructor, please help! Thanks!

**Comment by jbnicolai** [comment]
Mocha no longer rewrites these constructors, but uses `Lodash.create`. However, this has always been consistent between all reporters, and should not cause an issue specifically with the Nyan one. Tried to reproduce, but (no longer) seems to be an issue.
