### ISSUE TITLE
Run `after` and `afterEach` even after spec failure

### ISSUE THREAD

**Issue by gyandeeps** [mochajs/mocha#1516]
I think the `after` and `afterEach` should run even if the `spec` fails. Sometimes its needed to because we might be doing some clean up work inside `after` and `afterEach` functions.

Example would be:
Let say I am testing a module which copies a directory recursively into a different directory. Now after the test is over I want to delete the newly created a directory as a cleanup.

Its like in the `database` world, when you test you manipulate the data inside the tables but when your test finishes you always `rollback` the changes regardless of failure or success.

**Comment by dasilvacontin** [comment]
Doesn't that already work? Can you provide a reproducible failing test and your mocha version?

Envoyé de mon iPhone

**Comment by gyandeeps** [comment]
Not able to reproduce now. Will reopen the issue if see that happening again.
Sorry about that.

**Comment by dasilvacontin** [comment]
No problemo! The fix was added on one of mocha's latest versions, maybe you were still running an old release.
