### ISSUE TITLE
Very simple test calls done() multiple times. What to do?

### ISSUE THREAD

**Issue by DanielApt** [mochajs/mocha#1517]
I've created a very simple test, to demonstrate the following:

We want to test that the `click` event works on both `div` and `div > span`.

In this scenario the second test seems to invoke the first one, which leads to the error:
```
 1) Example should trigger on DIV:
     done() called multiple times
```

The source for the test can be found below:

```
describe('Example', function () {
    before(function () {
        $('body').append('<div><span></span></div>');
    });

    it('should trigger on DIV', function (done) {
        $('div').on('click', function (e) {
            e.stopPropagation();
            done();
        });

        $('div').click();
        this.timeout(50);
    });

    it('should trigger on DIV > SPAN', function (done) {
        $('span').on('click', function (e) {
            e.stopPropagation();
            done();
        });

        $('span').click();
        this.timeout(50);
    });

});
```

*Update Added `stopPropogation` as suggested by @toastynerd, but still no luck. Either way let's keep it in, as it illustrates that this isn't caused by event propogation.*
*Update 2: Moved `stopPropogation` above `done()`. Still no luck.*

**Comment by toastynerd** [comment]
Looks like, the click event is propagating up the dom, using stopPropagation might fix it: https://api.jquery.com/event.stoppropagation/

**Comment by DanielApt** [comment]
@toastynerd I've already done that, to no avail. I have the feeling something bigger/buggier is going on…

**Comment by dasilvacontin** [comment]
I'll try this asap. Were you able to reproduce, @toastynerd?

**Comment by toastynerd** [comment]
@dasilvacontin @DanielApt hmm, I can't reproduce this, how are you running these tests/can you post your test harness?

**Comment by DanielApt** [comment]
@toastynerd @dasilvacontin I've reproduced it here, in the most basic set up I could write:
http://jsfiddle.net/xLd4oyj9/

Notice how I've got 2 passes, yet 1 failure. That 1 failure is `done()` being called multiple times.

This error is more obvious in the console, as it logs the error. To run it in the console I'd use [`mocha-phantomjs`](https://github.com/metaskills/mocha-phantomjs)

**Comment by toastynerd** [comment]
Ah okay, I had that as well and didn't pay too much attention to it, if you place the `stopPropagation`s before the `done()` it should fix it.

**Comment by DanielApt** [comment]
@toastynerd I've done that here, but it still hasn't addressed it. http://jsfiddle.net/xLd4oyj9/1/

**Comment by dasilvacontin** [comment]
The problem is that there are two 'div' items.

$('div') gets all div objects (2 in this case). Therefore you are defining a listener for both divs, and then executing each of them.

**Comment by toastynerd** [comment]
Yup, I forgot that the way I actually fixed it was to add an id to the click div. Just as @dasilvacontin said you have 2 divs and your test is actually clicking on the mocha div.

**Comment by DanielApt** [comment]
@dasilvacontin Indeed! I've just made the selectors more specific, and it has addressed the issue!
Check it out in action http://jsfiddle.net/xLd4oyj9/2/

**Comment by dasilvacontin** [comment]
I'm glad it worked out. Back to work! :)
