### ISSUE TITLE
Errors in third party reporters get swallowed by Mocha

### ISSUE THREAD

**Issue by adamgruber** [mochajs/mocha#1521]
I've been working on building a reporter for Mocha but it can be difficult to debug errors in the reporter because Mocha eats them up. Would be great if Mocha could at least log the reporter error before throwing an invalid reporter error. Something like this? 

```js
Mocha.prototype.reporter = function(reporter, reporterOptions){
  if ('function' == typeof reporter) {
    this._reporter = reporter;
  } else {
    reporter = reporter || 'spec';
    var _reporter;
    try { _reporter = require('./reporters/' + reporter); } catch (err) {};
    if (!_reporter) try { _reporter = require(reporter); } catch (err) {
      console.warn(err);
    };
    if (!_reporter && reporter === 'teamcity')
      console.warn('The Teamcity reporter was moved to a package named ' +
        'mocha-teamcity-reporter ' +
        '(https://npmjs.org/package/mocha-teamcity-reporter).');
    if (!_reporter) throw new Error('invalid reporter "' + reporter + '"');
    this._reporter = _reporter;
  }
  this.options.reporterOptions = reporterOptions;
  return this;
};
```

**Comment by dasilvacontin** [comment]
I see. I'm not sure why we aren't currently logging the reporter load errors. 'invalid reporter' doesn't really say much. I guess the code's author didn't expect the reporter to blow up during the require.

**Comment by dasilvacontin** [comment]
It would be nice to differentiate between missing reporter and broken reporter, in the end.

**Comment by adamgruber** [comment]
I would think it wouldn't be too hard to make that distinction.

**Comment by dasilvacontin** [comment]
Not at all, just checking the value of `err` in catch. And as messages, I could see something like:
"nyan" reporter not found.
"unstable" reporter blew up, and show stack trace.

**Comment by danielstjules** [comment]
Fixed in https://github.com/mochajs/mocha/pull/1543 :) Thanks a lot @adamgruber!
