### ISSUE TITLE
Can we get a release?

### ISSUE THREAD

**Issue by bjornstar** [mochajs/mocha#1522]
I'm mostly looking forward to the fix to the grep querystring.

Pretty please?

**Comment by dasilvacontin** [comment]
Please, bump #1481 instead of creating a new issue.
There's also a patch at #1492 that you could help reviewing.
Thanks.

**Comment by bjornstar** [comment]
I was talking about #1494, but I can certainly chime in on open PRs and Issues.

**Comment by dasilvacontin** [comment]
Oh, I see! Sorry, I didn't get it at first.

I don't have ownership of `mocha` in npm. The release should be made by either @boneskull or @travisjeffery, unless they want to delegate the task to me. :)

**Comment by travisjeffery** [comment]
yeah will do soon, thanks
