### ISSUE TITLE
fix tests that need to be uncommented

### ISSUE THREAD

**Issue by dasilvacontin** [mochajs/mocha#1528]
Some tests ask to be uncommented to see actual behaviour, because they are designed to fail.

Instead of doing that, another instance of mocha should be run and then test on that instance if the before/after/tests are run/failed/etc. Kinda of what I've done at `test/mocha.js`.

**Comment by dasilvacontin** [comment]
Thanks to @geoguide we've also discovered that async errors are reported as 'Uncaught'. All the tests that 'need to be uncommented to check behaviour' should be improved, IMO.

**Comment by jbnicolai** [comment]
Closed thanks to the great work of @glenjamin in #1781
