### ISSUE TITLE
Make mocha persist Express 4 session

### ISSUE THREAD

**Issue by VictorQueiroz** [mochajs/mocha#1530]
There is some way to make Mocha persist with session data when testing with supertest?

**Comment by dasilvacontin** [comment]
persist when? Between test executions, suite executions, command execution, ...? Can't you store the HttpSession data of the fake client?

**Comment by VictorQueiroz** [comment]
http://pastebin.com/YXeEkEa3

I just want to keep the `req.session.cart` alive, for my controller are using it to keep the user cart.

**Comment by dasilvacontin** [comment]
Alive between what?

**Comment by VictorQueiroz** [comment]
Between all the tests. The `req.session.cart` is `undefined` before any of these requests... That's  the problem.

**Comment by dasilvacontin** [comment]
This has nothing to do with mocha..

You must send some kind of session identifier in the header of your request/response, or using a cookie. And then depending on the value, you initialise the `req.session.cart` in your middleware.
