### ISSUE TITLE
Node.js 0.12: child_process warning

### ISSUE THREAD

**Issue by XhmikosR** [mochajs/mocha#1539]
```
child_process: customFds option is deprecated, use stdio instead.
```

**Comment by travisjeffery** [comment]
pretty sure you're on an older mocha version, try updating mocha to the latest and let me know if you still have the issue

**Comment by XhmikosR** [comment]
All right, I'll double check if it's something wrong grunt-mocha-cov is doing.

**Comment by XhmikosR** [comment]
Indeed, grunt-mocha-cov is using an old mocha version. Sorry for the noise.
