### ISSUE TITLE
Before function doesn't allow console to print output

### ISSUE THREAD

**Issue by ilanbiala** [mochajs/mocha#1549]
I have a before function that makes an API call, and if the test times out, then it doesn't print anything, which isn't useful when I'm trying to see what the server logs.

**Comment by a8m** [comment]
Can you please provide some code snippet or fiddle example @ilanbiala ? 
thx

**Comment by ilanbiala** [comment]
The code inside the `before` function used to not work, and debugging it was extremely difficult because I would not get any logging from the server.
```
before(function(done) {
    this.timeout(3000);

    agent
      .post('/auth/mock')
      .send({
    		firstName: 'Test',
    		lastName: 'User',
    		displayName: 'Test User',
    		email: 'testuser@gmail.com',
    		provider: 'local',
    		password: 'testuser',
    		isAdmin: true
    	})
      .expect(200)
      .end(function(err, res) {
        if (err) {
          return done(err);
        }

        res.body.should.have.property('success', true);

        user = res.body.user;

        done();
      });
  });
```

**Comment by boneskull** [comment]
Dunno... if it times out, it times out.  How is Mocha supposed to know what to print?

My suggestion would be to set a timeout on your HTTP request itself.  Is this workable?

**Comment by ilanbiala** [comment]
@boneskull it didn't time out, it threw an error, but it wouldn't print out anything from anywhere else.

**Comment by dasilvacontin** [comment]
@ilanbiala What error? In the first post you actually mentioned 'when it times out'..

**Comment by ilanbiala** [comment]
@dasilvacontin I changed a lot of my code to get it working now, so I can't reproduce it and tell you whether it said it timed out or that an error occurred. I'll provide any more information if I encounter this issue again.

**Comment by dasilvacontin** [comment]
Oh, so you can't reproduce the error anymore, @ilanbiala?

**Comment by ilanbiala** [comment]
The error was reproducible when I had certain code to test, but that code has changed. I'll post any more info here if I hit that wall again.

**Comment by dasilvacontin** [comment]
If the problem is that Mocha quits before you log anything, why don't make the server log into a file?

**Comment by danielstjules** [comment]
@ilanbiala Closing for now. If you're able to reproduce the issue and provide a small test case, feel free to re-open! :)
