### ISSUE TITLE
Why "return done(err)"?

### ISSUE THREAD

**Issue by pensierinmusica** [mochajs/mocha#1554]
Hi,

Just a quick question about something I can't fully grasp.

Could you help me understand why in the [docs ](http://mochajs.org/#getting-started) the async example rejects with `return done(err)` instead of simply `done(err)`?

This is the code I'm referring to:

```javascript
describe('Connection', function(){
  var db = new Connection
    , tobi = new User('tobi')
    , loki = new User('loki')
    , jane = new User('jane');

  beforeEach(function(done){
    db.clear(function(err){
      if (err) return done(err);
      db.save([tobi, loki, jane], done);
    });
  })

  describe('#find()', function(){
    it('respond with matching records', function(done){
      db.find({ type: 'User' }, function(err, res){
        if (err) return done(err);
        res.should.have.length(3);
        done();
      })
    })
  })
})
```

What would be the difference it was written like this?

```javascript
describe('Connection', function(){
  var db = new Connection
    , tobi = new User('tobi')
    , loki = new User('loki')
    , jane = new User('jane');

  beforeEach(function(done){
    db.clear(function(err){
      if (err) done(err);
      db.save([tobi, loki, jane], done);
    });
  })

  describe('#find()', function(){
    it('respond with matching records', function(done){
      db.find({ type: 'User' }, function(err, res){
        if (err) done(err);
        res.should.have.length(3);
        done();
      })
    })
  })
})
```

In fact, it seems unconsistent to me that when there is an error the promise is rejected with `return done(err)`, but if all is fine is fulfilled insted with `done()`. Shouldn't we simply call `done([err])` in both cases, without the need to `return` it?

Btw, this seems to be the same approach used in the docs of [chai-as-promised](https://github.com/domenic/chai-as-promised/).

Thanks!

**Comment by rlidwka** [comment]
This code:

```js
if (err) return done(err)
res.should.have.length(3)
done()
```

Is a short equivalent to this:

```js
if (err) {
  done(err)
} else {
  res.should.have.length(3)
  done()
}
```

And `return` statement is necessary to prevent calling `done` twice. That's basic javascript syntax.

**Comment by dasilvacontin** [comment]
Thanks for explaining it @rlidwka. I'm closing this, leave a comment if there is any doubt left.

**Comment by pensierinmusica** [comment]
Hi @rlidwka, I see, thanks for the clarification  :)  I should have seen it myself, but when one codes too much things tend to get a bit blurry... ahaha! Cheers
