### ISSUE TITLE
HTML runner formats function source incorrectly

### ISSUE THREAD

**Issue by fasttime** [mochajs/mocha#1556]
We noticed an issue with the source code of a test function shown in the HTML runner when a user clicks on a test case. When the function's body curly bracket starts on a new line, the output is not truncated correctly, i.e.:

```js
it(
    'test case',
    function ()
    {
        say('hi!');
    }
);
```

is presented in the browser as

```
function ()
    {
        say('hi!');
````

If the curly bracket is on the first line, then everything is fine.

```js
it(
    'test case',
    function () {
        say('hi!');
    }
);
```

correctly renders as

```
say('hi!');
```

I was able to work around this issue by manually changing the regular expression
`/^function *\(.*\) *{|\(.*\) *=> *{?/`
into
`/^function *\(.*\)\s*{|\(.*\) *=> *{?/`
in mocha.js and lib/utils.js.
A more robust solution would be better here.

**Comment by danielstjules** [comment]
Hi @fasttime, thanks for pointing this out! Your solution is about as robust as I think we'd be willing to go. To be able to accommodate all possible scenarios (in particular, involving comments), we'd need something like esprima or acorn, which becomes a bit heavy for such simple functionality.
