### ISSUE TITLE
Some documentation appears backwards

### ISSUE THREAD

**Issue by travisperson** [mochajs/mocha#1557]
Synchronous code
*When testing synchronous code, omit the callback and Mocha will automatically continue on to the next test.*

The callback is not introduced till the Asynchronous section right below.

Asynchronous code
*All "hooks", that is before(), after(), beforeEach(), afterEach() may be sync or async as well, behaving much like a regular test-case.*

Hooks aren't described till after this section.

**Comment by jbnicolai** [comment]
Doesn't seem like an issue. The documentation is not really meant as a linear explanation, but as a reference manual in which you look up things.
