### ISSUE TITLE
Uncaught ReferenceError: Buffer is not defined [mocha.js:5833]

### ISSUE THREAD

**Issue by dustinbrownman** [mochajs/mocha#1558]
Getting this error with the latest version of the `mocha.js` file. I'm using the browser interface. Looks like the line that causes this error was added in eab389f3f106290e8386520a2f3b8206c18c486e. I set up a [dummy app](http://github.com/dustinbrownman/test-mochajs) demonstrate the error. Just open up `spec-runner.html` and open up the developer tools. Any thoughts on how to fix this? (Thanks to @clemf for finding this)

**Comment by boneskull** [comment]
Thanks.  If we don't start building with browserify soon I'm gonna jump off a cliff

**Comment by callmevlad** [comment]
Seeing the same thing. Needs to be `if (typeof Buffer !== 'undefined' && ...)` instead of `if (Buffer && ...)`, though I'm still trying to track down another error (`failed to require "supports-color"`) that's downstream from that fix.

**Comment by a8m** [comment]
> Needs to be `if (typeof Buffer !== 'undefined' && ...)` instead of `if (Buffer && ...)`

why it's matter @callmevlad ?

**Comment by callmevlad** [comment]
@a8m Browsers handle this differently than V8 in Node.js - for example, try the following in your Chrome console:

Breaks:
`if (Bob) { console.info("Bob exists."); }` -> ` Uncaught ReferenceError: Bob is not defined`

Works:
`if (typeof Bob !== "undefined") { console.info("Bob exists."); }`

**Comment by dustinbrownman** [comment]
Confirmed that this is still an issue. Updated dummy app with new `mocha.js` file and it's the same error, but on a different line. And @callmevlad is right, this is a browser issue. I've tested it in Chrome and Firefox and gotten the same error each time.

**Comment by a8m** [comment]
@callmevlad makes sense, thx.

**Comment by callmevlad** [comment]
Just added a PR for this: https://github.com/mochajs/mocha/pull/1560
