### ISSUE TITLE
publish a minor release

### ISSUE THREAD

**Issue by dasilvacontin** [mochajs/mocha#1568]
It's been asked for weeks already, maybe over a month.

**Comment by a8m** [comment]
+1 @dasilvacontin 
(I'm waiting for that since f43006aec9bff54e1d71cd6f7513dd6352d1410c)

**Comment by dasilvacontin** [comment]
That's def over a month then. :)

**Comment by am11** [comment]
:+1:

**Comment by a8m** [comment]
since we're released a new version 65fc80ecd96ca2159a792aff089bbc273d4bd86d, this issue can be closed.

**Comment by am11** [comment]
@a8m, thanks for the heads-up dude! I was desperately waiting for this release. :stuck_out_tongue_winking_eye:

**Comment by a8m** [comment]
Cheers @am11

**Comment by dasilvacontin** [comment]
Awesome! Thanks for preparing the release, @travisjeffery. :)
