### ISSUE TITLE
Using "-gc" flag omits all tests

### ISSUE THREAD

**Issue by GeoffreyPlitt** [mochajs/mocha#1571]
When I run mocha tests normally, everything works.

But when I use the "-gc" flag which is supposed to expose garbage collection, I just get "0 passing", it skips all tests.

**Comment by GeoffreyPlitt** [comment]
Related: https://github.com/mochajs/mocha/issues/152

**Comment by danielstjules** [comment]
Hi @GeoffreyPlitt, what version of mocha are you using? I can't seem to reproduce with 2.2.1:

``` javascript
danielstjules:~/git/mocha (master =)
$ cat example.js
it('test', function() {});
it('test2', function() {});
it('test3', function(done) { setTimeout(done, 180); });
danielstjules:~/git/mocha (master =)
$ ./bin/mocha -gc example.js


  ․․․

  3 passing (185ms)
```

**Comment by GeoffreyPlitt** [comment]
Sorry, looks like I was on Mocha 2.1.0, I'll use the latest, thanks!

**Comment by danielstjules** [comment]
Happy it worked!
