### ISSUE TITLE
Stop printing trailing whitespace for it(...) checked messages

### ISSUE THREAD

**Issue by mcandre** [mochajs/mocha#1574]
As a power user, I want to be able to feed Mocha output to other command line programs without fear of trailing whitespace gumming up things. As of Mocha 1.21.4, each checked message prints with an extra space at the end, creating issues with documentation tools and editorconfig.

**Comment by danielstjules** [comment]
I thought this might only be an issue before 2.x.x, but looks like it's still a problem! I'll get a PR ready - thanks for reporting this!

```
$ cat example.js
it('test', function() {});
it('test2', function() {});

# 1.21.4
$ ./bin/mocha --reporter spec example.js > output.txt

^[[0m^[[0m
^M^[[32m  ✓^[[0m^[[90m test ^[[0m
^M^[[32m  ✓^[[0m^[[90m test2 ^[[0m

^[[92m ^[[0m^[[32m 2 passing^[[0m^[[90m (4ms)^[[0m


# 2.2.1
$ ./bin/mocha --reporter spec example.js > output.txt

  ✓ test <- there's a trailing space
  ✓ test2 <- another trailing space

  2 passing (3ms)
```

**Comment by mcandre** [comment]
Thanks Dan!

**Comment by danielstjules** [comment]
No problem! Happy to help :)
