### ISSUE TITLE
Documentation - coverage report when running programmatically

### ISSUE THREAD

**Issue by vasanthps** [mochajs/mocha#1576]
I found in the wiki how to run mocha programmatically:- https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically

It would be helpful if you can include how to generate coverage report when running programmatically as well.

Thanks

**Comment by danielstjules** [comment]
@vasanthps It would depend on the tool doing the coverage reports. I personally use blanket, but some prefer istanbul or jscoverage. You may also want to send it to something like coveralls. I feel like there's quite a few possibilities here.

**Comment by vasanthps** [comment]
@danielstjules Thank you. I had just started using mocha and was in a impression that, mocha also had coverage reporter inbuilt. I am now using Istanbul and things are working fine.

Regards
Vasanth
