### ISSUE TITLE
How to report a failed test manually? (globally)

### ISSUE THREAD

**Issue by staxmanade** [mochajs/mocha#1593]
Hello,

I'm working on a WinJS Windows 8 app and MochaJS is mostly running great.

My problem comes with a global exception is raised. WinJS does not use `global.onerror` to trap errors, but `WinJS.Application.onerror`.

I can handle the error in `WinJS.Application.onerror`, but have not yet figured out a way to tell mocha about this exception and allow it to fail the currently running test.

Any thoughts?

**Comment by danielstjules** [comment]
Though I'm completely unfamiliar with WinJS, is it possible to do something like:

``` javascript
WinJS.Application.onerror = function(err, url, line) {
  global.onerror(err, url, line);
};
```

**Comment by staxmanade** [comment]
SWEET :+1: 

With all the hacking I did, I'm surprised I didn't stumble on an approach like that - THANKS...

Here's what I eventually did: I'm using the `stack` property as it contains basically a full string of the exception message and stack trace combined.

```javascript
    app.onerror = function (ex) {
        window.onerror(ex.detail.exception.stack);
        return true;
    }
```

**Comment by danielstjules** [comment]
Glad that worked for ya!
