### ISSUE TITLE
_mocha not work under mac os

### ISSUE THREAD

**Issue by calidion** [mochajs/mocha#1594]
Error Info:

```bash
./node_modules/.bin/_mocha: line 1: /Applications: is a directory
./node_modules/.bin/_mocha: line 2: LICENSE: command not found
./node_modules/.bin/_mocha: line 3: node_modules/: is a directory
./node_modules/.bin/_mocha: line 5: syntax error near unexpected token `('
./node_modules/.bin/_mocha: line 5: `var program = require('commander')'
make: *** [test] Error 2
````

Solution:
Add this line to the top of _mocha file

```bash
#!/usr/bin/env node
````

**Comment by danielstjules** [comment]
Related: https://github.com/mochajs/mocha/issues/1585 https://github.com/mochajs/mocha/pull/1567 https://github.com/mochajs/mocha/commit/1430c2b5102e9d355119a643e9b2be2e76e91d1f https://github.com/mochajs/mocha/issues/1548

@calidion How are you invoking mocha?

**Comment by calidion** [comment]
> _mocha --reporter spec
/home/travis/build/calidion/web-errors/node_modules/.bin/_mocha: 1: /home/travis/build/calidion/web-errors/node_modules/.bin/_mocha: /bin: Permission denied
/home/travis/build/calidion/web-errors/node_modules/.bin/_mocha: 2: /home/travis/build/calidion/web-errors/node_modules/.bin/_mocha: LICENSE: not found
/home/travis/build/calidion/web-errors/node_modules/.bin/_mocha: 3: /home/travis/build/calidion/web-errors/node_modules/.bin/_mocha: node_modules/: Permission denied
/home/travis/build/calidion/web-errors/node_modules/.bin/_mocha: 5: /home/travis/build/calidion/web-errors/node_modules/.bin/_mocha: Syntax error: "(" unexpected

**Comment by calidion** [comment]
```make
	@$(NPM)/_mocha \
		--reporter $(if $(or $(TEST),$(V)),spec,dot) \
		--slow 600 --timeout 2000 \
		--grep '$(TEST)'
```

**Comment by danielstjules** [comment]
Have you tried using `mocha` instead of `_mocha`?

**Comment by calidion** [comment]
@danielstjules 
using mocha works well.
thanks.
