### ISSUE TITLE
On timeout 'after' or 'afterEach' doesnt run

### ISSUE THREAD

**Issue by gyandeeps** [mochajs/mocha#1596]
I had one asyn test which fails because the operation timeout. But what I saw was the `after` and `afterEach` did not run after that.
Since it is important in my case because I do some clean up in those steps.

Is this desired behavior or its a bug?

**Comment by danielstjules** [comment]
Hi @gyandeeps, it doesn't seem to be a problem with the latest version of mocha. What version are you running? If not the latest (2.2.1), have you tried upgrading?

Here's a working example:
``` javascript
$ cat example.js
afterEach(function() {
  console.log('afterEach');
});

after(function() {
  console.log('after');
});

it('this will timeout', function(done) {
  setTimeout(done, 10000);
});

dstjules:~/git/mocha (master=)
$ ./bin/mocha example.js

  ․afterEach
after


  0 passing (213ms)
  1 failing

  1)  this will timeout:
     Error: timeout of 200ms exceeded. Ensure the done() callback is being called in this test.
      at null.<anonymous> (lib/runnable.js:170:19)
```

**Comment by gyandeeps** [comment]
I am using 2.2.1
It happened 4 out of 5 times and I had 3 - 4 timeout errors.
Basically my test was testing `svn checkout` operation so it had different results on each run.

**Comment by danielstjules** [comment]
What sort of logic are you trying to invoke in the `after` and `afterEach` hooks? Is it possible the logic in the hooks have a race condition or some other issues? If not, can you provide a small, reproducible test case? It would definitely help us narrow down what the issue is :)

**Comment by gyandeeps** [comment]
This is my test file:

```.js
var assert = require("chai").assert;
var sinon = require("sinon");
var path = require("path");
var svnOperations = require("../../lib/util/svnOperations");
var fse = require("fs-extra");
var fs = require("fs");

describe("SVN operations testing", function(){
    before(function(){
        this.cwd = process.cwd();
        process.chdir(path.resolve(__dirname, "..", "./resources"));
    });

    beforeEach(function(){
        //create svn directory if its not already there
        fse.ensureDirSync("./svn");
    });

    afterEach(function(){
        if(fs.existsSync("./svn")){
            fse.removeSync("./svn");
        }
    });

    after(function(){
        if(fs.existsSync("./svn")){
            fse.removeSync("./svn");
        }
        process.chdir(this.cwd);
    });

    it("Throw error if the svn checkout is not a successful", function(done){
        var callback = sinon.spy(function(err){
            assert.instanceOf(err, Error);
            done();
        });

        svnOperations.checkout("<any url of an invalid location>", "./svn", callback);
    });

    it("svn checkout is successful", function(done){
        var callback = sinon.spy(function(){
            assert.isTrue(fs.existsSync("./svn/src/main/resources/component/js/warfarin.js"));
            done();
        });

        svnOperations.checkout("<any url of an invalid location>", "./svn", callback);
    });
});
```

**Comment by danielstjules** [comment]
@gyandeeps Could `svnOperations.checkout()` be the culprit? Is it doing anything on top of https://github.com/ddliu/node-svn-spawn/blob/master/lib/svn.js#L36 ? If you add `console.log` before the condition, are you positive that the afterEach hook isn't being invoked? Maybe even log the cwd.

I'm wondering if something is passing a diff cwd option to Client.prototype.checkout, and https://github.com/ddliu/node-easy-spawn/blob/master/index.js#L35-L119 which would result in the cleanup never happening - since `./svn` may not exist.

Sorry if I sound skeptical. I'm just not convinced it could be mocha since I can establish tons of specs that timeout and not have this issue.

**Comment by gyandeeps** [comment]
I guess i will keep trying to dig more into this. If i see a issue with mocha then i will reopen this issue.
Thanks a lot for your time @danielstjules

**Comment by danielstjules** [comment]
Sorry I couldn't be of more help!

If you were to update the specs to use:

``` javascript
    afterEach(function(){
        console.log('afterEach');
        if(fs.existsSync("./svn")){
            fse.removeSync("./svn");
        }
    });

    after(function(){
        console.log('after');
        if(fs.existsSync("./svn")){
            fse.removeSync("./svn");
        }
        process.chdir(this.cwd);
    });
```

you're positive the hooks aren't being invoked? Aside from that, I'd def try digging into the chdir and cwd calls.
