### ISSUE TITLE
[Question] Purpose of process.exit(failures); when running programmatically

### ISSUE THREAD

**Issue by IanVS** [mochajs/mocha#1605]
In the wiki for running Mocha programmatically (https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically), there is a strange bit of code at the end and I can't determine its purpose:
```
process.on('exit', function () {
  process.exit(failures);
});
```
According to the Node docs for the [exit event](https://nodejs.org/api/process.html#process_event_exit), the snippet above seems to do nothing other than exit with the same error status that the process would have exited with in the first place.

I could see this being more useful if it were perhaps:
```
process.on('exit', function () {
  if (failures > 0) {
    console.log(failures, 'Failing Tests');
  } else if (failures === 0) {
    console.log('All Tests Passed!');
  }
});
```
I'm not very experienced with Node, so is there some reason for having these lines which I'm not understanding?

**Comment by danielstjules** [comment]
```
mocha.run(function(failures){
  process.on('exit', function () {
    process.exit(failures);
  });
});
```

Imagine if this script/program was part of a build system (travis ci, etc). By default, Node will exit with an error code of 0, which indicates success. As a result, if a job/build ran that script, it would pass. But say you wanted the build to fail if there were any failures in the test suite. To do that, you pass the number of failures to `process.exit`. That way, if failures is 0, the script will indicate that everything ran normally, and the build will pass. But when failures is greater than 0, the build will fail as it's a non-zero exit code.

Hope that makes sense. :)

**Comment by IanVS** [comment]
Thanks @danielstjules.

The example in the Node docs is basically:
```
process.on('exit', function(code) {
  console.log('About to exit with code:', code);
});
```
Which makes it seem to me like the code would be passed without the explicit `process.exit`

So wouldn't this be sufficient to cause the process to exit with the number of failures?
```
mocha.run(function (failures) { });
```
Maybe I should go do some tests before I say anything else too stupid...

**Comment by danielstjules** [comment]
``` javascript
$ cat test.js
process.on('exit', function(code) {
  console.log('About to exit with code:', code);
});

danielstjules:~
$ node test.js
About to exit with code: 0
```

``` javascript
$ cat test.js
process.on('exit', function(code) {
  console.log('About to exit with code:', code);
});

throw new Error('oops!');

danielstjules:~
$ node test.js
About to exit with code: 1
```

Using that function will only help if the process was already going to exit with a non-zero status code. Since Mocha isn't throwing any uncaught exceptions or anything, the process would still exit normally (non-zero) after invoking `run`, despite the fact that test failures occurred. Hence needing to pass failures as the exit code.

**Comment by danielstjules** [comment]
By using
``` javascript
mocha.run(function (failures) { });
```

your script would always exit with a zero status code, unless some other part of your code (unrelated to Mocha) called process.exit or threw an error or something similar. When you use mocha programmatically, you're using lib/mocha.js rather than bin/mocha, which doesn't ever call process.exit()

For reference: https://github.com/mochajs/mocha/blob/369fb486e1ddef5393635e438793cd18ae466196/lib/mocha.js#L417-L442

**Comment by IanVS** [comment]
I see now, thanks for taking the time to explain it.  The main difference I was missing is that in the Node example, the `process.on('exit')` was taking a callback with the code as an argument, meaning this code was already going to be used as the exit code.  The mocha snippet, on the other hand, does not use an argument in that callback, the argument is on the `mocha.run` itself (one level higher).

Again, thanks for taking the time to explain!

**Comment by danielstjules** [comment]
No worries, hope it helped a bit! :)

**Comment by IanVS** [comment]
It sure did.  The whole reason I was looking at this is that it caused a failure in ESLint rule "[no-process-exit](http://eslint.org/docs/rules/no-process-exit.html)", whereby it flags any use of process.exit() since normally it's better to throw an error.  But, down at the bottom of the page is the statement:

> There may be a part of a Node.js application that is responsible for determining the correct exit code to return upon exiting. In that case, you should turn this rule off to allow proper handling of the exit code.

So, that's exactly what I'll do here!

One last question though: since Node has defined meanings to error codes (https://nodejs.org/api/process.html#process_exit_codes) is there any downside to overloading the exit code to represent the number of failing tests?

**Comment by danielstjules** [comment]
Nope, not unless you intend to listen and react to those error codes. So I wouldn't worry about it. :)

Looking at https://nodejs.org/api/process.html#process_exit_codes, if you _really_ needed to support node's exit codes, you could try one of the following:

``` javascript
mocha.run(function(failures) {
  process.on('exit', function (code) {
    // Shift mocha exit codes into the 20s+
    // This works if you have under 108 failures lol
    process.exit(code || (failures + 20));
  });
});

mocha.run(function(failures) {
  process.on('exit', function (code) {
    // Exit code 13 means failing test, otherwise it's a node error
    // I picked 13 as it's the first int not used by node in that list
    // You could use something else between 13 and 127
    process.exit(failures ? 13 : code);
  });
});
```
