### ISSUE TITLE
Add support for nativescript

### ISSUE THREAD

**Issue by gngeorgiev** [mochajs/mocha#1608]
https://www.nativescript.org/

**Comment by dasilvacontin** [comment]
I'm not familiar with NativeScript, but I've dug around a bit.

Seems like your .js files are copied to the bundle as is, no compiling or transpiling, and the only thing that changes are the underlying NativeScript libraries that you are using depending on your target platform. Therefore, Mocha is supported out of the box.

I've found no way of executing the App's code unless when running the app on the target platform. You should anyways test the code on the target devices to ensure everything runs fine.

You could `require` and use Mocha programatically. The output would show in your IDE/console when running the App in debug mode, e.g. in Xcode's Console.

That's the best solution I've come up with so far. Maybe someone else comes up with a better one, not sure.

**Comment by boneskull** [comment]
NativeScript should provide some reasonable way to test your app.  A cursory browse through the issues and documentation shows no mention of testing whatsoever.

**Comment by z3t0** [comment]
@boneskull Agreed. I am also looking for something like this... all they have is the debug feauture

**Comment by boneskull** [comment]
@z3t0 https://github.com/NativeScript/karma-nativescript-launcher/blob/master/concept.md
