### ISSUE TITLE
Infinite loops seem to escape timeouts

### ISSUE THREAD

**Issue by akrs** [mochajs/mocha#1609]
I wrote a test where the fail condition would be an infinite loop. However, infinite loops seem to escape the normal mocha timeout. See trivial test case below:
```javascript
expect = require("chai").expect

describe("loops", function() {
    it("does timeout", function(done) {
        setTimeout(done, 3000);
    });
    
    it("should timeout", function(done) {
        while (true) {}
        done();
    });
});
```

The "does timeout" test fails as expected, but the "should timeout" test runs forever.

**Comment by akrs** [comment]
It seems like this is something that node does. For example, for the following node snippet, `test` will never be printed.
```javascript
setTimeout(function() {console.log("test")}, 1000);
while (true) {}
```

Unless there's some way to work around this, you might want to remove "auto-exit to prevent "hanging" with an active loop" from the homepage.

**Comment by danielstjules** [comment]
It should be able to handle asynchronous loops:
```
var i, test;
i = 0;
test = function() {
  console.log(i++);
  setTimeout(test, 1000);
};

test();
```

If a loop such as yours blocks the event loop, there isn't much opportunity for Mocha or any other function to jump in and stop it.

**Comment by danielstjules** [comment]
You're probably right that it's a distinction we could make though :) Thanks for mentioning it.

**Comment by danielstjules** [comment]
@akrs Just noticed you were referring to `auto-exit to prevent "hanging" with an active loop`. Mocha does correctly handle that. What is meant by that statement, is that mocha will exit even if the event loop has functions to be ran. As a result, the example below will not cause Mocha to hang for 10 seconds:

``` javascript
setTimeout(function() {
  console.log(Date.now());
}, 10000);

it('test', function() {
  console.log(Date.now());
});
```

```
$ mocha example.js

  1427088876813

  ․

  1 passing (7ms)
```

Notice that mocha exit as soon as it's done running the test suite, and doesn't wait for the function that's set to be ran 10 seconds later. Hope that makes sense! :)

**Comment by ccoenen** [comment]
I think, it is worth a sentence in the "Timeout" section on the website. A simple "an infinite loop will not cause a timeout, this is a limitation of node.js" would do just fine.

**Comment by krzkaczor** [comment]
I am writing now some babel plugins and I got bitten by this behaviour. 

Actually, there is a way to a break from 'unbreakable loops' for example using this library: https://github.com/tjanczuk/tripwire I am gonna take a closer look at it.
