### ISSUE TITLE
String diffs not shown anymore when using node assert.equal

### ISSUE THREAD

**Issue by mantoni** [mochajs/mocha#1614]
I created a gist that reproduces the issue for me on OS X with node 0.10.32:
https://gist.github.com/mantoni/e2927ced1484f01b1fb8

Thanks for looking into it!

**Comment by a8m** [comment]
I'm not sure what do you mean by saying "anymore", in which version it works @mantoni ?
as far as I know, using `assert` never was showing diff. for [this](https://github.com/mochajs/mocha/blob/master/lib/reporters/base.js#L182) reason.

**Comment by mantoni** [comment]
Can't say exactly when it stopped working, but I took this screenshot once: https://www.npmjs.com/package/consolify

**Comment by mantoni** [comment]
Thanks for the pointer @a8m, I removed the `err.showDiff &&` part from the conditional in the line you mentioned and then it works perfectly fine.

**Comment by a8m** [comment]
kk, I'm on it.
trying to detect in which version it's stop to work.

**Comment by a8m** [comment]
this commit: https://github.com/a8m/mocha/commit/a5d7240a83f934b16b98b07f170c2d6288d58d7d

**Comment by a8m** [comment]
Thanks for pointing that out @mantoni.

**Comment by a8m** [comment]
Is this something that we want to fix @mochajs/mocha ? if so, I'll label it as a "bug", and start to working on it.

**Comment by dasilvacontin** [comment]
So it depends on whether the asserting library sets `showDiff` to true or not? Like, as an user, could you do something to show the diff, without modifying the library?

**Comment by mantoni** [comment]
It's a feature that is advertised on the mocha page, but it only works in specific setups. So if this is bot going to considered a bug, it could be a new flag to opt in and it would be nice to pit some notes on how to get it working on the web page.

**Comment by a8m** [comment]
Yes, but it's worked before(`<1.21.5`) @dasilvacontin . that's the reason I see it as a regression.

**Comment by dasilvacontin** [comment]
Could you please answer my doubts/questions?

Regarding if it's a regression or not, we are making people waste time trying to figure out why the diff is not showing, and how to make it show it again. That's something I would only do in a major version. We need to get this fixed this asap.

**Comment by a8m** [comment]
> So it depends on whether the asserting library sets showDiff to true or not, right?

Yes.

> Like, as an user, could you do something to show the diff, without modifying the library?

If you're using `assert`, I don't see any other way except this:
```js
try {
  assert.equal("foo", "bar")
} catch(e) {
  e.showDiff = true
  throw e
}
```

**Comment by dasilvacontin** [comment]
Thanks very much, @a8m.

Ugh, this is ugly. Maybe we could add a flag for ignoring `.showDiff` and introduce it in `3.0.0`. Or what would you suggest?

**Comment by a8m** [comment]
> Maybe we could add a flag for ignoring ...

Flag is not a good solution for some reasons(e.g: you can't use it dynamically or for a specific assertions).

I think it should `.showDiff` by default and if you don't want it, you should explicitly set it to `false`, [like this](https://github.com/mochajs/mocha/blob/master/test/reporters/base.js#L105-L136) (and it will not break anything).

**Comment by dasilvacontin** [comment]
But then the user wouldn't have a choice, it would be up to the assertion module/library, right?

**Comment by mantoni** [comment]
I like @a8m proposed because it makes Mocha work as advertised without breaking other libraries that depend on the `showDiff` property. The proposal brought up by @dasilvacontin make sense and I think having an option to control the behavior would certainly improve the feature. However, I don't see that being necessary to fix the issue.

**Comment by a8m** [comment]
> However, I don't see that being necessary to fix the issue.

Me too.

**Comment by dasilvacontin** [comment]
Goes. :ship:

**Comment by a8m** [comment]
Thanks guys @mantoni @dasilvacontin

**Comment by arve0** [comment]
For other goofers experiencing this, remember that `npm test` runs local node_modules/mocha. So do a `npm install -g mocha` if you use `mocha mytest.js`.
