### ISSUE TITLE
How to implement setTimeout in TDD user-interface

### ISSUE THREAD

**Issue by Virbhadrasinh** [mochajs/mocha#1620]
I need setTimeout in TDD user-interface.

I want to do something like,
<pre>
suite('Sample Suite', function() {
	suite('sample timeout test', function() {
		test('should know 5+5', function() {
			setTimeout(function() {
				expect(11).to.equal(10);
			}, 1000);
		});
	});
});
</pre>

This test case should fail but it is passing and giving error in console like **Uncaught AssertionError: expected 11 to equal 10**

How can I force this test case to fail ?

**Comment by dasilvacontin** [comment]
Since it's an async test, you need to define a `done` callback and execute it when your test is finished:
```js
test('should know 5+5', function(done) { // <-----
  this.timeout(500); // <------ (if you want to change the  200 default ms for which mocha waits for a result
  setTimeout(function() {
    expect(11).to.equal(10);
    done(); // <------
  }, 1000);
});
```

**Comment by Virbhadrasinh** [comment]
It's working now. Thanks a lot.

**Comment by dasilvacontin** [comment]
You're welcome! Come back if you have any other doubts or you happen to find a bug. :)
