### ISSUE TITLE
CLI doesn't support the `-v` option

### ISSUE THREAD

**Issue by dasilvacontin** [mochajs/mocha#1629]
```bash
➜  Desktop  mocha -v
  error: unknown option `-v'
```

**Comment by a8m** [comment]
`v` for version ?

**Comment by dasilvacontin** [comment]
Yeah, usually both `-v` and `--version` should tell the version of the program.

**Comment by a8m** [comment]
Did you try `-V` ?

**Comment by a8m** [comment]
This is something of `commander` I think.

**Comment by dasilvacontin** [comment]
oh shit. Why not lowercase? Maybe `commander` bug? idk

**Comment by a8m** [comment]
see [mocha(https://github.com/mochajs/mocha/blob/master/bin/_mocha#L58)

**Comment by dasilvacontin** [comment]
I see. I will take a look at `commander` then, and reopen this if necessary. Kudos!

**Comment by a8m** [comment]
Great, thx @dasilvacontin

**Comment by danielstjules** [comment]
Yea, commander uses `-V|--version`, which is nice cause a lot of people use `-v|--verbose` for detailed cli output.
