### ISSUE TITLE
new ui / reporter thing

### ISSUE THREAD

**Issue by paulpflug** [mochajs/mocha#1633]
I just created a new ui / reporter thing.
It will make the results pretty by sending them to the browser..
It combines the debug level of the console (it watches stdout and stderr)
with the pretty output of a browser ui. 

[report-viewer](https://github.com/paulpflug/report-viewer)

I would add it to the wiki if I may (Add-ons -> Interfaces & Reporters ?)

**Comment by danielstjules** [comment]
Starred it. :) That is super cool! And yeah, def add it to the wiki!

**Comment by dasilvacontin** [comment]
Let us know if you need any help! :)

**Comment by paulpflug** [comment]
ok, I added it. Thank you guys.

**Comment by dasilvacontin** [comment]
You're welcome, thanks for the addition/reporter! :)
