### ISSUE TITLE
update documentation of `--async-only` for v2.3.0

### ISSUE THREAD

**Issue by dasilvacontin** [mochajs/mocha#1636]
It can be now satisfied by returning a promise. Related: #1490.

**Comment by boneskull** [comment]
@mochajs/mocha see milestone v2.3.0 for features; please add stuff if needed

**Comment by boneskull** [comment]
going to leave this here as it relates to the next release, but otherwise anything labeled `Documentation` should go into mochajs/mocha.github.io

**Comment by boneskull** [comment]
closing this; need to update docs
