### ISSUE TITLE
setting currentTest in a hook is incorrect

### ISSUE THREAD

**Issue by brian-mann** [mochajs/mocha#1638]
This line:

https://github.com/mochajs/mocha/blob/41a21192ff288958b81654aeea3805190e9304b3/lib/runner.js#L263

This is completely wrong based on the when `self.test` is defined.

Currently `self.test` is defined when a test emits its `test` event here:

https://github.com/mochajs/mocha/blob/41a21192ff288958b81654aeea3805190e9304b3/lib/runner.js#L462

This has the following problems:
- A `beforeAll` hook will not have `hook.ctx.currentTest` defined, since `self.test` has not been assigned to the runner yet.
- Nested suites which have a `beforeAll` hook will actually set the `hook.ctx.currentTest` to the PREVIOUSLY run test, based on the same logical problem as the previous bullet point.
- `beforeEach` hooks do not suffer from this problem because tests emit their `test` event prior to the hooks being invoked, thus setting `self.test` on the runner.

The structure I'm referring to looks like this:

``` coffeescript
before ->
  ## this.currentTest is undefined

describe "outer suite", ->
  it "foo", ->

  context "nested [0me]", ->
    before ->
      ## this.currentTest will refer to "foo" test and not "bar" test

    it "bar", ->
```

**Comment by danielstjules** [comment]
So, if I understand correctly, you'd like currentTest to be set for the `before` hook. To demonstrate how this behavior does not currently exist:

``` javascript
describe('example', function() {
  before(function() {
    console.log('before', this.currentTest);
  });

  beforeEach(function() {
    console.log('beforeEach', this.currentTest.title)
  });

  afterEach(function() {
    console.log('afterEach', this.currentTest.title)
  });

  after(function() {
    console.log('after', this.currentTest.title)
  });

  it('test1', function() { });

  it('test2', function() { });
});
```

```
$ ./bin/mocha test.js

before undefined
beforeEach test1

  ․afterEach test1
beforeEach test2
․afterEach test2
after test2
```

**Comment by brian-mann** [comment]
Yes, you've demonstrated the bug exactly as described.

The one thing you're missing is that if you were to nest a new `describe` block, and then issue a new `before` hook, instead of seeing `undefined` as `this.currentTest`, you would actually see a reference to the previous test.

That makes this bug twice as bad.  In a top level `before` hook, `this.currentTest` is usually `undefined`, but in a nested `before` hook, `this.currentTest` will actually refer to the **wrong** test.

**Comment by ORESoftware** [comment]
:+1:  whoops that's a bug

**Comment by boneskull** [comment]
my hunch this that is actually the root cause of a handful of other problems. 

if I get bitten by the bug-fixing-bug, I'll take a look at this.  otherwise, would appreciate help!
