### ISSUE TITLE
Error: timeout of 1.7976931348623157e+308ms exceeded.

### ISSUE THREAD

**Issue by callumacrae** [mochajs/mocha#1643]
I set `this.timeout(Number.MAX_VALUE);` to see what would happen, and my tests instantly fail with the following error:

```
Error: timeout of 1.7976931348623157e+308ms exceeded. Ensure the done() callback is being called in this test.
```

I definitely didn't wait that long

**Comment by dasilvacontin** [comment]
Too big for `setTimeout`.
```
function sayHi () {
  console.log('hi')
}
setTimeout(sayHi, Number.MAX_VALUE)
> hi
```
Related: http://stackoverflow.com/questions/3468607/why-does-settimeout-break-for-large-millisecond-delay-values

I don't think it's useful/necessary to support timeouts bigger than 24.8 days, and it's probably a better idea to keep consistency with `setTimeout`'s behavior.

If someone disagrees, please reopen the issue / let me know.

**Comment by callumacrae** [comment]
Ah, that's completely fair enough. It's definitely useless :smile:

**Comment by boneskull** [comment]
perhaps a more relevant exception should be thrown

**Comment by dasilvacontin** [comment]
@boneskull, that's true, as a reminder of `setTimeout`'s behavior. So that we save them looking into that.
