### ISSUE TITLE
2.2.3 no longer exposes suite global

### ISSUE THREAD

**Issue by sebmck** [mochajs/mocha#1645]
`suite` is no longer a global, is this intentional?

```
/Users/sebmck/Projects/babel/core/test/core/api.js:6
suite("api", function () {
^
ReferenceError: suite is not defined
```

**Comment by sebmck** [comment]
Actually I'm pretty sure it's because `mocha` is no longer picking up `mocha.opts` as `node node_modules/mocha/bin/_mocha --ui tdd test/core/` works. Reference babel/babel#1196.

**Comment by TheSavior** [comment]
This is failing all of our builds on projects depending on mocha. Serious issue.

**Comment by a8m** [comment]
Seems like this option was moved from `_mocha` to `mocha` in 83e1bc8f7cd1dcba5436c2c5c1bff9d6279521bc

/cc @travisjeffery

**Comment by danielstjules** [comment]
@sebmck Are you able to switch to using `node_modules/mocha/bin/mocha`?

**Comment by travisjeffery** [comment]
i'm trying it now and it's working for me?

**Comment by TheSavior** [comment]
We could switch, but this is a major issue causing breaking changes in backwards compatibility in a minor release. This breaks semver and needs a hotfix.

**Comment by travisjeffery** [comment]
yeah @sebmck just went through those contributions guides and it worked for me.

@TheSavior how are you running mocha?

**Comment by travisjeffery** [comment]
oh, for some reason you were executing the `_mocha` file rather than `mocha`?

**Comment by TheSavior** [comment]
```javascript
"scripts": {
    "travis": "grunt style && istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage"
  },
```

**Comment by boneskull** [comment]
@TheSavior What happens if you use the `mocha` executable?  Running `_mocha` directly is unsupported and may be completed dropped with the next major...

**Comment by boneskull** [comment]
@TheSavior If that fails (as it sounds like it will), does istanbul provide some sort of configuration file?

**Comment by travisjeffery** [comment]
running `mocha` will work

@TheSavior mocha itself uses `mocha`, https://github.com/mochajs/mocha/blob/master/Makefile#L45.

**Comment by travisjeffery** [comment]
i'm gonna re-add the option loading in `_mocha` for now, but that's definitely not gonna be possible in the next major version

**Comment by sebmck** [comment]
Had no idea why I was using `_mocha` but it was likely because I didn't want to unnecessarily spin up another process. Thanks for the hotfix @travisjeffery, really appreciate it!

**Comment by TheSavior** [comment]
FWIW, node-inspector also specifies that you need to use `_mocha` in order to debug tests: https://github.com/node-inspector/node-inspector#how-do-i-debug-mocha-unit-tests

**Comment by boneskull** [comment]
@mochajs/mocha 

I think it's worth taking a step back here.

I don't think `mocha` needs to fork `_mocha`.  This leads to a lot of confusion.

The *reason* `mocha` forks `_mocha` is because Mocha wants to support NodeJS CLI options (think `--harmony`).

I don't see a reason for that!  If you want NodeJS CLI options, *execute `mocha` with the `node` executable*, supply your options, and use `--` to supply extra options to `mocha`.  Feel me?

**Comment by travisjeffery** [comment]
with harmony flags et el., those get used a lot and will be more and more. so i don't think we're gonna remove those quite yet

**Comment by boneskull** [comment]
@travisjeffery If we remove the option to execute directly from `_mocha` we're going to obviously break some debuggers and coverage tools.  If there's no other way for those tools to do what they need, then we need to support something... I just don't see why we can't yank all that garbage out.  Besides, who says your executable is `node` anyway
