### ISSUE TITLE
Meta test generation fails to behave as expected when using promises

### ISSUE THREAD

**Issue by carrollgt91** [mochajs/mocha#1646]
I'll preface this by saying that I know that I'm taking the meta test generation a bit farther than is probably intended.

I'm attempting to build a regression test suite using mocha, and we need to be able to compose and parameterize mocha test suites. Here's a simple example:

``` javascript
var expect = require("chai").expect,
    Q = require("q");

var Workflow1 = {},
    Workflow2 = {};

Workflow1.run = function(param) {
  var deferred = Q.defer();

  describe("Example workflow1", function() {
    it("should have an assertion", function() {
      expect(param).to.be.an("object")
    });

    it("should have another assertion", function() {
      expect(10).to.not.equal(20);
    });

    after(function() {
      deferred.resolve();
    });
  });

  return deferred.promise;
}

Workflow2.run = function() {
  var deferred = Q.defer();

  describe("Example workflow2", function() {
    it("should have an assertion", function() {
      expect(2).to.equal(2)
    });

    it("should have another assertion", function() {
      expect(10).to.not.equal(20);
    });

    after(function() {
      deferred.resolve();
    });
  });

  return deferred.promise;
}

var Manifest = {};

Manifest.run = function() {
  Workflow1.run({blah: "blah"}).then(function() {
    debugger;
    Workflow2.run().then(function() {
      debugger;
    });
  });
};

Manifest.run();
```

However, if you run a file with this in it using `mocha debug path/to/file.js`, it will only run the first workflow. It will execute Workflow2.run, but the tests within will not be executed.

However, if you nest the `deferred.resolve()` statement within another describe block, as seen in this gist:

https://gist.github.com/carrollgt91/9f2a74a9b8faf31a93da

it works as intended, and will correctly chain the tests. That being said, it requires you to hack it a bit when you don't actually need the nested describe block there.

My first thought is I should probably use the programmatic interface to get this sort of fine grained control over what Mocha is running, but I would love the ability to maintain the BDD syntax within my workflows.

**Comment by boneskull** [comment]
@carrollgt91 I'm not exactly sure *why* you're doing what you're doing, but you may want `--delay` here (or not; it's at least worth taking a look at).

[See example](https://github.com/mochajs/mocha/blob/master/test/delay/delay.js)

It's unclear what you're proposing.  Is this a bug?  New feature?

**Comment by carrollgt91** [comment]
Thanks for the suggestion! Unfortunately, that flag prevents all tests from running in our dummy example.

I'd say that this would be a new feature.

 I'm building a black box regression test suite. We're running tests against an API (not built in javascript) with the intension of having complete separation between the test suite and API itself.

We want to be able to have modular tests that can easily compose with one another so that we can reuse our tests in multiple places with different parameters.

For example, if our API was the Github API and we were testing repository creation and collaboration, we'd take the following steps:

* Login as User1
* Create the repo as User1
* Push to the repo as User1
* Add User2 as a collaborator to the repo as User1
* Login as User2
* Push to the repo as User2

We want to make the same assertions about correctness every time we login, create a repo, and push to the repo. In this example, it feels pretty redundant, but due to the complexity of the business logic in our API, it would be hugely useful to err on the side of re-testing everything in various scenarios.

If this is outside of the scope of what you guys would like mocha to do, I totally understand. However, if you're interested in mocha fitting into a system like this, I would be happy to work on enabling it to work in this way.

**Comment by danielstjules** [comment]
@carrollgt91 I'm wondering if you really need promises for what you'd like to do?

This might be an alternative:
``` javascript
var expect = require("chai").expect,
    Q = require("q");

var Workflow1 = {},
    Workflow2 = {};

Workflow1.run = function(param) {
  describe("Example workflow1", function() {
    before(function() {
      console.log('  In Workflow1 with', param);
    });

    it("should have an assertion", function() {
      expect(param).to.be.an("object")
    });

    it("should have another assertion", function() {
      expect(10).to.not.equal(20);
    });
  });
}

Workflow2.run = function() {
  describe("Example workflow2", function() {
    before(function() {
      console.log('  In Workflow2');
    });

    it("should have an assertion", function() {
      expect(2).to.equal(2)
    });

    it("should have another assertion", function() {
      expect(10).to.not.equal(20);
    });
  });
}

var Manifest = {};

Manifest.run = function() {
  Workflow1.run({blah: "blah"});
  debugger;
  Workflow2.run();
  debugger;
};

Manifest.run();
```

```
$ mocha example.js


  Example workflow1
  In Workflow1 with { blah: 'blah' }
    ✓ should have an assertion
    ✓ should have another assertion

  Example workflow2
  In Workflow2
    ✓ should have an assertion
    ✓ should have another assertion


  4 passing (15ms)
```

**Comment by boneskull** [comment]
@carollgt91 it fails in the dummy example because you need to call `run()` somewhere. please try again and see if it's workable?

**Comment by webxl** [comment]
This gets a vote from me as well. At first I thought it had something to do with nested it calls, but now I think the issue is with nested promises. The presence of assertions also seems to affect execution.

**Comment by gig177** [comment]
+1. I think this issue very coupled with #1793 issue.
