### ISSUE TITLE
Is it possible to describe a 'skip'?

### ISSUE THREAD

**Issue by another-dave** [mochajs/mocha#1649]
Similar to [JUnit's Ignore annotation](http://junit.sourceforge.net/javadoc/org/junit/Ignore.html), it would be nice to be able to describe a skip, e.g. by overloading to allow for an extra descriptive piece of text that could be output with the test results.

Happy to look into this, but as per contrib guidelines said I'd raise it for discussion first.

Something like:

```
it.skip('should display results', function(){
    //…
})
```

becoming

```
it.skip('skipped until bug-fix 123 implemented', 'should display results', function() {
    //…
})
```

Which could output something along the lines of:

>    - should display results (skipped until bug-fix 123 implemented)
>
>1 pending

Best
Dave

**Comment by dasilvacontin** [comment]
Hmm, I'd personally do directly:
```
it.skip(''should display results (skipped until bug-fix 123 implemented)', function() {
    //…
})
```
I guess I'm missing the point of this sugar.

**Comment by another-dave** [comment]
Think the additional field gives more options around code analysis (e.g. making sure that a reason is given when skip is used), though I guess it's a minor one alright.

**Comment by boneskull** [comment]
@another-dave Likewise using some sort of convention would make this more easily digested:

```js
it.skip('skipReason(bug 123 needs fixing) should display results', function() {
  // ..
});
```

Furthermore, reporters would need to consume this information and output it in some way.

I can't see adding this unless it's shown there is no reasonable workaround for a use case.

Thanks!

**Comment by another-dave** [comment]
NP, just a thought :)

Cheers!
D
