### ISSUE TITLE
"Script error" regression

### ISSUE THREAD

**Issue by tj** [mochajs/mocha#165]
cc @c4milo 

possibly due to the new IE stuff, taking a look

**Comment by lzrski** [comment]
I think it's related to Same Origin Policy.

I was running my tests in Chromium version 39.0.2171.65 Ubuntu 14.04 64-bit. Everything was served from localhost (by simple express server) over HTTP, except Chai which was served from CDN. I had same symptoms. Accessing Chai via HTTP or HTTPS made no difference. Downloading it and serving from localhost server fixed the problem.

**Comment by nilbus** [comment]
Perhaps that applies differently to `http://localhost` and `file://`.

**Comment by lzrski** [comment]
I'm not an expert, but it seems that sometimes browsers treat two files loaded via `file:` scheme as having different origin. For Firefox it's discussed here: [Same-origin policy for file: URIs](https://developer.mozilla.org/en-US/docs/Same-origin_policy_for_file:_URIs). There's also this [StackOverflow answer](http://stackoverflow.com/a/12587751/1151982) which quotes HTML5 spec, but provided link is broken, so I'm not sure if it's up to date.

@nilbus It's very easy to serve local files with *ad hoc* server though. Check out this [Big list of http static server one-liners](https://gist.github.com/willurd/5720255). That might be the easiest workaround for you.
