### ISSUE TITLE
Async tests without calling 'done' always displayed as succeeded in UI

### ISSUE THREAD

**Issue by pke** [mochajs/mocha#1664]
`return WinJS.Promise.timeout(1, promise).should.eventually.be.rejectedWith(/Timeout reached/)` does print the failure in the console but in the UI the test is displayed as being successful.

`WinJS.Promise.timeout(1, promise).should.eventually.be.rejectedWith(/Timeout reached/).and.notify(done)` works as expected and displays the test in the UI als failed.

**Comment by boneskull** [comment]
need more info/code

**Comment by danielstjules** [comment]
@pke Does WinJS use chai-as-promised? What is the type of `WinJS.Promise.timeout(1, promise).should.eventually.be.rejectedWith(/Timeout reached/)`? Is it `thenable`?

**Comment by pke** [comment]
Yes @danielstjules I have used chai-as-promised.
I have uploaded my test project here http://1drv.ms/1HKnLUo

**Comment by danielstjules** [comment]
I don't have WinJS setup, so this might be quicker for you. If not, I'll set it up this evening. In any case, can you give this a shot:

``` javascript
P.timeout = function (t, promise) {
  var timeoutPromise = oldTimeout(t);
  if (promise) {
    /*timeoutPromise.then(function () {
      promise.timedout = true;
      promise.cancel();
    });
    return promise.then(function (result) {
      timeoutPromise.cancel();
      return result;
    }, function (error) {
      timeoutPromise.cancel();
      if (error.name === "Canceled" && promise.timedout) error = new WinJS.ErrorFromName("Timeout", "Timeout reached after " + t + "ms");
      return WinJS.Promise.wrapError(error);
    });*/
    return new WinJS.Promise(function (c, e, p) {
      promise.then(c,e,p);
      timeoutPromise.then(function () {
        e(new WinJS.ErrorFromName("Timeout", "Timeout reached after " + t + "ms"));
      });
    });
  } else {
    return timeoutPromise;
  }
};

// ------------------------------
// Replace with
// ------------------------------

P.timeout = function(t, promise) {
  return new WinJS.Promise(function(resolve, reject) {
    console.log('timeout promise running');
    reject(new Error('error from timeout promise'));
  });
};
```

Does the `timeout promise running` get printed to the console? And does the test correctly fail?

**Comment by pke** [comment]
Yes it fails with "expected promise to be rejected with an error matching /Timeout reached/ but got 'error from timeout promise'
I see `timeout promise running` printed 2 times in the console.

**Comment by danielstjules** [comment]
So it's not a problem with mocha then, but your custom P.timeout in the example. That should help you debug?

**Comment by pke** [comment]
I am still not sure. The P.timeout returns a proper, thenable Promise. The mocha test works correct when using `.and.notify(done);` but not without. What could that mean?
Even your code does not work without `and.notify(done)`. The message you expected is printed in the console, but mocha reports the test has timed out after 2000msec.
Maybe its a chai-as-promised problem?

**Comment by danielstjules** [comment]
Using:
``` javascript
P.timeout = function(t, promise) {
  return new WinJS.Promise(function(resolve, reject) {
    console.log('timeout promise running');
    reject(new Error('error from timeout promise'));
  });
};
```
does not yield an error with `return WinJS.Promise.timeout(1, promise).should.eventually.be.rejectedWith(/Timeout reached/)`? It requires `and.notify(done)`?

I'll setup winjs tonight.

**Comment by pke** [comment]
It might be even possible to use the WinJS (tryout site)[http://try.buildwinjs.com/#play]
