### ISSUE TITLE
Timing out a finished test makes no sense

### ISSUE THREAD

**Issue by brian-mann** [mochajs/mocha#1667]
Specifically this line: https://github.com/mochajs/mocha/blob/master/lib/runnable.js#L221

Why would this ever make sense to check?

If the test is going to time out, it already has had a setTimeout function which fails the test.  If the test hasn't failed, why would you then check to see if it has timed out?  It hasn't timed out!

In previous versions of Mocha this wasn't a problem, but now this one line creates havoc in the following situations:

**You use debugger**
Going into the debugger is basically 100% guaranteed timeout.  The duration of the test will ALWAYS exceed its start time.  This wasn't a problem before, because debugger would halt javascript execution and the real setTimeout function wouldn't be "counted down".  This was ideal.  Now its untenable.

**You change timeouts within a test**
I have a situation where I am modifying a runnable's timeout dynamically.  One piece of code may extend it to 30s, another may reduce it down to under 2 secs.  The problem with this is after each command successfully runs I reset the timeout back to the original.  But by the time the test passes the test will always fail at this last step because its duration will always exceed the current timeout value.

In what situation could the test ever have timed out without the actual timeout setTimeout function running?

**Comment by boneskull** [comment]
if you are using a debugger you will want to disable timeouts or set them very high. 

why do you need to dynamically modify timeouts of runnables?

**Comment by brian-mann** [comment]
I find having to disable timeouts or change them on a one off basis to utilize `debugger` is ridiculous.

I concede that my use case for needing to dynamically modify timeouts is extremely edge-case and rare, though very practical for my application: www.cypress.io

However, this still doesn't really answer my question - **why** does it **ever** make sense to throw a timeout on a passing test?

If the test did indeed time out, its `timer` setTimeout would have caused that, I see no need for a double check here.  The code is basically duplicated between the `resetTimeout` function and the `done` callback.

In my situation I've overridden runnable `resetTimeout` and disabled mocha's timeouts completely to solve my issue.  Just wish I didn't have to hack so much to get this to work.

**Comment by boneskull** [comment]
> I find having to disable timeouts or change them on a one off basis to utilize debugger is ridiculous.

I agree this is inconvenient.  I'm curious how you'd propose solving the issue?

> However, this still doesn't really answer my question - why does it ever make sense to throw a timeout on a passing test?

It doesn't.  This sounds like a bug--a reproducible example would be helpful.
