### ISSUE TITLE
consider adding mocha.opts parsing to the API

### ISSUE THREAD

**Issue by thom-nic** [mochajs/mocha#1668]
Some folks using `gulp-mocha` would like to be able to re-use `mocha.opts` when invoking mocha via gulp.  Looks like since parsing is done in `bin/options.js`, not only is it not part of Mocha's accessible API, but that function modifies `process.argv` rather than returning an options hash.

Discussion at https://github.com/sindresorhus/gulp-mocha/issues/44

I imagine the case would be the same for other builders like grunt and broccoli.

**Comment by boneskull** [comment]
any discussion should probably be in #1457.  I wish GitHub had subtickets.
