### ISSUE TITLE
Exceptions outside tests are silent when using --delay flag 

### ISSUE THREAD

**Issue by BrennanRoberts** [mochajs/mocha#1669]
[Here's a sample.](https://gist.github.com/BrennanRoberts/f71a815cbeb5e927635d)

When using the "--delay" flag, exceptions outside of a test are silent. For context, I'm using delay in order to load my test files with requirejs, which the timeout is meant to simulate.

When running without --delay (and removing the timeout), the exception is not silent, so I'm assuming this is unintentional.

**Comment by boneskull** [comment]
@BrennanRoberts nice catch.  any ideas about the best way to solve this?  since `--delay` is not available in a browser context I imagine it's probably safe to play with domains here.

**Comment by danielstjules** [comment]
Found an even simpler reproduce case:
``` javascript
setTimeout(function() {
  throw new Error('oops');
  it('test', function() {});
  run();
}, 100);
```
