### ISSUE TITLE
Should `if (err) throw err` be `if (err) throw done(err)`?

### ISSUE THREAD

**Issue by freewind** [mochajs/mocha#1670]
http://mochajs.org/#asynchronous-code

```
Asynchronous code

Testing asynchronous code with Mocha could not be simpler! Simply invoke the callback when your test is complete. By adding a callback (usually named done) to it() Mocha will know that it should wait for completion.

describe('User', function(){
  describe('#save()', function(){
    it('should save without error', function(done){
      var user = new User('Luna');
      user.save(function(err){
        if (err) throw err;
        done();
      });
    })
  })
})
```

Just thinking `if (err) throw err;` should be `if (err) throw done(err);`, right?

(PS: Can't find the correct file to create a pull request)

**Comment by dasilvacontin** [comment]
It should work either way: you can let Mocha catch the error that you are throwing asynchronously, or you can pass it directly to the `done` callback.

**Comment by freewind** [comment]
Cool, great to know that

**Comment by dasilvacontin** [comment]
No worries, let us know if you bump into any issue. :)
