### ISSUE TITLE
How to return value in async testing via `done`?

### ISSUE THREAD

**Issue by chenweiyj** [mochajs/mocha#1671]
I am testing my apis by using mocha. Since calling to my apis needs authorization, I call the authorization api to get the access token in the `beforeEach` hook. I wrap the `doFakeAuth` function in the `utils.js` file and export it, which is denoted as follows.

```
exports.doFakeAuth = function (done) {
  var route = '/v1/auth/weibo';
  var body = {
    weibo_uid: 'test_weibo_uid_full_data',
    avatarurl: 'http://fake_weibo',
    birth_year: 1995,
    birth_month: 5,
    birth_day: 8,
    gender: 2,
    nickname: 'cw',
    signature: 'i will win'
  }

  request(url)
    .post(route)
    .send(body)
    .expect('Content-Type', /json/)
    .expect(200)
    .end(function (err, res) {
      if (err) throw err;
      //
      res.body.should.have.property('user');
      res.body.should.have.property('token');
      res.body.user.should.have.length(24);
      return res.body.token;
      done();
    });
}
```

However, I cannot get the `res.body.token` in the async call. I also tried 
```
done(res.body.token);
```

But it said `Error: done() invoked with non-Error: <token detail>`. 

So how can I get the token in the caller.

**Comment by boneskull** [comment]
>
  ```js
  return res.body.token;
  done();
  ````

The above is a basic misunderstanding of programming.  Once you `return` from a function, any subsequent lines within the function are unreachable.

I'm not sure really what I'm looking at here.  Is `utils.js` code under test, a fixture, or what?  If you need to call some async function and get its return value:

```js
describe('foo', function() {
  var response;
  beforeEach(function(done) {
    someAsyncCall(function(err, data) {
      response = data;
      done();
    });
  });
  it('should blah blah', function() {
    // use response here
  });
});
```

**Comment by schatekar** [comment]
@boneskull How would you do this if `beforeEach` is defined in a helper file to be used across multiple specs?

**Comment by boneskull** [comment]
@schatekar do what..?

**Comment by schatekar** [comment]
If I have defined `beforeEach` in a separate file then how do I return value of `response` variable set inside `beforeEach` back to my specs?
