### ISSUE TITLE
Hijacking and silencing the console with beforeEach / afterEach

### ISSUE THREAD

**Issue by maximilianschmitt** [mochajs/mocha#1672]
For some tests I find myself needing to hijack the console (or stdout) and silence it. It would be ideal if I could do this in the `beforeEach` / `afterEach` events but that doesn't really work, see the test case below:

```js
'use strict';
const expect = require('chai').expect;

describe('hijacking the console with beforeEach / afterEach', function() {
  const consoleLog = console.log;
  
  beforeEach(function() {
    // hijack
    console.log = function() {};
  });

  afterEach(function() {
    // restore
    console.log = consoleLog;
  });

  it('doesn\'t work well', function() {
    console.log('this doesn\'t get logged (as expected), but the test case won\'t either');
    expect(true).to.equal(true);
  });
});

describe('hijacking the console per test case', function() {
  const consoleLog = console.log;
  
  it('works fine but is repetitive', function() {
    // hijack
    console.log = function() {};

    console.log('this doesn\'t get logged (as expected), but the test case will');

    // restore
    console.log = consoleLog;

    expect(true).to.equal(true);
  });
});
```

Check out the missing logs for the first test case:

```
$ mocha


  hijacking the console with beforeEach / afterEach

  hijacking the console per test case
    ✓ works fine but is repetitive


  2 passing (9ms)
```

It would be kind of nice if it was possible to hijack the console with `beforeEach` / `afterEach`. I wonder how others approach this, maybe there is a better pattern that I don't know of?

**Comment by danielstjules** [comment]
Related to https://github.com/mochajs/mocha/issues/1582

**Comment by boneskull** [comment]
```js

describe('hijacking the console per test case', function() {
  const consoleLog = console.log;
  beforeEach(function() {
    console.log = function() {};
  });

  it('works fine but is repetitive', function() {
    console.log('this doesn\'t get logged (as expected), but the test case will');
    expect(true).to.equal(true);
  });

  afterEach(function() {
    console.log = consoleLog;
  });
});

```

**Comment by boneskull** [comment]
oops, that's exactly what you wrote in the original post

**Comment by boneskull** [comment]
anyway, not currently possible.  you may be better served attempting to stub stdout

**Comment by fruch** [comment]
any news on getting this type of things solved ? it's very annying we can't easily control the output without messing with the spec outptut...

**Comment by ORESoftware** [comment]
probably better to monkey patch process.stdout.write, like so:

```js
const write = process.stdout.write;
process.stdout.write = function(){
   // send stdout to a log file instead of the console
};
```

**Comment by fruch** [comment]
I've tried that, but it messes up the output of the spec when used in after/before, doing that inside every test can get very old very fast. Me coming from the python world, and in py.test this option of holding the output as a default.

**Comment by ORESoftware** [comment]
you can use a external before hook outside of the scope of each of your tests

you can put the monkey patching in there?
