### ISSUE TITLE
XUnit reporter should use process.stdout if available... fallback to console.log

### ISSUE THREAD

**Issue by alemangui** [mochajs/mocha#1674]
Hello

I'm running Mocha on PhantomJS using https://github.com/metaskills/mocha-phantomjs This means Mocha is not run in Node and thus has no access to fs.

Mocha-PhantomJS provides the option of dumping the reporter output to a file by redirecting process.stdout.write. Unfortunately, I'm having issues with the xunit reporter since it is using console.log.

I understand this is to maintain compatibility with browsers, but would it be desirable to check the existence of process.stdout and call it if available?

It would be a trivial PR... I would gladly prepare it but I would like to ask for your insight first:
```javascript
/**
 * Write out the given line
 */
XUnit.prototype.write = function(line) {
    if (this.fileStream) { 
        // Node JS environment
        this.fileStream.write(line + '\n');
    } else if (process && process.stdout) {
        // Browser with process.stdout (as in mocha-phantomjs)
        process.stdout.write(line + '\n');
    } else {
        // Browser
        console.log(line);
    }
};
```

**Comment by boneskull** [comment]
`console.log` calls `process.stdout.write` last time I checked.  I don't understand the problem.  Is this a `mocha-phantomjs` issue?

**Comment by alemangui** [comment]
The problem is basically that Mocha-Phantom (and potentially other tools/scripts) can redirect the process.stdout to a different output (i.e., to have the reporter output saved into a file). Having some reporters using console.log removes this possibility.

**Comment by danielstjules** [comment]
@alemangui  console.log uses process.stdout.write internally. Here's an example:

``` javascript
var oldWrite = process.stdout.write;
var counter = 0;
var output = '';

process.stdout.write = function(str) {
  counter++;
  output += counter + '. ' + str;
};

// Does not output foo/bar
console.log('foo');
console.log('bar');

// Restore and print modified output
process.stdout.write = oldWrite;
console.log(output);
```

```
$ node example.js
1. foo
2. bar
```

So if you redirect process.stdout to a different output, console.log will use it as well.

**Comment by alemangui** [comment]
Thanks for your clarification @danielstjules. console.log indeed uses process.stdout under a Node environment. 

The problem I'm having with Mocha-Phantomjs - if I understand correctly - comes from the fact there is a differentiation between console.log calls and process.stdout calls in order to tell apart the reporter output from the other console.log calls (Mocha-Phantomjs is after all mocha running in a browser environment).

I'm guessing https://github.com/metaskills/mocha-phantomjs/issues/161 and https://github.com/metaskills/mocha-phantomjs/issues/114 (both on mocha-phantomjs side) are related to what I'm saying.

At this point I'm not sure where the fix should be though.

**Comment by jbnicolai** [comment]
I'd be happy with a node/browser compatible solution for this, but otherwise we'll keep it as is.
