### ISSUE TITLE
Impossible to only run a dynamically generated test

### ISSUE THREAD

**Issue by ZECTBynmo** [mochajs/mocha#1676]
I'm working inside of a very large mocha test suite with hundreds of tests, so having the ability to run a single test using .only is extremely useful during test development.

However, as far as I can tell, there's no way to mark a dynamically generated test suite as being the only one that runs. I'd really like to write some dynamically generated tests, and it's hard to run all the tests every time. Am I missing something? Is there a pattern you might suggest to get around this issue?

I expected there might be something like:
```
mocha = new Mocha
suite = Mocha.Suite.create mocha.suite, config.name
suite.only()
mocha.run()
```

I have stumbled across this pattern, but it only runs the first of my dynamically generated tests
```
describe.only config.name, ->
  it 'should run tests', ->
     mocha = new Mocha
     ...stuff...
     mocha.run()
```

**Comment by boneskull** [comment]
I don't understand why `only` doesn't work.  please supply more code

**Comment by ORESoftware** [comment]
IMO, if you have 6 describe.only blocks, dynamically generated or not, all 6 should run not just the first one.

Otherwise, if you want only the first registered describe.only to be run, then Mocha should throw an error if there is more than one describe.only.

Pick one.

**Comment by Munter** [comment]
One year and no feedback. For future reference, use --grep to filter out relevant tests from the command line

**Comment by ScottFreeCode** [comment]
Also, for the record, multiple `only` (including on suites) has already been made well-defined in 3.x: https://mochajs.org/#exclusive-tests

**Comment by ORESoftware** [comment]
--grep  will be difficult to do for tests with dynamically generated names?
