### ISSUE TITLE
How to Inject an Object/Variable into Mocha?

### ISSUE THREAD

**Issue by benmarten** [mochajs/mocha#1679]
I am working on a project where we need to start mocha from within the node application:

e.g.
	var browser = new myBrowser();
	var mocha = new Mocha({});
	mocha.addFile('./' + file);
	mocha.run();

Since we do browser automation, we need the browser handle within the it(...) function. Hence the question is how we can make the browser object available within each it() block?

**Comment by boneskull** [comment]
what's the "browser object"?

**Comment by benmarten** [comment]
it's e.g. a selenium web driver... anyway i have solved it differently, thanks
