### ISSUE TITLE
mocha does not allow for return values from test

### ISSUE THREAD

**Issue by milanbella** [mochajs/mocha#1684]
done() call does not allow any other return parameter except `undefined' (i.e. no parameter at all) or Error(). Following test results in exception:

    it('pass', function (done) {
        done('test finished ok');
    });

The only way to pass the return value from test is to call done(null, val):

   it('pass', function (done) {
        done(null, 'test finished ok');
    });

But then such return value is not available in custom reporter.

**Comment by dasilvacontin** [comment]
Maybe because that's the purpose of `done`. What's your use-case? I believe this has been discussed in other issues.

**Comment by boneskull** [comment]
if you need to set metadata, you can stuff it in `this`.  most of the events emitted to the reporters will pass the test instance, so you'll have access to whatever is in `this`

**Comment by dasilvacontin** [comment]
I take note of your answer, @boneskull. :)

**Comment by boneskull** [comment]
please don't take my response as a "best practice" :D

**Comment by dasilvacontin** [comment]
I take it as a "quick hack that works and saves your day" :D
