### ISSUE TITLE
Not supporting latest V8 flags

### ISSUE THREAD

**Issue by jclem** [mochajs/mocha#1688]
Mocha is not passing the latest V8 flags, including for example "--harmony_computed_property_names".

**Comment by danielstjules** [comment]
Related, but still missing: https://github.com/mochajs/mocha/pull/1680

**Comment by jclem** [comment]
There's got to be a better way to support these than requiring that they be committed to the mocha source.

**Comment by danielstjules** [comment]
I think we need a better way of presenting these flags, rather than showing them all as part of `--help`.. or at least having them visually grouped differently

**Comment by danielstjules** [comment]
Agreed

**Comment by jclem** [comment]
Well part of the problem is that mocha just ignores them. Took me a while to figure out that my tests were failing because mocha just happily ignored a flag I passed without complaining.

**Comment by boneskull** [comment]
Mocha should stop trying to do this.  We should have one executable, and if you need flags, execute `mocha` with the `node` executable. 

Meanwhile see if `node --<flags> _mocha` works

**Comment by dasilvacontin** [comment]
It's quite annoying having to manually 'whitelist' these flags in mocha.

**Comment by jclem** [comment]
Currently going with @boneskull's suggestion.

**Comment by boneskull** [comment]
Going to close this, and probably any similar issue following

**Comment by jclem** [comment]
@boneskull What's the actual resolution here, though? Another question—out of the 300-odd V8 flags, how are the 20 or so in the "pre-binary" actually chosen?

**Comment by boneskull** [comment]
yup
