### ISSUE TITLE
inner 'before' runs before outer 'beforeEach'

### ISSUE THREAD

**Issue by bblack** [mochajs/mocha#1694]
given e.g.
```
describe('foo', function(){
  beforeEach('1', function(){})
  describe('bar', function(){
    before('2', function(){})
})
```
'2' will run before '1'. However, changing '2' to a 'beforeEach' will cause 2 to run after 1.

**Comment by boneskull** [comment]
intended behavior

**Comment by bblack** [comment]
can you link me to documentation or discussion indicating such?

**Comment by ramiel** [comment]
Why should be this an intended behavior?
Is not documented and led to confusion.
Then all the use cases I can think of need the opposite order.
Can you make an example of the need to have this behavior?
