### ISSUE TITLE
Error when using compilers option

### ISSUE THREAD

**Issue by skiwi2** [mochajs/mocha#1695]
My technology stack is ReactJS + JSX + Mocha, hence I need to compile the .js files beforehand, however there seems to be some error as I get this output:

> C:\Users\Frank\Dropbox\PycharmProjects\DLL>npm test

> DLL@0.0.0 test C:\Users\Frank\Dropbox\PycharmProjects\DLL
> mocha --compilers js:./DLL_application/frontend/tests/compiler.js ./DLL_application/frontend/tests --recursive

> C:\Users\Frank\Dropbox\PycharmProjects\DLL\node_modules\mocha\lib\interfaces\bdd.js:32
    var common = require('./common')(suites, context);
                                    ^
TypeError: object is not a function
    at Suite.<anonymous> (C:\Users\Frank\Dropbox\PycharmProjects\DLL\node_modules\mocha\lib\interfaces\bdd.js:32:37)
    at Suite.emit (events.js:129:20)
    at C:\Users\Frank\Dropbox\PycharmProjects\DLL\node_modules\mocha\lib\mocha.js:191:11
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Users\Frank\Dropbox\PycharmProjects\DLL\node_modules\mocha\lib\mocha.js:189:14)
    at Mocha.run (C:\Users\Frank\Dropbox\PycharmProjects\DLL\node_modules\mocha\lib\mocha.js:422:31)
    at Object.<anonymous> (C:\Users\Frank\Dropbox\PycharmProjects\DLL\node_modules\mocha\bin\_mocha:398:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Test failed.  See above for more details.

Using the following `package.json`:

```
{
  "name": "DLL",
  "version": "0.0.0",
  "main": "server.js",
  "dependencies": {
    "classnames": "^2.1.1",
    "react-bootstrap": "^0.21.2",
    "react-router-bootstrap": "^0.13.0",
    "jquery": "^2.1.4"
  },
  "devDependencies": {
    "jsx-loader": "^0.13.2",
    "react": "^0.13.2",
    "react-hot-loader": "^1.2.6",
    "react-router": "^0.13.3",
    "webpack-dev-server": "^1.8.2",
    "jsdom": "^3.1.2",
    "mocha": "^2.2.4",
    "react-tools": "^0.13.2",
    "sinon": "^1.14.1"
  },
  "scripts": {
    "dev": "webpack-dev-server --config webpack-config.js --hot --progress --colors --port 3001 --inline",
    "build": "webpack --config webpack-config.js --progress --profile --colors",
    "test": "node_modules/.bin/mocha --compilers js:./DLL_application/frontend/tests/compiler.js ./DLL_application/frontend/tests --recursive"
  },
  "author": "",
  "license": "ISC"
}
```

And the following `setup.js`:

```
/**
 * Created by Frank van Heeswijk on 12-5-2015.
 */

var jsdom = require('jsdom');

global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
global.window = document.parentWindow;
global.$ = require('jquery')(window);
```

And this `compiler.js`:

```
/**
 * Created by Frank van Heeswijk on 12-5-2015.
 */

var fs = require('fs');
var ReactTools = require('react-tools');

var originalJS = require.extensions['.js'];

require.extensions['.js'] = function (module, filename) {
    if (filename.indexOf("node_modules") > -1) {
        return (originalJS || require.extensions['.js'](module, filename));
    }

    console.log("compiling " + filename);

    var content = fs.readFileSync(filename, 'utf8');
    var compiled = ReactTools.transform(content, {harmony: true});

    return module._compile(compiled, filename);
};
```

I really have no clue what is going wrong, can anyone help me on this?

**Comment by skiwi2** [comment]
I don't even know why the files in node_modules are attempted to be compiled, is there no way to turn that off?

**Comment by boneskull** [comment]
well, you're adding a compiler for all `.js` files, so naturally all `.js` files would get compiled.  

I don't know squat about React, but if you have a `.js` file which isn't actually vanilla JavaScript, you should use a different extension.  

This isn't a Mocha issue, so I'm going to close it.
