### ISSUE TITLE
Make stack-traces in node_modules configurable 

### ISSUE THREAD

**Issue by raadad** [mochajs/mocha#1696]
As of Mocha 2.2.2   558191d@a8mfeat(runner/stack-trace): solve issue #545 + tes  -  lines 6358-63560

Errors that occur inside node_modules are not shown, this may not be ideal for people who are testing code that is running with node_modules or running a full stack test suite as the stack traces do not show.

Let me know your thoughts, i'm happy to PR a way to make this configurable.

**Comment by twada** [comment]
@raadad You can use `--full-trace` option to display full stack traces.

(Also found that [Mocha site](http://mochajs.org/) doesn't have documents for `--full-trace` option. It's another problem.)

**Comment by raadad** [comment]
I have confirmed this to be functioning, thanks for the quick response
