### ISSUE TITLE
missing possibility customize error list output

### ISSUE THREAD

**Issue by jkryl** [mochajs/mocha#1703]
At the end of running tests is printed a short summary (passed, failed, pending) and a list of errors numbered from 1 to n. The list of errors is implemented by lib/reporters/base.js:list() , which loops through array of failed tests and prints "something" based on err.message and err.stack attributes. We find this insufficient as there are types of errors where we would like to print more information about them. Customizing this output proved to be difficult. It requires overriding the list method and to large extent duplicating the code from it.

What I would like is a new public "listFailure" method in base reporter which would be called from list() method and users could redefine this method if they required a special output. In my particular case when I'm happy with the standard output and just need to add some extra info, I would redefine the method to call the original method plus print extra info if error is instance of particular class.

I can submit a pull request to make this happen unless there is a better way how to accomplish the same. Opinions?

**Comment by boneskull** [comment]
this would be more easily accomplished after #1457, whenever that is..  I think this is good to take into consideration though.
