### ISSUE TITLE
runner should emit 'skip' event when skipping a test

### ISSUE THREAD

**Issue by avetisk** [mochajs/mocha#1705]
Would allow reporters to show skipped tests, etc.

**Comment by dasilvacontin** [comment]
Hi @avetisk! `.skip()` just marks the test/runnable as `pending`, so you should listen for the `'pending'` event instead.

```js
var mocha = require('mocha')
var Runnable = mocha.Runnable
var Suite = mocha.Suite
var Runner = mocha.Runner

var test = new Runnable('testerino', function () {
    console.log('very test')
})
test.pending = true

var suite = new Suite()
suite.addTest(test)

var runner = new Runner(suite)
runner.on('pending', function (pending) {
    console.log('pending/skipped test:', pending)
})
runner.run()
```

outputs:

```js
pending/skipped test: {
  "title": "testerino",
  "async": 0,
  "sync": true,
  "timedOut": false,
  "pending": true,
  "parent": "#<Suite>",
  "ctx": "#<Context>"
}
```

Otherwise, if you meant being able to differentiate between `pending` tests and `skipped` tests, let us know. Thanks!

**Comment by dasilvacontin** [comment]
Currently, you can tell if a test has been `skip`ed during its execution if you get a `test` event for it followed by a `pending` one.

**Comment by avetisk** [comment]
I don't think its a good way to handle it, i.e it's a pain in the ass compared to simply listening to a `skip` event.

Moreover, it complies with other events.

You should really emit a `skip` event.

**Comment by boneskull** [comment]
@avetisk You're welcome to send a PR.
