### ISSUE TITLE
Setting global timeout/slow via code?

### ISSUE THREAD

**Issue by tivac** [mochajs/mocha#1711]
Is there a way to set a global timeout/slow value from code? I want to be able to do the same thing that `--timeout` and `--slow` do, but via code running via `npm test`.

I'm setting up server stuff in a global `before()/after()` that all test files will require and was hoping to specify timeout stuff there. The tests are going to be spread out into a bunch of different projects so I can't use `mocha.opts` to set these values, and requiring multiple people to remember to set the CLI values is a no-go as well. I tried calling `this.timeout(...)` and `this.slow(...)` from the global `before()` but that just set those values for the `before()` itself, not all the other tests. 

Is there a way to do what I want? I haven't been able to find a reference to the mocha global or anything and digging through mocha's code hasn't really helped me narrow it down either.

**Comment by tivac** [comment]
I think I've got a workaround but it feels super-gross. I don't love it and it seems like there has to be a better way. 

This is untested on anything other than a trivial test suite.

```js
before(function(done) {
    var suite = this.test;

     while(suite.parent) {
        suite = suite.parent;
    }

    suite.timeout(15000);
    suite.slow(5000);

    ...

    done();
});
```

**Comment by tivac** [comment]
Thought I could just walk upwards from `this.test` in my `before()`, but it turns out that timeouts are only inherited from the root suite when they're added. By the time my code was running every test/suite had its own timeouts set and ignored the root values.

So it seems like I'll have to write code to walk every suite/test & call `.timeout()` on them to achieve what I want?

**Comment by danielstjules** [comment]
Have you looked into running mocha programmatically? https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically

When you create your instance of mocha, you can pass in a timeout: https://github.com/mochajs/mocha/blob/master/lib/mocha.js#L65

**Comment by tivac** [comment]
@danielstjules Yeah, but that means that if I want all the other useful mocha CLI features like `--grep` I have to support them my wrapper.

I've given up on this, mocha just doesn't expose the necessary APIs to achieve what I had hoped for so I'll solve it some other way.
