### ISSUE TITLE
site improvements

### ISSUE THREAD

**Issue by rstacruz** [mochajs/mocha#1714]
would you guys be interested in a contribution to make the `gh-pages` branch more maintainable? i can do a PR when i'm free.

- use github pages's jekyll to automatically format `index.md` as markdown.
- locally, use the `github-pages` gem to build the site instead of `markdown`.
- that means no more build step :)
- move *.js and *.css into assets/ to make the root directory cleaner.

there are also some questionable files in gh-pages that can probably be (re)moved:

 - http://mochajs.org/index.js (what's this?)
 - http://mochajs.org/_mocha.js (should've been gitignored but got committed)
 - http://mochajs.org/coverage.html (same)
 - http://mochajs.org/html5shiv.js (can be linked to cdn)
 - http://mochajs.org/jquery.js (same)
 - http://mochajs.org/normalize.min.css (same)
 - http://mochajs.org/head.html (can be moved to jekyll's _layouts)
 - http://mochajs.org/foot.html (same)

**Comment by rstacruz** [comment]
oops, just saw #1640 it seems you have this covered

**Comment by jbnicolai** [comment]
Yep, but you're more than welcome to contribute!

A big *yes* all the suggestions you list, it would make things a lot simpler and more consistent with other pages projects.

Moving dependencies to a cdn is fine with me as well, as long as google or some other reputable host is the provider ;)

**Comment by rstacruz** [comment]
done and done

**Comment by berkerpeksag** [comment]
This can be closed since https://github.com/mochajs/mocha/pull/1777 has merged into gh-pages.

**Comment by dasilvacontin** [comment]
Thanks for the reminder @berkerpeksag!
