### ISSUE TITLE
How can I pass custom data to my mocha test suite?

### ISSUE THREAD

**Issue by chevex** [mochajs/mocha#1715]
We are using [sauce labs](http://saucelabs.com) to do cross-platform/cross-browser testing.

You can find my test suite in this gist (to save room here): https://gist.github.com/chevex/397a5a18a1a386897b41

The problem is that the only way I could figure out how to pass custom data to the test suite is [via an environment variable](https://gist.github.com/chevex/397a5a18a1a386897b41#file-sauce-tests-js-L35). Because of this, when my gulp task tries to run the test suite against multiple targets in parallel, they all end up running against the same target since the loop is done iterating and `process.env.SAUCE_TARGET` is set to the final value before the first suite even runs.

```javascript
var gulp = require('gulp');
var gulpMocha = require('gulp-mocha');
var mergeStream = require('merge-stream');
gulp.task('sauce-tests', function () {
  var targets = ['chrome', 'firefox', 'internet explorer'];
  var streams = targets.map(function (target) {
    process.env.SAUCE_TARGET = target;
    return gulp.src('./test/sauce-tests.js', {read:false})
      .pipe(gulpMocha({ reporter: 'spec' });
  });
  return mergeStream.apply(null, streams);
});
```

The closure provided by `forEach` doesn't help because it's setting an essentially global value (`process.env.SAUCE_TARGET`) on each iteration.

Is there a better way to pass the `SAUCE_TARGET` to my test suite so that I can run multiple test suites in parallel with different target values?

I can get it working if I run all the tests synchronously but that takes far longer than I want it to. The only thing preventing parallelism is the fact that I can't pass encapsulated values to my mocha suite.

**Comment by boneskull** [comment]
@chevex Have you tried using the `require` option?  I am not sure if this is any *better*, but, have 3 files, one for each target:

```js
var targets = ['chrome', 'firefox', 'ie'];
var streams = targets.map(function (target) {    
    return gulp.src('./test/sauce-tests.js', {read:false})
      .pipe(gulpMocha({ reporter: 'spec', require: 'test/' + target + '.js') });
  });
```

`firefox.js`:
```js
global.TARGET = 'firefox';
```

`ie.js`:
```js
global.TARGET = 'internet explorer';
```

`chrome.js`:
```
global.TARGET = 'chrome';
```

Then:

```js

  before(function () {
    browser = wd.promiseChainRemote(
      'ondemand.saucelabs.com',
      80,
      process.env.SAUCE_USERNAME,
      process.env.SAUCE_ACCESS_KEY
    );
    browser.on('status', function (info) {
      console.log(info.cyan);
    });
    browser.on('command', function (eventType, command, response) {
      console.log(' > ' + eventType.cyan, command, (response || '').grey);
    });
    browser.on('http', function (meth, path, data) {
      console.log(' > ' + meth.magenta, path, (data || '').grey);
    });
    return browser.init({browserName: TARGET});
  });
```

The fixture module loaded by the `require` option doesn't raise errors or warnings about global leaks, so you are free to munge the global context w/ impunity.

**Comment by boneskull** [comment]
also you could probably stuff webdriver config in there too:

`chrome.js`:

```js
require('./wd-cfg`)
global.TARGET = 'chrome';
```

`wd-cfg.js`:
```js
global.WD_CFG = [     
  'ondemand.saucelabs.com',
  80,
  process.env.SAUCE_USERNAME,
  process.env.SAUCE_ACCESS_KEY
];
```

or just reduce boilerplate everywhere:

```js
global.browser = wd.promiseChainRemote.apply(wd, WD_CFG);
```
