### ISSUE TITLE
Travis isn't running

### ISSUE THREAD

**Issue by mc10** [mochajs/mocha#1716]
Seems like builds are completely absent... any idea why?

**Comment by danielstjules** [comment]
[Tweeted them](https://twitter.com/danielstjules/status/605758241012772865) with no response. I'll fire off an email.

**Comment by jbnicolai** [comment]
Odd. Everything seems to work again now though.

Thanks for reporting the issue, @mc10

**Comment by danielstjules** [comment]
@jbnicolai It's not fixed yet :(

![screen shot 2015-06-05 at 10 08 09 am](https://cloud.githubusercontent.com/assets/817212/8011118/cc4599b6-0b6a-11e5-928f-795907a09cb9.png)

![screen shot 2015-06-05 at 10 08 14 am](https://cloud.githubusercontent.com/assets/817212/8011120/ce63a33c-0b6a-11e5-960e-e6f77ea4e741.png)

**Comment by danielstjules** [comment]
https://github.com/travis-ci/travis-ci/issues/3996 seems relevant

**Comment by jbnicolai** [comment]
@danielstjules you're absolutely right. I was still receiving e-mails from failed/succesful builds, causing me to believe it was still working.

**Comment by boneskull** [comment]
when I click on our "unknown build status" icon I end up at *my fork*.

**Comment by boneskull** [comment]
over on the left, I choose `mochajs/mocha` and I see the build status.  cc @BanzaiMan

**Comment by danielstjules** [comment]
All fixed :)
