### ISSUE TITLE
Support mocha.opts in root

### ISSUE THREAD

**Issue by TheSavior** [mochajs/mocha#1721]
One of the benefits of mocha.opts is to be able to specify your flags there and be able to just call `mocha` from the command line. However, if your tests aren't in the `./tests` directory, mocha doesn't know where to look to find a mocha.opts file to find your tests. 

This problem would be solved if we were able to have mocha also look in the cwd of where mocha was run as well as up the tree until it found one (optional). Then I can specify in the mocha.opts file in my project root which folder my tests are in.

**Comment by jbnicolai** [comment]
I'd be fine with looking at the cwd or recursing up. Would you be interested in creating a PR introducing and documenting this?

**Comment by TheSavior** [comment]
I'm not going to be able to work on implementing this feature. Would love to have it though! :)

**Comment by boneskull** [comment]
I don't think building more features around `mocha.opts` is a good idea.

**Comment by TheSavior** [comment]
@boneskull Is there a conversation about deprecating mocha.opts somewhere? Do you have a better recommendation for this?

**Comment by boneskull** [comment]
@TheSavior I've mentioned it in several tickets.  I think it should be completely removed and replaced with an "rc" file, which would be either `.ini`, `.json` or `.yaml`.

If you just need to run Mocha with certain options, you can write a shell script, use a Makefile, use Grunt, use Gulp, etc., etc.

**Comment by boneskull** [comment]
hell you can stick it in the `scripts` property of `package.json` too

**Comment by boneskull** [comment]
gonna close this
