### ISSUE TITLE
Replace __proto__ throughout with setPrototypeOf shim

### ISSUE THREAD

**Issue by ndhoule** [mochajs/mocha#1728]
See https://github.com/mochajs/mocha/pull/1727#discussion_r31872646 for details

**Comment by jbnicolai** [comment]
:+1:

**Comment by boneskull** [comment]
I'm just gonna have to ask why we need to do this in the first place.  If we're subclassing, we can use `util.inherits()`.  If we're modifying the prototype of an existing object, well, we probably shouldn't do that.

**Comment by ndhoule** [comment]
`util.inherits` is fine in Node, but not in the browser, and Browserify's [`util` shim](https://github.com/defunctzombie/node-util) isn't ES3-compatible. We could come up with an ES3-compatible `util` shim, but at that point, unless we're relying on other functions from `util` we might as well just use a standalone lib.

**Comment by ndhoule** [comment]
(Sorry, partially my fault here for naming this issue poorly.)
