### ISSUE TITLE
Global leaks old firefox versions strange behavior

### ISSUE THREAD

**Issue by bgaillard** [mochajs/mocha#1733]
Hi, i'm currently doing lot of tests using Browserstack. 

Today I executed unit tests on the ~500 browsers Browserstack supports and encountered a strange `Error: global leak detected: navigator` which appears only with old Firefox versions (the error is encountered in Firefox 5.X and older). 

My settings are very simple ; 
```html
<script type="text/javascript">
    mocha.setup({ui: 'bdd'});
</script>

<script type="text/javascript" src="test/spec/my-tests.js"></script>

<script type="text/javascript">
    mocha.checkLeaks();
    mocha.run();
</script>
```

The first time I execute the tests the following error is reported : `Error: global leak detected: navigator`.

But if I refresh the tab it works without problem, what's strange is that if I add only `navigator.userAgent;` before `mocha.checkLeaks();` then it works. 

```html
...
<script type="text/javascript">
    navigator.userAgent;
    mocha.checkLeaks();
    mocha.run();
</script>
```

Do you know why I encounter this strange behavior ? Is it a bug in Mocha's leaks detection ? 

If somebody else encounters the same error the workaround is simply to change you Mocha settings. 

```javascript
mocha.setup(
    {
        ui: 'bdd',
        globals: ['navigator'] 
    }
);
```

Thanks, 

Baptiste

**Comment by boneskull** [comment]
if a new property appears in the global context between the `mocha.run()` and its completion, the global leak detection error will occur.  what FF is doing, I don't know, but that's why.  good to know for people using older FF versions though--thanks

**Comment by bgaillard** [comment]
Hi @boneskull, ok I understand now, makes sense. 

So old FF versions should have a buggy page initialization. 

Thanks for the explanations !
