### ISSUE TITLE
mixed use of promise and async APIs is hard to debug

### ISSUE THREAD

**Issue by metamatt** [mochajs/mocha#1734]
I was converting some Mocha tests I'd written to use promises instead of async callbacks, because the underlying API I was testing had changed to use promises.

Given a `testSomething` function that returns a promise, I had a test that looked something like

```
it('should', function(done) {
  testSomething().then(function(result) {
    // check result
    done();
  });
});
```

and I converted it to

```
it('should', function(done) {
  return testSomething();
});
```

can you spot the bug that cost me some head-scratching?

It's probably pretty obvious in the context of this bug report and with such simple test code, but with much more complicated test code, I investigated a bunch of dead ends (e.g. is my promise actually resolving) before I realized that the promise I was returning was being ignored entirely by Mocha because of the function signature of my `it` handler.

I suggest that Mocha should consider it a coding error to have an `it` handler accept a `done` argument and then return a promise.

**Comment by boneskull** [comment]
I'm not sure if this is necessary--perhaps a warning instead?  Otherwise this would be targeted to v3.0.0.

@mochajs/mocha anybody else have thoughts on this?

**Comment by metamatt** [comment]
A warning would be fine too. But silent failure is pretty darn unhelpful in the case that you make that mistake. (Sure, the existing failure says `Ensure the done() callback is being called in this test.` But that's not all that helpful if you're in a promise state of mind, because you've already told yourself that `done()` doesn't exist and what matters is resolving the promise. I'll note that even if you write a mocha test that doesn't accept the `done` argument but returns a promise that never resolves, you get exactly the same failure message. Maybe if that wasn't the case and the error message only mentioned `done()` when it was relevant, it would be safer to rely on the existing error message.)

What's the argument against this? Code weight? Backwards compatibility?

**Comment by boneskull** [comment]
Backwards compatibility will be an issue if we choose to throw an exception, so then it'd have to go into the next major.

I'm scratching my head trying to figure out if anything needs to be done here.  If you used `--async-only`, you'd have to call `done()`, regardless of whether or not you return a `Promise`, which would have avoided your original problem.

Another solution would be to simply ignore the presence of the `done` parameter if a `Promise` is returned.  

But again, I'd like input from others.

**Comment by metamatt** [comment]
> Another solution would be to simply ignore the presence of the done parameter if a Promise is returned.

I like that idea. Then there'd be no need to complain/warn/error, and the code would just do what I actually meant. (This boils down to reversing the order you check the handler return value vs handler.length, right now we check length and if it takes an argument we ignore the return value, instead we'd check the return value and if it's a Promise we wouldn't check length.) I too am curious how others feel about that.

**Comment by ndhoule** [comment]
In my promise-driven tests `Ensure the done() callback is being called in this test` has always told me exactly what I needed to know, but a more helpful message would be nice.

Could we just refactor runnable so that when we're about to throw a timeout error, we check to see if `this.fn` returned a promise and modify the error message to something like, `The done() callback was not called but a promise was returned. Ensure you're using one or the other` (better phrased than that)? That'd be more helpful without requiring a major.

If I were to pick my ideal default behavior, I'd want promise-returning tests that include a `done` callback to throw an error—seems like the most sane, least surprising behavior to me to save people from themselves:

```js
describe('whatever', function() {
  it('should be a better-written test', function(done) {
    return somePromiseYieldingFunction().then(function(data) {
      if (data === 100) return done(new Error('ono');
      done();
    });
  });
});
```

Obviously contrived but I could see it happening to people who are refactoring, not yet familiar with how Mocha handles async/promise test cases, etc.

**Comment by boneskull** [comment]
@metamatt after sitting on this for awhile, I think yes, we want to throw an error if you use both, like @ndhoule suggests.

but, that has to wait for `v3.0.0`.

further comments in #1735

**Comment by antkazam** [comment]
The error message is pretty clear. Please don't remove the ability to mix `done()` and `return somePromise`. Mocha still has issues with catching failed expectations with some usages of promises so we've had to chain an explicit `.then ... done()` onto some tests. I could remove the `return ` as well but that makes it two things to remember to do to work around that issue
