### ISSUE TITLE
Stack traces missing for >= 2.2.1, regression?

### ISSUE THREAD

**Issue by j13z** [mochajs/mocha#1736]
For some reason more recent versions of Mocha do not display stack traces anymore in some cases.

The code snippet below **stops working with all versions after 2.2.1** – the diff output is there but the stack trace is missing (2.2.1 shows both). Seems to be a regression.

Commenting out the `it` call gives me a stack trace again, but in this case it’s just a raw Node stack trace, without any test runner output (`… chai/lib/chai/assertion.js:107 throw new AssertionError(msg, { …`).

```javascript
// Test run with: `./node_modules/.bin/mocha dist/test/test.js`,  Node.js v0.12.4

// Works with mocha 2.2.1 (also tested with 2.0.0)
// Does not work with: 2.2.5, 2.2.4, 2.2.3

'use strict';

var chai = require('chai');       // v3.0.0
chai.config.includeStack = true;  // (makes no difference)
var expect = chai.expect;

describe('This test', function () {

	it('should work ', function () {    // <----

		expect(true).to.equal(false);
	});
});
```

**Comment by twada** [comment]
@j13z Mocha displays shorten stack traces since [PR 1564](https://github.com/mochajs/mocha/pull/1564) has landed (version 2.2.2).

You can use `--full-trace` option to display full stack traces.

**Comment by j13z** [comment]
@twada: Oh, I didn’t see the `--full-trace` option. That helps, thanks.

The problem I had was something different though, and seems to be caused by my node project’s directory structure and *not* Mocha itself. Sorry!

When I move my project root directly to `~/project` and reinstall all `node_modules` I get the expected result with the last line:

	at Context.<anonymous> (/source/test/test.js:52:17)

Before that, this last line got somehow lost … Guess node’s `require` algorithm sourced a “wrong” module somewhere down the directory tree.

**Could you please close this issue?** Sorry for the confusion.

**Comment by dasilvacontin** [comment]
No worries @j13z. This might help other people who didn't notice the new option either. :)
