### ISSUE TITLE
weird timeouts on Appveyor (Windows CI)

### ISSUE THREAD

**Issue by stevenvachon** [mochajs/mocha#1737]
Consistently on x86 io.js v1.x

And what's weirder is that with higher timeouts (like 10+ seconds), they pass consistently and no single test takes longer than 200ms. So, what is timing out?? https://ci.appveyor.com/project/stevenvachon/hidefile/build/12

**Comment by boneskull** [comment]
@stevenvachon I'm not sure anyone can help without more information and/or a reproducible case

**Comment by stevenvachon** [comment]
Is it possible that mocha is starting its timeout before the test begins, where Appveyor is taking a long time to run? How else could it consistently time out after 5000ms when the tests pass in 150ms, and no longer time out when max timeout is increased to 10000ms?

I don't know what other info to give you aside from diving into mocha and solving it myself.

**Comment by boneskull** [comment]
@stevenvachon I was thinking you would provide the problem test(s)

anyway, the code you would be interested in is probably [in `runnable.js`](https://github.com/mochajs/mocha/blob/master/lib/runnable.js).  `Runnable#timer` is the result of the `setTimeout()` call.  `Runnable#clearTimeout()` must be called before `Runnable#_timeout` milliseconds, or the test will timeout.

**Comment by stevenvachon** [comment]
It's not always the same test, but it was consistently this one for a while: https://github.com/stevenvachon/hidefile/blob/master/test/test.js#L432-L443

**Comment by boneskull** [comment]
this needs investigation, but @stevenvachon you might want to dig deeper on this one if you want to see movement sooner

**Comment by boneskull** [comment]
someone should review this

**Comment by boneskull** [comment]
actually, probably not.  please comment if you can provide a mcve, and we'll reopen
