### ISSUE TITLE
Mocha and jspm dependencies

### ISSUE THREAD

**Issue by yamsellem** [mochajs/mocha#1747]
By default, Mocha launches its tests with `node_modules` dependencies.
Is there way to use `jspm_packages` dependencies as well?

As an example, I wrote this setup.js file:
```
import { expect } from 'chai';
import $ from 'jquery';
global.expect = expect;
```

Launching `mocha --compilers js:babel/register --require ./test/setup.js` gives the error `Cannot find module 'jquery'` (chai is correctly imported, it was installed with `npm install --save-dev`).

The problem is that `jquery` has been installed with `jspm install jquery` and thus is only available in `jspm_packages`. In the client code, the `import from 'jquery'` works fine. But because mocha look for jquery in `node_modules`, it can't find it.

Is there a way to fix this?
Maybe using `System.config({..})
` somewhere will do the trick?

ps. [issue opened in jspm-cli](https://github.com/jspm/jspm-cli/issues/843)

**Comment by jbnicolai** [comment]
This seems to have been thoroughly answered in jspm/jspm-cli#843
