### ISSUE TITLE
Merge  co-mocha into mocha source tree so that mocha support for generator function testing in browser.

### ISSUE THREAD

**Issue by lygstate** [mochajs/mocha#1748]
https://github.com/blakeembrey/co-mocha

**Comment by danielstjules** [comment]
Previously discussed in https://github.com/mochajs/mocha/pull/1575

**Comment by blakeembrey** [comment]
As mentioned in the other thread, I think `mocha` should focus on common built-in flow controls and `async`/`await` would work in place of `co-mocha` some day (today, if you transpile). For browser support in `co-mocha`, I've released a patch that will work with `window.Mocha` in browsers.

**Comment by boneskull** [comment]
@blakeembrey thanks.
