### ISSUE TITLE
SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by Snorlock** [mochajs/mocha#1751]
Im trying to require a selfwritten script that use generators. But when I run my tests with mocha --reporter --harmony spec it cant seem to get past the require inn the files stage. Any suggestions how to get this work?

**Comment by ndhoule** [comment]
@Snorlock 

> mocha --reporter --harmony spec

You need to specify `spec` as an argument to `--reporter`; i.e. `mocha --harmony --reporter spec`

**Comment by jbnicolai** [comment]
Ah, yep there's the issue. Thanks @ndhoule
