### ISSUE TITLE
Bundle mocha for Nashorn

### ISSUE THREAD

**Issue by wejrowski** [mochajs/mocha#1756]
I need to have a single file with Mocha and all it's dependencies to use in a Nashorn environment. I can't have any requires in the final file as it stands for node, or as the browser mocha.js stands, since my environment will not allow for that. I've tried this with browserify and I'm getting a number of dependency errors. Currently I'm using Jasmine as it nicely stands as a single file, but there have been some issues with Jasmine lately so I thought I'd try Mocha.

Anyone have any pointers? Has anyone tried this? This is the gist of what I'm trying:

```javascript
// gulpfile
var browserify = require('browserify');
var sourceStream = require('vinyl-source-stream');
var gulp       = require('gulp');

gulp.task('build-mocha', function () {
    browserify('mocha-browserify-me.js')
        .bundle()
        .pipe(sourceStream('mymocha-2.2.5-bundle.js'))
        .pipe(gulp.dest('./'))
});
```

```javascript
//mocha-browserify-me.js
var Mocha = require('./lib/mocha.js');
```

**Comment by wejrowski** [comment]
I found the culprit: lib/reporters/index.js

```
exports.HTMLCov = require('./html-cov');
```

If I comment that out it's fine. I'm going to play around with this some more. There may be a fix somewhere in there or it may be nice to exclude some of these reporters for something like this.

**Comment by jbnicolai** [comment]
@brent the recent #1260 should have resolved this issue. Mocha does not assume it's running in a browser environment at all.

However, feel free to comment if you feel this issue is still relevant.
