### ISSUE TITLE
ReferenceError: before is not defined

### ISSUE THREAD

**Issue by elennaro** [mochajs/mocha#1762]
I'm trying to make some tests with Mocha for my Sails application. As described [here](http://sailsjs.org/#!/documentation/concepts/Testing).

#### test/mocha.opts:
````
--require test/bootstrap.test.js
````

#### test/bootstrap.test.js:

````
var Sails = require('sails'), sails;


before(function(done) {
  Sails.lift({
    // configuration for testing purposes
  }, function(err, server) {
    sails = server;
    if (err) return done(err);
    // here you can load fixtures, etc.
		console.log("Sails Loaded");
    done(err, sails);
  });
});

after(function(done) {
  // here you can clear fixtures, etc.
  sails.lower(done);
});
````

#### test/unit/model/User.test.js
````
/* global describe, User */

describe.only('UserModel', function() {

	describe('#find()', function() {
		it('should check find function', function(done) {
			User.find()
							.then(function(results) {
								console.log(results);
								done();
							})
							.catch(done);
		});
	});

});
`````

When I'm running tests, I see an error:
````
...
test\bootstrap.test.js:4
before(function(done) {
^
ReferenceError: before is not defined
...
````

**Comment by dasilvacontin** [comment]
You don't declare suites, tests or hooks on `--require`d files.

Instead, you could `require(...)` helpers in your spec/test files, and execute methods that define those hooks.

```js
require('./setup.js')()

describe(..., function () {
  it(...)
})
```

**Comment by dasilvacontin** [comment]
To clarify, `--require`d files are `require(...)`d _once_ by the CLI even before a `Mocha` instance is created, so they are useful for one time setup of globals and stuff.

e.g, you can execute `require('chai').should()` in your `--require`d file to avoid doing so in each of your test files.

**Comment by elennaro** [comment]
Thans for explanation  and for solution @dasilvacontin!
I solved it by simply running **test/bootstrap.test.js** through  **test/mocha.opts**:

````
test/bootstrap.test.js
````

**Comment by aventurella** [comment]
@elennaro what do you mean by:

> I solved it by simply running test/bootstrap.test.js through test/mocha.opts:

you just put that line as the first line in your **test/mocha.opts** ?

**Comment by elennaro** [comment]
Yes @aventurella 
Here's my mocha opts:
```
--silly
--full-trace
--timeout 20000
test/bootstrap.test.js
```

**Comment by jsandeepm** [comment]
I was also getting below mentioned error.

> global.window.beforeEach = beforeEach;
>                            ^
> ReferenceError: beforeEach is not defined
> 

I changed --require to --required and now its working fine.

My application mocha.opt

```
--compilers js:babel-register,jsx:babel-register
--recursive
--colors
--reporter list
--required ./test/setup.js
```

**Comment by tianjianchn** [comment]
Hi guys, I just find using async call in the required file will solve this problem:
```js
setTimeout(() => {
  beforeEach(async () => {
    // ***
  });

  afterEach(async () => {
    // ***
  });
});

```

**Comment by marswong** [comment]
@tianjianchn it only works for `beforeEach` and `afterEach`, `before` and `after` still suck

**Comment by Almenon** [comment]
I got the same error, but the reason was that I was using tdd, which uses suiteSetup instead of before.

**Comment by gcerrato** [comment]
For me what worked was the following:

From docs:

> Mocha loads modules specified by --require
> **If a file loaded this way contains known Mocha-specific exports (e.g., root hook plugins), Mocha “registers” these**
> If not, Mocha ignores any exports of a --require’d module

```
// common JS

exports.mochaHooks = {
  beforeEach(done) {
    // do something before every test
    done();
  }
};

// with ES Modules

export const mochaHooks = {
  beforeEach(done) {
    // do something before every test
    done();
  }
};
```
