### ISSUE TITLE
Passthrough --use_strict option to node

### ISSUE THREAD

**Issue by andrewbranch** [mochajs/mocha#1768]
I've seen it mentioned that this is not currently supported, but is there a reason for that?

**Comment by boneskull** [comment]
Mocha isn't written in strict mode maybe?  Other than that, passing Node flags is something we should move away from. Try it if you wish; `node --use-strict _mocha`

**Comment by diversario** [comment]
That just runs `_mocha` in strict mode; the process that it spawns doesn't enforce strict mode, from what I saw.
