### ISSUE TITLE
Fun way to set shared scope with a before-like function

### ISSUE THREAD

**Issue by ORESoftware** [mochajs/mocha#1775]
When I was new to ```Mocha```, I thought that maybe this would work:

```javascript
describe('Redis should failover successfully', function () 

    before(function(){
         var sentinel = require('redis-sentinel');
         var sentinelClient = sentinel.createClient(endpoints, {role: 'sentinel'});
    });

    it('Should return error 400 when message is not application/json', function (done) {

        sentinelClient.send_command('SENTINEL', ['failover', 'my master'], function(err, resp){
        //of course, sentinelClient is not defined so this won't work
        });
    });
});
```

however, of course, the ```before()``` callback function doesn't share the same scope as the ```it()``` callback function. 

So you have to do something like this:

```javascript
describe('Should accept all incoming message.', function () {

    var sentinel = null;
    var sentinelClient = null;

    before(function(){
         sentinel = require('redis-sentinel');
         sentinelClient = sentinel.createClient(endpoints, {role: 'sentinel'});
    });
    it('Should return error 400 when message is not application/json', function (done) {

        sentinelClient.send_command('SENTINEL', ['failover', 'my master'], function(err, resp){

        });
    });
});
```

Frankly, I find this to be pretty unclean - having to declare variables in the describe block. It would really nice to be able to declare them in the before.
In other words, it would be really slick, using the plasticity of JS, to make the scope for the describe callback to be shared with the scope from the callback of ```before()```, so that you could do what I wanted Mocha to be able to do when I was a Mocha newb.

Has anyone made a request like this prior? Does this make any sense?

**Comment by danielstjules** [comment]
I think this is a misunderstanding of scope and closures in JS. How would you propose we achieve this? 

I think you might be confusing modifying scope with the triviality of binding contexts in JS. Your original example can be roughly achieved using:
``` javascript
$ cat test.js
before(function() {
  this.object = {foo: 'bar'};
});

it('test', function() {
  console.log(this.object);
});
$ mocha test.js


{ foo: 'bar' }
  ✓ test

  1 passing (10ms)
```

**Comment by ORESoftware** [comment]
Well, in order to share scope between two functions, you'd have to put in one inside the other. I don't know of another way off the bat. In this case, you'd have to secretly be putting it() inside before(). I don't know if it's possible but it would be fun to see if it were.

**Comment by danielstjules** [comment]
> I don't know if it's possible but it would be fun to see if it were.
Unfortunately, without a build step, or parsing/manipulating the test files and using eval, it's not. We can't change the fact that JS has function-based lexical scoping.

**Comment by ORESoftware** [comment]
The sexier way to do this would be of course:

```javascript
describe('this refers to callback function',function(){
before(function() {
  this.object = {foo: 'bar'};
});

it('test', function() {
  console.log(this.object);
});

});
```

I checked and this does refer to the callback hook function (I think), 

https://www.dropbox.com/s/a64mp30f2wt5c4y/Screenshot%202015-07-01%2013.46.20.png?dl=0

**Comment by danielstjules** [comment]
Yup, it does. That's a feature of mocha :) You can set properties on the context itself, and it'll be shared between hooks and specs of a suite.

**Comment by ORESoftware** [comment]
that's pretty cool. is there a place in the docs that talks about this?

**Comment by danielstjules** [comment]
Yup! https://github.com/mochajs/mocha/wiki/Shared-Behaviours

**Comment by ORESoftware** [comment]
kool thx
