### ISSUE TITLE
--grep is not working

### ISSUE THREAD

**Issue by ORESoftware** [mochajs/mocha#1776]
I can't get --grep to work for either test/filename or the names passed to it().

How can I demonstrate a failing test for this on my local system?

**Comment by ORESoftware** [comment]
I figured out the problem - this might want to be in the docs

you need to wrap all your tests in a top level describe function for --grep to work. We had some set up code (20 lines or so) before our first describe function in our tests, and --grep wasn't working as I described above.

it looks like that if the first line of code in your test files is not a describe function, then the grep won't work as expected. Is this at all correct?

**Comment by ORESoftware** [comment]
However, one more thing on the same topic:

Say I have the following

//test1.js
```javascript
describe('@test1', function(){

   var x = {};

  it('should do something', function(done){
    //does something
     done();
});

});
```

//test2.js
```javascript
describe('@test1', function(){

   var y = {};

  it('should do something else', function(done){
    //does something else
});

})
```

if I do:

mocha grep test1

it will only run the it() pertaining to test1 HOWEVER it will run the code var y = {} inside the describe for test2.

I am very certain of this. Why is this happening? Is it by mistake or design?

**Comment by jbnicolai** [comment]
@ORESoftware both are by design, and for the same reason. The `describe` function has to be invoked to register the underlying `it` blocks. So naturally, other expressions within the same function scope will also be evaluated.

If you want your code to only run when the underlying tests are invoked, use [hooks](http://mochajs.org/#hooks)

**Comment by ORESoftware** [comment]
ok thanks will give this a go

**Comment by ORESoftware** [comment]
i think i see the light. one suggestion would be for the docs to have a clear demonstration of attaching all setup code in the before hooks and why putting the setup code outside the before but inside a describe can lead to said code running even when a grep option says not to run that code.
