### ISSUE TITLE
Put http://mochajs.org/ behind cloudflare

### ISSUE THREAD

**Issue by jbnicolai** [mochajs/mocha#1778]
Should improve caching, adds TLS and should improve search engine ranking (slightly).
What do you guys think?

Current Nameservers  | Change Nameservers to:
------------- | -------------
ns1.dreamhost.com	 | chad.ns.cloudflare.com
ns2.dreamhost.com	 | lorna.ns.cloudflare.com
ns3.dreamhost.com | Remove this nameserver

**Comment by boneskull** [comment]
@jbnicolai sounds fine to me.  how do we do that?

**Comment by jbnicolai** [comment]
@boneskull I've already created a cloudflare account for mochajs.org. All that would need to happen is for the DNS nameservers to be updated to the ones mentioned above, and I'll need to figure out if I can somehow invite you and @travisjeffery to that account so we share ownership.

Of course, if you ever want to revert this you simply point back to the original nameservers and cloudflare is out of the loop.

**Comment by boneskull** [comment]
@jbnicolai okay, see about those accounts.  I'll update the DNS records

**Comment by boneskull** [comment]
@jbnicolai records updated.  let me know if it doesn't propagate properly

**Comment by jbnicolai** [comment]
@boneskull seems like I should've done my homework before urging you to do this. Shared admin access to a website on cloudflare is a paid-only feature.

A way around this is to simply have a dedicated account for mochajs.org, the credentials for which we share. However, this would involve transfering the account, see https://support.cloudflare.com/hc/en-us/articles/200167856-How-do-I-transfer-or-move-a-domain-to-another-account-

tr;dr: if you'd revert the nameserver changes, I'll delete this cloudflare account and set up one separate from my personal account for mochajs.

**Comment by jbnicolai** [comment]
No worries btw, nothing will break ;)

**Comment by boneskull** [comment]
@jbnicolai reverted for now

**Comment by jbnicolai** [comment]
Ok, transfered.

The two new nameservers are `adi.ns.cloudflare.com` and `west.ns.cloudflare.com` and you should've received the credentials via PM.

**Comment by boneskull** [comment]
done
