### ISSUE TITLE
Extract the website to a separate repository, mochajs.github.io

### ISSUE THREAD

**Issue by jbnicolai** [mochajs/mocha#1779]
For history reasons the mocha website is currently a github [project page](https://pages.github.com/#project-site) rather than an [organisation site](https://pages.github.com/#user-site). I'd like to propose we change this.

This would entail:
- Create a new repository at github.com/mochajs/mochajs.github.io
- Place the content (and perserve history) of the `gh-pages` branch of this repository under that repository

Benefits:
- Separate issue and PR tracking for the website
- The direct URL would be http://mochajs.github.io rather than http://mochajs.github.io/mocha
- We wouldn't have a `gh-pages` branch that is completely unrelated to `master`

So all in all not a huge deal, but I figured it might be nice.

**Comment by boneskull** [comment]
this is a good idea.

**Comment by boneskull** [comment]
(however, the direct URL will be http://mochajs.org either way)

**Comment by jbnicolai** [comment]
> (however, the direct URL will be http://mochajs.org either way)

Correct, it's just a behind-the-scenes change

**Comment by boneskull** [comment]
done

**Comment by boneskull** [comment]
@jbnicolai think it's safe to zap `gh-pages` branch?

**Comment by jbnicolai** [comment]
@boneskull Pretty sure it is, mochajs.github.io seems to redirect as it should :)

Only thing I noticed is that you didn't transfer the history. While not extremely important, it would probably be best to preserve all commits on the gh-pages branch - right?

**Comment by jbnicolai** [comment]
But ^ shouldn't be blocking for removing the branch from this repo, so go right ahead. I'll retroactively fix the history somewhere tomorrow :+1:

**Comment by jbnicolai** [comment]
Done both :)
