### ISSUE TITLE
Consider relicencing mochajs.org's source

### ISSUE THREAD

**Issue by jbnicolai** [mochajs/mocha#1783]
See discussion in #1777

**Comment by boneskull** [comment]
tangentially: nobody likes a CLA, but the purpose of them is to protect us from litigation if someone submits a PR for copyrighted work and we accept it.  I'm not sure, but I imagine we would be potentially liable...

**Comment by jbnicolai** [comment]
Yes, technically I believe you are completely correct.

Personally, I'm not afraid of such a scenario occurring. Especially since we're not an asset-holding company.

**Comment by boneskull** [comment]
@jbnicolai but is it possible we'd be *personally* held liable?

**Comment by jbnicolai** [comment]
@boneskull impossible to answer, as I'm sure it depends on country, state and court. However, what could you possibly have personally done that you could be held liable for? Neither of us have profited from Mocha, and are in fact lending the name Mocha to the code others contribute.

**Comment by boneskull** [comment]
Anyway, [this](http://stackoverflow.com/questions/4035702/can-i-relicense-someones-mit-code-under-gpl) looks applicable to our situation.

We could either keep TJ's license on there *in addition to* the CC license, *or* we could politely ask TJ if he'd be willing to change the license of the site at mochajs.org (and *only* the site at mochajs.org) to CC.

**Comment by boneskull** [comment]
@jbnicolai I imagine the charge would be something like "redistributing copyrighted work".  In the USA, regardless of whether or not you profit, you may be held liable for redistribution.

Normally nobody is going to care for smaller projects, but Mocha's fairly popular.  It's not crucial that we put a CLA in place at this point, but we should have it on the table if we grow.  Perhaps a good benchmark would be if we wind up on the front page of npmjs.com.  This shows the top 15 most popular packages (though, I'm not sure by which metric).  Mocha is currently #18.

I'm all for CLAs, but I realize they are widely misunderstood.

**Comment by boneskull** [comment]
(anyway, there are great resources like [Contributor Agreements](http://contributoragreements.org/) and [CLAHub](http://clahub.com) if we ever wanted to move forward with that)

**Comment by jbnicolai** [comment]
@boneskull I understand what you're saying - although I don't think we're the ones redistributing mocha per-se. I just don't think the risk is anywhere near significant enough to warrant action.

I've been maintaing [chalk](https://github.com/chalk/chalk) for years, and it's been on the frontpage of npmjs.org for a long time as well; currently the \#8 most depended on package. Never had any issues like this, and haven't heard of other projects that weren't affiliated with a corporate sponsor having any either.

But if you'd like it for your personal peace of mind, I don't mind strongly enough to object ;-)

**Comment by jbnicolai** [comment]
CLAHub does look pretty painless though

**Comment by boneskull** [comment]
I've read up on this crap--I'm preparing an email to TJ about this, which clarifies some things for everyone

**Comment by boneskull** [comment]
in summary:

- The current site is not licensed
- Therefore nobody can use or modify it in any way
- Furthermore, anyone who forked Mocha and checked out the `gh-pages` branch could be sued by TJ
- We should license it for reuse
- We can't license it MIT, because MIT applies to software only
- So let's license it under a CC license
- TJ will still retain copyright, but the CC license cannot be revoked

**Comment by boneskull** [comment]
I am pretty sure all emails from GitHub wind up in TJ's spam folder (if I was him, that's what I'd do), but here's the cc just in case:  @tj

**Comment by boneskull** [comment]
continue in mochajs/mocha.github.io#4
