### ISSUE TITLE
Certain mocha command line options not working

### ISSUE THREAD

**Issue by sarus** [mochajs/mocha#1790]
I'm baffled by this.  I have mocha 2.2.5 installed globally

Running:

```
mocha --bail
```

give the error:

```
  error: unknown option `--bail'
```

Other options work fine like

```
mocha -V
mocha --help
mocha --trace
```

Then some other options give the same error as `--bail`

```
mocha --watch
 error: unknown option `--watch'

mocha --no-timeouts
error: known option `--no-timeouts`
```

Any clue what could be causing this?  I'm using Node `v0.12.6`

**Comment by jbnicolai** [comment]
@sarus what's the output of `which mocha` and `mocha --version`?

**Comment by sarus** [comment]
@jbnicolai Please let me know if there is any other information that might help figure this out.

```
which mocha
/opt/node/bin/mocha

mocha --version
2.2.5
```

**Comment by boneskull** [comment]
@sarus what are the contents of `/opt/node/lib/node_modules/mocha/node_modules`?  My best guess at that path... I'm looking for the contents of Mocha's `node_modules` folder.

**Comment by boneskull** [comment]
@sarus (does `npm remove -g mocha` then `npm install -g mocha --force` help?)

**Comment by sarus** [comment]
Contents of `/opt/node/lib/node_modules/mocha/node_modules` 

```
commander  debug  diff  escape-string-regexp  glob  growl  jade  mkdirp  supports-color
```

Dong `npm remove -g mocha` and then `npm install -g mocha --force` did not help.  I just noticed that mocha does work in other projects on the same machine.

so I have
```
/home/sarus/project1 <-- inside this project mocha --bail is broken
/home/sarus/project2 <-- inside this project mocha works fine
/home/sarus/project3 <-- inside this project mocha works fine
```

In all three project `which mocha` points to the same `/opt/node/bin/mocha`

**Comment by boneskull** [comment]
@sarus do you have `mocha` installed as a dev dependency of each of those projects?

**Comment by sarus** [comment]
Yes, mocha is installed as a dev dependency on all of them with the same version.

```json
    "devDependencies": {
        "mocha": "~2.2"
    }
```

**Comment by dstaley** [comment]
I'm running into this issue as well. It looks like `--bail`, `--watch`, `--no-timeouts`, and `--reporter` are all giving `error: unknown option`. Running `mocha` in my project works just fine, however. I'm using mocha 2.2.5 on node 0.12.7. The `--reporter` option worked for me last night, and the only things I've changed since then have been adding a few more tests.

**Comment by dstaley** [comment]
Actually, I think I found the issue. I was using the commander package to add CLI functionality. Removing the package (and the commander specific code) seems to have fixed the problem. I'll whip up a test case and file another issue.

**Comment by madarche** [comment]
I confirm that I have the same problem and that when I remove the `commander` module no more `error: unknown option` problems. I'm not using the `rewire` module though.

Thanks @dstaley for the investigation!

**Comment by drazisil** [comment]
This appears solved.

**Comment by ScionOfBytes** [comment]
I just got this issue, but this time with the simple mocking module.

**Comment by rottmann** [comment]
Same problem today when run mocha locally installed in devDependencies

node 8.1.4
npm 5.3.0
mocha 3.4.2

`$ node_modules/mocha/bin/mocha --bail tests/`
error `error: unknown option '--bail'`

or in package.json scripts
`"test": "mocha --bail tests/`
`$ npm run test`
error `error: unknown option '--bail'`

global installed it is ok
`$ mocha --bail tests/`

**Comment by ScottFreeCode** [comment]
Hi, @rottmann, sorry for the late reply -- can you try removing the global Mocha and double-check that the version of the local Mocha is 3.4.2 or 3.5.0?

**Comment by rottmann** [comment]
Solved for me: the error was not from mocha, it was a wrong check of args in my test (something changed in commander) that produced the error.
