### ISSUE TITLE
Unexpected working of an after hook

### ISSUE THREAD

**Issue by gig177** [mochajs/mocha#1793]
```bash
$ mocha -V
2.2.5
```
```javascript
var Q = require('q');

first().then(second)

function first() {
    var deffered = Q.defer();
    describe('First suite', function() {
        after(function someTeardownTask(done) {
            setTimeout(function() {
                deffered.resolve();
                done();
            }, 0);
        });
        it('first spec');
    });
    return deffered.promise;
}
function second() {
    describe('Second suite', function() {
        it('second spec');
    });
}
```
```bash
$ mocha
  First suite
    - first spec

  0 passing (12ms)
  1 pending
```
if i replace the after hook with before then this works fine.

**Comment by boneskull** [comment]
@gig177 please describe the expected behavior

**Comment by gig177** [comment]
I expected:
```
  First suite
    - first spec

  Second suite
    - second spec

  0 passing (12ms)
  2 pending
```

**Comment by gig177** [comment]
What am i misunderstood? At Jasmine framework  i met with the same problem. I can't go to the next step of my project without close this issue. Help me please.

**Comment by danielstjules** [comment]
Could a delayed suite be helpful in what what you're trying to achieve? Also, do you need to define the specs in an async manner? Or could they just be skipped that way?

**Comment by gig177** [comment]
Yep. I should use the delayed suite. I need to test an async tasks in order manner. This [call](https://github.com/gig177/spadmin/blob/master/view/test/crud.js#L14) doesn't successful.

**Comment by boneskull** [comment]
OK, it sounds like this can be closed.
