### ISSUE TITLE
Support Wallaby.js

### ISSUE THREAD

**Issue by DenisGorbachev** [mochajs/mocha#1795]
http://mochajs.org/#editor-plugins — it would be great if you had mentioned [Wallaby.js](http://wallabyjs.com/) with an intro video here. Much better than default JetBrains test runner.

**Comment by boneskull** [comment]
Wallaby sounds cool.  I'll have to try it.

@ArtemGovorov Do you offer free licenses to open-source projects?

**Comment by boneskull** [comment]
I forgot, this belongs [here](/mochajs/mochajs.github.io/issues)

**Comment by boneskull** [comment]
please continue discussion in mochajs/mocha.github.io#3
