### ISSUE TITLE
documentation issues

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#1796]
now that I've actually moved all the documentation issues, I'm thinking maybe I shouldn't have.  people are probably going to post them here anyway.  maybe I should delete those in the site repo, and reopen the ones I closed here, then disable "issues" for the site repo...?

cc @mochajs/mocha

**Comment by danielstjules** [comment]
I guess the question for me is what docs should exist on the site vs the wiki?

**Comment by boneskull** [comment]
@danielstjules Good question.

I would prefer everything be on the site, simply because it's more accessible.

re #1783, I spoke with the GM of the [Open Source Initiative](http://opensource.org) the other day at OSCON about this very issue.  We came to the conclusion that since @tj hasn't replied to my email about the license, our only option is to completely rewrite the site.

I would prefer the API documentation should be auto-generated, with liberal examples, and accompanied by tutorials--perhaps migrate bits of the wiki over as well.

cc @mochajs/mocha
