### ISSUE TITLE
grep does not handle "(" and ")" in title

### ISSUE THREAD

**Issue by michaelkantor** [mochajs/mocha#1797]
On selecting a set of tests in the web UI, the grep expression is invalid if the title contains parenthesis.

I have a title: "/blah-endpoint blah blah blah (STATUS: JIRA-313 Story Not Begun)" 

On selecting that title, the grep regex that is generated is: 
```/\/blah-endpoint blah blah blah (STATUS: JIRA-313 Story Not Begun)/```

Which fails as it should be:

```/\/blah-endpoint blah blah blah \(STATUS: JIRA-313 Story Not Begun\)/```

**Comment by michaelkantor** [comment]
Also doesn't handle "?".  I have a title:  `it("Should connect to http://blah.com/?blah=blah")`

but the regex fails to escape the "?"

As with the "(" error, this is easily fixed on my end by rephrasing my titles, but having to step through a debugger to debug the framework running the test suite is probably not a great experience for typical developers.

**Comment by boneskull** [comment]
I imagine it wouldn't handle anything a regex recognizes as a meaningful character

**Comment by boneskull** [comment]
@michaelkantor is your title a suite or a test?

**Comment by boneskull** [comment]
actually nm I think that's irrelevant

**Comment by michaelkantor** [comment]
In any case, the answer is that I use these for both; a specific test is often linked to a specific jira entry which I may put in parenthesis.  A suite of tests may be linked to a jira user story which I would also put in the test name.  

In either case, the real issue is that there is no visibility into WHY grep fails short of openning a debugger stepping through as grep executes (which I did prior to opening this ticket).  Most developers will not know why it isn't working and not know to change their test titles.

**Comment by boneskull** [comment]
@michaelkantor What version of Mocha are you using?

**Comment by michaelkantor** [comment]
Version 2.2.5

**Comment by jasonpang** [comment]
I can confirm this issue still exists on Mocha 2.5.3. In my case, test names with `(` or `)` cannot be grepped for. In other words, if you have something like:

`yourtestsite.com/tests.html?grep=method()`

The test will not appear at all (grep fails).

**Comment by ScottFreeCode** [comment]
This seems like intended functionality to me -- you can escape the `(` and `)` with `\` (or `[(]`/`[)]` or `%5C`), but otherwise they're part of a regular expression. If the expression were automatically escaped it wouldn't be possible to use the grep url parameter for regular expression features. The links in the HTML reporter include such explicit escaping. Furthermore, you can use `?fgrep=partial match for test title here` to get automatic escaping (unfortunately, that way you can't force it to match the whole test title using `^` and `$`, which you can with `?grep=`).

**Comment by michaelkantor** [comment]
Well then perhaps the error is in the renderer which provides links that use "(" and ")" incorrectly when putting them in grep.  Whats most disturbing about the issue is that there is no error handling whatsoever, and only by stepping through mocha code does one discover why no tests are running.

**Comment by ScottFreeCode** [comment]
In the current version it is providing links that use parentheses correctly.

**Comment by michaelkantor** [comment]
Looking into that now.  FYI: http://mochajs.org/#running-mocha-in-the-browser has examples using the same version I'm running.

**Comment by michaelkantor** [comment]
Behaves as you've reported using CDN "https://cdnjs.cloudflare.com/ajax/libs/mocha/2.5.3/mocha.min.js".

While I recommend updating the docs, my concerns are addressed, thanks!
