### ISSUE TITLE
Mocha might crash on unit testing failure randomly

### ISSUE THREAD

**Issue by mocheng** [mochajs/mocha#1803]
This is hard to provide reproduce code, but we get mocha randomly crashed if there is unit testing failure.

We have +700 test cases. From time to time, mocha just died silently without any error message. By looking up the reported log, we know there is some unit testing failure. However, since mocha died before spit out the details of assertion statements, we don't know why the unit test case fail.

Is there any way to make mocha dump test case failure info into log file?

For the time being, we just change 
https://github.com/mochajs/mocha/blob/master/lib/reporters/spec.js#L74 to be like

```
  runner.on('fail', function(test, err) {
    cursor.CR();
    console.log(indent() + color('fail', '  %d) %s'), ++n, test.title, err);
  });
```

So that there is failure reason even mocha crashed.

**Comment by danielstjules** [comment]
Sorry, I know this is a bit late. Is it possible something is killing the process, and mocha can't recover? E.g. something like a process.exit being hit.

**Comment by rwlaschin** [comment]
I'm seeing the same behavior in my mocha tests.  I use mocha/wd/chai

I'm using grunt to start mocha with mocha.run  Also I run multple passes with .run as I need to run the tests with a different browser configuration for use with saucelabs.  

When mocha dies there is no output to indicate why there is a failure.  We are running through a bash console so debugging is limited.

**Comment by roza1298** [comment]
I am running the test with Mocha & Chai , and facing same issue
Random test are failing though i am using promise : 

 it(" ", function(done){
done();
});

Any suggestion around would be helpful 

Note : Have seen the console.log(result of previous test) is displayed in next test

**Comment by juergba** [comment]
This is an old issue and not reproducible => closing.

To isolate bugs with current version of Mocha:
- use `--allow-uncaught` option which aborts process upon uncaught exception.
- we have known issues with failing reporters silently aborting process.
Use `--no-diffs` to exclude diff generating bugs, or choose another reporter eg _MIN_ .
