### ISSUE TITLE
Console.write() not showing up in terminal

### ISSUE THREAD

**Issue by dschinkel** [mochajs/mocha#1805]
I'm doing a console.write but do not see it in the mocha test results

            it('we should have an application available', function(done){
                console.write("I cannot see this in the terminal");
                server.app.should.be.a('object');
                done();
            });

**Comment by danielstjules** [comment]
I think you want `console.log` :)

**Comment by dschinkel** [comment]
omg please delete the entire thread.  I'm embarrassed lol duh.  Not like I haven't used log before, been a long day.

**Comment by danielstjules** [comment]
haha no worries, I def have those kinds of moments all the time
