### ISSUE TITLE
Mocha loggin "NaN passing" and "NaN failing" when running tests

### ISSUE THREAD

**Issue by CGavrila** [mochajs/mocha#1806]
The title says it all, I guess.

I run `mocha` in the root of my project and then I get the output like usual, except for the number of tests passing/failing.

```
Some class
    ......
    .....


  NaN passing (36ms)
  NaN failing
```

**Comment by boneskull** [comment]
@CGavrila can you provide more info such as the tests themselves, your command line args and/or `mocha.opts`

**Comment by danielstjules** [comment]
Are you running the latest version of mocha? And a small reproduce-case would be appreciated! :)

**Comment by CGavrila** [comment]
Sorry, forgot to provide some stuff:

```
$ uname -a
Linux Jmen 3.16.0-43-generic #58~14.04.1-Ubuntu SMP Mon Jun 22 10:21:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ mocha -V
2.2.5

$ node -v
v0.12.5
```

I do not run mocha with any arguments.

Anyway, I think I found what the problem is. I am using a module called [better-log](https://github.com/rreverser/better-log) in order to enhance my `console.log`s. Commenting it out of my `require`s seems to do the trick. It's a bit strange that it manifests itself this way, but there we go.

I guess this can be closed.
