### ISSUE TITLE
upgrade Jade dependency

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#1811]
Our Jade version is ancient and should be upgraded to latest.

But I know that it *will* break things.

I also know that I'm not interested in fixing it.  So... PR's accepted

(see old PR #1084)

**Comment by timbeadle** [comment]
Also jade is renaming to pug to avoid a lawsuit: https://github.com/pugjs/pug/issues/2184

**Comment by YasharF** [comment]
https://github.com/mochajs/mocha/issues/2200#issuecomment-235493858
