### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by ncuzp** [mochajs/mocha#1816]
when I typed 'mocha -R HTML test.js'  in CL, it happens!

**Comment by danielstjules** [comment]
Sounds like you're running browser tests from the command line, without a headless browser. This might be what you want: https://github.com/nathanboktae/mocha-phantomjs https://github.com/mrhooray/gulp-mocha-phantomjs

**Comment by danielstjules** [comment]
Closing as the last reply was almost a month ago.

**Comment by DKhateek1372** [comment]
Hey 
The solution is provided by you is now deprecated.
Still I am getting the same error  is that : 
 Reference Error: document is not defined
 
 
 
![image](https://user-images.githubusercontent.com/30972035/107034802-3a640980-67dd-11eb-93ad-a3b746cb4f5c.png)
