### ISSUE TITLE
add --strict flag 

### ISSUE THREAD

**Issue by charlierudolph** [mochajs/mocha#1818]
I'd like a `--strict` CLI flag that will cause my tests to exit with non-zero status if
- any test is marked as only
- any test is marked as skipped
- any test is marked as pending

**Comment by boneskull** [comment]
This may be a good solution to the problem of accidentally committing these. 

@mochajs/mocha any opinions?

**Comment by dasilvacontin** [comment]
Hmm, I thought skipped tests are actually marked as pending?

People do commit these (looking at you `.only`), so I believe this is useful, and I'm looking forward to it.

**Comment by Spy-Seth** [comment]
I would love to have this!

I you do not want a test (even in prod): it's probably because this is a dead/outdated test and need to be deleted from the source code.

**Comment by dasilvacontin** [comment]
cc @mochajs/mocha

**Comment by danielstjules** [comment]
Could we use some different terminology so that it's not confused with node/v8's `--use_strict` ?

**Comment by boneskull** [comment]
How about `--production`

**Comment by IvanGuardado** [comment]
What is the status of this issue? I've been following the related PRs but they seem to be closed all. 

I think this is an important configuration and I was surprised that it didn't exist since some commit could add a `.only` and the test suite would be giving invalid feedback...

Thanks!

**Comment by boneskull** [comment]
@IvanGuardado https://github.com/mochajs/mocha/pull/1935#issuecomment-242995238
