### ISSUE TITLE
Mocha versions 2.3.0 and 3.0.0

### ISSUE THREAD

**Issue by ardeshirbadr** [mochajs/mocha#1819]
Hi,
I am doing some research on Mocha 2.3.0 and 3.0.0 versions and am interested in end of availability/support dates for these versions. 
What kind of support I can have if I use theses versions beyond their end of their availability/ support?
Any information on this subject is appreciated.
Best regards,
Ardeshir.

**Comment by danielstjules** [comment]
2.3.0 was released, and 3.0.0 is in the works, though the scope is still being discussed. Hard to say what will go into 3.0.0, and we don't yet have a timeline AFAIK. In terms of support, you should try to stick to the most recent version as we try our best to avoid breaking changes. But if a regression is found, we'll hopefully resolve it rather quickly. :) And of course, there's the option to stick to older versions.

As long as you're on 2.x.x, you should expect good support, as the core implementation hasn't drastically changed across minor/patch releases.
