### ISSUE TITLE
Helpers

### ISSUE THREAD

**Issue by mnichols** [mochajs/mocha#182]
Apologies if there is a better place to ask this...I wasn't sure where to ask about Mocha.

I am coming from Jasmine with its 'helpers' magic. 
I am primarily using Mocha for browser BDD specs right now and can't determine the best way to have Mocha run beforeEach on each spec from some kind of helper.  
The `require` option isn't available when running in the browser (I think) and I am not sure how to hook into Mocha to do some kind of setup.  

Any guidance or tips would be appreciated...I don't want to bend Mocha into a Jasmine mold, so if I am missing something please let me know.

Thanks!
mike

**Comment by emahuni** [comment]
i think this should be implented to make mocha simple to use.
