### ISSUE TITLE
Ability to force strict mode for all tests.

### ISSUE THREAD

**Issue by diversario** [mochajs/mocha#1821]
Basically, either make mocha itself do something to turn strict mode on or run child process with `--use_strict` (is that possible somehow?).

**Comment by danielstjules** [comment]
We could add it as a case to https://github.com/mochajs/mocha/blob/master/bin/mocha#L55-L59 for a quick fix until that logic gets cleaned up :)

**Comment by diversario** [comment]
Sure! That works for me.
