### ISSUE TITLE
How can I just run one test with mocha?

### ISSUE THREAD

**Issue by xidui** [mochajs/mocha#1822]
I have many unit test files and in each one there are plenty of tests.
It takes long to run all of them. But sometimes I only want to see the result of one or several tests.
How can I do?
 To add an 'x' before each describe will work. But I will add plenty of 'x', I feel that troublesome. Is there any more simple way to do this?

**Comment by a8m** [comment]
Using [grep](http://mochajs.org/#g-grep-lt-pattern-gt) will be a good solution here.
Thanks @xidui

**Comment by twada** [comment]
@xidui @a8m To run single case or suite, you can use [only](http://mochajs.org/#exclusive-tests) feature.

**Comment by a8m** [comment]
Sure,
`only` will be a good solution if you want to run a single case or suite.
but he asked for:
> see the result of one or several tests
