### ISSUE TITLE
Possible to use custom UIs in browser?

### ISSUE THREAD

**Issue by keirlawson** [mochajs/mocha#1823]
I was wondering if this was possible? My naive approach to doing this by using Webpack and following the documentation on the wiki is not working.

**Comment by jasonkarns** [comment]
I'm having similar troubles. It seems that custom UIs attempt register themselves via `require('mocha').interfaces['my-new-ui'] = myNewUi`.

However, the browser global that mocha exposes from the browser build does not expose the `interfaces` object, so the custom UI throws errors when attempting to register itself. (I'm attempting mocha-given and mocha-gwt, both of which fail with the same error).

**Comment by tauren** [comment]
:+1:

**Comment by JohnBaileyN** [comment]
:+1:

**Comment by danielstjules** [comment]
This is fixed via https://github.com/mochajs/mocha/pull/1972 and more specifically https://github.com/mochajs/mocha/commit/a61b1f3287b436522545e5458d071d7e791c15d0
Thanks!
