### ISSUE TITLE
Add `--grep` extension to run all tests if no matches

### ISSUE THREAD

**Issue by joefiorini** [mochajs/mocha#1831]
We have a make task that runs a watcher; the watcher runs our test suite after each build of our app. If I want to solo out a test I have to quit the watcher and rerun it passing in `--grep @solo`. It would be great to be able to hardcode the `--grep @solo` in our make task, so that all we have to do is add the tag whenever we want and it will match just what we want. However, if we don't have anything soloed out, we would want the entire test suite to run.

I'm thinking I could implement this by adding a an extra flag that causes mocha to first do the grep silently then run all tests if there are no matches. Maybe something like:

`mocha --grep @solo --run-all-no-matches tests`

Before I start trying to implement and send a PR, I wanted to get the feel from the community. Does this functionality exist and I'm missing something? If not, is this something others would find useful?

**Comment by dasilvacontin** [comment]
Wait, why not use `.only`?

**Comment by boneskull** [comment]
@dasilvacontin either I am half asleep or I don't understand your comment

**Comment by boneskull** [comment]
I would be in favor of modifying spec's output to list "tests run" in addition to number of failures and number of passes.

**Comment by boneskull** [comment]
then you could pipe to grep or something.
