### ISSUE TITLE
merge v2.3.0 -> v3.0.0

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#1836]
there's a conflict in `lib/runnable.js` that I need to sort out

**Comment by boneskull** [comment]
ok

**Comment by boneskull** [comment]
well, maybe I should have done 2.3.0->3.0.0 first... heh

**Comment by boneskull** [comment]
anyway, `master` is now merged into `v2.3.0`

**Comment by dasilvacontin** [comment]
Done then. (?)

**Comment by boneskull** [comment]
@dasilvacontin yeah but forgot to change the title again

**Comment by dasilvacontin** [comment]
I see. I hope the conflicts are not strong with this one. :wink:

**Comment by ngeor** [comment]
Good morning,

can this issue be closed?

Best regards,
Nikolaos
