### ISSUE TITLE
mocha can't find module 'coffee-script/register' if not run at the root of the project

### ISSUE THREAD

**Issue by albertnetymk** [mochajs/mocha#1837]
## How to Reproduce the problem

1. Setup the repo and install its `coffee-script` dependency.

    ```
    git clone https://github.com/albertnetymk/mocha_dummy
    cd mocha_dummy
    npm install
    ```
2. Run mocha at the root of the project.

    ```
    mocha --compilers coffee:coffee-script/register test/*
    ```
    and the output is:
    ```
        0 passing
    ```
3. Run mocha at the non-root of the project.

    ```
    cd test; mocha --compilers coffee:coffee-script/register *
    ```
    and the output is:
    ```
    ...
    Error: Cannot find module 'coffee-script/register'
    ...
    ```
    
## ENV
mocha: 2.25

**Comment by boneskull** [comment]
if you are not at the project root, you need to tell it where to look for the `coffee-script` module, a la:

```shell
$ mocha --compilers coffee:../node_modules/coffee-script/register *
```

**Comment by albertnetymk** [comment]
This answer is not very convincing, for node could find the `node_modules` folder, according to [this](http://www.bennadel.com/blog/2169-where-does-node-js-and-require-look-for-modules.htm).

Testing using the head of  master, 6862b7efd0, the problem goes away.

Thank you very much for this wonderful tool.
