### ISSUE TITLE
how to show the whole stacktrace when there is exception in test case of bower mocha

### ISSUE THREAD

**Issue by lygstate** [mochajs/mocha#1843]
At the current time, it's only output the error string
but without the stacktrace information and hard to debugging

**Comment by boneskull** [comment]
`--full-trace`

**Comment by lygstate** [comment]
This does't answer my question

I am running mocha in browser, so I have no way to specify the command line, how to do that?
```
    <script src="../bower_components/mocha/mocha.js"></script>
    <script src="../bower_components/chai/chai.js"></script>
    <script src="../bower_components/co-mocha/co-mocha.js"></script>
    <script type="application/javascript;version=1.8">
      const {Cc, Ci, Cu} = require('chrome');
      const Services = Cu.import("resource://gre/modules/Services.jsm", {}).Services;
      let console = Cu.import("app://app-bootstrap/Console.js", {}).console;
      mocha.setup('bdd')
      let expect = chai.expect;
    </script>
```

**Comment by dasilvacontin** [comment]
@lygstate `--full-trace` just does `mocha.fullTrace()`, ref https://github.com/mochajs/mocha/blob/master/bin/_mocha#L277.

**Comment by mhluska** [comment]
In 2018, that link to master does not point where you intended it to 😛

**Comment by lygstate** [comment]
Oh so calling mocha.fullTrace()>

**Comment by plroebuck** [comment]
@mhluska well you are referring to an issue closed more than three years ago.
@lygstate yes... 
```js
    <script type="application/javascript;version=1.8">
      const {Cc, Ci, Cu} = require('chrome');
      const Services = Cu.import("resource://gre/modules/Services.jsm", {}).Services;
      let console = Cu.import("app://app-bootstrap/Console.js", {}).console;
      mocha
        .setup('bdd')
        .fullTrace();
      let expect = chai.expect;
    </script>
```

**Comment by mhluska** [comment]
@plroebuck and yet I still flowed in here through Google as many probably do. This link will last longer: https://github.com/mochajs/mocha/blob/a371e2f73f8a6781aab6723bb596a31fc275bdf7/bin/_mocha#L448
