### ISSUE TITLE
Manually import / require describe it etc?

### ISSUE THREAD

**Issue by peteruithoven** [mochajs/mocha#1849]
Is there anyway to manually import / require functions like `describe` and `it`? 
I'd like to use mocha without the commandline interface, in a regular browser. (I'm using JSPM as dependency manager)
I couldn't find documentation on this on the [Mocha website](https://mochajs.org/).

**Comment by SerkanSipahi** [comment]
@peteruithoven  see here for using mocha in browser: https://mochajs.org/#running-mocha-in-the-browser

**Comment by peteruithoven** [comment]
Ah thanks, the extra examples you added where the docs I was missing. 

I'm not able to get your JSPM(SystemJS) example working though, are you sure you've included all the details? Is there more info elsewhere? 
I've created a very minimal example of what I tried:
https://github.com/peteruithoven/jspm-mocha

**Comment by peteruithoven** [comment]
Anyone?

**Comment by boneskull** [comment]
see #956 for further discussion
