### ISSUE TITLE
Would be nice if mocha sets the NODE_ENV variable to 'test'

### ISSUE THREAD

**Issue by Cowboy-coder** [mochajs/mocha#185]
Pretty handy if different middlewares / configs etc. in Express or such is needed when running the test suite.

**Comment by felixfbecker** [comment]
As far as I know `NODE_ENV=test mocha` doesn't work on Windows, neither does `make`.

**Comment by felixfbecker** [comment]
It would be nice to have a simple `--env` option so you can write tests that don't depend on a specific platform.

**Comment by tswaters** [comment]
@felixfbecker - for windows,  `set NODE_ENV=test && mocha`

**Comment by felixfbecker** [comment]
Sure but then the same command will not work on *nix systems, if you want to put it in your `npm test` script

**Comment by naholyr** [comment]
@felixfbecker @tswaters have you checked [env-test](https://github.com/lmtm/node-env-test)?

**Comment by felixfbecker** [comment]
That only works for NODE_ENV though and relying on values of NODE_ENV is bad practice. See http://12factor.net/config

**Comment by halkeye** [comment]
I know this is super super old, but cross-env (https://www.npmjs.com/package/cross-env) takes care of the windows issue.

**Comment by boneskull** [comment]
@halkeye Good tip, thanks.

**Comment by tombh** [comment]
I am one of those people that always runs raw `mocha` because I like to `--grep` single tests. To me this is a fundamental aspect of Test Driven Development, which in turn is a fundamental approach to software development. The suggestions to use `make` or `npm` (which do not pass on the `--grep` arg) betray a lack of awareness or indeed interest in a TDD approach. Which is somewhat ironic, given this is all about a prominent testing tool.

**Comment by halkeye** [comment]
`npm run test -- --grep whatever` will work fine

Also you can use https://www.npmjs.com/package/env-test and add requires env-test to your mocha.opts too

There's lots of options out there.

**Comment by tombh** [comment]
But should someone that doesn't know that `npm run test -- --grep whatever` works, then goes straight to `mocha`, be penalised?

Mocha itself should be the one championing idempotency. The `env-test` plugin is the only real solution here.

**Comment by jasonk** [comment]
Since this still seems to get a lot of traffic I thought I would throw out a relatively simply solution for people like me who wish there was a `--env` flag.  What I've been doing is add a `test/mocha.env.js` file in the repo, and then add `--require test/mocha.env.js` to `mocha.opts`:

```
// mocha.opts
--require babel-register
--require test/mocha.env.js
--timeout 60000

// mocha.env.js
process.env.NODE_ENV = 'test';
```

**Comment by demisx** [comment]
Per @jasonk, the same approach works in TypeScript:

```ts
// In mocha.opts
--require test/mocha.env
...

// In mocha.env.ts
process.env.NODE_ENV = 'test';
```

**Comment by AlexanderTserkovniy** [comment]
Guys, cannot get what do you mean by "There are plenty of other ways to get this done" https://github.com/mochajs/mocha/issues/185#issuecomment-54729812.
I have simple requirement my CI&CD should be able to change env variables for TEST/STAGE/PROD, how it would do it? Change .env file on flight? Or how?

**Comment by AlexanderTserkovniy** [comment]
Okay, I had to do this way (within package.json script section):
`"test": "HEADLESS=$HEADLESS URL=$URL mocha -A --recursive tests -t 10000"`
So it means that it will pass `URL` and `HEADLESS` params to mocha.
Examples of use:
`HEADLESS=false URL=http://example.com npm run test`

**Comment by jedwards1211** [comment]
@tombh
> But should someone that doesn't know that npm run test -- --grep whatever works, then goes straight to mocha, be penalised?

Yeah, and it can get even worse than that for people who do know that trick.  For instance in Sequelize I had to use two double dashes because it has npm scripts running other npm scripts:
`npm run test-postgres -- -- --grep sheesh`

Further more, the test-postgres script is something like
`DIALECT=postgres npm run test-unit && npm run test-integration` which means that only `test-integration` receives the options.

**Comment by jedwards1211** [comment]
Actually whoops I mistakenly thought this issue was about getting options from a `MOCHA_OPTS` environment variable, I googled for that and skimmed to quickly

**Comment by krzkaczor** [comment]
Another idea: if you use mocha's config JavaScript file you can just put it there:
*.mocharc.js:*

```javascript
process.env.NODE_ENV = 'test';

module.exports = {
  require: 'ts-node/register/transpile-only',
  extension: ['ts'],
  watchExtensions: ['ts'],
  spec: ['test/**/*.test.ts'],
}
```

**Comment by shalior** [comment]
since node 20.6.0: use "node-option" to natively load an env file. 
`.mocharc.json:`
```json
{
	"ui": "bdd",
	"node-option": ["import=tsx", "env-file=.env.test"],
}
```
