### ISSUE TITLE
Bind ES6 arrow functions to Context

### ISSUE THREAD

**Issue by michielbdejong** [mochajs/mocha#1856]
disclaimer: I'm quite new to Mocha and to arrow functions, so feel free to close this if it's nonsense. :)

Consider these three tests:
````js
test('Mocha Context available in normal ES5 functions', function() {
  expect(this.slow).to.be.a('function');
});
test('Mocha Context available ES6 arrow functions', () => {
  // Will fail, because it's bound to `window`:
  expect(this.slow).to.be.a('function');
});
test('Mocha Context available in nested, bound ES6 arrow functions', function() {
  (() => {
    expect(this.slow).to.be.a('function');
  })();
});
````
afaics this is because [Mocha uses `fn.call(ctx);`](https://github.com/mochajs/mocha/blob/master/lib/runnable.js#L289) to execute the function passed to `test`, which does not have the desired effect in case of ES6 arrow functions, as you can [read here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Invoked_through_call_or_apply) and also see if you run this in your browser console:
````js
(() => { console.log(this); }).call({ foo: 'bar' });
// prints the Window object
(function() { console.log(this); }).call({ foo: 'bar' });
// prints { foo: 'bar' }
(function() { (() => { console.log(this); })(); }).call({ foo: 'bar' });
// prints { foo: 'bar' }
````
Looking especially at how that third test (arrow function wrapped inside a normal function) does pass, I think it could be fixed by wrapping the variable `fn` in a normal ES5 function before calling its `.call` method, i.e. replacing that `fn.call(ctx);` with `(function() { fn(); }).call(ctx);` on [line 289 of Runnable.js](https://github.com/mochajs/mocha/blob/master/lib/runnable.js#L289)

**Comment by michielbdejong** [comment]
Or the easier option would of course be to add a note to the documentation saying: Don't put your test in an arrow function if you plan to use `this.slow` or other methods from the Context. :)

**Comment by developit** [comment]
@michielbdejong The documentation suggestion works, or Mocha could pass the test context as an argument in addition to setting it as `this`.

**Comment by danielstjules** [comment]
I believe instead of `(function() { fn(); }).call(ctx);` you would need `(function() { return fn(); }).call(ctx);`

**Comment by danielstjules** [comment]
@michielbdejong Your suggested fix doesn't seem to work in practice

``` javascript
var assert = require('assert');

function it(str, fn) {
  var ctx = {
    skip: function() {}
  };

  (function() {
    fn().call(ctx)
  }).call(ctx);
}

it('Mocha Context available ES6 arrow functions', () => {
  assert.equal(typeof this.skip, 'function');
});
```

```
$ node --version
v4.0.0
$ node example.js

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: 'undefined' == 'function'
```

The reason that `(function() { (() => { console.log(this); })(); }).call({ foo: 'bar' });` works is because the inner arrow function is already bound to its parent function's context prior to the `call()`

**Comment by danielstjules** [comment]
How babel transpiles the codes should make it evident why this won't work:
``` javascript
(function() {
  it('test', () => {
    console.log(this);
  });
});

// => 

'use strict';

(function () {
  var _this = this;

  it('test', function () {
    console.log(_this);
  });
});
```

**Comment by danielstjules** [comment]
Closing for now. An issue/pr in https://github.com/mochajs/mochajs.github.io would be appreciated! :)

**Comment by michielbdejong** [comment]
> Your suggested fix doesn't seem to work in practice

Oh, of course, sorry. I see why now. Thanks for taking the time to write a code example!

I created https://github.com/mochajs/mochajs.github.io/pull/14.

**Comment by danielstjules** [comment]
No problem - my commit referenced in this issue should hint that I thought it would work too haha.

And appreciate the PR! :)

**Comment by timkinnane** [comment]
If anyone finds this solution unsatisfactory, as I did, because you'd really prefer to use arrow functions, I have good news! You can just declare the top level `describe` with a normal function,: e.g. `describe('MyClass', function () {`

It works because any arrow functions within will have `this` bound to their containing function's scope (i.e. the mocha context). So the follow will totally work...

```
describe('thing', function () {
  describe('does stuff', () => {
    beforeEach(() => {
      this.foo = 'bar'
    })
    it('should work', () => {
      assert(this.foo === 'bar')
    })
  })
})
```

👍👍👍👍👍

**Comment by ScottFreeCode** [comment]
WARNING: that is not the same thing\* and *might* not behave equivalent to the non-arrow-function code for:
- nested suites
- configuration (`this.timeout(<milliseconds>)` and the like)
- `currentTest` in hooks
- anything else `this`-related that would normally affect the specifically the current hook or test or otherwise be specially handled

\* For better or for worse, Mocha is doing some magic regarding the `this` object to achieve all the uses it supports, so it isn't simply sharing the same context object between all suites and tests.

**Comment by timkinnane** [comment]
@ScottFreeCode thanks for the tip! I've edited my comment to reflect my reduced confidence.

**Comment by catamphetamine** [comment]
Is there an option to pass a custom `ctx` so that `it` callbacks are bound to it?
We prefer binding our tests to a certain "library" as `this`.
