### ISSUE TITLE
Spies not being removed after tests in 2.3.0

### ISSUE THREAD

**Issue by rayd** [mochajs/mocha#1857]
As soon as we upgraded to mocha 2.3.0 our tests started failing with the error:
`TypeError: Attempted to wrap {some function name} which is already wrapped`. We're using sinon.js to create spies. Seems like there's some kind of incompatibility with sinon and mocha 2.3.0?

**Comment by boneskull** [comment]
Please paste your test code

**Comment by boneskull** [comment]
actually, this *is* stale.
