### ISSUE TITLE
Error stack filtering should be configurable

### ISSUE THREAD

**Issue by ArtemGovorov** [mochajs/mocha#1859]
While I think excluding lines with `node_modules` substring from error stacks is reasonable, excluding [stack lines with `components` substring](https://github.com/mochajs/mocha/blob/4f0b32e0cef5d999f7f9594e3dccef89f023d65f/lib/utils.js#L709) seems very questionable. We have hit [the issue](https://github.com/wallabyjs/atom-wallaby/issues/6) in wallaby.js and I'm sure many people may have missing stack lines for their `components` folders and subfolders in their specs and source folders.

Setting `fullTrace` somewhat helps, but it starts reporting `node_modules` stack lines. 

What do you think about having a setting to set an array of strings (or a function) to be used for filtering error stacks?

**Comment by aaronjensen** [comment]
If any are interested, here's a monkey patch work around, tested on mocha 2.3.0:

```js
      var fail = Mocha.Runner.prototype.fail;
      var originalFilter = Mocha.utils.stackTraceFilter();

      function stackFilter(stack) {
        return originalFilter(stack.replace("/components/", "/__componentz__/"))
          .replace("/__componentz__/", "/components/");
      }

      Mocha.Runner.prototype.fail = function(test, err) {
        if (err.stack) {
          err.stack = stackFilter(err.stack);
        }

        return fail.apply(this, [test, err]);
      }
      mocha.fullTrace();
```

**Comment by danielstjules** [comment]
I think just changing `components` to `bower_components` would be an immediate fix. I agree that components is too general of a term for a filter criteria. Beyond that, a regexp option for filtering the stacktrace would work well too.

**Comment by aaronjensen** [comment]
:+1:

**Comment by danielstjules** [comment]
Proposed solution in https://github.com/mochajs/mocha/pull/1880

**Comment by donaldpipowitch** [comment]
Any way to do custom filtering in v3?

**Comment by drazisil** [comment]
Merged PR https://github.com/mochajs/mocha/pull/1880
