### ISSUE TITLE
stack traces are useless

### ISSUE THREAD

**Issue by wonnage** [mochajs/mocha#1863]
```
Chrome 45.0.2454 (Mac OS X 10.10.5) ERROR
  Uncaught TypeError: Cannot read property 'actions' of undefined
  at /Users/vlin/workspace/source-2/responsive-web/src/tests.bundle.js:55939:0 <- webpack:///src/modules/flux-context/index.jsx:41:8
Chrome 45.0.2454 (Mac OS X 10.10.5): Executed 0 of 0 ERROR (1.175 secs / 0 secs)
```

Great? Could really use more than one line of context here. I'm not sure if the problem lies in mocha, karma-webpack, webpack, karma, babel, or any of the other bricks in the towering abomination of build tools we've constructed...

**Comment by danielstjules** [comment]
What version of mocha are you using? Wondering it it's an issue with stacktrace filtering, since we have a couple open issues. Could you you post the output with mocha 2.2.0?

**Comment by wonnage** [comment]
Hey @danielstjules,

That output came from 2.2.1. After doing some more digging it looks like the truncated stack traces happen when there's a crash in the test setup (tests haven't actually started running yet). If you point me towards where to look for the stacktrace filtering logic I can investigate more.

**Comment by dmitriiabramov** [comment]
that doesn't have anything to do with mocha though. It's the way karma+babel+webpack build the test file

**Comment by danielstjules** [comment]
Stack filtering was introduced in 2.2.2 though, so it's likely unrelated to mocha

**Comment by wonnage** [comment]
Gotcha. Thanks!

**Comment by silvenon** [comment]
@wonnage you could set `devtool` to `source-map` in your webpack config and use [node-source-map-support](https://github.com/evanw/node-source-map-support) with Mocha by passing `--require source-map-support/register`. This will report line lumbers from the source, not the compiled bundle.
