### ISSUE TITLE
Single-expression ES6 arrow functions being treated as Promises

### ISSUE THREAD

**Issue by OOPMan** [mochajs/mocha#1865]
I have some test code I am converting to ES6.

The ES5 version of the code is as follows:
```
it("should be a function", () => {
    test.function(encapsulate);
});
```

Converting it to ES6 Arrow functions one would think to use the following form:
```
it("should be a function", () => test.function(encapsulate));
```

Unfortunately, this test fails because Mocha seems to think that if a value is returned by a test it *must* be a Promise and works on the assumption that is is one. This breaks the above form.

Instead, one is forced to do the following:
```
it("should be a function", () => { test.function(encapsulate) });
```

While there isn't much difference I do think the 2nd form is optimally readable and it would be nice if Mocha allowed some way to handle it...

**Comment by danielstjules** [comment]
https://github.com/mochajs/mocha/blob/master/lib/runnable.js#L290 Does `test.function` not return a promise? Just a plain 'old function?

**Comment by danielstjules** [comment]
Expanding on your example, things seem to be working as expected

``` javascript
var test = {
  function: function(fn, cb) {
    return fn(cb);
  }
}

function encapsulate(cb) {
  setTimeout(() => {
    console.log('RUNNING');
    cb();
  }, 1000);
}

it("should be a function", (done) => test.function(encapsulate, done));

// -----------------------------------
// Transpiles to
// -----------------------------------

"use strict";

var test = {
  "function": function _function(fn, cb) {
    return fn(cb);
  }
};

function encapsulate(cb) {
  setTimeout(function () {
    console.log('RUNNING');
    cb();
  }, 1000);
}

it("should be a function", function (done) {
  return test["function"](encapsulate, done);
});

// -----------------------------------
// And outputs
// -----------------------------------

$ mocha example.js


RUNNING
  ✓ should be a function (1003ms)

  1 passing (1s)
```

Is your spec async? If so, and you're not returning a promise, you still need handle the callback function. Something like:
```
it("should be a function", (done) => test.function(encapsulate, done));
```

**Comment by OOPMan** [comment]
Aaaah, okay. I wasn't under the impression my spec was async but I guess it must be?

You can check the entire source at https://github.com/OOPMan/encapsulate/blob/master/test/encapsulate.es6

**Comment by danielstjules** [comment]
Is there an exception being thrown when you run your specs? If mocha were to assume it was a promise, then it'd throw from the lack of a `then` property on the returned function.

**Comment by danielstjules** [comment]
E.g.

``` javascript
$ cat example.js
it('test', function() {
  // this will pass, as it's not returning an object with a then function
  return false;
});

it('promise like', function() {
  // this spec will fail as it's not a real promise
  return {
    then: function() {
      console.log('this ran');
    }
  };
});

$ mocha example.js


  ✓ test
this ran
  1) promise like

  1 passing (2s)
  1 failing

  1)  promise like:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by OOPMan** [comment]
I don't think an exception is being thrown. When I modify the arrow functions to be of the form ```() => { //single expression }``` everything works fine.

As soon as I remove the braces I get the error noted.

**Comment by danielstjules** [comment]
> As soon as I remove the braces I get the error noted.

What is the error being thrown though? The original post only mentions
> Unfortunately, this test fails because Mocha seems to think that if a value is returned by a test it must be a Promise and works on the assumption that is is one. This breaks the above form.

**Comment by danielstjules** [comment]
Changing one of the specs to:
``` javascript
        it("should produce a function", () => {
            console.log(test.function(instantiator).then)
            test.function(instantiator)
        });
```
Reveals that `unit.js` returns an object with a `then` function. It seems to be an invalid promise implementation, as seen below:
``` javascript
test.function(instantiator).then(function(res) {
    console.log('res', res)
}, function(err) {
    console.log('err', err);
});

// Runs both resolve and reject callbacks
// res undefined
// err undefined
```

So that's either a bug with https://github.com/unitjs/unit.js or it's simply not meant to be used that way. Might wanna ping them! :)

**Comment by OOPMan** [comment]
Awesome, will do.

**Comment by Nicolab** [comment]
Hello,

it's not a bug of Unit.js see in the guide [http://unitjs.com/guide/helpers.html#then-](http://unitjs.com/guide/helpers.html#then-) and in the [API doc](http://unitjs.com/api/helpers.html#then)

The method `then` is a BDD style (Given / When / Then). It does nothing, is just pass-through method for a fluent chain. If a function is passed, it is called.

If you want with a promise, look [http://unitjs.com/guide/promise.html](http://unitjs.com/guide/promise.html) (promisified: Given / When / Then)

**Comment by danielstjules** [comment]
Thanks for the clarification! :)

**Comment by Nicolab** [comment]
NP :)
