### ISSUE TITLE
remove lodash.create for npm < v1.3.7 support

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#1868]
prompted by #1867

**Comment by boneskull** [comment]
@dougwilson just gotta update the changelog and publish

**Comment by dougwilson** [comment]
Thanks, @boneskull . Now that 2.3.2 is finally published, I tried it out, and still no dice: 2.3.2 still does not install. The new version of `jade` in 2.3.0 now has multiple dependencies with `^`: https://github.com/jadejs/jade/blob/1.11.0/package.json#L25-L36

**Comment by boneskull** [comment]
I think instead of reverting the Jade upgrade, it would be best to completely remove the dependency and either:

1. remove the htmlcov reporter--there are other tools available which generate HTML coverage and probably a lot better than Mocha does
2. move it to its own repo
3. make it an `optionalDependency`

Thoughts?

cc @mochajs/mocha

**Comment by dougwilson** [comment]
Hi @boneskull , is there any update here?

**Comment by travisjeffery** [comment]
I'm in favor of simply reverting the jade version.

**Comment by danielstjules** [comment]
Is there any disadvantage to using an older version of jade?

**Comment by dougwilson** [comment]
As far as I can tell, the jade upgrade was a "just because why not" upgrade (https://github.com/mochajs/mocha/issues/1811 and https://github.com/mochajs/mocha/pull/1835).

**Comment by boneskull** [comment]
I thought someone was having a problem with something, but I don't recall what.  Feel free to just revert it.

**Comment by dasilvacontin** [comment]
Revert jade as simple solution for now. Looking forward to remove the dependency via extracting reporters in the future.
