### ISSUE TITLE
remove npm upgrade in .travis.yml

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#1869]
currently we run `scripts/ensure-compatible.npm.sh` to upgrade npm if it's old.  since we want to retain support for old npm versions (for now), let's not do that.

**Comment by boneskull** [comment]
okay, this is not possible due to the `coffee-script` dev dep.

**Comment by boneskull** [comment]
so, theoretically, we are fine with npm pre-1.3.7 in *production*--i.e., `npm install mocha`

**Comment by boneskull** [comment]
cc @dougwilson

**Comment by dougwilson** [comment]
So, is `coffeescript` is only needed for development, or is it also needed to run the tests on Travis CI? If it is not needed to run tests, then you can always remove it before Travis CI does the install (similar to https://github.com/jshttp/mime-db/blob/master/.travis.yml#L13-L21).

**Comment by dougwilson** [comment]
And of course, if you actually do need `coffeescript` for running tests, you can always split tests in two parts (kinda like https://github.com/dougwilson/nodejs-depd/blob/master/.travis.yml#L13-L15 + https://github.com/dougwilson/nodejs-depd/blob/master/test/browserify.js#L9).

**Comment by dougwilson** [comment]
Looks like it is at least used in your `test-compilers` Makefile target https://github.com/mochajs/mocha/blob/master/Makefile#L55 We could probably jiggle things around to get it to work. If you are serious about removing the npm upgrade, let me know, and I can even perhaps work on a PR to do so instead of you feeling like the burden is on you :)

**Comment by boneskull** [comment]
Is it a big deal though?  Do you need to develop Mocha on a system with an old npm version?

**Comment by boneskull** [comment]
I have pushed code for 2.3.2 but haven't published yet

**Comment by dougwilson** [comment]
> Is it a big deal though? Do you need to develop Mocha on a system with an old npm version?

I have to be able to install mocha to test on the systems that I support. I'm not developing on those systems, but mocha is the test runner, so without being able to install mocha, I cannot run any tests against the systems that will be running production code, which would make using mocha not very useful to me.

**Comment by boneskull** [comment]
Well, you can still do that (in theory), you just can't `git clone` mocha and install its devdependencies.  Am I missing something?

**Comment by dougwilson** [comment]
No, you're not missing anything. The main problem right now is that if you cannot do the install on Travis with an old version of npm, you'll never notice when a change breaks the install process for production users.

**Comment by dougwilson** [comment]
In other words, it's generally in your favor for your CI process to prevent the need to make commits like https://github.com/mochajs/mocha/commit/c7a8fedd08c13315c2befcb99699abeda1a9f3b0 , but the current CI process in this repository does not assist in identifying breaking changes.

**Comment by boneskull** [comment]
Right.  

I'd consider a solution similar to what you posted above (https://github.com/dougwilson/nodejs-depd/blob/master/.travis.yml#L13-L15).  This is fine for CI, but if a user is running `npm test` locally, they will run into problems.  Two more ideas:

1. Have a `prepublish` script which installs `coffee-script` if the detected npm version is high enough (and if there's a env var that npm sets if it's installing in development mode?  failing that, presence of `.git/` may be sufficient), and then have a conditional which skips the test if `coffee-script` is not present.  

2. Tell Travis to upgrade npm (if necessary), install `coffee-script`, then downgrade it again, then `npm install`.  Because we know `coffee-script` would break an old npm, this is fine.  If *any other* dependency would break stuff, then the build would error.

I'm partial to #2 since it avoids modifying the dependencies or tests themselves.

**Comment by dougwilson** [comment]
>  This is fine for CI, but if a user is running npm test locally, they will run into problems. 

What problem will they run into? If you clone that repo and run the tests, you'll see there is no issue running them at all (the suggestion consisted of two different areas).

> and then have a conditional which skips the test if coffee-script is not present. 

That's my original suggestion, the one you referenced with the link to the .travis.yml file :)

> Tell Travis to upgrade npm (if necessary), install coffee-script, then downgrade it again, then npm install. Because we know coffee-script would break an old npm, this is fine. If any other dependency would break stuff, then the build would error.

I tried this in the past with my modules but was never able to get the downgrade to work. This means that I would not be successful in implementing this for you, so the implementation would have to be left on your shoulders :(

**Comment by dougwilson** [comment]
Sorry to interrupt the conversation, but now that 2.3.2 is finally published, I tried it out, and still no dice: 2.3.2 still does not install. The new version of `jade` in 2.3.0 now has multiple dependencies with `^`: https://github.com/jadejs/jade/blob/1.11.0/package.json#L25-L36

**Comment by dougwilson** [comment]
Sorry, moved the above comment into the proper issue thread :)
