### ISSUE TITLE
set up codeclimate properly

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#1870]
add a `.codeclimate.yml` or whatever the hell.

![screenshot](http://content.screencast.com/users/chiller/folders/Jing/media/bdefbbe2-3b36-4ec0-8815-3f03c830d59d/00000256.png) is a little embarrassing, even if it doesn't mean much

**Comment by dasilvacontin** [comment]
It seems like enabling the project on codeclimate will be enough. I guess only `Owner`s can do that.

**Comment by drazisil** [comment]
@boneskull @dasilvacontin It looks like any member should be able to do this, unless the third-party restrictions are in place. https://docs.codeclimate.com/docs/open-source-free#administering-open-source-repositories

**Comment by juergba** [comment]
We use Coveralls now.
