### ISSUE TITLE
IE8 compatibility

### ISSUE THREAD

**Issue by danielstjules** [mochajs/mocha#1872]
We should setup some unit tests or linting rules for verifying basic compatibility with IE8 and lower. An es5 shim might also work, but is a bit heavy.

https://github.com/mochajs/mocha/pull/1617
https://github.com/mochajs/mocha/pull/1858

**Comment by ScottFreeCode** [comment]
I'm going to go ahead and close this since we have IE8 tested in CI nowadays (and are thinking of dropping pre-ES5 support in a coming semver-major at some point).
