### ISSUE TITLE
error with out line info.

### ISSUE THREAD

**Issue by calidion** [mochajs/mocha#1873]
1) sails GroceryController should update store info

  60 passing (12s)
  1 failing

  1) sails GroceryController should update store info:
     Uncaught TypeError: undefined is not a function

only tells that there is undefined variable but don't given the line that have such variable

**Comment by danielstjules** [comment]
If you checkout the branch from https://github.com/mochajs/mocha/pull/1848, does that fix the problem?

**Comment by kevinburke** [comment]
(*Hopefully* it should since we are running the same project - sails - and saw our code get usable stack traces, but let me know!)
