### ISSUE TITLE
Command-line Flag for io.js support

### ISSUE THREAD

**Issue by jereme-leandev** [mochajs/mocha#1874]
Will there be a command-line flag to support io.js. I am having difficulties in running libraries like zombie.js. I hope we could have something like 
mocha --iojs

**Comment by danielstjules** [comment]
I don't think this is necessary given that iojs has merged back into node for v4.0.0, and you can symlink as necessary. For example, when using nvm:
```
$ nvm use 3.0.0
Now using io.js v3.0.0
$ node --version
v3.0.0
```
