### ISSUE TITLE
upgrade to 2.3.x makes markdown reporter fail

### ISSUE THREAD

**Issue by m90** [mochajs/mocha#1884]
When using mocha `2.3.x` together with the markdown reporter I am getting the following error:

```
/home/frederik/foobar/node_modules/mocha/lib/reporters/markdown.js:41
    suite.suites.forEach(function() {
                 ^
RangeError: Maximum call stack size exceeded
```
This is called using a npm script:

```
  "scripts": {
    "pretest": "jshint .",
    "test": "mocha test/.",
    "posttest": "cat README.install.md > README.md && mocha test/. -R markdown >> README.md"
  }
```

The test hook itself will pass just fine.

When I downgrade to `2.2.5` it will work as expected.

The test suite sems to be of no importance as I tried using:

```js
var assert = require('assert');
describe('test', function(){
  it('passes', function(){
    assert(true);
  });
});
```

and the issue persists.

**Comment by danielstjules** [comment]
Fixed via https://github.com/mochajs/mocha/pull/1876 We'll hopefully get a patch release out soon. Sorry about that!

**Comment by m90** [comment]
Wow that was *fast*. Sorry for missing the dupe and thanks for fixing!
