### ISSUE TITLE
2.3.{0,1,2} no longer installs on older npm versions

### ISSUE THREAD

**Issue by dougwilson** [mochajs/mocha#1887]
This is a new issue to continue discussion around this (previous https://github.com/mochajs/mocha/issues/1867 and https://github.com/mochajs/mocha/issues/1868). There were multiple attempts to fix this regression in 2.3.x, but there is still an issue. The currently known issue is the jade upgrade: jade was upgraded in 2.3.0 up past a major breaking version, which dropped npm supported versions.

@boneskull had some thoughts on what to do here: https://github.com/mochajs/mocha/issues/1868#issuecomment-138420357

**Comment by danielstjules** [comment]
Proposed fix for patch release: https://github.com/mochajs/mocha/pull/1888

**Comment by dasilvacontin** [comment]
Reverted jade in master via #1888.

**Comment by dougwilson** [comment]
Thank you, the current `master` branch installs fine on the older version of `npm`. Looking forward to the next `mocha` release :)

**Comment by boneskull** [comment]
@dougwilson I trust you'll let us know of any similar issues in the future.  I can't guarantee Mocha v3 will keep the contract, but I'd like to ensure v2 will always work with npm pre-v1.3.7.  thanks for taking the time to let us know about the issue

cc @mochajs/mocha
