### ISSUE TITLE
Node 4.0 and Mocha Generator Functions

### ISSUE THREAD

**Issue by dschinkel** [mochajs/mocha#1891]
Just wondering if I need to try to use middleware such as gulp-mocha-co or mocha-generators since Node 4.0 includes support for generators via ES6.

So should we assume we should be able to now run tests like this with Node 4.0 which would use ES6 natively?

    it('should return all countries when no id passed', function*(done){

        ..some code
        responseModel.countries.should.have.length(2);
        responseModel.countries[0].id.should.equal(55);
        responseModel.countries[1].id.should.equal(10);
        done();
    });

**Comment by danielstjules** [comment]
ES6 supports generators, but coroutines are a little different. While you can might be able to use generator functions with specs, mocha doesn't do anything special for coroutine support (what allows you to yield promises) This was proposed in https://github.com/mochajs/mocha/pull/1575 but closed.

In the meantime, it looks like https://github.com/blakeembrey/co-mocha is the recommended solution! :)

**Comment by dschinkel** [comment]
ok thanks, I might have to slap back on gulp-mocha-co again.  That wraps co-mocha.

**Comment by dschinkel** [comment]
but then it's recommended not to run the harmony flag anymore https://nodejs.org/en/docs/es6/ which libraries like co-mocha depend on

**Comment by danielstjules** [comment]
co-mocha doesn't depend on the `--harmony` flag, it only depends on generators being enabled. With node 4, they're enabled by default. So if you were using `--harmony-generators` or `--harmony` with node 0.12 or iojs, you don't need those flags anymore :)

**Comment by dschinkel** [comment]
thanks for the reply.

**Comment by dschinkel** [comment]
well I'm using gulp-mocha-co so don't know if I can just just mocha-co in that case

**Comment by danielstjules** [comment]
Oh, gulp-mocha-co uses a fork of mocha (https://github.com/ilkkao/co-mocha) Didn't realize that.

Instead, I'd just use: https://github.com/sindresorhus/gulp-mocha with https://github.com/blakeembrey/co-mocha Then, your config could look something like:

``` javascript
var gulp = require('gulp');
var mocha = require('gulp-mocha');

gulp.task('default', function () {
    return gulp.src('test.js', {read: false})
        .pipe(mocha({require: 'co-mocha'}));
});
```
