### ISSUE TITLE
Wrong line numbers in stack traces if a test fail

### ISSUE THREAD

**Issue by anthony-o** [mochajs/mocha#1892]
When my tests fail, I'm having wrong line numbers in stack traces.

Look at this stackoverflow: http://stackoverflow.com/q/25770946/535203

**Comment by dasilvacontin** [comment]
Mocha version? Can you provide simple code that reproduces the issue?

**Comment by anthony-o** [comment]
I couldn't reproduce it, it is finally correctly giving me the line numbers, sorry !

**Comment by dasilvacontin** [comment]
No worries, glad you got it working :)

Let us know if you find any other bug!
