### ISSUE TITLE
How to test this kind of application

### ISSUE THREAD

**Issue by AlaRuba** [mochajs/mocha#1895]
Hi,

I'm using the cluster module and mocha to test it.

It seems when mocha finishes a test and exits (I get a new command line), it doesn't actually exit because I get all these statements, which are the print statements that I had the workers of cluster printout and some mocha stuff 

 1) "before all" hook

  0 passing (2s)
  1 failing

  1)  "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

  1) "before all" hook

  0 passing (2s)
  1 failing

  1)  "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

  1) "before all" hook
  1) "before all" hook

  0 passing (2s)
  1 failing

  0 passing (2s)

  1 failing

  1)  "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

  1)  "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

  1) "before all" hook

  0 passing (2s)
  1 failing

  1)  "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

  1) "before all" hook

  0 passing (2s)
  1 failing

  1)  "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

  1) "before all" hook
  1) "before all" hook

  0 passing (2s)
  1 failing
  0 passing (2s)
  1 failing

  1)  "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

  1)  "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

I was wondering how to test cluster using mocha. Thanks.

**Comment by drazisil** [comment]
This is an old question. Even though it was never answered, the OP never checked back, so I assume they found a solution.
