### ISSUE TITLE
Issue with beforeEach hook

### ISSUE THREAD

**Issue by poorvikamahesh** [mochajs/mocha#1899]
Hello All,

I am new to JS and mocha.
My code looks something like this -

``` javascript
describe ("MODULE 1 ", function(){
    beforeEach(function (){
        //Some actions to complete before each Test Case
    });

    it("TestCase 1", function(){
    });

    context("TestCase 2", function(){
        it("Step 1" function(){
            //1st part of the test case
        });
        it("Step 2" function(){
            //2nd part of the test case continue after 1st part
        });
    });
});
```

My issue is, I want the beforeEach method to run before every test case only, and not before each 'it' method. Is there a way to do that.

Right now my test case runs like below -
beforeEach > it(TestCase 1) > beforeEach > context(TestCase2) > it(Step 1) > beforeEach > it(Step 2)

Is there anyway to run the script as below - 
beforeEach > it(TestCase 1) > beforeEach > context(TestCase2) > it(Step 1) > it(Step 2)

**Comment by cowboyd** [comment]
@poorvikamahesh It sounds like what you might be looking for is the `before` hook. It will be run *once* for each `describe`/`context` block, but not before every `it` block.

That said, my personal experience is that using `beforeEach` is actually most often the thing that I want.

**Comment by drazisil** [comment]
Question answered, no reply from OP in 2.5 years, closing
