### ISSUE TITLE
Add a way of a programmatically skipping a test

### ISSUE THREAD

**Issue by gajus** [mochajs/mocha#1901]
> I have a code where certain tests will always fail in CI environment. I would like to disable them based on an environment condition.
> How to programmatically skip a test in mocha during the runtime execution?

– http://stackoverflow.com/q/32723167/368691

**Comment by gajus** [comment]
There does not appear a way to conditionally skip tests from the program itself, e.g.

```js
describe('foo', (d) => { 
    before(() => {
        d.skip();
    });

    it('foo', (i) => { 
        i.skip();
    });
});
```

**Comment by danielstjules** [comment]
Hm, have you tried:
``` javascript
$ cat test.js
describe('foo', function() {
  before(function() {
    this.skip();
  });

  it('foo', function() {
    // will not run
    console.log('This will not be printed');
  });
});
$ mocha test.js


  foo
    - foo


  0 passing (9ms)
  1 pending
```

Async skip will hopefully land in the next minor release via https://github.com/mochajs/mocha/pull/1618

**Comment by danielstjules** [comment]
In your example above:
``` javascript
describe('foo', (d) => { 
    before(() => {
        d.skip();
    });
//...
});
```

d is undefined. Mocha doesn't pass anything to functions that wrap suites, only specs.

**Comment by gajus** [comment]
Where is this documented?

**Comment by lukealbao** [comment]
This is not documented as far as I can tell. I was looking to do the same thing and having trouble. The problem was an outdated version of Mocha. Updating to 2.3.3 allows me to do this:

```javascript
describe('skipping', function () {
  it('should skip', function () {
    var u = false;
    this.skip();
    expect(u).to.equal(true); // <= Will not throw because it's skipped
  });
});
```

You can see that this was added in 718c411.

**Comment by felixfbecker** [comment]
How about this?
```js
describe('something', function () {
  (os === 'windows' ? it : it.skip)('should do something that doesnt work on windows', function () {
    
  })
})

**Comment by mislav** [comment]
Skipping tests is broken right now in 2 ways. See fixes in https://github.com/mochajs/mocha/pull/1945#issuecomment-170399078.

* It's broken when `skip()` is invoked within hooks such as `before()`
* It's broken when `skip()` is called within individual test combined with HTML reporter.

**Comment by jdmarshall** [comment]
I think you telegraph the problem better if you tag the troublesome tests and use a mocha test filter in your build environment.  In addition to tests failing in CI, it's not uncommon to have tests that fail on Dev.  **note that I am not condoning this situation, only acknowledging that it exists.**

I think conditional logic conceals problems that should be surfaced, and loudly.  Nonfunctioning tests are legitimate concerns, and burying them in the spec file means fewer eyeballs on the problem.

**Comment by mislav** [comment]
Agreed that using `skip` too often in a test suite should be in general considered a code smell. However, for those rare cases where you need it (e.g. having a browser test suite that should run one test only in capable browsers, but that test needs to be skipped in PhantomJS due to lack of browser support) it would be great if it just worked.

Right now Mocha offers this feature, but it wasn't working well historically (unsure of the state in latest stable version of Mocha). It would be great that if there's a test suite feature, it at least worked.

**Comment by jdmarshall** [comment]
And I'm going to reiterate that I believe tests that don't work in Phantom should be tagged as such and any build that runs on phantom should filter those tests out.  

It is immediately clear from the build history that only part of the tests were run.

**Comment by boneskull** [comment]
The problems with `this.skip()` should be fixed in v3, if not `master`.  Please reopen if `master` does not address the problem(s).
