### ISSUE TITLE
Hooks inside 'describe' not firing

### ISSUE THREAD

**Issue by dacodekid** [mochajs/mocha#1904]
```javascript
describe('Hooks', function() {
  console.log('Prints')  // <--------------- Prints
  before('Fire Up', function() {
    console.log('Nope') // <---------------- Not this one
  });

  after('Cleanup', function() {
    console.log('Nope') // <---------------- Not this one
  });
});
```

But they are working fine, if I remove the 'describe' block

**Comment by danielstjules** [comment]
Did you try adding a single spec?

``` javascript
$ cat test.js
describe('Hooks', function() {
  console.log('Prints');
  before('Fire Up', function() {
    console.log('Nope');
  });

  after('Cleanup', function() {
    console.log('Nope');
  });

  it('test', function() {});
});

$ mocha test.js
Prints


  Hooks
Nope
    ✓ test
Nope


  1 passing (2ms)
```

**Comment by dacodekid** [comment]
@danielstjules - Thank You. adding a spec works.  Is it a 'workaround' or a requirement?

Also, I wrapped the blocks inside "it" spec and only "after" hook firing up.

```javascript
describe('Hooks', function() {
  console.log('Prints');
  it('before', function() {
    before('Fire Up', function() {
      console.log('Nope from before');
    });
  });

  it('after', function() {
    after('Cleanup', function() {
      console.log('Nope from after');
    });
  })
});
```
```
Prints


  Hooks
    ✓ before
    ✓ after

Nope from after

  2 passing (23ms)
```

Adding both (before & after) under one spec also only fires up 'after' hook.

```javascript
describe('Hooks', function() {
  console.log('Prints');
  it('before', function() {
    before('Fire Up', function() {
      console.log('Nope from before');
    });

    after('Cleanup', function() {
      console.log('Nope from after');
    });
  })
});
```

```
Prints


  Hooks
    ✓ before

Nope from after

  1 passing (20ms)
```

**Comment by danielstjules** [comment]
I suppose a requirement :) It doesn't really make sense to have hooks run if a suite is empty.

As for your last couple examples, hooks are supposed to be used outside of specs. Anything else is undefined behavior. So typically, you'd do:

``` javascript
var assert = require('assert');

describe('suite', function() {
  before(function() {
    console.log('before');
  });

  after(function() {
    console.log('after');
  });

  it('test', function() {
    assert(true);
  });
});
```

**Comment by dacodekid** [comment]
That makes sense.  Thx :).  But I'm still baffled with why just the 'after' hook runs but not the 'before' inside the spec.

**Comment by kunagpal** [comment]
@danielstjules This doesn't appear to work if the `it` block from your previous snippet is replaced by a `describe` block, like so:

```javascript
var assert = require('assert');

describe('suite', function() {
  before(function() {
    // setup
    console.log('before');
  });

  after(function() {
    // cleanup
    console.log('after');
  });

  describe('test', function() {
    // one or more it blocks go here.
  });
});
```

Is there a workaround?

**Comment by danielstjules** [comment]
@kunagpal That's because there's no specs :) Adding a nested `it` should resolve this!

**Comment by kunagpal** [comment]
@danielstjules I see. Would it be possible for Mocha to acknowledge non-empty describe blocks like the one described above as a valid spec for hooks?

**Comment by danielstjules** [comment]
But that `describe` defines an empty suite - there's no specs. And hence no setup or teardown to perform. I'm not sure why this would be desirable.

**Comment by kunagpal** [comment]
Yes, but I was wondering about cases where the describe blocks are non-empty. Of course, the discussion would make little sense if blank describe blocks were involved.
