### ISSUE TITLE
Using mocha programmatically: make mocha not exit when running many tests?

### ISSUE THREAD

**Issue by mikemaccana** [mochajs/mocha#1908]
I am attempting to run mocha over a variety of specific submodules at once, and have followed (and contributed to) https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically.

However as soon as the first test suite completes, even with 0 failures, mocha exits the process. How can I make mocha not exit the process? Thanks!

**Comment by seawatts** [comment]
I think there is an option `--no-exit`
