### ISSUE TITLE
Hanging after assert.deepEqual

### ISSUE THREAD

**Issue by flippmoke** [mochajs/mocha#1915]
I have run into a problem where mocha hangs forever in garbage collection using 100% cpu rather then ending.

I have narrowed all this down to a simple test case I have created in this [repo](https://github.com/flippmoke/mochaAssertHang).

I am using node version `v0.10.35`.

You can replicate the error by doing:

```
git clone git@github.com:flippmoke/mochaAssertHang.git
cd mochaAssertHang
npm install
npm test
```

You will note however, that simply running `node ./index.js` will not hang and will just output the exception thrown from `assert.deepEqual`.

I traced back the last working version of this with mocha and it works properly with `2.2.1` but fails with later versions of mocha.

Here is a screen cap of a sample of the process while hung, as you can see it seems to be stuck doing garbage collection.

<img width="955" alt="screen shot 2015-10-06 at 5 58 50 pm" src="https://cloud.githubusercontent.com/assets/1794907/10326786/0a2e6b78-6c54-11e5-885d-020df60df233.png">

**Comment by flippmoke** [comment]
After digging found that it hangs at this line:

https://github.com/mochajs/mocha/blob/0c702772302d4e62f8d9132122ad17880f3ac709/lib/reporters/base.js#L413

Therefore this seems to be a problem with `diff` package.

This would also make sense as this commit https://github.com/mochajs/mocha/commit/789ac581c0f0feb34805b2c1373df8b38df0e7c9 would have changed the diff version about the right time.

**Comment by flippmoke** [comment]
Created an issue on `jsdiff` and will see if there can be any resolution because the latest version of `jsdiff` (`diff`) still does not seem to solve the issue.

**Comment by mojavelinux** [comment]
This could be the same problem as described in this issue: https://github.com/chaijs/chai/issues/1109. I've provided a workaround (at least for chai).
