### ISSUE TITLE
Best way to extend bdd.js UI

### ISSUE THREAD

**Issue by tauren** [mochajs/mocha#1917]
I'd like to create a new custom UI based on `bdd.js`. This UI would have all of the existing BDD functionality plus a few additional functions that I need to attach to `context`.

The [Third-party-UIs page](https://github.com/mochajs/mocha/wiki/Third-party-UIs) illustrates how to create a new UI from scratch, but doesn't show how to _extend_ an existing UI with additional functionality.

Is there a good way to do this?

**Comment by drazisil** [comment]
This is an old question. Even though it was never answered, the OP never checked back on it so assuming they found a solution.
