### ISSUE TITLE
Grep URLs escaped incorrectly

### ISSUE THREAD

**Issue by Saulis** [mochajs/mocha#1924]
If a test suite has a name that contains a `.` it will be escaped as `\.` in the grep URL. For example `test-suite.html` becomes `test-suite\.html` which translates incorrectly into a link `...?grep=test-suite%5Chtml`

In mocha v2.2.5 the URL is escaped like [this](https://github.com/mochajs/mocha/blob/2b2c576e580abaae90ef9e0c8cdedcc333460028/mocha.js#L2839):
`return window.location.pathname + (search ? search + '&' : '?' ) + 'grep=' + encodeURIComponent(s);`

But after commit a81e5558f086808b682b6d196b80893d2c8926f8 in v2.3.0 it has been escaped like [this](https://github.com/mochajs/mocha/blob/a81e5558f086808b682b6d196b80893d2c8926f8/mocha.js#L2465): `return window.location.pathname + (search ? search + '&' : '?') + 'grep=' + encodeURIComponent(escapeRe(s));`

Can't tell if this change has been done intentionally or not...

**Comment by boneskull** [comment]
this needs to be confirmed.

**Comment by JoshuaKGoldberg** [comment]
At this point, many years later, we can assume it's the intended behavior. 

If someone feels strongly that I'm wrong here, please file an issue with one of our new templates. We'd be happy to take a look!
