### ISSUE TITLE
array of errors instead of just single error

### ISSUE THREAD

**Issue by ORESoftware** [mochajs/mocha#1925]
Is it at all possible to pass an array of error objects to done()

some of my tests naturally generate multiple errors

I know it's a little crazy, but could we handle

``` javascript
var errArray = [];
done(errArray);
```

?

**Comment by danielstjules** [comment]
Would it not make more sense to define these as separate, isolated tests?

**Comment by ORESoftware** [comment]
ideally yes, but in some cases we all know there can be multiple errors and we don't just want to fail out on the first one

**Comment by ORESoftware** [comment]
for example I have a lib that returns all the instances of require
statements that correspond to to missing entries in dependencies in
package.json

...how would I pass back one error instance from my lib to mocha
representing multiple errors that yet don't have a stack trace or anything
like that? is there a best practice for this?

I just want to know a good way to do this. as you can see my lib is all or
nothing you cant break it into different mocha tests

**Comment by danielstjules** [comment]
Can you link to the lib? If the library finds statements that correspond to missing dependencies in package.json, why not invoke a function that returns a name of each of these missing deps? Why does that function need to return an error per module. Wouldn't it be nicer to have a single error like:
"Error: Required packages missing from package.json: bluebird, co, express, redis, sqlite"

**Comment by ORESoftware** [comment]
yes, that's about right except it would be better to have

"error: missing dependencies

path/to/file/x
a
b
c

path/to/file/y
d
e

path/to/folder/file/z
f
g
h"

so I want that kind of output with a mocha test somehow

I don't think returning an error from my lib with the above as a string
argument will get it right?

**Comment by ORESoftware** [comment]
my goal is to make this dependency check a mainstay in developer teams'
test suite so that they never deploy code with missing dependencies

there is one other module that does this but they do it wrong and it's very
unreliable..this needs to be 100% reliable.

**Comment by papandreou** [comment]
Unless the individual stack traces matter, I recommend squashing all the errors into a single `Error` instance and be done with it. The error message can be multi-line and read as a report of all the offences your dependency checker found.

**Comment by ORESoftware** [comment]
alright will give it a go

**Comment by drazisil** [comment]
No response from OP in 2.5 years, closing.
