### ISSUE TITLE
Stream does not read in tests

### ISSUE THREAD

**Issue by spamguy** [mochajs/mocha#1929]
Running mocha 2.3.3. I have a simple app to read a big file by stream:

```
var fs = require('fs'),
    path = require('path'),
    stream = fs.createReadStream(path.join(__dirname, 'datc_v2.4_06.txt'), { encoding: 'utf8' }),
    expect = require('chai').expect;

console.log(fs.readFileSync(path.join(__dirname, 'datc_v2.4_06.txt')));

stream.on('error', function(err) {
    debugger;
});

stream.on('data', function(line) {
    debugger;
});

stream.on('end', function() {
    debugger;
});
```

If I run `node-debug myfile.spec.js`, the breakpoints are hit right away.

If I run `mocha myfile.spec.js --debug-brk`, the code walks through the topmost code and then exits. No stream events are triggered, no breakpoints are hit. Needless to say any other logging or efforts to demonstrate this haven't worked. My only conclusion is that somehow mocha is preventing my stream from reading properly. *But*, the readFileSync() dumps correctly, so I have no idea what's going on.

**Comment by travisjeffery** [comment]
you haven't defined any tests so mocha isn't finding anything to run. wrap your streaming with 

``` js
it('should do w/e', function(done) {
...
});

and it'll run the stream code
