### ISSUE TITLE
Mocha Integration Tests Timing out

### ISSUE THREAD

**Issue by dschinkel** [mochajs/mocha#1930]
I've got a problem whereas sometimes my tests fail due to the asserts being run before the response comes back here in my integration tests:

```
   it('should find all countries when no id is specified', co.wrap(function *(){
        var uri = '/countries';
        var response = yield request.get(uri);

        should.exist(response.body);
        response.status.should.equal(200);
    }));
```
Not sure how to tweak mocha or supertest to wait or if I should use a promise here or what. I'm using generators with mocha here.

I'm using Supertest to make the requests...so they are hitting a real database.

**Comment by marcelocure** [comment]
I would use a promise, something like

 it('should find all countries when no id is specified', co.wrap(function *(){
        var uri = '/countries';
        $http.get(uri)
        .then(function(response){
             should.exist(response.body);
             response.status.should.equal(200);
        });
    }));

**Comment by dschinkel** [comment]
I'm using generators...and prefer to keep it that way :)

**Comment by danielstjules** [comment]
You might like https://github.com/blakeembrey/co-mocha :)

As for the assertion running before the response is received, it doesn't seem as likely from the snippet above. I'm guessing there's more to the issue. Could you maybe create some small working reproduce case that sometimes fails? Thanks!

**Comment by dschinkel** [comment]
yea thanks for trying.  I'm using co-mocha already WITH co-wrap.

**Comment by danielstjules** [comment]
You shouldn't need to use both. The whole idea behind co-mocha is that it'll wrap generator functions. But if you pass a function wrapped by co.wrap, it's already a promise, so co-mocha doesn't touch it.

**Comment by danielstjules** [comment]
But let us know if you can create a small failing example! :)

**Comment by travisjeffery** [comment]
i would just use co-mocha, i've used it one tons of projects and never had an issue. so your code would look like:

``` js
  it('should find all countries when no id is specified', function *(){
        var uri = '/countries';
        var response = yield request.get(uri);

        should.exist(response.body);
        response.status.should.equal(200);
    });
```

**Comment by dschinkel** [comment]
Yea I'lll have to retry co-mocha, I just remember the generators didn't work when I tried but will try it again.

**Comment by travisjeffery** [comment]
sounds good, i'm gonna close this. if you can make small reproducible example of this then feel free to comment with a link and i'll reopen. thanks.
