### ISSUE TITLE
Mocha output readability is worse when using Bunyan or other logging facilities

### ISSUE THREAD

**Issue by ORESoftware** [mochajs/mocha#1934]
Is there a good way to marry a logging module like Bunyan with Mocha? I find that the output from Mocha becomes _harder_ to read, not easier, when piping through Bunyan - but I do want Bunyan because then I can ignore higher levels of logging output that don't matter in my tests.

Is there a good solution? Will Mocha start using a logging module?

**Comment by kaiquewdev** [comment]
You have the reporters for that and it is possible to write a new one who perfectly fit your needs.

https://mochajs.org/#reporters [default reporters]
https://www.npmjs.com/search?q=mocha+reporter

**Comment by ORESoftware** [comment]
thanks that helps

**Comment by blurab** [comment]
Hi,

I've write a reproter that provide a pretty output of bunyan logs when you run mocha:
http://stephanechretien.blogspot.fr/2016/06/nodejs-bunyan-mocha-glup.html
https://www.npmjs.com/package/mocha-pretty-bunyan-nyan

**Comment by drazisil** [comment]
Question appears answered per the OP, closing
