### ISSUE TITLE
Execute the same test suite several times with multiple configurations

### ISSUE THREAD

**Issue by jabrena** [mochajs/mocha#1939]
Hi, 

I would like to execute the same test suite, a set of tests in the same folder several times with a different configuration.

Is it possible?

**Comment by chilicoder** [comment]
Not sure, what exactly is your situation. Why can't you do it outside of the mocha?

**Comment by jabrena** [comment]
I found a solution:

```
  "scripts": {
    "preversion": "mocha test --config=LOCAL_INSTANCE_1",
    "start": "node index.js",
    "test": "mocha test --config=LOCAL_INSTANCE_1 && mocha test --config=PIVOTAL && mocha test --config=BLUEMIX"
  },
```

File:
https://github.com/prosociallearnEU/cf-nodejs-client/blob/master/package.json
