### ISSUE TITLE
Can't resolve absolute path in mocha tests

### ISSUE THREAD

**Issue by chilicoder** [mochajs/mocha#1940]
I did some test using mocha and testem and found some wierd behavior of the path resolver.

The function

```
 function (postfix) {
     var result = process.cwd()+postfix;
     return result;
     };
```

that did return the absolute path with postfix didn't returned it but only postfix. And in normal environment it works as expected.

I created a supplementary [repo](https://github.com/chilicoder/bug-with-path) to show the bug. It raises in 0.10, 0.12 and 4.1 node versions.

Does anybody can explain where is the problem? Because now I can't resolve absolute path to file.

**Comment by kaiquewdev** [comment]
My guess

var path = require('path');
function getPath(p) { return path.resolve((__dirname || process.cwd()), p); }
