### ISSUE TITLE
beforeEach and afterEach affects tests in other files

### ISSUE THREAD

**Issue by Bartinger** [mochajs/mocha#1949]
When I create tests in different files and at least one of them includes the beforeEach or afterEach hook, those hook gets called for all tests.
You can reproduce this with the following code.

**test1.js**
```
module.exports = {
    	test1: function () {
    		console.log('test1');
    	}
};
```

**test2.js**
```
module.exports = {
	beforeEach: function () {
		console.log('beforeEach');
	},
	test2: function () {
		console.log('test2');
	}
};
```

Then run:
```
mocha -u exports --recursive .

beforeEach
test1
  ✓ test1
beforeEach
test2
  ✓ test2

  2 passing (8ms)
```

**Comment by ORESoftware** [comment]
hahaha if this is true this is really bad :) :+1:

**Comment by boneskull** [comment]
afaik this behavior is intended.  you aren't using a suite, so you're adding a `beforeEach` to the root suite, which would run it after every test.
