### ISSUE TITLE
Introduction to mocha.js on Global Ember Meetup

### ISSUE THREAD

**Issue by taras** [mochajs/mocha#1957]
*mocha.js* can be used with EmberCLI with `ember-cli-mocha` library. EmberCLI uses QUnit by default, so most people are not familiar with *mocha.js*. 

We have a "Ember Testing Day" coming up on [Global Ember Meetup](http://global-ember-meetup.com) in 2 weeks. Would someone who loves *mocha.js* be interested in coming on and giving a lightning talk about *mocha.js* and why use it?

**Comment by dasilvacontin** [comment]
Since it might not be obvious to everyone, it's worth pointing out that this is a Webinar.

**Comment by taras** [comment]
Yes, thank you :)

**Comment by dasilvacontin** [comment]
No problemo :)

**Comment by cowboyd** [comment]
@taras This is something that I feel pretty strongly about, so I'd be willing to take that on.

**Comment by taras** [comment]
@cowboyd sweet, would you be able to give a lightning talk about it on November 21st? https://www.bigmarker.com/global-ember-meetup/Ember-Testing-Day

**Comment by cowboyd** [comment]
@taras I can definitely do that.

**Comment by taras** [comment]
Sweet, I’ll add you to the list of talks. Look forward to it :)

-- 
Taras Mankovski

On November 13, 2015 at 10:38:12 AM, Charles Lowell (notifications@github.com) wrote:

@taras I can definitely do that.

**Comment by boneskull** [comment]
cool!
