### ISSUE TITLE
MOCHA_REPORTER environment variable as override for --reporter

### ISSUE THREAD

**Issue by viliusl** [mochajs/mocha#1959]
Challenge: I want to use default reporter when running tests locally (npm test) and https://www.npmjs.com/package/mocha-teamcity-reporter when running tests in ci. And I want this to be as transparent as possible for developers (given we have tens/hundreds of npm modules).

Do you think it makes sense to add this feature like:

default:
```
$ mocha
```

ci:
```
$ npm install -g mocha-teamcity-reporter
$ export MOCHA_REPORTER=mocha-teamcity-reporter
$ mocha
```

Thanks

**Comment by boneskull** [comment]
I don't think this is necessary.

`package.json`:

```json
  "config": {
    "mocha_reporter": "spec"
  },
  "scripts": {
    "test": "mocha --reporter ${NPM_CONFIG_MOCHA_REPORTER}"
  }
}
```

CI:

```shell
$ npm install -g mocha-teamcity-reporter
$ NPM_CONFIG_MOCHA_REPORTER=mocha-teamcity-reporter npm test
```

**Comment by fopinappb** [comment]
For those ending in this old issue like myself, use lowercase environment variable `npm_package_mocha_reporter` instead
