### ISSUE TITLE
invalid custom reporter

### ISSUE THREAD

**Issue by bonjonbovi87** [mochajs/mocha#1961]
Previously, we could just drop some `reporter.js` into `mocha/lib/reporters/` and it would be picked up.  However, the below commit removed that functionality and would now force you to add it to `reporters/index.js` for it to work.

Commit: https://github.com/mochajs/mocha/commit/a81e5558f086808b682b6d196b80893d2c8926f8

Any way we can add that back in, possibly like this?

``` javascript
if (reporters[reporter]) {
     _reporter = reporters[reporter];
}
else {
    try {
        _reporter = require('./reporters/' + reporter);
    } catch (err) {
        // Ignore
    }
}
```

**Comment by jfbibeau** [comment]
+1 also affected by this.

**Comment by ScottFreeCode** [comment]
Closing this as current versions of Mocha should allow custom reporters *either* as node_modules *or* relative to the directory in which the CLI is run, without need for putting anything in Mocha's folders.
