### ISSUE TITLE
`this` keyword does not get cleaned after each test

### ISSUE THREAD

**Issue by rodoabad** [mochajs/mocha#1971]
How come mocha does not `this` keyword for each test?

```javascript
describe.only('A spec', function () {

  beforeEach(function () {

    this.foo = 0;

  });

  it('can use the `this` to share state', function () {

    expect(this.foo)
      .to
      .equal(0);

    this.bar = 'test';

  });

  it('prevents test pollution by having an empty `this` created for the next spec', function () {

    expect(this.foo)
      .to
      .equal(0)

    expect(this.bar)
      .to
      .equal(undefined); // still 'test'
  });

});
```

**Comment by boneskull** [comment]
hooks and tests share state.

you can use `this` to share state between a hook and a test if you wish, but I wouldn't recommend it.

**Comment by schatekar** [comment]
@boneskull can I use `this` to share state if the hook is defined in a separate file?

**Comment by danielstjules** [comment]
Not if the tests belong to different suites.

``` javascript
$ cat test.js
describe('suite1', function() {
  it('test1', function() {
    this.foo = "foo";
  });
});

describe('suite2', function() {
  it('test2', function() {
    console.log(this.foo); // => undefined
  });
});
```

There's certainly ways to dynamically generate the test suite to get around that.

**Comment by rodoabad** [comment]
@danielstjules Yeah but there are scenarios where you want to bundle up a couple of tests together under one describe block.

**Comment by danielstjules** [comment]
@rodoabad But in that case, you can define them in the same file? Besides, it's a codesmell if you're sharing that much state between tests which should generally be isolated.

**Comment by rodoabad** [comment]
@danielstjules Sharing state between tests is a bad idea. I don't do it and I don't recommend it to anyone. I was just comparing `mocha` and `jasmine` and noticed this difference.

**Comment by boneskull** [comment]
if you need to share common code between two test files, just make a third file and `require()` it in both

**Comment by schatekar** [comment]
I understand sharing state across tests is not a very good idea. 

I am testing some APIs which need a token to be passed into the request header. This token needs to be obtained from the server first by creating a test user and authenticating it. While I can isolate this code into its own file and call it from each test I was wondering if I could execute this once and use the same token in every test. This would also make tests faster as I am not creating and authenticating user on every API call.

**Comment by boneskull** [comment]
Use `--require` and probably `--delay`
