### ISSUE TITLE
[Learning Help] Mocha done callback

### ISSUE THREAD

**Issue by DeChrish** [mochajs/mocha#1973]
Sorry if it is the wrong place to ask help.

I was learning mocha and its done call back. I have created a repo to test it.

Error : 
1)  should have sso session:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

Code repo:
 git@github.com:DeChrish/request-node.git

**Comment by dasilvacontin** [comment]
Hi @DeChrish! You can also put questions on our Gitter, you may get faster feedback: https://gitter.im/mochajs/mocha

The error mocha is giving is correct – your test code is never executing the `it`'s `done` callback (the function meant to be executed when your test finishes doing async stuff) and therefore the test times out after 2s, which is the default timeout value. The callback function you are giving to `requestFunction` in your code is never being executed.

If you look at `requestFunction`s definition at https://github.com/DeChrish/request-node/blob/master/src/hi.js#L4, you will notice that it doesn't even expect the `callback` argument you are trying to give it.

It should be something along the lines of:

```js
C.requestFunction = function (callback) { // <-- callback argument, a function to execute
  // so that you can notify the user of the function that you are done
  return request('http://www.google.com', function (error, response, body) {
     // error handling
     if (error) {
       callback(error) // <-- notify user about internal error
     }
     // notify the user of the callback that you are done via executing the callback
     // and pass in the results that you want to provide (first argument should be an error,
     // if any, and the second should be the results)
     callback(undefined, body)
  }
}
```

Your test will work after these changes. Though you might want to do something with the result passed via the `requestFunction` callback:

```js
var assert = require('chai').assert
it("should have sso session" , function(done){
  hi.requestFunction(function(err, body) { // <-- added a `body` result argument to the callback
    if (err) {
      return done(err)
    }
    assert(body === 'Hello world', 'websites body should be "Hello world"')
    done()
  });
});

Let us know if this helped you / solved your doubts! :)

**Comment by DeChrish** [comment]
Hi @dasilvacontin : Thanks a lot \o/ - it cleared my doubts ; Gitter is awesome ;

**Comment by gyashasvi** [comment]
Hi,
Error 
  Timeout of 500ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
please slove my error.
