### ISSUE TITLE
Markdown reporter doesn't understand `=>`functions from es6

### ISSUE THREAD

**Issue by diasdavid** [mochajs/mocha#1978]
I learned that when using the markdown reporter on tests with `=>` functions, mocha deletes the function call from the output completely

Example: 
- original code - https://github.com/ipfs/js-ipfs-api/blob/auto-docs/test/api/add.spec.js#L36-L40
- output with markdown reporter - https://github.com/ipfs/js-ipfs-api/blob/auto-docs/API.md#add
  ![image](https://cloud.githubusercontent.com/assets/1211152/11396685/57895a84-936b-11e5-8688-ec93b31fdce9.png)

**Comment by johnkpaul** [comment]
The links here are sadly broken now. 

@diasdavid Is this still relevant?

**Comment by diasdavid** [comment]
Not anymore, thanks for checking @johnkpaul :)
