### ISSUE TITLE
🚀 Feature: Return full error with window.onerror handler

### ISSUE THREAD

**Issue by roadhump** [mochajs/mocha#1979]
Now `window.onerror` handler from `support/browser-entry.js` creates new error with uncaught error message and short location. [Spec](https://developer.mozilla.org/en/docs/Web/API/GlobalEventHandlers/onerror) says that `window.onerror` has full uncaught error as last argument and it seems that all latest browsers support this spec. It would be great for reporting to return full uncaught error for mocha tests in browsers in case it is supported. I am ready to create PR if you find this idea ok.

**Comment by JoshuaKGoldberg** [comment]
I believe this was actually resolved by #4174. 🚀 

If I'm wrong about that, please file a new issue using one of our new templates. They'll ask for a bit more clarifying info that'll help explain why #4174 wasn't a resolution. Cheers!
