### ISSUE TITLE
Question:  Why is --harmony flag required for ES6 when using Node v4 locally?

### ISSUE THREAD

**Issue by mikrofusion** [mochajs/mocha#1990]
Spent some time trying to figure this out today and decided to open a question in hopes that someone here might know the answer.

I am trying to use ES6 + mocha without transpiling (i.e. Babel).  I am using Node 4.2.1 (which supports all the ES6 harmony features by default).

If I just run mocha test (without the --compile babel option) then I get errors whenever I use any ES6 features.  I can get around this by enabling the --harmony flag as part of the mocha cli options.

Since I am running node 4 I dont understand why the --harmony flag is required to use ES6 functionality with mocha.  From everything I can see in bin/babel mocha is just using my local node version.

As ES6 and Node 4 become more popular I am thinking this question might come up more and more - any help understanding this is greatly appreciated.

Thanks!

**Comment by danielstjules** [comment]
Works with node 4.2 and mocha 2.3.4:

```
$ node --version
v4.2.0
danielstjules:~
$ mocha --version
2.3.4
danielstjules:~
$ cat test.js
it('test', function() {
  console.log(`template string`);
});
danielstjules:~
$ mocha test.js


template string
  ✓ test

  1 passing (7ms)
```

**Comment by danielstjules** [comment]
If you run the following, what output do you get:
```
$ cat test.js
it('test', function() {
  console.log(process.version);
});
```

For me, it prints 4.2. In your case, I'm wondering if mocha is executing under an older version?

**Comment by mikrofusion** [comment]
@danielstjules thanks for the help!  Your examples worked for me, which led me to try to determine why it was only my code that was failing.  It appears I was trying to use default parameters, which is supported in babel, but not in the version of node 4 that I am running:  https://github.com/nodejs/node/issues/3070.

Thanks again for your help.
