### ISSUE TITLE
add/ the ability to tag test files for easy multi-topic coverage

### ISSUE THREAD

**Issue by davidpaulhunt** [mochajs/mocha#2012]
For large applications, it would be great to tag files using Mocha. We've made the switch from vows but lost that ability because of the difference in UI and how Mocha runs. As in, adding extra attributes to Mocha export tests fail because it tries to run the attribute as either a title or function. My solution proposed below is to offer the option of adding tags by using a utility `taggable.js`. For example:

``` js
var Taggable = require('mocha').Taggable;

module.exports = Taggable(['foo', 'bar'], {
  Foo: {
    '#new Foo()': {
      'foo should be of Foo': function() {
        var foo = new Foo();
        foo.should.be.instanceOf(Foo);
      }
    }
  }
});
```

Please see PR #2011 

If there is a better way to do this, please suggest it. Thanks!

**Comment by drazisil** [comment]
Connected to closed PR, closing
