### ISSUE TITLE
Passing URL parameters into components

### ISSUE THREAD

**Issue by taichatha** [mochajs/mocha#2013]
I'm trying to test a page component in React JS, but it relies on getting url parameters. When I try to test it in Mocha, I get this error:  

'var reset_key = this.props.params.reset_key ? this.props.params.reset_key : null;
                                         ^

TypeError: Cannot read property 'reset_key' of undefined'

Params being the url parameters.

This is when I try to build the component, even before I get to testing.

**Comment by danielstjules** [comment]
If you comment out that line and set a debugger, or console.log(this.props), is params defined? Closing because this wouldn't be an issue with mocha, but happy to help all the same :)
