### ISSUE TITLE
feature request: support customized command line parameters

### ISSUE THREAD

**Issue by mkatsoho** [mochajs/mocha#2015]
Currently mocha only support predefined cmdline parameters, but it reports error for any customized ones. It is common to use cmdline parameters due to, e.g. test against 'http://internal.abc.com', instead 'http://www.abc.com' in internal env. And using cmdline parameter is the most direct way. 

Two workarounds are
1) 'Using mocha programmatically' can read cmdline parameters as any other nodejs application
2) in test/mytest.js file, read a hardcode parameter file to get those parameters

If you agree, those 2 workarounds are indirect. It would helpful if providing cmdline parameters, such as

```
mocha -Dkey1=value1 -Dkey2=value2
mocha -Dkey1 value1 -Dkey2 value2
```

**Comment by plroebuck** [comment]
Consider using [dotenv](https://www.npmjs.com/package/dotenv)?

**Comment by outsideris** [comment]
These days, environment variables is a best practice and could solve this problem.
If you have another issue, please report it newly.
