### ISSUE TITLE
Mocha does not support Node 5.2

### ISSUE THREAD

**Issue by casertillo** [mochajs/mocha#2016]
Hi I am having this issue when trying to run "npm test" with mocha, I know that is clear that mocha does not support Node 5.2 but maybe should be a request or update.

MEAN.JS - Test Environment
Environment:			test
Port:				3001
Database:				mongodb://localhost/mean-test
App version:			0.4.2
MEAN.JS version:			0.4.2

Running "mochaTest:src" (mochaTest) task
>> Mocha exploded!
>> Error: Unsupported Node version: 5.2.0
>>     at Object.<anonymous> (/home/casertillo/NorthwindNode/node_modules/mock-fs/lib/index.js:35:9)
>>     at Module._compile (module.js:399:26)
>>     at Object.Module._extensions..js (module.js:406:10)
>>     at Module.load (module.js:345:32)
>>     at Function.Module._load (module.js:302:12)
>>     at Module.require (module.js:355:17)
>>     at require (internal/module.js:13:17)
>>     at Object.<anonymous> (/home/casertillo/NorthwindNode/modules/core/tests/server/core.server.config.tests.js:12:10)
>>     at Module._compile (module.js:399:26)
>>     at Object.Module._extensions..js (module.js:406:10)
>>     at Module.load (module.js:345:32)
>>     at Function.Module._load (module.js:302:12)
>>     at Module.require (module.js:355:17)
>>     at require (internal/module.js:13:17)
>>     at /home/casertillo/NorthwindNode/node_modules/mocha/lib/mocha.js:172:27
>>     at Array.forEach (native)
>>     at Mocha.loadFiles (/home/casertillo/NorthwindNode/node_modules/mocha/lib/mocha.js:169:14)
>>     at MochaWrapper.run (/home/casertillo/NorthwindNode/node_modules/grunt-mocha-test/tasks/lib/MochaWrapper.js:51:15)
>>     at /home/casertillo/NorthwindNode/node_modules/grunt-mocha-test/tasks/mocha-test.js:86:20
>>     at capture (/home/casertillo/NorthwindNode/node_modules/grunt-mocha-test/tasks/mocha-test.js:33:5)
>>     at Object.<anonymous> (/home/casertillo/NorthwindNode/node_modules/grunt-mocha-test/tasks/mocha-test.js:81:5)
>>     at Object.<anonymous> (/home/casertillo/NorthwindNode/node_modules/grunt/lib/grunt/task.js:264:15)
Warning: Task "mochaTest:src" failed. Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.

**Comment by boneskull** [comment]
not a mocha issue.  this error comes out of mock-fs.  upgrade mock-fs
