### ISSUE TITLE
options for ui

### ISSUE THREAD

**Issue by stalniy** [mochajs/mocha#2019]
I created "ui" library https://github.com/stalniy/bdd-lazy-var and want to add some configuration:
* global getters for variables
* getters on "get" function

depending on ui configuration. So, I have 3 suggesstions:
1. **Simple**: add options for UI, so "ui" libraries are able to be dependent on configuration (similar to `reporterOptions`)
2. **Even simpler**: inside `bin/_mocha` pass all arguments as options in `Mocha` constructor
3. **Conflicting**: allow to combine multiple ui-s (e.g. `new Mocha({ ui: 'bdd+lazy-var+lazy-var-global' })` or `new Mocha({ ui: [ 'bdd', 'lazy-var', 'lazy-var-global' ] })`. But this will allow to merge `tdd` and `bdd` ui-s which are so natural as `bdd` and `lazy-var`

Let me know your opinions and I would be able to create an appropriate PR

**Comment by boneskull** [comment]
see #1969, but I don't foresee a PR being accepted that does this.  Mocha will support this behavior out-of-the box.

**Comment by boneskull** [comment]
e.g.,

```js
const mocha = require('mocha');
mocha.use(require('mocha-ui-bdd')); // this is the default, so not necessary
mocha.use(require('mocha-ui-tdd')); // this does not overwrite the BDD UI
const {describe, setup, it} = mocha;
// bdd-style
describe('my thing', () => {
  // tdd-style
  setup(() => {
    // do setup
  });

  it('should do stuff', () => {
    // make assertion
  });
});
```
