### ISSUE TITLE
Mocha results gone

### ISSUE THREAD

**Issue by sateffen** [mochajs/mocha#2022]
Hey,

I've got a question, that drives me crazy like hell...

I'm using mocha in a couple of projects, and had never problems. I use [grunt-mocha-test](https://github.com/pghalliday/grunt-mocha-test) as grunt integration, and it works so far, no problems with it.

For using multible reporters one should rerun the tests, because mocha caches the result. That is great, and is very simple as well, so I'm using this in some private projects, as well as in our company. But since I installced mocha 2.3.4 only the first testrun has a reporter with data, every following call has no data. I switched back to 2.3.3, but it's not changing 0.0

As reference you can use my [node-package-boilerplate](https://github.com/sateffen/node-package-boilerplate) and change in _grunttasks/mocha.task.js_ the config to this:

```
    grunt.config('mochaTest', {
        run: {
            options: {
                reporter: 'spec',
                captureFile: 'test/results/result.txt',
                require: [
                    'test/setup/chai',
                    'test/setup/chaispies'
                ]
            },
            src: ['./test/tests/**/*.js']
        },
        runxunit: {
            options: {
                reporter: 'XUnit',
                captureFile: 'test/results/result.xml',
                quiet: false
            },
            src: ['./test/tests/**/*.js']
        }
    });
```

The XUnit run has no results, it's just empty.

I opened the bug here, because mocha seems to do something unintended, it doesn't rerun my tests, but the reporter is empty as well. Maybe someone here can help me, it worked for a long time, and now I don't get why not even mocha@2.2.5 or so will give me new results..

Can someone help me?

**Comment by sateffen** [comment]
Some infos, that might help: I've tried this on 3 different systems, 1 windows 7, 2 windows 10. All systems run NodeJS 5.2 with NPM 3.3.12

I didn't try different node versions, but when I've got some time left, that's the next thing to do. Maybe it's a node related problem?

**Comment by sateffen** [comment]
Tested with NodeJS 4.2.4 and NPM 2.24.12, same result. No results for the following reporter calls.

**Comment by sateffen** [comment]
I nailed it down, and the main problem is mocha, and my fail to read the documentation of something till the end.

First of all, the problem is already documented [here](https://github.com/pghalliday/grunt-mocha-test#running-in-permanent-environments-like-watch), so the problem is, that mocha operates on cache, not on the actual modules. Because of this, every following call to run mocha, even with a new instance, doesn't work.

I don't know if there are any other tickets regarding this issue, I didn't find anything, but in my opinion, there should be a way to fix this. For nodejs it's pretty simple, just create the modules by yourself, not by node, but I don't know, whether this works for the browser as well.

Any ideas or intentions?

**Comment by ORESoftware** [comment]
You could run your tests in a child process and that would not use the existing cache
