### ISSUE TITLE
🚀 Feature: Allow adding a description with the reason why a test is pending

### ISSUE THREAD

**Issue by basharov** [mochajs/mocha#2026]
I can add pending reason in Jasmine tests with `.pend()` method and replacing `it()` with `xit()` like this:

```
xit('should save settings when proper object is passed', function(){}).pend('No local storage is supported yet');
```

Can I somehow add a pending reason message for Mocha tests?

**Comment by gurdiga** [comment]
As a lightweight workaround, I would think of tweaking the test description to include the reason why it’s pending. :blush: 
```js
xit('works as expected; PENDING: waiting for a dependency to be implemented', function() {
});
```
I’m guessing this would work, but I curious to know how would such a feature be useful? :construction_worker:

**Comment by tommy-p** [comment]
This feature is pretty useful, is is not a good idea to mix test description and reason why test is pending. pend() method allows to distinguish pend reason from description. And instead of meaningless reason "No reason given" in jasmine you can add more info, issue number, etc.

**Comment by rdennis** [comment]
What would the syntax be for this feature? I would expect something like:
```javascript
// describe.skip = xdescribe
describe.skip('Foo', function () {
    ...
}, 'Reason Foo was skipped');

describe('Bar', function () {
    // it.skip = xit
    it.skip('#baz', function () {
        ...
    }, 'Reason #baz was skipped');
});
```

Or would a chained function be more readable?
```javascript
describe.skip('Foo', function () {
    ...
})
.because('Reason Foo was skipped');

describe('Bar', function () {
    it.skip('#baz', function () {
        ...
    })
    .because('Reason #baz was skipped');
});
```

**Comment by Nokel81** [comment]
I like the chain version since that seems to be the best inline with how the rest of mocha operates

**Comment by yuriy-g-eleks** [comment]
Any plans on adding this feature?

**Comment by fotoflo** [comment]
Using xit.() makes tests pending - which confused me as a new user because pending means "awaiting decision or settlement." - i assumed it was some async that hadn't completed. 

seems skipped would be a better description for xit. 

```
  24 passing (690ms)
  7 pending
```

**Comment by JoshuaKGoldberg** [comment]
Related to the discussion: #1815 tracks separating "pending" and "skipped" categories.

This needs discussion on how the feature should look. Maybe it should be the fluent API (`test(...).describe("...")`)? Maybe rolled into #928 (test metadata)?

**Comment by JoshuaKGoldberg** [comment]
> As a lightweight workaround, I would think of tweaking the test description to include the reason why it’s pending. 😊

Triaging with @voxpelli: amusingly, this first + simplest approach seems the most reasonable to us. We can see why an explicit indicator would be useful - but it's not a particularly common need, and adding a description to the test description is a pretty good workaround for most.

Closing as wontfix, as #928 (test metadata) would be a better holistic solution. Thanks all! 🤎
