### ISSUE TITLE
--fgrep doesnt work with --watch

### ISSUE THREAD

**Issue by VictorioBerra** [mochajs/mocha#2027]
### Expected

when using `--fgrep "my search string" --watch` one would think a file change would run tests with the provided fgrep string.
### Actual

all tests re-run when a file is changed as if `--fgrep` was never used.

**Comment by Fahrradflucht** [comment]
Confirmed! The `fgrep` flag is only recognised for the first test run. re-runs just run all tests. This is a major issue on large codebases.

**Comment by boneskull** [comment]
grep and watch don't play nice together.

**Comment by Janpot** [comment]
`--watch` + `--grep` used to work well for me. It just broke completely in `mocha@6` for me. It just runs `0` tests.

**Comment by Janpot** [comment]
To reproduce:
given the following test file:
```js
/* eslint-env mocha */
describe('testsuite', () => {
  it('test1', () => {});
  it('test2', () => {});
});
```
Running under v5:
```sh
$ npx mocha@5 --watch --grep test1
npx: installed 24 in 2.949s



  testsuite
    ✓ test1


  1 passing (5ms)
```
Running under v6:
```sh
$ npx mocha@6 --watch --grep test1
npx: installed 230 in 6.878s



  0 passing (1ms)
```

**Comment by plroebuck** [comment]
@Janpot, already fixed in #3755.

**Comment by boneskull** [comment]
rather, it'll be fixed when it's released.

duplicate of #3748

**Comment by boneskull** [comment]
oh, whoops.
