### ISSUE TITLE
add .mochaignore

### ISSUE THREAD

**Issue by TrejGun** [mochajs/mocha#2036]
Please add .mochaignore file same as .gitignore
to ignore some files

yes i know there is `.skip` for tests but it would be good to ignore dirs or files with utils and configs

**Comment by boneskull** [comment]
absolutely a good idea, but probably won't get implemented before #1969 unless there's a PR.

**Comment by megagon** [comment]
I want to make PR for this, do you have any wishes about how it should looks like?
my suggestion is to make by default something like mocha.ignore with something like this:
`var skiplist = {folders:[], files: [], suites:[], tests:[]};` 
How is it sound?

**Comment by ScottFreeCode** [comment]
A couple thoughts/questions:
1. Should test files ignored this way be loaded but marked entirely as pending?
2. Can/should something equivalent to this work in the in-browser testing mode?

**Comment by boneskull** [comment]
since #1969 is still basically nowhere, a PR for this would be helpful.

**Comment by gonnza** [comment]
Is the idea to allow a configuration as megagon suggested?

Something like 

`{folders:[], files: [], suites:[], tests:[]};`

?

- folders: Ignores a complete folder and its subdirectories from running tests
- files: Ignore specific files (by name ? by path?)
- suites: to ignore `describe` tests by name
- test: to ignore specific `it` tests by name

Should they show as pending, or as they do not exists?

**Comment by boneskull** [comment]
As of v6, this is implemented as the `excludes` config value.  A `.mochajs.json` which includes the following should exhibit the requested behavior:

```json
{
  "excludes": [
    "some-glob/**",
    "some-other-glob/*.derp"
  ]
}
```

I think that we could alias the `excludes` option to `ignore`.

**Comment by boneskull** [comment]
Would prefer we don't support `.mochaignore`, simply because it's functionality that's now duplicated in a config file.  

FWIW, ESLint [is moving in the direction of dropping its "ignore" file](https://github.com/eslint/rfcs/blob/ea369d753d571128ecb9afb3c459b8ce936fba24/designs/2019-config-simplification/README.md).

**Comment by plroebuck** [comment]
Pre-Mocha-6, this might have been attractive, but now it's just an extra file to process with no benefit not already available.

Close as "wontfix" IMO.

**Comment by gndelia** [comment]
Cool, I did not know the exclude option was already implemented. Then I agree, this should be closed

**Comment by boneskull** [comment]
I'm cool with an `ignore` alias.  I can probably knock that out.

**Comment by boneskull** [comment]
Closing this because we already support this behavior in `.mocharc.*` config files as of v6.
