### ISSUE TITLE
New version of Mocha requested

### ISSUE THREAD

**Issue by klamping** [mochajs/mocha#2040]
The last release of Mocha was on Nov. 15th and many improvements have been added since then. Specifically for my needs, [the `retry` functionality](https://github.com/mochajs/mocha/pull/1989) was introduced after the latest release. Can we get a new release of Mocha to take advantage of these changes?

Another request for a release was made here: https://groups.google.com/forum/#!topic/mochajs/Olw3berArnA (so i'm not the only one :smile:)

**Comment by longlho** [comment]
:+1:

**Comment by LordWingZero** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by danielstjules** [comment]
In a few days? I'd like to close up some possible bugs and include fixes in the minor release.

**Comment by LordWingZero** [comment]
Sounds good to me.

**Comment by boneskull** [comment]
@danielstjules Please let me know when ready

cc @mochajs/mocha

**Comment by robraux** [comment]
:+1: looking forward to it, thank you

**Comment by TrejGun** [comment]
:+1:

**Comment by danielstjules** [comment]
Seems to be issues with the HTML reporter in master - investigating now

**Comment by danielstjules** [comment]
Sorry for the delay. imo, this should be fixed before the next release: https://github.com/mochajs/mocha/issues/1760

**Comment by jonny-improbable** [comment]
Sorry to bump this issue but it's been a week since the last comment; a 2.3.5 release would be greatly appreciated.

**Comment by boneskull** [comment]
We're stuck on a browser-related issue afaik.  @danielstjules know what's up here?

**Comment by antinescience** [comment]
@danielstjules same thing here - would love to see 2.3.5 hit npm!

**Comment by klamping** [comment]
Any updates on this? Maybe y'all can put out a prerelease so I can move forward (since the bug doesn't affect my needs).

**Comment by danielstjules** [comment]
This is the current blocker. The browser reporter in master (run `make`) is not functional

![screen shot 2016-01-25 at 11 05 07 pm](https://cloud.githubusercontent.com/assets/817212/12574374/3b5c1f0e-c3b8-11e5-93d0-b9b55492b545.png)

**Comment by danielstjules** [comment]
Done :+1:

**Comment by klamping** [comment]
Awesome, thanks! Can't wait to try out the new features!
