### ISSUE TITLE
Block-level before hook

### ISSUE THREAD

**Issue by AdamBoxall** [mochajs/mocha#2041]
Is it possible to define a block-level `before()` hook when using parent `beforeEach()` hooks?

Take the following example:

``` js
describe("something", function() {
  beforeEach(function() {
    console.log("parent beforeEach");
  });

  it("should do something", function() {});

  describe("something else", function() {
    before(function() {
      console.log("child before");
    });

    it("should do something else", function() {});
  });
});
```

Which produces:

```
  something
parent beforeEach
    ✓ should do something
    something else
child before
parent beforeEach
      ✓ should do something else
```

Logically that does actually make sense: it always runs the `before()` hooks before any `beforeEach()` hooks. Unfortunately that means if you depend on some setup done within a parent `beforeEach()` hook, you cannot use `before()` hooks lower down. If you're doing something relatively expensive that doesn't need to be run before every test in that block, you're still forced to use `beforeEach()`.

I'm using v2.3.4.

**Comment by Sinewyk** [comment]
I want to say that it doesn't make sense. If mocha give us the means to scope stuff. Then the `beforeEach` of the parent scope should run before the `before` of the child scope.

**Comment by Sinewyk** [comment]
Meh, duplicate https://github.com/mochajs/mocha/issues/1694 and apparently intended behavior.

**Comment by Sinewyk** [comment]
Quoting the documentation on the main website:
> Tests can appear before, after, or interspersed with your hooks. Hooks will run in the order they are defined, as appropriate; all before() hooks run (once), then any beforeEach() hooks, tests, any afterEach() hooks, and finally after() hooks (once).

The inner before should be inside that `tests` scope. So a inner before should run AFTER an outer beforeEach. Or the documentation is wrong.
