### ISSUE TITLE
discussion: bundled assertion library

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2044]
Mocha's always been unopinionated and flexible.  That being said, it _may_ be a barrier to entry that an assertion library is not included.

In Node.js, one can `require('assert')` (though it's not recommended by the Node.js team) without installing extra packages.  In a browser context, you're going to have to explicitly grab some library via some means.  Packages like [karma-chai](https://www.npmjs.com/package/karma-chai) make this less of a burden, however.

In my experience, the lack of a bundled library has never been a barrier, however there are reason(s) to want closer integration with assertion libs (see #1651).  So I'm fine with the status quo, but am wondering about others' thoughts here?

cc @mochajs/mocha @dasilvacontin

**Comment by willnwhite** [comment]
Both times I've been introduced to tests it's primarily been by using assertion libraries.

**Comment by dasilvacontin** [comment]
>
```js
describe('foo', function() {
  it('does stuff', function() {
    this.assertions(4);
    expect(foo).to.be(bar);
    expect(foo).to.be(bar);
    expect(foo).to.be(bar);
    expect(foo).to.be(bar);
  });
});
```

Does `this.assertions(4)` or `t.plan(4)` really provide extra value? How?

**Comment by MShawnDillon** [comment]
I regard one of Mocha's advantages is that it does **not** include (or even give preferential treatment to) any assertion library.  I like the "if it throws, the test fails; if not, the test passes" operation along with the promise- and callback- based corollaries.

In the same vein, I would **not** want something like `this.assertions(4)` or `t.plan(4)` to appear in Mocha... the reasons for which are well described [here](https://www.youtube.com/watch?v=iP0Vl-vU3XM).

I have recently been bombarded with hype promoting tap/tape and denouncing Mocha (interesting is [this "demonstration"](https://github.com/ChiperSoft/tape-vs-mocha) and [this diatribe](https://ponyfoo.com/articles/testing-javascript-modules-with-tape) against Mocha).  The demonstration claims that a feature of tap/tape is the ability to continue running a test after a failed assertion, while the latter does make a good point about Mocha's own use of the global namespace.

After having tried several options, I still tend to be in agreement with [this comparison](http://www.slant.co/topics/4506/compare/~mocha_vs_jasmine_vs_tape) of the most widely-used test frameworks and tools.

**Comment by Bamieh** [comment]
Closing this, feel free to re-open if your opinions has not changed regarding this issue @boneskull .

Personally I'd vote -1 for this feature.
