### ISSUE TITLE
Retries hang on async tests

### ISSUE THREAD

**Issue by chrmod** [mochajs/mocha#2045]
As shown by this PR tests something is wrong when async test fails and we want to retry it
https://github.com/mochajs/mocha/pull/2046

What we experienced aside of no retry, is also lack of higher level afterEach being called.

**Comment by chrmod** [comment]
@longlho maybe you can take a look

**Comment by longlho** [comment]
ah thanks for the tests :) I'll take a look

**Comment by danielstjules** [comment]
Can you provide a small example? This works for me:
``` javascript
var i = 0;
it('test', function(done) {
  this.retries(3);
  this.timeout(1000);
  console.log('attempt');
  if (++i < 3) throw new Error('Boom');
  setTimeout(done, 500);
});
```

```
$ ./bin/mocha example.js

attempt
attempt
attempt

  ․

  1 passing (9ms)
```

**Comment by chrmod** [comment]
@danielstjules please try to trigger a fail by timeout. 

Our use case is some integration test waiting for DOM node. As the first timeout hits, tests stop to run.

**Comment by danielstjules** [comment]
Ah, you're right! Small example:
```
var i = 0;
it('test', function(done) {
  this.retries(2);
  console.log('attempt');
  if (++i < 3) {
    return setTimeout(done, 300);
  }
  setTimeout(done, 50);
});
```

Ideally, it should output the same results as above (3 attempt strings), but even the reporter output is failing.

**Comment by longlho** [comment]
cool tks guys I'm takin a look :)

**Comment by longlho** [comment]
@chrmod I put in a PR for it

**Comment by chrmod** [comment]
It works great, thank you! @longlho @danielstjules
