### ISSUE TITLE
Browser test `array pop` fail due to bad test script

### ISSUE THREAD

**Issue by hllhll** [mochajs/mocha#2049]
Using the test in "mocha/test/browser/" fails under  Array #pop()
Test result (Copied from browser):

```
Array
#pop()
X should remove and return the last value ‣
Error: failed
    at assert (:11:26)
    at Context.<anonymous> (array.js:29:7)
var arr = [1,2,3];
assert(arr.pop() == 3);
assert(arr.pop() == 2);
assert(arr.pop() == -1);
V should adjust .length
```

I Guess due to the last assert '-1'  should be '1'.

**Comment by danielstjules** [comment]
This is intentional, and was introduced to verify that errors were correctly displayed with the HTML reporter. Relevant commit: https://github.com/mochajs/mocha/commit/e12ff8f7b634fc2ba4715fd0b68758030773e4dc Thanks!
