### ISSUE TITLE
Mocha omits parts of the path 

### ISSUE THREAD

**Issue by spatialvlad** [mochajs/mocha#2055]
Hello,

I’m relatively new to Mocha, and though overall it works fine for me, I have a strange issue that I do not know how to fix and could not find an issue that describes the problem and the solution.
For some reason Mocha omits part of the path to a file when it resolves it from a path in a file it tests. The part that is omitted is the base directory of the project.
E.g. actual path to a file is C:/Users/Me/Projects/SampleProject/test/file.js
In the production code I use “../test/file.js” to reference the needed file and it works fine. However, Mocha resolve this as “C:/Users/Me/Projects/test/file.js”, omitting the base directory of the project –“SampleProject”.
If I explicitly specify the base directory in the Mocha files (e.g. “../SampleProject/test/file.js”), it resolves the path correctly and works fine.
This behavior was not very convenient, but more or less usable when I tested simple files, I would simply use different paths for Mocha and the production code.
But recently I started testing more complex scripts, that in turn use other modules/scripts. And Mocha fails in this scenario, unless I change the paths in all the nested levels of files, which becomes very inconvenient, time consuming and prone to mistakes.
Could someone advise me where to look into how to fix the issue?
Thanks!

Vlad

**Comment by ScottFreeCode** [comment]
Hi, @spatialvlad, sorry no one noticed this issue when we should have (and I didn't even see the bot's initial message, only noticed when it closed), but if it still makes any difference (or if anyone else finds this issue when searching for a similar problem), this sounds like the code was affected by the current working directory and should have used `require("path").join(__dirname, <path relative to file>)` to ensure consistent behavior regardless of current working directory. That isn't really anything special about Mocha, it's just how Node resolves filepaths for just about everything other than `require`: where you run the script from is where relative paths resolve from unless you specifically do something to update it. (It's hard to be absolutely certain of this without an actual code example, so if you -- or anyone else reading this -- still have an issue and it's not that, feel free to post some minimal but complete sample code to demonstrate it.)
