### ISSUE TITLE
Upgrade glob to latest

### ISSUE THREAD

**Issue by gyandeeps** [mochajs/mocha#2058]
Mocha is using `glob` module version from 2013. I would be good if we can upgrade that to latest so that we can use a lot of globbing patterns with it.

If its ok, then I can send the PR.

**Comment by danielstjules** [comment]
We've previously experienced issues with upgrading dependencies: https://github.com/mochajs/mocha/issues/1867 https://github.com/mochajs/mocha/issues/1887 https://github.com/mochajs/mocha/issues/1868

Aside from a bump, we'd want to verify compatibility with old versions of node/npm.

**Comment by gyandeeps** [comment]
What is our official nodejs support range?
If its too wide then this change might cause issue (but i have to try it).

**Comment by boneskull** [comment]
this is not possible as any glob newer than the one we currently have uses fuzzy version matching against minor versions (`^`) which precludes nodejs 0.8.  

I imagine 0.8 will be dropped w/ next major, however.

closing for now

**Comment by boneskull** [comment]
(it doesn't *actually* preclude using 0.8; you can generally still upgrade npm, but some people cannot for various reasons)

**Comment by danez** [comment]
The problem on the other hand is that this old glob, depends on an old version of graceful-fs. And this one is using node apis which are getting removed in the next major. So either beeing backward compatible or forward :/

From install:
```
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
```

**Comment by danielstjules** [comment]
Sounds like it won't get removed until v7: https://github.com/nodejs/node/issues/5213#issuecomment-183633565 But I agree that we can look at breaking compatibility with the next major mocha release :) https://github.com/mochajs/mocha/issues/2111#issuecomment-184599809

**Comment by isiahmeadows** [comment]
If you're testing against 0.8, graceful-fs was rewritten in 4.x to [support 0.8 better](https://github.com/isaacs/node-graceful-fs/issues/47), and it [does test against that version in CI](https://github.com/isaacs/node-graceful-fs/blob/master/.travis.yml). And apparently, [not much changed between 3.x and 4.x](https://github.com/isaacs/node-graceful-fs/issues/470) other than its monkey-patching-by-default behavior (which is likely to break something).

Most of the breakage you might encounter would probably be in node-glob, not graceful-fs, unless you unintentionally rely on graceful-fs' monkey-patching.

**Comment by danielstjules** [comment]
@isiahmeadows It's less about node compatibility, and more about npm. Release newer than our current uses a caret range (^) in version matching, which isn't supported in older versions of npm.

**Comment by isiahmeadows** [comment]
Okay. What range does this support?

**Comment by isiahmeadows** [comment]
Ok. What `npm` versions does this support?

Also, is it possible to use `bundledDependencies`? That could avoid the problem altogether, since `npm@3` still supports 0.8.x, and this could be done at `prepublish` and in [Travis/etc](http://tech.vg.no/2014/05/30/npm-travis-node-and-the-caret-operator/).

**Comment by boneskull** [comment]
@isiahmeadows >= v.1.2.30

`bundledDependencies` is something I hadn't thought of.  Though I'm unsure of the implications.  I'd be adverse to doing that in a minor release anyway...
