### ISSUE TITLE
Travis --no-color, truncated test cases

### ISSUE THREAD

**Issue by kevinawoo** [mochajs/mocha#2060]
When testing using Travis using the option `--no-colors`, color escape codes are still being outputted. This leads to some test cases being truncated.

[Latest mocha master branch](https://travis-ci.org/mochajs/mocha/jobs/103528682)
![screenshot 2016-01-19 23 39 27](https://cloud.githubusercontent.com/assets/3469532/12442584/ebe82122-bf05-11e5-90d3-3214c0fa5250.png)

[See Travis with --no-color option](https://travis-ci.org/kevinawoo/mocha/jobs/103544709)
![screenshot 2016-01-19 23 40 06](https://cloud.githubusercontent.com/assets/3469532/12442591/fd0b6e46-bf05-11e5-8e63-7256dbcb45a3.png)

Here's the raw outputs of a different repo I have running mocha+travis:

Not truncated, colorized (using mocha) output from travis:

```
 [0m [0m
 [0m  CAR COLOR: [0m
 [0m    find [0m
 [2K [0G     [32m  âœ“ [0m [90m return all car colors [0m [33m (55ms) [0m
 [2K [0G     [32m  âœ“ [0m [90m return all managed car colors [0m
 [2K [0G     [32m  âœ“ [0m [90m return all unmanaged car colors [0m
```

Truncated, colorized turned off (using mocha --no-colors) output from travis:

```
  CAR COLOR:
    find
 [2K [0G      âœ“ return all car colors (48ms)
 [2K [0G      âœ“ return all managed car colors
 [2K [0G      âœ“ return all unmanaged car colors
```

---

I've spoken with Travis and they have a couple issues already open for it. Support Engineer's reply:

> I am afraid that some escape sequences are hard to emulate on line-oriented log display like ours. For example, [nK (https://github.com/travis-ci/travis-ci/issues/1950) and [nG (https://github.com/travis-ci/travis-ci/issues/1951) are not supported as a result.
> 
> Is there a way to suppress these ANSI sequences on your testing tool?

**Comment by boneskull** [comment]
you'd have to run mocha with `--no-colors`
