### ISSUE TITLE
assert does not always work

### ISSUE THREAD

**Issue by christianfriedl** [mochajs/mocha#2062]
I have the following code inside an it() function:

            const transformFunction = function(err, dirName, fileName, callback) { callback(false); }
            const afterFunction = function(err, results) {·
                console.log('afterFunction starts', paths);
                assert.ok(false, 'assertion fails!!!!!');
                console.log('afterFunction ends');
            };
            atomic.transformSingleFile('source', 'file.txt', transformFunction, afterFunction, 'target', 'file.txt');

in this case, afterFunction gets called (so my function obviously calls it), but the assertion text never appears, and neither does the 'afterFunction ends' text. So the assertion gets triggered, but is swallowed, and the test runs through as if there was no assertion at all.

**Comment by ryanshawty** [comment]
Looks like you are doing asynchronous operations in a synchronous test case try:

```js
it('test', function(done){
  ...
  afterFuncEtc = function(err, results){
    // assert etc

    done()
  }
  ...
});
```

**Comment by christianfriedl** [comment]
Ahhh.... *lightbulb* Cool, thanks for the fast reply.

Sorry, my bad obviously. I was a bit tired already and wasn't aware that the assert capturing depends on the done() call.
