### ISSUE TITLE
Ideas on getting the current testname outside of the mocha test file

### ISSUE THREAD

**Issue by ILikeToNguyen** [mochajs/mocha#2065]
We have a module where we'd like to get the test name information in order to send it over to module's server it is interacting with.  Is it possible to get the "test name" which could be the full file path of the mocha .js file, or the string in the 'it'.

I know this is possible from within the test it self by doing this.test.title but we don't want to put the burden of having the users of our node module need to get the test name and pass it into our module.

Things I've tried:
- I tried looking at process.env values and mocha doesn't create a env property var for the current test.  
- I can't find an equivalent in mocha to separate testNG's listener where i could possibly intercept each mocha run, and in an onBeforeTest, with the mocha suite or test , get the test name and save it to en env variable so that my module can read it at server connection time.

Any creative ideas on how to get the test title or mocha file's .js full path outside of the mocha js test file?

**Comment by SunainaVijay** [comment]
I am looking for an answer to the above question, please help!
