### ISSUE TITLE
HTML/DOC reporter regressions as a result of #2037

### ISSUE THREAD

**Issue by danielstjules** [mochajs/mocha#2067]
https://github.com/mochajs/mocha/pull/2037

As a result of that PR, the browser & doc reporters cannot handle showing function bodies when exceptions are thrown async, outside of the duration of the originating suite (after the suite has ended). They'll result in: `Uncaught TypeError: Cannot read property 'toString' of undefined`

The line in question:
``` javascript
var pre = fragment('<pre><code>%e</code></pre>', utils.clean(test.fn.toString()));
```

Rather than revert https://github.com/mochajs/mocha/pull/2037, I propose caching the function body strings, which should still be light.

**Comment by francisco-sanchez-molina** [comment]
Hi @danielstjules @boneskull! After _test.fn.toString()_ to _test.body_ change, when "before" throw Error mocha explode in mocha.js:5980 Uncaught TypeError: Cannot read property 'replace' of undefined

2.4.4 version http://jsfiddle.net/38v388kw/

2.3.4 version http://jsfiddle.net/joes4L1q/

**Comment by asadsahi** [comment]
any fix for this? having same issue.
