### ISSUE TITLE
grep links for test names with dots "." don't get escaped correctly.

### ISSUE THREAD

**Issue by btelles** [mochajs/mocha#2070]
Steps to Reproduce:
1. Create a test whose suite name contains a dot, for example "crud-behavior-basic.html"
2. Navigate to the test page, for example: http://localhost:5000/test/index.html
3. Click on the link to "crud-behavior-basic.html"

Expected result:
Link reduces the tests to be run to those inside crud-behavior-basic.html file.
Generated link has: grep=crud-behavior-basic.html

Actual result:
No tests are run.
Generated link has: grep=crud-behavior-basic%5C.html

Related bug: https://github.com/mochajs/mocha/issues/1687
Related PR: https://github.com/mochajs/mocha/pull/1698

It appears the following line of code is overzealous. Replacing the . with %5C
https://github.com/benvinegar/mocha/commit/3166e701a356d472656878ae78e5b819099f95d9#diff-998e3fb668a2094eedccab3e56199e4fR204

**Comment by btelles** [comment]
Thanks! That definitely fixes it. :+1: :-)

**Comment by btelles** [comment]
The same problem reared its head again in WebComponentTester. Not sure what changed in mocha to add it back in, but just wanted you all to know.

**Comment by JoshuaKGoldberg** [comment]
👋 @btelles I'm not familiar with WebComponentTester and don't see a straightforward way to reproduce this in the latest versions of Polymer. I know it's been a few years, but are you able to provide a standalone reproduction for this issue?

(for context on why you're only now getting pinged, see #5027)

**Comment by JoshuaKGoldberg** [comment]
Closing out old issues. If someone does have a repro, please do post back - we'd be happy to take a look!
