### ISSUE TITLE
-c option broken in 2.4.1

### ISSUE THREAD

**Issue by gyandeeps** [mochajs/mocha#2073]
`-c` CLI option is broken in `2.4.1` but works in `2.3.4`.

**Scenario 1**
If I run mocha with `-c` flag then it doesnt even run my tests.
```sh
./node_modules/mocha/bin/_mocha -R progress -c tests/*.js
```

**Scenario 2**
If I run mocha without `-c` flag then it does run my tests but there is no color.
```sh
./node_modules/mocha/bin/_mocha -R progress tests/*.js
```

**Comment by danielstjules** [comment]
Related: https://github.com/mochajs/mocha/commit/119291449cd03a11cdeda9e37cf718a69a012896

**Comment by gyandeeps** [comment]
Something which also happening is that the unit test are not run in scenario 1. Its not just about the color.

**Comment by gyandeeps** [comment]
Here is the reason why this is happening because some of the reporters with custom color never got updated with chalk functions:

* https://github.com/mochajs/mocha/blob/master/lib/reporters/landing.js#L20-L32

CC: @danielstjules

**Comment by boneskull** [comment]
my bad.  I'll fix.

**Comment by gyandeeps** [comment]
I working on the PR now.
