### ISSUE TITLE
Doesn't work in IE8 after release v2.4.1

### ISSUE THREAD

**Issue by yurevichcv** [mochajs/mocha#2078]
All my tests started to fail after new release in IE8 with the following error:

```
Object doesn't support this property or method
  at /home/travis/build/driveback/digital-data-manager/node_modules/mocha/mocha.js:11671
```

**Comment by gyandeeps** [comment]
Thats because at ~3 spots `Object.keys` was used directly rather than checking if the function is present or not.

**Comment by boneskull** [comment]
Ugh.

**Comment by boneskull** [comment]
Just load es5-shim until we fix it (very soon)

**Comment by yurevichcv** [comment]
I have es5-shim, but it still doesn't work :)

**Comment by gyandeeps** [comment]
do you have it for `object.keys` and `[].forEach`?

**Comment by boneskull** [comment]
alright, testing this fix atm.

**Comment by gyandeeps** [comment]
@boneskull why not use the polyfill for 2 methods so that it easy to remove later on when we end IE8 support?

**Comment by boneskull** [comment]
@gyandeeps rather not add another dependency or monkey with other stuff right now.

**Comment by boneskull** [comment]
@yurevichcv can you run your tests with [this mocha.js file](https://rawgit.com/boneskull/mocha/a4345efe0de0f80d09b35794f5e130d730542def/mocha.js) and tell me if you have better results in IE8?

**Comment by boneskull** [comment]
@gyandeeps anyway, mocha contains a bunch of hand-rolled shims which need replacing.  it's a somewhat bigger job than you'd expect

**Comment by gyandeeps** [comment]
I see. thanks

**Comment by boneskull** [comment]
downloading an IE8 vm to try it myself

**Comment by danielstjules** [comment]
@boneskull Your changes work:

**Before**

<img width="765" alt="screen shot 2016-01-27 at 8 10 36 am" src="https://cloud.githubusercontent.com/assets/817212/12619639/b5f627a8-c4cd-11e5-813f-eb7a708bd808.png">

**After**

<img width="608" alt="screen shot 2016-01-27 at 8 11 57 am" src="https://cloud.githubusercontent.com/assets/817212/12619643/ba9b15c0-c4cd-11e5-9451-2e874f58de55.png">

**Comment by boneskull** [comment]
v2.4.3 published
