### ISSUE TITLE
beforeEach doesn't run with it.only 

### ISSUE THREAD

**Issue by Yeti-or** [mochajs/mocha#2087]
```
  describe('group', () => {

    beforeEach('before', () = > {doSmth()});

    it.only('only me', () => {expect('').to.be.eq('');});

  });
```

If there is no `it.only` then `doSmth` will be called;
If there is no `only` `doSmth` will be called;

**Comment by ORESoftware** [comment]
did you try this same thing without any arrow functions? it will probably work.

**Comment by camstuart** [comment]
Same issue here.... as it happens, I too was using arrow functions.
The arrow functions are generated into my test stubs from the feathersjs framework.

I tried using:

```JavaScript
it.only('fails to create user when the email address is already taken', function () {
  // ...
}
```

And encountered the same issue, my `beforeEach` did not execute

**Comment by juergba** [comment]
With current master the hook behavior (`beforeEach` and `before`) is correct:
- hook is not executed when no test at all.
- hook is executed with
  - it()
  - it.only()
