### ISSUE TITLE
Watch mode doesn't work when importing describe/it

### ISSUE THREAD

**Issue by c089** [mochajs/mocha#2088]
When I use `import {describe, it} from 'mocha'` and enable `--watch`, tests are only executed once on start. When I change a file, the watcher registers that change, but does not execute any tests and just prints `0 passing`.

(I'm using babel 6.x and `--compilers js:babel-register` here, haven't had the time to try this with commonjs requires yet)

**Comment by thangngoc89** [comment]
:+1: I have this issue too

**Comment by ScottFreeCode** [comment]
This looks like https://github.com/mochajs/mocha/issues/2207#issuecomment-328280956; I can't reproduce it if I use the default BDD interface and `describe`/`it`, but can with `--ui tdd` and `describe`/`it`. Going to close this to focus discussion of interface mismatch issues there, but if you have code/steps to reproduce that does not depend on using a different interface than is selected by `--ui`, we can reopen this.
