### ISSUE TITLE
Change console output icons

### ISSUE THREAD

**Issue by konradjurk** [mochajs/mocha#2090]
Hi,

I am wiring up a [lambdacd](https://github.com/flosell/lambdacd) build pipeline for my nodejs application. The CI somehow captures the console output, stores it into JSON and then prints it to the webui.

This process destroys the nice checkmark icons (✓) so every test is prefixed with a `?`. Is it possible to replace the checkmark (or error icon) with a custom string like `[SUCCESS]`?

```
findLanguageOrUseCustomerDefault()
      ? is a function
      ? finds and returns requested language (customer.language undefined)
```

**Comment by ScottFreeCode** [comment]
Hi, @konradjurk,

Sorry we didn't see this issue before. Are you still in need of a solution? I'd be curious whether LambdaCD can do something like `sed` Mocha's output to replace the Unicode characters.

I think Mocha's already using different characters on Windows than elsewhere, though, so maybe we just need to identify the type of environment LambdaCD is running/simulating and find an appropriate set of characters for that?
