### ISSUE TITLE
HTML reporter bug: error is shown twice

### ISSUE THREAD

**Issue by antpaw** [mochajs/mocha#2092]
Everytime a error happens the HTML reporter shows it twice.

here is a testcase: 
http://stuff.antpaw.de/mocha.html or https://jsfiddle.net/u5zqnwrv/

**Comment by ArnaudBuchholz** [comment]
Got the same issue here

**Comment by ohnnyj** [comment]
Possible duplicate of #2083.

**Comment by ArnaudBuchholz** [comment]
Confirmed, I also qualified a second 'test end' call.

**Comment by danielstjules** [comment]
Closing as duplicate of #2083
