### ISSUE TITLE
The home page should mention --inline-diffs along with the screenshot

### ISSUE THREAD

**Issue by nickolay** [mochajs/mocha#2098]
http://mochajs.org/#diffs shows output of `mocha --inline-diffs`, which is not the default (since #862?).

I needed inline diffs and spent some time figuring out what I had done wrong, a pointer to `--inline-diffs` near the screenshot would be very helpful.

**Comment by mattflix** [comment]
+1

I was confused too...  the diff report is "the money shot", and (for whatever reason) it is not the default behavior.

**Comment by juergba** [comment]
We updated our docs accordingly, thank you.
