### ISSUE TITLE
mocha + ejs - Syntax error: unexpected token <

### ISSUE THREAD

**Issue by caalberts** [mochajs/mocha#2099]
When I run mocha test on a react + webpack + babel app where a dependency (auth0-lock) has **.ejs** files, I get a `SyntaxError: Unexpected token <`

```
mocha test/components/channel.spec.js --compilers js:babel-register
/myapp/node_modules/auth0-lock/lib/html/main.ejs:1
(function (exports, require, module, __filename, __dirname) { <div id="a0-lock" class="a0-lock<%= (locals && locals.options.theme) ? ' a0-theme-' + locals.options.theme : ''%>" dir="auto">
                                                              ^
SyntaxError: Unexpected token <
```

Any help on this is appreciated.

**Comment by iamjpg** [comment]
I'm having the exact same issue with precompiled EJS templates. As @caalberts said above, any help would be greatly appreciated. Thank you.

**Comment by caalberts** [comment]
@iamjpg `mocha --compilers ejs:ejsify` worked for me

**Comment by iamjpg** [comment]
Thank you, @caalberts!
