### ISSUE TITLE
Unexpected token ...

### ISSUE THREAD

**Issue by zentuit** [mochajs/mocha#2100]
I'm getting the same error message that is in this stackoverflow question:
[http://stackoverflow.com/questions/34559822/spread-operator-in-react-native-causes-unexpected-token-error-with-mocha](http://stackoverflow.com/questions/34559822/spread-operator-in-react-native-causes-unexpected-token-error-with-mocha)

The line "...require('React')," was added to Libraries/react-native/react-native.js. 

Now when trying to unit test anything that touches something that includes 'react-native' (in my case an import of AsyncStorage) will cause the "Unexpected token ..." error message.

I have installed 'stage-2' preset and included it in my .babelrc file but that does not seem to have made any difference.

Are there any ideas on how to continue using Mocha in this project?

**Comment by danielstjules** [comment]
I'd open an issue with react-native, or update your babel setup to not ignore node_modules. From their docs:
``` javascript
require("babel-register")({
  // This will override `node_modules` ignoring - you can alternatively pass
  // an array of strings to be explicitly matched or a regex / glob
  ignore: false
});
```
This isn't really mocha specific as you'll hit this issue with any test runner that doesn't automatically run babel for you. Hope that helps!
