### ISSUE TITLE
Does Mocha support Node 5.x?

### ISSUE THREAD

**Issue by ilanbiala** [mochajs/mocha#2102]
Mocha seems to crash when testing against Node 5.6.0 on our repository's [Travis CI](https://travis-ci.org/meanjs/mean/jobs/108313328#L2916). It seems that Mocha supports everything at least 0.8 though, so I'm not sure what versions work.

**Comment by danielstjules** [comment]
Yup, mocha supports Node 5.x. It looks like your exception is being thrown from `mock-fs`?

```
$ node --version
v5.6.0
dstjules:~/git/mocha (master=)
$ ./bin/mocha test/


  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․

  155 passing (552ms)
  1 pending
```
