### ISSUE TITLE
Error: Unsupported Node version: 5.6.0

### ISSUE THREAD

**Issue by bustazone** [mochajs/mocha#2105]
Hi I am having this issue when trying to run "npm test" with mocha.
I've copied the stack below. Thank you.

--
MEAN.JS - Test Environment
Environment:			test
Port:				3001
Database:				mongodb://localhost/mean-test
App version:			0.4.2
MEAN.JS version:			0.4.2
--

Running "mochaTest:src" (mochaTest) task
>> Mocha exploded!
>> Error: Unsupported Node version: 5.6.0
>>     at Object.<anonymous> (/Users/busta/Documents/proyectos_eclipse/node_test/mean/node_modules/mock-fs/lib/index.js:35:9)
>>     at Module._compile (module.js:413:34)
>>     at Object.Module._extensions..js (module.js:422:10)
>>     at Module.load (module.js:357:32)
>>     at Function.Module._load (module.js:314:12)
>>     at Module.require (module.js:367:17)
>>     at require (internal/module.js:16:19)
>>     at Object.<anonymous> (/Users/busta/Documents/proyectos_eclipse/node_test/mean/modules/core/tests/server/core.server.config.tests.js:12:10)
>>     at Module._compile (module.js:413:34)
>>     at Object.Module._extensions..js (module.js:422:10)
>>     at Module.load (module.js:357:32)
>>     at Function.Module._load (module.js:314:12)
>>     at Module.require (module.js:367:17)
>>     at require (internal/module.js:16:19)
>>     at /Users/busta/Documents/proyectos_eclipse/node_test/mean/node_modules/mocha/lib/mocha.js:172:27
>>     at Array.forEach (native)
>>     at Mocha.loadFiles (/Users/busta/Documents/proyectos_eclipse/node_test/mean/node_modules/mocha/lib/mocha.js:169:14)
>>     at MochaWrapper.run (/Users/busta/Documents/proyectos_eclipse/node_test/mean/node_modules/grunt-mocha-test/tasks/lib/MochaWrapper.js:51:15)
>>     at /Users/busta/Documents/proyectos_eclipse/node_test/mean/node_modules/grunt-mocha-test/tasks/mocha-test.js:86:20
>>     at capture (/Users/busta/Documents/proyectos_eclipse/node_test/mean/node_modules/grunt-mocha-test/tasks/mocha-test.js:33:5)
>>     at Object.<anonymous> (/Users/busta/Documents/proyectos_eclipse/node_test/mean/node_modules/grunt-mocha-test/tasks/mocha-test.js:81:5)
>>     at Object.<anonymous> (/Users/busta/Documents/proyectos_eclipse/node_test/mean/node_modules/grunt/lib/grunt/task.js:264:15)
Warning: Task "mochaTest:src" failed. Use --force to continue.

Aborted due to warnings.

**Comment by danielstjules** [comment]
Please see https://github.com/mochajs/mocha/issues/2102#issuecomment-182584781 Thanks!
