### ISSUE TITLE
allowUncaught is not working as expected

### ISSUE THREAD

**Issue by yonida** [mochajs/mocha#2106]
In my code there are cases where I might get some errors, which I'm fine with.
I looked around and found the `allowUncaught` flag to prevent uncaught errors to fail my tests.
Problem is, I don't really understand what this flag does, because the tests keep failing.

``` javascript
process.on = function(e, fn){
        if ('uncaughtException' == e) {
      global.onerror = function(err, url, line){
      fn(new Error(err + ' (' + url + ':' + line + ')'));
      return !mocha.allowUncaught;
    };
    uncaughtExceptionHandlers.push(fn);
  }
};
```

As you can see in the code, there is no way to block the fn callback in cause of `uncaughtException`.

If this flag is not intended for this use case, please add some proper documentation for it.

**Comment by lolmaus** [comment]
`mocha.allowUncaught` is designed to prevent mocha from catching exceptions, letting them fall through into the console for further inspection.

It does not prevent exceptions from breaking your tests.

**Comment by doublerebel** [comment]
@yonida I and others have the same issue, check out the solutions in #1985

**Comment by drazisil** [comment]
Being handled under https://github.com/mochajs/mocha/issues/1985
