### ISSUE TITLE
show full pathes of files in stack trace

### ISSUE THREAD

**Issue by divramod** [mochajs/mocha#2108]
Hey, 

i have a test-directory with a spec file in a structure like that:

    test/packages/liveGames/actions/addLiveGame_spec.js

this file tests a file at 

    src/packages/liveGames/actions/addLiveGame.js

i run mocha like that

        "test": "node_modules/mocha/bin/mocha --compilers js:babel-core/register --require mocha-clean --require ./test/utils/chaiImmutable.js 'test/**/*_spec.@(js|jsx)'",

i let that test fail and get a stack trace like that:

    TypeError: ...
      at addLiveGame (addLiveGame.js:5:33)
      ...
      at Context.<anonymous> (addLiveGame_spec.js:36:34)

I really like to see the full path of the file addLiveGame.js and addLiveGame_spec.js.
ie like that

    at addLiveGame (src/packages/liveGames/actions/addLiveGame.js)
    ...
    at Context.<anonymous> (test/packages/liveGames/actions/addLiveGame_spec.js)

Is that somehow possible with mocha?

Background:

- i use tmux and will jump from that path directly to the file in vim

**Comment by danielstjules** [comment]
This is due to mocha-clean. With a vanilla mocha install:

```
$ tree src/
src/
└── packages
    └── example.js

1 directory, 1 file

$ mocha --recursive src


  1) test

  0 passing (10ms)
  1 failing

  1)  test:
     Error: foo
      at Context.<anonymous> (src/packages/example.js:2:9)
```

Hope that makes sense!
