### ISSUE TITLE
Deprecated graceful-fs

### ISSUE THREAD

**Issue by thedark1337** [mochajs/mocha#2111]
Hi, I just noticed after installing mocha that it relies on an outdated dependency on glob@3.2.3 which uses graceful-fs@2.0.3 .  

`npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible`

See the tracking issue here: https://github.com/nodejs/node/issues/5213

**Comment by LinusU** [comment]
Would be nice to update glob, the latest version is `7.0.0`...

**Comment by danielstjules** [comment]
Please see: https://github.com/mochajs/mocha/issues/2058#issuecomment-173077615

This won't be needed until Node 7.0. Furthermore, we can't break support for older version of npm atm. This is something we could pursue in a major release at some point.

**Comment by LinusU** [comment]
Hmm, that's to bad :(

Although Node 0.8 is at end of life, it isn't supported anymore. I think it's time to drop support for that from mocha...

**Comment by danielstjules** [comment]
That's something we can def look into in the next major release :) We wouldn't want to break compatibility in 2.x.x

**Comment by LinusU** [comment]
I understand :+1:
