### ISSUE TITLE
What to do with enormous stack traces?

### ISSUE THREAD

**Issue by rhendric** [mochajs/mocha#2114]
I've seen stack traces that'd shock your eyelids. Hundreds of lines long, these majestic beasts reign supreme over node.js reporter output, overfilling all but the most capacious terminal scrollback buffers.

Something ought to be done! But what?
* A reporter option for turning off stack trace printing?
* A reporter option for truncating stack traces to the top _n_ lines?
* A core Mocha option that drops or truncates stack traces before passing them to the reporter?
* We hate adding options; change the default behavior to truncating stack traces to the top _n_ lines?
* Something else?

I'll make the PR if a maintainer can point me in the desired direction!

**Comment by danielstjules** [comment]
Have you tried https://github.com/rstacruz/mocha-clean ? We do some cleaning ourselves, but it's hard to be conservative with it (only eliminating mocha lines) when using compilers/transpilers.

Closing to direct discussion towards https://github.com/mochajs/mocha/issues/545
