### ISSUE TITLE
code of conduct

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2135]
here's a rough draft:

---
# Mocha Code of Conduct

_This code of conduct is applicable to issues and pull requests on Mocha's GitHub repository, and its Gitter chat room._
1.  Be nice; don't attack or threaten anyone.  
   - If you _aren't_ nice, expect someone to let you know.
   - ...and if you let somebody know, be nice when you do it.
2.  It is difficult to convey tone or attitude in GitHub issues.  Be clear, and _slow down_.
3.  If you're new to GitHub or OSS, look around for resources on etiquette and how to get started--these will help you!
4.  Read `CONTRIBUTING.md` before you contribute.
5.  Mocha is free; please temper your expectations.

---

that's all I got.

**Comment by danielstjules** [comment]
:+1:

I feel like most project code of conducts could be summed up as "Please be nice, don't be rude."

**Comment by boneskull** [comment]
yeah, but if someone acts out you can point them at the CoC for extra leverage, I guess.

**Comment by kunagpal** [comment]
http://contributor-covenant.org/ is also a good reference.
