### ISSUE TITLE
HTML Reporter crashes when an error is thrown in a beforeEach hook

### ISSUE THREAD

**Issue by delta62** [mochajs/mocha#2136]
It appears that the HTML reporter in 2.4.x crashes when an error is thrown in a beforeEach hook. This may effect other hooks (afterEach, before, after) as well. If I swap mocha out for version 2.3.x, everything works as expected.

For a repro, please see [this SAP test repo](https://github.com/delta62/mocha-beforeEach-error). Clone, start up your favorite http server (e.g. `http-server`), and hit `index.html` from your browser.

Chrome 48
Node 4.2.2
NPM 3.3.12

**Comment by andrei-picus-hs** [comment]
This was fixed in #2115 but was not published :sob:

**Comment by drazisil** [comment]
Merged PR, closing issue

**Comment by delta62** [comment]
Thank you!
