### ISSUE TITLE
Retry logic does not work with uncaught exceptions

### ISSUE THREAD

**Issue by grvk** [mochajs/mocha#2137]
Hi,
I'm writing mostly asynchronous tests with Promises. For some reason, retry logic does not work on any of them:

```
describe("Suite", function() {
    this.retries(1);
    var flag = true;

    it("Test", function(done) {
        console.log("Test!!!");
        setTimeout(function() {
            if (flag) {
                flag = false;
                throw new Error()
                done()
            }
            else
                done()
        }, 250);
    });
});
```

Here is the output:

>   Suite
> Test!!!
>     1) Test
> 
>   0 passing (265ms)
>   1 failing
> 
>   1) Suite Test:
>      Uncaught 
>   rror
>       at null._onTimeout (c.js:12:11)

Could you take a look into it?

Thanks,
George

**Comment by Turbo87** [comment]
I think retries(1) means that the test is only tried once. Did you check if retries(2) works?

**Comment by grvk** [comment]
Nope, retries(1) means 1 retry
Yes, I tested it with this.retries(2) as well. It didn't work

**Comment by danielstjules** [comment]
Looks like it's an issue with handling uncaught exceptions, not async tests. For example, if the specs were correctly passing the exceptions to the done handler, or returning them from the promise, things would work as expected:

``` javascript
describe('suite', function() {
  var flag;
  this.retries(1);

  beforeEach(function() {
    flag = true;
  });

  it('spec1', function(done) {
    console.log('running spec1');
    setTimeout(function() {
      if (flag) {
        flag = false;
        done(new Error());
      } else {
        done();
      }
    }, 250);
  });

  it('spec2', function() {
    console.log('running spec2');
    return new Promise(function(resolve, reject) {
      setTimeout(function() {
        if (flag) {
          flag = false;
          reject(new Error());
        } else {
          resolve();
        }
      });
    });
  });
});
```

```
  suite
running spec1
running spec1
    1) spec1
running spec2
running spec2
    2) spec2
```

**Comment by danielstjules** [comment]
Uncaught exception handling is tough without domains or a similar solution. A solution to your issue might get a little harry. But I'd definitely recommend passing exceptions to the spec callback or rejecting them in the promise. Relying on uncaught exception handling in async tests certainly makes things tougher to debug.
