### ISSUE TITLE
Sub folders ignored (even with `--recursive`) when tests present in parent folder

### ISSUE THREAD

**Issue by adamreisnz** [mochajs/mocha#2138]
I'm encountering a strange issue, which I assume is a bug.

The relevant folder structure looks roughly like this:

```
app
  |_ shared
    |_ helpers
```

My `mocha.opts` contains the following:

```
--recursive
--require test/helpers/setup
--require mocha-clean
```

And I am running Mocha using an NPM run script, using:

```
mocha app/**/*.spec.js
```

This was working fine as long as I only had tests in the `shared/helpers` folder. The moment I created a `.spec.js` file in the `shared` folder itself, the tests from `shared/helpers` were no longer executed.

I found a fix for this on StackOverflow, which recommended putting the tests command in a string, like so:

```
mocha "app/**/*.spec.js"
```

However, not sure if that's an artefact of npm or an issue with Mocha.

I also tried to put `app/**/*.spec.js` as the last parameter in `mocha.opts`, but that had the same effect, and putting quotes around it in there caused Mocha to crash.

If any more information is required to reproduce/debug this please let me know.

**Comment by stephanebruckert** [comment]
Kind of the same for me, but in the opposite order. Only the tests in the sub folders were executed (`shared/helpers`) and the ones in the current folder (`shared`) weren't.

Thanks for pointing a fix out, surrounding the path with quotes fixed the issue.

**Comment by actonw** [comment]
Running into this as well.

**Comment by ScottFreeCode** [comment]
This is Posix shells expanding the path before passing it to Mocha; if they're not configured to treat `**` recursively, they'll replace it with only one level of directories, so to make your paths reliable you have to quote them, otherwise Mocha never gets the chance to do anything about it.

**Comment by pratiknikam** [comment]
Had exactly same issue and adding single quotes around path after `--recursive` fixed the issues.

**Comment by mscottx88** [comment]
Unfortunately, this fix does not work cross-platform.

On Windows: 
`mocha -c --reporter=spec --require test/setup.js --recursive test/integration/**/*.spec.js` 👍 
`mocha -c --reporter=spec --require test/setup.js --recursive 'test/integration/**/*.spec.js'` 👎 

On Mac:
`mocha -c --reporter=spec --require test/setup.js --recursive test/integration/**/*.spec.js` 👎 
`mocha -c --reporter=spec --require test/setup.js --recursive 'test/integration/**/*.spec.js'` 👍 

Keep trying!

**Comment by HarrySarson** [comment]
@mscottx88 Does replacing `'` with `"` fix the problem on windows?

**Comment by mscottx88** [comment]
Yes it does :)  That is the cross-platform solution we needed!

`mocha -c --reporter=spec --require test/setup.js --recursive \"test/integration/**/*.spec.js\"`

Windows & Mac 👍 👍

**Comment by hilleer** [comment]
I just came across this issue and for others that might find it too, I can confirm surrounding the path with double quotes solved the issue for me too (on mac).

**Comment by basickarl** [comment]
> Yes it does :) That is the cross-platform solution we needed!
> 
> `mocha -c --reporter=spec --require test/setup.js --recursive \"test/integration/**/*.spec.js\"`
> (as embedded in an `npm run "integration"` script)
> 
> Windows & Mac

Doesn't work on Bash on Linux. 

GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Linux version 4.10.0-32-generic (buildd@lcy01-01) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017

**Comment by ericminio** [comment]
Working on Bash on Ubuntu 20.04: `mocha $(find<folder> -name '*.spec.js')`
