### ISSUE TITLE
This Context Pollution And Inaccessibility

### ISSUE THREAD

**Issue by corybill** [mochajs/mocha#2139]
<pre>
describe("Context Pollution", function () {
  let someErrorMessage;
  beforeEach(function () {
    console.log("bef", this.expectedErrorMessage); // WILL ALWAYS PRINT UNDEFINED
    delete this.expectedErrorMessage; // CANNOT RESET CONTEXT POLLUTION
    this.expectedErrorMessage = undefined; // CANNOT RESET CONTEXT POLLUTION
  });
  it("should fail when the first parameter in mockThisFunction is not a string.", function () {
    this.expectedErrorMessage = constants.errorMessages.MockThisFunctionMockString;
    someErrorMessage = constants.errorMessages.MockThisFunctionMockString;
    expect(this.expectedErrorMessage).eql(this.expectedErrorMessage);
    expect(someErrorMessage).eql(someErrorMessage);
  });
  it("should have undefined values if they are not defined for this test.", function () {
    expect(this.expectedErrorMessage).eql(undefined); // WILL FAIL BECAUSE OF CONTEXT POLLUTION & INABILITY TO RESET THIS CONTEXT
    expect(someErrorMessage).eql(undefined); // WILL FAIL BECAUSE OF CONTEXT POLLUTION & INABILITY TO RESET THIS CONTEXT
  });
  it("should still have undefined values if they are not defined for this test.", function () {
    expect(this.expectedErrorMessage).eql(undefined); // WILL FAIL BECAUSE OF CONTEXT POLLUTION & INABILITY TO RESET THIS CONTEXT
    expect(someErrorMessage).eql(undefined); // WILL FAIL BECAUSE OF CONTEXT POLLUTION & INABILITY TO RESET THIS CONTEXT
  });
});
<pre>

I know that the context pollution issue has already been discussed, but I still believe this to be a serious defect.  A defect that will push me back towards Jasmine very quickly.  I should only have the variables in a test, that I have explicitly defined within that test.  Anything else WILL lead to false positives in test suites.  This is a basic building block to sustainable test suites!!!

That being said, an even more important issue that I am seeing, is that the same this context is not available in the afterEach & beforeEach, that is available in the it blocks.  This means that I can never reset the context pollution, unless I manually do it inside of every it block. Is this intended functionality?  Am I doing something wrong?

I would expect to have access to the same this context throughout all describe, afterEach, beforeEach, and it blocks.  Especially since Mocha allows the this context to be polluted between tests.

I am using the most recent version of Mocha as of today which I believe is 2.4.5.  Thanks for any help / direction you can provide.  Thanks.

**Comment by danielstjules** [comment]
Closing as a dup of your other issue https://github.com/mochajs/mocha/issues/2140
