### ISSUE TITLE
Inaccessibility Of 'this' Context In 'beforeEach'

### ISSUE THREAD

**Issue by corybill** [mochajs/mocha#2140]
<pre>
describe("Context Pollution", function () {
  let someErrorMessage;

  beforeEach(function () {
    console.log("bef", this.expectedErrorMessage); // WILL ALWAYS PRINT UNDEFINED
    delete this.expectedErrorMessage; // CANNOT RESET CONTEXT POLLUTION
    this.expectedErrorMessage = undefined; // CANNOT RESET CONTEXT POLLUTION
  });
  
  it("should fail when the first parameter in mockThisFunction is not a string.", function () {
    this.expectedErrorMessage = "Some errorMessage defined inside of this context";
    someErrorMessage = "Some errorMessage defined outside of this context";
    expect(this.expectedErrorMessage).eql(this.expectedErrorMessage);
    expect(someErrorMessage).eql(someErrorMessage);
  });

  it("should have undefined values if they are not defined for this test.", function () {
    expect(this.expectedErrorMessage).eql(undefined); // WILL FAIL BECAUSE OF CONTEXT POLLUTION & INABILITY TO RESET THIS CONTEXT
    expect(someErrorMessage).eql(undefined); // WILL FAIL BECAUSE OF CONTEXT POLLUTION & INABILITY TO RESET THIS CONTEXT
  });

  it("should still have undefined values if they are not defined for this test.", function () {
    expect(this.expectedErrorMessage).eql(undefined); // WILL FAIL BECAUSE OF CONTEXT POLLUTION & INABILITY TO RESET THIS CONTEXT
    expect(someErrorMessage).eql(undefined); // WILL FAIL BECAUSE OF CONTEXT POLLUTION & INABILITY TO RESET THIS CONTEXT
  });
});
</pre>

I know that the this context pollution issue has already been discussed, but I still believe this to be a serious defect.  I should only have the variables in a test, that I have explicitly defined within that test.  Anything else breaks encapsulation fundamentals and, in my opinion, will lead to false positives in test suites.  Obviously there are work arounds to that issue, by building your own context for each test instead of using 'this'.

That being said, an even more important issue that I am seeing, is that the same this context is not available in the 'afterEach' & 'beforeEach', that is available within the 'it' blocks.  This means that I can never reset the context pollution, unless I manually do it inside of every it block. Is this intended functionality?  Am I doing something wrong?

Expected Behavior
I would expect to have access to the same this context throughout all describe, afterEach, beforeEach, and it blocks.  Especially since Mocha allows the this context to be polluted between tests.

I am using the most recent version of Mocha as of today which I believe is 2.4.5.  Thanks for any help / direction you can provide.  Thanks and I am looking forward to your reply.

**Comment by danielstjules** [comment]
I agree that the behavior is broken. Would you mind directing the discussion to https://github.com/mochajs/mocha/issues/2140 It's hard to change this behavior in a minor since so many test suites could start failing. We'd need to push out a new major. Hope that makes sense!
