### ISSUE TITLE
Compiler and Require Programatic Options

### ISSUE THREAD

**Issue by trainerbill** [mochajs/mocha#2141]
I am using gulp 4, gulp-mocha, with babel, so the babel-register is included.  I cannot get mocha to work with babel.  I have searched everywhere and doing require('babel-register') in the gulpfile does not work.  When I run mocha on the command line it works fine:

```sh
mocha --compilers js:babel-register tests/
```

After looking at the mocha source it looks like neither the require nor the compiler options are supported programatically.

```js
/**
 * Set up mocha with `options`.
 *
 * Options:
 *
 *   - `ui` name "bdd", "tdd", "exports" etc
 *   - `reporter` reporter instance, defaults to `mocha.reporters.spec`
 *   - `globals` array of accepted globals
 *   - `timeout` timeout in milliseconds
 *   - `retries` number of times to retry failed tests
 *   - `bail` bail on the first test failure
 *   - `slow` milliseconds to wait before considering a test slow
 *   - `ignoreLeaks` ignore global leaks
 *   - `fullTrace` display the full stack-trace on failing
 *   - `grep` string or regexp to filter tests with
```
Can these options be supported?  Looks like they would be similar to the globals implementation.

Edit:  Even better could we just get an arguments array that tacks onto the CLI?

**Comment by danielstjules** [comment]
Check this out: https://github.com/jmeas/testing-with-babel

Hope it helps :)
