### ISSUE TITLE
Update TAP reporter to TAP 13

### ISSUE THREAD

**Issue by lencioni** [mochajs/mocha#2149]
I noticed that mocha is using the older TAP specification and wondering if you would be open to updating it to [TAP 13](https://testanything.org/tap-version-13-specification.html)? It is pretty similar. I think the main differences are that version 13 starts with a line that says `TAP version 13`, and encodes test output in YAML.

General format:

``` tap
TAP version 13
1..N
ok 1 Description # Directive
# Diagnostic
  ---
  message: 'Failure message'
  severity: fail
  data:
    got:
      - 1
      - 3
      - 2
    expect:
      - 1
      - 2
      - 3
  ...
ok 47 Description
ok 48 Description
more tests....
```

**Comment by cades** [comment]
+1 for TAP 13
with YAML,  multiline error message can be handled correctly by [testem](https://github.com/testem/testem) test runner.
