### ISSUE TITLE
HTML Reporter: Add count of pending / skipped tests and provide same functionality when clicked as passes and fails

### ISSUE THREAD

**Issue by ericlau-solid** [mochajs/mocha#2150]
![image](https://cloud.githubusercontent.com/assets/8011182/13682947/fce26372-e6b8-11e5-8815-7cf19e1c9732.png)

in HTML reporter, currently there is functionality to filter test results by passes and fails. Requesting the same for pendings (skips). If you think this functionality is good I don't mind taking on the PR work in a few weeks.

**Comment by danielstjules** [comment]
Would love to see a PR for it! :)

**Comment by ericlau-solid** [comment]
#2170 in PR

**Comment by drazisil** [comment]
https://github.com/mochajs/mocha/pull/2170 exists for this, closing this issue
