### ISSUE TITLE
I want to use `tests` directory rather than `test` for testing

### ISSUE THREAD

**Issue by leegom** [mochajs/mocha#2151]
May I implement it through PR?
Or, Are there some old issues or PR related my issue?
Thanks.

**Comment by bbultman** [comment]
While I agree that 'tests' should also be acceptable, right now you could always just specify the folder when you execute mocha:

```$ mocha tests```

**Comment by leegom** [comment]
@bbultman Okay. Thanks! But I wish add *tests* into default test directory same as *test*.

**Comment by danielstjules** [comment]
Thanks for the issue! Unfortunately, this could potentially be a breaking change, since a new directory is suddenly being included by default. As a result, builds could randomly start failing when pulling down a newer version of mocha.
