### ISSUE TITLE
Mocha nomenclature support question

### ISSUE THREAD

**Issue by ORESoftware** [mochajs/mocha#2154]
Hey all

I am wondering what the nomenclature is for Suites and Tests in Mocha.

For example:

```js
describe('A', function(){    // "suite" or "test suite"?

    it('a', function(){    // "test case" ?

    });

   describe('B', function(){     // "suite" or "test suite"?

    it('b', function(){      // "test case" ?

    });
  });

});
```

 I am wondering what the official terms are for these. Do A and B have different names or are they the same? Likewise a and b? My guess is that the top level describe can be considered "Suite", but then what are the nested describes? Are they also monikered "Suite"? I think that's what the code indicates.

**Comment by danielstjules** [comment]
Yup, you've got it right! They're all just suites and tests. :)
