### ISSUE TITLE
Tests are not executing if global.process is set to undefined in NodeJS

### ISSUE THREAD

**Issue by Lewerow** [mochajs/mocha#2160]
If `process` variable is overridden in `beforeEach` with `undefined`, no tests from this suite are executed, and no failures are visible.

here's a minimal failing example:
```javascript

"use strict";

var assert = require('assert');

describe("global process variable overriden", function() {
  var overriddenProcess;
  beforeEach(function() {
    overriddenProcess = process;
    process = undefined; // commenting out this line causes test case to be executed
  });
  
  afterEach(function() {
    process = overriddenProcess;
    overriddenProcess = undefined;
  });
    
  it('causes no tests to be executed', function(done) {
    assert(true);
    done();
  });
});
```

In case you wonder why would I do such a thing: ultimately, I want to port my project (asynchronous time forwarding library: https://github.com/Lewerow/zurvan) to the browser. However, since right now I'm not able to set up entire CI infrastructure for the browser (since most probably it won't work now anyway, as in the beginning I was writing a library dedicated for Node.js), I'm trying to add tests in Node.js that would verify that the library is able to run without some assumptions that can be made for Node.js - such as existence of `process` variable.

**Comment by Lewerow** [comment]
Important detail: this is true for node.js series 0.10, in later ones an error related to timers:
```javascript

  if (!process._needImmediateCallback) {
              ^
TypeError: Cannot read property '_needImmediateCallback' of undefined
    at Object.exports.setImmediate (timers.js:460:15)
    at process._fatalException (node.js:274:40)
```
 
is visible, so it's not that bad (for reference see: https://travis-ci.org/Lewerow/zurvan/builds/116737333)

**Comment by danielstjules** [comment]
I'm not sure that this is something we can accommodate. It's a reasonable assumption and requirement to have the stdlib and env available when running mocha under node. Setting process to undefined in node is comparable to somehow forcing `window = undefined` in a browser.

To work around that, mocha would need to cache references to all required globals, as well as props, and pass them around to all dependencies. For example, while you're only setting `process = undefined`, what if you were first to do `process.nextTick = undefined`? When overwriting global node objects, there's not much we can do to guarantee functionality. Sorry!

My recommendation would be to use browserify in your build step. Then you can continue to use code like `process.nextTick` in the browser.

**Comment by Lewerow** [comment]
Thank you for your response. I certainly do not expect mocha to have full functionality without built-in node variables. However, what I would expect is that if mocha's internal assumptions/requirements are not met, it blows up somehow (not necessarily gracefully - a crash as in 0.11 and newer versions is also fine enough). Otherwise automated CI will not even recognize that something went wrong.

Note: this _might_ be an issue of `node` itself, as the stack points there. 

If you are willing to incorporate such changes, I could take a look at the code to figure out how such safety check should be implemented and issue a pull request afterwards.
