### ISSUE TITLE
Context in before differs when it's in a nested describe vs top level

### ISSUE THREAD

**Issue by ORESoftware** [mochajs/mocha#2165]
Hey all, I am trying to wrap my head around the contexts in the before hooks.

One discrepancy I noticed was the following

<img width="1168" alt="screenshot 2016-03-22 21 41 28" src="https://cloud.githubusercontent.com/assets/11139560/13975866/362dbf74-f077-11e5-9fe4-04894c027a9f.png">

<img width="1143" alt="screenshot 2016-03-22 21 41 50" src="https://cloud.githubusercontent.com/assets/11139560/13975863/2fa6a92c-f077-11e5-8bff-d6a5619cd0fd.png">

As you can see, for the first before hook in the top-level describe "currentTest" is undefined as we would probably expect, since before() hooks don't pertain to a particular test.

But what I didn't except was in the nested describe, the before hook 'this' value has "currentTest" defined. When I inspected with the debugger I could verify this. Why is this the case? Perhaps explaining this might help me understand Mocha contexts. Thanks!

**Comment by ORESoftware** [comment]
here is the original test code that generated the above:



```js

describe('a',function(){


    before(function(){

        console.log('before this a:',this.parent);

    });

    beforeEach(function(){

        console.log('beforeEach this a:',this.parent);

    });


    it('a', function(done){

        console.log('it this a:', this.parent);

        done();

    });


    describe('b',function(){

        before(function(){

            console.log('before this b:',this.parent);

        });

        beforeEach(function(){

            console.log('beforeEach this b:',this.parent);

        });


        it('b', function(done){

            console.log('it this b:',this.parent);


            done();
        });



    });


});
```

**Comment by danielstjules** [comment]
Thanks for reporting this! Yup, this is a bug. A smaller reproduce case:

``` javascript
describe('foo', function() {
  it('test1', function() {});

  describe('nested', function() {
    before(function() {
      console.log('CURRENT:', this.currentTest.title);
    });

    it('test2', function() {});
  });
});
```

```
  foo
    ✓ test1
    nested
CURRENT: test1
      ✓ test2


  2 passing (8ms)
```

This is a known issue here: https://github.com/mochajs/mocha/issues/1638

**Comment by ORESoftware** [comment]
thanks, yeah np I just wanted to make sure because that would throw me way off in understanding what was going on
