### ISSUE TITLE
Assertion errors catched in next test when mocha timeout is applicated

### ISSUE THREAD

**Issue by mpetrak** [mochajs/mocha#2189]
Hi guys,
I'm having troubles with assertions in mocha, which are thrown after mocha timeout and are catched in next running tests.

Example code:
file testA.js
```javascript
var assert = require('assert');

module.exports = {
	'Test A': {
		before: function (done) {
			done();
		},
		'Test step': function (done) {
			this.timeout(5000);
			setTimeout(function (err) {
				assert(false, 'My assertion error!');
				done();
			}, 10000);
			
		},
		'Test step 2': function (done) {
			done();
		},
		after: function (done) {
			done();
		}
	}
};
```
file testB.js
```javascript
module.exports = {
	'Test B': {
		before: function (done) {
			done();
		},
		'Test step': function (done) {
			this.timeout(25000);
			setTimeout(function (err) {
				done();
			}, 20000);
		},
		'Test step 2': function (done) {
			done();
		},
		after: function (done) {
			done();
		}
	}
};
```

If I run `mocha -u exports .` I get:
```
 Test A
    1) Test step
    ✓ Test step 2

  Test B
    2) Test step
    ✓ Test step 2


  2 passing (10s)
  2 failing

  1) Test A Test step:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

  2) Test B Test step:

      Uncaught AssertionError: My assertion error!
      + expected - actual

      -false
      +true
      
      at null._onTimeout (TestA.js:15:5)

```

Problem here is a fact, that assertion error is in testA and I don't want to have it in testB.
Do you have any suggestion how to solve this?

Using:
mocha 2.4.5 with node LTS v4.4.1

**Comment by mpetrak** [comment]
Really nothing?

**Comment by dasilvacontin** [comment]
Sorry @mpetrak, known bug: https://github.com/mochajs/mocha/issues/2137#issuecomment-199100394.

You can try using Promises or passing the error through the done callback.

**Comment by mpetrak** [comment]
Thank you @dasilvacontin

**Comment by dasilvacontin** [comment]
No worries. We could do a better job on the timeout exceeded error message and explain that this scenario can happen.

**Comment by danielstjules** [comment]
Unrelated to retries, but it's a common enough issue. I believe boneskull is looking into alternatives to domains to hopefully make this a bit easier. If you find it difficult troubleshooting a particular error though, here's a workaround for a more accurate error message:

``` javascript
'Test step': function (done) {
    this.timeout(5000);
    setTimeout(function (err) {
        try {
            assert(false, 'My assertion error!');
        } catch (e) {
            done(e);
        }
        done();
    }, 10000);
},
```
