### ISSUE TITLE
How do I know if `beforeEach` is before which task?

### ISSUE THREAD

**Issue by stevemao** [mochajs/mocha#2191]
I have gone through the docs and issues here but I can't find related information. Basically I wanna do something like this:

``` js
beforeEach(function() {
  if (this.testId === 1) {
    console.log('before test 1');
  }
  if (this.testId === 2) {
    console.log('before test 2');
  }
  if (this.testId <= 3) {
    console.log('before test 1, 2 and 3');
  }
  console.log('before every test');
});
```

Is it possible? Or am i using the wrong approach? Thanks.

**Comment by danielstjules** [comment]
I believe it's possible if you don't mind mucking around with the private api, but could it be avoided? If logic in a beforeEach should only run for some subject of the specs, then it sounds like it could benefit from some additional nested suites to appropriately group them?

**Comment by Smurf-IV** [comment]
`
	beforeEach(function () {
		log.debug('***************** %s', this.currentTest.title);
	});
`
