### ISSUE TITLE
nodejs logs dirtied the report xml file

### ISSUE THREAD

**Issue by fanguigui** [mochajs/mocha#2193]
when I run mocha --recursive -R xunit test > test-reports.xml
the report is not formal xml format and jenkins can not open it with Junit\xunit plugin, the report  looks like below
`Listening on port 8079
upload file to : app/1362726851/9089e1faceac11d2767dad24ca410928.png ,success
<testsuite name="Mocha Tests" tests="98" failures="3" errors="3" skipped="0" timestamp="Fri, 08 Apr 2016 09:21:03 GMT" time="6.467">
<testcase classname="addAdopt" name="cookieId null" time="0.065"/> .......`
how can I fix this?

**Comment by juergba** [comment]
You can use the `--reporter-option` flag:
`--reporter xunit --reporter-option output=test-reports.xml`
