### ISSUE TITLE
Tests directory

### ISSUE THREAD

**Issue by richburdon** [mochajs/mocha#2196]
No docs on how to change from the default "test" directory.

> By default, mocha looks for the glob ./test/*.js, so you may want to put your tests in test/ folder.

**Comment by 1j01** [comment]
You can tack on a directory to the mocha command, i.e. `mocha --various arguments tests/`
I also found this to be quite lacking. I don't know how I found how to do this.

**Comment by 1j01** [comment]
I guess it is mentioned vaguely in this line: `Usage: mocha [debug] [options] [files]` (but that's it)

**Comment by danielstjules** [comment]
What @1j01 said :) I find it's easiest to add all those mocha options to your package.json's test script so you just need to remember: `npm test`

**Comment by 1j01** [comment]
Uh, I didn't see any docs get added...
