### ISSUE TITLE
Async tests that must run sequentially.

### ISSUE THREAD

**Issue by alvaro1728** [mochajs/mocha#2197]
I'm trying to test some async calls under multiple test cases that must run sequentially.  So something like this:

```
describe ('case 1', () => {
  it('should test case 1 asynchronously', done => {
       // use setTimeout to run some async tests
       done();
  });
});

describe ('case 2, which should wait for 1 to finish', () => {
  it('should test case 2 asynchronously', done => {
       // use setTimeout to run some async tests
       done();
  });
});
```
Is there an easy way to tell the second "it" to wait until the first one has called done?

Thanks!
Alvaro

**Comment by boneskull** [comment]
tests run in serial.  do you have some sort of reproducible case where that's *not* happening?

**Comment by alvaro1728** [comment]
My tests are not running sequentially if case 1 calls setTimeout(someFunctionThatDependsOnAnEvent, 500). It will proceed to case 2 while case 1 is waiting to finish.  But my case 2 depends on case 1 -- it's a workflow, so it will fail if it runs before case 1 has finished.   Thanks.

**Comment by alvaro1728** [comment]
I went back to try to reproduce this but figured out it's because I didn't have a "done" in my first case.  Once I added it and called it, I got the proper sequential behavior.  Thanks.

**Comment by PoojaMittal27** [comment]
test.describe("Testing", function () {

    const driver = new wd.Builder().forBrowser('chrome').usingServer(server_url).build();

     before(function () {
         driver.get(config.site_url);
     });

    it('Login', done => {
        console.log("Inside Test case")
        let pageNavigator = new PageNavigator({ driver: driver });
        pageNavigator.visit(config.site_url).then(function () {
            console.log("Enter credentials");
            driver.findElement(by.id('edit-name')).sendKeys('test@gmail.com');
            driver.findElement(by.id('edit-pass')).sendKeys('rdftgyh');
            console.log("Enter credentials");
            driver.findElement(by.id('edit-submit')).click();
        }).then (()=>{
            done();
            driver.quit();
             })
   
    });

    after(function () {
         driver.quit();
    });

});

I'm trying this code. All before, it and after run parallel while I want to write the cases dependent on prior cases. Is there any way to run the cases one by one.

**Comment by abhinavrastogi** [comment]
Unless `driver.get(...)` is a blocking call, you need to pass `done` to `before` and `after` too. Or use `async-await`.

```js
before(async function () {
     await driver.get(config.site_url);
 });

it('Login', async function() {
    //...
});

after(function(done) {
    driver.quit().then(() => {
        done();
    });
});
```

**Comment by kanikeravi** [comment]
> My tests are not running sequentially if case 1 calls setTimeout(someFunctionThatDependsOnAnEvent, 500). It will proceed to case 2 while case 1 is waiting to finish. But my case 2 depends on case 1 -- it's a workflow, so it will fail if it runs before case 1 has finished. Thanks.

Can you provide the sample code. I tried this, still I m not able achieve it. 

Spec file : 
```
describe('Testing specs', function () {
  it('one',  done => {    
      console.log('First');
      global = test.getValue();
      done();    
  })
  it('Two', done => {    
      console.log('Second')
      console.log('global value is ', global);
      done();
  });
})
```
getValue Method : 
```
getValue() {
        setTimeout(function () {
            return 1;
        }, 2000)
    }
```
