### ISSUE TITLE
Promise handling not working in node v5.5.0

### ISSUE THREAD

**Issue by danieldkim** [mochajs/mocha#2203]
Simple test:

```javascript
it('should wait for the promise', function() {
  console.log("foo...")
  return new Promise(function(resolve, reject) {
    setTimeout(function () {
      console.log('bar.')
      resolve();
    }, 100);
  });
});
```

Using node v4.2.2, mocha waits for the promise to resolve and "bar" is printed to the console.  Using node v5.5.0, that does not occur.

**Comment by danieldkim** [comment]
```
foo@bar[~/projects/myproject](Mon Apr 11 19:35:44)$ node --version
v5.5.0
foo@bar[~/projects/myproject](Mon Apr 11 19:36:38)$ mocha test/promise.js 
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.

  foo...
․

  ✔ 1 test complete (17 ms)

foo@bar[~/projects/myproject](Mon Apr 11 19:38:43)$ nvm use 4
Now using node v4.2.2 (npm v2.14.7)
foo@bar[~/projects/myproject](Mon Apr 11 19:38:50)$ mocha test/promise.js 


foo...
bar.
  ✓ should wait for the promise (107ms)

  1 passing (119ms)

foo@bar[~/projects/myproject](Mon Apr 11 19:38:53)$ node --version
v4.2.2
```

**Comment by parinck** [comment]
`it('should pass', (done) => {
			var a = {
				"key": 123
			};
			var b = {
				"key": "123123123123123"
			};
			//assert.deepEqual(b, a, "response doesnot match");
			let p = new Promise(function(resolve, reject) {
				setTimeout(function() {
					resolve();
				}, 100)
			});

			p.then(function success() {

				console.log("success---->", a, b);
				assert.deepEqual(a, b, "response doesnot match");
				// assert.equal(b.key, a.key, "response doesnot match");

				done();
			}, function error() {

				console.log("error---->", a, b);
				assert.deepEqual(a, b, "response doesnot match");
				// assert.equal(b.key, a.key, "response doesnot match");

				done();
			});
		});`

same is happening for me also. node 5.6.0

**Comment by dasilvacontin** [comment]
Weird, works for me (I added a `console.log(process.version)` just in case)

```
➜  temp mocha
v5.5.0

foo...
bar.
  ✓ should wait for the promise (257ms)

  1 passing (262ms)
```

**Comment by danieldkim** [comment]
Sorry, false alarm.  Weird issue with nvm where it's linking to an old version of mocha in the non-nvm node location when i do `npm install -g mocha` while using node 5.  Closing.
