### ISSUE TITLE
`--ui require` for require interface

### ISSUE THREAD

**Issue by jmm** [mochajs/mocha#2210]
There seems to be quite a bit of discussion about how to handle globals in future versions of Mocha, e.g. https://github.com/mochajs/mocha/issues/1969. It seems like that stuff is going to be slow to hash out. In the meantime I'd like to suggest that you consider making it possible to do `mocha --ui require` to signal that you want the require interface -- meaning that you _don't_ want globals defined. To me the current system is a half measure -- if you want to avoid using globals what you really want is to avoid them being defined at all to eliminate pollution of the global namespace and a source of potential bugs. To me it's very odd that "using" the require interface still requires using one of the other interfaces, which by default is `bdd` which defines globals.

**Comment by JoshuaKGoldberg** [comment]
> that stuff is going to be slow to hash out

...yes 😄. `require` is becoming less of a common practice over time in modern JS code. ESM is taking over. Closing this as aged away.

**Comment by lo1tuma** [comment]
> If anybody has a really compelling use case for continuing to `require` with Mocha, please do file a new issue with details. Thanks!

I’m not sure if there is a misunderstanding here. If I understand the request correctly it is about the `require` interface from `mocha` as an alternative to e.g. `bdd`. It is not about supporting commonjs or not. Mochas `require` interface also works with `ESM`. So ideally the interface should be renamed, but that is a different topic.

Right now it is not possible to define the `require` interface via `--ui` so one of the other interfaces has to be used, if non is chosen the default `bdd` will apply. The reason for picking the `require` interface is to avoid the `globals` from mocha. So the request here is that when explicitly setting `--ui require` mocha doesn’t set any global variables und functions like `describe` or `it` can be only accessed when requiring them or importing them.

Related:
* https://github.com/mochajs/mocha/issues/1160
* https://github.com/mochajs/mocha/issues/956

**Comment by JoshuaKGoldberg** [comment]
We're talking about https://mochajs.org/#require, right?

If so: #956 would be the right tracking feature there. _"require"_ as a term is what we're trying to avoid. A name like _"import"_ or _"esm"_ (just ideating) would be more forward-facing.

But, also note #5027: we're intentionally trying to change too many big things with Mocha.

**Comment by lo1tuma** [comment]
> We're talking about https://mochajs.org/#require, right?

Yes, exactly.


> If so: https://github.com/mochajs/mocha/issues/956 would be the right tracking feature there.

Alright, I will add a comment there suggesting this feature as one way to opt-out of globals.

**Comment by JoshuaKGoldberg** [comment]
Awesome thanks! FWIW I think I'm pretty in agreement with you, that having some equivalent to `--ui require` would be the right way to go long-term. `@jest/globals` was a nice step in Jest-land a bit back, and Vitest not enabling global by default is IMO a good thing (for them, without the long backwards compatibility story of Mocha).
