### ISSUE TITLE
Suppress intentionally thrown errors

### ISSUE THREAD

**Issue by teckays** [mochajs/mocha#2217]
I'm building a module that handles Express error logging and I have an endpoint where I intentionally throw an error. I do this because I want the error to pass through the error handling Express middleware and log it with a specific `winston` transport. However I would like to suppress the error so it's stack is not printed when I run my tests with mocha. Any way to do this?

**Comment by danielstjules** [comment]
Hi @teckays I'd disable console output in the winston transport, perhaps by directing the output to a different stream of your choice so you can still add some assertions. If the stacktrace is being logged by a different function, then again, I'd either disable/redirect it, or just overwrite console.log/process.stdout.write for that spec.

There's a pretty long issue on the topic here that includes an example: https://github.com/mochajs/mocha/issues/1582#issuecomment-87464832

Hope that helps!
