### ISSUE TITLE
🐛 Bug: Internal errors in reporter for pending tests incorrectly labelled

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mocha#2220]
In the process of digging into #2211 (e.g. [as discussed in this comment](2211#issuecomment-213286956)), I discovered that failures when processing a test that was not run (e.g. incorrect pending checks in a reporter, although it seems those particular errors have been fixed in master) will be reported as belonging to a previously run test or hook. To see, simply take master, add an error to a reporter's processing of a pending test result, and run a suite with pending tests after either non-pending tests or a before or beforeEach hook that will run.

I've narrowed it down to the fact that the `currentRunnable` variable in mocha/lib/runner.js is assigned whenever a hook is found and whenever a test _is run_, but not if a test is pending. I believe there are a couple possible fixes:
- Remove `self.currentRunnable = self.test;` [on line 527 of runner.js](../blob/d4f7905dbb9d4cc65cca02373b99e5549fa7ce2a/lib/runner.js#L527), add `self.currentRunnable = test;` at [line 509](../blob/d4f7905dbb9d4cc65cca02373b99e5549fa7ce2a/lib/runner.js#L509) (well, between what's currently lines 508 and 510; there should probably be a couple newlines on either side of the added line), so that errors occurring during processing of pending tests are reported with that test's description rather than with the most recently run test or hook's description. (`currentRunnable` isn't used except in uncaught error reporting, so this shouldn't have any unwanted side effects.)
- Detect and specially label errors originating in Mocha code rather than test code; for instance, wherever it's getting the stack location of the error in the case of internal errors, also override the name associated with the error to something like "Mocha internal error" instead of the name of the `currentRunnable`.
- Both -- fix the `currentRunnable` for the case of pending tests, but also prepend "Mocha internal error processing: " to the name reported when a Mocha internal location is found for the error's origin.

**Comment by JoshuaKGoldberg** [comment]
This hasn't had interactions since 2017. Closing out as stale/wontfix - but if someone has a real repro of the issue, please do post so we can re-open. Cheers!
