### ISSUE TITLE
Cannot find module 'chai' ?

### ISSUE THREAD

**Issue by sunnysk** [mochajs/mocha#2223]
I'm trying to study mocha and after I execute the getting started demo ,It show me the error 
Cannot find module 'chai'

**Comment by danielstjules** [comment]
Sounds like you haven't installed chai yet! Try running `npm install --save chai` from the directory :)

**Comment by sunnysk** [comment]
@danielstjules I use require('assert') to instead require('chai').assert , it works ok ,so I wanna know why the getting started use require('chai').assert

**Comment by danielstjules** [comment]
chai is just one of many assertion libraries you can use with mocha. For example:
* https://nodejs.org/api/assert.html (what you're using)
* http://chaijs.com/
* https://github.com/Automattic/expect.js
* https://github.com/tj/should.js/

**Comment by sunnysk** [comment]
@danielstjules got it,  thx a lot !
