### ISSUE TITLE
Configure compilers from mocha setup

### ISSUE THREAD

**Issue by akofman** [mochajs/mocha#2225]
Hello,

Would that make sense to add the ability to configure compilers from `mocha.setup` ?
I noticed it is possible to configure some options like : ui, reporter, bail etc ... but the cli has still more options which are not accessible programatically.
I just ask the question, I'm a beginner with mocha so maybe I didn't get some points.

Thanks for your responses !

**Comment by boneskull** [comment]
Can you explain your use-case a bit more thoroughly?  What are you trying to compile (in the browser)?

**Comment by akofman** [comment]
Yep, I'd like to compile with babel-register as I can do it using the command line : `mocha --compilers js:babel-register`.
My goal would be to use it from the [webpack/mocha-loader](https://github.com/webpack/mocha-loader) loader. It could be convenient to easily configure hot reload tests. A workaround is to add the babel loader to your project and configure it from the webpack config but it's a little bit verbose comparing just using the mocha loader.
