### ISSUE TITLE
Exclusive Tests running different test suite with same title

### ISSUE THREAD

**Issue by andrewmunro** [mochajs/mocha#2226]
Minor issue but it caused me a headache to pin down and see what was happening.

I have two test files with the same suite name:
```
//MyComponent.test.js
describe("MyComponent", function()....

//MyComponent.test.jsx
describe("MyComponent", function()....
```

After putting a `.only` on the first suite, it was running tests in the second one:
```
//MyComponent.test.js
describe.only("MyComponent", function()....

//THESE TESTS RUN INSTEAD!
//MyComponent.test.jsx
describe("MyComponent", function()....
```

The obvious fix was to change the suite titles so they are unique, but I feel like this should either be fixed or well documented somewhere.

**Comment by scags9876** [comment]
+1

Just encountered the same

**Comment by boneskull** [comment]
let's just say `only` doesn't work the way you think it does (it uses pattern matching).  this has been addressed in many issues already
