### ISSUE TITLE
deprecated graceful-fs usage

### ISSUE THREAD

**Issue by CafeLungo** [mochajs/mocha#2227]
When including mocha as a dependency, I'm getting the following warning at 'npm install'

> npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

Traced this to the use of an old version of 'glob' in mocha (I think).

I also receive a warning about jade, but that issue is already reported under #2200.

**Comment by danielstjules** [comment]
This has been fixed in master: https://github.com/mochajs/mocha/commit/c9bcfc1b015c8d15d5fe5159e30818cd02f6a098
Thanks! :)

**Comment by silkentrance** [comment]
Great! Now the warning is somewhat like ``gracefulfs will break with node > 6.x`` :grin:
