### ISSUE TITLE
Please update glob version

### ISSUE THREAD

**Issue by plynchnlm** [mochajs/mocha#2230]
I am trying to use mocha with node v6.  When I npm install mocha, it pulls mocha 2.4.5 (the latest tagged version) and I get the message:

"graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v6.0"

graceful-fs is a dependency of glob, which is specified in package.json (of mocha 2.4.5) to be exactly 3.2.3.  The latest version of glob does not use graceful-fs.

**Comment by danielstjules** [comment]
This has been fixed in master :) https://github.com/mochajs/mocha/pull/2201
