### ISSUE TITLE
Not able to find element using element id on webview

### ISSUE THREAD

**Issue by PankajImpetus** [mochajs/mocha#2235]
I want to automation one login page (web-view) for an ios application, i can locate the ID of the username and password field but when i am using the driver.elementById() it shows no such element found. Does any one have any idea about this.
I am using mocha and chai.

**Comment by danielstjules** [comment]
Hi! I'd recommend posting in the issue tracker for the driver you're using instead, as the problem isn't mocha-specific. Good luck!
