### ISSUE TITLE
NPM dependencies need updating

### ISSUE THREAD

**Issue by genyded** [mochajs/mocha#2237]
Getting warnings about Jade being renamed to Pug and also graceful-fs version being deprecated and no longer working with newer versions of NPM.

**Comment by aaronmcohen** [comment]
+1

**Comment by gabrielcsapo** [comment]
also getting warnings about `graceful-fs`

```
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v6.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```

```
└─┬ mocha@2.4.5
  └─┬ glob@3.2.3
    └── graceful-fs@2.0.3 
```

**Comment by amacneil** [comment]
Looks like the glob/graceful-fs issue was [already fixed on master](https://github.com/mochajs/mocha/commit/c9bcfc1b015c8d15d5fe5159e30818cd02f6a098), just need a new version released.

**Comment by boneskull** [comment]
please see pr #2234 re glob and issue #2200 for jade
