### ISSUE TITLE
--require doesn't work for properly formed modules

### ISSUE THREAD

**Issue by jdmarshall** [mochajs/mocha#2240]
I've seen a number of examples around the internet of using --require for example to do:

`mocha --require chai`

While that will load chai, since chai is a normal module, it doesn't write any values into the global namespace, so --require means you still have to do require('chai')

As written, it seems to only be useful for loading arbitrary javascript files.  Was that the intended use case?

**Comment by boneskull** [comment]
That's how it's supposed to work, yes.  If you want to stuff something into the global context, do this:

```js
// fixture.js
global.expect = require('chai').expect;
```

and

```shell
$ mocha --require fixture
```
