### ISSUE TITLE
Shared Specs - Incorrect Logging

### ISSUE THREAD

**Issue by jamescmartinez** [mochajs/mocha#2241]
Let's assume I have two files:

`user.js`

``` js
import { User } from '../../app/models'
import { validatesPresence } from './shared-specs'

describe('User', () => {
  describe('.jsonSchema', () => {
    validatesPresence(User, 'username')
  })
})
```

`shared-specs.js`

``` js
import { expect } from 'chai'

export function validatesPresence(model, attribute) {
  it(`validates presence of ${attribute}`, () => {
    expect(() => {
      const json = {}
      json[attribute] = null
      model.fromJson(json)
    }).to.throw(model.ValidationError)
  })
}
```

When running my tests, I expect the following output:

```
User
  .jsonSchema
    ✓ validates presence of username
```

...but instead I'm getting this:

```
✓ validates presence of username
User
  .jsonSchema
[OTHER SPECS]
```

**Comment by ScottFreeCode** [comment]
Which ES6 module system implementation is this running on? Are the files bundled? Is Mocha being run on the Node commandline, or in a browser?

**Comment by jamescmartinez** [comment]
Command line using Babel.

**Comment by ScottFreeCode** [comment]
Thanks; I'll see if I can reproduce this and start looking for the source of the issue.

**Comment by boneskull** [comment]
I'd like to see if using `require()` instead of `import` here makes a difference

**Comment by ScottFreeCode** [comment]
Well, I'm getting this:
```
  User
    .jsonSchema
      √ validates presence of username


  1 passing (142ms)
```

At least, when I used this as models\index.js:
```js
export const User = {
  fromJson: function fromJson(json) {
    if (!json.username) {
      throw new ValidationError("User needs username")
    }
  }
}
```
...and this .babelrc:
```json
{
  "presets": ["es2015"]
}
```

**Comment by ScottFreeCode** [comment]
I did just pick up on a subtlety in dealing with a delayed test definition in another issue: if the function that actually calls `it` does so in an asynchronous callback, then `it` ends up being called outside the `describe` block and will end up reported as though it were top-level rather than reported as a member of that suite. Is it possible this is what's happening in your tests?
