### ISSUE TITLE
path.resolve('C:') is different from process.cwd() on Windows.

### ISSUE THREAD

**Issue by sttk** [mochajs/mocha#2242]
When the following code is executed,

```js
const path = require('path');
            
console.log('1.');                                                     
console.log(process.cwd());
console.log(path.resolve('C:'));

process.chdir(process.cwd());

console.log('2.');
console.log(process.cwd());
console.log(path.resolve('C:'));
```
the result is as follows:

```
C:\Users\sttk\Works>node test
1.
C:\Users\sttk\Works
C:\Users\sttk\Works
2.
C:\Users\sttk\Works
C:\Users\sttk\Works

C:\Users\sttk\Works>mocha test
1.
C:\Users\sttk\Works
C:\                   <= why?
2.
C:\Users\sttk\Works
C:\Users\sttk\Works

```

**Comment by boneskull** [comment]
I have no idea.

**Comment by timaschew** [comment]
How this is related to mocha?

**Comment by sttk** [comment]
I don't know whether this is mocha's problem, but when I did a test case related to path on Windows, this difference was a cause of a NG.
I resolved it by executing `process.chdir(process.cwd())`, but I thought I should report this behavior for your information.
If this is not mocha's problem, I'm OK that this issue will be closed.

**Comment by ScottFreeCode** [comment]
I've narrowed it down to a minimal test case, although I haven't determined whether it's intended Node behavior and/or we're doing something wrong, or if it's a Node bug:
> test.js

```js
const path = require("path")

console.log(path.resolve("C:"))
console.log(process.cwd())

process.chdir(process.cwd())

console.log(path.resolve("C:"))
console.log(process.cwd())
```
> wrap.js

```js
var spawn = require('child_process').spawn,
  path = require('path'),
  args = [path.join(__dirname, 'test.js')];

spawn(process.execPath, args, { stdio: 'inherit' });
```
Call `node wrap.js` to see the issue.

I believe this is coming into play in Mocha because `mocha` spawns `_mocha`.

**Comment by sttk** [comment]
@ScottFreeCode Thanks!

**Comment by boneskull** [comment]
Maybe pass `cwd` when spawning?

**Comment by sttk** [comment]
@boneskull It would be good about current drive. But considering current directories of other drives also, it may be troublesome.

**Comment by sttk** [comment]
This issue was solved as an issue of node.js : [nodejs/node#7215](https://github.com/nodejs/node/issues/7215)

So I think it's ok to close this issue.

@ScottFreeCode Thank you for sending a PR to node team and explaining to them the details about this issue.

**Comment by ScottFreeCode** [comment]
Huh, I hadn't realized this one was still open. Yeah, it looks like their fix should resolve it with the next version of Node. We can always review then if need be!
