### ISSUE TITLE
Bump major version of glob

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [mochajs/mocha#2247]
Can you please bump the version of glob? I think this repo is the reason why I see deprecations warnings for `graceful-fs` on nearly every `npm install`

**Comment by eljefedelrodeodeljefe** [comment]
See

```
yargs@4.7.0 /Users/jefe/repos/yargs
├─┬ cpr@1.1.1
│ └── graceful-fs@4.1.4 
├─┬ mocha@2.4.5
│ └─┬ glob@3.2.3
│   └── graceful-fs@2.0.3 
└─┬ nyc@6.4.4
  ├─┬ caching-transform@1.0.1
  │ └─┬ write-file-atomic@1.1.4
  │   └── graceful-fs@4.1.4 
  └─┬ yargs@4.7.0
    ├─┬ pkg-conf@1.1.2
    │ └─┬ load-json-file@1.1.0
    │   └── graceful-fs@4.1.4 
    └─┬ read-pkg-up@1.0.1
      └─┬ read-pkg@1.1.0
        ├─┬ load-json-file@1.1.0
        │ └── graceful-fs@4.1.4 
        └─┬ path-type@1.1.0
          └── graceful-fs@4.1.4 
```

**Comment by robogeek** [comment]
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

**Comment by wyaeld** [comment]
I can see this is done by https://github.com/mochajs/mocha/commit/c9bcfc1b015c8d15d5fe5159e30818cd02f6a098

but still need them to actually cut a release

**Comment by eljefedelrodeodeljefe** [comment]
That and still it's only v3. @boneskull I feel this is rather urgent. Can you cut a release from this?

**Comment by boneskull** [comment]
@eljefedelrodeodeljefe What's urgent about it?

**Comment by boneskull** [comment]
(a release won't happen until #2231 is merged; this will likely happen *before* Node.js v7 is released.  if you're in a hurry, you can either suppress the warnings or `npm install mochajs/mocha` to get the latest source in `master`)

**Comment by eljefedelrodeodeljefe** [comment]
It's very bad UX for two thirds of npm users seeing deprecations warnings and wondering what is wrong and not being able to do anything.

**Comment by eljefedelrodeodeljefe** [comment]
hmm. Waiting for that PR seems ambitious.

**Comment by boneskull** [comment]
*channeling Allen Iverson*

I mean, listen, we're sitting here talking about a *warning*.  Not an *error*.  Not an *error*.  Not an *error*.  But we're talking about a *warning*.  We're not talking about an *error*.  We're not actually talking about an *error*, where it actually matters, but we're talking about a *warning*.  

* * * 

I've seen maybe 10 issues created for this issue. I am not sure what is so scary about a *warning* involving *a version of Node.js that is not released yet*.  Let's just all take a deep breath and realize that the sky will not fall.  

We'll do the next release methodically to mitigate the likelihood of *actual errors*.  We're not going to rush it to suppress a warning.

**Comment by eljefedelrodeodeljefe** [comment]
Yeah that's all fine. Still that makes me question why an integral part of the ecosystem fails to nurture its development by not updating ancient dependencies. The is the pre-stage of issues like left-pad and deeply worry me.

**Comment by boneskull** [comment]
@eljefedelrodeodeljefe [this is why](https://github.com/mochajs/mocha/issues/2200#issuecomment-216017864)

**Comment by wyaeld** [comment]
It's pretty obvious at this point that @boneskull 

1. has a plan on when he wants to release
2. cares about maintaining compatibility for his users

He's described a workaround, I just updated to use it and moved on.

Here are the docs for anyone not familiar with that - ironically using mocha as an example.
https://docs.npmjs.com/files/package.json#github-urls

Comparing this to left-pad is a bit poor though.  The team here deserves a bit of gratitude for the work being put in.
