### ISSUE TITLE
How to require multiple modules?

### ISSUE THREAD

**Issue by purezen** [mochajs/mocha#2250]
I am setting up tests for my app using mocha and wanted to use multiple modules but it seems the -r (--require) argument only allows to use one module(?).

**Comment by boneskull** [comment]
`--require module --require some_other_module --require yet_another_module`

**Comment by purezen** [comment]
@boneskull does it work on your system? Because when I try it, it doesn't give an error, but only loads the first package mentioned. Ditto when done using `mocha.opts`.

**Comment by boneskull** [comment]
yes.

```js
// a.js
console.log('a');
```

```js
// b.js
console.log('b');
```

```js
// test.js
const assert = require('assert');

describe('test', function () {
	it('should pass', function () {
		assert(true);
	});
});
```

```shell
$ mocha --require a --require b test.js
a
b


  test
    ✓ should pass


  1 passing (6ms)
```

**Comment by jonathansampson** [comment]
@boneskull Any particular reason a list isn't supported? `-r foo bar` or `-r foo, bar`

**Comment by boneskull** [comment]
`--require x --require y`

**Comment by jonathansampson** [comment]
@boneskull My apologies if I wasn't clear; why not support something like `--globals` where values are separated by commas (or spaces)?
