### ISSUE TITLE
describe.only fails when used in combination with -i and -g command-line options

### ISSUE THREAD

**Issue by scouten** [mochajs/mocha#2260]
**Steps to reproduce:**
1. Create a test suite that has multiple top-level `describe` tests.
2. Mark one of those tests as `describe.only`.
3. Run mocha with `-i` and `-g` options. (Choose a filter that does not match the test chosen for step 2 above.)

**Expected result:**

Only tests within the top-level suite chosen within step 2 above are executed, provided they do not match the filter specified in step 3.

**Actual result:**

The test specified in step 2 does not run. Tests in every **other** top-level suite are executed, again provided they do not match the filter specified in step 3.

Note that the obvious workaround (to try to use `describe.skip`) also fails, because `.skip` actually works as intended. 😢

**Comment by scouten** [comment]
Related: If you are using `describe.only` without the `-i` and `-g` options as specified above, mocha will also run any other unrelated tests that happen to grep-match the name of the `.only` suite, even reaching inside other suites.

**Comment by boneskull** [comment]
do you know of *any* workaround?

**Comment by scouten** [comment]
No, I don't.

**Comment by ScottFreeCode** [comment]
Given that `only` uses `grep`, isn't using `only` and the `-g` flag equivalent to using `only` twice?

**Comment by scouten** [comment]
@ScottFreeCode IMHO the fact that `only` uses `grep` is an implementation detail (and IIRC is not mentioned in the docs).

**Comment by ScottFreeCode** [comment]
Apologies for not following up on this when 3.0.0 was released -- the change to make `only` no longer piggyback on `grep` *should* have fixed this. @scouten if it still matters to you, can you confirm that it works in Mocha >= 3? (And sorry about digging this up after all this time.)

**Comment by scouten** [comment]
@ScottFreeCode I'm not currently doing any JavaScript work, so I don't really have a way to test this now. Best wishes.

**Comment by ScottFreeCode** [comment]
Alright, thanks! Given that it shouldn't be an issue in Mocha >= 3, I'm going to go ahead and close this for now, but if you come back to it and still have trouble just let us know!
