### ISSUE TITLE
Mocha doesn't play nicely with absolute import paths

### ISSUE THREAD

**Issue by ffxsam** [mochajs/mocha#2261]
When my Mocha tests import some of my React components that use absolute import paths, things go south. For instance, I might have a test that imports a JS file which starts out with:

```
import React from 'react';
import MyThing from '/client/components/MyThing';
```

Mocha bombs out at the second line because it doesn't understand absolute paths. These are used all over my app which has thousands of lines of code, so I'd rather not go through and change all my imports. Especially since I have a pretty deep folder structure and would wind up with import statements such as:

    import MyThing from '../../../../client/components/MyThing';

**Comment by ScottFreeCode** [comment]
Can you elaborate on the error itself? I would think that imports are handled by something other than Mocha itself (a module loader, maybe an ES6+ transpiler, etc.).

I've seen another weird import-related issue recently... here it is: #2241 I wonder if the ES6+ implementations we have so far have some kind of quirk with their module system...

**Comment by ffxsam** [comment]
Sure! So the command being issued is:

    mocha --watch tests/.setup.js tests/**/*-test.js

Here are all the relevant files:

#### tests/.setup.js
```
require('babel-register')();

var jsdom = require('jsdom').jsdom;

var exposedProperties = ['window', 'navigator', 'document'];

global.document = jsdom('');
global.window = document.defaultView;
Object.keys(document.defaultView).forEach((property) => {
  if (typeof global[property] === 'undefined') {
    exposedProperties.push(property);
    global[property] = document.defaultView[property];
  }
});

global.navigator = {
  userAgent: 'node.js'
};

documentRef = document;
```

#### .babelrc
```
{
  "presets": ["airbnb", "stage-2"]
}
```

**Comment by ScottFreeCode** [comment]
Cool, that should be enough for me to see if I can reproduce it and start looking for where the problem lies.

**Comment by ffxsam** [comment]
In the mean time, I've got a workaround (solution?): https://forums.meteor.com/t/solved-mocha-is-unhappy-about-absolute-paths-and-meteor-imports

**Comment by ScottFreeCode** [comment]
Alright; so, I tried this with these files:
- setup.js
```js
require("babel-register")()
```
- producer.js
```js
export default "example"
```
- consumer.js
```js
import data from "./producer"
console.log(data)
```
Ran it with `node -r ./setup consumer.js` and got `example` printed on the console. So far, so good.

Changed "./producer" to "/producer", "producer", "/my-test-package/producer" and "my-test-package/producer" and got this error:
```
module.js:440
    throw err;
    ^

Error: Cannot find module '{attempt name}'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (consumer.js:1:42)
    at Module._compile (module.js:541:32)
    at loader ({path to}/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] ({path to}/node_modules/babel-register/lib/node.js:168:7)

    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
```

Then I tried changing the test to this:
- producer.js
```js
module.exports = "example"
```
- consumer.js
```js
var data = require("./producer")
```
Ran it with `node consumer.js`, got `example` printed, tried the four variations on the path to producer in consumer.js and got a very similar error and stacktrace:
```
module.js:440
    throw err;
    ^

Error: Cannot find module '{attempt name}'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ({path to}/consumer.js:1:80)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

So, my hunch was actually only half right, half wrong -- this not only doesn't seem to be a Mocha issue, but it doesn't even seem to be a Babel issue; looks like it's just a Node limitation.

**Comment by ffxsam** [comment]
I can close this issue, I just wasn't sure where to report it (if it was Node, Mocha, etc). And I'm happy with the workaround that someone provided.

**Comment by ScottFreeCode** [comment]
Sounds good; looks like that plugin manages to find the root of the package (or of wherever it's being run from?), so that would work around Node's limitation. There seem to be a few different approaches out there with different pros and cons, but I guess that's a discussion for another time. Give my regards to the good folks who found your solution!

**Comment by deanius** [comment]
Thanks @ffxsam that was just what I needed tonight :)
