### ISSUE TITLE
Double error report on minimal test case

### ISSUE THREAD

**Issue by gertsonderby** [mochajs/mocha#2263]
A (purposely) failing test in [gertsonderby/C1-Prototype](https://github.com/gertsonderby/C1-Prototype) (described in [this file](https://github.com/gertsonderby/C1-Prototype/blob/master/test/minimum.spec.js)) shows the error report twice. It's set up to be run in the browser, go to /test/index.html.

The same problem occurs if replacing the assertion with a `throw` statement.

This is tested on Windows, using npm 2.15.1, jspm 0.16.34, systemjs 0.19.27, mocha 2.4.5, unexpected 10.13.2.

**Comment by dasilvacontin** [comment]
Dup of #2083.
