### ISSUE TITLE
2.4.5 -> 2.5.0 update: Error: Cannot find module 'to-iso-string'

### ISSUE THREAD

**Issue by gr2m** [mochajs/mocha#2278]
```
$ node --version
v4.4.4
$ npm --version
2.15.1
```

I see a lot of errors like these: https://travis-ci.org/hoodiehq/hoodie-app-tracker/jobs/132202611. Seems like others have the issue, too. Look for `mocha@2.5.0 breaks build 🚨` in https://github.com/greenkeeperio-bot?tab=activity

Pretty much every project I use mocha in right now has that failing build. I could not reproduce the problem locally yet. I tried clearing travis cache and restart, didn’t help. My guess is that it is somehow related to npm 2.15.1? 

Others might run into the same problem so I thought it’d be worth opening the issue

**Comment by gr2m** [comment]
ah seems it’s already fixed in https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#251--2016-05-23

Maybe leave that open for a day or two to avoid duplicate issues, your call. Thanks for all the work <3

**Comment by azu** [comment]
It seem that this issue was resolved by 2.5.1 https://github.com/mochajs/mocha/commit/3ef083ef0ccdc95286fc0395847df3ca075806d3

**Comment by dasilvacontin** [comment]
@gr2m Thank you for reporting the issue and supporting Mocha. <3
