### ISSUE TITLE
Add a command line flag to error on `.only`

### ISSUE THREAD

**Issue by jacobcarpenter** [mochajs/mocha#2280]
[Exclusive tests / `.only`](https://mochajs.org/#exclusive-tests) is a great development-time convenience. However, it seems like it might be easy to forget to remove an `.only` call before committing.

Can we add a command line option to force the runner to fail if there are any `.only` calls present?

This would be handy to specify on the build server and when running locally before committing.

**Comment by dahjelle** [comment]
I just discovered [eslint-plugin-no-only-tests](https://github.com/levibuzolic/eslint-plugin-no-only-tests) which uses ESLint to accomplish this, obviously only if you are already using ESLint before committing.

**Comment by kunagpal** [comment]
@jacobcarpenter You could also take a look at https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-exclusive-tests.md, as this is a code style related enforcement. It doesn't make a whole lot of sense for a test runner to enforce standards, which would also tend to the opinionated side.

**Comment by Bamieh** [comment]
we have `--forbid-only` flag now
