### ISSUE TITLE
Mocha silently discards Promise rejection in browser when `allowUncaught` is enabled.

### ISSUE THREAD

**Issue by dtinth** [mochajs/mocha#2281]
## Context

I’m using `allowUncaught` to allow exceptions to propagate to the browser, so that I can inspect it via Chrome DevTools (which converts the source maps).

``` js
mocha.allowUncaught()
```

But there is a problem in `allowUncaught`: **It makes all async tests pass.**
## Test case

``` js
describe('a rejected promise', () => {
  it('should fail the spec', () => {
    return Promise.reject(new Error('meow'))
  })
})
```
## Actual result

The spec passed despite promise rejection. This problem doesn’t occur when `allowUncaught` is not set. In both cases, there are no errors reported to console.

<img width="664" alt="screen shot 2016-05-27 at 9 58 49" src="https://cloud.githubusercontent.com/assets/193136/15596433/aafa2628-23f1-11e6-8c19-45d432b60f4b.png">
## Expected result

The spec should fail.

<img width="664" alt="screen shot 2016-05-27 at 9 59 28" src="https://cloud.githubusercontent.com/assets/193136/15596459/da5f21d4-23f1-11e6-949e-f0901c498c5b.png">

An error should be reported in the console.

<img width="664" alt="screen shot 2016-05-27 at 10 11 57" src="https://cloud.githubusercontent.com/assets/193136/15596674/816881d6-23f3-11e6-9fb1-77931da45c7e.png">
## Workaround

Don’t use `allowUncaught()`, but add a `fail` handler so that it can be logged.

``` js
var runner = mocha.run()
runner.on('fail', function (test) {
  setTimeout(() => { throw test.err })
})
```

**Comment by ScottFreeCode** [comment]
We should check whether this is related to #1801.

**Comment by boneskull** [comment]
Currently, `allowUncaught`, when enabled, completely ignores a `Promise` return value.

**Comment by juergba** [comment]
- returning a rejected Promise is **not** an uncaught exception, it's a perfectly written async test case. So it's ok that no exception is reported in the console.
- `allowUncaught`: it makes all async tests pass ==> fixed meanwhile
