### ISSUE TITLE
Incorrect character in browser report

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mocha#2283]
The HTML reporter is supposed to use ‣ for its grep buttons (&amp;#x2023; is the hex code I believe), but I'm getting this symbol instead: â€

**Comment by spiritphyz** [comment]
I found a fix for the problem of the " ‣" symbols showing up as garbled "â€" characters on the righthand side of the page.

In the HTML file, you need to add `<meta charset="UTF-8">` inside the <head> tags.

**Comment by dasilvacontin** [comment]
This bug has been fixed in [v3.3.0](https://github.com/mochajs/mocha/releases/tag/v3.3.0)! 🎉
