### ISSUE TITLE
Expecting `afterEach` to fail

### ISSUE THREAD

**Issue by peoronoob** [mochajs/mocha#2284]
I wrote an `afterEach` function to check that each test correctly finalizes some data.

I'd like to write a test for it, to be sure that `afterEach` works, since it already broke a couple of times.
Is that possible?

**Comment by dasilvacontin** [comment]
@peoronoob I guess you can essentially make `afterEach` call a function, and then you could have unit tests for that function (?).

**Comment by boneskull** [comment]
Yeah, but how do you know the unit test that asserts the function is correct is correct? 😝
