### ISSUE TITLE
window.location.pathname in links in browser HTML reporter

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mocha#2285]
A link starting with `window.location.pathname` (which is used in the grep links in the HTML reporter) is treated oddly in some browsers, at least when the page is run without a server (straight from the filesystem). For example, Internet Explorer on Windows gets "/C:/path/to/page.html" for `window.location.pathname`, which causes it to try to go to "C:/C:/path/to/page.html?grep=..." when the grep links are clicked. (I am not sure if this issue affects any other browsers. I'm also not sure whether this is strictly a problem for browsing the page straight off the filesystem, although I wouldn't be surprised if it is.) We should find out if simply removing pathname and using just "?grep=..." for the links works in all browsers, or if there's any other fix.

Looks like test/browser/ui.html tests this, but I don't know whether we can get all the same behavior in automated testing for it or not (or even whether the approach used by test/browser/ui.html works for automated testing).

**Comment by JoshuaKGoldberg** [comment]
Given that IE is out of support, closing this as aged away.
