### ISSUE TITLE
Watch from programmatic API

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mocha#2293]
Is there an equivalent of the `--watch` flag for the programmatic (from Node) API? If not, we should look into adding one. If there is, we should make sure it's as easy as `--watch` to find in the documentation.

This was prompted by Gitter discussion with @DrMabuse23

**Comment by DrMabuse23** [comment]
thx

**Comment by dasilvacontin** [comment]
Hmm, afaik we wanted to drop `watch`. But if it's moved into a plugin, then it's something to consider.

**Comment by boneskull** [comment]
Indeed.

Moving it into a plugin--and ensuring we're leveraging something like `chokidar`--is the best path for the future

**Comment by DrMabuse23** [comment]
this is my test run script https://github.com/relution-io/relution-cli/blob/master/testrunner.js let me know when i can add the restart method or the watch options 👍
