### ISSUE TITLE
Base reporter, add unified diff separator

### ISSUE THREAD

**Issue by olsonpm** [mochajs/mocha#2295]
Right now the unified diff output has no separators.  Resulting in output similar to this:

![no-diff-seperator](https://cloud.githubusercontent.com/assets/5957709/15793934/c98aae62-29ac-11e6-8d8a-d0a5954c5b87.png)

Having not used mocha in some time, I had completely forgotten it splits before/after 4 lines from the affected text and spent a while trying to figure out how "PD" could possibly be having values of "15/30" or "50/100".

I don't know what kind of separator to add, but a blank line or two should suffice for majority of cases.  I'd have to check to see if other libraries have tackled this problem how they went about it.

The code to modify would be this:
https://github.com/mochajs/mocha/blob/7493bca76662318183e55294e906a4107433e20e/lib/reporters/base.js#L161-L207

**Comment by ScottFreeCode** [comment]
Git has a format something like this: `@@ -<line number of start of this segment in previous file version>,<number of lines removed> +<line number of start of this segment in next file version>,<number of lines added> @@`
It's blue, where the + are green and the - are red. And I'm not sure I'm interpreting those numbers exactly right -- maybe the numbers after the commas include the unchanged lines shown?

**Comment by olsonpm** [comment]
hmm - the problem with generating line numbers is that these diffs are for formatted objects, thus line numbers don't seem appropriate.  

However I did notice `git grep` separates sections with `\n--\n` if multiple matches are found.  That seems intuitive enough.

**Comment by boneskull** [comment]
@olsonpm Can you show what *should* be output?

**Comment by olsonpm** [comment]
As I said I'm open for discussion on what makes the most sense, but my vote leans toward the output of `git grep -C<number>`, where sections are delimited by a double dash.  E.g.

![asdf](https://cloud.githubusercontent.com/assets/5957709/16383688/caa21d24-3c4b-11e6-85f8-a4d285ec165b.png)

**Comment by olsonpm** [comment]
@boneskull - trying to prevent the issue from being closed.  I provided the requested feedback, so at least remove that label please.

**Comment by ScottFreeCode** [comment]
I'd be fine with just `--` as a separator if no one has better suggestions or other concerns. Do we want to put this behind a flag for compatibility? (Another advantage to a flag would be we could provide the ability to override `--` with some other non-dynamic string...)

**Comment by boneskull** [comment]
[unexpected](https://npm.im/unexpected) may have a good solution we can pilfer; let's take a look at what their messaging looks like.

Otherwise, `--` is just as reasonable as any other string.

@ScottFreeCode I don't think this needs an option to change the separator, and a flag also feels like overkill.  

If we're erring on the site of caution, this is `semver-major`, because it could confuse anything that's programmatically consuming the output.  No, nothing *should* consume it, but something probably does.

**Comment by olsonpm** [comment]
Sweet - I'll get a pr in next week.  Thanks for the responses.

**Comment by ScottFreeCode** [comment]
This went out in 4; thanks again!
