### ISSUE TITLE
Docs about timeout for hooks

### ISSUE THREAD

**Issue by JustBlackBird** [mochajs/mocha#2296]
It seems that one can use `this.timeout` to set timeout for hooks. Here is an example:

```js
describe('case', function() {
    beforeEach(function(done) {
        this.timeout(3000);
        setTimeout(done, 2500);
    });

    it('should do something', function(done) {
        // ...
       done();
    });
});
```

The problem is there is nothing in [docs](https://mochajs.org/#timeouts) about such feature. I believe it could be useful to document it.

I could open a PR for docs but I'm not sure where the docs are situated.

**Comment by ScottFreeCode** [comment]
I think they're in the next repository over, [mochajs/mochajs.github.io](../../mochajs.github.io).

**Comment by JustBlackBird** [comment]
Thank you, I'll open a PR there soon.
