### ISSUE TITLE
XUnit Reporter Throws Fatal Error "test.isPending is not a function"

### ISSUE THREAD

**Issue by matthewriley** [mochajs/mocha#2297]
The XUnit reporter (/lib/reporters/xunit.js) fails on [line 134](https://github.com/mochajs/mocha/blob/master/lib/reporters/xunit.js#L134) when attempting to call `test.isPending()`. The error reported is: `Fatal error: test.isPending is not a function`.

When I inspect the test object passed into `XUnit.prototype.test`, I do not see isPending defined on the object.

If I modify the else if condition to `typeof test.isPending === 'function' && test.isPending()`, all tests complete successfully and the XUnit report is written correctly.

What I cannot determine (at least not without a little help) is if this is a valid error or if this is a downstream effect caused by something my code is doing incorrectly.

I’m calling mocha from [grunt-mocha](https://github.com/kmiyashiro/grunt-mocha) for client side tests. If this is an upstream error on their side I’m happy to help track it down.

**Comment by ScottFreeCode** [comment]
Can you narrow it down to a minimal test case that reproduces the issue? The XUnit reporter is working ok for me. As far as I'm aware, `isPending` is definitely supposed to be a function and not ignored by the reporter, but there could be some unusual failures that would try to report something that's not a normal test. (In the meantime I will see if I can dig up the place I previously saw such failures.)

**Comment by matthewriley** [comment]
I created a small sample app that recreates the issue. I'm running Node 4.4.1 and npm 3.9.5, if that helps any.

To run it, cd to test/client/config/, do a `npm install` then run `grunt` for the Spec reporter, which completes successfully. Then to see it fail run `grunt testJenkins --force` and you’ll see the fatal error `test.isPending is not a function`.

Mocha XUnit Reporter Sample
https://github.com/matthewriley/mocha-xunit-reporter-sample 

Please let me know if I provide any further detail to help diagnose this error.

**Comment by ScottFreeCode** [comment]
Could this be made into two separate tests, a Grunt test without Angular and an Angular test without Grunt?

**Comment by ScottFreeCode** [comment]
I've narrowed it down. Used this test file: `describe("suite",function(){it("test",function(){})})` Took the other tests and the references to Angular out of testrunner.html. Still got the error. Changed to testing the JS file directly with "grunt-mocha-test" instead of "grunt-mocha", did not get the error. So it's something to do with "grunt-mocha" or one of its components...

**Comment by ScottFreeCode** [comment]
Correpsonding ticket on grunt-mocha: kmiyashiro/grunt-mocha#163

**Comment by matthewriley** [comment]
Closing in favor of grunt-mocha issue listed above.

**Comment by ScottFreeCode** [comment]
Cool; glad I could help. Thanks for the test code!

**Comment by cades** [comment]
I encounter the same problem when writing custom interface.

thanks @fry2k points out the change is from [this commit](https://github.com/mochajs/mocha/commit/d4f7905dbb9d4cc65cca02373b99e5549fa7ce2a).

I found the root suit (for example, [this](https://github.com/mochajs/mocha/blob/master/lib/interfaces/bdd.js#L26)) is not `instanceof` "mocha/lib/suite".

so `isPending` is not on its prototype chain. it this the root cause?

**Comment by ScottFreeCode** [comment]
> I encounter the same problem when writing custom interface.

Can you provide an example of custom interface code that will cause the issue? It would be great to narrow down what sort of code will run into problems.

> ...the change is from this commit.

However, it doesn't break Mocha per se (that is, Mocha is setting up `isPending` on everything it should): [I can run the same test code with Mocha and with various integrations, and only certain integrations are broken](https://github.com/mochajs/mocha/issues/2297#issuecomment-225168596).

> I found the root suit (for example, this) is not  instanceof  "mocha/lib/suite".

For anyone reading this thread and not the other one, I reply to this here: https://github.com/kmiyashiro/grunt-mocha/issues/163#issuecomment-227011271

**Comment by cades** [comment]
Here is the interface I'm working on: https://github.com/cades/respec-given

And the file defines interface:
https://github.com/cades/respec-given/blob/master/mocha/index.js

version 0.0.6 already have the workaround applied, you can use 0.0.5 to re-produce that error.

**Comment by ScottFreeCode** [comment]
Thanks! I will take a look at it.

**Comment by ScottFreeCode** [comment]
My tests are passing using respec-given@0.0.5 without issue, both with the default reporter and with the XUnit reporter.

**Comment by cades** [comment]
I found the root suite is created by `mocha` command, whose version may be different from locally installed one. If `mocha` is invoked from npm scripts or `node_modules/.bin/mocha`, locally installed version is invoked, which is consistent with what an interface `require`s in.

However if `mocha` is invoked from command line directly, globally installed version is invoked, which may be not consistent with what an interface `require`s in.

**Comment by cades** [comment]
Just wrote [patch code](https://github.com/cades/respec-given/blob/master/mocha/patch-for-version-inconsistency.js), and [example usage](https://github.com/cades/respec-given/blob/master/mocha/index.js#L10)

**Comment by ScottFreeCode** [comment]
It seems like the global install plus local plugin thing would affect any commandline Node program that takes plugins. We should find out if there's a standard solution for it rather than trying to hack together some custom workaround. (Note that the standard solution might turn out to be just "don't use local plugins with global commands, make both local or make both global." But we should find out.)

I will look into whether the original Grunt-Mocha issue is being caused by some kind of double-versioning or discrepant copies of Mocha thing among its *local* installs, however, since I confirmed the issue for Grunt-Mocha using all local installs.

**Comment by ScottFreeCode** [comment]
The Grunt-Mocha issue is not caused by multiple differing versions of Mocha; when I install the test provided by matthewriley and reproduce the issue with it, there is only one copy of Mocha installed.

**Comment by cades** [comment]
Does the installed mocha version is same as the globally installed one (you can check it with `mocha --version`)?

**Comment by cades** [comment]
as for the standard solution, I think [gulp](https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md) and [gulp-cli](https://github.com/gulpjs/gulp-cli) is a good example. They use the approach of "separate globally installed command and locally installed module". `gulp-cli`'s responsibility will find locally installed `gulp` module and use it to consume `gulpfile`, so there's no concern of version conflict.

**Comment by ScottFreeCode** [comment]
> Does the installed mocha version is same as the globally installed one (you can check it with  mocha --version )?

What globally installed version?

If you're referring to this:
> The Grunt-Mocha issue is not caused by multiple differing versions of Mocha; when I install the test provided by matthewriley and reproduce the issue with it, there is only one copy of Mocha installed.

...then I can clarify that I *did not use use a globally installed Mocha*, instead using the locally installed one that the project had as a dependency. (In fact, I did not even have Mocha globally installed, hence my saying that there was only one copy installed.)

**Comment by cades** [comment]
I got it. I suppose everyone has one `mocha` globally installed, now I know it's wrong. Sorry for my misunderstanding.
