### ISSUE TITLE
allowUncaught doesn't work in hooks

### ISSUE THREAD

**Issue by dima117** [mochajs/mocha#2302]
For example if exception was thrown in `beforeEach` hook then it will be caught even if `mocha.allowUncaught()` was executed. This is because during the hook execution the runner not sets `allowUncaught` parameter for it.

**Comment by ScottFreeCode** [comment]
We should check whether this is related to #1985.

**Comment by dima117** [comment]
Hi,

what is tis issue current state?

**Comment by boneskull** [comment]
I think this is still broken.

**Comment by givanse** [comment]
New PR https://github.com/mochajs/mocha/pull/3669
