### ISSUE TITLE
Can not find module 'C'

### ISSUE THREAD

**Issue by silentcloud** [mochajs/mocha#2310]
Run tests with custom compilers:

`
mocha --compilers js:Absolute Path
`

Absolute Path: `C:\Users\xxxx\test-demo\lib\compiler.js` is my custom file;

windows system, what's the right way?

**Comment by afc163** [comment]
ref https://github.com/ant-design/antd-init/issues/72

**Comment by afc163** [comment]
https://github.com/mochajs/mocha/issues/2242

**Comment by boneskull** [comment]
closed via ea71b4428f627683422c39907793a47e8105485e
