### ISSUE TITLE
`this.slow()` doesn't work in describe callbacks like `this.timeout`

### ISSUE THREAD

**Issue by AgentME** [mochajs/mocha#2311]
```js
describe('a', function() {
  this.timeout(5000);
  this.slow();

  it('1', function(cb) {
    setTimeout(cb, 3000);
  });

  it('2', function(cb) {
    this.slow(); // just for contrast with test 1
    setTimeout(cb, 3000);
  });
});
```

If I understand the docs correctly, I expect neither of the tests to timeout or have slow warnings because they're both covered by `this.timeout` and `this.slow` calls in the describe section. Neither of the tests timeout, but the first test (not covered by its own redundant `this.slow`) has a slow warning still:

```
  a
    ✓ 1 (3008ms)
    ✓ 2


  2 passing (6s)
```

mocha version 2.5.3

**Comment by boneskull** [comment]
`this.slow()` doesn't do anything except return the current setting.  You'll need to give it a parameter.

**Comment by AgentME** [comment]
I'm confused because in test 2, calling `this.slow()` causes it to not show the slow warning without a parameter given. Removing it causes this output:

```
  a
    ✓ 1 (3006ms)
    ✓ 2 (3001ms)


  2 passing (6s)
```

**Comment by boneskull** [comment]
OK, thanks.  that's a bug.  this is mostly for my benefit, but the explanation:

```js
Runnable.prototype.slow = function(ms) {
  if (!arguments.length) {
    return this._slow;
  }
  if (typeof ms === 'string') {
    ms = milliseconds(ms);
  }
  debug('timeout %d', ms);
  this._slow = ms;
  return this;
};
```

When you call `this.slow()` from a test, it calls this:

```js
Context.prototype.slow = function(ms) {
  this.runnable().slow(ms);
  return this;
}
```

If the latter function is called without a parameter, `Runnable.prototype.slow()` will have `arguments` equal to `[undefined]`.  The fix is to test `ms` explicitly.
