### ISSUE TITLE
🐛 Bug: Markdown reporter doesn't work with source maps

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mocha#2313]
When using Mocha with a compiler such a Babel or CoffeeScript, is it possible to view the original function body instead of the transpiled function body in Mocha reports such as the Markdown reporter?

cc: @thomas88

**Comment by ScottFreeCode** [comment]
@thomas88, can you try this and see if it works?
`npm i source-map-support`
`mocha --require source-map-support/register <the rest of your mocha command here>`

**Comment by thomas88** [comment]
Thanks for opening the issue @ScottFreeCode. I've uploaded a minimal example showing the actual vs. desired behaviour at https://github.com/thomas88/mocha-reporter-original-source. 

Using `source-map-support` alone does not help with the markdown reporter. Or maybe I don't use it correctly.

However my understanding right now is, that it's up to the respective reporter to implement Source Map support. I found these reporters for example:
- https://github.com/marcominetti/mocha-lcov-sourcemap-reporter
- https://github.com/btd/mocha-better-spec-reporter

If there is a desire to get support for Source Map support in Mocha core?

**Comment by boneskull** [comment]
I'm not sure what is going on with the Markdown reporter, but it's not good.

@thomas88 here's [an example of using Mocha with source-map-support and Babel](https://git.io/voH5U).

**Comment by snaptopixel** [comment]
@boneskull @vercasson I'm having the same issue here when using Typescript. Started a new project and thought it would be glorious to just generate the README via the md reporter, which it is, except for the fact that the code snippets are of the compiled code not the source-mapped TS 😭

**Comment by btilford** [comment]
Any update on typescript or typescript sourcemaps for either markdown or docs reporters?

**Comment by juergba** [comment]
@btilford Newer versions of Node.js introduce the `--enable-source-maps` flag. Could this flag help in anyway?

**Comment by btilford** [comment]
@juergba That actually gets pretty close. It looks like `--require source-map-support` isn't needed anymore?

**Comment by iongion** [comment]
The browser based version doesn't show original source, even with source-map-support

**Comment by btilford** [comment]
I ended up writing a tool that executes markdown blocks as mocha tests. Also supports typescript. https://github.com/btilford/md-check/tree/master/plugins/exec-mocha

**Comment by JoshuaKGoldberg** [comment]
The discussion here got kind of lost around the `--enable-sourcemaps` / `--require source-map-support` point. It's hard to tell what is or isn't supported anymore. Closing as aged away / stale.

If anybody has a reproduction on the latest major version of Mocha, please file a new issue with one of our new issue templates. The template will prompt for the info we'd need. Cheers all!
