### ISSUE TITLE
Uncaught TypeError: Cannot read property 'currentRetry' of undefined

### ISSUE THREAD

**Issue by ksuszka** [mochajs/mocha#2315]
Tested on Mocha 2.5.3.

When uncaught error is thrown during "before" phase additional "Uncaught TypeError: Cannot read property 'currentRetry' of undefined" error is thrown from mocha.

Simple test case:
```js
'use strict';

describe('test', function () {
    before(function () {
        require('http').createServer().listen(1);
    });

    it('something', function () {
    });
});
```

output:
```
  test
    1) "before all" hook

  2) Uncaught error outside test suite

  0 passing (27ms)
  2 failing

  1) test "before all" hook:
     Uncaught Error: listen EACCES 0.0.0.0:1
      at Object.exports._errnoException (util.js:953:11)
      at exports._exceptionWithHostPort (util.js:976:20)
      at Server._listen2 (net.js:1240:19)
      at listen (net.js:1289:10)
      at Server.listen (net.js:1385:5)
      at Context.<anonymous> (test/test.js:5:40)

  2) test Uncaught error outside test suite:
     Uncaught TypeError: Cannot read property 'currentRetry' of undefined
```

**Comment by boneskull** [comment]
haven't confirmed this, but it seems feasible.  what reporter are you using?

**Comment by ksuszka** [comment]
I've tested it with the default reporter, but I've just checked spec, nyan, json reporters and same issue occurs.

 It seems that it happens only if an error is thrown from asynchronous code. So even simpler test case is:
```
'use strict';

describe('test', function () {
    before(function () {
        setImmediate(function () {
            throw Error('error');
        });
    });

    it('something', function () {
    });
});
```

Note: I've just checked that the previous test case worked on linux under root account as it seems you can setup http server on port 1 as a root, so if you test under linux use sample with setImmediate or try to open same port twice.

**Comment by ScottFreeCode** [comment]
Remind me to double-check that this doesn't overlap with #2220.

**Comment by boneskull** [comment]
@ksuszka Thanks for the help here.

**Comment by boneskull** [comment]
Having a hell of a time getting this to reproduce in a test environment, which sucks.

**Comment by ksuszka** [comment]
Do you use docker by any chance?

I've created a docker image with this issue. If you have docker then you can recreate the issue by running:
```
docker run ksuszka/mocha_issue_2315_demo
```

This is output on my machine:
```
Unable to find image 'ksuszka/mocha_issue_2315_demo:latest' locally
latest: Pulling from ksuszka/mocha_issue_2315_demo
51f5c6a04d83: Already exists
a3ed95caeb02: Already exists
7004cfc6e122: Already exists
d2e8a01d4f62: Already exists
d86212eebced: Already exists
4d1cea628cb5: Pull complete
10ba257b6e63: Pull complete
f652cf24f303: Pull complete
Digest: sha256:a2602f05b2e37cb11be9cb1e506b28f7bf9e43aaf4be92642fde89886e4c35e4
Status: Downloaded newer image for ksuszka/mocha_issue_2315_demo:latest


  test
    1) "before all" hook

  2) Uncaught error outside test suite

  0 passing (43ms)
  2 failing

  1) test "before all" hook:
     Uncaught Error: error
      at Error (native)
      at Immediate._onImmediate (test.js:6:19)

  2) test Uncaught error outside test suite:
     Uncaught TypeError: Cannot read property 'currentRetry' of undefined
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at Immediate._tickCallback [as _onImmediate] (internal/process/next_tick.js:98:9)
```

The source code for this docker image is here: https://github.com/ksuszka/mocha_issue_2315_demo.

**Comment by boneskull** [comment]
@ksuszka Thanks.  I can reproduce the issue fine, I just can't reproduce it in a way that's testable; thus, I can't assert it's fixed if I can't assert it's broken.

**Comment by boneskull** [comment]
I'm not sure spinning my wheels on this is the best use of my time.  I get the impression that this isn't a showstopper.  I'd happily accept a PR to fix it, if it can be tested.

**Comment by gurdiga** [comment]
Hey guys! 🙂

Just a quick thought: If this is in the context of async setup code, shouldn’t we then use the `done` callback to tell Mocha about that? 🤔

I mean something like this:
```js
'use strict';

describe('test', function () {
    before(function (done) {       // <--------------- added the `done` argument
        setImmediate(function () {
            throw Error('error');
            done();
        });
    });

    it('something', function () {
    });
});
```
In this case it the failure message seems to be more clear:
```
    ~/tmp/mocha ɀ  mocha 2315.js

  test
    1) "before all" hook

  0 passing (20ms)
  1 failing

  1) test "before all" hook:
     Uncaught Error: error
      at Error (native)
      at Immediate._onImmediate (2315.js:6:19)


    ~/tmp/mocha ɀ  mocha --version
2.5.3
    ~/tmp/mocha ɀ  node --version
v6.2.2
    ~/tmp/mocha ɀ  
```
Which makes me think that this may be categorized as a slight misuse instead of a bug. What do you guys think? 🤓

**Comment by 1999** [comment]
I had a bit of time to investigate into this issue. The interesting thing here is that this code works as expected (0 passing, 1 failing):
```javascript
describe('issue-2315: cannot read property currentRetry of undefined', function () {
  before(function () {
    throw new Error;
  });

  it('something', function () {});
});
```

and this does not (0 passing, 2 failing, uncaught error outside test):
``javascript
describe('issue-2315: cannot read property currentRetry of undefined', function () {
  before(function () {
    require('http').createServer().listen(1);
  });

  it('something', function () {});
});
```

So it feels like the problem is somewhere inside `http` module. So I dived into [net](https://github.com/nodejs/node/blob/master/lib/net.js) module of node.js which is used for `listen` function of `http.Server`. And if smth goes wrong (for example like in @ksuzska example when current user has no rights to listen to port 1), error is emitted but [on the next tick](https://github.com/nodejs/node/blob/master/lib/net.js#L1256) but `before()` was sync and this is the reason of "uncaught error outside test" error. So it looks like the problem here is just about the wrong interpretation of the error. A simple dirty fix for that is inside [my PR](https://github.com/mochajs/mocha/pull/2439).

**Comment by 1999** [comment]
cc @boneskull

**Comment by mikermcneil** [comment]
(for the record, seeing this with mocha@2.4.5 as well)

**Comment by ljharb** [comment]
We've been seeing this on mocha for awhile now on our large codebase, but couldn't narrow it down to specific tests. Any progress here?

**Comment by boneskull** [comment]
@ljharb @1999 A PR was sent (#2439) that needs some review.

**Comment by ljharb** [comment]
@boneskull thanks!!! when do you think this might be released?

**Comment by boneskull** [comment]
@ljharb If I had to guess, somewhere between 0 and 7 days from now.

**Comment by muneermuhammed** [comment]
I am facing issue when I run my tests with mocha-allure-reporter ,the tests are running successfully with mocha ,but mocha --reporter mocha-allure-reporter returns the following error

> notifications-api@1.0.0 test /app
> mocha --reporter mocha-allure-reporter

2016-11-15T06:13:26.762Z - info: Notification API up and running on port 4000
2016-11-15T06:13:26.773Z - error: Tue, 15 Nov 2016 06:13:26 GMT uncaughtException
2016-11-15T06:13:26.775Z - error: TypeError: test.currentRetry is not a function
at Runner.<anonymous> (/app/node_modules/mocha-allure-reporter/index.js:29:19)
at emitOne (events.js:77:13)
at Runner.emit (events.js:169:7)
at next (/app/node_modules/mocha/lib/runner.js:517:10)
at Runner.runTests (/app/node_modules/mocha/lib/runner.js:556:3)
at /app/node_modules/mocha/lib/runner.js:637:10
at next (/app/node_modules/mocha/lib/runner.js:283:14)
at Immediate._onImmediate (/app/node_modules/mocha/lib/runner.js:319:5)
at processImmediate [as _immediateCallback] (timers.js:383:17)
npm ERR! Test failed.  See above for more details.
Can anyone help to fix this issue?

**Comment by afrancht** [comment]
I'm still running into this issue although it has said to be fixed. I'm running mocha 6.2.2 though. Any help?

**Comment by juergba** [comment]
Where do you set `user`? Not in the `before` hook, I guess you leave it `undefined`?
