### ISSUE TITLE
update jade dependency to pug

### ISSUE THREAD

**Issue by arturh85** [mochajs/mocha#2316]
On installation of your fine module in its latest version 2.5.3 I get the following warning:

> npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

Please change jade dependency to pug as suggested.

**Comment by marvinhagemeister** [comment]
Duplicate of #2200

**Comment by boneskull** [comment]
@arturh85 please search before adding an issue, thanks
