### ISSUE TITLE
QUnit interface missing from help overview

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mocha#2317]
https://github.com/mochajs/mocha/blob/dce0aec52de79bae9c4936d4bf539f3c9b25ca7a/bin/_mocha#L77 is missing the QUnit interface in its list: "(bdd|tdd|exports)"

Incidentally, would it be feasible to just copy the names from lib/interfaces/index.js (e.g. with a for in loop or the `keys` function)? (Both there and at https://github.com/mochajs/mocha/blob/dce0aec52de79bae9c4936d4bf539f3c9b25ca7a/bin/_mocha#L157) That way they couldn't get out of sync like this in the future.

**Comment by boneskull** [comment]
Yes.

**Comment by boneskull** [comment]
This is "documentation" in the rough sense of the word
