### ISSUE TITLE
Running mocha programmatically doesn't show outside-of-test errors

### ISSUE THREAD

**Issue by super-cache-money** [mochajs/mocha#2319]
Currently, for example, I was missing a module that I was attempting to `require` within the only test with which I did `mocha.add(test)`.

When I do `mocha.run()` by running my test runner, as expected - none of the tests run. However, there is no error printed out, the node process just silently dies.

However, when I call mocha from the command line on the same test file, a nice error is printed telling me I forgot to install the module.

Why is this happening :(

**Comment by super-cache-money** [comment]
Nevermind. Was being retarded 💩

**Comment by ScottFreeCode** [comment]
If you've got a solution (or even an explanation of a mistake), it'd be great to have it here in case anyone else is running into the same issue. 8^)

**Comment by super-cache-money** [comment]
I forgot to catch a promise :D
