### ISSUE TITLE
"--require" does not honour "--compilers" file extension support

### ISSUE THREAD

**Issue by graingert** [mochajs/mocha#2321]
babel-register registers file extensions like ".es" and ".jsx". You cannot:

```
--compilers js:babel-register
--require ./test/installDirtyChai
```

 when installDirtyChai has a different extension: `./test/installDirtyChai.es`

In other oddness if you do:

```
# test/mocha.opts
--compilers js:babel-register
--require ./test/installDirtyChai
```

``` js
// test/installDirtyChai.js
require('./installDirtyChaiActual');
```

``` js
// test/installDirtyChaiActual.es
import chai from 'chai';
import dirtyChai from 'dirty-chai';

chai.use(dirtyChai);
```

everything works, so it's like the require function is not being overridden correctly

**Comment by graingert** [comment]
babel-register registers file extensions like ".es" and ".jsx". You cannot:

```
--compilers js:babel-register
--reporter mocha-multi
--reporter-options spec=-,xunit=./test-reports/file.xml
--require ./test/installDirtyChai
```
 when installDirtyChai has a different extension: `./test/installDirtyChai.es`

**Comment by ScottFreeCode** [comment]
As far as I'm aware, `--require` just delegates to Node's `require` function, so this is unsurprising.

It might be nice to be able to load some compiled code before testing too, but I'm not sure off the top of my head what a good way to do it is.

**Comment by graingert** [comment]
@ScottFreeCode it does actually compile the code if you use ".js" files. But not in any of the other supported extensions.

**Comment by graingert** [comment]
It looks like https://github.com/mochajs/mocha/blob/master/bin/_mocha#L172 is hard-coded to only allow ".js" files rather than looking at "require.extensions" after the require hooks have loaded.

**Comment by boneskull** [comment]
@graingert That code actually looks like it's trying to append `.js` to the required module name if it doesn't exist.

**Comment by boneskull** [comment]
Well, `--compilers js:babel-register` means "compile `.js` files with babel-register", afaik.

So what if you did `--compilers es:babel-register`?

`--compilers` was intended for CoffeeScript really.  You can probably achieve what you want with `--require babel-register --require ./test/installDirtyChai`

**Comment by boneskull** [comment]
Given `require.extensions` is deprecated, I'd probably avoid adding it.  If avoiding `--compilers` works for you, then I don't see a pressing reason to change this code.  It would be a good idea to update documentation.

**Comment by graingert** [comment]
@boneskull no, but changing the hardcoded ".js" to ".es" does work. This value should be direcly updated from "--compilers"
