### ISSUE TITLE
--watch and --recursive command line parameters not executing tests correctly on Windows

### ISSUE THREAD

**Issue by WaffleSouffle** [mochajs/mocha#2327]
## Setup

Tested with node 6.2.2 (https://nodejs.org/dist/v6.2.2/node-v6.2.2-x64.msi)
and current master build (v7.0.0-pre) built with MinGW 64 compiler
on Windows 8.1
`npm install mocha -g` installs mocha 2.5.3 with warnings

> npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

Going through walkthrough https://www.codementor.io/nodejs/tutorial/unit-testing-nodejs-tdd-mocha-sinon
Same results executing in a DOS prompt, or a MinGW64 console.
## Steps

Running `mocha tests --recursive --watch --colors` where tests is a root level directory containing tests.
Correctly runs tests initially.

>   CartSummary
>     √ getSubtotal() should return 0 if no items are passed in
>     √ getSubtotal() should return the sum of the price \* quantity of the items
> 
>   2 passing (6ms)

Then edit a test file to introduce non-breaking change.
Output appends

> 0 passing (0ms)

Any subsequent edits go ignored.
## Expected Behaviour

Changes to test files to trigger execution.
Subsequent edits to be noticed.

**Comment by dasilvacontin** [comment]
@WaffleSouffle what if you run mocha with less options, eg only `--watch` and try modifying `tests/*.js`?

**Comment by dasilvacontin** [comment]
This appears to be a Windows only bug.

**Comment by boneskull** [comment]
As with #2330, I'd suggest using a purpose-built tool for watching.  Mocha's built-in "watch" functionality is limited.  Such functionality really deserves something which can support multiple platforms and edge cases.

**Comment by boneskull** [comment]
@dasilvacontin Did you confirm this?

**Comment by dasilvacontin** [comment]
@boneskull No, I don't have a Windows setup.

**Comment by ScottFreeCode** [comment]
Just tried to reproduce this on Windows and was unable to do so. I will double-check the tutorial and see if there might be something I missed.

**Comment by ScottFreeCode** [comment]
...Yeah, I'm not seeing anything different that should affect this. My test doesn't have Chai and stuff, but that shouldn't matter... right?... I've got this on Windows 8.1, same directory structure, same command, Mocha installed globally...

**Comment by jfnields** [comment]
I am having the same issue. I do not have this issue on Mac setup.

**Comment by dobryanskyy** [comment]
I also have such issue on windows.
npm version 3.10.3
node version 6.3.1
mocha version 3.0.2

**Comment by boneskull** [comment]
For those having issues, please try passing a glob instead of the `--recursive` flag, and let me know if you have success:

```shell
# quotes are necessary
mocha "tests/**/*.js" --watch
```

**Comment by boneskull** [comment]
Any PR here should not grossly add to the level of complexity

**Comment by dobryanskyy** [comment]
@boneskull I've tried the workarounds you suggested both with slashes and backslashes with and without recursive flag and double/single quotes. None of that did help

**Comment by gurdiga** [comment]
@WaffleSouffle @jnields @dobryanskyy Could you please prepare a minimal setup that demonstrates this issue? 🤔

I think this would greatly help to pinpoint the root cause. 🤓

**Comment by boneskull** [comment]
@dobryanskyy adding to what @gurdiga wrote, please keep it minimal unless you can provide the entire thing.  also using "Babel" or "bundling" is a relevant detail; please include those

**Comment by dobryanskyy** [comment]
@boneskull yes, I'm using babel for jsx and es6 transpilation.

**Comment by UsulPro** [comment]
I also have problem!
windows 8.1 pro
only one index.js file in src/test
>   Button                                     
>    √ should show the given text             
>    √ should handle the click event          
>                                             
>                                             
>  2 passing (63ms)                           
>                                             
>                                             
>                                             
>  0 passing (0ms)                            
>                                             

But may be this small tip could be usefull: if run the same from `Git Bash` (for windows) everything works properly.

**Comment by higimo** [comment]
Windows 7, mocha 3.4.2, cmder
mocha ./test/ --compilers js:babel-core/register --compilers jsx:babel-register -w
```
0 passing (0ms)
```

**Comment by boneskull** [comment]
not stale

**Comment by DonGiulio** [comment]
having the same problem, on osx 

this is my command line for running mocha: 
 
       mocha --require 'test/javascript/helpers/includes.jsx' 'test/javascript/helpers/browser' 'app/javascript/bundles/**/*.spec.jsx' --watch

if I touch the first file: `test/javascript/helpers/browser` tests get run, 

if I touch any of the `app/javascript/bundles/**/*.spec.jsx` they don't. 

I've also tried with `--recursive` with no luck.

**Comment by higimo** [comment]
@UsulPro you use a symlink?

I have this problem when using symlink
> 2 passing (63ms)
> 
> 0 passing (0ms)

**Comment by ScottFreeCode** [comment]
Hi @DonGiulio, try adding `--watch-extensions jsx` and see if that fixes it.

@higimo Could you elaborate on your code's structure and how to create a symlink that will encounter this? I was under the impression that symlinks are treated the same both times, but I'd be interested to take a look at it. (And just to double-check I'm on the same page: Is this on Windows? With cmd, or another shell?)

**Comment by DonGiulio** [comment]
Thanks @ScottFreeCode the `--watch-extensions jsx` did the trick, here's the complete command line. 


`mocha --watch-extensions jsx --watch --require 'test/javascript/helpers/includes.jsx' 'test/javascript/helpers/browser' 'app/javascript/bundles/**/*.spec.jsx'`

**Comment by boneskull** [comment]
I don't think this is actionable.

**Comment by javahaxxor** [comment]
I have this issue on both OSX and Linux  
![screen shot 2017-12-12 at 09 34 48](https://user-images.githubusercontent.com/3932029/33874652-bf8ca562-df1f-11e7-8444-c8a57f71064b.png)

**Comment by Moulde** [comment]
Adding --watch-extensions ts works for me too (on osx, visual studio code) 👍 

mocha -r ts-node/register test/**/*.ts --reporter mochawesome --reporter-options reportDir=TestResults --watch --watch-extensions ts
