### ISSUE TITLE
`Runner#fail` is getting executed with an instance of `Pending`

### ISSUE THREAD

**Issue by dasilvacontin** [mochajs/mocha#2337]
code smell: https://github.com/mochajs/mocha/pull/946#issuecomment-227715287
https://github.com/mochajs/mocha/blob/8a37e016e5629b46709891740c74d5f0b69929e0/lib/runner.js#L221-L234

**Comment by dasilvacontin** [comment]
The test shouldn't be marked as `failed` when the thrown Error is what we use to indicate a Pending test.

**Comment by ScottFreeCode** [comment]
Re. https://github.com/mochajs/mocha/pull/2335#issuecomment-228910822: we also have #2228 re. the relationship of Pending and Error. However, merely changing Pending to extend Error would in this case presumably result in it being processed through the `fail` function as though it were a regular error, which wouldn't be correct either... am I right about that?

**Comment by boneskull** [comment]
Oh, hm.  Well, `Pending` isn't a failure, but it is intended to abort the test.  I don't think it should be marked "failed", but as long as reporters don't know about it, I don't see it being a urgent issue, right?

**Comment by dasilvacontin** [comment]
I hadn't seen #2228 – thanks for the ref, @ScottFreeCode!

Not urgent, but I'm somewhat curious about this one.

**Comment by boneskull** [comment]
@dasilvacontin `Runner.prototype.fail()` doesn't seem to actually get executed when something is skipped via `this.skip()`.  Did you observe this?

**Comment by dasilvacontin** [comment]
Yes, in my trivial async skip example. Or at least I did get the exception when I wrote the comment.
