### ISSUE TITLE
 minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

### ISSUE THREAD

**Issue by efortes** [mochajs/mocha#2342]
Could you please update your package to use the latest version of minimatch?

Error: minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

``-- mocha@2.5.3
  `-- glob@3.2.11
    `-- minimatch@0.3.0
`

**Comment by boneskull** [comment]
@efortes please search before posting an issue

#2331

**Comment by krushnachandra** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\CGM\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'lite' ]
2 info using npm@3.10.6
3 info using node@v5.5.0
4 verbose run-script [ 'prelite', 'lite', 'postlite' ]
5 info lifecycle product-management@1.0.0~prelite: product-management@1.0.0
6 silly lifecycle product-management@1.0.0~prelite: no script for prelite, continuing
7 info lifecycle product-management@1.0.0~lite: product-management@1.0.0
8 verbose lifecycle product-management@1.0.0~lite: unsafe-perm in lifecycle true
9 verbose lifecycle product-management@1.0.0~lite: PATH: C:\Users\CGM\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;E:\Krushna\Angular2\Angular2-GettingStarted\APM - Final Updated\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\Krushna\Angular2\Angular2-GettingStarted\APM - Final Updated\node_modules\.bin;C:\Users\CGM\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\CGM\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Skype\Phone;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Git\cmd;C:\Program Files\dotnet;C:\Program Files\nodejs;C:\Users\CGM\.dnx\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\CGM\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle product-management@1.0.0~lite: CWD: E:\Krushna\Angular2\Angular2-GettingStarted\APM - Final Updated
11 silly lifecycle product-management@1.0.0~lite: Args: [ '/d /s /c', 'lite-server' ]
12 silly lifecycle product-management@1.0.0~lite: Returned: code: 1  signal: null
13 info lifecycle product-management@1.0.0~lite: Failed to exec lite script
14 verbose stack Error: product-management@1.0.0 lite: `lite-server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\CGM\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\CGM\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid product-management@1.0.0
16 verbose cwd E:\Krushna\Angular2\Angular2-GettingStarted\APM - Final Updated
17 error Windows_NT 10.0.10240
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\CGM\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "lite"
19 error node v5.5.0
20 error npm  v3.10.6
21 error code ELIFECYCLE
22 error product-management@1.0.0 lite: `lite-server`
22 error Exit status 1
23 error Failed at the product-management@1.0.0 lite script 'lite-server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the product-management package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     lite-server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs product-management
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls product-management
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
