### ISSUE TITLE
expand IE matrix

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2344]
saucelabs should test ie9, ie10, ie11

**Comment by coderbyheart** [comment]
Actually I think it would be better to split the execution of the saucelabs test up so they are separate on Travis. I'll make that change and update the PR.

**Comment by boneskull** [comment]
> Actually I think it would be better to split the execution of the saucelabs test up so they are separate on Travis. I'll make that change and update the PR.

If they are separate, how can we guarantee we don't run over the concurrency limit?

**Comment by coderbyheart** [comment]
If set the concurrency limit of travis to 5 … https://blog.travis-ci.com/2014-07-18-per-repository-concurrency-setting/

**Comment by coderbyheart** [comment]
But it's actually breaking for other reasons, I've just started the build again, let's see: https://travis-ci.org/coderbyheart/mocha
