### ISSUE TITLE
we need stinkin' badges

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2346]
I guess I'd like to see some badges that show what environments Mocha claims to support.

**Comment by hollomancer** [comment]
@boneskull, is this different from #2590?

**Comment by dasilvacontin** [comment]
It would be lacking the Node versions I guess.

**Comment by kunagpal** [comment]
Badges galore: https://github.com/boennemann/badges

**Comment by juergba** [comment]
fixed by #4438.
