### ISSUE TITLE
upgrade eslint

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2348]
eslint is stuck at 1.x due to breaking changes.  I'm not going to change it for v3.0.0, so sometime thereafter would be fine.

**Comment by tjni** [comment]
I had some spare time so was looking to do some busy work like this, but ESLint 3 drops support for versions of node < 4. Should we upgrade to 2.x and stay there until a similar decision can be made for Mocha?

**Comment by tjni** [comment]
Actually, does the v3.0.0 refer to Mocha or to ESLint? If the former, then that makes sense if Mocha 3 drops support for old versions of node. But it would need to drop even 0.12 for the latest ESLint.

**Comment by boneskull** [comment]
@tj v3.0.0 refers to Mocha.  eslint@2.x.x would be fine, but if we can't get to the latest major it's even less important

**Comment by boneskull** [comment]
closed via #fb6ef8fbfbba6b4c4f48b491977e02a732e82b03 in v3.0.0 branch
