### ISSUE TITLE
delete old branches

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2353]
too many branches just hangin' around.

**Comment by drazisil** [comment]
I can delete all merged and closed branches, if that's ok. (not sure if I have the permissions though.

**Comment by boneskull** [comment]
go for it. any un-merged branch over a couple years old should be deleted
too. the rest we can look at

**Comment by drazisil** [comment]
Done. What do you want done with the Greenkeeper PRs? https://github.com/mochajs/mocha/pulls?q=is%3Apr+is%3Aopen+label%3Agreenkeeper

**Comment by boneskull** [comment]
they all seem to break the build, but everything except #2668 is a devdependency, and we should probably upgrade those if we can.  upgrading production dependencies is difficult rn

**Comment by boneskull** [comment]
in other words, leave and/or fix and/or merge them
