### ISSUE TITLE
drop HTMLCov and JSONCov reporters

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2356]
I mentioned this in [Gitter](https://gitter.im/mochajs/mocha?utm_source=share-link&utm_medium=link&utm_campaign=share-link), but both of these reporters leverage [node-jscoverage](/tj/node-jscoverage), which is old and busted.  It's my suspicion that these two reporters are rarely--if ever--used by anyone.  Better coverage options exist in the form of [istanbul](http://npmjs.com/package/istanbul), [nyc](http://npmjs.com/package/nyc), etc.

Furthermore, the only reason we have a dependency on jade/pug is these reporters.

I would like to drop them completely for v3.0.0, and remove the jade/pug dependency.

**If anyone out there uses either of these reporters, please let us know!**

cc @mochajs/core

**Comment by dasilvacontin** [comment]
Reporter usage statistics? :)

**Comment by boneskull** [comment]
Well, we won't know until we break it and someone tells us, but it *is* a major.

**Comment by boneskull** [comment]
closed via b47835b in `v3.0.0` branch

**Comment by ScottFreeCode** [comment]
A bit late, but my 2&cent;'s worth:
- Using reporters that require a specific coverage tool does not scale well. Having a standard format for coverage to be output and (a) reporter(s) that use(s) said format, so we're not limited to specific coverage tools, would be far more maintainable.
- If there are adequate coverage tools that work with Mocha without a special Mocha reporter needed at all, then a reporter's not really a necessity.
- Mocha can take third-party reporters if I'm not mistaken, so if anybody wants/needs Mocha reporters that include coverage (including the existing ones), we/they can just package them separately.
