### ISSUE TITLE
🚀 Feature: Highlight words wrapped in backticks on reporter output

### ISSUE THREAD

**Issue by ricardogama** [mochajs/mocha#2358]
It's a common practice to wrap words related to code in backticks on test titles, which can make a lot of visual noise on the reporter output.

I suggest to add an option that could enable such feature, for example `--highlight-backticks`, which could transform this:

<img width="919" alt="screen shot 2016-07-06 at 18 15 31" src="https://cloud.githubusercontent.com/assets/8616978/16627603/decb5cc8-43a5-11e6-920c-e87bc31d3294.png">

Into this:

<img width="878" alt="screen shot 2016-07-06 at 18 16 55" src="https://cloud.githubusercontent.com/assets/8616978/16627614/e5755b8c-43a5-11e6-8575-dcb0a50b59c9.png">

I already made a draft of its implementation but I would like to have some feedback about its usefulness  prior to opening a PR.

**Comment by boneskull** [comment]
This is a cool idea.  But it has me thinking: what if we could use [marked-terminal](https://www.npmjs.com/package/marked-terminal), or something like it?

Granted, we're going to have some problems with the `chalk` dependency, but we could try that again, since we know what we're getting into...

**Comment by ricardogama** [comment]
@boneskull I'm glad you like the idea!

Refactoring the output management seems cool and would clean up code like a charm, but adding a dependency to do so has some drawbacks, like the engine requirements. 

As you said, [chalk](https://github.com/chalk/chalk) has Node.js 0.10 as minimum engine requirement which could break Mocha's 0.8 compatibility, unless you guys consider releasing a major version.

The solution I came around has no breaking changes and is ready to be pushed but keep the discussion going, I think the reporters' refactor is a thing that we really should sleep on.

**Comment by boneskull** [comment]
@ricardogama We're planning on dropping v0.8 compat [for v3.0.0](/mochajs/mocha/pull/2350), but the real concern is browser compatibility, believe it or not.

**Comment by JoshuaKGoldberg** [comment]
Coming back to this >7 years later: kind of funny that Chalk compatibility would again be a concern... except this time, it's Chalk being ESM only. 😂 

Anyway, I don't know of other test runners that do this, and only ~4 people have interacted with this issue in that time. That's barely more than one person every two years. I'm going to take that as a sign that there isn't much user interest in this feature. Given #5027, we're trying to avoid changes that don't have broad appeal. 

If anybody thinks I'm wrong here, please do file a new issue - it is an nice idea! 

For now, closing as wontfix. Thanks all!
