### ISSUE TITLE
add working examples

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2359]
We should have some working examples of common configurations.  Ideally these will also be available on [mochajs.org](https://mochajs.org), but should live in the repo as well.  These files should not be distributed with a production `npm` install nor a `bower` install.

If anyone is interested in adding something, I'm using the [examples branch](/mochajs/mocha/tree/examples); send a PR or commit there.

**Comment by gurdiga** [comment]
Hey @boneskull! 😃 

That’s interesting. I just realized that when I setup testing for a new web project, I just copy and paste the HTML from the [mochajs.org webpage](http://mochajs.org/#running-mocha-in-the-browser), and then start tweaking it until it’s right. 🤓

Thinking about it, I guess it tells that I’m accustomed, and for this PR it’d be useful to have the perspective of someone who is just beginning with Mocha. I was wondering if maybe there are other PRs — or really any other kind of thing — that would hint on what are some of those scenarios that it’d be helpful to have examples for. 🤔

**Comment by brutalcrozt** [comment]
It seems the example branch is limited to internal team? Since i need read access, please enable it publicly. :smile:

**Comment by outsideris** [comment]
Now, we have [mocha-examples](https://github.com/mochajs/mocha-examples).
