### ISSUE TITLE
Update minmatch/dependencies who pull in minimatch to avoid RegExp DoS issue? 

### ISSUE THREAD

**Issue by yaananth** [mochajs/mocha#2363]
```
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

**Comment by boneskull** [comment]
@yaananth please search before creating issues, thanks

**Comment by yaananth** [comment]
@boneskull  I did.
![image](https://cloud.githubusercontent.com/assets/12280011/16705839/c4c50228-4564-11e6-9d09-66af4ac5a0ca.png)

There might be an issue addressing this, but when I search ( I would be searching for minimatch, since that's the issue.)

Could you please link the existing issue? Thanks!

**Comment by bilherron** [comment]
@yaananth the search in your screenshot is "minmatch" (missing an i). :)

**Comment by yaananth** [comment]
@bilherron  oh wow :) thanks for pointing it out. #2331
