### ISSUE TITLE
proper name

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2369]
Okay, since we needed to use `mochajs` for the GH org and `mochajs.org` for the site, there's a precedent for **MochaJS** as the proper name, or **Mocha.js**.  But then again `mocha` is the package and `mocha` is the repo and the logo reads "mocha".

An argument for "MochaJS" or "Mocha.js" is that it is unique, and thus easily searchable.  An argument for "Mocha" is that it is simple.  Curious to hear anybody's thoughts.

@mochajs/core

**Comment by gurdiga** [comment]
Sorry for the potentially silly question: Proper name of what? 😬

**Comment by WillLuce** [comment]
MochaJS seems right to me. If it's the URL, it should be the name. MochaJS is the way I've heard it referenced in the wild.

**Comment by boneskull** [comment]
@willluce would you expect the package name and cli executable to be `mochajs`?

**Comment by WillLuce** [comment]
@boneskull that makes sense. As a developer, I can see that as an evolution of the project. This just feels like pulling everything together and making it more professional. Even npm is https://www.npmjs.com/

**Comment by Alhadis** [comment]
I don't think the names of the package and executable need to be changed to reflect a shift in name. Node.js remains `node`, and it's usually clear what "node" refers to in a conversation's context.

> Even npm is https://www.npmjs.com/

Well... can't say for sure, but that might've had something to do with http://www.npm.com/ being a redirect to nasdaqprivatemarket.com. =)

**Comment by dasilvacontin** [comment]
| GH Org | Repo | Package/Executable | Name in Website | Website |
| ------- | ----- | --------------------- | ---------------- | -------- |
| chancejs | chancejs | chance | Chance | http://chancejs.com/ |
| gruntjs | grunt | grunt / grunt-cli | Grunt | http://gruntjs.com/ |
| gulpjs | gulp | gulp / gulp-cli | gulp | http://gulpjs.com/ |
| nodejs | node | node | Node | https://nodejs.org/ |
| mochajs | mocha | mocha | Mocha | http://mochajs.org/ |

(feel free to edit and add more)

**Comment by ScottFreeCode** [comment]
That list confirms my hunch that the apparent inconsistency in Mocha's naming convention is actually consistent with a common convention for JS libraries and tools.

Even in the absence of such examples, I'd be inclined to keep the current convention on the grounds that:
- Mocha is arguably the library/tool's "true" name, easier to read out loud, and the simpler way to refer to it when in a context where it's already obvious we're working with JavaScript, but
- MochaJS (or mochajs in GH/urls where capitalization is frowned upon or ignored) is handily explicit and clear in broader contexts, like saying "the JavaScript tool/library Mocha" only far less wordy, thus avoiding vagueness as to what Mocha is or potential confusion with any non-JS thing named Mocha (though I'm not aware of any at this time, who knows what the future holds; just look at the Jade/Pug issue, or the leftpad fiasco)

**Comment by boneskull** [comment]
@dasilvacontin's table basically resolves this issue.  excellent work
