### ISSUE TITLE
Putting a testing suite in a function causes it to execute last

### ISSUE THREAD

**Issue by brubakbd** [mochajs/mocha#2374]
I'm fairly new to mocha, just started working with it for my summer internship, just as a forewarning in case I'm just doing something stupid. 

I've written some code to dynamically test a feature of my company's product. We're able to send a request and get back all of the possible values to test the feature with. From there, the testing suite is basically the same and I have it all in a function with a few variables. That way I should be able to call the function with the desired values and the test suite will run for that case. However, the issue I'm getting is that it runs all the tests in the function at the very end of the testing for some reason, and it puts them outside of the overarching suite when looking at test results. In addition, a console log right before entering the function will print in the right order, but a console log inside the function will all print at the very end.

I made some extremely simplified code that kind of shows the layout of what I'm trying to do:
```
function test(){
    //Testing suite to test through a certain functionality using different variables
    describe('inner',function(){
        it('test3',function(){
            console.log('\ninner test');
        });
    });
}
function entityLoop() {
    describe('outer',function(){
        //Get field values from an http request
        it('test1',function(){
            console.log('\ntest1');
        });
        it('test2',function(){
            console.log('\ntest2');
        });

        //This MUST run after the other two tests, as those tests get the values needed to run the following tests
        //I know it's typically bad practice to make dependent tests, but that's how we're dynamically creating the tests
        after(function(){
            //Use field values in a testing suite
            console.log('after test');
            test();
        })
    })
}

describe("Overall loop",function(){
    //Need to loop through a testing suite, changing some variables each time
    for(var i = 0; i < 5;i++){
        entityLoop();
    }

});
```

This is the console output of it:
```
test1
test2
after test
test1
test2
after test
test1
test2
after test
test1
test2
after test
test1
test2
after test
inner test
inner test
inner test
inner test
inner test
Process finished with exit code 0
```

Issue is that 'inner test' is for some reason all printed at the very end, instead of in the patter the other 3 console.logs are printed at.

**Comment by boneskull** [comment]
The behavior of Mocha (and RSpec, which it was based on) is:

- execute all suites (`describe`) in a depth-first fashion
- tests and hooks are queued up as they are encountered, but not executed
- when all suites have executed, tests (and hooks) begin to run

Which seems consistent with what you're experiencing.  This issue has come up before--the order in which things run is sometimes surprising to new users of Mocha.  This strategy enables a feature wherein you can run only a single test or suite.  If we execute tests as they appear, and we have two tests *A* and *B*, we cannot skip test *A* if Mocha is told to *only* execute test *B*.  Make sense?
