### ISSUE TITLE
Running test-suites in independent process/thread?

### ISSUE THREAD

**Issue by SamuelMarks** [mochajs/mocha#2376]
Running my tests one suite at a time and they all pass. Running them together gives an `AdapterError`.

https://github.com/SamuelMarks/waterline-test-case

Is there some way to run them independently yet concurrently? - Failing, how do I configure them to run sequentially? (await one suite's end before beginning another)

BTW: Posted on [the mailing-list](https://groups.google.com/d/topic/mochajs/4itJXrHX8pI/discussion) about a week ago also

**Comment by boneskull** [comment]
...then something in your suite is not cleaning up after itself.  By "running them together" I suppose you mean executing multiple test files at once.

Mocha does not support concurrent execution, though there are some hacks around it published to npm.

*Suites* do not run asynchronously; you cannot do asynchronous stuff in a `describe()` block, unless you use the `--delay` option--and even then you can only do it *once*.

*Tests* run sequentially.  *Hooks* and *Tests* both support asychronous behavior.

I'm curious if the `teardown` function in [this line](https://github.com/SamuelMarks/waterline-test-case/blob/master/test/shared_tests.js#L5) is losing its context when run in this manner.  Does it need `Function.prototype.bind()`?

**Comment by gurdiga** [comment]
@SamuelMarks announced on the mailing list that:

> Oh finally resolved the issue today, was a problem with the adapters teardown adapter

So we can close this. 🤓
