### ISSUE TITLE
Getting started guide throw error because chai is not found

### ISSUE THREAD

**Issue by gerrytan** [mochajs/mocha#2384]
The getting started guide at https://mochajs.org/#getting-started gives me error when I try to run the test using the `mocha` command. It complained about unable to find chai. I had to do `npm install chai` to resolve it

**Comment by boneskull** [comment]
hmm, yeah, good point, this belongs in [the other repo though](/mochajs/mochajs.github.io)

**Comment by anthony-redFox** [comment]
[pull request](https://github.com/mochajs/mochajs.github.io/pull/45) for the issue.
