### ISSUE TITLE
Update glob to update vulnerable minimatch package

### ISSUE THREAD

**Issue by nbergseng** [mochajs/mocha#2385]
[minimatch < 3.0.2 is vulnerable to a DoS](https://nodesecurity.io/advisories/118) and fails nsp checks.  Recommend updating to latest glob (>=7.0.5) to pick up a more recent minimatch.

**Comment by marvinhagemeister** [comment]
Duplicate of #2318, #2349, #2129, #2363, #2354, #2342

**Comment by nbergseng** [comment]
doh. closing.

**Comment by popomore** [comment]
Is there an PR? Don't see it on master.

**Comment by popomore** [comment]
https://github.com/mochajs/mocha/commit/05c5e5ca7ae9c4beb1bb1d944dbf1a6d9a5a50bd

Saw it on 3.0.0
