### ISSUE TITLE
using multiple User Interfaces, -u, --ui

### ISSUE THREAD

**Issue by quangv** [mochajs/mocha#239]
Pretty easy for someone to just add `suite = describe; etc.`, but it's an interesting idea to consider adding native...

```
mocha test.js -u tdd -u bdd
```

which would allow syntax like

``` javascript
suite('Test', function() {
  describe('Function', function() {
    setup(function() {
      // setup...
    });
    it('should work', function() {
      // blah blah
    });
    teardown(function() {
      // teardown...
    });
  });
});
```

lol, I guess I just don't like things like

```
suite('Parent', function() {
  suite('Child', function() {
    // "describe" sounds better nested
  });
});
```

downside is encouraging bad habits, and name conflicts... what do you think?

**Comment by danday74** [comment]
I don't want to mix and match - I'm forced to!
