### ISSUE TITLE
Option to exit with code 0 for test runners that produce structured reports

### ISSUE THREAD

**Issue by ianwremmel** [mochajs/mocha#2392]
I'm using mocha with jenkins and xunit. Jenkins builds have three basic states: failed, unstable, success. unstable implies some tests failed, but the general set of orchestration to run the tests succeeded whereas failed implies the test script is incorrect. It would be helpful if mocha could (optionally) follow a similar strategy (at least when using test reporters that produce structured output). 

(I'm invoking mocha via grunt, so it's not as simple as wrapping in a bash script and suppressing the exit code)

**Comment by boneskull** [comment]
@ianwremmel It's not clear to me what behavior you want, exactly.

At some point someone (maybe even me; I don't remember) decided it was a good idea to exit with a code representing the number of errors.  I'll have to refresh my memory about how this is supposed to be consumed (and see if anything "in the wild" is consuming it)...

**Comment by ianwremmel** [comment]
@boneskull, yea, I kinda felt like I was rambling a bit when I submitted that. First, let me be clear that I don't want to change default behavior; if this gets built it should definitely require opting in to this behavior. 

For test runners like Travis, an exit code is the only way to indicate that tests have failed. Jenkins, however, lets you produce structured output (in my case, I'm using the Xunit reporter). Jenkins differentiates an "unstable" build (where tests have failed) from a "failed" build (where something has gone wrong with the testing process and tests couldn't run: e.g. a syntax error). It would be really helpful if mocha could exit with code zero when it successfully produces test reports, even if those test reports indicate failed tests. 

(I see no need to make mocha detect if it's using such a test reporter, a command line option seems adequate)

**Comment by gurdiga** [comment]
Hey @iammerrick! 🙂

It seems to me that this kind of plumbing work falls into a build tool’s responsibilities. 🤔

You said that you’re invoking Mocha via Grunt. This made a question pop up in my mind: In that case Mocha is run programmatically by Grunt, and then we’re talking about Grunt’s return value, aren’t we? 🤓

**Comment by ianwremmel** [comment]
Sort of. I'm using grunt-continue to get halfway to what I'm asking for, but the problem is that I still end up suppressing both test failures and errors caused by test suite misconfiguration. Since a misconfigured test suite doesn't produce any junit output, Jenkins will actually see this failure as a success. Hence, I'm asking for a way for mocha (and, as a side effect, grunt-mocha-test) to be configured to only fail if something prevents it from running tests and to not fail if certain tests fail.

**Comment by ianwremmel** [comment]
So, I just opened https://github.com/pghalliday/grunt-mocha-test/pull/126, which solves the problem on the node side of things, but I also run my tests in web browsers using karma, and so far, I haven't worked out how to do something similar with karma. 

I'm not sure I fully understand mocha's exit process yet, but could this be done by adding something like the following pseudocode to the `exit()` function in https://github.com/mochajs/mocha/blob/master/bin/_mocha?

```
if (SUPRESS_FAILED_TESTS && code > 0) {
  process.exit(0)
}
```

And would that change easily propagate to wrappers like grunt-mocha or does the option handling really belong somewhere inside lib/mocha.js?

**Comment by Munter** [comment]
@boneskull 

> At some point someone (maybe even me; I don't remember) decided it was a good idea to exit with a code representing the number of errors.

Danger! Exit codes can only be in the range of 0-255. An exit value greater than 255 returns an exit code modulo 256, which means you can infer nothing from it. Also some exit codes have special meaning, which will potentially cause clashes.

See http://tldp.org/LDP/abs/html/exitcodes.html

**Comment by boneskull** [comment]
@iammetrick does `--no-exit` help? this shouldn't return nonzero unless there's an uncaught exception (I think...)

**Comment by ianwremmel** [comment]
Sounds plausible. I'll look into it, thanks! Is that documented anywhere or just in the command line output?

**Comment by reduckted** [comment]
`--no-exit` does not help. It still returns the number of errors (at least from my trials with it using mocha via `npm run test`). 

From what I can see, it would be easy enough to always return zero if there were failed tests by using a new option, but differentiating between a failed assertion and an error in a test seems to be a bit trickier (assuming that we would still want to return non-zero if there was an error).

**Comment by amedee** [comment]
I have the same question. I have this in my `Jenkinsfile`:

        stage('Test') {
            steps {
                sh './node_modules/.bin/mocha --reporter mocha-multi --reporter-options dot=-,xunit=reports/test.xml'
            }
            post {
                always {
                    junit allowEmptyResults: true, testResults: 'reports/*.xml'
                }
            }
        }

I want this step to be UNSTABLE (yellow) when there are test failures, and FAILED (red) when there are syntax errors in the test script.

**Comment by gannons** [comment]
Disappointing to see this remains an issue in 2020. Did anyone come up with a work around?

So far I'm heading toward

    sh "npm test || true"

which is not ideal.

**Comment by ianwremmel** [comment]
@gannos Not exactly a workaround but I
1. Switched to jest
2. Switched to buildkite for CI which let's me control which jobs fail a build
3. Built check-run-reporter.com to move the report processing out of the CI system so I don't have to care about the exit code.

Mostly, I simply accepted that most report systems don't acknowledge the difference between Errors and Failures so I stopped trying.

**Comment by gannons** [comment]
Good memory @ianwremmel. I doubt I'd have much luck recalling what I worked on 4 years ago.

Originally I switched to `jest`. But it had a few problems (mostly around logging) and I ended up switching back to `mocha`.

> I simply accepted that most report systems don't acknowledge the difference between Errors and Failures

Think that's the really answer here.

**Comment by ianwremmel** [comment]
I mean, I've been working on check-run-reporter.com for quite a while now, so it's hard to forget ;)

But really, it is mostly that Jenkins is the only system I've encountered that has this particular notion of "unstable", so once I was freed from Jenkins's tyranny, this stopped being a thing on my mind.

**Comment by boneskull** [comment]
I'd recommend using `mocha || true`.  `command-that-may-exit-with-nonzero-code || true` is how I've implemented behavior akin to this, and I've seen it used in various scripts

**Comment by ZiedHf** [comment]
I just fixed this issue by using try catch finally in the Jenkins file

```
try {
      doTest() // for instance powershell "yarn test"
      currentBuild.result = 'SUCCESS'
} catch (err) {
    echo "Failed: ${err}"
    currentBuild.result = 'FAILURE' // OR UNSTABLE if you want
} finally {
    doDisplayResult() // use junit or whatever you want to display the structured reports
}
```

Hope this help someone.
