### ISSUE TITLE
Question: Has anyone noticed a speed difference in initialization on a Windows vs Mac

### ISSUE THREAD

**Issue by kwelch** [mochajs/mocha#2396]
I am using mocha with our team, and others on the team including our build box take a long time to initialize tests(6 mins). However, on my mac I am able to run the multiple times over before they see the result of their first run. 

I assume it is initialize, because based on the metrics all of my 100+ tests take under 200ms to run. 

We are using `NODE_ENV = 'test'`, disabled `css, scss, png, jpg` extensions, and are using `babel-register`

**Comment by boneskull** [comment]
I have noticed running mocha's own tests is significantly slower on AppVeyor. 

It'd be helpful if someone could run benchmarks or otherwise discover the bottleneck, and if it's something we can even address.

**Comment by Kitanotori** [comment]
I'm not sure if we are talking about same issue, but the first time running mocha was very slow for me, almost 1min even though there were only few simple test cases. Does mocha use some kind of global cache or something, because I'm not able to reproduce the issue?
