### ISSUE TITLE
Q: How to test es6 code in combination with coffee-script in my mocha tests

### ISSUE THREAD

**Issue by felixbecker** [mochajs/mocha#2397]
Hi I have posted a question on stackoverflow because I have a hard time configuring mocha to test my es6 production code with coffee-script mocha tests.

Since I got no feedback I would like to ask if someone could help either here or on stackoverflow to answer my question. 
I explained my tryings and details here: http://stackoverflow.com/questions/38445457/how-to-use-babel-in-combination-with-coffee-script-in-my-mocha-tests

Any help would be kindly appreciated.
Thanks

**Comment by boneskull** [comment]
Replied on SO
