### ISSUE TITLE
Watch does work only for test files, does not refresh for project files

### ISSUE THREAD

**Issue by tomitrescak** [mochajs/mocha#2399]
I have this strange issue, when mocha reloads only when I update a "test" file. When I update a project file (SUT) the mocha keeps the original version somehow cached. I tried different approaches and nothing works. Any ideas?

Here is how I run it:

```
mocha --colors --watch imports/test/browser.js imports/**/tests/**/*.js* --compilers js:babel-core/register
```

**Comment by boneskull** [comment]
probably because babel gives mocha a transpiled file, and mocha watches the transpiled file instead of the source file.  try it with `--require babel-register` instead of `--compilers`; if that doesn't help you, you'll need to have some other tool help you do this.

**Comment by boneskull** [comment]
at any rate, #1780 is a thing, and I'd rather not build on top of it in its current state, and instead extract the functionality into a separate module.

**Comment by boneskull** [comment]
I heard [npm-watch](https://www.npmjs.com/package/npm-watch) is a thing

**Comment by tomitrescak** [comment]
@boneskull thanks for your comment. I solved it along those lines. I used the watch-run lib and here is my solution extracted from package.json

```
scripts: {
      "test": "mocha --colors imports/**/tests/**/*.js* --require babel-register",
      "test-watch": "watch-run -i -p 'imports/**/tests/**/*.js*,imports/ui/*.jsx' npm run test"
}
```

run it as 

```
npm run test-watch
```
