### ISSUE TITLE
Update minimatch

### ISSUE THREAD

**Issue by rugk** [mochajs/mocha#2404]
Minimatch seems to be vulnerable:
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by boneskull** [comment]
in YouTrack, they have a feature wherein it displays "similar issues" to the user as they create a ticket...

**Comment by rugk** [comment]
As https://github.com/mochajs/mocha/pull/2325 was closed, is there an open issue tracking (the time until) a fix?
Is there any open issue or PR tracking this? I mean obviously the issue is still there...

**Comment by boneskull** [comment]
It will be in v3.0.0 which I had planned to release last week. Beta versions have been released and are installable from npm. Might release tonight; don't know. In general, only the largest OSS projects will have some sort of formal release schedule, so asking "when" something will land is usually an exercise in futility--unless, of course, you fix it yourself. :smile:
