### ISSUE TITLE
Jade transition to Pug

### ISSUE THREAD

**Issue by YasharF** [mochajs/mocha#2405]
Jade is renamed to Pug.  Although dependencies on Jade work, the code is not maintained from what I have gathered as all the new changes will be under the pug package.  There are some syntax differences, so moving from Jade to Pug may require verifying that all the views still work.

Refrence: https://github.com/pugjs/pug#rename-from-jade

**Comment by boneskull** [comment]
please search before creating issues

**Comment by YasharF** [comment]
https://github.com/mochajs/mocha/issues/2200#issuecomment-235493858
