### ISSUE TITLE
Mention on Totally Tooling Tips

### ISSUE THREAD

**Issue by gauntface** [mochajs/mocha#2409]
I'm a big fan of Mocha and would like to mention it on Totally Tooling Tips, is this ok with the org / project?

(Totally Tooling Tips is a Video series me and Addy Osmani do here: https://www.youtube.com/watch?v=IWgNn1kqrsA&list=PLOU2XLYxmsILKwwASNS0xgfcmakbK_8JZ)

Cheers,
Matt

**Comment by danielstjules** [comment]
Don't see why not 😄

**Comment by gauntface** [comment]
Thank you :)
