### ISSUE TITLE
investigate test flake on AppVeyor

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2415]
The 'delay' test on Node.js v4 on AppVeyor seems to have a high failure rate (though inconsistent).  Let's fix it.

**Comment by ScottFreeCode** [comment]
@boneskull Is this still an issue? I haven't seen any problems in AppVeyor (except that issue with Node 0.10 that we recently fixed) in a long time.

**Comment by boneskull** [comment]
this is now invalid.  AppVeyor failures are usually just timeouts.
