### ISSUE TITLE
infinite loop with nested .only()

### ISSUE THREAD

**Issue by adamjmurray** [mochajs/mocha#2417]
Run the following test through mocha 3.0.1:
```
var assert = require('assert');

describe('Array', function() {

  describe.only('.push()', function() {

    it.only('appends a value to the end of the array', function() {
      var array = [1];
      array.push(2);
      assert.deepEqual(array, [1, 2]);
    });
  });
});

```

Mocha exits with an exception that seems to indicate an infinite loop occurred:
```
RangeError: Maximum call stack size exceeded
    at filterOnly (/Users/adam/workspace/cirrus/node_modules/mocha/lib/runner.js:857:23)
    at /Users/adam/workspace/cirrus/node_modules/mocha/lib/runner.js:861:9
    at Array.forEach (native)
    at filterOnly (/Users/adam/workspace/cirrus/node_modules/mocha/lib/runner.js:857:23)
    at /Users/adam/workspace/cirrus/node_modules/mocha/lib/runner.js:861:9
    at Array.forEach (native)
    at filterOnly (/Users/adam/workspace/cirrus/node_modules/mocha/lib/runner.js:857:23)
    ...
```

This is a simplified example. In practice, I sometimes focus on getting a single `it.only()` test passing, and then go "up a level" and test a group of related tests via a `describe.only()` block.

Not a blocker. Workaround: don't use nested `.only()`

**Comment by not-an-aardvark** [comment]
Can reproduce. The issue is that the suite is attempting to filter its own `only` suites [here](/mochajs/mocha/blob/6a401c74c8f990e9c9d74e826bb56c449e1c1c3b/lib/runner.js#L858-L861), rather than its children's `only` suites. I'll make a PR.
