### ISSUE TITLE
Third party reporters (mocha 3.0.0)

### ISSUE THREAD

**Issue by genzoman** [mochajs/mocha#2418]
I'm on OSX, have mocha installed globally and locally.  I added a custom reporter to both my global node install path and my local node install path in the /lib/reporters folder, and when I try to run 
mocha myRepoter -R ./spec/test.js I get "unknown reporter".

**Comment by gurdiga** [comment]
Hey @genzoman! 🙂

It looks like your command line needs a little tweak: the reporter name is expected to be after the `-R`, something like this:
```
mocha -R myRepoter ./spec/test.js
```

Give it a try and see if it solves it. 🤓

**Comment by boneskull** [comment]
gonna assume that worked :smile:
