### ISSUE TITLE
JS errors block tests from running

### ISSUE THREAD

**Issue by arosenb2** [mochajs/mocha#2421]
I recently noticed that if I had a parse error in one of my test files, it seems to block execution of all the tests in that and subsequent test files. It would be nicer if any JS errors would trigger an overall run failure instead.

**Comment by boneskull** [comment]
I think the current behavior is OK, because we have no way of knowing (short of parsing an AST) if  a syntax error in file `a.js` would break `b.js`.  What you're asking for could result in very tough-to-debug situations.  Thanks for the suggestion though!
