### ISSUE TITLE
Question: Is there a javascript API documentation?

### ISSUE THREAD

**Issue by moglars** [mochajs/mocha#2422]
Mocha seems to output its results only over CLI. Is there a way to use mocha programmatically without having to parse stdout for the results?

**Comment by gurdiga** [comment]
Hey @moglars! 🙂

[The docs](http://mochajs.org/#more-information) say:

> For the JavaScript API, view [The Source®](https://github.com/mochajs/mocha/blob/master/lib/mocha.js#L51).

…which, even with that nice and readable source code, I agree may not be the most newcomer-welcoming message. 😑

Other than that though, there is a quick-start wiki page: [Using mocha programmatically](https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically). Maybe that would be helpful to get you up and running. 🤓

**Comment by moglars** [comment]
I looked into the code. The event system suits my needs:
```
var runner = mocha.run()
runner.on('pass', function(test) {console.log(test.title)})
runner.on('fail', function(test, err) {console.log(test.title,err.toString())})
```
The page https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically doesn't mention that `mocha.run()` returns a `Runner ` instance that emits events of interest. I recommend adding a note about this in the wiki page.

**Comment by Munter** [comment]
If you are interested in writing your own reporter I suggest you take a look at the different already existing ones: https://github.com/mochajs/mocha/tree/master/lib/reporters

**Comment by gurdiga** [comment]
> I recommend adding a note about this in the wiki page.

Documentation improvements are always welcome! 🤓 I have [added](https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically/_history) it myself this time, but I bet you could do it yourself next time, and get your dent in The Open Source Universe®. 😎

**Comment by boneskull** [comment]
yeah, the wiki needs love.  I'm not sure the "API" is really worth documenting though.  😦
