### ISSUE TITLE
Test succeeds but should fail. Plus sign in the test name.

### ISSUE THREAD

**Issue by Andreyul** [mochajs/mocha#2428]
This test succeeds in Mocha 3.0.2 but should fail.
```
const assert = require('assert');

it('+ ', function () {
    assert(false);
});
```
This test is failing under Mocha 2.5.3 as expected.

Output:
```
Test Name:	+
Test Outcome:	Passed
Result StandardOutput:	
1..0
# tests 0
# pass 0
# fail 0
```
Visual Studio 2015 Pro v.14.0.25425.01 Update 3
Node.js Tools 1.2.40726.00
TypeScript 1.8.36.0
Mocha 3.0.2

**Comment by gurdiga** [comment]
Hey @Andreyul! 🙂

I have tried to reproduce and didn’t quite succeed: https://asciinema.org/a/35iycay1hn60b6d7bjyyq5ks9. 😑

Could you please take a quick look and see what I may have missed? 🤓

**Comment by Andreyul** [comment]
Node.js Tools for Visual Studio calls [mocha.grep(testName)](https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/TestFrameworks/mocha/mocha.js#L68) when running tests.
Before Mocha 3.0.0 strings passed to mocha.grep were escaped. Now it is a Regexp.
Probably they should change `mocha.grep(testName)` to
```
if (typeof mocha.fgrep === 'function')
    mocha.fgrep(testName); // since Mocha 3.0.0
else
    mocha.grep(testName); // prior Mocha 3.0.0
```

**Comment by Andreyul** [comment]
[Pull request](https://github.com/Microsoft/nodejstools/pull/1197) have been merged into NTVS.
