### ISSUE TITLE
Cyclic JSON Error when invoking Mocha 3.0.2 from express.js

### ISSUE THREAD

**Issue by genzoman** [mochajs/mocha#2437]
I've got a programmatic way to run mocha
```
var Mocha = require("mocha"),
  fs = require("fs"),
  path = require("path");
var Promise = require("bluebird");

var mocha = new Mocha();
mocha.addFile("./spec/spec.js")
module.exports = doMocha;
function doMocha() {

  var failures = [];

  return new Promise(resolve => {
    mocha.run()
      .on('test', function (test) {

      })
      .on('test end', function (test) {

      })
      .on('pass', function (test) {

      })
      .on('fail', function (test, err) {
        failures.push(test);
      })
      .on('end', function (results) {
        console.log("DONE")
        resolve(failures);
      });
  });
}
doMocha()
  .then(data=>{
    console.log(data);
  })
```
and if I run this from node, it prints out the JSON as expected, so I know the logic here is correct.
If I remove the actual invocation of doMocha, and instead try to call mocha from an express server.

```
app.get("/api/data", (req, res) => {
  runner()
    .then(data=>{
      res.send(data);
    });
});
```
I get the error Converting circular structure to JSON.  This only seems to happen if there are failures in the test suite.

**Comment by genzoman** [comment]
I was able to get around this(ish).  
```
function doMocha() {

  var failures = [];

  return new Promise(resolve => {
    mocha.run()
      .on('test', function (test) {

      })
      .on('test end', function (test) {

      })
      .on('pass', function (test) {

      })
      .on('fail', function (test, err) {
        failures.push({
          test: test.err,
          file: test.file
        });
      })
      .on('end', function (results) {
        console.log("DONE")
        resolve(Object.assign({},failures));
      });
  });
}
```
this worked, but when I tried to include the stack property, it threw.

**Comment by gurdiga** [comment]
@genzoman Could this be related to something like https://github.com/mochajs/mocha/issues/2433#issuecomment-239621095? 🤔

**Comment by genzoman** [comment]
@gurdiga I assume so, though this particular instance happens without using the JSON reporter (I'm not sure of the lifecycle of mocha, but I assume my error is happening before the output gets to the reporter).

**Comment by boneskull** [comment]
This isn't really a Mocha thing (since Express is stringifying the response), though the wisdom of using circular object structures is suspect.  Add [json-stringify-safe](https://npmjs.com/package/json-stringify-safe) to your project.
