### ISSUE TITLE
npm install produces unwanted .orig files in mocha lib directory.

### ISSUE THREAD

**Issue by bigtimecriminal** [mochajs/mocha#2446]
When I npm install mocha, I also receive half a dozen git .orig files in the lib/ directory, complete with git diffing markup.  Is there an error in mocha's current deployment to npm?

The files are:

runner.js.orig
runnable.js.orig
mocha.js.orig
suite.js.orig
test.js.orig
utils.js.orig

**Comment by boneskull** [comment]
huh.

**Comment by boneskull** [comment]
@bigtimecriminal nice catch.  not sure how that happened, but likely my fault.

**Comment by boneskull** [comment]
See npm/npm#13708

**Comment by boneskull** [comment]
There's nothing to be done about mocha@3.0.2.  If npm/npm#13708 is not merged & released before mocha@3.0.3 is to be published, then we should explicitly add `*.orig` to `.npmignore`.

**Comment by boneskull** [comment]
The fix in npm landed in v3.10.8.

**Comment by boneskull** [comment]
...which hasn't been published yet. :smile:

**Comment by boneskull** [comment]
actually, it has, just not `latest` tag.  so we're good.
