### ISSUE TITLE
Can't get relative path of tests

### ISSUE THREAD

**Issue by fgarcia** [mochajs/mocha#2449]
I can't seem to get a good relative path (to the project root) of failed tests.

Since I write tests next to my source folder, every failing tests reports back with something like:

```
      at Context.<anonymous> (spec.js:13:44)
```

Is it possible to get something more concrete with a longer path?

**Comment by boneskull** [comment]
How are you executing Mocha?

**Comment by fgarcia** [comment]
I just use the vanilla `./node_modules/./bin/mocha` called either directly from the command line or `npm`

I've seen this effect in tutorials like the react-redux-soundcloud one

https://github.com/rwieruch/react-redux-soundcloud/tree/master/base-init

That example has little code, much less than those boilerplates adding everything possible

**Comment by fgarcia** [comment]
looks like my problem was solved with the classic solution of re installing all npm modules
