### ISSUE TITLE
Question: Allow failures?

### ISSUE THREAD

**Issue by amilajack** [mochajs/mocha#2451]
Is there a way to allow the failure of specific tests but show that they are failing?

**Comment by boneskull** [comment]
By "allow" you mean what, exactly?

**Comment by amilajack** [comment]
Similar to allow_failures on travis:

https://docs.travis-ci.com/user/customizing-the-build#Rows-that-are-Allowed-to-Fail
https://www.google.com/search?q=travis+ci+allow+failures&oq=travis+ci+allow+failures&aqs=chrome..69i57.4573j0j7&sourceid=chrome&ie=UTF-8

**Comment by AnnieCyl** [comment]
Like jasmine, it has a "fail" function, 
```
describe("A spec using the fail function", function() {
  var foo = function(x, callBack) {
    if (x) {
      callBack();
    }
  };

  it("should not call the callBack", function() {
    foo(false, function() {
      **fail("Callback has been called");**
    });
  });
});
```

**Comment by amilajack** [comment]
Exactly!

**Comment by mlrawlings** [comment]
@boneskull This [section in the `ava` docs](https://github.com/avajs/ava#failing-tests) describes a huge benefit that comes with this: a PR with a failing test (but a failing test that doesn't break the build).

I'm currently using `it.skip` in a few cases where there are known bugs and we have a failing test case, but it's not a high enough priority for an immediate fix.  This doesn't actually run the failing test though and doesn't differentiate between an unwritten pending test and a known failing test.

It would be great to see something like:
```
441 passing (509ms)
3 pending
1 expected failing
```

**Comment by mlrawlings** [comment]
Also, I wouldn't be able to take this on immediately, but if you'd be willing to merge a PR that implemented this, I would be willing to work on this in the near future.

**Comment by kellyselden** [comment]
Here is a simplified workaround

```js
it.allowFail = (title, callback) => {
  it(title, function() {
    return Promise.resolve().then(() => {
      return callback.apply(this, arguments);
    }).catch(() => {
      this.skip();
    });
  });
};

it.allowFail('skip on error', function() {
  assert.ok(false);
});
```

or use it [here](https://github.com/kellyselden/mocha-helpers/pull/4) if you want.

**Comment by ssbarnea** [comment]
AFAIK skipping a test is not the same as ignoring its failure. Did something change since this old bug was closed?
