### ISSUE TITLE
es6 without babel

### ISSUE THREAD

**Issue by caperavensoftware** [mochajs/mocha#2455]
Are there any plans to start supporting es2015 code like import and export without the use of babel?

**Comment by ScottFreeCode** [comment]
That's entirely up to the environment in which Mocha is run. I believe the latest versions of Node support just about all of ES2015 except the `import`/`export` module syntax; I don't know if or when that syntax is expected to be added to Node. Mocha doesn't have much say in these features one way or the other; it doesn't add core JavaScript functionality itself (except by integration of transpilers, and then it's up to the transpiler), and won't be able to do anything to block them once they're available either.

**Comment by caperavensoftware** [comment]
ok so it's a node requirement then.
I am running the current latest version but the problems I am running into are in fact import and export. Thanks for the reply ScottFreeCode

**Comment by boneskull** [comment]
@caperavensoftware You'll need to transpile.  There are various ways to accomplish this.  You could do `babel-node /path/to/_mocha my-tests` or `mocha --require babel-register my-tests`, etc, etc

**Comment by SGD1953** [comment]
Is it worth considering to reopen this since [nodejs does now support imports](https://nodejs.org/dist/latest-v8.x/docs/api/esm.html)?

**Comment by boneskull** [comment]
@SGD1953 I'm not sure why this would need to be reopened if there's native support.  just use it

**Comment by boneskull** [comment]
I'm nearly certain we allow experimental flags to pass through the `mocha` executable; someone make a bug if it doesn't work

**Comment by SGD1953** [comment]
I opened #3006 for this, apparent the situation is a bit more nuanced.
