### ISSUE TITLE
process.stdout may not exist

### ISSUE THREAD

**Issue by pcfreak30** [mochajs/mocha#2459]
When using browserify, it uses https://github.com/defunctzombie/node-process/blob/master/browser.js But stdout is not shimmed apparently on purpose. Need to check for process.stdout in base reporter.

**Comment by pcfreak30** [comment]
Reference https://github.com/defunctzombie/node-process/issues/41

**Comment by boneskull** [comment]
@pcfreak30 What bug does this cause?

**Comment by boneskull** [comment]
@pcfreak30 Mocha shims `process.stdout` via the `browser-stdout` module.

**Comment by pcfreak30** [comment]
@boneskull i figured that out in the end. browserify seems to use node-process though.

Where though is https://gist.github.com/pcfreak30/cea969f1f6a3db67d296fbf7c4e4be0f created at? I can not find that bootstrap script.

**Comment by pcfreak30** [comment]
@boneskull As for bug, it crashes the web page as its accessing something thats not there. I was importing `mocha/lib/mocha` directly as well as I could not use the browserified version. So far I have got a working solution, but it took forever to figure it out.

**Comment by boneskull** [comment]
@pcfreak30 You're looking for `./browser-entry.js`.  See the `mocha.js` target in `Makefile`.

I will need more information about your bug.  It sounds like you're browserify-ing Mocha yourself?  What's the use case?

**Comment by pcfreak30** [comment]
@boneskull I could not get the prebuilt version of mocha working myself as a node module.Im using browserify, mocha, and phantomjs. I am not using bower for this.

**Comment by boneskull** [comment]
@pcfreak30 Can you supply more details of your setup (the actual scripts)?  I don't understand why you'd need to browserify Mocha.

**Comment by boneskull** [comment]
@pcfreak30 For reference, [here's how we do it](https://github.com/mochajs/mocha/blob/master/Makefile#L13)

**Comment by boneskull** [comment]
I don't understand why you need to browserify Mocha yourself.

**Comment by pcfreak30** [comment]
@boneskull Because i can't seem to build the non browserify version when importing it in es6.
