### ISSUE TITLE
using child_process.exec in test does not execute callback

### ISSUE THREAD

**Issue by mikeerickson** [mochajs/mocha#2461]
Config:

- Mocha 3.0.2
- Node 5.9.1
- OSX

I have a simple child_process.exec call as follows

```
    it.only('should use child process', () => {
        child_process.exec('npms search gulp --output --size 5', 'utf8', (err, stdout, stderr) => {
            let obj = JSON.parse(stdout)
            console.log(obj.length)
        })
    })
```

When the rest is run, nothing is output to console.

However, if I have the same code (minus the `it` block) outside of the `describe` block, it returns the correctly results and outputs info to console

```
        child_process.exec('npms search gulp --output --size 5', 'utf8', (err, stdout, stderr) => {
            let obj = JSON.parse(stdout)
            console.log(obj.length)
        })
```

I have also created a very basic call to `node` which does not work either

```
        child_process.exec('node test.js', 'utf8', (err, stdout, stderr) => {
            console.log(stdout)
        })
```

**Comment by mikeerickson** [comment]
FWIW, I have gotten past this issue.  All is working as expected

**Comment by gagan-bansal** [comment]
@mikeerickson I encountered same issue, how could you resolve it?

**Comment by felixfbecker** [comment]
@gagan-bansal Make sure you call the `done` callback

**Comment by gagan-bansal** [comment]
@felixfbecker Thanks for the response. Yes `done` should be called back and I find out from [here](http://stackoverflow.com/a/12580359/713573) that done should be passed in the function that is provided to mocha. It could be `it` also. Here is an example:

```javascript
it('test1', function(done) {
  fs.readFile('path-to-file', function(err, data) {
    if (err) throw err
    console.log(data)
    done() 
  })
})
```
