### ISSUE TITLE
TypeError: Cannot read property 'plugins' of undefined

### ISSUE THREAD

**Issue by prinspark** [mochajs/mocha#2466]
I use sample code to test a website,but got a type error of cannot read property,someone help?

const Browser = require('zombie');

// We're going to make requests to http://example.com/signup
// Which will be routed to our test server localhost:3000
//Browser.localhost('www.douban.com');
Browser.strictSSL = false;
Browser.loadCSS = false;
var domain = 'http://beijing.douban.com';

describe('User visits signup page', function() {

    const browser = new Browser();

    before(function() {
        return browser.visit(domain + '/');
    });

    describe('submits form', function() {

        before(function() {
            browser
                .fill('email',    'zombie@underworld.dead')
                .fill('password', 'eat-the-living');
            return browser.pressButton('Sign Me Up!');
        });

        it('should be successful', function() {
            browser.assert.success();
        });

        it('should see welcome page', function() {
            browser.assert.text('title', 'Welcome To Brains Depot');
        });
    });

});

**Comment by boneskull** [comment]
There is no `plugins` property in Mocha.  Whatever the problem is here, it's likely with Zombie...
