### ISSUE TITLE
node inspector

### ISSUE THREAD

**Issue by weepy** [mochajs/mocha#247]
Hi 

Is it possible for mocha to work with node inspector ? 

I tried with mocha -d, but this seemed to just give the node debug prompt.

weepy

**Comment by alexanderkartavtsev** [comment]
does anyone still experience this issue?
my configuration:
node-inspector: "0.12.8",
mocha: "2.4.5",
OS X: "10.11.5"

i'm running **BABEL_ENV=test node-debug mocha --opts content/test/mocha.opts**

mocha.opts is: 
`--recursive`
`--check-leaks`
`--require babel-core/register`
`--require content/test/mocha.setup.js`
`content/test/app`

setting the breakpoint on the last line of mocha script or a workaround suggested by @deitch don't work for me
