### ISSUE TITLE
mocha --help gets it's output cut off.

### ISSUE THREAD

**Issue by Jontem** [mochajs/mocha#2471]
Hi!

In my osx terminal i get the output of running `mocha --help` cut off.
![screen shot 2016-09-04 at 16 41 57](https://cloud.githubusercontent.com/assets/4803402/18231631/ce53ed90-72be-11e6-963b-b30978c5ceb8.png)

I've tested on windows command-line and it works there.

Node: 6.2.0
Mocha: 3.0.2

**Edit:** I upgraded to node 6.5.0. And it now seems to work.

**Comment by boneskull** [comment]
I can confirm this bug is present in Node.js 6.0.0 through 6.2.0.  Neither Node.js 5.12.0 nor 6.2.1 exhibit this behavior.  Whether or not we can do anything about it is anyone's guess.  Would like to know *why* this happens, at any rate...

**Comment by ISNIT0** [comment]
I'd imagine this is related to https://github.com/nodejs/node/issues/6297

Lots of packages seem to have had a similar problem.

UglifyJS fixed it as so: https://github.com/mishoo/UglifyJS2/pull/1061/files
I'm not sure if that's the kind of fix (slightly adhoc) that would be appropriate in Mocha, maybe someone who knows the code base better could check it out?

**Comment by boneskull** [comment]
could probably do that, yes

**Comment by boneskull** [comment]
I'm gonna call this one.  it's not worth bothering with; it affects a certain range of node v6 on certain environments, and has long since been fixed upstream.
