### ISSUE TITLE
npm installs version 3.0.2 by default

### ISSUE THREAD

**Issue by JuanCaicedo** [mochajs/mocha#2476]
If you currently run `$ npm install --save mocha`, it installs version 3.0.2. Given that this version is in pre-release beta, shouldn't version 2.5.3, be installed instead? I had this happen on accident and it gave me some very strange errors. I can report those errors in another issue 😃

**Comment by boneskull** [comment]
@JuanCaicedo 3.0.2 is not a pre-release; 3.0.0-2 is a pre-release.  There was no "GitHub" release crteated for 3.0.2 (until just a second ago)--but it is tagged--which may have contributed to the confusion.
