### ISSUE TITLE
Call done with string or error type argument support.

### ISSUE THREAD

**Issue by urosjarc** [mochajs/mocha#2482]
If done is invoked with string in argument, done function should throw error with argument from done.

This test:
```
it('should fail',function(done){
    done('Should not pass');
})
```
Should throw error:

```
Error: Should not pass
```

And not this error:
```
Error: done() invoked with non-Error: Should not pass
```

**Comment by boneskull** [comment]
@urosjarc I'm not sure what the problem is here?  You should be invoking `done()` with an `Error`.  A string is not an `Error`.

If you want this output:

```
Error: Should not pass
```

Do this instead:

```js
it('should fail',function(done){
    done(new Error('Should not pass'));
})
```

**Comment by urosjarc** [comment]
Yea I'm fully aware that done should be called with error type, but done should recognize string type and throw error like this:
```
function done(error){
    if(typeof error == 'string') throw new Error(error);
    else throw error;
}
```

**Comment by boneskull** [comment]
Why? What problem is the current behavior causing?

Rather than silently coercing into an `Error`, the current behavior educates the user about conventional usage of node-style callbacks.
