### ISSUE TITLE
audit slow tests

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2483]
some tests may need new `slow` values (e.g. `this.slow(1000);`) since they consistently run at a certain speed.
1.  run all mocha tests
2.  find the ones reporting slowness
3.  increase this value to something reasonable if the test can't be made faster

**Comment by coderbyheart** [comment]
What's the difference to #2597?

**Comment by Bamieh** [comment]
Mocha has this feature now, reopen if i am misunderstanding this issue.
