### ISSUE TITLE
use semistandard

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2490]
We have some code standards in place, but not enough.  We have disabled many warnings which we probably shouldn't have, to avoid changing too much code when we picked up ESLint originally.  I'd also prefer to use a widely-used style instead of a custom style.

- Install eslint-semistandard-config and all necessary dependencies
- Update `.eslintrc` to be just `{"extends": "semistandard"}`
- `eslint --fix` everything
- Manually fix everything else

If anyone disagrees, please let me know.  Unless that disagreement involves "semicolons"; if so, please keep it to yourself.  :smile:

**Comment by Munter** [comment]
Great move! 👍
