### ISSUE TITLE
The 'it' function description text don't display

### ISSUE THREAD

**Issue by zhanba** [mochajs/mocha#2492]
![image](https://cloud.githubusercontent.com/assets/4224253/18627918/4e98b29c-7e90-11e6-9c52-80a42527e479.png)
My system is  Windows 10 Version 1607 X64. In travis CI, the output infomation has no problem.

**Comment by Munter** [comment]
If you copy/paste that whole block, does the text appear? Would be nice to know if this is a bad coloring issue, of if the text actually isn't rendered at all

**Comment by zhanba** [comment]
Yes, it's a coloring issue! I paste the the whole block to text editor, and the text appear. 
Then I run my project in another win10 computer, the output is complete, and color is normal. So it maybe my computer's problem, I have changed the windwos CMD setting. I tried to set it back, it just don't work.

**Comment by boneskull** [comment]
Modify terminal colors/contrast
