### ISSUE TITLE
Slack Channel

### ISSUE THREAD

**Issue by WillLuce** [mochajs/mocha#2500]
Is there a Mocha slack channel? If not, would anyone be opposed to me starting one? Would you guys rather see a Mocha channel or a JS Testing Stack channel?

**Comment by dasilvacontin** [comment]
@WillLuce What's wrong with our Gitter channel? (2nd badge in README)

**Comment by WillLuce** [comment]
Didn't see that. Thanks.

**Comment by dasilvacontin** [comment]
Yep, gitter branding for the badge is pretty bad. We could use something better.

**Comment by WillLuce** [comment]
Maybe put it in the Links or a communication section?
