### ISSUE TITLE
Why in callback always pass, even obvious a failed case

### ISSUE THREAD

**Issue by GongDexing** [mochajs/mocha#2501]
```js
	describe('#find', () => {
		it('test have email "test20160925@gmail.com"', () => {
			db.findOne('tbl_user', ['email'], {name: 'test'}, (err, result) => {
				if(err) throw err;
				expect(result[0].email).to.be.equal('test20160925@test.com');
				done();
			});
		});
	});
```
>
    #find
      √ test have email "test20160925@gmail.com"

**Comment by Munter** [comment]
You are running the test synchronously because you are not declaring the done callback argument. So the test immediately finishes with no exceptions thrown; success.

Declare done in the arguments for the test callback
