### ISSUE TITLE
Promise in beforeEach not working

### ISSUE THREAD

**Issue by thomasthiebaud** [mochajs/mocha#2506]
I have this kind of code using mocha where all the functions inside database return a promise.

```
  beforeEach(function () {
    return database.truncate();
  });

  describe('customers', function () {
    it('should create a default customer', function () {
      return database.addDefaultCustomer();
    });
  });

  describe('users', function () {
    it('should create a default user for the default customer', function () {
      return database.addDefaultCustomer()
        .then(() => database.addDefaultUser());
    });
  });
```

This code is not working (the `database.truncate` is not called as it is expected to be, so If I try to add the same customer again, I have a `ConflicError`), but if I switch to something like

```
describe('customers', function () {
  it('should create a default customer', function () {
    return database.truncate()
      .then(() => database.addDefaultCustomer());
  });
});
```

it works. Is it not supposed to be the same thing ? Mocha is not supposed to go into the tests if the `beforeEach` hook does not resolve, right ?

Did I miss something or is it a bug ?

**Comment by boneskull** [comment]
I have some questions:

- Is the `beforeEach()` top-level?  Is it in a `describe` block?
- Is this all the same file?
- Are you running in the browser?
- What options / flags are you running with?
- Have you ran your test with a debugger?  Can you assert that the `beforeEach` hook is never called?

**Comment by thomasthiebaud** [comment]
- The `beforeEach()` is in describe block
- This is all the same file
- It's not running in the browser
- I'm running it with `gulp-mocha` without special options
- With a debugger the `beforeEach` is called. But if the `beforeEach` is called, why is the `truncate` function not working ? It is working outside the `beforeEach` function

**Comment by thomasthiebaud** [comment]
Ok the problem came from the library, so `mocha` is working well. Thanks a lot for your help.
