### ISSUE TITLE
Babel is not defined

### ISSUE THREAD

**Issue by peteringram0** [mochajs/mocha#2508]
I am running the following

`````
./node_modules/mocha/bin/mocha --timeout 30000 --compilers js:babel-register --require babel-polyfill ./tests/**/*.test.js

`````

My test has the following imports

`````

import System from 'systemjs';
import '../config.js';

import 'babel-polyfill'


import 'jsdom-global/register'

var chai = require('chai');
var spies = require('chai-spies');
var expect = chai.expect;
var assert = require('chai').assert;

chai.use(spies);


var jsdom = require('mocha-jsdom');
`````

When using 'jsdom-global/register' i am getting the error 'SystemJS babel is not defined'

Has anyone seen this before? 

Thanks,

**Comment by boneskull** [comment]
you might want to file this ticket in either the `mocha-jsdom` repo or the `jsdom-global` repo. or `systemjs`.  either way probably doesn't have much to do with mocha..
