### ISSUE TITLE
detecting the active mocha-ui

### ISSUE THREAD

**Issue by osher** [mochajs/mocha#2510]
Hi, 
I'm working on a utilizer that works with a custom mocha-ui, I want to think of a way to help it serve users of the standard bdd ui.
For this I need to detect the current active mocha-ui and decide how to operate.
More specifically, if I need to return an object for `ui-exports` OR use `describe/it`.

(even more specific, see the following branch: https://github.com/osher/mocha-ui-exports-request/tree/dev-ui-bdd)

The obvious thing I would fallback to do is to check process.argv for --ui, and fallback to trying to read `path.join(process.cwd(), 'test', 'mocha.opts')`  looking `--ui` flag there, and default to `bdd`.

But I'm here because I hope there's a standard API to accomplish this task that somebody here can point me to...

If there is no such API and the proposed strategy is not guaranteed to work because of whatever reason I'd be very happy to hear about it now.

The last resort will be to ask the user to call an *additional* method, which is not very pretty and less than the level of service I aspire to give my users...

Any advise will be appreciated...

**Comment by boneskull** [comment]
if you're running in node, most straightforward would be checking `process.argv` for `--ui`.  if it's not set, assume `bdd`.

**Comment by osher** [comment]
what about --ui expressed in `mocha.opts` ?

**Comment by osher** [comment]
Aha. I get it. it's loaded on argv of `bin/_mocha` by `bin/mocha`...
