### ISSUE TITLE
Option to disable diff

### ISSUE THREAD

**Issue by pensierinmusica** [mochajs/mocha#2514]
Hi,

We currently have a use case where we're testing a large array for deep equality against something returned from a function. The problem is that when the test fails the output in the reporter is very long and clogs all the tests.

Is there any option to disable the diff? In this case it would be very useful, since we don't really need to know where the output is different from the expected result, but just if it's deeply equal to it or not.

Thanks!

**Comment by boneskull** [comment]
No, there's nothing like this
