### ISSUE TITLE
multiple compilers for one extension

### ISSUE THREAD

**Issue by Mosho1** [mochajs/mocha#2516]
Is there a way to apply multiple compilers to an extension (karma allows this via webpack, for example). The use case is transpiling TypeScript to ES6 and then using babel to transpile to ES5.

**Comment by alveflo** [comment]
@Mosho1 did you solve this one? I'm facing the same issue here...

**Comment by Mosho1** [comment]
@alveflo I ended up writing my own "compiler". It's just something that registers the extension in `require.extensions`, which is what all the typescript babel etc. compilers do.
