### ISSUE TITLE
Consider using flagged-respawn

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mocha#2517]
From `bin/mocha`:

``` js
/**
 * This tiny wrapper file checks for known node flags and appends them
 * when found, before invoking the "real" _mocha(1) executable.
 */
```

It appears likely that we could merge `bin/_mocha` into this file (and probably simplify the code currently in `bin/mocha`) using https://www.npmjs.com/package/flagged-respawn

May need to consider whether removing the direct `_mocha` executable would be a breaking change.

**Comment by boneskull** [comment]
> May need to consider whether removing the direct _mocha executable would be a breaking change.

Fully *removing* it would be a breaking change--tools like Istanbul depend on it--but if it was just an alias, it *might* not necessitate a major:

```js
// _mocha
require('./mocha');
```

Needs more investigation.

**Comment by ScottFreeCode** [comment]
As a potential alternative, I hear you can now `npx -n --use_strict mocha`, which starts to sound not too bad compared to `node_modules/.bin/mocha --use_strict` or even `mocha --use_strict` -- it's far better than `node --use_strict node_modules/mocha/bin/mocha` at least. Plus if we relied on that instead of Mocha respawning itself, we wouldn't have to update as Node flags are added. But there's old-Node compatibility to consider: https://github.com/zkat/npx/issues/30 And, perhaps most critically, I don't think you could put Node flags (of which at least `--use_strict` is useful... perhaps so useful there's some other config method that could activate it?...) into `mocha.opts` that way.

**Comment by juergba** [comment]
Since v6.2.0 we are aiming to avoid child-processes and do respawn only when Node flags are used or the `esm` module is required.

Node flags are detected by `process.allowedNodeEnvironmentFlags` or its polyfil `node-environment-flags`.
