### ISSUE TITLE
Paranthesis in it name makes unit test pass

### ISSUE THREAD

**Issue by Laro88** [mochajs/mocha#2518]
This might be related to Microsofts (NTVS / VS2015) test inspector, however I find the behaviour a bit worrying.
I have some unit tests and I found a couple of tests that certainly should fail. However when I have a set of matching paranthesis inside a guaranteed fail such as around **published** in the code snippet then the test passes. Removing both or just one makes the test fail - strict mode on thisisnotdefined

I am on node 6.7, Windows platform, mocha and others up to date.

Is there something that I have overlooked completely?
```
it('mqtt publish to mosca.on(published)', function (done) {
        thisisnotdefined
        this.timeout(5000);

        testconfig.moscaserver.on('published', function (packet, client) {
            assert.equal('c', packet.payload);
            done();
        });

        var mqttclient;
        mqttclient = mqtt.connect('mqtt://localhost');
        
        mqttclient.on('connect', function (pkg) {
            mqttclient.publish('a', 'b');
        })
    });
```

**Comment by ScottFreeCode** [comment]
If you run just Mocha from the commandline does the issue still occur?

And is it being labelled as "passed" or merely not labelled as "failed"? This sounds a little like some issues we've had with regex escaping in filtering tests by title.

**Comment by boneskull** [comment]
I can't reproduce this on the command line.  Not sure what VS2015 is up to here.  If you can dig up the command it's executing to run Mocha, that would be helpful.  Otherwise, you might want to file a ticket with the VS2015 project, if that is even possible.

**Comment by Laro88** [comment]
This is a VS2015 issue, NOT a mocha thing. running in command line fails as expected.
My VS2015 goes green on everything when there is a matching set of paranthesis in the descrive name as below, commandline fails as expected.
```
it('Test 2(ok)', function(d) {
        assert.ok(1 === 1, "This shouldn't fail");
        //assert.ok(false, "This should fail");
        dancinghamstercrash
        d();
    })
```
