### ISSUE TITLE
"compilers" does not compile fork scripts

### ISSUE THREAD

**Issue by maxcnunes** [mochajs/mocha#2519]
Running a project that depend on some features not available in the latest Node js yet such as `async await` I use `--compilers js:babel-register` on mocha to compile my code during the tests. This works really well in most cases. But this does not work if I have a fork process which also use `async`.

If I run `babel-node` over the main script it will by default compile the fork scripts as well.
But running mocha with `--compilers js:babel-register` it does not happen. I was expecting it would work the same way `babel-node` does.

Here is the a project to help reproduce the problem: https://github.com/maxcnunes/problem-fork-with-babel-node

**Comment by boneskull** [comment]
(`--compilers` isn't needed here; you can use `--require babel-register`; see [docs](https://mochajs.org/#about-babel)

`process.execPath` must be `babel-node` for any forked process to run `babel-node`. 

two potential workarounds off the top of my head:

- run Mocha with `babel-node /path/to/mocha` (the `mocha` executable forks the `_mocha` executable; it *should* retain `process.execPath`, but if it doesn't, `babel-node _mocha` would work instead)
- in your test or test fixture, manually set `process.execPath` to `/path/to/babel-node` (though this may have unintended consequences)

related: #2517

**Comment by maxcnunes** [comment]
Thanks @boneskull. From all your suggestions the only one I had not tried before was  `babel-node /path/to/mocha`. Which by the way is the only one works :smile: 

So running `babel-node node_modules/mocha/bin/_mocha test.js` applies by default the compiler to the child process.

**Comment by boneskull** [comment]
as I understand `babel-node` is especially slow versus other methods. have you found this to be true?
