### ISSUE TITLE
async-only should apply to test setup and tear down routines (or a similar option should be provided)

### ISSUE THREAD

**Issue by bpytlik** [mochajs/mocha#2539]
async-only doesn't apply to `before` `beforeAll` etc.., only test. It would be nice for it either to apply across the board, or for their to be a different option which applies the same constraints across the board.

**Comment by boneskull** [comment]
This makes sense, but I feel a bit like the ship has sailed.  Changing this would necessitate a major release and probably break a fair share of CI builds.  Unless there's more interest, I'm not sure that's worth the trouble.

**Comment by tianchuanting** [comment]
Is there a way to handle async after() right now? Say, if I need to reset the database before moving to the next test, and the reset is done asynchronously?

**Comment by bpytlik** [comment]
@boneskull I agree changing the behavior of the tag would be a major release change. Adding a different option (async-setup-only?) to enforce the behavior on setup and teardown methods would not be a breaking change.
