### ISSUE TITLE
ignore-promises option would be useful

### ISSUE THREAD

**Issue by bpytlik** [mochajs/mocha#2540]
For those of us who agree with issue #2511, having an option to ignore the promises that are returned from a test would be useful. It would allow an easy way to shift to mocha 3.X without having to touch every test case in a test suite. It would also act as a bridge until #2509 is finished.

**Comment by boneskull** [comment]
I get what you're saying, but the overhead of adding this, then deprecating it once it's useless, then breaking backwards compat *just to get rid of it* isn't really worth it for the project.

**Comment by Munter** [comment]
It would be more useful if someone wrote a code mod to let people migrate their code away from implicit returned promises where they didn't mean it

**Comment by bpytlik** [comment]
@boneskull That's fine. We'll just stick on mocha 2.5.X for now. If this gets cleaned up in the future where we don't have to touch nearly every test in our test suite, then maybe we'll consider moving forward. If it doesn't, then mocha might not be for us anymore. (Which is fine, it's not like you owe us anything. I just want to make it clear that this is something that would cause us to reevaluate our use of mocha.)

**Comment by bpytlik** [comment]
I guess I could just make a fork of mocha 3.X too and add the flag. I can't imagine it's hard to actually make the change we want since it amounts to just tossing promises on the ground. Maybe I'll look into it if I have spare time.

**Comment by boneskull** [comment]
That might be best. We are planning a reasonable solution to this by respecting both returned Promises and the `done` call, but it's non-trivial--and I'm not sure where that PR will come from. Other workarounds exist, but none don't involve changing tests. FWIW, @munter's idea would be a one-time deal, and others could probably use it. This would absolve you from maintaining the fork.

**Comment by boneskull** [comment]
@bpytlik also, if #2511 is an actual bug (likely), then there's no reason why it couldn't be fixed.  I don't detect any disagreement about that issue in particular.
