### ISSUE TITLE
Expand CONTRIBUTING.md

### ISSUE THREAD

**Issue by CapacitorSet** [mochajs/mocha#2542]
CONTRIBUTING.md lacks some information for contributors. For example, [you shouldn't push changes to `mocha.js`](https://github.com/mochajs/mocha/pull/2536#discussion_r83543557); I suspect there are more similar gotchas that contributors should be aware of.

**Comment by boneskull** [comment]
yes, indeed. This should all get documented as our contribution guidelines are adjusted under the JS foundation.
