### ISSUE TITLE
Test case skip()ed, beforeEach() hook still executed, afterEach() missed

### ISSUE THREAD

**Issue by s100** [mochajs/mocha#2546]
This with Mocha 3.1.2. Source test file:

``` javascript
"use strict";
describe('outer', function() {

  beforeEach(function() {
    console.log("A");
    this.skip();
  });

  describe('inner', function() {
    beforeEach(function() {
      console.log("B");
    });

    it('test case', function() {
      console.log("C");
    });

    afterEach(function() {
      console.log("Y");
    });
  });

  afterEach(function() {
    console.log("Z");
  });
});
```

Expected output: either "B" **and** "Y" should be printed, or neither "B" **nor** "Y" should be printed.

Actual output: "B" is printed, but not "Y":

```
  outer
    inner
A
B
      - test case


  0 passing (11ms)
  1 pending
```

In general,

* If I call `skip()`, then I would not expect that inner `beforeEach` blocks would be executed.
* If a `beforeEach` block is executed, then the corresponding `afterEach` blocks should also be executed, for symmetry.

**Comment by ORESoftware** [comment]
I think the inner beforeEach will always run unless you call

```
 it.skip('test case', function() {
      console.log("C");
    });
```

the `this.skip()` functionality is fundamentally different than `it.skip` etc, if you want to know why, I can explain more. It's merely bad naming on the part of Mocha authors, I think.

I don't it's well specified or understand what will happen if you call this.skip() inside a hook. Ideally it would be named, this.continue() or something like that, because all it means is that "we are done here" let's move to the next item.

**Comment by nullin** [comment]
Looks like a dup of #2286. I'll be great to get #2623 merged as that might solve this too.

**Comment by philipwalton** [comment]
This is an issue for several projects I work on, so I'd like to see it stay open.

**Comment by philipwalton** [comment]
Looks like this issue might be related to this line of code:
https://github.com/mochajs/mocha/blob/ade8b90a46c641345b67c7979f855bcfbda900d5/lib/runner.js#L671-L673

Which I discovered when reporting this on a related issue here: https://github.com/mochajs/mocha/pull/2571#issuecomment-477407091

Commenting out the above code makes this work as expect, but I'm not sure if that code is needed for other features.

**Comment by plroebuck** [comment]
@juergba could you take a look at this and provide your opinion?

**Comment by juergba** [comment]
@plroebuck see above, I have a PR pending on this.

> Commenting out the above code makes this work as expected

Yes, everybody has his own expectations, so first you would have to define/agree on a hook pattern before changing the code.

**Comment by philipwalton** [comment]
I think most people assume that, if their `beforeEach()` hook runs, then their `afterEach()` hook should also run.

In many cases tests will error if a `beforeEach()` hook runs and then it runs again without the `afterEach()` hook running (e.g. stubbing methods and then re-stubbing before unstubbing). This is the case with me, and mocha's current behavior means I have to do all my test reseting in **both** `beforeEach()` and `afterEach()` hooks, just in case.

**Comment by plroebuck** [comment]
@philipwalton see mochajs/mocha#3740. We have _many_ identified issues, but it's not as trivial to determine the ramifications of proposed changes against a myriad of possible user settings and configurations (e.g., should it _still_ run "afterEach" if test fails when `--bail` given).
