### ISSUE TITLE
npm test aways fails

### ISSUE THREAD

**Issue by kauegimenes** [mochajs/mocha#2547]
OS: Mac
npm: 3.10.8
node: 6.8.1
mocha: 3.1.2

package.json scripts:
`"scripts": {
    "test": "mocha tests/**/*.js"
  },`

output:
```
$ npm test

> project@1.0.0 test /Users/user/project
> mocha tests/**/*.js
  testA File
    ✓ First it()
    ✓ Second it()
npm ERR! Test failed.  See above for more details.
```

folder structure:

- tests/
    - fristFolder/
        - testA.js (only the first one shows in the console)
        - testB.js

what i tried: 
- use `--reporter spec` on the npm test script

**Comment by ScottFreeCode** [comment]
What are the contents of testA.js and testB.js?

If you run `mocha tests/**/*.js` directly and then `echo $?` what number do you get?

**Comment by vivganes** [comment]
@kauegimenes My guess is that the error is in the `@after` section in `testA.js` or it could be there in `testB.js` too. It would be easy to debug if you post the files and logs as asked by @ScottFreeCode

**Comment by kauegimenes** [comment]
@vivganes @ScottFreeCode The problem fixed itself, sorry i was unable to share more datails on that happend.
