### ISSUE TITLE
Explodes on ES6 default parameters

### ISSUE THREAD

**Issue by Cazra** [mochajs/mocha#2548]
Mocha is having trouble when it encounters ES6 default parameters being given to functions, even if it is encountered in a depency node module. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

E.g.:

```
constructor(name, hostname='localhost') {
    this._name = name;
    this._hostname = hostname;
    this._openChannels = {};
}
```

In the console, it gives a message like this:

```
/path/to/src/index.js:44
  constructor(name, hostname='localhost') {
                            ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
...
```

**Comment by ScottFreeCode** [comment]
I tried writing a test that uses a function with a default parameter and it worked fine; can you provide a complete (but minimal) example of code and Mocha command(s) that will trigger this?

**Comment by Cazra** [comment]
Sure, here's a really simple Mocha code example that triggers it: 

```
'use strict';

const assert = require('chai').assert;

function getAnswer(arg=42) {
  return arg;
}

describe('test', () => {
  it('do the thing', () => {
    let answer = getAnswer();
    assert.equal(answer, 42);
  });
});
```

I'm using Node v4.0.0.

**Comment by ScottFreeCode** [comment]
Looks like this was only added in Node 6: http://node.green/#default-function-parameters

You can also confirm this by trying using a function with default parameters in Node outside of Mocha, I think; let me know if it does work there after all and I'll help dig into it further.
