### ISSUE TITLE
want to be able to force process.exit(0)

### ISSUE THREAD

**Issue by mikael-entefy** [mochajs/mocha#2549]
The mocha --watch switch isn't sufficient for the watching that I need, so I'm using nodemon.
However, nodemon exits if the spawned processes exit code is non-zero.

I would like some way to force the exit code from mocha to be 0.

Maybe a --clean-exit switch.

I'm happy to do a PR for this, but it's a feature not a bug so wanted to talk about it first.

**Comment by boneskull** [comment]
`--no-exit`

**Comment by mikael-entefy** [comment]
Awesome, thanks.
