### ISSUE TITLE
Allow to customize ignored files?

### ISSUE THREAD

**Issue by laggingreflex** [mochajs/mocha#2554]
When in `--watch` mode, it currently only ignores `node_modules` and `.git` by default. I would like to add other folders such as `dist`. Is it possible to customize ignored files? If not please consider it. It takes way too much resources at initial load time going through setting up monitors for unnecessary files.

**Comment by laggingreflex** [comment]
Temporary solution: patching [`utils.files`](../blob/master/lib/utils.js#L245) in a `--require`
```
const files = utils.files;
utils.files = (...args) => files(...args).filter((path) => !path.match(
  /node_modules|dist|vendor/
));
```

**Comment by ScottFreeCode** [comment]
We have a couple issues about ignoring files (#1577 and #2036) but as far as I see the last one about doing it with `--watch` is #909. For better or for worse, you're not likely to get a different answer now than then -- we still want to replace `--watch` with packages like Chokidar (see #1780), but to get the same speed we're going to need to fix the programmatic API.

**Comment by boneskull** [comment]
closing as dupe in lieu of several other tickets mentioned above
