### ISSUE TITLE
I have asserts and sometimes errors in promises, but all tests passing! Why asserts in promises does not count as tests?

### ISSUE THREAD

**Issue by idchlife** [mochajs/mocha#2557]
Using mocha for typescript tests

![image](https://cloud.githubusercontent.com/assets/4563032/19776640/90d5743c-9c7d-11e6-8224-8fa3c4dbfe10.png)

Errors like field is undefined (runtime error), or assert is failed.

**Comment by ORESoftware** [comment]
I think adding a code example is the first thing people will ask for

**Comment by ScottFreeCode** [comment]
Asserts work by throwing exceptions; Mocha doesn't actually know about the asserts, it just catches the exceptions and uses their info for the test failure. Exceptions inside a promise turn into promise rejections. Mocha can't know about those if you're not returning the promise -- in fact, it can't even know to wait for the promise code to complete in that case. But if you return the promise Mocha will wait for it and detect those rejections as test failures.

The relevant section in the documentation is here, for what it's worth: https://mochajs.org/#working-with-promises Although you don't generally need to know about the `done` callback if you're using promises, as returning the promise is usually the simpler alternative.

**Comment by dasilvacontin** [comment]
It sometimes feels as if enforcing the usage of `done` when a `Promise` is not returned would help people.

I'm going to start labeling common mistakes, so we can see the bigger picture whenever we need to.

**Comment by idchlife** [comment]
Yep, **returning promise** it 'it' do the trick! Mocha detects all fails in then() and test failes! Thank you.
