### ISSUE TITLE
Consider clarifying `--recursive` doc

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mocha#2564]
As I understand it, `--recursive` has an effect roughly equivalent to changing `path/to/directory` into `path/to/directory/**/*.js`. In any case, however, people are occassionally confused expecting it to somehow complement globbing rather than act as an alternative to globbing -- I suspect that some people expect it to turn `*.js` or `*.spec.js` into `**/*.js` and `**/*.spec.js` (respectively), which it doesn't in fact. The current documentation, as far as I've found, is vague enough to justify the misunderstanding.

We probably should make sure the documentation for this option, both on the commandline and on the website, briefly notes both what exactly it does and its relationship to globbing, preferably with a minimal example.

**Comment by Bamieh** [comment]
I believe recursive is well documented on the website now
