### ISSUE TITLE
Add a command line option to filter only specific test description

### ISSUE THREAD

**Issue by pmoleri** [mochajs/mocha#2565]
This is a _feature request_ to add a command line option able to *filter tests matching a specific description*. Similar to `.only()` but from command line.

e.g.
```
describe('Test', function () {
  describe('.clone()', function () {
    ...
    it('should copy the title', function () {
      this._test.clone().title.should.equal('To be cloned');
    });
```

If this test is failing, I would get this report:
```
 Test
   .clone()
    1) should copy the title

  ...
  1 failing

  1) Test .clone() should copy the title
```

Now, let's assume the requested option is called `filter`.
Then if I want to re-run only that test, I would do it from command line like this:
`mocha --filter "Test .clone() should copy the title"`

And this should behave exactly like a `it.only()` on that test.

Some additional proposed details:
- A plain text and a regexp alternative (e.g; `--filter` & `--rfilter`)
- Plain text should match if the string is contained in the test full description
- Regex can be used to match full description unsing `^...$`
- The match can be at any part, so --filter ".clone()" should run everything under `describe(' .clone()', ...)`

**Comment by ScottFreeCode** [comment]
Mocha [already has this](https://mochajs.org/#g---grep-pattern) (including [literal and inverted variants](https://mochajs.org/#usage), and [equivalent browser commands](https://mochajs.org/#grep))

**Comment by pmoleri** [comment]
I see that now. I had totally misunderstood the usage of grep. Somehow I thought it operated on filenames not test descriptions.
Sorry for the noise.

**Comment by ScottFreeCode** [comment]
No problem! Now that you mention it, we could probably improve the commandline documentation a little to make that obvious -- say, add "with description" before "matching"/"contains".
