### ISSUE TITLE
Explicitly disable cursor manipulation

### ISSUE THREAD

**Issue by diversario** [mochajs/mocha#2573]
I know that cursor manipulation is disabled when output is going to a non-tty output but sometimes that check isn't enough – for example, running tests in Jenkins yields an output file that has control characters and is difficult to parse and it looks like a mess:
![image](https://cloud.githubusercontent.com/assets/355800/20017271/149ba11c-a280-11e6-8bb9-4330f5cbab82.png)

In this case, each test name is printed twice and they have leading control chars.

It would be good to have a reporter option to disable such output and print lines in their final form.

**Comment by outsideris** [comment]
It's too old issue, but I don't understand what is the problem.
Please reopen if you still have the problem.
