### ISSUE TITLE
BeforeEach inside Describe

### ISSUE THREAD

**Issue by heynemann** [mochajs/mocha#2574]
I'm not sure if my case is actually a bug or if I'm not understanding correctly how to use beforeEach.

I have a `common.js` file with:

```
describe('API', function () {
  console.log("Common - Describe")
  beforeEach(async () => {
    console.log("Common - Before")
  })
})
```

Then in my test file I have:

```
require ('./common')

describe.only('API', function () {
  it('should do something', async () => {
    console.log("it")
  })
  // many more "it"s
})
```

I only get logs for "Common - Describe" and "it".  The beforeEach never gets called.

Any ideas on what I'm doing wrong?

**Comment by ORESoftware** [comment]
Mocha uses a stack data structure to register all API calls.

In order to achieve what you want, you have to do this instead:


// common.js
  beforeEach(async () => {
    console.log("Common - Before")
  })

require ('./common'); // requires the above code

describe.only('API', function () {
  it('should do something', async () => {
    console.log("it")
  })
  // many more "it"s
})


otherwise, the beforeEach won't get applied because the hook is not "at the right level of the stack".

**Comment by heynemann** [comment]
The issue with that is that I have 3 different major "common.js" files for three different modules of my app. I can't have all three execute before each test.  That's why I need to include the describe in the common.js.

I have a extensions module for common code, a worker module for the worker of my app and an api module for the rest api. Each has it's common.js for test setup.

I can't have the worker beforeEach happen in each of the tests of the API.

What was happening is that they were accumulating: the API only ran the API common. The extensions ran both the API and extensions. The worker ran all three before each test.

**Comment by ORESoftware** [comment]
Yep, this is why Mocha has problems IMO.  Let me try to solve your issue though. 

```js
describe(1, function(){
 
    require('beforeEach1');   // if you load it here, then he beforeEach will only apply to registered calls inside this describe block

   // do your thing;
})


describe(2, function(){
 
    require('beforeEach2');   // ditto above

   // do your thing;
})


describe(3, function(){
 
    require('beforeEach3');  // ditto above

   // do your thing;
})
```

that should solve your problem

**Comment by heynemann** [comment]
Thanks! That was very helpful!

**Comment by ORESoftware** [comment]
no problem amigo

**Comment by boneskull** [comment]
@ORESoftware Thanks for helping @heynemann.  

While this is appreciated, what *isn't* appreciated is your history of unproductive commentary on Mocha and its authors / maintainers.  Constructive criticism is welcome, but your criticism is seldom of this variety.

It's becoming a distraction to not just me, but other maintainers.  You will be banned from the `mochajs` org (and this issue tracker) if we see more of it.  Thanks!

**Comment by ORESoftware** [comment]
@boneskull no comment
