### ISSUE TITLE
deprecate karma-no-mocha

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2583]
after next release, deprecate karma-no-mocha (and remove the repo?)

**Comment by boneskull** [comment]
okay, it's deprecated.  I'm not sure if it's safe to remove the repo.

**Comment by ScottFreeCode** [comment]
I'd assume the repo is needed for Bower but not for NPM? In which case, if we don't support testing Mocha itself via Bower instead of NPM, it would be safe to remove?

**Comment by boneskull** [comment]
The repo isn't needed for anything, I think.  

The only issue (afaik) would be that the repository link in npm is dead.  This would show on npmjs.com, and attempting to open the repo via `npm repo karma-no-mocha` would result in a 404.

**Comment by ScottFreeCode** [comment]
> The only issue (afaik) would be that the repository link in npm is dead. This would show on npmjs.com, and attempting to open the repo via  npm repo karma-no-mocha  would result in a 404.

I doubt that would be an issue in practice, considering it's deprecated and points potential users to `karma-mocha` instead, and that anyone who really wants to see what was different about the code can look at the code in NPM and compare it to versions of `karma-mocha` from the same time. At worst, it might look bad -- but the fork has no reputation worth upholding. Right?
