### ISSUE TITLE
BUG/FEAT: Dynamic title does NOT change, when set during setup-hook.

### ISSUE THREAD

**Issue by evandenrijd** [mochajs/mocha#2589]
I have a simple gist with output commented:

```javascript
const expect = require('expect')

describe('dynamic tests', () => {
  const c = 1
  let s

  before('setup', () => {
    s = 1
    expect(s).toBe(1)
  })

  describe('dynamic title', () => {
    it(`working with const: '${c}'`, () => {
      expect(c).toBe(1)
    })
    it(`not working when set during setup: '${s}'`, () => {
      expect(s).toBe(1)
    })
    it(`check title of the test, first OK, second NOT`)
  })

})

//mocha --require babel-register mocha_test.tests.js6
//
// dynamic tests
//   dynamic title
//     ✓ working with const: '1'
//     ✓ not working when set during setup: 'undefined'
//     - check title of the test, first OK, second NOT
//
// 2 passing (54ms)
// 1 pending
```

Or am I missing some feature?

I use the latest mocha 3.1.2 and babel-register 6.18.0.

Thanks

**Comment by ScottFreeCode** [comment]
This is expected/intended. Mocha does not run any hooks (`before` et al.) until after it has run all the `describe`/suite callbacks to find out what all the hooks and tests are. The hooks are only for setting up and tearing down the environment for the tests, not for helping define the tests. You can dynamically generate test names or even entire tests, but not using stuff from in the hooks.

**Comment by ScottFreeCode** [comment]
This might be X/Y Problem speculation on my part, but it's also worth noting: if you need to do something asynchronous in the process of dynamically defining the tests, you can use the [delay](https://mochajs.org/#delayed-root-suite) option to allow asynchronous test definition calling `run()` when the tests have been defined and are ready to run. (One thing to note in regard to this is that suites with content that is defined in an asynchronous callback/action must themselves be defined in the same asynchronous section; e.g. it does not work to:
```js
describe("suite", function() {
  setTimeout(function() {
    it("test", function() {
      // test code here
    })
    run()
  }, 500)
})
```
...but it does work to:

```js
setTimeout(function() {
  describe("suite", function() {
    it("test", function() {
      // test code here
    })
  })
  run()
}, 500)
```
Obviously, both these examples use `setTimeout` for sake of focusing on where the `describe` goes and not on the nature of the asynchronous action, but the same principle would apply to any asynchronous callback, defining tests in a promise's `then`, etc.)
