### ISSUE TITLE
split CI matrix on browser

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2592]
Currently we're running all browsers in a single build; let's split that up.

**Comment by boneskull** [comment]
I think the Sauce failures (#2478) are due to opening a Sauce Connect tunnel, running tests, closing the tunnel, then immediately thereafter re-opening the tunnel with a new Karma run.  The `test-browser` target launches Karma four (4) times.

To get around this, we'll need to manually open the Sauce Connect tunnel *before* running Karma, then tell Karma not to open it, and use the existing tunnel.

**Comment by boneskull** [comment]
Example job: https://travis-ci.org/mochajs/mocha/jobs/179153053

**Comment by juergba** [comment]
This issue has been inactive for several years.
