### ISSUE TITLE
make test timeouts closer to reality

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2597]
Many tests in our suite regularly output "slowness" warnings:

![image](https://cloud.githubusercontent.com/assets/924465/20592829/7eda1df6-b1e4-11e6-8555-a32dee0de34e.png)

Let's increase the `--timeout` and/or `--slow` setting so the information it produces is actually helpful.

**Comment by ScottFreeCode** [comment]
Seems like this and #2837 are duplicate of each other?

**Comment by juergba** [comment]
closing, see #3539.
