### ISSUE TITLE
investigate jwt for saucelabs integration in PRs

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2602]
Apparently, using json web tokens, we can run our browser tests (on SauceLabs) on pull requests.  Currently, we're not doing this, because security.

Not sure when Travis-CI introduced its [JWT addon](https://docs.travis-ci.com/user/jwt/), but we should be able to leverage it.

**Comment by boneskull** [comment]
this will be closed by #2861

**Comment by ScottFreeCode** [comment]
Did this end up happening in the Sauce launcher consolidation, or do we still need to give it a try?

**Comment by boneskull** [comment]
@ScottFreeCode I haven't looked at JWT, no.

**Comment by craigtaub** [comment]
This has surfaced again from tests passing on PR but causing master to fail. I can have a go.

**Comment by juergba** [comment]
> The JWT addon is deprecated and will be discontinued on April 17, 2018.
