### ISSUE TITLE
less @import syntax error error when running tests (webpack/mocha)

### ISSUE THREAD

**Issue by cdmcmahon** [mochajs/mocha#2607]
I am using Mocha to write tests for my application. Any time I try to test a component that uses a widget from the library [`react-widgets`](https://github.com/jquense/react-widgets) I am presented with the following error message:

```
<path_to_my_app>/app/node_modules/react-widgets/lib/less/react-widgets.less:1
(function (exports, require, module, __filename, __dirname) { 
@import "./variables.less";
                                                              
^

SyntaxError: Unexpected token ILLEGAL
```

I have the following loaders in my `webpack.config.js`:

```
loaders: [
      { test: /\.js$/, exclude: /(node_modules|bower_components)/, loader: 'babel' },
      { test: /\.json$/, loader: 'json' },
      { test: /\.css$/,  loader: 'style-loader!css-loader' },
      { test: /\.less$/, loader: 'style-loader!css-loader!less-loader' },
      { test: /\.gif$/, loader: 'url-loader?mimetype=image/png' },
      { test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'url-loader?limit=10000&minetype=application/font-woff' },
      { test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'file-loader?name=[name].[ext]' },
      { test: require.resolve('trackjs'), loader: 'exports?trackJs'}
    ]
```

I get no such errors when actually *running* my application, simply when trying to test components that eventually reach this import.

I also found reports of a similar error [logged here on the repo for webpack's less-loader](https://github.com/webpack/less-loader/issues/55) however in that case, the users seem to experience the error in all cases, whereas I only experience the error in testing.

**Comment by villesau** [comment]
@cdmcmahon  Are you sure you need a real loader for your less files in unit tests at all? I would use null loader for less files and basically all the assets instead, ie: {test: /\.(?:css)$/, loader: 'null-loader'}

**Comment by cdmcmahon** [comment]
I ended up finding a fix this afternoon that involved a significant restructuring of my testing infrastructure, but I will that that using a null-loader has always seemed ill-advised to me. You ideally want identical circumstances between your tests and actual application. Secondly, null-loading anything could hide errors that are actually present.

**Comment by parkjoon** [comment]
Apologies for reviving this issue, but cdmcmahon, what did you restructure to resolve this issue?

**Comment by cdmcmahon** [comment]
Using karma as a test runner and all the associated plugins to deal with webpack, for starters.

**Comment by lstebner** [comment]
this was frustrating for me to come across and there's really no answers in any of these threads, but google leads here a lot, so for any one else who ends up here, the solution is https://github.com/bkonkle/ignore-styles and it works like a charm.
