### ISSUE TITLE
Hook failures do not print the full test title

### ISSUE THREAD

**Issue by rearadmiral** [mochajs/mocha#2608]
Is it intentional that the hook failure only include the immediate test title and not its full title include context? We have a lot of tests with different context names but the same it("....") name so it would be really helpful to see the full name with contexts in the hook failure at the summary of the test run at the end.

**Comment by Elergy** [comment]
@rearadmiral Hi!

I tried to reproduce the behavior you described, and it seems like it works correctly now.
Could you please check my test case [here](https://gist.github.com/Elergy/6b4471d244e1d7591ee0d1d9ff745d88) and prove that everything is good for you now?

Thanks!

**Comment by rearadmiral** [comment]
Works for me. Thanks!
