### ISSUE TITLE
Error: global leak detected: tvt

### ISSUE THREAD

**Issue by arLevi** [mochajs/mocha#2610]
I'm creating the issue after searching google for similar issue w/o any results.

Two issues here:
1. Each time this exception is raised **somewhere else**; meaning, test A can fail now - and after a refresh test B will fail with the **exact** same traceback.

2. There's nothing called `tvt` not via the API results which I'm testing or any JS script in the entire directory/files ... including the npm directories

3. It only happens in **Chrome ( everytime )**, Firefox/Safari - this exception never raised

Before "ignoring" this issue - I want to understand "who" is creating this variable

```
Error: global leak detected: tvt
    at Runner.checkGlobals (js/qa/mocha.js:4773:21)
    at Runner.<anonymous> (js/qa/mocha.js:4648:44)
    at Runner.EventEmitter.emit (js/qa/mocha.js:616:20)
    at js/qa/mocha.js:5077:14
    at done (js/qa/mocha.js:4518:5)
    at js/qa/mocha.js:4538:9
    at qa/api.js:77:13
    at p.callback (js/qa/superagent.min.js:1:9482)
    at p.<anonymous> (js/qa/superagent.min.js:1:6403)
    at p.n.emit (js/qa/superagent.min.js:1:4073)
```

And the row is:
```
it('test A', function(done) {
  ...... testing .....

   done();               <= this is where it raises the exception
}
it('test B', function(done) {
  ...... testing .....

   done();               <= this is where it raises the exception
}
```

**Comment by Slayer95** [comment]
Do this:

```
Object.defineProperty(window, 'tvt', {
  set() {throw new Error("naughty global set")},
}):
```

That will give you a sensible stack trace when something tries to write that global.
I doubt this is an issue with ``Mocha``, though.

**Comment by boneskull** [comment]
> There's nothing called tvt not via the API results which I'm testing or any JS script in the entire directory/files ... including the npm directories

Grepping source isn't going to be bulletproof with JS, of course.

Are there plugins running in Chrome that might be doing this?

@Slayer95 is correct though; this is Mocha simply *reporting* a leak in the code & envrionment which it was handed.  This is not a bug, and is intended behavior.  If you wish to disable the global leak checks, you can do (assuming browser context):

```js
mocha.setup({
  ignoreLeaks: true
});
```

**Comment by arLevi** [comment]
Then why there's no leak in Firefox / Safari ?
The leak is only when using Chrome ?!
