### ISSUE TITLE
before block gets called after test suites

### ISSUE THREAD

**Issue by SergeyKhval** [mochajs/mocha#2612]
If I run the following code, string 'before block' is logged to console only after both 'test suite 1' and 'test suite 2'. `beforeEach`, `after` and `afterEach` all work as intended

```javascript
describe('before', () => {
  before(() => {
    console.log('before block\n');
  });

  it('should log after before block', () => {
    console.log('test suite 1\n');
  });

  it('should log after before block', () => {
    console.log('test suite 2\n');
  });
}
```

Mocha version 3.2.0

**Comment by boneskull** [comment]
can't reproduce; unlikely a Mocha problem anyway.  will need more info about environment.  please include your actual test

**Comment by SergeyKhval** [comment]
Yes it seems it was a problem with my IDE. However I could reproduce this behavior in mocha, wdio-mocha-framework, webdriverio stack so I guess the problem is somewhere there. Issue can be closed
