### ISSUE TITLE
do not commit generated files to VCS

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2615]
When we added Bower support long ago (#584), it was implemented by committing the bundle (the root `mocha.js`) to VCS.

This, of course, is bad practice.  

I have no numbers anywhere on how many people install Bower via Mocha, but it's probably enough to cause pain if we stop supporting it.

Instead, we can create a script that dumps the dist file(s) into [another repository](/mochajs/bower-mocha), *a la* AngularJS.  The dist file(s) would still be *published* to npm.

Practically speaking, whenever anybody runs the browser-based tests via Karma, we generate a new bundle so that `karma-mocha` uses Mocha to test itself.  That's inconvenient for contributors and causes confusion.

* * *

An alternative or supporting solution is to consume [unpkg](https://unpkg.com/#/) in some way.  I'm a little hesitant to depend on this service.  It's open-source, so we could run our own server, but $.

**Comment by ScottFreeCode** [comment]
>Practically speaking, whenever anybody runs the browser-based tests via Karma, we generate a new bundle so that `karma-mocha` uses Mocha to test itself. That's inconvenient for contributors and causes confusion.

Isn't this necessary in any case so that when Mocha is self-testing it's testing the latest Mocha code?

**Comment by ScottFreeCode** [comment]
We've had multiple PRs recently that only updated the generated bundle.

I seem to recall there was an issue or PR where we had more details on what it will take to make the change happen, but I'm not finding a more recent one than this; anybody remember which issue or PR it was?

**Comment by dasilvacontin** [comment]
@ScottFreeCode  idk. The only solution I have in mind right now is a script in CI that checks whether `mocha.js` has not been modified in the PR.

**Comment by ScottFreeCode** [comment]
I think #2267 may have been the previous discussion I was thinking of, but it turns out there isn't much there that isn't already here.

**Comment by boneskull** [comment]
let's not go the angular route.  npm is fine; unpkg is fine; bower users should stop using bower.

**Comment by dasilvacontin** [comment]
I remember that @Munter mentioned about making "test" or whatever build "mocha.temp.js" instead of "mocha.js". He highlighted that one of the problems is that we overwrite the "build file" for testing, when the "build file" should only be modified when we actually want to "rebuild the published binary".

**Comment by ScottFreeCode** [comment]
Yeah, we've got `BUILDTMP/mocha.js` now to fix that -- I think he set it up if I recall correctly!

**Comment by Munter** [comment]
Yeah. We should be in a place where contributors are able to make local changes and run the tests without creating publication build artefacts. Of course this is no guarantee that they won't run the build step to create those artefacts manually and check in the changes. We should still have a bot to highlight that error and block merging. But at least that case shouldn't happen a lot in recent times

**Comment by boneskull** [comment]
OK, so this is what's gonna happen *before* we tag v4.0.0:

- the `preversion` script will change to run `test` and maybe a `dont-break` check or two (which I'll poke at a bit later)
- the `prepublish` script will change to run `make mocha.js`, which will cause the file to be published.

*when* we tag v4 (not before), this will happen:

- `mocha.js` will be removed from VCS
- `mocha.js` will be added to `.gitignore`
- `bower.json` will be removed from VCS

**Comment by boneskull** [comment]
this is done
