### ISSUE TITLE
create roadmap

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2617]
It should reference the [projects](/orgs/mochajs/projects)

**Comment by brutalcrozt** [comment]
Awesome, it's already on [devdoc](http://devdocs.io/mocha/).

> Documentation is too Node.js-centric, and we have a growing number of users consuming Mocha in the browser

Yay mocha in browser, even i still stuck how to get coverage.
I like to listing some existing good documentation site (will inspect later) :

- http://devdocs.io/
- https://webpack.js.org/concepts/
- https://angular.io/docs

**Comment by juergba** [comment]
closed due to inactivity.
