### ISSUE TITLE
identify areas that need more examples

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2619]
a good way might be to look at SO and see the most upvoted mocha-related questions.

another is the "common mistake" label in this repo.

deliverable is a proposed list of items to add examples for, then on to mochajs/mocha#2359.

**Comment by boneskull** [comment]
I think maybe we should rename the `pr-please` label to `please-help`, since this doesn't need a PR.

**Comment by boneskull** [comment]
there's branch `issue/2619-examples` with one (1) example in it.

**Comment by outsideris** [comment]
Now, we are adding new examples under [mocha-examples](https://github.com/mochajs/mocha-examples).
