### ISSUE TITLE
I am unable to run my test cases as a normal user but all test cases are running if I run then as root or sudo.

### ISSUE THREAD

**Issue by RatanShreshtha** [mochajs/mocha#2627]
I am running my test cases on my machine running ubuntu 16.04 and mocha@3.2.0 but I am unable to run them as normal user but test cases are running ad root.

I am using node 7.2.0 and npm 4.0.3.

What might be the cause of this problem ?

**Comment by ORESoftware** [comment]
What is the error you see if you don't run them as root user?

**Comment by RatanShreshtha** [comment]
Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Comment by ORESoftware** [comment]
Can you show us the code?

**Comment by RatanShreshtha** [comment]
No

**Comment by Munter** [comment]
Are you depending on global installations of mocha or any other node module, and is your node installed as root originally?

**Comment by RatanShreshtha** [comment]
I have installed mocha globally and rest of the modules locally.

**Comment by Munter** [comment]
This is not a recommended setup. Install mocha as a `devDependency` locally in your project an run that binary.

Also, installing node as root, then depending on any type of global install as a non-root user will always get you into similar trouble across all sorts of tooling. Install your node in user space so global installs are accessible as non-root users or stop depending on global installs

**Comment by Munter** [comment]
Tips for running a local mocha:
- Add a `test` entry in your package.json `scripts` which runs mocha. Npm scripts always use the locally installed binaries before any global installs. Then run the test with `npm test`
- Prepend `./node_modules/.bin` to your `$PATH`, which will make the path resolution prefer locally installed binaries. Then starts mocha with just `mocha` in your project

**Comment by RatanShreshtha** [comment]
I will try that solution.
