### ISSUE TITLE
Error messages not appearing for syntax errors when using `--compiler` and `--watch`

### ISSUE THREAD

**Issue by mylesmegyesi** [mochajs/mocha#2630]
I'm using the ts-node to compile TypeScript tests as described in their [README](https://github.com/TypeStrong/ts-node#mocha), however when there is a compilation error in a test file, no error message is displayed in watch mode (works fine with a single run). I've done some investigation and it appears the problem is two fold:

1) The mocha watcher catches the exception that is thrown by `require`, but [only prints `e.stack`](https://github.com/mochajs/mocha/blob/master/bin/_mocha#L423). The works because Node puts the error message into `e.stack` in addition to the stack trace.
2) ts-node only sets [`e.message` instead of `e.stack`](https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L651), so the error message is lost.

Would you accept a PR that changed the error printing logic to this?

```javascript
if (e.stack) {
  console.log(e.stack);
} else {
  console.log(e.message);
}
```

This should preserve the existing behavior and allow error messages from ts-node to be displayed.

**Comment by KaidenR** [comment]
@mylesmegyesi We just started running into this issue after updating a few of our NPM packages. We found that if we reverted our ts-node package back to the previous version we were using (1.3.0), we were able to see errors again. Reverting mocha did not fix the problem.

So it looks like this may be an issue with ts-node instead of mocha?

**Comment by mylesmegyesi** [comment]
I wouldn't say that either Mocha or ts-node has a problem _per se_, but there are mismatched assumptions. Mocha assumes that content of the error resides in `e.stack` and ts-node assumes that consumers will only be reading `e.message`. That being said, I think that both sides should take steps to make less assumptions about their integration points. On Mocha's side, the simple change that I have proposed above will remove Mocha's assumptions about where the error message resides. On ts-node's side, [they should hydrate the `e.stack` property](https://github.com/TypeStrong/ts-node/issues/248).

I'm more than willing to submit a PR to implement this change if it is desired.

**Comment by patrickjuchli** [comment]
This is working again since `ts-node 1.7.1`.
