### ISSUE TITLE
Test suite oganisation

### ISSUE THREAD

**Issue by PigeonT** [mochajs/mocha#2631]
I need to organise different test suites using mocha, but I ain't find the way to do that, need some help!
something like these:
```javascript
    //main entry for testing stuff
    for (let p : testSuiteCollection) {
        runSuite(p);    
    }
```
thx in advance

**Comment by Munter** [comment]
If this is still relevant I suggest you ask in the gitter channel: https://gitter.im/mochajs/mocha
