### ISSUE TITLE
Windows: Unable to add dynamic content

### ISSUE THREAD

**Issue by serbanghita** [mochajs/mocha#2635]
**The error:**

```
HTML1701: Unable to add dynamic content '<ul id="mocha-stats"><li class="progress"><canvas width="40" height="40"></canvas></li><li class="passes"><a href="javascript:void(0);">passes:</a> <em>0</em></li><li class="failures"><a href="javascript:void(0);">failures:</a> <em>0</em></li><li class="duration">duration: <em>0</em>s</li></ul>'. A script attempted to inject dynamic content, or elements previously modified dynamically, that might be unsafe. For example, using the innerHTML property to add script or malformed HTML will generate this exception. Use the toStaticHTML method to filter dynamic content, or explicitly create elements and attributes with a method such as createElement.  For more information, see http://go.microsoft.com/fwlink/?LinkID=247104
```

**The reason:**

```
<ul id=\"mocha-stats\"><li class=\"progress\"><canvas width=\"40\" height=\"40\"></canvas></li><li class=\"passes\"><a href=\"#\">passes:</a> <em>0</em></li><li class=\"failures\"><a href=\"#\">failures:</a> <em>0</em></li><li class=\"duration\">duration: <em>0</em>s</li></ul>
```

has changed into

```
<ul id="mocha-stats"><li class="progress"><canvas width="40" height="40"></canvas></li><li class="passes"><a href="javascript:void(0);">passes:</a> <em>0</em></li><li class="failures"><a href="javascript:void(0);">failures:</a> <em>0</em></li><li class="duration">duration: <em>0</em>s</li></ul>
```

Notice the `href="javascript:void(0);"`

That particular piece of code, triggers the error above on Windows.
A simple removal of that (or an external binding made via an unique id attribute) can stop this problem for Windows users.

**My temporary solution** was to go to `function fragment (html) {` and update the code:

```
  var result = html.replace(/%([se])/g, function (_, type) {
    switch (type) {
      case 's': return String(args[i++]);
      case 'e': return escape(args[i++]);
      // no default
    }
  });

   div.innerHTML = window.toStaticHTML(result);
```

I could make a patch to go back to `href="#"`.

**Comment by ScottFreeCode** [comment]
Could you be more specific about what you mean by "on Windows" -- is this a particular version of Internet Explorer or Edge? I was not able to reproduce with my usual local IE environment of IE 11 on Windows 8.1.

I also haven't managed to find any standard documentation on `toStaticHTML`, so if this function is a Microsoft extension I doubt that Mocha would end up using it directly (since we also need to support non-Microsoft browsers that run on multiple OSes). I would presume there's a reason for the use of `javascript:void(0)` as well, so it may not be correct behavior to sanitize this or to revert it to `#`. Assuming we can confirm the issue in the first place, it may be necessary to fix this by switching from use of `innerHTML` to use of DOM methods to build the elements programmatically instead.

**Comment by serbanghita** [comment]
@ScottFreeCode sorry about not being specific to the platform, I was in a hurry when posting the bug report.
It's on a Win8.1 app environment. It's something similar to https://github.com/angular/angular.js/issues/1853

I'm guessing `javascript:void(0);` is there to prevent unnecessary scrolling. I believe one solution would be to figure out why the code was updated from `#` and keep `innerHTML` for the simplicity.
I check and nobody complained before about running mocha in such environment. 

It might as well not worth the effort. I'll close it for now and if this resurfaces maybe its worth patching.

Thanks for your time!

**Comment by ScottFreeCode** [comment]
Ah, interesting. The new metro apps are sort of uncharted territory for us. It'd be great if we could easily support it -- it is neat that Microsoft supports using HTML and JavaScript for them in the first place -- but it could be pretty hard to avoid little breaking things like this unless we can find some kind of continuous integration for that environment that can plug into GitHub. Maybe if AppVeyor could do that?

Did you by any chance try [the shim library that was mentioned in that Angular thread](https://github.com/Microsoft/winstore-jscompat)? I'd be curious to know if that works.

**Comment by serbanghita** [comment]
Yes the shim works as well! I'm not sure about the performance penalty it adds but it works.

This problem is gone in Win 10 apps, but still I think it might be worth having an AppVeyor Visual Studio integration and attempt to run the tests inside an empty app. Kind of like I did here: https://github.com/serbanghita/Cordova-Windows-App-Boilerplate/blob/master/appveyor.yml

Do you think this is worth trying?
