### ISSUE TITLE
Run test from string code

### ISSUE THREAD

**Issue by ToonvanStrijp** [mochajs/mocha#2638]
I want to run my mocha test from a string with code instead to use the addFile method. Is there some way to do this, without writing the code to a file first?

**Comment by ScottFreeCode** [comment]
You could probably rig up something using Node's [sandboxing](https://nodejs.org/api/vm.html) capabilities, e.g.:
```js
var vm = require("vm")
var assert = require("assert")

describe("dynamic test", function() {
  var testString = "assert.strictEqual(" + Math.random() + ", " + Math.random() + ")"
  var testName = "dynamically generated test"
  vm.runInNewContext("it('" + testName + "', function() {" + testString + "})", {assert: assert, it: it}, {displayErrors:true})
})
```
...or, to emulate `addFile` + `loadFiles` (this is based on the code in `loadFiles`):
```js
var vm = require("vm")
var Mocha = require("mocha")
var mocha = new Mocha({ui:"bdd"})
pseudoFile(mocha, {assert:require("assert")},
  "describe('dynamic tests', function() {\
    it('should be crazy', function() {\
      assert.strictEqual('what', 'on earth')\
    })\
  })")
mocha.run()

function pseudoFile(mocha, context, fileContent) {
  mocha.suite.emit("pre-require", context, ":memory:", mocha)
  mocha.suite.emit("require", vm.runInNewContext(fileContent, context, {displayErrors: true}), ":memory:", mocha)
  mocha.suite.emit("post-require", context, ":memory:", mocha)
}
```

**Comment by ScottFreeCode** [comment]
(On a little further reflection, I'm not certain if that works for the `exports` interface -- I don't have much experience with the `vm` module. So let me know if you have any trouble with that and I will see if I can dig into it more.)

**Comment by boneskull** [comment]
This begs the question why you want to run tests from a string.

**Comment by ToonvanStrijp** [comment]
@ScottFreeCode Thanks for the explanation I'll try it in a couple of days. @boneskull I'm working on a server side code validation system. And I want to write mocha tests to test the code that is going to be send to the api.

**Comment by ScottFreeCode** [comment]
Now that I think about that, I feel the need to mention that if you're running end-user/third-party code on your server (not sure if that's the case, but just in case) then you will want some sort of security audited sandboxing, as there are a lot of things that the code to be "tested" could try to tamper with when being run for the testing.
