### ISSUE TITLE
--compiler then --require does use compiler for the required file

### ISSUE THREAD

**Issue by memelet** [mochajs/mocha#2639]
With a command containing

```... --compilers js:babel-register --require test/helper.js```

The helper.js file is loaded before babel is setup and hence fails with syntax errors.

**Comment by ScottFreeCode** [comment]
Try `node --require babel-register test/helper.js` to confirm that `babel-register` is the right module to use and that you have Babel configured correctly.

**Comment by memelet** [comment]
Babel is indeed working. It works for all files *other than* ```test/helper.js```.

**Comment by dasilvacontin** [comment]
I can't see the problem while taking a quick look: https://github.com/mochajs/mocha/blob/master/bin/_mocha#L326-L346.

**Comment by memelet** [comment]
I guessing that the problem is with the intellij eslint plugin, as I cannot reproduce this on the command line. 

I have refactored so that we no longer depend on a magic global helper file. So I will close this

Thanks very much @ScottFreeCode and @dasilvacontin for looking into this, and my apologies for any invaluable effort on your part.
