### ISSUE TITLE
async failed test doesn't display an assertion error when using promise

### ISSUE THREAD

**Issue by itayod** [mochajs/mocha#2643]
code for example:

`
  
    function fakePromise() {
      var promise = new Promise((res)=>{
        setTimeout(()=>{
          res();
        },100)
      })
      
      return promise;
    }
    
    it('should display assertion error', (done) => {
      var promsie = fakePromise();
      promsie.then(()=>{
        console.log('hi')
        expect(2).to.equal(1);
        done();
      })  
    })
`

**Comment by anthony-redFox** [comment]
@itayod 

more better return Promise

```
function fakePromise() {
  var promise = new Promise((res)=>{
    setTimeout(()=>{
      res();
    },100)
  })
  
  return promise;
}

it('should display assertion error', () => {
  var promsie = fakePromise();
  return promsie.then(()=>{
    console.log('hi')
    expect(2).to.equal(1);
  })  
})
```

**Comment by itayod** [comment]
I still don't get the assertion error I was expecting,

instead I am getting this error:

Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Comment by itayod** [comment]
that worked for me, 

thank you.

**Comment by anthony-redFox** [comment]
@itayod Could you please close the issue.

**Comment by drazisil** [comment]
Closing due to no response from OP
