### ISSUE TITLE
TypeError: #<CustomPromise> is not a promise

### ISSUE THREAD

**Issue by milewski** [mochajs/mocha#2650]
```
class CustomPromise extends Promise {}
```

```
it('do something', () => {
 return new CustomPromise( accept => accept() );
});
```

Im subclassing Promise ... however mocha thinks its not a instance of promise.... any workaround?

**Comment by ferm10n** [comment]
I just had the same issue with TAP. You might need to adjust your class to be like this:
`class CustomPromise extends Promise {
    then () {
      super.then.apply(this, arguments)
    }
  }`
