### ISSUE TITLE
Empty xdescribes cause improper nesting of subsequent tests in output

### ISSUE THREAD

**Issue by nickmccurdy** [mochajs/mocha#2652]
I have noticed some strange behavior when using xdescribe with no callbacks. If I use the default reporter and have an `xdescribe` with no callback before an `it` test, the `xdescribe` nests everything after it within itself. This also happens if there's a `describe` with implemented tests and at least one `xdescribe` inside it, followed by implemented tests.

# Input
```
xdescribe('empty describe 1')
xdescribe('empty describe 2')
it('pending test 1')
it('pending test 2')
```

# Output
```
  empty describe 1
    empty describe 2
      - pending test 1
      - pending test 2


  0 passing (0ms)
  2 pending
```

# Environment
- Node 7.3.0
- Mocha 3.2.0

**Comment by mnhy520** [comment]
Soory, I can't help you.

**Comment by nickmccurdy** [comment]
Hi, was this marked as invalid because it's stale or has this issue been fixed?
