### ISSUE TITLE
enhancement: new interface to support arrow functions

### ISSUE THREAD

**Issue by alexreardon** [mochajs/mocha#2657]
Currently functions that use `() =>` cannot take advantage of the mocha context: http://mochajs.org/#arrow-functions. 

However, arrow function usage could be improved by passing the context as an argument:

```js
it('should do something cool', (done, context) => {
  context.timeout = 5000;
  ...
});
```

The complicating factor is the `done` argument. The presence of which makes the test async. Perhaps if you want to use the `context` argument then you need to also call `done` when appropriate.

**Comment by laggingreflex** [comment]
Came here for this, but I've also found https://github.com/skozin/arrow-mocha

**Comment by eight04** [comment]
Here is a version which can work with mocha's `--require` option:
https://www.npmjs.com/package/mocha-context

**Comment by boneskull** [comment]
Replacing the default `bdd` interface with this is a non-starter.

It's possible to create an interface which passes the context as the first parameter, but would likely require modifications to Mocha's core to support, due to hardcoded assumptions.

Would accept a PR that would allow the "async check" of an interface to be configurable.  Once that's ready, then it should be fairly trivial to provide an alternate interface.

**Comment by eight04** [comment]
> allow the "async check" of an interface to be configurable.

What does it mean?

I think this feature could be implemented in 2 ways:

1. Create a new interface e.g. `bdd-arrow` that would [decorate the arrow function](https://github.com/eight04/mocha-context/blob/84715db337ec5fd690a190091c995e5774f76050/index.js#L11-L20) before [sending `fn` to `new Test`](https://github.com/mochajs/mocha/blob/0d95e3f41a0859be4e7225541575e78b6d8926ee/lib/interfaces/bdd.js#L85).
2. Add a new option e.g. `mocha --context-argument` that would change [how `runnable.fn` is called](https://github.com/mochajs/mocha/blob/0d95e3f41a0859be4e7225541575e78b6d8926ee/lib/runnable.js#L372).

**Comment by boneskull** [comment]
@eight04 see #3399

**Comment by JoshuaKGoldberg** [comment]
Yeah, this would be a pretty big change to Mocha that is already solved by at least one userland integration mentioned in this thread. Per #5027 we're not looking to do big shakeups any time soon.
