### ISSUE TITLE
Document how to use --harmony* flags with _mocha

### ISSUE THREAD

**Issue by BrandonZacharie** [mochajs/mocha#2665]
I expect these flags to work because
```bash
➜ node_modules/.bin/_mocha --help               

  ...

  Options:

    ...
    --harmony<_classes,_generators,...>     all node --harmony* flags are available
```

However, as of
```bash
➜ node_modules/.bin/_mocha --version
3.2.0
```

I get
```bash
➜ node_modules/.bin/_mocha --harmony_async_await

  error: unknown option `--harmony_async_await'
```

**Comment by ScottFreeCode** [comment]
I'm not sure off the top of my head whether there's a way to give `mocha` and `_mocha` separate help messages. I am fairly sure that the main reason for the two separate files is specifically so that `mocha` can pass the Node flags (such as `--harmony*`) to Node while calling the actual `_mocha` under the hood. This would presumably be improved/fixed by #2517... Or, depending on why you're using `_mocha`, we may be able to figure out how to call it so as to get the `--harmony*` flags to Node directly, rather than sending them through Mocha at all.

**Comment by BrandonZacharie** [comment]
If there's any other way to get --harmony_async_await working, i'm for it.

**Comment by ScottFreeCode** [comment]
Does `node --harmony_async_await node_modules/istanbul/lib/cli.js <command> node_modules/mocha/bin/_mocha` still work? (Found here: https://github.com/gotwarlost/istanbul/issues/44#issuecomment-31564339 the next thing after that on google is https://www.npmjs.com/package/istanbul-harmony...)

**Comment by BrandonZacharie** [comment]
```
➜ node --harmony_async_await node_modules/.bin/istanbul cover node_modules/.bin/_mocha
node_modules/mocha/lib/mocha.js:79
  this.files = [];
             ^

TypeError: Cannot set property 'files' of undefined
    at Mocha (node_modules/mocha/lib/mocha.js:79:14)
    at Object.<anonymous> (test/index.js:10:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Object.Module._extensions.(anonymous function) [as .js] (node_modules/istanbul/lib/hook.js:109:37)
    ...
```

**Comment by BrandonZacharie** [comment]
I think I understand now... I tried your script on other repos that use `istanbul` and it worked perfectly. The one i'm working with now spills out a bunch of errors like

```
Transformation error; return original code
{ Error: Line 26: Unexpected token =>
    at constructError (node_modules/esprima/esprima.js:2407:21)
    at createError (node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (node_modules/esprima/esprima.js:2500:13)
    ...
  lineNumber: 26,
  description: 'Unexpected token =>',
  index: 560 }
```

and one like

```
ReferenceError: window is not defined
      at Object.<anonymous> (coverage/lcov-report/prettify.js:1:63)
      at Object.Module._extensions.(anonymous function) [as .js] (node_modules/istanbul/lib/hook.js:109:37)
      at node_modules/require-directory/index.js:76:17
      ...
```

I believe both are related to [`istanbul` and ES8 syntax](https://github.com/gotwarlost/istanbul/issues/733). The others that tested fine with your script, [like this one](https://github.com/BrandonZacharie/node-redis-server), only use ES6 syntax.

With that said, I think it would still be A Good Idea™ to go forward with #2517 and maybe document this workaround somewhere in the meantime.

**Comment by ScottFreeCode** [comment]
> With that said, I think it would still be A Good Idea™ to go forward with #2517 and maybe document this workaround somewhere in the meantime.

Yeah, I'm a little surprised myself that it's this tricky, so we should definitely document this until we can test that #2517 doesn't break anything (depending on how it works, it might have the same problem running Istanbul as using `mocha` rather than `_mocha` does now...). Since we've got issue #2517 to track the potential simplification, mind if we use this ticket to track the lack of documentation for the workaround?

**Comment by BrandonZacharie** [comment]
Sounds good. On that note, is the Wiki the appropriate place to put something like this? If so, maybe we could add a Known Issues section and putting this there.

**Comment by ScottFreeCode** [comment]
It should be in theory, but I don't know how up to date it is.

**Comment by Munter** [comment]
@BrandonZacharie You might have better luck with using [nyc](https://github.com/istanbuljs/nyc) for code coverage rather than istanbul

**Comment by sabakugaara** [comment]
I just use `node --harmony ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- tests/*`, it work well

**Comment by juergba** [comment]
The `_mocha` executable does not support Node flags and there are no plans to do so in future.

You have two options:
- use the `mocha` executable which detects the Node flags and spawns a child-process.
- pass the Node flags directly to Node (not via Mocha) as shown above by @sabakugaara 

see [docu](https://mochajs.org/#about-node-flags)
