### ISSUE TITLE
Question: specifying compilers programmatically?

### ISSUE THREAD

**Issue by buddyp450** [mochajs/mocha#2666]
I found this issue [elsewhere](https://groups.google.com/forum/#!topic/mochajs/-xlWtH4jr5s) online without answer but my specific use case is that I have at test runner similar to [guybedford's guide](http://guybedford.com/systemjs-mocha-istanbul) for mocha and I'm unable to specify a compiler so that my tests can be written for my react app with full enzyme/jsx support.

The specific snippet I'm trying to work this into is here:
```javascript
var Mocha = require('mocha');

SystemJS.import('./test.config.js')
.then(function() {
  var runner = new Mocha({
    ui: 'bdd',
    // this line is what will allow this runner to work in both the browser and Node
    reporter: typeof window != 'undefined' ? 'html' : 'spec'
  });

  // set up the global variables
  runner.suite.emit('pre-require', global, 'global-mocha-context', runner);

  return SystemJS.import('./test/app/components/index.js')
  .then(function(tests) {
    return new Promise((resolve, reject) => {
      runner.run((failures) => {
        if (failures)
          reject(failures);
        else
          resolve();
      });
    });
  });
})
.catch(console.error.bind(console));

```

**Comment by ScottFreeCode** [comment]
Hi @buddyp450, sorry for the late reply, hope it's not too late. Mocha's `--compilers` CLI option is really just a shorthand for a combination of:
- `require`ing the specified compiler registration module, which then handles compilation automatically behind the scenes
- adding the specified extension to the files to search for and/or watch

In programmatic usage you have to do more of the file lookup and watching yourself, so you'd just handle the desired extensions however is appropriate as part of that process. That leaves the actual compiling, for which the direct programmatic equivalent is basically just `require(<compiler registration module>)` at some point before you start `require`ing test files. Unless, of course, you'd prefer a higher degree of control over file compilation and/or loading and want/need to specifically call the compiler against the files, in which case it's going to depend entirely on the compiler. In any case, there's not really any magic happening under Mocha's hood to expose programmatically in the first place -- the CLI flag merely provides easier commandline access to the combination of `require`ing the compiler and configuring Mocha's test file lookup.

That may or may not make things easy for your programmatic use case, depending on whether you're just `require`ing the test files and can use the same sort of compiler registration modules that Mocha's CLI supports. I'd have to look at `./test/app/components/index.js` to give more specific advice I guess.
