### ISSUE TITLE
Add an 'alone' modifier to 'it' and 'describe'.

### ISSUE THREAD

**Issue by Lindenk** [mochajs/mocha#2685]
Hello!

My suggestion is to include a new modifier to `it` and `describe` that will force the test(s) to be run without any other tests in their scope running concurrently. The full behavior of this feature can be described as: Any test marked as `alone` will be run seperately from all other features in it's scope. The goal of this feature is to simplify the implementation of tests that depend on a single resource without confliction.

Consider the following scenario:

```javascript
describe("A process intensive resource test", function() {
    let resource;
    before(function() {
        resource = createSomeExpensiveResource();
    });

    beforeEach(function() {
        resource.reset(); // reuse resource without recreating
    });

    it("should be able to be set to 5", function() {
        return resource.setValue(5)
            .then(() => resource.getValue())
            .should.eventually.be.eql(5);
    });

    it("should be able to be set to 6", function() {
        return resource.setValue(6)
            .then(() => resource.getValue())
            .should.eventually.be.eql(6);
    });
});
```

Currently, mocha will run the two tests concurrently causing them to write to the same resource before either finish, causing a race condition. Modifying the above situation to include this suggestion results in the following:

```javascript
describe("A process intensive resource test", function() {
    let resource;
    before(function() {
        resource = createSomeExpensiveResource();
    });

    beforeEach(function() {
        resource.reset(); // reuse resource without recreating
    });

    it.alone("should be able to be set to 5", function() {
        return resource.setValue(5)
            .then(() => resource.getValue())
            .should.eventually.be.eql(5);
    });

    it.alone("should be able to be set to 6", function() {
        return resource.setValue(6)
            .then(() => resource.getValue())
            .should.eventually.be.eql(6);
    });
});
```

This would cause the tests marked as `alone` to run separately from any other tests in it's `describe` block.

**Comment by ScottFreeCode** [comment]
> Currently, mocha will run the two tests concurrently...

This should not be the case, and if it is then you've discovered a bug (whether in your test code, or in the assertion library, or in Mocha), not a feature; Mocha will not report test failures correctly if they run concurrently.

Could you provide a minimal but complete example of a test that will get this issue (i.e. something I can copy-paste into a fresh project and run to verify the problem)? That way we can look at whether it may be incorrect usage of the assertion library or something like that. (Even if it turns out it is a bug in Mocha, we'll want to be able to reproduce it in order to dig into how it happens.)

**Comment by Lindenk** [comment]
Huh, I can't seem to reproduce the problem. I might have stumbled on a bug, or it's possible I didn't write the tests correctly. Well, I suppose my problem is solved in either case. Thanks
