### ISSUE TITLE
when using --watch if test has missing dependency watch dies

### ISSUE THREAD

**Issue by AutomatedTester** [mochajs/mocha#269]
If I run watch on the following and my `node_modules` havent been installed then watch dies. It would be good for it to notice the error and then wait for an update like [nodemon](https://github.com/remy/nodemon)

``` javascript
var mongoose = require("mongoose")
  , assert = require("assert");

describe('logging',function(){
  beforeEach(function(done){
    done;
  });

  describe('messages', function(){
    it('should push data into mongo', function(done){
      done()
    });
  });

  afterEach(function(done){
    done();
  });
});
```

**Comment by danielstjules** [comment]
Not sure when the behavior was fixed, but it's not a problem with 2.2.0 https://github.com/mochajs/mocha/commit/65fc80ecd96ca2159a792aff089bbc273d4bd86d :) Closing this issue.
