### ISSUE TITLE
Mocha test for Socket.io not starting API? 

### ISSUE THREAD

**Issue by georgeedwards** [mochajs/mocha#2692]
I have a nodejs API project which I am testing with mocha and Chai. I am now trying to develop a socket.io aspect of my API. To test it I have the following test:

```
    var socket = require('socket.io-client')('http://localhost:3000/api/jobs');
    
    describe('Jobs Socket /api/jobs', function () {
        it('Should connect', function (done) {
            socket.on('connect', function () {
                done()
            });
        })
    })
```

However, the test times out. I am assuming that this is because my API isn't running in these tests. Despite having already developed quite a lot of REST end points, I haven't paid much attention as to how the API server is being run. I have a `../index.ts` file which includes:

```
    var server = http.createServer(app);
    //var io = require('socket.io')(server);
    //server.listen(80);
    
    var io = require("socket.io").listen(server);
    new RealTimeJobs(io);
```

So this is how the socket it being created, so do I need to call this file somehow from my mocha test?

**Comment by Munter** [comment]
You might be experiencing a race condition. Are you sure that the `connect` event hasn't already been fired at the time when the test runs? Since you are connecting to localhost this might happen fairly fast
