### ISSUE TITLE
Mocha configuration with webpack 2 Tree Shaking

### ISSUE THREAD

**Issue by Olgagr** [mochajs/mocha#2711]
With Webpack 2 we get a built-in tree-shaking feature. It demands to turn off modules transformation in babel (webpack right now understands native modules). Basically what has to be done in .babelrc:

```
"presets": [["es2015", { "modules": false }]]
```

However, then mocha has problems with native modules. I added plugin to transform modules only for tests:

```
"env": {
    "test": {
      "plugins": [
        ["babel-plugin-transform-es2015-modules-commonjs"]
      ]
    }
  }
```

Then I run my tests:

```
BABEL_ENV=test mocha --compilers js:babel-register
```

However, this still doesn't work:

```
{ import assert from 'assert';
SyntaxError: Unexpected token import
```

Is there any way to setup mocha with webpack 2 treeshaking mode ?

**Comment by jeffijoe** [comment]
I did this:

```
{
  "presets": [
    ["es2015", { "modules": false }],
    "stage-2",
    "react"
  ],
  "plugins": ["transform-runtime", "react-hot-loader/babel", "transform-decorators-legacy"],
  "env": {
    "test": {
      "presets": ["es2015"]
    }
  }
}
```

and then `NODE_ENV=test mocha...` - did the trick for me.

**Comment by Munter** [comment]
For things to run in mocha you definitely need babel to compile module imports. I run with a similar setup to what @jeffijoe suggests. It's a bit tedious, but that's what you get for opting into transpilers at an early stage

**Comment by Olgagr** [comment]
Hmm, interesting but it did not work for me. In my .babelrc file I have:

```
{
  "presets": [["es2015", { "modules": false }]],
  "plugins": [
    "transform-class-properties",
    "transform-object-rest-spread"
  ],
  "env": {
    "test": {
      "presets": ["es2015"]
    }
  }
}
```

and I run my test:

```
NODE_ENV=test mocha --compilers js:babel-register
```

and I still get error:

```
(function (exports, require, module, __filename, __dirname) { import assert from 'assert';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
```

**Comment by Olgagr** [comment]
This has to be very specific for my test suit. I noticed that when I run test files separately, one by one, everything is working. However, when I try to run all of them at once, I get this error. Strange.

**Comment by Olgagr** [comment]
Found it! Somebody in out team decided to overwrite the whole process.env in some test :1st_place_medal: Thanks @jeffijoe and @Munter  for help!

**Comment by a8568730** [comment]
Thank you @jeffijoe , it works perfectly.

**Comment by ahmadalibaloch** [comment]
Not working any of the above solutions.
