### ISSUE TITLE
importing dependecy problem

### ISSUE THREAD

**Issue by tasoss** [mochajs/mocha#2712]
Hello.I have a node.js app which works correctly.When i try to run some tests that i have written
i get Class extends value undefined is not a function or null.When i try to run the tests via webstorm i get 
'class TennisGame  extends Game.Game' that Game is an empty object.I'm using const Game = require("./Game.js"); which works correctly on runtime(when i run via node the application).
What am i missing? Thanks!

**Comment by kunagpal** [comment]
@tasoss Could you share a working example, including the code and its test(s)? It's difficult to deduce the exact issue from the information provided. 😅
