### ISSUE TITLE
mocha.setup('bdd'),where does it from?

### ISSUE THREAD

**Issue by zzzgit** [mochajs/mocha#2719]
I've download a demo form the internet,and I found that there is a line `mocha.setup('bdd');`.
Why?
Does it belong to API of mocha?

**Comment by ScottFreeCode** [comment]
It's documented twice over, [here](http://mochajs.org/#browser-specific-methods) and [here](http://mochajs.org/#browser-configuration).

The short version is that `mocha.setup('bdd')` activates the BDD API (that is, puts the `describe`, `it`, `before`, `beforeEach`, `after` and `afterEach` functions into the global scope).

Closing this for now, but feel free to let us know if there's anything else unclear about it based on the documentation.
