### ISSUE TITLE
Add support for --inspect-brk

### ISSUE THREAD

**Issue by stropitek** [mochajs/mocha#2720]
Nodejs 7.6.0 has added the flag `--inspect-brk` as an alias for `--inspect --debug-brk`. Would it be possible to support it in mocha as well?

**Comment by dasilvacontin** [comment]
Closed by #2769.

**Comment by dasilvacontin** [comment]
This enhancement has been released in [v3.3.0](https://github.com/mochajs/mocha/releases/tag/v3.3.0)! 🎉
