### ISSUE TITLE
Flag to detect `process.env` changes after tests

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mocha#2729]
To detect problems like this: https://github.com/mochajs/mocha/issues/2711#issuecomment-284220006 Could we do something like the global leak detection, only for `process.env`'s properties and concerned with changes in general rather than with additions?

**Comment by kunagpal** [comment]
@ScottFreeCode Since there's already an option called `--check-leaks`, it could be extended to take in an optional argument to check for `process.env` leaks as well. For instance,

```js
mocha ... --check-leaks env,global
```

The default value here would be to check for global variable leaks only.

**Comment by ScottFreeCode** [comment]
Some sort of argument to `--check-leaks`/`checkLeaks` instead of a new flag/method for anything else we want to add is an interesting idea... I wonder if there'd be any benefit to allowing this to be less like a list of options and more like a list of global variables to check for added properties, defaulting to the global variable that represents the object that contains global variables (`global` in Node, `window` in browser assuming no web workers where it would be `self`). For instance, if you have a test in the browser that involves creating elements with IDs that should clean up the created elements afterward, then knowing that the browser sets `document.<id>` to refer to the element with that `id`, you could `mocha.checkLeaks(["window", "document"])`; to get the `process.env` behavior on the CLI, you'd do `--check-leaks process.env,global` instead of `--check-leaks env,global`. That might be overkill for a very few use cases, however...
