### ISSUE TITLE
Question: How to call specific test cases from one file to another file.

### ISSUE THREAD

**Issue by velanbabu** [mochajs/mocha#2736]
Hi All,

I'm new to Mocha. I want to call Test case 2 from a.js file to b.js like import the test case because of same test cases repeatable in the b.js file. Example

File a.js : 
describe('Sample a',function(){
it('Test case1',function(done){
console.log('Testing test case1');
});
it('Test case2',function(done){
console.log('Testing test case2');
});
it('Test case3',function(done){
console.log('Testing test case3');
});
});

File b.js:
describe('Sample b',function(){
it('Test case2',function(done){
console.log('Testing test case2');
});
});

I tried below approach, it took entire test cases in the js file. 
exports.importTest = function(name, path) {
    it(name, function() {
        require(path);
       
    });
};

Kindly provide the solution for this problem.

Thanks
VV

**Comment by honeyjills** [comment]
Hi , 
Did you find anything on this ?

**Comment by petrdunaj** [comment]
I'm also interested :)
