### ISSUE TITLE
Override describe and it behavior

### ISSUE THREAD

**Issue by tomitrescak** [mochajs/mocha#2737]
Hi, is it possible to override somehow the describe and it behavior?
I need to automatically keep the full test path in a global variable for my snapshot testing mechanism for mocha.

Currently I cannot find a way of how to override it.
this is the implementation that will be used:

```js
const origDescribe = global.describe;
  global.describe = (name, impl) => {
    testName.push(name);
    try {
      origDescribe(name, impl);
    } catch (ex) {
      throw ex;
    } finally {
      testName.pop();
    }
  };
  const origIt = global.it;
  global.it = (name, impl) => {
    testName.push(name);
    try {
      origIt(name, impl);
    } catch (ex) {
      throw ex;
    } finally {
      testName.pop();
    }
  };
```

**Comment by ScottFreeCode** [comment]
It's underdocumented, but you should be able to get this info out of the `this` object in test and hook functions, if that would work.

Otherwise, you might be better off using a custom interface, (specify the name of the path to your interface file, without leading `.`, instead of "bdd" or "tdd" or "exports"), optionally based on the Mocha interface you desire, instead of trying to monkey-patch Mocha's interface.

**Comment by tomitrescak** [comment]
Thanks to @artemgovorov Was able to do it like this:

```js
// mocha is the reference to the running mocha framework
mocha.suite.on('pre-require', function (context) {
    const origIt = context.it;
    context.it = function (name, impl) {
      return origIt.call(this, name, function() {
        try {
          let name = this.test.title;
          let parent = this.test.parent;
          while (parent != null) {
            name = parent.title + ' ' + name;
            parent = parent.parent;
          }
          root.testName = name;
          return impl();
        } catch (ex) {
          throw ex;
        }
      });
    };
  });
```

**Comment by danon** [comment]
@tomitrescak What is `root` here?

**Comment by tomitrescak** [comment]
where I keep the reference to the tes, some more global variable ... been a day.

**Comment by GrayedFox** [comment]
Leaving this here for future eyeballs 👀

If you just need to do something straight forward like ensure default options are set it might instead be worth wrapping the Mocha method and calling that custom wrapper instead - annoying refactor in the sense of importing a custom `context` hook everywhere but safer than overwriting the global describe hook. This 

```js
import * as Mocha from 'mocha';

// destructure Mocha describe hook
const { describe: mochaDescribe } = Mocha;

/**
 * @type {Mocha.SuiteFunction}
 */
const describe = (name, optionsOrFunction, fn) => {
    const numRetries = process.env.MOCHA_CONTEXT_RETRIES || 2;
    const testFn = typeof optionsOrFunction === 'function' ? optionsOrFunction : fn;
    const testOptions =
        typeof optionsOrFunction === 'object' ? { ...optionsOrFunction, retries: numRetries } : { retries: numRetries };

    mochaDescribe(name, testOptions, () => {
        // eslint-disable-next-line no-console
        console.log('custom describe/context hook called');
        testFn();
    });
};

// add bound skip and only methods to the suit function
describe.skip = mochaDescribe.skip.bind(describe);
describe.only = mochaDescribe.only.bind(describe);

const context = describe;

// custom describe/context hooks for E2E tests
export { context, describe };
```

We've got a mix of JS and TS in our codebase so this ended up being the "good enough" solution - use with care 👍🏽
