### ISSUE TITLE
Getting error "Error: Resolution method is overspecified. Specify a callback *or* return a Promise; not both."

### ISSUE THREAD

**Issue by fbarnard** [mochajs/mocha#2738]
I have something simple as this.

` it("should call promise", async (done) => {

        const testPromise = new Promise((resolve, reject) => {

            setTimeout(() => {

                resolve("Hello World!");

            }, 200);
        });

        const result = await testPromise;

        done();
}`

But I keep on getting the error " Error: Resolution method is overspecified. Specify a callback *or* return a Promise; not both.".

If I take out done() then the test times out.

tsconfig.json
`{
    "compilerOptions": {
        "module": "commonjs",
        "target": "ES6",
        "noImplicitAny": false,
        "types": ["node", "mocha","supertest"],
        "typeRoots": [
            "./node_modules/@types"
        ]
    }
}`
mocha.opts
`--require ts-node/register 
--reporter dot
--watch-extensions tsx,ts 
test/**/*.ts`

**Comment by fbarnard** [comment]
lovely found how to fix it remove done in the function param and at bottom and it works. As soon as you put the done in function param it goes haywire

**Comment by ScottFreeCode** [comment]
Keep in mind also that `async` functions automatically return a promise.

**Comment by vickenliu** [comment]
seems as long as you `async`, and as @ScottFreeCode said, it returns promise, so we just skip calling `done()` . works.

**Comment by QauseenMZ** [comment]
Removing done worked for me!

Before:
`
it('receives successful RPC response', async (done)  => {
     const getSomeData = await getResponse(unitData, function callBack(unit, error, data){
            expect(data.statusCode).to.be.equal(200);
            done();
      })
})`

AFTER (Works!!):
`
it('receives successful RPC response', async ()  => {
     const getSomeData = await getResponse(unitData, function callBack(unit, error, data){
            expect(data.statusCode).to.be.equal(200);
      })
})`

**Comment by QauseenMZ** [comment]
Removing done worked for me!

Before:

it('receives successful RPC response', async (done) => { 
     const getSomeData = await getResponse(unitData, function callBack(unit, error, data){ 
     expect(data.statusCode).to.be.equal(200); done(); 
     }) 
})

AFTER (Works!!):

it('receives successful RPC response', async () => { 
      const getSomeData = await getResponse(unitData, function callBack(unit, error, data){ 
           expect(data.statusCode).to.be.equal(200); 
     }) 
})

**Comment by QauseenMZ** [comment]
![image](https://user-images.githubusercontent.com/20565540/57986837-e123d780-7a47-11e9-9270-398c5788bd2c.png)

**Comment by QauseenMZ** [comment]
Removing done worked for me!

BEFORE:

![image](https://user-images.githubusercontent.com/20565540/57986847-fbf64c00-7a47-11e9-8980-9368edee2aaf.png)

AFTER (Works!!):

![image](https://user-images.githubusercontent.com/20565540/57986866-2d6f1780-7a48-11e9-99e9-95c70ff8f2c5.png)

**Comment by kheengz** [comment]
**Before**
```
   before(async function (done) {
        user = new User({ ...});
        await user.save();
        done()
    });
```

**After**
```
   before(async function () {
        user = new User({ ...});
        await user.save();
    });
```
These works for me

**Comment by gkirill** [comment]
I am having the same problem, and I need to user done, because I need to test that my promise fails. So I catch it, and then calling done, but getting this error.

```
it("...", async function (done) {
  try {
    await asyncFung(...);
    done("The call should have failed")
  } catch (error) {
    if (error instanceof MyError) {
      done()
    } else {
      done(error)
    }
  }
});
```
