### ISSUE TITLE
Hope that --require option support requiring local module

### ISSUE THREAD

**Issue by xingxingted** [mochajs/mocha#2742]
When I'm trying to require some modules with mocha.opts like below
```
--require should
--require ../Utils/Logger
--recursive
```

I get the error in the stderr:
```
Error: Cannot find module '../Utils/Logger'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at E:\WebstormProjects\activity-system\node_modules\mocha\bin\_mocha:345:3
```

Why not try to support the user to require a local module not only a module from node_modules?

**Comment by ScottFreeCode** [comment]
Mocha does support this. Where is `Utils/Logger` relative to the project root? (I assume you are running Mocha from the project root, also; is this correct?)

**Comment by xingxingted** [comment]
No No, I can clearly understand the reason why I get this error and I mean, why not add a feature like what a descibe above?

**Comment by ScottFreeCode** [comment]
Humour me for a minute and try changing `../Utils/Logger` to `./Utils/Logger`.

**Comment by dosentmatter** [comment]
From my results, it seems like mocha requires the full file path name including the file extension if you are `require`ing a local module. So `../Utils/Logger.js`. If the local module was in the local directory, `Utils/Logger` works for me.
