### ISSUE TITLE
mocha test files from memory

### ISSUE THREAD

**Issue by CzBuCHi** [mochajs/mocha#2748]
any chance, that mocha is able to run tests from files, that are stored in memory-fs 'filesystem' ?

Somethig like this:
```js
const MemoryFS = require("memory-fs");
const webpack = require("webpack");
const Mocha = require('mocha');
const config = require('webpack.config.js');

// use webpack to compile tests written in typescript and store outputs in memory
const fs = new MemoryFS();
const compiler = webpack(config);
compiler.outputFileSystem = fs;
compiler.run(function (err) {
    if (!err) {
        // run tests in compiled files
        const mocha = new Mocha();
        // mocha.useFs(fs); - specify source 'filesystem'
        mocha.addFile('test.js')
        mocha.run(function (failures) {
            ...
        });
    }
});
```

**Comment by ScottFreeCode** [comment]
There's currently no support for alternatives to the real filesystem in that manner, as far as I'm aware of; however, if you're using Mocha programmatically, it's possible to copy [the code from the `loadFiles` function](https://github.com/mochajs/mocha/blob/master/lib/mocha.js#L224-L234) and tweak it to evaluate arbitrary code:
```js
const vm = require("vm");
//...
  let code = <get string representation of processed code>
  let filepath = <representation of bundled test file>
  mocha.suite.emit('pre-require', global, filepath, mocha);
  mocha.suite.emit('require', vm.runInThisContext(code), filepath, mocha);
  mocha.suite.emit('post-require', global, filepath, mocha);
```

**Comment by kunagpal** [comment]
@CzBuCHi @ScottFreeCode It appears that this question has been resolved, and could be closed.

**Comment by ScottFreeCode** [comment]
I'm actually not certain whether my VM usage is correct, off the top of my head (I know it exists but I rarely use it) -- although in theory the `loadFiles` imitation should work with *some* kind of code evaluation method, in any case... It would be nice to get confirmation from @CzBuCHi

**Comment by CzBuCHi** [comment]
@ScottFreeCode frankly, i didnt try your code - maily because it uses some internal voodoo, that can be changed in next version of mocha and its not defined in [@types/mocha](https://www.npmjs.com/package/@types/mocha) ...

Anyway, i ditch webpack and babel for unit testing (its slow for TDD) and using tsc only and these dont seems to work in memory ...

PS: Virtual fs would be nice for support files (eg when testing method, with uses fs package)

closing this for now ...

**Comment by ScottFreeCode** [comment]
Hi @CzBuCHi, thanks for the update!

I can't speak to types/mocha, and I totally get the desire to avoid undocumented functionality; but I do want to point out one thing: the events in that example aren't really as internal as they look. They're used to set up the interface, and Mocha quite specifically supports custom interfaces, so those event emissions are effectively part of the public API (albeit the portion that's missing from the readme and the website for no reason other than that nobody ever sat down and wrote it up in a user-friendy fashion... I think we even have an issue about that sitting around somewhere).

**Comment by jameshmread** [comment]
Hi,

I am attempting to do a similar thing using 'memfs' as an in memory file system. However. when adding files. Mocha cannot resolve the path because i'm assuming it looks on disk for the file it is provided with.

I tried the above method from @ScottFreeCode but I keep getting 'suite does not exist on mocha' problems. I'm using pure Typescript with TS-node.

**Comment by privatenumber** [comment]
I accomplish this by overwriting the `loadFiles` method (as @ScottFreeCode suggested) [here](https://github.com/privatenumber/instant-mocha/blob/abd1d81418832f3cc6dde43741311f5fc5fe1110/src/lib/mocha.ts#L24) in [instant-mocha](https://github.com/privatenumber/instant-mocha)
