### ISSUE TITLE
Promise does not work in combination with native addon

### ISSUE THREAD

**Issue by hollei** [mochajs/mocha#2749]
I wrote a demo application where mocha Promises do not work in combination with native node modules: https://github.com/hollei/nodejs-native-async-callback

The native addon just calls asynchronously a calback function. The mocha test just waits for the callback. If I use a Promise to wait for the callback, mocha test failes with a timeout.

See the Readme.md in the test project how to build and run the test.

**Comment by isortegah** [comment]
I have the same problem when I want to execute the request (npm request) function, the request is not launched (https://github.com/isortegah/mocha-report/blob/master/report.js), provide Promises and what Is included in the function is processed minus the request.
