### ISSUE TITLE
Mocha.utils.stringify() hangs on recursive data structures

### ISSUE THREAD

**Issue by vaskevich** [mochajs/mocha#2751]
I'm using `Chai`, and often use `assert.deepEqual()` to make sure that one object is equal to another. This works as expected, but to print out the diff, Chai uses `Mocha.utils.stringify()`. When there are recursive objects involved, however, the whole tests fails at this point, so I've had to use this fix in my tests:

```
const util = require('util');
Mocha.utils.stringify = value => util.inspect(value, {depth: 5});
```

That prevents the test from hanging, but doesn't always work as well as Mocha's stringify function.

As an example of a test that would hang, consider:

```
it('should fail', () => {
  const a = {};
  const b = {a};
  a.b = b;
  assert.deepEqual(b, {});  // Expected to fail, but instead the whole test suite hangs.
});
```

**Comment by ScottFreeCode** [comment]
I am unable to reproduce this; I get "`AssertionError: expected { a: { b: [Circular] } } to deeply equal {}`"

We do still have a few issues involving circular references, though none of them appear to involve hanging that I notice:
#2598
#2559

**Comment by vaskevich** [comment]
Ah sorry, I never bothered testing to make sure this failed. :( It appears the issue has something to do with some more complex Objects, perhaps containing getters or Proxies. Closing this for now, and will re-open if I find time to find the root cause.
