### ISSUE TITLE
Required problem : when I try require same file 

### ISSUE THREAD

**Issue by love8587** [mochajs/mocha#2757]
*--- test.js*

```
var authBlackListService = require(path.resolve('api/services/auth/blacklist'));
var authPoliceService = require(path.resolve('api/services/auth/police'));
```

*---api/services/auth/police*

```
 var authBlackListService = require(path.resolve('api/services/auth/blacklist')); 
```

*Running Result:*
```
Uncaught TypeError: authBlackListService.add is not a function
      at async.auto.addBlackList (api/services/auth/police/index.js:125:32) 
```

I don't know why the error has occurred. so I changed `blacklist` => `blackList` like below code

*--- test.js*

```
var authBlackListService = require(path.resolve('api/services/auth/blackList'));
var authPoliceService = require(path.resolve('api/services/auth/police'));
```

It's working now... I don't understand why ... anybody can explain about it ?

**Comment by drazisil** [comment]
Can you share what the `api/services/auth/blacklist` file looks like?

**Comment by love8587** [comment]
@drazisil Oh Thanks. I seem to find the issue-point almost.

**api/services/auth/blacklist**
```var helper = require(path.resolve('api/helpers')); // <=== issue-point
var l = helper.logger;
...
report() { ... }
add() { ... }
```

**api/helpers/index.js**
```
exports.logger = require('./logger');
exports.util = require('./util');
```

**api/helpers/util.js**
```
var authPoliceService = require(path.resolve('api/services/auth/police'));

module.exports.sendError = function (res, error) {
  authPoliceService.report( ... );
}
```

This must be an unintended structure.
And I think the current call-structure is strange, but I wonder exactly what causes it.

**Comment by drazisil** [comment]
This doesn't feel like a Mocha issue, but I might not understand enough of what you are doing.

**Comment by love8587** [comment]
@drazisil Yes, right. I think so. It's not a Mocha issue.
