### ISSUE TITLE
highlight regex needs to be non-greedy for string

### ISSUE THREAD

**Issue by plessbd** [mochajs/mocha#276]
in mocha.js

.replace(/('.*')/gm, '<span class="string">$1</span>')

should be

.replace(/('.*?')/gm, '<span class="string">$1</span>')

**Comment by danielstjules** [comment]
Fixed in https://github.com/mochajs/mocha/commit/ea57802fa17c4e64c41aeecae8d2f4043aa59562#diff-037110b12e45b56f6f5c48b9cf213ab6R4564 :)
