### ISSUE TITLE
How to prevent console clears when using --reporter min (-R min)

### ISSUE THREAD

**Issue by erikmellum** [mochajs/mocha#2761]
Right now I get lots of clears in my console when using the --reporter min flag. This is not desired because I am running tests as part of a gulpfile that does watching / transpiling / linting etc. The console clears really obfuscate some of the other important info that I get.

Is there any way to stop the console clears? I perused the mochajs homepage and couldn't find a way.

Thanks!

**Comment by erikmellum** [comment]
This was the closest thing I could find https://github.com/mochajs/mocha/issues/2312

**Comment by jhyman2** [comment]
I too have this problem. Any updates?
