### ISSUE TITLE
feature: better watch

### ISSUE THREAD

**Issue by paulpflug** [mochajs/mocha#2763]
Hey,

I came up for a fast and efficient way to watch all dependencies for changes for my package [autodev](https://github.com/paulpflug/autodev). I think this would be **very** suitable for mocha.

Here is the core extracted:
```coffee
# save already loaded modules as they don't need to get watched
unwatchedModules = []
for k,v of require.cache
  unwatchedModules.push k

watcher = null
busy = false

runTests = () =>
 # statemanagement if many files change in short time
 busy = true
 
 ### run the tests ###
 
 # get real dependencies of the tests
 filesToWatch = []
 for k,v of require.cache
  if unwatchedModules.indexOf(k) < 0
   filesToWatch.push k

  # use e.g. chokidar to watch all deps
  unless watcher?
    watcher = chokidar.watch filesToWatch, ignoreInitial: true
    .on "all", (e,filepath) =>
      # needs to clear cache recursivly
      # https://github.com/paulpflug/recursive-uncache
      uncache(filepath,__filename)
      unless busy
        runTests()
  else
    watcher.add filesToWatch # chokidar handles double entries
  busy = false
````

This works out of the box for coffeescript and json dependencies, zero-config.
Even local `npm link` dependencies getting watched this way - very helpful

If this pleases, this could get put behind a `--auto-watch` flag to prevent breaking stuff.

Update:
I implemented a quick and dirty wrapper: [mocha-watch](https://github.com/paulpflug/mocha-watch/) 
[relevant part](https://github.com/paulpflug/mocha-watch/blob/master/_mocha.js#L393-L465)

**Comment by juergba** [comment]
The `watch` feature has been refactored in Mocha `v7.0.0` depending on Chokidar.
