### ISSUE TITLE
Mocha not throwing error when undefined pass as callback on describe

### ISSUE THREAD

**Issue by Altiano** [mochajs/mocha#2766]
I am using mocha 3.0.2 with karma 1.3.0
This is my code

    import { notExists } from './module' 
    describe('.....', notExists)

Mocha not throwing error and my coverage increase..

**Comment by Elergy** [comment]
It looks normal for the case when you don't have the second parameter at all:
```
describe('test that should be created in the future');
```
Doc - https://mochajs.org/#pending-tests

But we probably should check `arguments.length` in `describe/it` function to be sure that a user didn't pass an undefined variable.
