### ISSUE TITLE
Supporting interactive debugger for tests

### ISSUE THREAD

**Issue by jcrben** [mochajs/mocha#2775]
I've never been able to get my debuggers or breakpoints to work inside tests. Typically using Webstorm or Intellij Ultimate. Just tried again today with node v7.7.4 and Intellij 2017.1 since I noticed that a Jetbrains developer added support for child process debugging to ava: https://github.com/avajs/ava/pull/874

Thoughts on adding this functionality, perhaps by taking a close look at ava's approach? It's also possible that this will be more widely available once https://github.com/nodejs/node/pull/5025 lands; also a feature request at https://github.com/nodejs/node/issues/9621

If this is already supported, some tips would be handy. Noticed this issue https://github.com/mochajs/mocha/issues/1091 where someone was talking about --debug-brk so maybe I'm missing something

**Comment by boneskull** [comment]
@jcrben I don't have this issue, so I'm going to need more information about your configuration.  Can you send me a project or something small & reproducible?

The only times when I do run into problems is when there are several transpilation steps.

**Comment by jcrben** [comment]
Hmm, I think it must have been something in my setup - either the project or how I was setting up the IntelliJ launch configuration. I tried reproducing it with a small test case using the VSCode Mocha Tests configuration at https://github.com/Microsoft/vscode-node-debug/blob/7dacdc985ad42e45c31d5e4a986201bc780de13c/package.json#L211 and it seems to work OK.
