### ISSUE TITLE
Hostile Custom Runner API - Silent crash

### ISSUE THREAD

**Issue by fgarcia** [mochajs/mocha#2777]
I've just noticed that my custom runner started crashing silently. The problem is that Runner errors cause Mocha to crash with an OK exit status and no error notice.

For example:

```javascript
var mocha = require('mocha');

function FooReporter(runner) {
  mocha.reporters.Base.call(this, runner);
  
  //return visual(runner)

  let count = 0
  runner.on('suite', function(test){
  })

  runner.on('pass', function(test){
    count++
    if(count > 3) throw Error('An error!')
    process.stdout.write('.')
  });

  runner.on('fail', function(test, err){
    process.stdout.write('x')
  });

  runner.on('end', function(){
    console.log()
    console.log('end!')
  });
}

module.exports = FooReporter;
```

Using the above runner will silently crash Mocha after 3 test passes. The thrown Error will not be shown and shell exit status of mocha will be 0

**Comment by ScottFreeCode** [comment]
This could be related to https://github.com/mochajs/mocha/issues/2890#issuecomment-311118312

**Comment by ORESoftware** [comment]
You mean custom reporter, not custom runner right?

**Comment by fgarcia** [comment]
My mistake. Yes I meant custom reporter. Any error inside the reporter will
cause the runner to fail silently

**Comment by fgarcia** [comment]
Closing this issue because it seems that since my report, now Mocha reporters crash with "reporter blew up with error" message and even there is a stacktrace
