### ISSUE TITLE
Mocha doesn't report pending test as inconclusive

### ISSUE THREAD

**Issue by fforjan** [mochajs/mocha#2786]
It seems mocha can only report the test as failed or passed but not inconclusive.

Proposal would be to map pending to inconclusive.
Pending is done when the skip method is called.

This would requires to introduce a new property into the testexecutor / testframework exchange data structure about skipped tests.

Any thought ?

**Comment by fforjan** [comment]
sorry, wrong project arrghhh

**Comment by ScottFreeCode** [comment]
For posterity, this appears to be an issue with Visual Studio integration: https://github.com/Microsoft/nodejstools/issues/1555

Mocha does report skipped tests as `pending`, so integrations should be able to get that just like passes/failures. Let us know if any assistance is needed finding the details!
