### ISSUE TITLE
Mocha browser test failing when i run on iOS based browsers

### ISSUE THREAD

**Issue by bipo1980** [mochajs/mocha#2792]
Hello Experts, Need your help again to run a mocha test using an html file on iOS/Safari or iOS/Chrome browser. I have tried asking the question at [SO](http://stackoverflow.com/questions/43849373) but have had not had luck. I come here sincerely hoping i am not breaking rules but hope to find a solution for the same. Much Thanks in advance.

Below is the scripts i am using. No problems if in run on Windows/Chrome.

But i get this Error when i run on iOS/Safari/Chrome: 

    "before all" hook
    SyntaxError: Unexpected identifier "a"(https://..../test/iosmodule.js:10)(https://..../node_modules/mocha/mocha.js:64) 

**ios.js**

    var mod;
    describe('suite', function(){
        before(function(done){
            requirejs.config({ baseUrl: '.', paths: { }, nodeRequire: require });
                require(['./iosmodule'], 
                    function(_mod) {
                        mod = _mod;
                        done();
                });                        
        });
        it('case', function(){
            console.log(mod.get());        
        });    
    });

**iosmodule.js**

    define([], function() {
        return {
            get: function() {
                return "Hello Node World!!!";
            }
        };
    });

**ios.html**

    <!DOCTYPE html>
    <html>
    <head>
      <title>Mocha Test</title>
      <link rel="stylesheet" href="../node_modules/mocha/mocha.css">
    </head>
    <body>
      <div id="mocha"></div>  
      <script src="../node_modules/mocha/mocha.js"></script>
      <script src="../node_modules/requirejs/require.js"></script>
      <script>mocha.setup('bdd')</script>
      <script src="./ios.js"></script>
      <script>mocha.run()</script>
    </body>
    </html>

**Comment by johnkpaul** [comment]
@drazisil Can you share a live example of this? What version of mocha/require are you using?
