### ISSUE TITLE
🚀 Feature: Test duration not shown for failed tests, but does for passed tests

### ISSUE THREAD

**Issue by aDu** [mochajs/mocha#2796]
Concerning runners, listening to 'test end' events.

For passed tests, test.duration is given in milliseconds.

However, when there is a failed test, test.duration is not defined.

Why is that? Can test.duration be implemented for failing tests?

Thanks in advance! =)

**Comment by Elergy** [comment]
Hey @AlanDu50,

Could you please provide some information about how you run tests (a sample of code would be helpful) because I tried to reproduce the situation and couldn't do that [here](https://github.com/mochajs/mocha/issues/2834)

Thanks!

**Comment by BrandonZacharie** [comment]
I think I'm seeing this as well...

![Screen Shot 2019-09-19 at 16 55 54](https://user-images.githubusercontent.com/27306/65289197-9ce03b00-dafe-11e9-855a-b60282d7a8c2.png)

The test that was run after the test that failed somehow had `duration` undefined. I placed that log statement on the first line in `runner` callback...

![image](https://user-images.githubusercontent.com/27306/65289361-27289f00-daff-11e9-9e9f-01d0a2f86f10.png)

🤷🏾‍♂️

**Comment by JoshuaKGoldberg** [comment]
I don't know what to make of this issue 😞 nobody ever posted a full reproduction. So I'm going to close it as stale.

But if someone is facing this, please do file a new issue with one of our new issue templates. They prompt for the info needed to diagnose problems.

Cheers, all! ☕
