### ISSUE TITLE
I get this: /usr/bin/env: ‘node\r’

### ISSUE THREAD

**Issue by theofilis** [mochajs/mocha#2799]
I run this `mocha --recursive` at Ubuntu 16.04, and I get this output:
```
/usr/bin/env: ‘node\r’: No such file or directory
npm ERR! Test failed.  See above for more details.
```
I use mocha@3.4.0

There is problem with line ending, you should use UNIX like version instead of Windows one.

**Comment by JigSawFr** [comment]
the same problem, no issue before today.

**Comment by pollx** [comment]
Same here

**Comment by nweinstein7** [comment]
Seeing this as well

**Comment by theofilis** [comment]
I resolved this issue converting the line ending from DOS to UNIX format.
In vim I used this command:

`vim node_modules/.bin/mocha` then I run this command on vim `:set ff=unix`

**Comment by ScottFreeCode** [comment]
This is what I get for releasing from Windows to work around git problems on my Linux box. Give me just a minute and I'll fix it...

**Comment by stevenvachon** [comment]
Reverting to 3.3.0 as 3.4.0 was not correctly tested. Please add OS X to travis.yml and test on Windows with AppVeyor from now on.

**Comment by LeoColomb** [comment]
Ha ha, v3.4.0 breaks a lot of build! 😸 
https://github.com/search?q=An+in-range+update+of+mocha+is+breaking+the+build&type=Issues&utf8=%E2%9C%93

Anyway, thanks for maintaining mocha! 💌

**Comment by ScottFreeCode** [comment]
This should now be fixed in 3.4.1

Despite the fact that we already have both Linux and Windows testing, git's autocrlf behavior busted the line endings in the copy of the file that actually got published -- if anyone knows a way to programmatically prevent such issues please let us know.

**Comment by stevenvachon** [comment]
Prepublish script that analyzes all files.

**Comment by remotezygote** [comment]
There's a discussion (admittedly without much discussion yet) about this issue and how it relates to NPM here: https://github.com/npm/npm/issues/13203 (wanted to be sure that link was established between repos/issues)

**Comment by ScottFreeCode** [comment]
@stevenvachon Good idea -- I'll see what options there are for determining the line endings of files given Mocha's expected development environment (something built into NPM would be ideal I suppose, but otherwise Git or Node would be next best, and if all else fails it wouldn't be the first thing for which we rely on some posixy command...).

@remotezygote Thanks, I was just wondering why NPM doesn't already sanitize this. 😆 

And @ all, sorry about the snafu/panic there; hopefully as we shift to more regular releases and more participation from our team we'll get these kinks ironed out such that everything's safer in the future.

**Comment by ScottFreeCode** [comment]
Does anybody know if there's a way to prompt all those Greenkeeper instances to pick up 3.4.1 (or to do so faster)?

**Comment by LeoColomb** [comment]
> Does anybody know if there's a way to prompt all those Greenkeeper

Ping @greenkeeperio-bot people: @finnp, @boennemann @christophwitzko

**Comment by LeoColomb** [comment]
@ScottFreeCode 
FYI, Greenkeeper is commenting every issues with 3.4.1 update review.
Example: https://github.com/jeffjewiss/broccoli-postcss/issues/97#issuecomment-301349110

**Comment by ScottFreeCode** [comment]
> This is an interesting case, since more than 1,000 issues are opened for this "bad" version (and counting...).

Sometimes it's scary just how widely depended-upon Mocha is. 😆 That and how fast some of the automated elements of the ecosystem pick these things up. Definitely a bit nerve-wracking for us all...
