### ISSUE TITLE
Intermittent EPERM when running the test suite on Windows

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mocha#2804]
https://github.com/mochajs/mocha/blob/0a93024b475e58e75c5def6b2f5228bd363874de/test/integration/reporters.spec.js#L53 gets a spurious EPERM error trying to unlink the temporary file about half the time. Should we try graceful-fs here? Or would it suffice to try-catch the error and make multiple unlink attempts if necessary?

**Comment by juergba** [comment]
outdated
