### ISSUE TITLE
scrolling sidebar

### ISSUE THREAD

**Issue by tj** [mochajs/mocha#282]
if you have lots of files and a small screen this is no good

**Comment by danielstjules** [comment]
This one had never been fixed. Will submit a PR.

**Comment by danielstjules** [comment]
I lied - the menu uses `overflow-y`.

```css
#menu {
  position: fixed;
  font-size: 12px;
  overflow-y: auto;
```

The styles in the generated coverage report found at http://mochajs.org/coverage.html are just outdated. So this problem was resolved! :)
