### ISSUE TITLE
test cov docs

### ISSUE THREAD

**Issue by tj** [mochajs/mocha#283]
for setup since you can't (easily) do it transparently with node anymore

**Comment by danielstjules** [comment]
The site includes a section highlighting coverage:

![screen shot 2015-03-08 at 1 47 55 pm](https://cloud.githubusercontent.com/assets/817212/6547594/ce6b0396-c599-11e4-9a47-b987df9f97ff.png)

The linked express commit presented as an example is https://github.com/strongloop/express/commit/b6ee5fafd0d6c79cf7df5560cb324ebee4fe3a7f Furthermore, the wiki features a section on test coverage: https://github.com/mochajs/mocha/wiki#test-coverage. 

Hope you don't mind if I close this one too. :)
