### ISSUE TITLE
Mocha 3.4.2 | Error: Resolution method is overspecified. Specify a callback *or* return a Promise; not both.

### ISSUE THREAD

**Issue by skumar568** [mochajs/mocha#2833]
Hi,

Even though issue #2407 and #2413 are closed, I am still getting same error with mocha 3.4.2.

Thanks,
Sanjeev

**Comment by fearphage** [comment]
Is this a bug? It seems odd to return a promise *and* pass a callback. Why not choose one? Wouldn't changing `return promise.then` to `promise.then` in your test(s) fix this?

**Comment by skumar568** [comment]
aah...Thanks for pointing this.

It does work!
