### ISSUE TITLE
normalize test timeouts

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2837]
Various tests generally produce "slow" warnings.  The "slow" threshold is based on a fraction of the timeout setting, unless it is otherwise supplied.

The timeout setting is set to a default of 200ms as per [mocha.opts](https://github.com/mochajs/mocha/blob/master/test/mocha.opts#L7).  This is *generally* OK for unit tests, but inappropriate for anything invoking Mocha itself.

However, there are various overrides in `Makefile` and the test files themselves; let's find a single place to put them all, and avoid one-off settings, if possible.

It's important to note that our tests run much more slowly on AppVeyor.  That should be the baseline for timeout values--not your MacBook Pro. :wink:

**Comment by ScottFreeCode** [comment]
Seems like #2597 and this are duplicates of each other?

**Comment by juergba** [comment]
closing, see #3539.
