### ISSUE TITLE
fix broken phantomjs test execution

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2840]
At some point we wound up running PhantomJS v2.x, which is why 93392ddb061e6870eb3fc524a7eff600c881cef3 happened.

But this was erroneous--we should still be running PhantomJS v1.9.8 to assert compatibility.  And no, I still can't run that version on macOS Sierra.

93392ddb061e6870eb3fc524a7eff600c881cef3 should be reversed.  [karma-phantomjs-launcher](https://npm.im/karma-phantomjs-launcher) installs PhantomJS v2.x [since v1.0.1](https://github.com/karma-runner/karma-phantomjs-launcher/commit/9ae8ada4e59c38a2c4d47041bd13e4be56816091), and I think this doesn't play nicely with npm v4+.  It should be downgraded.

**Comment by boneskull** [comment]
Also we're missing `process.stdout` in the browser tests, for some reason.

**Comment by ScottFreeCode** [comment]
When I ran Mocha's tests the other week, I wondered why it downloaded Phantom twice! Good to see this addressed...

Is it possible we could add a check into our tests that would ensure only the `1.9.8` instance is being used, to prevent this from regressing?
