### ISSUE TITLE
diffing has non-obvious output when expected and actual stringify identically

### ISSUE THREAD

**Issue by SaarLevy** [mochajs/mocha#2844]
I execute this code:

        const v1 = vector.Vector(1,1);
        const v2 = vector.Vector(1,1);
        assert.deepEqual(v1, v2);

with this command `mocha --inline-diffs`
  
and get this error:

      AssertionError: { x: 1,
      y: 1,
      magnitude: [Function: magnitude],
      mult: [Function: mult] } deepEqual { x: 1,
      y: 1,
      magnitude: [Function: magnitude],
      mult: [Function: mult] }
      actual expected

      1 | {
      2 |   "magnitude": [Function]
      3 |   "mult": [Function]
      4 |   "x": 1
      5 |   "y": 1
      6 | }

[http://imgur.com/KbMoaix](url)
^Image of output

Why am I not getting two different object with color highlighting?

**Comment by ScottFreeCode** [comment]
What does it show when used without `--inline-diffs`?

**Comment by SaarLevy** [comment]
same thing up to the 'actual expected' line, not even one object.

I actually solved this in a hacky way by asserting both the X and Y values of the vectors separately  but I'm still annoyed that I cannot assert a whole object and have to check 2 different values. The issue still stands

**Comment by ScottFreeCode** [comment]
Thanks; I just wanted to confirm whether this is an issue with `--inline-diffs` specifically, or a more general issue; sorry I wasn't clearer about that to begin with.

So it sounds as though what's happening here is that our diffing system as a whole doesn't currently have a way to represent the difference between two objects that happen to deep loosely equal that get thrown by a strict equality comparison. Does that seem accurate to you? (We'll have to double-check the code and make sure that there isn't supposed to be a way that's handled that just happens not to be getting triggered correctly anymore; if there's not, we'll have to discuss how to represent "the expected and actual objects look the same except for having different object reference identities".)

**Comment by SaarLevy** [comment]
Sounds accurate. 
Also I'm pretty certain that it's a feature that's not triggered correctly and not a feature to be added since it does say "actual expected". Unless I misunderstood the error prompts' intention.

**Comment by ScottFreeCode** [comment]
The "actual expected" prompt would typically guide viewing the difference between the expected value and the actual value when there's a difference to show. For instance:
```js
it("dummy example", function() {
  assert.deepEqual([1,2,3], [0,1,2])
})
```

(On the CLI there would also typically be coloring of the actual/expected differences -- in `--inline-diffs` the coloring is the only differentiator.)
```txt
  1)  dummy example:

      AssertionError [ERR_ASSERTION]: [ 1, 2, 3 ] deepEqual [ 0, 1, 2 ]
      + expected - actual

       [
      +  0
         1
         2
      -  3
       ]
```

**Comment by ScottFreeCode** [comment]
Looking more closely at the assertion in the original example, I'm getting a sense that this is actually objects that are not thrown because they're strictly unequal but rather because they're loosely unequal due to different function closures in their members, but the diff isn't showing any difference because the functions stringify the same. I'm not too familiar with the implementation of the diffing code though, so that's just a hunch...

**Comment by ScottFreeCode** [comment]
Yeah, based on a quick set of test cases, either of those situations will get this lack of diff presentation:
```js
var assert = require("assert")

it("strictly unequal but loosely equal", function() {
  assert.strictEqual([0,1,2], [0,1,2])
})

it("loosely unequal but same stringification", function() {
  assert.deepEqual(function foo() {}, function bar() {})
})
```

> node_modules/.bin/mocha

```txt
  1)  strictly unequal but loosely equal:

      AssertionError [ERR_ASSERTION]: [ 0, 1, 2 ] === [ 0, 1, 2 ]
      + expected - actual


      at Context.<anonymous> (test\test.js:4:10)

  2)  loosely unequal but same stringification:

      AssertionError [ERR_ASSERTION]: [Function: foo] deepEqual [Function: bar]
      + expected - actual


      at Context.<anonymous> (test\test.js:8:10)
```

> node_modules/.bin/mocha --inline-diffs
```txt
  1)  strictly unequal but loosely equal:

      AssertionError [ERR_ASSERTION]: [ 0, 1, 2 ] === [ 0, 1, 2 ]
      actual expected

      1 | [
      2 |   0
      3 |   1
      4 |   2
      5 | ]

      at Context.<anonymous> (test\test.js:4:10)

  2)  loosely unequal but same stringification:

      AssertionError [ERR_ASSERTION]: [Function: foo] deepEqual [Function: bar]
      actual expected

      [Function]

      at Context.<anonymous> (test\test.js:8:10)
```
(no coloring in terminal output of `--inline-diffs` mode to indicate difference either)

**Comment by SaarLevy** [comment]
Thanks a lot for the help. Hope someone will take up the challenge to fix this.

**Comment by boneskull** [comment]
Before someone can fix it, we'll need to determine what it *should* be showing.

This is [why](https://github.com/nodejs/node/blob/master/lib/assert.js#L158) two different empty functions will throw.  It is because functions are treated as primitives (for better or worse).  I am not sure which coercions happen in which order to compare `(function () {}) == (function () {})`, which is `false`.

**Comment by boneskull** [comment]
This is `needs-feedback` because we need a suggestion on how to display the difference.

**Comment by JoshuaKGoldberg** [comment]
It's been several years with no concrete suggestion. Per #5027 we're not looking to shake things up significantly. If someone wants to file a new issue with a clear suggestion on next steps, please do - that'd be great. Cheers!
