### ISSUE TITLE
npm test doesn't work from WebStorm interface

### ISSUE THREAD

**Issue by Elergy** [mochajs/mocha#2845]
WebStorm provides an interface to run tests by click:

![image](https://cloud.githubusercontent.com/assets/2610768/26600380/862a0d62-4584-11e7-9bf8-bfa1f43b5b59.png)

But when I run tests this way, one of them is broken, because WebStorm's console prints colored text:

```
1) Mocha should not output colors to pipe:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at test/color.spec.js:15:7
      at ChildProcess.exithandler (child_process.js:204:7)
      at maybeClose (internal/child_process.js:827:16)
      at Socket.<anonymous> (internal/child_process.js:319:11)
      at Pipe._onclose (net.js:477:12)
```

**Comment by Elergy** [comment]
There is one more problem with WebStorm: https://github.com/mochajs/mocha/issues/2775

**Comment by boneskull** [comment]
@Elergy Interesting.  It's not the console, because running `npm test` in a console from WebStorm doesn't exhibit this behavior.  Anyway, I would probably file this at youtrack.jetbrains.com

**Comment by Elergy** [comment]
@boneskull I debugged this behavior and found that if we run code inside WebStrom's npm-test console:
1. `process.stdout.isTTY` is always `true`
2. `process.env.FORCE_COLOR` is always `true`

Therefore `supports-color` library tells us that the console supports colors (and it's true).
Then we wrap the strings we want to log into ANSI-escape-colors

How do you think, can it be a problem for users or it can affect only Mocha-contributors?
