### ISSUE TITLE
mocha/test/browser/index.html doesn't find array.js

### ISSUE THREAD

**Issue by PopradiArpad** [mochajs/mocha#2849]
**Reproducing:**
open mocha/test/browser/index.html with Chrome Dev Tools :
![mocha_index_array](https://cloud.githubusercontent.com/assets/4144816/26638463/7a671238-4622-11e7-94df-6bd89df85bed.png)

**Comment by ScottFreeCode** [comment]
Looks like this was fixed in #2850?
