### ISSUE TITLE
Mocha making uncaughtExceptions unreadable

### ISSUE THREAD

**Issue by jmwilkinson** [mochajs/mocha#2852]
Version 3.4.2

Given the following file with a syntax error:

```
let a = {1,2,3}
```

If this file is run with mocha, it outputs this completely unreadable block of text:

>error: uncaughtException: Unexpected token , date=Wed May 31 2017 16:10:09 GMT-0700 (PDT), pid=22316, uid=26283, gid=100, cwd=/home/redacted/dev/workspace/example/packages/example-project, execPath=/usr/bin/node, version=v6.10.3, argv=[/usr/bin/node, /usr/lib/node_modules/mocha/bin/_mocha, test/, --recursive], rss=26505216, heapTotal=18911232, heapUsed=9472600, external=108709, loadavg=[0.0771484375, 0.07080078125, 0.072265625], uptime=5424230, trace=[column=10, file=vm.js, function=createScript, line=56, method=null, native=false, column=10, file=vm.js, function=Object.runInThisContext, line=97, method=runInThisContext, native=false, column=28, file=module.js, function=Module._compile, line=542, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=579, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=487, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=446, method=null, native=false, column=3, file=module.js, function=Function.Module._load, line=438, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=497, method=require, native=false, column=19, file=internal/module.js, function=require, line=20, method=null, native=false, column=27, file=/usr/lib/node_modules/mocha/lib/mocha.js, function=null, line=222, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=14, file=/usr/lib/node_modules/mocha/lib/mocha.js, function=Mocha.loadFiles, line=219, method=loadFiles, native=false, column=10, file=/usr/lib/node_modules/mocha/lib/mocha.js, function=Mocha.run, line=487, method=run, native=false, column=18, file=/usr/lib/node_modules/mocha/bin/_mocha, function=, line=459, method=null, native=false, column=32, file=module.js, function=Module._compile, line=570, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=579, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=487, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=446, method=null, native=false, column=3, file=module.js, function=Function.Module._load, line=438, method=Module._load, native=false, column=10, file=module.js, function=Module.runMain, line=604, method=runMain, native=false, column=7, file=bootstrap_node.js, function=run, line=390, method=null, native=false, column=9, file=bootstrap_node.js, function=startup, line=150, method=null, native=false, column=3, file=bootstrap_node.js, function=null, line=505, method=null, native=false], stack=[/home/redacted/dev/workspace/example/packages/example-project/test/unit/lib/test_consumer.js:19, let a = {1,2;3},           ^, SyntaxError: Unexpected token ,,     at createScript (vm.js:56:10),     at Object.runInThisContext (vm.js:97:10),     at Module._compile (module.js:542:28),     at Object.Module._extensions..js (module.js:579:10),     at Module.load (module.js:487:32),     at tryModuleLoad (module.js:446:12),     at Function.Module._load (module.js:438:3),     at Module.require (module.js:497:17),     at require (internal/module.js:20:19),     at /usr/lib/node_modules/mocha/lib/mocha.js:222:27,     at Array.forEach (native),     at Mocha.loadFiles (/usr/lib/node_modules/mocha/lib/mocha.js:219:14),     at Mocha.run (/usr/lib/node_modules/mocha/lib/mocha.js:487:10),     at Object.<anonymous> (/usr/lib/node_modules/mocha/bin/_mocha:459:18),     at Module._compile (module.js:570:32),     at Object.Module._extensions..js (module.js:579:10),     at Module.load (module.js:487:32),     at tryModuleLoad (module.js:446:12),     at Function.Module._load (module.js:438:3),     at Module.runMain (module.js:604:10),     at run (bootstrap_node.js:390:7),     at startup (bootstrap_node.js:150:9),     at bootstrap_node.js:505:3]

On the other hand, running the file with just node gives us this clear and useful output:

```
let a = {1,2,3}
          ^
SyntaxError: Unexpected token ,
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
```

If anything, mocha should make error reporting clearer, not obfuscate the problem. At the very least, there should be an option to disable error reporting for uncaughtExceptions.

>

**Comment by ScottFreeCode** [comment]
I'm unable to reproduce this with a fresh project just containing a test file with `let a = {1,2,3}` and a local install of Mocha 3.4.2 -- and "uncaught exception" isn't a typical result of syntax errors in a file in any case, which suggests that there's more going on in your Mocha run than I'm seeing here. Could you provide a [complete (but still minimal) example](https://stackoverflow.com/help/mcve) I can run to see this? Thanks!

**Comment by jmwilkinson** [comment]
Thanks for the response. I an entirely new and separate test file and also could not reproduce it. So I am not sure what is happening in my main project... clearly there is more going on than I thought. I'll close this as I cannot reproduce in a completely clean environment.

**Comment by ScottFreeCode** [comment]
Ok; feel free to ask any questions you need to help track it down!
