### ISSUE TITLE
Don't depend on macaddress

### ISSUE THREAD

**Issue by stevenvachon** [mochajs/mocha#2853]
[This issue](https://github.com/scravy/node-macaddress/issues/7) is almost a year old.

**Comment by ScottFreeCode** [comment]
As far as I can tell Mocha does not depend on macaddress. When I `npm i mocha` and then `npm ls macaddress`, or `git clone <mocha> .` then `npm i` and then `npm ls macaddress`, I get no results. It is likely a dependency of some other testing tool you are using in combination with Mocha, but feel free to let us know what you can find out.

**Comment by stevenvachon** [comment]
Hmm, yeah, I can't reproduce the [old] error anymore. Thank you.
