### ISSUE TITLE
Exit code and test summary clarity request

### ISSUE THREAD

**Issue by ubershmekel** [mochajs/mocha#2855]
Maybe I'm the only one who does this but when npm told me that

```
npm ERR! api@1.0.0 test: `mocha --compilers js:babel-core/register --recursive --colors`
npm ERR! Exit status 40
```

And then
```
npm ERR! api@1.0.0 test: `mocha --compilers js:babel-core/register --recursive --colors`
npm ERR! Exit status 5
```

I started googling for the exit code meanings e.g. "mocha exit code 40". I expected one of them to mean that the tests had an unhandled exception, perhaps the other had an unawaited promise, maybe there was another for failed tests, and another for warnings. Maybe it was a bit mask. I don't know. I would never have guessed that it's the amount of tests failed until I googled and found this:

https://github.com/mochajs/mocha/issues/2438

I assumed there was no output depicting the amount of tests failing because it was buried in between the full test output and the failure output. Which brings me to the feature request. Please print the total succeeded/failed summary at the very bottom of the output. Also more prominent banners between sections would be nice.

I would request that the exit code was just 1 when the tests fail, but I believe that will break backwards compat more than it's worth.

**Comment by mlucool** [comment]
Agreed. The code [here](https://github.com/mochajs/mocha/blob/2bc9c4d1d638c8a95250757dd23724f788918abe/lib/runner.js#L831) is the problem. Mocha should not co-opt a well known mechanism of [error codes](http://www.thegeekstuff.com/2010/10/linux-error-codes) to mean something else. This is confusing.

**Comment by boneskull** [comment]
this is useful for users in certain CI environments.

**Comment by mlucool** [comment]
I think it would be better to let people opt in to this feature or enable another way of getting this data rather than use error code as a counter. It makes integration with other software hard.

**Comment by boneskull** [comment]
feel free to send a PR which hides the behavior behind a flag, but it will need to be opt-out for now.
