### ISSUE TITLE
After Node 8 release, "after" hook issue

### ISSUE THREAD

**Issue by bitinn** [mochajs/mocha#2857]
I am not sure whether Node 8.0.0 broke Mocha or Node broke itself, but here is my problem:

- For [node-fetch](https://github.com/bitinn/node-fetch) we use mocha `before` and `after` hook to launch and stop a simple local test server. [The code is deliberately simple](https://github.com/bitinn/node-fetch/blob/1.x/test/server.js#L11-L29).

```javascript
function TestServer() {
	this.server = http.createServer(this.router);
	this.port = 30001;
	this.hostname = 'localhost';
	this.server.on('error', function(err) {
		console.log(err.stack);
	});
	this.server.on('connection', function(socket) {
		socket.setTimeout(1500);
	});
}

TestServer.prototype.start = function(cb) {
	this.server.listen(this.port, this.hostname, cb);
}

TestServer.prototype.stop = function(cb) {
	this.server.close(cb);
}
```
- As you can see there is a `stop()` method that invokes `server.close()` with callback. [This is how we actually use them](https://github.com/bitinn/node-fetch/blob/1.x/test/test.js#L32-L40).

```javascript
describe('node-fetch', function() {

	before(function(done) {
		local = new TestServer();
		base = 'http://' + local.hostname + ':' + local.port;
		local.start(done);
	});

	after(function(done) {
		local.stop(done);
	});

//...

});
```

**Now my issue:** after Node 8.0.0 release, we realise what was working before now [leaves an error on Travis CI](https://travis-ci.org/bitinn/node-fetch/jobs/238990964#L321).

> 1) node-fetch "after all" hook:
> Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

I can't imagine closing a server would take that long, so my guess is either:

- Node 8.0.0 somehow changed how fast server is closed.
- Mocha `done()` in `after` hook is somehow broken.
- Travis CI is fucked up (I have tried restarting the job, same result).

If anyone have been experimenting with this, please let me know, thx!

**Comment by boneskull** [comment]
`net.Server.close()` only closes when there are no more connected sockets.  In my poking at your code (in Node.js 8), I see a nonzero number of connected sockets upon execution of "after all".  I'll leave it to you to figure out how to stop that from happening.  :wink:

**Comment by bitinn** [comment]
interesting, this was not a problem in any previous version of Node (all the way back to  0.10). I will have to look deeper then.

(From my phone)

**Comment by bitinn** [comment]
For prosperity: Node 8 introduces a keep-alive pool and it now properly waits for connections to timeout before closing server, which is why we now have this problem.

(I choose to set server.keepAliveTimeout to a lower number, for the purpose of our tests it's ok.)

ref: https://github.com/nodejs/node/issues/2642
