### ISSUE TITLE
🛠️ Repo: Automate tests in browser HTML files

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mocha#2862]
Our test suite contains a folder "browser" full of HTML files. The ones I've seen typically take other test files (which are run by our automated process) and demonstrate using them manually in the browser. It would be great to find a way to programmatically test these pages, however -- the tests themselves are covered under Karma/Sauce, but the way of including them in an HTML page with the HTML reporter would be great to have an automated test for.

**Comment by JoshuaKGoldberg** [comment]
I don't see these files in the repo anymore. Aged away, I suppose.
