### ISSUE TITLE
replace uses of should with expect.js

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2882]
Most of the tests are written using expect.js or assert.  A small handful are using [should](https://npm.im/should), which requires ES5.

I can't determine any reason why we're using multiple assertion libraries other than to assert we can use multiple assertion libraries.  If that's the case, we should be explicit about it instead.

Currently we have some failing tests because of f20de56637b2223f614ce40adc0d41a58030f042, which passed CI due to false positives (see #2867).

**Comment by boneskull** [comment]
Actually it's used in many places.  Ugh.

**Comment by boneskull** [comment]
...and we can't get away from it completely, because of how it handles assertion failures.  We can't test diffs properly w/ `expect.js`, because it doesn't add any nice metadata to its `Error` objects?

I *can* remove it from the unit tests, though.

**Comment by boneskull** [comment]
This is in the same branch as PR #2868 because they are both needed to get the build passing.

**Comment by ScottFreeCode** [comment]
I wouldn't mind getting rid of `should` altogether and testing diffs explicitly using something like this (could be put in a helper function if need be):
```js
var error = new Error("message");
error.expected = "whatever was expected";
error.actual = "whatever was actually there";
throw error;
```

**Comment by ScottFreeCode** [comment]
> We can't test diffs properly w/  expect.js , because it doesn't add any nice metadata to its  Error  objects?

Actually, for the record, `expect.js` adds everything needed for diffs just fine. Diffs aren't displayed by the Karma reporter. They're displayed by Mocha's own non-Karma reporters.

We should open an issue for diff-printing at the Karma reporter instead.
