### ISSUE TITLE
gather anonymous usage metrics

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2884]
Before anyone jumps down my neck, this would be strictly **opt-in**, like Yeoman.  Some of you may hate this idea anyway.  That said, I think it's important to be transparent about what information we'd be gathering and why it's useful.

In a nutshell, we should know *where* Mocha is being used, and *how* it's used.  This will inform how we spend maintenance resources.

For example:

We want to know what *language* users of Mocha speak in order to start thinking about translating documentation and i18n.  Off the top of my head, there are two ways to gather this.  One is detecting the language via browser or command-line environment.  Another is GeoIP.

I don't need the IP addresses of anyone, but it'd be helpful to have an idea of what country, so we could guess at the native language of a Mocha user.  VPN usage will dirty this data.  Likewise, not every user configures their OS or browser to use their native tongue. 

These are imperfect solutions, but they are better than what we currently have, which is nothing.

* * *

Another is "what environment is Mocha running in?"  If it's a browser, which one?  If it's Node.js, which version?  What tools is it used with?  Are we using Babel or TypeScript alongside it?  What assertion library?

A useful question (which may not be answerable) is "are we running unit tests or functional tests?"

How do users structure their tests?  How many tests do they run?  How many people actually use the QUnit interface or Nyan reporter??

What percentage of our users are using Mocha to test proprietary codebases?

* * *

It's possible we could query GitHub or use BigQuery and get at *some* of this information by analyzing public repositories.  It'd be cool to chat with a data scientist if anybody knows one.  ;)

Insofar as implementation details, we will need a data store.  Yeoman consumes Google Analytics, which I'd rather *not* use.  This has the potential to be a substantial amount of data; it might be cost-prohibitive to run our own, say, Graphite server.

Be sure to disable if Travis, Jenkins, Snap, TeamCity, Bamboo, Circle CI, etc., is encountered.

**Comment by j-f1** [comment]
Also, maybe `$TERM_PROGRAM` to see what terminal emulators people are using.

**Comment by juergba** [comment]
Issue has been inactive for years, closing.
