### ISSUE TITLE
Not able to run Mocha tests with node-schedule npm module

### ISSUE THREAD

**Issue by manikumar446** [mochajs/mocha#2887]
I've setup a suite of tests in mocha using Sinon and Chai.
What I'm aiming for is that the tests will run daily and then email the results to my team.
So I installed below npm modules,
--> node-schedule: To run tests daily
--> mocha-runner-reporter: To send the test report as email.

The tests are all running and sending email as expected only first time. From second time on wards it's neither running the tests nor sending email. I have attached the sample project as well.
i'd appreciate any suggestions.

[Samplecode.zip](https://github.com/mochajs/mocha/files/1079754/Sample.code.zip)

**Comment by ScottFreeCode** [comment]
I'm not familiar with mocha-runner-reporter, but if it uses Mocha's programmatic API and isn't doing anything to work around [Mocha's known issues with running the programmatic API multiple times](https://github.com/mochajs/mocha/issues/2176#issuecomment-305340676) then you might have to apply some of those workarounds yourself if possible (e.g. see if it works if you clear the require cache before each run). Let me know if that works for you!

**Comment by manikumar446** [comment]
@ScottFreeCode Thank you for the reply. I have tried all workarounds mentioned in above comment. [This work around](https://github.com/mochajs/mocha/issues/995#issuecomment-261752316) solved my problem.

**Comment by ScottFreeCode** [comment]
Awesome! Glad that worked.

I'm going to go ahead and close this since we have those other issues for the same problem already, but feel free to participate there if you have any new ideas, suggestions or questions!

**Comment by hemanh27** [comment]
@manikumar446 Could you post your updated or modified sample code if possible. Still facing the issue.
