### ISSUE TITLE
Doesn't colorize output in Git Bash terminal

### ISSUE THREAD

**Issue by wzup** [mochajs/mocha#2888]
**bash.exe**
Apparently colors work right:

![mingw64__c_2017-06-16 12 47 10](https://user-images.githubusercontent.com/3880497/27212372-3014bab0-5292-11e7-86b3-a607c0137f69.png)

**git-bash.exe**
Doesn't colorize output:

![mingw64_ 2017-06-16 12 48 13](https://user-images.githubusercontent.com/3880497/27212398-5a8a9580-5292-11e7-9fa6-a4d7d25be7e9.png)

Why is it happening? How to fix it? I use `git-bash.exe` in my work, so it wold be great if you explain how to fix the issue.

**Comment by ScottFreeCode** [comment]
I don't know the exact criteria off the top of my head, but there are heuristics such as `is-a-tty` that Mocha (and most colored commandline programs) use to tell when it's safe to provide color by default; in some cases those end up ambiguous or just incorrect and the program has to play it safe. Without looking into it more deeply I couldn't tell you for sure whether that's happening here, or whether there's a bug in git-bash, or in Mocha.

*However!* What I can say right now is that Mocha has a `--colors` option (or maybe it's `--color`; try both and see which one works) to override that and try to use color anyway.

**Comment by GuillaumeLeclerc** [comment]
I think it can be fixed just by:

`export  TERM=xterm-256color`

**Comment by peterjmartinson** [comment]
I use mintty 2.0.3 via Git for Windows, and was having this problem.  As @ScottFreeCode pointed out, `mocha --colors` solved this issue for me.
