### ISSUE TITLE
How to bail only failed describe() in nested describe() ?

### ISSUE THREAD

**Issue by shashikumarraja** [mochajs/mocha#2894]
My test structure is as follows
```
describe('Test Suite'){
     describe('First Test Case'){
        it('1st step'){};
        it('2nd step'){};
        it('3rd step'){};
    }
     describe('SecondTest Case'){
        it('1st step'){};
        it('2nd step'){};
        it('3rd step'){};
    }
}
```
I want to use --bail such that if inside **First Test Case** any it() fails then that describe() should be bailed.But the **Second Test Case** should run.

I am getting the expected result by using:

```
describe('Test Suite'){
     this.bail(false)
     describe('First Test Case'){
        this.bail(true);
        it('1st step'){};
        it('2nd step'){};
        it('3rd step'){};
    }
     describe('SecondTest Case'){
        this.bail(true);
        it('1st step'){};
        it('2nd step'){};
        it('3rd step'){};
    }
}
```
Is there any other way to do it without explicitly assigning bail to true in each describe()?

**Comment by artyomtrityak** [comment]
That would be awesome to have such option like `--bail-describe`. It's often does not make sense to continue current describe if any test case fails but still make sense to go to another one.

**Comment by boneskull** [comment]
does `this.bail()` in `beforeEach()` or `before()` work?

**Comment by artyomtrityak** [comment]
I would vote to re-open it. It does not work in beforeEach / before

**Comment by artyomtrityak** [comment]
I found work-around, maybe it will help:

In setup file:
```js
const FAILED_TESTS = {};
// Skip test if first test from folder failed
beforeEach(function() {
  if (FAILED_TESTS[this.currentTest.file]) {
    this.skip();
  }
});

afterEach(function() {
  if (this.currentTest.state === "failed") {
    FAILED_TESTS[this.currentTest.file] = true;
  }
});
```

**Comment by coder-mike** [comment]
If you only need to bail from the particular `describe` (and not the file per se), the following work-around also works (inspired by @artyomtrityak's work-around):
```js
let failed = false;
// Skip test if any prior test in this describe failed
beforeEach(function() { failed && this.skip() });
afterEach(function() { failed = this.currentTest.state === "failed" });
```
