### ISSUE TITLE
suppress stdout from test cases

### ISSUE THREAD

**Issue by defunctzombie** [mochajs/mocha#290]
Something nice to have would be a way to silence the stdout from the tests themselves (not the reporters). That way if I have trace output in my program I can easily suppress it to see some nice test output :)

**Comment by biern** [comment]
I've implemented a mocha reporter that captures (and hides) stdout and stderr during tests. It then displays the captured output only of the failed tests alongside their error messages. For me it significantly increases readability of a test report.

Internally it just mocks `process.stdout` so it should work with most third party libraries out there.

Maybe you'll find it useful: https://github.com/biern/mocha-dd-reporter

**Comment by marcopelegrini** [comment]
Nice job @biern , this is much better than the `mocha-suppress-logs`
