### ISSUE TITLE
Print debug logs in CI

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mocha#2903]
In Node CI tests, we should consider setting `DEBUG=mocha:*` to get the `debug` logs, if it won't interfere too much with the reporter output (and if we can find a way to deactivate it for integration tests without breaking Node 0.10, see #2897).

In browser CI tests... I don't know, we are currently suppressing the `debug` module using the `browsers` entry in `package.json`; most likely we can't just stop doing that because `debug` might not support all the old browsers Mocha supports, but maybe we could selectively convince Browserify to *not* do it for the `BUILDTMP` build *and* activate `mocha:*` for debug logging in Karma?

Why is this worth looking into? **I believe getting these logs in the browser runs will show us a message that is being suppressed about #2890.**

**Comment by juergba** [comment]
This issue is inactive, oudated and IMO without any clear benefit, closing.
