### ISSUE TITLE
Before/After middleware

### ISSUE THREAD

**Issue by henit** [mochajs/mocha#2905]
I would like to reduce repeatedly used before/after hooks like:

    describe('...', () => {
        before(() => {
            StartSomething();
        });
        after(() => {
            StopSomething();
        });

        // ... test code
    });

Could it be possible to have some kind of middleware that adds a before and after hook to a describe block? So the above code could become something like:

    describe('...', () => {
        IncludeSomething()
        
        // ... test code
    });

Is something like this possible today, or could block middlewares be an idea for a new feature?

**Comment by ScottFreeCode** [comment]
This should work as you've supposed; but if at any point it doesn't, you should always be able to work around it by passing `before` and the others to `IncludeSomething` instead of relying on the globals being affected in all scopes/files.

Let us know if you have any other questions or concerns!
