### ISSUE TITLE
mocha.opts file should define the default options when using new Mocha on nodejs

### ISSUE THREAD

**Issue by erikvold** [mochajs/mocha#2910]
Currently, when using mocha programmatically one has to provide options like so `new Mocha(options)` but it would be helpful if the default options were read from the `mocha.opts` file which is already done when using mocha via cli.

So that `new Mocha()` would check for the `mocha.opts` file and use the options defined there by default, when used on nodejs, obviously in the browser context this is not possible.

**Comment by boneskull** [comment]
the refactoring to do this in an elegant manner (without pushing a bunch of junk into the browser build) may not be worth it...

**Comment by honzajavorek** [comment]
I just stumbled upon this. We have multiple test suites within one project where we use Mocha and most of them are implemented as running the Mocha binary from the npm script. One or two though need some customization and we'd like to use the JS API for that. But in that case, we either need to duplicate `mocha.opts` or to parse them ourselves. Both is very complicated as it also includes parsing glob the same way Mocha would do, etc.

Maybe just refactoring the `bin` files somehow so they're not running and modifying everything globally would be sufficient? I mean, to encapsulate and separate the functionality of loading the opts file and evaluating the options into something usable also from outside Mocha.

**Comment by plroebuck** [comment]
@honzajavorek, which Mocha-related options in "mocha.opts" are causing your heartburn?

**Comment by honzajavorek** [comment]
Our mocha.opts look like this:

```
--reporter mocha-multi-reporters
--reporter-options configFile=test/mocha-multi.json
--require test/integration/mocha-bootstrap.js
--recursive
src/**/*.integration.js
```

If I want to run Mocha programmatically, with the same options and maybe just with `grep` or `fgrep` added, I'd have to parse these options, parse and evaluate the glob, and to somehow give it to the `Mocha` JavaScript instance. Currently that's not trivial and the only option is to stick to running Mocha in a subprocess, but in our use case that happens many times, so it slows down the test suite a lot.

**Comment by juergba** [comment]
`mocha.opts` has been deprecated and removed some time ago. Mocha uses now cofiguration files.

In [lib/cli/](https://mochajs.org/api/module-lib_cli.html) you can find some public functions for that purpose:
- `loadOptions()`
- `loadPkRc()`
- `loadRc()`
- `lookupFiles()`
