### ISSUE TITLE
Mocha done() invoked error

### ISSUE THREAD

**Issue by pc-snandakumar** [mochajs/mocha#2911]
done() invoked with non-Error: Log : Wait until element is visible, selector: "#appointment .active",
Error: done() invoked with non-Error: Log : Wait until element is visible, selector: "#appointment .active",
    at promise.ControlFlow.runInFrame_ (eval at <anonymous> (node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:1857:20)
    at goog.defineClass.notify (eval at <anonymous> (node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:2448:25)
    at promise.Promise.notify_ (eval at <anonymous> (node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:564:12)
    at Array.forEach (native)
    at promise.Promise.notifyAll_ (eval at <anonymous> (node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:553:15)
    at goog.async.run.processWorkQueue (node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)

**Comment by pc-snandakumar** [comment]
var clickScheduleCall = function () {
	// Click on "Schedule a call" button from Dashboard- Advisor section
	driver.findElement(By.linkText('Schedule a Call')).click();

	// Trying to lacate Scheduling iFrame
	driver.wait(until.ableToSwitchToFrame(driver.findElement(By.css('#scheduleCallModal iframe'))), 15000);
	driver.switchTo().frame(driver.findElement(By.css('#scheduleCallModal iframe')));
	helper.waitElementLocated(By.css('#appointment .active'), 12000);
	helper.waitElementIsVisible(By.css('#appointment .active'), 12000);
	helper.waitForLoader();	
	driver.findElement(By.className('active')).then(function (elem) 
	{
		
		elem.getAttribute('id').then(function(txt)
		{
			if (txt == 'availabilities_panel')
			{
				helper.waitElementIsVisible(By.css('#availabilities_panel .col-xs-4:nth-child(1) .availability .weekday'), 10000);
			}

			else

			{
				helper.waitElementIsVisible(By.linkText('Change Appointment'), 10000);
				
			}


		}); 
	
	})
}

**Comment by ScottFreeCode** [comment]
You should be calling the `done` callback parameter from Mocha's test functions with no arguments for success, or with an `Error` object for failures. Or, for promises, you can simplify this by doing one of:
- return the promise (Mocha will treat resolved as success and rejected as failed)
- use an `async` function as your test function (this implicitly returns a promise as well as allowing you to use `await` to write promise code more like synchronous code)
- use Selenium's `require('selenium-webdriver').promise.consume` method or an equivalent (e.g. from Co) (effectively a library implementation of `async`/`await`, compatible on slightly older browsers and Node versions)

Note also that Selenium eventually will not support implicitly synchronous usage of its API without `then`, `yield` (with `promise.consume` or equivalent) or `await`: http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/promise.html

(I don't happen to see Mocha code in the code you posted; if you need more specific advice than the above or if you believe Mocha is not behaving as described/documented, we'll need [a minimal but complete example](https://stackoverflow.com/help/mcve) to help you with.)

* * *

Additionally, although it shouldn't make a difference to the behavior, if you're using `then` explicitly you can avoid nesting promise callbacks like this:
```js
somePromise.then(function(value) {
  value.getAnotherPromise().then(function(otherValue) {
    otherValue.use()
  })
})
```
...by taking advantage of `then`'s flattening behavior:
```js
somePromise.then(function(value) {
  return value.getAnotherPromise()
}).then(function(otherValue) {
  otherValue.use()
})
```

* * *

Unrelatedly, here's a quick GitHub tip inspired by your example code: you can write blocks of code into issues and comments safely by surrounding them with \`\`\` (optionally with a language specified after the opening) e.g.:
>\`\`\`js
>function exampleJavaScriptCode() {
>  console.log("the whole thing is treated as a code block correctly") // there are two spaces at the start of this line
>})
>\`\`\`

...will be printed as:
```js
function exampleJavaScriptCode() {
  console.log("the whole thing is treated as a code block correctly") // there are two spaces at the start of this line
})
```

**Comment by pc-snandakumar** [comment]
var clickScheduleCall = function () {
	// Click on "Schedule a call" button from Dashboard- Advisor section
	driver.findElement(By.partialLinkText('Schedule a Call')).click();

	// Trying to lacate Scheduling iFrame
	driver.wait(until.ableToSwitchToFrame(driver.findElement(By.css('#scheduleCallModal iframe'))), 15000);
	driver.switchTo().frame(driver.findElement(By.css('#scheduleCallModal iframe')));
	driver.sleep(30000);
	helper.waitElementLocated(By.css('#appointment .active'), 15000);
	helper.waitElementIsVisible(By.css('#appointment .active'), 15000);
	helper.waitForLoader();	
	driver.findElement(By.className('active')).then(function (elem)
	{
		
		elem.getAttribute('id').then(function(txt)
		{
			if (txt == 'availabilities_panel')
			{
				helper.waitElementIsVisible(By.css('#availabilities_panel .col-xs-4:nth-child(1) .availability .weekday'), 10000);

			}

			else

			{
				helper.waitElementIsVisible(By.partialLinkText('Change Appointment'), 10000);
				
			}

		

		}); 
	
	});
}

done() invoked with non-Error: Log : Wait until element is visible, selector: "#appointment .active",
Error: done() invoked with non-Error: Log : Wait until element is visible, selector: "#appointment .active",
    at promise.ControlFlow.runInFrame_ (eval at <anonymous> (node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:1857:20)
    at goog.defineClass.notify (eval at <anonymous> (node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:2448:25)
    at promise.Promise.notify_ (eval at <anonymous> (node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:564:12)
    at Array.forEach (native)
    at promise.Promise.notifyAll_ (eval at <anonymous> (node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:553:15)
    at goog.async.run.processWorkQueue (node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)

This is the element which is causing error while running in jenkins. any insights will be useful.

I am not sure why done is invoked...

**Comment by ScottFreeCode** [comment]
This looks like the same code to which my reply was originally addressed; I believe all of my comments still apply at this point, for what it's worth.

I should add/clarify that since there isn't any Mocha code in that function, it's necessarily missing the full picture. *Mocha's test failure output should list the test in which this error occurred.* From what I see here I'd guess what you need to find out is how `helper` or `helper.waitElementIsVisible` is defined *in that test*. A more minimal (as well as complete) example that still demonstrates the issue may be easier to diagnose, explain, and/or resolve, however.
