### ISSUE TITLE
test output order

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mocha#2917]
In #2846 it came up that some of our integration and reporter tests check multiple lines of output using a set of RegExp tests via `forEach` that ensures each line is present but does not ensure they are in the right order. We should find all instances of this pattern and correct it to ensure the right order somehow. (They should remain insensitive to the style of line ending used by the OS's shell/whatever...) (#2846 may need to be updated to the new style if this issue is resolved before we can merge #2846 into a semver-major release, or if this is not resolved against a semver-major branch to which #2846 is merged while awaiting such a release.)

**Comment by juergba** [comment]
outdated
