### ISSUE TITLE
Windows (AppVeyor) coverage

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mocha#2919]
Besides browser coverage, there are a few environmental factors that affect the branches covered in our tests:
- Environment version, inasmuch as we shim some stuff or otherwise handle outdated environments specially.
- Special environments, e.g. whether the shell is or is not running in a TTY or whatever `isatty` is about.
- Travis Linux tests vs. AppVeyor Windows tests.

The first of these is addressed as much as can be hoped by adding coverage to all Node versions' tests in the [multi-coverage branch](/mochajs/mocha/tree/multi-coverage) (PR #2886, it also contains coverage for the browser tests; #2900 adds tests for the browser reporter to bring the numbers back up to a new record high). The second is going to require some kind of special testing if it's possible at all. I'm opening this issue to discuss and/or track the last one.

* * *

According to this issue: https://github.com/lemurheavy/coveralls-public/issues/613 it should be possible to have AppVeyor report coverage too, *but* (unless Coveralls has fixed this and didn't close the issue on the tracker) it will be reported as though it were a separate commit/PR/build, not merged together like how multiple jobs are automatically merged together.

* * *

We should probably go ahead and try it anyway just to see what happens -- it's possible the issue would still be better than not having those coverage numbers, or that the issue was fixed without updating the tracker; and if niether of those turns out to be the case, we can just close the PR after we see it.

If that doesn't do, we could consider switching services: https://github.com/lemurheavy/coveralls-public/issues/613#issuecomment-244724308

Or we could consider a (dubious) workaround: create a Node version of [this hack](https://github.com/Robpol86/appveyor-artifacts) that:
- runs on Travis (could be a great opportunity to using a build stage instead of trying to shoehorn it into the test jobs or creating a test job that doesn't run tests)
- waits for AppVeyor to complete
- downloads the coverage report(s) from AppVeyor
- fixes any Windows formatting/path issues
- and then leaves us with our existing tools to do any coverage-report merging necessary and upload AppVeyor coverage to Coveralls as though it were part of the Travis job set

A variation of the latter might be to have both CI services send their reports immediately, but add [`COVERALLS_PARALLEL=true`](https://coveralls.zendesk.com/hc/en-us/articles/203484329) and have the job or stage that waits for both CI services simply trigger the associated webhook rather than doing any report downloading or merging on its own, and see if simply using `COVERALLS_PARALLEL` "fixes" https://github.com/lemurheavy/coveralls-public/issues/613

**Comment by boneskull** [comment]
@ScottFreeCode 

Am I correct in stating that the "win" here would be seeing which lines *differ* between the two CI environments, not necessarily that we need the "numbers" from AppVeyor?

**Comment by ScottFreeCode** [comment]
@boneskull 

> Am I correct in stating that the "win" here would be seeing which lines differ between the two CI environments, not necessarily that we need the "numbers" from AppVeyor?

More precisely, we don't care that much about seeing the difference or seeing numbers (beyond "> 0"), but currently there are lines and branches that are listed as "uncovered" that are actually covered but only on Windows because they're handling OS differences.

**Comment by juergba** [comment]
outdated
