### ISSUE TITLE
Allow calling only on multiple its and describes

### ISSUE THREAD

**Issue by danielbaak** [mochajs/mocha#2923]
Currently the first ( or a random ) block tagged `.only(` is executed if multiple calls of only exist.

I would like to propose adding a behavior that is more aligned to a common usecase I have:
Run all `it`s and `describe`s that are setup with `.only(`.

(Haven't yet looked in to the amount of work behind this change proposal)

**Comment by ScottFreeCode** [comment]
This is supposed to be supported already as of Mocha 3.x; see [here](https://mochajs.org/#exclusive-tests) for details.

Double-check that you've got the latest version (and if you have a global install -- although we don't recommend that anymore -- double-check both the global and the local version); if you do and you still get behavior that doesn't match the description linked above, we'd love to have a specific (preferably minimal but still complete) example that demonstrates the issue!

**Comment by danielbaak** [comment]
I was running mocha@2.4.3, now mocha@3.1.x and mocha@3.4.2 both ignore any .only passed to an it or describe block in my tests.  I'll try to figure out if a problem with my setup is causing this.

**Comment by danielbaak** [comment]
Just found out that the issue occurs only in conjunction with grunt-mocha-test@0.12. 
Using mocha@3  together with grunt-mocha-test@0.13 works like a charm.
Thanks!
