### ISSUE TITLE
Using --opts flag does not make mocha.opts work as expected 

### ISSUE THREAD

**Issue by alaboudi** [mochajs/mocha#2929]
I have used the --opts flag to change the location of the mocha.opts file location. Doing so throws an error. If erase the --opts flag and put back the file under ./test everything works fine

I get an unexpected identifier issue referencing the first line of my mocha.opts file. As stated the content is correct as it works when placed under ./test.

Below is the content of the file
--require apps.js
--recursive test

**Comment by ScottFreeCode** [comment]
What's the location and name you moved the `mocha.opts` file to? What's the full command you used to run Mocha? What is the full error (at least the exact error message, preferably the stacktrace too)?

> I get an unexpected identifier issue referencing the first line of my mocha.opts file.

Based on this, I'd guess that you gave the opts file a name ending in `.js` and ran it as a test file; I can't give a more detailed or definitive answer from the information I have so far, however.

**Comment by alaboudi** [comment]
I have definitely have not given the file a .js extension.  

I have placed the file as an immediate child of the root directory of my application. Then, I have configured package.json's test script.

```
"scripts": {
    "test": "istanbul cover node_modules/mocha/bin/_mocha --opts ./mocha.opts",
    "start": "node app.js"
  },
```
mocha.opts file
```
--require app.js
--require test/bootstrap.js
```

when running `npm test`,  I get the following error stack trace

> > istanbul cover node_modules/mocha/bin/_mocha --opts ./mocha.opts
> 
> No coverage information was collected, exit without writing coverage information
> C:\Users\yazan\Documents\Web Projects\Web Apps\backend\mocha.opts:2
> --require app.js
>           ^^^
> SyntaxError: Unexpected identifier
>     at createScript (vm.js:56:10)
>     at Object.runInThisContext (vm.js:97:10)
>     at Module._compile (module.js:542:28)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Object.Module._extensions.(anonymous function) [as .js] (C:\Users\yazan\Documents\Web Projects\Web Apps\backend\node_modules\istanbul\lib\hook.js:109:37)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at C:\Users\yazan\Documents\Web Projects\Web Apps\backend\node_modules\mocha\lib\mocha.js:230:27
>     at Array.forEach (native)
>     at Mocha.loadFiles (C:\Users\yazan\Documents\Web Projects\Web Apps\backend\node_modules\mocha\lib\mocha.js:227:14)
>     at Mocha.run (C:\Users\yazan\Documents\Web Projects\Web Apps\backend\node_modules\mocha\lib\mocha.js:495:10)
>     at Object.<anonymous> (C:\Users\yazan\Documents\Web Projects\Web Apps\backend\node_modules\mocha\bin\_mocha:469:18)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Object.Module._extensions.(anonymous function) [as .js] (C:\Users\yazan\Documents\Web Projects\Web Apps\backend\node_modules\istanbul\lib\hook.js:109:37)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Function.Module.runMain (module.js:604:10)
>     at runFn (C:\Users\yazan\Documents\Web Projects\Web Apps\backend\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
>     at C:\Users\yazan\Documents\Web Projects\Web Apps\backend\node_modules\istanbul\lib\command\common\run-with-cover.js:251:17
>     at C:\Users\yazan\Documents\Web Projects\Web Apps\backend\node_modules\istanbul\lib\util\file-matcher.js:68:16
>     at C:\Users\yazan\Documents\Web Projects\Web Apps\backend\node_modules\istanbul\node_modules\async\lib\async.js:52:16
>     at C:\Users\yazan\Documents\Web Projects\Web Apps\backend\node_modules\istanbul\node_modules\async\lib\async.js:361:13
>     at C:\Users\yazan\Documents\Web Projects\Web Apps\backend\node_modules\istanbul\node_modules\async\lib\async.js:52:16
>     at done (C:\Users\yazan\Documents\Web Projects\Web Apps\backend\node_modules\istanbul\node_modules\async\lib\async.js:246:17)
>     at C:\Users\yazan\Documents\Web Projects\Web Apps\backend\node_modules\istanbul\node_modules\async\lib\async.js:44:16
>     at C:\Users\yazan\Documents\Web Projects\Web Apps\backend\node_modules\istanbul\node_modules\async\lib\async.js:358:17
>     at LOOP (fs.js:1773:14)
>     at _combinedTickCallback (internal/process/next_tick.js:73:7)
>     at process._tickCallback (internal/process/next_tick.js:104:9)
>

**Comment by ScottFreeCode** [comment]
Looks like Istanbul is interpreting that command as meaning it should cover `./mocha.opts`. (I'm looking up Istanbul's documentation now to see if there's a specific way to ensure that arguments like that are passed on to the other program instead; may double-post if I find anything...)

**Comment by ScottFreeCode** [comment]
Here we go: https://github.com/gotwarlost/istanbul#the-cover-command Looks like the script should be `istanbul cover node_modules/mocha/bin/_mocha -- --opts ./mocha.opts` (extra `--` between the Mocha script and the arguments). Let us know if that works!

(You may also want to look at `nyc`, by the way, which is the more up-to-date and improved successor to Istanbul's CLI. It builds on the same underlying library but fixes a lot of the rough edges.)

**Comment by alaboudi** [comment]
thank you so much 👍  everything is fine now.

**Comment by ScottFreeCode** [comment]
You're welcome!
