### ISSUE TITLE
Update dependency version for debug

### ISSUE THREAD

**Issue by danhdoancs** [mochajs/mocha#2939]
Hi guys,

I'm getting this warning from debug every time I run mocha tests:
(node:13161) DeprecationWarning: `DEBUG_FD` is deprecated. Override `debug.log` if you want to use a different log function (https://git.io/vMUyr)

Based on https://github.com/visionmedia/debug/issues/410 issue, they fixed it in version 2.6.1. However, the mocha@3.4.2 still depend on debug@2.6.0. Could anyone please update debug version to fix this issue?

**Comment by ScottFreeCode** [comment]
Mocha 3.5.0 was just released and should have Debug 2.6.8 if I recall correctly; @danhdoancs can you confirm that the issue is resolve in 3.5.0? Thanks!

**Comment by danhdoancs** [comment]
@ScottFreeCode Yes that warning is gone in 3.5.0. Thank you very much!

**Comment by ScottFreeCode** [comment]
You're welcome! 🎆
