### ISSUE TITLE
Unreadable text problem on some color scheme (especially Solarized Dark)

### ISSUE THREAD

**Issue by piroor** [mochajs/mocha#2945]
Some people say that the mocha's output is unreadable because texts are colorlized quite same to the background color. For example:

 * [Please change color scheme · Issue #1200 · mochajs/mocha](https://github.com/mochajs/mocha/issues/1200)
 * [Much of the color output is invisible with solarized terminal theme · Issue #802 · mochajs/mocha](https://github.com/mochajs/mocha/issues/802)
 * [Solarized · Issue #122 · mochajs/mocha](https://github.com/mochajs/mocha/issues/122)

Just changing color is not best solution, because there are too many color schemes on the world. It is very hard to keep enough contrast between fixed text color and platform's background color.

Instead, I think some logical control code is better on this case. They reporters say that texts colorized with `90` is unreadable on Solarized Dark. By default the color is applied for `pass`, `error stack`, `fast`, `light`, and `diff gutter`; they all mean "weaker than other information" logically. In other words, we just hope that important information to be highlighted and others to be dim. And I've found that the control code `2` means `dim` which seem to be designed for this purpose. I believe that the logical code `2` is better than phisical color code `90` in this context. Could you consider to use that?

**Comment by boneskull** [comment]
sorry, this has been beaten to death.
