### ISSUE TITLE
Returning a promise that rejects - real error is obscured

### ISSUE THREAD

**Issue by kamilkp** [mochajs/mocha#2953]
I am using async/await in my tests like this:

```javascript
it('should work', async () => {
  const result = await sthAsync();
  expect(result).to.be.ok;
});
```

It works perfectly unless the async function actually returns a rejection. So if I make a typo for instance:

```javascript
it('should work', async () => {
  const result = await sthAsyncWhoopsTypoHere();
  expect(result).to.be.ok;
});
```

When I run this I get the following error:

```
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

How hard would it be to actually report the true error that's behind it i.e.:

```
Uncaught ReferenceError: sthAsyncWhoopsTypoHere is not defined
```

**Comment by ScottFreeCode** [comment]
If I run the `sthAsyncWhoopsTypoHere` example I get:
>   1) should work
> 
>   0 passing (31ms)
>   1 failing
> 
>   1)  should work:
>      ReferenceError: sthAcyncWhoopsTypoHere is not defined
>       at Context.it (tmp.js:2:24)
>       at callFn (lib\runnable.js:350:21)
>       at Test.Runnable.run (lib\runnable.js:342:7)
>       at Runner.runTest (lib\runner.js:443:10)
>       at lib\runner.js:549:12
>       at next (lib\runner.js:361:14)
>       at lib\runner.js:371:7
>       at next (lib\runner.js:295:14)
>       at Immediate._onImmediate (lib\runner.js:339:5)

**Comment by kamilkp** [comment]
Ahh. You're absolutely right. It's caused by the fact that I hack `global.Promise` with angularjs's `$q` service in order to mitigate the pain of being out of the digest cycle in async functions (not sure how much you know about this caveat and angularjs itself). Anyway this is clearly not a mochajs issue.

**Comment by ScottFreeCode** [comment]
Thanks for following up -- I really wasn't sure what I could ask about that might cause this, now I have at least one idea to keep in mind for next time it comes up!
