### ISSUE TITLE
Error: Timeout of 2000ms exceeded

### ISSUE THREAD

**Issue by cemiltokatli** [mochajs/mocha#2958]
When I try to use promises with mocha, I'm getting the error below:

> Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

Actually, I'm trying to retireve data from a remote server. Mocha won't wait until the promise has been resolved or rejected.
```

function fn(){
  return new Promise((resolve, reject) => {
       setTimeout(() => resolve({foo:'bar'}),7000);
  })
}

 it('should retrieve data',function(done){
            fn().then((res) => done()).catch((err) => done(err));
 });
```

After 2 seconds, this error occurs.
I've been planning to check the returning data within then and call the assert.

```
it('should retrieve data',function(done){
   fn().then(() => {
       assert(true)
       done()
   });
});
```

What am I doing wrong? I want to check the returning data if it has proper keys, etc.

**Comment by ScottFreeCode** [comment]
If it is expected/acceptable for your test to take longer than the timeout specified in the error message, you can override the amount of time for the timeout using [`this.timeout(<maximum acceptable time>)`](https://mochajs.org/#timeouts) or [`--timeout <maximum acceptable time>`](https://mochajs.org/#t---timeout-ms).

P.S. You can remove `done` from the tests and `return fn().then(...` instead, Mocha will treat promise resolution as success and rejection as failure.

**Comment by Jo-ravar** [comment]
#### Facing the same issue when using `chai-http` and `expect`

`Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.`

I was planning to run the check if function called is function or not and have not used _chai-http_ any where .

**Code** :--

```
const app = require('../../app');
const chai = require('chai');
const expect = require('chai').expect;
const chaiHttp = require('chai-http');
const async = require('async');

const sellerPurchase = require('../../lib/seller/purchases');

chai.use(chaiHttp);
describe('SELLER: PURCHASE module', () => {
  describe('"#insertNewOrder()"', () => {
    // 1. Checks whether the variable exported from that file is a function itself or not
    it('should be a function', done => {
      this.timeout(10000);
      expect(sellerPurchase.insertNewOrder).to.be.a('function');
      done();
    });
  });
});
```
Now the thing is when I am not loading server file `app` or `const app = = require('../../app');` this is working fine but when i am loading it  is giving the error.

**Note** :-- I  have tried increasing timeout still its not working.

**Comment by ScottFreeCode** [comment]
@Jo-ravar I can't really debug that since I don't have your `../../app` or `../../lib/seller/purchases`. Do you think you could trim down those two modules to the simplest they can be that will still cause the issue, and then post the simplified version? (There are no obvious problems with the code you have posted. In fact, given that it's a synchronous test and all it does is have an assertion check that a property is a function, you'd have to abuse some relatively advanced/hacky JavaScript techniques to slow it down at all, let alone cause it to time out. But the only way to figure out for sure is to have all the code needed to run it and get the issue.)

**Comment by Jo-ravar** [comment]
### Here is the simplified version of code

```
const app = require('../../app');
const chai = require('chai');
const expect = require('chai').expect;
const chaiHttp = require('chai-http');
chai.use(chaiHttp);

describe('"#Check Sum"', function() {
  this.timeout(10000);
  // 1. Checks whether the variable exported from that file is a function itself or not
  it('should be a number', done => {
    expect(2 + 3).to.be.a('number');
    done();
  });
});
```

The only thing causing issue is the first line here whenever I am loading the server or `app.js` file it is giving error and when I am not loading it is working fine.

**Note** :---
1. I have tried out timeout function with .
2. I have also tried it after removing arrow function has described [](https://github.com/mochajs/mocha/issues/2018) . Then too it is not working.

**Comment by ScottFreeCode** [comment]
I'm still not seeing the code for the `app.js` file?

**Comment by inboxdarpan** [comment]
@Jo-ravar How much timeout did you set? I was testing one upload function, and it depended on size of file I was trying to upload. So, sometimes it didn't give me error on 10 seconds, while for some uploads it even gave me failures for 45 second timeout.

**Comment by Pravee08** [comment]
@Jo-ravar i am too getting the same error , have you found the solution?

**Comment by amoswachanga** [comment]
Any resolution on this?

**Comment by boneskull** [comment]
This needs an [mcve](https://stackoverflow.com/help/mcve); I don't believe it's a Mocha problem anyway.  Re-open if someone can confirm.

**Comment by negarineh** [comment]
I have found the solution for my case here [#2025](#2025)

**Comment by selvakumar1994** [comment]
i used the below script but i got the same Timeout exceed error.

Myscript :

describe("getBillingDetail", async function (){
this.timeout(55000);
it.only("check given valid Jobname",async function (done){
this.timeout(55000);
var result = await url.getBillingDetail('12254785565647858');
console.log(result);
assert.equal(result,true);
});
});

Error: Timeout of 55000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Comment by yihaoye** [comment]
For the people who still struggling with this problem, just add `this.enableTimeouts(false)` will solve it.
Example:
`
describe('Test', function () {
  this.enableTimeouts(false)
  // your code here
}
`

**Comment by ldonjibson** [comment]
You can may also try to run the code last. I had the same issue but was able to by pass it using:
`after('Test', (done) => {
//your code
});`

**Comment by solaar14** [comment]
go here https://mochajs.org/#timeouts

**Comment by leonelRos** [comment]
Hey, guys, I was running through the same error. after carefully searching I found out I need to call the "done()" function. It was given some trouble but now it passes the test.

describe('sample_tests', function () {
	// this.timeout(10000)
	it('test 0', (done) => {
		expect(1).to.be.equal(1);
	--->	done();
	});
});

**Comment by fitorec** [comment]
:neckbeard: Other option, you can use de TIMEOUTS suite, check this example:

```js
describe('a suite of 7 seconds', function () {
  this.timeout(7500);
  it('should take less than 5s', function (done) {
    setTimeout(done, 5000);
  });

  it('should take less than 2s as well', function (done) {
    setTimeout(done, 2000);
  });
});
```

More info: :point_right: <https://mochajs.org/#timeouts>

**Comment by ju4n23** [comment]
I am also having the same error. Can anybody help me? This is my code:

import mongoose from 'mongoose'
import AuthRepository from '../../../../src/auth/data/repository/AuthRepository'
import dotenv from 'dotenv'
import { expect } from 'chai'

dotenv.config()

describe ('AuthRepository', () => {
    let client : mongoose.Mongoose
    let sut: AuthRepository

    beforeEach(() => {
        client = new mongoose.Mongoose()
        const connectionStr = encodeURI(process.env.TEST_DB as string)
        client.connect(connectionStr, {
            useNewUrlParser: true,
            useUnifiedTopology: true
        })

        sut = new AuthRepository(client)
    })

    afterEach(() => {
        client.disconnect()
    })

    it('should return user when email is found', async () => {
        const email = 'juansantiago@gmole.com'
        const password = 'pass'

        const result = await sut.find(email)

        expect(result).to.not.be.empty
        
    })
})

**Comment by SomeJoker** [comment]
> ### Here is the simplified version of code
> ```
> const app = require('../../app');
> const chai = require('chai');
> const expect = require('chai').expect;
> const chaiHttp = require('chai-http');
> chai.use(chaiHttp);
> 
> describe('"#Check Sum"', function() {
>   this.timeout(10000);
>   // 1. Checks whether the sum is number or not
>   it('should be a number', done => {
>     expect(2 + 3).to.be.a('number');
>     done();
>   });
> });
> ```
> 
> The only thing causing issue is the first line here whenever I am loading the server or `app.js` file it is giving error and when I am not loading it is working fine.
> 
> **Note** :---
> 
> 1. I have tried out timeout function .
> 2. I have also tried it after removing arrow function has described in [Mocha Arrow Issue](https://github.com/mochajs/mocha/issues/2018) . Then too it is not working.

I used it solve my question. just add a ```line this.timeout(10000)``` in first line

**Comment by liudonghua123** [comment]
I have the same problems, I also need to rewrite the anonymous arrow function to normal function.

![image](https://user-images.githubusercontent.com/2276718/220849966-77da58d6-4b29-4189-a1ad-0c1a0a59f5c8.png)

![image](https://user-images.githubusercontent.com/2276718/220850057-8a69956b-73a4-4bc2-8f07-58b13a86ed69.png)
