### ISSUE TITLE
Update growl to 1.10.2 to prevent vulnerability

### ISSUE THREAD

**Issue by rmdort** [mochajs/mocha#2965]
Can growl be updated to 1.10.2 to prevent Command Injection vulnerability

https://nodesecurity.io/advisories/146

**Comment by ScottFreeCode** [comment]
Closing as a duplicate of #2791; see also open PRs #2930 and #2931, as well as discussion of how to resolve compatibility issues at https://github.com/mochajs/mocha/pull/2930#issuecomment-315798341
