### ISSUE TITLE
QUESTION: mocha with loopback.get null from db built in memory.

### ISSUE THREAD

**Issue by xisuoyo** [mochajs/mocha#2968]
In mocha test,`app.models.User.findOne()` return null though there's data in memoryDB.json.
the definition in datasource config is 
`"memory": {
    "name": "memory",
    "connector": "memory",
    "file": "memoryDB.json"
  },`.
Is there someway mocha can get data from a memory db.

**Comment by ScottFreeCode** [comment]
Mocha doesn't have an `app.models` or memory database (though you can certainly use it to test code that does); you'll probably need to ask for help troubleshooting the framework that's being used by the code you're testing instead of here.
