### ISSUE TITLE
--bail option doesnt work with retries

### ISSUE THREAD

**Issue by larstonne** [mochajs/mocha#2969]
Bail kicks in if test fails even if rertries are configured

**Comment by ScottFreeCode** [comment]
Hi, @larstonne, could you post some code to demonstrate this issue that is complete and verifiable (possible to demonstrate the problem by copy-pasting the code into an empty project) but minimal (try to narrow it down to just the code that actually triggers the issue)?

I tried running this test:
```js
var count = 0

it("bail issue", function() {
  this.retries(5)
  if (count < 4) {
    count += 1
    throw new Error("Must be retried")
  }
})

it("another test", function() {
})
```
...with this command:
```sh
mocha --bail
```
...and I got successful output for both tests:
>  √ bail issue
>  √ another test
>
>  2 passing (31ms)

**Comment by ScottFreeCode** [comment]
(Removed labels as discussion in #2970 appears to indicate there is not currently a bug here.)

**Comment by Noitidart** [comment]
I am also having this issue. In my mocha.opts i set `--bail`, but i have test that has `this.retries(10)`. Bail should not bail out until all 10 retries have failed. It is counting a retry-error as a bail. It should count ALL-retry-failed as single error.

**Comment by Noitidart** [comment]
Oops never mind, I was using a fat arrow function, should have used regular.
