### ISSUE TITLE
import / require xit

### ISSUE THREAD

**Issue by LukasBombach** [mochajs/mocha#2972]
Is there a way to `import` / `require` to satisfy my tooling?

I can do

```javascript
import { it } from 'mocha';
```

but not

```javascript
import { xit } from 'mocha';
```

or

```javascript
import { xit } from 'mocha/lib/interfaces/bdd';
```

**Comment by ScottFreeCode** [comment]
Looks like the `x` cases are missing from https://github.com/mochajs/mocha/blob/2bc9c4d1d638c8a95250757dd23724f788918abe/lib/mocha.js#L200-L214 They should be pretty easy to add, although I'll have to look around a bit more to find where we have tests for those exports so we can add tests for the `x` cases.

**Comment by solodynamo** [comment]
Hey @ScottFreeCode I would like to give a try to this.

**Comment by ScottFreeCode** [comment]
We'd be happy to take a pull request!

Don't worry about including tests at this point -- I just went looking for them and it seems that we're currently only testing `describe` and `it` out of all those functions: https://github.com/mochajs/mocha/blob/f20de56637b2223f614ce40adc0d41a58030f042/test/unit/required-tokens.spec.js So we'll want to expand that, but not just for the couple of new additions, and can/should do it in a separate PR.

**Comment by ScottFreeCode** [comment]
(Created #2982 for adding a more complete test of this feature.)

**Comment by solodynamo** [comment]
Hey @ScottFreeCode made a PR for this issue https://github.com/mochajs/mocha/pull/2997

**Comment by rpaterson** [comment]
I think this fix introduced a bug https://github.com/mochajs/mocha/issues/3004
