### ISSUE TITLE
Security Report: growl@1.9.2

### ISSUE THREAD

**Issue by atian25** [mochajs/mocha#2973]
146 - Command Injection

Vulnerable: <1.10.2 - Patched: >=1.10.2 - Path: mocha@3.5.0 > growl@1.9.2

How to fix
Update to version 1.10.2 or greater

https://nodesecurity.io/orgs/eggjs/projects/16be4d34-c7a2-4e01-9696-62a90742d571/71

**Comment by d4nyll** [comment]
FYI, there's a related PR at #2931

**Comment by ScottFreeCode** [comment]
Going to close this as a duplicate of #2791, but feel free to take any additional discussion there -- in particular, if you can help us find any of the info mentioned in https://github.com/mochajs/mocha/pull/2930#issuecomment-315798341, that would help us resolve this.
