### ISSUE TITLE
automate code formatting

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2980]
I've played with [prettier](https://www.npmjs.com/package/prettier) a bit, and it seems like a reasonable solution (especially when [combined with husky](https://www.npmjs.com/package/prettier#pre-commit-hook)) to enforce a code style across the codebase.

This should prevent nitpicks about style in PRs.

We could also likely make the pre-commit hook run `eslint --fix`.

`semver-patch` because it should have no impact upon API or program output.

**Comment by boneskull** [comment]
A thing that will happen if we do this is pretty much every file will be touched, because there's no way to disable some of the disagreements between prettier and semistandard.

**Comment by boneskull** [comment]
to be more specific, prettier will remove the spaces after the `function` keyword and that's that.  I don't really care.  does anyone care? 

fwiw, I'm cool with using a more unopinionated formatter if one exists.  the killer feature here for Mocha is *automatic application of a style*--not the style itself--but prettier conflates the two.  that's fine for FB and solves their problem, but it's not necessarily Mocha's problem.

**Comment by boneskull** [comment]
(because Mocha is not thousands of javascript projects, it's just one)

**Comment by ScottFreeCode** [comment]
I wouldn't at all mind losing the spaced between `function` and `(`. I've never seen that outside of JS projects that rely on Standard for their linting.

I believe [XO](https://github.com/sindresorhus/xo) is designed to work better with Prettier *and* to be less stubbornly opinionated, if I heard correctly in the past.

**Comment by bakkot** [comment]
Drive-by: it looks this issue was addressed by #3344?

**Comment by boneskull** [comment]
@bakkot totally missed it, thanks.
