### ISSUE TITLE
server side version of init

### ISSUE THREAD

**Issue by tansaku** [mochajs/mocha#2989]
### Prerequisites

* [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)

### Description

This is a feature suggestion - I was wondering about creating a version of `mocha init` that would work for server side code rather than client side, e.g. just create a test dir with a single test file that might have some boilerplate code in it ...

It could also update package.json to have:

`"test": "mocha test/**/*.js"`

I'm thinking about similar server side init things I've seen for the ruby projects bundler and rspec.
I've looked and I don't seem to see the existence or discussion of such a thing.  Would this be desirable for anyone?  I'd find it handy to have when starting up a new project to speed things up a little ...

**Comment by boneskull** [comment]
I would be open to this idea.   Eventually this should expand to use a config file in place of `mocha.opts`. Thanks!

(I don't suggest creating `mocha.opts` with any `init` command)

**Comment by outsideris** [comment]
See #3385 .
