### ISSUE TITLE
Test case related to excel,file and PDF operation are not failing 

### ISSUE THREAD

**Issue by rajtomar99** [mochajs/mocha#2991]
I have written a test case for UI testing as well as integrated Excel,pdf and File operation . Now when I run test my test.js file I am able to see the failure for UI in report but for excel I am getting below promise rejection warning  and test case are marked as pass:
(node:9628) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): AssertionError: in fnExcelEnterDatainemptyrow

I am using assert for failing the test case and it is working fine for UI test cases. 

Please find my test.js as below:

var Yadda = require('yadda');
var library = require('./step-definition/intranet-step.js');
var assert;
var webdriver = require('selenium-webdriver');
var config = require('config');
var fs = require('fs');
const gBrowser = config.get('browser');
var logger = require('./log4js.js'); //This is required to set the var to log configuration file where log configuration has been defined.
var log = logger.LOG; //This is how you can get hold of LOG static variable which you can use to log details.
var driver;
Yadda.plugins.mocha.StepLevelPlugin.init();
var features = new Yadda.FeatureFileSearch('example/features');
features.each(function(file) {
    featureFile(file, function(feature) {
        before(function(done) {
            log.info('Start of the automation test Execution');
            
            driver = new webdriver.Builder().usingServer().withCapabilities({'browserName': gBrowser}).build();
            
            driver.manage().timeouts().implicitlyWait(10000);
            done();
        });

        var yadda = new Yadda.Yadda(library);
        scenarios(feature.scenarios, function(scenario) {
            steps(scenario.steps, function(step, done) {
                executeInFlow(function() {
                    new Yadda.Yadda(library,{ driver: driver }).yadda(step);
                }, done);
                // yadda.yadda(step,done);

            });
        });

        afterEach(function(done) {
            takeScreenshotOnFailure(this.currentTest);
            done();
        });

        after(function(done) {
            log.info('End of the automation test Execution');
            driver.quit().then(done);
        });
    });
});

function executeInFlow(fn,done) {

    webdriver.promise.controlFlow().execute(fn).then(function() {
       done();
       // process.on('unhandledRejection', () => {});
    }, done);
}

function takeScreenshotOnFailure(test) {
    if (test.status != 'passed') {
        var path = 'screenshots/' + test.title.replace(/\W+/g, '_').toLowerCase() + '.png';
        driver.takeScreenshot().then(function(data) {
            fs.writeFileSync(path, data, 'base64');
        });
    }
}

and excel function as below:

ExcelUtil.prototype.fnExcelGetCellData =  function (path, sheetName, row, col) {
	var promDefer = webdriver.promise.defer();
	workBook.xlsx.readFile(path).then(function () {
		var workSheet = workBook.getWorksheet('Sheet1');
		var rowVal = workSheet.getRow(row);
		var cellData = rowVal.getCell(col).value;
		promDefer.fulfill(cellData);
		assert.equal(true, false, "in fnExcelGetCellData");
	}, function (e) {
		promDefer.fulfill(false);
		log.error(e.message);
	});
	return promDefer.promise;
};
 
I have done the same thing for my all function for UI testing and they are working fine:

FunctionLibrary.prototype.fnVerificationOfElementAttributeValue = function (element, attribute, strText) {
    var d = webdriver.promise.defer();
    this.driver.findElement(element).getAttribute(attribute).then(function (text) {
        if (text === strText) {
            log.info("Pass - Value of Element's attribute " + attribute + " has been verified successfully.");
            assert.equal(true,true,"Pass - Value of Element's attribute " + attribute + " has been verified successfully.");
            d.fulfill(true);
        }
        else {
            log.error("Fail - Element with attribute " + attribute + "- value has not been verified.");
            assert.equal(true,false,"Fail - Element with attribute " + attribute + "- value has not been verified.");
            d.fulfill(false);
        }
    }, function (e) {
        d.fulfill(false);
        assert.equal(true,false,"Error: " +e.message);
        log.error(e.message);
    });
    return d.promise;
};

Please help me in finding the right approach and let me know what needs to be corrected here.

Regards,
Raj

**Comment by ScottFreeCode** [comment]
Hi Raj,

Do you think you could boil it down to a [more minimal and complete example](https://stackoverflow.com/help/mcve) and surround your code blocks with \`\`\`js at the start and \`\`\` at the end? This is very difficult to even read and look for your issue, both in terms of the amount of code we have to dig through, and in terms of the lack of formatting. I'm not seeing the `fnExcelEnterDatainemptyrow` your unhandled rejection warning claims to come from, or even any reference to that function.

**Comment by boneskull** [comment]
This should have gotten a `needs-feedback`.  anyway, reopen if necessary.
