### ISSUE TITLE
@std/esm compatibility for running mocha programmatically

### ISSUE THREAD

**Issue by eliw00d** [mochajs/mocha#2993]
I am trying to run mocha programmatically using `@std/esm` but have run into the issue where a loader might be necessary (see https://github.com/standard-things/esm/issues/89).

I have an example repo set up for the problem I am facing: https://github.com/eliw00d/std-esm-example

Basically, if you `npm run test` in the dependency project, you get SyntaxErrors for import being an unexpected token. However, if you `mocha -r @std/esm ./src/test` those errors are not present as the correct loader is being used. 

Are there any plans to allow `@std/esm`'s require to be used instead of what mocha uses internally?

**Comment by boneskull** [comment]
Why can't `npm test` run `mocha -r @std/esm -r my-other-script.js ./src/test`?

You may be able to get `--compilers` to help you, but I can't say for sure.

**Comment by jdalton** [comment]
Thank you `stale` bot! I don't think this is a mocha bug.

**Comment by boneskull** [comment]
@jdalton thanks for the heads-up
