### ISSUE TITLE
"mocha -ui tdd -w" do not working

### ISSUE THREAD

**Issue by codermarcos** [mochajs/mocha#2994]
The first test working but on next changes return this 0 passing 
```javascript
const assert = require('assert');

describe('Default', () => {
  it('format', () => {
    assert.equal('a', 'a');
  });
});
```
 ☝️  return this  👇
```bash
  Default
    √ format


  1 passing (7ms)
```
but when i change and  save this 
```javascript
const assert = require('assert');

describe('Default', () => {
  it('format', () => {
    assert.equal('a', 'b');
  });
});
```
 ☝️  return this  👇
```bash
  0 passing (1ms)
```

**Comment by ScottFreeCode** [comment]
If run with `--ui tdd` as in the title of this issue, shouldn't this throw an error because `describe` is not defined? Seems like an extension of #2207 if I've understood that correctly.

**Comment by codermarcos** [comment]
Thanks for the quick response, but i solved my problem another form. But responding your question i think you're right and my problem is an extension of that bug. When adding --watch the problem gets worse.

**Comment by ScottFreeCode** [comment]
Glad to hear you've got it covered!

I'm going to close this to keep discussion centered on #2207, but will note there what happens when also using `--watch`.
