### ISSUE TITLE
Rest API Performance.

### ISSUE THREAD

**Issue by monera23** [mochajs/mocha#3012]
I have been trying to run a node.js application having database calls(sqllite3) and then running mocha tests to check the REST API endpoints. I am making around 5k requests, and on my system it takes around 30 sec to execute all of it.

I have a platform where I have 1gb RAM to use and when I run the exact above application with the tests it takes around 4 minutes to execute.

Does the RAM make such a difference or I am doing anything wrong?

**Comment by ScottFreeCode** [comment]
Hi @monera23,

Does the performance difference significantly lessen if you run the same calls outside of Mocha testing? We can try to track down any performance problems in Mocha itself if we can get a better idea where exactly they're coming from, and we can help with Mocha usage if there's a problem with a particular test usage pattern (we'd need to see minimal but complete example code that demonstrates it however), but this isn't a general performance troubleshooting forum. I could barely begin to list the things that can affect performance, especially in the case of an app with both a database backend and a network API:

- memory speed/latency
- disk read/write speeds
- network characteristics (this is *unlikely* -- though not impossible -- to be an issue if the database, application and tests are all on the same machine, but *very* likely to be an issue if any of those three is on a different machine from any of the others)
- processor characteristics
- OS and software stacks in use
- what else is running on the machine at the same time
- database usage patterns in the application
- how much data is being processed
- anything else the application is doing (assuming it's not just accepting SQL over HTTP)
- probably twice as many things that have slipped my mind

**Comment by monera23** [comment]
```
describe('all_tests', function() {

	it('test 1', (done) => {
		Promise.mapSeries(event, (e) => {
			
		}).then((results) => {
			
			done();
		}).catch((err) => {
			done(err);
		});
	});
      
	it('test 2', (done) => {
		Promise.mapSeries(event, (e) => {
			
		}).then((results) => {
			
			done();
		}).catch((err) => {
			done(err);
		});
	});
    
	it('test 3', (done) => {
		Promise.mapSeries(event, (e) => {
			
		}).then((results) => {
			
			done();
		}).catch((err) => {
			done(err);
		});
	});

	it('test 4', (done) => {
		Promise.mapSeries(event, (e) => {
			
		}).then((results) => {
			
			done();
		}).catch((err) => {
			done(err);
		});
	});
});
'''

In each Promise loop I make around 500-800 request(get, post, delete). So total around 3k requests.

**Comment by boneskull** [comment]
there's really not enough information here to be of further help.  I can suggest to you to split your tests up and run parallel `mocha` processes, assuming the build agent has multiple cores to work with.
