### ISSUE TITLE
use dont-break

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3013]
See [dont-break](https://github.com/bahmutov/dont-break) which is pretty awesome.

- take a look on [libraries.io](https://libraries.io) and see what the most popular packages built on top of mocha are (`mocha` would be a `dependency` of said projects)
- add a select few to the `dont-break` config

This could be slow, but perhaps do it as a `preversion` lifecycle script.

**BONUS POINTS**: Implement something that will automatically pull the top *n* packages depending on package *x* and hand them off to `dont-break`.

**Comment by ScottFreeCode** [comment]
I think we should also try this on a few of the most popular libraries to use Mocha as a `devDependency` for their own tests, in addition to those that actually build on Mocha. We'd get different value out of each of these -- one ensures we aren't changing popular ways of enhancing/abusing Mocha, the other ensures we don't accidentally screw up something for actual test usage that happens not to be covered by our own tests.

**Comment by boneskull** [comment]
here as some I picked from [libraries.io](https://libraries.io/npm/mocha/dependents) (give it time to load):

- `chai`
- `babel-core`
- `eslint`
- `webpack`
- `gulp`
- `rxjs`
- `express`
- `typescript`

some of these have really giant test suites, so it's not feasible to run this unless it's pre-release or nightly...

**Comment by boneskull** [comment]
a cursory run through these was not very successful. tests failed for unrelated reasons.  also it relies on git changesets (not npm versions) because many packages don’t publish their tests and/or dev environment. 

so we might have success pegging them to a particular tag, but it seems `master` is too volatile. also it’s unknown what kind of environment is expected from any given package...the dev environment may be particular while the runtime environment isn’t. 

let’s just let greenkeeper send PRs to upgrade 🙂
