### ISSUE TITLE
remove special cases around unsupported Node.js versions

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3029]
@ScottFreeCode I think basically we're looking at reverting  8710438c8de06b951b4ba99ac0e706c90fa94c91, but also if you see anything else in the code please zap that nasty

**Comment by boneskull** [comment]
please remove `lib/to-iso-string`; we don't need it any longer

**Comment by boneskull** [comment]
this is probably going to be an ongoing process... I've zapped some (shims) anyway.

**Comment by boneskull** [comment]
Not sure if there are any still hanging around; think I got most of them.

**Comment by boneskull** [comment]
If anyone wants to help here, please see that there's nothing weird leftover.

The only thing that *is* held back currently is the `buffer` package, which stays at ^4.0.0 for IE10 support.

**Comment by juergba** [comment]
> The only thing that is held back currently is the buffer package, which stays at ^4.0.0 for IE10 support.

Removed long time ago => closing this PR.
