### ISSUE TITLE
json-cov reporter should not print report to stdout

### ISSUE THREAD

**Issue by nherment** [mochajs/mocha#304]
Hi,

When running `mocha --reporter json-cov`, the coverage report is printed to `process.stdout`.

The consequence is that logs are mixed with the JSON coverage report. We are not using html-cov.
This forces us to parse stdout content and separate logs fron the JSON report. It's dirty coding and pretty much unreliable.

Mocha could take an extra parameter like `--file <fileName>` so that we can separate logs from reports.

Thanks,
- Nicolas

**Comment by darkxeno** [comment]
For me this makes sense too. Sometimes can be very difficult to remove all things going to the stdout, and having the possibility of use the logging on stdout and the reports directly on file can be useful.
