### ISSUE TITLE
unexpected token import if use of import with promise

### ISSUE THREAD

**Issue by wende60** [mochajs/mocha#3046]
### Prerequisites

* [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
Using a setup wit react and webpack 3, js/jsx is transpiled with babel preset es2015. Of course we use **import** to get the components, no problems so far. For code splitting we also use **import with promises** within functions. Running the test we now get the error "unexpected token import". Webpack itself runs without problems and creates the needed bundles.

### Steps to Reproduce
no problems with usual import like
`import React, { Component, PropTypes } from 'react';`

problems occur with promises to split the code:
```
    importLayout() {
        import('./foobar/index').then(module => {
            this.setState({ foobar: module.default });
        });
    }
```
In earlier Versions of Webpack this was done with **require.ensure**

the testing-script in package.json contains 
`mocha --compilers js:babel-register`

**Expected behavior:** 
Mocha has no problems wit the regular import, there should'nt be problems with the promises neither

**Actual behavior:**
Syntax Error while testing "unexpected token import"
The test is interrupted

**Reproduces how often:** 
always happening

### Versions
 If applicable, please specify:
 * The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 3.5.3
 * The output of `node --version`: v8.4.0
 * The version and architecture of your operating system: Mac OSX Sierra
 * Your shell (bash, zsh, PowerShell, cmd, etc.): Darwin
 * Your browser and version (if running browser tests): Any Browser, e.g. latest Chrome
 * Any other third party Mocha related modules (with versions):
 * The code transpiler being used: 6.26.0 (babel-core 6.26.0)

### Additional Information
Also tried with the latest version of Mocha without success

**Comment by ScottFreeCode** [comment]
- I could be wrong as I'm not an expert on it, but it seems far more likely to me that use of `import` as a function in that example is not being correctly transpiled than that the imported value being a promise would make any difference. You might try replacing `import(...).then` with `import promise from ...; promise.then` as a workaround if you can't find the right transpiler configuration.
- Am I understanding correctly that this works in Webpack but not with Babel without Webpack? If so, that would point toward Babel configuration problems -- although alternatively you might try testing the modules bundled by Webpack instead of just running Mocha with Babel (this is more complex but may be a more realistic test case if the package is meant to be used in its bundled form).
- Mocha *has no ability to affect this*. All it does is use `require` to load the transpiler; after that it's up to the transpiler to do its job.

**Comment by wende60** [comment]
The transpiler (babel) has no problems with it, Webpack has no problems with it - only Mocha does. The App itself runs properly...

import().then() can not be replaced by import from as the wanted behaviour is code splitting.

**Comment by boneskull** [comment]
how are you executing Mocha?

**Comment by boneskull** [comment]
also please provide a relevant test or harness

**Comment by wende60** [comment]
as mentioned above by a package.json script: **mocha --compilers js:babel-register**. The whole statement:

`"test-with-coverage": "export NODE_PATH=./src:./tests && find ./src -name '*.spec.js' | xargs nyc --require babel-register --require babel-polyfill mocha --compilers js:babel-register --require ./tests/helpers.js --require ignore-styles -R spec"`

Right now 138 test are running, usually without problems ;) 
I do not think the tests are special, like so:

import React from 'react';
import myComponent from './myComponent.js';
```

describe('(Component) myComponent', () => {
    let props = {};

    beforeEach(() => {
        props = {
            ... some props
        };
    });

    it('should not show any error as default', () => {
        // act
        const container = shallow(<MyComponentView {...props} />);
        // do something

        //assert
        expect(...).to.have.length(0);
    });
});
```
As i said: everything is running, only if a add the function above i run into syntax errors.

thanks for your feedback, cheers jo

**Comment by boneskull** [comment]
afaik `import()` is not recognized as a valid function name in Node.js even with the `--experimental-modules` flag unless babel knows to do something with it (and certainly the 2015 preset won't).  so you'll need to run tests against a bundle somehow.  best bet is read webpack docs about it; I'm not sure what's the best solution nowadays.

**Comment by wende60** [comment]
Whats about some kind of comment to tell mocha it should ignore the next lines?

**Comment by boneskull** [comment]
the syntax error is coming out of the javascript runtime not mocha
