### ISSUE TITLE
#after not working while other hooks (ie. beforeEach) are

### ISSUE THREAD

**Issue by ArThoX** [mochajs/mocha#3070]
### Prerequisites
* [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [no-idea] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
My test did work, but then I needed some post-test logic and I wanted to use #after.

My code is in ts ran through ts-node and this is a 'compilation' error but would you please advice ?
### Steps to Reproduce

```
process.env.NODE_ENV = 'test';

let mongoose = require("mongoose");

let chai = require('chai');
let expect = chai.expect;
let chaiHttp = require('chai-http');
import { app, end } from '../../src/server/app';
let should = chai.should();

chai.use(chaiHttp);
describe('Tests', () => {
  after(function(done) {
    end();
  });......
```
```
 mocha test/server/test.ts  --required --require ts-node/register                                                                                                                                   

/home/ubuntu/workspace/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
test/server/test.ts (13,3): Cannot find name 'after'. (2304)
    at getOutput (/home/ubuntu/workspace/node_modules/ts-node/src/index.ts:307:15)
    at /home/ubuntu/workspace/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/home/ubuntu/workspace/node_modules/ts-node/src/index.ts:498:11)
```

### Versions
```
xxx:~/workspace (master) $ mocha --version
4.0.1
xxx:~/workspace (master) $ node node_modules/.bin/mocha --version
4.0.1
xxx:~/workspace (master) $ node -v
v6.11.0
```

### Edit 1
Debugging I can see the #after defined (if I remove the call).
So this is a compilaltion issue about typecript not knowing #after is defined...

**Comment by ArThoX** [comment]
Used `TS_NODE_IGNORE_WARNINGS=TRUE TS_NODE_DISABLE_WARNINGS=TRUE` to fix my issue.
Seem dirty.

**Comment by ScottFreeCode** [comment]
You can assign local (module-level) variables for `describe`, `it` and the hooks by [getting them from `require("mocha")`](https://mochajs.org/#require).

Alternatively, based on poking around `ts-node`'s repo for documentation and examples, I've found that you can also have a configuration setting "compilerOptions" that includes a "types" entry that is an array that includes "mocha", and that allows Mocha's globals to be used -- it also appears that one has to `npm i @types/mocha` for this method to work. (If doing this gives errors about `require` I think there's a similar thing for including "node" in the "types" array, may or may not also have to `npm i @types/node`.) There might also be Typescript options to allow certain arbitrary globals to be treated as predefined, if necessary, but I imagine the standard globals configuration for Mocha should do as long as you're using Mocha's standard interfaces.

I'd recommend looking to the `ts-node` and/or the Typescript projects/communities for further support; there's not much more to know about it from Mocha's end beyond the fact that Mocha's interfaces are defined as global variables.
