### ISSUE TITLE
remove engines.npm from package.json

### ISSUE THREAD

**Issue by pabigot** [mochajs/mocha#3073]
### Prerequisites

* [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

Node 4.0 introduced an engine dependency on npm >= 2.15.11.  The [blog post](https://boneskull.com/mocha-v4-nears-release/#mochawillnolongersupportnpmolderthanv21511) says this is because that version shipped with Node.js v4.0.0.

This is incorrect.  [Nodejs v4.0.0 shipped with npm 2.14.2](https://github.com/nodejs/node/blob/v4.0.0/deps/npm/package.json).  Nodejs v4.5.0, which I have to use, shipped with 2.15.9.

It is true that the current Nodejs 4 (v4.8.4 at time of writing) does use 2.15.11, but that update wasn't done until v4.6.2.

Please consider reducing the dependency to 2.14.2, if your intent is to support all Nodejs 4 releases.
### Steps to Reproduce

**Expected behavior:** Installation of mocha 4.0.1 under nodejs 4.5.0 emits no diagnostics.

**Actual behavior:** 

    npm WARN engine mocha@4.0.1: wanted: {"node":">= 4.0.0","npm":">= 2.15.11"} (current: {"node":"4.5.0","npm":"2.15.9"})

**Reproduces how often:** Every time

**Comment by boneskull** [comment]
@pabigot Are you using AWS Lambda?

**Comment by boneskull** [comment]
@pabigot Also, is there anything other than a warning?

**Comment by boneskull** [comment]
See #3149 as well

**Comment by boneskull** [comment]
I'm not entirely sure what the intent *should* be.  Only the latest v4.x is maintained, so perhaps the `engines` field should be updated instead.

**Comment by boneskull** [comment]
or we could add 4.0.0 to the build matrix...

**Comment by pabigot** [comment]
No, I'm not using lambda.  It is a warning, but that warning suggests the claim of supporting >=4 (rather than >=4.6.2) is not justified: if I saw this in a production dependency I'd be much more concerned that it reflected a real failure to support.  Until action occurs on #3149 my preferred path is that the npm engine dependency be reduced to match the documented behavior and 4.0.0 be added to the build matrix.

I don't think it makes sense only support the latest release in any LTS series.  You'd spend a lot of time updating dependencies and annoying users who don't want to update their infrastructure every couple weeks.

**Comment by boneskull** [comment]
From what I understand, `npm`'s behavior when the `engines` field is violated is a *warning*, but Yarn will actually *error* and refuse to install.

Given that a version of `npm` which fails to install Mocha is by definition incompatible, one can find that out rather directly by attempting to install Mocha with said incompatible version.  :smile:

I am proposing removal of the `engines.npm` field, since we can't be certain what it does or what value it provides in any given situation.

**Comment by boneskull** [comment]
@pabigot #3154

**Comment by pabigot** [comment]
@boneskull I don't see any issues with the solution in #3154.

**Comment by boneskull** [comment]
@pabigot #3154 is the fix to remove the field and thus the warning.
