### ISSUE TITLE
Performance problem. An execution time of entire test suit is not equal to the execution time of its parts.

### ISSUE THREAD

**Issue by AIRTucha** [mochajs/mocha#3078]
### Prerequisites

* [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

I have a big test suit which contains to major describe-blocks. The first one takes me 3 seconds to run and the second one 2, but tougher they are executed for 17 seconds. It is visually noticeable that inside of a test suit latter tests are slower then if they are executed independently.

### Steps to Reproduce

1) Create a test suit with two describe-blocks
2) Run each of them separately with .only()
3) Run entire pack of tests at ones.

**Expected behavior:** 

Some of test suit part's execution time have to be roughly equal to the execution time of entire test suit.

**Actual behavior:** 

Entire test suit execution takes several times more time than a sum of an execution  time of its part separately.

**Reproduces how often:**

Always.

### Versions

mocha: 3.4.2
node: v6.11.3
Windows 10, ArchLinux, Mac OS High Sierra, Fedora Linux
Any terminal ( we develop project at several different machines with different os and terminals )

**Comment by ORESoftware** [comment]
I think a code sample would help. Create a repo and share the repo?
