### ISSUE TITLE
Option.args mochaOpts tagging tests

### ISSUE THREAD

**Issue by djordje-mmilovanovic** [mochajs/mocha#3086]
I have tried to run my tests with in-line args, but it seems i cant find right syntax for it.
My cmd command for calling the test is:  

grunt e2e:cert:ed:regression_part_3   

and am trying to add tagging args something like this:

 grunt protractor --mochaOpts={tags: "myTag"} e2e:cert:ed:regression_part_3

but it doesn't seem to work ... 
any ideas ?

**Comment by ScottFreeCode** [comment]
Hi @djordje-mmilovanovic,

Sorry about the late reply -- Mocha doesn't have a built-in tagging feature or a `tags` option, nor is this style of Mocha options part of the "vanilla" library, so this probably has to do with Protractor or the Grunt plugin you're using, and you'll probably get more specific guidance from either or both of those projects.

I can tell you just at a glance that you probably need to quote the whole argument containing `{` and `}` as those tend to be interpreted specially by shells. Hope that helps at least.
