### ISSUE TITLE
Using only() to run a specific test is too quiet

### ISSUE THREAD

**Issue by alexmuller** [mochajs/mocha#3087]
### Prerequisites

* [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

Mocha should be louder when the `only()` method is used, for example by outputting an obvious warning to the console. The docs say:

> Be mindful not to commit usages of `.only()` to version control, unless you really mean it!

But this isn't really enough. It's still easy to accidentally commit `.only()` and disable a large part of a test suite without noticing. I'd love an output to the console that says something like:

```
=================================================
You're using .only() to disable some tests!
=================================================
```

### Steps to Reproduce

**Expected behavior:** Use `.only()`, accidentally commit it and your colleagues are more likely to notice that it's there

**Actual behavior:** Use `.only()`, accidentally commit it and have it disable most of your test suite for a year before anyone notices :scream:

**Reproduces how often:** Always

### Versions

1.18.2 and 4.0.1 are both affected.

**Comment by markowsiak** [comment]
@alexmuller Thanks for submitting this issue about the developer experience you've had.  It's surely one that has impacted many people and projects before, myself included.  I'll look into this further with other contributors.

In my history, I've seen teams and individuals perform pre-commit hooks as seen here: https://github.com/mochajs/mocha/issues/1529#issuecomment-77232425

I'll leave this open and follow up again soon.

**Comment by alexmuller** [comment]
Thanks very much! Similar to what's mentioned in the linked issue, my friend points out that Ginkgo (a test framework for Golang) always exits with a non-zero code when running a subset of tests:

> When Ginkgo detects that a passing test suite has a programmatically focused test it causes the suite to exit with a non-zero status code. This is to help detect erroneously committed focused tests on CI systems. When passed a command-line focus/skip flag Ginkgo exits with status code 0 - if you want to focus tests on your CI system you should explicitly pass in a -focus or -skip flag.

https://onsi.github.io/ginkgo/#focused-specs

**Comment by ScottFreeCode** [comment]
For what it's worth:

- The `--forbid-only` flag was created to address this.
- We have #3030 about making it the default.

**Comment by markowsiak** [comment]
I think we can safely close this if favor of #3030.  Please track it's progress there @alexmuller 👍
