### ISSUE TITLE
Bail with failing after() runs suite twice

### ISSUE THREAD

**Issue by rawb** [mochajs/mocha#3096]
### Prerequisites

* [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
With a failing test suite using the `bail` option in conjuncture with an `after` clause that throws an error.
Mocha bails properly, executes the after as expected.
Then it does it all again. [But Why?](https://media.giphy.com/media/s239QJIh56sRW/giphy.gif)

### Steps to Reproduce
Very simple repro steps.
File new with latest mocha.
```  
"scripts": {
    "test": "./node_modules/.bin/mocha --reporter spec --bail"
  }
```
and
```
describe("some suite", function() {
    it("does the first test", function() {
        throw new Error('first error')
    });
    after(() => {
        throw new Error('after error')
    })
})
```
yarn test, observe double suite run
remove error in after, observe one suite run

**Expected behavior:** [What you expect to happen]
test suite is only ran once
**Actual behavior:** [What actually happens]
test suite is ran twice
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

node node_modules/.bin/mocha --version => `4.0.1`
macOS Sierra 10.12.6
zsh

**Comment by ScottFreeCode** [comment]
Seems to happen for me no matter which hook is used (`after`, `before`, `afterEach`, `beforeEach`), regardless of whether the test passes or fails, and no matter whether they are inside a `describe` or not.

Doesn't rerun the tests as far as I can tell, just prints the final summary/results twice -- probably some variation of #2906 (strange that there are so many different things that can cause such behavior).

**Comment by plroebuck** [comment]
Possible that the fix to this problem should have been done [here](https://github.com/outsideris/mocha/blob/e798eeca5ba3e9d6e37a1d9bfa2ed9ff8215b6dc/lib/runner.js#L842) instead?

Done is done, right? Just process the event **once**.

```js
this.once('end', function () {
    debug('end');
    process.removeListener('uncaughtException', uncaught);
    fn(self.failures);
});
```
