### ISSUE TITLE
File globbing not documented on site

### ISSUE THREAD

**Issue by wzup** [mochajs/mocha#3098]
How to configure it? This for example
> By default, mocha looks for the glob ./test/*.js and ./test/*.coffee, so you may want to put your tests in test/ folder.

No any info in whole [docs](http://mochajs.org/) and wiki

**Comment by ORESoftware** [comment]
+1

**Comment by ScottFreeCode** [comment]
Besides https://mochajs.org/#the-test-directory, there is https://mochajs.org/#usage:

> Usage: mocha [debug] [options] [files]
> (...list of options...)

However, I'm surprised that we don't have anywhere that the possibilities of *globbing* are highlighted, e.g. using `lib/**/*.test.js`. Even if we just pointed people at the `glob` NPM package for details on the supported syntaxes. (Although I think it would probably also be worth mentioning the pattern of putting files that *need* to run inside `mocha.opts` and then the default all-tests glob inside the `test` script in `package.json` so `npm test` runs all tests but `mocha <path to specific file>` runs only specific tests.)

I'm also surprised at the reference to Coffeescript -- I'm pretty sure that hasn't actually been part of the default for a long time... Clearly this whole section is long overdue for some TLC.

Site repo is at https://github.com/mochajs/mochajs.github.io, although we eventually want to get it merged into this repo...
