### ISSUE TITLE
describe.only and context.only run all the describe/context suites which match the pattern instead of only one selected describe/context suite

### ISSUE THREAD

**Issue by piotr-s-brainhub** [mochajs/mocha#3099]
### Prerequisites
* [X] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [X] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [X] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [X] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
Using `describe.only` causes that instead only this one `describe` suite, mocha runs all the `describe` suites which match the pattern given as the `describe.only` suite's message.

The same is for `context.only`.

It works correctly for `it.only` if there is no additional only at the `describe` or `context` level.

### Steps to Reproduce

* case 1:
  **Expected behavior:** [What you expect to happen]
  I run `./node_modules/.bin/mocha foobarbaz.js`
  `foobarbaz.js`:
  ```
  describe('GET /users', () => {
    it('foo', () => {});
  });

  describe.only('GET /', () => {
    it('bar', () => {});
    it('baz', () => {});
  });
  ```

  It should run only `GET /` tests
  ```
  GET /
    ✓ bar
    ✓ baz
  ```
  **Actual behavior:** [What actually happens]
   It runs all the tests
  ```
  GET /users
    ✓ foo

  GET /
    ✓ bar
    ✓ baz
  ```
  **Reproduces how often:** [What percentage of the time does it reproduce?]
100 %

* case 2:
  **Expected behavior:** [What you expect to happen]
  I run `./node_modules/.bin/mocha foobarbaz.js`
  `foobarbaz.js`:
  ```
  describe('GET /users', () => {
    it('foo', () => {});
  });

  describe.only('GET /', () => {
    it('bar', () => {});
    it.only('baz', () => {});
  });
  ```

  It should run only `GET / baz` test
  ```
  GET /
    ✓ baz
  ```
  **Actual behavior:** [What actually happens]
   It runs all the tests
  ```
  GET /users
    ✓ foo

  GET /
    ✓ bar
    ✓ baz
  ```
  **Reproduces how often:** [What percentage of the time does it reproduce?]
100 %

* case 3:
  **Expected behavior:** [What you expect to happen]
  I run `./node_modules/.bin/mocha foobarbaz.js`
  `foobarbaz.js`:
  ```
  describe('', () => {
    context('GET /users', () => {
      it('foo', () => {});
    });

    context.only('GET /', () => {
      it('bar', () => {});
      it('baz', () => {});
    });
  });
  ```

  It should run only `GET /` tests
  ```
  GET /
    ✓ bar
    ✓ baz
  ```
  **Actual behavior:** [What actually happens]
   It runs all the tests
  ```
  GET /users
    ✓ foo

  GET /
    ✓ bar
    ✓ baz
  ```
  **Reproduces how often:** [What percentage of the time does it reproduce?]
100 %

### Versions
 * mocha version: 2.5.3
 * NodeJS version: 8.6.0
* npm version: 5.5.1
 * OS: Mac OS X 10.12.2
 * shell: fish 2.4.0

**Comment by ORESoftware** [comment]
fyi if you remove the space before the X it will render correctly

before

[ X] Checked t

after

[X] Checked t

**Comment by ORESoftware** [comment]
+1

**Comment by ScottFreeCode** [comment]
This was changed in version 3 (the current major version line is 4); there are no plans to change it in the old version 2 line.

(In the old version `only` was a shortcut for `grep`ping that suite or test's title. The suites/tests are now programmatically filtered for whether they were marked `only` instead, and these examples work as expected.)
