### ISSUE TITLE
BDD vs TDD: setup and teardown

### ISSUE THREAD

**Issue by goloroden** [mochajs/mocha#310]
Is there a special reason why BDD style supports
- before
- beforeEach
- after
- afterEach

but TDD only supports
- setup
- teardown

?

**Comment by raine** [comment]
@louwers I think setup and teardown are the TDD counterparts.

#91

**Comment by danielstjules** [comment]
Exactly :)

![screen shot 2015-03-07 at 12 15 08 pm](https://cloud.githubusercontent.com/assets/817212/6543107/ae6f5b72-c4c3-11e4-8d52-d8eb6b90e7d2.png)

**Comment by dschinkel** [comment]
BDD are different style and kind of tests, I think you should keep it separate mocha team.

**Comment by kashiraja** [comment]
The documentation should probably say the following instead:

```
suite('Array', function() {
  suiteSetup(function() {           <--- suiteSetup() instead of setup()
    // ...
  });

  suite('#indexOf()', function() {
    test('should return -1 when not present', function() {
      assert.equal(-1, [1,2,3].indexOf(4));
    });
  });
});
```

**Comment by ORESoftware** [comment]
@dschinkel  can you explain more

**Comment by dschinkel** [comment]
don't remember, but not sure why we even need two separate types of tests.  If you BDD, it includes the TDD cycle.  I just use beforeach or whatever.  I don't see why there is another "TDD" style in here.

**Comment by gopherkhan** [comment]
I was looking through the docs for explanations as well. Surprised this request has been open since 2012...

**Comment by SirJackovich** [comment]
BDD:
describe
it
before
beforeEach
after
AfterEach

TDD:
suite
test
suiteSetup
setup
suiteTeardown
teardown
