### ISSUE TITLE
Run code before beforeEach for each it

### ISSUE THREAD

**Issue by csutorasr** [mochajs/mocha#3112]
### Description

I would like to have a new type of test with I can reduce the repetition or code.

The problem happens if I have mocked something for the component and little changes needed to be done to the mocks. (e. g. for this test I need another value for test 6) In the `beforeEach` I create the component, with the dependencies. If I do the modification in the `it` the component is created and I can't apply changes to the mock for the creation part.

Example code:

```javascript
class Component {
  constructor(service) {
    this.data = service.ex();
  }
}
```

```javascript
describe('component', () => {
  const mock = {
    ex() { return 1; }
  };
  let component;
  beforeEach(() => {
    component = new Component(mock);
  });
  it(() => {
    expect(component.data).toEqual(1);
  });
  it(() => {
    spyOn(mock, 'ex').and.returnValue(2); // The component is created, it is too late to set value.
    expect(component.data).toEqual(2);
  });
});
```

A workaround can be:

```javascript
describe('component', () => {
  const mock = {
    ex() { return 1; }
  };
  let component;
  it(() => {
    component = new Component(mock);
    expect(component.data).toEqual(1);
  });
  it(() => {
    spyOn(mock, 'ex').and.returnValue(2);
    component = new Component(mock);
    expect(component.data).toEqual(2);
  });
});
```

But the real solution would be:

```javascript
describe('component', () => {
  const mock = {
    ex() { return 1; }
  };
  let component;
  beforeEach(() => {
    component = new Component(mock);
  }, {
    name: 'creation'
  });
  it(() => {
    expect(component.data).toEqual(1);
  });
  it(() => {
    expect(component.data).toEqual(2);
  }, {
    before:{
      creation: () =>  spyOn(mock, 'ex').and.returnValue(2); // The component is not created.
    }
  });
});
```

### Additional information:

Sometimes the code of creation is not one line and it is really annoying if the test file has the same lines in most of the tests.

**Comment by ORESoftware** [comment]
+1

**Comment by boneskull** [comment]
@ORESoftware please use reactions instead of adding "+1" all over the place

**Comment by boneskull** [comment]
@csutorasr you could nest suites as another strategy:

```
describe('component', () => {
  const mock = {
    ex() { return 1; }
  };
  let component;
  describe('component a', function () {
    it(() => {
      component = new Component(mock);
      expect(component.data).toEqual(1);
    });
  });
  describe('component b', function () {
    it(() => {
      spyOn(mock, 'ex').and.returnValue(2);
      component = new Component(mock);
      expect(component.data).toEqual(2);
    });
  });
});
```

likewise you can use `beforeEach` to create `component` (I would).  but this is perhaps more of a OO design issue than a Mocha issue...

> as an aside, you may want to avoid using lambdas for the callbacks, as every test, hook and suite has a context object.  it can make refactoring difficult if you ever need to use, say, `this.timeout()`.

**Comment by csutorasr** [comment]
This is the same solution as my workaround. The problem is the code cannot be reused inside of the two `it`. (As I wrote it sometimes was longer code.)

**Comment by boneskull** [comment]
@csutorasr if your code is difficult to test, you may want to consider a different design.  would lazy evaluation work? 

```js
class Component {
  constructor(service = defaultService) {
    this.service = service;
  }

  get data() {
    return this.service.ex();
  }
}

const c = new Component();
c.service = mockService;
expect(c.data).to.equal(whatever);
```
