### ISSUE TITLE
Redundant Folders of Pictures

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mocha#3117]
Mocha's repo has no less than three different folders at the top level for pictures: `assets`, `images` and `media`. Some of these are used in Growl notifications and should live or die with the Growl integration. The rest... actually, I'm not sure they're used *anywhere*. Unless the (*currently* separate) mocha website is somehow pulling in images from this repo, or something.

While this isn't technically harmful, it's needlessly confusing for new contributors (one of whom brought it to my attention by asking when to look in which folder, more or less). I'd like to propose that:

- Any of these that need to be in this repo should get moved into a single folder and organized in subfolders that indicate how they're used or what they're for.
- Any of them that are needed but do not need to be in this repo get moved either to where they're needed (e.g. if they're part of the site put them with the site) or into some dedicated repo or host.
- Any of them that are no longer needed should be removed (if we really want to get them back for some reason we can always dig them out of the commit history).

(NOTE: If some of them are needed for running Mocha, e.g. the Growl ones, and others are only needed e.g. for the readme or the site, this plan *may* require us to be more specific with specifying which files to publish instead of publishing the whole images folder.)

**Comment by DavNej** [comment]
Hi @ScottFreeCode 
is this issue still on? I'd be glad to make it my first contribution!

**Comment by markowsiak** [comment]
@DavNej  I assigned it to myself, but if you're interested in it please take it over an let me know 👍
