### ISSUE TITLE
TextMate integration?

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mocha#3118]
It appears Mocha's repo sports an unadvertised TextMate integration that can be installed using `make tm`.

Why is TextMate the only editor or IDE with an integration directly maintained as part of Mocha itself?

Can we move this out into its own repo? (Would that be semver-major? The install is with `make` instead of `npm run` and it's only available in the first place if you clone the repo, not if you `npm i mocha`.)

It doesn't seem like it's needed maintenance since I've been here, but it would be one fewer folders for new contributors to wonder about.

**Comment by Bamieh** [comment]
@ScottFreeCode IMO Its not semver-major since its not bundled upon installation through `npm`. after all the the versioning is set on npm's `package.json` file. it's like removing an unused file. Those who need it need to npm install another mocha module.
