### ISSUE TITLE
Mocking mobile user agent

### ISSUE THREAD

**Issue by NateZ7** [mochajs/mocha#3121]
* [x ] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [ x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [ x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [ x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
I have a unit test to test an android/ios update

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

Versions -
mocha - 4.0.1
node - 6.11.4
os - MacOS

my code is -

```
  describe('GET /ios/update', function () {
  	it('should update ios', function (done) {
 	   		var self = this;
      	self.sess.get('/ios/update')
      	.expect('Content-Type', /json/)
        .expect(200, done);
      });
});
```

I just want to be able to mock a mobile user agent for the test above.
Thanks !

**Comment by boneskull** [comment]
Hi @NateZ7, please ask on stackoverflow or [our chat room](https://gitter.im/mochajs/mocha)
