### ISSUE TITLE
Bizarre test case pattern passes without errors

### ISSUE THREAD

**Issue by ORESoftware** [mochajs/mocha#3126]
### Prerequisites

* [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. 

### Description

We have this in package.json

```json
    "karma": "^1.7.1",
    "karma-chai": "^0.1.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-jasmine": "^1.1.0",
    "karma-junit-reporter": "^1.2.0",
    "karma-mocha": "^1.3.0",
    "karma-ng-html2js-preprocessor": "^1.0.0",
    "karma-sinon": "^1.0.5",
    "karma-sonarqube-unit-reporter": "0.0.14",
    "karma-spec-reporter": "0.0.31",
    "karma-webdriver-launcher": "^1.0.5",
    "mocha": "^4.0.1",
```

We are using Mocha with Karma. My coworker wrote a bunch of tests that look like this.
They should totally fail, but they don't fail, they pass.  But `assigneeList` should be undefined. I am mystified. Does anyone know why an error would not be thrown?

```js
  it('should get a assignment with id', function () {

      //expectGET to make sure this is called once.
      var url = encodeURI('/api/v1/assignments?filter={"promptId":"foobar"}');

      httpBackend.expectGET(url).respond(assigns);

      var assigneeList;

      myService.getAssignmentsByPromptId("foobar").then(function (response) {
        assigneeList = response;
      });

      httpBackend.flush();

      expect(assigneeList.length).to.equal(2);  // assigneeList should be undefined...
      expect(assigneeList[0]._id).to.equal(assigns[0]._id);
    });
```

**Comment by boneskull** [comment]
there is black magic here, and I only know that because I wrote a lot of angular.

promises in angular 1.x are weird.  `httpBackend.flush()` causes your callback `assigneeList = response` to execute *synchronously*.  `console.log` it and be amazed...

**Comment by ORESoftware** [comment]
yeah I did log it, I think sometimes the logging order is messed up because of Karma, one time I logged it and the order was as you said, then I was in disbelief and the next 20 times I logged it was in the order you'd expect with real promises. But I believe you, because that's the only way it makes sense.
