### ISSUE TITLE
drop node.js v7 from build matrix; add node.js v9

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3127]
I think it's safe to do this now that npm v5.6.0 has been released.

**Comment by xxczaki** [comment]
Yeah, if npm is working on Node.js 9.0 we should definitely add it, but i'm not sure about dropping Node.js 7.0 from build matrix...

**Comment by boneskull** [comment]
node 7 is not maintained afaik. safe to drop

**Comment by Bamieh** [comment]
closing this since the implementation is merged on master (fixed by  https://github.com/mochajs/mocha/pull/3185)
