### ISSUE TITLE
stop using phantomjs to run browser tests

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3128]
headless Chromium probably makes sense.  I'm not sure how far along headless FF is yet, but would prefer this over Chromium.

- [ ] remove karma-phantomjs-launcher
- [ ] add [karma-headless-chrome-launcher](https://npm.im/karma-headless-chrome-launcher)
- [ ] reconfigure `karma.conf.js` as appropriate

**Comment by boneskull** [comment]
(the reason is phantomjs is no longer maintained afaik and probably fewer problems than a major browser in headless mode)

**Comment by akrawchyk** [comment]
@boneskull @ScottFreeCode PR submitted let me know what you think
