### ISSUE TITLE
Documented Undocumented Reporters

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3131]
_From @ScottFreeCode on October 4, 2017 3:58_

https://mochajs.org/#undocumented-reporters documents the XUnit reporter. Instead of the section being labelled "XUnit", it is labelled "Undocumented Reporters". Since the section documents the XUnit reporter, the XUnit reporter is not undocumented as the section name implies.

Amusing anecdote: this reminds me somewhat of the Liar Paradox, but I think it can be resolved without needing to understand the Incompleteness Theorem. (...It is possible I am using a non-standard implementation of the amusement module...)

_Copied from original issue: mochajs/old-mochajs-site#83_

**Comment by outsideris** [comment]
This was fixed already in https://github.com/mochajs/mocha/commit/bca57f438037b7ce2906b4b8f7ab4b9fba5d8102 .
We can close it.

**Comment by boneskull** [comment]
ty
