### ISSUE TITLE
"features" list should link to the documentation for said feature.

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3135]
_From @AshKyd on December 16, 2015 1:38_

Invariably when I land on the Mocha site and search for a thing, I land on the "Features" list and am dismayed that it's not clickable. IMO the features list should link to the relevant feature docs, similar to the TOC.

![image](https://cloud.githubusercontent.com/assets/49600/11829607/4f1d8cb0-a3e9-11e5-99de-5975c7c6a5ff.png)

I'm happy to look into this if there's no objections.

_Copied from original issue: mochajs/old-mochajs-site#21_

**Comment by boneskull** [comment]
_From @hollomancer on August 15, 2016 3:53_

@AshKyd - still interested in looking into this?

**Comment by AshKyd** [comment]
Nah, close it. Completely fell off my radar :D

**Comment by xxczaki** [comment]
I can try to do something with this, seems like an interesting feature 😄 Don't close it
