### ISSUE TITLE
Document `enableTimeouts` option

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3137]
_From @boneskull on July 12, 2015 4:14_

from mochajs/mocha#1281

> The option was added in 1.21.0, but it is not documented yet.

_Copied from original issue: mochajs/old-mochajs-site#7_

**Comment by 38elements** [comment]
`enableTimeouts` is `--no-timeouts `.
I think `--no-timeouts ` exists at [docs/index.md](https://github.com/mochajs/mocha/blob/6fc2d9e90c4b190811173da3e8db5f2cef45a6d4/docs/index.md#usage).


https://github.com/mochajs/mocha/blob/6fc2d9e90c4b190811173da3e8db5f2cef45a6d4/bin/_mocha#L266-L270
