### ISSUE TITLE
Add timeout option to xits using arrow functions

### ISSUE THREAD

**Issue by MattOakley** [mochajs/mocha#3142]
### Prerequisites

* [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

When using the arrow function syntax to override the default timeout. You specifiy it on the return value of the it function.

    it("should override the timeout", () => { }).timeout(100);

But if we want to ignore the test by adding an x we get an exception, which is annoying.

### Steps to Reproduce

    // Throws
    xit("should override the timeout", () => { }).timeout(100);

**Expected behavior:** The test should be ignored

**Actual behavior:** We get an exception
>> Mocha` exploded!
>> TypeError: Cannot read property 'timeout' of undefined

**Reproduces how often:** 100%

### Versions
mocha 4.0.1

**Comment by boneskull** [comment]
Is this a documented API?  I don't recall ever seeing anyone use this before.

**Comment by boneskull** [comment]
anyway, this looks pretty trivial to address.   I'm going to call it a bug even though it's more of an "internal consistency" issue, since we don't necessarily expect consumers to use the object returned from `it` or `xit` for anything.

**Comment by Bamieh** [comment]
@boneskull this is a very interesting side effect of returning the test object from inside the `it` function. I have a PR coming in a few.

**Comment by boneskull** [comment]
@Bamieh I've already got one ready ;)

**Comment by boneskull** [comment]
@Bamieh beat me to it
