### ISSUE TITLE
Mocha only runs one test

### ISSUE THREAD

**Issue by javahaxxor** [mochajs/mocha#3159]
### Prerequisites

* [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

Mocha doesn't run all tests, just one
### Steps to Reproduce
See the attached screenshots. Neither mocha test/**/*.spec.js nor mocha --recursive work for me

**Expected behavior:** [What you expect to happen]
all tests in the directory should be executed
**Actual behavior:** [What actually happens]
Only one test is ran
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions

mocha version 4.0.1
 I'm getting this error on both OSX and Linux, regardless of globstar settings
### Additional Information

I'm wondering if there is a bug. I'm getting this error on both OSX and Linux:
![screen shot 2017-12-12 at 18 29 33](https://user-images.githubusercontent.com/3932029/33899059-9230cf26-df6a-11e7-93b2-4ea5fd2d2317.png)
![screen shot 2017-12-12 at 18 31 32](https://user-images.githubusercontent.com/3932029/33899093-b3558c46-df6a-11e7-8bb2-97d2b9275eb7.png)
![screen shot 2017-12-12 at 18 33 29](https://user-images.githubusercontent.com/3932029/33899187-06433156-df6b-11e7-8b35-07e08189070d.png)

**Comment by boneskull** [comment]
I don't understand which test file(s) aren't executed which are supposed to be.  from that first screenshot, it looks like they all might be... but I can't really tell you more without more info about the repo.

you could try removing `mocha.opts` and see what happens

**Comment by ORESoftware** [comment]
could it be an `.only` call?

**Comment by wertlex** [comment]
Same here. 
I made simple example: https://github.com/wertlex/mocha-recursive-issue

Issue is in `npm run test-wildcard-recursive`. Expected mocha will run tests from both `test/admin` and `test/admin/superadmin`, but only first one run. 

Looks like `mocha ./test/**/*.js --recursive` not works as expected.

**Comment by wertlex** [comment]
Found. This problem explained here: https://github.com/mochajs/mocha/issues/3136
@javahaxxor you just need quotes
@boneskull this issue can be closed

**Comment by javahaxxor** [comment]
@wertlex I have quotes ..

**Comment by outsideris** [comment]
@javahaxxor Can you show your example which has the problem like @wertlex

**Comment by boneskull** [comment]
@javahaxxor grep for `.only` in your tests
