### ISSUE TITLE
Error message masked in async hook when thrown after done() already called "successfully"

### ISSUE THREAD

**Issue by JamesMaroney** [mochajs/mocha#316]
I have an interesting situation where my async beforeEach thinks it's completed successfully, so I call done(). But, in reality an async loader issue ultimately threw an error. Due to the check for multiple calls to done, the error message (of the second call to done) is masked.
### Details:

I am running mocha (latest) in node, but testing modules written for requirejs.

There is an interesting situation where you can require a module which has async module requirements embedded inside it. Something like:

_first/module:_

``` coffeescript
define [], ->
  require ['some/module'], (someModule) ->
  return {}
```

If the nested require fails (for instance, the module is not found), an error is thrown -- but not before the original requestor of _first/module_ was given the `{}` object.

In this case, it is easy for the original requestor to think that all is well and call done(). Then, the exception is thrown by requirejs and ultimately `done(err)` is called via your _runnable.js_
### Possible solution:

Without a comprehensive study of the impact of such a change, the following modification appropriately fixes the issue for me.

Replacing [this line](https://github.com/visionmedia/mocha/blob/master/lib/runnable.js#L130) with

``` javascript
if (finished) return err ? fn(err) : multiple();
```

**Comment by chalecao** [comment]
if you call mocha.run() in a module define function, it may cause "script error " uncaught function, it's odd. may be different define and require realization may cause the error. when i debug, i found that async test case turns null when call done function, if you set a debugger in the 
` self.runTest(function (err) {
         debugger
        test = self.test;
        if (err) {`
you will see
