### ISSUE TITLE
Enable Let's Encrypt SSL on mochajs.org with Netlify

### ISSUE THREAD

**Issue by xxczaki** [mochajs/mocha#3174]
https://www.netlify.com/docs/ssl/

@Munter 😄

**Comment by boneskull** [comment]
@xxczaki  What's the advantage of this vs. Netlify's managed SSL?

**Comment by Munter** [comment]
I'll take a look at it when the name servers are changed to netlify. Before they can verify that move, none of the other DNS settings are activated

**Comment by Munter** [comment]
This should be done now. Awaiting full DNS propagation and browser dns cache timeouts for everyone to get the page from the right host
