### ISSUE TITLE
--retries <number> doesn't work

### ISSUE THREAD

**Issue by luoxi001713** [mochajs/mocha#3178]
I use following, case failed but doesn't retry, it there something wrong? Or I use the wrong way.
`mocha  --retries 2 casename.spec.js`

**Comment by Bamieh** [comment]
which version of mocha are you using? the retries are working fine, try this code snippet for example:

```javascript
let counter = 0;
describe('lol', function() {
  it('lols', function() {
    if(counter > 1) {
      console.log('counter::', counter) //logs 3
    } else {
      throw new Error(++counter)
    }
  })
})
```
