### ISSUE TITLE
Mocha stack trace color conflicts with solarized light background

### ISSUE THREAD

**Issue by zwhitchcox** [mochajs/mocha#3183]
* [x ] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [x ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [x ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [x ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
text does not show up on solarized light

### Steps to Reproduce

add solarized light theme to your terminal and run mocha.  the error stack trace is the same color as the background. solarized light is a very common theme, and it seems worth avoiding this collision

**Reproduces how often:** 100%

### Versions
mocha version 4.0.1
node version 8.4.0
GalliumOS, xfce
just the regular terminal program
bash
babel-register

Really, ideally, you would be able to configure mocha with custom colors. I don't know why this feature wouldn't be included, but maybe it's more difficult than I realize.

**Comment by zwhitchcox** [comment]
So, I was able to fix my problem by changing one line https://github.com/mochajs/mocha/blob/master/lib/reporters/base.js#L64 to 92.

It seems like it would be easy to expose this to the user, and I wouldn't have to do that every time I install my project or any other and not have to maintain a separate version of mocha just for this one line.

It would be really appreciated.

Thank you.

**Comment by boneskull** [comment]
@zwhitchcox please search the issue tracker (more?) before creating issues

duplicate

**Comment by zwhitchcox** [comment]
I did search, but I didn't see one. Could you please show me where this already exists?

**Comment by boneskull** [comment]
search for "solarized" or "colors" etc etc.  

paraphrased:  solarized is broken, not mocha.  use a different color scheme.

**Comment by zwhitchcox** [comment]
Ok, so you're not gonna fix this?

**Comment by zwhitchcox** [comment]
Sorry, if I seem dense, it just seems unbelievable to me that you wouldn't fix something so simple that is affecting so many people. Kind of hard to believe to me.

**Comment by boneskull** [comment]
the bug is not in mocha so there is no fix. solarized is broken; use another color scheme
