### ISSUE TITLE
mocha.options.document

### ISSUE THREAD

**Issue by daarond** [mochajs/mocha#3186]
### Prerequisites

* [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
I have a cordova app I am testing with mocha. The UI styles make playing well with divs difficult, so pushing the mocha output to an iframe or other window makes things easier to see. I have a branch that replaces 8 instances of "document" with a getMochaDocument method, returning the option document value or the regular document, if not set. With your blessing, I will offer a pull request.

Usage:
```
<iframe id="testiframe"></iframe>
</body>
</html>
<script>
    let framesrc = '<link href="https://cdn.rawgit.com/mochajs/mocha/2.2.5/mocha.css" rel="stylesheet" />';
    framesrc += '<body><div id="mocha"></div></body>';
    $('#testiframe').contents().find('html').html(framesrc);
	mocha.checkLeaks();
	mocha.globals(['jQuery']);
	mocha.options.document = document.getElementById("testiframe").contentDocument;
	mocha.run();
</script>
```

**Comment by boneskull** [comment]
Can you please explain a bit more about why this is necessary?

**Comment by daarond** [comment]
Decided to go another way.
