### ISSUE TITLE
Mocha screws with npm environment variables

### ISSUE THREAD

**Issue by alasdairhurst** [mochajs/mocha#3188]
### Prerequisites

* [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
When running a node script/app as part of a package.json script, for example "npm run test", npm will inject config variables into process.env.

For example:

```
  npm_config_cache_min: '10',
  npm_config_cafile: '',
  npm_config_cert: '',
  npm_config_cidr: '',
  npm_config_color: 'true',
  npm_config_commit_hooks: 'true',
  npm_config_depth: 'Infinity',
  npm_config_description: 'true',
```

When logging out these variables in a mocha test, the unset ('') variables in the example above are the string 'undefined'. This causes issues when spawning npm since 'undefined' is an invalid value for a lot of these keys.

```
  npm_config_cache_min: '10',
  npm_config_cafile: 'undefined',
  npm_config_cert: 'undefined',
  npm_config_cidr: 'undefined',
  npm_config_color: 'true',
  npm_config_commit_hooks: 'true',
  npm_config_depth: 'Infinity',
  npm_config_description: 'true',
``` 

Spawning a regular node process with the code ``console.log(process.env)``` does not have these undefined values and looks like the example.

### Steps to Reproduce

1. Create index.js 
``` console.log(process.env) ```
2. Create an empty node app with a mocha dependency.
2a. npm init
2b. npm i mocha

3. create 2 scripts in package.json:
``` 
"scripts": {
  "node": "node index.js",
   "mocha": "mocha index.js"
}
```
4. run ```npm run node``` and ```npm run mocha```
5. compare the outputs of both commands.

**Expected behavior:** indentical output aside from any mocha specific variables which may be added.

**Actual behavior:** any npm_config_ values which were '' before are now 'undefined'

**Reproduces how often:** All the time

### Versions
 * The output of `mocha --version` and `node node_modules/.bin/mocha --version`:  4.1.0
 * The output of `node --version`: 8.9.1
 * The version and architecture of your operating system: Windows 10 1607
 * Your shell (bash, zsh, PowerShell, cmd, etc.): cmd and git bash

**Comment by boneskull** [comment]
I can't reproduce this.  Will need more information

**Comment by alasdairhurst** [comment]
@boneskull What information do you think would be useful? I can't think of anything relevant so I guess I'll have to step through the source.

**Comment by MCSH** [comment]
I ran this test, I can not reproduce the error as well: 

```
[~/tmp/mocha2]$ mocha index.js > res1.txt 
[~/tmp/mocha2]$ node index.js > res2.txt
[~/tmp/mocha2]$ diff res1.txt res2.txt 
48,53c48
<   _: '/usr/bin/mocha',
<   LOADED_MOCHA_OPTS: 'true' }
< 
< 
<   0 passing (0ms)
< 
---
>   _: '/usr/bin/node' }
[~/tmp/mocha2]$ npm run node > res3.txt
[~/tmp/mocha2]$ npm run mocha > res4.txt
[~/tmp/mocha2]$ diff res3.txt res4.txt 
2,3c2,3
< > mocha2@1.0.0 node /home/sajjad/tmp/mocha2
< > node index.js
---
> > mocha2@1.0.0 mocha /home/sajjad/tmp/mocha2
> > mocha index.js
16c16
<   _: '/usr/bin/node',
---
>   _: '/home/sajjad/tmp/mocha2/node_modules/.bin/mocha',
68c68
<   npm_lifecycle_event: 'node',
---
>   npm_lifecycle_event: 'mocha',
93c93
<   npm_config_argv: '{"remain":[],"cooked":["run","node"],"original":["run","node"]}',
---
>   npm_config_argv: '{"remain":[],"cooked":["run","mocha"],"original":["run","mocha"]}',
127c127
<   npm_lifecycle_script: 'node index.js',
---
>   npm_lifecycle_script: 'mocha index.js',
185c185,190
<   npm_config_package_lock: 'true' }
---
>   npm_config_package_lock: 'true',
>   LOADED_MOCHA_OPTS: 'true' }
> 
> 
>   0 passing (0ms)
> 

```

Using zsh on node 9.3 and mocha 4.0.1 running on arch linux.

**Comment by alasdairhurst** [comment]
Sorry, just noticed that the information under "versions" was still commented out. Hopefully this helps a bit more.

**Comment by HarrySarson** [comment]
Running on windows 10 command prompt I cannot reproduce. :(

**Comment by Bamieh** [comment]
i cannot reproduce this on my machine (macOS v10.13.2).

**Comment by alasdairhurst** [comment]
Ok update: Been playing around and can no longer reproduce it with the basic case above which is baffling me. Now I can only reproduce it with the very specific environment of cmder(bash shell) running mocha in an npm script through a learna command. when mocha spawns `_mocha` the environment variables which are set to '' are changed to 'undefined'.

I will try digging into this further. It could be an issue with node spawn and the sub-process depth or something but it's very strange.
