### ISSUE TITLE
[RFC] Moving the `Mocha needs YOU!` disclaimer from the README.md file

### ISSUE THREAD

**Issue by Bamieh** [mochajs/mocha#3191]
The first thing that a user sees when opening `mochajs/mocha` is a huge disclaimer of 

> # Mocha needs YOU!
> ...

For new comers, this message might be a little intimidating and discouraging to use mocha as their testing tool.

Maybe we can move this section into the `CONTRIBUTING.md` file, and write a small message encouraging developers to contribute to mocha to keep this awesome project alive.

P.S. `mocha's immediate needs` needs to be updated as well!

What do you think?

**Comment by outsideris** [comment]
I agreed with you. and a small message encouraging contribution in README is ok for me.
