### ISSUE TITLE
Ability to show only changes and deletions in diffs, not additions

### ISSUE THREAD

**Issue by Mingun** [mochajs/mocha#3193]
### Prerequisites

- [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

I use `chai` assertion library and [`chai-like`](https://github.com/zation/chai-like) library for the partial comparing of objects: I am interested in existence and compliance only of those properties that are listed in an `expected` object. Existence of additional properties in an `actual` object permissibly. Unfortunately, when diff is created it is not considered in any way and those properties, existence which for the test it is indifferent get to diff. It would be desirable to have a way to suppress their generation in a diff. Example:

Test:
```js
'use strict';

let chai = require('chai');
let expect = chai.expect;
chai.use(require('chai-like'));

describe("diff test", function() {
  let AST = {
    type: 'grammar',
    rules: [
      { type: 'rule', name: 'rule1' },
      { type: 'rule', name: 'rule2' },
    ]
  };
  it("chai-like", function() {
    expect(AST).like({
      rules: [
        { name: 'rule' },
        { name: 'rule2' }
      ]
    });
  });
});
```

This is current actual output which is too large in some cases and contains unnecessary details
```console
  1) diff test
       chai-like:

      AssertionError: expected { Object (type, rules) } to be like { Object (rules) }
      + expected - actual

       {
         "rules": [
           {
      -      "name": "rule1"
      -      "type": "rule"
      +      "name": "rule"
           }
           {
             "name": "rule2"
      -      "type": "rule"
           }
         ]
      -  "type": "grammar"
       }

      at Context.<anonymous> (test\test.js:24:17)
```
But I want that diff looked here so:
```diff
 {
   "rules": [
     {
-      "name": "rule1"
+      "name": "rule"
     }
   ]
 }
```
I think that there is no such opportunity now and that it appeared, it is necessary to add to an `AssertionError` object new property which could control such behavior of diff, and then support its in all assertion libraries.

If the idea is supported, I can make PRs for its implementation in all necessary libraries.

**Comment by boneskull** [comment]
Any such property will need to be added in Chai itself (or whatever other assertion library).  Once it's added, we can consider adding support for it.  Please create a new issue if/when that happens.

**Comment by Mingun** [comment]
So, in compliance with the comment https://github.com/chaijs/chai/issues/1120#issuecomment-356148878 this issue can be reopened.

**Comment by boneskull** [comment]
We won't be reopening this issue; please see [my comment in chaijs/chai#1120](https://github.com/chaijs/chai/issues/1120#issuecomment-356376717)
