### ISSUE TITLE
netlify should only deploy when repo is tagged

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3206]
@Munter when we merge changes into `master` which have documentation updates, those updates go live, even if the features they describe aren't yet in Mocha.

I'd like to have it deploy when:

- a new Git tag or release happens
- manually

(ideally both)

Is that doable?

**Comment by Munter** [comment]
Manual deploy is certainly possible. That sounds quite impractical though. I don't see anything in the admin interface that would allow only deploying on a release.

These re the options available:
![image](https://user-images.githubusercontent.com/331790/35031207-4b0f651c-fb62-11e7-9f2a-c86cb0e1daa1.png)

I guess we could have a docs branch and merge master into it whenever we want to deploy the documentation.

I can ask netlify if there is a way to trigger deploys on releases. Their rest API doesn't seem to have a hook to trigger a deploy for a commit/tag

**Comment by boneskull** [comment]
yeah I guess we can automate a branch push upon release

**Comment by boneskull** [comment]
For now let's just use a `docs` branch.  Let's add a `postpublish` script which resets the branch to the latest tag.

If there isn't a module on npm to do this, let's publish one.

**Comment by samuelcolvin** [comment]
Just found this issue while trying to find out whether netlify have built-in support for release only on tags. 

Apparently, they don't which I think is mad.

But my workaround for pydantic is to setup netlify to deploy a fictional branch `foobar` (to avoid netlify auto-deploying), then manually deploy from CI when a tag is created, see [here](https://github.com/samuelcolvin/pydantic/blob/master/Makefile#L68-L71) for the makefile command, and [here](https://github.com/samuelcolvin/pydantic/blob/master/.travis.yml#L49) for the travis setup.

I think that's more elegant than manually pushing to a branch.

**Comment by boneskull** [comment]
@samuelcolvin thanks for the tip!

**Comment by boneskull** [comment]
cc @Munter @craigtaub 

I tried this:

1. I rolled back to the earliest good deploy of v5.2.0 (deploys were failing around the release, but this was fixed sometime after).  That's eeccd05 if we want to be specific.
1. I disabled auto-deployment of the production branch (`master`)
1. I disabled automatic deployment of *all* branches, which we shouldn't be doing anyway.
1. I didn't change our deployment preview settings.
1. I created an incoming webhook on netlify.  These only trigger a build against a selected branch.  I selected `master`.
1. I created an outgoing webhook on GitHub to be triggered whenever a GitHub "release" event occurs.

This doesn't work, unfortunately, because of the disabled auto-deployment.  

Netlify's API has an endpoint to lock/unlock deployment, however.  I'll see what I can do with this.  If I can't figure it out, we'll just have to create a branch for doc deployment, and update that branch every time we tag a release (or automate it).

**Comment by boneskull** [comment]
OK, yeah, in order to make that happen properly I'd need to either create a GitHub app or action.  The former is more work than I'm willing to do atm (though using [Probot](/probot/probot) would be a great place to start), and the later is still in private beta, so whatever.  Branches it is for now.

I'll configure netlify to only publish, say, the `mochajs.org` branch, and keep that updated when we release.

**Comment by jakeleboeuf** [comment]
It seems this is still a pain to setup, is there any plan to add support for only deploying tagged releases?

**Comment by CanRau** [comment]
Maybe you could use GitHub Actions https://github.com/netlify/actions ?

>

**Comment by craigtaub** [comment]
Created an issue for someone to look at https://github.com/mochajs/mocha/issues/4117
