### ISSUE TITLE
travis "before script" should only be run once

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3208]
This script basically asserts `define` doesn't appear in the browser distfile (`mocha.js`).

- This check probably needs to have its own line in the build matrix
- It should be invoked via a script in `package-scripts.js` so developers can run it locally

**Comment by boneskull** [comment]
scripts/travis-before-script.sh

**Comment by Bamieh** [comment]
I'll check it out later on today

**Comment by outsideris** [comment]
@Bamieh Oops. I'm trying to fix it. Can I submit for PR for this?

**Comment by outsideris** [comment]
I worried about you are working on it.

**Comment by Bamieh** [comment]
@outsideris thanks for helping out!
