### ISSUE TITLE
How to do a post call in before hook

### ISSUE THREAD

**Issue by vishalbiradar** [mochajs/mocha#3219]
I want to do an HTTP post call inside before hook.
So, I can use the output from that post call in my all test cases.
So is there any provision to do so.
I may be having several test files containing several test cases.
But I want to execute an HTTP post call only once before all the test cases.

**Comment by boneskull** [comment]
Hooks can execute async code just like tests.  

Please read up on maybe `--delay` [on mochajs.org](https://mochajs.org), or ask in the [chat room](https://gitter.im/mochajs/mocha) or stackoverflow.
