### ISSUE TITLE
Exit mocha immediately

### ISSUE THREAD

**Issue by basickarl** [mochajs/mocha#3220]
Is there any way to explicitly exit the process with an error message? I would like to have a checker for something that all my tests require and if the checker fails would like to exit immediately with an error message as stated.

Something like `mocha.exit('Error message here')`.  I tried `process.exit(1);` but nothing happens.

**Comment by boneskull** [comment]
Here's one idea:

```js
// checker.js
module.exports = filename => {
  describe('checker thing', function () {
    // this and any suite within it will exit Mocha upon the first error
    this.bail(true);

    it('should exit if this fails', function () {
      if (somethingBad) {
        throw new Error(`${filename} broke`);
      }
    });
  });
};
```

Then from `my-test.spec.js`:

```js
require('./checker')(__filename);

describe('my test', function () {
  it('should be business as usual', function () {
    // etc
  });
});
```
