### ISSUE TITLE
Went from testing and passing to suddenly does not run

### ISSUE THREAD

**Issue by mwpowellhtx** [mochajs/mocha#3221]
I stood *Mocha*/*Chai* up on its feet and running pretty well in a "testing" clone of my working repository. When I was satisfied with that, I committed that and pulled those updates into my working repository. I opened that solution and now suddenly nothing works, *Mocha*/*Chai* cannot be found, describe, it are undefined, at best, and nothing runs, tests are ignored.

I am running from *Visual Studio 2015*, using *Chutzpah* test runner to facilitate things.

As far as I know *npm* ran successfully to pull in all the requisite package references.

**Comment by mwpowellhtx** [comment]
I should add, when the test runner runs, it is insisting on Jasmine specifications being reported. Kind of at a loss here; what might I be missing?

My *Gulpfile.js* task:

```JavaScript
gulp.task("test",
    function() {
        var opts = {
            "executable": "C:/Dev/NuGet/packages/Chutzpah.4.3.6/tools/chutzpah.console.exe"
        };
        return gulp.src(cfg.spec + "/*.js", { read: false })
            .pipe(chutzpah(opts));
    });
```

My *Chutzpah.json*:

```JavaScript
{
    "Framework": "mocha",
    "MochaInterface": "bdd",
    "References": [
        { "Path": "./node_modules/chai/chai.js" },
        { "Path": "./Scripts/ExtensionsJS/arr.js" }
    ]
}
```

My *package.json* *devDependencies*:

```JavaScript
"del": "3.0.0",
"gulp": "3.9.1",
"gulp-gzip": "1.4.2",
"gulp-minify": "2.1.0",
"gulp-tar": "2.1.0",
"tar-pack": "3.4.1",
"mocha": "5.0.0",
"chai": "4.1.2",
"jasmine": "2.9.0",
"gulp-mocha": "5.0.0",
"gulp-chutzpah": "1.3.0",
"gulp-jasmine": "3.0.0",
"jasmine-reporters": "2.3.0"
```

**Comment by mwpowellhtx** [comment]
Perhaps is a tooling issue, but I wondered what other insights there may be. Specifically, when I close *VS2015* entirely, relaunch, and open the solution, then the environment suddenly "works". The only thing I can fathom is that possibly there is some JavaScript "runtime" state that requires a reboot and/or a refresh.

So, the question is, when I discover a fresh *clone* and/or *pull* from my solution, I want to be updating the *npm* dependencies automatically, *nuget* packages automatically, etc, in such a way that *VS2015* is happy with the outcome.

**Comment by ORESoftware** [comment]
probably a tooling issue, might want to ask Chutzpah about this, I personally avoid IDE tooling and just use the command line and some bash files if need be

**Comment by mwpowellhtx** [comment]
@ORESoftware Yes, that's where the evidence is pointing, IMO. I could be wrong, but that seems to be the behavior. Thanks for the response.
