### ISSUE TITLE
object diff gets stuck in infinite loop

### ISSUE THREAD

**Issue by chriseppstein** [mochajs/mocha#3229]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

Mocha's Object printer gets stuck in an infinite loop for some objects with circular references.

### Steps to Reproduce

This gist is a git repo that can be checked out and ran to reproduce the issue:
https://gist.github.com/chriseppstein/1060367f3ffe3615a1aaf33b5dfd7fac

**Expected behavior:**  object diffs are produced and circular references are marked with `[circular]` in the output.
**Actual behavior:** Error report is never returned because an infinite loop occurs eventually crashing with an out of memory error.

**Reproduces how often:** Every time.

### Versions

- The output of `mocha --version`: not installed.
   - and `node node_modules/.bin/mocha --version`: 5.0.0
- The output of `node --version`: v8.1.3
- The version and architecture of your operating system: OSX 10.12.6
- Your shell (bash, zsh, PowerShell, cmd, etc.): zsh
- Your browser and version (if running browser tests): N/A
- Any other third party Mocha related modules (with versions): none.
- The code transpiler being used: None.

**Comment by boneskull** [comment]
this is an `assert` issue, not a mocha issue.
