### ISSUE TITLE
Nyan Reporter has Weird Output in Travis CI

### ISSUE THREAD

**Issue by gneatgeek** [mochajs/mocha#3231]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha. (I have no control of this)

### Description

The Nyan runner's output is a bit strange in Travis CI (see screenshot).

### Steps to Reproduce

**Expected behavior:** Test runner outputs as it does in the console

**Actual behavior:** Lots of newlines output

**Reproduces how often:** 100%

### Versions

"mocha": "^5.0.0"
node v8.9.4

### Additional Information

![screen shot 2018-02-04 at 8 43 22 pm](https://user-images.githubusercontent.com/1232730/35788777-5f4c68e8-09ec-11e8-9273-34b95ee4adbd.png)

![screen shot 2018-02-04 at 8 43 36 pm](https://user-images.githubusercontent.com/1232730/35788784-6464b196-09ec-11e8-89c6-6d266e91dbf4.png)

**Comment by outsideris** [comment]
It's not a problem. Nyan report shows report dynamically in your terminal, but Travis's log is a static file. So, it just saves all stdout and can't show it dynamically. Nyan report is not the best option for Travis ci.

**Comment by gneatgeek** [comment]
@outsideris, thanks for the clarification.
