### ISSUE TITLE
Mocha 5.0.0 won't precompile using Babel

### ISSUE THREAD

**Issue by blainesch** [mochajs/mocha#3235]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

I can't seem to get mocha to work with babel. I get an `unexpected token import` issue.

```
./node_modules/.bin/mocha --compilers js:babel-core/register test/actions.spec.js
/Users/bschmeisser/projects/cupcake-pgp/src/actions.js:1
(function (exports, require, module, __filename, __dirname) { import jetpack from 'fs-jetpack';
                                                              ^^^^^^

SyntaxError: Unexpected token import
```

### Steps to Reproduce

```
git clone git@github.com:blainesch/cupcake-pgp.git
cd cupcake-pgp
npm install
./node_modules/.bin/mocha --compilers js:babel-core/register test/actions.spec.js
```

**Expected behavior:** Run my tests

**Actual behavior:** Didn't run my tests

**Reproduces how often:** 100%

### Versions

* Mocha: 5.0.0
* Node v8.9.0
* NPM 5.5.1
* babel-core 6.24.1
* babel-loader 7.1.2

**Comment by blainesch** [comment]
I think it's swallowing the real error. When I switch `--compilers js:babel-core/register` to something silly such as `--compilers js:meow` nothing different happens.

However the help docs do say it's using this format in `mocha --help` it says `--compilers <ext>:<module>,...          use the given module(s) to compile files`

**Comment by blainesch** [comment]
Re-adding back in my `.babelrc` file didn't seem to fix anything, but if anybody wants it:

```
{
  "plugins": ["transform-class-properties"],
  "presets": ["react"]
}
```

**Comment by boneskull** [comment]
not a mocha issue.  you need something like `babel-preset-env` to go with `babel-preset-react`, because the latter doesn't give you any ES6+ support.
