### ISSUE TITLE
Test suite failing with citgm

### ISSUE THREAD

**Issue by MylesBorins** [mochajs/mocha#3240]
Seems to be something to do with the way you use `node-gyp`. Doesn't seem to matter which version of node or npm... but I haven't dug in too much yet

to repro

```
npm i -g citgm
citgm -v verbose mocha
```

**Comment by Bamieh** [comment]
Hey @MylesBorins, can you submit the verbose log in here?

**Comment by outsideris** [comment]
In my machine, it looks fine.

```
info:    passing module(s)   |
info:    module name:        | mocha
info:    version:            | 5.0.0
info:    done                | The smoke test has passed.
info:    duration            | test duration: 175293ms
```

**Comment by MylesBorins** [comment]
5.0.1 is now passing locally for me. It was possible failures were due to workign on a pre-releasae version of node

Still having issues in CI

```
20:36:37 error:                     | CI mode disabled 
```
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/238/MACHINE=ubuntu1604-64/console

**Comment by Bamieh** [comment]
@MylesBorins is this still happening? can you guide me on how to reproduce this so i can debug it?
