### ISSUE TITLE
Browser opens with 'data:,' on test fails

### ISSUE THREAD

**Issue by Visakeswaran** [mochajs/mocha#3246]
Whenever a test case fails, my browser window closes and a new browser opens with a blank page and 'data:,' in the URL section for the next test case, causing rest of the cases in the suite to fail. In the before hook, i want to check the state of the previous test case and if the previous test case is a failed one, i want to navigate to url where it failed and continue with the next test cases.

This is my code:
`
describe("Login Page Test:", function() {
  before(function(client, done) {
    client.url(inputs.utils.URL.input, function() {
      done();
    });
  });

  after(function(client, done) {
    client.end(function() {
      done();
    });
  });

  beforeEach(function(client, done) {
    done();
  });

  afterEach(function(client, done) {
    done();
  });

  it("Should redirect user to the dashboard page on logging in with valid credentials", function(browser, done) {
    login_utils(browser).login(
      "inputs.login.TC_01.loginID",
      inputs.login.TC_01.password
    );
    login_utils(browser).confirmLogin();
  });

  it("Should open the User Dropdown click the Logout Button and redirect to Login Page", function(browser) {
    dashboard_utils(browser).userDropDown();
    dashboard_utils(browser).clickUserDropDownOption(selectors.logoutButton);
    login_utils(browser).confirmLogout();
  });

  it("Should stay on login page and should display an error message for invalid Username or email", function(browser) {
    login_utils(browser).login(
      inputs.login.TC_02.loginID,
      inputs.login.TC_02.password
    );
    login_utils(browser).confirmUnsuccessfullLogin();
  });

  it("Should stay on login page and should display an error message for invalid password", function(browser) {
    login_utils(browser).login(
      inputs.login.TC_03.loginID,
      inputs.login.TC_03.password
    );
    login_utils(browser).confirmUnsuccessfullLogin();
  });

  it("Should stay on login page and should display an error message for invalid Username and password", function(browser) {
    login_utils(browser).login(inputs.login.TC_04.loginID, inputs.login.TC_04.password);
    login_utils(browser).confirmUnsuccessfullLogin();
  });

  it("Should stay on login page and should display an error message for empty credentials", function(browser) {
    login_utils(browser).login(inputs.login.TC_05.loginID, (inputs.login.TC_05.password == "null") ? "":inputs.login.TC_05.password);
    login_utils(browser).confirmEmptyCreds();
  });

  it("Should stay on login page and should display an input error message for wrong email format", function(browser) {
    login_utils(browser).login(inputs.login.TC_06.loginID, inputs.login.TC_06.password);
    login_utils(browser).confirmInputError();
  });
});

`

**Comment by Bamieh** [comment]
Please provide more details, what are you trying to achieve, and explain your question in the description of the issue. There is a template provided when filing an issue, it would be awesome to follow it in order for us to help you out!

Thanks
