### ISSUE TITLE
How do you add a message in a test suite?

### ISSUE THREAD

**Issue by patrickptm** [mochajs/mocha#3247]
Background:
I am running a customize third-party mocha reporter like this:
```js
var customReporter = function (runner) {  // private method
        
        runner.on('pass', function (test) {
            console.log('The following test has passed: '+test.title);
            console.log(test);
            testsPassed++;
            totalTests++;
        });
        
        runner.on('fail', function (test) {
            console.log('the following test has failed: '+test.title);
            testsFailed++;
            totalTests++;
        });
        
        runner.on('pending', function (test) {
                console.log('pending');
                pending.push(test);
        });
```
Is it possible to include in a `describe`, `it` block a message, which will be displayed when the tests are failing? The message is in my case the error message I get from the API call I'm testing. I wonder how I can pass it inside my tests to be visible in my reporter. I am using Chai for assertions.

```js
    it('Checking firsName is valid', function (done) {
        var key = keyJson[0];
        expect(json.profiles[key]["firstName"]).to.not.equal(" ");
        done();
         //how to include the json here? 
    });
```

**Comment by patrickptm** [comment]
any solution to this?

**Comment by patrickptm** [comment]
The solution I have so far is using try and catch, however this is not elegant at all:

it('Checking guid', function (done) {
        var key = keyJson[0];
        try {
            expect(json.profiles[key]["guid"]).to.equal('PSI'+key);
            done();
        }catch(err)
        {
            done(new Error("No Json returned"));
        }
    });

Would it be possible to allow done to receive a custom error message without checking first if the test fails or not? At the moment, inserting an error message in done, when the test passes, causes the failure of the test. So, when you run it programmatically, the custom reporter should be dealing with the errors. My main problem is that there is not elegant way to override mocha error messages and use my own.

Thoughts?

**Comment by plroebuck** [comment]
`test.fullTitle()` work for you?

**Comment by plroebuck** [comment]
```js
var _ = require('lodash');

describe('suite', function () {
  it('Checking guid', function (done) {
    var key = keyJson[0];
    var res = _.attempt(expect(json.profiles[key]["guid"]).to.equal('PSI'+key));
    return (_.isError(res)) ? 
      done(new Error("No JSON returned"));
      done();
});
```

Did you try using a wrapper function that is passed the `done` function and your custom error message as arguments?

**Comment by plroebuck** [comment]
BTW, you could _alter_ Chai's default `expect` assertion message:
See [here](https://github.com/chaijs/chai/issues/81) and [here](https://stackoverflow.com/questions/45678706/how-to-provide-chai-expect-with-custom-error-message-for-mocha-unit-test) for details.

**Comment by plroebuck** [comment]
BTW, your `testsPassed`, `testsFailed`, and `totalTests` variables above are already available via Mocha-provided `runner.stats` object.
