### ISSUE TITLE
Mocha tests pass the first time when running on watch mode but get a timeout error after all subsequent runs.

### ISSUE THREAD

**Issue by cubadomingo** [mochajs/mocha#3249]
### Prerequisites

- [x ] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

When I run mocha on watch mode, all tests will pass initially. When an unrelated test file is saved, thus causing mocha to run again, I will get the ` Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.` on one of my tests that purposely returns an error.

### Steps to Reproduce

This test will pass on the first run by mocha and on any run after the first it will continuously fail.

```it('returns an error if date is taken', function () {
      const data = {//data}

      return chai.request(server)
        .post(`/api/v1/service-requests`)
        .send(data)
        .catch((err) => {
          expect(err).to.have.status(404);
          expect(err.response.body.message).to.equal('Time frame is not available');
        })
    })
```

I'm basically making a post request on an express backend. This specific test causes an error to be thrown and then the express error handler sends over the error in a JSON format.

Here is the route in express

```
router.post('/', function (req, res, next) {
 newServiceRequest(req.body)
    .then((serviceRequest) => {
      res.status(200).json({ serviceRequest });
    })
    .catch((error) => {
      error.status = 404;
      next(error);
    });
});
```

and here is the error handler that kicks in when next is called with the error:

```
app.use(function(err, req, res, next) {
  res.status(err.status || 500);
  res.json({
    message: err.message.split(',').join(', '),
    error: err
  });
});
```
Now I've tested that the error handling works fine when I test the endpoint manually in both dev and test environments. Mocha also sees that it's valid on the first run, but any other run afterwards throws the dreaded timeout error. Not sure where to go from here.

**Expected behavior:** Tests should pass on all subsequent passes that don't affect the test.

**Actual behavior:** The suite fails with one test not passing.

**Reproduces how often:** Every time mocha is used on watch mode.

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 3.5.3
- The output of `node --version`: v8.7.0
- The version and architecture of your operating system: macOS 10.13.2
- Your shell (bash, zsh, PowerShell, cmd, etc.): bash
- Your browser and version (if running browser tests):
- Any other third party Mocha related modules (with versions):
- The code transpiler being used:

**Comment by boneskull** [comment]
Hi

1.  Please upgrade Mocha
2.  Remove your assertion and replace it with `return Promise.resolve()`.  What happens?
