### ISSUE TITLE
Mocha file 404 test js front end

### ISSUE THREAD

**Issue by ShintaroNippon** [mochajs/mocha#3252]
I'm trying to implement this tutorial by the way https://blog.codeship.com/mocha-js-chai-sinon-frontend-javascript-code-testing-tutorial/

https://github.com/mochajs/mocha/raw/master/mocha.js

but in file mocha.js i found a 404... Can someone help me and provide this file to put on front end...

I couldn't found the right one as equal to work on it.

Many thanks Carlos Vieira

**Comment by outsideris** [comment]
I didn't do the tutorial, but I guess you can use [mocha files in cdnjs](https://cdnjs.com/libraries/mocha/). You should check mocha version which you will use.

**Comment by ShintaroNippon** [comment]
I cant see the version... i already tried the last one but didint work...
Or its missing somethinghow can i check the version, in tutorial says nothing.
Thanks

**Comment by ShintaroNippon** [comment]
using this log
https://github.com/mochajs/mocha/blob/master/CHANGELOG.md
in 2013 date of the post the version was 1.16
i will try
many thanks

**Comment by outsideris** [comment]
Did you test with v3.x or v4.x? Last update date of the tutorial is 2017-06-19. So [v3.x](https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#342--2017-05-24) should work.

**Comment by boneskull** [comment]
`mocha.js` is no longer committed to version control.  Pull it from a Unpkg or https://unpkg.com/mocha/mocha.js or cdnjs.com or whatever
