### ISSUE TITLE
Provide owner information for failing tests

### ISSUE THREAD

**Issue by vreddi** [mochajs/mocha#3254]
It would be neat to have an owner entity associated with each test. When the result of all the passing and failing test is printed to the console, if the owner entity could also be mentioned in the failure details it would be really useful.

For teams with a lot of engineers and a lot of tests having the feature would be very useful.
with every it() block the owner property (optional: to make this change non breaking) could be specified.

**Comment by boneskull** [comment]
Thanks for the suggestion, but I think this is something better handled by version control.  You could conceivably write your own reporter that cross-references line numbers against `git blame`.
