### ISSUE TITLE
Unicode characters don't render correctly in console.log

### ISSUE THREAD

**Issue by generateui** [mochajs/mocha#3259]
### Prerequisites

- [x ] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Steps to Reproduce

**Expected behavior:** windows commandline displays `A 🡒 B`

**Actual behavior:** windows commandline displays `A �� B`

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
'mocha' is not recognized as an internal or external command,
operable program or batch file.
- The output of `node --version`:
v8.4.0
- The version and architecture of your operating system:
Windows 10 x64
- Your shell (bash, zsh, PowerShell, cmd, etc.):
Windows commandline (cmd.exe)
- Your browser and version (if running browser tests):
- Any other third party Mocha related modules (with versions):
- The code transpiler being used:
babel ^6.0.0

**Comment by boneskull** [comment]
pretty sure this is expected in Windows / `cmd.exe`

**Comment by ilya-g** [comment]
@boneskull Could you share some details why is it expected and what are the possible workarounds?

**Comment by generateui** [comment]
1. cmd.exe
2. copy/paste → symbol

Note that it displays just fine and is not a problem in the `cmd.exe`. Somehow, the output of mocha.js gets mangled in a way that makes `cmd.exe` display it incorrectly.

A workaround is not to use that arrow symbol, but ascii-art (e.g. ->). However, my code will use non-latin unicode symbols much more in the future, so it is not a great workaround.
