### ISSUE TITLE
better test harness for reporters

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3260]
There's a lot of duplicated code in the reporter tests.  Let's extract that into helper modules/functions/etc.

**Comment by jMuzsik** [comment]
Hi! I'd be willing to do this

**Comment by Bamieh** [comment]
@jMuzsik Hello!, thanks for your interest to contribute 🎉. Just say you're going to work on it and start. Here is how it generally works in all OSS; You fork the project and create a new branch from master with a link to the issue number you are working as a commit message and push it before writing any code. This will link your branch to this issue, letting people know that you are working on it and follow on the progress. If you need comments on the code or your branch is ready, submit a PR and we'll have a look at it to get it merged!

Cheers
