### ISSUE TITLE
[feature] allow failing tests 

### ISSUE THREAD

**Issue by mlrawlings** [mochajs/mocha#3261]
I'd really like to make it easy for people to submit failing tests as pull requests to my projects and ava has a [really good story](https://github.com/avajs/ava#failing-tests) around this.  I'd like to implement a similar feature in mocha.

This should give a pretty good idea of what I'm thinking:
https://github.com/mlrawlings/it-fails

I'm going to go ahead and start using `it-fails`, but...
- it's hacky
- overwrites a lot of the mocha internals
- the built in reporters don't have knowledge of expected failures (though this is mostly fine)

If it were implemented in core, it could be much cleaner.   

Let me know if a PR for this would be accepted and we can discuss the approach a bit more.  I could probably do a bit of cleanup on the stats (#3256) at the same time.

**Comment by boneskull** [comment]
Hi, thanks for the suggestion.  Sorry, but I don't think Mocha should have this feature.  This is why:

1.  It's unlikely to see wide use.  I'm not sure if I've seen this particular request before... I don't think so.  This means the majority of Mocha users do fine w/o it.
1.  Implementation will be weird / complicated (as you've noted)
1. Someone will eventually ask for `this.fails()` *a la* `this.skip()`, which makes things more complex
1. More features = more complexity = more bugs
1.  Other related [philosophical reasons](https://www.petrikainulainen.net/programming/unit-testing/why-you-should-keep-your-build-green/); it sets a precedent that tests are allowed to fail, which is bad (in my opinion)

There's a workaround, which is to write a passing test for the unwanted behavior.

Would love help fixing the stats though!
