### ISSUE TITLE
"utils.files is not a function" (mocha: 5.0.2)

### ISSUE THREAD

**Issue by 5c077yP** [mochajs/mocha#3265]
### Description

Hey, i've just upgraded to the latest mocha version `5.0.2` and I now start to see a `"utils.files is not a function"` error when running in watch mode with passing a glob path. Seems this commit ec8901a23c5194b6f7e6eee9c2568e5020c944ce removed the function which is still used in https://github.com/mochajs/mocha/blob/master/bin/_mocha#L532

### Steps to Reproduce

`NODE_ENV=test mocha './test/**/*.js'`

**Expected behavior:** 

it should execute my tests as before.

**Actual behavior:** 

it crashes all the time

```bash
> NODE_ENV=test mocha './test/**/*.js' "--watch"

/opt/MY-PACKAGE/node_modules/mocha/bin/_mocha:532
  const watchFiles = utils.files(cwd, [ 'js' ].concat(program.watchExtensions));
                           ^

TypeError: utils.files is not a function
    at Object.<anonymous> (/opt/MY-PACKAGE/node_modules/mocha/bin/_mocha:532:28)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

### Versions

- `5.0.2`
- shell: zsh
- The code transpiler being used: babel

**Comment by remolueoend** [comment]
Same here, looks like `utils.files` was removed in https://github.com/mochajs/mocha/commit/ec8901a23c5194b6f7e6eee9c2568e5020c944ce but is still in use.

**Comment by archae0pteryx** [comment]
This exists in 5.0.1 as well it seems.

**Comment by arichiardi** [comment]
Confirm this is still an issue.

**Comment by ihsw** [comment]
Downgraded to 5.0.1, it works.

**Comment by sebs** [comment]
Error exists in 5.11, node 9.5.0 as well

**Comment by sebs** [comment]
Please reopen.

**Comment by boneskull** [comment]
@sebs This has already been fixed; please check that the `mocha` you are executing is indeed v5.1.1; you may need to run `mocha -v`.  sometimes a globally-installed mocha is used by mistake

**Comment by sebs** [comment]
I am running the mocha via npm scripts. I can investigate that. I am running an NVM setup. I have no recollection of places where mocha is not adhering to be run via npm scripts, but my node 9.5.0 is a bit outdated. 

I used the global installation to trouble shot and make sure it was really changed.

**Comment by sebs** [comment]
Ah I donnu, I was so sure I had pinned it down to 5.1.1 Mocha works as intended
Thanks
