### ISSUE TITLE
`--watch` flag causes crash starting with Mocha 5.0.2

### ISSUE THREAD

**Issue by ip** [mochajs/mocha#3269]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

Mocha 5.0.2 - 5.0.3 crashes when using `--watch` flag with the following error:

![image](https://user-images.githubusercontent.com/1111008/37105680-1a9a0fdc-2230-11e8-827b-52a24835738c.png)

Version 5.0.1 works fine.

### Steps to Reproduce

I created a minimal demo which reproduces: https://github.com/ip/mocha_bug_demo

Tried with both Yarn and NPM.

**Expected behavior:** It works

**Actual behavior:** It crashes

**Reproduces how often:** 100% of time

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 5.0.2 - 5.0.3
- The output of `node --version`: v8.9.4
- The version and architecture of your operating system: macOS High Sierra 10.13.3 (17D47)
- Your shell (bash, zsh, PowerShell, cmd, etc.): zsh 5.3 (x86_64-apple-darwin17.0)
- Your browser and version (if running browser tests):
- Any other third party Mocha related modules (with versions):
- The code transpiler being used:

**Comment by boneskull** [comment]
closed via #3268
