### ISSUE TITLE
"watch" functionality needs tests

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3270]
We have no integration tests around the "watch" functionality (see #3265).

Why?  Because it's a pain.  You'd have to run a test against some files, then modify a file from the test, then manually kill the child process and assert its output is as expected.  Normally we like to use the JSON reporter internally, but this test won't print a single JSON file to STDOUT like the others--it would return multiple files to STDOUT.  So we'll have to split up the output and make assertions on both.

**Comment by boneskull** [comment]
A good place to start might just be "run a test with `--watch` enabled, kill the child process, and assert the output is correct"

**Comment by boneskull** [comment]
cc @outsideris, for context

**Comment by outsideris** [comment]
I agreed with you on integration tests.

**Comment by outsideris** [comment]
Closed by #3379
