### ISSUE TITLE
failing Error: timeout of 2000ms exceeded

### ISSUE THREAD

**Issue by jeffWalt** [mochajs/mocha#3271]
I had this working a few months ago, I think something updated (maybe) and now it's not working,

my "/todos" route work, infact I can call done() after the if statement in the end callback and it'll update the database, but when I add a my mongodb query to verfiy it has been added, it doesn't update my database and it gives me
`Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.`

```

describe('POST /todos', () => {
  it('should create a new todo', (done) => {
    var text = 'Test todo text';

    request(app)
      .post('/todos')
      .send({text})
      .expect(200)
      .expect((res) => {
        expect(res.body.text).toBe(text);
      })

      .end((err, res) => {
        if (err) {
          return done(err);
        }
        
        Todo.find({text}).then((todos) => {
          expect(todos.length).toBe(1);
          expect(todos[0].text).toBe(text);
          done();
        }).catch((e) => done(e));
      })
  });
});
```

**Comment by boneskull** [comment]
Hi!  General support questions are better asked [in our chat room](https://gitter.im/mochajs/mocha), [mailing list](groups.google.com/forum/#!forum/mochajs), or [StackOverflow](https://stackoverflow.com).  Thanks!
