### ISSUE TITLE
watch always watches .js

### ISSUE THREAD

**Issue by tomitrescak** [mochajs/mocha#3275]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

This is not an issue but feature request.

Watch mode always watches for ".js" files even when I specify --watch-extensions to be "ts,tsx". Is it possible to change the behaviour to strictly watch only the specified extensions?

**Comment by tomitrescak** [comment]
Why is this a problem? Well, even whan I specify to be my test and folder to be in 'src/' mocha watches files outside of these directories. For example in ".fusebox' where my bundler stores cached files.

**Comment by outsideris** [comment]
Did you see #2554 or https://github.com/mochajs/mocha/issues/1780 . 
I don't know all history of mocha, but it seems mocha.js want to drop the watch feature rather than enhance it.

**Comment by boneskull** [comment]
I *would love to drop this feature*, but I don't think that's going to happen.

Too many people use it.

It should be fixed.  It shouldn't necessarily *receive new features*, but it should work as expected.

I'd consider this to be a bug.

**Comment by plroebuck** [comment]
@tomitrescak, not a TypeScript guy myself... Are watched files your only issue? What about the default files to test? Here are the relevant portions of code related to this question.

https://github.com/mochajs/mocha/blob/c580294893e1bf2f9e51adafd73e6cac71690d19/bin/_mocha#L450-L462
https://github.com/mochajs/mocha/blob/c580294893e1bf2f9e51adafd73e6cac71690d19/bin/_mocha#L478-L515

Note the variable `program.watchExtensions` deals with which files to watch. The variable `extensions` (for "native/transpiled" code) is used to determine which files are selected for testing.
