### ISSUE TITLE
Using Mocha Programmatically should support more than paths

### ISSUE THREAD

**Issue by Starmann** [mochajs/mocha#3284]
### Prerequisites
- [X] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [X] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [X] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
Mocha's programmatic API currently only supports adding files via a path. The problem with this is that the developer might want to process the Javascript first. Although support for Streams would be the ideal, simply being able to evaluate strings via Mocha would be greatly appreciated.

**Comment by boneskull** [comment]
@Starmann What's the real use case here?

**Comment by Starmann** [comment]
Glad you asked. I'm trying to modify the code first using an Abstract Syntax Tree.

**Comment by john-dev** [comment]
I am looking for such a solution as well.
If i understood @Starmann right, he would like to execute tests programmatically to be able to evaluate the results for further processing.
Same goes for me. Those tests are coming via an api (so the webinterface), having access to mocha results as json(streams) would be very handy for a lot of things like notifications etc. (i use mocha to cron-test remote RestAPI's for example)

**Comment by JoshuaKGoldberg** [comment]
This seems like a very niche request. It would probably be resolved by #1457... but without more detail, it's hard to say.

Closing as wontfix. But if someone reading this really wants this feature, please do file a new issue with our new feature template & describe your situation. I'd be interested to know more. Thanks!
