### ISSUE TITLE
investigate use of Travis-Ci jobs and stages, etc.

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3292]
This is a [beta feature](https://docs.travis-ci.com/user/build-stages/) on Travis-CI, but we could (potentially) leverage it to make it more obvious what's happening during each build in the matrix.

It may not be worth doing, either.  We don't have a bunch of packaging, deployment or artifact generation happening (though we have some).

**Comment by Bamieh** [comment]
@boneskull Nice! I have been missing this feature on travis, while circleCI has a similar one. I will definitely try it out soon and give feedback/PR.

**Comment by outsideris** [comment]
I closed this because #3302 has merged.
