### ISSUE TITLE
Wrong example

### ISSUE THREAD

**Issue by falsandtru** [mochajs/mocha#3294]
`this` can't be used in arrow functions:

https://github.com/mochajs/mocha/blob/master/docs/index.md#arrow-functions

**Comment by markowsiak** [comment]
Hi @falsandtru 
Thanks for taking the time to file this.  However, the example was given as something that won't work as described by the preceding text:
```
For example, the following code will fail:
```

What might be interesting is if we standardize a clearer way of giving properly formed examples and breaking examples? @ScottFreeCode @boneskull what do you think?  Is there enough cases or gotchyas we can cover by that type of documentation change?  I'm envisioning a 50% split in the code block examples, one with a heading "Works" in green, and the other with "Won't Work" in red?

**Comment by boneskull** [comment]
IMO the best way to do this would be to have "live" code examples, a la AngularJS.  @markowsiak can you make an issue for that?  I don't think it'll get done any time soon, but if someone ever wants to work on the site, that's a big win.

**Comment by falsandtru** [comment]
Right, sorry about that.
