### ISSUE TITLE
Support per-test cleanup by calling `after` inside a test

### ISSUE THREAD

**Issue by DanTup** [mochajs/mocha#3296]
I have tests using `sinon` that have cleanup that must be called to avoid subsequent tests failing. Here's an example:

```ts
describe("refactor", () => {

	before(() => activate());

	it("can extract simple code into a method", async () => {
		const showInputBox = sinon.stub(vs.window, "showInputBox");
		showInputBox.resolves("printHelloWorld");

		await setTestContent(`
main() {
  print("Hello, world!");
}
		`);
		await (vs.commands.executeCommand("_dart.performRefactor", doc, rangeOf("|print(\"Hello, world!\");|"), "EXTRACT_METHOD"));
		await ensureTestContent(`
main() {
  printHelloWorld();
}

void printHelloWorld() {
  print("Hello, world!");
}
		`);

		// TODO: This won't be restored if an error occurs
		showInputBox.restore();
	});
```

If the `restore` at the bottom doesn't get called, things break. This means when one test fails, it generally brings down the whole lot.

I can't put this cleanup in `after` or `afterEach` because it's specific to this test. I don't want to wrap another needless `describe` around each test. Wrapping in a `try`/`finally` adds yet another level of nesting and requires the variables be declared before the `try` (to be in scope for `finally`).

It would be nice if we could do per-test cleanup be calling `after` again inside a test. It could work a bit like `defer`:

```ts
describe("refactor", () => {

	before(() => activate());

	it("can extract simple code into a method", async () => {
		const showInputBox = sinon.stub(vs.window, "showInputBox");
		showInputBox.resolves("printHelloWorld");

		after(showInputBox.restore); // This will be called after this test, success or fail, and only once

		// SNIP
	});
```

Currently this seems to just execute at the end of the run (and if you call `afterEach`, it runs after every test from this one forwards).

**Comment by DanTup** [comment]
FWIW I was able to somewhat emulate this with a `defer` function in my test helpers file like this:

```ts
const deferredItems: Array<() => Promise<void> | void> = [];
afterEach(async () => {
	for (const d of deferredItems) {
		await d();
	}
	deferredItems.length = 0;
});
export function defer(callback: () => Promise<void> | void): void {
	deferredItems.push(callback);
}
```

I'm not sure if my `afterEach` will end up stacking up multiple times (one for each time this helper file is loaded into a test) but since it clears the array after processing, I don't think that'd cause any problems.

**Comment by outsideris** [comment]
IMO supporting after for each test can make mocha much complexly. Another `describe` or `try`/`catch` block seems simple workaround for general purpose.

**Comment by plroebuck** [comment]
Fail to see why you can't use `afterEach()` along with Sinon [sandbox](http://sinonjs.org/releases/v4.5.0/sandbox/).

**Comment by DanTup** [comment]
@plroebuck Oh awesome, I didn't realise it supported that - that'll definitely simplify things :-)

**Comment by plroebuck** [comment]
Does that resolve your issue?

**Comment by DanTup** [comment]
I don't think it makes this request less applicable, but it should solve my problem (I haven't tested it yet, but I'd already implemented my own `defer` method as mentioned above). If you don't think it's worth adding, feel free to close!

**Comment by DanTup** [comment]
FWIW, the sandbox seems to work and simplified my code, removing a bunch of `defer` calls for each stub :)

**Comment by outsideris** [comment]
@DanTup I like to hear that you address the problem. :)

**Comment by jtakalai** [comment]
This is a very common problem though: often you have tests that modify a fixture that you might want to re-use in subsequent test cases. Either you'll have to wrap the whole case into a try/catch, or create a new fixture for each case. Boo.

Mocha already supports modifying the timeout: `it(() => { testing() }).timeout(1000)`. Couldn't there be similarly `it(() => { testing() }).finally(() => { cleanup() })`, finally alluding to try/catch where finally is executed regardless of errors.
