### ISSUE TITLE
Programmatic Usage Freezes

### ISSUE THREAD

**Issue by simlu** [mochajs/mocha#3298]
I'm currently using mocha as described [here](https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically). However it seems that I can not execute the runner recursively. The program freezes instead of running the "inner" instance of Mocha.

Does the runner enforce a lock somehow? 

Help is much appreciated! Thank you, L~

**Comment by outsideris** [comment]
Could you provide example code to let us understand what your problem is.

**Comment by simlu** [comment]
After further investigation it seems that I can not spawn a grunt task while running tests programmatically. I will try to provide a minimal test case over the weekend.

**Comment by simlu** [comment]
Thank you for the quick reply. This seems to have been an issue with grunt. After removing the test runner everything works fine. Cheers, L~
