### ISSUE TITLE
browser unable to load latest node version

### ISSUE THREAD

**Issue by abidrana7** [mochajs/mocha#3300]
i'm running my Mocha scripts via Browserify in browser but got the following error in browser's console:

"Uncaught Error: Sync-request requires node version 0.12 or later.  If you need to use it with an older version of node
you can `npm install sync-request@2.2.0`, which was the last version to support older versions of node."

However installed nodejs's version on machine is  `v9.5.0'

![node_v](https://user-images.githubusercontent.com/16793789/38192434-47edb6ea-3686-11e8-85e3-0923666625f3.png)

**Comment by outsideris** [comment]
mocha doesn't have a dependency for `sync-request`, see [package.json](https://github.com/mochajs/mocha/blob/master/package.json#L309). 
Could you provide more detail about your environment?
