### ISSUE TITLE
Not compatible with Node 8

### ISSUE THREAD

**Issue by abdennour** [mochajs/mocha#3306]
### Prerequisites

- Node 8.5.0
- Don't use transpiler like Babel

### Description

I am building a frontend boilerplate project where the main frameworks are mocha and webpack using Node8. Webpack 4 is working fine with Node 8 without any intervention of transpiler tools like babel. However, Mocha does not.

### Steps to Reproduce

1. Switch to Node 8 

```sh
nvm install 8.5.0 && nvm use 8.5.0
```

2. Write a unit-test case compatible with Node 8 (includes `import` keyword) : 

```js
import Component from './App.component.js';

describe('App component', () => {
  it('is named App', () => {
    expect(Component.component).toEqual('app')
  })
})

```

3. Run unit-tests using mocha 

```sh
mocha --watch $(find  src -name '*.spec.js')
```

**Actual** Seeing a message in the STDERR: 

```
(function (exports, require, module, __filename, __dirname) { import Component from './App.component.js';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
```

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:  `5.0.5`
- The output of `node --version`:  `v8.5.0`
- The version and architecture of your operating system: `Darwin MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`
- Your shell (bash, zsh, PowerShell, cmd, etc.): `zsh`
- Your browser and version (if running browser tests):
- Any other third party Mocha related modules (with versions): 
- The code transpiler being used: No and we require to not use it, but rather leverage Node 8 features ( import, export, async, await and so on)

### Additional Information

No additional info.

**Comment by outsideris** [comment]
Node.js v8.5.0 only support ES Modules with `--experimental-modules` flag.
We want to support all flag for node.js runtime, but there is not a  way to pass flags to node.js easily yet, see https://github.com/nodejs/node/issues/17740 .

**Comment by boneskull** [comment]
The answer as of this writing is to use `node --experimental-modules path/to/_mocha <whatever>`
