### ISSUE TITLE
Live Coding Examples

### ISSUE THREAD

**Issue by markowsiak** [mochajs/mocha#3314]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

Mocha should provide live coding examples on its website to show both successfully executing constructs, and those that fail.  This would reduce the number of frequency asked questions and add depth to the documentation.

**Comment by juergba** [comment]
see [mocha-examples](https://github.com/mochajs/mocha-examples).
