### ISSUE TITLE
React propTypes validation is not invoked during component unit tests

### ISSUE THREAD

**Issue by lubomir-sokolovsky-sde** [mochajs/mocha#3319]
I have a React component (using TypeScript):

    import ...
    import PropTypes from "prop-types";

    export class PageSizeComponent extends React.PureComponent<PageSizeProps, PageSizeState> {

        public static defaultProps: Partial<PageSizeProps> = {
            pageSizes: [10, 20, 50, 100],
            initialPageSize: 10
        };
    
        static propTypes = {
            pageSizes: (props: PageSizeProps, propName: string, componentName: string) => {
                if (!props.pageSizes.length) {
                    return new Error("At least one option for page size must be supplied.");
                }
            }
        };
        ...
    }

    export default PageSizeComponent;

And a unit test testing the `propTypes` of the component:

    describe("PageSize", () => {
        let component: ShallowWrapper;
        let error: SinonStub;

        beforeEach(() => {
            error = stub(console, "error").callsFake((args) => console.log("console.error", ...Array.from(arguments)));
            component = shallow(<PageSize onChangePageSize={() => { }} pageSizes={[]} />);
        });

        afterEach(() => {
            error.restore();
            error = null;
            component = null;
        });

        it("should write a console error if pageSizes is empty", () => {
            expect(error.callCount).is.greaterThan(0);
        });
    });

When I try to run the tests, I get an assertion error saying, that the error count is 0 (although the expect count is 1). However, when I run the application and supply an empty array to the PageSize component, I can see the following message in the console:

    Warning: Failed prop type: At least one option for page size must be supplied.
        in PageSizeComponent (created by UsersComponent)
        ...

I tried adding a simple `console.log` just before the `if` statement in the `propTypes` validation of the component. When running in browser, I could see the message in the console. However, when running `npm test`, the message did not get outputted. I tried adding console messages to other places in the code and they did display in when running `npm test`. It seems the propTypes validation is not called at all. 

I have also tried using a real component instead of the `ShallowWrapper`, but that did not help either.

Used package versions are following:

 - karma-mocha ^1.3.0
 - mocha ^5.0.1
 - react 16.2.0
 - sinon ^4.5.0
 - sinon-chai ^3.0.0

  [1]: https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-reactproptypes

**Comment by outsideris** [comment]
Are you using babel or something like?
And did you import `PageSizeComponent` as `PageSize` in your test code?

**Comment by lubomir-sokolovsky-sde** [comment]
Yes, `PageSizeComponent` is imported as `PageSize`. And yes, we are using babel. Here are the individual package versions we use:

    "babel-cli": "^6.24.1",
    "babel-core": "^6.17.0",
    "babel-eslint": "^8.0.3",
    "babel-loader": "^7.1.2",
    "babel-plugin-istanbul": "^4.1.6",
    "babel-plugin-react-intl": "^2.3.1",
    "babel-polyfill": "^6.16.0",
    "babel-preset-es2015": "^6.16.0",
    "babel-preset-es2016": "^6.22.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-react-hmre": "^1.1.1",
    "babel-preset-stage-2": "^6.17.0",
    "babel-preset-stage-3": "^6.22.0",

**Comment by boneskull** [comment]
This isn't a Mocha error... your best bet is StackOverflow or the [chat room](https://gitter.im/mochajs/mocha)
