### ISSUE TITLE
reading a csv file stops the dynamic test

### ISSUE THREAD

**Issue by hsloan1a** [mochajs/mocha#3322]
### Prerequisites

package file:
  "scripts": {
    "test": "./node_modules/.bin/mocha --exit",
    "start": "node index.js"
  },
  
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.18.2",
    "chai": "^4.1.2",
    "chai-http": "^3.0.0",
    "cors": "^2.8.4",
    "csv-parser": "^1.12.1",
    "dotenv": "^4.0.0",
    "express": "^4.16.2",
    "fs": "0.0.1-security",
    "http": "0.0.0",
    "mocha": "^5.0.0",
    "path": "^0.12.7",
    "watson-developer-cloud": "^3.0.3"

### Description

can't read a csv to create a dynamic test

### Steps to Reproduce
```
describe('creating` a dynamic test from csv file', function(){
//    run();
    //setTimeout(function(data, err){
 //   for (var i = 0; i < 500; i++) { 
//    dataFromCSV.forEach(function(myTest) {
    //console.log("FullUtterance:", dataFromCSV)
    //console.log("Intent:", myTest.Intent)
       //myTest = results.data[i];'
    fs.createReadStream('./test/Input_DataFile01.csv')
      .pipe(csv())
      .on('data', function (data) {
      it('should return for input'  + ' and return value ' + 1 , function() {
              assert.equal(1, 1);

      // chai.request(app)
      // .post('/api/v1/message')
      // .send({input: "test"})
      // .end(function (err, res) {
      //   res.status.should.equal(200);
        //done();
      
        });
    }) 
 //     });
//  }
//});
});
```
'
**Expected behavior:** I was going to read a csv file and create tests on the fly using that as an input. 

**Actual behavior:** All tests but the one above shows up on the response.

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
    - 5
- The output of `node --version`:
    -8
- The version and architecture of your operating system:
    -iOS latest
- Your shell (bash, zsh, PowerShell, cmd, etc.):
    -terminal

### Additional Information

I have tried papaparse and creating my custom. I can see the data with console.log, but it just dies at the it. I have tried to run and --delay, but I can't seem to get that working. If I remove the readcsv and just do the for loop 500 times, it appears to work, so it would appear to me it has to be the file. I haven't checked on the file size. I think I have about 100 test cases. I haven't shrunk that down yet. I'm just trying to setup a way for a non-developer to run test cases. The other thought I had was trying to convert it to a json and see if that makes a difference. Just haven't made it that far.

**Comment by hsloan1a** [comment]
I converted the csv to a json file and it appears to be working

**Comment by janupan** [comment]
> I converted the csv to a json file and it appears to be working

How you do to convert the csv file?
