### ISSUE TITLE
feature-request/question: bypass exclusive (only) tests on CI

### ISSUE THREAD

**Issue by talanta** [mochajs/mocha#3326]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

It there an existing flag, or something planned in the roadmap to force all tests to run, regardless of the `.only` on some tests ?

### Additional Information

sometime developers might forget the `.only` on a specific suite or single test, then after the push, the CI will pass, even the reviewer can miss it, if too much line of code to read, so all lights green until goprod. Regressions if happen, will be notice very late.  
Have someone already dealt with that kind of issue ?

**Comment by outsideris** [comment]
If you use `--forbid-only` options in the CI, the tests will be failed when developers pushed tests with `only`.
