### ISSUE TITLE
`--file` documentation is confusing with regards to `--recursive`

### ISSUE THREAD

**Issue by machineghost** [mochajs/mocha#3327]
### Prerequisites

- [X] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)

(The rest aren't checked because this is a documentation bug.)

- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

Documentation of `--file` is unclear, particularly it's interaction with `--recursive`.  The current documentation for `--file` says:

>The file passed is not affected by any other flags (--recursive or --sort have no effect).

That makes it sound like you can use both, but `--recursive` won't impact `--file`.  However, that isn't the case: if I run with just `--file someFile.js` my file runs first, but if I add `--recursive` it doesn't get run until later (if at all).

It seems odd that running "whatever's in a directory and its nested sub-directories" would make it impossible to pick one file and run it before you start recursing, but I'm sure there's a good reason.  If you could perhaps make the existing documentation clearer by saying something like "--file may not/will not work if you combine it with --recursive", and maybe even add after some explanation of why Mocha works that way, eg. "(and here's why that seemingly easy thing of running a file before a bunch of recursed files isn't something Mocha can do)" I think it would greatly improve the documentation.

### Steps to Reproduce

Documentation bug.

**Expected behavior:** I expect the documentation to accurately convey how the library's arguments work.

**Actual behavior:** Behavior (and the reason for that non-intuitive behavior) is not documented

**Reproduces how often:** Every time you read the `--file` documentation.

### Versions

Latest (I'm going by the documentation on your website).

### Additional Information

**Comment by plroebuck** [comment]
Are you specifying a file with `--file` that would _also_ be included from recursive directory walk of your project's "test" directory?

**Comment by plroebuck** [comment]
Afraid you'll need to provide an [MCVE](https://stackoverflow.com/help/mcve) to prove your point.
It seems to be functioning exactly as [documented](https://mochajs.org/#--file-file).

Reading the [code involved](https://github.com/mochajs/mocha/blob/adb1f612a8e909c3ce158ab66f75bb4a54a29014/bin/_mocha#L510-L557), files given via `--file` are handled [here](https://github.com/mochajs/mocha/blob/adb1f612a8e909c3ce158ab66f75bb4a54a29014/bin/_mocha#L549), then test spec files are appended [here](https://github.com/mochajs/mocha/blob/adb1f612a8e909c3ce158ab66f75bb4a54a29014/bin/_mocha#L557).
The `--sort` and `--recursive` options _only_ apply to test spec files.
