### ISSUE TITLE
Output gets cut off if piped into another application

### ISSUE THREAD

**Issue by joewhite** [mochajs/mocha#333]
If I run my Mocha tests directly from the command line, they run fine, and the output displays with no problems. But if I try to pipe Mocha's output to another program, the output doesn't all get there; only the beginning of the output ever makes it into the pipe.

I've seen this in several manifestations, but it's easy to reproduce just from the command line. I've reproduced this on two different computers, both running 64-bit Windows 7, the latest version of Node.js installed from the Web site, and the latest Mocha installed with `npm install -g mocha`.

If I create a file with just one test in it:

    it('works', function() {});

and run it from the command line, I see the expected output:

    C:\Temp>mocha test.js

      .

      ✔ 1 tests complete (2ms)

    C:\Temp>

But if I pipe its output into any other tool, even something as simple as `more`, then Mocha's output is cut off. I only see the line of dots -- sometimes not even that. The summary line isn't shown.

    C:\Temp>mocha test.js | more

      .

    C:\Temp>

If there are failing tests, and you run STDERR through a pipe, then the test-failure information will be cut off:

    C:\Temp>mocha fail.js 2>&1 | more

      .  Γ£û 1 of 1 tests failed:

    C:\Temp>

I've also seen this behavior when running Mocha from my text editor (Sublime Text 2) and capturing the output into an output window (the output doesn't all appear); and when writing Node.js code that shells out to Mocha (using `child_process.exec`) and captures its STDOUT and STDERR (the output doesn't all get sent). I haven't seen any other app cutting off its output like this in any of these circumstances, but Mocha does it every time its output is a pipe.

**Comment by am11** [comment]
Hello guys, over at node-sass, we are also experiencing the same issue. Any updates? 

Related: https://github.com/sass/node-sass/issues/506 and http://help.appveyor.com/discussions/problems/1091-npm-test-always-fails. 

Note: we tried @stephenmathieson's suggestion and used `--no-exit`, but then it doesn't exit the test process even after passing all the testes (until the CI [times out](https://ci.appveyor.com/project/sass/node-sass/build/250/job/0r75512tu1rbb9hf) and reports failure).

**Comment by dougwilson** [comment]
@am11 solution's code: https://github.com/mochajs/mocha/pull/1440/files

**Comment by dougwilson** [comment]
@am11 it was merged here, but just hasn't yet been released to npm.

**Comment by am11** [comment]
@dougwilson, thanks for fixing this issue in mocha.  :+1: 

Over at node.js, they have fixed it in 0.12 branch, but yet to backport to 0.10.x branch: https://github.com/joyent/node/pull/7196 (see the late comments). Not sure if/ever it will land in 0.10.x branch.

**Comment by dougwilson** [comment]
I doubt they'll ever backport it to 0.10.

**Comment by jbnicolai** [comment]
Fix has been shipped ^^

**Comment by chrisleck** [comment]
Looks like this is failing now on node 7.2.1.  The `stream.write('', done);` call never calls the callback.  I'll open a new bug to track.
