### ISSUE TITLE
Mocha does not run tests defined within a function

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [mochajs/mocha#3347]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
I am trying to test my API with mocha & superagent, the thing is, I need to wait for the db to open, then export the app, because the tests require some initialization code that depends on the db.

So, in order to do that, I had to wrap my test code within an `async` function and call it, but it doesn't run the tests.

```
// test.js

describe('math', async () => {
  it('multiplies', () => {
    let result = 2 * 2;
    result.should.equal(4);
  });
});

const test = async () => {
  const should = require('chai').should();
  const request = require('supertest');
  const path = require('path')
  const app = await require(path.resolve('./server'));


  describe('math', async () => {
    it('adds', () => {
      let sum = 1 + 1;
      sum.should.equal(2);
    });
  });

  describe('users', async () => {
    it('creates a customer', async () => {
      let res = await request(app).get('/api/should-404/');
      res.status.should.equal(200);
    });
  });
};

test().catch(console.err);
```

```// server.js

module.exports = run().catch(console.err);

const run = async () => {
  const app = express()();
  const mongoose = require('mongoose');
  await mongoose.connect('mongodb://localhost:27017/speero_test');

  const db = mongoose.connection;

  db.on('error', console.error.bind(console, 'connection error:'));
  db.once('open', () => {console.log.bind(console, 'connection :')});

  // the line below depends on the db
  const initRolesPolicies = require(path.resolve('./initialize/initPolicies'))();

  app.listen(port, function () {
    console.log('Autotash is running ' + process.env.NODE_ENV.toUpperCase() + ' on port ' + port + ' !');
  });

  return app;
}

module.exports = run().catch(console.err);
```

### Steps to Reproduce

**Expected behavior:** All tests to run, the multiplication, the addition, and the customer creation.

**Actual behavior:** Only the multiplication test (the one outside the _test function_) run, the ones inside are completely ignored even though I execute the function at the bottom.

I don't completely like wrapping the test suites inside a function, but I have to await for the app to be returned, I am open for any other approaches to accomplish this. I just need to wait for db to be ready before exporting the `app` object and running the tests.

**Reproduces how often:** [100%]

### Versions

- mocha v4.0.1
- node v8.9.3
- mongoose v5.0.14
- Windows 10
- Cmder

**Comment by ORESoftware** [comment]
First thing I notice:

```js
const test = async () => {
   // ...

  describe('math', async () => {
    it('adds', () => {
      let sum = 1 + 1;
      sum.should.equal(2);
    });
  });

 // ....
};
```

you shouldn't registered any of the following asynchronously:

`it/describe/before/after/afterEach/beforeEach`, etc.

all hooks should be registered synchronously, otherwise you will get unknown behavior.

**Comment by AbdelrahmanHafez** [comment]
What if I need to do some async functions on `before` and `beforeEach`, like cleaning the database for example?
How should I handle that?

**Comment by AbdelrahmanHafez** [comment]
Actually, I think I just found a solution!
```
// test.js
const should = require('chai').should();
const request = require('supertest');
const path = require('path')
let app;

before(async () => {
  try {
    app = await require(path.resolve('./server'));
  }
  catch (err) {
    console.log(err);
  }
});

describe('math', async () => {
  it('multiplies', () => {
    let result = 2 * 2;
    result.should.equal(4);
  });
  it('adds', () => {
    let sum = 1 + 1;
    sum.should.equal(2);
  })
});

describe('users', async () => {
  it('creates a customer', async () => {
    let res = await request(app).get('/api/should-404/');
    res.status.should.equal(200);
  });
});
```

This did the trick after two days of trying to figure it out.

I am completely new to testing, is there a better way to do this?

**Comment by ORESoftware** [comment]
yep what you have now is good, that is a very common pattern with Mocha.

**Comment by AbdelrahmanHafez** [comment]
Thanks a lot!

**Comment by LordOfTheDings** [comment]
Thank you very much for posting your solution. I had the same problem and this provided me with the necessary information.

**Comment by AbdelrahmanHafez** [comment]
@LordOfTheDings 
Nothing makes me happier than coming back to things years earlier that saved someone else time.
Pay it forward 👍

**Comment by RishabhAtomos** [comment]
describe('Test', () => {
    console.log("describe1")
    it('should return 200 status code', function (done) {
      console.log("IT")
      chai.request(app)
        .get('/v1/cis/test')
        .end((error, response) => {
          expect(response).to.have.status(200);
        });
        done();
    });
    console.log("describe2")
  });
  
  Why my it() is not getting executed?

**Comment by AbdelrahmanHafez** [comment]
@RishabhAtomos 
Your code looks right, it should run but the test doesn't really test anything because you are calling `done()` too quickly.
Your code calls `done()` before the `.end(...)` happens
```js
  chai.request(app)
      .get('/v1/cis/test')
      .end((error, response) => {
        expect(response).to.have.status(200);
      });
      done();
```

You need to move the `.done()` within the `.end(...)` callback.
```js
  chai.request(app)
      .get('/v1/cis/test')
      .end((error, response) => {
        expect(response).to.have.status(200);
        done();
      });
```

That way your test exits execution only after there is a response from the `chai.request().get()`.

Worth noting that callbacks and `done()` are things of the past, I highly recommend you learn more about promises and async/await, it'll make your life much easier.
