### ISSUE TITLE
npm run mocha-test fails.

### ISSUE THREAD

**Issue by Nazarah** [mochajs/mocha#3351]
Hello, I am trying to run mocha in my app, but every time it is failing.

I am trying `npm run mocha-test` command.

I am getting the following error in the command prompt:

![image](https://user-images.githubusercontent.com/17976243/39233898-5a841578-487a-11e8-87b9-f929e3238a6d.png)

When I tried to google with 

> Error: EPERM: operation not permitted, symlink 

I found a solution in [this issue](https://github.com/meteor/meteor/issues/8091) in GitHub:

`meteor reset`
`npm install`
`npm test`

However, I received the following error then (on running `npm test`):
![image](https://user-images.githubusercontent.com/17976243/39233661-b1a630ee-4879-11e8-8b21-89d6aa0ac7ca.png)

I checked manually in the library and found fibers.node
I also initiated a build in `C:\Program Files\nodejs\node.exe C:\Users\Omistaja\Documents\GitHub\platform\node_modules\chimp\node_modules\fibers` but that failed as well.

I am not sure what I am doing wrong.
Sorry for the long description.

Node version: **v8.11.1**
Meteor Version: **1.5.2**
npm version: **5.6.0**

**Comment by outsideris** [comment]
It looks like meteor's problem, not mocha's.

**Comment by boneskull** [comment]
or meteor-mocha... not sure.  sorry, but we can't help.
