### ISSUE TITLE
Exception swallowed 

### ISSUE THREAD

**Issue by barocsi** [mochajs/mocha#3353]
node v8.9.4.
mocha v5.1.1
```
describe('[Test', function () {
    it('Should display some exception', function (done) {
        throw new Error('my error');
    })
})
```
outputs:
```
 [Test]
    1) Should display some exception


  0 passing (8ms)
  1 failing

  1) [Test]
       Should display some exception:
     Uncaught Error: my error
      at Context.<anonymous> (partner.sync.total.test.js:3:15)
```

**Comment by plroebuck** [comment]
Why are your results unexpected? You threw an exception without try/catch, so it went uncaught.
Can you explain what you're trying to achieve? Perhaps I could suggest something testable afterwards.

**Comment by boneskull** [comment]
Use `--allow-uncaught` if you want to see that right away (though it will mean the process will end).
