### ISSUE TITLE
reporter cannot find dynamic tests

### ISSUE THREAD

**Issue by AShubin** [mochajs/mocha#3357]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

When I try change reporter to doc or etc I receive  warning 
`
Warning: Could not find any test files matching pattern: doc
`

```
var assert = require('chai').assert;

function add() {
    return Array.prototype.slice.call(arguments).reduce(function(prev, curr) {
        return prev + curr;
    }, 0);
}

describe('add()', function() {
    var tests = [
        {args: [1, 2],       expected: 3},
        {args: [1, 2, 3],    expected: 6},
        {args: [1, 2, 3, 4], expected: 10}
    ];

    tests.forEach(function(test) {
        it('correctly adds ' + test.args.length + ' args', function() {
            var res = add.apply(null, test.args);
            assert.equal(res, test.expected);
        });
    });
});
```

### Steps to Reproduce
* save code to test.js
* mocha --delay -R doc test.js

**Expected behavior:** 
It should process all dynamic added test
 
**Actual behavior:** 
it returns Warning: Could not find any test files matching pattern: doc

**Reproduces how often:** 
always

### Versions

-  mocha 4.1.0:
- node v9.8.0
- MacOS 10.13.4
- ITerm2

**Comment by outsideris** [comment]
I tried to reproduced it. I did it with both mocha v5.1.1 and 4.1.0.

```sh
$ mocha -R doc test.js
    <section class="suite">
      <h1>add()</h1>
      <dl>
        <dt>correctly adds 2 args</dt>
        <dd><pre><code>var res = add.apply(null, test.args);
assert.equal(res, test.expected);</code></pre></dd>
        <dt>correctly adds 3 args</dt>
        <dd><pre><code>var res = add.apply(null, test.args);
assert.equal(res, test.expected);</code></pre></dd>
        <dt>correctly adds 4 args</dt>
        <dd><pre><code>var res = add.apply(null, test.args);
assert.equal(res, test.expected);</code></pre></dd>
      </dl>
    </section>
```

Could you provide more details?

**Comment by plroebuck** [comment]
Although it should make absolutely no difference (but since JeongHoon couldn't reproduce), what happens if you these?

```bash
$ mocha test.js -R doc                  # move positional argument first
    --or--
$ mocha --reporter doc test.js     # use long option name
```

**Comment by AShubin** [comment]
hm, it works after updating to latest version and only when I use global module.
thank you!
