### ISSUE TITLE
access to test status in tearDown() and suiteTearDown()

### ISSUE THREAD

**Issue by ehartford** [mochajs/mocha#336]
in tearDown() and suiteTearDown() I am not seeing any way to access 1) list of passed tests 2) list of failed tests 3) list of skipped tests.

I would like my teardown logic to react to whether there were failures.

**Comment by danielstjules** [comment]
Closing as this has been feasible for a while using `this.test.parent.tests`, though it is using private APIs. A test which has not yet ran will not have a state or duration property.

To get total number of failures, if interested:
``` javascript
after(function() {
  var failures = this.test.parent.tests.map(function(test) {
    return test.state;
  }).reduce(function(prev, curr) {
    return (curr === 'failed') ? prev + 1 : prev;
  }, 0);
});
```

To get the state of the last test:
``` javascript
$ cat example.js
var util = require('util');

afterEach(function() {
  var test = this.test.parent.tests.reduce(function(prev, curr) {
    return (!curr.state) ? prev : curr;
  });

  console.log(test.title, test.state);
});

it('foo', function(done) {
  setTimeout(done, 100);
});

it('bar', function(done) {
  setTimeout(done, 100);
});

it('baz', function(done) {
  setTimeout(done, 250);
});

$ ./bin/mocha example.js


  ․foo passed
․bar passed
․baz failed


  2 passing (412ms)
  1 failing

  1)  baz:
     Error: timeout of 200ms exceeded. Ensure the done() callback is being called in this test.
      at null.<anonymous> (/Users/danielstjules/git/mocha/lib/runnable.js:170:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

```

@travisjeffery We could expose a property in the runnable context like `this.lastTest`, though it's likely not warranted given the lack of interest.
