### ISSUE TITLE
discuss: reconsider browserify

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3366]
While Browserify has served us well over the years, the ecosystem is approaching death.  While Browserify itself still sees maintenance, many transforms haven't been updated in years.

As the web ecosystem continues to evolve, the lack of a vibrant community will make Browserify an even *less* attractive technology.

*An aside*: **Not** bundling Mocha for the browser (and allowing users to do their own bundling) would be ideal, but that's not going to happen as long as packages such as [karma-mocha](https://npm.im/karma-mocha) depend on the bundle--and people seem to like running browser tests manually (see the popularity of [mochawesome](https://www.npmjs.com/package/mochawesome)).

I'm interested in hearing opinions.  This is by no means *urgent*, as Browserify seems to work fine for now, but something I'd just like to toss around...

**Comment by juergba** [comment]
outdated.
