### ISSUE TITLE
Remove bower installation in docs

### ISSUE THREAD

**Issue by outsideris** [mochajs/mocha#3369]
In [docs/index.md](https://github.com/mochajs/mocha/blob/master/docs/index.md#installation), we should remove installing mocha via bower because mocha no longer supports bower; see [the comments](https://github.com/mochajs/mocha/pull/3364#discussion_r185073819).

**Comment by fesebuv** [comment]
It seems like this issue was addressed by this pr https://github.com/mochajs/mocha/pull/3405/files. Perhaps this issue should be resolved?
@outsideris

**Comment by outsideris** [comment]
@fesebuv You're right. Thanks.
