### ISSUE TITLE
How to fix require paths in tested code

### ISSUE THREAD

**Issue by johnrobertporter** [mochajs/mocha#3384]
Please forgive me if this has been answered, I am a complete noob with JS testing, and I can't find the answer anywhere.

I use brunch to compile all my modules, and have a special function which allows me to use the module name without any path in the `require` statement.

This, of course, means that I can't test my code as none of the require paths work.

`app/my.module.js`

```js
require('my.module');
```

This even works in brunch for nested modules:

`app/nested/another.module.js`

```js
require('another.module');
```

Can anyone give any help on how I can allow mocha to resolve these paths?

**Comment by akrawchyk** [comment]
This is not supported by `brunch` [per its documentation](http://brunch.io/docs/testing):

> The current options for unit testing are:
> * use your built bundle from public in node
> * run unit tests in the browser

> **Currently, there is no way to run unit tests directly on node, but... A better approach is in the works.**

Here be dragons 🐉:

You can try using `mocha`'s `--require` option to load your custom module resolution code.

Please note, this is not a `mocha` specific issue, and seems more like a tech support question. I'd recommend familiarizing yourself with how Node handles [module resolution](https://nodejs.org/docs/latest-v8.x/api/modules.html#modules_loading_from_the_global_folders) to understand why this is happening.

**Comment by johnrobertporter** [comment]
Ok, that's some helpful information for me. Pretty new to node, brunch, and mocha, so I really appreciate the pointer.

Thanks for your help
