### ISSUE TITLE
Proposal: improve issue template.

### ISSUE THREAD

**Issue by outsideris** [mochajs/mocha#3389]
I feel our issue template pretty verbose.

Recently, [GitHub improves issue template](https://blog.github.com/2018-05-02-issue-template-improvements/) to users can report it categorized at an entry point. So, we can simplify our templates.

Babel already uses it like [this](https://github.com/babel/babel/issues/new/choose). (code is [here](https://github.com/babel/babel/tree/master/.github/ISSUE_TEMPLATE))

I think we need the options below.
* Bug Report
* Feature Request
* Support Question

What do you think?

**Comment by plroebuck** [comment]
"blew options" -> "the options below:"
