### ISSUE TITLE
How to use root level hooks when I import my mocha project?

### ISSUE THREAD

**Issue by tatthipatla** [mochajs/mocha#3390]
### Prerequisites

- [x ] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
I have created a project using mocha 3.5.3 which has a library file having root level before and after hooks for my test data creation and teardown. When I execute my tests in this project, my library with root level hooks get executed properly along with tests.
Now I import this project in my other nodejs project to make use of my library and try to compile/execute that project, it is failing with 
ReferenceError: before is not defined

Since in the new project, Iam not running with mocha context and root level hooks in my library are not considered as there is no implied describe.

### Steps to Reproduce

1. create a nodejs project with mochajs.
2. create a library with root level before and after hooks. create some functions that can be used in other files/project.
3. import this package in another project.
4. try to compile/run/execute the project.

**Expected behavior:** Should be able to import and use mochajs project in another project.

**Actual behavior:** ReferenceError: before is not defined ic coming.

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:3.5.3
- The output of `node --version`:v8.9.0
- The version and architecture of your operating system:MAC OS
- Your shell (bash, zsh, PowerShell, cmd, etc.):BASH
- Your browser and version (if running browser tests):N/A
- Any other third party Mocha related modules (with versions):
- The code transpiler being used:babel

**Comment by plroebuck** [comment]
Could you give us _something_ to look at, pls?
Make this sample project available online so we can follow along.
How did you "execute" your tests? (specify your cmdline)

**Comment by boneskull** [comment]
Closing; please ask in [chat room](https://gitter.im/mochajs/mocha) or SO
