### ISSUE TITLE
Mocha 5.1.1 is not testing all files

### ISSUE THREAD

**Issue by ssunny2** [mochajs/mocha#3393]
I upgraded mocha from `^2.2.5` to `5.1.1` in my Angular JS project. I have 11550 test cases in my application, all of which were successful before the upgrade. However, after upgrading Mocha, I'm getting irregular outputs while running grunt test such as

- Firefox 60.0.0 (Windows 10.0.0): Executed 6132 of 11550 (skipped 86) SUCCESS (3 mins 13.945 secs / 16.863 secs) TOTAL: 6132 SUCCESS

- Firefox 60.0.0 (Windows 10.0.0): Executed 868 of 11550 (skipped 9) SUCCESS (35.564 secs / 3.799 secs) TOTAL: 868 SUCCESS

- Firefox 60.0.0 (Windows 10.0.0): Executed 951 of 11550 (3 FAILED) (skipped 9) (32.092 secs / 3.229 secs) TOTAL: 3 FAILED, 948 SUCCESS`
1) "before each" hook Testing the homePageService functionality  

2) "after each" hook

 currentSpec is null
module.$$cleanup@http://localhost:8100/base/bower_components/angular-mocks/angular-mocks.js?861c27a0d62d5f7beed79cd1b40b44f0560b2eb5:2992:9 module.$$afterEach@http://localhost:8100/base/bower_components/angular-mocks/angular-mocks.js?861c27a0d62d5f7beed79cd1b40b44f0560b2eb5:2987:7

3) "after each" hook for "To test submitZip method"

 currentSpec is null
module.$$cleanup@http://localhost:8100/base/bower_components/angular-mocks/angular-mocks.js?861c27a0d62d5f7beed79cd1b40b44f0560b2eb5:2992:9 module.$$afterEach@http://localhost:8100/base/bower_components/angular-mocks/angular-mocks.js?861c27a0d62d5f7beed79cd1b40b44f0560b2eb5:2987:7

Do note that for the first two times I ran test, I wasn't getting any logs on the NPM console for failed tests, which of course was because the tests were passing, although after ignoring many TCs.

Angular CLI: 6.0.1
Node: 9.4.0
NPM: 5.6.0
OS: win32 x64

**Comment by plroebuck** [comment]
You jumped 3 **major** versions at once; did you try upgrading a single version at a time to see how far back the problems started (i.e., jump major until problem, then downgrade major and bump minor, then patch versions)?

There's precious little you provided for us to be able to help you. Can you share some small portion of the code involved that demonstrates the problem and a means to test it?

**Comment by ssunny2** [comment]
Hi, Sorry for the delay in response

Yes I downgraded mocha till 3.5.1, where all tests fully ran without any failures. When I upgrade to 3.5.2, I start getting errors( snapshot attached)
![mocha3 5 2](https://user-images.githubusercontent.com/30898686/40640203-a433161a-6332-11e8-975a-589980d15071.JPG) . The number of test cases covered too, has reduced by `100-150 with every upgrade till Mocha 4.1.0. 

Yes, it should be covering 11550 every time, no matter what the version of Mocha is. Version 5.x.x however, isn't doing that. It's skipping approx. 5000 TCs , giving a "SUCCESS" output and isn't providing any logs on the skipped ones. 

What kind of code are you expecting here? I could provide more. Here's the devDependencies object inside package.json

"devDependencies": {
    "async": "^1.2.1",
    "blink-diff": "^1.0.12",
    "brfs": "^1.4.1",
    "browser-sync": "^2.10.0",
    "browserify": "^11.0.1",
    "chai": "^4.1.2",
    "chai-as-promised": "^5.1.0",
    "chalk": "^1.0.0",
    "chromedriver": "^2.16.0",
    "coffee-script": "^1.9.3",
    "connect-modrewrite": "^0.8.2",
    "crypto": "0.0.3",
    "date-time": "^1.0.0",
    "decache": "^4.1.0",
    "eslint-html-reporter": "^0.4.14",
    "figures": "^1.3.5",
    "fs-extra": "^0.26.2",
    "glob": "^5.0.10",
    "graceful-fs": "^4.1.2",
    "grunt": "^0.4.5",
    "grunt-accessibility": "^4.0.0",
    "grunt-angular-templates": "^0.5.7",
    "grunt-autoprefixer": "^3.0.3",
    "grunt-browser-sync": "^2.2.0",
    "grunt-cache-breaker": "^2.0.1",
    "grunt-concurrent": "^1.0.1",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-compass": "^1.0.3",
    "grunt-contrib-concat": "^0.5.1",
    "grunt-contrib-connect": "^0.10.1",
    "grunt-contrib-copy": "^0.8.0",
    "grunt-contrib-csslint": "^0.4.0",
    "grunt-contrib-cssmin": "^0.12.3",
    "grunt-contrib-htmlmin": "^0.4.0",
    "grunt-contrib-imagemin": "^0.9.4",
    "grunt-contrib-internal": "^0.4.12",
    "grunt-contrib-jshint": "^0.11.2",
    "grunt-contrib-less": "^1.0.1",
    "grunt-contrib-uglify": "^0.9.1",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-curl": "^2.2.0",
    "grunt-eslint": "^17.3.1",
    "grunt-exec": "^0.4.6",
    "grunt-file-append": "0.0.6",
    "grunt-filerev": "^2.3.1",
    "grunt-google-cdn": "^0.4.3",
    "grunt-graceful": "^1.0.0",
    "grunt-html-angular-validate": "^0.5.0",
    "grunt-html-snapshot": "^0.6.1",
    "grunt-injector": "^0.6.0",
    "grunt-jsbeautifier": "^0.2.10",
    "grunt-jscpd-reporter": "^0.1.5",
    "grunt-jscs": "^1.8.0",
    "grunt-junit": "^0.1.6",
    "grunt-karma": "^0.12.2",
    "grunt-lesslint": "^1.1.14",
    "grunt-mocha": "^0.4.12",
    "grunt-newer": "^1.1.1",
    "grunt-ng-annotate": "^1.0.1",
    "grunt-ngdocs": "^0.2.7",
    "grunt-parallelize": "^1.1.0",
    "grunt-plato": "^1.2.1",
    "grunt-protractor-runner": "^3.2.0",
    "grunt-remove-logging": "^0.2.0",
    "grunt-rename": "^0.1.4",
    "grunt-shell": "^1.1.2",
    "grunt-sitemap": "^1.2.1",
    "grunt-svgmin": "^2.0.1",
    "grunt-uncss": "^0.3.8",
    "grunt-usemin": "^3.0.0",
    "grunt-version-check": "^0.2.1",
    "grunt-wiredep": "^2.0.0",
    "grunt-yslow-test": "^0.1.0",
    "grunt-zip": "^0.17.0",
    "hooker": "^0.2.3",
    "jasmine-fail-fast": "^2.0.0",
    "jasmine-spec-reporter": "^2.4.0",
    "js-beautify": "1.6.14",
    "jshint-stylish": "^2.0.0",
    "karma": "^1.7.1",
    "karma-browserify": "^4.3.0",
    "karma-chai": "^0.1.0",
    "karma-chai-plugins": "^0.6.0",
    "karma-chrome-launcher": "^0.1.12",
    "karma-coverage": "^0.4.2",
    "karma-firefox-launcher": "^0.1.6",
    "karma-htmlfile-reporter": "^0.2.2",
    "karma-junit-reporter": "^0.2.2",
    "karma-mocha": "^0.1.10",
    "karma-ng-html2js-preprocessor": "^0.1.2",
    "karma-phantomjs-launcher": "^0.2.0",
    "karma-sinon": "^1.0.4",
    "karma-sinon-chai": "^1.0.0",
    "karma-sinon-expect": "^0.1.4",
    "karma-spec-reporter": "0.0.20",
    "load-grunt-config": "^0.17.1",
    "load-grunt-tasks": "^3.2.0",
    "lodash": "^3.9.3",
    "log-symbols": "^1.0.2",
    "mkdirp": "^0.5.1",
    "mocha": "^3.5.2",
    "phantomjs": "^1.9.17",
    "pretty-ms": "^1.1.0",
    "protractor": "3.0.0",
    "protractor-console": "^2.0.1",
    "protractor-html-screenshot-reporter": "^0.0.19",
    "protractor-jasmine2-html-reporter": "^0.0.6",
    "protractor-jasmine2-screenshot-reporter": "^0.3.1",
    "protractor-screenshot-reporter": "^0.0.5",
    "q": "^1.4.1",
    "request": "^2.79.0",
    "selenium-webdriver": "2.48.2",
    "sinon": "^1.15.3",
    "sinon-chai": "^2.8.0",
    "string-length": "^1.0.0",
    "supertest": "^1.0.1",
    "text-table": "^0.2.0",
    "time-grunt": "^1.2.1",
    "wd": "^0.4.0",
    "wd-bridge": "0.0.2",
    "xlsx": "^0.8.0",
    "yargs": "^3.29.0"
  }

**Comment by plroebuck** [comment]
Looked at both [3.5.2](https://github.com/mochajs/mocha/releases/tag/v3.5.2) (AMD-related) and [3.5.3](https://github.com/mochajs/mocha/releases/tag/v3.5.3) (xUnit-related) releases, but found nothing that should have caused skipping of tests. Release [4.0.0](https://github.com/mochajs/mocha/releases/tag/v4.0.0) was pretty major -- oner thing that stuck out there was a [change](#2879) to default behavior that Mocha no longer forces process to exit once all tests are complete; your tests are expected to cleanup after themselves. If you run your tests with the cmdline argument `--exit` and see many more run (than without the flag), then your tests are starting processes but not stopping them afterwards. If so, these two npm packages ([wtfnode](https://www.npmjs.com/package/wtfnode) and [stoppable](https://www.npmjs.com/package/stoppable)) may be useful to track down your problems.

P.S. Might want to cleanup that dependency list -- several offer duplicate functionality (e.g., "jscs", "jshint", "eslint") with others woefully out-of-date (e.g., "yargs").

**Comment by boneskull** [comment]
Hi, this could be a whole host of problems.  Please try asking in [the chat room](https://gitter.im/mochajs/mocha) or stackoverflow after creating an [MCVE](https://stackoverflow.com/help/mcve).

**Comment by jerrythimothyj** [comment]
I have moved from 2.4.5 to 6.1.4 and the number of tests running got reduced from 815 to 30.

@boneskull , any idea why?

**Comment by antennaio** [comment]
It's all fine for me on `mocha@4.1.0`, all 92 tests are executed every time. As soon as I upgrade to  mocha v5 (`mocha@5.2.0`) the number of tests that are run is reduced and different every time I run the test suite... It's 37, 39, 40, 42, sometimes 45 tests completed.

**Comment by renanbandeira** [comment]
I'm facing the same issue. I use mocha 5.0.1 because when I go to mocha 5.1, it reduces tests execution from 2100 to 455.

**Comment by fgkolf** [comment]
I was facing the same issue when trying to upgrade from `3.2.0`. Everything worked fine in `5.0.1` but when moved to `5.0.2` tests were reduced from 2695 to 875. It seems that the problem is in that version, mocha started NOT to swallow the errors that are thrown asynchronously. The relevant change is described here -> https://github.com/mochajs/mocha/releases/tag/v5.0.2.
 
What i did was to go to the last or the next to last test from the results and run it independently in order to see the error logged and fix the problem. Seems that mocha made a legit change since these tests are actually false positives.

You may need to repeat this lots of times until you have fixed all the problematic tests and your suite runs fully again.
