### ISSUE TITLE
Recursive doesn't seem to work as expected

### ISSUE THREAD

**Issue by gkvappium** [mochajs/mocha#3394]
I have an automation test framework built using appium. I am using mocha as the test framework. I am facing some problems when using the --recursive flag.

My Project structure is something like this.

    e2e
         -Test folder1
              -Test case file1
              -Test case file2
         -Test folder2
              -Test case file1
              -Test case file2
         -Test folder3
              -Test case file1
              -Test case file2

When I do a npm run e2e -- --runType configuration --recursive e2e/Testfolder1, all the folders are picked up for test execution

When I do a npm run e2e/Testfolder1 -- --runType configuration I get an error saying that it cannot find the scripts.

@boneskull , any inputs?

**Comment by Munter** [comment]
@gkvappium What is `e2e`? Could you reproduce the case you think is failing with the mocha command line tool instead, so we don't have to debug some external code that is not under our control?

**Comment by boneskull** [comment]
Hi, please ask in the [chat room](http://gitter.im/mochajs/mocha) or StackOverflow. be sure to provide an [MCVE](https://stackoverflow.com/help/mcve).  Thanks.
