### ISSUE TITLE
How to run one specific "it" case by command without using "only" function?

### ISSUE THREAD

**Issue by li-01** [mochajs/mocha#3409]
I know how to run one specific file from the wiki, but how to run one "it" case?

**Comment by ematipico** [comment]
`it.only` or `describe.only` is what you're looking for, I think.

**Comment by li-01** [comment]
@ematipico I mentioned it in the title, I don't want to write down "only" in the script.
My question was, is there any command like below?
$ mocha test\demo3.js (some "it" case)

**Comment by outsideris** [comment]
@li-01 You can use `--grep` or `--fgrep`.

**Comment by li-01** [comment]
@outsideris thank you very much!
