### ISSUE TITLE
Adding a custom UI breaks watch mode

### ISSUE THREAD

**Issue by rochdev** [mochajs/mocha#3415]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

When adding a custom UI while watch mode is enabled, tests are not re-run after saving a file.

### Steps to Reproduce

```js
// ui.js
const Mocha = require('mocha')

module.exports = Mocha.interfaces['my-ui'] = function (suite) {
  suite.on('pre-require', function (context, file, mocha) {
    const common = require('mocha/lib/interfaces/common')([suite], context)

    context.run = mocha.options.delay && common.runWithSuite(suite)
  })
}
```

```sh
./node_modules/.bin/mocha --watch --require ui.js --ui my-ui 'test/**/*.spec.js'
```

I also tried with the following code with the same result:

```js
// ui.js
const Mocha = require('mocha')

module.exports = Mocha.interfaces['my-ui'] = function (suite) {}
```

**Expected behavior:** I expect watch mode to still be working, since this UI basically changes nothing from the default UI.

**Actual behavior:** On the first run, tests are run. On file save, the suite is run with 0 tests: `0 passing (0ms)`

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 5.2.0
- The output of `node --version`: 8.11.1
- The version and architecture of your operating system: macOS 10.13.4
- Your shell (bash, zsh, PowerShell, cmd, etc.): bash
- Your browser and version (if running browser tests):
- Any other third party Mocha related modules (with versions):
- The code transpiler being used:

**Comment by outsideris** [comment]
It is because you didn't `context.describe` and so one like [bdd.js](https://github.com/mochajs/mocha/blob/master/lib/interfaces/bdd.js#L25).

If you use `bdd` style, invoking `context.describe` add suites. If you use `tdd` style, invoking `context.suite` add suites. There is no `context.describe` or `context.it`, so rerun can't regist suites and tests.

Below example use extending bdd style.

```
const Mocha = require('mocha')
const Test  = require('mocha/lib/test');

module.exports = Mocha.interfaces['my-ui'] = function myUiInterface(suite) {
  var suites = [suite];

  suite.on('pre-require', function (context, file, mocha) {
    const common = require('mocha/lib/interfaces/common')(suites, context, mocha)

    context.run = mocha.options.delay && common.runWithSuite(suite);

    context.describe = context.context = function(title, fn) {
      // console.log(common.suite);
      return common.suite.create({
        title: title,
        file: file,
        fn: fn
      });
    };

    /**
     * Pending describe.
     */

    context.xdescribe = context.xcontext = context.describe.skip = function(
      title,
      fn
    ) {
      return common.suite.skip({
        title: title,
        file: file,
        fn: fn
      });
    };

    /**
     * Exclusive suite.
     */

    context.describe.only = function(title, fn) {
      return common.suite.only({
        title: title,
        file: file,
        fn: fn
      });
    };

    /**
     * Describe a specification or test-case
     * with the given `title` and callback `fn`
     * acting as a thunk.
     */

    context.it = context.specify = function(title, fn) {
      var suite = suites[0];
      if (suite.isPending()) {
        fn = null;
      }
      var test = new Test(title, fn);
      test.file = file;
      suite.addTest(test);
      return test;
    };

    /**
     * Exclusive test-case.
     */

    context.it.only = function(title, fn) {
      return common.test.only(mocha, context.it(title, fn));
    };

    /**
     * Pending test case.
     */

    context.xit = context.xspecify = context.it.skip = function(title) {
      return context.it(title);
    };

    /**
     * Number of attempts to retry.
     */
    context.it.retries = function(n) {
      context.retries(n);
    };
  })
}
```
