### ISSUE TITLE
Error while run test

### ISSUE THREAD

**Issue by sivahanuman** [mochajs/mocha#3422]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Steps to Reproduce

**Expected behavior:** [ Test the code and print the status  ]

**Actual behavior:** [
$ npm run test

> inbox@1.0.0 test D:\Blockchain\solidity\inbox
> mocha

D:\Blockchain\solidity\inbox\node_modules\mocha\lib\interfaces\index.js:1
(function (exports, require, module, __filename, __dirname) {

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Blockchain\solidity\inbox\node_modules\mocha\lib\mocha.js:35:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! inbox@1.0.0 test: `mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the inbox@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Siva\AppData\Roaming\npm-cache\_logs\2018-06-21T12_33_10_485Z-debug.log

]

**Comment by outsideris** [comment]
Be sure to provide an [mcve](https://stackoverflow.com/help/mcve).

**Comment by Pomax** [comment]
Even without an MCVE, that error should say _what is wrong_. Just "SyntaxError: Invalid or unexpected token" does not tell folks anything about what they actually need to fix, or even where to look. They might be staring at 100% correct code with the error somewhere completely else, and Mocha will not help them figure that out.
