### ISSUE TITLE
initialise --inspector part the way through a test suite

### ISSUE THREAD

**Issue by christopherreay** [mochajs/mocha#3429]
- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

Debugging during tests can be very useful, since tests are a natural context from which to "test" code. The tests build the runtime context you need to explore .

Mocha runs perfectly well inside node with the V8 --inspector running, however, tests can take a very long time to execute when an inspector is connected to the inspection port

Its very easy to get node to shift into debugging mode dynamically during code execution

So I have created a "mocha test" that can be inserted part the way through the test suite, which pushes the node process into --inspector mode, and waits for the user to connect an inspector instance (e.g. chrome dev-tools inspector)

### Steps to Reproduce

Run loads of tests with the inspector debugging

**Expected behavior:** wait a long time to arrive at the test you want to debug

**Actual behavior:** you have to wait a long time to arrive at the test you want to debug

**Reproduces how often:** always

### Additional Information

is there like a "mocha tests utilities" library I could add this to? Or should I create my own importable npm module? Or it could conceivable be added to this repo, though it seems abit of an edge case for that

**Comment by plroebuck** [comment]
Where's the code?

**Comment by christopherreay** [comment]
oh hello, sorry. I'll dig it out tomorrow. works nicely

**Comment by christopherreay** [comment]
Hello, sorry.

Here, there is the code I use bedded in here. It still has the reference to the mocha "done" function in it, though I dont always pass that done from mocha anymore.

Umm... Ill just put it in a pasteof.code

https://paste.ofcode.org/S5yHYf5caU2PKJxGewvREs

Give me a shout if it is of interest. The point really is to send the kill signal with the right number.
its then possible to attach and detach the debugger as needed, and to pause and unpause the interpreter to wait for contact.

I didnt find an easy way to wait until the inspector is connected to the debugging port other than by just getting the user to put in a readline, but in practice it happens not so very often, that its not much bother

**Comment by christopherreay** [comment]
so basically you can insert a test into the test flow which has this content, which means you can run all the previous tests in a straight interpreter, which is "fast", and then debug your latest test from the environment created by all the previous tests.

my use case is pretty specific, but I suppose it would also work for large test suites, or something, rather  than for just the usecase where the tests are building environment on top of each other

I didnt find a way of "stopping" the debugging mode of the interpretter. I didnt look that hard though. either way, disconnecting the inspector from the port does a decent job of speeding stuff back up after debugging

**Comment by plroebuck** [comment]
So your pasteof.code is not there. Maybe just put it in the issue if you can't use a gist.
Curious in one sense as to why you're testing this way (without having seen the content).
If you're debugging your latest test, why bother running the existing ones at the same time?

**Comment by christopherreay** [comment]
https://gist.github.com/christopherreay/1880461039fe5d39c40ecbc8bab61bb3

here is a gist

the reason for this is that the tests that run before create the state which the further functionality relies.
As I build interacting sets of tools, the later tools rely on the results of the tests previously to create the state in which they make sense. As I said, I think, my use case is pretty edge case, but I dont think it is all that strange. 

Anyway I think this is cool :)

**Comment by plroebuck** [comment]
Reading your gist, I have some questions:
* What is `atRoot.ls` function; where does it come from -- how different from `console.debug`?
* Are environment variable names just made up or purposeful? If latter, explain what each does.
* In `catchUserDebugging` function, what sets `t` to `true`?
* What happens when run on MS-Windows? Node only documents enabling "late start" inspector for UNIX platforms.

Concerned about the security implications associated with enabling the debugger; not sure average person will understand the danger of doing this.

**Comment by christopherreay** [comment]
atRoot.ls is a simple wrapper function over console.debug (not really important what it is for... but outputs colorized objects nicely to the terminal).

the environment variable names are arbitrary, just relating to what is their shallow implication in the function.

it's the developer sets t to true using devtools, to continue the async. (I used to use a readline from the console, but sometimes I have sub node processess running)

I don't consider Windows platforms in dev.

I agree this is a edge case, in terms of users... I'm not sure of its generic value, but it's very useful for me, I use it in many scenarios to allow me to create a kind of easy to debug space for any new code... I can just flick out to async and open devtools anywhere in the code base.

I apologise if I have not been clear enough, but your questions were all exactly ok the money afaiac
