### ISSUE TITLE
How to develop a plugin / extension to mocha

### ISSUE THREAD

**Issue by daprahamian** [mochajs/mocha#3430]
Hi all,

For about a year now, we have been using a library we wrote called [`metamocha`](https://github.com/mongodb-js/metamocha) to run our tests. It allows us to add metadata to our tests in `mocha`, and then apply filters to filter out certain test cases.

We'd ideally like to be able to switch from using our own wrapper around `mocha` to instead use a plugin API to integrate `metamocha` into `mocha`. I could not find any documentation for writing plugins / extensions to `mocha`. Is there a way to do this?

Thanks,
Dan

**Comment by Bamieh** [comment]
Closing this as resolved, if you have specific questions to writing plugins feel free to open a new issue.

**Comment by onesandzeroes-maker** [comment]
@daprahamian may I ask on what path did you end up going? Metamocha has not been updated for a while and I wonder if you found an alternative solution...

**Comment by daprahamian** [comment]
I no longer work on the project, but I believe the approach was to specify a file that was preloaded whenever mocha was run, and have that file do most of the work that metamocha did. You could check out https://github.com/mongodb/node-mongodb-native/ and see what they have done in their tests.
