### ISSUE TITLE
Mocha is not waiting for the Promise to resolve.

### ISSUE THREAD

**Issue by thesageinpilani** [mochajs/mocha#3431]
post(url,data,callback){
        return this.service.post(url,data).then((response) => callback(response.status,response.data));
    }
the above code is in another file, service is an axios object. here axios is returning a promise.

describe("dummy Service",function() {
    it("it dummy",async function() {
        this.timeout(4000);
        return service.post('/dummy',{"abcd":"zyxw"},function(statusCode,data){
            expect(statusCode).to.equal(400);
            expect(data.status).to.equal("SUCCESS");
        });
    });
});

Here axios is returning a promise and i am returning that promise. But the mocha is not picking this up, i will get test passed and when the promise resolves, i get assertion error.(because the status code is 200). Help will be appreciated, Thanks.

**Comment by Munter** [comment]
If you are using an async function you should await the response instead of returning the promise. Our you could remove the async nature of your test function
