### ISSUE TITLE
afterEach runs before test completes

### ISSUE THREAD

**Issue by rohitsainimonotype** [mochajs/mocha#3439]
```
import sinonChai from 'sinon-chai';

/* eslint-disable no-undef */
chai.use(sinonChai);
/* eslint-enable no-undef */

describe.only('temp', () => {
    beforeEach(() => {
        console.log('beforeEach');
    })

    afterEach(() => {
        console.log('afterEach');
    })

    it('temp test', (done) => {
        setTimeout(() => {
            console.log('setTimeout');
            done();
        }, 1000);
    })
})
```

In this case what I assume is that setTimeout needs to print before afterEach as my test hasn't completed until I call done() , but reverse is happening. Any idea ?

**Comment by Bamieh** [comment]
I cannot reproduce your issue,

![image](https://user-images.githubusercontent.com/6191849/43193134-debaeb08-9007-11e8-844b-93ee454eea37.png)

Can you provide more details, including the mocha options you are passing and mocha version?

**Comment by Bamieh** [comment]
@rohitsainimonotype is there a reason why you are not using a later version of mocha? mocha `3.2.0` was released in 2016, so maybe that issue does not happen anymore in later version (currently at version `5.2.0`).

I ran the following script in my terminal and I got the same results:
```bash
for n in {1..15}; do npm run just:mocha; done
```

Without actual steps to reproduce I'm afraid I cannot help you, maybe you can upgrade mocha and try again?

**Comment by rohitsainimonotype** [comment]
beforeEach
15 FAILED temp temp test
Uncaught Error: Cookie has domain set to a public suffix
    at CookieJar.setCookie (index.js:24158)
    at CookieJar.setCookieSync (index.js:24531)
    at HTMLDocument.set (index.js:26537)
    at D (heap-3412661233.js:1)
    at z (heap-3412661233.js:1)
    at Object.0 (heap-3412661233.js:1)
    at e (heap-3412661233.js:1)
    at 0 (heap-3412661233.js:1)
    at heap-3412661233.js:1
CookieJar.setCookie @ index.js:24158
(anonymous) @ index.js:24531
set @ index.js:26537
D @ heap-3412661233.js:1
z @ heap-3412661233.js:1
0 @ heap-3412661233.js:1
e @ heap-3412661233.js:1
0 @ heap-3412661233.js:1
(anonymous) @ heap-3412661233.js:1
debug.js:21 Error: Uncaught Error: Cookie has domain set to a public suffix (http://localhost:9876/base/index.js:24158)
(anonymous) @ debug.js:21
setTimeout (async)
(anonymous) @ debug.js:20
window.__karma__.result @ debug.js:23
(anonymous) @ adapter.js:172
EventEmitter.emit @ mocha.js:389
Runner.uncaught @ mocha.js:5213
uncaught @ mocha.js:5297
global.onerror @ mocha.js:64
error (async)
process.on @ mocha.js:63
Runner.run @ mocha.js:5322
Mocha.run @ mocha.js:1781
mocha.run @ mocha.js:160
(anonymous) @ adapter.js:211
karma.loaded @ chai-adapter.js:17
(anonymous) @ debug.html:51
afterEach
Skipped 0 tests
setTimeout
mocha.js:5069 Uncaught TypeError: Cannot set property 'state' of undefined
    at mocha.js:5069
    at done (mocha.js:4397)
    at mocha.js:4485
    at index.js:119738


errors I am getting in karma-chrome

**Comment by rohitsainimonotype** [comment]
It was issue of my code. So, closing it.

**Comment by Alqio** [comment]
What was the issue in your code? I might be facing a related issue, as sometimes my tests do not reach afterEach
