### ISSUE TITLE
Add JS API option equivalent too `--exit`

### ISSUE THREAD

**Issue by jacobq** [mochajs/mocha#3442]
### Prerequisites
- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

(Unchecked items are N/A)

I'd like to upgrade from Mocha 3.x to the latest, but need to work around the Mocha won't force exit behavior change in 4.0. We are launching programmatically (new Mocha({/* options */})), but I don't see an equivalent for the --exit flag. Is there one? If so, please document it (assuming I'm looking in the right place it isn't there). If not, please consider adding it (I think it would make sense to have feature parity between CLI arguments and programmatic arguments).

(accidentally filed as https://github.com/nodejs/node/issues/22005 -- doh)

**Comment by outsideris** [comment]
See #3072
