### ISSUE TITLE
Use --inspect in place of --debug, for Node version 8.11.x upwards

### ISSUE THREAD

**Issue by sunsagong** [mochajs/mocha#3443]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
```
(node:48) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.
```

I run into a problem where mocha failed to run on `node:8.11.2` in debug mode.
From Node 8.11.x upwards, `node --debug` is officially replaced with `node --inspect`.
I know that add `--inspect` flag to all `mocha` call works, but I don't think this is proper, because other `mocha` front-ends like `grunt` or `gulp` extension does not support flag injections and they should not do this.

Reopening #3436.

### Versions
```
$ node --version
v8.11.2
```

**Comment by outsideris** [comment]
So, what do you expect?

**Comment by plroebuck** [comment]
Alternatively, could **you** not just pass the _proper_ flag yourself?

Pass `--inspect` when you use Node-8.11+.
Mocha allows pass-thru Node option flags, but the mechanism isn't there to enforce their validity.

**Comment by Bamieh** [comment]
I will close this because it is not related to mocha. These issues are rising because you are passing deprecated/removed flags to node. Mocha just passes them, as @plroebuck has elaborated.

**Comment by gedion** [comment]
@plroebuck. even with your suggestion I get "Inspector support is not available with this Node.js build" as shown below. The below example is when I ssh into tessel as root. The same error happens when running using the CLI.

```bash
root@june:~/eg# node -v
v8.11.3
root@june:~/eg# cat temp.js 
debugger;
console.log('a');
root@june:~/eg# node --inspect temp.js 
Inspector support is not available with this Node.js build
node: bad option: --inspect
```

**Comment by plroebuck** [comment]
If you look [here](http://thlorenz.com/node-dox//build/node-v8.x/html/d5/d9c/node__debug__options_8cc_source.html) on lines 107-114, you will notice the compile time `HAVE_INSPECTOR` option. So if you're getting this message, it implies to me that you (or whoever) built the Node executable without all the pieces.

If "tessel" is a production UNIX server, this is probably intentional for [security reasons](https://nodejs.org/en/docs/guides/debugging-getting-started/#security-implications) -- try this on a development UNIX server, Docker container, or your local Mac/PC instead.

I haven't build Node myself, but assuming it uses GNU-based build chain, you might try running `./configure --help` _before_ `make`. Look for whatever option is related to `--inspect` support.
With any luck, it _should_ be fairly obvious.

Or just install a [prebuilt binary](https://nodejs.org/en/download/) with debugging support (simpler).

**Comment by dingxiangfei2009** [comment]
@piroebuck You missed the point. It was `mocha` passing the wrong flags to `node`. The user had no control over this behavior. The suggestion does not fix the problem anyway.

**Comment by plroebuck** [comment]
> @piroebuck You missed the point.

@dingxiangfei2009 missed what point?

> It was mocha passing the wrong flags to node. 

Mocha-5.2.x was **not** passing the wrong flags -- it was passing _whatever_ the user provided...

https://github.com/mochajs/mocha/blob/5bd33a0ba201d227159759e8ced86756595b0c54/bin/mocha#L27-L34

> The user had no control over this behavior.

Not sure where you come up with this concept as the flags came from somewhere.
All `grunt` plugins that I know of allowed passing Mocha options via their "Gruntfile" task, and the "mocha.opts" file could have been used regardless of plugin support.

> The suggestion does not fix the problem anyway.

The submitter had already acknowledged that using `--inspect` (the correct option) worked with Node-8. How could the suggestion to use the version-appropriate flag possibly be incorrect?

**Comment by dingxiangfei2009** [comment]
@plroebuck The design of the CLI flags parsing is inconsistent.

On one hand, the logic for handling `-d` flag involves translation of this flag into the `--debug` flag. It is like many other flags, such as `-gc` and any other flags not falling into the other category in the `default` branch. By the way, `-d` flag works with `8.11.x` downwards, not upwards.

On the other hand, the logic for handling `debug`, `--debug`, `--debug-brk`, `--inspect` and `--inspect-brk` does not involve translation, and the the flag is passed *as is* to `node`.

Now `mocha` has two sets of flags that are all activating the debugging mode of `node`, and some of them are working in one version of `node`, with manual choices, and others don't.

Can we reconcile this difference and give users fewer surprises?
