### ISSUE TITLE
Silence Logs in debug mode of Karma browser

### ISSUE THREAD

**Issue by chrisdel101** [mochajs/mocha#3445]
### Description
In the Karma debug console there are lines of useless output. This is traced to the module. I`d like to know how to fix this.

### Steps to Reproduce
Once Karma is running, open debug console in browser and logs appear (see image)

It seems to be this piece in moch.js. If comment out the logs, things work as expected. (line 6959 for me)
```
BrowserStdout.prototype._write = function(chunks, encoding, cb) {
  var output = chunks.toString ? chunks.toString() : chunks
  if (this.label === false) {
    console.log(output)
  } else {
    console.log(this.label+':', output)
  }
  process.nextTick(cb)
}
```

How would I deal with fixing this permanently so I don`t see these logs? I'm not sure how to do this, or if it is possible, or if this is an issue on my end how I can solve it.

![image 1](https://user-images.githubusercontent.com/14151974/43527678-2bc742a8-9575-11e8-80ae-b867c36021b7.png)

**Comment by plroebuck** [comment]
When #3477 is merged, the `stdout:` prefix will disappear from output.
But he is running the `NyanCat` reporter above which spews Terminal escape codes for a living.

@chrisdel101, does your problem improve if you specify `--reporter min` or `--reporter spec`?
Use of `--no-color` option _might_ reduce output further.

**Comment by chrisdel101** [comment]
I added the additional `NyanCat` reporter flag to try and see if it did anything, or it the reporters did anything to the output. They did not, that I could see. 
It was still giving those output logs before I added that though.

 I've commented out the line in in question in mocha.js to fix this for now, and it makes it useable.

I checked with my teammates and we have these logs happening so it's something that needs investigation here. I am closing this as I cannot provide the investigation necessary now (and apologies for not providing enough info about OS etc to begin with). Thanks!

**Comment by plroebuck** [comment]
Full Disclosure: never used Karma

From quick glance, these "karma.conf.js" configuration options might be applicable.
* `browserConsoleLogOptions`
* `client.captureConsole`
* `detached` 

Your "patch" disables all output sent to `stdout` when run in browser.

Good luck and let us know if one of these options resolves your problem (without requiring you to comment out any code).
