### ISSUE TITLE
Mock a function before the test file is run

### ISSUE THREAD

**Issue by jim-moody** [mochajs/mocha#3446]
### Prerequisites

- [x ] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

This is more of a question about testing strategy using Mocha. I need to mock a global function (localStorage), but I need that mock to happen _before_ the file is run, because localStorage is being called from within an imported module. 

But I don't know where I can put the mock, because anywhere I put it, it doesn't work because the imported module has already run and failed for an undefined variable.

Example:

```js
// module-a.js

export const state = {
  version: localStorage.getItem('version')
}
```

```js
// module-a.test.js
import { state } from './module-a.js'

describe('my test', () => {
  it('should set version = localStorage version', () => {
    global.localStorage = {
      getItem: () => '1'
    }
    expect(state.version).to.equal('1')
  })
})
```

Error: localStorage is not defined

**Comment by outsideris** [comment]
It is not mocha's responsibility. 
To use global properties like `localStorage`, you should check the existence of them first. Only in your example, you can define `global.localStorage` in the top of`module-a.test.js` or use `--require` flag of mocha.

**Comment by jim-moody** [comment]
This was helpful, thanks
