### ISSUE TITLE
Don't use eval

### ISSUE THREAD

**Issue by rugk** [mochajs/mocha#3448]
In environments, where `eval` is not allowed (i.e. [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) without `unsafe-eval`), this line below likely fails:

https://github.com/mochajs/mocha/blob/f24607e6b04d129610613592d19f5a5af9b65d51/docs/example/chai.js#L2215

So you may say, adjust your CSP, but this is no solution. Of course, I want to run my tests and confirm that the tested code e.g. does not use eval and works correctly without eval.

**Comment by Munter** [comment]
Chai is not a part of the mocha source code. It's just an example. You can choose your own assertion library that's more to your liking, or open an issue in their repository
