### ISSUE TITLE
getting "before all" hook error

### ISSUE THREAD

**Issue by fmegclark** [mochajs/mocha#3449]
Hi,
I did not change anything but, a test that was working before is all of a sudden giving me the following error in stack trace:
"before all" hook
Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
I tried everything that I could find online but nothing worked.
Thank you for your help!

**Comment by fesebuv** [comment]
It looks like you are running asynchronous code in your assertion or that the code you are trying to assert is taking longer than 10 seconds to run. 

Check out the doc for reference
https://mochajs.org/#asynchronous-code

**Comment by fmegclark** [comment]
Hi,
Thank you for responding.
I did see that and I went and increased the timeout time to 25 seconds but I am still getting the same error.

**Comment by fesebuv** [comment]
do you mind pasting the code to see what the issue may be?

**Comment by fmegclark** [comment]
Hi,
Thanks again for your attention on this.
I found out it was an issue with my proxy.
I will go ahead and close this issue.

Thanks, again!!!

**Comment by fesebuv** [comment]
Excellent, you are welcome!

**Comment by KellyAineah** [comment]
"before all" hook in "{root}"
