### ISSUE TITLE
before or beforeAll?

### ISSUE THREAD

**Issue by FengShangWuQi** [mochajs/mocha#3453]
1. **before**：test pass but eslint error.
2. **beforeAll**: test error but eslint pass.

package version:
```json
{
  "eslint-config-react-app": "^2.1.0",
  "mocha": "^5.2.0"
}
```

**Comment by outsideris** [comment]
Please provide the details.

**Comment by craigtaub** [comment]
Would `eslint-config-react-app` not expect Jest as the test runner (`create-react-app` uses it)? 
Jest has got a `beforeAll` but don't think a `before`.

**Comment by outsideris** [comment]
Mocha doesn't have `beforeAll`. So it looks like a lint problems.
Did you define `before` as global variables or use a plugin like [eslint-plugin-mocha](https://www.npmjs.com/package/eslint-plugin-mocha).

**Comment by FengShangWuQi** [comment]
thanks @outsideris , I forgot specifying environments("mocha") in ESLint config, but I still dont's understand how beforeAll can be run,  because I have saw beforeAll could pass("yarn test") in my partner's code.

**Comment by outsideris** [comment]
I can't say about your partner's case without I see the code. Anyway, is your problem solved? If so, I want to close the issue.

**Comment by FengShangWuQi** [comment]
OK.
