### ISSUE TITLE
Charts tool to be used with Mocha

### ISSUE THREAD

**Issue by noopole** [mochajs/mocha#3454]
Are there any chart tools that can be used with Mocha to display Mocha test results delay?

I would like to create a dashboad that will display mocha test results (run for example every 5 minutes) in the form of a timeline:
- x coodinate would be the time
- y coordinate would be the response time

I've tried to find such a tool via common search engines but couldn't find interesting answers.

The goal is to monitor a website responsiveness with scenario developed with Mocha.

Can you suggest some tools?

**Comment by Munter** [comment]
Mocha isn't really a tool designed to measure website responsiveness. Why don't you use a tool that's better suited for that?

**Comment by noopole** [comment]
Because I know how to use Mocha and how to develop tests in Mocha (with Selenimu-Webdriver to test it with a browser). I like the results (response time) it delivers.

And because I don't know any good tool suited for that. Maybe you can suggest me one ? I would like to develop the scenarios with Javascript and if possible run with nodejs.

**Comment by noopole** [comment]
Thank you for pupetter I didn't know this solution :+1: 
However I'll always need to provide a visual representation of the results variation in the course of time

**Comment by Bamieh** [comment]
I will close this as it is not directly related to mocha per se. Please re-open if you feel otherwise.
