### ISSUE TITLE
how to use stackTraceFilter() ?

### ISSUE THREAD

**Issue by divramod** [mochajs/mocha#3456]
Is there an example on how to use the stackTraceFilter function?
I just can't find out, how to configure it.

I wrote a question on stackoverflow for it: https://stackoverflow.com/questions/51853184/mocha-how-to-use-utils-function-stacktracefilter

i try to use the mocha utils [stackTraceFilter()](https://mochajs.org/api/module-utils.html#.stackTraceFilter) function

but i cannot find an example usage case where someone explains how to use it in ones test. I found the official tests here: [link](https://github.com/mochajs/mocha/blob/668b541090c84b66a701823b30f6880d3fc0f2b9/test/node-unit/stack-trace-filter.spec.js)

But how can i implement it in my tests, which somehow look like that:

    import { expect } from 'chai'
    import 'mocha'
    
    import { main, main2 } from './'
    
    describe.only('index.ts', async () => {
    
        it('should start a job', async () => {
            // const R_RUN_MAIN = await main()
    
            await main2()
            // TEST
            expect(1).to.equal(1) // fails
    
        })
    
    })

In the tests i can see the line

    expect(filter(stack.join('\n')), 'to be', stack.slice(0, 3).join('\n'));

But how do i get the Stack for my test?

    expect(1).to.equal(1) // fails

or in general, how do i get the stack and initialize the filter function for the whole file when, for example, code from an imported file is already failing and creating a long stack trace?

**Comment by outsideris** [comment]
The API document is mocha's programmable API. Therefore, you should use [mocha programmatically](https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically). 

```js
const Mocha = require('mocha')

const filter = Mocha.utils.stackTraceFilter()

const err = new Error();

const output = filter(err.stack)
```

**Comment by divramod** [comment]
thx. is there somewhere an example on how to use mocha programatically, which includes a describe block? i somehow dont know where to start.

**Comment by divramod** [comment]
so i got mocha running in a programmatic way:

```
export {}
import * as MOCHA from 'mocha'

async function run() {
    const mocha = new MOCHA({
        reporter: 'progress',
        reporterOptions: {
            verbose: true,
        },
    })
    mocha.addFile(`./src/utils/mocha/index.spec.ts`)
    const R = mocha.run((failures) => {
        process.on('exit', () => {
            process.exit(failures)
        })
    })

}

run()
```

I dont know where to add and run the Filter function?

 ```const filter =  MOCHA.utils.stackTraceFilter```

**Comment by plroebuck** [comment]
If you're doing this in order to debug async tests that are not completing, take a look at [how to debug Mocha v4 if hanging](https://gist.github.com/boneskull/7fe75b63d613fa940db7ec990a5f5843).

**Comment by outsideris** [comment]
Why do you want to use `stackTraceFilter`?

**Comment by plroebuck** [comment]
@divramod, did you get this resolved? Can we close this issue?
