### ISSUE TITLE
Mocha killed

### ISSUE THREAD

**Issue by toien44** [mochajs/mocha#3460]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

After deleting node_modules and re-installing mocha breaks and is killed every time it's run.

### Steps to Reproduce

When I use the command node_modules/mocha/bin/mocha I get the output 
```
[1]    22568 killed     node_modules/mocha/bin/mocha
or 
killed: 9
```

**Expected behavior:** Start mocha command and start test

**Actual behavior:** mocha is killed and ends the test
**Reproduces how often:** 100%

### Versions
- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 5.0.5 but also updated to 5.2.0
- The output of `node --version`: 8.11.0
- The version and architecture of your operating system:
- Your shell (bash, zsh, PowerShell, cmd, etc.): zsh
- Your browser and version (if running browser tests): chrome 65 (latest)
- Any other third party Mocha related modules (with versions):
- The code transpiler being used: babel

### Additional Information

The issue was removed when downgraded to mocha 4.0.1

**Comment by plroebuck** [comment]
Two thoughts you may want to try... Neither fixes your issue, but may provide some clues.
```bash
$ NODE_DEBUG='*' node_modules/mocha/bin/mocha script.js
```

```bash
$ strace node_modules/mocha/bin/mocha script.js
```

**Comment by plroebuck** [comment]
Uh, "script.js" was to be _your_ Mocha test file, not the literal string.

Simple enough. Install the package first.
You didn't specify your OS above, so assuming CentOS/RedHat:
```bash
# yum install strace
```

**Comment by plroebuck** [comment]
@toien44, did you figure out the cause?

Can this issue be closed?

**Comment by Bamieh** [comment]
@toien44 @plroebuck I will close the issue, feel free to re-open if you need further assistant.
