### ISSUE TITLE
Advice to a sibling repository: how do you manage this repo?

### ISSUE THREAD

**Issue by goldbergyoni** [mochajs/mocha#3462]
### Prerequisites

- [X ] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ X] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ X] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ ]X Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
Hey,

Looking for a friendly advice: [our repo here](https://github.com/i0natan/nodebestpractices) just grew a little bit and we look for tools/tips about how to manage many PRs, permissions, and sub-repos. Do you use any other tool that GitHub for management? what type of GH account do you use (considering that developer account has limited permissions settings and team account has significant costs)?

Thanks!

Best,
Yoni

**Comment by Bamieh** [comment]
I'm not sure I completely follow the question.
1. We have an organization with private repos.
2. Check any PR to see how we handle our CI. We use travis, coveralls, AppVeyor and some other tools.

I wish you can specify a more detailed question so we can give you a detailed answer.
