### ISSUE TITLE
Use of JSON export encourages Webstorm/IntelliJ to suggest it when the JSON (js) class is used.

### ISSUE THREAD

**Issue by francisu** [mochajs/mocha#3463]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

Export of 'JSON' in reporter/index.js causes Webstorm/IntelliJ to constantly suggest this as an import with an annoying popup. JSON comes with Javascript, so I think it's inappropriate to export this. I verified with JetBrains support that this export is what's causing this issue, and I think the IntelliJ is doing the right thing by suggesting this.

<img width="685" alt="screenshot 2018-08-19 15 57 11" src="https://user-images.githubusercontent.com/944949/44314060-c34a1900-a3c8-11e8-845e-ec85ddac34a7.png">

### Steps to Reproduce

Simply install Mocha and use something like JSON.stringify in your code. Use IntelliJ/WebStorm and click on the JSON (the popup is suggested all the time even when you don't click on it and it's pretty annoying as it's over code you may want to look at).

### Versions

Mocha 5.2.0

### Additional Information

This should be very easy to fix, by renaming the json reporter module (not the reporter itself). However, I'm not sure if this will break the API or means of importing the JSON reporter.

**Comment by francisu** [comment]
I would be happy to submit a PR for this if it's likely to be accepted.

**Comment by Bamieh** [comment]
@francisu is there another way to fix this without renaming the export? renaming the reporter is a breaking change that I do not think is worth doing

**Comment by francisu** [comment]
I think this is more of an IntelliJ problem: https://youtrack.jetbrains.com/issue/WEB-34452
So it's probably best to not consider this one. Thanks for looking at it!
