### ISSUE TITLE
can Mocha.run() by add code, not by addFile before?

### ISSUE THREAD

**Issue by peng2018** [mochajs/mocha#3468]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?
### Description

I hope that mocha could run the code for testing immediately, not by addFill before.

because our web can help users edit online code， it only save the code for testing.
now the only way the users could run testing code online is that we build testing files from the code, and addFile , run file with Mocha.

so, is there a  immediate way to run the code for testing with Mocha? thx

**Comment by plroebuck** [comment]
Cannot understand what you're asking here. You can run Mocha by CLI or programmatically. You have to write your _own_ tests. Once those exist, maybe use temp files for Mocha invocation.

**Comment by peng2018** [comment]
ok, thx.
i got it.  I want to run Mocha by Progrommatically.
