### ISSUE TITLE
Documentation missing "describe" and "it" imports

### ISSUE THREAD

**Issue by ericmorand** [mochajs/mocha#3470]
I'm currently reading the "Get started" documentation here:

https://mochajs.org/#getting-started

And here is the first example:

```
var assert = require('assert');
describe('Array', function() {
  describe('#indexOf()', function() {
    it('should return -1 when the value is not present', function() {
      assert.equal([1,2,3].indexOf(4), -1);
    });
  });
});
```

This code won't compile because `describe` and `it` are never imported. I can't even find where thery are supposed to be imported from. Is it from the mocha package itself?

Anyway, the documentation needs to be updated in this regards. Newcomers can't use mocha by relying solely on the official documentation.

**Comment by Bamieh** [comment]
You need to run the code through mocha, not by running `node my-test.js`
If you keep on reading the next code block in the documentation you'll figure it out.

> Back in the terminal:
> 
> $ ./node_modules/mocha/bin/mocha

Im going to close this as resolved, if you have further questions feel free to re-open.

**Comment by ericmorand** [comment]
Oh, that means that `describe` and `it` are only available as globals through mocha runtime?

Doesn't it make impossible to write tests in TypeScript? They would never compile.

**Comment by Bamieh** [comment]
@ericmorand You can run mocha with typescript through requiring `ts-node/register` in mocha's configurations (`cli` or `mocha.opts` file), I believe there are plenty of resources in the wild about this topic, you can also [chat with us on gitter](https://gitter.im/mochajs/mocha).
