### ISSUE TITLE
utils.canonicalize runs out of memory

### ISSUE THREAD

**Issue by marneborn** [mochajs/mocha#3472]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
We are using sequelize. Each instance a bunch of "private" data.
Because of the many associations that we have, this sequelize internal  structure is very wide and deep.
Running utils.canonicalize on these instances hangs the machine eventually running out of memory.

### Steps to Reproduce
To see the hang takes an example that is too big to create easily.
In lieu of that, in this simple/small example canonicalize takes ~275ms visiting  221,980 nodes in the tree with a max depth of 26.
In real usage I have had node crash after a long time and the terminal taking upwards of 20GB of memory.

```
const Promise = require('bluebird');
const Sequelize = require('sequelize');
const { canonicalize } = require('mocha/lib/utils');

const sequelize = new Sequelize(process.env.POSTGRES_CONNECT_URI, {
  dialect: 'postgres',
  logging: false,
  pool: { max: 10, min: 0, idle: 10000 },
});

const options = {
  schema: 'public',
  timestamps: false,
  underscored: true,
  paranoid: false,
};

const Parent = sequelize.define(
  'Parent',
  {
    id: {
      type: Sequelize.UUID,
      primaryKey: true,
      defaultValue: Sequelize.UUIDV4,
    },
    title: {
      type: Sequelize.STRING,
      allowNull: false,
    },
  },
  {
    ...options,
    tableName: 'parents'
  }
);

const Thing = sequelize.define(
  'Thing',
  {
    value: {
      type: Sequelize.STRING,
    },
    parent_id: {
      type: Sequelize.UUID,
      references: {
        model: 'parents',
        key: 'id',
      },
    },
  },
  {
    ...options,
    tableName: 'things'
  }
);

Thing.belongsTo(Parent, {  as: 'Parent',  foreignKey: 'parent_id' });
Parent.hasMany(Thing, { as: 'things', foreignKey: 'parent_id' });

Promise.resolve()
  .then(() => Parent.sync({ force: true }))
  .then(() => Thing.sync({ force: true }))
  .then(() => Parent.create({ title: 'stuff' }))
  .then(parent => Thing.create({ value: 'hi!', parent_id: parent.id }))
  .then(() => Thing.findOne({ include: { model: Parent, as: 'Parent' }}))
  .then(thing => {
    const start = Date.now();
    const canonicalized = canonicalize(thing)
    console.log(`Took: ${Date.now() - start}`);
  })
  .catch(err => console.log(`-E- ${err.stack || err}`))
  .finally(process.exit);
```

**Expected behavior:** [What you expect to happen]
To canonicalize the instance quickly, ideally ignoring all "private" properties.

**Actual behavior:** [What actually happens]
Machine hangs, node eventually runs out of memory and dumps.
On simple models that do complete "private" properties are logged in the error reporting making it hard to see what is failing.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
5.2.0 (was on 3.2.0, but upgraded before submitting issue).

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
5.2.0 for both
- The output of `node --version`:
v8.11.3
- The version and architecture of your operating system:
macOS 10.13.6 (also hangs on CircleCI/ubuntu)
- Your shell (bash, zsh, PowerShell, cmd, etc.):
bash(dash on circle)
- Your browser and version (if running browser tests):
N/A
- Any other third party Mocha related modules (with versions):
"chai": "^4.0.2",
"chai-shallow-deep-equal": "^1.4.6",
- The code transpiler being used:
N/A

### Additional Information

Maybe something like:
```
    case 'object':
      if (typeof value.toCanonicalized === 'function') {
        canonicalizedObj = value.toCanonicalized(value);
      } else {
        canonicalizedObj = canonicalizedObj || {};
        withStack(value, function() {
          Object.keys(value)
            .sort()
            .forEach(function(key) {
              canonicalizedObj[key] = exports.canonicalize(value[key], stack);
            });
        });
      }
      break;
```

**Comment by Bamieh** [comment]
Can you explain what do you mean by "private"? also where did you get the `toCanonicalized` method?

**Comment by marneborn** [comment]
What I mean by "private" is a property that would be private in a class if javascript supported private variables. Ie a property that is intended only for internal use.

What I would like is a way of defining how an instance of a class is canonicalized.
One solution would be to add a `toCanonicalized` method, in test, to all of our sequelize Instance classes. This is a method I would define and utils.canonicalize would use, instead of `Object.keys(value).sort().forEach()`.

Another option is to let me override how the keys are picked. So instead of `Object.keys(value)` have `exports.keys(value)`. I could then `require('mocha/lib/utils').keys = myFunctionToGetKeys;`

It would be nice if canonicalized timed out at some point too. But that's a bit of a mess.

To be a little more specific about my problem.
This is what canonicalize returns for my `thing` in the example above (this object is 696k lines with out collapsing the "{SOME VERY BIG OBJECT}"s).

```
{
  "$modelOptions": "{SOME VERY BIG OBJECT}",
  "$options": "{SOME VERY BIG OBJECT}",
  "Parent": {
    "$modelOptions": "{SOME VERY BIG OBJECT}",
    "$options": "{SOME VERY BIG OBJECT}",
    "__eagerlyLoadedAssociations": [],
    "_changed": {},
    "_previousDataValues": {
      "id": "ac6c236e-1edc-4bf8-91e8-6e1edfefd1ce",
      "title": "stuff"
    },
    "dataValues": {
      "id": "ac6c236e-1edc-4bf8-91e8-6e1edfefd1ce",
      "title": "stuff"
    },
    "hasPrimaryKeys": true,
    "isNewRecord": false
  },
  "__eagerlyLoadedAssociations": [],
  "_changed": {},
  "_previousDataValues": {
    "Parent": {
      "$modelOptions": "{SOME VERY BIG OBJECT}",
      "$options": "{SOME VERY BIG OBJECT}",
      "__eagerlyLoadedAssociations": [],
      "_changed": {},
      "_previousDataValues": {
        "id": "ac6c236e-1edc-4bf8-91e8-6e1edfefd1ce",
        "title": "stuff"
      },
      "dataValues": {
        "id": "ac6c236e-1edc-4bf8-91e8-6e1edfefd1ce",
        "title": "stuff"
      },
      "hasPrimaryKeys": true,
      "isNewRecord": false
    },
    "id": 1,
    "parent_id": "ac6c236e-1edc-4bf8-91e8-6e1edfefd1ce",
    "value": "hi!"
  },
  "dataValues": {
    "Parent": {
      "$modelOptions": "{SOME VERY BIG OBJECT}",
      "$options": "{SOME VERY BIG OBJECT}",
      "__eagerlyLoadedAssociations": [],
      "_changed": {},
      "_previousDataValues": {
        "id": "ac6c236e-1edc-4bf8-91e8-6e1edfefd1ce",
        "title": "stuff"
      },
      "dataValues": {
        "id": "ac6c236e-1edc-4bf8-91e8-6e1edfefd1ce",
        "title": "stuff"
      },
      "hasPrimaryKeys": true,
      "isNewRecord": false
    },
    "id": 1,
    "parent_id": "ac6c236e-1edc-4bf8-91e8-6e1edfefd1ce",
    "value": "hi!"
  },
  "hasPrimaryKeys": true,
  "isNewRecord": false
}
```

What I would like it to return is:
```
{
  "id": 1,
  "parent_id": "ac6c236e-1edc-4bf8-91e8-6e1edfefd1ce",
  "value": "hi!"
  "Parent": {
    "id": "ac6c236e-1edc-4bf8-91e8-6e1edfefd1ce",
    "title": "stuff"
  }
}
```

This is so that some thing like this gives a useful error message on an error.
```
    const foundThing = await findThing(this.thing.id);
    expect(foundThing).to.shallowDeepEqual({
      id: this.thing.id,
      Parent: { id: this.parent.id },
    });
```

**Comment by Munter** [comment]
Your example code shows direct use of mocha internals, which are not real a part of the public API. Was this deliberate to highlight which part of mocha shows a problem in done real world test use case, or are you really using internal mocha utilities for things they were obviously not designed for?

I don't think it's mocha's core functionality to make objects canonical, so unless this impacts real tests is like to close this and defer you to done other npm library that actually is designed for this use case

**Comment by marneborn** [comment]
We don't use internals in, this was "deliberate to highlight which part of mocha shows a problem".

If I do ```
    const foundThing = await findThing(this.thing.id);
    expect(foundThing).to.shallowDeepEqual({
      id: this.thing.id,
      Parent: { id: this.parent.id },
    });
``` 
And the expect throws the spec reporter (and dot, haven't tested others) hang.
This hang is in canonicalize <- stringifyDiffObjs <- Base.list <- Base.epilgue <- runner.once('end'

So it's the reporters that are broken for me, the solution seems to be in utils.canonicalize.

**Comment by Munter** [comment]
Yeah, diffing large objects is quite an intensive task, especially if there is to be syntax highlighting as well.

Would it be possible to create a pr with the offending piece of data and a failing test? Maybe with a ci skip, do we don't need to much with Travis along the way. That would give us a way to recreate the setup and work on the problem.

For now I'd probably work around it if I was you. Maybe destructure the relevant properties out of the main subject before doing the partial deep equality, out maybe by trying require('unexpected')(subject, 'to satisfy', {...}) Because it uses a different engine for creating the diffs

**Comment by plroebuck** [comment]
Curious if [proxyquire](https://github.com/thlorenz/proxyquire) could be used to "monkey patch" Mocha with your desired behavior.

**Comment by ddolcimascolo** [comment]
Hey guys,

Sorry for resurrecting an old thread, but this is indeed still present and can be triggered with any chai assertion on a sequelize Model instance. Sequelize Models are circulars, but I don't know the exact reason...

Anyway, for those using mocha, chai and sequelize, I've written this small chai plugin that you should load last:

```javascript
/**
 * Intercepts all calls to chai.Assertion.assert to sequelize models, or arrays of models
 * Avoids Mocha issue https://github.com/mochajs/mocha/issues/3472
 */
chai.use((_chai) => {
  const { assert } = _chai.Assertion.prototype; // Original Assertion.assert function

  function extractSequelizeValues(val) {
    if (Array.isArray(val)) {
      return val.map(extractSequelizeValues);
    }

    if (val instanceof Model) {
      return val.get({ plain: true });
    }

    return val;
  }

  // eslint-disable-next-line no-param-reassign
  _chai.Assertion.prototype.assert = function(expr, msg, negateMsg, expected, _actual, showDiff) {
    return assert.call(this, expr, msg, negateMsg, expected, extractSequelizeValues(_actual), showDiff);
  };
});
```

As an added benefit, this also prevents hangs in Webstorm for the exact same issue.

@Munter Are you still interested in minimal reproduction steps? If so, that should be easy to do in a fresh projects with sequelize, mocha and chai. I can set this up in a repo if that's worth it.

Regards,
David

**Comment by dvtate** [comment]
```
Starting build process...
Process started
Browserslist: caniuse-lite is outdated. Please run the following command: `npm update`
Process finished with exit code 0
------------------------
Starting run process...
Process started
Running 3 tests...
westatix.editor.test:
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
... 1/3: ModelTest.constructor() [2.610 s]
... 2/3: ModelTest.structure() [2.216 s]
... 3/3: ModelTest.results() [26.527 s]
FAILURE: should have "getter" and "setter" ------------

<--- Last few GCs --->

[134:0x336a2a0]    49712 ms: Mark-sweep 2044.6 (2056.1) -> 2043.8 (2048.6) MB, 70.9 / 0.0 ms  (+ 285.8 ms in 39 steps since start of marking, biggest step 21.8 ms, walltime since start of marking 378 ms) (average mu = 0.124, current mu = 0.092) finalize i[134:0x336a2a0]    49730 ms: Scavenge 2045.7 (2048.6) -> 2044.3 (2061.1) MB, 7.5 / 0.0 ms  (average mu = 0.124, current mu = 0.092) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x13cce79]
Security context: 0x11d8618c08d1 <JSObject>
    1: escapeFn(aka escapeFn) [0x3785ecd0bf31] [internal/util/inspect.js:~410] [pc=0x284d3143425e](this=0x34425e5c04b1 <undefined>,0x11d8618f3aa9 <String[#1]: \>)
    2: StubFrame [pc: 0x14094bc]
    3: replace [0x11d8618ccc71](this=0x2da965861a59 <Very long string[16313]>,0x3785ecd0bc91 <JSRegExp <String[#19]: [\x00-\x1f\x27\x5c]>>,0x3785ecd0bf31 <JSFunction esc...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa0bb60 node::Abort() [/usr/bin/node_orig]
 2: 0xa0bf6c node::OnFatalError(char const*, char const*) [/usr/bin/node_orig]
 3: 0xb820fe v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node_orig]
 4: 0xb82479 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node_orig]
 5: 0xd2ee35  [/usr/bin/node_orig]
 6: 0xd2f4c6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/bin/node_orig]
 7: 0xd3bd45 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/bin/node_orig]
 8: 0xd3cbf5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node_orig]
 9: 0xd3e29f v8::internal::Heap::HandleGCRequest() [/usr/bin/node_orig]
10: 0xcecd85 v8::internal::StackGuard::HandleInterrupts() [/usr/bin/node_orig]
11: 0x1047a46 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node_orig]
12: 0x13cce79  [/usr/bin/node_orig]
Run 3 tests in 58.685 s.
Process finished with exit code 0
```
