### ISSUE TITLE
Can not transpile Coffescript when running mocha command

### ISSUE THREAD

**Issue by elisei-timofte** [mochajs/mocha#3474]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

I try to run Mocha with a CoffeeScript compiler and I get `Unexpected token import`.
Below is my command which I'm trying to run:
`node_modules/mocha/bin/mocha --require coffeescript/register app/server/lib/server_tests/*.test.coffee --reporter mochawesome
`

Here is the error stack trace 
````
import should from 'should';
^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Object.loadFile (/Users/timofte/Documents/work/projects/sonar/node_modules/coffeescript/lib/coffeescript/register.js:18:19)
    at Module.load (/Users/timofte/Documents/work/projects/sonar/node_modules/coffeescript/lib/coffeescript/register.js:53:36)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at /Users/timofte/Documents/work/projects/sonar/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>:null:null)
    at Mocha.loadFiles (/Users/timofte/Documents/work/projects/sonar/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/timofte/Documents/work/projects/sonar/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/timofte/Documents/work/projects/sonar/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3

````
It works if I change that line to `should = require 'should'`

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 5.2.0
- The output of `node --version`:v9.8.0
- The version and architecture of your operating system: MacOS 10.13
- Your shell (bash, zsh, PowerShell, cmd, etc.): Terminal
- Your browser and version (if running browser tests): Google Chrome Version 68.0.3440.106
- Any other third party Mocha related modules (with versions):     mochawesome - v3.0.3
- The code transpiler being used: coffeescript - v2.3.1

**Comment by plroebuck** [comment]
About halfway down the stack ("mocha.js:250"), Mocha attempts to load your "require'd" coffeescript registration - it blows up during that processing.

My current CoffeeScript experience is with v1.12.7, where my code uses the style documented [here](https://coffeescript.org/#nodejs-usage) (i.e., like your "It works if I" code). Think your `import should from 'should';` is **invalid CoffeeScript** which is why it implodes.

**Comment by elisei-timofte** [comment]
CoffeeScript 2 supports import. I use that code in other places in my meteor app and it works. If I run these tests from meteor with mocha it works just fine. 

My problem came when I've tried to use mochawesome as a reporter and I have to run mocha command for that.

**Comment by plroebuck** [comment]
So does it work with the "spec" reporter?

**Comment by elisei-timofte** [comment]
Mocha works in Meteor environment, but only with the terminal reporter, with this command: `"TEST_WATCH=1 meteor test --port 3100 --driver-package meteortesting:mocha",`

The web one is an empty page as follows:

![screen shot 2018-09-06 at 16 35 52](https://user-images.githubusercontent.com/6162068/45160931-57064c80-b1f3-11e8-842d-2ba65e8a6657.png)


That's why I'm tying to add a custom reporter, running mocha command as described in the issue.

**Comment by plroebuck** [comment]
Assuming what you're calling the terminal reporter is the same as "spec" reporter. What happens when you use the "html" reporter then?

**Comment by elisei-timofte** [comment]
If I run `node_modules/mocha/bin/mocha --require coffeescript/register app/server/lib/server_tests/*.test.coffee --reporter html`, I get the same error.

I meteor I'm not able to pass any mocha arguments to my `meteor test` command.

I'm not sure if this helps. 

Thanks for your time and patience.

**Comment by Bamieh** [comment]
@elisei-timofte Do you have any updates regarding this?

I do not think this is a mocha issue, rather than how you are configuring coffee script to run through mocha.

**Comment by elisei-timofte** [comment]
Hi, I don't have any updates on this yet. 

It could be just a CoffeeScript issue. I'll have to investigate more when I got some time. 

Thanks for your help. If I'll find a solution I'll post it here, maybe it will help others.
