### ISSUE TITLE
Travis job spawn errors in tests

### ISSUE THREAD

**Issue by plroebuck** [mochajs/mocha#3483]
### Description

Two Growl-related spawn errors occur in Travis jobs [example](https://travis-ci.org/mochajs/mocha/jobs/429915846#L1081), but they don't cause jobs to fail.

#### Affected tests
* `test.node.jsapi`
   * after `timeouts` suite
* `test.node.unit`
    * after `stackTraceFilter()` suite

#### Sample job output
```console
An error occured. { Error: spawn notify-send ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn notify-send',
  path: 'notify-send',
  spawnargs:
   [ '-i',
     '/home/travis/build/mochajs/mocha/assets/growl/ok.png',
     '--hint=int:transient:1',
     'Passed',
     '280 tests passed in 1497ms' ] }
```

### Solution
These can be squelched on Ubuntu by installing [libnotify-bin](https://launchpad.net/ubuntu/trusty/+package/libnotify-bin) in "[.travis.yml](https://github.com/mochajs/mocha/blob/master/.travis.yml)".

```sh
addons:
  apt:
    packages:
    - libnotify-bin
```

**Comment by outsideris** [comment]
I agreed with libnotify-bin solve the error.

We need growl notification in CI? And why ddid [only unit tests enable](https://github.com/mochajs/mocha/blob/master/package-scripts.js#L94) `growl`?

**Comment by plroebuck** [comment]
Did you try the solution? Still haven't had the chance myself. But if it eliminates the errors in TravisCI runs, it's an easy LGTM'd win.

As far as what activates Growl in our unit tests, I hadn't had a chance to investigate further.
Part of the problem (for remote testing anyway) is that desktop notification doesn't make sense
if you don't have a desktop to begin with. Even if we install the required binaries, they quite
possibly won't work (on Linux, it often requires `dbus` notification daemon to be running
which is not the case on container VMs). But at least we (should) get a different error...

**Comment by outsideris** [comment]
I didn't, but [growl's README](https://github.com/tj/node-growl#ubuntu-linux), which is mocha used says install libnotify-bin.

**Comment by plroebuck** [comment]
Verified that output is squelched after installation of ```libnotify-bin```.
See [here](https://travis-ci.org/plroebuck/mocha/jobs/441521875).

**Comment by plroebuck** [comment]
@alanstevens, could you be talked into fixing your [Growl Chocolatey package](https://chocolatey.org/packages/Growl) so we can get Mocha working correctly for AppVeyor?

**Comment by plroebuck** [comment]
@Iristyle, could you be talked into fixing the [Growl Chocolatey package](https://chocolatey.org/packages/Growl) so we can get Mocha working correctly for AppVeyor?
