### ISSUE TITLE
Mocha does not catch crash in native extension

### ISSUE THREAD

**Issue by pronebird** [mochajs/mocha#3490]
### Prerequisites

- [ ] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

Hi,

I am running tests with electron-mocha which runs mocha behind the scenes AFAIK.

That's the output from CI:

```
> electron-mocha
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/travis/build/pronebird/NSEventMonitor/node_modules/robotjs/build/Release/robotjs.node
  Expected in: flat namespace
dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/travis/build/pronebird/NSEventMonitor/node_modules/robotjs/build/Release/robotjs.node
  Expected in: flat namespace
The command "npm run test" exited with 0.
Skipping a deployment with the releases provider because this is not a tagged commit
```

So kinda "no pasa nada" even though the node process got wrecked. Is there any way to catch those kinds of errors in Node.js?

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]

Return non-zero exit code

**Actual behavior:** [What actually happens]

Presumably mocha exits with zero code

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: n/a | 5.2.0
- The output of `node --version`: v10.2.1
- The version and architecture of your operating system: macOS on Travis CI
- Your shell (bash, zsh, PowerShell, cmd, etc.):
- Your browser and version (if running browser tests):
- Any other third party Mocha related modules (with versions):
- The code transpiler being used:

**Comment by plroebuck** [comment]
You're running someone else's code, not ours -- file your bug report [here](https://github.com/jprichardson/electron-mocha/issues).

**Comment by pronebird** [comment]
@inukshuk you think it’s electron-mocha issue? 🤔
