### ISSUE TITLE
adding timestamp in multiple describe prints sametime 

### ISSUE THREAD

**Issue by alnvny** [mochajs/mocha#3520]
file auth.js
var now = new Date();
describe('AUTH test set: ' + now.toUTCString(), () => {
//has test cases which will run for atleast 2 mins
}

file info.js
var now = new Date();
describe('INFO test set: ' + now.toUTCString(), () => {
//has test cases which will run for atleast 2 mins
}

I run the code using the below command,
mocha test/auth.spec.js test/info.spec.js

when I see the console I am seeing the results as below
AUTH test set: **Wed, 17 Oct 2018 07:13:10 GMT**
INFO test set: **Wed, 17 Oct 2018 07:13:10 GMT**

Why are the time stamps are same in AUTH test set and INFO test set?

**Comment by outsideris** [comment]
Why do you think they should be different?

**Comment by plroebuck** [comment]
Spec files from cmdline are loaded via `require`. This occurs _quickly_. If you change your `describe` titles to `Date.now()`, you might see an msec difference between the two files. As such, your `describe` title timestamps represent load time, not run time.

**Comment by plroebuck** [comment]
Question answered? Can we close this?

**Comment by plroebuck** [comment]
See also #3523.

**Comment by alnvny** [comment]
Thanks a lot. This answered my question
