### ISSUE TITLE
Inconsistent event output in browser with json-stream reporter

### ISSUE THREAD

**Issue by rla** [mochajs/mocha#3521]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

There is inconsistent output in browser with json-stream reporter. The start/pass/fail events are printed to stdout as JSON messages but the end event has string 'stdout' prepended to it. I believe that such inconsistency is not necessary.

The inconsistency comes from this line: https://github.com/mochajs/mocha/blob/01171b1e7acec133363b50d5baacc9719af6bf1d/lib/reporters/json-stream.js#L50

The end event uses `process.stdout.write` instead of `console.log` to print its output. `browser-entry` module uses the package `browser-stdout` which optionally prepends a label to console messages. In this case it prepends 'stdout:'.

### Steps to Reproduce

1. Configure Mocha to use json-stream reported in the browser.
2. Run a trivial test case in browser.
3. Inspect console output using the page debugger.

**Expected behavior:** [What you expect to happen]

Events are printed to console as JSON messages.

**Actual behavior:** [What actually happens]

All events except the end event is printed as JSON messages.

**Reproduces how often:** [What percentage of the time does it reproduce?]

All the time.

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:

```
mocha --version
bash: mocha: command not found

node node_modules/.bin/mocha --version
5.2.0
```

- The output of `node --version`:

```
node --version
v10.5.0
```

- The version and architecture of your operating system: Debian Stretch amd64
- Your shell (bash, zsh, PowerShell, cmd, etc.): bash
- Your browser and version (if running browser tests): Puppeteer 1.9.0, Chromium 594312, Chrome 67.0.3396.99
- Any other third party Mocha related modules (with versions): none
- The code transpiler being used: none

**Comment by rla** [comment]
Comes out that there is a PR that is supposed to fix it yet this issue seems to not be filed before: <https://github.com/mochajs/mocha/pull/3477>

**Comment by rla** [comment]
Looks like it was filed before in #2095 but the proposed fix there did not completely fix the issue.

**Comment by plroebuck** [comment]
Well, thanks for filing this -- you pointed us to a test case! Had delayed pushing #3477 forward without knowing what (if anything) depended on the current behavior. Yes, standardizing the output stream is _high_ on the list as well; but that would not be until the next **major** release at best.

**Comment by plroebuck** [comment]
My _first_ "Mocha in the browser" test!

### Files:
"auth.spec.js"
```js
function logCurrTime() {
  console.log((new Date()).toUTCString());
}

describe('AUTH test set: ' + Date.now(), () => {
  it('first', () => { logCurrTime() });
  it('waits two seconds', function(done) {
    let delay = 2000;
    this.timeout(delay + 100);
    setTimeout(() => {
      logCurrTime();
      done();
    }, delay);
   });
});
```
"browsertest.html"
```html
<html>
<head>
  <meta charset="utf-8">
  <title>Mocha Tests</title>
  <link href="https://unpkg.com/mocha@5.2.0/mocha.css" rel="stylesheet" />
</head>
<body>
  <div id="mocha"></div>

  <script src="https://unpkg.com/chai/chai.js"></script>
  <script src="https://unpkg.com/mocha@5.2.0/mocha.js"></script>
  <script>
    mocha.setup({
      ui: 'bdd',
      reporter: 'json-stream'
    });
  </script>
  <script src="auth.spec.js"></script>
  <script>
    mocha.run();
  </script>
</body>
</html>
```

### Steps:
* Loaded HTML file into browser window
   * Expect no visible output on webpage _ever_.
* Open browser console
   * Cleared (press trashcan icon in console on Firefox)
* Reload current page

### Results:
```console
["start",{"total":2}] mocha.js:2919:5
Sat, 20 Oct 2018 06:20:59 GMT auth.spec.js:2:3
["pass",{"title":"first","fullTitle":"AUTH test set: 1540016459876 first","duration":0,"currentRetry":0}] mocha.js:2923:5
Sat, 20 Oct 2018 06:21:01 GMT auth.spec.js:2:3
["pass",{"title":"waits two seconds","fullTitle":"AUTH test set: 1540016459876 waits two seconds","duration":2001,"currentRetry":0}] mocha.js:2923:5
stdout: ["end",{"suites":1,"tests":2,"passes":2,"pending":0,"failures":0,"start":"2018-10-20T06:20:59.879Z","end":"2018-10-20T06:21:01.884Z","duration":2005}] mocha.js:6964:5 
```
**Note the last line starts with `stdout: `.**

### Reccomendations
1. We now have the steps to verify our pending fix for `browser-stdout`.
If we merge #3477, it will close this issue.
1. JSONStream reporter should not be writing to different streams (though end result _should_ have been the same). Fix this in a "[Don't cross the streams](https://www.youtube.com/watch?v=wyKQe_i9yyo)" issue at later time.

**Comment by outsideris** [comment]
close by #3477
