### ISSUE TITLE
Error format is different depending on message content

### ISSUE THREAD

**Issue by l1bbcsg** [mochajs/mocha#3531]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

The presence of colon (`:`) symbol in Error reported by assertion engine along with `showDiff` set to `true` and fields `expected` and `actual` present alters the format of error in default reporter.

### Steps to Reproduce

Sample test (`sample.js`):

```js
class TestError extends Error {
	constructor(message) {
		super(message + ': expected something else');
		this.showDiff = true;
		this.actual = null;
		this.expected = null;
	}
}

it('Should print message without a colon', () => { 
	throw new TestError('message without a colon'); 
});

it('Should print message with a colon(:)', () => {
	throw new TestError('message with a colon(:)');
});
```

Run `mocha sample.js`

**Expected behavior:** [What you expect to happen]

Error messages follow the same format. Whichever it is, but I like stripped more because it allows to get rid of content if it's too long.

**Actual behavior:** [What actually happens]

```


  1) Should print message without a colon
  2) Should print message with a colon(:)

  0 passing (8ms)
  2 failing

  1) Should print message without a colon:

      message without a colon
      + expected - actual


      at Context.it (sample.js:11:8)

  2) Should print message with a colon(:):

      Error: message with a colon(:): expected something else
      + expected - actual


      at Context.it (sample.js:15:8)



```

Note that message that did not have colon was stripped off `expected: something else` part and Error class name, while the message with a colon was printed as if it was straight out of `toString` method.

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:  `5.2.0` local, no global
- The output of `node --version`: `v10.12.0`

### Additional Information

If `showDiff` is `false` or either `actual` or `expected` fields are missing, both errors are printed similarly.

Very unintuitive and took a while to figure out. I encountered this while testing http requests and trying to print urls in errors.

Easy to reproduce with chai as well. Assertions could look like this:

```js
expect(1).to.equal(2);
expect(1, 'message without a colon').to.equal(2);
expect(1, 'message with a colon(:)').to.equal(2);
```

**Comment by outsideris** [comment]
I'm not sure it is a bug or not.
BTW it is caused by [here](https://github.com/mochajs/mocha/blob/adb1f612a8e909c3ce158ab66f75bb4a54a29014/lib/reporters/base.js#L245-L246)

**Comment by plroebuck** [comment]
It's not a bug. Intentional behavior to support extended assertion messages from Chai.
Issue #991 has details, but if that's a TL;DR thing, Chai's [expect](https://www.chaijs.com/guide/styles/#expect) supports prepending arbitrary text to beginning of assertion messages.

Essentially, if you use `expect(someVar).not.to.be.undefined` and `someVar` is undefined, you get back `AssertionError: expected undefined not to be undefined` (which is pretty useless).

Instead, you can use their extended style `expect(someVar, 'someVar').not.to.be.undefined`, and get back the more informative `AssertionError: someVar: expected undefined not to be undefined`.

**Comment by plroebuck** [comment]
Please close this issue if that answers your question. Thx!

**Comment by juergba** [comment]
As @outsideris  pointed out the line in question is:
`var match = message.match(/^([^:]+): expected/);`

I didn't catch the purpose of that regex, but as you can see, it contains ': expected'
The second part of your error message contains also ': expected'

To avoid this match just change your error message in something similar like:
`super(message + ': expects something else');`  or
`super(message + ':   expected something else');`   // with two spaces after ':'

The format of your error message will be as expected.

**Comment by bmarker** [comment]
I don't think that regex is doing quite what was intended.
```
    expect(false, 'something: expected foo').to.exist.and.to.be.true
```

Output:
```
      something
      + expected - actual

      -false
      +true
```

chai@5.2.0
mocha@11.7.0

I can open a new issue if somebody wants to take another look.

I also don't want to include the expectation in my custom message. It's easier to maintain when expectations change and easier to re-use when copying to other tests with different expectations. The default message being included automatically helps with chaining too.

Take this case:
```
const value: number | undefined = testFunction()
expect(value, 'Test:').to.exist.and.be.greaterThan(3)
```

The "to be above" part is pretty helpful in this case:
```
      AssertionError: Test:: expected 1 to be above 3
      + expected - actual

      -1
      +3
```

Best option I found so far is to put in a leading colon:

```
expect(value, ':Test').to.exist.and.be.greaterThan(3)
```

At least that output looks somewhat intentional:
```
      AssertionError: :Test: expected 1 to be above 3
```

**Comment by bmarker** [comment]
Note: It's only an issue if you show diffs. If you hide diffs, the output is like I'd expect.

Test:
```
import { expect } from 'chai'
import * as chai from 'chai'

describe.only('Logging', function () {
  describe('with diff', function () {
    before(function (){
      chai.config.showDiff = true
    })

    it('with no colon', function () {
      expect(false, 'Test').to.be.true
    })

    it('with colon', function () {
      expect(false, ':Test').to.be.true
    })
  })

  describe('without diff', function () {
    before(function (){
      chai.config.showDiff = false
    })

    it('with no colon', function () {
      expect(false, 'Test').to.be.true
    })

    it('with colon', function () {
      expect(false, ':Test').to.be.true
    })
  })
})
```

Output:
```
1) Logging
       with diff
         with no colon:

      Test
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (src/test/unit/expect.test.ts:11:34)
      at processImmediate (node:internal/timers:483:21)

  2) Logging
       with diff
         with colon:

      AssertionError: :Test: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (src/test/unit/expect.test.ts:15:35)
      at processImmediate (node:internal/timers:483:21)

  3) Logging
       without diff
         with no colon:
     AssertionError: Test: expected false to be true
      at Context.<anonymous> (src/v2/test/unit/api/types.test.ts:25:34)
      at processImmediate (node:internal/timers:483:21)

  4) Logging
       without diff
         with colon:
     AssertionError: :Test: expected false to be true
      at Context.<anonymous> (src/test/unit/expect.test.ts:29:35)
      at processImmediate (node:internal/timers:483:21)


```

**Comment by bmarker** [comment]
Ahhh ... I think I see what's happening. In this case:
```
expect(false, 'Test').to.be.true
```

The `message` is "Test: expected false to be true". I was thinking it was just "Test". This does match the regex.

But when you add the extra colon, it no longer matches the regex.

**Comment by bmarker** [comment]
If you change the regex to:
```
      var match = message.match(/^(.+): expected/);
```

Both `Test` and `:Test` behave the same. It trims off the `:expected ...`. It's not the behavior I want but it's at least consistent.

The capture group is also greedy so it trims off the last `: expected ...` instead of stopping at the first colon.

With the above regex, this passes through the whole custom message:
```
    expect(1, 'Test: expected foo').to.exist.and.be.greaterThan(3)
```

Output:
```
      Test: expected foo
      + expected - actual

      -1
      +3
```
