### ISSUE TITLE
Philosophical Reporter Questions

### ISSUE THREAD

**Issue by plroebuck** [mochajs/mocha#3537]
Full Disclosure: _Yes, I know the terminal codes will interfere with certain file formats._

* An upcoming change to the xunit reporter intentionally turns use of color off. If a user issues the command below, were his expections _met_?
```bash
$ FORCE_COLOR=1 mocha --reporter xunit
```
* Should a reporter be able to completely disregard a user setting? If so, should it warn?

If the command line had been that below, I _could_ see not bothering since file output was specified.
```bash
$ FORCE_COLOR=1 mocha --reporter xunit --reporter-options output=xunit.xml
```

While not currently implemented, I could also see reporter that outputs to **both** file and console.
For instance, the above could also echo any failed tests to console (via reporter option, of course)

**Comment by mlucool** [comment]
I agree this should either warn or throw.

>  I could also see reporter that outputs to both file and console.

I have implemented something similar in my code, but the reporter for console is spec and the output for file is xunit because spec is great for people and xunit is great for machines.

**Comment by boneskull** [comment]
- We can safely output warnings to STDERR while the test output stays in STDOUT.
- If there's a valid use case for machine-readable reporters to output in color, then we can support such a thing if someone wants it, but I don't believe there is.
- I'm :-1: on a warning if `FORCE_COLOR` or `--color` is used with a machine-readable output format.  I can see a situation in which it'd create extra work for developers to avoid/suppress the warning--like if it's conflicting with other defaults (e.g., `mocha.opts`).
