### ISSUE TITLE
isMochaInternal to filter stack is too simple

### ISSUE THREAD

**Issue by robstoll** [mochajs/mocha#3540]
### Prerequisites

- [x ] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
I have a test which involves the stack of an error. The exception message contains the stack trace which means it also contains `node_modules/mocha.js`
Due to this the first line is removed from the stack in error reporting. The bug is in ["utils.js" line 631](https://github.com/mochajs/mocha/blob/b9b3ac0122347df9b9699413d2025541674c929f/lib/utils.js#L631), function [isMochaInternal line 611](https://github.com/mochajs/mocha/blob/b9b3ac0122347df9b9699413d2025541674c929f/lib/utils.js#L611) respectively.

### Steps to Reproduce
throw an exception with `node_modules/mocha.js` in the exception message

**Expected behavior:** [What you expect to happen]
The line is shown in error reporting even if `node_modules/mocha.js` or one of the other internal keywords are found within the line.

**Actual behavior:** [What actually happens]
The line is filtered out

**Reproduces how often:** [What percentage of the time does it reproduce?]
always

### Versions
- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
  - mocha is not installed globally
  - `node_modules/.bin/mocha --version`: 5.2.0

- The output of `node --version`: v8.12.0

**Comment by robstoll** [comment]
Can be reproduced as follows:
1. git clone https://github.com/robstoll/atrium.git
2. git checkout mocha-filter-stack
3. open up a terminal in the root of the project and `gr :atrium-core-api-js:runMocha`
4. Will fail with something like:
```
  1) ch.tutteli.atrium.core.polyfills
       DummySpec
         illegalStateException:
     assert: [DummySpec.illegalStateException [...], callFn (/home/travis/build/robstoll/atrium/core/api/atrium-core-api-js/node_modules/mocha/lib/runnable.js:372:21), [...]]        (ArrayList <1>)
◆ is: empty
  ◆ is: empty
      at AssertionError_init_0 (build/node_modules/kotlin.js:24991:22)
      at ThrowingAssertionChecker.check_i2wsmx$ (build/node_modules/atrium-core-robstoll-lib-js.js:146:25)
      at AssertionPlantWithCommonFields$CommonFields.check_tgi7xs$ (build/node_modules/atrium-core-api-js.js:1347:27)
      at ReportingAssertionPlantImpl.MutableListBasedReportingAssertionPlant.checkAssertions_8qzvkp$_0 (build/node_modules/atrium-core-robstoll-lib-js.js:275:25)
      at ReportingAssertionPlantImpl.MutableListBasedReportingAssertionPlant.addAssertion_94orq3$ (build/node_modules/atrium-core-robstoll-lib-js.js:270:10)
      at toBe_2 (build/node_modules/atrium-api-cc-infix-en_GB-js.js:284:22)
      at DummySpec.illegalStateException (build/classes/kotlin/test/atrium-core-api-js_test.js:309:5)
      at Context.<anonymous> (build/classes/kotlin/test/atrium-core-api-js_test.js:835:34)
```
=> see https://travis-ci.org/robstoll/atrium/jobs/448519900#4950 for an example.
It should be:
```` 
   assert: [DummySpec.illegalStateException [...], callFn (/home/travis/build/robstoll/atrium/core/api/atrium-core-api-js/node_modules/mocha/lib/runnable.js:372:21), [...]]        (ArrayList <1>)
◆ is: empty
AssertionError("assert:  [DummySpec.illegalStateException [...]")
◆ is: empty   
   at ....
```` 
The duplicate `is: empty` is only because the first line in the stack was filtered out.

**Comment by plroebuck** [comment]
Sorry haven't gotten around to research this, but does it still happen if you use `--full-trace` cmdline arg?

**Comment by plroebuck** [comment]
So `stackTraceFilter` is _only_ filtering `err.stack`, which makes for more concise error reporting.
But you say we're filtering `AssertionError("assert:  [DummySpec.illegalStateException [...]")` which doesn't quite seem right, since that's _not_ a stack trace. Or have you annotated the stack trace?

As Mocha has no means of special-casing atrium, it'll have to be done on your side.
Either run using the `--full-trace` cmdline arg or homoglyph "mocha" as `"\u217focha"`
to evade the stack filtering.

**Comment by plroebuck** [comment]
damn, changes don't stick now...

**Comment by robstoll** [comment]
Please try to reproduce the error, you will see that mocha filters the first stack frame out.
err.stack is initially (before filtering):
```
AssertionError("assert:  [DummySpec.illegalStateException [...]")
is: empty
      at AssertionError_init_0 (build/node_modules/kotlin.js:24991:22)
      at ThrowingAssertionChecker.check_i2wsmx$ (build/node_modules/atrium-core-robstoll-lib-js.js:146:25)
      at AssertionPlantWithCommonFields$CommonFields.check_tgi7xs$ (build/node_modules/atrium-core-api-js.js:1347:27)
      at ReportingAssertionPlantImpl.MutableListBasedReportingAssertionPlant.checkAssertions_8qzvkp$_0 (build/node_modules/atrium-core-robstoll-lib-js.js:275:25)
      at ReportingAssertionPlantImpl.MutableListBasedReportingAssertionPlant.addAssertion_94orq3$ (build/node_modules/atrium-core-robstoll-lib-js.js:270:10)
      at toBe_2 (build/node_modules/atrium-api-cc-infix-en_GB-js.js:284:22)
      at DummySpec.illegalStateException (build/classes/kotlin/test/atrium-core-api-js_test.js:309:5)
      at Context.<anonymous> (build/classes/kotlin/test/atrium-core-api-js_test.js:835:34)
```
I am not sure what you mean with that's not a stack trace. Npm the includes the error type and message in Error.stack

**Comment by plroebuck** [comment]
> Well well, the error remains, I am going to delete the branch I created for this issue.

We're attempting to launch Mocha-6.0 and have been for over a week. I have over 300 Mocha-related messages in my email as of this morning... and it was clean last week. If I'm not working fast enough for _you_, feel free to _solve_ the problem for me.

**Comment by robstoll** [comment]
Sorry, I did not meant to stress or offend you. I have worked around the issue in my lib as you suggested. I cleaned up my repo and deleted branches I have created for third-party libs and only wanted to let you know where you have to proceed with the investigation.
I could help with the fix but we need an agreement on the implementation. I don't want to break things for you after all. Thus I need to know if you expect `stack` to be according to the spec here: https://nodejs.org/api/errors.html#errors_error_stack
Which means it can contain the Error + message. If that's the case, then I would adjust the filtering since it filters out the message if it contains /mocha/ for instance.

**Comment by robstoll** [comment]
@plroebuck I am closing this issue as it has no relevance for me as the workaround works well. Let me know in case you make up your mind on how it should be implemented, I would still help you with the implementation.
