### ISSUE TITLE
TravisCI windows

### ISSUE THREAD

**Issue by outsideris** [mochajs/mocha#3551]
Recently, Tavis CI supported Windows. See [Windows is Available (Early Release)](https://blog.travis-ci.com/2018-10-11-windows-early-release).

Is it helpful if we move from AppVeyor to Travis CI?

**Comment by plroebuck** [comment]
Not yet. I'm still trying to get the Chocolatey Growl package fixed. Windows support appears _far_ more limited at this time on Travis than AppVeyor.
