### ISSUE TITLE
Mocha fails on Node v10: "console.log is not a function"

### ISSUE THREAD

**Issue by MonkeyDo** [mochajs/mocha#3553]
### Prerequisites
- [X] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [X] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [X] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [X] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

On Octobre 30th NodeJS [updated their LTS version](https://nodejs.org/en/blog/release/v10.13.0/) to be 10.13, and my Travis CI tests started failing (for node version `lts/*`).
I've been able to reproduce the failure on my development machine using `nvm` to try with different versions of node.
The test suite is working up to version 10.0 (9.11.2 works fine)

One of my first steps was to upgrade to the latest mocha version available on NPM.

Here is the output of the test suite when using Node >= 10:

```
$ npm run test

> bbsite@0.0.0 test /Work/BookBrainz/bookbrainz-site
> npm run lint-errors && cross-env SSR=true NODE_ENV=test mocha


> bbsite@0.0.0 lint-errors /Work/BookBrainz/bookbrainz-site
> eslint --quiet .

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration.
/Work/BookBrainz/bookbrainz-site/node_modules/mocha/lib/reporters/spec.js:80
    console.log(indent() + color('fail', '  %d) %s'), ++n, test.title);
            ^

TypeError: console.log is not a function
    at Runner.<anonymous> (/Work/BookBrainz/bookbrainz-site/node_modules/mocha/lib/reporters/spec.js:80:13)
    at Runner.emit (events.js:187:15)
    at Runner.fail (/Work/BookBrainz/bookbrainz-site/node_modules/mocha/lib/runner.js:251:8)
    at Runner.uncaught (/Work/BookBrainz/bookbrainz-site/node_modules/mocha/lib/runner.js:735:12)
    at process.uncaught (/Work/BookBrainz/bookbrainz-site/node_modules/mocha/lib/runner.js:839:10)
    at process.emit (events.js:182:13)
    at process._fatalException (internal/bootstrap/node.js:435:27)

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! bbsite@0.0.0 test: `npm run lint-errors && cross-env SSR=true NODE_ENV=test mocha`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the bbsite@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2018-11-05T17_54_27_925Z-debug.log
```

My mocha.opts file:
```
--recursive
--require babel-register
--timeout 20000
--exit
```

I found the NPM log didn't provide much more information, but here it is in case I missed something:
```
0 info it worked if it ends with ok
1 verbose cli [ '/.nvm/versions/node/v10.0.0/bin/node',
1 verbose cli   '/.nvm/versions/node/v10.0.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test' ]
2 info using npm@5.6.0
3 info using node@v10.0.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle bbsite@0.0.0~pretest: bbsite@0.0.0
6 info lifecycle bbsite@0.0.0~test: bbsite@0.0.0
7 verbose lifecycle bbsite@0.0.0~test: unsafe-perm in lifecycle true
8 verbose lifecycle bbsite@0.0.0~test: PATH: /.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Work/BookBrainz/bookbrainz-site/node_modules/.bin:/.nvm/versions/node/v10.0.0/bin:/usr/local/bin:/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/share/dotnet:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS
9 verbose lifecycle bbsite@0.0.0~test: CWD: /Work/BookBrainz/bookbrainz-site
10 silly lifecycle bbsite@0.0.0~test: Args: [ '-c',
10 silly lifecycle   'npm run lint-errors && cross-env SSR=true NODE_ENV=test mocha' ]
11 silly lifecycle bbsite@0.0.0~test: Returned: code: 7  signal: null
12 info lifecycle bbsite@0.0.0~test: Failed to exec test script
13 verbose stack Error: bbsite@0.0.0 test: `npm run lint-errors && cross-env SSR=true NODE_ENV=test mocha`
13 verbose stack Exit status 7
13 verbose stack     at EventEmitter.<anonymous> (/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:947:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
14 verbose pkgid bbsite@0.0.0
15 verbose cwd /Work/BookBrainz/bookbrainz-site
16 verbose Darwin 17.7.0
17 verbose argv "/.nvm/versions/node/v10.0.0/bin/node" "/.nvm/versions/node/v10.0.0/bin/npm" "run" "test"
18 verbose node v10.0.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 7
22 error bbsite@0.0.0 test: `npm run lint-errors && cross-env SSR=true NODE_ENV=test mocha`
22 error Exit status 7
23 error Failed at the bbsite@0.0.0 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 7, true ]
```

### Steps to Reproduce

I'm sorry I don't have a minimal example, but the [bookbrainz-site](https://github.com/bookbrainz/bookbrainz-site) repository can be used in combination with [NVM](https://github.com/creationix/nvm) to reproduce the issue, at least on the travis CI server and on my computer (OSX 10.13.6)

### Versions

- `mocha --version`: no global version of mocha installed
- `node node_modules/.bin/mocha --version`: 5.2.0
- `node --version`: v10.0.0
- The version and architecture of your operating system: Mac OSX 10.13.6
- Your shell (bash, zsh, PowerShell, cmd, etc.): [iTerm2](https://iterm2.com)
- Any other third party Mocha related modules (with versions):
- The code transpiler being used: babel-register

**Comment by MonkeyDo** [comment]
The Travis CI machine runs Ubuntu 14.04.5 LTS

Here is an example log of a failing test for node v10.13:
https://travis-ci.org/bookbrainz/bookbrainz-site/jobs/447747282#L979

**Comment by boneskull** [comment]
your mocha version reported in this issue doesn't match the version in your `package.json`.

**Comment by boneskull** [comment]
I'm not sure why this is happening in Node.js v10.  But your debugger will show you the `console` object is actually [this object](https://github.com/bookbrainz/bookbrainz-site/blob/master/test/test-achievement.js#L73).  Something's getting fouled up between Babel, rewire, etc.

Not a Mocha issue... good luck 😉

**Comment by MonkeyDo** [comment]
Thanks, you've been a great help !
