### ISSUE TITLE
Reporter tests affected by shallow cloning

### ISSUE THREAD

**Issue by plroebuck** [mochajs/mocha#3554]
### Description

While updating our reporter test code, it has been discovered that many tests are restoring aspects of the tested objects due to use of shallow cloning. Typically, the test code makes a copy of the affected object, mutates it temporarily, then restores it. Problem is that making a copy via assignment of an object does not work protect its properties, and those "twiddled" properties are still present in the original when restored. We need a "deep clone" method, and then to apply it to **all** reporter specs.

While not evaluated elsewhere (yet), it is almost certain this problem is **far** more widespread.

### Versions

Mocha 5.2 (past & future)

**Comment by boneskull** [comment]
Do you have an example...?

**Comment by outsideris** [comment]
Maybe [this one](https://github.com/mochajs/mocha/pull/3528#discussion_r227994683)?

**Comment by boneskull** [comment]
Couldn't this just be solved by using e.g., [Sinon](https://npm.im/sinon)?
