### ISSUE TITLE
Promise.finally(done) never fails tests

### ISSUE THREAD

**Issue by Teivaz** [mochajs/mocha#3555]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Steps to Reproduce
```js
describe('promise', ()=>{
	it('never fails with `done` in finally', (done)=>{
		Promise.resolve().then(assert.fail).catch(assert.fail).finally(done)
	})
	it('no matter what', (done)=>{
		Promise.reject().then(assert.fail).catch(assert.fail).finally(done)
	})
	it('but properly fails when returning', ()=>{
		return Promise.reject().then(assert.fail).catch(assert.fail)
	})
})
```
Output I get:
```
  promise
    ✓ never fails with `done` in finally
(node:83761) UnhandledPromiseRejectionWarning: AssertionError: AssertionError: assert.fail()
(node:83761) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:83761) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    ✓ no matter what
(node:83761) UnhandledPromiseRejectionWarning: AssertionError: assert.fail()
(node:83761) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
    1) but properly fails when returning


  2 passing (12ms)
  1 failing

  1) promise
       but properly fails when returning:
     AssertionError: AssertionError: assert.fail()
```

**Expected behavior:** All three tests should fail

**Actual behavior:** Only last test fails

**Reproduces how often:** Always

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: <no global installation>, 5.2.0
- The output of `node --version`: v11.1.0
- The version and architecture of your operating system: macOS High Sierra 10.13.2
- Your shell (bash, zsh, PowerShell, cmd, etc.): default macOS Terminal.app
- Your browser and version (if running browser tests): no
- Any other third party Mocha related modules (with versions): chai 4.2.0
- The code transpiler being used: pure ES6

### Additional Information

This issue seems related https://github.com/mochajs/mocha/issues/1283 but it does not cover current problem

**Comment by outsideris** [comment]
If you want to make a test failed, you should pass `Error` object to `done` like `done(new Error())`. [`finally` doesn't receive any argument](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally).

> A finally callback will not receive any argument, since there's no reliable means of determining if the promise was fulfilled or rejected.

**Comment by starpit** [comment]
for future reference, if my `finally` block returns a promise, then mocha will not fail. for example:

```
try {
  // something that fails
} catch (err) {
  // log and rethrow
  throw(err)
} finally {
  return promisify(unlink)(file.name)
}
```

in this example mocha (6.1.3, running with spectron 5.0.0) never detects the rethrown error; however if the finally block does not return the unlink promise, then mocha fails with the rethrown error, as expected.
