### ISSUE TITLE
use ms module instead of internal implementation

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3557]
It's good to reduce LOC and use purpose-built modules.  

Prompted by comments on #3556.

Remove internal `ms.js` and use https://npm.im/ms instead.

**Comment by gizemkeser** [comment]
Hello, may I work on this issue?

**Comment by boneskull** [comment]
@gizemkeser go for it

**Comment by plroebuck** [comment]
Files:
lib/runnable.js
lib/suite.js
lib/reporters/base.js
test/unit/ms.spec.js
test/unit/runnable.spec.js
package.json
package-lock.json

Would also be nice to import module within source as:
```js
var milliseconds = require('ms');
```
