### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3560]
~~yargs’ [y18n](https://npm.im/y18n) looks easy to use and we should probably start using it. ~~

UPDATE: use a different i18n library; see links below

it’d also be a great opportunity to encourage translation contributions!

**Comment by boneskull** [comment]
:+1: good resources. thanks

**Comment by juergba** [comment]
I live in Europe where we speak dozens of different languages. I don't know of a single developer who doesn't speak english. IMO internationalization makes maintenance more complex and the added value is minimum.
Closing.
