### ISSUE TITLE
Use "package.json" to determine test directory

### ISSUE THREAD

**Issue by plroebuck** [mochajs/mocha#3562]
### Description

Read "package.json" field `directories.test` if it exists. If it does, use its value instead of `"test"` as Mocha's default for test directory. 

Inspired from discussion in #1275 where someone had named his test directory "tests" and then Mocha wouldn't find his "mocha.opts" file (without specifying it via `--opts`).

**Comment by juergba** [comment]
`package.json` is not updated dynamically. When creating/renaming directories, the field `directories.test` would have to be maintained manually. `package.json` is not a good place to define the default directory. There is already a place to set such values, which is the `mocha.opts` file.

For the test files `scripts.test` in `package.json` can already be used for defining the test directory.
```
"scripts": {
    "test": "mocha ./tests/"
  },
```

**Comment by plroebuck** [comment]
> `package.json` is not a good place to define the default directory.

Unsure why you think this, since it's [specifically documented](https://docs.npmjs.com/files/package.json#directoriestest) as the means to communicate a package's structure.

The `directories` field in "package.json" _does not exist_ by default; therefore, if `directories.test` does exist, the user purposefully set it and we should respect that value, without making them re-specify the same thing in "mocha.opts" or the `scripts.test` field of "package.json".

It should just work...

**Comment by juergba** [comment]
> The directories field in "package.json" does not exist by default; [...]

When you do `npm init` and the directory test already exists, the `directories` field is created automatically. This works at least with VSCode, no other directories unless `test` are recognised and inserted.

> It should just work...

You have made your decision, so close the `discussion` label.
And I would like to implement this.
