### ISSUE TITLE
Timeout default is incorrect, 200ms instead of 2000ms

### ISSUE THREAD

**Issue by juergba** [mochajs/mocha#3571]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
The timeout default value is set differently in the master branch and my local Mocha V5.2.0
```
describe('suite1', function () {
  console.log(this._timeout);
});
```
Output master branch: 200
Output my local Mocha: 2000

Many integration test are failing for that reason. These tests do pass correctly when using the flag --timeout=2000

### Steps to Reproduce

**Expected behavior:** default timeout should be 2000ms

**Actual behavior:** default timeout is 200ms

**Reproduces how often:** always

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: master branch
- The output of `node --version`: V10.5.0
- The version and architecture of your operating system: windows 10 Home 1809
- Your shell (bash, zsh, PowerShell, cmd, etc.): cmd of VSCode
- Your browser and version (if running browser tests):
- Any other third party Mocha related modules (with versions):
- The code transpiler being used:

### Additional Information

master branch
```
git show --oneline -s
593e9b8 (HEAD -> master, origin/master, origin/HEAD) Add ability to query Mocha version programmatically (#3535)
```

**Comment by plroebuck** [comment]
_Which_ integration test(s) fail? Specific set from "package-scripts"?

**Comment by juergba** [comment]
for example: they all do work with --timeout=2000
- test\integration\timeout.spec.js
- test\integration\options.spec.js
- test\integration\hooks.spec.js
- test\integration\hook-err.spec.js
- test\integration\retries.spec.js

**Comment by outsideris** [comment]
How did you run tests? 
For integration test, [timeout is 5000ms](https://github.com/mochajs/mocha/blob/master/package-scripts.js#L101).

**Comment by juergba** [comment]
Yes, running the tests with the package script, then timeout is 5000ms. Running some individual tests/spec files manually as the ones listed above, then timeout is 200ms.

**Comment by outsideris** [comment]
You can run them with `test.node.integration` and  [exclusive-tests](https://mochajs.org/#exclusive-tests).
