### ISSUE TITLE
Resolve conflict between envvar and cmdline arg for same resource

### ISSUE THREAD

**Issue by plroebuck** [mochajs/mocha#3574]
### Description

What happens when envvar and cmdline arg for same resource specify different values?

We need to add a couple tests regarding color:
* Given _both_ envvar `FORCE_COLOR` and `--no-color`, is color enabled?
* Given _both_ envvar `FORCE_COLOR=1` and `--no-color`, is color enabled?
* Given _both_ envvar `FORCE_COLOR=0` and `--color`, is color enabled?

**Comment by shubham-rocko** [comment]
Hi, could you please explain it bit more or provide some resources related to this issue?

**Comment by juergba** [comment]
Mocha's option parsing with _yargs-parser/yargs_ does not consider environment variables. Closing.
