### ISSUE TITLE
Correctly diagnose errors from required reporter module

### ISSUE THREAD

**Issue by aido179** [mochajs/mocha#3596]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

When developing a third party reporter, mocha misdiagnoses an error coming from within the reporter as the reporter module not being found.

### Steps to Reproduce

[Minimal reproduction](https://github.com/aido179/mocha-err)
1. Create a parent project that uses mocha.
2. Create a custom reporter, that doesn't require mocha anywhere. 
3. Install that reporter in the parent project (in this case, as a local package using the file location).
4. When mocha `require`s the reporter, node throws an error. The `require` works correctly, but mocha erroneously `console.warn`s that the reporter wasn't found.

**Expected behavior:**

Mocha says that the reporter package caused the error.

**Actual behavior:** 

Mocha erroneously `console.warn`s that the reporter wasn't found.

**Reproduces how often:** 100%

### Versions

Mocha version: 5.2.0 (not installed globally)
Node version: v8.11.1
OS: MacOs High Sierra v10.13.6
Shell: iTerm2 build 3.2.4beta2

### Additional Information
As discussed in #3530, initially thought the package was not being required correctly.

**Comment by plroebuck** [comment]
While I can see how a better error message could be helpful, the _real_ bug here is in _your_ reporter  depending on missing project dependencies.
