### ISSUE TITLE
CLI path directory expansion should be case-insensitive

### ISSUE THREAD

**Issue by stevenvachon** [mochajs/mocha#3599]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
The directory expansion of files should result in a case-insensitively sorted list.

### Steps to Reproduce

Run `mocha test/` in a project with `test/a-tests.js` and `test/B-tests.js`.

**Expected behavior:**  "a" suite  runs before "B" suite

**Actual behavior:** "B" suite runs before "a" suite

**Reproduces how often:** always

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: **5.2.0**
- The output of `node --version`: **10.14.1**
- The version and architecture of your operating system: **macOS 10.14.1**
- Your shell (bash, zsh, PowerShell, cmd, etc.): **bash**
- Your browser and version (if running browser tests):
- Any other third party Mocha related modules (with versions):
- The code transpiler being used:

**Comment by plroebuck** [comment]
Why? We support case-sensitive filesystems too. You could just name your tests so they would alphabetize in ASCII order.

**Comment by boneskull** [comment]
When given a directory, Mocha uses `fs.readdir()`, which returns the files in this order.

If you need a specific order, consider using `--file`.

Maybe it'd be worthwhile to use `glob` under the hood instead of `fs.readdir()` so the ordering is consistent.

The function that handles this is in [`lib/utils.js`](https://github.com/mochajs/mocha/blob/1f325e746033f698c6a040329a2fd7670daaf274/lib/utils.js#L513-L514).  Instead of `fs.readdir()` we could use `glob.sync()` to look for `<dirpath>/*.{<extensions>}` where `dirpath` in this case would be `test`, and `extensions` is the array of extensions to load/watch (by default this is `['js']`), comma-separated.  If `--recursive` is used, change the  `/*` in the globspec to `/**/*`.

**Comment by plroebuck** [comment]
We don't set the `nocase` glob [option](https://www.npmjs.com/package/glob#options), so this ordering was not intended.
If `glob`'s output is ordered differently on case-insensitive filesystems, [sorting its output before return](https://github.com/mochajs/mocha/blob/1f325e746033f698c6a040329a2fd7670daaf274/lib/utils.js#L527) would be simpler (and faster) means of consistency, without surprising all the non-(FAT/NTFS/HFS+) users.

**Comment by plroebuck** [comment]
Having looked further, **no** order is implied via [`fs.readdir`](https://nodejs.org/api/fs.html#fs_fs_readdir_path_options_callback). Different OS/filesystem combinations can give different results (via [readdir(3)](https://stackoverflow.com/questions/8977441/does-readdir-guarantee-an-order)) which returns [directory] entries in _traversal_ order which may or may not be alphabetical (e.g., on macOS, HFS+ uses lexical order and APFS uses filename hash order). `glob` uses `fs.readdir` [under the covers](https://github.com/isaacs/node-glob/blob/8882c8fccabbe459465e73cc2581e121a5fdd25b/sync.js#L288), but not necessarily processing in a straight line.

See also:
* [Ensuring a repeatable directory ordering in Linux](https://serverfault.com/questions/406229/ensuring-a-repeatable-directory-ordering-in-linux)
* [How to reset Launchpad order in macOS High Sierra?](https://apple.stackexchange.com/questions/300109/how-to-reset-launchpad-order-in-macos-high-sierra#307210)
* [borgbackup:Order of traversing files in a directory](https://github.com/borgbackup/borg/issues/905)

**Comment by boneskull** [comment]
@plroebuck 	Are you suggesting to enable sorting by default (i.e., `--sort`)?

**Comment by boneskull** [comment]
I don't think we should change this behavior, but happy to discuss.  Mocha makes no guarantees about the order in which files are loaded if it is not operating on a globspec (this is undocumented).  That said...

Changing the behavior to sort differently (whatever that looks like) will break tests.  And not of the "dirty tests" variety either--users may have some setup hooks within the root suite, which is a perfectly valid use case.  Other workarounds such as `--file` are available, but this still forces users to change stuff for a relatively flimsy reason.

**Comment by stevenvachon** [comment]
I'm not sure how macOS sorts files, but Finder.app sorts it how I'd described.

**Comment by plroebuck** [comment]
> @plroebuck Are you suggesting to enable sorting by default (i.e., `--sort`)?

No. Original suggestion was only sorting `glob` results (attempting to make them match those from `fs.readdir` which at the time I assumed were alphabetical).

**Comment by plroebuck** [comment]
> I'm not sure how macOS sorts files, but Finder.app and `glob` both sort how I'd described in "expected behaviour".

Each `Finder.app` window _explicitly_ sorts its contents via selected column header (e.g., Name, Size, Date Modified, Kind). Many things can also affect sorting order (e.g., locale, comparison function); even `Finder.app`'s sort order can be changed [under the hood](http://mygeekdaddy.net/2016/02/29/change-finder-sort-order-for-os-x-el-capitan/).

**Comment by plroebuck** [comment]
I updated the API documentation to specify no order should be assumed.
Using consistent file naming and `--sort` will provide alphabetical ordering if required.
