### ISSUE TITLE
How to log mochaOpts in the test?

### ISSUE THREAD

**Issue by shridharkalagi** [mochajs/mocha#3605]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
How do I print mochaOpts.retries in the test? Currently, tests are triggered from a 3rd party service and I'm not sure whether the tests are retried or not. So I wanna add a console log to figure out the how the tests are configured. Can someone help me here?
### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 5.2.0
- The output of `node --version`: 10.11.0
- The version and architecture of your operating system: Mac
- Your shell (bash, zsh, PowerShell, cmd, etc.): zsh
- Your browser and version (if running browser tests): Chrome 69
- Any other third party Mocha related modules (with versions):
- The code transpiler being used:

**Comment by craigtaub** [comment]
Have you tried logging `this.retries()` inside the test? It should be highest priority retry value at that time.

**Comment by shridharkalagi** [comment]
This is not working for me. Is there any other way?

**Comment by craigtaub** [comment]
Can you print what code you are using and what is happening. Thanks
