### ISSUE TITLE
Improve default resolution of mocha.opts

### ISSUE THREAD

**Issue by paulmelnikow** [mochajs/mocha#3612]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)

### Description

Mocha looks for `mocha.opts` in `test/mocha.opts`. Ref: https://github.com/mochajs/mocha/issues/1275#issuecomment-437538329

Many projects keep tests next to the code they're testing, which means there's no `test/` directory and  so unless that `test/` folder is created especially for this config file, there's no place that `mocha.opts` will be read by default.

#1277 provides an alternative here. You can put `mocha.opts` wherever you want, e.g. alongside `package.json`, and specify `--opts mocha.opts`. However the `package.json` I'm working with has 11 different `mocha` invocations. I can add `--opts mocha.opts` to each one, though it's inconvenient and makes these invocations more difficult to read.

It would be a usability improvement to default to searching for `mocha.opts` _alongside the `package.json`_ in addition to looking in `test/mocha.opts`.

### Steps to Reproduce

1. Set options in `mocha.opts` alongside `package.json` e.g. `--reporter mocha-env-reporter`
2. Run `mocha`

**Expected behavior:** The reporter is loaded.

**Actual behavior:** The reporter is not loaded.

**Reproduces how often:** Always.

### Additional Information

If both files exist, probably it makes sense to print a warning and use `test/mocha.opts`, for compatibility with the old behavior.

**Comment by craigtaub** [comment]
Hey
Wanted to let you know in version 6 we have changed how options are loaded (see https://mochajs.org/#configuring-mocha-nodejs). We recommend you create a configuration file at your projects root.

`mocha.opts` is now considered legacy (https://mochajs.org/#mochaopts).

Hopefully this will be useful for you.

**Comment by paulmelnikow** [comment]
That is _fabulous_!

Looks like that hasn't shipped yet! Where's the best place to track the release?

**Comment by craigtaub** [comment]
Great.

I think its very close to being released. We usually send messages out to usual channels (Twitter/Gitter etc) but you could track via a Github  "Releases only" notification.

Closing this issue.
