### ISSUE TITLE
done is not defined()

### ISSUE THREAD

**Issue by DawidKowalczyk** [mochajs/mocha#3618]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
- The output of `node --version`:
- The version and architecture of your operating system:
- Your shell (bash, zsh, PowerShell, cmd, etc.):
- Your browser and version (if running browser tests):
- Any other third party Mocha related modules (with versions):
- The code transpiler being used:

**Comment by DawidKowalczyk** [comment]
Hi I have this test


`    it('record should fetch and displayed data from db ',(done) =>
        {
        request.get({url:telemetryUrl + '/graph/v1/services/telemetry/subscriptions/'+testSubscriptionId},
        function(error, response, body){
            try{

                console.log("__Status code:"+response.statusCode);
                console.log(response.body["tenantId"])
            }

            catch(err){
                done(new Error(err));
            }

        }
    )
        });
    console.log("connecting to db...")
    tenantId = testConfig.tenantId

    let query = 'SELECT * FROM telemetry_tenant_registration WHERE tenant_id=? ALLOW FILTERING';
    client.execute(query,  [tenantId])
    .then(result => {
        try
        {
            expect(result.rows[0].tenant_id,tenantId,"Unable to find tenantID in db");
            done();
        }catch(err){
            done(new Error(err));
        }
        });`

**Comment by DawidKowalczyk** [comment]
have Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. error

**Comment by plroebuck** [comment]
Please fill in the required version information.

**Comment by plroebuck** [comment]
It would appear this is (hopefully) what you meant to do...
```js
it('record should fetch and displayed data from db ', (done) => {
  let url = telemetryUrl + 
            '/graph/v1/services/telemetry/subscription/' +
            testSubscriptionId;
  request.get({url:url}, function (error, response, body) {
    if (error) {
      done(error);
    }
    console.log("__Status code:"+response.statusCode);
    console.log(response.body["tenantId"]);
  });

  console.log("connecting to db...")
  tenantId = testConfig.tenantId

  let query = 'SELECT * FROM telemetry_tenant_registration WHERE tenant_id=? ALLOW FILTERING';
  client.execute(query, [tenantId])
    .then((result) => {
      expect(result.rows[0].tenant_id,
             tenantId,
             "Unable to find tenantID in db");
      done();
    })
    .catch((err) => {
      done(err);
    };
});
```

**Comment by DawidKowalczyk** [comment]
`const cassandra = require('cassandra-driver');
const telemetryUrl = 'http://';
const dbAuthority = '10.xxx", "10.xxx","10.xxx';
let subscriptionId;
let client;

// noinspection JSAnnotator
before({
    subscriptionId = 'xxxx',

console:log("connecting to db cluster..."),
const:clientOptions = {
    contactPoints: [dbAuthority],
    authProvider: new cassandra.auth.PlainTextAuthProvider('cassandra', 'cassandra')
},
client = new cassandra.Client(clientOptions)}

it('should fetch subscription and display corresponding db data', () => {
    let fetchPromise = new Promise((resolve, reject) => {
        let url = telemetryUrl +
            '/graph/v1/services/telemetry/subscription/' +
            subscriptionId;
        console.log("requesting subscription for " + subscriptionId + "...");
        request.get({url: url}, (error, response, body) => {
            if (error) {
                console.error("request failed:", error.message);
                reject(error);
            }
            console.log("__Status code: " + response.statusCode);
            let tenantId = response.body["tenantId"];
            console.log("tenantId:", tenantId);
            resolve(tenantId);
        });
    });

    fetchPromise.then((tenantId) => {
        let query = 'SELECT * FROM telemetry_tenant_registration WHERE tenant_id=? ALLOW FILTERING';
        console.log("querying db for tenant " + tenantId + "...");
        client.execute(query, [tenantId])
            .then((result) => {
                console.log("db responded...");
                expect(result.rows[0].tenant_id,
                    tenantId,
                    "Unable to find tenantID in db");
            });
    });
});`

got SyntaxError: Invalid shorthand property initializer
but I changed some ',' and ';' placement due to failing

**Comment by DawidKowalczyk** [comment]
`const cassandra = require('cassandra-driver');
const telemetryUrl = 'http://xxx:9090';
const dbAuthority = '10.xx", "10.xxx","10.xxx';
let subscriptionId;
let client;


before({
    subscriptionId :'someNumber',
    const:clientOptions = {
    contactPoints: [dbAuthority],
    authProvider: new cassandra.auth.PlainTextAuthProvider('cassandra', 'cassandra')
},
client :new cassandra.Client(clientOptions)})

it('should fetch subscription and display corresponding db data', () => {
    let fetchPromise = new Promise((resolve, reject) => {
        let url = telemetryUrl +
            '/graph/v1/services/telemetry/subscription/' +
            subscriptionId;
        console.log("requesting subscription for " + subscriptionId + "...");
        request.get({url: url}, (error, response, body) => {
            if (error) {
                console.error("request failed:", error.message);
                reject(error);
            }
            console.log("__Status code: " + response.statusCode);
            let tenantId = response.body["tenantId"];
            console.log("tenantId:", tenantId);
            resolve(tenantId);
        });
    });

    fetchPromise.then((tenantId) => {
        let query = 'SELECT * FROM telemetry_tenant_registration WHERE tenant_id=? ALLOW FILTERING';
        console.log("querying db for tenant " + tenantId + "...");
        client.execute(query, [tenantId])
            .then((result) => {
                console.log("db responded...");
                expect(result.rows[0].tenant_id,
                    tenantId,
                    "Unable to find tenantID in db");
            });
    });
});`

I got npm ERR! Test failed.  but normally it work

**Comment by plroebuck** [comment]
Outside some minor mods to customize to your environment, what I posted earlier should have been adequate. Rather than break the `before`, use the one I provided -- you turned a function body into an object...

**Comment by DawidKowalczyk** [comment]
TypeError: Cannot read property 'call' of undefined

Yes my response server is a JSON file. As you are an export maybe you could tell my why such  error occurs? to lead me to the solution.

**Comment by DawidKowalczyk** [comment]
maybe I explain what i need I need to send GET call and compare result in that case is tenantId with tenant_id from Cassandra. I think I need assertion here? am I right?

**Comment by ORESoftware** [comment]
Random thought - you should return

```js
          if (error) {
                console.error("request failed:", error.message);
                return reject(error);  // <<<  use return here
            }
```

**Comment by ORESoftware** [comment]
ummm is it not:

```js
it('record should fetch and displayed data from db ', (done) => {
  request.get({url:telemetryUrl + '/graph/v1/services/telemetry/subscription/'+testSubscriptionId},
    function(error, response, body) {
      try {
         console.log("__Status code:"+response.statusCode);
         console.log(response.body["tenantId"]);
         done(null);  /// <<<<<< you need to add this call
       } catch(err) {
         done(new Error(err));
       }
    }
  )
});    <<<------ You ended your test here by mistake, never having called `done`
```

**Comment by DawidKowalczyk** [comment]
still not working but there is no simplest way to do such kind of assertion ?

**Comment by DawidKowalczyk** [comment]
> done(null);

(node:11588) UnhandledPromiseRejectionWarning: ReferenceError: done is not defined
    at client.execute.then.result 
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:11588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not h
andled with .catch(). (rejection id: 1)
(node:11588) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by plroebuck** [comment]
> TypeError: Cannot read property 'call' of undefined
> 
> Yes my response server is a JSON file. As you are an export maybe you could tell my why such error occurs? to lead me to the solution.

You don't provide enough information for anyone to help you. Remember, I can't see your screen...

Change `dbAuthority`, `telemetryUrl`, `subscriptionId` variables as appropriate, rerun using [sample test](https://github.com/mochajs/mocha/issues/3618#issuecomment-447365553) provided, and post the output.

**Comment by DawidKowalczyk** [comment]
non of yours was working but thanks anyway for your contribution

**Comment by crisantus** [comment]
> have Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. error

do something like this 
  setTimeout(function () {
      try {
        assert.equal(message, "Hi there!");
          done();
      }
      catch (e) {
          done(e);
      }
  }, 1000);
