### ISSUE TITLE
Promise rejection with await not throwing UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by coreyc** [mochajs/mocha#3622]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

```javascript
const someFn = async () => {
  throw new Error(`I'm an error!`)
}

describe('someFn', () => {
  it('should result in UnhandledPromiseRejection', async () => {
    await someFn()
  })
})
```
In the above code, if `try/catch` is not used in the test I would expect an UnhandledPromiseRejection to be logged in the console, but instead, the error is. Trying to understand why. Maybe this is a duplicate of #2640 ? Couldn't quite tell.

**Expected behavior:** expect an UnhandledPromiseRejection to be logged in the console

**Actual behavior:** error is logged, without UnhandledPromiseRejection

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 4.1.0
- The output of `node --version`: 10.0.0
- The version and architecture of your operating system: OS X 10.10.5
- The code transpiler being used: none

**Comment by boneskull** [comment]
It's not unhandled because the `Promise` returned by your test is then caught and eaten by Mocha.  It's considered a test failure.
