### ISSUE TITLE
xdescribe executes the code

### ISSUE THREAD

**Issue by uluhonolulu** [mochajs/mocha#3630]
### Prerequisites

- [ x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code. (doesn't apply here)
- [ ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself (doesn't apply here)
- [ ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha. (doesn't apply here)

### Description
The code that runs inside an `xdescribe` block is executed, although it's not supposed to.

### Steps to Reproduce

```
xdescribe('hey', () => {
    console.log("YOOO")
});
```

**Expected behavior:** 
No console output

**Actual behavior:** 
"YOOO" in the console output

**Reproduces how often:** 
Always

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
5.2.0
- The output of `node --version`:
v8.11.2
- The version and architecture of your operating system:
Windows 7
- Your shell (bash, zsh, PowerShell, cmd, etc.):
VSCode terminal

**Comment by craigtaub** [comment]
Not quite sure if this is by design or not, but docs do suggest should not execute describe block.

**Comment by uluhonolulu** [comment]
@craigtaub I couldn't find any docs for xdescribe -- where did you see that "Docs suggest should be executed"?

**Comment by craigtaub** [comment]
@uluhonolulu sorry i meant "not" executed. xdescribe same as `.skip.`.

**Comment by boneskull** [comment]
Yes, this is by design.  The reasoning is that `.skip` is not the only way to control which suites / tests are executed.  We have `--grep`, `--fgrep` and `.only`, and they all have precedence.  The only way to ensure multiple options are respected (though the greplike options are mutually exclusive now) is to execute all suites.
