### ISSUE TITLE
too much noise if no files found

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3646]
To reproduce, run `mocha` (verbatim) in a directory with no `test/` subdir:

```
Warning: cannot find any files matching pattern "test/": 'test/'
✖ No test files found
```

We should remove the warning and use the error.  Print the dir it's looking for, but only once.  :smile:

I think @craigtaub might be good to address this since he changed some errors recently, but please unassign/re-label if you don't want to do it.

**Comment by craigtaub** [comment]
Happy to look. In this scenario perhaps it should just error and exit instead of warn first time.
