### ISSUE TITLE
Mocha not running test

### ISSUE THREAD

**Issue by bugs181** [mochajs/mocha#3659]
### Prerequisites

- [✔️] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [✔️] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [✔️] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [✔️] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

Running `npm test` appears to not run any mocha tests.

### Steps to Reproduce

```
$ npm install --global mocha
$ npm test
0 passing (3ms)
```

**Expected behavior:** [What you expect to happen]
To show 1 passing

**Actual behavior:** [What actually happens]
Shows 0 passing

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of time

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: `5.2.0`
- The output of `node --version`: `v11.0.0`
- The version and architecture of your operating system: `OSX 10.14 (18A391)`
- Your shell (bash, zsh, PowerShell, cmd, etc.): `terminal?`
- Your browser and version (if running browser tests): N/A
- Any other third party Mocha related modules (with versions): N/A
- The code transpiler being used: N/A

### Additional Information

`package.json` snippet
```
{
  "main": "index.js",
  "scripts": {
    "test": "mocha"
  },
  "devDependencies": {
    "chai": "^4.2.0",
    "mocha": "^5.2.0",
    "should": "^13.2.3"
  }
}
```

`test/test.js` snippet
```
/* eslint-disable no-undef */

var chai = require('chai')
var expect = chai.expect

describe('...', function() {
  describe('...', function() {
    expect(...).to.be.true
  })
})
```

**Comment by juergba** [comment]
There is no test to run in your "test.js". Please see [here](https://mochajs.org/#getting-started).

**Comment by bugs181** [comment]
My example `test.js` didn't cover the whole test file. I had a lot of nested `describe` functions and was under the assumption that it would work. (It appeared to work fine in Wallaby.js). The fix for me was to change some of those `describe` functions into `it` functions. Consider this issue closed.
