### ISSUE TITLE
update mochajs.org to use @mocha/docdash@^2

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3663]
[@mocha/docdash](/mochajs/mocha-docdash) should pull down changes from [docdash](/clenemt/docdash), since there are some new features in there we could use.

**Comment by outsideris** [comment]
Did you [merge them](https://github.com/mochajs/mocha-docdash/commits/master)?

**Comment by boneskull** [comment]
@outsideris Yes.  Next step is to upgrade.  I think this might want to wait on #3652.

**Comment by outsideris** [comment]
Closed by #3738
