### ISSUE TITLE
syntax highlighting on API site should use light color scheme

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3664]
It can be difficult (if not impossible) for colorblind people to read code on a dark background.

Use a color scheme with a light background.  Feel free to adapt the scheme from [mochajs.org](https://github.com/mochajs/mocha/blob/master/docs).

[`static/styles/prettify.css`](https://github.com/mochajs/mocha-docdash/blob/master/static/styles/prettify.css) is the file that needs modification.

You'll need to fork [@mocha/docdash](/mochajs/mocha-docdash) and send a PR *there*--*not* to this repo!

**Comment by amanriquez** [comment]
Hello, I am a beginner looking for first issues. Are the item bars what you're talking about? like these:
https://mochajs.org/api/mocha#asyncOnly

**Comment by outsideris** [comment]
I believe it is [these kinds of code block](https://mochajs.org/api/mocha.js.html#line503).

**Comment by lqez** [comment]
@boneskull I found a lot of light themes of code prettifier. Could you recommend a theme from https://jmblog.github.io/color-themes-for-google-code-prettify/?

**Comment by oussama-ber** [comment]
May I work on this?

**Comment by craigtaub** [comment]
There is already an open PR @oussama-ber .
