### ISSUE TITLE
🐛 Bug: mochajs.org needs a CSP (Content Security Policy)

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3667]
From [this comment](https://github.com/mochajs/mocha/pull/3652#issuecomment-452403364) by @plroebuck w/ comments by @munter.

**Comment by JoshuaKGoldberg** [comment]
Closing per https://github.com/mochajs/mocha/pull/3999#issuecomment-653881172. Someone yell at me if that's wrong. 🙂
