### ISSUE TITLE
Mocha doesn't support --experimental-worker

### ISSUE THREAD

**Issue by esromneb** [mochajs/mocha#3670]
### Prerequisites

- [ x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
I would like to test code that relies on the `worker_threads`module, however Mocha does not support passing this flag.  I figured out how to pass the flag by editing my local `node_modules/.bin/mocha` file, but I'm not sure what else (documentation) would need be updated, so I'm holding off on a PR.

### Steps to Reproduce
Use the `worker_threads` module in a test such as:

```nodejs
const { Worker, isMainThread, parentPort, workerData } = require('worker_threads');
```

Results in 
```bash
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'worker_threads'
```

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 5.2.0
- The output of `node --version`: 5.2.0
- The version and architecture of your operating system: Ubuntu 18.10
- Your shell (bash, zsh, PowerShell, cmd, etc.): bash
- Your browser and version (if running browser tests):
- Any other third party Mocha related modules (with versions):
- The code transpiler being used:

**Comment by blackening** [comment]
As a workaround, on windows, i used this and it works:
set NODE_OPTIONS=--experimental-worker && mocha -r ts-node/register server/src/**/*.spec.ts

(mocha + typescript + experimental-workers)

**Comment by Farenheith** [comment]
Just to report here, mocha worked with --experimental-worker with the following command in the package.json:
```
"test": "mocha --experimental-worker"
```
