### ISSUE TITLE
try eslint-plugin-ie11

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3679]
[eslint-plugin-ie11](https://www.npmjs.com/package/eslint-plugin-ie11) should help us cover those few things that ESLint doesn't do out-of-the-box.

If proven useful, it should be used in all code which isn't specifically found in the [whitelist of files supporting ES6](https://github.com/mochajs/mocha/blob/master/.eslintrc.yml#L20-L29).

**Comment by szb512** [comment]
This would be beneficial. We should run tests on it.

**Comment by juergba** [comment]
Outdated, we transpile our browser bundle to ES5. Has been working perfectly for more than a year now.
