### ISSUE TITLE
programmatic mocha.run synchronous reporters

### ISSUE THREAD

**Issue by brewster1134** [mochajs/mocha#3682]
i need to generate separate reports for each test file, however when i use mocha programmatically, the reporters don't generate assets (e.g. html, doc). they just seem to send everything to stdout. so then i tried running `mocha.run()` once for each file, and tried capturing stdout to create the file, but i canno get it to run synchronously.

any suggestions on how i could generate multiple reports?

**Comment by plroebuck** [comment]
https://github.com/stanleyhlng/mocha-multi-reporters
