### ISSUE TITLE
Boolean option "--delay" does not work in all cases

### ISSUE THREAD

**Issue by juergba** [mochajs/mocha#3683]
- [X] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [X] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [X] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [X] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

The output is different depending on the order of `--delay` and `--timeout` options.

node mocha **--delay --timeout 5000** .\fixtures\options\delay.fixture.js

The output is correct:
```
 delayed execution
    √ should have no effect if attempted twice in the same suite
  1 passing (12ms)
```
node mocha **--timeout 5000 --delay** .\fixtures\options\delay.fixture.js

There is no output at all.

### Steps to Reproduce

Use [this](https://github.com/mochajs/mocha/blob/master/test/integration/fixtures/options/delay.fixture.js) test file.

**Expected behavior:** result should not depend on order of option flags

**Actual behavior:** result is different

**Reproduces how often:** always

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: v6.0.0-1
- The output of `node --version`: v10.5.0
- The version and architecture of your operating system: Windows 10 Home
- Your shell (bash, zsh, PowerShell, cmd, etc.): VS Code cmd
- Your browser and version (if running browser tests):
- Any other third party Mocha related modules (with versions):
- The code transpiler being used:

### Additional Information

Mocha seems to be rather quiet when trying to use misspelled or non-existent option flags. There are no errors or warnings.

**Comment by juergba** [comment]
args.opts in options.js shows
- when the order is `--timeout 5000 --delay`:
`delay: "D:/mocha3291/mocha/test/integration/fixtures/options/delay.fixture.js"`

- when the order is `--delay --timeout 5000`:
`delay: true`

**Comment by juergba** [comment]
In "lib/cli/run-option-metadata.js" the dictionary of yargs option types is incomplete.
`boolean: []` does not include the `--delay` option.

**Comment by boneskull** [comment]
@juergba 	does adding `delay` to `boolean` fix the issue?

**Comment by juergba** [comment]
@boneskull yes, it does.

**Comment by juergba** [comment]
@boneskull ok, PR tomorrow.

**Comment by plroebuck** [comment]
Might be related to my issue as well. Does it work with "bin/_mocha"?

**Comment by juergba** [comment]
@boneskull your test does not list options without assigned type. It just lists the options already present in the dictionary of yargs option types, but not the missing ones, like `delay`.

**Comment by juergba** [comment]
@plroebuck 
without assigned type to `delay`: "bin/mocha" and "bin/_mocha" don't work.
with assigned type  to `delay`: both work
