### ISSUE TITLE
consider supporting node-report if present

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3688]
[node-report](https://github.com/nodejs/node-report) was recently pulled in to Node.js core.

it might be cool to consume this _if it exists_ to provide extra information in case of an unexpected failure.

maybe that looks like formatted output before process end, or just creation of a report file.  there may be tools already that ingest this data and output it in a pretty, human-readable format (I think the version in node core is JSON).

[node-report the userland module](https://npm.im/node-report) is also a thing, but it's a native module, so we shouldn't bother with it.  even if it's an optional dependency, users will complain about compilation errors and warnings upon installation.

any implementation should take steps to avoid use of this module in the browser.

**Comment by juergba** [comment]
I'm closing this inactive issue.
