### ISSUE TITLE
bin/mocha: don't spawn child process unnecessarily

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3690]
This _may_ or _may not_ be a good idea:

If the user has _not_ passed Node.js-specific or V8-specific arguments, import `main` from `lib/cli/cli.js` and execute it.

If the user _has_ passed Node.js-specific or V8-specific arguments, use current behavior.

Advantages:
- faster startup time

Disadvantages:
- increased potential for inconsistent behavior
- would require us to be much more careful about which executable we're using in integration tests
- would possibly require the same integration tests execute against both executables

This isn't related to process replacement, but that's something else to consider if the hacks aren't too bad.

**Comment by juergba** [comment]
closed, see #3827
