### ISSUE TITLE
After() JSON

### ISSUE THREAD

**Issue by wilsonbrito** [mochajs/mocha#3693]
### Prerequisites
5.2.0

### Description
I'm having problem in after (), when it contains two tests with the same JSON, eg:

| -fixtures
| --products
| --- charmander.json
| -test
| --products.spec.js
| --quotes.spec.js

If no products and quotes contains the same product as example, called charmander.json, does not run the project and reports as error the test 'quotes.spec.js'.

It is worth remembering that before is to create these products before the test and after to delete those products after completing the test.

Sometimes it reports the following error too:
"1)" after all "hook"

**Comment by outsideris** [comment]
I didn't get the issue. Could you provide [MCVE](https://stackoverflow.com/help/mcve)?
