### ISSUE TITLE
Impossibility to change the description in "it (string, fn)" and "describe (string, fn)" during the execution of tests

### ISSUE THREAD

**Issue by iamnikas** [mochajs/mocha#3696]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

Found a bug in the functions it () and describe () in which there is a description with variables does not change if variables change.
I use Mocha to describe the end-points Rest API and the format of test descriptions I have follows a pattern:
`/METHOD URL?PAR_1=&PAR_2= ...`

Example:
`/GET http://test.com/getAll?user_id=1234&resource=123`

Each test and block it() uses different parameter values. Each test run is accompanied by the receipt of unique parameters in the before (root before hook) block. This is done so that the state and the launch of tests are independent of the previous ones.
The set of parameters as it was said above was obtained from root before hook and written to globals in the environment array.

Code Example:
~~~~
describe('[TEST]', function() {
	it('/GET http://test.com/getAll?user_id='+global.environment.user_id+'&resource='+global.environment.resource, function(done) {
		// ... 
		done();
	})
})
~~~~

### Steps to Reproduce 

**Expected behavior:** I expect changes of values from global variables in the description of it() & describe(). The behavior of other variables (not global) may be the same as now.

**Actual behavior:** At the time of the tests I get the following spec line / GET http://test.com/getAll?user_id=undefined&resource=undefined. Variables in the description it(), describe() not updated

**Reproduces how often:** is always

### Versions

- `mocha --version`: 5.2.0 
- `node node_modules/.bin/mocha --version`: 5.2.0
- The output of `node --version`: v9.11.2

**Comment by iamnikas** [comment]
@boneskull Hi Christopher!
Can you tell me? How hard is it to fix my problem by expanding the functionality mocha?

**Comment by boneskull** [comment]
I don’t really understand. Can you please provide a repo or gist that shows the problem?

**Comment by iamnikas** [comment]
Yes of course!)

https://github.com/iamnikas/mocha_title_bug


I prepared a project with a bug. It seems to me that the title of the description in the function it('title_'+global.var, fn(){...}) & describe('title_'+global.var, fn(){...}) should change if the variable in globals has been changed.
To do this, I propose to slightly modify the --delay mode so that you can perform any logic before initializing the title descriptions in it() and describe().

Thus, such an order of execution will be possible:
1. start node app
2. load mocha modules
3. init mocha with --delay
4. any pesonal logic
5. trigged run() mocha fn
5. init test mocs, functions it(), describe()
6. Running test process

**Comment by plroebuck** [comment]
This is **not** a bug.

Suite and test titles are processed _when the file is sourced_.
If you want dynamic titles, you must use a function that returns the suite/test.

**Comment by iamnikas** [comment]
> See this [SO article](https://stackoverflow.com/questions/22465431/how-can-i-dynamically-generate-test-cases-in-javascript-node/23989138#23989138) for example of dynamic generation.

@plroebuck And if there is no possibility to make tests dynamically?

**Comment by plroebuck** [comment]
Nikita, why would creating tests dynamically not be possible?

**Comment by iamnikas** [comment]
> Nikita, why would creating tests dynamically not be possible?

The fact is that more than 3000 lines of test code have already been written, some of them have a multistage Chai nesting. Or is this not a problem?

**Comment by plroebuck** [comment]
From your code, doesn't this work?

```js
describe('[RUN TESTS]', function() {
  function genGET() {
    it('[TEST] GET http://test.com?tick=' + global.environment.tick, function(done) {
      done();
    });
  }

  genGET();
});
```

Could move your root suite `before` inside your `describe` and use local variables rather than `environment` global variable.

**Comment by plroebuck** [comment]
> > Nikita, why would creating tests dynamically not be possible?
> 
> The fact is that more than 3000 lines of test code have already been written, some of them have a multistage Chai nesting. Or is this not a problem?

You wrote 3000 lines of test code without running it at all?
Sorry, but I'd have to see more than your simple repo to answer.

**Comment by plroebuck** [comment]
An alternative approach would be to use the `--delay` flag.
See [delayed root suite](https://mochajs.org/#delayed-root-suite) in the docs.

**Comment by iamnikas** [comment]
@plroebuck What package do you advise to use instead of async-request? Axios?

**Comment by plroebuck** [comment]
```js
const http = require('http');
const axios = require('axios');

const mochaTimeout = 5000;  // Five seconds

before(async function() {
  const self = this;

  const url = 'https://api.exmo.me/v1/ticker/';
  const config = {
    maxContentLength: 32767,    // Allow up to 32k response size
    responseEncoding: 'utf8',
    responseType: 'json',
    timeout: 1000              // Wait up to 1 second for response
  };

  console.log('[ROOT] before hook');

  self.timeout(mochaTimeout);

  await axios
    .get(url, config)
    .then(function(response) {
      // random get item
      let max_items = Object.keys(response.data).length;
      let rnd_index = Math.floor(Math.random() * (max_items - 0)) + 0;

      // get item key
      let ticker = Object.keys(response.data)[rnd_index];
      return ticker;
    })
    .catch(function(err) {
      if (err.response) {
        let code = err.response.status;
        console.error(`[${code}] ${http.STATUS_CODES[code]}`);
      } else if (err.request) {
        console.error(`error: no response from ticker server in ${config.timeout} msecs`);
      } else {
        console.error(`error: request setup: ${err.message}`);
      }
      self.skip();
    })
    .then(function(ticker) {
      const url = `http://test.com?ticker=${ticker}`;
      const suite = {
        title: '[RUN TESTS]',
        tests: [
          {
            title: `[TEST] GET ${url}`,
            url: url
          }
        ]
      };

      genSuite(suite); // <= begin() abuse
    });
});

it('placeholder');

function genSuite(suite) {
  describe(suite.title, function() {
    this.timeout(mochaTimeout);
    suite.tests.forEach(genTest);
  });
}

function genTest(test) {
  it(test.title, async function() {
    const jsonMimeType = 'application/json';
    const config = {
      headers: {
        'Accept': `${jsonMimeType}, */*;q=0`
      },
      maxContentLength: 32767,    // Allow up to 32k response size
      responseEncoding: 'utf8',
      responseType: 'json',
      timeout: 1000              // Wait up to 1 second for response
    };

    await axios
      .get(test.url, config)
      .then(function(response) {
        if (response.headers['content-type'] !== jsonMimeType) {
          throw new Error('unacceptable response');
        }

        console.log(response);
        // assertions here...
      });
  });
}
```
