### ISSUE TITLE
🛠️ Repo: Two-column lists in the docs should not be the default style for lists

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3702]
This should not be the default list style:

![image](https://user-images.githubusercontent.com/924465/51947480-e6e2a800-23d9-11e9-924d-6dafdbec79c4.png)

Change the stylesheet to display a "normal" list unless we apply a specific class for two-column display.  I think it's OK to use in some places, but not for *all* lists.

unless there's a way to specify the class in our markdown compiler (not sure), just use html for the ones we keep.  features and table of contents are good to keep... not sure about the rest.

For implementors:

To see changes locally, run `npm start docs` and open up `docs/_dist/index.html` with your browser. You can also do `npm start docs.watch` to rebuild as you work (you'll still have to reload).

**Comment by crossaaron** [comment]
would like to take this one.  any documentation on getting the local development environment running?  struggling with Karma/saucelabs auth process  to pass all tests

**Comment by boneskull** [comment]
@crossaaron the `wd` module is only used for tests on SauceLabs, which you aren't running locally, so not sure what the problem was there.

at any rate, changes here should not affect any browser tests; the only potential failure would be a linting error.

**Comment by marjys** [comment]
Hi! I'm new to Open Source and was looking for a _good first issue_ to start contributing. May I give it a try? (#3702)
Thanks in advance!
