### ISSUE TITLE
duplicated header anchor links on mouseover

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3714]
1. Go to https://next.mochajs.org
1. Mouseover a heading

![image](https://user-images.githubusercontent.com/924465/52230074-538ef400-286b-11e9-89ad-c0e72fb8ba7d.png)

Remove the `#`; keep the other one.

cc @Munter

**Comment by cjdeleon62** [comment]
@boneskull @Munter mind if I take this issue?

**Comment by Munter** [comment]
Is this still a thing? I thought I fixed that one. If it's still a problem it might be related to the markdown auto header linking functionality

**Comment by jd2rogers2** [comment]
i am still seeing the issue so put in a fix (my first, so def open to feedback)
however, if no one else is seeing it maybe this should be closed?
