### ISSUE TITLE
smart quotes and smart hyphens in docs

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3716]
It’d be cool if we could get “smart quotes”—and hyphens—in our documentation. 

that’s probably going to be a markdown processor or eleventy plugin. ideally this would apply to API docs as well but that can be a separate issue since the tools are different (there’s another issue about consolidating the markdown tools somewhere)

**Comment by shobhu98** [comment]
Please assign me to this one

**Comment by boneskull** [comment]
I can’t but would be happy to see a PR to fix!

**Comment by boneskull** [comment]
I fixed this on accident in #4291
