### ISSUE TITLE
Project-local custom reporter launching binary mocha

### ISSUE THREAD

**Issue by victorhugojt** [mochajs/mocha#3718]
### Prerequisites

- [ X] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [X] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [X] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [X] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

When launch mocha programatically using the _mocha binary file and try to set up a local custom reporter mocha doesn't accept it and try to look for it in a default reporters or in a installed module

### Steps to Reproduce

Use the binary mocha

```
command = `${process.cwd()}/node_modules/.bin/_mocha`;
consoleParameters.push('--reporter', '../../../customReporter.js');
const runTestProcess = child.fork(command, consoleParameters);

------------------Transpiled customReporter.js-----------------------

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const mocha_1 = require("mocha");
class CustomReporter {
    constructor(runner) {
        mocha_1.reporters.Base.call(this, runner);
        let passes = 0;
        let failures = 0;
        //tslint:disable
        console.log('Custom Reporter !!!!!');
        runner.on('pass', function (test) {
            passes++;
            console.log('pass: %s', test.fullTitle());
        });
        runner.on('fail', function (test, err) {
            failures++;
            console.log('fail: %s -- error: %s', test.fullTitle(), err.message);
        });
        runner.on('end', function () {
            console.log('end: %d/%d', passes, passes + failures);
        });
    }
}
exports.CustomReporter = CustomReporter;
```

**Expected behavior:** [What you expect to happen]
Able to listen runner events
**Actual behavior:** [What actually happens]

```
/../../../../node_modules/mocha/lib/mocha.js:520
  var reporter = new this._reporter(runner, options);
                 ^

TypeError: this._reporter is not a constructor
    at Mocha.run (/../../../../node_modules/mocha/lib/mocha.js:520:18)
    at Object.<anonymous> (/../../../../node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
always
### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
- The output of `node --version`:
- The version and architecture of your operating system:
- Your shell (bash, zsh, PowerShell, cmd, etc.):
- Your browser and version (if running browser tests):
- Any other third party Mocha related modules (with versions):
- The code transpiler being used:

**Comment by plroebuck** [comment]
You didn't provide enough information to help you.
Fill out the "Versions" section above so I'll at least be able to tell what/where to look.

**Comment by boneskull** [comment]
a reporter must be exported as `module.exports = MyReporter`
