### ISSUE TITLE
Mocha TypeError fn is not a function

### ISSUE THREAD

**Issue by Ch84** [mochajs/mocha#3720]
### Description
Mocha won't run, leaving me a `TypeError` message that 'fn' is not a "function".

What do I have to do to solve this?

Thanks in advance!

See attached image.
![mochatypeerror](https://user-images.githubusercontent.com/33604841/52489131-c11b8700-2bc1-11e9-99d6-fe68738cfc5a.JPG)

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]
Mocha should run the script.

**Actual behavior:** [What actually happens]
Initiates searching for the driver and finding Chrome but then crashes.
Script won't run at all

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: **5.2.0**
- The output of `node --version`: **10.15.0**
- The version and architecture of your operating system:
  - OS: **Windows 10 version 1803 OS-Version 17134.523**
  - Architecture: **??????**
- Your shell (bash, zsh, PowerShell, cmd, etc.): **bash**
- Your browser and version (if running browser tests): **Google Chrome 72.0.3626.96**
- Any other third party Mocha related modules (with versions):
  - **Selenium WebDriver ??????**
  - **Selenium WebDriver Testing ??????**
- The code transpiler being used: **None**
- Editor: **Visual Studio Code**

**Comment by plroebuck** [comment]
Actually filling in the template is required -- no idea what version you're running, OS, what you did...

**Comment by Ch84** [comment]
### Steps to Reproduce
**Expected behavior:** [Mocha should run the script]

**Actual behavior:** [Initiates searching for the driver and finding Chrome but then crashes, script won't run at all]

**Reproduces how often:** [100%]

### Versions
* The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 5.2.0
* The output of `node --version`: 10.15.0
* The version and architecture of your operating system: Windows 10 version 1803 OS-Version 17134.523
* Your shell (bash, zsh, PowerShell, cmd, etc.): bash
* Your browser and version (if running browser tests): Google Chrome 72.0.3626.96
* Any other third party Mocha related modules (with versions): None
* The code transpiler being used: Visual Studio Code

**Comment by craigtaub** [comment]
Pease send details of what is in your script, including what you expect for output. Looking at the screenshot looks like the error is from selenium-webdriver.

**Comment by Ch84** [comment]
Here is my code:

var webdriver = require ('selenium-webdriver'),  
    { suite, it, afterEach, beforeEach } = require ('selenium-webdriver/testing');
By = webdriver.By,
until = webdriver.until;
var driver;

// Describe the scenario and write function

suite('Google Search Engine Scenario', function() {
    this.timeout(50000);
    beforeEach(function() {

    // Set up the driver and URL 

    driver = new webdriver.Builder().forBrowser('chrome').build();
    driver.get('https://www.google.se');

    });

    // Driver will quit after each function

    afterEach(function() {
    driver.quit();

    });

    it ('Inputs text in the text search field', function() {

        var textField = driver.findElement(By.name('q')).sendKeys('Selenium Webdriver');
        driver.wait(function() {

            return textField.getNameValue('q').then(function(result) {

                return result === '1';

            });

        });

    }, 5000);

});

it ('works with mocha', function() {

    var searchBtn = driver.findElement(By.name('btnK'));
    searchBtn.click();
    driver.wait(until.elementLocated(By.name('btnK')), 5000).getText().then(function(txt) {

        console.log("Clicked button successfully: " + txt);

    });

});

Anything missing?

**Comment by Ch84** [comment]
Expected output is that it should start and run the script, I checked the documentation and there has been some changes and I read that I am supposed to use suite instead of describe, since it first gave me the error that describe is not a function. So that is what I have been finding out so far, but I don't understand what could be the problem with selenium-webdriver in this case.

**Comment by plroebuck** [comment]
* Replace `suite` with `describe` in both places (they perform the same function, but `suite` is for "tdd" interface, while `describe` is for "bdd" interface). Don't mix'n'match. Where did you read that?
* Should move `it`(works with mocha) within the `describe`, or your driver will not be setup (since it's in the root suite).
* The `it` already within `describe` passes `5000`argument -- Mocha's `it` only takes 'title' and 'function' arguments.

**Comment by Ch84** [comment]
Changed the code to this:

var webdriver = require ('selenium-webdriver'),  
    { describe, it, afterEach, beforeEach } = require ('selenium-webdriver/testing');
By = webdriver.By,
until = webdriver.until;
var driver;

// Describe the scenario and write function

describe('Google Search Engine Scenario', function() {
    this.timeout(50000);
    beforeEach(function() {

    // Set up the driver and URL 

    driver = new webdriver.Builder().forBrowser('chrome').build();
    driver.get('https://www.google.se');

    it ('works with mocha', function() {

        var searchBtn = driver.findElement(By.name('btnK'));
        searchBtn.click();
        driver.wait(until.elementLocated(By.name('btnK')), 5000).getText().then(function(txt) {
    
            console.log("Clicked button successfully: " + txt);

            console.error("<<functname>>");
    

    });

    // Driver will quit after each function

    afterEach(function() {
    driver.quit();

    });

    it ('Inputs text in the text search field', function() {

        var textField = driver.findElement(By.name('q')).sendKeys('Selenium Webdriver');
        driver.wait(function() {

            return textField.getNameValue('q').then(function(result) {

                return result === '1';

            });

        });

    }, 5000);

});


    });

});

But getting the same error msg as before using describe.

See attached image.
![mochadescribeerror](https://user-images.githubusercontent.com/33604841/52536379-08d51680-2d5a-11e9-8b3a-b139e0a9efb8.JPG)

Any ideas?

**Comment by plroebuck** [comment]
This work?

***"example.spec.js"***:
```js
const debug = require('debug')('testme');
const {By, Key, until} = require('selenium-webdriver');
const {suite} = require('selenium-webdriver/testing');

// Describe the scenario and write function
suite(function(env) {
  debug('env:', env);

  describe('Google Search Engine Scenario', function() {
    let driver;

    before(async function() {
      const debug = debug.extend('before');
      debug('driver setup');
      driver = await new env.builder().build();
    });

    after(function() {
      const debug = debug.extend('after');
      debug('driver teardown');
      driver.quit();
      driver = null;
    });

    it('Inputs text in the text search field', async function() {
      const debug = debug.extend('it');
      debug('fetching site');
      await driver.get('https://www.google.se');
      debug('finding element');
      let q = await driver.findElement(By.name('q'));
      debug('sending input');
      await q.sendKeys('webdriver', Key.RETURN);
      await driver.wait(
        until.titleIs('webdriver - Google Search'),
       1000);
      });
      await () =>  { debug('done') };
    });
  });
});
```

```sh
$ SELENIUM_BROWSER=chrome mocha --timeout 12000 example.spec.js
```

**Comment by Ch84** [comment]
Created new file and wrote that code.

But gives me a syntax error

![syntaxerrormochadebugcode](https://user-images.githubusercontent.com/33604841/52537281-31164280-2d65-11e9-8bb5-f66955d114d9.JPG)

I have searched the code for misspellings, missed define of variables e.t.c. and corrected all mistakes I made, but still no difference, the syntax error remains.

Here is my version of the code:

const debug = require ('debug')('testme');
const {By, Key, until} = require ('selenium-webdriver');
const {suite} = require ('selenium-webdriver/testing');

// Describe the scenario and write function

suite(function(env) {

    debug('env:', env);

    describe('Google Search Engine Scenario', function() {

        let driver;

        before(async function() {

            const debug = debug.extend('before');
            debug('driver setup');
            driver = await new env.builder().build();

        });
        
        after (function() {

            const debug = debug.extend('after');
            debug('driver teardown');
            driver.quit();
            driver = null;

        });

        it('Inputs text in the text search field', async function() {

            const debug = debug.extend('it');
            debug('fetching site');
            await driver.get('https://wwww.google.se');
            debug('finding element');
            let q = await driver.findElement(By.name('q'));
            debug('sending input');
            await q.sendKeys('webdriver', Key.RETURN);
            await driver.wait(
               until.titleIs('webdriver - Google Search'), 
               1000);
        });

        await () => {debug('done')};

        });

    });

});

**Comment by plroebuck** [comment]
Corrected given code and provided working [step-by-step instructions](https://github.com/mochajs/mocha/issues/3720#issuecomment-462152731) for sample project using Selenium WebDriver using Chrome.

**Comment by plroebuck** [comment]
@Ch84, you have any problems using instructions?

**Comment by Ch84** [comment]
Got a problem with git bash but i think i have been figuring out why. I will try that solution first and get back to you. Thanks in advance!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by Ch84** [comment]
Just as I thought that error message depended on that I forgot to turn on the administrator for git bash denying me some permissions :). With that solved and done everything I got this far anyway. Attaching image.
![gitbasherrormsgmochastart](https://user-images.githubusercontent.com/33604841/52736680-b51d3400-2fca-11e9-9597-b2df0666aa30.JPG)

**Comment by plroebuck** [comment]
Well, it's sort of working. Something isn't right with ChromeDriver installation; WebDriver can't find the download. Can try reinstalling it and hopefully see something in the output...
```sh
$ npm install --save-dev chromedriver
```

I verified this on **macOS 10.13.6**...
[Dilbert - Computer Holy Wars](https://dilbert.com/strip/1995-06-24)

**Comment by Ch84** [comment]
still same error msg so I tried to just actually copy my chromedriver.exe file to the same path as my javascript file and then try to run again. It found the webdriver and started to run chrome, so my guess was right anyway it was looking for the chromedriver.exe file. Although the tests failed, but I guess I just now have to continue to play around with my code and try to get further =p. Anyway here is dumps on how it looks now.
![gitbashmocharunningwithchrome_test_suite_failed0](https://user-images.githubusercontent.com/33604841/52815764-c97f3080-309f-11e9-8fd5-f2abb1a294ae.JPG)
![gitbashmocharunningwithchrome_test_suite_failed1](https://user-images.githubusercontent.com/33604841/52815772-cdab4e00-309f-11e9-81ff-8011bb3d3040.JPG)

**Comment by Ch84** [comment]
And one more question is, can I access this project from the Windows GUI? Since I am using Visual Studio Code. In that case how do I do that?
