### ISSUE TITLE
make sponsors logo more readable when logo is white in homepage

### ISSUE THREAD

**Issue by outsideris** [mochajs/mocha#3736]
In [homepage](https://mochajs.org/), some sponsors's logo is white. So, people can't realize who is support us. 
We should make them to people see the logo well like background color or shadow.

<img width="943" alt="2019-02-16 18 02 34" src="https://user-images.githubusercontent.com/390146/52897195-0c164980-3215-11e9-97fb-41c01eec4ea2.png">

**Comment by boneskull** [comment]
I'll ask OC about this.

**Comment by znarf** [comment]
It’s tricky. The simplest would be to contact the sponsor to upload the white logo with a background color, or a non-white logo that works well on white backgrounds.

**Comment by boneskull** [comment]
Thanks @znarf.  I asked (in Slack):

> is that something OC could do for us?  are logos unique to each OC, or unique to a company?

**Comment by outsideris** [comment]
There were some changes for background in OC. It looks ugly with our website.

<img width="851" alt="스크린샷 2019-06-04 12 45 30" src="https://user-images.githubusercontent.com/390146/58849777-a7e59b80-86c6-11e9-9bd3-39e254f562ca.png">

**Comment by znarf** [comment]
@outsideris Sorry for the breaking change, we effectively shipped a major refactoring which is related to that. 

I think you can avoid that behavior by switching from `.jpg` to `.png` while including these images. Before: `https://opencollective.com/mochajs/backer/1/avatar.jpg` After: `https://opencollective.com/mochajs/backer/1/avatar.png`

On our side, we'll check if there is a simple fix to have the background default to white when using the jpg format.

**Comment by outsideris** [comment]
@znarf Thank you. We will fix them.

**Comment by znarf** [comment]
I fixed the black background issue. https://github.com/opencollective/opencollective-images/pull/70 It's being deployed. Still doesn't hurt to migrate to png.

**Comment by outsideris** [comment]
@znarf Thank you. It looks great.
