### ISSUE TITLE
this.skip() - bug summary

### ISSUE THREAD

**Issue by juergba** [mochajs/mocha#3740]
#### 1. `this.skip()` in `beforeEach` hooks
Incorrect hook pattern.
All `beforeEach` hooks are executed, but `afterEach` hooks are skipped completely, see #2546
=> fixed: #3741

#### 2. async `this.skip()` in `beforeEach` hooks
results in a "Uncaught async skip; aborting execution", see [test](https://github.com/mochajs/mocha/blob/master/test/integration/fixtures/pending/skip-async-beforeEach.fixture.js)
`before` hooks seem to work async though, and as per user documentation it should work.
=> fixed: #3745 

#### 3. `this.skip()` in `it` tests
does not work correctly, since `beforeEach` hooks are executed, but `afterEach` hooks do not run.
=> fixed: #3859

#### 4. `this.skip()` in `afterEach` hooks
Incorrect, since already passed/failed tests are set to `pending` retrospectively. No tests are skipped at all.
=> definition of use case still pending

#### 5. `this.skip()` in `after` hooks
Incorrect, since already passed/failed tests are set to `pending` retrospectively. No tests are skipped at all.
=> soft deprecation: #3719
=> disallow usage: #4136

#### 6. `this.skip()` with `--allow-uncaught`
Incorrect, since silently aborts execution after first `this.skip()`.
=>fixed: #4030 

### Versions
current master

**Comment by mrstux** [comment]
Would really like to see this.skip() from an AsyncStatus test result in the afterEach being called. 

In our test suite, the this.skip() is being called from a function invoked by the test which checks prerequisites, and if they fail, it calls skip(), which as you know, throws an exception which aborts the outer function. 

Except the cleanup hook doesn’t get called, and should.

**Comment by marmik18** [comment]
i am facing issue with `this.skip()` in `it` tests. 
the test does not skip.

**Comment by JoshuaKGoldberg** [comment]
Closing as this just points to other issues/PRs.
