### ISSUE TITLE
CoffeeScript tests after v6.0.0 and suite return value check

### ISSUE THREAD

**Issue by wdavidw** [mochajs/mocha#3744]
### Prerequisites

- [x ] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

Issue #3243 shipped with v6.0.0 throw a deprecation warning or an error if `--throw-deprecation` is enabled with all CoffeeScript tests since the language support implicit returns.

### Steps to Reproduce

The following minimalist test case:

```coffee
describe 'My Suite', () ->
  it 'run a test', () ->
    console.log 'yes'
```

Throw the error "DeprecationWarning: Suites ignore return values. Suite "My Suite" in /package/test/my/test.coffee returned a value; this may be a bug in your test code"

A temporary workaround include returning `undefined`:

```coffee
describe 'system.authconfig', () ->
  it 'fuck around', () ->
    console.log 'yes'
  undefined
```

### Versions

- The output of `npx mocha --version` : 6.0.0
- The code transpiler being used: CoffeeScript
- Other information not relevant

### Additional Information

I understand the motivation behind #3243. One way to please everyone is to detect if the return value found in the suite is not the same as the one returned by `it`.

**Comment by plroebuck** [comment]
This works though, right?
```coffeescript
describe 'My Suite, () ->
  it 'run a test, () ->
    console.log 'yes'
    return
```
I remember cleaning up my project after enabling strict settings from `coffeelint`.

**Comment by wdavidw** [comment]
The problem is not inside `it` but inside `desribe` so this example wouldn't work, it shall be

```coffee
describe 'My Suite, () ->
  it 'run a test, () ->
    console.log 'yes'
  return
```

**Comment by plroebuck** [comment]
OK. So one `return` per `describe`, not per `it`. Just checking in case example misformatted.
But it doesn't occur without Node `--throw-deprecation` argument?

**Comment by wdavidw** [comment]
Exact... until version 7.0.0!

**Comment by jakesjews** [comment]
This is preventing my team from upgrading too. I'd rather not suppress all deprecations. Perhaps some sort of option to disable the return check would work? We have a few thousand tests so it would be a lot of work to add return undefined to every describe.

**Comment by plroebuck** [comment]
How many `describe`s in your tests?

Had quickly thought of checking for `".coffee"` in `require.extensions`, but that wouldn't be of any help for source already transpiled... We run a few tests against CoffeeScript, but didn't think to add one for implicit returns.

**Comment by wdavidw** [comment]
Same for me, among others, the csv package implements all tests in coffee.

**Comment by jakesjews** [comment]
We have 2215 describes

**Comment by wdavidw** [comment]
What about my proposal, checking if the return value is an instance of what it return ? Actually, does `it` really need to return something? Can't it return undefined ?

**Comment by plroebuck** [comment]
Was supposed to help solve this...
```js
describe("my suite", async function() {
  await Promise.resolve();
  it("does a thing", function() {
    assert(false);
  });
});
```

**Comment by wdavidw** [comment]
@jakesjews 2215 in one package ? that is a good score. 154 for the csv package, 390 for nikita

**Comment by wdavidw** [comment]
@plroebuck, yes, that is what i meant when mentioning #3744 in the title (and not in the contents, issues shall be linked now) and saying that I understood the motivation.

**Comment by jakesjews** [comment]
@wdavidw this is in a larger application with backend and frontend

**Comment by plroebuck** [comment]
> This is preventing my team from upgrading too. I'd rather not suppress all deprecations.
> Perhaps some sort of option to disable the return check would work? We have a few
> thousand tests so it would be a lot of work to add return undefined to every describe.

Keep in mind that Mocha-6.0 has several large rewrites of portions of the codebase.
We're not coming out with Mocha-7.0 _anytime_ soon; after all, this version _just_ rolled out.
So don't use the Node `--throw-deprecation` argument for now, and we'll get this fixed soon.

**Comment by plroebuck** [comment]
> @plroebuck, yes, that is what i meant when mentioning #3744 in the title (and not in the contents, issues shall be linked now) and saying that I understood the motivation.

I knew you understood. I posted the original motivation code, edited that, then reposted. Edit didn't go through, but didn't notice...

**Comment by jakesjews** [comment]
@plroebuck sounds good to me. When you do decide how you want to go about fixing this let me know and I can get started on a PR to implement it.

**Comment by wdavidw** [comment]
Thanks, keep up with the good work and don't forget us

**Comment by boneskull** [comment]
OK, so an option isn't really workable for this.  We'd have to support it going forward, and it seems kind of silly to do that just for CoffeeScript.  Literally everybody using CoffeeScript would want to use it, right??

The original intent, IIRC, was to avoid people attempting to return `Promise`s from suites.

So three (3) potential fixes:

1. Only warn when a `Promise` is returned from a suite.  Other values returned from a suite are *likely* not as potentially harmful.  But we can only do so much.
1. Special-case for coffeescript.  Detect via `require.extensions`, probably.
1. Just back out the deprecation.  In the future, it may be workable & desirable to allow async suites (enough people have asked for it anyway!).  Deprecating it only to re-introduce it with a *different* behavior would potentially cause more problems and work for users than simply introducing the different behavior.

I'm inclined to back it out.  There's only so much we can do to save users from misusing the API...

**Comment by boneskull** [comment]
PR that backs out the deprecation: #3759

**Comment by plroebuck** [comment]
I briefly considered the `require.extensions` route, but this wouldn't help with post-transpiled CoffeeScript code, if someone went that route.

**Comment by wdavidw** [comment]
I am myself using a lot of ".coffee.md" literate format. Also, why a you not considering my solution, CoffeeScript will return the last element, which in most case, shall be the result of calling `it`. We could just accept that.

**Comment by boneskull** [comment]
@wdavidw because suite callbacks don’t necessarily end with anything in particular. could be it, a hook, could be other code entirely
