### ISSUE TITLE
Standard xunit reporter throws an error even when all tests pass

### ISSUE THREAD

**Issue by peni4142** [mochajs/mocha#3747]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

The programttically use of the standard xunit reporter ends in an error

### Steps to Reproduce

```
var Mocha = require("mocha");
let mocha = new Mocha({
    ui: "tdd",
    reporter:"xunit"
    reporterOptions: {
        output: "c:\\any\\directory\\file.xml",
        suiteName: "anyName",
    }
});

mocha.addFile("File.test.js");
mocha.run():
```

**Expected behavior:** [What you expect to happen]
no throw at the end, if all tests pass

**Actual behavior:** [What actually happens]
```
C:\__GIT\VSCX\node_modules\mocha\lib\reporters\xunit.js:126
      fn(failures);
    at WriteStream.<anonymous> (C:\__GIT\Repo\node_modules\mocha\lib\reporters\xunit.js:126:7)
    at Object.onceWrapper (events.js:277:13)
    at WriteStream.emit (events.js:189:13)
    at finishMaybe (_stream_writable.js:641:14)
    at stream._final (_stream_writable.js:619:5)
    at WriteStream._final (internal/fs/streams.js:263:3)
    at callFinal (_stream_writable.js:612:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
Using reporter "spec":
![image](https://user-images.githubusercontent.com/33463108/53035813-93aec300-3476-11e9-82a4-f67335bdcf70.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

- The output of `mocha --version:5.2.0` and `node node_modules/.bin/mocha --version:5.2.0` (Yeah I have both)
- The output of `node --version`:v10.15.1
- The version and architecture of your operating system:
- Your shell (bash, zsh, PowerShell, cmd, etc.): cmd
- Your browser and version (if running browser tests): NodeJS
- Any other third party Mocha related modules (with versions):---
- The code transpiler being used:

**Comment by plroebuck** [comment]
Fixed #3580 in Mocha-6.0.

For Mocha-5.2, 
```js
function exitMocha(code) {
  code = code ? 1 : 0;
  process.exitCode = code;

  var draining = 0;
  function done() {
    if (!draining--) {
      process.exit(code);
    }
  }

  [process.stdout, process.stderr].forEach(function (stream) {
    draining++;
    stream.write('', done);
  });

  done();
};

mocha.run(exitMocha):
```
