### ISSUE TITLE
weird message when a non-Error object is thrown

### ISSUE THREAD

**Issue by fr0** [mochajs/mocha#3757]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

```
Error: the string "Configuration not loaded" was thrown, throw an Error :)
```

Thjs "Configuration not loaded" message is coming from my code. I'm guessing mocha is saying the code should be throwing an `Error` object, but the message it's providing is weird and confusing. And I have no idea why there's a smiley face at the end?

**Expected behavior:** [What you expect to happen]

Seems like a better message would be something like:

```
Error: the string "Configuration not loaded" was thrown. It is recommended that Error objects are used for exceptions instead of strings.
```

Although I'm not sure mocha even needs to be policing this. I think `Error: the string "Configuration not loaded" was thrown.` is sufficient.

**Actual behavior:** [What actually happens]

The message provided by mocha is weird, confusing, and overly cutesy.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time.

### Additional Information

Here's the line of code:
https://github.com/mochajs/mocha/blob/118c9aeab5b6192d627b0b369e43584ab8f9f0b7/lib/runner.js#L1002

**Comment by plroebuck** [comment]
> I'm guessing mocha is saying the code should be throwing an `Error` object, ...
> ... I think `Error: the string "Configuration not loaded" was thrown.` is sufficient.

Mocha's error message hints to throw an `Error`, not a string.
The hint seems necessary -- nothing weird or confusing about it.
If you think the emoticon is overly cutesy, well... you may have a point there.
