### ISSUE TITLE
fix test flake in Node.js v6/v8

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3769]
see this build failure: https://travis-ci.org/mochajs/mocha/jobs/497987351#L1728

not sure what's happening here... would welcome help to address it

**Comment by szb512** [comment]
Well the build is a success, try uploading a different log.

**Comment by boneskull** [comment]
ugh, apparently if you restart a travis job, the job is overwritten.

I'll close this until I see it again.

**Comment by boneskull** [comment]
OK, I believe this is the same failure, in Node v8 this time:

https://travis-ci.org/mochajs/mocha/jobs/498906350#L1746

**Comment by juergba** [comment]
The support of Node v8 has been dropped.
