### ISSUE TITLE
Synchronous tests don't run when running test suite with --delay flag 

### ISSUE THREAD

**Issue by antonyshau** [mochajs/mocha#3770]
**Description:**
Synchronous test won't kick off when running a test suite with --delay flag. However, tests that have async setup and attached `run()` callback work just fine

**Steps to reproduce:** 

1. write a test that requires some async setup... make sure to attach `run()` callback: 
```
Promise.all(someAsyncFunction).then(runTests(); run())
```
2) in the same test folder, write a simple test that doesn't require any setup...hence doesn't require `--delay/run()`: 
```
 describe('foobar', () => {
    it('test positive', () => {
      expect(2).to.equal(2);
    })

    it('test negative', () => {
      expect(2).to.equal(3);
    })

  });
```
3) run tests using "all" wildcard - `mocha --delay **/*test.js` (OR run only sync test - `mocha --delay **/sync.test.js`)

**Expected behavior:** 
Both tests run. Sync test without `run()` callback should still run

**Actual behavior:** 
Test without `run()` callback doesn't run unless you wrap it in an async function: 
```
setTimeout(
describe('foobar', () => {
    it('test positive', () => {
      expect(2).to.equal(2);
    })

    it('test negative', () => {
      expect(2).to.equal(3);
    })

  });
,100)
```

**Reproduces how often:** 
Can reproduce consistently. 10 out of 10 

**Versions**
v5.2-v6

**System:** 
- MacOS 10.13.6 (64bit)
- no code transpilers 
- node - 10.11.0
- npm - 6.8.0

**Comment by juergba** [comment]
The `--delay` flag defers the "root suite" and therefore all nested tests within, wether sync or async.
One of your test files should include the call to the global `run()` anyway.

**Comment by plroebuck** [comment]
Typical usage would be to have a file named **"test/async-setup.js"** (or whatever) that would perform all the asynchronous setup and invoke `run` when ready.
```js
Promise.all([asyncSetup1, asyncSetup2, ..., asyncSetupN])
  .then(function(values) {
    run();
  });
```
And invoke Mocha.
```sh
$ mocha --require 'test/async-setup.js' --delay 'test/**/*.spec.js'
```
There's no "us/them" concept for which tests get run.

**Comment by antonyshau** [comment]
@juergba @plroebuck ...thanks for looking into this. I think There was some misunderstanding on my end on how to run tests all at the same time :) (https://github.com/mochajs/mocha/issues/3771)
I followed  your suggestions ...and things seem to be working just fine now. Appreciate your help on this. 
Closing the issue
