### ISSUE TITLE
Only one test file gets executed when running command with 'all' wildcard and --delay flag

### ISSUE THREAD

**Issue by antonyshau** [mochajs/mocha#3771]
**Description:**
Only one test file gets executed when running tests with "all" wildcard and `--delay` flag. 

**Steps to reproduce:**
1. create 2+ test files with test code that requires some async setup. For example: 
```
Promise.all(asyncSetUp).then(runTests(); run())
```
2. make sure to pass `run()` callback into both tests so that `--delay` functionality works as expected
3. place test files in the same test folder
4. run tests using the following command: `mocha --delay **/*.test.js` 

**Expected behavior:** 
Both test files get executed

**Actual behavior:** [What actually happens]
Only one of 2 files will run 

**Reproduces how often:**
100%

**Versions:**
v5.2-6

**System:**
* MacOS 10.13.6 (64bit)
* no code transpilers
* node - 10.11.0
* npm - 6.8.0

**Comment by juergba** [comment]
Have you tried to put the global `run()` in just one of the test files?

**Comment by antonyshau** [comment]
@juergba , you are right. Having just one `run()` globally (in just one file) does the trick. I guess we can close this issue. Something I might have missed reading through the documentation.
