### ISSUE TITLE
--interfaces and --reporters should be --list-interfaces and --list-reporters, respectively

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3777]
1. `--reporters` would be nice to alias to `--reporter` if/when we support multiple reporters; so let's use `--list-reporters` instead
1. `--interfaces` should be `--list-interfaces` for consistency :smile:

I probably would *not* call this change semver-major, even if it might be per our usual interpretation.  @mochajs/core thoughts?

**Comment by craigtaub** [comment]
Change makes sense.
Whats reasoning behind _not_ major bump? Feels potentially-risky to only minor.

**Comment by plroebuck** [comment]
Would break my 'abao' package, for one. Given `--reporters` cmdline option has been there for years, how would an external package trying to do this know the meaning had completely changed?

Not saying it's a bad idea. But it has definite **major** implications...

**Comment by szb512** [comment]
Change ABSOLUTELY makes sense.

**Comment by boneskull** [comment]
My rationale for not being a major change would be that the functionality (if you want to call it that) is akin to `--help`.  

@plroebuck 	I guess I didn't really expect any "machine" to be attempting to read that output. I should have known better...

What is `abao` doing with that output?

**Comment by plroebuck** [comment]
Abao lists available reporters so, in my case, it's just a pass-thru. My project generates BDD tests dynamically and runs them. Mocha is an implementation detail of how they get run, but much of that is achieved by programmatic invocation.

To any package spawning Mocha (and mine certainly wasn't the only one), your cmdline API _is_ your "public" API.
