### ISSUE TITLE
Website HTML tweaks

### ISSUE THREAD

**Issue by plroebuck** [mochajs/mocha#3783]
### Description

**"docs/_includes/default.html"**

* Fix `<title>` (solution courtesy of @XhmikosR)
```html
    <title>{{ title }}</title>
```

* Remove the `shortcut` relationship. [While allowed, it's meaningless](https://github.com/whatwg/html/commit/95978ef2b115e7dbd03b5b5e8d78c00340119588). See [here](https://mathiasbynens.be/notes/rel-shortcut-icon) also.
```html
<link rel="icon" href="favicon.ico" />
```
 
* Mocha logo
  * Change the `alt` attribute to "Mocha logo"
  * Add an `id` attribute.
  * Migrate `width` and `height` attributes to stylesheet
```html
<img
  id="mocha-logo"
  src="/images/mocha-logo.svg"
  alt="Mocha logo" />
```
**"docs/css/style.css"**
```css
#mocha-logo {
  width: 192px;
  height: 192px;
}
```

* Convert the `<span>` tag to a `<div>`. [Inline tags may **not** contain block tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements#Conceptual_differences).
```html
<span>
  <a href="https://mochajs.org">mochajs.org</a> is licensed under a
  <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"
          >Creative Commons Attribution 4.0 International License</a>.
   <p>
     <em>Last updated: {{ 'now' | date: '%a %b %d %H:%M:%S %Y' }}</em>
  </p>
</span
```

* Add "rel=home" protocol for Mocha URL. Append slash ("/") to end of URL.
```html
  <a rel="home" href="https://mochajs.org/">mochajs.org</a> is licensed under a
```

* Use "https" protocol for CC license `<a>` "href" URL
```html
  <a rel="license" href="https://creativecommons.org/licenses/by/4.0/"
          >Creative Commons Attribution 4.0 International License</a>.
```

* Convert the`<p>/<em>` tags with the following `<dl>` embedding `<time>`
```html
  <dl class="dl-inline last-modified">
    <dt>Last updated</dt>
    <dd>
      <time
        itemprop="lastModified"
        datetime="{{ 'now' | date: '%Y-%m-%dT%H:%M:%SZ' }}">
              {{ 'now' | date: '%a %b %d %H:%M:%S %Y' }}
      </time>
    </dd>
  </dl>
```
**"docs/css/style.css"**
```css
.last-modified {
  font-style: italic;
}
.dl-inline dt, .dl-inline dd {
  display: inline;
  margin: 0;
}
.dl-inline dt:after {
  content: ': ';
}
.dl-inline dd + dt:before {
  content: '';
  display: block;
}
```

* Annotate _all_ links to outside URLs with these relations:
  * [`external`](http://microformats.org/wiki/rel-external) - Indicate link is not part our website
  * [`noopener`](https://developers.google.com/web/tools/lighthouse/audits/noopener) - [**Security**](https://mathiasbynens.github.io/rel-noopener/)

```html
<a href="https://apex.sh/ping/" rel="external noopener" target="_blank">
```
### Discussion
* Determine if we should also annotate with relation.
  * [`nofollow`](http://microformats.org/wiki/rel-nofollow#Abstract) - Indicate not an endorsement. See [here](https://stackoverflow.com/questions/19481030/external-links-when-use-rel-external-or-rel-nofollow/50772627#50772627) also.
 * Should we add `favicon`-like [icons for mobile browsers](https://stackoverflow.com/a/25961390)?

**Comment by rscotchmer** [comment]
Hi!  I'd like to tackle this issue if that's okay!

**Comment by XhmikosR** [comment]
I'd add https://validator.w3.org/nu/?doc=https%3A%2F%2Fmochajs.org%2F and also do some HTML5 hygiene like removing the useless end tags (`/>` -> `>`).

Finally, I'd stop inlining the SVGs. Since the website is behind Cloudflare, it has http/2 so this is not really needed. The current HTML size is 118.9KB after brotli compression, which is way too much.

On the other hand, I'd inline `avatars.js before the closing `body` tag.

I could have a look, as long as I figure out how local development works :)

**Comment by XhmikosR** [comment]
OK, I sorted everything out, found an issue when building the docs on Windows too, so I'm gonna submit a few patches.

For the inlining part, I believe it's Netlify's image optimization setting? Or is it something in eleventy?
