### ISSUE TITLE
Cannot pass multiple node flags

### ISSUE THREAD

**Issue by aginzberg** [mochajs/mocha#3787]
With a simple mocharc.json:
```
{
  "max-old-space-size": 4096,
  "v8-allow-natives-syntax": true
  ...
}
```
I get the error
```Error: illegal value for flag --max-old-space-size=4096 --allow-natives-syntax of type size_t```

**Comment by craigtaub** [comment]
Can you supply mocha, node, os versions please. Also an [MCVE](https://stackoverflow.com/help/mcve). 

Or better yet fill out a [Bug report template](https://github.com/mochajs/mocha/issues/new?labels=unconfirmed-bug&template=bug_report.md&title=) please.

**Comment by juergba** [comment]
see also #3791

**Comment by aginzberg** [comment]
Mocha: 6.0.2
Node: 10.15.1
OS: Mac Mojave 10.14.2

**.mocharc.json:**
```
{
  "max-old-space-size": 4096,
  "v8-allow-natives-syntax": true
}
```

**test.js**
```
var assert = require('assert');
it('is true', function(){
  assert.equal(2, 1 + 1);
});
```

**Error:**
```Error: illegal value for flag --max-old-space-size=4096 --allow-natives-syntax of type size_t```
