### ISSUE TITLE
bad option with mocha v6.x

### ISSUE THREAD

**Issue by XhmikosR** [mochajs/mocha#3791]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Since mocha v6.0.0, I've been getting:

```
C:\Program Files\nodejs\node.exe: bad option: --throw-deprecation --trace-deprecation --trace-warnings --use_strict
```

### Steps to Reproduce

```
git clone https://github.com/MaxCDN/bootstrapcdn.git -b develop-xmr-update-mocha
npm i
npm test
```

**Expected behavior:** [What you expect to happen]

No error to be thrown

**Reproduces how often:**

100%

### Versions

- Node.js v10.15.2
- npm 6.4.1
- mocha 6.0.2
- OS is irrelevant

### Additional Information

test/mocha.opts:

```
--check-leaks
--globals __core-js_shared__
--reporter dot
--throw-deprecation
--timeout 10000
--trace-deprecation
--trace-warnings
--use_strict
```

https://github.com/MaxCDN/bootstrapcdn/tree/develop-xmr-update-mocha

---

Isn't this supposed to still work? Going back to v5.2.0 it works as expected without any errors.

Thanks!

**Comment by juergba** [comment]
maybe related to #3788.
Could you please patch "lib/cli/node-flags.js" as per PR3788? It's just one line.
Does it work?

**Comment by XhmikosR** [comment]
Yup, it does fix it. I'm gonna close this and follow #3788 and I'll wait for a new release, thanks!
