### ISSUE TITLE
Extension option does not clear the default .js

### ISSUE THREAD

**Issue by fatso83** [mochajs/mocha#3808]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ x Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

According to [Mocha's own docs](https://mochajs.org/#-extension-ext-watch-extensions-ext) one should be able to specify which extensions mocha will automatically load and that by specifying an extension the default of `*.js` should be cleared. _This does not happen in version 6_ (and I have never seen it happen earlier either).

### Steps to Reproduce
```
git clone fatso83/test-driven-learning
cd javascript/mocha-recursive-extensions-test
npm i
npm run test-bar
```

**Expected behavior:** 
Only this output should be shown, by Mocha loading only the file with the `.bar` extension
```
mocha --extension bar

  normal.bar
    ✓ should do nothing but register the test
```

**Actual behavior:** 
It loads the `normal.bar` - _in addition to_ all the files ending in `.js`.
```
mocha --extension bar

This is not a test: no-test.js


  normal.bar
    ✓ should do nothing but register the test

  normal.bar.js
    ✓ should do nothing but register the test

  normal.js
    ✓ should do nothing but register the test
```

**Reproduces how often:** 
Always

### Versions

6.0.2

**Comment by craigtaub** [comment]
As far as I can tell this particular feature hasn't worked since v6. Tried on `6.0.0-0` and includes `.js`. When run with debugger (i.e. `DEBUG=mocha:cli:* mocha`) prints below as "raw args"
```
'--extension',
'bar',
'--extension',
'js',
```
Suggesting its defaulted somewhere before yargs. Perhaps feature was lost in migration to yargs.

**Comment by dedene** [comment]
I came across this issue while finding out why the latest version of Mocha was also including all .js files in the watchlist of files. #3820 seems to fix it. However the ci build seems to fail, I'll see if I can find why and fix it.

**Comment by boneskull** [comment]
See #3834, cc @fatso83
