### ISSUE TITLE
Regression caused by the deprecation of `enableTimeouts`

### ISSUE THREAD

**Issue by romainPrignon** [mochajs/mocha#3813]
### Description

There is a regression caused by the deprecation of `enableTimeouts`

As you cas see here: https://github.com/mochajs/mocha/pull/3556/files#diff-aa849a970cef551664c12f04a4209f6fR121
`enableTimeouts` was marked as deprecated and the use of `timeout: false` should replace it.

But in the same time, we removed:
```js
if (typeof options.timeout !== 'undefined' && options.timeout !== null) {
    this.timeout(options.timeout);
```

The bug is present with `grunt-mocha-test`. As you can see, `grunt-mocha-test` parse all options as undefined:
```js
{ grep: undefined,
  reporter: 'spec',
  bail: false,
  ui: undefined,
  timeout: undefined,
  invert: undefined,
  ignoreLeaks: undefined,
  growl: undefined,
  globals: undefined,
  require: undefined,
  colors: undefined,
  slow: undefined 
}
```

The bug is not present with `grunt-simple-mocha`

Should we kept it while `enableTimeouts` is marked as deprecated ?

### Steps to Reproduce
```sh
npm install grunt grunt-mocha-test
```

in `Gruntfile.js`

```js
module.exports = function(grunt) {

  grunt.loadNpmTasks('grunt-mocha-test');

  grunt.initConfig({
    mochaTest: {
      test: {
        src: ['test/**/*.js']
      }
    }
  });

  grunt.registerTask('default', 'mochaTest');

};
```

Then launch test
```sh
grunt mochaTest
```

### Expected behavior

Mocha v6 should work with options like {timeout: undefined} because there is only a deprecation warning in v6 for `enableTimeouts` option.

### Actual behavior:

TypeError: Cannot read property 'toString' of undefined
  at Suite.timeout (/home/fwadmin-server/smc/node_modules/mocha/lib/suite.js:124:10)
  at Mocha.timeout (/home/fwadmin-server/smc/node_modules/mocha/lib/mocha.js:625:14)
  at new Mocha (/home/fwadmin-server/smc/node_modules/mocha/lib/mocha.js:124:8)
  at new MochaWrapper (/home/fwadmin-server/smc/node_modules/grunt-mocha-test/tasks/lib/MochaWrapper.js:30:15)

### Reproduces how often:
  Always

### Versions
  6.0.2

**Comment by boneskull** [comment]
Thanks.  Looks like I obliterated this guard.

**Comment by boneskull** [comment]
ref: #3816

**Comment by romainPrignon** [comment]
I just test #3816 
It works as expected with my current setup: `grunt grunt-mocha-test`

Thanks ! It was fast !
