### ISSUE TITLE
Custom Location is not working as expected for --config

### ISSUE THREAD

**Issue by AartiJ** [mochajs/mocha#3818]
### Prerequisites

- [ ] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]
config file should load from the given custom location

**Actual behavior:** [What actually happens]
Getting issue as below
> mocha --no-opts --config node_modules/ace-api-testlib/lib/.mocharc.js --reporter mocha-allure-reporter "

/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/cli/config.js:63
    throw new Error(`failed to parse ${filepath}: ${err}`);
    ^

Error: failed to parse node_modules/ace-api-testlib/lib/.mocharc.js: Error: Cannot find module 'node_modules/ace-api-testlib/lib/.mocharc.js'
    at exports.loadConfig.filepath (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/cli/config.js:63:11)
    at loadRc (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/cli/options.js:229:21)
    at loadOptions (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/cli/options.js:299:20)
    at Object.<anonymous> (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/bin/mocha:29:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
npm ERR! code ELIFECYCLE

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
 % mocha --version
6.0.2

- The output of `node --version`:
 % node --version
v8.11.1

- Your operating system
  - name and version: macOSHighSierra 10.13.6
  - architecture (32 or 64-bit):
- Your shell (e.g., bash, zsh, PowerShell, cmd): bash
- Your browser and version (if running browser tests):
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):

**Comment by AartiJ** [comment]
my .mocharc.js configuration file is in another node artifact which I am basically using in this e2e project.

**Comment by juergba** [comment]
Is the path `node_modules/../lib/.mocharc.js` correct? Try to use an absolute one instead.

**Comment by AartiJ** [comment]
yes, the path is correct and from root directory.

**Comment by juergba** [comment]
Is `node_modules/../lib/.mocharc.js` not identical with `lib/.mocharc.js` ?

I'm quite sure (I don't know macOS) that `node_modules/ace-api-testlib/lib/.mocharc.js` is not an absolute path. If your path is a relative one, try: `./node_modules/ace-api-testlib/lib/.mocharc.js`

**Comment by AartiJ** [comment]
tried your suggestion and still getting the same issue.
> mocha --no-opts --config ./node_modules/ace-api-testlib/lib/.mocharc.js --reporter mocha-allure-reporter

/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/cli/config.js:63
    throw new Error(`failed to parse ${filepath}: ${err}`);
    ^

Error: failed to parse ./node_modules/ace-api-testlib/lib/.mocharc.js: Error: Cannot find module './node_modules/ace-api-testlib/lib/.mocharc.js'
    at exports.loadConfig.filepath (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/cli/config.js:63:11)
    at loadRc (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/cli/options.js:229:21)
    at loadOptions (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/cli/options.js:299:20)
    at Object.<anonymous> (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/bin/mocha:29:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
npm ERR! code ELIFECYCLE

**Comment by plroebuck** [comment]
Adding "./" to the beginning will have no effect (doesn't hurt or help).
```sh
$ ls -al node_modules/ace-api-testlib/lib/.mocharc.js
```
Relatively certain this will fail though...

**Comment by plroebuck** [comment]
> yes, the path is correct and was using absolute path. I have updated the description above.

The path above is _relative_. Absolute paths on UN*X begin with a slash character `'/'` (i.e., the path from the root directory).

**Comment by AartiJ** [comment]
I got the below output for the commands you requested to execute
C02Q383EG8WP:ace-ilp-lib ajadeja$ ls -al node_modules/ace-api-testlib/lib/.mocharc.js
-rw-r--r--  1 ajadeja  1849915958  530 Mar  7 16:31 node_modules/ace-api-testlib/lib/.mocharc.js
C02Q383EG8WP:ace-ilp-lib ajadeja$ find node_modules -name ".mocharc*"
node_modules/ace-api-testlib/lib/.mocharc.js

**Comment by plroebuck** [comment]
you left out the _most important_ -- `pwd`

**Comment by AartiJ** [comment]
Sorry here it is 
C02Q383EG8WP:ace-ilp-lib ajadeja$ pwd
/Users/ajadeja/git_test/ace-ilp-lib
C02Q383EG8WP:ace-ilp-lib ajadeja$ ls -al node_modules/ace-api-testlib/lib/.mocharc.js
-rw-r--r--  1 ajadeja  1849915958  530 Mar  7 16:31 node_modules/ace-api-testlib/lib/.mocharc.js
C02Q383EG8WP:ace-ilp-lib ajadeja$ find node_modules -name ".mocharc*"
node_modules/ace-api-testlib/lib/.mocharc.js
C02Q383EG8WP:ace-ilp-lib ajadeja$

**Comment by plroebuck** [comment]
```sh
$ which mocha
```

**Comment by AartiJ** [comment]
C02Q383EG8WP:ace-ilp-lib ajadeja$ which mocha
/Users/ajadeja/.nvm/versions/node/v8.11.1/bin/mocha
C02Q383EG8WP:ace-ilp-lib ajadeja$ cat package.json
{
  "name": "ace-ilp-lib",
  "version": "1.0.9",
  "description": "Provides basic test framework support, including session management, logging, test data management",
  "main": "index.js",
  "dependencies": {
    "ace-api-testlib": "1.0.7",
    "mocha": "^6.0.2",
    "mocha-allure-reporter": "^1.4.0"
  },
  "files": [
    "lib",
    "test"
  ],
  "directories": {
    "lib": "lib"
  },
  "scripts": {
    "test": "mocha --no-opts --config ./node_modules/ace-api-testlib/lib/.mocharc.js --reporter mocha-allure-reporter",
    "report": "allure generate target/allure-results --clean -o allure-report"
  },
  "repository": {
    "type": "git",
    "url": "https://stash.intralinks.com/scm/ace/ace-ilp-lib.git"
  },
  "author": "ace-api",
  "license": "ISC"
}

**Comment by plroebuck** [comment]
Quick test with absolute path...

```json
"scripts": {
"test": "mocha --no-opts --config '/Users/ajadeja/git_test/ace-ilp-lib/node_modules/ace-api-testlib/lib/.mocharc.js' --reporter mocha-allure-reporter",
"report": "allure generate target/allure-results --clean -o allure-report"
},
```
```sh
$ npm test
```

**Comment by plroebuck** [comment]
Does "ace-ilp-lib" contain a Mocha config file you're trying to avoid?

**Comment by AartiJ** [comment]
> Does "ace-ilp-lib" contain a Mocha config file you're trying to avoid?

No but if I put in ace-ilp-lib it works since that's the default path

**Comment by AartiJ** [comment]
> Quick test with absolute path...
> 
> ```json
> "scripts": {
> "test": "mocha --no-opts --config '/Users/ajadeja/git_test/ace-ilp-lib/node_modules/ace-api-testlib/lib/.mocharc.js' --reporter mocha-allure-reporter",
> "report": "allure generate target/allure-results --clean -o allure-report"
> },
> ```
> 
> ```shell
> $ npm test
> ```

Yes this one works

**Comment by plroebuck** [comment]
Works means it ran your tests as expected, or it didn't immediately blow up?

**Comment by AartiJ** [comment]
> Works means it ran your tests as expected, or it didn't immediately blow up?

it ran tests as expected

**Comment by plroebuck** [comment]
Out of curiosity, why are you putting the Mocha config files in the "lib" directory to begin with?
Does "ace-api-testlib" have a "test" directory?
Does "ace-ilp-lib" have a "test" directory

**Comment by AartiJ** [comment]
> Out of curiosity, why are you putting the Mocha config files in the "lib" directory to begin with?
> Does "ace-api-testlib" have a "test" directory?
this is our inhouse framework which is being used by e2e test Projects. So basically config file should come from this so that it will be consistent across all e2e projects and also with this end user do not need to add config file. It has test directory but only unit tests.
> Does "ace-ilp-lib" have a "test" directory?
Yes, it does since this is one of the e2e Project

**Comment by AartiJ** [comment]
that's fine, I know now that we should give absolute path here. I will try to find other ways for my requirement.

**Comment by plroebuck** [comment]
So:
* "ace-api-testlib" package has a "test" directory with unit tests.
* "ace-ilp-lib" package has a "test" directory with e2e tests

Still kinda lost on why put the Mocha config file in the "lib" directory.
Why not "ace-api-testlib/.mocharc.js" where it would found by design?

**Comment by AartiJ** [comment]
> So:
> 
> * "ace-api-testlib" package has a "test" directory with unit tests.
> * "ace-ilp-lib" package has a "test" directory with e2e tests
> 
> Still kinda lost on why put the Mocha config file in the "lib" directory.
> Why not "ace-api-testlib/.mocharc.js" where it would found [by design](https://mochajs.org/#configuring-mocha-nodejs)?

oh will it? I tried putting in  ace-api-testlib/.mocharc.js and it was not working. If I keep in ace-api-testlib/.mocharc.js what will be my path for --config file?

**Comment by plroebuck** [comment]
Some of my concern is also that "node_modules/ace-api-testlib/lib/.mocharc.js" turns around and exports YA relative path...

**Comment by plroebuck** [comment]
Suggest:
```json
$ cat package.json
{
  "name": "ace-ilp-lib",
  "version": "1.0.9",
  "description": "Provides basic test framework support, including session management, logging, test data management",
  "main": "index.js",
  "dependencies": {
    "ace-api-testlib": "1.0.7"
  },
  "devDependencies": {
    "mocha": "^6.0.2",
    "mocha-allure-reporter": "^1.4.0"
  },
  "files": [
    "lib",
    "test"
  ],
  "directories": {
    "lib": "lib",
    "test": "test"
  },
  "scripts": {
    "test": "mocha --config ./node_modules/ace-api-testlib/.mocharc.js",
    "report": "allure generate target/allure-results --clean -o allure-report"
  },
  "repository": {
    "type": "git",
    "url": "https://stash.intralinks.com/scm/ace/ace-ilp-lib.git"
  },
  "author": "ace-api",
  "license": "ISC"
}
```

**Comment by AartiJ** [comment]
Tried the suggestion which gives same as original error
> mocha --config ./node_modules/ace-api-testlib/.mocharc.js "--sut=dev2" "--spec=test/V2APITest"

/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/cli/config.js:63
    throw new Error(`failed to parse ${filepath}: ${err}`);
    ^

Error: failed to parse ./node_modules/ace-api-testlib/.mocharc.js: Error: Cannot find module './node_modules/ace-api-testlib/.mocharc.js'
    at exports.loadConfig.filepath (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/cli/config.js:63:11)
    at loadRc (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/cli/options.js:229:21)
    at loadOptions (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/cli/options.js:299:20)
    at Object.<anonymous> (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/bin/mocha:29:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by plroebuck** [comment]
$ cat node_modules/ace-api-testlib/.mocharc.js
```js
'use strict';
const path = require('path');
const FIFTY_SECS = 50000;
const allureArtifactsDir = process.env.OUTDIR
  ? path.join(process.env.OUTDIR, 'allure-results')
  : 'target/allure-results';

module.exports = {
  timeout: FIFTY_SECS,
  file: path.resolve('./node_modules/ace-api-testlib/mocha.global.js'),
  opts: false,
  reporter: 'mocha-allure-reporter',
  reporterOption: [ 'targetDir=' + allureArtifactsDir ]
}
```

**Comment by AartiJ** [comment]
> $ cat node_modules/ace-api-testlib/.mocharc.js
> 
> ```js
> 'use strict';
> const path = require('path');
> const FIFTY_SECS = 50000;
> const allureArtifactsDir = process.env.OUTDIR
>   ? path.join(process.env.OUTDIR, 'allure-results')
>   : 'target/allure-results';
> 
> module.exports = {
>   timeout: FIFTY_SECS,
>   file: path.resolve('./node_modules/ace-api-testlib/mocha.global.js'),
>   opts: false,
>   reporter: 'mocha-allure-reporter',
>   reporterOption: [ 'targetDir=' + allureArtifactsDir ]
> }
> ```

gives same error as given above

**Comment by plroebuck** [comment]
What's in './node_modules/ace-api-testlib/mocha.global.js'?

**Comment by AartiJ** [comment]
> What's in './node_modules/ace-api-testlib/mocha.global.js'?

global hooks configuration for e2e tests

**Comment by plroebuck** [comment]
You have `sudo` capability? Rename your global "mocha" and get it out of the way...

**Comment by AartiJ** [comment]
I deleted the global mocha, still gives same error

**Comment by plroebuck** [comment]
```sh
$ cat node_modules/ace-api-testlib/package.json | grep version
```

**Comment by AartiJ** [comment]
> ```shell
> $ cat node_modules/ace-api-testlib/package.json | grep version
> ```

Unable to execute this commnad
C02Q383EG8WP:ace-ilp-lib ajadeja$ $ cat node_modules/ace-api-testlib/package.json | grep version
bash: $: command not found
C02Q383EG8WP:ace-ilp-lib ajadeja$

**Comment by plroebuck** [comment]
Figured out your issue... I think anyway. 
Here's the relevant code from **"lib/cli/config.js"**:
```js
const parsers = (exports.parsers = {
  yaml: filepath =>
    require('js-yaml').safeLoad(fs.readFileSync(filepath, 'utf8')),
  js: filepath => require(filepath),
  json: filepath =>
    JSON.parse(
      require('strip-json-comments')(fs.readFileSync(filepath, 'utf8'))
    )
});
```
The other parsers are reading the config file directly, so relative path is straightforward. But your JS config file is handled by `require` which uses [these rules](https://nodejs.org/api/modules.html#modules_file_modules) instead. 

So rather than:
```json
  "scripts": {
    "test": "mocha --config ./node_modules/ace-api-testlib/.mocharc.js"
  },
```
instead use the even shorter:
```json
  "scripts": {
    "test": "mocha --config ace-api-testlib/.mocharc.js"
  },
```

Used [this recipe](https://gist.github.com/plroebuck/7900f3a3ff3949c3c208b3250b34894b) for testing. **There were additional changes needed to get your setup (as I understand it anyway) to work.**

**Comment by AartiJ** [comment]
> ```json
> mocha --config ace-api-testlib/.mocharc.js
> ```

After changing the code for lib/cli/config.js getting below error.

> mocha --config ace-api-testlib/.mocharc.js "--sut=dev2" "--spec=test/V2APITest"

/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/node_modules/yargs/yargs.js:1148
      else throw err
           ^

Error: Cannot find module '/Users/ajadeja/git_test/ace-ilp-lib/node_modules/ace-api-testlib/mocha.global.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/mocha.js:327:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/mocha.js:324:14)
    at Mocha.run (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/mocha.js:801:10)
    at Object.exports.singleRun (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/cli/run-helpers.js:207:16)
    at exports.runMocha (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/cli/run-helpers.js:300:13)
    at Object.exports.handler.argv [as handler] (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/cli/run.js:296:3)
    at Object.runCommand (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/node_modules/yargs/yargs.js:1072:28)
    at Object.parse (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/cli/cli.js:62:6)
    at Object.<anonymous> (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/bin/_mocha:10:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by AartiJ** [comment]
> Figured out your issue... I think anyway.
> Here's the relevant code from **"lib/cli/config.js"**:
> 
> ```js
> const parsers = (exports.parsers = {
>   yaml: filepath =>
>     require('js-yaml').safeLoad(fs.readFileSync(filepath, 'utf8')),
>   js: filepath => require(filepath),
>   json: filepath =>
>     JSON.parse(
>       require('strip-json-comments')(fs.readFileSync(filepath, 'utf8'))
>     )
> });
> ```
> 
> The other parsers are reading the config file directly, so relative path is straightforward. But your JS config file is handled by `require` which uses [these rules](https://nodejs.org/api/modules.html#modules_file_modules) instead.
> 
> So rather than:
> 
> ```json
>   "scripts": {
>     "test": "mocha --config ./node_modules/ace-api-testlib/.mocharc.js"
>   },
> ```
> 
> instead use the even shorter:
> 
> ```json
>   "scripts": {
>     "test": "mocha --config ace-api-testlib/.mocharc.js"
>   },
> ```
> 
> Used [this recipe](https://gist.github.com/plroebuck/7900f3a3ff3949c3c208b3250b34894b) for testing. **There were additional changes needed to get your setup (as I understand it anyway) to work.**

Yes this works as expected.. thanks

**Comment by plroebuck** [comment]
Everything working now? Hope recipe helped. If no further questions, please close the issue. Thx

**Comment by AartiJ** [comment]
> Everything working now? Hope recipe helped. If no further questions, please close the issue. Thx

Yes, recipe helped. Everything works now. Closing the issue.

**Comment by AndyOGo** [comment]
Maybe I'm doing something wrong, but I thought `mocha --config .mocharc-custom.js` should work 🤔 

Unfortunately neither absolute nor relative path to custom config file does work for me 😞
