### ISSUE TITLE
mocha prints a test summary with partial results in the middle of a test run and prints nothing at the end (after upgrading to 5.0 or 6.0)

### ISSUE THREAD

**Issue by pallymore** [mochajs/mocha#3828]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Hello,

I'm working on a React app with ~2000-ish tests.
We've been using mocha since the beginning of the project - it has been working great for us until recently we tried to bring it to the latest version. 

Previously we are on 4.x - no issues. 
I tried to upgrade to 5.x and 6.0.2 with the same set of configurations. 
```
{
extensions: ['js', 'jsx'],
colors: true,
diff: true,
globals: '*'
}
```

We are using babel-7 with some pretty common packages:

```
    "@babel/cli": "^7.0.0",
    "@babel/core": "^7.2.2",
    "@babel/polyfill": "^7.0.0",
    "@babel/preset-env": "^7.3.1",
    "@babel/preset-react": "^7.0.0",
    "@babel/register": "^7.0.0",
```

test command (that have not been changed since 4.0)

```
$ mocha --require @babel/register --require ./test/mocha/test-helpers.js "./src/js/**/*.spec.{js,jsx}"
```

Issue: 

Now (6.0.2) mocha reports summaries in the middle of running all tests

e.g. when it is still running the test suites it reports a spec fail mid-way (and continued to run all the other tests without reporting a second summary.

![image](https://user-images.githubusercontent.com/2566530/54153580-5656a900-4416-11e9-8567-9078bfa9be96.png)

(this happens with or without spec failures in the first "set" of reports - if there are no failed tests, it is only going to report `1047 passing` in the middle of all specs, and nothing at the end)

It seems it runs all `.spec.js` tests first, then proceeds to run all the `.spec.jsx` test files.

With same configuration, reverting mocha version back to 4.x without changing any other packages, it runs all 2000 specs and prints one summary at the very end.

When I change the glob pattern to run `js` or `jsx` files only, it runs specs correctly and prints one summary at the end.

I'm not sure what else I should check - let me know if you need more information.

### Steps to Reproduce

same configuration, just run `mocha` with the same glob pattern.

**Expected behavior:** [What you expect to happen]

Mocha runs all test suites and prints 1 summary at the end.

**Actual behavior:** [What actually happens]

Mocha prints 1 summary in the middle of a test run, and prints nothing at the end. 

**Reproduces how often:** [What percentage of the time does it reproduce?]

works perfectly when using 4.x, this behavior occurs 100% of the time with mocha 5.x and 6.x

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
both 6.0.2

- The output of `node --version`:
10.15.1 (also tested in 8.15, same results)

- Your operating system
  - name and version: macOS 10.14.3
  - architecture (32 or 64-bit): 64
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh 5.3 (also tested in bash 3.2)
- Your browser and version (if running browser tests): N/A
- Any third-party Mocha-related modules (and their versions): none
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):
Babel 7
```
    "@babel/cli": "^7.0.0",
    "@babel/core": "^7.2.2",
    "@babel/polyfill": "^7.0.0",
    "@babel/preset-env": "^7.3.1",
    "@babel/preset-react": "^7.0.0",
    "@babel/register": "^7.0.0",
```

### Additional Information

None at this moment.

**Comment by pallymore** [comment]
> At minimum:
> 
> * How is `babel` configured? What is that configuration?
> * Enzyme? WebPack?
> * Which type Mocha config file is that above (js or json)?

here's my `.bablerc` 

```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "browsers": [
            "last 2 versions",
            "safari >= 7"
          ]
        }
      }
    ],
    "@babel/preset-react"
  ],
  "only": [
    "./.storybook",
    "./src",
    "./build",
    "./test"
  ]
}
```

both `.babelrc` and `

I'm using `enzyme` 3.8 with `enzyme-adapter-react-16` 1.9.1 
I'm also on `chai` 3.5.0 and `chai-enzyme` 1.0.0 (beta)

the mocha config file is in `js` format, however I omitted `module.exports = ` part.
for mocha 4.0, I'm using `mocha.opts` with the following contents:

```
--colors
--globals '*'
--growl
--exit
```

additionally running the tests with `nyc mocha` or `mocha` yields the same results for mocha version 4.0, and same issue exists for mocha ~5.0 and 6.0.2

I'm indeed using webpack, however it is not referenced / used anywhere in the test setup - how does it interfere with mocha tests?

**Comment by pallymore** [comment]
actually - I think it might be caused by an exception thrown during middle of the test by a third party library. :/ 

please park this for now - let me dig deeper into this and see what else i might find. Thanks!

**Comment by plroebuck** [comment]
Any progress here? Can issue be closed?

**Comment by pallymore** [comment]
Hi @plroebuck  - sorry for the late response.

It seems this is caused by a `setTimeout` buried deep in the code. the delayed function tries to access an object that no longer exists and throws an error. For some reason the error is causing mocha to end prematurely. 

Let's close this for now - I'll open a new ticket if I can find a way to create a demo that replicates this issue.

**Comment by plroebuck** [comment]
Maybe...

```js
describe('isolated failing test', function() {
  let listeners;

  before(function() {
    listeners = process.listeners('uncaughtException');
    process.removeAllListeners('uncaughtException');
  });

  it('should work but fails...', async function() {
    // invoke existing test implementation
  });

  after(function() {
    listeners.forEach(function(listener) {
      process.on('uncaughtException', listener);
    });
  });
});
```
