### ISSUE TITLE
Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by marikaner** [mochajs/mocha#3837]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

When running mocha in a CI environment (Jenkins), I get the following error:

```sh
.../node_modules/mocha/lib/cli/cli.js:58
  GitHub: ${ansi.blue(repository.url)}
                                 ^

TypeError: Cannot read property 'url' of undefined
```
- while locally this works. I believe that for some reason I am not using the cli correctly, so that the epilogue is printed. Unfortunately in the CI environment, the `repository` key does not exist in mocha's [`package.json`](https://github.com/mochajs/mocha/blob/d1024a3ea8298dda76afee2196b5f94472538cff/lib/cli/cli.js#L19). Thus, trying to read its `url` will result in reading 'url' of `undefined`. I think a simple step would be to add a check for the existence of `repository` before printing this and maybe not print it, if not available? ¯\_(ツ)_/¯ 

### Steps to Reproduce

As I am not sure why the repository is not there on Jenkins, I can't say more than run any `mocha -h` on Jenkins.

**Expected behavior:** Optimally same results as locally
**Actual behavior:** Fails on writing epilogue
**Reproduces how often:** everytime

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: **6.0.2**
- The output of `node --version`: **v10.14.0**
- The output of `npm --version`: **??????**
- Your operating system
  - name and version: **SUSE Linux Enterprise Server 12 SP3**
  - architecture (32 or 64-bit): **x86-64**
- Your shell (e.g., bash, zsh, PowerShell, cmd): **bash**
- Your browser and version (if running browser tests): **NA**
- Any third-party Mocha-related modules (and their versions):
  - **@types/mocha-??.??.??**
  - **chai-??.??.??**
  - **sinon-chai-??.??.??**
  - **types-??.??.??**
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):
  - **tsc 3.3.3333**

### Additional information
The command I am running is:
```sh
$ npx nyc mocha -r ts-node/register --file "test/test-util/bootstrap.ts" -c --watch-extensions "ts" "test/**/*.spec.ts"
```

**Comment by plroebuck** [comment]
Aware that the browserified "package.json" would not have this field, but CLI certainly should. Any chance you could patch your version of Mocha and tell us what _is_ there?

Add the following line at "lib/cli/cli.js#L18".
```js
console.log('package.json:', require('../../package.json');
```

**Comment by marikaner** [comment]
I can actually access the file in the workspace:

```json
{
  "files": [
    "bin/{*mocha,options.js}", 
    "assets/growl/*.png", 
    "lib/**/*.{js,html,json}", 
    "index.js", 
    "mocha.css", 
    "mocha.js", 
    "browser-entry.js"
  ], 
  "_location": "/mocha", 
  "contributors": [...], 
  "_spec": "6.0.2", 
  "_integrity": "sha512-RtTJsmmToGyeTznSOMoM6TPEk1A84FQaHIciKrRqARZx+B5ccJ5tXlmJzEKGBxZdqk9UjpRsesZTUkZmR5YnuQ==", 
  "logo": "https://cldup.com/S9uQ-cOLYz.svg", 
  "keywords": [
    "mocha", 
    "test", 
    "bdd", 
    "tdd", 
    "tap"
  ], 
  "devDependencies": {
    "coffee-script": "^1.10.0", 
    "karma-sauce-launcher": "^1.2.0", 
    "cross-spawn": "^6.0.5", 
    "@11ty/eleventy": "^0.7.1", 
    "chai": "^4.2.0", 
    "eslint-config-prettier": "^3.6.0", 
    "markdown-it-attrs": "^2.3.2", 
    "eslint-config-standard": "^12.0.0", 
    "unexpected": "^10.39.2", 
    "remark-github": "^7.0.6", 
    "@mocha/docdash": "^2.0.0", 
    "markdown-it": "^8.4.2", 
    "eslint-plugin-standard": "^4.0.0", 
    "eslint-config-semistandard": "^13.0.0", 
    "uslug": "^1.0.4", 
    "eslint-plugin-prettier": "^3.0.0", 
    "rewiremock": "^3.12.3", 
    "prettier": "^1.16.4", 
    "eslint-plugin-promise": "^4.0.1", 
    "markdown-it-prism": "^2.0.1", 
    "sinon": "^7.2.4", 
    "markdown-toc": "^1.2.0", 
    "nps": "^5.9.3", 
    "watchify": "^3.11.1", 
    "nyc": "^13.3.0", 
    "markdown-magic": "^0.1.25", 
    "karma": "^4.0.0", 
    "to-vfile": "^5.0.2", 
    "markdownlint-cli": "^0.13.0", 
    "through2": "^3.0.0", 
    "eslint-plugin-node": "^8.0.1", 
    "lint-staged": "^8.1.4", 
    "unexpected-sinon": "^10.11.1", 
    "karma-mocha": "^1.3.0", 
    "jsdoc": "^3.5.5", 
    "rimraf": "^2.5.2", 
    "remark-inline-links": "^3.1.2", 
    "browserify": "^16.2.3", 
    "markdown-it-anchor": "^5.0.2", 
    "markdown-magic-package-json": "^2.0.0", 
    "cross-env": "^5.2.0", 
    "karma-mocha-reporter": "^2.2.4", 
    "remark": "^10.0.1", 
    "coveralls": "^3.0.2", 
    "@mocha/contributors": "^1.0.3", 
    "assetgraph-builder": "^6.6.3", 
    "karma-chrome-launcher": "^2.0.0", 
    "unexpected-eventemitter": "^1.1.3", 
    "eslint": "^5.14.1", 
    "karma-browserify": "^6.0.0", 
    "strip-ansi": "^5.0.0", 
    "husky": "^1.2.1", 
    "browserify-package-json": "^1.0.1", 
    "eslint-plugin-import": "^2.16.0", 
    "svgo": "^1.1.1"
  }, 
  "_from": "mocha@6.0.2", 
  "yargs": {
    "dot-notation": false, 
    "short-option-groups": false, 
    "combine-arrays": true
  }, 
  "engines": {
    "node": ">= 6.0.0"
  }, 
  "_phantomChildren": {
    "which-module": "2.0.0", 
    "argparse": "1.0.10", 
    "find-up": "3.0.0", 
    "has-flag": "3.0.0", 
    "os-locale": "3.1.0", 
    "camelcase": "5.0.0", 
    "y18n": "4.0.0", 
    "set-blocking": "2.0.0", 
    "require-directory": "2.1.1", 
    "strip-ansi": "4.0.0", 
    "cliui": "4.1.0", 
    "esprima": "4.0.1", 
    "decamelize": "1.2.0", 
    "is-fullwidth-code-point": "2.0.0"
  }, 
  "_args": [
    [
      "mocha@6.0.2", 
      "/xmake/data/xmake/prod-build10010/w/ma/MA-sdk-js-SP-REL-linuxx86_64_indirectshipment-linuxx86_64/gen/out/module"
    ]
  ], 
  "notifyLogo": "https://ibin.co/4QuRuGjXvl36.png", 
  "version": "6.0.2", 
  "prettier": {
    "bracketSpacing": false, 
    "singleQuote": true, 
    "endOfLine": "auto"
  }, 
  "_inBundle": false, 
  "homepage": "https://mochajs.org/", 
  "gitter": "https://gitter.im/mochajs/mocha", 
  "bin": {
    "_mocha": "./bin/_mocha", 
    "mocha": "./bin/mocha"
  }, 
  "_requested": {
    "name": "mocha", 
    "escapedName": "mocha", 
    "saveSpec": null, 
    "rawSpec": "6.0.2", 
    "raw": "mocha@6.0.2", 
    "registry": true, 
    "fetchSpec": "6.0.2", 
    "type": "version"
  }, 
  "description": "simple, flexible, fun test framework", 
  "_development": true, 
  "_requiredBy": [
    "#DEV:/"
  ], 
  "dependencies": {
    "browser-stdout": "1.3.1", 
    "findup-sync": "2.0.0", 
    "diff": "3.5.0", 
    "object.assign": "4.1.0", 
    "yargs-unparser": "1.5.0", 
    "yargs": "12.0.5", 
    "minimatch": "3.0.4", 
    "growl": "1.10.5", 
    "wide-align": "1.1.3", 
    "ansi-colors": "3.2.3", 
    "which": "1.3.1", 
    "node-environment-flags": "1.0.4", 
    "log-symbols": "2.2.0", 
    "glob": "7.1.3", 
    "mkdirp": "0.5.1", 
    "js-yaml": "3.12.0", 
    "yargs-parser": "11.1.1", 
    "he": "1.2.0", 
    "supports-color": "6.0.0", 
    "strip-json-comments": "2.0.1", 
    "escape-string-regexp": "1.0.5", 
    "ms": "2.1.1", 
    "debug": "3.2.6"
  }, 
  "scripts": {
    "test": "nps test", 
    "start": "nps", 
    "version": "nps version", 
    "prepublishOnly": "nps test clean build"
  }, 
  "browserify": {
    "transform": [
      "./scripts/package-json-cullify"
    ]
  }, 
  "name": "mocha", 
  "license": "MIT", 
  "@mocha/contributors": {
    "exclude": [
      "greenkeeperio-bot <support@greenkeeper.io>", 
      "greenkeeper[bot] <greenkeeper[bot]@users.noreply.github.com>", 
      "TJ Holowaychuk <tj@vision-media.ca>"
    ]
  }, 
  "directories": {
    "test": "./test", 
    "lib": "./lib"
  }, 
  "author": {
    "name": "TJ Holowaychuk", 
    "email": "tj@vision-media.ca"
  }, 
  "bugs": {
    "url": "https://github.com/mochajs/mocha/issues/"
  }, 
  "_where": "/xmake/data/xmake/prod-build10010/w/ma/MA-sdk-js-SP-REL-linuxx86_64_indirectshipment-linuxx86_64/gen/out/module", 
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  }, 
  "_id": "mocha@6.0.2", 
  "browser": {
    "./lib/growl.js": "./lib/browser/growl.js", 
    "tty": "./lib/browser/tty.js", 
    "fs": false, 
    "./index.js": "./browser-entry.js", 
    "glob": false, 
    "supports-color": false, 
    "path": false
  }
}
```

On a side note: I also reduced my command to `npx nyc mocha -r ts-node/register --file "test/test-util/bootstrap.ts" "test/**/*.spec.ts"`, but it still fails. Potientially, this has something to do with the browserification. I cannot exclude, that I am doing something wrong, but this worked in the same environment with version 5.2.0.

**Comment by plroebuck** [comment]
As you can see, the field exists:
https://github.com/mochajs/mocha/blob/d1024a3ea8298dda76afee2196b5f94472538cff/package.json#L467-L470

Something is stripping the field from our "package.json". You didn't provide any of the requested information in the "Versions" area of issue (besides mocha version). Something before or during transfer to Jenkins slave?

**Comment by marikaner** [comment]
I added the versions to the original comment. Hope that helps.

**Comment by outsideris** [comment]
How did you install mocha in CI?

**Comment by plroebuck** [comment]
_I made some edits above to your issue description; could you provide the `???` information?_

Could you provide your "package.json"? Either one of its scripts (or another build script) is removing our `"repository"` field. And since it's not said, what is this machine - a personal/group/cloud Jenkins server/slave?

> Potentially, this has something to do with the browserification. I cannot exclude, that I am doing something wrong, but this worked in the same environment with version 5.2.0.

Browserification (for us) only creates a browser-usable Mocha bundle; as your issue description explicitly provides CLI usage, it doesn't apply to this situation. I'm aware `npm` adds fields to `"package.json"`, but above I note others have been reordered (e.g., "dependencies") as well. Are other packages missing their "repository" fields, or just us?

Do you know how your package gets installed on Jenkins? Is your `npm` using a private repository setup or getting the packages from public server? Using `npm install` or `npm ci`?

**Comment by marikaner** [comment]
@plroebuck Well, this is embarassing, I just found that this is an issue on our side -.-
There is a central build script stripping this information to make sure that there are no corporate information shared. I will try to convince the maintainers of this script to restrict this to the project package.json files only.
Also, I just confirmed, that I can work around this (which I really don't want to do unless absolutely necessary).
So, thank you so much for your support, I guess you will not need the missing information anymore? Nevertheless, maybe it is still a good idea to only log the github link if this information is available.

**Comment by plroebuck** [comment]
Glad you found the problem.

> Nevertheless, maybe it is still a good idea to only log the github link if this information is available.

Sorry. Decline as we do not support recovery from users deleting random parts of our package.

Tell your DevOps guys to apply the scripts performing the stripping to only _your company's_ packages instead. Better yet, transfer this bug to _their_ issue handler as this a legitimate bug in _their_ setup...
