### ISSUE TITLE
Fix/Remove NPM Mocha  "next" tag

### ISSUE THREAD

**Issue by plroebuck** [mochajs/mocha#3838]
https://www.npmjs.com/package/mocha?activeTab=versions

**Comment by plroebuck** [comment]
So what's progress on this?

**Comment by davesag** [comment]
Very keen to see the `6.1.0` milestone completed as it includes security audit fixed required by a project I am working on right now.

**Comment by boneskull** [comment]
the problem with this issue is that it is one of "fix" or "remove", or maybe that means both.  I'm not entirely sure what to do with the `next` tag.  remove it?  move it to the latest release?

**Comment by boneskull** [comment]
I'm gonna go with "move it to the latest release" in case some poor schmo has it in `package.json`.

note to self: once you use a tag, you can't really un-use a tag.

**Comment by boneskull** [comment]
this is done; `next` is the same as `latest`.
