### ISSUE TITLE
EPROTO error when trying to connect to a localhost WSS 

### ISSUE THREAD

**Issue by Vayvala** [mochajs/mocha#3839]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Connection to a localhost WSS results in this error:

```
Error: write EPROTO 1748:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332: 
at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:67:16)
```

Same code works fine in raw Node.js

Mocha Version: 5.2.0

**Comment by juergba** [comment]
Do you really expect us to be able to reply in a helpful manner, with this little information you provided?

**Comment by plroebuck** [comment]
Usually happens when server and client can't agree on a cypher to use for SSL.
Also reported to happen with http proxy given https connection.

See [npm Common proxy and networking problems](https://npm.community/t/common-proxy-and-networking-problems/151/2).

Either way, nothing to do with Mocha...

**Comment by jimbits** [comment]
When testing make sure you don't use https: that worked for me...
