### ISSUE TITLE
--forbid-only doesn't recognize `it.only` when `before` crashes

### ISSUE THREAD

**Issue by medikoo** [mochajs/mocha#3840]
Not sure if it's a feature or a bug, but `--forbid-only` crashes only in case of approaching `describe.only` but not `it.only`.

It caught me by a surprise.

Is it supposed to work that way? I assume it should crash same way it crashes for `describe.only`

**Comment by boneskull** [comment]
@medikoo It should be working (at least in `master`) as I can reproduce the failure 
 by running:

```shell
$ bin/mocha test/integration/fixtures/options/forbid-only/only.fixture.js
  forbid only - test marked with only
    1) test2


  0 passing (5ms)
  1 failing

  1) forbid only - test marked with only
       test2:
     Error: `.only` forbidden
      at Runner.runTest (lib/runner.js:515:8)
      at /Users/boneskull/projects/mochajs/mocha/lib/runner.js:647:12
      at next (lib/runner.js:441:14)
      at /Users/boneskull/projects/mochajs/mocha/lib/runner.js:451:7
      at next (lib/runner.js:362:14)
      at Immediate._onImmediate (lib/runner.js:419:5)
```

The contents of that file:

```js
'use strict';

describe('forbid only - test marked with only', function() {
  it('test1', function() {});
  it.only('test2', function() {});
  it('test3', function() {});
});

```

**Comment by medikoo** [comment]
@boneskull I looked closer into it, and narrowed it down.

The issue is, that it becomes ignored if `before`, crashes, e.g. following is nice minimal test case that exposes it:

```javascript
describe('something', () => {
  before(function() {
    this.skip();
  });
  it.only('only test', () => {});
});

describe('something else', () => {
  it('other test', () => {
    throw new Error('Fail');
  });
});
```

``Error: `.only` forbidden`` is reported, only if  `ths.skip()` is commented out, otherwise we have a successful pass.

To me it already looks as design issue fact that those errors are reported at test _runtime_, and not at test _definition_ phase (when mocha gathers all `describe` and `it` declarations).

Technically I would expect this error to be thrown before any test being run.

**Comment by boneskull** [comment]
I haven't independently confirmed this but seems plausible enough

**Comment by boneskull** [comment]
IIRC @outsideris changed it so `describe.skip` would be detected at this point, but it sounds like consolidating those checks at suite definition time is what we need to do.

**Comment by outsideris** [comment]
I confirmed this bug.

**Comment by rpgeeganage** [comment]
@boneskull ,
I like to help on fixing the bug and contribute.

**Comment by rpgeeganage** [comment]
@outsideris,
Shall I start working on this?

**Comment by rpgeeganage** [comment]
I have started looking into the bug 😄 😄

**Comment by outsideris** [comment]
@rpgeeganage Good. :)

**Comment by plroebuck** [comment]
> ```js
> describe('something', () => {
>   before(function() {
>     this.skip();
>   });
>   it.only('only test', () => {});
> });
> ```
> 
> `` Error: `.only` forbidden `` is reported, only if `this.skip()` is commented out, otherwise we have a successful pass.
> 
> To me it already looks as a design issue, fact that those errors are reported at test _runtime_, and not at test _definition_ phase (when mocha gathers all `describe` and `it` declarations).
> 
> Technically I would expect this error to be thrown before any test being run.

Unsure there is a _specified_ priority order in which tests are filtered out...
Relevant [comment](https://github.com/mochajs/mocha/issues/3630#issuecomment-450944170) from #3630...
