### ISSUE TITLE
JS-Yaml Denial of Service in v3.12

### ISSUE THREAD

**Issue by dannypaz** [mochajs/mocha#3842]
Just got a vulnerability message from npm on one of my repos using Mocha. Looks like the dep `js-yaml` needs to be updated from 3.12 to >=3.13
 
![Screen Shot 2019-03-21 at 2 47 01 PM](https://user-images.githubusercontent.com/5478311/54787222-48f4a800-4be8-11e9-884c-c73e296a4f77.png)

Link: https://npmjs.com/advisories/788

**Comment by elf-mouse** [comment]
+1

**Comment by Xilis** [comment]
Fixed in #3843

**Comment by mayrbenjamin92** [comment]
When will 6.1.0 be released?

**Comment by nolanmar511** [comment]
I'm very excited to see this issue is fixed!
I see it's already been asked, but when will 6.1.0 be released?

I use mocha and have npm audit as a presubmit check, and would love to see that check passing again.
