### ISSUE TITLE
Does Mocha encourage `this` for shared behaviors?

### ISSUE THREAD

**Issue by morgannewman** [mochajs/mocha#3844]
**Clarify whether Mocha encourage `this` context assignment**
[This 7 year old wiki](https://github.com/mochajs/mocha/wiki/Shared-Behaviours) encourages using `this` to store testing context in beforeEach(), tests, and afterEach() as an alternative to global variables.

>The "context" (this) is the same object within the "before each", "after each" hooks, and the test-case itself, allowing you to utilize this instead of closures to store data.

Can a maintainer clarify if this usage is encouraged?

**Comment by morgannewman** [comment]
@boneskull @tj @plroebuck any comment on this?

**Comment by plroebuck** [comment]
I've assigned this to @boneskull as this usage predates anything I've been exposed to.

Field ownership is unclear; don't see anything that explicitly documents which `this` fields are _solely_ for user to prevent future issues between Mocha and user.

Personally I use closures as a more self-apparent approach, but IIWM, I'd add whatever within a `this._clientData` object to eliminate potential for conflicts.

**Comment by noelmace** [comment]
@boneskull I have the same question, following https://github.com/open-wc/open-wc/issues/715. Do you think you could answer it here, or should we discuss this in Gitter?

**Comment by frankie-zeng** [comment]
how to handle this in typescript?
