### ISSUE TITLE
Assertion error while matching two errors

### ISSUE THREAD

**Issue by agrawalarpit14** [mochajs/mocha#3846]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

When an error is thrown and is asserted to be equal to a similar but manually crafted error, the results are as follows
```
      AssertionError: expected [Error: false] to equal [Error: false]
      + expected - actual
```

### Steps to Reproduce

Function to be checked
```
const checkIfPortIsAvailable = (port) => {
  return new Promise((resolve, reject) => {
    portscanner.checkPortStatus(port, function (error, status) {
      if (error) {
        throw new Error(error)
      } else {
        if (status === 'open') {
          logger.warn(`Port ${port} is not available (${colors.red('NOT OK')})`)
          reject(new Error(false))
          return
        }
        logger.info(`Port ${port} is available (${colors.green('OK')})`)
        resolve(true)
      }
    })
  })
}
```
Test Written
```
describe('open a server before running the test', () => {
      const testServer = net.createServer()
      before(() => {
        testServer.listen(3000)
      })

      it('should reject when port 3000 is open', () => {
        return checkIfPortIsAvailable(3000).then((result) => {
          expect(result).to.not.equal(true)
        }, (err) => {
          expect(err).to.equal(new Error(false))
        })
      })

      after(() => {
        testServer.close()
      })
    })
```

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: - and 6.0.1
- The output of `node --version`: v10.15.1
- Your operating system
  - name and version: macOS Mojave v10.14.1
  - architecture (32 or 64-bit): 64-bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh
- Your browser and version (if running browser tests): 
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):

**Comment by juergba** [comment]
```js
console.log(new Error('dadada') === new Error('dadada'));  // false
console.log({} === {});   // false
```
You are (strict) comparing two different objects, there reference is different.
Otherwise try deep equality.

**Comment by plroebuck** [comment]
Untested, but perhaps more to the point...
```js
const checkIfPortIsAvailable = port => {
  return new Promise((resolve, reject) => {
    portscanner.checkPortStatus(port, function (error, status) {
      if (error) {
        throw new Error(error)
      }

      if (status === 'open') {
        logger.warn(`Port ${port} is not available (${colors.red('NOT OK')})`)
        return reject()
      } else {
        logger.info(`Port ${port} is available (${colors.green('OK')})`)
        return resolve()
      }
    })
  })
}
```

```js
const net = require('net')
const chai = require('chai')
const chaiAsPromised = require('chai-as-promised')
chai.use(chaiAsPromised)
const expect = chai.expect

describe('when another server is already running', () => {
  const testServer = net.createServer()
  const port = process.env.PORT || 3000

  before(done => {
    testServer.listen(port, done)
  })

  it('should reject if port already in use', () => {
    return checkIfPortIsAvailable(port)
      .then(result => {
        expect(result).not.to.be.fullfilled
      })
      .catch(err => {
        expect(err).to.be.rejected
         .and.to.eventually.be.undefined
      })
  })

  after(done => {
    testServer.close(done)
  })
})
```
