### ISSUE TITLE
Medium severity vulnerability via js-yaml@3.12.0

### ISSUE THREAD

**Issue by mceachen** [mochajs/mocha#3857]
### Description

`$ snyk test --dev`

Medium severity vulnerability found in js-yaml
Description: Denial of Service (DoS)
Info: https://snyk.io/vuln/SNYK-JS-JSYAML-173999
Introduced through: electron-mocha@7.0.0
From: electron-mocha@7.0.0 > mocha@6.0.2 > js-yaml@3.12.0

Pulling in js-yaml version 3.13.0 or higher will address this.

See also: https://www.npmjs.com/advisories/788

**Comment by juergba** [comment]
Thanks, please see #3845
This issue has already been fixed in current master and will be released with v6.1.0 shortly.
