### ISSUE TITLE
DoS vulnerability in global dependency

### ISSUE THREAD

**Issue by TasiPeter** [mochajs/mocha#3858]
The version 6.0.2 is dependent on **js-yaml** version 3.12.0, which has a DoS vulnerability  issue as stated here:

[https://nodesecurity.io/advisories/788](https://nodesecurity.io/advisories/788)

Updating to version 3.13.0 should solve the problem.

**Comment by juergba** [comment]
Thanks, please see #3845
This issue has already been fixed in current master and will be released with v6.1.0 shortly.
