### ISSUE TITLE
Error after updating to 6.1.0

### ISSUE THREAD

**Issue by njzjz** [mochajs/mocha#3866]
```
$ yarn test
yarn run v1.3.2
(node:6135) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
warning package.json: License should be a valid SPDX license expression
$ NODE_ICU_DATA='node_modules/full-icu' nyc mocha test/test
: No such file or directory
```

full log: https://travis-ci.com/njzjz/chemicaltools-js/jobs/190964352

But it worked fine before.

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by njzjz** [comment]
Before updating it worked well.
https://travis-ci.com/njzjz/chemicaltools-js/jobs/190893338

**Comment by jasonk** [comment]
I just ran into this too.  If you just run `mocha` without anything wrapping it the problem becomes clearer:

```
$ mocha
env: node\r: No such file or directory
```

It seems the package was published with CRLF line endings, which will cause issues on non-windows platforms:
```
$ file *.js bin/* lib/*.js
browser-entry.js:       ASCII text, with CRLF line terminators
index.js:               ASCII text, with CRLF line terminators
mocha.js:               UTF-8 Unicode text, with very long lines, with CRLF, LF line terminators
bin/_mocha:             a /usr/bin/env node script text executable, ASCII text, with CRLF line terminators
bin/mocha:              a /usr/bin/env node script text executable, ASCII text, with CRLF line terminators
bin/options.js:         ASCII text, with CRLF line terminators
lib/context.js:         ASCII text, with CRLF line terminators
lib/errors.js:          ASCII text, with CRLF line terminators
lib/growl.js:           ASCII text, with CRLF line terminators
lib/hook.js:            ASCII text, with CRLF line terminators
lib/mocha.js:           ASCII text, with CRLF line terminators
lib/pending.js:         ASCII text, with CRLF line terminators
lib/runnable.js:        ASCII text, with CRLF line terminators
lib/runner.js:          UTF-8 Unicode text, with CRLF line terminators
lib/stats-collector.js: ASCII text, with CRLF line terminators
lib/suite.js:           ASCII text, with CRLF line terminators
lib/test.js:            ASCII text, with CRLF line terminators
lib/utils.js:           ASCII text, with CRLF line terminators
```

**Comment by AviVahl** [comment]
yeah, shebang in `/bin/mocha` got broken because of the `\r`.
This renders mocha cli useless on many Unix-based systems (I use Fedora).
@juergba

**Comment by juergba** [comment]
yes, I have seen it. I'm working on it. Any suggestions?

**Comment by kevinoid** [comment]
I agree with @jasonk and @AviVahl that the `\r` on the shebang line is causing breakage.  I just wanted to note that the shebang is automatically fixed during installation by npm v5.4.0 and later (due to npm/npm@0ef320cb4 from npm/npm#16634).  So the breakage is conditional on the version of npm used to install `mocha`.

**Comment by AviVahl** [comment]
@juergba thx for the quick response.
check this out: https://help.github.com/en/articles/dealing-with-line-endings
you might want to add a .gitattributes file to the repo and rerelease with LF line endings.

**Comment by AviVahl** [comment]
@kevinoid I personally use latest `yarn@1.15.2` and it breaks there...

**Comment by kevinoid** [comment]
@AviVahl Does `yarn` change the shebang line itself?  If not, that would explain why `yarn` is also affected.

**Comment by cspotcode** [comment]
Came here to suggest the gitattributes approach as well.  It'll force LF checkouts on all platforms; I add one religiously to all new projects.

`* text=auto EOL=LF`

**Comment by AviVahl** [comment]
@kevinoid I guess they leave the file untouched. AFAIK, on Linux, `yarn` basically creates symlink from `.bin` to the file specified in the `".bin"` field of the package's `package.json`. If that file was published with CRLF, it breaks. This is unlike the Windows behavior, where a proxy `.cmd` file is auto-created by `yarn`/`npm`.

**Comment by juergba** [comment]
@cspotcode can we chat please on gitter?

**Comment by jasonk** [comment]
Since mocha is already using prettier, the easy fix would be to change the prettier config in `package.json` to enforce specific line endings instead of just keeping whatever is there, and to ensure that prettier gets run before publishing...

```
// in package.json:
...
"scripts": {
  "prepublishOnly": "nps format test clean build",
},
"prettier": {
  "endOfLine": "nl"
}
```

**Comment by borisovg** [comment]
FYI this makes tests fail Travis when using Node 6.

**Comment by AlexZeitler** [comment]
CircleCI is broken as well using Node 10.

**Comment by juergba** [comment]
@AlexZeitler on Unix as well?

**Comment by AlexZeitler** [comment]
@juergba Not on my local machine (Ubuntu 18.04) but in CircleCI:
https://circleci.com/gh/PDMLab/httpproblem/15

**Comment by mceachen** [comment]
@juergba thanks for addressing this.

I'm surprised that the [smoke test in CI](https://travis-ci.org/mochajs/mocha/jobs/516888314) didn't catch this issue. 

If you want help setting up CI on other platforms (mac on travis and windows on appveyor), I'd be happy to help you do that (the PR is not that much work, it's mostly creating the appveyor account, which has to be done by a committer).

**Comment by juergba** [comment]
@mceachen 
Thanks, we have windows tests on appveyor. It seems pushing to github was fine, just `npm publish` went wrong.

**Comment by cspotcode** [comment]
The problem was the `npm publish` command run on Windows produced a tarball
that could not run on Linux.  I don't think the smoke test deals with that.

**Comment by AlexZeitler** [comment]
@juergba Upgrading to `6.1.1` fixed it :+1:

**Comment by juergba** [comment]
@AlexZeitler thank you for your confirmation!

**Comment by mceachen** [comment]
> @mceachen
> Thanks, we have windows tests on appveyor.

Ah, that's great. I didn't see a badge for the build in the header of the README.

**Comment by boneskull** [comment]
> The problem was the `npm publish` command run on Windows produced a tarball
that could not run on Linux.  I don't think the smoke test deals with that.

@juergba How did you fix this?

**Comment by boneskull** [comment]
n/m, `.gitattributes` change.
