### ISSUE TITLE
bin/mocha and bin/_mocha have no exe permission in 6.1.x

### ISSUE THREAD

**Issue by Flarna** [mochajs/mocha#3867]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

It seems the the files `bin/mocha` and `bin/_mocha` have no exe permissions in 6.1.0 and 6.1.1. If I do an `npm install --no-bin-links` and try `./node_modules/mocha/bin/_mocha` (or `mocha`) I get `Permission denied` in linux.

At least in 6.0.2 these files had `rwx` permissions.

### Steps to Reproduce

Linux environment needed
`npm install --no-bin-links`
`./node_modules/mocha/bin/_mocha` or
`./node_modules/mocha/bin/mocha`

**Expected behavior:** [What you expect to happen]
file is executable and actually `node ./node_modules/mocha/bin/_mocha` get's executed.

**Actual behavior:** [What actually happens]

File is not executable and therefore `Permission denied` happens.

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 6.1.1
- The output of `node --version`: 10.15.3
- Your operating system
  - name and version: Linux Ubuntu 18.04
  - architecture (32 or 64-bit): 64
- Your shell (e.g., bash, zsh, PowerShell, cmd): bash
- Your browser and version (if running browser tests): -
- Any third-party Mocha-related modules (and their versions): -
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): -

**Comment by boneskull** [comment]
@juergba I think you might need to fix this on your side if you're going to be publishing.  I've re-published to work around the issue, but we need to ensure that the file modes are set properly when publishing from windows. 

This is a Git issue.  When you cloned, it's likely the permissions for `bin/mocha`, `bin/_mocha` and `lib/cli/cli.js` were lost.  These URLs might help... 

- http://blog.lesc.se/2011/11/how-to-change-file-premissions-in-git.html
- https://stackoverflow.com/questions/6476513/git-file-permissions-on-windows

**Comment by boneskull** [comment]
Also, WSL or Git-for-Windows' cygwin thing might help?  not sure.

**Comment by boneskull** [comment]
@Flarna This has been (temporarily) fixed in v6.1.2:

![image](https://user-images.githubusercontent.com/924465/55747995-63a18c00-59f2-11e9-96ea-684ee32296cc.png)

**Comment by boneskull** [comment]
whoa 1985? wtf

**Comment by plroebuck** [comment]
> whoa 1985? wtf

What are you talking about?

**Comment by plroebuck** [comment]
```sh
$ touch 201902081301 bin/mocha
$ touch 201811291355 bin/_mocha bin/options.js
```

**Comment by plroebuck** [comment]
The "npm" registry needs work...
_We need to unpublish both mocha-6.1.0 and 6.1.1; don't need users downloading either of these._
**Unpublishing must occur within 72 hours!**

Further, mocha@next is somehow set to "6.0.2"

**Comment by plroebuck** [comment]
If using Windows, use this to prevent file permission changes to UN*X scripts:
```cmd
C:> git config --local core.fileMode false
```

**Comment by Flarna** [comment]
Thanks!

**Comment by plroebuck** [comment]
@juergba, note the npm issues!

**Comment by cspotcode** [comment]
Related:
https://github.com/npm/npm/issues/16645

IMO this is an npm issue that's never been fixed.

**Comment by boneskull** [comment]
see also https://github.com/npm/node-tar/issues/210 which may be where the fix needs to live
