### ISSUE TITLE
"stats" field is missing in JSON reporter in mocha@6

### ISSUE THREAD

**Issue by 1999** [mochajs/mocha#3875]
Hi, I'm working on mocha-parallel-tests project which is aiming to run mocha files in parallel. I'm trying to support mocha@6 right now and faced an issue with JSON reporter: it looks like it doesn't have a "stats" field in mocha@6 whereas in mocha@5 the field was there. It wasn't mentioned as a breaking change so I'm wondering if it's a bug or just a missing breaking change thing.

### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

JSON reporter of mocha@6 is missing the "stats" field

### Steps to Reproduce

Run any test with `mocha -R json`. In mocha@5 stdout has a "stats" field, in mocha@6 it doesn't.

**Expected behavior:** JSON reporter in mocha@6 should have a "stats" field or it should be mentioned in the breaking changes of mocha@6 release.

**Actual behavior:** stdout of JSON reporter doesn't have a "stats" field.

**Reproduces how often:** always

**Comment by plroebuck** [comment]
You mean this `stats` field?
https://github.com/mochajs/mocha/blob/f1fe632a5aca224994fa8c1240be6852bec236a8/lib/reporters/json.js#L34
https://github.com/mochajs/mocha/blob/f1fe632a5aca224994fa8c1240be6852bec236a8/lib/reporters/base.js#L280

**Comment by 1999** [comment]
Sorry for taking your time @plroebuck, I should not create bugs after 10pm probably :) This was a bug on my side - for some reason "stats" field was missing in the code I was running.
