### ISSUE TITLE
Drop Node.js 6.x support

### ISSUE THREAD

**Issue by outsideris** [mochajs/mocha#3884]
Node.js v6 will be the end of life on April 30th.

There isn't an issue to drop supporting Node.js v6 for me. Do you know any problem?

**Comment by juergba** [comment]
Then the `debug` options could be deprecated as well.

**Comment by Bamieh** [comment]
No problems for us in dropping support for Node.js v6 that I know of.

**Comment by mojosoeun** [comment]
@juergba what you said means is `--debug` or `--debug-brk` could be deprecated. right?
https://mochajs.org/#-debug-inspect-debug-brk-inspect-brk-debug-inspect
