### ISSUE TITLE
--exit returns non-zero exit code and CI tool returns failure

### ISSUE THREAD

**Issue by jiteshsojitra** [mochajs/mocha#3898]
As we all know, we can use --exit in mocha command to exit the tests. We are using this especially for leaving opened application to save the time (instead of opening and closing desktop app using Spectron).

But the problem with --exit in CI returns exit code as non-zero so tool keeps complaining that automation failed. Is there any solution for this with --exit? Is there any way to return 0 always on Windows powershell with mocha command as an alternative?

**Comment by plroebuck** [comment]
Don't do Windows in general... bash would simply use "||" to accomplish this.

But in that spirit, it would seem the idea is to run mocha within another script and force the exit code `0`. Maybe something like this guy's [approach](https://weblogs.asp.net/soever/returning-an-exit-code-from-a-powershell-script)?

**Comment by jiteshsojitra** [comment]
Agreed but i don't have any option due to Windows dependency. This approach doesn't allow to modify exit code to 0.

**Comment by plroebuck** [comment]
Don't follow -- that _was_ a Windows solution.
Well, what about something like this (untested)...

**"\<project\>/bin/run_mocha"**
```js
var childProcess = require('child_process');
var path = require('path');

var mochaBin = path.join(__dirname, 'node_modules', '.bin', 'mocha');
var args = [
  mochaBin,
  process.argv.slice(2)
];
var options = {
    stdio: 'inherit'
};

childProcess.spawn(process.execPath, args, options)
  .on('exit', function(code, signal) {
    process.on('exit', function() {
      if (signal) {
        process.kill(process.pid, signal);
      } else {
        process.exit((process.env.CI === 'true') ? 0 : code);
      } 
    });
  });
```

**Comment by plroebuck** [comment]
Did the above work for you?

**Comment by jiteshsojitra** [comment]
Thanks Plorebuck for helping me, i had special requirement for Windows.
