### ISSUE TITLE
Is it possible to parallel run the test cases ?

### ISSUE THREAD

**Issue by RyanLiuF** [mochajs/mocha#3907]
There are multiple the separate  JS files, if the sequential execution will take more time, it will save a lot of time to be able to run in parallel.
So I advise that the mocha will be more perfect if it supports to parallel run the test case.

**Comment by martinoppitz** [comment]
try mocha-parallel

**Comment by plroebuck** [comment]
Various reporters write output as they process events on the fly; output is **not** buffered. If run in parallel, the output from different specs would be intermixed.

If insistent on going parallel route, suggest using [mocha-parallel-tests](https://www.npmjs.com/package/mocha-parallel-tests) package. Read [comparison](https://github.com/mocha-parallel/mocha-parallel-tests/wiki/Comparison-with-mocha.parallel) against [mocha-parallel](https://www.npmjs.com/package/mocha.parallel) package.

**Comment by RyanLiuF** [comment]
I will try to use [mocha-parallel-tests](https://www.npmjs.com/package/mocha-parallel-tests). Very thanks.
