### ISSUE TITLE
Push required module options not possible

### ISSUE THREAD

**Issue by martinoppitz** [mochajs/mocha#3908]
For example we use @babel/register.

In this module is default: ignore node_modules

Is there any way to do this?

**Comment by martinoppitz** [comment]
See too: https://github.com/babel/babel/issues/9961

**Comment by juergba** [comment]
@martinoppitz you got an answer to your question in your babel issue.
Please close this issue, when that solution has been working for you.

**Comment by martinoppitz** [comment]
@juergba Yes that is correct, but hoped I can config that in .mochrc too.

**Comment by plroebuck** [comment]
Maybe it's just me but it seems rather wrongheaded to be compiling _anything_ in "node_modules" since they're already installed. If the installed packages require babelizing, that should be done by the packages themselves...

**Comment by juergba** [comment]
@martinoppitz no, that's not possible and currently there are no plans/resources to implement your hopes.

I guess you could also use one of `Babel`s configuration files as `babel.config.js` to pass your options to `Babel`.
