### ISSUE TITLE
Tests teardown is unnecessary delayed (creates unexpected states)

### ISSUE THREAD

**Issue by medikoo** [mochajs/mocha#3920]
When running tests in Node.js, to avoid long stack traces, each next test run scheduled with [`setImmediate`](https://github.com/mochajs/mocha/blob/94033bf5f5d4266caa8b53f3eb4b1b1de76a114c/lib/runner.js#L153)

In Node.js `setImmediate` is slower than `process.nextTick` (obviously) and `setTimeout` (not that obvious).

This creates undesired race conditions when in some specific scenarios e.g. forgotten `return promise` is not exposed with failure (which otherwise may happen)

Test case exposing unexpected state:

```javascript
describe('test', () => {
  let foo;

  before(() => (foo = 'in test'));
  after(() => (foo = 'out of test'));

  it('test', () => {
    setTimeout(() => {
      if (foo === 'in test') throw new Error('Unexpected state');
    });
  });
});
```
--- 
macOS: 10.14.4
Node.js: v12.2.0
Mocha: v6.1.4

**Comment by plroebuck** [comment]
From [Flavio's blog](https://flaviocopes.com/node-setimmediate/) (emphasis mine):

> A function passed to process.nextTick() is going to be executed on the current iteration of the event loop, after the current operation ends. This means it will always execute before setTimeout and setImmediate.
>
> A setTimeout() callback with a 0ms delay is very similar to setImmediate(). _The execution order will depend on various factors, but they will be both run in the next iteration of the event loop._

**Comment by medikoo** [comment]
@plroebuck point is that ideally test teardown should be made immediately after test finishes.

As I read from commit history Mocha introduced a _gap_ between test finish and teardown, purely to ensure that stack traces do not go down to previous test runs

Currently Mocha to introduce a gap with `setImmediate` which in node.js introduces observably longer gap than `process.nextTick` or `setTimeout(fn, 0)`.

This more often leads to scenarios where code that's supposed to be executed _after_ test teardown is executed _before_.

It's very easy to improve, just by ensuring: `Runner.immediately = process.nextTick` in Node.js, and this is how I patch this issue in projects I use Mocha with.

**Comment by plroebuck** [comment]
Your example checks for an asynchronously changing state via `setTimeout` (which would not execute within `it`); believe this test is just poorly designed to begin with.

My reading would imply that execution order of `setImmediate` and `setTimeout` callbacks may vary, not the massive gap you portray. Either way, the test would be improved by **not** depending on async execution order.

Don't see us changing this if code was previously changed to avoid some other bug...

> This leads to scenarios where code that's supposed to be executed _after_ test teardown is executed _before_.

The code should be written to do its teardown _within_ `after` rather than after.

**Comment by medikoo** [comment]
> believe this test is just poorly designed to begin with.

Exactly, I opened this issue because currently Mocha hides such issues, which I believe should not be the case.

I approached that problem, when fixing [test setup issues](https://github.com/serverless/serverless/issues/6116) in project that has serious problems with it, and of the reasons for that is that Mocha hides bugs in tests setup.
