### ISSUE TITLE
Can we get a mention in the docs somewhere for @testdeck/mocha?

### ISSUE THREAD

**Issue by silkentrance** [mochajs/mocha#3923]
## Question

We have created a wrapper for existing test frameworks, including also mocha.
Please see https://github.com/testdeck/testdeck and also https://github.com/testdeck/testdeck-mocha-seed for a working minimal setup.

Perhaps you can give us a little boost by mentioning the project in your official documentation?

TIA!

**Comment by juergba** [comment]
@silkentrance 
Mentioning your project somewhere on our documentation would mean: we recommend your project to our users. We couldn't do that in a sincere manner without evaluating your project first. We are a small team and unfortunately don't have resources for similar tasks.
This is may personal opinion, I'm sorry.

**Comment by silkentrance** [comment]
@juergba I see that you do not have anything similar to a curated list of third party mocha reporters and uis, so I guess that this is ok with me. Not that it will help much, but @testdeck/mocha is actually the successor of mocha-typescript. Closing.
