### ISSUE TITLE
Pass meta

### ISSUE THREAD

**Issue by Chris-Eckersley** [mochajs/mocha#3925]

**Comment by Chris-Eckersley** [comment]
Is there a way to add data or extra properties onto the error object?

I'm running e2e tests that make http requests and then asserting on the response object.

If the assertion fails I'd like to pass both the request and response object to the reporter to display with report.

**Comment by craigtaub** [comment]
I think that might be something an assertion library can help you with (e.g. https://www.chaijs.com/guide/plugins/, https://nodejs.org/api/assert.html#assert_assert_value_message). 

If you can get to the req object, i see no reason why you should not be able to print it.

**Comment by plroebuck** [comment]
Closing per #3928 recommendation of using "axios" package.
