### ISSUE TITLE
Testing interpreter written in JavaScript

### ISSUE THREAD

**Issue by jcubic** [mochajs/mocha#3926]
My question is this, can I use mocha to test something like this:

**test.js**
```javascript
const fs = require('fs');

fs.readFile('test.test', (err, data) => {
  // this is just example in my real code I'm testing interpreter library
  // that have access to JavaScript so it can call describe and it functions
  eval(data.toString()); 
});
```

where my test.test have this code:

**test.test**
```javascript
console.log('1');

var assert = require('assert');

describe('xxx', function() {
   console.log('2');
   it('xxx', function() {
      console.log('3');
      assert.equal([1, 2, 3].indexOf(4), -1);
   });
});
```

When I run

mocha test.js

I've got
```
1
2
```
no 3 and 0 test passing (it is not executed)

One additional thing is that in my library `lips.exec` I use instead of eval return a promise. Can I use mocha with something like this?

**Comment by plroebuck** [comment]
No promises (and unsupported...)
```js
const fs = require('fs');
const Mocha = require('mocha');

const mocha = new Mocha({});
const specfile = './test.spec';

const evalContent = new Promise(resolve => {
  fs.readFile(specfile, (err, data) => {
    if (err) {
      throw err;
    }
    const content = data.toString();
    resolve(eval(content));
  });
});

evalContent
  .then(suite => {
    mocha.suite = suite;
    mocha.run();
  })
  .catch(err => {
    console.error('well that went sideways... ', err);
  });
```

**Comment by jcubic** [comment]
IS this working example? Becuse you said it's not supported but you provided the code. What is suite variable suppose to be, isn't this just be undefined, if you don't have expression in eval? Where can I find it and describe functions for use with eval?

**Comment by plroebuck** [comment]
> IS this working example? Becuse you said it's not supported but you provided the code. What is suite variable suppose to be, isn't this just be `undefined`, if you don't have expression in `eval?` Where can I find `it` and `describe` functions for use with `eval`?

You asked "can I use mocha to test something like this?" -- maybe...
It's a working example for _your_ test spec file. Will it work for others? Don't know,
but not supporting your use case if not; [Mocha.loadFiles](https://github.com/mochajs/mocha/blob/master/lib/mocha.js#L324) is the supported means of doing so.

The sheer number of possible bad outcomes from `eval`ing random JS _should_ have convinced 
you **not** to go this route anyway... Read [this](https://odino.org/eval-no-more-understanding-vm-vm2-nodejs/) if you haven't already!

**Comment by jcubic** [comment]
I'm not doing real JS eval I have my own interpreter that is async (`lips.exec`), it call JS code from different language, so if JS have `describe` or `it` it will call it. I want my language test to be written in same testing framework as my parser that is called in JS, so I can have code coverage of JS code.
