### ISSUE TITLE
Adding data to the Error object

### ISSUE THREAD

**Issue by Chris-Eckersley** [mochajs/mocha#3928]
Hello all- awesome code base to read!

Is there a way I can append to the error object from within an `it` block?

Thank you!

**Comment by Chris-Eckersley** [comment]
An example would be:
`
it('should send info about the request if it fails', async function(){ 
  const postData = await request.post('https://some.endpoint.com/user')
    .set({ Authorization: `Bearer 55555555555` })
    .send({
      someData: 'stuff'
    })
    .retry(2);

    expect(postData.status).to.equal(204);

  // If this 'it' block fails I'd like to see the post data in the 
  // error response object for reporting.
  // It should including the path, params, request body, and 
  // the http response status.
})
`

**Comment by juergba** [comment]
Please note this issue tracker is not a help forum. We recommend using [gitter](https://gitter.im/mochajs/mocha) for questions.

**Comment by plroebuck** [comment]
Suggest using [axios](https://www.npmjs.com/package/axios) instead. It's promise-based and [already provides this](https://github.com/axios/axios/#handling-errors).

**Comment by Chris-Eckersley** [comment]
Thanks @plroebuck . I don't think the request library applies to this use case.

Axios (like superagnet) is promise based. If a superagent request fails (receives a 4xx, 5xx, etc.) it will throw an error and pass extra data to mocha. I can see that in the JSON reporter.

The use case I'm referring to is this:
1. The axio request receives a http 200 status.
2. I expect the response body to have an 'isActive' property and the assertion fails.

In the report (and in the error body) I'd like to see information about the successful axios request which  received a 200 but the assertion in the `it` block failed.

**Comment by plroebuck** [comment]
Something like this?
```js
const axios = require('axios');

describe('HTTP', function() {
  it('should be successful', async function() {
    return await axios.get(url, options)
      .then(function (response) {
        expect(response.status, 'to be', 200);
        try {
          const body = response.data;
          expect(body.isActive, 'to be true');
        } catch (err) {
          const { request, ...moar } = response;
          err.request = request;
          err.response = moar;
          throw err; // Rethrow
        }
      });
  });
});
```

If you instead treat the expectations as [postconditions](https://en.wikipedia.org/wiki/Postcondition), assertion failure _implies_ the response body without the need for such gymnastics.

**Comment by Chris-Eckersley** [comment]
We are getting really close!
Instead of using axios directly we are using a client API that uses axios (some use superagent) and then we are calling that API from within the test.

`
const AccountClient = require('../api/Account_client.js');

describe('HTTP', function() {
  it('should be successful', async function() {
    const response = await AccountClient.getActiveStatus(url, options);// Returns a promise from axios

    expect(response).to.have.property('isActive'); // Test will fail
  });
});
`

If the tests fails I want to get append the response object returned from axios onto/in the error  in the report.
