### ISSUE TITLE
Why does describe.skip still execute code in the suite?

### ISSUE THREAD

**Issue by oliversalzburg** [mochajs/mocha#3932]
In a test file I have code similar to this:
```js
describe.skip( "skip this", () => {
	throw new Error( "was executed anyway" );
} );
```

I expected that `describe.skip` skips executing the entire suite, but it only skips executing _tests_ declared in it. Is that by-design? I feel like the documentation is unclear about this.

**Comment by juergba** [comment]
Yes, this behavior is made by design, please see https://github.com/mochajs/mocha/issues/3630#issuecomment-450944170

**Comment by plroebuck** [comment]
Although the comment from #3630 answers his question, I'm reopening this.

Since it is not the first issue brought up on the subject, the [relevant documentation](https://mochajs.org/#pending-tests) should be updated to make clear that `describe.skip` is _really_ just syntactic sugar for marking any child test (`it`) as if it had been written as `it.skip`, but the namespace (i.e., `describe`'s function argument) is _still_ executed.

**Comment by oliversalzburg** [comment]
@plroebuck That'd be great. I often refer to the mocha documentation, even though I have been using it for years and this surprised me. I'm amazed I haven't noticed this earlier.

But I believe the relevant documentation should be https://mochajs.org/#inclusive-tests, which currently states:

>  By appending .skip(), you may tell Mocha to simply ignore these suite(s) and test case(s). 

This is misleading, because the suites aren't ignored, only the tests contained within them.

**Comment by plroebuck** [comment]
@oliversalzburg, care to draft what it should say?

**Comment by oliversalzburg** [comment]
The documentation currently starts the introduction to inclusive tests with suites, then points out the behavior for individual tests. I think it would be better to start with the tests, then say that putting `.skip` on a suite is identical to putting `.skip` on every test in the suite (and that is also overrides any `.only` on tests in that suite) and skipping hooks declared in the suite. 

I believe that is different, because if you'd put `.skip` on every test individually, then you'd have no reason to think remaining code in the suite was ignored.

What do you think?

**Comment by plroebuck** [comment]
Difficult to evaluate without seeing the replacement text...

**Comment by oliversalzburg** [comment]
@plroebuck Could you have a look at [my PR](https://github.com/mochajs/mocha/pull/3947)?
