### ISSUE TITLE
Specify setup/teardown for each test individually

### ISSUE THREAD

**Issue by eight04** [mochajs/mocha#3935]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**

Currently, we can:

1. Define a setup/teardown for a `describe` block by using `before`/`after`.
2. Define a setup/teardown for *all* `it` blocks by using `beforeEach`/`afterEach`.

There is no way to define a setup/teardown for *one* `it` block.

As a workaround, I'm putting the setup code *inside* the `it` block. Downside:

1. The setup code is mixed with the calculation.
2. The setup time is also counted in the timing.

**Describe the solution you'd like**

Some proposals:

1. Make `it` accept more arguments to define setup/teardown:
    ```js
    it(
      "my test",
      () => {
        // setup
      },
      () => {
        // test
      },
      () => {
        // teardown
      }
    );
    // look better with an option object
    it({
      name: "my test",
      setup() {
        // ...
      },
      test() {
        // ...
      },
      teardown() {
        // ...
      }
    });
    ```
2. Add new block (or reuse `before`, `after`) inside `it`:
    ```js
    it("my test", () => {
      itBefore(() => {
        // ...
      });
      // test
      itAfter(() => {
        // ...
      });
    });
    ```
3. Allows the test to emit an event to indicate the current phase:
    ```js
    it("my test", function () {
      this.section("setup");
      // ...
      
      this.section("test");
      // ...
      
      this.section("teardown");
      // ...
    });
    ```

**Describe alternatives you've considered**

**Additional context**

This should be handy for [dynamically-generated tests](https://mochajs.org/#dynamically-generating-tests) since they often have to read some data from the disk before running the actual test.

**Comment by plroebuck** [comment]
Or perhaps more simply, just put a `describe` around the test (`it`) that you want to add hooks for setup/teardown. No changes required and backwards/forwards-compatible.

**Comment by eight04** [comment]
That is another workaround. It prints an additional line for each test as the downside:
![image](https://user-images.githubusercontent.com/1324510/58761272-0bf84a80-8575-11e9-9b18-4a415c2bf802.png)

**Comment by outsideris** [comment]
Why don't you just put setup/teardown in your `it` test case if the setup/teardown is for only one?

**Comment by eight04** [comment]
> Why don't you just put setup/teardown in your `it` test case if the setup/teardown is for only one?

As I mentioned in the first comment:



> As a workaround, I'm putting the setup code _inside_ the `it` block. Downside:
> 
> 1. The setup code is mixed with the calculation.
> 2. The setup time is also counted in the timing.

**Comment by justinasfour04** [comment]
I agree with @eight04. I'm facing this problem right now. I want to stub functions before each dynamically created test. The beforeEach function uses different data for each it()

**Comment by JoshuaKGoldberg** [comment]
This is a rather old issue that hasn't had much user engagement. Per #5027 we're trying to avoid big changes. Closing as wontfix. Someone please yell at me if there's a good reason to re-open though!
