### ISSUE TITLE
🚀 Feature: Crash or issue warnings on invalid config parameters

### ISSUE THREAD

**Issue by medikoo** [mochajs/mocha#3936]
By mistake I've setup a configuration in `package.json` as:

```json
  "mocha": {
    "-R": "tests/mocha-reporter"
  }
```

Mocha didn't say the word, and ignored an invalid option (it should be `R` instead of `-R`).

It'll be great if Mocha produces some feedback on such errors, so they do not come unnoticed.

Node.js v12.3.1
Mocha: v6.1.4

**Comment by Alhadis** [comment]
That could screw with extensions that use Mocha's config for their own settings.

**Comment by plroebuck** [comment]
John, you have a Gitter acct so we could chat?

**Comment by Alhadis** [comment]
@plroebuck Nope, only an email. Is something wrong...?

**Comment by medikoo** [comment]
I rememeber that mocha@5 produced errors on incorrect CLI options, as:

```bash
$ npx mocha --foo .

  error: unknown option `--foo'
```

That was quite helpful. Still I see with v6 it's no longer the case

**Comment by Alhadis** [comment]
@medikoo An invalid option passed on the command line is expected to raise an error (as per long-standing conventions). But configuration need not enforce the same restrictions.

**Comment by medikoo** [comment]
Ok, so if I want to maintain params validation, best option for me to go is with `mocha.opts` ?

Still, anyway I see that args validation is gone with Mocha v6, feels like regression.

**Comment by medikoo** [comment]
Also it'll be better if extensions have dedicated namespace for their own options. It's how it's usually solved, that way they do not interfere with main options.

**Comment by Alhadis** [comment]
What about backwards compatibility? A version of Mocha that adds an option in a minor release would technically be a breaking change, as setups using that new option would fail to run with older versions.

**Comment by medikoo** [comment]
> A version of Mocha that adds an option in a minor release would technically be a breaking change, 

A case when upgrade to new version switches from _crashing_ setup to _non-crashing_ one, is not a breaking change. It can be about bug fix or feature addition/improvement.

It's the other way when it's breaking (switch from _non-crashing_ to _crashing_) but also only when we categorize the update as the _feature_ not a _bug fix_

**Comment by Alhadis** [comment]
It still seems like an awfully draconian measure that adds more problems than it solves.

**Comment by plroebuck** [comment]
@Alhadis wrote:
> Nope, only an email. Is something wrong...?

Could you join Gitter? Wanted to chat on possible problems for something terminal-related.

**Comment by plroebuck** [comment]
> Ok, so if I want to maintain params validation, best option for me to go is with `mocha.opts` ?

Definitely not -- "mocha.opts" is going away RSN.

**Comment by plroebuck** [comment]
> Mocha didn't say the word, and ignored an invalid option (it should be R instead of -R).

Actually, that's incorrect as well (and likely only working due to happy accident).
It should be "reporter", not "R".

See [example config](https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml) for valid names.

**Comment by Alhadis** [comment]
> Could you join Gitter? Wanted to chat on possible problems for something terminal-related.

Sorry, I forgot about this. I've joined.

**Comment by JoshuaKGoldberg** [comment]
Per #5027, we're trying to avoid making big changes that don't have a lot user demand. This hasn't been touched since 2019 and hasn't had a lot of users asking for it. Closing out as wontfix.

If someone things I'm wrong to close this out, great! Please file a new issue with your reasoning and a link to this one. The new issue templates will prompt for the context we'd need to be able to re-triage this. We'd be happy to take a look. Cheers all! 🤎
