### ISSUE TITLE
Uncaught exceptions are silenced if happen in timeframe of skipped test

### ISSUE THREAD

**Issue by medikoo** [mochajs/mocha#3938]
Possibly related to https://github.com/mochajs/mocha/issues/3740

### Steps to Reproduce

```javascript
describe('test', () => {
  it('test1', () => {
    setTimeout(() => {
      throw new Error('Uncaught');
    }, 3);
  });
  it('test2', function () {
    this.skip();
  });
  it('test3', function () {
    this.skip();
  });
  it('test4', function () {
    this.skip();
  });
});
```

**Expected behavior:**

Tests should fail unconditionally

**Actual behavior:**

In most cases suite passes (there is a race condition,due to which occasionally error gets exposed)

### Versions

mocha:  6.1.4
Node.js: 12.3.1
macOS: 10.14.5

**Comment by plroebuck** [comment]
Test1 should pass, though the error may get caught outside the test itself (depending on timing).
Recode as async test (using `done` or `Promise`) if you want to catch `Error` from `setTimeout`.

All other tests should be marked pending regardless.

**Comment by medikoo** [comment]
It's a question of how mocha handles the case, when user misconfigured the test so it results with unhandled exception.

I believe the goal is to expose them to user as errors, in this case it's to doesn't happen, therefore it's a bug.

**Comment by plroebuck** [comment]
Which part of my reply are you implying Mocha does incorrectly here? Test1 or the other three?

Your "Expected Behavior" is hard to tell what you expect -- did you mean "all" tests or only the attempted fail of first one?

**Comment by medikoo** [comment]
> Which part of my reply are you implying Mocha does incorrectly here

Incorrect is assumption that developers do not make mistakes.

In discussed case, test by mistake was configured that it ends before an actual job it started ends. The left over job additionally raises an uncaught exception (currently silenced by Mocha, therefore developer is left with no clue the tests setup is broken)

I believe Test runner should not silence uncaught exceptions, no matter in what context they exploded, whether it was failed test, pending test, or maybe after all tests were registered as ended.

It general it goes down to rule: _unhandled errors should not be silenced_

**Comment by juergba** [comment]
Which is the result when you use `--allow-uncaught` option?

**Comment by plroebuck** [comment]
Fail to understand why you continue to create new issues over the same problem though.
We went through all this in #3917.

**If you want it fixed, send a PR.**

**Comment by medikoo** [comment]
> We went through all this in #3917.

No, it's a different issue.

All things I report are actually issues I discover when working with quite extensive Mocha setup in real world project (currently it comes with four Mocha bug patches, so it behaves reasonably)

**Comment by plroebuck** [comment]
Seems like another aspect of same problem -- an uncaught error occurs in asynchronous code run from a synchronous Mocha test.

Notwithstanding whether Mocha is _lacking_ in this department, some chunk of the solution for _you_ would be to write your tests using Mocha's asynchronous API instead...

**Comment by medikoo** [comment]
> Which is the result when you use --allow-uncaught option?

In this case it ends with output as:

```bash
  test
    ✓ test1
    1) test2
```

Which indicates an error in `test2`, but provides no details.

And process exists with `0` success code.

So it's also an invalid outcome

**Comment by wnghdcjfe** [comment]
Can you give me a more detailed explanation? 
I tested
```js
describe('test', () => {
    it('test1', () => {
      setTimeout(() => {
        throw new Error('Uncaught');
      }, 3);
    });
    it('test2', function () {
        console.log(2)
      this.skip();
    });
    it('test3', function () {
        console.log(3)
      this.skip();
    });
    it('test4', function () {
        console.log(4)
      this.skip();
    });
  });
```
and result
```
 test
    ✓ test1
2
    - test2
3
    - test3
4
    - test4


  1 passing (7ms)
  3 pending

/Users/juhongchul/Desktop/dev/test/a.js:4
        throw new Error('Uncaught');
        ^

Error: Uncaught
    at Timeout.setTimeout [as _onTimeout] (/Users/juhongchul/Desktop/dev/test/a.js:4:15)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```
is very clear, 1 passing because move to event loop and other things pending
you think 2, 3, 4, and 1 failed?

**Comment by medikoo** [comment]
@wnghdcjfe run it few times, you'll see that in some cases test suite ends with success, not reporting the error.

It happens only when race condition (`throw new Error('Uncaught');` being caught between `this.skip()` and following `it` run) occurs.
 Also the more further tests going, the more likely issue is to occur, try e.g.:

```javascript

describe("test", () => {
    it("test1", () => {
        setTimeout(() => {
            throw new Error("Uncaught");
        }, 3);
    });
    it("test2", function() {
        this.skip();
    });
    it("test3", function() {
        this.skip();
    });
    it("test4", function() {
        this.skip();
    });
    it("test5", function() {
        this.skip();
    });
    it("test6", function() {
        this.skip();
    });
    it("test7", function() {
        this.skip();
    });
    it("test8", function() {
        this.skip();
    });
    it("test9", function() {
        this.skip();
    });
    it("test10", function() {
        this.skip();
    });
    it("test11", function() {
        this.skip();
    });
});

**Comment by wnghdcjfe** [comment]
I found it and i try to fix that


/Users/juhongchul/Desktop/dev/test.js:5
          throw new Error("Uncaught");
          ^

Error: Uncaught
    at Timeout.setTimeout [as _onTimeout] (/Users/juhongchul/Desktop/dev/test.js:5:17)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by wnghdcjfe** [comment]
I think you sould add done parameter like this
```js
const assert = require('assert'); 
describe("test", () => {
  it("test1", (done) => {
      setTimeout(() => {
          throw new Error("wow..");
          done();
      }, 3);
  });
  it("test2", function() {
      this.skip();
  });
  it("test3", function() {
      this.skip();
  });
  it("test4", function() {
      this.skip();
  });
  it("test5", function() {
      this.skip();
  });
  it("test6", function() {
      this.skip();
  });
  it("test7", function() {
      this.skip();
  });
  it("test8", function() {
      this.skip();
  });
  it("test9", function() {
      this.skip();
  });
  it("test10", function() {
      this.skip();
  });
  it("test11", function() {
      this.skip();
  });
});

```
 I added done and I tested and the result is.. 
exactly this

  0 passing (17ms)
  10 pending
  1 failing

  1) test
       test1:
     Uncaught Error: wow..
      at Timeout.setTimeout [as _onTimeout] (test.js:5:17)

the mocha said
ASYNCHRONOUS CODE
Testing asynchronous code with Mocha could not be simpler! Simply invoke the callback when your test is complete. By adding a callback (usually named done) to it(), Mocha will know that it should wait for this function to be called to complete the test. This callback accepts both an Error instance (or subclass thereof) or a falsy value; anything else will cause a failed test.

because setTImeout is a async

thank you your issue.
