### ISSUE TITLE
No test files found even though one specified with --file

### ISSUE THREAD

**Issue by gabegorelick** [mochajs/mocha#3941]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

If mocha doesn't find any test files, it returns a `No test files found` error. This appears to happen even if `--file` is specified.

### Steps to Reproduce

`mocha --file foo.js --exclude '**/*.js'`

Per the docs, "Files specified using --file are not affected" by `--exclude`, so this should work.

**Expected behavior:** `foo.js` is loaded

**Actual behavior:** `No test files found` error

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 6.1.4
- The output of `node --version`: v8.15.1
- Your operating system
  - name and version: macOS 
  - architecture (32 or 64-bit): 64bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh
- Your browser and version (if running browser tests): n/a
- Any third-party Mocha-related modules (and their versions): none
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): none

### Additional Information

Use case for this is to run only a given set of files and override any "default" files loaded via positional arguments. For example, `mocha --file test/foo.js --exclude '**/*.js' 'test/**/*.js'`
would only run `test/foo.js`.

**Comment by gabegorelick** [comment]
I think this is the source of the issue:
https://github.com/mochajs/mocha/blob/f3ed729b6908f3893e6f87722c6e996cca5f7733/lib/cli/run-helpers.js#L142-L168

Note how files from `--file` is only added after the error is thrown.

**Comment by outsideris** [comment]
I didn't understand the use case. Why should we load `--file` even if there are no target test files. `--file` is not for test files. It is for pre-loaded files before testing.

**Comment by outsideris** [comment]
The previous comment that I deleted is caused by my misunderstanding. Sorry.
