### ISSUE TITLE
regression bug: command line reporter-options parameter doesn't override mocha.opts

### ISSUE THREAD

**Issue by stalb** [mochajs/mocha#3951]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description
Mocha doesn't override `reporter-options` value defined in mocha.opts with the one defined on command line.

### Steps to Reproduce

1. Define a mocha.ops file with `reporter-options`:
```
--recursive
--reporter=xunit
--reporter-options output=./test-reports/junit.xml
```
2. Call mocha using a different value for `reporter-option`
```
node node_modules/mocha/bin/mocha --reporter-options output=./test-reports/unit.xml
```

3. Verify that mocha has created `./test-reports/junit.xml` and not  `./test-reports/unit.xml`

**Expected behavior:** [What you expect to happen]

Mocha should use the `reporter-options` specified on the command-line instead of the one defined in mocha.opts.

**Actual behavior:** [What actually happens]

Mocha use the `reporter-options` defined in mocha.opts instead of the one specified on the command-line.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

- *mocha*:  6.0.0-6.1.4  (works fine with version 5.2.0)  -- mocha is not installed globally
- *node*: 8.14.1 / 10.15.3 / 12.4.0
- Your operating system
  - name and version: windows 10 1903 / debian stretch 
  - architecture (32 or 64-bit): 64bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): PowerShell / bash

**Comment by juergba** [comment]
The reason could be: `reporter-options` is an array. So the values don't get overriden, but accumulated. I'm not sure though.
Could you check please, wether a string option like `reporter` gets overridden?

**Comment by stalb** [comment]
Yes, I've verified and  `reporter` is overridden.

If the values of `reporter-options` are accumulated and only the latest value survives, then the problem is perhaps just in which the order there are accumulated.

Also I can use `reporter-options` on the command line or in mocha.opts (and that's works in both), the problem is when `reporter-options` is defined in both.

**Comment by juergba** [comment]
Thank you for your help. It's a bug.
`reporter-options` is a special case of option, the solution will be to make the array unique (with the first value, not the last one) before converting to an object.

Anyway you should not use "mocha.opts", it's considered legacy. Better to use one of the configuration files. This bug will remain activ though.

**Comment by outsideris** [comment]
I believe it only a bug with `mocha.opts. but we already drop to support `mocha.opts `.
