### ISSUE TITLE
Mocha 4 security issue

### ISSUE THREAD

**Issue by octref** [mochajs/mocha#3958]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)

### Description

There's a security issue with `diff` 3.3.1 that Mocha 4 is using: https://github.com/microsoft/vscode-extension-vscode/network/alert/yarn.lock/diff/open

This affects `vscode` package which is depended by almost all VS Code extensions.

I suggest simply updating diff to 3.5.0 and make a release 4.1.1.

Do you still ship security fixes to 4.x? If so I can prepare a PR.
If not I'd likely have to fork, but I would avoid forking if possible. Thanks!

**Comment by juergba** [comment]
No, we don't maintain Mocha v4.x anymore, our actual version is v6.1.4.
There have been first discussions about defining a LTS strategy, but no practical steps so far.

**Comment by octref** [comment]
@juergba OK, thanks. Will either fork or upgrade major versions.

**Comment by mgenware** [comment]
This issue still exists on latest version, diff 3.5.0 is present in [package.json](https://github.com/mochajs/mocha/blob/master/package.json#L519)
