### ISSUE TITLE
Custom path of babel.config (for babel-register) ?

### ISSUE THREAD

**Issue by stevenvachon** [mochajs/mocha#3964]
```shell
mocha test.js --require=@babel/register
```

* `scripts/babel.config.js`
* `package.json`

How can I get this to work without adding a new file or moving my Babel config?

**Comment by craigtaub** [comment]
What version of mocha/babel etc?

How does your app point to that babel config? Does that work?

Any reason you did not want to place the config in root (or package.json), which i believe is the recommended approach?

**Comment by stevenvachon** [comment]
* @babel-core v7.5.0
* mocha v6.1.3

```json
"scripts": {
  "build": "babel lib/ --config-file=./scripts/babel.config.js --out-dir=lib-cjs/ --source-maps"
}
```

I prefer not to have too many files in the project root.

**Comment by craigtaub** [comment]
@stevenvachon you may need a new file to load babel and specify the config value, see below. AFAIK there is no way to pass a babel cli option from mocha cli directly. 

mocha config
```
require: 'scripts/register-babel.js'
```

scripts/register-babel.js
```
require("@babel/register")({
  configFile: "./scripts/babel.config.js",
});
```

Does that help?

**Comment by stevenvachon** [comment]
> Does that help?

Yup! Thanks!

I didn't use a mocha config file, though; instead opting for the `--require` CLI option.
