### ISSUE TITLE
variables in .env file are not loaded during test

### ISSUE THREAD

**Issue by aramadsanar** [mochajs/mocha#3969]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

I am currently building an integration test where the sensitive variables are placed in .env file in the root of the project directory. I had been following the solution in issue #2996, but it is still not reading variables in specified path of .env and instead declares the variables I need as undefined, which is really annoying

### Steps to Reproduce
This is the code to reproduce the issue
```
const chai = require("chai");
const request = require("superagent");

var should = require("chai").should();
var path = require("path");

//Specify where the .env is
var dotEnvPath = __dirname + "../../.env";

//This should load the .env
require("dotenv").config({ path: dotEnvPath });

var expect = chai.expect;
let server;

const {
  SOME_VAR
} = process.env;


describe("the test", () => {
  it("test 1", done => {
    //This should no be undefined
    console.log("hoho ", SOME_VAR);
    
    //auto fail
    expect(SOME_VAR).to.be.ok;
  });
});
```

**Expected behavior:** it should print "hoho" followed by whatever SOME_VAR contains and the test passes
**Actual behavior:** it prints "hoho undefined and test fails

**Reproduces how often:** all the time

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 6.2.0
- The output of `node --version`: v11.0.0
- Your operating system
  - name and version: Ubuntu 18.04
  - architecture (32 or 64-bit): 64-bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): bash

**Comment by juergba** [comment]
Try `const SOME_VAR = process.env;` instead. Without the brackets.
I don't think this is an issue of Mocha, possibly of `dontenv`.

**Comment by outsideris** [comment]
It is a path problem. you  should should `path.join` not `__dirname + "../../.env"` which is just string, not path.

```
var dotEnvPath = path.join(__dirname, '../', '../', '.env');
```
