### ISSUE TITLE
📝 Docs: Indicate that "exports" interface does not work in browsers

### ISSUE THREAD

**Issue by JKAnderson409** [mochajs/mocha#3974]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
I wasted a good deal of time trying to get the "exports" interface (which I think is perfect for organizing tests for a large OOP project) only to find that it just does not work in the browser. I can get my demo test to run on the command line (node) just fine but Firefox and Chromium ignore the exported test suite when the interface is set to "exports".

**Describe the solution you'd like**
The docs should indicate that this is the case in both the "Interfaces" and "Browser support" sections.

**Describe alternatives you've considered**
Of course it would be nice if it was fixed to work in the browser but I think that updating the docs is the best immediate fix.

**Additional context**
This was brought up quite a while ago (https://github.com/mochajs/mocha/issues/2198) with some manual solutions to get it working but it does not appear that the docs were updated to reflect the issue.

**Comment by craigtaub** [comment]
Makes sense. Thanks for raising.
