### ISSUE TITLE
Weird iteration of promises with native addon - Promise is resolved seconds later

### ISSUE THREAD

**Issue by JCMais** [mochajs/mocha#3976]
### Prerequisites
- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Hi, I am the author of the module `node-libcurl`, recently this issue was reported there: https://github.com/JCMais/node-libcurl/issues/177

Basically the promises takes a long time to resolve itself after resolve/reject was called.

### Steps to Reproduce

Run the following test case:
```
const { Curl } = require('node-libcurl')

const makeCall = () =>
  new Promise((resolve, reject) => {
    const curl = new Curl()

    curl.setOpt('URL', 'http://localhost:8080')
    curl.setOpt('CONNECTTIMEOUT', 1)
    curl.setOpt('TIMEOUT', 1)

    curl.on('error', () => {
      resolve()
    })

    curl.on('end', () => {
      resolve()
    })

    curl.perform()
  })

describe('Promisified curl call test', () => {
  it('should resolve', done => {
    makeCall()
      .then(() => {
        console.warn('TEST DONE')
        done()
      })
      .catch(() => {
        console.warn('TEST CATCHED ERROR')
        done()
      })
  })

  it('should resolve (async/await way)', async () => {
    await makeCall()
    console.warn('ASYNC/AWAIT DONE')
  })
})
```

It will fail with a timeout error, if the timeout is increased to `20s`, the tests will pass, but only after ~8s each.

If we add `setTimeout(() => {}, 0)` or `setImmediate(() => {})` right after the `resolve()` / `reject()` in the on end / on error callbacks, it works correctly taking just some milliseconds.

I've tried to debug it with some breakpoints but the only thing I could see was that the code was taking a really long time inside async hooks.

I've confirmed this is an issue with mocha by running the exact same test file with Jest, and also running the code directly, on both cases there was no slowdown.
### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
> `6.2.0`
- The output of `node --version`:
> `v12.1.0`
- Your operating system
  - name and version:
  > `Windows 10`
  - architecture (32 or 64-bit):
  > `64-bit`
- Your shell (e.g., bash, zsh, PowerShell, cmd):
> `bash (wsl)`

**Comment by juergba** [comment]
> Basically the promises takes a long time to resolve itself after resolve/reject was called.

I doubt above comment.
IMO it takes a long time until the `end`/ `error` cb's are executed and `resolve` is called.

I guess `curl.perform()` is emitting the `end`/ `error` events, the corresponding cb's are not executed synchronously, but added to a queue of the event loop. So no `resolve()` has been called yet.

At this point the situation is stuck, the `it()` function waits for the promise to be resolved, but the event loop does not proceed to the queue with the event cb's =>no `resolve()` is called.

I imagine Node will proceed after some timeout (8s?) and the event cb's are triggered.

**Comment by juergba** [comment]
What happens if you replace `curl.perform()` by `curl.emit('end')`?

**Comment by JCMais** [comment]
> What happens if you replace `curl.perform()` by `curl.emit('end')`?

Then it runs without delay

**Comment by JCMais** [comment]
@juergba looks like the issue can be reproduced without using mocha, so I don't know if this issue should still be kept open or not. Still weird that the sample code above runs correclty directly and with Jest. But I suppose this is probably because mocha maintains some timers internally that are making the issue on the addon appear.

Btw, do you have any idea on what might be causing this? (see latest comments on the issue I linked above)

**Comment by juergba** [comment]
IMO it's the timing between the emitting and listening of the event.
I don't know what `curl.perform()` exactly does. Why does the simple `curl.emit('end')` work, `curl.perform()` does not? How does latter fire the event, synchronously or using `nextTick()`, or `setImmediate()`?

There is more than one event-loop-queue involved
- a promise `then` job uses the microtask queue of V8
- nextTick uses the nextTick-queue of Node (and runs before microstask queue)
- setImmediate() runs after each event loop phase. Firing the event here could possibly block the resolving of `makeCall` promise.

You could experiment with [queueMicrotask](https://nodejs.org/dist/latest-v12.x/docs/api/globals.html#globals_queuemicrotask_callback) for listening and firing the event.


Yes, please close this issue as soon as you are sure.

**Comment by JCMais** [comment]
`curl.perform()` fires the libcurl request on the C++ side, this uses libuv to make it run async:

this `onEnd` callback here is emitted after the request finishes on the native side, and the `end` event is emitted inside of it: 
https://github.com/JCMais/node-libcurl/blob/4a1bde612318d3/lib/Curl.ts#L280-L318

I can see that the execution inside the native part runs fast, `end` is emitted normally, and there is only the slowdown after the resolve itself is called.
