### ISSUE TITLE
excluding the only first file in pattern

### ISSUE THREAD

**Issue by pustovitDmytro** [mochajs/mocha#3990]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

I have following test directory structure:

```
tests
├── api
│   ├── 1.js
│   ├── 2.js
│   └── 3.js
├── constants.js
├── env.js
├── external
│   ├── 1.js
│   ├── 2.js
│   └── 3.js
├── permissions
│   ├── 1.js
│   └── 2.js
├── validation
│   ├── 1.js
│   └── 2.js
├── unit
│   ├── 1.js
│   ├── 2.js
│   ├── 3.js
│   └── 4.js
└── utils.js
```

I want to execute all tests except ```external``` directory, with --exlude/--ignore options:

```
mocha --config .mocharc.json --ignore tests/external/*.js tests/**/*.js
```
but only file tests/external/1.js is ignored, tests/external/2.js and tests/external/3.js are still required by mocha.

### Steps to Reproduce

ignore all files in directory with exclude pattern

**Expected behavior:**  exclude all files, matching pattern

**Actual behavior:** exclude first file in directory

**Reproduces how often:** 100%

### Versions

mocha --version
6.2.0

node node_modules/.bin/mocha --version
6.2.0

node --version
v8.11.1

Ubuntu 16.04, zsh
### Additional Information
 my mocharc.json:
```
{
    "diff": true,
    "extension": ["js"],
    "reporter": "spec",
    "slow": 500,
    "timeout": 30000,
    "ui": "qunit",
    "exit": true,
    "color": true,
    "full-trace": true,
    "recursive": true,
    "require": ["./tests/env.js", "@babel/register"]
}
```

**Comment by juergba** [comment]
I can't reproduce this case on my Windows laptop.
Please try to quote your globs with double or single quotes.

**Comment by DrizzlingCattus** [comment]
See PR #3996 , this issue has been discussed! :)

**Comment by pustovitDmytro** [comment]
thanks, single quotes helped, also I've used the workaround glob 'tests/{,!(external)/**/}/*.js'
