### ISSUE TITLE
Passing argument to description

### ISSUE THREAD

**Issue by canmingir** [mochajs/mocha#3994]
I couldn't find an option that I needed to use command line argument as a part of description and eventually as a part of test like this:

```
describe("Application", function() {
  it("creates entity ${n} times", n, function() {
  ..
  });
  it("updates entity ${n} times", n, function() {
  ..
  });
});
```

**Comment by craigtaub** [comment]
@canmingir 

You can pass node env variables from CLI. i.e.
`> env TITLE="our title" mocha`

```
describe('Suite', () => {
  it(`test name ${process.env.TITLE}`, () => { // "test name our title"
    // ...
  });
});
```

Does that solve your problem?

**Comment by canmingir** [comment]
Great, I was also be able to use local variables
```
var n = argv.n ? argv.n : 2;
it(`creates entity ${n} times`, ..)
```
