### ISSUE TITLE
Calling shared tests does not honor before/after hooks

### ISSUE THREAD

**Issue by gwh-cpnet** [mochajs/mocha#3997]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Steps to Reproduce

```js
/* eslint-env mocha */
const assert = require('assert');

const genVar = () => new Promise((resolve) => {
  setTimeout(resolve(1), 500);
});

const sharedTest = (i) => {
  it('should be 1', () => {
    assert.equal(i, 1);
  });
};

describe('shared', () => {
  let i = 0;
  before(async () => {
    i = await genVar();
  });

  it('should be 1', () => {
    assert.equal(i, 1);
  });

  sharedTest(i);  // failed because i == 0

  after(() => {
    i = 2;
  });
});

```

**Expected behavior:** both tests passed

**Actual behavior:** [What actually happens]

sharedTest(i) would failed. 

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 6.2.0
- The output of `node --version`: v10.16.2
- Your operating system
  - name and version: manjaro
  - architecture (32 or 64-bit): 64
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh
- Your browser and version (if running browser tests):
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): 

### Additional Information

I was tring to implement some `Shared Behaviours` in https://github.com/mochajs/mocha/wiki/Shared-Behaviours to reuse some test cases. But I got some async call in my before hook, calling the shared test would not wait the promise in before hook to resolve. 

Wrapping `sharedTest(i);` in another `it` would cause other problems. 

If calling paramized test cases would always fail, how to do it correctly?

**Comment by gwh-cpnet** [comment]
the problem about wrapping the shared tests is demonstrated as code below

```js
/* eslint-env mocha */
const assert = require('assert');

const delay = (t) => new Promise((resolve) => setTimeout(resolve, t));

const genVar = async () => {
  await delay(500);
  return Promise.resolve({ a: 0 });
};

const sharedTest = (d) => describe('shared test', () => {
  it('should equal to the val set in before hook', async () => {
    assert.deepEqual(d, { a: 0 });
  });
});

describe.only('shared', () => {
  let d = null;
  before(async () => {
    d = await genVar();
  });

  it('embeded test', () => {
    assert.deepEqual(d, { a: 0 });
  });

  it('wrapped with it', () => { // failed because d == { a: 1 }
    sharedTest(d);
  });

  sharedTest(d); // failed because d is null

  after(() => {
    d.a = 1;
    console.log('in after');
  });
});
```

**Comment by DrizzlingCattus** [comment]
@gwh-cpnet 

I'm not reading all, but I have a certain idea, so I answered.

First, you can use shared test with context 'this' using js dynamic binding, check this ref (https://github.com/mochajs/mocha/wiki/Shared-Behaviours).

Second, you use arrow function and this is a problem when using 'this', check this ref (https://mochajs.org/#arrow-functions)

I hope this answer helps you!

**Comment by juergba** [comment]
I have no experience with shared behaviors. I just made some short testing and it seems to work so far.

```js
const assert = require('assert');

const genVar = () => new Promise((resolve) => {
  setTimeout(resolve, 500, 1);
});

const sharedTest = () => {
  it('should be 2', () => {    
    assert.equal(i, 2);
    i++;
  });
};

let i = 0;

describe('shared', () => {
  before(async () => {
    console.log('before plain');
    i = await genVar();
  });

  it('should be 1', () => {
    assert.equal(i, 1);
    i++;
  });

  sharedTest(genVar);

  it('should be 3', () => {
    assert.equal(i, 3);
    i++;
  });

  after(() => {
    console.log('after');
    assert.equal(i, 4);
  });
});
```

**Comment by gwh-cpnet** [comment]
@juergba Thanks for your response, I think our difference is whether i is global. 

this test would pass:
```js
const assert = require('assert');

const genVar = () => new Promise((resolve) => {
  setTimeout(resolve, 500, 1);
});

let i = 0;

const sharedTest = () => {
  it('should be 2', () => {
    assert.equal(i, 2);
  });
};

describe('shared', () => {
  before(async () => {
    console.log('before plain');
    i = await genVar();
  });

  it('should be 1', () => {
    assert.equal(i, 1);
    i += 1;
  });

  sharedTest();

  it('should be 2', () => {
    assert.equal(i, 2);
    i += 1;
  });

  after(() => {
    i += 1;
    console.log('after');
    assert.equal(i, 4);
  });
});
```

but this one would fail as I open the issue:
```js
/* eslint-env mocha */
/* eslint-disable no-console */
const assert = require('assert');

const genVar = () => new Promise((resolve) => {
  setTimeout(resolve, 500, 1);
});

const sharedTest = (i) => {
  it('should be 2', () => {
    assert.equal(i, 2);
  });
};

describe('shared', () => {
  let i = 0;

  before(async () => {
    console.log('before plain');
    i = await genVar();
  });

  it('should be 1', () => {
    assert.equal(i, 1);
    i += 1;
  });

  sharedTest(i);

  it('should be 2', () => {
    assert.equal(i, 2);
    i += 1;
  });

  after(() => {
    i += 1;
    console.log('after');
    assert.equal(i, 4);
  });
});
```

The problem is that if `i` is passed to shartedTest as a argument, it would ignore the hook. 
But in the typical use case for `shared` test, it always written in another source file, where it got no defination of the global `i`.

**Comment by gwh-cpnet** [comment]
@DrizzlingCattus Thanks for your comment. The `this` context matters. So I have to write the tests in this way:

```js
/* eslint-env mocha */
/* eslint-disable no-console */
const assert = require('assert');

const genVar = () => new Promise((resolve) => {
  setTimeout(resolve, 500, 1);
});

const sharedTest = function () {
  it('should be 2', function () {
    assert.equal(this.i, 2);
  });
};

describe.only('shared4', () => {
  before(function (done) {
    console.log('before plain');
    genVar().then((i) => {
      this.i = i;
      done();
    });
  });

  it('should be 1', function () {
    assert.equal(this.i, 1);
    this.i += 1;
  });

  sharedTest();

  it('should be 2', function () {
    assert.equal(this.i, 2);
    this.i += 1;
  });

  after(function () {
    this.i += 1;
    console.log('after');
    assert.equal(this.i, 4);
  });
});
```

Instead of passing test target as an argument to shared test, we should use `this`. Well, it works. But the code just looks from the es5 dynasty.

**Comment by aguegu** [comment]
Ok, with a better understanding about the `this` context, a better-looking code looks like this: 

```js
/* eslint-disable no-console */
const assert = require('assert');

const genVar = () => new Promise((resolve) => {
  setTimeout(resolve, 500, 1);
});

const sharedTest = (v) => {
  it(`should be ${v}`, function () {
    assert.equal(this.i, v);
  });
};

describe.only('shared4', () => {
  before(async function () {
    console.log('before plain');
    this.i = await genVar();
  });

  it('should be 1', function () {
    assert.equal(this.i, 1);
    this.i += 1;
  });

  sharedTest(2);

  it('should be 2', function () {
    assert.equal(this.i, 2);
    this.i += 1;
  });

  sharedTest(3);

  after(function () {
    this.i += 1;
    console.log('after');
    assert.equal(this.i, 4);
  });
});
```

**Comment by gwh-cpnet** [comment]
Ok, with a better understanding about the `this` context among tests, a better-looking code looks like this: 

```js
/* eslint-disable no-console */
const assert = require('assert');

const genVar = () => new Promise((resolve) => {
  setTimeout(resolve, 500, 1);
});

const sharedTest = (v) => {
  it(`should be ${v}`, function () {
    assert.equal(this.i, v);
  });
};

describe('shared', () => {
  before(async function () {
    console.log('before plain');
    this.i = await genVar();
  });

  it('should be 1', function () {
    assert.equal(this.i, 1);
    this.i += 1;
  });

  sharedTest(2);

  it('should be 2', function () {
    assert.equal(this.i, 2);
    this.i += 1;
  });

  sharedTest(3);

  after(function () {
    this.i += 1;
    console.log('after');
    assert.equal(this.i, 4);
  });
});
```

So I would not mark it as a bug, thanks all.

**Comment by gwh-cpnet** [comment]
```js
/* eslint-disable no-console */
const assert = require('assert');

const init = () => new Promise((resolve) => {
  setTimeout(resolve, 500, { k: 1 });
});

const sharedTest = (x, v) => {
  it(`x.k should be ${v}`, function () {
    console.log(this.x);
    assert.equal(x.k, v); // always failed
  });

  it(`this.x.k should be ${v}`, function () {
    assert.equal(this.x.k, v);
  });
};

describe.only('shared4', () => {
  let x = { k: 0 };
  before(async function () {
    console.log('before plain');
    this.x = await init();
    x = await init();
  });

  it('should be 1', function () {
    assert.equal(x.k, 1);
    assert.equal(this.x.k, 1);
    x.k += 1;
    this.x.k += 1;
  });

  sharedTest(x, 2);

  it('should be 2', function () {
    assert.equal(x.k, 2);
    assert.equal(this.x.k, 2);
    x.k += 1;
    this.x.k += 1;
  });

  sharedTest(x, 3);

  after(function () {
    console.log('after');
    x.k += 1;
    this.x.k += 1;
    assert.equal(x.k, 4);
    assert.equal(this.x.k, 4);
  });
});
```
here is a test case for passing arguments to shared tests. `this.x` works as expected. But the `local x` works `interesting`.
