### ISSUE TITLE
Could mocha support 10000 test steps or more?

### ISSUE THREAD

**Issue by zhuguocheng29** [mochajs/mocha#3998]
Now I have a case that has 10000 steps such as srcoll left or scroll right step, I use mocha however it meet OOM problem even if I set  --max-old-space-size=4096. Therefore, my question is that could mocha support 10000 test steps or more?
my code such as
```
describe('', function(){
    for(let count = 0; count< 10000; count++) {
        it('scroll left', ...)
        it('scroll right', ...)
    }
})
```

**Comment by DrizzlingCattus** [comment]
I don't know inside of your test 'it('scroll left', ...)', so simply implement like this.


```javascript
const assert = require('assert');

const LOOP_MAX = 10000;
describe('retry is working?', function() {
    for (let i = 0; i < LOOP_MAX; i++) {
        it('loop test one', function() {
            assert(1 === 1);
        });

        it('loop test two', function() {
            assert(2 === 2);
        });
    }
});
```

and it works, but above code create 20000 test like this.

![test-count](https://user-images.githubusercontent.com/4661295/63633894-79a2a700-c68a-11e9-8069-57ad8fadafd7.png)


From this, i think the problem you met is too many testcase (result of out of memory).

So, i use mocha retry feature for reduce testcase like below.
(mocha retry : https://mochajs.org/#retry-tests)

![test2-retry](https://user-images.githubusercontent.com/4661295/63634111-e7e86900-c68c-11e9-82b0-70a09525913c.png)

```javascript
const assert = require('assert');

const LOOP_MAX = 10000;
describe('retry2 is working?', function() {
    this.retries(LOOP_MAX);

    it('loop test one', function() {
        // some expect for this test...
        assert(1 === 1);
        // check current retry count and if not MAX, then do fail for retry

        if (this.test.currentRetry() < LOOP_MAX) {
            console.log('hello one');
            assert.fail();
        }
    });

    it('loop test two', function() {
        assert(2 === 2);
        if (this.test.currentRetry() < LOOP_MAX) {
            console.log('hello two');
            assert.fail();
        }
    });
});
```

I hope this is helpful.

**Comment by zhuguocheng29** [comment]
@DrizzlingCattus  
Thanks for your reply. But I think retries feature doesn't fit my case. Actually, I want to scroll left firstly then scroll right secondly and loop these two steps 10000 times. In your recommendation, I will scoll left 10000 times first and then scoll right 10000 times scondly. This is not what I want. 
Is there any other good way to achieve this case?

**Comment by zhuguocheng29** [comment]
@DrizzlingCattus 
I have another question that how many testcases mocha can support now. My tests are basically more than 20000 testcases which don't use retry feature now .

**Comment by DrizzlingCattus** [comment]
@zhuguocheng29 
I looked at the mocha code, but I didn't find where set limit of testcase.

```javascript
/**
 * Add a `test` to this suite.
 *
 * @private
 * @param {Test} test
 * @return {Suite} for chaining
 */
Suite.prototype.addTest = function(test) {
  test.parent = this;
  test.timeout(this.timeout());
  test.retries(this.retries());
  test.enableTimeouts(this.enableTimeouts());
  test.slow(this.slow());
  test.ctx = this.ctx;
  this.tests.push(test);
  this.emit(constants.EVENT_SUITE_ADD_TEST, test);
  return this;
};
```

**Comment by DrizzlingCattus** [comment]
@zhuguocheng29 

If you want to test left scroll and right scroll sequentially, then i think it is more suitable to combine them into one.

```
const assert = require('assert');

const LOOP_MAX = 10000;

const leftScrollTest = function(n) {
    assert(1 === 1, `left scroll ${n}-th is not working properly`);
};

const rightScrollTest = function(n) {
    assert(2 === 2, `right scroll ${n}-th is not working properly`);
};

describe('retry is working?', function() {

    it('scroll left and right', function() {
        for (let i = 0; i < LOOP_MAX; i++) {
            leftScrollTest(i);
            rightScrollTest(i);
        }
    });

});
```

The code above does not generate a test when it runs, like below.

![properly-working-3](https://user-images.githubusercontent.com/4661295/63654478-9a1b5000-c7b5-11e9-8a6c-bf48718d0681.png)

Plus, you can save memory and can figure out where something went wrong with Error message.

![3-fail-message](https://user-images.githubusercontent.com/4661295/63654479-9d164080-c7b5-11e9-89dd-fad343cb729a.png)

**Comment by zhuguocheng29** [comment]
@DrizzlingCattus
I have set --max-old-space-size = 4096, but it still has OOM problem

**Comment by zhuguocheng29** [comment]
@DrizzlingCattus 
It still has a problem if I combine these two steps into one. These two steps may cost 10 hours, However in describe block I set `this.timeout(10 * 60 * 1000)`

**Comment by DrizzlingCattus** [comment]
@zhuguocheng29 

10 hours? that's too big... maybe i think that is a reason of memory problem.. and i'm not sure how to solve it.

**Comment by zhuguocheng29** [comment]
@DrizzlingCattus
Thank you for your reply.
