### ISSUE TITLE
Overwriting CLI options when passed multiple times

### ISSUE THREAD

**Issue by larsgw** [mochajs/mocha#4001]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
Nice-to-have: I'm getting the following error for CLI options that should only be included once.

> ✖ ERROR: "--reporter <reporter>" can only be specified once

**Describe the solution you'd like**
Is it possible to use the last value passed (with or without a warning saying the user passed multiple values) instead of exiting with the error?

**Describe alternatives you've considered**

  - accept the change and change my workflow (see below): possible, but it would be inconsistent
  - downgrade mocha: let's not do that

**Additional context**
I have a `npm test` script like

    mocha --reporter dot test/*.spec.js

Sometimes I run it like `npm test -- --grep "something"` for specific test cases. Every now and then, I also ran `npm test -- --reporter spec` to make sure all test cases are run, etc. However, this is not possible anymore since https://github.com/mochajs/mocha/commit/b5c0fb0a26ee9f8fd574e78732a2cf715d7ab6ca (`v6.0.0-0`). [Obligatory xkcd](https://xkcd.com/1172/).

**Comment by juergba** [comment]
This issue was fixed in v6.2.0.

**Comment by larsgw** [comment]
Sorry, hadn't seen that yet.
