### ISSUE TITLE
Documentation should give an example of using `mocha` property in `package.json`

### ISSUE THREAD

**Issue by thw0rted** [mochajs/mocha#4005]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
The documentation mentions the ability to use a property in `package.json` instead of a separate `mocha.opts` file.

**Describe the solution you'd like**
I can't find an example of actually *doing* this anywhere.

**Describe alternatives you've considered**
It's pretty hard to search online for people talking about "the `mocha` property in `package.json`", since "package.json" is probably the single most common string in any page about Node tooling.

**Additional context**
I'm specifically interested in how to specify flags that can be repeated, e.g. `--file`.

**Comment by juergba** [comment]
You find information about configuration format [here](https://mochajs.org/#configuration-format).
Follow the link [example/config](https://github.com/mochajs/mocha/tree/master/example/config) and have a look at the `.mocharc.json` file. This same configuration could be provided in the `mocha` property of your project's `package.json`.

The `--file` option is an `array`.

**Comment by thw0rted** [comment]
Ah, that makes sense.  I was also apparently looking for `spec` and the note about passing node options, since I needed `require: ts-node/register` to run Typescript directly.  I'll go ahead and close the ticket; worst case somebody who has trouble with the property-based version will find this ticket and be enlightened 👍

**Comment by postspectacular** [comment]
It would be great to extend these example configs and show how this setup can be used to specify additional options for Node itself. I've been trying to enable the "--experimental-wasm-simd" option for via any of the described config methods, but with no avail. How can this be done?

**Comment by akopchinskiy** [comment]
Mocha's documentation about configs really sucks

**Comment by SergiuToporjinschi** [comment]
yes it sucks

**Comment by SergiuToporjinschi** [comment]
here is a bit of explanation https://mochajs.org/#configuration-format

**Comment by HartS** [comment]
Would be nice to include a package.json example in https://github.com/mochajs/mocha/tree/master/example/config (linked from the configuration doc you shared @SergiuToporjinschi )
