### ISSUE TITLE
Retries and before each not working

### ISSUE THREAD

**Issue by furstenheim** [mochajs/mocha#4006]
When having an integration/e2e test it might happen that beforeEach could fail.
In the example from the documentation: https://mochajs.org/#retry-tests

```
describe('retries', function() {
  // Retry all tests in this suite up to 4 times
  this.retries(4);

  beforeEach(function() {
    browser.get('http://www.yahoo.com');
  });

  it('should succeed on the 3rd try', function() {
    // Specify this test to only retry up to 2 times
    this.retries(2);
    expect($('.foo').isDisplayed()).to.eventually.be.true;
  });
});
```
It could happen that browser.get fails and we need a retry.
Currently, one could have "browser.get" inside the it, but that does not allow to reuse code across tests.

I'd be interested in doing:

```
beforeEach(function() {
    this.retries(2)
    browser.get('http://www.yahoo.com');
  });

```
 Not sure that it makes 100% sense. If it does not make sense, maybe it would be possible to change the documentation, since it can be slightly misleading:

> This feature does re-run beforeEach/afterEach hooks but not before/after hooks.

It could either mean that retries affect beforeEach, or what it actually means, that if the test fails then beforeEach will be executed again.

**Comment by wnghdcjfe** [comment]
I think if there is existed test A, B, C
retires not as A, B, C, A, B, C ... actually AA, BB, CC
am I right? and Are you saying that because you're confused, you want me to change it more clearly?

**Comment by furstenheim** [comment]
Hi @wnghdcjfe sorry that I didn't explain myself properly.
I was working in a context very similar to the example displayed, expecting it to retry on the beforeEach.
What I mean is that it would be nice to retry tests even if they fail in the beforeEach. I can understand that this can be problematic. In the particular example of the documentation it would make perfect sense, for example if the website timeouts the first time to retry.

What I'd like is either a way to use retries in the beforeEach, and if not possible, change the documentation to avoid confusion in the case someone is checking if beforeEach implement retries.

As I mentioned before:
> This feature does re-run beforeEach/afterEach hooks but not before/after hooks.

Could mean that when a test is retried,  then the beforeEach will be executed again (this is what it means), or that this.retries affects beforeEach in case beforeEach fails

**Comment by Nizarius** [comment]
If this feature is not yet implemented why documentation says about that:
https://mochajs.org/#retry-tests:
```This feature does re-run beforeEach/afterEach hooks but not before/after hooks.```

**Comment by frixatrix** [comment]
Can confirm the issue exists.

Mines _beforeEach_ I do cookie cleanup  and when test failed and retry starts - can see old cookies there.

**Comment by juergba** [comment]
`this.retries()` has no effect on failing hooks. No hooks or tests will be re-run.

`this.retries()` does re-run a failing test `it()`
- incl. its corresponding `beforeEach` and `afterEach` hooks
- excl.  `before` and `after` hooks

**Comment by juergba** [comment]
We updated our docs accordingly, thank you.
