### ISSUE TITLE
Multiple iteration of IT block to perform data creation 

### ISSUE THREAD

**Issue by dixitgargi** [mochajs/mocha#4007]
Hello Guys, 

There is one implementation which I need to do on my current mocha framework but I am stuck.

Agenda:
Create multiple data present in excel and iterate functional flow IT block till the data is present in the excel.

below code statement is global declaration of an array

`var exceldata = [];`

below code signifies reading excel file

```
workbook.xlsx.readFile("TestData.xlsx").then(function () {

    var sheet = workbook.getWorksheet("ecuFamily");
    var row, column;
    for (row = 2; row <= sheet.rowCount; row++) {
        for (column = 1; column <= sheet.columnCount; column++) {
                exceldata.push(sheet.getCell(row, column).toString().trim());  
        }
    }
    /**
     * Iterate the imported data stored in Array
     */
    //console.log(exceldata.length);
    for (var i = 0; i <= exceldata.length; i++) {
        console.log("Index is : " + i + " Value is :" + exceldata[i] + "type of"+ typeof exceldata[i]);
    };
});
```

Now i have to perform one functional flow for each and every data present in excel corresponding to column values

I was thinking to create a run time map and then iterate that map for particular It block.

But that sounds difficult to me. could you please guide me to achieve this.

**Comment by juergba** [comment]
I haven't really understood your "agenda".
You could try to create your data in an async `before` hook and then create your tests dynamically as shown [here](https://mochajs.org/#dynamically-generating-tests).

**Comment by dixitgargi** [comment]
Thanks juergba for responding. so The link which you have mentioned  has one data set of key value pair.  which exactly I want to create but I want to generate that data set dynamically as per the values present in excel

**Comment by juergba** [comment]
@dixitgargi please note, this is an Mocha issue tracker, not a help forum.

Creating a dataset is a pure javascript task and has nothing to do with Mocha. As mentioned above use a `before` hook (sync or async, depending on your javascript implementation) and then create your tests dynamically.

Take step by step, create your tests with hardcoded datas first, then add your real dynamic dataset.
