### ISSUE TITLE
How to access to the reports that Mocha run in the Terminal?

### ISSUE THREAD

**Issue by JavierPons** [mochajs/mocha#4010]
I have been diving into info and not find any answer. I don´t want to resign to that it is not possible.

`const mocha = new Mocha({
            reporter: "json"
          });
          const pathFile = `./test/${title}`;

          mocha.addFile(pathFile);

          const runner = mocha.run(failures => {
            console.log(failures);
            if (failures) console.log(true);
          });
console.log(runner);`

After run Mocha display the results on the Terminal. When It fail, the report is a bit different as if not, as natural. 
How I can access and manipulate as I want the data that is displayed in the Terminal? Interested specially to access into ReferenceError and the json report data. 

When I console log runner it gives me different info that it is displayed on the Terminal. So I can´t access to the data that is displayed to the Terminal.

`---
Runner {
  _globals: [
    'global',         'clearInterval',
    'clearTimeout',   'setInterval',
    'setTimeout',     'queueMicrotask',
    'clearImmediate', 'setImmediate',
    'before',         'after',
    'beforeEach',     'afterEach',
    'run',            'context',
    'describe',       'xcontext',
    'xdescribe',      'specify',
    'it',             'xspecify',
    'xit',            'STLLoader',
    'json',           'XMLHttpRequest',
    'Date',           'errno'
  ],
  _abort: false,
  _delay: undefined,
  suite: Suite {
    title: '',
    ctx: Context {},
    suites: [ [Suite] ],
    tests: [],
    pending: false,
    _beforeEach: [],
    _beforeAll: [],
    _afterEach: [],
    _afterAll: [],
    root: true,
    _timeout: 2000,
    _enableTimeouts: true,
    _slow: 75,
    _bail: undefined,
    _retries: -1,
    _onlyTests: [],
    _onlySuites: [],
    delayed: false,
    _events: [Object: null prototype] {
      newListener: [Function],
      'pre-require': [Array]
    },
    _eventsCount: 2
  },
  started: true,
  total: 1,
  failures: 0,
  _events: [Object: null prototype] {
    'test end': [ [Function], [Function], [Function] ],
    'hook end': [Function],
    suite: [Function],
    pass: [ [Function], [Function], [Function] ],
    fail: [ [Function], [Function], [Function], [Function] ],
    pending: [ [Function], [Function] ],
    end: [ [Function], [Function], [Function] ],
    'suite end': [Function]
  },
  _eventsCount: 8,
  _defaultGrep: /.*/,
  _grep: /.*/,
  _invert: undefined,
  stats: {
    suites: 0,
    tests: 0,
    passes: 0,
    pending: 0,
    failures: 0,
    start: 2019-09-06T08:29:27.520Z
  },
  ignoreLeaks: true,
  fullStackTrace: undefined,
  asyncOnly: undefined,
  allowUncaught: undefined,
  forbidOnly: undefined,
  forbidPending: undefined,
  nextSuite: [Function: next]
}
-----`

**Comment by Munter** [comment]
If you want access to the output of the reporter, pipe that output into a file or process that handles an input stream.

If none of the reporters do what you need and you can't post-process their output, write your own reporter to generate the output you need

**Comment by JavierPons** [comment]
I created my own reporter. But fails because it cant find the file-reporter I created.  So If my code is 
` const mocha = new Mocha({
            reporter: `./Reporter.js`
          });
          const pathFile = `./test/${title}`;

          mocha.addFile(pathFile);

          const runner = mocha.run(failures => {
            console.log(failures);
            process.exitCode = failures ? 1 : 0;
            if (failures) console.log(true);
          });`
reporter only allow  for exam. json or line.   How I can give the option/way to find my-reporter file?
