### ISSUE TITLE
fix: color output in Solarized theme is the same as background

### ISSUE THREAD

**Issue by nicholaschiang** [mochajs/mocha#4012]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Steps to Reproduce

1) Install [Solarized](https://ethanschoonover.com/solarized/) or just set your terminal colors 8 and 0 to be the same (with the Ubuntu 18.04.2 LTS default terminal emulator go to `Edit >> Preferences >> Profiles >> Color` and click on the palette colors to modify them).
2) Run `mocha` on any local terminal-outputted tests. You should see that you can't read the test descriptions for those that succeed.

**Expected behavior:** All output is legible against the background (i.e. outputs to a color other than the terminal palette color 8 (which in [Solarized](https://ethanschoonover.com/solarized/), is the same as the background color)).

**Actual behavior:** Log messages for the success of a test output in terminal palette color 8 which is the same color as the background, making the text illegible.

**Reproduces how often:** Every time that I run `mocha` with [Solarized](https://ethanschoonover.com/solarized/) as my terminal theme.

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 6.2.0
- The output of `node --version`: v10.8.0
- Your operating system
  - name and version: Ubuntu 18.04.2
  - architecture (32 or 64-bit): 64-bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): bash
- Your browser and version (if running browser tests):
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):

**Comment by juergba** [comment]
I don't see any reason why we should adapt our colors to Solarized. Just change the color settings in Solarized or use a different color scheme.
As a second option you could create your own Mocha reporter.
