### ISSUE TITLE
`--require esm` works as command-line arg, but not in `mocha.opts`

### ISSUE THREAD

**Issue by alexbepple** [mochajs/mocha#4015]
I believe this is a regression in Mocha 6 from Mocha 5. At least, I have not found any doc describing the change in behavior.

Here is a minimal repo demonstrating the difference in behavior.
https://github.com/alexbepple/possible-mocha-bug-with-require

I believe this to be a bug.

**Comment by juergba** [comment]
@alexbepple thank you for this issue. Yes, it's a bug, see #3975.
We have already fixed it in current master, but it's not published, yet.

BTW we recommend not to use `mocha.opts` any longer and to switch to our configuration files. `mocha.opts` is going to be deprecated in the next major release.
