### ISSUE TITLE
Where do I find all options for config file?

### ISSUE THREAD

**Issue by tar-aldev** [mochajs/mocha#4018]
I see that I can use config file for mocha, However I can't find what options I can put in this file.
Is there a list of options? Because it is mentioned everywhere that config file can be used, but a very little explanation is given.

**Comment by juergba** [comment]
See our documentation or use the option `-h` for an option list.
We also have examples of configuration files in our github repo.

Please note this is an issue tracker and not a help forum. See also [gitter](https://gitter.im/mochajs/mocha).
