### ISSUE TITLE
Can't  find the scss module

### ISSUE THREAD

**Issue by SummerXIAhaha** [mochajs/mocha#4023]
when I run test, the mistake will happen.
neoas is our Component gallery，the function.scss is existed，and run dev, run build is successed.
please tell me how to fix it, thank you.

WEBPACK  Failed to compile with 1 error(s)

Error in ./node_modules/neoas/src/components/label/label.vue?vue&type=style&index=0&lang=scss&  Module build failed (from ./node_modules/sass-loader/lib/loader.js):  Can't find stylesheet to import.
    ╷  1 │ @import '../function.scss';    │         ^^^^^^^^^^^^^^^^^^

**Comment by outsideris** [comment]
It doesn't seem that mocha's problem. Please provide more details.
