### ISSUE TITLE
JSON Stream documentation

### ISSUE THREAD

**Issue by Lindsay-Needs-Sleep** [mochajs/mocha#4027]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

While working on pull request #4026 I noticed that the [JSON Stream documentation](https://mochajs.org/#json-stream) hints that you should use 
`"JSON stream"` 
as the name for the JSON Stream reporter.

But, browser mocha will only accept 
`"json-stream"` 
or 
`"JSONStream"`.  
See [lib/reporters/index.js:19](https://github.com/mochajs/mocha/blob/master/lib/reporters/index.js#L19)

Is this a typo in the documentation, or is this an inconsistency between browser mocha and node mocha?  (eg. node mocha actually accepts "JSON stream"?)

### Steps to Reproduce

**Expected behavior:** documentation reflects usage correctly

**Actual behavior:** documentation indicates incorrect name for browser mocha (node mocha as well?)

**Comment by outsideris** [comment]
You are right. It is typo.
mocha only accept `json-stream` or `JSONStream`.

**Comment by juergba** [comment]
fixed by #4127
