### ISSUE TITLE
File path from Mocha options file is different from the command line

### ISSUE THREAD

**Issue by shridharkalagi** [mochajs/mocha#4028]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

I'm using Mocha in Monorepo with multiple packages. `--file` argument that I pass to load the file while startup is behaving differently when I pass it from command line than passing from the mocha.opts file

### Steps to Reproduce

**Expected behavior:** value for the `--file` argument should remain same from CLI and mocha.opts file

**Actual behavior:** Its not working with same value for `--file` argument

**Reproduces how often:** Always
### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 6.2.0
- The output of `node --version`: 12+
- Your operating system
  - name and version: Mac Mojave
  - architecture (32 or 64-bit):
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh
- Your browser and version (if running browser tests):
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): Babel - 7.6.2

**Comment by craigtaub** [comment]
Hi apologies it has taken a while to respond to this. Is this still an issue?
There is a specific order of priority when it comes to loading options via different methods, see https://mochajs.org/#merging.

**Comment by juergba** [comment]
`mocha.opts` has been deprected/removed.
Closing.
