### ISSUE TITLE
 it's necessary code for Mocha?

### ISSUE THREAD

**Issue by wnghdcjfe** [mochajs/mocha#4031]
I think I found the old code while analyzing it. It's probably been under 2.x, but I'm still wondering if it's necessary for Mocha, so I'm leaving a message.

## runnable.js 385
```js
  function callFn(fn) { 
    var result = fn.call(ctx); 
    //my custom log
    console.log("ret : ", result)
    if (result && typeof result.then === 'function') {
      self.resetTimeout();
      result.then(
        function() { 
          done(); 
          // Return null so libraries like bluebird do not warn about
          // subsequently constructed Promises.
          return null;
        },
        function(reason) {
          done(reason || new Error('Promise rejected with no or falsy reason'));
        }
      );
    }
```

that.. "Return null so libraries like bluebird do not warn about"

I think this has something to do with bluebirds, so I did a bluebird example, and that part of it is undefined. So I wonder if it's necessary. Is this not necessary? Or I'd appreciate it if you let me know if you've handled any other exceptions.

## test code
```js
const Promise = require('bluebird') 
const {expect} = require('chai') 
describe('BlueBird AsyncTest', function() { 
    it('should be resolved value : 10', function() {
        Promise.resolve(10).then(a =>{
            expect(a).to.equal(10) 
        }) 
    }); 
});
```

## result
```

  BlueBird AsyncTest
ret :  undefined
    ✓ should be resolved value : 10
  1 passing (9ms)
```

**Comment by juergba** [comment]
@wnghdcjfe 
I don't know wether this line of code is needed or not, it certainly does no harm.
IMO this single line is not worth taking any risk by removing it.
So I'm closing ths PR, sorry.
