### ISSUE TITLE
Root-level before() and after() hooks not running on each suite

### ISSUE THREAD

**Issue by dmchurch** [mochajs/mocha#4039]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

The [run cycle overview](https://mochajs.org/#run-cycle-overview) in the documentation states that root-level `before()`/`after()` hooks should run before and after every test suite, just like the `beforeEach()`/`afterEach()` hooks run before and after every test. However, only the `beforeEach()` and `afterEach()` hooks actually work as described; there is no way to register hooks to be run before and after every test suite.

### Steps to Reproduce

```javascript
// test.js
const assert = require('assert');
const runs = [];
before(function() {
  runs.push('root');
})

describe("Suite 1", function() {
  before(function() {
    runs.push('suite1');
  });
  it("root has run once", function() {
    assert.deepStrictEqual(runs, ['root','suite1']);
  });
  it("root has still run once", function() {
    assert.deepStrictEqual(runs, ['root','suite1']);
  });
});

describe("suite 2", function() {
  before(function() {
    runs.push('suite2');
  });
  it("root has run twice", function() {
    assert.deepStrictEqual(runs, ['root','suite1','root','suite2']);
    assert.equal(runs[0],2);
  });
});
```

**Expected behavior:** `mocha test.js` passes

**Actual behavior:**

```
  Suite 1
    ✓ root has run once
    ✓ root has still run once

  suite 2
    1) root has run twice


  2 passing (7ms)
  1 failing

  1) suite 2
       root has run twice:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

  [
    'root',
    'suite1',
-   'root',
    'suite2'
  ]
      + expected - actual

       [
         "root"
         "suite1"
      +  "root"
         "suite2"
       ]
      
      at Context.<anonymous> (test.js:24:12)
      at processImmediate (internal/timers.js:439:21)
```

**Reproduces how often:** Always

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 6.2.1
- The output of `node --version`: v12.10.0
- Your operating system
  - name and version: MacOS 10.14.6
  - architecture (32 or 64-bit): 64-bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): bash
- Your browser and version (if running browser tests): N/A
- Any third-party Mocha-related modules (and their versions): N/A
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): N/A

**Comment by juergba** [comment]
The root-level `before/after` hooks run just once for the root suite which is created by Mocha, not the user. Suites can be nested, so your suites are inside of Mocha's root suite, and you can put more of your sub-suites inside of your first level suite.

> there is no way to register hooks to be run before and after every test suite.

Use nested suites.

**Comment by dmchurch** [comment]
> The root-level `before/after` hooks run just once for the root suite which is created by Mocha, not the user. Suites can be nested, so your suites are inside of Mocha's root suite, and you can put more of your sub-suites inside of your first level suite.

I'm aware of what it's doing, I've seen the code. However, the docs pretty clearly state that root-level hooks - which it describes as hooks set "outside all `describe()` blocks" - happen per suite. Either the code is wrong or the docs are.

> > there is no way to register hooks to be run before and after every test suite.
> 
> Use nested suites.

Doesn't work if you want it to work on _every_ test suite across multiple files (using the `--file` option), since nesting is by definition in a single file.

**Comment by ericzered** [comment]
Hello, I think I have an issue like this : 
I'm using mocha with webdriverIO tests.
I have several specs file ('test.spec.ts'). Inside each spec file, I have several 'describe' and inside each 'describe', I have several 'it'.

I'm looking for a way to execute something before each 'describe' (so 'suite' if I'm reading the doc correctly).
So I put actions in "beforeSuite" in the "wdio.conf.js" file, but it's executed only when the spec file start.

And I'm looking for a way to retry a 'describe' when a test is failing, and right now I'm only able to retry an 'it' or an entire specs file, not a 'describe' suite.
What conf should I do ? 
Thanks a lot

**Comment by mabubakr10** [comment]
> Hello, I think I have an issue like this :
> I'm using mocha with webdriverIO tests.
> I have several specs file ('test.spec.ts'). Inside each spec file, I have several 'describe' and inside each 'describe', I have several 'it'.
> 
> I'm looking for a way to execute something before each 'describe' (so 'suite' if I'm reading the doc correctly).
> So I put actions in "beforeSuite" in the "wdio.conf.js" file, but it's executed only when the spec file start.
> 
> And I'm looking for a way to retry a 'describe' when a test is failing, and right now I'm only able to retry an 'it' or an entire specs file, not a 'describe' suite.
> What conf should I do ?
> Thanks a lot

same problem here.

**Comment by d2ci8xc5** [comment]
Any updates on this? I am in a similar case to the author in which I have multiple suites distributed across multiple files. The docs clearly state that root level hooks will run on all suites. For the moment I guess the patch is to simply paste the hooks across your suite. Not very DRY. 

```
You may also pick any file and add "root"-level hooks. For example, add beforeEach() outside of all 
describe() blocks. This will cause the callback to beforeEach() to run before any test case, regardless 
of the file it lives in (this is because Mocha has an implied describe() block, called the "root suite").
```

**Comment by stevenvachon** [comment]
Same with:
```js
mocha.rootHooks({
  afterAll: () => {}, // after all suites
  afterEach: () => {} // after each test
});
```

There is no `after` for "after each suite".

**Comment by littlezigy** [comment]
This would be incredibly useful.

**Comment by boneskull** [comment]
I would like to understand better what the use cases are for this. As mentioned above, the "Mocha way" to do this is to use nested suites, but that sounds unpalatable for some.

- What third-party software are you using Mocha with?
- What are the drawbacks you're facing when trying to express this with nested suites?
- Are you trying to run code after each suite across all files, or across each suite within a file, or across each suite within a parent suite? 
- The same question as previous, but _before_ instead of _after_?
- Would you need a shared context object (`this`)?
- What exactly are you trying to do after every suite?

**Comment by littlezigy** [comment]
- Does third party software include npm packages?

- I would like before hooks that run before every test suite (all files). For integrated tests and functional tests, I like to do db cleanups before each suite. Inside the suites, I setup the db for the nested tests to use.

Right now, I just use the same root level before hook in each test file (which is just nested suites). It gets tedious with several test files. 

I don't really use after, but I imagine it would be useful in some cases.
I don't know about others, but I don't need 'this', except maybe for setting timeout, but I'm assuming that would work in the before file, or on the terminal.

**Comment by JoshuaKGoldberg** [comment]
https://github.com/mochajs/mocha/issues/4039#issuecomment-719839040 has some very good questions. It's been over 3 years since this was posted and they mostly haven't been answered. Closing this issue for housekeeping. If anybody wants to continue it, please do file a new issue with a new issue template. Cheers!
