### ISSUE TITLE
Unexpected token on ES6 Import Statement in React Native

### ISSUE THREAD

**Issue by dschinkel** [mochajs/mocha#4040]
I have setup mocha for React just fine using the proper @babel plugins or presets.  But with React Native, cannot get past the error saying it can't transpile import statements.

Typically you'd just add whatever babel 7 presets are missing in .babelrc but since it's using metro I guess it doesn't work with say the following in my .babelrc:

```
{
  "presets": [
    ["@babel/preset-env", {
      "targets": {
        "node": "current"
      }
    }],
    ["@babel/preset-react", {
      "development": true,
      "modules": false
    }],
    ["module:metro-react-native-babel-preset"]],
  "plugins": [
    ["@babel/plugin-transform-runtime"],
    ["@babel/plugin-proposal-export-default-from"],
    ["@babel/plugin-transform-async-to-generator"]
  ]
}
```

Any suggestions?  Is mocha not compatible with React Native or am I just not understanding the proper setup for mocha with native?  Should I just ditch mocha all-together with native and use Jest?

**Comment by craigtaub** [comment]
Sorry this has taken so long to get seen. Did you have any luck here?
