### ISSUE TITLE
Manage  contributors in package.json

### ISSUE THREAD

**Issue by outsideris** [mochajs/mocha#4053]
As @juergba [said](https://github.com/mochajs/mocha/pull/4041#pullrequestreview-296882461), contributors in `package.json` is too large.

I agreed with him because it makes hard to show `package.json`. Sometimes, when I explained about mocha's `package.json`, there are too many lines.

We can keep the list in `CONTRIBUTORS.md` or `AUTHORS.md`. ref: https://github.com/mochajs/contributors/pull/7

What do you think? @mochajs/core

**Comment by juergba** [comment]
I agree, this list should be removed out of package.json. Node has an "AUTHORS" file, maybe we can use the same software to extract the names and create the file.

**Comment by Munter** [comment]
The solution Node runs with sounds finw

**Comment by craigtaub** [comment]
Agree re: `AUTHORS`

**Comment by jdaykin454** [comment]
> As @juergba [said](https://github.com/mochajs/mocha/pull/4041#pullrequestreview-296882461), contributors in `package.json` is too large.
> 
> I agreed with him because it makes hard to show `package.json`. Sometimes, when I explained about mocha's `package.json`, there are too many lines.
> 
> We can keep the list in `CONTRIBUTORS.md` or `AUTHORS.md`. ref: https://github.com/mochajs/contributors/pull/7
> 
> What do you think? @mochajs/core

**Comment by jdaykin454** [comment]
> As @juergba [said](https://github.com/mochajs/mocha/pull/4041#pullrequestreview-296882461), contributors in `package.json` is too large.
> 
> I agreed with him because it makes hard to show `package.json`. Sometimes, when I explained about mocha's `package.json`, there are too many lines.
> 
> We can keep the list in `CONTRIBUTORS.md` or `AUTHORS.md`. ref: https://github.com/mochajs/contributors/pull/7
> 
> What do you think? @mochajs/core

**Comment by jdaykin454** [comment]
Add

**Comment by jdaykin454** [comment]
> As @juergba [said](https://github.com/mochajs/mocha/pull/4041#pullrequestreview-296882461), contributors in `package.json` is too large.
> 
> I agreed with him because it makes hard to show `package.json`. Sometimes, when I explained about mocha's `package.json`, there are too many lines.
> 
> We can keep the list in `CONTRIBUTORS.md` or `AUTHORS.md`. ref: https://github.com/mochajs/contributors/pull/7
> 
> What do you think? @mochajs/core

**Comment by jdaykin454** [comment]
> I agree, this list should be removed out of package.json. Node has an "AUTHORS" file, maybe we can use the same software to extract the names and create the file.

**Comment by jdaykin454** [comment]
Manage author

**Comment by jdaykin454** [comment]
> I agree, this list should be removed out of package.json. Node has an "AUTHORS" file, maybe we can use the same software to extract the names and create the file.

**Comment by jdaykin454** [comment]
> I agree, this list should be removed out of package.json. Node has an "AUTHORS" file, maybe we can use the same software to extract the names and create the file.

**Comment by jdaykin454** [comment]
> As @juergba [said](https://github.com/mochajs/mocha/pull/4041#pullrequestreview-296882461), contributors in `package.json` is too large.
> 
> I agreed with him because it makes hard to show `package.json`. Sometimes, when I explained about mocha's `package.json`, there are too many lines.
> 
> We can keep the list in `CONTRIBUTORS.md` or `AUTHORS.md`. ref: https://github.com/mochajs/contributors/pull/7
> 
> What do you think? @mochajs/core
