### ISSUE TITLE
Issue with mocha 'retries'

### ISSUE THREAD

**Issue by pk-saxena** [mochajs/mocha#4067]
Hi everyone.
I have a question related to usage of retries inside mocha framework. I am using webdriverio v 5.11 with mocha test runner. Below is a condensed version of my test:
```
  describe('should set up creating test data', () => {
    this.retries(3) // Retry all tests in this suite up to 3 times
    let respJobList = {}
    it('should succeed on the 3rd try', async () => {
      respJobList = await executeScriptFromPathToGenerateBaseData(
        __dirname,
        '../',
        'data',
        'job_list',
        'jobList.yml'
      )
      expect(respJobList).to.not.equal(undefined)
      recruiterJobListTest = {
        email: respJobList.recruiterJobList.email,
        password: respJobList.recruiterJobList.password
      }
    })
  })
```
I have described `mochaOpts` in `wdio.conf.js`
```
  mochaOpts: {
    ui: 'bdd',
    require: ['babel-polyfill'],
    compilers: ['js:babel-core/register'],
    timeout: debug ? ONE_HOUR : 300000,
    retries: 3
  }
```
Actual Results: When I run this test, I get the error `TypeError: Cannot read property 'retries' of undefined`.
What am I missing here?

Thanks in advance.

**Comment by juergba** [comment]
[arrow functions](https://mochajs.org/#arrow-functions)
You can't use arrow functions with `this.timeout` / `this.retries` / `this.skip`... in Mocha.
Change it to a normal function: `describe('should set up creating test data', function() {`

**Comment by pk-saxena** [comment]
thanks a lot. working now.
