### ISSUE TITLE
--retries <retryNumber> is not working if code execution fails in beforEach / before hook

### ISSUE THREAD

**Issue by d33pshikha** [mochajs/mocha#4075]

**Comment by wnghdcjfe** [comment]
Can you show me the example code?
I tried like this. 
```js
'use strict'; 
const {expect} = require('chai'); 
beforeEach(function() { 
  console.log(1)
});

describe('Test --retries <retryNumber>#4075', function() { 
  it('should be retries', function(){   
    //this.retries(4);
    expect(false).to.be.true; 
  });
});

afterEach(function() { 
  console.log(2) 
});
```
and it is worked. 
```shell
Juui-MacBookAir:test juhongchul$ mocha a.js --retries 4


  Test --retries <retryNumber>#4075
1
2
1
2
1
2
1
2
1
    1) should be retries
2


  0 passing (18ms)
  1 failing

  1) Test --retries <retryNumber>#4075
       should be retries:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (a.js:10:24)
```

**Comment by d33pshikha** [comment]
'use strict'; 
const {expect} = require('chai'); 
beforeEach(function() { 
// If there is any pre-requisite step which fails
  expect(false).to.be.true; 
});

describe('Test --retries <retryNumber>', function() { 
  it('should retry', function(){
    console.log("test");
  });
});

Just wanted to confirm, what if a test fails in beforeEach or before hook, whether --retries will retry ?

**Comment by wnghdcjfe** [comment]
```js
'use strict'; 
const {expect} = require('chai'); 


describe('Test --retries <retryNumber>#4075', function() { 
  beforeEach(function() {  
    it('should be retries', function(){   
      this.retries(4); 
      expect(false).to.be.true; 
      console.log("should tested?")
    });
    console.log(1) 
  });
  it('should be retries', function(){   
    //this.retries(4);
    expect(false).to.be.true; 
  });
  afterEach(function() { 
    console.log(2) 
  });
});
 ```
You mean this? `describe > beforeEach > it` retries and test is not work?  
And I want you to use Markdown's grammar to see a clean code

**Comment by d33pshikha** [comment]
I mean describe > beforeEach. 
I am not nesting tests.

**Comment by wnghdcjfe** [comment]
You want to put a test on that hook?
You can't test in hook.

**Comment by juergba** [comment]
> Just wanted to confirm, what if a test fails in beforeEach or before hook, whether --retries will retry?

No, it will not. This behavior is by design, see [docu](https://mochajs.org/#retry-tests).
see also #4006
