### ISSUE TITLE
Pending test emit `test end` event

### ISSUE THREAD

**Issue by ilgonmic** [mochajs/mocha#4079]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description
Now there is `test end` event after `pending` event in case of pending test
It can be a bit unexpected, because there is no `test start` event

### Steps to Reproduce
1. One pending test
For example
```
describe("MyTest", function () {
    xit("foo");
});
```

**Expected behavior:** [What you expect to happen]
Only `pending` event emitted

**Actual behavior:** [What actually happens]
`pending` event emitted
`test end` event emitted

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 6.2.2
- The output of `node --version`: v12.10.0
- Your operating system
  - name and version: MacOS Catalina 10.15
  - architecture (32 or 64-bit): 64 bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): bash
- Your browser and version (if running browser tests): Chrome 77.0.3865.120
- Any third-party Mocha-related modules (and their versions): -
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): -

### Additional Information

I think, it can be related with:
https://github.com/mochajs/mocha/blob/f73e7c681699a72a1b6b4d8db5c3af9ceccce66f/lib/runner.js#L630
I can make PR, if you agree that it is defect, but not "by design"

**Comment by juergba** [comment]
@ilgonmic thank you.
Some of our reporters listen to the `EVENT_TEST_END` event, therefore I prefer to leave the code as is.
