### ISSUE TITLE
No longer works on Windows in Node.js 12.11.0 and later

### ISSUE THREAD

**Issue by vitaly-t** [mochajs/mocha#4080]
Starting from Node.js 12.11.0, mocha no longer works on Windows.

In my project, I use the following command inside `package.json`:

```json
"test": "nyc mocha -r ts-node/register test/**/*.spec.ts"
```

This has worked across all platforms and all Node.js versions up to version 12.10.0

Starting from Node.js 12.11.0, all tests stopped working, producing the following error:

```
> nyc mocha -r ts-node/register test/**/*.spec.ts

internal/modules/cjs/loader.js:783
    throw err;
    ^

Error: Cannot find module 'D:\NodeJS\sub-events\node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
npm ERR! Test failed.  See above for more details.
```

Note that Linux environment seems to be unaffected, only Windows.

The actual project, which can be used for testing the issue: [sub-events](https://github.com/vitaly-t/sub-events). From Node.js 12.11.0 and later, running `npm test` will succeed on Linux, but will fail on Windows.

---

* Windows 10 64-bit
* Node.js 12.11.0, 12.12.0, 12.13.0
* Mocha 6.2.2

---

P.S. I'm not quite sure if this is the `mocha` issue or `nyc`, the error log isn't clear on that.

**Comment by wnghdcjfe** [comment]
Can you give me a mini-example? 
Or have you ever tested it with JavaScript instead of TypeScript?

**Comment by vitaly-t** [comment]
[example](https://github.com/vitaly-t/sub-events) link was given earlier. Running `npm test` under Windows will show the problem when Node.js is v12.11.0 or later.

**Comment by cedx** [comment]
@vitaly-t The problem is probably with `nyc`. Upgrading to the latest version (15.0.0-beta.0) fixes the issue.
See: https://github.com/istanbuljs/nyc/issues/1205

**Comment by juergba** [comment]
> P.S. I'm not quite sure if this is the mocha issue or nyc, the error log isn't clear on that.

@vitaly-t  Can this PR be closed?

**Comment by juergba** [comment]
I tested your project `sub-events` and it works:
- Windows 10 64-bit
- Node v12.13.0
- Mocha v6.2.2
- Nyc v14.1.1

**Comment by vitaly-t** [comment]
@juergba It works now, thank you!

**Comment by BenJohnThird** [comment]
Just for confirmation, update your nyc version to the latest and it would work.
Currently, I've set mine into "npx nyc@latest mocha" which from the documentation, installed the latest nyc versions for us.
