### ISSUE TITLE
Insufficient white space for API docs in view on mobile

### ISSUE THREAD

**Issue by HyunSangHan** [mochajs/mocha#4081]
[API docs](https://mochajs.org/api/) has responsive design patterns across different devices. However, the left white space looks inadequate when the device width is less than 400 px. Especially on 360px devices, the text is hidden, so hard to read it like this:

![image](https://user-images.githubusercontent.com/44132406/67502372-bf96de00-f6c0-11e9-9849-11b88abbe538.png)

This may need to be fixed, since most mobile devices are less than 400px wide (usually 375px or 360px) as shown below:

![image](https://user-images.githubusercontent.com/44132406/67489952-67a2ac00-f6ad-11e9-9778-7eea6fd6508b.png) ![image](https://user-images.githubusercontent.com/44132406/67489987-77ba8b80-f6ad-11e9-9e3d-b4ab9c9977a0.png) 
(I captured this reference in [Sketch 3](https://www.sketch.com/docs/grouping/artboards/) application.)

**Comment by wnghdcjfe** [comment]
LGTM

**Comment by craigtaub** [comment]
We will need to release this. I'll take a look.
