### ISSUE TITLE
describe.only/--grep still runs code in other describe blocks

### ISSUE THREAD

**Issue by kwasimensah** [mochajs/mocha#4086]
### Prerequisites

- [ x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

describe.only/--grep will still run code in other describe blocks if they're outside of in it block.

### Steps to Reproduce

```
describe("Suite A", function() {
  console.log("Before test in Suite A")
  it("runs Test", function() {
    console.log("In Suite A")
  })
})

describe.only("Suite B", function() {
  console.log("Before test in Suite B")
  it("runs Test", function() {
    console.log("In Suite B")
  })
})
```

**Expected behavior:** [What you expect to happen]
"Before test in Suite A" is not printed

**Actual behavior:** [What actually happens]

"Before test in Suite A" is printed

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of the time.

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
6.2.2

- The output of `node --version`:
v12.12.0

**Comment by kwasimensah** [comment]
Just realized it works properly if you use before blocks. What's the recommend way of having a series of tests share variables (all immutable so no worries about side effects)?

```
describe("Suite A", function() {
  before(function() {
    console.log("Before test in Suite A")
    
  })
  it("runs Test", function() {
    console.log("In Suite A")
  })
})

describe.only("Suite B", function() {
  before(function() {
    console.log("Before test in Suite B")
  })
  it("runs Test", function() {
    console.log("In Suite B")
  })
})
```

**Comment by Munter** [comment]
This is by design. The [lifecycle](https://mochajs.org/#run-cycle-overview) is to execute all `describe` calls first to set up hooks and queue tests. Any code inside `describe` will be executed at this time, before any tests start running.

If you want code to be executed as part of running your tests, [hooks](https://mochajs.org/#hooks) are how to do it
