### ISSUE TITLE
mocha splitting = in cli arguments

### ISSUE THREAD

**Issue by basickarl** [mochajs/mocha#4091]
mocha 6.1.4
node 10.16.0

I have an application which is started with the following:
```
node index.js --prefix=DEV
```

In node.js the arguments list shows as following (https://nodejs.org/docs/latest/api/process.html#process_process_argv):
```
[ '/home/karl/.nvm/versions/node/v10.16.0/bin/node',
  '/home/karl/dev/application/index.js',
  '--prefix=DEV' ]
```
mocha however seems to split `=` strings:
```
[ '/home/karl/.nvm/versions/node/v10.16.0/bin/node',
  '/home/karl/dev/application/node_modules/mocha/bin/_mocha',
  'index.js',
  '--prefix',
  'DEV'
```

This makes mocha impossible to test an application that is dependent on using the `=`. Or is there a workaround I'm not aware of?

**Comment by juergba** [comment]
Mocha's CLI parses Mocha / Node options and positional arguments. You cannot expect Mocha to do the same for your own application, and of all the others as well.

To pass your own application's options to Mocha tests:
you can use environment variables (similar to NODE_OPTIONS),
or your flags should still be available on `process.argv`,
or you create an RC file with your configuration, which you can access in a `before` hook.

**Comment by basickarl** [comment]
@juergba I can't expect it? I disagree. This is a test framework meant to test application code. If I write a cli application that takes arguments in the form of --prefix=DEV that node.js *can handle* I expect mocha to do the same.

We are not talking about environmental variables here, that is a completely different matter.
Yes they are available in process.argv, but not handled correctly/the same way as node.js, which is the point of this issue, as I showed in the example.
Such workarounds work around testing application code. I was rather hoping there was a flag/argument in mocha to pass arguments to the node binary, which would act like a production application.

**Comment by juergba** [comment]
> The question is: Will you take me seriously

I'm not sure about your profil. Either you are a troll and very funny. Or ... I don't know.
Mocha does not test your application for you like `node mocha yourApplication.js`. You have to write the tests yourself and then run them against your application. And no, AFAIK Mocha does not touch `process.argv`.
Maybe you should have a look at our tests in our github repo, you will find some CLI test too.

**Comment by basickarl** [comment]
Thank you for the personal remarks, there is a point with my profile which was just shown.

> And no, AFAIK Mocha does not touch `process.argv`.

There a clear difference in the examples I have shown, perhaps someone who does know why the array is different could answer this thread.

I'm not interested in writing flaky tests, I want actually cli arguments to be passed to the node binary.
