### ISSUE TITLE
rerun entire Describe if a test failed

### ISSUE THREAD

**Issue by ericzered** [mochajs/mocha#4094]
Hello, I'm reading here https://webdriver.io/docs/retry.html#rerun-suites-in-mocha that this.retries(4) should retry all the Describe part if any error occurs. But it only retry the "it" which fails.
I have this in my package.json:
```
"@wdio/mocha-framework": "^5.10.1",
"@types/mocha": "^5.2.7",
"mocha": "^5.2.0",
```
my script :
```
describe ('test', function() {
    this.retries(4);
    it ('1 step', function() {
        console.log('1');
    });
    it ('2 step', function() {
        console.log('2');
        assert(false);
    });
});
```
and output, proof that only the second 'it' ran 5 times
```
[0-0] 1
[0-0] 2
[0-0] 2
[0-0] 2
[0-0] 2
[0-0] 2
[0-0] AssertionError in "test 2 step"
[MultiremoteBrowser #0-0]    ✓ 1 step
[MultiremoteBrowser #0-0]    ? 2 step
[MultiremoteBrowser #0-0]    ? 2 step
[MultiremoteBrowser #0-0]    ? 2 step
[MultiremoteBrowser #0-0]    ? 2 step
[MultiremoteBrowser #0-0]    ✖ 2 step
[MultiremoteBrowser #0-0]
[MultiremoteBrowser #0-0] 1 passing (1.8s)
[MultiremoteBrowser #0-0] 1 failing
[MultiremoteBrowser #0-0]
[MultiremoteBrowser #0-0] 1) test 2 step
[MultiremoteBrowser #0-0] Unspecified AssertionError
```
I see that I have the exact same problem than here : https://github.com/webdriverio/webdriverio/issues/564#issuecomment-263579491
I'm looking for a way to rerun describe but maybe it's not possible...
Thanks

**Comment by wnghdcjfe** [comment]
decribe > test : mocha doesn't design that

**Comment by juergba** [comment]
[docu](https://mochajs.org/#retry-tests)
`this.retries()` reruns failed tests up to a certain number of times, but not complete `describe`'s.
Your output shown above is correct as it is intended to be, Mocha does not offer a feature to repeat a complete `decribe` block upon failure.
