### ISSUE TITLE
404 link for official documentation

### ISSUE THREAD

**Issue by mrdulin** [mochajs/mocha#4095]
Below links are 404:

* https://github.com/mochajs/mocha-examples/tree/master/babel
* https://github.com/mochajs/mocha-examples/tree/master/typescript

From the section of official documentations: https://mochajs.org/#-require-module-r-module

**Comment by SheetJSDev** [comment]
Commit https://github.com/mochajs/mocha-examples/commit/120b82846a28532572d3853335dfe44b8fadf23d in late October moved those paths into a `packages` subdirectory, the new links are:

- https://github.com/mochajs/mocha-examples/tree/master/packages/babel
- https://github.com/mochajs/mocha-examples/tree/master/packages/typescript

**Comment by mrdulin** [comment]
@SheetJSDev Thanks!
