### ISSUE TITLE
Can't find and run all test files recursively

### ISSUE THREAD

**Issue by mrdulin** [mochajs/mocha#4096]
### Prerequisites

- [ x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Can't find and run all test files recursively. Here is my folder structure:

```bash
☁  src [master] ⚡  tree    
.
└── stackoverflow
    ├── 57586444
    │   ├── index.spec.ts
    │   └── index.ts
    ├── 57997682
    │   ├── index.spec.ts
    │   └── index.ts
    ├── 58058653
    │   ├── sendEmail.ts
    │   ├── submitDetails.spec.ts
    │   └── submitDetails.ts
    ├── 58357977
    │   ├── index.spec.ts
    │   └── index.ts
    └── 58822996
        ├── index.spec.ts
        └── index.ts

6 directories, 11 files
```
I need to run all `*.spec.ts` files in subdirectories.

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]

Expected all `*.spec.ts`  test files in subdirectories run.

**Actual behavior:** [What actually happens]

It's very weird that only one test file run.

```bash
☁  mocha-chai-sinon-codelab [master] ⚡  npx mocha ./src/**/*.spec.ts                                                                                          


func called
  ✓ should check if function is called or not

  1 passing (15ms)
```
With `--recursive` option, it's same.
```bash
☁  mocha-chai-sinon-codelab [master] ⚡  npx mocha ./src/**/*.spec.ts --recursive


func called
  ✓ should check if function is called or not

  1 passing (13ms)
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time.

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 6.2.2
- The output of `node --version`: v10.16.0
- Your operating system
  - name and version:   macOS 10.13.6 (17G6030)
  - architecture (32 or 64-bit): 64-bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh
- Your browser and version (if running browser tests): 
- Any third-party Mocha-related modules (and their versions): 
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): ts-node/register

### Additional Information

Minimal reproduce repo: https://github.com/mrdulin/mocha-chai-sinon-codelab

**Comment by yeldiRium** [comment]
I just thought I had a similar problem and found a solution for mine. Try to put the path in your command in quotes, like this:

```
☁  mocha-chai-sinon-codelab [master] ⚡  npx mocha "./src/**/*.spec.ts" --recursive
```

The glob expansion behavior of mocha seems to differ from that of the shells I've tried (namely bash and zsh).

**Comment by juergba** [comment]
Use single quotes (and remove `--recursive`), then it should work.

**Comment by juergba** [comment]
In one of your spec files you are using `it.only(...)`, therefore only one test is executed.

**Comment by mrdulin** [comment]
@juergba  Thanks. yes it is, there is a test file using `it.only(...)`. well, my thinking is the scope of `it.only(...)` is a file scope. But now, it looks like the scope is global scope which means cross all test files.
