### ISSUE TITLE
With `ui` set to `tdd` I have to import "mocha" (TypeScript)

### ISSUE THREAD

**Issue by jgehrcke** [mochajs/mocha#4099]
With `ui` set to `bdd` (default) this works:
```
import { strict as assert } from "assert";

describe("A demo dest suite", () => {
  it("demo test", () => {
    assert.equal(true, true);
  });
});
```

Changing to `ui` set to `tdd` (and replacing `describe` with `suite`, and `it` with `test`):
```
import { strict as assert } from "assert";

suite("A demo dest suite", () => {
  test("demo test", () => {
    assert.equal(true, true);
  });
});
```
I was surprised to see a `mocha.test.ts:3:1 - error TS2582: Cannot find name 'suite'`. I can address that by adding `import "mocha";` to the second example.

But I suspect that this is not intended behavior, I expect the `tdd` and `bdd` to behave more symmetrically. Feedback welcome.

**Comment by juergba** [comment]
You don't mention your typescript setup at all, so I can't give you any feedback about your specific example.
I tested our own typescript [sample](https://github.com/mochajs/mocha-examples/tree/master/packages/typescript) and it works perfectly with `tdd` interface.
You have to set the interface accordingly, in a configuration file or by `npm test -- --ui tdd`.

**Comment by jgehrcke** [comment]
> You have to set the interface accordingly, in a configuration file or by npm test -- --ui tdd.

As I said this is what I did:

> Changing to `ui` set to `tdd` (and replacing describe with suite, and it with test):

This sentence _precisely_ describes the difference between the success and error scenario.

I understand that a complete minimal working example (MWE) is a little bit easier to parse, but I am surprised that you seemingly missed the part where I explicitly stated that the problem occurs with setting `ui` to `tdd`.

I might look into providing an MWE, let's see.

**Comment by jgehrcke** [comment]
MWE repro. @juergba would you mind having another look at this? Thank you! :)

### environment details
```
$ cat package.json 
{
  "name": "repro",
  "version": "1.0.0",
  "private": true,
  "description": "",
  "scripts": {
    "mocha": "mocha"
  },
  "author": "",
  "license": "wtf",
  "dependencies": {
    "@types/mocha": "^5.2.7",
    "mocha": "^6.2.2",
    "ts-node": "^8.5.2",
    "typescript": "^3.7.2"
  }
}

$ npm install .
audited 190 packages in 0.775s
found 0 vulnerabilities

$ node --version
v12.13.1

$ cat .mocharc.json 
{
  "extension": ["ts"],
  "require": "ts-node/register"
}
```


### bdd w/o import mocha: works
```
$ cat repro-bdd-style.test.ts 
import { strict as assert } from "assert";

describe("A demo dest suite", () => {
  it("demo test", () => {
    assert.equal(true, true);
  });
});
```
```
$ npm run mocha repro-bdd-style.test.ts -- --ui bdd

> repro@1.0.0 mocha /<XXXX>
> mocha "repro-bdd-style.test.ts" "--ui" "bdd"



  A demo dest suite
    ✓ demo test


  1 passing (4ms)
```

### tdd w/o import mocha: error
```
$ cat repro-tdd-style.test.ts 
import { strict as assert } from "assert";
//import "mocha"

suite("A demo dest suite", () => {
  test("demo test", () => {
    assert.equal(true, true);
  });
});
```

```
$ npm run mocha repro-tdd-style.test.ts -- --ui tdd

> repro@1.0.0 mocha /<XXXX>
> mocha "repro-tdd-style.test.ts" "--ui" "tdd"


/<XXXX>/node_modules/ts-node/src/index.ts:293
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
repro-tdd-style.test.ts:4:1 - error TS2582: Cannot find name 'suite'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.
[...]
```

### tdd _with_ import mocha: works

Removing the `//` in the last snippet:
```
$ cat repro-tdd-style.test.ts 
import { strict as assert } from "assert";
import "mocha"

suite("A demo dest suite", () => {
  test("demo test", () => {
    assert.equal(true, true);
  });
});
```
Running this:
```
$ npm run mocha repro-tdd-style.test.ts -- --ui tdd

> repro@1.0.0 mocha /home/jp/dev/opstrace/test/test-remote/import-fuck
> mocha "repro-tdd-style.test.ts" "--ui" "tdd"



  A demo dest suite
    ✓ demo test


  1 passing (4ms)
```

**Comment by juergba** [comment]
> TSError: ⨯ Unable to compile TypeScript:

This obviously is a typescript compile error. Something in your typescript setup is wrong, eg. I can't see `tsconfig.json` in your environment details. I recommend to download our typescript sample mentioned above and adapt it to your needs.

**Comment by jgehrcke** [comment]
> I can't see tsconfig.json in your environment details

Thanks for the hint and for your time @juergba -- you had the right intuition all along. Up the directory tree I had a  let's say complex" `tsconfig.json`. By putting an empty `tsconfig.json` into my repro directory snippet `(2)` from my previous comment works!
