### ISSUE TITLE
More inclusive language in documentation

### ISSUE THREAD

**Issue by carolstran** [mochajs/mocha#4120]
:wave: Sorry I know I'm ignoring your well-thought-out templates, but I wasn't sure where this would land! Hear me out...

I noticed that there are a couple of instances of words like "simply" in your documentation. Unfortunately, words like this can make people feel frustrated and isolated while reading - especially if they are facing issues.

If it's alright with your team, I'd like to take a shot at updating the content to make it more inclusive by removing or replacing instances of "simply", "easy", "just", etc. We use mocha in some [Unmock](https://github.com/unmock) projects so I'm happy to help 😊  

Also if you're interested or want more information on this topic, I'd highly recommend watching Jim Fisher's [Don't Say Simply](https://www.youtube.com/watch?v=gsT2BBWBVmM) talk from Write the Docs Prague 2018 ✍️ 🤓 

Thank you for the work you do and please let me know if you need more details!

**Comment by juergba** [comment]
@carolstran thank you.
For my taste this issue is too far-fetched and I don't see a reason for opening an PR.
I will close this issue within the next few days.

**Comment by carolstran** [comment]
Hi there 👋  I respect your opinion, but I would still encourage you to take some time and watch [Jim Fisher's talk](https://www.youtube.com/watch?v=gsT2BBWBVmM) or read my article on [removing condescending language](https://dev.to/meeshkan/how-to-remove-condescending-language-from-documentation-4a5p). While it may seem far-fetched at first, this issue could have a huge impact on how people feel about and learn Mocha.

Thanks for your time and consideration. If you ever change your mind, I'm happy to do the work!

**Comment by ORESoftware** [comment]
inclusivity, diversity and equality ♾️
