### ISSUE TITLE
TypeError: mocha.reporter is not a function

### ISSUE THREAD

**Issue by breyana** [mochajs/mocha#4124]
### Prerequisites
- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Attempting to call mocha.reporter is returning "mocha.reporter is not a function"

### Steps to Reproduce
```
const mocha = require('mocha')
mocha.reporter()
```

**Expected behavior:** 
Console mentions needing parameters for mocha.reporter()

**Actual behavior:** [What actually happens]
```
TypeError: mocha.reporter is not a function
    at Object.<anonymous> (/Users/[scrubbed])
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```

**Reproduces how often:** 100%

### Versions

- node_modules/.bin/mocha --version
6.2.2

- The output of `node --version`:
v12.13.0

- Your operating system
  - name and version: macOS Mojave Version 10.14.6
- Your shell (e.g., bash, zsh, PowerShell, cmd): 
zsh

**Comment by juergba** [comment]
You have to create a Mocha instance before you can use it.
Please see [here](https://github.com/mochajs/mocha/wiki/Using-Mocha-programmatically) for using Mocha programmatically.

**Comment by breyana** [comment]
Thank you!
