### ISSUE TITLE
Update Documentation for "every option shown" .mocharc.yml

### ISSUE THREAD

**Issue by 76784** [mochajs/mocha#4130]
In the mocha documentation (https://mochajs.org/#configuration-format) we are pointed to this: https://github.com/mochajs/mocha/tree/master/example/config

One may then view https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml

...where one is told: `This is an example Mocha config containing every Mocha option plus others`

There are two issues with https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml

**Issue One**
Based on https://mochajs.org/api/mocha, it would appear that https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml is out of date. 

Firstly, .mocharc.yml shows property names that are different from what is listed at https://mochajs.org/api/mocha. 

For example:
full-trace vs. fullStackTrace
reporter-option vs reporterOption

Secondly, .mocharc.yml does not have some of the property names listed at https://mochajs.org/api/mocha

For example:
enableTimeouts
useInlineDiffs

**Issue Two** 
Including options that are "other" than those that are part of the mocha options without explanation is incredibly confusing. To give but one example, how is one supposed to know what the "file" option does _when it is not listed at mocha_?

If you are going to provide "other" options, there should be an explanation of what they are and where the documentation for them reside.

**Comment by juergba** [comment]
You are mentioning two different things: our CLI options and the `Mocha` constructor.
Yes, you are right, there are some confusing and even buggy facts about our options in <=v6.2.2, which should have been adressed in our current `master` branch, to be published with v7.0.0.
The option names have also been synchronized between CLI, `Mocha` constructor (and browser).

- [mocharc.yml](https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml): shows state of `master`. Use `--help` to see list of CLI options of your version.
- `This is an example Mocha config containing every Mocha option plus others`: IMO all Mocha options are documented, but additionally you can set Node options via Mocha. We are not planning to document Node options.
- `--file`: all Mocha options should be documented. `--file` is a CLI option and there is no sense in listing it in the `Mocha` constructor.

Part of the confusion is explained by the fact that "mocharc.yml" shows the state of `master`. I'm sorry about that, will be solved with v7.0.0.
Second please don't mess CLI options with `Mocha` constructor options.
You need CLI options when you launch Mocha via command line.
You use the `Mocha constructor options when you run Mocha programmatically.

**Comment by 76784** [comment]
I see, and thanks for the response. Then if I may suggest making it clear to the reader by keeping two sections in the mocha options with comments, like so:

```
# Mocha CLI options - complete list 
# (use --help to see list of CLI options of your version of Mocha):
allowUncaught: true
...
useInlineDiffs

# Additionally, Node options can be set via the Mocha config file. Examples:
spec: foo/**/*.test.js
diff: true
extension:
   - txt
file: 
   - src/**/calc.js
ignore: 
   - blah/**/bar.test.js
```
> Second please don't mess CLI options with Mocha constructor options.

This also should be made clear, with an example in the file. Thank you.

**Comment by juergba** [comment]
Please have another look at our documentation [command-line-usage](https://mochajs.org/#command-line-usage), where you find every Mocha CLI option documented.
