### ISSUE TITLE
Expected "Resolution method is overspecified"

### ISSUE THREAD

**Issue by coreyfarrell** [mochajs/mocha#4135]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Creating test with an async function which calls `done` synchronously does not result in the "Resolution method is overspecified" error.

### Steps to Reproduce

Run the following test with mocha 6.2.2:
```js
it('should throw overspecified resolution', async (done) => {
  done();
});
```

**Expected behavior:**
`Error: Resolution method is overspecified. Specify a callback *or* return a Promise; not both.`

**Actual behavior:**
The test passes.

**Reproduces how often:**
Every time.

### Versions
- mocha 6.2.2 (I tested local install only)
- node 8+
- Fedora 30 / x86_64
- bash shell
- No additional modules installed (`npm i mocha` only)

**Comment by craigtaub** [comment]
Hey, so according to the docs 

> returning a Promise and calling done() will result in an exception

Nothing to do with an async test. The code checks for a promise returned but your example does not do that so would not throw the expected message.

**Comment by coreyfarrell** [comment]
Async functions always return a promise.

**Comment by craigtaub** [comment]
@coreyfarrell yes but the "test function" and what the "test function" returns are 2 different things. A promise chain depends on that.

Mocha checks what the (async) test returns. For your example the test itself returns undefined, whereas for the docs example a promise is returned.

**Comment by coreyfarrell** [comment]
This does not seem consistent to me but to be honest I'm indifferent.  This is something that was discovered investigating an issue discovered by a user of the tap mocha interface.  Since you say mocha is acting as intended I'll close this issue.
