### ISSUE TITLE
Show more precise time duration in reporter epilogue

### ISSUE THREAD

**Issue by yomed** [mochajs/mocha#4149]
**Describe the solution you'd like**
At the end of a test run, the total duration currently shows a rounded value, like `1m`. It would be great if this was more precise, like `1m 12s 354ms` or `00:01:12.354`.

**Additional context**
The relevant code appears to be in the base reporter epilogue, here:
https://github.com/mochajs/mocha/blob/1412dc80d87d0479f7f1d60202da2b33c90eb939/lib/reporters/base.js#L349

**Comment by yomed** [comment]
This should be straightforward once `ms` supports decimal places https://github.com/vercel/ms/pull/125

**Comment by JoshuaKGoldberg** [comment]
Per https://github.com/mochajs/mocha/issues/4797#issuecomment-990737385:

> No, we are not planing to change the time format in our reports. Quite a few third-party reporters are using _mocha/lib/reporters/base.js_, so this would be a breaking change.
> 
> You can create your own reporter and implement your desired time format.
