### ISSUE TITLE
multiple calls to done() doesn't always fail if second done is called async

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#4151]
Example:

```js
it('should fail', function (done) {
  process.nextTick(function () {
    done();
    setTimeout(done);
  });
});
```

The above won't fail with a nonzero exit code. `EVENT_TEST_FAIL` is emitted, but nothing is listening at this point.

To address this:

1. The `Runner` must have a notion of a "stopped" state
1. If a test fails _while the `Runner` is in the stopped state_, then it must throw an exception.
1. How this exception is handled depends on whether the standard uncaught exception handler is still bound.  If it is, we let it be handled, and we get a proper stack trace back to the test.
1. If the standard uncaught exception handled has been disabled (which happens when `EVENT_RUN_END` is emitted)--and the process will fail with a bog-standard uncaught exception--Mocha will need to retain extra information in the error so the user can find which test is responsible.  I'm not sure why we lose the stack trace back to the test; maybe somebody can help.

Anyway, I have a fix in-progress for this.

Ref: https://twitter.com/jsumners79/status/1216391159699988481

**Comment by feckertson** [comment]
We ran into the below \[distilled\] issue with done. Is it the same thing?

The coding defect was caught in a code-review, but it never should have made it that far. 

developer's erroneous source code:
```javascript
exports.handler = function eventHandler(callback) {
  if (true){
    callback('error');
  }
  callback(null);  //triggers a second call to done during testing, but the second call does not get flagged.
}
``` 

a test which should have exposed it:
```javascript
const expect = require('chai').expect;
const subject = require('../mocha-issue.js');

describe('mocha-issue', () => {
  it('procblematic test', (done) => {
    subject.handler((e) => {
      expect(e).to.equal('error');
      done();
    });
  });
});
```

**Comment by iqianxing** [comment]
async test throw an uncaught error when test is timeout.
my test code like below:
```
var assert = require('chai').assert;
describe("# async test", function () {
  this.timeout(2000);

  it("async error", function (done) {
    var errorMessage = "some error"
    setTimeout(function () {
      assert.notOk(errorMessage)
      done();
    }, 5000)
  })
})
```
i run my test , an uncaught error display on my console like below:
![image](https://user-images.githubusercontent.com/2938263/121025336-a2e8e480-c7d7-11eb-8a6a-522cd83757e6.png)

error detail:
```
mocha\lib\runner.js:962
    throw err;
```

**Comment by iqianxing** [comment]
> async test throw an uncaught error when test is timeout.
> my test code like below:
> 
> ```
> var assert = require('chai').assert;
> describe("# async test", function () {
>   this.timeout(2000);
> 
>   it("async error", function (done) {
>     var errorMessage = "some error"
>     setTimeout(function () {
>       assert.notOk(errorMessage)
>       done();
>     }, 5000)
>   })
> })
> ```
> 
> i run my test , an uncaught error display on my console like below:
> ![image](https://user-images.githubusercontent.com/2938263/121025336-a2e8e480-c7d7-11eb-8a6a-522cd83757e6.png)
> 
> error detail:
> 
> ```
> mocha\lib\runner.js:962
>     throw err;
> ```
> 
> ![image](https://user-images.githubusercontent.com/2938263/121025735-0f63e380-c7d8-11eb-87d7-47808510e8f3.png)

some async code is still running after async test task is stopped.
