### ISSUE TITLE
Isolation of "this" on test basis.

### ISSUE THREAD

**Issue by andreventuravale** [mochajs/mocha#4157]
I have these simple tests:

```
  beforeEach(function () {
    this.count = (this.count || 0) + 1
  })

  it.only('a', function () {
    console.log('a', 'count', this.count)
    this.count = 1000
  })

  it.only('b', function () {
    console.log('b', 'count', this.count)
  })
```

Which always prints this on the console:

```
a count 1
    ✓ a
b count 1001
    ✓ b
```

The counter isn't increasing between runs, which makes sense but "b" sees the changes made by "a". Is this expected / per design?

My understanding is that "this" would always be isolated between each single test.

I was expecting the result to be:

```
a count 1
    ✓ a
b count 1
    ✓ b
```

**Comment by JosefButts** [comment]
In the before each you are setting the value to either the current value of this.count (if it is defined or 0) + 1. When the second test runs this.count is already defined and the value of this.count is set as the current value, which is 1000. If this.count needs to be set reset every time you should simply reset the value to 0 or 1 (or whatever it should be) in the before each without referencing the existing value.
```
beforeEach(function () {
    this.count =  1
  })

  it.only('a', function () {
    console.log('a', 'count', this.count)
    this.count = 1000
  })

  it.only('b', function () {
    console.log('b', 'count', this.count)
  })
```
