### ISSUE TITLE
ESNext and Create-React-App support.

### ISSUE THREAD

**Issue by RyanJMcGowan** [mochajs/mocha#4158]
Mocha does not recognize import statements on Typescript transpiled code to esnext. It gets syntax errors as it wrongly assumes commonjs formatted javascript. Note that Create-React-App does not support commonjs.

Currently, I can only run Mocha tests by either command line scripts that force transpiling to commonjs, or manually change the tsconfig.json file to use extensions like Mocha Sidebar whenever I want to run tests in a React app.

To replicate this issue, create a Create-React-App, install Mocha, and attempt to use a Mocha-run Chai test. Changing the tsconfig.json from esnext to commonjs will temporarily fix the issue, but `npm start` will return it to esnext every time. You can run a script to default to commonjs, but this only works if you use Mocha from the CLI, and should (IMO) be something that is necessary.

It would be wonderful to just add Mocha to a Typescript project in esnext and just continue working.

**Comment by juergba** [comment]
I'm unsure wether I have understood the core of this PR.
I'm not going to create a Create-React-App for this purpose, neither does Mocha transpile esnext for you.

We have implemented Node's native ESM modules support in an experimental [release](https://github.com/mochajs/mocha/releases/tag/v7.0.0-esm1).
Give it a try, maybe that helps.

**Comment by juergba** [comment]
Please try our new release v7.1.0 which supports Node's native ESModules support.
