### ISSUE TITLE
Working with Hybrid ui

### ISSUE THREAD

**Issue by osher** [mochajs/mocha#4159]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
Hi. I got to meet a breaking change in mocha 7.x and wonder if it could be solved configurably, and if not - then would like to ask such a configuration to be supported.

The previous behavior was that when I provided any `--ui` value to a valid ui - I got to have that ui side by side with the default ui - `bdd`. However now - I get only the specified ui  - no built-in satelites.

I tried to provide two `--ui` flags - and saw that the last one overrides :disappointed: 

**Describe the solution you'd like**
Let the user provide multiple `--ui` options
Or keep the built-in bdd ui alongside the user's selection.

**Describe alternatives you've considered**
I considered downgrading mocha, but not seriously...
I considered working with two mocharc files, and that makes the run very clunky and sophisticated - especially when I want to support `npm run test` and `npm run cover` with `nyc`.

**Additional context**
I'm the author of [mocha-ui-exports-request](https://www.npmjs.com/package/mocha-ui-exports-request) - which lets you express HTTP api tests at ease.

The package started as a second layer over [https://www.npmjs.com/package/mocha-ui-exports](https://www.npmjs.com/package/mocha-ui-exports) - which brings back the go'old `exports` ui to modern capabilities - i.e fills in the gaps that `bdd` and `tdd` got but were neglected from the frozen `exports` ui (timers, pending tests, etc...).

Eventually, `mocha-ui-export-request` evolved to expose a `.bddCtx()` method that will recursively pass the entries on the suite object to the `bdd` `describe(...)` and `it(...)` calls (with the respective hooks) - and that's the part that stopped working well - because now the user is forced to chose and stick to a single ui. :disappointed: 

The hybrid mode allowed teams to using both uis side by side whenever each of them suites them best without need to migrate everything to one form

Thanks in advance :+1:

**Comment by osher** [comment]
Let me be more precise on my failing user-scenario.

The user has a custom ui in his opts file - e.g. `tdd`.
This causes the `exports-request` to return the suite, augmented with `.bddCtx()` and lets the user decide what to do with it.

The user writes tests using `bdd` even though he declared `tdd` (it used to just work).
The user tries to call the `.bddCtx()` to load the generated suite onto the `describe(..)`, `it(...)` and the respective hooks.

Expected - should work (or at least used to)
Found - `describe is not defined`

Example build:
https://travis-ci.org/osher/mocha-ui-exports-request/jobs/639393915?utm_medium=notification&utm_source=github_status

I admit - looks like I'll have to array a much bigger set of tests to support mocha 5.x, mocha 6.x and mocha 7.x and see it running though, I'll find the time to do it later.

The proposed solution will let user state all the UIs he'd like to be loaded - so all should work fine if multiple uis would be supported :grinning: 

Thanks in advance

**Comment by juergba** [comment]
If I remember well, back to v5 times this used to work (BDD plus second interface), but was classified as a bug. I don't think we are going to support this behavior again.

As an alternative you can built your own interface, as described in [wiki](https://github.com/mochajs/mocha/wiki/Third-party-UIs).

**Comment by osher** [comment]
I know, [https://www.npmjs.com/package/mocha-ui-exports](https://www.npmjs.com/package/mocha-ui-exports) is such a ui.

So what you're suggesting is that `mocha-ui-exports` should implement `bdd` as well?
I'm afraid it won't work because the user-story is that the user uses `--ui tdd` and expects to keep using `bdd` features.

What about let the user specify multiple uis? That's the proposed feature here, basically.

**Comment by juergba** [comment]
@osher No, we will not allow multiple ui's again.
As mentioned above, we already had this situation (BDD plus a second ui).
I'm sorry.
