### ISSUE TITLE
Tests stats refer the wrong line info of skipped tests

### ISSUE THREAD

**Issue by PeterNgTr** [mochajs/mocha#4166]
### Description

I have this tests.js

```js
var assert = require('assert');

// Create a test suite (group) called Math
describe('Math', function() {
  it('should test if 3*3 = 9', function(){
    // Our actual test: 3*3 SHOULD EQUAL 9
    assert.equal(9, 3*3);
  });
  // // Test Two: A string explanation of what we're testing
  // it('should test (3-4)*8 SHOULD EQUAL -8', function(){
  //   // Our actual test: (3-4)*8 SHOULD EQUAL -8
  //   assert.equal(-8, (3-4)*8);
  // });
  xit('should be clone', function(){
    // Our actual test: 3*3 SHOULD EQUAL 9
    assert.equal(9, 3*3);
  });

  it.skip('should be second clone', function(){
    // Our actual test: 3*3 SHOULD EQUAL 9
    assert.equal(9, 3*3);
  });

  describe.skip('NoMath', function() {
    it('should be disabled', () => {});
  });
});
```

When trying to get the tests stats, it returns the wrong line info
```js
[
  {
    name: 'should test if 3*3 = 9',
    suites: [ 'Math' ],
    line: 5,
    file: 'example/mocha/index_test.js',
    skipped: false
  },
  {
    name: 'should be clone',
    suites: [ 'Math' ],
    line: 14,
    skipped: true,
    file: 'example/mocha/index_test.js'
  },
  {
    name: 'should be second clone',
    suites: [ 'Math' ],
    line: 18, ---> this should be line 19. Refer screenshot for more details
    file: 'example/mocha/index_test.js',
    skipped: true
  },
  {
    name: 'should be disabled',
    suites: [ 'Math', 'NoMath' ],
    line: 23, ---> this should be line 24  Refer screenshot for more details
    file: 'example/mocha/index_test.js',
    skipped: true
  }
]
```

<img width="613" alt="Screenshot 2020-01-22 at 15 45 16" src="https://user-images.githubusercontent.com/7845001/72903886-527dfd80-3d2e-11ea-8639-055700ac3836.png">

**Expected behavior:** [What you expect to happen]
Refer to the proper line
**Actual behavior:** [What actually happens]
Refer to the wrong line

**Reproduces how often:** 100%

### Versions

Reproduced on:

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 6.2.2
- The output of `node --version`: 12.4.0
- Your operating system
  - name and version: MacOS
  - architecture (32 or 64-bit): 64-bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): bash
- Your browser and version (if running browser tests):
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):

**Comment by juergba** [comment]
@PeterNgTr  Which tests stats?

**Comment by PeterNgTr** [comment]
oh, sorry @juergba my bad. it's not the core of mochajs
