### ISSUE TITLE
Timeout in hooks leaves deamons (before & beforeEach)

### ISSUE THREAD

**Issue by saartochner** [mochajs/mocha#4168]
### Prerequisites

- [X ] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [X ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ X] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [X ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Timeout doesn't kill the test and leaves deamon that stuck the process.

### Steps to Reproduce

Run the simple following file:
```
describe("Test tmp", function () {
	this.timeout(5000);
	beforeEach(async function() {
		await new Promise(resolve => setTimeout(resolve, 20000));
	});

	it("test", async function() {
		// pass
	});
});
```

**Expected behavior:** 
The test will get timeout after 5s and then the process will exit.

**Actual behavior:** 
The process exists only after 20s (although we get the timeout message after 5s).

**Reproduces how often:** 
Always.

### Versions
7.0.0+

### Additional Information

That's killing our circleci jobs :-(

**Comment by juergba** [comment]
This behavior hasn't changed in v7, I just checked v6 which shows the identical result.
- you can use the `--exit` [option](https://mochajs.org/#-exit) to force Mocha's exit
- use an `afterEach` for correct cleanup
