### ISSUE TITLE
retries() logs state:null in json report

### ISSUE THREAD

**Issue by dcr007** [mochajs/mocha#4172]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

I'm trying this with retries() in the below async functions, please review and let me know what's that I'm doing wrong or is it a bug :
```
describe(`test description `, async function ()  {
    this.retries(1);
    let browser;
    let page;
    let presentationsPage;
   
    before(async () => {
        browser = await launchPuppeteer(options);
        page = await browser.newPage();
        await page.setViewport({ width: 1280, height: 1024 });
        navMenu = new NavigationMenu(page, dataCenter, companyID);
        await navMenu.loadNavigationMenu();
    });

    after(async () => {
        await browser.close();
    });

    it('Presentations Check', async function (done:Mocha.Done) {
        this.retries(1);
        presentationsPage = await navMenu.loadPresentationsPage();
        await presentationsPage.isPresentationsPageLoadComplete().then((result) => {
            expect(result).to.equal(true, 'Expected : Presentation Page');
            done();
        }) .catch((error) => {
            console.log('Promise rejected !\n');
            console.log(error);
            done(error);
        });
    }); 
});
```
though the retries(1) retries the test, and the console displays the test faliure as expected. But  I see the the mochawesome.json report logs test result as below, in which **I see "state": null** , is incorrect. and has to be **"state": "failed"** . 

```
{
              "title": "Presentations Check",
              "fullTitle": "Page Loads  Presentations Check",
              "timedOut": false,
              "duration": 32011,
              "state": null,
              "speed": null,
              "pass": false,
              "fail": false,
              "pending": false,
              "context": null,
              "code": "return __awaiter(this, void 0, void 0, function* () {\n    this.retries(1);\n    presentationsPage = yield navMenu.loadPresentationsPage();\n    yield presentationsPage.isPresentationsPageLoadComplete().then((result) => {\n        chai_1.expect(result).to.equal(true, 'Expected : Presentation Page');\n        done();\n    }).catch((error) => {\n        console.log('Promise rejected !\\n');\n        console.log(error);\n        done(error);\n    });\n});",
              "err": {},
              "uuid": "5b5e1a34-5309-4961-8711-9d5d32714ae4",
              "parentUUID": "57546864-0a26-49fa-8759-07ade66a8c78",
              "isHook": false,
              "skipped": true
            }
```

### Steps to Reproduce

1. npm run build  invokes:  npm run lint && rimraf lib && npm run moveJsonFiles && npm run moveAssetsFiles && tsc --outDir lib
2. npm test  invokes : mocha --timeout 999999 --reporter mochawesome lib/index.js compinfo
 
**Expected behavior:** [What you expect to happen]
The mochawesome.json report test result should be like :
```
{
              "title": "Presentations Check",
              "fullTitle": "Page Loads  Presentations Check",
              "timedOut": false,
              "duration": 32011,
              "state": "failed",
              "speed": null,  // not sure
              "pass": false,
              "fail": true,
              "pending": false,
              "context": null,
              "code": "return __awaiter(this, void 0, void 0, function* () {\n    this.retries(1);\n    presentationsPage = yield navMenu.loadPresentationsPage();\n    yield presentationsPage.isPresentationsPageLoadComplete().then((result) => {\n        chai_1.expect(result).to.equal(true, 'Expected : Presentation Page');\n        done();\n    }).catch((error) => {\n        console.log('Promise rejected !\\n');\n        console.log(error);\n        done(error);\n    });\n});",
              "err": { },// detail of the errors should get populated as displayed in the console.
              "uuid": "5b5e1a34-5309-4961-8711-9d5d32714ae4",
              "parentUUID": "57546864-0a26-49fa-8759-07ade66a8c78",
              "isHook": false,
              "skipped": true
            }
```
**Actual behavior:** [What actually happens]

The json and html reports for the 'retries' test does not gets reported correctly, however the console output looks correct.
{
              "title": "Presentations Check",
              "fullTitle": "Page Loads  Presentations Check",
              "timedOut": false,
              "duration": 32011,
              "state": null,
              "speed": null,
              "pass": false,
              "fail": false,
              "pending": false,
              "context": null,
              "code": "return __awaiter(this, void 0, void 0, function* () {\n    this.retries(1);\n    presentationsPage = yield navMenu.loadPresentationsPage();\n    yield presentationsPage.isPresentationsPageLoadComplete().then((result) => {\n        chai_1.expect(result).to.equal(true, 'Expected : Presentation Page');\n        done();\n    }).catch((error) => {\n        console.log('Promise rejected !\\n');\n        console.log(error);\n        done(error);\n    });\n});",
              "err": {},
              "uuid": "5b5e1a34-5309-4961-8711-9d5d32714ae4",
              "parentUUID": "57546864-0a26-49fa-8759-07ade66a8c78",
              "isHook": false,
              "skipped": true
            }

**Console output** 
   ✓ Instance Check (2374ms)
DELAY!: 1000 mS
DELAY!: 3000 mS
DELAY!: 2000 mS
    ✓ Login Check (11941ms)
DELAY!: 2000 mS
{ TimeoutError: waiting for selector "#biasdxSubTab_asdTALENTREVIEW_PRES_TAB" failed: timeout 30000ms exceeded
    at new WaitTask (/Users/jp116/PRECTS/deguarding/node_modules/puppeteer/lib/DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (/Users/jp116/PRECTS/deguarding/node_modules/puppeteer/lib/DOMWorld.js:478:22)
    at DOMWorld.waitForSelector (/Users/jp116/PRECTS/deguarding/node_modules/puppeteer/lib/DOMWorld.js:432:17)
    at Frame.waitForSelector (/Users/jp116/PRECTS/deguarding/node_modules/puppeteer/lib/FrameManager.js:627:47)
    at Frame.<anonymous> (/Users/jp116/PRECTS/deguarding/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.waitForSelector (/Users/jp116/PRECTS/deguarding/node_modules/puppeteer/lib/Page.js:1095:29)
    at PresationsPage.get PresationsTab [as PresationsTab] (/Users/jp116/PRECTS/deguarding/lib/pages/PresationsPage.js:19:26)
    at PresationsPage.<anonymous> (/Users/jp116/PRECTS/deguarding/lib/pages/PresationsPage.js:28:26)
    at Generator.next (<anonymous>)
    at /Users/jp116/PRECTS/deguarding/lib/pages/PresationsPage.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jp116/PRECTS/deguarding/lib/pages/PresationsPage.js:3:12)
    at PresationsPage.isPresationsPageLoadComplete (/Users/jp116/PRECTS/deguarding/lib/pages/PresationsPage.js:25:16)
    at Context.<anonymous> (/Users/jp116/PRECTS/deguarding/lib/tests/dsaxlogin.spec.js:67:41)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jp116/PRECTS/deguarding/lib/tests/dsaxlogin.spec.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }
Promise rejected !

{ AssertionError: Expected : Presations Page: expected false to equal true
    at PresationsPage.isPresationsPageLoadComplete.then (/Users/jp116/PRECTS/deguarding/lib/tests/dsaxlogin.spec.js:68:46)
  message: 'Expected : Presations Page: expected false to equal true',
  showDiff: true,
  actual: false,
  expected: true }
DELAY!: 2000 mS
{ TimeoutError: waiting for selector "#bibTab_TALENTREVIEW_PRES_TAB" failed: timeout 30000ms exceeded
    at new WaitTask (/Users/jp116/PRECTS/deguarding/node_modules/puppeteer/lib/DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (/Users/jp116/PRECTS/deguarding/node_modules/puppeteer/lib/DOMWorld.js:478:22)
    at DOMWorld.waitForSelector (/Users/jp116/PRECTS/deguarding/node_modules/puppeteer/lib/DOMWorld.js:432:17)
    at Frame.waitForSelector (/Users/jp116/PRECTS/deguarding/node_modules/puppeteer/lib/FrameManager.js:627:47)
    at Frame.<anonymous> (/Users/jp116/PRECTS/deguarding/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.waitForSelector (/Users/jp116/PRECTS/deguarding/node_modules/puppeteer/lib/Page.js:1095:29)
    at PresationsPage.get PresationsTab [as PresationsTab] (/Users/jp116/PRECTS/deguarding/lib/pages/PresationsPage.js:19:26)
    at PresationsPage.<anonymous> (/Users/jp116/PRECTS/deguarding/lib/pages/PresationsPage.js:28:26)
    at Generator.next (<anonymous>)
    at /Users/jp116/PRECTS/deguarding/lib/pages/PresationsPage.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jp116/PRECTS/deguarding/lib/pages/PresationsPage.js:3:12)
    at PresationsPage.isPresationsPageLoadComplete (/Users/jp116/PRECTS/deguarding/lib/pages/PresationsPage.js:25:16)
    at Context.<anonymous> (/Users/jp116/PRECTS/deguarding/lib/tests/dsaxlogin.spec.js:67:41)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jp116/PRECTS/deguarding/lib/tests/dsaxlogin.spec.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }
Promise rejected !

{ AssertionError: Expected : Presations Page: expected false to equal true
    at PresationsPage.isPresationsPageLoadComplete.then (/Users/jp116/PRECTS/deguarding/lib/tests/dsaxlogin.spec.js:68:46)
  message: 'Expected : Presations Page: expected false to equal true',
  showDiff: true,
  actual: false,
  expected: true }
    1) Presations Check

  2 passing (1m)
  1 failing

  1) dsax d80 InstanceID SS00632, Page Loads 
       Presations Check:

      AssertionError: Expected : Presations Page: expected false to equal true
      + expected - actual

      -false
      +true
      
      at PresationsPage.isPresationsPageLoadComplete.then (lib/tests/dsaxlogin.spec.js:68:46)

[mochawesome] Report JSON saved to /Users/jp116/PRECTS/deguarding/mochawesome-report/mochawesome.json

[mochawesome] Report HTML saved to /Users/jp116/PRECTS/deguarding/mochawesome-report/mochawesome.html

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:  6.2.0
npm list | grep mocha
├── @types/mocha@5.2.7
├─┬ mocha@6.2.0
├─┬ mochawesome@4.1.0
│ ├─┬ mochawesome-report-generator@4.0.1

- The output of `node --version`: v10.15.3

- Your operating system
  - name and version: mac osX : 10.14.6
  - architecture (32 or 64-bit): 64
- Your shell (e.g., bash, zsh, PowerShell, cmd): bash
- Your browser and version (if running browser tests): chrome-launcher@0.11.2 
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):
TypeScript : 3.5.3
### Additional Information
npm list | grep puppeteer
├─┬ @types/puppeteer@1.19.1
├─┬ puppeteer@1.20.0
├─┬ puppeteer-debug@1.0.1
│ └── puppeteer@1.20.0 deduped

I'm trying this 
```
it('PageLoad test', async function () {
        this.retries(1);
        homePage = await navMenu.loadHomePage();
        await homePage.isHomePageLoadComplete().then((result) => {
            expect(result).to.equal(true, 'Expected : Home Page');
        });
    });
```
though the retries(1) retries the test, the mocha json report logs the 
```
"state": null,
"speed": null,
 "pass": false,
 "fail": false,
```
as a result of which the HTML report does not show the failure.  How do I fix this ?

**Comment by juergba** [comment]
I don't see how Mocha's JSON reporter should be linked to Mocha's HTML reporter.
Please fill out the issue template completely, otherwise please close this issue, thank you.

**Comment by dcr007** [comment]
@juergba  updated with the issue template .

**Comment by juergba** [comment]
The _mochawesome_ reporter is a third party package, not Mocha core.
To find out wether it is a _mochawesome_ bug or not:
- is the report correct without `this.retries(1)`
- cut your example down to a simple test case (maybe even a sync one) with `this.retries(1)`. Is it still incorrect?

`async function (done:Mocha.Done)`: this is a overspecification, remove the `done`.
Instead of `then().catch()`, try to put your `expect()` into a `finally()`.

**Comment by juergba** [comment]
There are issues in _mochawesome_ repository about the `this.retries()` topic.

**Comment by dcr007** [comment]
ok can you please suggest me a good test reporter libs/packages I can use with Mocha core ?
