### ISSUE TITLE
spawn mocha ENOENT

### ISSUE THREAD

**Issue by JavierPons** [mochajs/mocha#4185]
Hi
I get this error output:
`{ Error: spawn mocha ENOENT at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19) at onErrorNT (internal/child_process.js:415:16) at process._tickCallback (internal/process/next_tick.js:63:19) errno: 'ENOENT', code: 'ENOENT', syscall: 'spawn mocha', path: 'mocha', spawnargs: [ './somepath/myapp/file.js' ] }
`

`[Container] 2020/02/17 08:27:56 Running command echo "Installing Node.js version 12 ..." 9 | Installing Node.js version 12 ... 10 |   11 | [Container] 2020/02/17 08:27:56 Running command n 12.13.0 12 | installed : v12.13.0 (with npm 6.12.0)`

I'm running this app inside AWS. using Codebuild, Pipeline and EC2. Any idea or some light? Using node v.12 and not resolving the problem.
The rest of features of the app that it doesn't use Mocha working well.

**Comment by juergba** [comment]
No, no idea, maybe ENOENT == no such file or directory?

Please note, this is an issue tracker, not a help forum.
You can try to get help on our Gitter chanel.
