### ISSUE TITLE
Mocha site bug: before, after hooks described incorrectly

### ISSUE THREAD

**Issue by SukantPal** [mochajs/mocha#4191]
<img width="941" alt="Screen Shot 2020-02-22 at 9 39 07 AM" src="https://user-images.githubusercontent.com/22450567/75094238-57b1b080-5557-11ea-8632-b7ef9eff5d79.png">

According to this thread https://stackoverflow.com/a/32682451/6805653, the `before` and `after` hooks run before all test in the _file_ rather than in the _block_. I believe the documentation has been incorrectly modified (as shown in the screenshot of the documentation site https://mochajs.org/#hooks).

**Comment by juergba** [comment]
No, this part of our docs is correct.
`before` and `after` hooks run before all test in the `describe` block.
You should not trust me though, just test it.

**Comment by SukantPal** [comment]
@juergba I see that. I think the documentation should be a little more elaborate - because the only difference in the two sentences is "all" vs "each". It is easy to mistake that "before all" means "before each".

**Comment by juergba** [comment]
@SukantPal thank you, we will incorporate your input at the next docs update.
