### ISSUE TITLE
Missing version dependency, mkdirp@0.5.3

### ISSUE THREAD

**Issue by joseluisvl** [mochajs/mocha#4210]
Today we have this problem when installing mocha, it seems that the mkdirp@0.5.3 is missing.

npm ERR! code ETARGET
npm ERR! notarget No matching version found for mkdirp@0.5.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'mocha'
npm ERR! notarget

Regards, Jose.

**Comment by juergba** [comment]
https://github.com/mochajs/mocha/issues/4199#issuecomment-600586478
