### ISSUE TITLE
Relaxed versions?

### ISSUE THREAD

**Issue by daveisfera** [mochajs/mocha#4212]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
Using specific versions causes users to end up with duplicate versions of modules and can leave them [exposed to security vulnerabilities](#4199)

**Describe the solution you'd like**
Please use `^` instead of specific versions

**Describe alternatives you've considered**
Using `~` would be better than a specific version

**Comment by juergba** [comment]
@daveisfera thank you for your proposition.
We are aware of this possibility, but have decided against some time ago.
We should update our dependencies more often though.

**Comment by daveisfera** [comment]
That's unfortunate. Any specific reasons why that decision was made?

**Comment by juergba** [comment]
Mocha runs in various environments as Node, modern browsers and our lovely IE11. We prefer therefore to peg our dependencies. Security incidents have been very rare in the past.

**Comment by daveisfera** [comment]
I agree that security incidents aren't a common problem, but multiple versions of a module is a common problem that causes bloat and wasted resources, so would you consider at least using `~` instead of specific versions?
