### ISSUE TITLE
No Mocha test results in VS Code Debug Mode (TypeScript, async, fast-running, mocha tests)

### ISSUE THREAD

**Issue by n8sabes** [mochajs/mocha#4213]
**Problem:** No test results from fast-running test output to integrated-console in VSCode + TypeScript.

**Workaround:** Set a breakpoint in the test, or including an `await sleep(1000)` in the `before` function.

**Environment:**
Mocha: 7.1.1
TypeScript: 3.8.3
Mac OS X: 10.15.3

--> I have not found a related issue, but please associate if one exists.

launch.json configuration:
```
        {
            "type": "node",
            "request": "launch",
            "name": "Fast Test",
            "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
            "args": [
                "-r",
                "ts-node/register",
                "--timeout",
                "999999",
                "--colors",
                "--require=.env-test.ts",
                "${workspaceFolder}/tests/code-tests/fast_test.ts",
            ],
            "console": "internalConsole",
            "internalConsoleOptions": "neverOpen",
            "protocol": "inspector"
        },
```

fast_test.ts:
```
    it('Fast Test 1', async () => {
        assert(true);
    });

    it('Fast Test 2', async () => {
        assert(true);
    });
```

**Comment by n8sabes** [comment]
This is the workaround I'm using in the interim:

```
const sleep = promisify(setTimeout);

describe(`${__filename.slice(__dirname.length + 1).replace(/\.[^/.]+$/, "")} Tests`, () => {

    let gTestStartTime = Date.now();

    it('Fast Test 1', async () => {
        assert(true);
    });

    it('Fast Test 2', async () => {
        assert(true);
    });

    after('After running tests', async () => {
        // Force a delay
        const execTime = Date.now() - gTestStartTime;
        execTime < 1000 && await sleep(1000 - execTime);
    });
});
```

**Comment by juergba** [comment]
`launch.json` is the VSCode configuration file for debugging. I don't really understand your question.
Does your test work in normal mode (without debugging)?

**Comment by n8sabes** [comment]
Hi @juergba, Upon further investigation

1. The problem **does not** occur when executing the test in the console.
2. The problem **only occurs** when running the test in debug mode w/o breakpoints and the test is fast/short-running.

As a matter of convenience in VS Code, I often hit F5 to execute the currently selected test and verify results. If the test is too short/quick, there are no results output to the integrated-console. Maybe because the test is `async`, the host context in some way is deconstructed before the output stream is received...??

Using the workaround above, it's not a show-stopper but a hack, which seems to slow the overall test allowing the integrated-console to pickup the test results output stream.

N8

**Comment by juergba** [comment]
Can you explain why you think this is a Mocha issue?
What do you expect when you start a debug session without breakpoint?
Why have you changed `internalConsoleOptions`?

**Comment by n8sabes** [comment]
@juergba, I have since opened this issue in the VS Code project as well (referenced, above). Mocha and VS Code are the two tools (together) in the toolchain that result in test output failure. I am uncertain where the failure originates.

As for your question about `internalConsoleOptions`, it was part of a mocha+vscode+typescript blog post in TypeScript debugging scenario that worked in my environment. I cannot recall the manual / automated testing situation why it was required.
