### ISSUE TITLE
 Uncaught TypeError: done is not a function

### ISSUE THREAD

**Issue by hnatashah96** [mochajs/mocha#4215]
Hi, can someone please tell me why i am getting this error message when i am trying to update and delete records in Mocha.
![image](https://user-images.githubusercontent.com/62608153/77439802-86989c00-6e0d-11ea-852c-236575695ad6.png)
![image](https://user-images.githubusercontent.com/62608153/77439823-8dbfaa00-6e0d-11ea-9083-787a4a4c2b5a.png)

My Update code is an follows:
const assert = require('assert');
const MarioChar = require ('../models/mariochar');

//describe what our test is going to do
//describe => consist all tests
describe('Updating records',function () {

  beforeEach(function (done) {
    var char;
    //need to predict what should be the test result
    //creating new instance with the Lawyer model
    char = new MarioChar({
      name: 'Mario'
    });
    //to save the instance of the object
    //save().then(function ()) => waits for the save action so to be completed. then, starts the function
    //save() => asynchronous
    char.save().then(function () {
      done();
    });
  })

  //create different test
  //it => single block which refers to the test
  //can be used to test whether a user has been successfully added to the db
  it('Updates one record from the database',function (done) {
    //findOne => used in the model itself
    MarioChar.findOneAndUpdate({name:'Mario'},{name: 'Luigi'}).then(function () {
      MarioChar.findOne({_id: char._id}).then(function (result) {
        assert(result.name === 'Luigi');
        done();
      });
    });
  });
})

**Comment by juergba** [comment]
@hnatashah96 Please note this is an issue tracker, not a help forum.
You find Mocha/mongodb samples by googling, or you can try to get support on our [gitter](https://gitter.im/mochajs/mocha?source=orgpage) channel.
Formatting your code would be nice.
