### ISSUE TITLE
🚀 Feature: Possibility to return 0 exit code when tests run successfully even with fails

### ISSUE THREAD

**Issue by ilgonmic** [mochajs/mocha#4216]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

Sometimes it is useful to separate situations when tests run successfully, and there is no infrastructure or runtime problems, and when there are some runtime problems.
Possibility to return non-zero exit code only on infrastructure or runtime problems make easier integration with different toolchain.

**Describe the solution you'd like**

Flag, something like `failOnFailingTests` like in Karma (https://github.com/karma-runner/karma/blob/master/docs/config/01-configuration-file.md#failonfailingtestsuite).
- 0 exit code when tests run successfully
- 1 exit code when something went wrong

**Describe alternatives you've considered**

Karma 
https://github.com/karma-runner/karma/blob/master/docs/config/01-configuration-file.md#failonfailingtestsuite

**Additional context**

**Comment by outsideris** [comment]
> Sometimes it is useful to separate situations when tests run successfully, and there is no infrastructure or runtime problems, and when there are some runtime problems.

I didn't understand it. Could you explain more detail for usecases.

**Comment by ilgonmic** [comment]
Using Mocha in some build tools (for example Gradle).
After Mocha successfully run, I know test status via custom loader. Then I provide test results to "parent" build system and doesn't matter on Mocha exit code. Further results will be processed, and I don't want to fail "parent" build system.
But it does matter if there is some problems with infrastructure (for example Node problem). And in this case I want to get non-zero exit code of Mocha and force to fail "parent" build system.

But for now I have to fail of "parent" build system on both cases, when tests are failed which is **valid** situation for "parent" build system, and infrastructure problem (syntax problem e.g.) which is **invalid** situation for "parent" build system.

If I ignore exit code of Mocha, there is no fail on failed tests (and it is OK) and on infrastructure problem (and it is not OK)

**Comment by ilgonmic** [comment]
@boneskull Thank you for reply.
I don't need any result as "passing", I think that in TS I incorrectly expressed the thought.
Let's imagine we have states:
- Tests passed and run successful - 0 failed tests and 0 zero code
- Some tests failed but run **successful** - some failed tests and 0 zero code
- Run **failed** - some infrastructure problems (for example don't find some critical module)

I want to get zero code only if no "infrastructure" problem. If I run `mocha <args> || true` I get zero code even in this case.

It is similar with next property in Karma
https://github.com/karma-runner/karma/blob/master/docs/config/01-configuration-file.md#failonfailingtestsuite

**Comment by JoshuaKGoldberg** [comment]
Note that this is related to, but does not intersect with #3559. #3559 is about changing what the non-zero exit code is on case of non-passing tests. This one is about switching to a zero exit code even when there are non-passing tests.

**Comment by JoshuaKGoldberg** [comment]
Published in [`mocha@10.7.0`](https://npmjs.com/package/mocha/v/10.7.0). 🚀
