### ISSUE TITLE
[Feature Request] ability to use "is" instead of "be" in .and.have.property('foo').that.be(X)

### ISSUE THREAD

**Issue by jedwards1211** [mochajs/mocha#4248]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
Not a huge deal but it's awkward that we have to use incorrect English grammar in this case.  Most significantly it's probably a bit confusing for first-timers.

**Describe the solution you'd like**
  Would be nice if we could use `.is` in the same place as `.be`: 
```js
.and.have.property('foo').that.is(X)
```

**Describe alternatives you've considered**
I suppose a plugin could support this but that doesn't seem like a good place for it.

**Comment by juergba** [comment]
`.and.have.property('foo').that.is(X)` is not a Mocha feature. Please close.

**Comment by jedwards1211** [comment]
@juergba I know, that's the feature I'm requesting

**Comment by jedwards1211** [comment]
oh argh.  Sorry, I'm confusing mocha and chai 😅
