### ISSUE TITLE
Tests and suites do not timeout when a zero timeout is changed to nonzero

### ISSUE THREAD

**Issue by fasttime** [mochajs/mocha#4254]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

When the timeout of a test or suite is set to zero and then changed again to a positive value, the test or suite does _not_ timeout as expected.

### Steps to Reproduce

```js
it.only
(
    'test',
    function (done)
    {
        this.timeout(0);
        this.timeout(10);
        setTimeout(done, 100);
    }
);
```

**Expected behavior:** [What you expect to happen]

The test above should timeout and fail.

**Actual behavior:** [What actually happens]

The test passes.

**Reproduces how often:** every time

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 7.1.2
- The output of `node --version`: 14.0.0

### Additional Information

[`_enableTimeouts`](https://github.com/mochajs/mocha/blob/master/lib/runnable.js#L86) is set to `false` on the Runnable instance when the timeout changes to 0 but never set back to `true` again.

**Comment by craigtaub** [comment]
This seems legit. Ive given this a go here https://github.com/mochajs/mocha/pull/4260
