### ISSUE TITLE
Missing callstack in error

### ISSUE THREAD

**Issue by PFight** [mochajs/mocha#4257]
In the cli.js there is such code:

```
    .fail((msg, err, yargs) => {
      debug(err);
      yargs.showHelp();
      console.error(`\n${symbols.error} ${ansi.red('ERROR:')} ${msg}`);
      process.exit(1);
    })
```
When this code handles the error it does not print error callstack. So I getting output like this:

![image](https://user-images.githubusercontent.com/198847/80517971-89e3f200-898e-11ea-9f43-4771d98aaeab.png)

Such output does not help to localize the problem. I spent hours to debug - where problem is by removing lines of code one by one.

I have some project configuration with babel, and I have no time to make minimal reproducing example, but in my project all errors in loading tests are handling with this code. It is very frustrating.

Please, change code to smth like this:
```
 console.error(`\n${symbols.error} ${ansi.red('ERROR:')} ${msg} \n${err && err.stack}`);
```

### Versions

$ mocha --version
7.1.2

$ node -v
v12.16.1

OS: Windows 8.1 x64
Shell: MinGW

**Comment by outsideris** [comment]
I don't know where `Cannot read property 'get' of undefined` comes from.
You can see call stack by setting `DEBUG` environment variable as `DEBUG=mocha:cli:cli` or `DEBUG=*`.
We don't want to show call stack to every user because it only needs to debug.
