### ISSUE TITLE
🛠️ Repo: Look at a Finite State Machine (FSM) implementation

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#4263]
we’re starting to use finite state machines in open PRs. right now there are two separate implementations. 

to be clear, we don’t need anything fancy: nested states, async transitions, etc. we’re looking to replace small collections of boolean flags a across a few classes. 

I’m interested in [@xstate/fsm](https://github.com/davidkpiano/xstate/blob/master/packages/xstate-fsm/README.md) since it’s minimal, but it’s likely we’ll need to transpile down to ES5 unless it ships a transpiled distfile.

Mocha could roll its own to be used across the codebase, but that puts the responsibility of testing it thoroughly on Mocha, which is unappealing if a well-tested dep is available. that said I think we can get away with something very tiny—and maybe it makes more sense to start with this and pull in a dep later if it becomes a burden. 

the tradeoff of course would be adding a dep and everything that goes with it. 

interested in thoughts of @mochajs/core

**Comment by Munter** [comment]
I'm still hoping to find time to continue work on the transpilation step soon. If we get that, pulling in fsm would not be a problem.

I agree that we should rather use a well tested one than roll our own

**Comment by JoshuaKGoldberg** [comment]
As much as I like XState, per #5027 we're not planning on significantly changing anything soon. If it organically comes up that we really want to take on this big overhaul we can always reopen.
