### ISSUE TITLE
AssertionError causing test to fail with timeout

### ISSUE THREAD

**Issue by georgeben** [mochajs/mocha#4265]
Hey, I don't understand what's going on with my code. I am writing a test for an asynchronous function which expects a callback. 
The function looks like this:
```js
const sendSmsForCompletingApplication = (arg, txn, data, callback) => {
    const { application } = data;

    let application_id;
    if (arg.user_role) {
        application_id = application.application_id;
    } else {
        application_id = application.id;
    }
    // Making a db query
    db.any(query.getApplicationData, [ application_id ])
        .then((result) => {
            if (result.length > 0) {
                const statuses = result.map((item) => item.status);

                const { user, lease } = data;
                const { phone_number } = user;
                const { id: lease_id } = lease;

                const message = `Text message`;

                sendSms(message, phone_number)
                    .then(() => {
                        return callback(null, arg, txn, data); 
                    })
                    .catch((e) => {
                        return callback(null, arg, txn, data); 
                    });
            } else {
                return callback(null, arg, txn, data);
            }
        })
        .catch((e) => {
            return callback(null, arg, txn, data);
        });
}
```
This is how my test suite looks like:
```js
describe('sendSmsForCompletingApplication', () => {
        const data = {
            application: {
                id: 'myid'
            }
        };
        const arg = {
            user_role: 'user'
        };

        it.only('should resolve correctly', (done) => {
              sendSmsForCompletingLease(arg, '', data, (err, rarg, rtxn, rdata) => {
              console.log(`Error: ${err}`);
              console.log('Args', rarg);
              // err should be null, however I want to see that the tests fails by making a wrong assertion. I am asseting that the error should be hello
              expect(err).to.equal('hello');
             // I am calling the done() callback here
              done();
            });
        });
    });
```
When I run my test, the function executes correctly, when it reaches the line where I made the assertion ` expect(err).to.equal('hello');`. It throws an AssertionError as expected. The assertion error is written below:
```js
AssertionError: expected null to equal 'hello'
    at /Users/georgeben/Dev/***/****/test/unit/payment/utils/sms.spec.js:41:30
```
However, after the AssertionError is thrown, `done()` is never called. I don't know why. It doesn't make sense, because I have written tests for other asynchronous functions this way and it works correctly. Please can you tell me what I'm missing? Thank you!

**Comment by juergba** [comment]
@georgeben please note, this is an issue tracker, not a help forum. For questions you can try to get support via [gitter](https://gitter.im/mochajs/mocha). What you have already done, and received a valid answer.

If your assertion fails, it throws an uncaught exception and `done()` will not be called. It's not a good practice to throw uncaught exceptions in **async tests** and leave the exception handling to Mocha. Mocha will try, but it's just on best effort basis.

**Comment by georgeben** [comment]
Thanks @juergba , so what I should have done is to wrap my assertion in a try-catch block?
