### ISSUE TITLE
"hook" event is triggered after "test" event

### ISSUE THREAD

**Issue by sskorol** [mochajs/mocha#4266]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

When we create a custom reporter with common events' handlers as described [here](https://github.com/mochajs/mocha/wiki/Third-party-reporters), `hook` is always triggered after `test` event, that seems incorrect.

### Steps to Reproduce

See a min [repo](https://github.com/sskorol/mocha-reporter-events) to reproduce the issue.

**Expected behavior:** `hook` event is triggered before `test` event.

**Actual behavior:** `hook` event is triggered after `test` event.

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 7.1.2
- The output of `node --version`: v13.13.0
- Your operating system
  - name and version: macOS Catalina, 10.15.1
  - architecture (32 or 64-bit): 64-bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh

**Comment by craigtaub** [comment]
Yes I see what you mean. 
The runner fires `EVENT_TEST_BEGIN` followed by the beforeEach hooks and the test. After that `EVENT_TEST_END` fires followed by the afterEach hooks. 
From this it does seem that "test function execution" includes beforeEach but not afterEach, which seems confusing.
It appears only the "list" reporter listens for `EVENT_TEST_BEGIN` event so it is possible this could be a bug which has flown under the radar. I am really unsure here tho.
@mochajs/core any thoughts on this?

**Comment by juergba** [comment]
This behaviour is not a bug, it was designed like this back in ancient times. We have integration tests for checking the event order, and there already are similar issues.

This is not a trivial topic, there should be good reasons for a change. It affects at least:
- the failing hook pattern (test is skipped upon failing `beforeEach`)
- conditional `this.skip()` in `beforeEach`
- when a test passes and then its `afterEach` fails, Mocha does not fail the test retrospectively.

**Comment by craigtaub** [comment]
Thanks.

> I need beforeEach hook triggered before test, and not after  

@sskorol unfortunately this is an outstanding nontrivial bug which has not been resolved yet. Perhaps there is an alternative approach you can take?

**Comment by sskorol** [comment]
@craigtaub @juergba the main problem I see here is that such a design flaw on the core level forces API users creating workarounds for all potential child reporters. This issue won't be annoying unless you need to collect some internal metadata from within the hook's body and physically save or send it somewhere in real-time. In this case, the wrong execution order might affect the child reporter's architecture or cause misinterpreting results by the receiver side. Of course, workarounds are always possible. But I would be greatly appreciated if such issues are considered for fixing on the core level.

**Comment by JoshuaKGoldberg** [comment]
Per #5027, we're not looking to make any major changes to Mocha at this point.
