### ISSUE TITLE
package-lock/package are out of sync

### ISSUE THREAD

**Issue by 43081j** [mochajs/mocha#4273]
You have published version 7.1.2 but your package-lock and package manifests are still at 7.1.0.

What this also means is you have dependencies which do not exist in your github repo (i.e. in your manifest files) but do exist in the published mocha package.

Is this because you are publishing builds manually? if so, the lock file must've updated when whoever published it, published it, so maybe it just didn't get committed?

**Comment by juergba** [comment]
We have various branches in our repo. The `master` branch normally does not correspond to the published versions since it contains PR's which haven't been released yet.
For v7.1.2 the release branch is `release/v7.1.x` which exactly mirrors the published version. Btw the lock file is not published.
