### ISSUE TITLE
ESM considerations for ts-node and other require.extensions hooks

### ISSUE THREAD

**Issue by cspotcode** [mochajs/mocha#4274]
I want to share a couple things I've hit while adding ESM support to ts-node, because I think it affects design decisions for mocha's ESM support.

### `require.extensions` need to add hacks to classify files as either CJS or ESM

@emma-borhanian hit an issue with babel's `require.extensions` hook, which also happens to ts-node
https://github.com/mochajs/mocha/pull/4038#discussion_r380195672

I've shared the fix I'm going to add to ts-node; babel could do something similar.
https://github.com/nodejs/modules/issues/351#issuecomment-625992425

With this fix we will throw the same errors as node when you try to `require()` an ESM file.

### Mocha needs to consult `require.extensions` to properly load non-standard file extensions

In mocha you have [a comment](https://github.com/mochajs/mocha/blob/master/lib/esm-utils.js#L10-L13) about using `import()` for all files in the future, letting it classify files as CJS or ESM.  Unfortunately, I believe this will fail to resolve non-standard file extensions such as `.ts`.

In ts-node we have implemented an ESM loader that *does* understand `.ts`, `.tsx`, and `.jsx`.  However, this requires users to invoke node or mocha like this:

```
node --loader ts-node/esm.mjs ./node_modules/mocha/bin/mocha --extension ts
```

Users who are not using ESM will not install this loader, so the ESM resolver will not be able to resolve nor classify `.ts`, `.tsx`, or `.jsx` files.  For this, `mocha` must continue using `require` to locate and attempt loading the file.  I believe that even `import(require.resolve('./ts-file.ts'))` will fail to classify the file as CJS or ESM if our custom ESM hook is not installed.

See also: https://github.com/nodejs/node/issues/33226
It's *possible* that node's built-in loader will be changed to classify unrecognized extensions based on package.json "type" field, but I'm not sure.

---

I hope this information is helpful!

**Comment by boneskull** [comment]
Thanks!

I'll admit I don't have enough experience with TS, `ts-node`, nor loaders to understand what, if anything, is actionable here.  

I think we'll want to add some tests for whatever we do, though.  There's precedent for this in our test suites, so we can pull in `ts-node` or whatever is necessary to test ... whatever it is we need to test, exactly.

**Comment by cspotcode** [comment]
The only actionable thing is:

* don't use `import()` to load all test files.  It will fail to discover files with non-standard file extensions.  The only action, if any, is to update the code comments to explain why `import()` fails to consider `require.extensions`

Also, I mentioned a hack we were going to use to classify files as either CJS or ESM.  Turns out that hack won't work reliably.  Instead, we've had to copy-paste some of node's source code where it discovers the nearest package.json and checks for a "type" field.
https://github.com/TypeStrong/ts-node/blob/7a1a55bc69bc35b665795c8a49b20131a3cb5fc0/dist-raw/node-cjs-loader-utils.js#L10-L20
Every time our require hook is invoked, we call `assertScriptCanLoadAsCJSImpl`.  If appropriate, it throws a ERR_REQUIRE_ESM lookalike error.  We do this so that you can still detect it https://github.com/mochajs/mocha/blob/57be4558eac737efae9ea67bee5de6e9f4fd6b0c/lib/esm-utils.js#L17
