### ISSUE TITLE
Mocha error in terminal while running Ethereum Smart Contracts tests.

### ISSUE THREAD

**Issue by ethernal12** [mochajs/mocha#4279]
Hello ,
I˙m having issues with running some ethereum smart contracts tests.

My Inbox.test.js: 
-------------------------------------------------------------------------------------->
```
const assert = require("assert");
const ganache = require("ganache-cli");
const Web3 = require("web3");
const web3 = new Web3(ganache.provider());
const {interface, bytecode} = require("../compile");

let accounts;
let inbox;

beforeEach(async ()=> {

//get a a list of all accounts

	accounts = await  web3.eth.getAccounts();

// Use one of those accounts to deploy the contract

	inbox =  await new   web3.eth.Contract(JSON.parse(interface))
	.deploy({ data: bytecode, arguments: ["Hi there!"] })
	.send({ from: accounts[0], gas: "1000000" });

});

describe ("Inboxxx", () => {

	it("this deploys a contract", () => {

		console.log(inbox);
	});
});
```
------------------------------------------------------------------------------------------->
My package.json:

```

{
  "name": "inbox",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "mocha"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ganache-cli": "^6.0.3",
    "mocha": "^4.0.1",
    "save": "^2.4.0",
    "solc": "^0.4.19",
    "web3": "^1.0.0-beta.26"
  }
}
```
My compile.js 
------------------------------------------------------------------------------------------------>
```
const path = require("path");
const fs = require("fs");
const solc = require("solc")


const inboxPath = path.resolve(__dirname, "contracts", "Inbox.sol");
const source = fs.readFileSync(inboxPath, "utf8");


module.exports = solc.compile(source,1).contracts[":Inbox"];
```
------------------------------------------------------------------------------------------------>
After i run:  npm run  test // in my cmd I get the output

![cmd-mocha error](https://user-images.githubusercontent.com/31479093/81540976-bb879080-9372-11ea-99fe-ad827b428e62.jpg)

------------------------------------------------------------------------------------------------>
and here is my debug.log file 

![debug lof file](https://user-images.githubusercontent.com/31479093/81541321-36e94200-9373-11ea-910f-46730aa5d41f.jpg)

---------------------------------------------------------------------------------------------->
I tried clearing my npm cache, unistalling mocha npm and solc but with no luck, the error presists.
 
I˙m doing this solidity ethereum course od Udemy but I dont get any answers from their side so I would really appriciate some help here... 
Tnx

**Comment by Munter** [comment]
This error doesn't come from mocha. If I recall correctly I've seen that error from the `async` library a bunch of times

**Comment by ethernal12** [comment]
Oh, hmm so what can I try to get rid of this error ? 

Tnx
