### ISSUE TITLE
📝 Docs: Document that hooks support the 'done' parameter

### ISSUE THREAD

**Issue by wheresrhys** [mochajs/mocha#4280]
In the fetch-mock library I have always bound the `reset`  method to the module in order that it can be used unwrapped in afterEach blocks: `afterEach(fetchMock.restore)`

I'm at the point where I need to [allow config to be passed in](https://github.com/wheresrhys/fetch-mock/pull/553), which now means the function length is `1`.

I've been unable to find the exact place in mocha's hooks codebase where it happens, but experimenting with various things leads me to believe that mocha creates its expectation that the `done()` method should be called based on the function length, so now that my function is of length 1, the afterEach hook times out.

Would it be possible to provide a mechanism to allow hooks to opt out of this behaviour e.g. by adding a property `_mochaAsyncCallbackIgnore` to the function?

**Comment by wheresrhys** [comment]
I managed to find a workaround, and fortunately my tests, by complete chance, captured what would have been a significant production bug. But I can't honestly think of anything you could have done to make me aware at the right time that function length matters, although I do note that [it isn't documented](https://mochajs.org/#asynchronous-hooks), so adding a note there would be good.

**Comment by Munter** [comment]
The hooks follow the same pattern as test callbacks. If the arity is above 0 the first argument is assumed to be an async callback function usually named 'done'. If this function is supplied, tests won't finish before it has been called.

It's a relic from before promises and native async behavior, and it's not something we can easily get rid of.

A pull request for clearer documentation would be much appreciated though.
