### ISSUE TITLE
 "before all" hook issue undefined value

### ISSUE THREAD

**Issue by paulovich10** [mochajs/mocha#4283]
I'm new at mocha and unit testing, and I'm dealing with some issues as I get this error. I have tried to include a setTimeout, and checked all the issues possible but none of what I'm trying seems to work.

  1) "before all" hook

  259 passing (32s)
  10 pending
  1 failing

     Uncaught TypeError: Cannot read property '_id' of undefined
      at chai_1.default.request.get.set.end (dist/test/deviceTests/createDevicesTests.js:82:93)

It's quite strange that trying to pass this test, with describe.only, it passes with no issues, but when I remove the .only and try to pass the complete test set, it fails.

I have a connection to a "volatile" ddbb that, deletes all the documents and creates them to pass the running test as follows:

import chai from "chai";
import chaiHttp from "chai-http";
const should = chai.should();
chai.use(chaiHttp);
import jwt from "jsonwebtoken";
import config from "config";
import User from "../../src/models/userModel";
import Permission from "../../src/models/permissionModel";
import ApiToken from "../../src/models/apiTokens";

export class CreateDevicesTests {
    private accessToken: string = "";
    private accessTokenWoutPermissions: string = "";
    private buildId: string = "";
    public runTests(): void {
        describe("Test to create new devices", (): any => {
            before((done): any=>{
                ApiToken.deleteMany({}).exec().then(()=>{
                    User.deleteMany({}).exec().then(()=>{
                        Permission.deleteMany({}).exec().then(()=>{
                            new User({
                                companyId: "5d1b19917ad7740012c53609",
                                email: "marvin@company.com",
                                passwd: "1234",
                                fullName: "Marvin Martian",
                                avatar: "",
                                location: "Mars",
                                phone: "+56486797985632135487687",
                                position: "Imperial destructor"
                            }).save().then((doc) => {
                                new Permission({
                                    userId: doc._id,
                                    name: doc.fullName,
                                    permissions: {
                                        userMgmt: true,
                                        deplyMgmt: true,
                                        deviceMgmt: true,
                                        deplyList: new Array()
                                    }
                                }).save().then(()=>{
                                    console.log('doc1', doc)
                                    this.accessToken = jwt.sign({ userId: doc._id, companyId: doc.companyId }, config.get("server.secret"), { expiresIn: 86400 });
                                    new User({
                                        companyId: "5d1b19917ad7740012c53609",
                                        email: "tramos@company.com",
                                        passwd: "1234",
                                        fullName: "Terrance Ramos",
                                        avatar: "",
                                        location: "Rome",
                                        phone: "+39 06 69865421",
                                        position: "Regular worker"
                                    }).save().then((doc) => {
                                        this.accessTokenWoutPermissions = jwt.sign({ userId: doc._id, companyId: doc.companyId }, config.get("server.secret"), { expiresIn: 86400 });
                                        new Permission({
                                            userId: doc._id,
                                            name: doc.fullName,
                                            permissions: {
                                                userMgmt: false,
                                                deplyMgmt: false,
                                                deviceMgmt: false,
                                                deplyList: new Array()
                                            }
                                        }).save().then(() =>{
                                            console.log('doc2',doc._id)
                                            new ApiToken({
                                                companyId: "5d1b19917ad7740012c53609",
                                                apiToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55SWQiOiI1ZDFiMTk5MTdhZDc3NDAwMTJjNTM2MDkiLCJpc0JCUkEiOnRydWUsImlhdCI6MTU2MjA1NzEwNX0.nCYqG2rCsBnChT-ZwBxggSay-rLNK41aGEoZKaX2e5I",
                                                name: "Barbara Admin"
                                            }).save().then(()=>{
                                                chai.request("http://localhost:5000")
                                                    .get("/images")
                                                    .set("authorization", this.accessToken.toString())
                                                    .end((err: any, res: any): any => {
                                                        if (!err) {
                                                            res.should.have.status(200);
                                                            this.buildId = res.body.response[0]._id;
                                                            done();
                                                        }
                                                    });
                                            });
                                        });
                                    });
                                });
                            });
                        });
                    });
                });
            });
            
            it("it should return a 400 no authorization header is not provided", (done): any => {
                chai.request("http://localhost:5000")
                    .post("/devices")
                    .end((err: any, res: any): any => {
                        if (!err) {
                            res.should.have.status(400);
                            res.body.response.errorCode.should.be.equal("ERRUMP04");
                            done();
                        }
                    });
            });
            it("it should return a 403 when the token is incorrect", (done): any => {
                chai.request("http://localhost:5000")
                    .post("/devices")
                    .set("authorization", jwt.sign({ userId: "123", companyId: "123" }, config.get("server.secret"), { expiresIn: 86400 }).toString())
                    .end((err: any, res: any): any => {
                        if (!err) {
                            res.should.have.status(403);
                            done();
                        }
                    });
            });

The funny thing is that, when making a console.log of the doc, it's there but I have no idea why it's getting undefined instead:

   Device routes tests
      create devices route tests
        Test to create new devices
doc1 { _id: 5eba5aeaeeb50606019e3c5a,
  companyId: '5d1b19917ad7740012c53609',
  email: 'marvin@company.com',
  passwd: '1234',
  fullName: 'Marvin Martian',
  avatar: '',
  location: 'Mars',
  phone: '+56486797985632135487687',
  position: 'Imperial destructor',
  __v: 0 }
doc2 5eba5aeaeeb50606019e3c5c
          1) "before all" hook

  259 passing (31s)
  10 pending
  1 failing

  1) Barbara Panel Backend Test Suite
       Device routes tests
         create devices route tests
           Test to create new devices
             "before all" hook:
     Uncaught TypeError: Cannot read property '_id' of undefined
      at chai_1.default.request.get.set.end (dist/test/deviceTests/createDevicesTests.js:82:93)

Could anybody help me?

**Comment by Munter** [comment]
From your error it seems like you have a problem in your own code to set up your tests. Please use the gitter chat for support questions as we try to keep GitHub issues focused on project related matters
