### ISSUE TITLE
How can I test console.log using mocha chai?

### ISSUE THREAD

**Issue by 95Rawan** [mochajs/mocha#4284]
I have this code and I want to make a test for the `console.log` piece, can you help?
```
let myAge = 22;
console.log(myAge);
```

I want to test it in two ways, the result showing in the terminal when I run the file and the testing it without me running the file and having a result in the terminal, is it possible?

**Comment by Munter** [comment]
Please use the gitter chat for questions on how to test. We'd like to keep GitHub issues focused on project development

**Comment by 95Rawan** [comment]
Can you tell me how to get there, please?

**Comment by Munter** [comment]
https://gitter.im/mochajs/mocha

**Comment by 95Rawan** [comment]
Thanks a lot, I appreciate it

**Comment by PaulPCIO** [comment]
Is there a way to search a question in gitter chat? Because I have the exact same question and it seems a bit redundant for everyone person with the same question having to ask it again and again in the gitter chat.

Github is still be the best place for Q&A
