### ISSUE TITLE
Using mocha programmatically, update supported options

### ISSUE THREAD

**Issue by Floriferous** [mochajs/mocha#4285]
The documentation for `Using Mocha programmatically` lists the options that are supported when using mocha. However it seems like it is not up to date with the actual mocha runner. I'm not sure if this is because it is outdated or because this is intended?

* https://github.com/mochajs/mocha/blob/master/lib/mocha.js
* https://github.com/mochajs/mocha/wiki/Using-Mocha-programmatically

**Comment by juergba** [comment]
@Floriferous thank your for issue.
You are right, this Wiki page is outdated. I updated it by adding a link to our [API documentation](https://mochajs.org/api/mocha).
