### ISSUE TITLE
Mocha.prototype.run API is weird and inconsistent

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#4286]
Currently, `Mocha.prototype.run` looks like this:

```js
Mocha.prototype.run = function(fn) {
  this._guardRunningStateTransition(); // can throw

  // ... setup runner, etc ...

  function done(failures) {
    // some stuff
    fn = fn || utils.noop;
    if (reporter.done) {
      reporter.done(failures, fn);
    } else {
      fn(failures);
    }
  }

  return runner.run(done);
}
```

Note:

1. This function can throw if the `Mocha` instance is not in the correct state.
1. The callback parameter, `fn`, is _optional_.
1. `Runner#run` returns a `Runner` instance.
1. `Runner#run` will call its callback, `done`, asynchronously.
1. `fn` will then be called (asynchronously) with a single numeric argument, `failures`.

This is... not like any API I'm familiar with.  It is **awkward and unfriendly**.

If we can adopt an conventional style for this API, I think consumers of `Mocha.prototype.run` (consumers running Mocha programmatically; third-party libs built on Mocha, etc.) will have an easier time of it--especially now that we're potentially throwing an exception synchronously.

Now, we can't just go and break this function w/o befouling presumably a lot of tooling.

We have, as I see it, two options:

1.  Make a best-effort guess at whether the consumer expects _error-first_ ("nodeback") style.  This can naively be done by inspecting the `length` prop of `fn`.  If the value is `2`, we can call it with an `Error` (if any), and `failures` as the second argument.  This will not work if `fn` doesn't care about `failures` (e.g., `fn` is `(err) => {}` instead of `(err, failures) => {}`).
1. Create a new, error-first-style function with the desired API, and soft-deprecate this one.  This _cannot_ be a `Promise`-returning function; it needs to return the `Runner` instance (we use it in the "watch" mode implementation). It _could_ return an object of type `{{Runner, Promise<number>}}`.

If we do go and make a new function, we should re-evaluate whether calling the callback (or resolving) with a _number_ (`failures`) is the best we can do.  We could return a big-ass object full of information about the run instead.  If we _also_ made a reporter _optional_, we could enable some cool stuff to be more easily built, e.g.:

```js
const Mocha = require('mocha');

async function main() {
  const mocha = new Mocha();

  someFiles.forEach(file => {
    mocha.addFile(file);
  });

  const result = await (mocha.run().result);

  return result.tests.filter(test => test.status === 'failed');
}
```

**Comment by boneskull** [comment]
on second thought, we could also instantiate the `runner` in the `Mocha` constructor (instead of within `Mocha.prototype.run` itself), and consumers could just reference it, instead of needing to return `{{Runner, Promise<whatever>}}`.

**Comment by JoshuaKGoldberg** [comment]
Per #5027, we're not planning on tackling any big shakeups like this one. 😞
