### ISSUE TITLE
Mocha with Playwright and parallel test execution

### ISSUE THREAD

**Issue by MihailPertsev** [mochajs/mocha#4296]
### Prerequisites

- [x ] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description
I do browser automation, mostly I fill out forms with some data. I decided to use mocha for some assertions and found such an interesting feature. I can run my iterations of browser automation almost in parallel, but the tests fail.

### Steps to Reproduce
1) Install playwright  https://www.npmjs.com/package/playwright
npm i playwright

2) Create new test with this code

```js
//code starts here
const { chromium } = require("playwright");

describe("should run in parallel", async function () {
  for (let i = 1; i <= 5; i++) {
    it("I want execute 5 browsers at the same tiem and I want my tests to pass", async function () {
      // this.timeout(30000);
      const browser = await chromium.launch({ headless: false, slowMo: 500 });

      const context = await browser.newContext({ viewport: null });

      const page = await context.newPage();

      await page.goto("https://www.google.com");

      await page.waitForLoadState("load");
      await page.type('[type="text"]', `it ${i}`);
    });
  }
});
//code ends here
```

3) Run the test

4) You will see 5 chromium instances that will run almost in parallel , _but all tests fail_. If you check the browsers, they will have 'it' and number of the test inside google search input. That means that the code works.

5) Now uncomment this line 
`this.timeout(30000)`

6) Run the test again

7) You will see the same result (5 browsers instances) and all tests pass. **But it will be five times slower**.

**Expected behavior:** I want to run my automation as  fast as possible. Which means that I want parallel execution of main loop, because this can speed up my tasks **A LOT**  ,but I also want my tests to pass. 

**Actual behavior:** I need to choose between parallel execution and "passing" the tests.

**Reproduces how often:** Every single time.

**Comment by boneskull** [comment]
1. `describe` cannot be asynchronous.  I don't think this is necessarily the problem, though.
1. Mocha does not execute tests in parallel.  One test must finish before the next begins.  Mocha will [soon have the ability to run individual test files in parallel](mochajs/mocha#4245), however.  
1. Run `console.log(this.timeout())` before setting the value to `30000`.  What is the result?  Are you decreasing the timeout?
1. You have not shown how the tests fail (I don't have time to create a test repo right now).  Please paste your Mocha output.

**Comment by MihailPertsev** [comment]
1. Yes, describe is not the case here.
2. As I said it **almost** parallel execution (there is 2 seconds delay, because of 2 seconds default timeout). You need to see it yourself. I want to be crystal clear here, _I like this behaviour_, but I also want my tests to pass.
3. 2000
4. Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

This kind of error in step 4.

No errors at all in step 7.

**Comment by MihailPertsev** [comment]
Any update?

**Comment by MihailPertsev** [comment]
> 
> 
> Can't really help you without an example.

What are you talking about? I made a steps to reproduce. This will work 10/10 times.

**Comment by MihailPertsev** [comment]
Any update?

**Comment by vania-pooh** [comment]
@MihailPertsev JFYI we added remote parallel Playwright test execution support on the remote side in recent release of [Moon](https://aerokube.com/moon/). It was initially running Selenium tests in parallel in Kubernetes cluster, but is now able to do the same with Playwright. Documentation about it is here: https://aerokube.com/moon/latest/#_using_playwright It is a free solution up to 4 parallel browsers, but requires a license if you need more.
