### ISSUE TITLE
Please don't prevent ES modules from being used on older Node.js versions

### ISSUE THREAD

**Issue by snoack** [mochajs/mocha#4297]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
We still support Node.js 10.19.0 and would like to use ES modules. But Mocha refuses to use `import()` on versions older than Node.js 12.11. However, if I relax [that check](https://github.com/mochajs/mocha/blob/cb5eb8ed42abfd0d63c5013353843f1208ff6582/lib/utils.js#L820-L822), Mocha just works fine with ES modules on Node.js 10.19.0 (when using the `--experimental-modules` flag).

**Describe the solution you'd like**
It would be great if the version check could be relaxed so that ES modules can be used on Node 10.19.

Or maybe that version check could be removed altogether. After all is `import()` [only used](https://github.com/mochajs/mocha/blob/cb5eb8ed42abfd0d63c5013353843f1208ff6582/lib/esm-utils.js#L7-L22) if the file extension is `.mjs` or if `require()` fails anyway.

**Comment by boneskull** [comment]
I'm calling this a bug.  Because pre-v12.11.0, Node.js' implementation had some differences, so it's more of a "use at your own risk" thing.  @giltayar are you able to explain and/or address this?

**Comment by snoack** [comment]
FWIW, I filed this as a feature request rather than as a bug since it works [as documented](https://mochajs.org/#nodejs-native-esm-support). Still it would be nice to lift this limitation. Removing the version check and updating the documentation to say "use at your won risk on versions of Node.js before X.X" sounds like a great idea.

**Comment by giltayar** [comment]
From what I remember, Node v10 ESM support is the "old support" (before the big changes that made ESM what it is today (e.g. before "type": "module")). So I didn't even try to see if it works.

@boneskull, if you think it's important, I can do a PR to lift that restriction, see that it works, and add a "try at your own risk" note in the docs, as @snoack suggested.

But @snoack, be aware that ESM in Node v12-14 is not compatible with ESM in Node v10, and that all ES modules in NPM currently assume Node v13 and above, and assume that they have things like "type": "module", conditional exports, and others. I would **strongly** advise to wait till you work on Node v13-14 till you move to ESM. Another problem with ESM in Node v10, is that it can _only_ work with `.mjs` extension, and I have found that lots of tools don't support `.mjs` well, and so most of my ESM packages use `type: module` in their `package.json` to enable `.js` ESM files.

**Comment by snoack** [comment]
For reference, [this](https://gitlab.com/eyeo/adblockplus/adblockpluschrome/-/merge_requests/266) is what I am doing. I even found a [workaround](https://gitlab.com/eyeo/adblockplus/adblockpluschrome/-/commit/88de10b78e8b95a5f78ff5c4c4c2ac160edc2a1c#766f9831ff5897c0f2ddc3d968bbb3e87d7021b8_45_23) to bypass your version check without patching Mocha. Anyway, I tested that code on Node.js 10.19.0, 10.20.1, 12.16.2  and 13.13.0 with the same result.

Maybe there are some edge cases that are not supported on Node.js 10.x, but as far as Mocha is interacting with ESM, as well as any use case I could come up with in our own code (not including conditional static imports), everything works just fine across these versions.

Finally, in case you wonder why Node.js 10.x matters, it's the version that come with most Linux distributions, and it perfectly does the job for what we need, i.e. build and development tooling. I rather don't increase the burden for our developers and contributors by requiring them to install software outside of their package manger if not absolutely necessary.

**Comment by giltayar** [comment]
@snoack How can I say no to somebody that wants to use ESM?  😀

Here you go: https://github.com/mochajs/mocha/pull/4299

Now it's up to the the maintainers to decide if they want unofficial support for ESM on Node v10. If they do, they can accept the PR that relaxes the check and enables Mocha ESM support on Node v10.

**Comment by snoack** [comment]
For reference, [this is how I ended up detecting ESM support in Gulp](https://github.com/gulpjs/gulp-cli/commit/15d064867185b27a7de9bf62e3aecf8e7e2e22e0#diff-40cd6517471ede0f4f676483c49e4f76R5-R10). No hard-coded versions, but feature detection.
