### ISSUE TITLE
Require 'flag' for JS api

### ISSUE THREAD

**Issue by Rauno56** [mochajs/mocha#430]
As far as I know there's no way to add files to require for suites using JS API. If there is, please educate me.

I would really like to help with that but it feels a bit too complex for me to get my hands dirty. If here's anyone who could explain me how it is working for cli, I would appriciate it. `require()` seems to be modded to able it to usage so the exports of a module would go global. Like here:
```javascript
module.paths.push(cwd, join(cwd, 'node_modules'));

program.on('require', function(mod){
  var abs = path.existsSync(mod)
    || path.existsSync(mod + '.js');

  if (abs) mod = join(cwd, mod);
  require(mod);
});
```
Any comments are welcome.

**Comment by danielstjules** [comment]
Closing as `Mocha.prototype.addFile` allows you to load additional files.
