### ISSUE TITLE
add netlify logo to site

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#4325]
We should put it at the bottom with Matomo and OJSF.

This is a pre-requisite to getting free service from Netlify.  After this is up, there's a form I'll fill out.

cc @Munter

**Comment by Munter** [comment]
Did they mention which one, or is it just at our discretion? https://www.netlify.com/press/#logos

We already have this one in the footer, which would probably look a but out of place next to the other ones:

![image](https://user-images.githubusercontent.com/331790/84365515-dd726e00-abd1-11ea-9fe2-00bdf5832644.png)

**Comment by boneskull** [comment]
duh, forgot about that one.
