### ISSUE TITLE
remove "unit tests in serial mode" job

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#4326]
This is a continuation of #4319. There's a job in `.travis.yml` that should be removed, since unit tests get run in serial mode by default again.

**Comment by gerardolgvr** [comment]
Hello @boneskull !  The job that you are talking is this?

- script: MOCHA_PARALLEL=0 npm start test.node.unit
   name: 'Latest Node.js (unit tests in serial mode)'

if not can you give me a hint? I would like to help :)

**Comment by Devjeel** [comment]
@boneskull Please check fix to this issue here : #4342

**Comment by juergba** [comment]
fixed by #4342
