### ISSUE TITLE
🚀 Feature: Support setting options via environment vars

### ISSUE THREAD

**Issue by jedwards1211** [mochajs/mocha#4330]
As discussed in #4232, it can be difficult to pass mocha command-line options through `npm run` scripts.  As @boneskull said:

> yargs has a feature that supports setting options via an environment variable; we should probably take advantage of that at some point. Might even be an issue for it already.

I didn't see any open issues for this so figured I would open one.

**Comment by boneskull** [comment]
sorry, butt-closed this one

yargs has support for this via `.env()` which we _should_ be able to leverage.

**Comment by jedwards1211** [comment]
From reading [the `yargs` docs](https://yargs.js.org/docs/#api-envprefix) seems like `.env('MOCHA')` should be sufficient, I'll open a PR soon

**Comment by boneskull** [comment]
in my experience, it's never that easy, but I wish you luck regardless 😅

**Comment by jedwards1211** [comment]
*You know*, this just makes me wish yargs itself would accept an environment variable that's equivalent to `.env('MOCHA')` so I could do this kind of thing with any command build with yargs

**Comment by icholy** [comment]
https://github.com/mochajs/mocha/pull/4835

**Comment by JoshuaKGoldberg** [comment]
#4835 was released in [`mocha@10.5.0`](https://www.npmjs.com/package/mocha/v/10.5.0). 🚀
