### ISSUE TITLE
Medium vulnerability | yargs-unparser -> lodash@4.17.15

### ISSUE THREAD

**Issue by martinoppitz** [mochajs/mocha#4332]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

The current mocha version contains a high vulnerability. That is a blocker for our CI/CD pipelines.

Vulnerability in lodash found. Lodash maintainer do nothing since more then 7 month!

Lodash shoud be removed from mocha! Issue ticket opened: https://github.com/yargs/yargs-unparser/issues/54 - we will see if a new npm package will be released.
- https://www.npmjs.com/package/yargs-unparser

Topic lodash is dead?!

https://github.com/lodash/lodash/issues/4809
https://github.com/lodash/lodash/pull/4745
... see issue and pr's in github

### Steps to Reproduce

Findings: https://snyk.io/test/npm/mocha?tab=issues

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
- The output of `node --version`:
- Your operating system
  - name and version:
  - architecture (32 or 64-bit):
- Your shell (e.g., bash, zsh, PowerShell, cmd):
- Your browser and version (if running browser tests):
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):

**Comment by andresvelezperez** [comment]
lodash@4.17.15
Prototype Pollution
Affecting lodash package, ALL versions

The function zipObjectDeep can be tricked into adding or modifying properties of the Object prototype. These properties will be present on all objects.

Report:
[https://snyk.io/vuln/SNYK-JS-LODASH-567746](https://snyk.io/vuln/SNYK-JS-LODASH-567746)
GitHub PR
[https://github.com/lodash/lodash/pull/4759](https://github.com/lodash/lodash/pull/4759)

**Comment by martinoppitz** [comment]
@andresvelezperez but nobody fix that . And nobody merge the pr

**Comment by martinoppitz** [comment]
It is possible to remove yargs-unparser.

I dont Knie, how publish a new yargs-unparser package?

**Comment by boneskull** [comment]
1. We can't trivially remove `yargs-unparser`.
1. `zipObjectDeep`, where the Lodash vulnerability lies, is not used in `yargs-unparser`
1. Therefore `yargs-unparser` is not vulnerable and this is a false positive.

This will get addressed if/when Lodash merges the PR, `yargs-unparser` updates, and Mocha updates to the latest `yargs-unparser`.

I would strongly suggest creating an exception in your CI pipeline to this particular warning.

**Comment by martinoppitz** [comment]
@boneskull Yes, I am agree, with you description.

But I observe that many vulnaribilities stay unfixed out there. We must reduce unmaintanaced dependencies.

**Comment by martinoppitz** [comment]
@Munter 
- closing the old PR is okay.
- but. why you closed the issue?

Sorry?

The new PR fixed the issue in the common way. I am happy that I could found anyone to publish a new version of `yargs-unparser`.

See. https://github.com/mochajs/mocha/pull/4336
