### ISSUE TITLE
Properly format units

### ISSUE THREAD

**Issue by getsnoopy** [mochajs/mocha#4335]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Units output by Mocha are not formatted properly as per grammar/SI rules. For example, the time it takes for a test suite to run is reported as `5s` instead of `5 s`.

### Steps to Reproduce

Run any set of tests.

**Expected behavior:** Units to be formatted properly, with spaces between the quantity and the unit symbol.

**Actual behavior:** Units are not formatted properly.

**Reproduces how often:** Every time

### Versions

This is version-agnostic.

**Comment by getsnoopy** [comment]
Turns out this is a bug upstream in the `ms` npm package, so will just keep this open until it is fixed there so that the dependency can be pointed to the new version here.

**Comment by boneskull** [comment]
I don't expect `ms` to actually change this, because it would probably break a ton of consumers.  But if they do, feel free to mention it and we can reopen this.
