### ISSUE TITLE
Option to suppress error logs

### ISSUE THREAD

**Issue by MatthewMueller** [mochajs/mocha#434]
Hey there,

Maybe I'm missing an option or there is a better way, but I think it would be nice to have some way to suppress errors and just show the report.

Here's some context: I recently ported over a mature test suite to run against a new project and I have 115 errors, which ends up logging out an obscene amount of data. I already know the main bugs that I need to tackle and it's just a matter of coding them up. It'd be great to maintain a nice report (like `-R min -w`) of how the project is progressing without the information overflow.

Thanks!
Matt

**Comment by danielstjules** [comment]
Closing for now as it looks like `tjbot` never closed the issue. I think this kind of functionality would be perfect for a third party reporter. :)
