### ISSUE TITLE
CONTRIBUTORS and PROSPECTIVE CONTRIBUTORS: join the Mocha session at OpenJS Collaborator's Summit, June 25 2020

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#4345]
**WE WILL HAVE A MEETING TOMORROW**: https://openjscs2020.sched.com/event/clHP/mocha-contributors-meeting

This is intended for Mocha's maintainers, current contributors, past contributors, or if you are interested in contributing.

The agenda is, err... well, that's what this issue is for.  @craigtaub and I will be in attendance, at minimum; maybe other maintainers as well.

Some things I'd be interested in talking about:

1. Introductions
1. Feature ideas; there's a set of things that I think Mocha really needs, and another set of things people have been asking for forever.  would like to hear everyone's thoughts
1. Discussion around sponsorship policy; we need to draft a policy (see mochajs/admin#10 for more info)
1. @craigtaub could talk about Mocha internals
1. Q&A?

@mochajs/core

**Comment by craigtaub** [comment]
I can present this (https://youtu.be/XefD5zuLAkU) if it's useful. As long as I can use speaker notes. I have no idea what the platform is like but I will try and have a proper look tomo.

**Comment by craigtaub** [comment]
Closing now. Meeting notes and actions here https://docs.google.com/document/d/1mtgbG6Sj7W1jB7HI6y9Kdv95ONslvdJGwhlGhzh5ZbA/edit
