### ISSUE TITLE
mocha runs only once in the browser

### ISSUE THREAD

**Issue by fson** [mochajs/mocha#435]
Calling mocha.run() again after running tests has finished has no effect.

Being able to run tests multiple times without refreshing the page would be
useful for me for adding some input fields in my testing page that must be
set by the user of the tests (for testing file upload). I need to run the tests
again after setting these since I want to always run the tests, when page is
loaded anyway.

**Comment by jbnicolai** [comment]
This is simply the `require` cache which needs busting. It might be nice for mocha to do this on `run`, but I feel that might cause more problems as well.

Closing as it's a very old issue that's been inactive for years. If someone feels strongly about this, feel free to comment :)
