### ISSUE TITLE
reduce netlify build times for PRs

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#4356]
The only branch that needs the "full production build" (the `docs.postbuild` script in `package-scripts.js`) is the `mochajs.org` branch, which is what mochajs.org is built from.  This script takes up _most_ of the build time, and we want to reduce the build minutes on netlify, because we're using too many.

I _think_ it's relatively safe to disable.  It's been a source of flake, and the problems are usually (but not always) corrected by a cache clear.

In its place, we'd need something to essentially just _rename_ `docs/_site` to `docs/_dist`, as `docs/_dist` is ultimately what gets deployed.

What do we think? @mochajs/core @Munter

**Comment by Munter** [comment]
Some of the production build creates significant performance improvements for our visitors, so I wouldn't want to disable them for the master branch. We could probably skip them for branches that don't work on the build system

**Comment by outsideris** [comment]
I've tried to optimize build time at #4264 , but I couldn't reduce time effectively.

I think we can run Netlify builds when the only PR has changes under `docs`.

**Comment by boneskull** [comment]
@outsideris can #4264 be closed?

this should have been closed via #4358
