### ISSUE TITLE
Feature: add option to print stack trace right away when a test fails

### ISSUE THREAD

**Issue by jgehrcke** [mochajs/mocha#4364]
This is a screenshot shown on https://mochajs.org/#reporters:
![](https://mochajs.org/static/reporter-spec-fail.resize920,9999-withoutEnlargement.b040f524a0.png)

The screenshot shows that the spec reporter shows the stack trace corresponding to each failed test at the _end_ of the test suite (the "epilogue", as this part of the report I think is called in mocha).

I'd like to see such stack trace in the reporter's output right after the failure, before the test suite moves on to executing the next test.

I might thave missed something but I have not found an option to achieve that (searched docs and github issues), therefore the feature request.

There's at least two good reasons from the point of view of a human consuming the report (text!):
1) when following output in real time: during a longish-running test suite you don't really want to wait until the end of the test suite to see all relevant error detail.
2) when trying to making sense of test failure patterns after the test suite completed: for tests that log output the clearest picture of what happened in which order is when log output is interleaved with stack traces (and that can then be best understood by simply reading top to bottom). With the stack traces being shown elsewhere in the output (instead of in the place where "they happened") makes me (as the person trying to make sense of log output and stack traces) jump between the main part of the report (showing log output) and the epilogue (showing stack traces).

(2) matters a lot when testing complex systems; where test failures might relate to each other in subtle and mean ways and where test failures are not always easy to understand in general.

**Comment by jgehrcke** [comment]
CC @boneskull -- what do you think?

**Comment by boneskull** [comment]
Thanks for the suggestion.  You can [create a custom reporter](https://mochajs.org/api/tutorial-custom-reporter.html) which will exhibit this behavior.

(I noticed the embedded code in that page is broken; the file it's referencing is [this one](https://github.com/mochajs/mocha/blob/ca0daa36c241d929f511a292f5471bd213aedb9f/test/integration/fixtures/simple-reporter.js))

**Comment by jgehrcke** [comment]
Thanks @boneskull -- I'll look into that. Do you know of custom reporters openly out there in the wild that do this?

When I get to that and if I have success, I'll share the outcome here.

**Comment by boneskull** [comment]
I don't know any offhand but you're bound to find some examples on npm. you can also use our own reporters as a starting point (the `spec.js` is the default)
