### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by dschiller** [mochajs/mocha#4377]
Repro Steps on Windows:

- Install mocha: `npm i --save-dev mocha`
- Update `package.json`: 
```
scripts": {
    "test": "mocha"   <<<
  },
...
"devDependencies": {
    "mocha": "^8.0.1"
  }
...
```
- Execute mocha: `npm test`
Result:
```
C:\_Daten\Work\Coding\Web\Kumba>npm test

> Kumba@1.0.0 test C:\_Daten\Work\Coding\Web\Kumba
> mocha

C:\_Daten\Work\Coding\Web\Kumba\node_modules\mocha\lib\esm-utils.js:8
  return import(file);
         ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\_Daten\Work\Coding\Web\Kumba\node_modules\mocha\lib\cli\run-helpers.js:18:27)
npm ERR! Test failed.  See above for more details.
```

Workaround:

Change `node_modules\mocha\lib\esm-utils.js` from

```
const path = require('path');
const url = require('url');

const formattedImport = async file => {
  if (path.isAbsolute(file)) {
    return import(url.pathToFileURL(file));
  }
  return import(file);
};
...
```

to

```
const path = require('path');
const url = require('url');

const formattedImport = async file => {
  if (path.isAbsolute(file)) {
    return require(url.pathToFileURL(file));   <<<
  }
  return require(file);   <<<
};
...
```

Someone has any idea why this Error appears ?

**Comment by juergba** [comment]
Probably it has something to do with Node's ESModules support. Difficult to say with above information.
Check the `type` property in your _package.json_.

**Comment by pdbq21** [comment]
> Repro Steps on Windows:
> 
> * Install mocha: `npm i --save-dev mocha`
> * Update `package.json`:
> 
> ```
> scripts": {
>     "test": "mocha"   <<<
>   },
> ...
> "devDependencies": {
>     "mocha": "^8.0.1"
>   }
> ...
> ```
> 
> * Execute mocha: `npm test`
>   Result:
> 
> ```
> C:\_Daten\Work\Coding\Web\Kumba>npm test
> 
> > Kumba@1.0.0 test C:\_Daten\Work\Coding\Web\Kumba
> > mocha
> 
> C:\_Daten\Work\Coding\Web\Kumba\node_modules\mocha\lib\esm-utils.js:8
>   return import(file);
>          ^^^^^^
> 
> SyntaxError: Unexpected token import
>     at createScript (vm.js:80:10)
>     at Object.runInThisContext (vm.js:139:10)
>     at Module._compile (module.js:617:28)
>     at Object.Module._extensions..js (module.js:664:10)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
>     at Function.Module._load (module.js:498:3)
>     at Module.require (module.js:597:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (C:\_Daten\Work\Coding\Web\Kumba\node_modules\mocha\lib\cli\run-helpers.js:18:27)
> npm ERR! Test failed.  See above for more details.
> ```
> 
> Workaround:
> 
> Change `node_modules\mocha\lib\esm-utils.js` from
> 
> ```
> const path = require('path');
> const url = require('url');
> 
> const formattedImport = async file => {
>   if (path.isAbsolute(file)) {
>     return import(url.pathToFileURL(file));
>   }
>   return import(file);
> };
> ...
> ```
> 
> to
> 
> ```
> const path = require('path');
> const url = require('url');
> 
> const formattedImport = async file => {
>   if (path.isAbsolute(file)) {
>     return require(url.pathToFileURL(file));   <<<
>   }
>   return require(file);   <<<
> };
> ...
> ```
> 
> Someone has any idea why this Error appears ?

This solution helped me (to change 'import' on 'require')

**Comment by rohitpiush** [comment]
Hi I am facing the same issue on mac.
SyntaxError: Unexpected token import at line 6 which is  return import(url.pathToFileURL(file));
I don't want to change the node modules file so the above solution do not work for me.
Can someone help? I am facing this on Jenkin build tool as well.

**Comment by beckbria** [comment]
I hit this because my version of Node was out of date (v8).  Updating to a newer build (v14.13) caused the error to go away.

**Comment by dschiller** [comment]
Agree with Brian. Updated Node to 12.x and it works.

```
D:\Work\Coding\Web\Kumba>npm test

> Kumba@1.0.0 test D:\Work\Coding\Web\Kumba
> mocha App/Tests/*.spec.js



  Array
    √ should return -1 when the value is not present


  1 passing (4ms)


D:\Work\Coding\Web\Kumba>node -v
v12.18.4

D:\Work\Coding\Web\Kumba>
```
