### ISSUE TITLE
Add debug logging that --inspect turns off timeouts

### ISSUE THREAD

**Issue by kwasimensah** [mochajs/mocha#4379]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**

I spent a couple hours debugging this until I found https://github.com/mochajs/mocha/issues/3519#issuecomment-435134716 and https://mochajs.org/#-timeout-ms-t-ms. 

**Describe the solution you'd like**

Something in the the debug logs that makes the behavior clear. Ideally without having to specify DEBUG=mocha*

**Describe alternatives you've considered**

You could also not turn off timeouts with --inspect.

**Comment by juergba** [comment]
You can pass `--inspect` in different ways to Node:
1. via NODE_OPTIONS
2. `node --inspect mocha test1`
3. `node mocha --inspect test1`

In alternatives 1. / 2. you are passing `--inspect` directly to Node and the `timeout` value remains unchanged.
In alternative 3. you are passing  `--inspect` first to Mocha, which then re-forwards it to Node. In this case `timeout` is intentionally set to zero. We are not planning to change this behaviour.

IMO it's not necessary to add a log output for this szenario. We also put quite an effort in our documentation.
