### ISSUE TITLE
A set of global variables that need to be available in all test environments.

### ISSUE THREAD

**Issue by Wxh16144** [mochajs/mocha#4380]
I use mocha in the `typescript` tool library, and I use the `.test.ts` test file. I want to use `__ENV__` globally. I didn't find the specific function in the document. Can you help me see it?

This is a screenshot of my project
![image](https://user-images.githubusercontent.com/32004925/88063627-ce051e00-cb9c-11ea-9756-82fd84cda26c.png)

Also I read the documentation of jest [globals](https://jestjs.io/docs/en/configuration#globals-object)

**Comment by boneskull** [comment]
`globals` is a list of _global variables_ (defined on the `global` object) which are _allowed_ to be added during a test run.  It does not have anything to do with environment variables.  The Mocha config file does not allow environment variables to be set, either.  If you want to set environment variables, do it in your shell or `package.json`, e.g., `NODE_ENV=development mocha` or use [cross-env](https://npm.im/cross-env) via `cross-env NODE_ENV=development mocha`
