### ISSUE TITLE
set timeout in .mocharc.yaml not work

### ISSUE THREAD

**Issue by zyf0330** [mochajs/mocha#4384]
### Prerequisites

- [ ] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

set timeout in .mocharc.yaml does not work

### Steps to Reproduce

1. set timeout=1000 in .mocharc.yaml
2. write a test in which `setTimeout(done, 1500)` 
**Expected behavior:** [What you expect to happen]
test fail
**Actual behavior:** [What actually happens]
test success
**Reproduces how often:** [What percentage of the time does it reproduce?]
every time
### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 8.0.1
- The output of `node --version`: 10.21.0
- Your operating system
  - name and version: ubuntu 20.04
  - architecture (32 or 64-bit): 64
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh
- Your browser and version (if running browser tests): no
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):
TypeScript

### Additional Information
Just set timeout by `this.timeout(1000)` inside describe of test, it works.

**Comment by juergba** [comment]
@zyf0330  I can't reproduce your test result.

As per my tests with Mocha v8.0.1 setting the `timeout` value in a _.mocharc.yaml_ configuration file is working perfectly.
Please make sure to place _.mocharc.yaml_ in the root directory of your project and to apply a correct syntax: `timeout: 1000`.

**Comment by zyf0330** [comment]
I know why. I enable node inspect flag and timeout is set as 0. So how to override this timeout in config?

**Comment by juergba** [comment]
Pass `inspect` directly to Node, see https://github.com/mochajs/mocha/issues/4379#issuecomment-665029112.
