### ISSUE TITLE
Flat 4.1.0 is deprecated causing an npm warn

### ISSUE THREAD

**Issue by JaredCE** [mochajs/mocha#4410]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

when installing mocha 8.1.1, npm warns that flat 4.1.0 is deprecated.

### Steps to Reproduce

run `npm i -g  mocha`

**Expected behavior:** [What you expect to happen]

No warns

**Actual behavior:** [What actually happens]

npm WARN deprecated flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.

**Reproduces how often:** [What percentage of the time does it reproduce?]

all the time

### Versions

mocha 8.1.1
node 12
ubuntu bionic

**Comment by hubiierik** [comment]
Issue opened in yargs-unparser:  https://github.com/yargs/yargs-unparser/issues/67
