### ISSUE TITLE
Print wrong count concurrent jobs in debug log

### ISSUE THREAD

**Issue by outsideris** [mochajs/mocha#4415]
# Description
In `mocha:cli:run:helpers` debug logs, it will print current concurrent jobs like below:

```
$ DEBUG=mocha:cli:run:helpers ./bin/mocha --parallel -jobs=3 sample.test.js
  mocha:cli:run:helpers files (in order):  [ '/Users/jeonghoon/Dropbox/projects/github/mocha/tt.js' ] +0ms
  mocha:cli:run:helpers executing 1 test file(s) across 3 concurrent jobs +0ms
```

But without `--jobs` option, it prints `NaN`.

```
$ DEBUG=mocha:cli:run:helpers ./bin/mocha --parallel sample.test.js
  mocha:cli:run:helpers files (in order):  [ '/Users/jeonghoon/Dropbox/projects/github/mocha/tt.js' ] +0ms
  mocha:cli:run:helpers executing 1 test file(s) across NaN concurrent jobs +0ms
```

### Steps to Reproduce
Run mocha with `--parallel` option but, without `--jobs` option.

```
$ DEBUG=mocha:cli:run:helpers ./bin/mocha --parallel sample.test.js
```

**Expected behavior:** [What you expect to happen]
Print current concurrent job count instead `NaN`.

### Versions
- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 8.1.1
- The output of `node --version`: v12.18.1
- Your operating system
  - name and version: macOS
  - architecture (32 or 64-bit): 64bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh

**Comment by boneskull** [comment]
fixed in #4478
