### ISSUE TITLE
TypeError: Suite  was defined but no callback was supplied. Supply a callback or explicitly skip the suite.

### ISSUE THREAD

**Issue by justin-wingo** [mochajs/mocha#4420]
I'm receiving the following error message
TypeError: Suite "" was defined but no callback was supplied. Supply a callback or explicitly skip the suite.
My code:
describe('Sample Test'), async function(done){
    const test = await someFunction()
    it('get partner',  function() {
      stub.get({ id: 1, tenant: 'dev'}, function (err, response) {
        console.log('data for partner:', response)});
    })
    it('get code',  function() {   
      stub.getCode({id: 1, tenant: 'dev'}, function (err, response) {
        console.log('data for partner:', response.login_id)});
    })
    if (err) return done(err);
  }

I am using done() for the callback and this is not working at all. Please advise

**Comment by boneskull** [comment]
Please double-check your syntax, as seen on https://mochajs.org.

(it's not `describe('something'), function() {}`, it's `describe('something', function() {})`)

**Comment by victorsfranco** [comment]
> Please double-check your syntax, as seen on https://mochajs.org.
> 
> (it's not `describe('something'), function() {}`, it's `describe('something', function() {})`)

THANK YOU BRO! HAHAHA
