### ISSUE TITLE
Separately run each async test file ok, but batch run will cause timeout

### ISSUE THREAD

**Issue by chenzx** [mochajs/mocha#4421]
I'm using Mocha to do async testing, each test around starting up a server & a client, I use before() to start server & after() to close it, & beforeEach with done callback to wait for client socket connected to server(with afterEach() to close the client) then do each it() test case.

The problem is, when i do the single test file running:

mocha --exit test/testCase1.js

The test quickly run ok, but when i do a batch run:

mocha --exit test/

Will result in multiple timeout exception.

Cannot figure out why.

Note: when i run each test file without "--exit" option, the node process won't exit, although `require('why-is-node-running')();` report `There are 0 handle(s) keeping the process running`

**Comment by chenzx** [comment]
This happens on prev Mocha-v7.2.0 + Node-v8.9.9 & latest Mocha + Node-v14

**Comment by chenzx** [comment]
```
const http = require('http');
const socketIO = require("socket.io");
const express = require('express');
const cors = require('cors');
const EventEmitter = require("events");
const port = 5000;

class SocketIOServer extends EventEmitter {
    constructor(){
        super();
        const app = express();
        app.use(express.json())
        app.use(express.urlencoded({ extended: true }));
        app.use(cors());
        app.getOrPost = (path, handler)=>{
            app.get(path, handler);
            app.post(path, handler);
        }
        this.server = http.createServer(app);
        console.log(`server created, now try to listen on port ${port}`);
        this.server.on("error", (error)=>{
            console.log("socket error: "+JSON.stringify(error));
        }).listen(port);
        const io = socketIO(this.server, {serveClient:false});
        io.on("connect", (socket)=>{
            socket.on("msg", (msg)=>{
                console.log("recv msg="+JSON.stringify(msg));
                this.emit("msg", msg)
            });
        });
    }

    close(){
        this.server.close();
    }
}

const socketIOClient = require('socket.io-client');
class SocketIOClient {
    constructor(socketCreatedCallback){
        this.socket = socketIOClient(`http://127.0.0.1:${port}`);
        this.socket.on("connect", ()=>{
            socketCreatedCallback(this.socket);
        });
    }
    send(msg){
        this.socket.emit("msg", msg)
    }
    close(){
        this.socket.close()
    }
}

describe("WebSocket Server/Client Async Msg Send/Recv Test", function(){
    let server;
    let client;
    // before(function(){
    //     server = new SocketIOServer()
    // })
    // after(function(){
    //     server.close();
    // })
    beforeEach(function(done){
        server = new SocketIOServer();
        client = new SocketIOClient((socket)=>{
            done();
        })
    })
    afterEach(function(){
        client.close();
        server.close();
    })

    it("send/recv test", function(done){
        this.timeout(2000);
        server.on("msg", (msg)=>{
            done();
        });
        client.send({test:"hello"});
    })

    it("send/recv 5 times test", function(done){
        this.timeout(5000);
        let data = 0;
        server.on("msg", (msg)=>{
            if(msg.data==5){
                done()
            }
        });
        let h = setInterval(()=>{
            data += 1;
            client.send({data:data});
            if(data==5)
                clearInterval(h);
        }, 50);
    })
})

```

**Comment by chenzx** [comment]
Try to reproduce the problem with minimal case(its size still very big), and Mocha hints that "done is called multiple times", which reminds me that cases may be run serializally? (i expect each it() case is run separately/serializally

So i remove before()/after() use, the above minimal case works ok, but my original tests still timeout error...

**Comment by outsideris** [comment]
When I run your code, it passed. I didn't understand what you prove in this code. 

```
  WebSocket Server/Client Async Msg Send/Recv Test
server created, now try to listen on port 5000
recv msg={"test":"hello"}
    ✓ send/recv test
server created, now try to listen on port 5000
recv msg={"data":1}
recv msg={"data":2}
recv msg={"data":3}
recv msg={"data":4}
recv msg={"data":5}
    ✓ send/recv 5 times test (267ms)


  2 passing (351ms)
```

And if tests are failed when you run all together, it means tests affect each other.

**Comment by chenzx** [comment]
I try to make a reproduce case but failed. But it really has the phenomenon i said in my test cases.

OK, i guess the problem may be due to: when a previous test calls server.close(), the server socket/handle is closing but not really closed then the next test's client.connect() crashes in?

I hope mocha can provide one-case per-process mechanism to make running multiple tests just as multiple of single-process "--exit" mode...

**Comment by chenzx** [comment]
Hi @outsideris , you need to copy the test file to multiple, named xxx-1.js xxx-2.js ..., & put them in a directory, then batch run them, then will see the wierd timeout...

**Comment by outsideris** [comment]
I made two same files under a test directory with the code above. But it's passed. If you didn't close sockets or servers properly at end of your tests, it can affect other tests.

```
$ mocha --exit test


  WebSocket Server/Client Async Msg Send/Recv Test
server created, now try to listen on port 5000
recv msg={"test":"hello"}
    ✓ send/recv test
server created, now try to listen on port 5000
recv msg={"data":1}
recv msg={"data":2}
recv msg={"data":3}
recv msg={"data":4}
recv msg={"data":5}
    ✓ send/recv 5 times test (254ms)

  WebSocket Server/Client Async Msg Send/Recv Test
server created, now try to listen on port 5000
recv msg={"test":"hello"}
    ✓ send/recv test
server created, now try to listen on port 5000
recv msg={"data":1}
recv msg={"data":2}
recv msg={"data":3}
recv msg={"data":4}
recv msg={"data":5}
    ✓ send/recv 5 times test (257ms)


  4 passing (579ms)
```

with mocha 8.1.3 and node.js v12.18.4.

**Comment by chenzx** [comment]
I'm no longer digging this problem anymore. The bug case may be not accurate, but the description happened here(--exit options cannot steadily effect when running multiple test files)
