### ISSUE TITLE
Broken wallaby logo on mochajs.org

### ISSUE THREAD

**Issue by outsideris** [mochajs/mocha#4430]
<img width="709" alt="스크린샷 2020-08-30 오후 2 06 36" src="https://user-images.githubusercontent.com/390146/91651647-28fa3100-eaca-11ea-845f-744ad96bdd63.png">

In our mochajs.org site, [wallaby-logo.png](https://github.com/mochajs/mocha/blob/master/docs/images/wallaby-logo.png) is broken. 

It is only happened in `docs.production` build, so I think it is optimization issue.

**Comment by Donghoon759** [comment]
Let me work on it :)

**Comment by boneskull** [comment]
fixed by #4431

**Comment by boneskull** [comment]
This should be in the process of being deployed to https://mochajs.org
