### ISSUE TITLE
Mocha does not pass "--prof" parameter to Node and thus does not allow for profiling

### ISSUE THREAD

**Issue by FlourishS** [mochajs/mocha#4433]
### Expected

When mocha is run with the --prof argument it will pass this argument to Node thus enabling Node to be profiled.

Example package.json:

```
...
  "scripts": {
    "start": "nodemon ./bin/www",
    "test": "mocha --prof --exit",
...
```

### Actual

The --prof argument is not passed to Node. It is therefore not possible to run node in profiling mode when using Mocha.

A dirty workaround is to patch bin/mocha as follows:

```
// sort options into "node" and "mocha" buckets
Object.keys(opts).forEach(opt => {
  if (isNodeFlag(opt) || opt == 'prof') { // dirty workaround
    console.log("node flag: " + opt);
    nodeArgs[trimV8Option(opt)] = opts[opt];
  } else {
    console.log("mocha flag: " + opt);
    mochaArgs[opt] = opts[opt];
  }
});
```

Tested with Mocha 8.1.2 and Node v12.15.0

Thank you very much for considering this bug.

**Comment by outsideris** [comment]
I confirmed `--prof` doesn't work. I think it is because of `--prof` is not in `process.allowedNodeEnvironmentFlags`.

**Comment by boneskull** [comment]
See #4439 for reasoning

**Comment by boneskull** [comment]
For anyone who wants to use `--prof`:

1. All V8 options (of which `--prof` is one) can be specified by prepending `--v8-` to the flag name, so use `--v8-prof`
1. Alternatively, use `NODE_OPTIONS=--prof` env var

**Comment by dgolant** [comment]
Heads up: second option above will throw "--prof not allowed in NODE_OPTIONS"

**Comment by frank-dspeed** [comment]
@boneskull we do not allow setting --prof in node options you can try it with a current nodejs version
