### ISSUE TITLE
Windows: mocha.opts is not recognized

### ISSUE THREAD

**Issue by osher** [mochajs/mocha#444]
Hi

I'm trying to use the following mocha.opts, which I saw in use in other projects:

```
--require should
--ui exports
```

When I pass the flags mannually - it runs well.
But without them - it runs with 0 tests complete (probably because of the default value of --ui)
I suppose it should take them from the file, right?

my platform:
- WindowsXP sp3
- node 0.6.9
- npm 1.1.0-3
- mocha 1.0.3 (installed using npm, nesting all it's declared dependencies in node_modules)

Thanks.

**Comment by danielstjules** [comment]
Closing as it's not an error, and the documentation explains this behavior. Glad things worked for you! :)

![screen shot 2015-03-14 at 1 05 54 pm](https://cloud.githubusercontent.com/assets/817212/6653336/ecb99ad2-ca4a-11e4-8712-b29bf6c0f8e6.png)
