### ISSUE TITLE
Cleanup and management of command line arguments

### ISSUE THREAD

**Issue by FStefanni** [mochajs/mocha#4441]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**

When a program access the `process.argv` array to get the command line, it just crashes since the command line
is dirty due to the running of mocha, i.e.:
* there will be mocha as first parameter
* possibly, there will follow the mocha parameters
* there will be no way to pass program/test specific arguments (i.e. arguments not managed by mocha)

For example:
```
mocha --require source-map-support/register --timeout 5000 "dist/tests/**/*_spec.js" --my-option
```

**Describe the solution you'd like**
A solution could be the following:
* mocha will automatically always clean up the `process.argv` array
* as first parameter of the new `process.argv`, mocha could place the name of the current `_spec` file running
* if in the command line there is a double-dash "--", the remaining parameters are not parsed by mocha
  but assumed as test/program parameters, and therefore added to the new process.argv

For example, the following command line:
```
mocha --require source-map-support/register --timeout 5000 "dist/tests/**/*_spec.js" -- --my-option
```

could be transformed by mocha as:
```
dist/tests/mytest_spec.js --my-option
```

**Describe alternatives you've considered**

I searched internet without success.

**Comment by FStefanni** [comment]
Hi,

I was missing that the actual first parameter is usually the interpeter (node),
so probably the "patched" command line should be something like:
```
<the current interpreter> dist/tests/mytest_spec.js --my-option
```

Regards.

**Comment by boneskull** [comment]
Hi,

Since your program is expecting `process.argv` to have a certain value, to test your program, you can:

1. Use `child_process.spawn()` or other to create a subprocess with the particular args (if you want an integration/functional test), or
2. Use a hook or root hook (see https://mochajs.org/#root-hook-plugins) to fiddle with `process.argv` yourself

**Comment by FStefanni** [comment]
Hi,

well, I know I can do tricks to adjust the command line.
The point is: a built-in feature could avoid mocha users to do these tricks manually, or, in other words,
it would simplify the mocha usage. Usability is a product value.

Regards
