### ISSUE TITLE
Support Yarn Workspaces/Monorepos with `--require`

### ISSUE THREAD

**Issue by resistdesign** [mochajs/mocha#4444]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
`--require` can't find some modules, like `ts-node/register`, when working in a `yarn` workspace.

**Describe the solution you'd like**
I'd like to see `--require` find modules when using `yarn` workspaces.

**Describe alternatives you've considered**
Jest doesn't support the `exports` style of "ui" or I might use Jest.

Right now I do this: `mocha --require ./mocha-ts-node-compat.js`

`./mocha-ts-node-compat.js` contents:
```js
require('ts-node/register');
```

**Additional context**
In all honesty, this could be a problem with `ts-node`, I noticed that it doesn't seem to be "hoisted" by `yarn`, but I don't know enough about the reasons behind that to say one way or the other just yet.

**Comment by boneskull** [comment]
This is not a `mocha` problem and is likely due to misuse/misconfiguration of workspaces

(you can also use `mocha --require ts-node/register` but that's not likely to work if your file above doesn't)

Ensure you are running `mocha` from a directory that has a `node_modules` containing `ts-node`.  You can also likely get some magic path resolution by adding `mocha` to your `test` lifecycle script in `package.json`.  But I don't know enough about how yarn handles workspaces to help further

**Comment by resistdesign** [comment]
@boneskull Sorry if I made it confusing, I use the file I mentioned above because just using `--require ts-node/register` in a monorepo package doesn't work for some reason.

**Comment by alexlafroscia** [comment]
In case anyone else ends up finding this issue as I did, I was able to resolve the problem that @boneskull calls out here

> Ensure you are running mocha from a directory that has a node_modules containing ts-node. You can also likely get some magic path resolution by adding mocha to your test lifecycle script in package.json. But I don't know enough about how yarn handles workspaces to help further

By providing a relative path to the `ts-node/register` package.

```json
// package.json
{
  "scripts": {
    "test": "mocha --require ./node_modules/ts-node/register tests/**/*.ts"
  }
}
```

The problem stemmed from needing to use the Yarn `nohoist` option with `ts-node` to resolve an unrelated issue to this one. That ended up putting `mocha` in the "top-level" `node_modules` and `ts-node` in the "package level" `node_modules`, which caused the problem with locating `ts-node`.
