### ISSUE TITLE
Better default test location for monorepos and TypeScript projects

### ISSUE THREAD

**Issue by bajtos** [mochajs/mocha#4448]
As a long-time Mocha user, I often prefer to skip `npm test` and to run mocha directly from the command line, e.g. `mocha` or `mocha -b`. This works great for traditional projects containing a single npm package written in JavaScript, where all tests are usually located in the directory `test`. Unfortunately, monorepos and TypeScript projects use a different convention for placing test files, therefore the default test directory does not work for them.

- TypeScript projects often use `src/__tests__` to keep original TypeScript test files and run `mocha dist/__tests__` to load the compiled JavaScript
- JavaScript monorepos are likely to use something like `mocha packages/*/test`, but there may be more than one top-level directory `packages`.
- TypeScript monorepos combine the two conventions above, we use something like `mocha {packages,extensions,examples}/dist/__tests__` in [loopback-next](https://github.com/strongloop/loopback-next).

It would be great to improve mocha CLI's [`spec` default value](https://github.com/mochajs/mocha/blob/738a57574f3eb82ba2844c8a512cafec974ed5ab/lib/cli/run.js#L265) to work out of the box for modern projects too.

I have two independent proposals to consider:

**(1) Configurable default for `spec` argument**

Add a new `.mocharc.js` option allowing projects to specify the default `spec` to use when no value was provided in CLI arguments. This should work for all kinds of conventions for laying out test files, single-package and monorepo projects, TypeScript and JavaScript.

Example RC file to set `spec` to all [lerna](https://lerna.js.org) packages:

```js
// .mocharc.js
const {packages} = require('./lerna.json');
const spec = packages.map(p => `${p}/dist/__tests__`);

module.exports = {
  defaultSpec: spec,
};
```

Example `defaultSpec` value created by the script above for loopback-next:

```js
[
  'acceptance/*/dist/__tests__',
  'fixtures/*/dist/__tests__',
  'benchmark/dist/__tests__',
  'docs/dist/__tests__',
  'examples/*/dist/__tests__',
  'packages/*/dist/__tests__',
  'extensions/*/dist/__tests__',
  'sandbox/*/dist/__tests__'
]
```
  
**(2) Add common TypeScript spec paths to the default provided by Mocha**

Change the default value of `spec` parameter to include `dist/__tests__` too. 

I think we cannot simply set `spec` to `['test', 'dist/__tests__']` because the code loading test files to is printing a warning `Cannot find any files matching pattern "..."` for each spec argument that points to a non-existent file/dir. 

Maybe we can check which of `test` and `dist/__tests__` directories exist and set the default value to the the existing dir? Or use a complex glob like `{test,dist/__tests__}/**/*.js`?

I understand this change may be controversial:
- It may break existing projects that happen to have `tests` storing test files and somehow manage to have `dist/__tests__` too with some other stuff.
- It's likely there are more popular conventions besides `test` and `dist/__tests__`. Adding only one convention may trigger discussions about adding more of them, we will need to find criteria on which conventions to support (add to the default list) and which not.

**Comment by boneskull** [comment]
```js
// .mocharc.js

module.exports = {
  spec: '*/dist/__tests__'
}
```

Does that work for your use-case?

I think though you're asking for _more default test file directories_, which I don't think is _necessarily_ a bad thing _if_ we have some data on what exactly are the most popular locations for test files.  I am not sure how I'd surface this info, but it'd seem like either a GH or BigQuery search would help.  It may turn out that `dist/__tests__` is way down the list.

**Comment by bajtos** [comment]
> ```js
> ```js
> // .mocharc.js
> 
> module.exports = {
>   spec: '*/dist/__tests__'
> }
> ```
> 
> 
> Does that work for your use-case?

Yes, if it does what I described in my (1) section. I'll give it a try, thank you for the pointer 🙇🏻 

> I think though you're asking for more default test file directories, which I don't think is necessarily a bad thing if we have some data on what exactly are the most popular locations for test files.  I am not sure how I'd surface this info, but it'd seem like either a GH or BigQuery search would help.  It may turn out that dist/__tests__ is way down the list.

Makes sense. I don't have bandwidth to run those queries, but wanted to open this issue to allow other users to chime in if they are interested. It looks that haven't been the case so far 🤷🏻
