### ISSUE TITLE
Tests only run once using the JS API

### ISSUE THREAD

**Issue by phpnode** [mochajs/mocha#445]
Hi, I'm trying to auto run mocha tests as part of my build process. I have a watcher that watches my application files and recompiles them and runs the tests when they change. Unfortunately I can only get mocha to run my tests once, here's something that reproduces it for me:
<pre>
# This one will work
mocha = new Mocha
mocha.reporter('spec').ui('bdd')
mocha.addFile myFilename
runner = mocha.run ->
  console.log "Done!"

# This one is identical but will find zero tests
mocha = new Mocha
mocha.reporter('spec').ui('bdd')
mocha.addFile myFilename
runner = mocha.run ->
  console.log "Done!"

</pre>

This happens even if i re-require mocha before the second one. Any ideas?

**Comment by branneman** [comment]
Same issue here. I'm running the same functional tests through multiple different browsers via the webdriver remote api (using [webdriver.io](http://webdriver.io/)).

I'm using multiple Mocha instances (via `new Mocha`, as described [here](https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically)), I went with the require-uncache hack for the moment.

**Comment by jbnicolai** [comment]
Dupplicate of #435
