### ISSUE TITLE
Document (and/or ease) how to customize Mocha globals

### ISSUE THREAD

**Issue by fgarcia** [mochajs/mocha#4451]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**

The alternative title: "Make Mocha even more extensible"

I am always tempted to customize / extend Mocha globals to:
   - ease some testing patterns
   - avoid requesting a new feature because I am not  even sure myself it would be worth increasing the feature creep of Mocha 

For example: 
```
describe('test', () => {
  it.after('release:3.1')('some test', () => {
    // ...
  })

  it('test', dsl => {
    dsl.after('release:3.1')
    dsl.readFixture('one')
  })
})
```

**Describe the solution you'd like**
I would like an official way to monkey patch the globals, specially 'it' because the 'done' call back is less useful to me after switching to`async` tests. Providing my own dsl/helpers through the `dsl` is very tempting.

One approach would be adding a function hook like `afterGlobalInstall() {}` to the mocharc.js. I would be OK with some wizardy hack forcing me to use Mocha programatically, but it should be officially supported so any investment/work by the user is more future proof.

This might open a pandora box of issues with Typescript types (up to the user to face such consequence). But at a bare minimum I do believe a custom **dsl** instead the **done** callback would be awfully convenient and easy type patch if official.

**Describe alternatives you've considered**
I've been playing with custom tests helpers like SpecHelper.for(__filename). Even better with the test object like SpecHelper.for(this) but that breaks easily if I forget the difference between normal and arrow functions.

A non official hack/monkey patch is doom to break sooner or later. 

Although I could survive with custom spec helpers, I see plenty of ways to reduce a lot of boilerplate on my tests and try new features without depending on opening an issue request

**Comment by boneskull** [comment]
You can create a custom interface to do this.  Look at e.g., `test/integration/fixtures/simple-ui.fixture.js`, and use that as a starting point.  You can then use `mocha --ui path/to/my-interface.js`.  The interface will listen for the `EVENT_FILE_PRE_REQUIRE` `Suite` event, then put whatever functions into the `context` object.  Generally speaking, the `context` object is `global`.

**Comment by boneskull** [comment]
(see `lib/interfaces/bdd.js` for the default interface, which might be better to build off of)
