### ISSUE TITLE
Upgrading to mocha 8.1.3 fails with error "Unexpected token import"

### ISSUE THREAD

**Issue by Craigfis** [mochajs/mocha#4452]
### Prerequisites
- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description
I've upgraded my version of mocha from 6.1.4 to 8.1.3
Similar to https://github.com/mochajs/mocha/issues/3228
Fixes described in here have not helped: https://stackoverflow.com/questions/35040978/babel-unexpected-token-import-when-running-mocha-tests#37076911

### Steps to Reproduce
Upgrade from early mocha to 8.1.3
Command to invoke:
 /mocha --require --require ts-node/register ./tests/inttest/*.ts

**Expected behavior:**
 tests should run

**Actual behavior:**
Fails with error: 
  return import(url.pathToFileURL(file));
            ^^^^^^
 SyntaxError: Unexpected token import

**Reproduces how often:**
always

### Versions
mocha 8.1.3
ts-node 9.0.0

**Comment by boneskull** [comment]
- Please provide a complete stack trace
- What version of node? 
- Can you supply something that I can test with, like a sample repo?

**Comment by Craigfis** [comment]
This was with node 8.15.1

Stack trace:
/builds/extensibility/gallery-api/node_modules/mocha/lib/esm-utils.js:6
     return import(url.pathToFileURL(file));
            ^^^^^^
 SyntaxError: Unexpected token import
     at createScript (vm.js:80:10)
     at Object.runInThisContext (vm.js:139:10)
     at Module._compile (module.js:617:28)
     at Object.Module._extensions..js (module.js:664:10)
     at Module.load (module.js:566:32)
     at tryModuleLoad (module.js:506:12)
     at Function.Module._load (module.js:498:3)
     at Module.require (module.js:597:17)
     at require (internal/module.js:11:18)
     at Object.<anonymous> (/builds/extensibility/gallery-api/node_modules/mocha/lib/cli/run-helpers.js:18:27)

**Comment by Craigfis** [comment]
Sorry, I just found in the release notes: 'Mocha no longer supports the Node.js v8.x line' :-(

**Comment by Craigfis** [comment]
Confirming upgrading my version of node fixed the problem.
Would've been nice if mocha detected it was running on an unsupported node version.
