### ISSUE TITLE
Some tests get skipped when the whole test folder is given as part of configuration whereas all tests pass when they are ran individually

### ISSUE THREAD

**Issue by praf111** [mochajs/mocha#4454]
### Prerequisites

- [ x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

 I have the following folder structure 
                                       Tests
                                           |-----Test1.js
                                           |-----Test2.js
                                            |-----Test3.js
When I use the following pattern for test execution:
                       [Tests/*]
Some of the tests get skipped. Whereas when I run the individual file using the pattern for ex:   [Tests/Test1.js] all of them get executed.
]

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:  6.2.3
- The output of `node --version`: v10.15.2
- Your operating system
  - name and version: macOS High Sierra (10.13.1)
  - architecture (32 or 64-bit): 64 bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): bash
- Your browser and version (if running browser tests): Chrome 85 on macOS (High Sierra)
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):

**Comment by boneskull** [comment]
need more information.  how exactly are you executing Mocha?   where are you specifying the pattern?
