### ISSUE TITLE
Delete my code

### ISSUE THREAD

**Issue by tj** [mochajs/mocha#4467]
Since [OpenCollective](https://opencollective.com/mochajs) has more funds than I do in the bank, and no one is willing to share for the % of contributions I've made to the project, I would like to delete every line which is still associated with my commits. I'll try to send a pull-request soon, same for the docs and website.

**Comment by jspiro** [comment]
You've given so much to the JavaScript community for so many years. You absolutely deserve whatever there is for your contributions.

If you want to be punitive, also delete lines modified after you created them... 💪🏻￼￼

**Comment by tj** [comment]
To be fair he's done a lot of work as well, just feels a bit shady, but whatever don't worry about it I guess. OSS sucks
