### ISSUE TITLE
How to pass --exit to mocha ?

### ISSUE THREAD

**Issue by AjaySabarish97** [mochajs/mocha#4473]
My `package.json` script

`"scripts": {
"test": "istanbul cover node_modules/mocha/bin/_mocha test/Testcases/ --exit" 
 }`

I want to run Istanbul coverage for mocha testcases, but after executing all the testcases mocha just hangs and hence istanbul coverage command doesn't run, so I tried passing the exit command, but it's not working still.

 Am I missing ?

**Comment by boneskull** [comment]
is there some reason you can't use `nyc`?

what version of `mocha` are you using?

ideally this script would be

```json
{
  "test": "nyc mocha --exit test/Testcases"
}
```
