### ISSUE TITLE
use More Linked Issues action

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#4479]
I just published https://github.com/marketplace/actions/more-linked-issues, which scratches an itch I had.

I tend to write "closes _issue_" in my commit messages and PR titles, but these are not picked up by GitHub automatically--the only place where it seems to work is in the PR description. 

The action searches PR titles and commit messages and adds the linked issues to the PR description.

**Comment by Maxgit3** [comment]
would I be able to look into this issue or do I need certain permission to add github action?

**Comment by boneskull** [comment]
I think you can just add it and it will run in your PR. let me know if it doesn't!

**Comment by juergba** [comment]
Outdated, there is the "Linked issues" feature recently added by GH.
Furthermore this action fails for PRs from forked repos.
