### ISSUE TITLE
Show only  pass/fail result without epilouge

### ISSUE THREAD

**Issue by dipakw** [mochajs/mocha#4492]
Hi,

Sometimes I just would like to know which test passed and which failed without detailed error messages (technically without epilouge) on failure. I looked at options available but didn't help at all.

I looked into the source code and it's found that there is a method **Base.prototype.epilouge** in the file base.js in reporters directory which prints the detailed error/debug message. Then I immediately thought that writing a new reporter would be a proper solution, and that new reporter shall be called **basic**.

I tried writing and running a new reporter on my local machine and it worked as expected.

So can I make a pull request for this? or what would you  suggest?

**Comment by boneskull** [comment]
You can just publish your custom reporter on npm; we don't need to merge it into Mocha.  Thanks!
