### ISSUE TITLE
[Question/Feature request] Add process id to mocha output

### ISSUE THREAD

**Issue by DJ-Glock** [mochajs/mocha#4509]
Hello team.
I use mocha with playwright for running tests in parallel. I run tests with `--jobs=8` parameter - in 8 parallels.
Playwright has a feature for debug - verbose logging by setting DEBUG=pw:api environment variable. When it's set, playwright sends debug logs to stderr. But it just sends traces without process id, so logs look like this:

```
pw:api => page.click started
pw:api   navigated to "https://website.com/"
pw:api waiting for selector "#login-field"
pw:api   selector resolved to visible <input value="" type="text" required="" data-val="true"…/>
pw:api attempting click action
pw:api   waiting for element to be visible, enabled and not moving
pw:api   element is visible, enabled and does not move
pw:api   scrolling into view if needed
pw:api   done scrolling
pw:api   checking that element receives pointer events at (960,338)
pw:api   element does receive pointer events
pw:api   performing click action
pw:api   click action done
pw:api   waiting for scheduled navigations to finish
```

When tests run in parallel, there could be an issue with reading logs. These traces can be mixed up because of workload.
I asked Playwright guys about adding process_id to the output, but they advised me to ask mocha team if it can put process id to it's output, because mocha is responsible for running tests in parallel in different processes.

So is there any possibility to add process id to each line of the mocha output?

**Comment by DJ-Glock** [comment]
As a workaround I did the following in the beginning of test file.
```
var access = fs.createWriteStream('/var/log/node/api.access.log');
process.stdout.write = process.stderr.write = access.write.bind(access);
```

**Comment by boneskull** [comment]
there's a (currently undocumented, but public) API now to define a worker reporter (`ParallelBufferedRunner#workerReporter`, which requires a custom reporter to call).  such a reporter could do this; JetBrains' Mocha plugin uses this API to handle test results in parallel mode.

but otherwise there's no obvious place to output this process ID information, especially since the debugging is happening outside of Mocha's own facilities.
