### ISSUE TITLE
get error "TypeError: Suite argument "title" must be a string. Received type "undefined"" when run my test use mocha chai

### ISSUE THREAD

**Issue by janupan** [mochajs/mocha#4512]
<img width="977" alt="Screen Shot 2020-11-16 at 08 11 41" src="https://user-images.githubusercontent.com/18500720/99209098-e7d60b00-27f4-11eb-861e-85323859cf12.png">

Hi All,
Anyone can that have the same problem?
Anyone can help me.

I use "mocha": "^7.0.1", and "chai": "^4.2.0",

I get this error when I try to run my test file. Previously all was well with me, this morning suddenly when I did a regression test it got like the picture above.

**Comment by boneskull** [comment]
the error says your suite has no title.  suites need a title.

**Comment by ctwomblyamzn** [comment]
I just ran into this as well, turned out it was due to the use of an anonymous function following describe's title: 

```js
describe('testTitleHere', () => {...});
```

Causes this issue.

**Comment by eik-1** [comment]
Help me
I got same problem
