### ISSUE TITLE
How to run mocha-teardown with parallel ?

### ISSUE THREAD

**Issue by dkuznetsov21** [mochajs/mocha#4518]
How to run mocha-teardown with the parallel test?
![image](https://user-images.githubusercontent.com/42741535/99958527-3013a100-2d92-11eb-98b8-1abcff14205c.png)
![image](https://user-images.githubusercontent.com/42741535/99958537-373aaf00-2d92-11eb-8e93-03e6445d9df3.png)
I always got this error:
![image](https://user-images.githubusercontent.com/42741535/99958553-41f54400-2d92-11eb-8c4d-003b8575018f.png)

I need to run mocha-teardown after all tests in parallel.

**Comment by boneskull** [comment]
https://mochajs.org#global-fixtures
