### ISSUE TITLE
SetTimeout Timing Out w/ Assert

### ISSUE THREAD

**Issue by destinybonavita** [mochajs/mocha#4520]
I'm using `Mocha` to execute tests against my APIs. One of the tests requires a 4-second delay. I'm using `Assert.strictEqual()` to validate the response code of the API, however, I'm getting the below exception: 

```
Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. 
```

This is how I'm running the test: 

```javascript
it("Delayed Event", done => {
        setTimeout(async () => {
            const response = await Axios.post(`${endpoint}/api1`);
            Assert.strictEqual(response.status, 200, "Delayed Event");

            done();
        }, 4000);
    });
```

I have confirmed that the API is definitely responding within that 15000ms interval.

**Comment by juergba** [comment]
```
it("Delayed Event", done => {
    setTimeout(async () => {
        // const response = await Axios.post(`${endpoint}/api1`);
        Assert.strictEqual(200, 200, "Delayed Event");

        done();
    }, 4000);
});
```
Above code works, so your `Axios.post` doesn't seem to resolve in time.
Anway if the assertions throws you are producing an uncaught AssertionError, which you should try to avoid.

**Comment by destinybonavita** [comment]
I measured the `Axios.post()` call and it's returning in under 200ms. It appeared to be an issue specifically when I add the `Assert.strictEqual()`. If that returns false then it hangs up

**Comment by juergba** [comment]
> If that returns false then it hangs up

It should throw an AssertionError, which you should handle by calling `done(err)`.
You don't get an AssertionError with eg. `Assert.strictEqual(300, 200, "Delayed Event");`?
