### ISSUE TITLE
[v8.2.1] Disappeared logs for exceptions.

### ISSUE THREAD

**Issue by zvs001** [mochajs/mocha#4528]
I'm testing express routes with mocha.
After some investigation I found that mocha `v8.2.1` causes this problem.

It works ok in `v8.0.1`

Behavior:
console.log - works
console.error - works
throw 'asdasd' - not working

**Comment by juergba** [comment]
@zvs001 please provide required details to reproduce this issue. Otherwise close. Thanks.

**Comment by zvs001** [comment]
@juergba You can check example here: https://github.com/zvs001/mocha-console-bug

**Comment by zvs001** [comment]
This issue is still actual with Mocha v10

I found workaround to fix it by passing configuration to mocharc file:

```
node-option:
  - 'unhandled-rejections=strict'
```
