### ISSUE TITLE
Unable to run tests with command line arguments

### ISSUE THREAD

**Issue by roiperlman** [mochajs/mocha#4529]
On some test files, I'm unable to run tests with command line arguments, and recieve an "unknown option" error message for the first argument passed. 
I've noticed that it happens in files where the before and after hooks are implemented, but it some of those files do manage to run with command line args.

**Comment by juergba** [comment]
@roiperlman With above information it's impossible to support you in any way.
Please provide required details to reproduce this issue or close. Thanks.
