### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by inovramadani** [mochajs/mocha#4531]
**Current behavior**
I faced intricate issue, posted on SOF before: https://stackoverflow.com/questions/65164157/set-up-testing-library-react-with-mocha-got-syntaxerror-unexpected-token

Please clone this repo: https://github.com/inovramadani/babel-bug
And then run `npm test`
Should get this error:
```
import Button from './button';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Expected behavior**
Should be able to run the test smoothly and not getting any error.

**Environment**
Tried on 3 different OS-es and 3 different npm and node versions, got same error. So I think has nothing to do with the environment.

**Comment by Maxgit3** [comment]
I think you have to use require for importing

`const Button = require('./button');`

I found this about compiling ES6 import statement
https://stackoverflow.com/questions/59042716/trying-es6-style-import-gives-cannot-use-import-statement-outside-a-module

**Comment by juergba** [comment]
Seems to be answered in: https://github.com/babel/babel/discussions/12463.

**Comment by execptionerror** [comment]
Already Solved at here [[Solved] “Uncaught SyntaxError: Cannot use import statement outside a module” when importing ECMAScript 6
](https://exerror.com/uncaught-syntaxerror-cannot-use-import-statement-outside-a-module-when-importing-ecmascript-6/)

**Comment by kyleplo** [comment]
If you aren't using TypeScript, you can also fix this by putting `"type": "module"` in the root of your `package.json` file
