### ISSUE TITLE
Security Vulnerability Issue

### ISSUE THREAD

**Issue by iadibar** [mochajs/mocha#4538]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 7.2.0
- The output of `node --version`:10.17.0
- Your operating system
  - name and version:
  - architecture (32 or 64-bit):64
- Your shell (e.g., bash, zsh, PowerShell, cmd):
- Your browser and version (if running browser tests):
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):

### Additional Information

Im using `mocha` that dependent on `flat version ^5.0.2`(inside package.json).
when I scan my app (with Veracode sca) I getting `Prototype Pollution` from `flat`,
They said : `flat is vulnerable to prototype pollution. A bypass of a previous fix for a prototype pollution vulnerability exists and allows for injection of arbitrary properties into existing construct prototypes and modification of attributes such as `__proto__`, `constructor` and `prototype``.

**What do you suggest to solve this problem?**

screen shout from Veracode sca security scan:

![Image 22-12-2020 at 9 12](https://user-images.githubusercontent.com/36728277/102860122-e02e0580-4435-11eb-8737-031e2b89db77.jpg)

**Comment by outsideris** [comment]
[flat](https://github.com/hughsk/flat) is a dependency of [yargs-unparser](https://github.com/yargs/yargs-unparser), and `flat@5.0.2` is latest version. So, we can do nothing here. Opening an issue in the flat project is better.

And `mocha@7.2.0` use [`yargs-unparser@1.6.0`](https://github.com/mochajs/mocha/blob/v7.2.0/package.json#L77) which use [`flat@4.1.0`](https://github.com/yargs/yargs-unparser/blob/v1.6.2/package.json#L45). So, I don't know where your `flat@5.0.2` from.
