### ISSUE TITLE
'nanoid' do not define a valid './non-secure' target

### ISSUE THREAD

**Issue by TheFive** [mochajs/mocha#4539]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Steps to Reproduce

I have created a new test project
package.json:
```
{
  "name": "mochatest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "mocha": "^8.2.1"
  }
}
```
test/test.js
```

const assert = require('assert');
describe("test",function() {
  it('should test something', function() {
    assert(1=1);
  });
});
```

running the test produces the error (during mocha load)
```
mochatest % npx mocha
Package exports for '/Users/TheFive.osm/development/mochatest/node_modules/nanoid' do not define a valid './non-secure' target
```

**Expected behavior:** 
Test should run without error.

**Actual behavior:** [What actually happens]

Error Message
```Package exports for '/Users/TheFive.osm/development/mochatest/node_modules/nanoid' do not define a valid './non-secure' target```

**Reproduces how often:** [What percentage of the time does it reproduce?]

Five tests 100 %

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: see package.json mocha -version does not work, see error.
- The output of `node --version`: V13.1.0
- Your operating system
  - name and version: OSX 10.15.7
  - architecture (32 or 64-bit):
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh
- Your browser and version (if running browser tests): n.a.
- Any third-party Mocha-related modules (and their versions): none
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): none

**Comment by TheFive** [comment]
simpler reproducable by following command line
```
mkdir test#4539
cd test#4539
npm install mocha
npx mocha --version
```
with nodeversion 13.1.0 result:
```
Package exports for '/Users/TheFive.osm/development/mochatest2/node_modules/nanoid' do not define a valid './non-secure' target
```

With node version v12.13.0 result as expected: 8.2.1
node version 12.20.0  result as expected
node version 14.15.3 is although working.

I will update my node version, and close the issue

**Comment by Whathecode** [comment]
I get this same exception when trying to upgrade from mocha 8.1.3 to 8.2.0.

Here is my `package.json`:

```
{
  "scripts": {
    "tsc": "tsc"
  },
  "devDependencies": {
    "@types/chai": "4.2.14",
    "@types/mocha": "8.2.0",
    "@types/node": "14.14.22",
    "@typescript-eslint/eslint-plugin": "4.14.1",
    "@typescript-eslint/parser": "4.14.1",
    "@typescript-eslint/typescript-estree": "4.14.1",
    "@typescript-eslint/types": "4.14.1",
    "chai": "4.2.0",
    "eslint": "7.18.0",
    "mocha": "8.1.3",
    "jsdom": "16.4.0",
    "jsdom-global": "3.0.2",
    "ts-node": "9.1.1",
    "typescript": "4.1.3"
  }
}
```

**Comment by Whathecode** [comment]
Still the case for mocha 8.4.0.

**Comment by mcmx** [comment]
Issue present in node v13.1.0, updated to v14.17.0 fixed it.
