### ISSUE TITLE
For async defined interfaces, code coverage is not detected

### ISSUE THREAD

**Issue by hjj921117** [mochajs/mocha#4545]
router.get('', async function (req, res) {
    let errMsg = utils.buildErrMsg(req, apis.HEALTH_CHECK);

    if(false){
        console.log('-------------')
    }
    errMsg.msg = 'success';
    return res.json(utils.resJSON(errCodes.SUCCESS, 'Health OK', 'Health OK', errMsg));
});

If async is removed, the code coverage of the module will be reported。
Please help to see what the problem is？Thanks

**Comment by outsideris** [comment]
You should explain your problem in detail.

**Comment by hjj921117** [comment]
Write a simple interface,that's what I wrote before. “router.get (', async function (req, res) ” when the interface generates a code coverage report through “npm run coverage”, there is no code test coverage of the interface. If async is removed “router.get ('', function (req, res)“, it will show that the if block in the block code has not been executed.

**Comment by juergba** [comment]
Incomplete issue description, closing. Probably not Mocha related anyway.
