### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by IamLizu** [mochajs/mocha#4561]
### Prerequisites

-  [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

I have this simple GET request which returns 'Hello World!' upon request. When I test this with `mocha` and `chai`, I get this following error,

>     Uncaught TypeError: Cannot read property 'apply' of undefined
>      at Immediate.<anonymous> (node_modules\express\lib\router\index.js:635:15)
>      at processImmediate (internal/timers.js:463:21)

### Steps to Reproduce

Fork this [repo](https://github.com/IamLizu/express-test-dummy) and run `npm i` & `npm test` inside the local dir of the repo.

**Expected behavior:** Test should run without any issue.

**Actual behavior:** Gives the above error.

**Reproduces how often:** All the time.

### Versions

- The output of `mocha --version`: 8.2.1
- The output of `node --version`: 14.15.4
- Your operating system
  - name and version: Windows 10
  - architecture (32 or 64-bit): 64bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): PowerShell
- Your browser and version (if running browser tests): N/A
- Any third-party Mocha-related modules (and their versions): N/A
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): N/A

**Comment by juergba** [comment]
I guess throwing an error (`if (err) throw err;`) is not the correct way to notify Mocha about the (failing) end of the test.
You are producing the uncaught exception yourself.

**Comment by IamLizu** [comment]
Happens to be the same with the line commented out,
```
describe("Entry point", () => {
    context("GET /", () => {
        it("should get greeting back", (done) => {
            chai.request(mainEntryPoint)
                .get("/")
                .end((err, res) => {
                    // if (err) throw err;
                    res.should.equal("Hello World!");
                    done();
                });
        });
    });
});
```

>     Uncaught TypeError: Cannot read property 'apply' of undefined
>      at Immediate.<anonymous> (node_modules\express\lib\router\index.js:635:15)
>      at processImmediate (internal/timers.js:463:21)

**Comment by juergba** [comment]
Now, you don't have any error handling at all. So again an uncaught exception.

**Comment by IamLizu** [comment]
Can you please tell me how should I handle it? I have tried like this bellow, still same.

```
            chai.request(mainEntryPoint)
                .get("/")
                .then((res) => {
                    res.should.equal("Hello World!");
                })
                .catch((err) => {
                    throw err;
                });
```

**Comment by juergba** [comment]
If your test uses a `done` callback, you have to call `done()` for a passing test or `done(err)` for a failing test.
The other option is to return a promise. In this case without defining a `done`  callback in your test.
Both ways are shown in the [chai HTTP docs](https://www.chaijs.com/plugins/chai-http/).
Probably there are more bugs in you app, since I can't see "Server started at port" printed anywhere.

I'm quite sure this has nothing to do with Mocha.

**Comment by IamLizu** [comment]
Well, the case should pass. So, its `done()`, and even if I check it for failing test (which it is not). It still doesn't work, any ways. Here's a snippet for not passing test (i removed the passing one),

```
describe("Entry point", () => {
    context("GET /", () => {
        it("should NOT get greeting back", (done) => {
            chai.request(mainEntryPoint)
                .get("/")
                .end((err, res) => {
                    // if (err) throw err;
                    res.should.not.be.equal("Hello");
                    done(err);
                });
        });
    });
});
```

And the server actually starts. Let's say if I start the server with `npm run dev` then try to run the test, it says port is in use. So, it starts or tries to start. I can strongly claim there is no bug in the code expect the test file.

**Comment by juergba** [comment]
Listen @IamLizu , this is a issue tracker, not a help forum. You have to narrow down the problem yourself, I don't have time to make your app work.
I'm quite sure that your app never gets up to `.end()`. Try to `console.log(res)`. If there is no `res`, why?
Also the error is thrown in _express\lib\router_.

**Comment by IamLizu** [comment]
Alright.

**Comment by tech-rounak** [comment]
hi @IamLizu was the problem solved??
