### ISSUE TITLE
Root hooks defined in plugins do not share their context with tests

### ISSUE THREAD

**Issue by acarstoiu** [mochajs/mocha#4568]
### Description
The recently introduced [Root Hook Plugins](https://mochajs.org/#root-hook-plugins) do not share the `this` context with the test suites and tests run by _mocha_.

### Steps to Reproduce
Having defined a plugin loaded via `--require` like this
```
exports.mochaHooks = {
	beforeAll() {
		this.some = ...
	},
...
};
```
if someone tries to use the `some` value in a test
```
describe("blabla", function() {
	this.some.xyz(...);
...
});
```
then a `TypeError: Cannot read property 'xyz' of undefined` is thrown.

**Expected behavior:**
The `some` value should be available everywhere, as these root hooks are always executed in the same VM context as the tests proper, even when running in parallel mode.

### Versions
Latest _mocha 8.2.1_.

**Comment by acarstoiu** [comment]
Damn, it looks like in hooks and tests proper, the context values set in a root hook **are** available!

Is this the case with all contexts? That is, they are shared **only** in actual testing code (hooks and tests) and not in suites themselves (the code that is run just to discover all tests and hooks)?

**Comment by juergba** [comment]
You have two phases:
- parsing: Mocha executes the `describe` functions, to find the tests/hooks, but without executing them. Builds the test runner "tree". So your `beforeAll` hasn't run yet.
- then Mocha runs the test runner and executes all tests/hooks.

**Comment by acarstoiu** [comment]
...So, there's no context to share **yet** in that initial phase, I see, but I expected that `this` would be properly set in this phase too, since it can be used to set timeouts, for example.

Actually, my use case was a bit more subtle, it was an arrow function used inside tests:
```
describe("blabla", function() {
	let helper = () => {
		this.some.xyz(...);
	}

	specify("...", function() {
		helper(...);
	}
...
});
```

So the two phases have different `this` hierarchies. I think this should be pointed out in the documentation.

**Comment by nielsdekeijzer** [comment]
@acarstoiu , could you please elaborate a bit? I am not able to share any context between mochaHooks and the tests. Not in the suite, describe() nor it(). 
My goal is to setup some generic testdata in the mochaHooks, and pass the result to the tests so additional test-specific data can be set up on top of that.
