### ISSUE TITLE
Custom Reporter (documentation update request)

### ISSUE THREAD

**Issue by ramtinsoltani** [mochajs/mocha#4573]
Hi there. I just wrote a custom Mocha reporter that I believe might be useful to Mocha users. Is it possible to have the official documentations list or mention it in the third-party reporters?

This is the package: <https://www.npmjs.com/package/mocha-progress-reporter>

There's a screen recording GIF in the documentation that shows some of the extra capabilities of this reporter.

P.S. I posted this a few days ago in the Gitter chatroom and no one replied. No idea where to ask this. So I apologize if this is not the right place.

**Comment by outsideris** [comment]
We don't manage third-party reporters tightly yet. So, I [added your reporter to our Wiki page](https://github.com/ramtinsoltani/mocha-progress-reporter). Thank you.

**Comment by ramtinsoltani** [comment]
@outsideris Thank you so much!
