### ISSUE TITLE
Root hook plugins not running when run in parallel with API (works through CLI)

### ISSUE THREAD

**Issue by decfrv** [mochajs/mocha#4575]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

When running through the CLI and requiring a file that exports a `mochaHook` root hook plugin object, running the tests in parallel will properly execute the root hooks. However when using the JS API to create a Mocha object and call `run`, the root hooks are not invoked when running in parallel (but work fine with parallel disabled).

### Steps to Reproduce

This issue originally surfaced while running in AWS Lambda, but I was able to reproduce it locally with the following example.

```
# runner.js

const Mocha = require('mocha');
const mochaHooks = require('./hooks').mochaHooks;

const mocha = new Mocha({
  parallel: process.env.PARALLEL === 'true',
  rootHooks: mochaHooks,
});

mocha.addFile('./tests');
const runner = mocha.run();
runner.on('end', () => { console.log('DONE'); });
```

```
# tests.js

describe('test suite', () => {
  it('test', () => {
    console.log('running the test');
  });
});
```

```
# hooks.js

exports.mochaHooks = {
  beforeAll: () => {
    console.log('beforeAll');
  },
  beforeEach: () => {
    console.log('beforeEach');
  },
  afterAll: () => {
    console.log('afterAll');
  },
  afterEach: () => {
    console.log('afterEach');
  },
};
```

Here are the differing outputs when run through the CLI/API and run in serial/parallel:

When running through the CLI in series:

`mocha --require ./hooks.js ./tests.js`

```
beforeAll
  test suite
beforeEach
running the test
    ✓ test
afterEach

afterAll

  1 passing (4ms)
```

When running through the CLI in parallel:

`mocha --require ./hooks.js ./tests.js --parallel`

```
beforeAll
beforeEach
running the test
afterEach
afterAll

  test suite
    ✓ test


  1 passing (153ms)
```

When running through the API in series:

`node ./runner`

```
beforeAll
  test suite
beforeEach
running the test
    ✓ test
afterEach

afterAll

  1 passing (4ms)

DONE
```

When running through the API in parallel:

`PARALLEL=true node ./runner`

```
running the test

  test suite
    ✓ test


  1 passing (165ms)

DONE
```

The rook hook plugins are only not invoked when called through the API and when running in parallel (even though the docs say this approach should work with parallel runs - https://mochajs.org/api/global.html#MochaRootHookObject) 

**Expected behavior:**

When running mocha through the API in parallel mode, rook hook plugin functions should be invoked.

**Actual behavior:**

When running mocha through the API in parallel mode, rook hook plugin functions are not invoked.

**Reproduces how often:**

100% of the time

### Versions

node node_modules/.bin/mocha --version
8.3.0

mocha --version
8.3.0

Originally observed this issue when attempting to run in AWS Lambda, but reproduced it locally on:

MacOS 10.15.7
zsh 5.7.1

**Comment by juergba** [comment]
@decfrv thanks for this issue and your detailed description.
I'm going to reproduce your samples within the next few days.

**Comment by juergba** [comment]
It seems as if the `worker` tries to use the `rootHooks` of the `--require` option, which in case of Mocha's API usage doesn't exist.
In serial mode no workers are used, neither via CLI nor via API.

**Comment by juergba** [comment]
The challenge is the communication between the processes (IPC). To use this IPC chanel the data has to be serialized/deserialized.
At the moment we use this chanel for plain object only, so functions (eg. `rootHooks`) are not interchanged because:
- serialization is slow.
- the function scope is lost by serialization.

Instead Mocha is extracting the `rootHooks` out of the `--require` module for every worker.
When using Mocha programmatically there is no `--require` module which explains the root cause of this issue.

Solution: by adding a `require` option to the `Mocha` constructor, every worker has access to the `rootHooks` module.
```js
const mocha = new Mocha({
  parallel: process.env.PARALLEL === 'true',
  rootHooks: mochaHooks,
  require: ['./hooks.js']        // added line
});
```

I'm not sure yet how to document this use case.

@decfrv any thoughts or comments are welcome.
