### ISSUE TITLE
mocha how to use same page between two it blocks

### ISSUE THREAD

**Issue by vikramdaruru** [mochajs/mocha#4576]
I am trying to do following using mocha and puppeteer. Any idea how can I pass the page which is already initialized in first it block to 2nd it block or multiple it blocks?

`const puppeteer = require('puppeteer')
const expect = require('chai').expect
const assert = require('chai').assert
var browser
var page

 describe('My Dev Tests', function () {

    before('Browser and page initiation and navigate to product list', async () => {
        browser = await puppeteer.launch({ headless: false, slowMo: 200, timeout: 0, defaultViewport: null,
            args: ['--start-maximized','--no-sandbox','--disable-web-security','--disable-features=IsolateOrigins,site-per-process']
            , executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'})
        page = await browser.newPage({timeout: 0})
            //page.setDefaultTimeout('300000')
        await page.goto('http://example.com')
        
    })

    it('Test1', async () => {
        await page.waitForSelector('input[name="netmarkets.product.list.searchInListTextBox"]', {timeout: 120000}).then(() => console.log('Successfully logged in!'))
        //Some operations and assertions
        
    })

    it('Test2', async () => {
        await page.waitForXPath('//button[text()="New Problem Report"]', {timeout: 120000})
        //some operations and assertions on same page of resulting page in Test1
        
    })

 })`

As soon as I run the above code, it gives following error.

`  Create New Problem Report:
 TypeError: page.waitForXPath(...) is not a function
  at Context.<anonymous> (uattests\DEVNewPRMA.js:58:9)`

**Comment by juergba** [comment]
@vikramdaruru please note this an issue tracker and not a help forum.
We recommend to use the [gitter](https://gitter.im/mochajs/mocha) chanel what you have already done.
Closing.
