### ISSUE TITLE
warning on done in async function 

### ISSUE THREAD

**Issue by hardfist** [mochajs/mocha#4581]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
when done appear in async function, it's kind of odd 
* bad, cause test to hang
```
it('async',async (done) => {
  this.timeout(99999);
  await Promise.resolve(1);
})
```
* ok
```
it('async', async () => {
  this.timeout(99999);
  await Promise.resolve(1);
})
```
it's kind of suppressing to see different result, just because the done parameters
**Describe the solution you'd like**
warning, if an async function passed by done arguments

**Comment by outsideris** [comment]
I think it is normal behavior. Actually, it is `returning Promise` vs. `done callback` for async tests.

If you provide `done`, mocha will wait for `done` to be invoked. I believe sometimes we should use `done` callback in async function`
