### ISSUE TITLE
How to get current runner within test code

### ISSUE THREAD

**Issue by dcaillibaud** [mochajs/mocha#4585]
Hi,
Is there a way to get the current runner within the js test code ?
In some case I want to add a fail listener on current runner (to dump some test informations), but I didn't find the way to do it (I read a lot of mocha documentation, api, stackoverflow).

I tried 
```
const Mocha = require('mocha')
const { EVENT_TEST_FAIL } = Mocha.Runner.constants

describe('attempt to add a listener', function () {
  // get current Suite object
  let runnable = this.runnable()
  while (runnable.parent && !runnable.root) runnable = runnable.parent
  // runnable is now the root Suite
  if (typeof runnable.on === 'function') {
    // this is called
    console.log('Add listener', EVENT_TEST_FAIL)
    runnable.on(EVENT_TEST_FAIL, function (event) {
      // but never this
      console.log('test fail event', event)
      console.log('test fail context', this)
    })
  }
  it('failing test', function () {
    return Promise.reject(Error('hand made failure'))
  })
})
```
I guess I should attach my fail listener to runner instead of root suite, but how ?
And if it's possible, how to get the failed Test object in this listener ?

Thanks a lot

**Comment by juergba** [comment]
You could create your [own reporter](https://github.com/mochajs/mocha/wiki/Third-party-reporters), which listens to runner's events. We already have a fail event which has the test obect in its scope.

The other option would be using [Mocha programmatically](https://github.com/mochajs/mocha/wiki/Using-Mocha-programmatically). `mocha.run()` returns the `runner` instance for registering your listeners.

**Comment by dcaillibaud** [comment]
Thanks !
I see it's useless I spend more time looking for something that doesn't exists ;-)
