### ISSUE TITLE
Using lambda expressions

### ISSUE THREAD

**Issue by mzedeler** [mochajs/mocha#4586]
I'm always frustrated when I have to write `it(..., function() {` in stead of `it(..., (thisArg) => ...`.

**Describe the solution you'd like**
I would like to be able to use lambda expressions in test bodies as described above.

**Describe alternatives you've considered**
A colleague of mine suggested writing a wrapper to work around the lacking access to `this`, but it seems unwieldy (`withThis((thisArg) => ...`).

I wouldn't mind exploring how to add lambda expressions support to Mocha myself.

**Comment by juergba** [comment]
@mzedeler thank you for your suggestion.
We already have open issue #2657 about the same subject.
Closing.
