### ISSUE TITLE
Mocha Retries test more often then expected

### ISSUE THREAD

**Issue by saadisfy** [mochajs/mocha#4587]
### Prerequisites

- [ x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

**Short Description:** I have set retries as 5 and normally it will stop after trying 5 times. But sometimes it will retry arbitrary times. For example, one time it retried 8 times and other time even 12, etc. Since it is each time a different retry value and can be a different test, I am unable to reproduce it. 

### Steps to Reproduce

I'm running Mocha programatically, which means I create a Mocha instance.  
The code skeleton for creating the test suit is the following:
**file: test.js**
`      describe('describe', function () {
        for (let value in configuration.list) {
          it('testName' + value , async function () {
            await utils.onTestFailure(testFile.functionToTest.bind(this, value));
          });
        }
      });`

- **onTestFailure**: used as an 'afterhook' to fix up things after error, so it can re-run test without any problems (deleting objects which were created in the test, etc.): Catches Error, does its fixup, and throws the caught error again, so mocha receives it. it also uses a retryCounter.

- **functionToTest**:
` this.timeout(600 * timeout);
this.retries(configuration.retries);
codeToTest.....
`

**Expected behavior:** **Configuration.retries** is set to 5. So I expect it to retry maximal five times after each failure.

**Actual behavior:** In occasional cases, it will go over the max limit and retry arbitrary times. There was a case where it went over 30 times (each test run takes around 40-70 seconds).

**Reproduces how often:** 1-2 %, 

### Versions

- The output of `mocha --version` and `node_modules/.bin/mocha --version`: no global,  and 8.2.1
- The output of `node --version`: v12.19.0
- Your operating system
  - name and version: win10
  - architecture (32 or 64-bit): 64
- Your shell (e.g., bash, zsh, PowerShell, cmd):
- Your browser and version (if running browser tests):
- Any third-party Mocha-related modules (and their versions): mochawesome (6.2.1)

### Additional Information
This is my first issue, so if any more details are needed feel free to tell me.
Since the 'bug' is not reproduce-able I am unable to create a mcve. 
I've also tried this on our Jenkins instance where the versions are slightly different and I have seen this bug a few times there, too. So I'm sure it is something in the code.
I assume that it has to do something with the way I'm setting the retry. It is set in a function in a different file, where I have the same this-context through the bind, but since it is impossible to reproduce the error, I can't different approaches to set the retry. 
I'm aware that the information I have given is not enough to directly say what the reason for this problem is, but I hope some mocha experts can give me some hints, what might be the reason for this behavior.

**Comment by juergba** [comment]
@saadisfy difficult to verify or explain if the issue is not reproducable. 😎

If you are throwing `uncaught exception`'s in your asynchronous code, Mocha tries to recover and keep going the runner, on best effort basis. Maybe this could be an explanation. Otherwise the code covering the `retries` logic is quite simple and doesn't contain any black holes.

**Comment by saadisfy** [comment]
@juergba yes, sadly this makes debugging the problem really hard :/

I will go through the code again and check all exceptions, thanks for the info. 

About the retries logic, if I understood it right, the retry value is only set at start, afterwards in each retried test function the set function `this.retries(value)` doesn't affect the value set initially. Is this true?

For example it is not possible to create an infinite loop with `this.retries(value++)` with a global value, right?

**Comment by juergba** [comment]
`Suite` and `Test` (extends `Runnable`) have their own internal property `_retries`, initially its value is set to -1.

> this.retries(value) doesn't affect the value set initially. Is this true?

Should be true, only `_currentRetry` will be changed.

> For example it is not possible to create an infinite loop with this.retries(value++) with a global value, right?

`Runnable#retries` is a private function. If the user calls it in a bad way, I guess you could create an infinite loop, if the test keeps failing.
