### ISSUE TITLE
Propose a Change to Mocha done() callback

### ISSUE THREAD

**Issue by jbactual** [mochajs/mocha#4590]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
I believe it both fixes current issues and is nice-to-have. 
Proposed feature eliminates the need for assertions and allows Mocha to transition from test to test more fluently. 

**Describe the solution you'd like**
Utilize the done() callback to manually submit a success or failure along with a message/error pertaining to the current test. This message will be displayed in the console directly under the pass/fail log. 

**Additional context**

```
// Purposed built in done() callback
// Param: testResult = {pass: boolean, message: string}
//     a. Pass: Boolean used to determine whether test passed or failed
//     b. Message: String used to describe what happened during last test. 
const done = (testResult) => {
 if (!testResult) {
  next(); // push to next test, for lifecyle methods
 }
 const { pass, message } = testResult;

 if (pass) {
  // Mocha Message w/ checkmark and other logic
  MochasTestPassedFn(message);
 }

 if (!pass) {
  // Mocha Message w/ X mark and other logic
  MochasTestFailedFn(message);
 }
}
```

```
#  Mocha Example Test
describe('Mocha Example Test', function () {
 it('Add user to mongodb', function (done) {
  const newUser = new User({ name: 'Jason' });

  // Using if/else statements in place of assertions eliminates 
  // the need for other dependencies and provides a more user friendly experience.
  // I also believe giving programmers the ability to add extra information under 
  // their test results can potentially be beneficial.  

  newUser.save((err) => {
   if (err) done({ pass: false, message: err });
   else done({ pass: true, message: 'User was successfully saved in 96ms.' })
  });
 });
});
```

**Comment by JoshuaKGoldberg** [comment]
I... don't understand 😬. But this is almost 3 years old and nobody's interacted with it since. Closing as wontfix.

If you're interested in this, please file a new issue with one our new issue templates. They ask for the information we'd need to understand this proposal. Cheers!
