### ISSUE TITLE
[docs] Update glob in docs to include .mjs and .cjs

### ISSUE THREAD

**Issue by jakub-g** [mochajs/mocha#4593]
The [docs are saying](https://github.com/mochajs/mocha/blob/master/docs/index.md#the-test-directory):

> By default, mocha looks for the glob "./test/*.js"

But this contradicts what is written at the beginning of the docs

> Mocha discovers test files; when given no files or directories, it finds files with extensions .js, .mjs or .cjs in the test directory (but not its children), relative to the current working directory

**Comment by outsideris** [comment]
Good catch. Thank you.
