### ISSUE TITLE
Error on attempt to run tests in parallel mode with nodejs 15.11

### ISSUE THREAD

**Issue by Xotabu4** [mochajs/mocha#4597]
### Prerequisites
- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Noticed that on attempt to run mocha in parallel mode with nodejs 15.11 (also with 15.8) causes error.

### Steps to Reproduce

You can clone my project (specific commit with with parallel enabled)- https://github.com/Xotabu4/pet-store-tests-READY/commit/ee6160b7fb36eb8f535f770271ee3665f3fbe915

it has package-lock.json file with all deps tree to reproduce correctly.

Just run: 
```
npm cit
```

**Expected behavior:** 

Parallel mode expected to be working

**Actual behavior:** [What actually happens]
```
➜  pet-store-tests-READY git:(7-configuration) ✗ npm run ttest

> pet-store-tests-ready@1.0.0 ttest
> mocha


TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be of type object. Received an instance of Array
    at ChildProcess.target.send (node:internal/child_process:716:7)
    at Array.forEach (<anonymous>)
    at dispatchQueuedRequests (/mnt/c/GitHub/api-project-examples/pet-store-tests-READY/node_modules/workerpool/src/WorkerHandler.js:250:21)
    at ChildProcess.<anonymous> (/mnt/c/GitHub/api-project-examples/pet-store-tests-READY/node_modules/workerpool/src/WorkerHandler.js:209:7)
    at ChildProcess.emit (node:events:378:20)
    at ChildProcess.EventEmitter.emit (node:domain:470:12)
    at emit (node:internal/child_process:920:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Reproduces how often:** 100

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 8.2.1
- The output of `node --version`: v15.11.0 and 15.8
- Your operating system
  - name and version: WSL2 ubuntu 18 (Windows 10 pro)
  - architecture (32 or 64-bit): x64
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh
- Your browser and version (if running browser tests): api tests, no browser
- Any third-party Mocha-related modules (and their versions): not related
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): ts-node (9.1.1), typescript (4.1.3)

**Comment by Xotabu4** [comment]
Works fine with
parallel: false in mocharc.js 

![image](https://user-images.githubusercontent.com/3033972/110361008-1d269300-8048-11eb-832e-cc6c900864a7.png)

**Comment by juergba** [comment]
@Xotabu4 Mocha v8.3.0 should be fine. Please try and revert back, thanks.

**Comment by Xotabu4** [comment]
> @Xotabu4 Mocha v8.3.0 should be fine. Please try and revert back, thanks.

Indeed, bumping to 8.3.1 solves the problem. Thanks!
