### ISSUE TITLE
Mocha 8.3.1 not linking _mocha binary in .bin folder

### ISSUE THREAD

**Issue by saqib-ahmed** [mochajs/mocha#4600]
With 8.3.1, `_mocha` is not being linked to `node_modules/.bin` directory. It produces an error whenever `mocha` command is used in package.json.

**NPM version** : 7.6.1
**Node version** : 12.20.0
**MacOSx 10.15.6**

**Comment by juergba** [comment]
This is most probabely not an issue with Mocha, it's [npm](https://docs.npmjs.com/cli/v7/configuring-npm/folders#executables) which creates those links.
Try to delete the `node_modules` folder and `package-lock.json` and install again.
