### ISSUE TITLE
Unable to update mocha to 8.3.1: fsevents@patch - Cannot apply hunk #1

### ISSUE THREAD

**Issue by DJ-Glock** [mochajs/mocha#4602]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description
I'm trying to update mocha from version 8.2.1 to 8.3.1. Mocha is installed as dev dependency.

### Steps to Reproduce
Set version 8.3.1 in package.json and run yarn **or** use upgrade-interactive **or** use yarn add mocha --dev.

**Expected behavior:**
Mocha 8.3.1 should be installed.

**Actual behavior:** [What actually happens]
Error occurred:
➤ YN0066: │ fsevents@patch:fsevents@npm%3A2.3.2#builtin<compat/fsevents>::version=2.3.2&hash=127e8e: Cannot apply hunk #1 (set enableInlineHunks for details)
![image](https://user-images.githubusercontent.com/26511191/110624232-fafb5500-81ae-11eb-87e8-988cde092234.png)

### Versions
- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 8.2.1
- The output of `node --version`:  12.18.3
- Your operating system
  - name and version: Windows 10
  - architecture (32 or 64-bit): 64-bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): Powershell
- Your browser and version (if running browser tests): -
- Any third-party Mocha-related modules (and their versions): yarn 2.3.3.
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): -

I searched for this error and found many issues from 2020, but all of them were resolved somehow. So not sure why it occurred for me especially on Windows.

**Comment by juergba** [comment]
maybe something like: `yarn install --ignore-optional`

**Comment by DJ-Glock** [comment]
@juergba you might be right about optional. It looks like the chain is: mocha [requires chokidar](https://github.com/mochajs/mocha/blob/master/package.json) and chokidar [requires fsevents](https://github.com/paulmillr/chokidar/blob/master/package.json), but optionally.

I have no idea why yarn 2 tries to install optional dependency and flag --ignore-optional does not work as per [this issue](https://github.com/yarnpkg/yarn/issues/2680).
I'll raise another issue for yarn team.

Thanks.

**Comment by DJ-Glock** [comment]
Update: it was a yarn issue. It looks like issue was fixed in yarn 2.4.1. We updated yarn to 2.4.0 - issue was in place, but after ipdating yarn to 2.4.1 everything is fine.

Hope this will help someone.
