### ISSUE TITLE
Typescript UnitTest with reference path

### ISSUE THREAD

**Issue by VishakVKurup123** [mochajs/mocha#4609]
I facing an issue running mocha tests for typescript.
My target project is having a similar structure.
[tests.zip](https://github.com/mochajs/mocha/files/6146621/tests.zip)
[scripts.zip](https://github.com/mochajs/mocha/files/6146622/scripts.zip)

When I run the npm test I get the following error:

TSError: ⨯ Unable to compile TypeScript:
tests/Student.test.ts:6:26 - error TS2304: Cannot find name 'MyTestApp'.

         let person = new MyTestApp.common.Person("Sachin", "Ramesh", "Tendulakar");
                           ~~~~~~~~~
tests/Student.test.ts:11:27 - error TS2304: Cannot find name 'MyTestApp'.

        let student = new MyTestApp.common.Student("Sachin", "Ramesh", "Tendulakar");


The issue can be solved if we use import/export statements but my target project is huge and cannot change at this moment. Can anyone give a solution? npm build runs without any error.

**Expected result**
Tests should run

**Actual result**
Test fail to run and shows error

**Comment by juergba** [comment]
@VishakVKurup123 please note this is an issue tracker, not a help forum.
We recommend to use our [gitter](https://gitter.im/mochajs/mocha) for general questions.
