### ISSUE TITLE
how to update version electron in mocha test

### ISSUE THREAD

**Issue by maajja** [mochajs/mocha#4610]
can somebody know how to update version of electron because when i run mycode in npm start is working but when i run my code in mocha test is have a lot of error  
![electron](https://user-images.githubusercontent.com/79619000/112266752-0c605900-8ca7-11eb-8f8f-ed2fa0e73bb0.jpg)

the left one is run with : npm start 

the right one isrun with : test mocha

and the problem is i think the electron is different version 

can somebody explained what happened :)

**Comment by juergba** [comment]
@maajja please note this is an issue tracker, not a help forum.
Searching the internet you will find documentation and tons of tutorials relating to electron.
