### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by dep-dt** [mochajs/mocha#4620]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Running my `mocha` test suite returns the error `SyntaxError: Unexpected token 'export'`.

### Steps to Reproduce

`npx mocha --exit --no-warnings 'src/**/*.spec.{ts,tsx}'`

**Expected behavior:** Suites run

**Actual behavior:** [What actually happens]

```
> @cloudvox/titan-billing-dashboard@0.3.34 mocha /Users/dpeck/dt/sandbox-docker/Titan/applications/react/billing-dashboard
> mocha --exit --no-warnings 'src/**/*.spec.{ts,tsx}'


/Users/dpeck/dialogtech/sandbox-docker/Titan/applications/react/core-components/dist/index.js:1
export * from './components';
^^^^^^

SyntaxError: Unexpected token 'export'
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
  - 8.3.2 (both)
- The output of `node --version`:
  - v12.18.1
- Your operating system
  - name and version: Catalina
  - architecture (32 or 64-bit): 64
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh

\

**Comment by juergba** [comment]
@dep-dt I'm sorry, but this issues doesn't contain any content.
You are trying to run typescript files. How are you transpiling? Are you using ESModules?
Please provide required information or otherwise close this issue.

**Comment by dep-dt** [comment]
Apologies, misconfiguration on my end.
