### ISSUE TITLE
Title for root hooks

### ISSUE THREAD

**Issue by DJ-Glock** [mochajs/mocha#4621]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
This feature request is opened to solve the reporter issue: https://github.com/travisjeffery/mocha-teamcity-reporter/issues/56

**Describe the solution you'd like**
I would like to have an optional ability to set a title for any root hook, like it can be done with normal hook:

```
export const mochaHooks = async () => {
  return {
    beforeEach('Before each root hook', () => {
      console.log(`Before each`);
    }),
    afterEach('After each root hook', () => {
      console.log(`After each`);
    }),
  };
};
```

**Additional context**
I'm trying to implement the ability to mute failed tests and hooks via TeamCity. TeamCity allows to mute tests to make build green. It works fine but only if we disable the following condition: one of build steps exited with an error (e.g non-zero exit code in command line runner):
![image](https://user-images.githubusercontent.com/26511191/113586022-a7591b80-9635-11eb-9d81-e916cee88581.png)

If we do not disable it, build will be always treated as failed because mocha returns exit code > 0 if any test or hook was failed.
So we decided to switch it off. But we faced another issue - we will not be able to realize that any hook failed because it does not look as a test for TeamCity and exit code is ignored. The only way to see it is to check count of executed test. Not the best way actually. The main issue here is tests that are skipped by mocha because of hook failure. You can check mochajs/mocha#4392 issue for details
So we enabled recordHookFailures flag and faced issue https://github.com/travisjeffery/mocha-teamcity-reporter/issues/56 - a lot of tests appeared in each build.

My suggestion how to solve reporter issue - is to check root hooks title. But it required some additional development in mocha, because in current implementation there is no way to define root hooks titles.

**Comment by juergba** [comment]
> If a hook is given a named function, that name will be used if no description is supplied.

Above suggestion doesn't work?

**Comment by DJ-Glock** [comment]
@juergba that's a great thing I missed! It works! Thank you so much.

```
export const mochaHooks = async () => {
  return {
    beforeEach: [
      function myRootBeforeEach() {
        console.log(`Before each global func`);
      }
    ],
    afterEach: [
      function myRootAfterEach() {
        console.log(`After each global hook`);
      },
    ]
  };
};
```
Log:
```
##teamcity[testSuiteStarted name='Login - Login page tests.' flowId='29560']
##teamcity[testStarted name='Test 1' captureStandardOutput='true' flowId='29560']
##teamcity[testStarted name='"before each" hook: myRootBeforeEach for "Test 1"' captureStandardOutput='true' flowId='29560']
Before each global func
Test 1 OK
##teamcity[testFinished name='Test 1' duration='0' flowId='29560']
##teamcity[testStarted name='"after each" hook: myRootAfterEach for "Test 1"' captureStandardOutput='true' flowId='29560']
After each global hook
##teamcity[testSuiteFinished name='Login - Login page tests.' duration='2' flowId='29560']
```

**Comment by DJ-Glock** [comment]
So suggestion above fixes my issue. But probably feature reqeust is still a good idea for the future.
No sure if I should close it or leave for the future.

**Comment by juergba** [comment]
Ok, we leave this issue open for some time.
Btw your solution should work without using arrays as well.

**Comment by JoshuaKGoldberg** [comment]
It's been some time, over 3.5 years. Closing. 🙂
