### ISSUE TITLE
Error: Timeout of 2000ms exceeded.

### ISSUE THREAD

**Issue by DoneDeal0** [mochajs/mocha#4622]
### Prerequisites
- [ x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

I'm trying to test my controllers' methods. The methods usually interact with a mongodb database. Each time I run a test, I receive the error:

```js
"before each" hook for "return partner information":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)
```

My test looks like this:

```js
import chai from "chai";
import { UserControler } from "../controllers/user";
import connectToDatabase from "../database/connection";

before((done) => {
  connectToDatabase().then(() => done());
});

describe("UserControler", () => {
  it("findUserById", async () => {
    const res = await UserControler.findUserById("123");
      chai.expect(res.username).to.equal({ name: "lola" });
  });
});
```
The connectToDatabase function is:

```js
import Mongoose from "mongoose";

export default async function connectToDatabase() {
  try {
    return Mongoose.connect(process.env.MONGODB as string, {
      useFindAndModify: false,
      useNewUrlParser: true,
      useUnifiedTopology: true,
      useCreateIndex: true,
      autoIndex: false,
    });
  } catch (err) {
    throw new Error(err);
  }
}
```

The script to launch the test is:
```js
    "test": "mocha -r ts-node/register ./src/tests/**/*.ts --exit",
```

How to solve this issue? I basically need mocha to wait for mongodb to be connected before running the tests, hence the before() above the describe. But it doesn't work. 

I've looked everywhere but couldn't find the answer. (yes I've read the whole thread here: https://github.com/mochajs/mocha/issues/3010, but increasing the the timeout to 15s or disabling  it didn't change anything). Sorry if this has already been answered elsewhere. 

### Versions

mocha: 5.2.0
node: v15.11.0
typescript: 4.2.3

**Comment by juergba** [comment]
> "before each" hook for "return partner information":

I don't see neither a `beforeEach` hook nor a `return partner information` test in your test file.
