### ISSUE TITLE
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

### ISSUE THREAD

**Issue by ju4n23** [mochajs/mocha#4631]
I was having this issue with my code I'm currently working on for out Thesis. Can anybody help me? Will be much appreciated. This is my code: 

import mongoose from 'mongoose'
import AuthRepository from '../../../../src/auth/data/repository/AuthRepository'
import dotenv from 'dotenv'
import { expect } from 'chai'

dotenv.config()

describe ('AuthRepository', () => {
    let client : mongoose.Mongoose
    let sut: AuthRepository

    beforeEach(() => {
        client = new mongoose.Mongoose()
        const connectionStr = encodeURI(process.env.TEST_DB as string)
        client.connect(connectionStr, {
            useNewUrlParser: true,
            useUnifiedTopology: true
        })

        sut = new AuthRepository(client)
    })

    afterEach(() => {
        client.disconnect()
    })

    it('should return user when email is found', async () => {
        const email = 'juansantiago@gmole.com'
        const password = 'pass'

        const result = await sut.find(email)

        expect(result).to.not.be.empty
        
    })
})

**Comment by marcioflaviof** [comment]
I don't know if it is the best solution, but try to pass --exit  flag  

```mocha --exit```

**Comment by outsideris** [comment]
You can use [Gitter](https://gitter.im/mochajs/mocha) for usage.
