### ISSUE TITLE
Feature: interactive watch mode support

### ISSUE THREAD

**Issue by m-sureshraj** [mochajs/mocha#4649]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**

Provide a feature to interactively filter test files by filename to improve Mocha's watch mode experience. Similar to [jest-watch-typeahead](https://github.com/jest-community/jest-watch-typeahead) behavior.

**Describe the solution you'd like**
- A new option to start the Mocha in interactive watch mode. e.g. `watch-interactive` (alias `wi`)
  ```
  > mocha --watch-interactive
  ```

- Collect all the matched test files and prompts autocomplete to filter tests by file name.
  * Prompt should not display files given through --file option
  * Prompt input should accept glob pattern

- Switch to test runner view and run the filtered test files
  * Display the runner stats after each run
  * Should be able to switch back to the filter view for further filtering.

**Describe alternatives you've considered**

[mocha-watch-typeahead](https://github.com/m-sureshraj/mocha-watch-typeahead) was my initial attempt to add interactive watch support to Mocha. But I couldn't implement all the necessary functionalities due to dependency issues.

**Additional context**

Here is the initial implementation in action:

![watch-mode-demo](https://user-images.githubusercontent.com/12813750/120916884-e0f7e280-c6c9-11eb-97d7-7cd69ec60b76.gif)

**Comment by m-sureshraj** [comment]
Please use this repository to run the demo locally. https://github.com/m-sureshraj/mocha-watch-demo

**Comment by juergba** [comment]
@m-sureshraj thank you first of all, you obviously have put a great effort in this issue. I have also seen your PR.

This clearly is a nice-to-have feature and IMO should not be part of Mocha's core. We don't have the manpower to maintain such low-priority features. We should keep our `watcher` simple, small and fast and concentrate on more important features as eg. ESModules.

I will leave this issue open, for other maintainers to comment.
There are `watcher` issues to be fixed with higher priority, such as missing ESM compatibility.

**Comment by m-sureshraj** [comment]
It makes sense @juergba. Obviously, it's a nice-to-have feature.

I've been using Mocha and Jest for a while now. In watch mode, Jest provides a more engaging experience through interactive watch support. I just wanted to add that experience to Mocha's watch mode as well. But I understand it requires effort to maintain this feature.

As I mentioned before, my initial attempt was to create a tool to extend Mocha's built-in watch, but due to dependency issues, I couldn't implement the solution properly.

While implementing this feature, I've learned a few things about how Mocha works internally. Especially the current `watcher` implementation. So I hope I can help with adding ESM compatibility.

Please feel free to close this issue and the PR. :+1: 

Thanks.
