### ISSUE TITLE
Stopped working on Node.js v10.24: "Error: Not supported" caused by ESM import

### ISSUE THREAD

**Issue by alexander-fenster** [mochajs/mocha#4652]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

In `lib/esm-utils.js`, `hasStableEsmImplementation` returns `true` on Node.js v10.24.1 even though it must only return `true` on versions >= 12.22.

### Steps to Reproduce

In the cloned `mocha` repository:

```
$ node -e 'const path = require("path"); const utils = require("./lib/esm-utils"); utils.requireOrImport(path.resolve("./index.js"))'
```

**Expected behavior:** [What you expect to happen]

No error

**Actual behavior:** [What actually happens]

```
(node:22250) UnhandledPromiseRejectionWarning: Error: Not supported
    at formattedImport (/Users/fenster/repos/mocha/lib/esm-utils.js:7:31)
    at Object.exports.requireOrImport.hasStableEsmImplementation [as requireOrImport] (/Users/fenster/repos/mocha/lib/esm-utils.js:46:38)
    at [eval]:1:79
    at Script.runInThisContext (vm.js:122:20)
    at Object.runInThisContext (vm.js:329:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at evalScript (internal/bootstrap/node.js:590:27)
    at startup (internal/bootstrap/node.js:265:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

9.0.0

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
- The output of `node --version`:
- Your operating system
  - name and version:
  - architecture (32 or 64-bit):
- Your shell (e.g., bash, zsh, PowerShell, cmd):
- Your browser and version (if running browser tests):
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):

**Comment by juergba** [comment]
> In lib/esm-utils.js, hasStableEsmImplementation returns true on Node.js v10.24.1 even though it must only return true on versions >= 12.22.

We dropped support of Node v10 in Mocha v9.0.0 as a breaking change.

**Comment by alexander-fenster** [comment]
@juergba I understand that :) My point here is that if it was hard to backport the code to keep it working on Node 10, it would've been a fair deal to drop it completely and not accept any fixes. In this particular case though, it's just a matter of a small (and _correct_) fix which might keep the code working on the older versions for the time being.

Of course we'll be able to pin our workflows to 8.x (since we do need to keep supporting Node 10 for a little bit longer), but - again - I personally don't like the idea of breaking the stuff that can still work.  Up to you though :)

**Comment by juergba** [comment]
@alexander-fenster I like clear cuts, but could live with your change.

@giltayar cc

**Comment by williamdes** [comment]
I had this error on Node 12 :/
See: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#gistcomment-3762987

**Comment by williamdes** [comment]
You can see my migration to use back the module after upgrading to Mocha v9: https://github.com/sudo-bot/gh-deployer/commit/3965e27cee2bac2cd9a1e560225190d0ca51a90a

```
Error: Not supported
    at formattedImport (/mnt/Dev/@sudo/gh-deployer/node_modules/mocha/lib/esm-utils.js:7:31)
    at Object.implementationOfRequireOrImportForUnstableEsm [as requireOrImport] (/mnt/Dev/@sudo/gh-deployer/node_modules/mocha/lib/esm-utils.js:87:14)
    at Object.exports.loadFilesAsync (/mnt/Dev/@sudo/gh-deployer/node_modules/mocha/lib/esm-utils.js:71:34)
    at Mocha.loadFilesAsync (/mnt/Dev/@sudo/gh-deployer/node_modules/mocha/lib/mocha.js:467:19)
    at singleRun (/mnt/Dev/@sudo/gh-deployer/node_modules/mocha/lib/cli/run-helpers.js:125:15)
    at exports.runMocha (/mnt/Dev/@sudo/gh-deployer/node_modules/mocha/lib/cli/run-helpers.js:190:10)
    at Object.exports.handler (/mnt/Dev/@sudo/gh-deployer/node_modules/mocha/lib/cli/run.js:366:11)
    at /mnt/Dev/@sudo/gh-deployer/node_modules/yargs/build/index.cjs:443:71

```

**Comment by juergba** [comment]
@williamdes this issue is about Mocha v9 and javascript.

As far as I can see you have had your issue 12 days ago, at that time Mocha v9 hasn't been published yet.
Furthermore you are on typescript and _ts-node_, sindresorhus is explaining in his guide what has to be done in this case.
