### ISSUE TITLE
Is there a way to retry the whole spec if before hook fails?

### ISSUE THREAD

**Issue by abhinaba-ghosh** [mochajs/mocha#4658]
Quite often `before` hook contains business-critical setup that is needed for all the tests (`it` blocks). From the retry logic, it is understood that retry works for only `it` blocks and corresponding `beforeEach` and `afterEach` hooks. Looking for a workaround or guidance for retrying the full suite/spec if `before` hook fails.

**Comment by juergba** [comment]
@abhinaba-ghosh No, there is no way to re-run a failing `before` hook. You would have to reset the suite and add it to the `runner` during runtime. We don't have an public API for such tweaks.

Evt. I'm going to add the `retries` logic to `beforeEach`, and later to `before` hook as well. But this may take some weeks.

**Comment by KramskoiSergei** [comment]
@juergba Hi there! 
Could you please answer - did you add 'retry" logic for before hooks?

**Comment by laurabur** [comment]
Hello, @juergba 
I'm also interested in the progress of "retry" logic for `before` and `beforeEach` hooks. Would be really useful!

**Comment by sph3rex** [comment]
Is this part of a milestone or are there any plans to support this? It's really counter intuitive how this retry mechanism runs at this time only for beforeEach and afterEach.

**Comment by onesandzeroes-maker** [comment]
Hi @juergba, wanted to follow up on this discussion. When you mentioned there are no public APIs to reset a suite and to add to a runner, are you able to share internal api's that we can use for this? I understand the risk of this functionality changing at any given time.
