### ISSUE TITLE
Custom UI option is not passed to parallel workers

### ISSUE THREAD

**Issue by love-expressen** [mochajs/mocha#4659]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

When using the `--ui` option together with `--parallel` (and `j > 1`) the ui option is not passed to the workers. This causes errors when running test files that depend on the UI being set up in the worker executing the test.

### Steps to Reproduce

Given a test file `test-with-ui.js` using a custom UI (cakes for gherkin syntax for example)
```
Feature("Gherkin Syntax", () => {
  Scenario("Writing a simple Scenario", () => {
    Given("the UI is properly registered", () => {
      //noop
    });
    When("the test runs", () => {
      //noop
    });
    Then("some assertion", () => {
      // noop
    });
  });
});
```

And the custom UI is installed 
`npm i mocha-cakes-2`

When running it in serial mode like this, it works
```
npx mocha --ui mocha-cakes-2 ./test-with-ui.js
```

But when running it in parallel like this, it fails
```
npx mocha --ui mocha-cakes-2 --parallel -j 2 ./test-with-ui.js 
```

**Expected behavior:**
In the case above the outputs from both test runs should be the same and there should be no error thrown when running in parallel.

**Actual behavior:** 
Serial mode works and outputs:
```
 Feature: Gherkin Syntax
    Scenario: Writing a simple Scenario
      ✔ Given the UI is properly registered
      ✔ When the test runs
      ✔ Then some assertion
```

Parallel mode crashes with the error message
```
1) Uncaught error outside test suite

  0 passing (206ms)
  1 failing

  1) Uncaught error outside test suite:
     Uncaught ReferenceError: Feature is not defined
      at Object.<anonymous> (test-with-ui.js:1:63)
      at Module._compile (internal/modules/cjs/loader.js:689:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
      at Module.load (internal/modules/cjs/loader.js:599:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
      at Function.Module._load (internal/modules/cjs/loader.js:530:3)
      at Module.require (internal/modules/cjs/loader.js:637:17)
      at require (internal/modules/cjs/helpers.js:22:18)
```

**Reproduces how often:** 
100%

### Versions
mocha --version 9.0.0
node --version v14.15.1

### Additional Information
The root cause of the issue is that mocha refers to external UI:s in the options object as function pointers and not the UI identifier string. When the options object is being serialized all functions are (thankfully) ignored. This causes the mocha instance in the workers to default to the `bdd` UI. 

A simple solution would be to map back to the string representation of the setting before passing the options to serialization. I tried this locally and for my case it worked.

**Comment by love-expressen** [comment]
A simplistic take is to update `buffered-worker-pool.js` like this (I don't know the code very well so this might cause more harm than good):

```
...
const registeredInterfaces = require('../mocha').interfaces;
...
/**
   * Given Mocha options object `opts`, resolves options.ui function references back
   * into static string references that can be serialized.
   *
   * @param {Options} [opts] - Mocha options
   * @private
   * @returns {Options} Options that can be serialized without losing ui reference
   */
  static generateSerializableOptions(opts={}) {
    const interfaceIds = Object.keys(registeredInterfaces);
    const uiRefAsStaticId = interfaceIds.find(id => registeredInterfaces[id] === opts.ui);
    
    if(uiRefAsStaticId && uiRefAsStaticId !== opts.ui) {
      return {
        ...opts,
        ui: uiRefAsStaticId
      }
    }

    return opts;
  }
  
  /**
   * Given Mocha options object `opts`, serialize into a format suitable for
   * transmission over IPC.
   *
   * @param {Options} [opts] - Mocha options
   * @private
   * @returns {string} Serialized options
   */
  static serializeOptions(opts = {}) {

    if (!optionsCache.has(opts)) {
      const serializableOpts = BufferedWorkerPool.generateSerializableOptions(opts);
      const serialized = serializeJavascript(serializableOpts, {
        unsafe: true, // this means we don't care about XSS
        ignoreFunction: true // do not serialize functions
      });
...
```

**Comment by juergba** [comment]
@love-expressen Thank you.

I haven't tested, yet and I need to do some investigation first.
I think the `--ui` option is not transmitted via IPC to the worker, but read from the `argv` array. In [worker.js](https://github.com/mochajs/mocha/blob/master/lib/nodejs/worker.js#L46).
I have to do some debugging to understand why it's not working.

**Comment by rayfoss** [comment]
This may be caused by async delay features. For some reason my UI does not load when I run a test that throws before the delayed `run` function. Worse, it hides all stdout.

A weird way around it is to run a single test spec at a time.

**Comment by love-expressen** [comment]
I don't know if there are any more complex cases I'm missing, but for my case it's pretty straight forward;

- mocha options are parsed and eventually passed to [buffered-worker-pool's run method](https://github.com/mochajs/mocha/blob/master/lib/nodejs/buffered-worker-pool.js#L104)
- setting a debugger here reveals that `options.ui` is a function reference and not a string if a custom ui is used.
- later inside the `run` method the `option` is serialized and passed to the `parallel-buffered-runner`
- serialization stripps the `options.ui` property since it's a function. 
- this obviously means the ui setting is not passed to `parallel-buffered-runner` or any downstream method (like worker.js)
- I've already confirmed that passing a string as `option.ui` instead of a function reference to the `serializeJavascript` method solves my issues. See code example above.

**Comment by juergba** [comment]
@love-expressen I agree with your analysis. `ui` should be a string `mocha-cakes-2`, not a reference to `mochaCakes` function.
But I'm not happy with your solution ...

If I compare eg. the `tdd` interface, it's a string `tdd` which gets serialized. Both `tdd` and `mocha-cakes-2` are included in `Mocha.interfaces`, so why don't they behave the same way? Maybe `ui` should never be set to a function reference, and if we solve this we have a nicer solution for this issue as well.

**Comment by juergba** [comment]
In [lib/cli/run-helpers.js](https://github.com/mochajs/mocha/blob/master/lib/cli/run-helpers.js#L229):
- replacing: `opts[pluginType] = require(pluginId);`
- by: `map[pluginType] = require(pluginId);`

also works, but I still have to check further consequences.

**Comment by juergba** [comment]
@love-expressen Currently the situation is:
- user sets `ui` to a string `mocha-cakes-2`
- Mocha overwrites `ui` with a function reference to the interface
- your patch sets `ui` back to the string

There is no need to set `ui` to a function reference and by changing the two lines in _lib/cli/run-helpers.js_:
 - `ui` remains a string `mocha-cakes-2`
 - the `mochaCakes` function reference is added to `Mocha.interfaces`.
 `mocha-cakes-2` already does this on its own, but there may be other third package interfaces not adding it.

When using Mocha via API in parallel mode, this solution (neither your proposition) does not work.
```js
const Mocha = require('mocha');
const mochawesome = require('mochawesome');

Mocha.interfaces['mocha-cakes-2'] = require('mocha-cakes-2');    // has to be set manually

const mocha = new Mocha({
  reporter: mochawesome,
  ui: 'mocha-cakes-2',                 // has to be a string
  parallel: true                       // parallel mode
})

mocha.addFile('./test-with-ui.js');
mocha.run();
```

Do you agree? Are you opening a PR? Or me?

**Comment by love-expressen** [comment]
Thanks for looking into this issue properly <3

> But I'm not happy with your solution ...

I agree. Solving this properly at an earlier point if possible would be great.

> ...but there may be other third package interfaces not adding it.

I'm happy you brought this up. It's been bothering me, and I think we should aim for a solution that doesn't depend on this "hack".

I'm not sure what solution or test you're proposing to start with in a PR, so if you've got the time please open it and point me to where I can help :)
