### ISSUE TITLE
Getting original process.argv value on parallel run

### ISSUE THREAD

**Issue by don-charlie-pc** [mochajs/mocha#4669]
I just upgraded to mocha 8 and enabled a parallel run of test files. It spawns several browser windows so it's working, but now the process.argv value has changed.

How do I get the original arguments passed to the command?

Here is my .mocharc.json file:

`
{
 "timeout": 90000,
 "extension": ["ts"],
 "parallel": true,
 "jobs": 4,
 "require": [
   "./tests/config/init.ts",
 ],
 "spec": ["./tests/specs/*.ts"]
}
`

Initially, when running without parallel mode, the value of process.argv is

`
['/usr/local/Cellar/node/16.0.0_1/bin/node',
 '/Users/current/proj/node_modules/mocha/bin/mocha',
 '-r',
 '/Users/current/proj/node_modules/ts-mocha/src/index.js',
 './tests/tsconfig.json',
 '--config=./tests/.mocharc.json',
 '--headless',
];
`

When running in parallel mode, it shows as:

`
['/usr/local/Cellar/node/16.0.0_1/bin/node',
 '/Users/current/proj/node_modules/mocha/lib/nodejs/worker.js',
];
`

Which makes sense, since now the process is a worker, but I need to retrieve the original values of process.argv.

**Comment by juergba** [comment]
I don't know.
Maybe you can attach `process.argv` to `process.env`which by default should be passed to the worker process.
This could be done in Mocha's configuration file `.mocharc.js`.

**Comment by don-charlie-pc** [comment]
> I don't know.
> Maybe you can attach `process.argv` to `process.env`which by default should be passed to the worker process.
> This could be done in Mocha's configuration file `.mocharc.js`.

@juergba how do I pass that value? Could you provide an example line? Thanks!

**Comment by juergba** [comment]
`process.env.mainArgv = process.argv;`

I don't remember wether `.mocharc.js` is read only once by the main process, or by each child-process as well.
Otherwise: `process.env.mainArgv = process.env.mainArgv || process.argv;`

I haven't tested this proposition.
