### ISSUE TITLE
`@babel/register` does not work in a project with type = "module" (native ES modules)

### ISSUE THREAD

**Issue by blikblum** [mochajs/mocha#4670]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

When requiring  `@babel/register` in a node project with native ES module ("type": "module" in package.json), code is not transpiled

### Steps to Reproduce

1. Create a node project
2. Set "type" to "module" in package.json
3. Install mocha and `@babel` packages
4. Configure babel with a plugin that does not transpile ES modules
4. Create a test with ES module syntax
5. Run "mocha --require @babel/register test/*.js"

A minimal example can be found at https://github.com/blikblum/bugs/tree/master/mocha/babel-register-native-es-module

**Expected behavior:** [What you expect to happen]

Test should be transpiled by babel

**Actual behavior:** [What actually happens]

Test code is not transpiled

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 9.0.1
- The output of `node --version`:  14.6.1
- Your operating system
  - name and version: Windows
  - architecture (32 or 64-bit): 64bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): cmd
- Your browser and version (if running browser tests):
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):
"@babel/core": "^7.14.6",
    "@babel/plugin-proposal-class-properties": "^7.14.5",
    "@babel/plugin-proposal-decorators": "^7.14.5",
    "@babel/register": "^7.14.5",

### Additional Information

Its possible to workaround by converting test code and babel config to cjs as can see at https://github.com/blikblum/bugs/tree/master/mocha/babel-register-native-es-module-workaround

This seems a limitation of `@babel/register` as noted in the docs: https://babeljs.io/docs/en/babel-register

>  Note: @babel/register does not support compiling native Node.js ES modules on the fly, since currently there is no stable API  for intercepting ES modules loading.

Posting here for the record. May also be accounted as a limitation of ES modules with mocha https://mochajs.org/#current-limitations

**Comment by juergba** [comment]
@blikblum it's unclear to me why you open this issue in Mocha's repo.
You can try this package [babel-register-esm](https://www.npmjs.com/package/babel-register-esm). Then close this issue, please

**Comment by blikblum** [comment]
> @blikblum it's unclear to me why you open this issue in Mocha's repo.


> Posting here for the record. May also be accounted as a limitation of ES modules with mocha https://mochajs.org/#current-limitations

As i noted in original post is a limitation of using native ES modules with mocha. It should at least be documented.

Its a tricky error that i spent much time to discover.

By documenting it could help others.

Closing as seems maintainers does not think is important

**Comment by smhg** [comment]
@blikblum I feel your pain. In my case it was JSX not being transpiled when switching to ESM.

However common it is to involve Babel in your test setup though, it indeed has little to do with Mocha.
A [few](https://github.com/babel/babel/issues/11108#issuecomment-583610872) [comments](https://github.com/babel/babel/issues/11108#issuecomment-723427709) in a Babel issue and a [note at the bottom of the docs](https://babeljs.io/docs/en/babel-register) are the best references I could find.

I put up a [gist](https://gist.github.com/smhg/9e75eee75818e09f99011e565340f45f) describing the (current) solution in terms of JSX. But it applies to all Babel-based transpilation needs.
