### ISSUE TITLE
Naming a Variable 'package' Makes Mocha Ignore the File the Declaration Is In

### ISSUE THREAD

**Issue by lzy-106** [mochajs/mocha#4673]
By ignoring, I mean the line count & coverage report would not consider the file at all
This may be a well-known JS bad practice and need not be fixed,
but still worth noting in the docs

## Reproduction
Just write `var package = 0;`

## Environment
- Node 8.17.0
- Mocha 5.2
- Istanbul 0.4
- NYC 13.1

**Comment by juergba** [comment]
@lzy-106 I'm closing this issue. I neither understand your description nor is it reproducable.
- Node 8.17.0: is end-of-life
- Mocha 5.2: the most recent version is v9.0.1
- Istanbul 0.4: is six years old and deprecated
- NYC 13.1: the most recent version is 15.1.0
