### ISSUE TITLE
ESM problem `Cannot use import statement outside a module`

### ISSUE THREAD

**Issue by deleonio** [mochajs/mocha#4690]
### Prerequisites

- [ x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

![image](https://user-images.githubusercontent.com/6279703/126024889-65533794-8e1c-4938-a0be-53ad94dd5105.png)

### Steps to Reproduce

You need a test who use ES6 code from the node_modules. The esm does not work on `node_modules` code.

Is there any setting?! 

**Expected behavior:** transpile all and exec tests

**Actual behavior:** transpilation of node_modules code does not work, since v9

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
- The output of `node --version`:
- Your operating system
- mocha: v9.0.2
  - name and version: win10
  - architecture (32 or 64-bit): win 64
- Your shell (e.g., bash, zsh, PowerShell, cmd): cmder
- Your browser and version (if running browser tests): chrome
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):

**Comment by juergba** [comment]
@deleonio please add a sample to reproduce this issue.

There are a few things I don't understand in your description:
- `import { log } from '../helpers/log';` doesn't have this file any extension?
- `The esm does not work on node_modules code.`: which esm? Are you talking about the `esm` package or Node's native ESM support?
- `transpile all and exec tests`: what transpilation? Mocha does not run any transpilation, and has never done.

**Comment by deleonio** [comment]
Checkout this repo (pachages/form/), upgrade only mocha and remove esm from .mocharc.js

https://github.com/leanupjs/leanup/tree/release/1.2/packages/form

**Comment by juergba** [comment]
@deleonio Let me clarify a few things ...

It's not my task to solve your problems, it's yours. You haven't spend many minutes in investigating as can be seen in your superficial issue description. And you haven't answered my questions.

A few inputs for you:
- the `esm` package is abandonded, see duplicate # 4671. You (not me, nor Mocha) will have to migrate to Node's native ESM.
- where do you transpile your `ts` files?
- _tsconfig.json_: `"target": "ES2015"` you will have to investigate the implications of this.
- `"@types/mocha": "8.2.3"`: Type definitions for mocha 8.2, not for v9. This may cause problems, I don't know.

**Comment by deleonio** [comment]
Okay @juergba - you are right! Now I spent more time and prepare a ref repo.

See diff: https://github.com/deleonio/mocha-v9/pull/1/files

Advice: `npm i` runs postinstall `npm test`

- I use `esbuild-register`, to transpile the code - (works with v8 / works not with v9)
- I used the `esm` module with v8 / I removed the `esm` module for v9
- I removed the `@types/mocha` for v9

**Comment by deleonio** [comment]
@juergba 

Is it documented, that dependent modules must configure as `type: "module"`.

With **v8** it is not required - But with **v9**.

After I add `type: "module"` to the dependent @leanup/lib package.json - it works fine!

THX!!!

**Comment by juergba** [comment]
> Is it documented, that dependent modules must configure as type: "module".
With v8 it is not required - But with v9.

You had to set `"type": "module"` in _package.json_ because you removed the `esm` package. No matter if Mocha v8 or v9.

**Comment by hefeng6500** [comment]
> @deleonio Let me clarify a few things ...
> 
> It's not my task to solve your problems, it's yours. You haven't spend many minutes in investigating as can be seen in your superficial issue description. And you haven't answered my questions.
> 
> A few inputs for you:
> 
> * the `esm` package is abandonded, see duplicate # 4671. You (not me, nor Mocha) will have to migrate to Node's native ESM.
> * where do you transpile your `ts` files?
> * _tsconfig.json_: `"target": "ES2015"` you will have to investigate the implications of this.
> * `"@types/mocha": "8.2.3"`: Type definitions for mocha 8.2, not for v9. This may cause problems, I don't know.

haha, Grumpy

**Comment by mattgodbolt** [comment]
I've just hit this issue too; a third party library I used before with v8 breaks in v9 with `SyntaxError: Cannot use import statement outside a module`. I'm transpiling with `webpack` in my case (or trying to!)
