### ISSUE TITLE
Is there a way to convert JSON result to HTML?

### ISSUE THREAD

**Issue by emutime** [mochajs/mocha#4696]
I'm using Mocha in a js binding environment, which embedded a V8 engine，not the node environment. 
I have done some adaptation work for it，and get the json result.
then, i want to convert the JSON result to HTML in the desktop side. but i can't find a way.
Any help will be appreciated!

**Comment by juergba** [comment]
@emutime There is a third-party reporter _Mochawesome_ which produces JSON and converts the result into HTML. I don't know wether that helps. We dont' have plans to implement our own JSON => HTML converter, this is way out-of-scope.
