### ISSUE TITLE
just a little typo in SERIAL MODE tutorials

### ISSUE THREAD

**Issue by joielee09** [mochajs/mocha#4698]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

I think I found a typo in mocha docs.
https://mochajs.org/#serial-mode
```
If not, Mocha ignores any exports of a --require’d module
```

### Steps to Reproduce
No need

### Versions
No need

### Additional Information

Thanks!

**Comment by joielee09** [comment]
https://github.com/mochajs/mocha/pull/4699

**Comment by juergba** [comment]
closing, see comment in PR.
