### ISSUE TITLE
nps not working

### ISSUE THREAD

**Issue by joielee09** [mochajs/mocha#4700]
### Prerequisites

- [ ] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

While following [the contributing code](https://github.com/mochajs/mocha/blob/master/.github/CONTRIBUTING.md#shoe-contributing-code-step-by-step)  got this error when I 'npm start test' and all the other scripts using nps not working.  I checked the link mentioned in exit code 1 in error statement, and it says I can try npm run without nps, so I tried test with ./bin/mocha. It works, but still nps is not working. 

Besides, when I tried ./bin/mocha I got 'expect.it is not a function' error. Is this a bug or is there other way to run test on mocha?
For short, I want to make contribution but found error when run test. 

Thanks for your time!

```
$ npm start test

> mocha@9.0.2 start D:\mocha
> nps "test"

nps is executing `test` : nps lint test.node test.browser
The script called "test" which runs "nps lint test.node test.browser" failed with exit code 1 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mocha@9.0.2 start: `nps "test"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mocha@9.0.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

### Steps to Reproduce

Followed the Contributing Code.

**Expected behavior:** [What you expect to happen]
**Actual behavior:** [What actually happens]
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:  9.0.2
- The output of `node --version`:  v12.18.3
- Your operating system
  - name and version: Window10
  - architecture (32 or 64-bit): 64
- Your shell (e.g., bash, zsh, PowerShell, cmd): git bash
- Your browser and version (if running browser tests): chrome latest
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):

**Comment by joielee09** [comment]
if needed I would be happy to make a pull request

**Comment by juergba** [comment]
@joielee09 I have been developping on Windows for years and can't confirm your issue.

When you install Mocha with `npm install`, you are using the package `npm`. Sometimes `npm` fails to create the `node_modules/.bin` folder correctly which may cause your error. This is a `npm` issue then, probably there has no entry been created for `nps` in the `.bin` folder.

In general please note, this is an issue tracker, not a help forum. We have a gitter chanel where you can try to get help. Please be creative, opening issues/PRs for everything (as for single letter typos) is not really helpful. Thank you.

For your `nps` problem: install a higher version of Node/npm as LTS 14.17.3 and try again.
