### ISSUE TITLE
Grep function randomly skips tests

### ISSUE THREAD

**Issue by TAVkiev** [mochajs/mocha#4704]
### Description

Probably this issue is my specific, but this behavior is strange  related to grep by regex. I am using mocha programmatically.
when I am using "grep" function.

The the problem is in this method:
`var match = self._grep.test(test.fullTitle());`
(node_modules\mocha\lib\runner.js )

This method outputs false, while it should be true, but only for some 'it' (tests). My describe has 2 it, one is passed, the other not visible because of condition 'false'.

Example:
this one 'it' visible:
'this is some description @testing, @testing-smoke Ensure dashFeeSensitivity exist'
while this 'it' not:
'this is some description @testing, @testing-smoke Ensure dashMaxFloor exist'

bot of them should return 'true', but within mocha, the second example returns 'false':
/@testing |@testing$|@testing-smoke |@testing-smoke$/g.test('this is some description @testing @testing-smoke Ensure dashFeeSensitivity exist')
/@testing |@testing$|@testing-smoke |@testing-smoke$/g.test('this is some description @testing @testing-smoke Ensure dashMaxFloor exist')

for testing purpose (I know my regex),  I changed ` self._grep` on `/@testing |@testing$|@testing-smoke |@testing-smoke$/g` and it works

### Versions

mocha - 8.4.0
node - 14.16.0, 10.15.3
OS - windows 10, 64
@babel/core - 7.8.4

**Comment by juergba** [comment]
@TAVkiev can you add a small test example, please?
Consisting of two files, one test and another containing the programmatic part.
Thank you.

**Comment by TAVkiev** [comment]
@juergba Hay, I added those files as small git project
https://github.com/TAVkiev/mocha-grep-issue

From 3 tests only one is running

**Comment by juergba** [comment]
@TAVkiev yes, thats' a weird case! It's the **global flag** `g` which produces this `true/false` flipping.
```js
let reIgnore = /a/g;

console.log(reIgnore.test("a")); // true
console.log(reIgnore.test("a")); // false
console.log(reIgnore.test("a")); // true
console.log(reIgnore.test("a")); // false
```

see [docs: mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test#using_test_on_a_regex_with_the_global_flag)
```
Using test() on a regex with the "global" flag
When a regex has the global flag set, test() will advance the lastIndex of the regex. (RegExp.prototype.exec() also advances the lastIndex property.)

Further calls to test(str) will resume searching str starting from lastIndex. The lastIndex property will continue to increase each time test() returns true.

Note: As long as test() returns true, lastIndex will not reset—even when testing a different string!
```
Remove the global flag, then it works:
- `var mocha = new Mocha().grep(/@smoke |@smoke$/);`
- or via Mocha constructor: `var mocha = new Mocha({grep: /@smoke |@smoke$/});`

Thank you for your issue and test example. I will open a PR and fix it.

**Comment by TAVkiev** [comment]
Indeed, loveliest regex :)
Thanks for your reply, in my case /g flag is really redundant, 'tag' should be only one
