### ISSUE TITLE
In parallel mode, the `afterEach` and `afterAll` hooks get executed before the test is completely finished

### ISSUE THREAD

**Issue by vaidkaran** [mochajs/mocha#4705]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description
When running in parallel mode (with `--parallel true`) the `afterEach` and `afterAll` hooks invoke before the test is completely finished.

### Steps to Reproduce
I created a small project which just has 2 test files.

tests/test1.spec.js
```
describe('mocha test 1', async () => {
  it('should log a message on the console', () => {
    console.log('----------- test1 ------------');
  });
});
```

tests/test2.spec.js
```
describe('mocha test 2', async () => {
  it('should log a message on the console', () => {
    console.log('----------- test2 ------------');
  });
});
```

globalHooks.js
```
exports.mochaHooks = {
  beforeAll: (done) => {
    console.log('------- beforeAll ------')
    done();
  },
  beforeEach: (done) => {
    console.log('------- beforeEach ------')
    done();
  },
  afterEach: (done) => {
    console.log('------- afterEach ------')
    done();
  },
  afterAll: (done) => {
    console.log('------- afterAll ------')
    done();
  },
}
```

Running mocha in serial with command: `./node_modules/.bin/mocha tests/ --require ./globalHooks.js --parallel false`
gives expected results (the "------- afterEach ------" gets printed after the test is completely finished)

console output:
```
------- beforeAll ------
  mocha test 1
------- beforeEach ------
----------- test1 ------------
    ✔ should log a message on the console
------- afterEach ------

  mocha test 2
------- beforeEach ------
----------- test2 ------------
    ✔ should log a message on the console
------- afterEach ------

------- afterAll ------

  2 passing (5ms)
```

But when running mocha in parallel using the command: `./node_modules/.bin/mocha tests/ --require ./globalHooks.js --parallel true`
the "------- afterEach ------" gets printed after the test is completely finished

console output:
```
------- beforeAll ------
------- beforeEach ------
----------- test1 ------------
------- afterEach ------
------- afterAll ------

  mocha test 1
    ✔ should log a message on the console

------- beforeAll ------
------- beforeEach ------
----------- test2 ------------
------- afterEach ------
------- afterAll ------

  mocha test 2
    ✔ should log a message on the console


  2 passing (160ms)
```

**Expected behavior:** In the parallel mode, I expect the afterEach to run after the test has finished (just like when running tests in serial). And "------- afterEach ------" and "------- afterAll ------" would show up after the "✔ should log a message on the console".

**Actual behavior:** In parallel mode, the afterEach and afterAll get printed before  "✔ should log a message on the console".

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions
Node version: "14.16.1"
Mocha version: "9.0.3"

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
- The output of `node --version`:
- Your operating system
  - name and version:
  - architecture (32 or 64-bit):
- Your shell (e.g., bash, zsh, PowerShell, cmd):
- Your browser and version (if running browser tests):
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):

**Comment by juergba** [comment]
In serial and in parallel mode the hooks are **executed** in correct order.
In parallel the stream of your `console.log()`'s has to be buffered in each worker and to be sent to the main branch when the job is done. The output of serial and parallel test runs will therefore never look the same.
