### ISSUE TITLE
mochaGlobalSetup fails because of timeout

### ISSUE THREAD

**Issue by ntr-808** [mochajs/mocha#4708]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

mochaGlobalSetup hook fails with timeout on runs after the initial in watch mode

### Steps to Reproduce

set up tests with a mochaGlobalSetup (ours is async) that takes > 2000ms to complete and use watch mode

**Expected behavior:** 

either that the setup will not fail because of a timeout or that `this.timeout(n)` can be used to specify how long the setup should take.

**Actual behavior:** [What actually happens]

```
  29 passing (2s)

 [mocha] waiting for changes...


  1) "before all" hook in "{root}"

  0 passing (2s)
  1 failing

  1) "before all" hook in "{root}":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 9.0.3
- The output of `node --version`: v14.15.3
- Your operating system
  - name and version: Ubuntu 20.04
  - architecture (32 or 64-bit): 64bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): bash
- Your browser and version (if running browser tests):
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): TypeScript 4.3.5

### Additional Information

```
module.exports = {
  extension: ["ts"],
  spec: "src/**/*.test.ts",
  require: ["ts-node/register", './src/test.utils.ts'],
};
```

**Comment by juergba** [comment]
@ntr-808 you can use `this.timeout(t)` in `mochaGlobalSetup` as in any other hook as well, unless you are using arrow functions which don't bind their own `this`.

Please add a test example, thank you.

**Comment by ntr-808** [comment]
Here is a gist example with corresponding error:

https://gist.github.com/ntr-808/39d7147dfc498886c67de8a8ab7b4942

```
~/code/mocha-gub on master -> npm t

> mocha-gub@1.0.0 test
> mocha

(node:63532) UnhandledPromiseRejectionWarning: TypeError: this.timeout is not a function
    at Runner.mochaGlobalSetup (/home/ntr/code/mocha-gub/setup.ts:2:10)
    at Mocha._runGlobalFixtures (/home/ntr/code/mocha-gub/node_modules/mocha/lib/mocha.js:1267:21)
    at Mocha.runGlobalSetup (/home/ntr/code/mocha-gub/node_modules/mocha/lib/mocha.js:1227:5)
    at runAsync (/home/ntr/code/mocha-gub/node_modules/mocha/lib/mocha.js:1069:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:63532) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:63532) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by juergba** [comment]
@ntr-808 thank your for your gist example.
- you are mentioning `mochaGlobalSetup` in your issue description.
At the same time you are listing an error message: `1) "before all" hook in "{root}":`. 
This isn't possible, `mochaGlobalSetup` does not register any hooks. Your sample doesn't reproduce this error either.
- `mochaGlobalSetup` doesn't check for timeouts. Even changing your sample to 20s, it does not timeout. It's correct that `mochaGlobalSetup` doesn't know `this.timeout()`, and there is no need to do so.

> you can use `this.timeout(t)` in `mochaGlobalSetup` as in any other hook as well [...]

I was wrong about that, sorry. `mochaGlobalSetup` does not register any hook.

**Comment by ntr-808** [comment]
Did you try the gist repo?

```
~/code -> git clone https://gist.github.com/ntr-808/39d7147dfc498886c67de8a8ab7b4942
Cloning into '39d7147dfc498886c67de8a8ab7b4942'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 15 (delta 2), reused 12 (delta 2), pack-reused 0
Unpacking objects: 100% (15/15), 21.51 KiB | 1.13 MiB/s, done.
~/code -> cd 39d7147dfc498886c67de8a8ab7b4942/
~/code/39d7147dfc498886c67de8a8ab7b4942 on master -> npm i

added 104 packages, and audited 105 packages in 3s

19 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
~/code/39d7147dfc498886c67de8a8ab7b4942 on master* -> npm t

> mocha-gub@1.0.0 test
> mocha

(node:82827) UnhandledPromiseRejectionWarning: TypeError: this.timeout is not a function
    at Runner.mochaGlobalSetup (/home/ntr/code/39d7147dfc498886c67de8a8ab7b4942/setup.ts:2:10)
    at Mocha._runGlobalFixtures (/home/ntr/code/39d7147dfc498886c67de8a8ab7b4942/node_modules/mocha/lib/mocha.js:1267:21)
    at Mocha.runGlobalSetup (/home/ntr/code/39d7147dfc498886c67de8a8ab7b4942/node_modules/mocha/lib/mocha.js:1227:5)
    at runAsync (/home/ntr/code/39d7147dfc498886c67de8a8ab7b4942/node_modules/mocha/lib/mocha.js:1069:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:82827) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:82827) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It quite clearly reproduces the issue.

**Comment by ntr-808** [comment]
The watch issue I mentioned above seems to have been resolved somehow, I will have to investigate further.
Thanks for your time and patience.
