### ISSUE TITLE
mocha-jenkins-reporter in parallel mode does not work

### ISSUE THREAD

**Issue by srknzl** [mochajs/mocha#4710]
As stated in https://mochajs.org/#limited-reporter-api-for-third-party-reporters, I am filing an issue.

mocha-jenkins-reporter in parallel mode does not work but in serial mode works

**Comment by juergba** [comment]
@srknzl Sorry, but this is an blank issue. What shall I do with "it does not work"?

**Comment by asztal** [comment]
This is a bug in mocha-jenkins-reporter which I have fixed and submitted a PR for.
https://github.com/juhovh/mocha-jenkins-reporter/pull/95

It's not yet in a released version, as far as I know.

**Comment by juergba** [comment]
@asztal thank you.

**Comment by srknzl** [comment]
Yeah sorry I forgot to enter the details. The issue was the one fixed in the PR. Thanks!
