### ISSUE TITLE
Showing the time(ms) for each Mocha test

### ISSUE THREAD

**Issue by sorin21** [mochajs/mocha#4712]
I started to learn Mocha and I see that for each test I don't see the time. I see only the total time for all tests.

I searched, asked people, try different things, but I guess you have a bug or I didn't find the right thing in your docs.

I searched in your docs a lot but I didn't find command to show time for each test in terminal.

On the [stackoverflow](https://stackoverflow.com/questions/68692816/how-to-show-in-terminal-the-time-for-each-mocha-test-using-mongoose-code) I have this question with all details.

On the above link you can see a screenshot with my tests in terminal, to understand better what I say.

If someone knows this please tell me, is there any command for this already? Or your code has a bug and doesn't ouput the time for each test.

I run all the code on windows OS.

**Comment by juergba** [comment]
Which Mocha version?

**Comment by sorin21** [comment]
"mocha": "^9.0.3",
"mongoose": "^5.13.5"

**Comment by juergba** [comment]
The default reporter `spec` doesn't show times per test, but:
- you can set the `--slow` option to zero: `--slow 0`
- or use a different reporter, eg:`list`: `--reporter list`
- or develop your own reporter, later when you have acquired advanced skills

**Comment by sorin21** [comment]
Oooo, I see now. I had now ideea that putin slow to zero will ouput the time for each test.
```
"scripts": {
      "start:test": "mocha  test/ --slow 0 --recursive --exit",
      "test": "nodemon --exec \"npm run start:test\""
  },
```


Works fine with reporter list, too

"scripts": {
      "start:test": "mocha  test/ --reporter list --recursive --exit",
      "test": "nodemon --exec \"npm run start:test\""
  }


Thank you very much @juergba
