### ISSUE TITLE
Expected and Actual Result for Passed Test Cases

### ISSUE THREAD

**Issue by Jabran-dev** [mochajs/mocha#4713]
Hi,

Can you please tell if we can console the expected and actual output of **Passed** test case? The mocha library only shows expected and actual output for failed test case. Is there a way that we can console expected and actual output for Passed test case? Your help will be highly appreciated, thanks

**Comment by juergba** [comment]
Mocha gets `actual` and `expected` from the error object, when a test assertion fails.
When a test passes, there is no error object. So no, Mocha does not print those values to the console.
You have to print that data yourself, in case of a positve test => `actual === expected`, so there is no need to print both values.

Please note, this is an issue tracker, not a help forum. You can try to get support on our [gitter chanel](https://gitter.im/mochajs/mocha). Thank you.
