### ISSUE TITLE
dynamically generating tests doesn't work with tdd (works with bdd)

### ISSUE THREAD

**Issue by asklar** [mochajs/mocha#4715]
### Prerequisites

- [X] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [X] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [X] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [X] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

I have a `suite` that generates `test`s, mocha is configured with `tdd`. When I run the tests in vscode, they are properly discovered.
However when I run them on the command line, no tests are dynamically added.

However if I change mocha's config to `bdd`, change `suite` to `describe` and `test` to `it`, then everything starts working.

### Steps to Reproduce

This works:

```ts

	const mocha = new Mocha({
		ui: 'bdd',
		color: true
	});
// ...

describe('foo', () => {
  [1,2,3,4].forEach(i => { it(i, () => {
     assert(i);
  } });
});
```

This doesn't:

```ts

	const mocha = new Mocha({
		ui: 'tdd',
		color: true
	});

// ...

suite('foo', () => {
  [1,2,3,4].forEach(i => { test(i, () => {
     assert(i);
  } });
});
```

**Expected behavior:** tests are added dynamically for tdd too

**Actual behavior:** "0 tests passed"

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 8.1.1
- The output of `node --version`: v14.16.0
- Your operating system 
  - name and version: Windows
  - architecture (32 or 64-bit): 64
- Your shell (e.g., bash, zsh, PowerShell, cmd): powershell
- Your browser and version (if running browser tests): n/a
- Any third-party Mocha-related modules (and their versions): n/a
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): TS 4.2.2

**Comment by juergba** [comment]
```js
const assert = require('assert');
suite('foo', () => {
  [1,2,3,4].forEach(i => { test(i + "", () => { assert(i); });});
});
```
@asklar `node bin/mocha --ui tdd ../test.js` is working perfectly.

I don't know why you are trying to squash "Mocha via Interface" and "Mocha via API" into one mess.
It's just one way or the other.
