### ISSUE TITLE
Unsupported `'no-timeout': true` option in example configs

### ISSUE THREAD

**Issue by radimbuchtela** [mochajs/mocha#4717]
The `'no-timeout': true` option described inside example .mocharc.js doesn't work.
https://github.com/mochajs/mocha/blob/09ffc30b43db53b0cb3f54670132270271d8fe97/example/config/.mocharc.js#L41
Other options like `timeout: false` or `timeout: 0` work correctly.

I suggest removing the note about `'no-timeout': true` option from example config files.

**Comment by juergba** [comment]
@radimbuchtela I agree, it's not working in config files.

The `timeout` option is `typeof string`, and the negation does not work. Mocha doesn't have an option named `no-timeout`.
Weird enough, on the CLI `--no-timeout` is working and `timeout` is set to zero. It seems to be some weirdness of _yargs-parser_ I don't want to rely on in future.

I will remove `no-timeout` from our config file samples and our docs.
Thanks for filing this issue.
