### ISSUE TITLE
Retry timeouts only 

### ISSUE THREAD

**Issue by gita-codaio** [mochajs/mocha#4722]
I would like to propose a flag that when used with retries it would only retry on timed out tests. This would help with retrying only flakey tests.

**Comment by juergba** [comment]
@gita-codaio thank you for your proposition.

I don't think we need such a granular configuration on CLI/config file  level. On flaky tests you can set `retries`:
- `it('flaky test', async function() { this.retries(2) });`
- `it('flaky test', async function() {  })retries(2);`
