### ISSUE TITLE
Custom error filename and stack track location

### ISSUE THREAD

**Issue by ghost** [mochajs/mocha#4725]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
I am validating JSON using Mocha, which makes a failed assert's contextual information more or less useless.
I have all the diagnostics information for the JSON. It's just a problem of reporting it in Mocha.

**Describe the solution you'd like**
I'd like to have a way to report a custom file and line number in Mocha.

**Describe alternatives you've considered**
Leaving it as a failed TypeScript assert gives no information about the JSON failure.
Using `console.log` won't give it a native look and could trigger linter warnings.

**Comment by outsideris** [comment]
Throwing your diagnostics and line number does not help your problem? 
I don't think I fully understand your needs. But you may need [a custom reporter](https://github.com/mochajs/mocha/wiki/Third-party-reporters).

**Comment by SNDST00M** [comment]
https://github.com/SNDST00M/starfall-visual-studio-code/blob/5e2c834/themes/test/suite/starfall-color-theme.test.ts

**Comment by JoshuaKGoldberg** [comment]
`status: waiting for author` on a deleted account. Okie dokie.
