### ISSUE TITLE
Compatibility with LiveScript

### ISSUE THREAD

**Issue by ghost** [mochajs/mocha#473]
LiveScript is using _it_ as a placeholder for the first argument passed to a function:

```
greet = -> console.log "#{it.name}"
greet name: "Peter"
```

And since Mocha uses _it_ inside a function that collides with LiveScript.

I get:

```
TypeError: undefined is not a function
```

since there is no argument passed to _describe_.

Perhaps _it_ could be put in _this_ so we could do:

```
@it "should ..." ->
```

Please help us LiveScripters use Mocha!

**Comment by raine** [comment]
Another workaround I've seen is

```livescript
describe 'foo' (_) ->
  it 'bar' ->
    assert true
```

**Comment by blvz** [comment]
@raine
```LiveScript
describe 'foo' (...) ->
  it 'bar' ->
    assert true
```
