### ISSUE TITLE
ReDoS in /scripts/update-authors.js

### ISSUE THREAD

**Issue by DangKhai0x21** [mochajs/mocha#4731]
## Summary:

In [/scripts/update-authors.js#L42](https://github.com/mochajs/mocha/blob/master/scripts/update-authors.js#L42) using evil regex `(^Author:|^Co-authored-by:)\s+(?<author>[^<]+)\s+(?<email><[^>]+>)` leads to DoS.

## Step to reproceduce:
Using compile code js to run code bellow:
```
let regex = /(^Author:|^Co-authored-by:)\s+(?<author>[^<]+)\s+(?<email><[^>]+>)/
t = performance.now()
regex.test('Author:' + ' '.repeat(3456))
console.log(performance.now() - t) // about 12 seconds
```

As you can sees the code to response about 12 seconds to parse input.

## Impact:

DoS services.

**Comment by juergba** [comment]
@DangKhai0x21 _scripts/update-authors.js_ is an internal script used every few weeks while preparing a new release.
Can you explain, how this supposed ReDoS attack would take place, please?

**Comment by DangKhai0x21** [comment]
The regex can match with `space character` by **\s+**, so an unterminated with start `Author:   ` containing n spaces will cause js regex engine to backtrack to try `2^n` states in the `NFA` . So, This causes the cpu to have to do many loops to find the last terminator of the regex string.

For example:
* First case, i use correct input correct match regex : `Author: dangkhai0x21 <dangkhai0x21@gmail.com>` :

![image](https://user-images.githubusercontent.com/32236617/130743700-72c7f85e-4bbf-46d3-851a-054cad86d24a.png)

Just process 23 steps to catch a string match.

* Second case, incorrect input: `Author:         [space]*30                    dangkhai0x21 <dangkhai0x21@gmail.com`

![image](https://user-images.githubusercontent.com/32236617/130744052-8bde6456-2c9c-450b-a299-5c2cce9b15f5.png)

Need 2509 step to finish the regex process.

You can use [regex101.com/debugger](https://regex101.com/debugger) to check other cases yourself.

**Comment by juergba** [comment]
The input data we use in this script, are retrieved from github. So your are saying, the github guys are potentially bad and could attack my local computer, if I run this script. Right?

**Comment by juergba** [comment]
@DangKhai0x21 thank you for this issue.

I dont't see how/why anybody could change Mocha's commit history in order to manipulate commit authors' data. I don't share your concerns, therefore I'm closing this issue.
