### ISSUE TITLE
Massive decrease in performance after updating from `v9.0.3` to `v9.1.0` (test executions are very slow)

### ISSUE THREAD

**Issue by ceisele-r** [mochajs/mocha#4732]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

We execute Selenium tests with mocha.
After updating from `v9.0.3` to `v9.1.0` yesterday, the test execution performance decreased massively:
* A test batch that prior to the update took ~9 minutes, after the update takes ~25 minutes
* A test batch that prior to the update took ~12 minutes, after the update takes ~28 minutes

### Steps to Reproduce

Use mocha `v9.1.0` -> performance is bad
Downgrade mocha to `v9.0.3` -> performance is normal again

**Expected behavior:** [What you expect to happen]
Performance in `v9.1.0` to equal the performance in `v9.0.3`.

**Actual behavior:** [What actually happens]
Performance is decreased massively after updating.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
Confirmed through multiple executions on "fresh" Github Action machines.
Confirmed the issue goes away after downgrading to `v9.0.3` and executing the tests again.

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: v9.1.0 (after update) and v9.0.3 before
- The output of `node --version`: `14.17.5`
- Your operating system
  - name and version: Ubuntu 20.04.2
  - architecture (32 or 64-bit): 64
- Your shell (e.g., bash, zsh, PowerShell, cmd): bash
- Your browser and version (if running browser tests): N/A
- Any third-party Mocha-related modules (and their versions): `ts-mocha v8.0.0`, `mocha-junit-reporter: v2.0.0`, `mochawesome: 6.2.2`
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): `typescript v4.3.5`.

### Additional Information

This is how we execute the tests:
`executetestbatch_1.js`
```
const Runner = require("mocha/lib/runner");
const { filterSuite } = require("./executetestbatchhelper");

const originalRun = Runner.prototype.run;

const batchID = 0;
const numberOfGroups = 3;

Runner.prototype.run = function (done) {
  // Filter tests to only include Tests in current batch
  this.suite.suites.forEach((suite) => filterSuite(suite, numberOfGroups, batchID)); //// <------ This just filters to a subset

  // Execute tests
  originalRun.call(this, done);
};
```

The command line is basically
`"test:e2e:pipeline:batch1": "npm run test:e2e:pipeline -- -- -- --require ./src/test/executetestbatch_1.js",` <-- gets executed
`"test:e2e:pipeline": "cross-env CI=true npm run selenium -- -- --bail --reporter mochawesome --reporter-options reportDir=testreports,reportFilename=SeleniumTestReport",`
`"selenium": "cross-env HOTRELOAD=no ts-mocha \"./src/**/*.roxselenium.ts\" --exit --recursive --timeout 120000 --retries 2"`

I unfortunately don't know where to start to further investigate what is causing this performance decrease. If anyone could give me any hint, I would appreciate it.
Since we isolated that the issue really comes from the update (and is good again after downgrading), I guess either something in `mocha` changed or there is now an incompatibility (/performance decrease) when the new mocha is being used with third-party related modules (e.g. `ts-mocha`).

**Comment by ceisele-r** [comment]
Unfortunately, I have to reopen this.
It seems I did something wrong when testing it "positive" after removing `ts-mocha` as I've written in my previous post.

Even after we now permanently removed `ts-mocha` from the scripts and just execute `mocha`, after updating to `9.1.1` or `v9.1.1` the performance drops again.

Reproducibly, after downgrading then to `v9.0.3`, the old performance is restored (it's fast again).

@juergba do you have any other idea where I could take a look at or how to further debug this?
I'm trying to isolate the area where it comes from.

**Comment by juergba** [comment]
@ceisele-r You have to narrow down the issue, wether TS or ts-loader or selenium or custom reporter or mocha.

With a small sample to reproduce I can have a look. Mocha has been blamed several times the past few weeks, for issues with TS plus ESM and Yarn pnp. Mocha has proven as innocent as a virgin.
You have the lead for the moment. Without a sample ...

**Comment by ceisele-r** [comment]
@juergba yeah, of course, I understand that. I will try to narrow it further down to see where the issue comes from.

**Comment by ceisele-r** [comment]
@juergba I think I found the issue.

As written above, we are splitting our tests in 3 batches that are then executed in parallel on separate machines (each machine executes 1 batch).

As mentioned above, the code to filter and execute the individual batches looks like this:
`executetestbatch_1.js`:
```javascript
const Runner = require("mocha/lib/runner");
const { filterSuite } = require("./executetestbatchhelper");

const originalRun = Runner.prototype.run;

const batchID = 0;
const numberOfGroups = 3;

Runner.prototype.run = function (done) {
  // Filter tests to only include Tests in current batch
  this.suite.suites.forEach((suite) => filterSuite(suite, numberOfGroups, batchID));

  // Execute tests
  originalRun.call(this, done);
};
```
`executetestbatchhelper.js`:
```javascript
const murmurhash = require("murmurhash");

/**
 * Recursively iterates through all suites & tests in the given suite and removes tests from test batch that are not in the given batchID based on their test title
 * @param {Mocha TestSuite} suite The test suite to filter (usually the root mocha test suite)
 * @param {number} numberOfGroups The total number of test batches
 * @param {number} batchID The ID of the current batach
 */
exports.filterSuite = (suite, numberOfGroups, batchID) => {
  console.log(`Handling suite: ${suite.title}`);

  console.log(`Tests: ${suite.tests.length}`);
  // Determine whether each test in the current suite should be included in the current test batch
  const filteredTests = suite.tests.filter((test) => {
    console.log(`Test title is: ${test.title}`);
    const hash = murmurhash.v3(test.title);
    // console.log(`Test's hash is ${hash}, testing against group ${batchID} out of ${numberOfGroups} groups`);
    const modulo = hash % numberOfGroups;
    // console.log(`Test's modulo: ${modulo}`);
    const isInTestGroup = modulo === batchID;
    if (isInTestGroup) {
      // console.log("Test is in Test group");
      return true;
    } else {
      // console.log("Test is NOT in Test group");
      return false;
    }
  });
  // console.log(`Reduced tests in this batch to ${filteredTests.length} (was original ${suite.tests.length})`);

  // Set tests in this group to all tests that should be included in test batch
  suite.tests = filteredTests;

  // console.log(`Suites: ${suite.suites.length}`);
  suite.suites.forEach((subSuite) => {
    // Recursively filter all sub-suites in the current suite
    this.filterSuite(subSuite, numberOfGroups, batchID);
  });
};
```

So the thing is, since mocha `v9.1.0`, the `filterSuite(...)` seems to no longer be executed at all (`console.log` statements are no longer logged).
=> This means that the tests are not filtered and therefore all test batches contain all tests and therefore naturally take the total duration of all tests (~23 minutes).

When downgrading to mocha `v9.0.3`, the `console.log` messages (like `Handling suite: ...`) reappear and the filtering works correctly.

Actually it seems that the overwritten `Runner.prototype.run = function (done) {...}` is no longer executed at all/overwriting no longer works as it used to be.
I looked through mochas commit history but could not find any commit that could relate to this.

Could you think of any change that could affect the way we are overwriting `Runner.prototype.run`?

**Comment by juergba** [comment]
You have to check wether the `--require` works correctly, called with several `npm ... -- -- --`.
Set some nonsense file name and you should get an error.

**Comment by ceisele-r** [comment]
@juergba thank you so much, this was it. I had to remove one `--`...

I don't know why this suddenly had to be changed now as we did not change something other than updating mocha, but it's working now again and I have something to keep in mind for the future.

Thanks again!
