### ISSUE TITLE
 Cannot find module

### ISSUE THREAD

**Issue by KingDracula** [mochajs/mocha#4738]
![image](https://user-images.githubusercontent.com/13584613/132005524-b9cf0dfb-d6d3-4ac7-b732-d3cb29a37ff0.png)
when i use the vscode auto import module , 
This code runs well in the program
npm run mocha it has error 
![image](https://user-images.githubusercontent.com/13584613/132005697-ac8d005e-84cc-429e-a615-1a044c714b8e.png)
how to config this to fix it 

Thanks

**Comment by juergba** [comment]
@KingDracula please note, this is an issue tracker, not a help forum. You can try to get support on our [gitter](https://gitter.im/mochajs/mocha) chanel.
