### ISSUE TITLE
"node-option" is mandatory in config file

### ISSUE THREAD

**Issue by cyrilverloop** [mochajs/mocha#4739]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Hi,

Since Mocha 9.1.0, when i launch my tests, i have the error message : `Error: No test files found`.
Adding `"node-option": [],` in my `.mocharc.json` configuration file seems to solve the problem.
It seems that Mocha does not consider the path given in `"recursive": ["./tests/**/*.js"]` without this option.
I don't know if it is the expected behaviour from https://github.com/mochajs/mocha/pull/4691.

### Steps to Reproduce

```shellsession
user@host ~$ git clone https://github.com/cyrilverloop/mocha-node-option.git
user@host ~$ cd mocha-node-option
user@host mocha-node-option$ npm test
```
- remove the option `"node-option": [],` in the `.mocharc.json` configuration file at the root of the project;
- run the test to see the error message.

**Comment by juergba** [comment]
```
{
    "node-option": [],
    "recursive": ["./tests/**/*.js"],
    "ui": "tdd"
}
```

`recursive` is a boolean flag, not an array. Your `.mocharc.json` looks then as follows:
```
{
    "node-option": [],
    "spec": ["./test/**/*.js"],
    "ui": "tdd"
}
```

With or without `node-option` your test will run as expected.

**Comment by cyrilverloop** [comment]
@juergba changing `"recursive"` to `"spec"` was the answer i was looking for. Thanks !

I do not know why it worked before 9.1.0 nor why adding `"node-option": []` makes it work now, but it does not matter to me.
I see that the `"spec"` default option is missing in [.mocharc.json](https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.json) and [.mocharc.jsonc](https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.jsonc). Should it be added ?
