### ISSUE TITLE
Getting MODULE NOT FOUND even though the package is not part of the dependancy

### ISSUE THREAD

**Issue by anandprasathm** [mochajs/mocha#4753]
Hi,

I have created a mocha project and included the spec file '.mocharc.json' and included the reporter '"@mochajs/json-file-reporter'.

My .mocharc.json looks like below
{
"spec": "test/**/test1.js",
"reporter": "@mochajs/json-file-reporter",
"reporter-option": [
"output=filename.json"
]
}

Scripts on the package.json as below
"scripts": {
"test": "mocha"
},

When i given npm test, it worked fine.

Then again, i ve created a new project and i didn't install/use any reference of '@mochajs/json-file-reporter' (not even have any .mocharc.json file) and specified the test directly on the scripts of the new project(package.json).

When i run this test from the new project, i am getting the Error MODULE NOT FOUND for @mochajs json-file-reporter

When i install this package, i am getting the error like 'Couldn't find any files matching pattern "test/**/test1.js"'.

I am not sure why my tests are not getting picked up from the current project and why this is always referring to the first one.

Has anyone come across this issue on Mocha?

**Comment by juergba** [comment]
@anandprasathm Please note, this is an issue tracker, not a help forum.

You will find lots of information in the net how to initialize a Node project and correctly install its dependencies.
We also have a [gitter](https://gitter.im/mochajs/mocha) chanel where you can try to get support. 
Thank you.
