### ISSUE TITLE
There is no ability to skip suite with tests via own api (works in mocha@2)

### ISSUE THREAD

**Issue by DudaGod** [mochajs/mocha#4761]
### Prerequisites

- [X] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [X] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [X] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [X] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

I want to add my own api to skip suites or tests like this:
```
myOwnApi.skip();
describe('foo', () => {
    it('bar', () => {
        console.log('hello world');
    });
});
```

My simple implementation to do it:
```
const Mocha = require('mocha');
const mocha = new Mocha();
const rootSuite = mocha.suite;

// function to add recursive handler for events triggered by mocha while parsing test file
function _addEventHandler(events, cb) {
    events = [].concat(events);

    const listenSuite = (suite) => {
        suite.on('suite', listenSuite);
        events.forEach((e) => suite.on(e, cb));
    };

    listenSuite(rootSuite);
}

const myOwnApi = {
    shouldSkip: false,
    skip: function() {
        this.shouldSkip = true; // next runnable (suite or test) will be skipped
    },
    handleRunnable: function(runnable) {
        if (this.shouldSkip) {
           runnable.pending = true; // skip suite or test via set pending flag
        }

        this.shouldSkip = false; // reset skip state
    }
}

global.myOwnApi = {
    skip: myOwnApi.skip.bind(myOwnApi) // add my API to global
};

_addEventHandler(['suite', 'test'], (runnable) => myOwnApi.handleRunnable(runnable));

mocha.addFile('./test');
mocha.loadFiles();

rootSuite.eachTest((test) => {
    if (!test.pending) {
        test.fn(); // if test is not pending then run it
    }
});
```

This code works fine with mocha@2 but does not work with mocha@3 and higher. The problem is here - https://github.com/mochajs/mocha/blob/master/lib/interfaces/common.js#L134. Event with suite emitted before change pending - https://github.com/mochajs/mocha/blob/master/lib/suite.js#L43.

We can fix this problem if change - `suite.pending = Boolean(opts.pending);` to `suite.pending = Boolean(opts.pending | suite.pending);`.

Or maybe there is some workaround that I don't see?
Thank you.

**Comment by juergba** [comment]
@DudaGod I'm not familiar with Mocha v2, many years have passed meanwhile. Lots of breaking changes have been applied and you can't expect Mocha v9 to peacefully run with your ancient solution. This isn't a good approach and we will not make any changes to our code based on this issue.

I see in your code snippet that you are using private functions, and also that you are not relying on `runner` which is the core feature of Mocha. This is a very error-prone approach. I don't know whether there was no `runner` in Mocha v2, or why you are using Mocha at all.

Anyway, if you want a special behaviour during parse cycle, then write your own interface and pass it via `--ui` option to Mocha, or to the `Mocha` constructor. Like this you can easily remove the hooks as well.

**Comment by DudaGod** [comment]
> I see in your code snippet that you are using private functions, and also that you are not relying on runner which is the core feature of Mocha. This is a very error-prone approach. I don't know whether there was no runner in Mocha v2, or why you are using Mocha at all.

It's my own private functions that can be public as well, because it's only simple example. I will look at the code of the mocha runner.

> Anyway, if you want a special behaviour during parse cycle, then write your own interface and pass it via --ui option to Mocha, or to the Mocha constructor. Like this you can easily remove the hooks as well.

The problem is if I override ui interface in our tool then our users can't add theirs own interfaces.
Anyway, thank you. I close it.
