### ISSUE TITLE
[Proposal] `rootHooks` accept  `import(name)` as input

### ISSUE THREAD

**Issue by loynoir** [mochajs/mocha#4780]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
### Background: karma & mocha
`karma-mocha` is not await for `<script type="module">`. When `XXX.spec.js` have top level await, or slow import, all unit tests within it are silently missing. [issue](https://github.com/karma-runner/karma-mocha/issues/243)

### `rootHooks` works in mocha
I fixed it in [pull](https://github.com/karma-runner/karma-mocha/pull/244). Try to add unit test. And mocha can identify if some unit tests are missing.
```js
mocha.setup({
    ui: "bdd",
    rootHooks: {afterAll},
})
```

### `rootHooks` not works in karma
Got serialize problem. `rootHooks` in `mocha.setup(config)` is not **serializable**. 
```js
// karma.config.js
client: {
    mocha: {
        timeout: 600000,
        rootHooks: {afterAll}
    },
}
```
```
// karma runtime context
> window.__karma__.config.mocha
{ timeout: 600000, rootHooks: {} }
```

**Describe the solution you'd like**

<details>
  <summary>Related defination, add here for better reading</summary>
  <p>
 
```ts
interface RootHookObject {
  afterAll?: Func | AsyncFunc | Func[] | AsyncFunc[] | undefined;
  beforeAll?: Func | AsyncFunc | Func[] | AsyncFunc[] | undefined;
  afterEach?: Func | AsyncFunc | Func[] | AsyncFunc[] | undefined;
  beforeEach?: Func | AsyncFunc | Func[] | AsyncFunc[] | undefined;
}
```
  </p>
</details>

### Current defination
```ts
interface MochaOptions {
  timeout?: number | string | undefined;
  ui?: Interface | undefined;
  // ...

  rootHooks?: Mocha.RootHookObject | undefined;
}

```

### Proposal
```ts
interface MochaOptions {
  timeout?: number | string | undefined;
  ui?: Interface | undefined;
  // ...

  rootHooks?:
    Mocha.RootHookObject
    | undefined
    | Promise<{ mochaHooks: Mocha.MochaOptions }>
    | { type: "import", value: string }
}
```

### Usage

Serializable configuration
```js
// karma.config.js
client: {
    mocha: {
        timeout: 600000,
        rootHooks: { type: "import", value: "/path/to/my/mochaHooks.mjs" }
    },
}
```

Equals to
```js
mocha.setup({
  rootHooks: { type: "import", value: "/path/to/my/mochaHooks.mjs" }
})
```

Equals to
```js
mocha.setup({
  rootHooks: import("/path/to/my/mochaHooks.mjs")
})
```

1. `import()` supported by node and browsers, and can use modules.
2. As unit test `describe()` in sync context, results in `mocha.setup` can't await here.

**Describe alternatives you've considered**
On `karma-mocha` side, using AST tools convert `rootHooks` to sync version browser support code, and somehow load all dynamic files into karma, before `mocha.setup` and all `karma` files.

**Additional context**

**Comment by juergba** [comment]
@loynoir we are using _karma-mocha_ in our repo as well and I'm not happy with it, since it hasn't been maintained for two years and a half. Its status is completely outdated. I always feel releived when our CI karma tests have passed successfully. So my enthusiasm to touch Mocha for _karma-mocha_'s sake is limited.

`karma-mocha is not await for <script type="module">`: to load ESM test files, I guess. I don't understand why you want to abuse hooks/rootHooks to load ESM test files. Why this complicated detour? Why not make _karma-mocha_ inject ESM modules the correct way?

`Got serialize problem`: ??

In Mocha the `mochaHooks` are loaded via `--require` plugin which then returns the `rootHooks` object. In the browser you directly work with the `rootHooks` object. To extend the `rootHooks` with an `import` feature seems weird to me.
Wouldn't this way be easier and more obvious?
```
// karma.config.js
 client: {
      mocha: {
        require: './hooks.js'
      }
 }
```

Tbh I don't really understand this PR. I don't see the link between `rootHooks` and EMS test files.

**Comment by loynoir** [comment]
> we are using karma-mocha in our repo as well and I'm not happy with it, since it hasn't been maintained for one year and a half. Its status is completely outdated. I always feel releived when our CI karma tests have passed successfully. So my enthusiasm to touch Mocha for karma-mocha's sake is limited.

Sorry, I just notice mocha hasn't been maintained for one year and a half. 

I'm very appreciate for your maintainance here. 👍

I'm ok to close this proposal.


<details>
  <summary></summary>
  <p>
 
 
> `Got serialize problem`: ??

`karma` seems can not parse function from `karma.config.js` to runtime context.

```js
// karma.config.js
client: {
    mocha: {
        timeout: 600000,
        // afterAll is a function
        rootHooks: {afterAll}
    },
}
```

```txt
// karma runtime context
// window.__karma__.config.mocha.rootHooks is empty object
> window.__karma__.config.mocha
{ timeout: 600000, rootHooks: {} }
```

> Why not make karma-mocha inject ESM modules the correct way?

Yes, before this proposal, I already fix that in my karma-mocha fork.

Run `mocha.run` after all `.mjs` are awaited, so none `describe()` is silently left behind.

> I don't see the link between rootHooks and ESM test files.

I use `rootHooks.afterAll` to test my fix work, `karma-mocha` not running `mocha.run` too early, `describe()` in `.mjs` in run at least one.


> require: './hooks.js'

Thanks for your suggestion. Anyway, I have got [test](https://github.com/loynoir/karma-mocha/blob/master/test/esm) working, to ensure no `describe()` is left behind.

---

At last, appreciate again, for your mocha maintainance 🤗

  </p>
</details>

**Comment by juergba** [comment]
@loynoir thank you 👍 
I'm going to close this issue then.

**Comment by jginsburgn** [comment]
I just want to leave a note here that the Karma repos are still being maintained but with limited resources.
