### ISSUE TITLE
Mocha throws UnparsableFileError instead of throwing the actual error when importing js/cjs

### ISSUE THREAD

**Issue by nopeless** [mochajs/mocha#4781]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

mocha would throw a UnparsableFileError when importing a `js`/`cjs` module that doesn't actually have syntax errors

### Steps to Reproduce

`.mocharc.cjs`
```js
require("0a9g"); //module that does not exist
require("chai"); // this is how I originally found the error
module.exports = {};
```

**Expected behavior:** [What you expect to happen]

Give some comprehensive error such as module "0a9g" does not exist

**Actual behavior:** [What actually happens]

`Error: Unable to read/parse ./test/.mocharc.cjs: Error: Cannot find module './test/.mocharc.cjs'`

**Reproduces how often:** [What percentage of the time does it reproduce?]

every time

### version

```
mocha --version > 9.1.3
npm run mocha -- --version > 9.1.3 // edit: I forgot to add --
node node_modules/.bin/mocha --version
<SOURCEDIR>\node_modules\.bin\mocha:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
node -v > v16.6.0
```

**Comment by nopeless** [comment]
bump

**Comment by sciffany** [comment]
Hi, first time contributor. May I take this issue please? Thank you.

**Comment by nopeless** [comment]
@sciffany what do you mean by "take this issue"

**Comment by sciffany** [comment]
@nopeless I want to try resolving this issue.

**Comment by nopeless** [comment]
> @nopeless I want to try resolving this issue. 

Sure. It would be nice if you did

**Comment by sciffany** [comment]
Made a PR #4286 to resolve this
