### ISSUE TITLE
Get the number of passed, failed and total test cases

### ISSUE THREAD

**Issue by aminnairi** [mochajs/mocha#4782]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
I am using GitHub Classroom to give assignments to my student for my JavaScript course for the school I work for. I wanted to automate the assignment so I use template repositories with unit tests so that student can check if they did understand the part of the course I'm grading them by filling the blank in each functions I want them to solve. I then need to calculate they grade. Initially, this was done manually by me getting the count of succeed tests divided by the count of tests multiplied by 20 (in France we grade students on a 20 based grade). I wanted to do this automatically of course to save some time by using the autograding feature proposed by GitHub Classroom, unfortunately, this tool is very basic as it is either a full grade or a zero. My last hope is that Mocha would have some sort of count (or at least, a list of tests failed, succeeded and total). Because whenever I try to grade my students, the object looks like this:

```javascript
mocha.after(function() {
  let succeededTests = 0;
  let numberOfTests = 0;

  this.test.parent.suites.forEach(suite => {
    suite.suites.forEach(subsuite => {
      subsuite.tests.forEach(test => {
        numberOfTests++;

        if (test.state === "passed") {
          succeededTests++;
        }
      });
    });
  });

  console.log(`Grade: ${Math.round(succeededTests / numberOfTests * 20 * 100) / 100}/20`);
});
```

This is because I have tests suite inside tests suites. And so this code is not portable at all because if I change the tests suite architectures, the context will also change.

**Describe the solution you'd like**
And simple way to get the total, failed and passed test count in the context of the `after` hook.

**Describe alternatives you've considered**
Manually getting all of those information on each and every single one assignment I give to my student, making me lose some more time.

**Additional context**
I could do a recursive search, but this would mean spend even more time on a rather simple problem.

EDIT: after some thinking, I finally found something recursively that I can use to get the total tests and succeeded tests count that I can use in any of my assignments.

```javascript
import mocha from "mocha";

const getSucceededTestsCount = suite => {
  const succeededTestsCount = suite.tests.reduce((total, test) => test.state === "passed" ? total + 1 : total, 0)

  if (suite.suites.length === 0) {
    return succeededTestsCount;
  }

  return succeededTestsCount + suite.suites.reduce((total, suite) => {
    return total + getSucceededTestsCount(suite);
  }, 0);
};

const getTotalTestsCount = suite => {
  const totalTestsCount = suite.tests.length;

  if (suite.suites.length === 0) {
    return totalTestsCount;
  }

  return totalTestsCount + suite.suites.reduce((total, suite) => {
    return total + getTotalTestsCount(suite);
  }, 0);
};

mocha.after(function() {
  const succeededTestsCount = getSucceededTestsCount(this.test.parent);
  const totalTestsCount = getTotalTestsCount(this.test.parent);

  console.log(`Grade: ${Math.round(succeededTestsCount / totalTestsCount * 20 * 100) / 100}/20`);
});
```

**Comment by juergba** [comment]
@aminnairi what you are describing is some kind of reporting. Mocha or custom reporters use event listeners to get their jobs done.

You have different options:
- use Mocha programmatically and register your own event listeners to the `runner`, like `test end` or `suite end` or ...
There is a statistic collecter `runner.stats` you evtl. can use for your purpose.
- use an existing reporter as `json` or `mochawesome` and read your info out of the written JSON file.
- write you own reporter / extend an existing one

We are not going to add any feature based on the `after` hook.
