### ISSUE TITLE
docs: mocha definition is hardly readable

### ISSUE THREAD

**Issue by surajnarsale** [mochajs/mocha#4787]
- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description
Document page mocha definition is hard to read due to '200' font weight. 

![mocha bug](https://user-images.githubusercontent.com/70274294/141933742-427d8f53-a4ca-4f50-b936-70c9409795ed.png)

**Comment by BrancuAlexandru** [comment]
This has been fixed, and I'm not talking about the PR that was auto closed. If you go to the doccumentation page it's fine now.
