### ISSUE TITLE
integrate mocha and testLink

### ISSUE THREAD

**Issue by Elham1368** [mochajs/mocha#4788]
how could I integrate mocha and testLink  ????
when I run my testCases in mocha I want to register my executions result in testLink automatically

**Comment by juergba** [comment]
@Elham1368 I'm closing this issue.

I have never heard of testLink, and with this very little information provided by you, what type of answer do you expect?
There is a third-party _mocha-testlink-reporter_ which may be helpful, or not, I don't know.

Please also note, this is a issue tracker, not a help forum, thank you.
