### ISSUE TITLE
Tests are not running in parallel, after adding attributes(tags) of Report portal api

### ISSUE THREAD

**Issue by shaifaliyadav** [mochajs/mocha#4789]
am running tests in parallel using -parallel attribute. And am using report portal https://github.com/reportportal/agent-js-mocha to publish the results.
Tests were running in parallel until i used this addattributes (tag ) feature of report portal. Example: 

const PublicReportingAPI = require('@reportportal/agent-js-mocha/lib/publicReportingAPI');
...
describe('suite',()=>{
  before(function (){
    PublicReportingAPI.addAttributes([{ key: 'suiteAttr1Key', value: 'suiteAttr1Value' }, { value: 'suiteAttr2' }]);
  });
  it('test', () => {
    PublicReportingAPI.addAttributes([{ key: 'testAttr1Key', value: 'testAttr1Value' }]);
    PublicReportingAPI.addAttributes([{ value: 'testAttr2' }]);
  });
});

now if i use this PublicReportingAPI.addAttributes([{ value: 'testAttr2' }]);, then tests don't tun in parallel mode and if i remove this, tests run in parallel mode.

**Comment by juergba** [comment]
@shaifaliyadav I have no idea what you are talking about.

**Comment by shaifaliyadav** [comment]
@juergba updated the description..please check and let me know if you need further details.

**Comment by juergba** [comment]
see https://github.com/reportportal/agent-js-mocha/issues/49#issuecomment-697514939
