### ISSUE TITLE
mochaGlobalTeardown is never called

### ISSUE THREAD

**Issue by unicornware** [mochajs/mocha#4790]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

I've created a file to store global fixtures. The file exports `mochaGlobalSetup` and `mochaGlobalTeardown`.

**Although `mochaGlobalSetup` works as expected, `mochaGlobalTeardown` is never called**.

### Steps to Reproduce

1. Create a file to store global fixtures
2. Insert the following:

      ```typescript
      export function mochaGlobalSetup(): void {
        console.log({ mochaGlobalSetup: 'HERE' })
      }
      
      export function mochaGlobalTeardown(): void {
        console.log({ mochaGlobalTeardown: 'HERE' })
      }
      ```

3. Create `.mocharc.cjs`

      ```javascript
      /**
       * @file Mocha Configuration
       * @see https://mochajs.org/#command-line-usage
       * @see https://mochajs.org/#configuration-format
       */
      
      const PWD = process.env.GITHUB_WORKSPACE
      const TYPES = ['', 'e2e', 'functional', 'integration']
      
      /** @type {Mocha.MochaInstanceOptions} */
      const config = {
        allowUncaught: false,
        asyncOnly: false,
        bail: false,
        checkLeaks: true,
        color: true,
        diff: true,
        exit: true,
        extension: TYPES.map(type => `${type}.spec.ts`),
        failZero: false,
        forbidOnly: true,
        forbidPending: false,
        fullTrace: true,
        globals: ['chai', 'expect', 'sandbox', 'sinon'],
        growl: !(require('is-ci') || process.env.GITHUB_ACTIONS === true),
        ignore: [
          '*/*/coverage/**',
          '*/*/node_modules/**',
          'coverage',
          'node_modules'
        ],
        inlineDiffs: true,
        /** @see https://typestrong.org/ts-node/docs/recipes/mocha */
        loader: `${PWD}/tools/loaders/esm.mjs`,
        noHighlighting: false,
        nodeOption: [
          'experimental-json-modules',
          'es-module-specifier-resolution=node',
          'no-warnings'
        ],
        parallel: false,
        recursive: true,
        reporter: `${PWD}/__tests__/reporters/jsonspec.ts`,
        reporterOptions: [],
        require: [
          `${PWD}/tools/loaders/tsconfig-paths.cjs`,
          `${PWD}/__tests__/config/mocha-global-fixtures.ts`,
          `${PWD}/__tests__/config/mocha-root-hooks.ts`
        ],
        retries: 0,
        sort: true,
        spec: '{,!(coverage|node_modules)/**}/__tests__/*.spec.ts',
        timeout: 2000,
        ui: 'bdd',
        watch: false
      }
      
      module.exports = config
      ```

4. Create a test file
5. Run `nyc mocha`
6. See that `{ mochaGlobalSetup: 'HERE' }` is logged, but `{ mochaGlobalTeardown: 'HERE' }` is not

**Expected behavior:** [What you expect to happen]

 `mochaGlobalTeardown` should be called so that `{ mochaGlobalTeardown: 'HERE' }` is logged.

**Actual behavior:** [What actually happens]

`mochaGlobalTeardown` is never called.

**Reproduces how often:** [What percentage of the time does it reproduce?] 

100% of the time.

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: `9.1.3`, `9.1.3`
- The output of `node --version`: `16.0.0`
- Your operating system
  - name and version: macOS Big Sur `v11.3.1`
  - architecture (32 or 64-bit): not sure where to find that information 😅
- Your shell (e.g., bash, zsh, PowerShell, cmd): `zsh`
- Your browser and version (if running browser tests): N/A
- Any third-party Mocha-related modules (and their versions): `nyc@15.1.0`, `ts-mocha@8.0.0`
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): `typescript@4.5.0-beta`

**Comment by juergba** [comment]
@unicornware thank you for this elaborated issue.

You are using Node's experimental `loader` hook, and your TS configuration is unclear.
Could you open a repo to reproduce this issue, please?
Where does your `loader` come from, _ts-node_?
Have you tried the compiled version of your tests (without _ts-node_)?

You should update your Node and _ts-mocha_ version.

**Comment by unicornware** [comment]
@juergba 

- my loader file uses `ts-node` and has some additional logic as well
- dropping my loader (adding `ts-node/register` to `require`) and running my tests with `nyc mocha` (as stated above) is something i already tried and has no impact - `mochaGlobalTeardown` still isn't called
- i'm purposely using `node@16.0.0` because the esm hooks api gets funky after `node@16.1.0`, and i don't feel like updating my loader _just_ because the node team decided to deprecate a few functions
- i'm already using the latest **stable** version of `ts-mocha`. seems to have been released last year, but i'm not sure how stable `9.0.0-alpha1` is (or if i'm ready to find out)
- haven't tried the compiled versions of my tests. my project isn't set up in such a way, and i'm not a fan of adding an extra build step or compile time to my testing workflow.
- don't have the bandwidth to create a new repo at the moment (didn't realize one was needed, either). what's missing from the "Steps to Reproduce" section? do you need it in javascript?

**Comment by juergba** [comment]
I just run some simple test with Mocha and plain javascript, requiring both an ESM and CJS global-fixture file. It works.

You are using Mocha, TS, EMS, Node's experimental `loader` feature, and a pimped version of `ts-Node/esm`. It doesn't work.
I think it's your task to narrow down the problem, your problem.

`package.json` is missing, TS configuration is missing, ...
Btw my time is precious as well.

**Comment by unicornware** [comment]
@juergba 

first, i didn't ask _you_ create reproduction. i simply said i did not have the time at the moment to create a new repo and asked if there was anything i could add to "Steps to Reproduce" as a quick patch. 

secondly, i actually shifted some time around (aka the wee hours of the morning) so i could do a repro and narrow down a solution. obviously that's my problem considering i created the bug report.

**btw, don't assume someone doesn't think your time is "precious". or at least be mindful of your tone.**
