### ISSUE TITLE
Maintainer Ethics & Responsibility

### ISSUE THREAD

**Issue by unicornware** [mochajs/mocha#4791]
Recently, I created a bug report regarding `mochaGlobalTeardown`. 

Someone who I assume to be a maintainer, @juergba, responded with a few questions. I replied with a list of answers and a question of my own. In their reply, the maintainer asked if I could create a repro repo. I do not know where they are located, but I'm in the U.S and it was quite late. I didn't have the bandwidth at the exact moment to create a new repo, so my question was in regard to how I could quickly update my "Steps to Reproduce" section to help the maintainer help me. 

Instead of answering my question politely, I was accused of laziness and not thinking the maintainer's time is "precious." I restated and clarified the parameters of question (not once did I ask _them_ to create a reproduction), as well as pointed out that their delivery and tone was horrendous. I ended up closing my own issue. I have not received an apology (either for the accusations or confusion). With that, I have a few questions:

- Is this the kind of "public behavior" expected of maintainers, as stated in the Mocha Maintainer's Handbook?
- Are there any plans to update the Mocha Maintainer's Handbook with sections on accountability and interacting with users?

While I understand you cannot make anyone apologize (nor do I expect a sincere apology), I also refuse to let such an incident go unnoticed and possibly go onto set a precedent for future maintainers.

**Comment by juergba** [comment]
[This](https://github.com/mochajs/mocha/issues/4790#issuecomment-974787244) is the issue in question.

@unicornware you can contact the OpenJS Foundation directly and ask your questions, and/or complain.
I will leave this issue open for some time.

**Comment by unicornware** [comment]
@juergba are they equipped to answer questions about the Mocha Maintainer’s Hanbook?

**Comment by juergba** [comment]
@unicornware
I'm closing this issue, our handbooks remain unchanged.
Thank you for your contribution.

**Comment by unicornware** [comment]
@juergba Thanks for showing your true self and priorities!
