### ISSUE TITLE
`expose-gc` not working after upgrading from mocha 8.x to mocha 9.1.2

### ISSUE THREAD

**Issue by mmomtchev** [mochajs/mocha#4794]
### Prerequisites

`test.js` with: 
```js
console.log(global.gc)
````

### Description

After upgrading from mocha 8.x to mocha 9.1.2 the old `--expose-gc` option (or `expose-gc` config item) is not functional anymore.

It seems that at some point along the way that option got renamed to `--gc-global`. However the Node.js option is still called `--expose-gc`. Passing `--gc-global` to mocha results in Node.js being launched with `--gc-global` which has no effect.

### Steps to Reproduce

```sh
mocha --expose-gc ./test.js   # absolutely no effect, this option is not recognized anymore
mocha --gc-global ./test.js     # launches node with --gc-global which has no effect either
```

**Expected behavior:**

```sh
node --expose-gc node_modules/mocha/lib/cli/cli.js  ./test.js # functional
```

### Versions

mocha 9.1.2
node 14.18.2
Ubuntu 20.04
ts-node 9.1.1

**Comment by mmomtchev** [comment]
There is a V8 debugging option called `--gc_global` (note the underscore) distinct from `--expose_gc` - which is probably the source of the confusion

**Comment by Patrik-Stas** [comment]
I have run into this jsut now as well. I was running mocha like this
```
TS_NODE_PROJECT=./test/tsconfig.json NODE_ENV=test RUST_BACKTRACE=full ./node_modules/.bin/mocha --timeout 10000 --expose-gc --recursive --use_strict --require ts-node/register ./mytest.test.ts
```
and `global.gc` is undefined on mocha `9.1.x` but I found the latest version it works at is mocha `9.0.3`

**Comment by juergba** [comment]
I don't know those `--expose-gc` or `--gc-global` options, wether they belong to Node or to V8. Certainly none of them is a Mocha option.

Use `mocha -n expose-gc` or `mocha -n gc-global`. Mocha will spawn a child-process and pass your options to Node. You are responsible for the values you choose, if `expose-gc` is not a valid Node or V8 option, Node will let you know.

**Comment by mmomtchev** [comment]
@juergba `--expose-gc` used to be an official mocha option and `--gc-global` (which should be `--gc_global`) is still listed:
<https://github.com/mochajs/mocha/blob/3b4cc05f3fa0502d5d714a8f62ac8785267aa695/lib/cli/node-flags.js#L23>

**Comment by juergba** [comment]
Does `mocha -n expose-gc` work? Does `mocha --v8-expose-gc` work?

Node accepts both `--gc_global` and `--gc-global`, at least with my Node v16.12.0.

**Comment by mmomtchev** [comment]
@juergba, `--v8-expose-gc` works, yes

**Comment by oliviertassinari** [comment]
`mocha -n expose-gc` work for me
