### ISSUE TITLE
TypeError: suite.dispose is not a function when running mocha with watch and parallel modes enabled

### ISSUE THREAD

**Issue by gomaloick** [mochajs/mocha#4796]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Steps to Reproduce

When running mocha in watch mode with parallel jobs, a type error is thrown and doesn't rerun tests on file changes :
`mocha build/tests/**/*.test.js -r build/tests/setup.js -w -p -j 3`

I am recompiling my project from typescript to javascript, and when the file change is detected (I tested several files)
I have a `TypeError: suite.dispose is not a function` at `node_modules\mocha\lib\suite.js:533:11`
I have the same error when trying with different number of jobs (2, 4, 5)
The command works fine without parallel mode

**Expected behavior:** Mocha detects file change and rerun all test suites succesfully

**Actual behavior:** TypeError is raised without rerunning test suites

```
TypeError: suite.dispose is not a function
    at node_modules\mocha\lib\suite.js:533:11
    at Array.forEach (<anonymous>)
    at Suite.dispose (node_modules\mocha\lib\suite.js:532:15)
    at Mocha.dispose (node_modules\mocha\lib\mocha.js:645:14)
    at beforeRun (node_modules\mocha\lib\cli\watch-run.js:45:13)
    at run (node_modules\mocha\lib\cli\watch-run.js:265:27)
    at rerun (node_modules\mocha\lib\cli\watch-run.js:297:5)
    at Object.scheduleRun (node_modules\mocha\lib\cli\watch-run.js:290:7)
    at FSWatcher.<anonymous> (node_modules\mocha\lib\cli\watch-run.js:188:14)
    at FSWatcher.emit (node:events:390:28)
    at FSWatcher.emitWithAll (node_modules\chokidar\index.js:541:32)
    at FSWatcher._emit (node_modules\chokidar\index.js:632:8)
    at listener (node_modules\chokidar\lib\nodefs-handler.js:370:20)
```

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 9.1.3
- The output of `node --version`: v17.0.1
- Your operating system
  - name and version: Windows 10 Professional 21H2
  - architecture (32 or 64-bit): 64-bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): PowerShell
- Your browser and version (if running browser tests):
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): TypeScript 4.5.2

**Comment by juergba** [comment]
@gomaloick I tried to reproduce your issue without success. I used a sample in plain javascript, no typescript.

Please add a sample for reproduction. Thank you.
