### ISSUE TITLE
[Feature Request] Mocha spec test

### ISSUE THREAD

**Issue by fncolon** [mochajs/mocha#4797]
Can we use second, hour instead of `ms` for spec test? As far I know there's no conventions time info should be milliseconds.

**Comment by juergba** [comment]
@fncolon see related issue #4149

No, we are not planing to change the time format in our reports. Quite a few third-party reporters are using _mocha/lib/reporters/base.js_, so this would be a breaking change.

You can create your own reporter and implement your desired time format.
