### ISSUE TITLE
Docs: document programmatic usage of mocha, more specifically: createStatsCollector

### ISSUE THREAD

**Issue by webketje** [mochajs/mocha#4798]
**Use case**: Use mocha as part of a build pipeline with a root suite with nested suites, without it being the main entrypoint for `mocha` CLI.
**Issue**: Documentation on how to use the 'pure' JS API is sparse, but more specifically there is no documentation code sample showing that initiating `createStatsCollector` is required after a certain version (TBD?), even for non-custom reporters. This is a google search for the exact match 'statsCollector' on the mochajs.org website: 
https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fmochajs.org+"statsCollector"

This works in mocha `5.x`:
```js
const { Suite, Context, Runner, reporters: { Spec }} = require('mocha')
const childSuite = require('./childSuite')

const rootContext = new Context()
const rootSuite = new Suite(rootContext)
rootSuite.addSuite(childSuite)

const runner = new Runner(rootSuite)
const spec = new reporters.Spec(runner)

runner.run()
```
But throws `uncaught(): got truthy exception TypeError: Cannot read property 'passes' of undefined` in mocha 9.x:
<details><summary>Full error log</summary>
<pre><code>mocha:runner uncaught(): got truthy exception TypeError: Cannot read property 'passes' of undefined
  mocha:runner     at Spec.Base.epilogue (node_modules/mocha/lib/reporters/base.js:363:30)
  mocha:runner     at Object.onceWrapper (node:events:513:28)
  mocha:runner     at Runner.emit (node:events:406:35)
  mocha:runner     at end (node_modules/mocha/lib/runner.js:1051:10)
  mocha:runner     at node_modules/mocha/lib/runner.js:912:7
  mocha:runner     at next (node_modules/mocha/lib/runner.js:489:14)
  mocha:runner     at Immediate.<anonymous> (node_modules/mocha/lib/runner.js:574:5)
  mocha:runner     at processImmediate (node:internal/timers:464:21) +1ms
  mocha:runner uncaught(): Runnable has already passed; bailing gracefully +1ms
  mocha:runner total number of failures: 1 +0ms
  1) should have a 'Installation' section
  mocha:runner abort(): aborting +1ms</code></pre>
</details>

Not sure in which version this was changed but it is due to missing a `StatsCollector`. The following snippet works as expected on mocha@latest:

```js
const { Suite, Context, Runner, reporters: { Spec }} = require('mocha')
const createStatsCollector = require('mocha/lib/stats-collector')
const childSuite = require('./childSuite')

const rootContext = new Context()
const rootSuite = new Suite(rootContext)
rootSuite.addSuite(childSuite)

const runner = new Runner(rootSuite)
createStatsCollector(runner)
const spec = new reporters.Spec(runner)

runner.run()
// but why not suite.run() which sounds more logical but does nothing?
```
Also hard to find in a guide (but somewhat  figuring in the API docs):
* runner.run must be called & not suite.run
* whether child suites inherit the root suite runner/reporter (they do) and whether a separate runner/reporter is supported/required/recommended for child suites
* how to access parent/root context from a child suite, or ensure all suites share context 
* the difference between/ when to use `suite.addSuite(new Suite(title, context))` vs `Suite.createSuite(title, context)`

**Comment by juergba** [comment]
> Use case: Use mocha as part of a build pipeline with a root suite with nested suites, without it being the main entrypoint for mocha CLI.

Mocha does not offer any public API to achieve this, e.g. `Suite.prototype.addSuite` is a private function. I have seen third-party packages depending on our private functions and also the weirdest example of dynamically creating tests via `before` hooks. But developping that way is on your own risk and you won't find any official docs about that.

So it's possible that your code - runnig on Mocha@5 - breaks on Mocha@9. Changes in private parts of the code base are no breaking changes. `createStatsCollector` is private as well.

So most of your question can only be answered by studying Mocha's code and then fiddling around.

Maybe using Mocha via CLI and dynamically creating tests via `top-level-await` or `--delay` option could be an alternative?

**Comment by webketje** [comment]
@juergba Sorry  `addSuite` is indeed private, but `new Suite` and `Suite.createSuite` aren't, so Mocha definitely does provide a public API to achieve this, if one can trust the `@public` docblocks also documented in the [API docs](https://mochajs.org/api). Here is an (undocumented- example using only public methods:

```js
const Mocha = require('mocha')
const tests = new Mocha()

tests.addFile('./path/to/childSuite.js')
tests.run()
```

It's unfortunate that `createStatsCollector` and `Suite.addTests` are private, because having them public would allow completely integrating mocha in a custom workflow. The example below also only uses public methods, but in the current state Mocha can only be instantiated like this with a 0-test suite.

```js
const rootSuite = new Mocha.Suite('Root')
const childSuite = Mocha.Suite.create(rootSuite, 'Child')
// childSuite.addTest('A test', function() {  require('assert').equal(true, true) })
const runner = new Mocha.Runner(rootSuite)
// const createStatsCollector = require('mocha/lib/stats-collector')
// createStatsCollector(runner)
// would be more consistent as Mocha.StatsCollector.create(runner)
const reporter = new Mocha.reporters.Spec(runner)

runner.run()
```

**Comment by juergba** [comment]
Yes, your first example is correct and you find it documented in our wiki and also in our [sample repo](https://github.com/mochajs/mocha-examples/tree/master/packages/programmatic-usage). It's a completely different use case  since you are not trying to build a test hierarchy (`runner`) with nested suites by programmatic means.

Your second example: `createStatsCollector` is private. We will never offer a public API to use Mocha programmatically without creating a `mocha` instance. Btw `mocha` does handle `statsCollector`.

**Comment by webketje** [comment]
@juergba thanks a lot for taking the time to answer in detail, and the docs pointer.
In my use case, a static site generator reads the input to test in memory, and I needed a way to pass this data across test suites, re-using mocha's nicely formatted output, which is not possible using the `.addFile`  API.
I understand this is an edge case and therefore this issue can be closed.
