### ISSUE TITLE
Keep information about currently executed test in suites

### ISSUE THREAD

**Issue by martinalbert** [mochajs/mocha#4802]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
It's nice to have. 

My problem (also described [here](https://stackoverflow.com/questions/70341079/how-to-retrieve-current-test-from-parent-mocha-suite) on stack-overflow) is that I would like to get information about currently executed test from parent suites. My main goal was to get name of test, that I can then use in method, that is executed throughout test file without passing `this.currentTest` or `this.test` in each call, but rather when instantiating class of this method in parent suite.

**Describe the solution you'd like**
Instance of Suite contains arrays `tests` and `suites`. It could contain instance of currently executed test or at least its id to access it through arrays.

**Describe alternatives you've considered**
My problem can be solved with re-instantiation of class in beforeEach or afterEach hooks and pass information about test name with `this.currentTest.fullTitle()`.

**Comment by JoshuaKGoldberg** [comment]
This has been open for two years with no interactions. I haven't dug deeply through the issue tracker, but the feature has been mentioned elsewhere or not enough users care deeply about it enough to warrant a built-in feature.

You can always build this yourself with ad-hoc functions called within `describe`, etc.
