### ISSUE TITLE
--parallel flag avoids parameter passthrough

### ISSUE THREAD

**Issue by 7c** [mochajs/mocha#4808]
Running mocha version 9.1.3, but also tried with 9.1.1. Same behaviour.

if i use -p or --parallel flag then arguments are not passed to script at all. Following screenshot shall help you guys to visualize:

![image](https://user-images.githubusercontent.com/22910022/148254154-20c0e72b-988a-4fc7-add9-e1baf111a076.png)

it looks like that worker.js which is probably responsible for --parallel flag does not pass the arguments .

**Comment by juergba** [comment]
No, those CLI flags have already been processed and passed to the `mocha` instance of the main process. They are not transmitted to the child-processes.

Working with environment variables should work though. They get passed through from main to child-processes and should be accessible on `process.env`.

**Comment by shivang16** [comment]
@juergba I'm facing a similar issue. I'm using the gulp task to run the mocha test. 
I'm first triggering the gulp task with some arguments (let's say --a --b --c)
And inside the gulp task, I'm triggering the mocha test with some arguments(say --d --e --f)

If I run the test serially 
`process.args` gives me all (--a --b --c --d --e --f)
But when I run it parallelly  
even the
`process.env` gives me --a --b --c (`process.args` will anyways won't work according to your above reply)

How do I get all the flags in parallel mode in the way I'm running the test?
