### ISSUE TITLE
Please update to yargs ≥ 17

### ISSUE THREAD

**Issue by guimard** [mochajs/mocha#4809]
### Prerequisites

- [X] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [X] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [X] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [X] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Hi, yhen using mocha with last yargs, mocha prints help and this error: `undefined ERROR: Cannot read property 'split' of undefined` without explaining where is the problem

### Steps to Reproduce

 * clone any package that uses mocha for test
 * install dependencies
 * update `node_modules/yargs` to last
 * launch test

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 9.1.3
- The output of `node --version`: 12.22.7
- Your operating system
  - name and version: Debian/unstable
  - architecture (32 or 64-bit): 64
- Your shell (e.g., bash, zsh, PowerShell, cmd): bash

Cheers,

**Comment by juergba** [comment]
We are careful with updating Yargs, it's a key dependency and there must be a good reason to do a major version bump. You haven't mentioned any, a major update for no reason is not worth the risk. So currently we are not planing to update yargs or yargs-parser.

I don't know the reason of your error message, the changelog of Yargs should give you some hints by listing all breaking changes v16=>17.

**Comment by guimard** [comment]
Thanks @juergba. I'm [Debian Developer](https://qa.debian.org/developer.php?email=yadd%40debian.org) and maintainer of mocha. I'll try to find a patch to be able to upgrade yargs in Debian.

Cheers,

**Comment by juergba** [comment]
@guimard every package like Mocha contains a `package.json` file which defines all dependencies with their exact version or range of versions. Eg. Mocha@9.1.3 depends on Yargs@16.2.0. You can't just update Yargs to latest and expect Mocha@9.1.3 to keep running.
When you run `npm install mocha`, npm downloads all dependencies as per `package.json`. So I don't really understand this Debian issue. Does Mocha run on Debian without installing it? Without considering Mocha's  `package.json`?

**Comment by guimard** [comment]
Debian forbid code duplication for various reason including security _(see [Policy Manual 4.13](https://www.debian.org/doc/debian-policy/ch-source.html#embedded-code-copies))_, then [node-mocha](https://tracker.debian.org/pkg/node-mocha) uses only Debian dependencies, there is no `node_modules` directory in it.

But of course, this is a Debian-only issue, I'll do my best to find a way and, _if success_, push an MR here for the record.

**Comment by juergba** [comment]
It seems very wrong to me to patch Mocha on Debian and nevertheless distribute it as v9.1.3. We would have two different v9.1.3 versions. 

I'm glad I'm using Windows and Ubuntu.

**Comment by guimard** [comment]
Ubuntu copies mocha from Debian. If Debian had a node_modules directory for each of its node-* packages, Size will grows a lot (and it's forbid by policy)

**Comment by guimard** [comment]
Note also that for each mocha update in Debian/unstable, test are replayed for all packages that use it for test (so hundreds packages). Migration to testing is done only when all issues are fixed.
