### ISSUE TITLE
mocha.global() function doesn't work

### ISSUE THREAD

**Issue by Ivan-Katovich** [mochajs/mocha#4820]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description
I'm trying to use mocha,globals() function to set up a global for the project: 
```
//runner.js
const Mocha = require('mocha');
var myInfo = 'Hello world';
(async () => {
    try {
        const mochaConfig = {timeout: 100000};
        const mocha = new Mocha(mochaConfig);
        mocha.global(['myInfo']);
        mocha.files = ['./test1.js'];
        mocha.run((failures) => {
            process.on('exit', () => process.exit(failures ? 1 : 0));
        });
    } catch (err) {
        process.exit(1);
    }
})();
```
```
//test1.js
describe('example spec 1', function() {
    it('first test 1',async function() {
        console.log(myInfo); //error
        console.log(global.myInfo); //undefined
        console.log(this.test.globals()); //undefined
        // what should I write to receive myInfo global ?
    });
});
```

### Steps to Reproduce

**Expected behavior:** I can access myInfo variable as global variable or somehow else in body of tests

**Actual behavior:** I can not access myInfo variable as global or any other ways

**Reproduces how often:** Each run

### Versions

- mocha version 9.1.3
.- node version 14.17.6
- Your operating system
  - windows 10
  - 64-bit
- PowerShell

### Additional Information
May be I missed something but just from official site information I didn't find any way to get access to a variable added as global using mocha.global() method.
And also is it possible to access to the globals in Worker threads if **parallel** option is set **true**

**Comment by juergba** [comment]
Mocha's functions as `describe` or `it` are on the `global` object, therefore you don't need to `require`/`import` them in your tests. So if you need a property in global scope, then just add it to `global.whatever  = ...`. This is javascript and has nothing to do with Mocha. 

[mocha.global()](https://mochajs.org/api/mocha#global) has a different purpose, see also [mocha.checkLeaks()](https://mochajs.org/api/mocha#checkLeaks).

> And also is it possible to access to the globals in Worker threads if parallel option is set true

Each worker process has its own `global`, global properties are not transmitted from main to child processes. Only environment variables are passed through from main to children.
