### ISSUE TITLE
Implement Object oriented way  to structure and execute tests similar to TestNG from Java

### ISSUE THREAD

**Issue by NazarYermolenko** [mochajs/mocha#4827]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
It would be nice to have to get the ability to structurize tests as classes and methods 
```java
public class TestNGTestOne {
  	
  	WebDriver driver;
  	
  @Test
  public void f() {
  	//Setting up the chrome driver exe, the second argument is the location where you have kept the driver in your system
  	  System.setProperty("webdriver.chrome.driver", "E:\\Softwares\\chromedriver.exe");
  	 
  	//Setting the driver to chrome driver
  	  driver = new ChromeDriver();
  	  String url = "https://www.google.com";
  	  driver.get(url);
  	  //Capturing the title and validating if expected is equal to actual
  	  String expectedTitle = "Google";
  	  String actualTitle = driver.getTitle();
  	  Assert.assertEquals(actualTitle, expectedTitle);
    }
  @BeforeMethod
  public void beforeMethod() {
  	  System.out.println("Starting the browser session");
  }
 
  @AfterMethod
  public void afterMethod() {
  	  System.out.println("Closing the browser session");
  	  driver.quit();
  }
}
```
And have a separated suite file where we can specify some parameters and tests which will be executed in a separated suite

**Additional context**
https://www.tutorialspoint.com/testng/testng_writing_tests.htm
It will allow structuring tests in a more convenient way and allows us to run tests to avoid mocha hooks.

**Comment by JoshuaKGoldberg** [comment]
This is a pretty huge change. And traditional Java design patterns around classes don't generally translate well to JavaScript. iven that nobody has interacted with this positive in 1.5 years, closing as out of scope.

Feel free to write your own decorators-based library to generate Mocha tests from decorators. It'd probably be pretty interesting to see!
