### ISSUE TITLE
Error when using the --dry-run flag with many suites

### ISSUE THREAD

**Issue by pheyos** [mochajs/mocha#4838]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Using the `--dry-run` flag with many suites causes an execution error.

### Steps to Reproduce

Basically following the [getting started steps](https://mochajs.org/#getting-started):

1. Create a new directory, execute the following steps in that directory
2. npm install mocha
3. mkdir test
4. $EDITOR test/test.js
5. Create many suites with one test each in `test.js`:
    ```javascript
    var assert = require('assert');
    describe('Wrapper suite', function () {
      for(let i=0; i < 300; i++) {
        describe(`suite ${i}`, function () {
          it(`test ${i}`, function () {
            assert.equal(1, 1);
          });
        });
      }
    });
    ```
6. Dry-run the tests with `./node_modules/mocha/bin/mocha --dry-run`

**Expected behavior:** The test output lists the suits and tests correctly.

**Actual behavior:**
- At some point, the test execution stops with an error, no summary is logged:
  ![image](https://user-images.githubusercontent.com/1945390/156158947-ba8461f4-1893-4fc0-85ee-5d5c7f59aafb.png)
- Running with `DEBUG=mocha:*`, logs `mocha:runner uncaught(): got truthy exception RangeError: Maximum call stack size exceeded`

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version` and `node_modules/.bin/mocha --version`: No global install, `node_modules/.bin/mocha --version` is 9.2.1
- The output of `node --version`: v16.13.2
- Your operating system
  - name and version: Ubuntu 20.04.4 LTS
  - architecture (32 or 64-bit): 64-bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh v5.8
- Your browser and version (if running browser tests): n/a
- Any third-party Mocha-related modules (and their versions): n/a
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): n/a

### Additional Information

- The test run finished as expected when running `./node_modules/mocha/bin/mocha` without the `--dry-run` flag.
- Running many tests in one suite instead of many suites with one test each works as expected with the `--dry-run` flag, e.g. this slightly modified `test.js` runs fine:
    ```javascript
    var assert = require('assert');
    describe('Wrapper suite', function () {
      for(let i=0; i < 300; i++) {
        it(`test ${i}`, function () {
          assert.equal(1, 1);
        });
      }
    });
    ```

**Comment by juergba** [comment]
@pheyos thank you for detailed analysis and excellent samples.
