### ISSUE TITLE
Cannot `npm update` on non-mac 

### ISSUE THREAD

**Issue by osher** [mochajs/mocha#4846]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Using any non-mac, `npm update` fails CI because `mocha` depends on `chokidar@2` which requires `os: darwin`.
This is solved by `chokiar@3` which presents itself cross-platform, while `chokiar@2` presents itself as a lib for mac.

### Steps to Reproduce

`npm i mocha@9`
and then
`npm --dev --depth 9999 --no-save update`

**Expected behavior:** [What you expect to happen]
The command to succeed.

**Actual behavior:** [What actually happens]

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
```

**Reproduces how often:** 100%.

### Versions

- The output of `mocha --version` and `node_modules/.bin/mocha --version`:
`9.2.2`

- The output of `node --version`:
`v14.16.0`

- Your operating system
  - name and version: ubuntu 18
  - architecture (32 or 64-bit):  64
  
- Your shell (e.g., bash, zsh, PowerShell, cmd): 
`zsh`
- Your browser and version (if running browser tests):
not relevant

- Any third-party Mocha-related modules (and their versions):
none

- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):
none

### Additional Information

While this may be also a bug in `npm` - I believe that by bumping chokidar we could work around it.

**Comment by juergba** [comment]
@osher Mocha is not depending on chokidar@2. I can't reproduce your issue either, on Windows.

**Comment by osher** [comment]
I double checked and this is the result:
![image](https://user-images.githubusercontent.com/803101/158062481-164e21d5-d9f1-41d9-bddb-4ead0f1d190b.png)

The error is reproduced only when `--no-save` is applied... 🤷 

I must have confused the versions, but like you can see I did get the error....
![image](https://user-images.githubusercontent.com/803101/158062373-aa05c2c4-519c-43a8-ac93-709e1f402252.png)

How wierd. This now looks like a strictly an `npm` bug...

Closing...
