### ISSUE TITLE
Incorrect numbering in TAP reporter output.

### ISSUE THREAD

**Issue by bengl** [mochajs/mocha#4847]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
~- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.~
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

I did some experimenting to see how mocha's TAP reporter deals with errors in before and after hooks. I was able to produce a test file in which the number of defined tests is 5, the number of reported tests on the `# tests` line in the TAP output (and also in the test plan) is 7, and the highest test ID in the output is 4. This seems incorrect. I'd expect all these numbers to be equal to 5.

Every version of the TAP protocol spec says that TAP data _should not_ repeat test IDs, and suggests that those parsing TAP data _should_ consider it a test error when this happens. This seems fine (but not ideal) where a before or after hook may fail and cause a test ID to be repeated to indicate the result of the test separately from indicating the failure of a hook. However, this shouldn't impact the total number of tests in the summary or in the test plan. In addition, this logic seems to be spilling over incorrectly to reduce the number of IDs to 4 when 5 tests are defined, and we can see them all having run in the TAP output.

### Steps to Reproduce

Run this test.js file with `mocha -R tap test.js`.

<details>
<summary>test.js (click to expand)</summary>

```js
describe('throwing before', () => {
  before(() => {
    throw new Error('bad')
  })
  it('works', () => {
  })
  after(() => {
  })
})

describe('throwing during', () => {
  before(() => {
  })
  it('works', () => {
    throw new Error('bad')
  })
  after(() => {
  })
})

describe('throwing after', () => {
  before(() => {
  })
  it('works', () => {
  })
  after(() => {
    throw new Error('bad')
  })
})

describe('throwing before and during', () => {
  before(() => {
    throw new Error('bad')
  })
  it('works', () => {
    throw new Error('bad')
  })
  after(() => {
  })
})

describe('throwing after and during', () => {
  before(() => {
  })
  it('works', () => {
    throw new Error('bad')
  })
  after(() => {
    throw new Error('bad')
  })
})
```

</details>

**Expected behavior:**

<details>
<summary>output (click to expand)</summary>

```
not ok 1 throwing before "before all" hook for "works"
  bad
  Error: bad
      at Context.<anonymous> (test.js:3:11)
      at processImmediate (node:internal/timers:466:21)
not ok 2 throwing during works
  bad
  Error: bad
      at Context.<anonymous> (test.js:15:11)
      at processImmediate (node:internal/timers:466:21)
ok 3 throwing after works
not ok 3 throwing after "after all" hook for "works"
  bad
  Error: bad
      at Context.<anonymous> (test.js:27:11)
      at processImmediate (node:internal/timers:466:21)
not ok 4 throwing before and during "before all" hook for "works"
  bad
  Error: bad
      at Context.<anonymous> (test.js:33:11)
      at processImmediate (node:internal/timers:466:21)
not ok 5 throwing after and during works
  bad
  Error: bad
      at Context.<anonymous> (test.js:46:11)
      at processImmediate (node:internal/timers:466:21)
not ok 5 throwing after and during "after all" hook for "works"
  bad
  Error: bad
      at Context.<anonymous> (test.js:49:11)
      at processImmediate (node:internal/timers:466:21)
# tests 5
# pass 1
# fail 4
1..5
```

</details>

**Actual behavior:**

<details>
<summary>output (click to expand)</summary>

```
not ok 1 throwing before "before all" hook for "works"
  bad
  Error: bad
      at Context.<anonymous> (test.js:3:11)
      at processImmediate (node:internal/timers:466:21)
not ok 1 throwing during works
  bad
  Error: bad
      at Context.<anonymous> (test.js:15:11)
      at processImmediate (node:internal/timers:466:21)
ok 2 throwing after works
not ok 3 throwing after "after all" hook for "works"
  bad
  Error: bad
      at Context.<anonymous> (test.js:27:11)
      at processImmediate (node:internal/timers:466:21)
not ok 3 throwing before and during "before all" hook for "works"
  bad
  Error: bad
      at Context.<anonymous> (test.js:33:11)
      at processImmediate (node:internal/timers:466:21)
not ok 3 throwing after and during works
  bad
  Error: bad
      at Context.<anonymous> (test.js:46:11)
      at processImmediate (node:internal/timers:466:21)
not ok 4 throwing after and during "after all" hook for "works"
  bad
  Error: bad
      at Context.<anonymous> (test.js:49:11)
      at processImmediate (node:internal/timers:466:21)
# tests 7
# pass 1
# fail 6
1..7
```

</details>

**Reproduces how often:** 100% of the time.

### Versions

- The output of `mocha --version` and `node_modules/.bin/mocha --version`: `9.2.2`
- The output of `node --version`: `v17.7.1`
- Your operating system
  - name and version: `Linux 5.13.0-35-generic #40-Ubuntu SMP Mon Mar 7 08:03:10 UTC 2022`
  - architecture (32 or 64-bit): `x86_64`
- Your shell (e.g., bash, zsh, PowerShell, cmd): `bash`
- Your browser and version (if running browser tests): N/A
- Any third-party Mocha-related modules (and their versions): None
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): None

**Comment by JoshuaKGoldberg** [comment]
I _think_ this is all working as expected so closing as `type: question`. But I don't use TAP much myself and may be wrong. Please point out mistakes so we can re-open if they exist! 😄 

---

> I'd expect all these numbers to be equal to 5.

7 tests comes from 5 `it` tests + 2 failing `after`s. This is a "feature": a good number of users intentionally put assertions in `after` blocks, essentially making them an ancillary test to the original one.

---

> Every version of the TAP protocol spec says that TAP data should not repeat test IDs ... a before or after hook may fail and cause a test ID to be repeated

Taking from [TAP 14 specification](https://testanything.org/tap-version-14-specification.html#test-point-id):

> Test Point IDs _should_ be unique within the TAP Document. Harnesses _may_ warn about repeated Test Point IDs or treat them as a test failure, but _must not_ treat a Test Point with a re-used ID as a non-TAP line.

Per [RFC 2119](https://datatracker.ietf.org/doc/html/rfc2119):

> **SHOULD**   This word, or the adjective "RECOMMENDED", mean that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course.

It seems to me that the `after` blocks satisfy that _"valid reasons"_ criteria here. The alternatives are:

* Have `after` blocks always auto-increment Test Point IDs
    * Not desirable: would cause unexpectedly large numbers in test suites that use them for cleanup
* Have `after` blocks only auto-increment Test Point IDs on failure
    * Not desirable: would cause in unpredictable numbers
