### ISSUE TITLE
Test body not cloned in Test.prototype.clone

### ISSUE THREAD

**Issue by rockwalrus** [mochajs/mocha#4849]
### Prerequisites
- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

[`Test.prototype.clone()`](https://github.com/mochajs/mocha/blob/d7f6ea5f5d8406204053618c708634dbf5aa9670/lib/test.js#L71) does not clone `this.body`. This results in unexpected code bodies being reported when using custom code bodies with the `retries` feature.

### Steps to Reproduce

A simple way to reproduce this in CodeceptJS 3.x (which uses custom bodies in order to show the test body instead of its wrapper around the test) is to run the following test with the Mochawsome reporter: 
```js
Scenario('wrong code', ({I}) => {
  I.waitForText('nonexistent text');
}).retries(2);
```

**Expected behavior:**
The Mochawesome report shows the code of the test

**Actual behavior:**
The Mochawesome report shows the code of the [wrapper](https://github.com/codeceptjs/CodeceptJS/blob/feadbd830c2d85c2f62f65700ebc60638900c58e/lib/scenario.js#L35).

**Reproduces how often:**
Every time.

### Versions

CodeceptJS 3.2.3 uses 8.1.3, but the problem is present in mocha's `master` as well.

**Comment by JoshuaKGoldberg** [comment]
@rockwalrus could you post a standalone reproduction please? Most folks aren't familiar with any arbitrary framework such as CodeceptJS, and `test.body` isn't used often enough by consumers for this to be a commonly understood case.

**Comment by JoshuaKGoldberg** [comment]
Closing out old issues. If someone does have a repro, please do post back - we'd be happy to take a look! 🤎
