### ISSUE TITLE
windows drive letter casing bug

### ISSUE THREAD

**Issue by lovettchris** [mochajs/mocha#4851]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Tests fail when drive letter is lower case.

### Steps to Reproduce

[repro.zip](https://github.com/mochajs/mocha/files/8308722/repro.zip)

```
npm install
node index.js
```

**Expected behavior:** [What you expect to happen]

Test should pass and print:
```
 √ Lean3 project
```

**Actual behavior:** [What actually happens]

Tests fail with this error:
```
TypeError: Cannot read properties of undefined (reading 'describe')
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

- The output of `mocha --version` and `node_modules/.bin/mocha --version`: 8.4.0
- The output of `node --version`: v16.14.0
- Your operating system
  - name and version: Windows 11 21H2 build 22000.588
  - architecture (32 or 64-bit): 64-bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): cmd
- Your browser and version (if running browser tests): running vscode tests using VS code 1.65.2.
- Any third-party Mocha-related modules (and their versions): N/A
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): Typescript.

**Comment by juergba** [comment]
@lovettchris what do you expect us to do with this "maybe a mocha bug" issue?

**Comment by lovettchris** [comment]
Is this not the place to file mocha bugs?

**Comment by juergba** [comment]
@lovettchris Is it a mocha bug?
Then please narrow down the issue and add a simple sample for reproduction. It's not my task to debug your project and prove it is or it is not a mocha bug.

**Comment by lovettchris** [comment]
I updated the bug comment with a minimal repro.

**Comment by juergba** [comment]
Your repo is not working, `npm install` does not create the `index.js` file.

I created my own simple test scenario - run on Windows11- which shows both uppercase/lowercase do work:

```js
// test.fixture.js
suite('test suite', function() {
    console.log(this.file)
    test('test', function() {})
})

// test.js
const Mocha = require("mocha");
const path = require("path");

const mocha = new Mocha({
    ui: 'tdd'
});

mocha.addFile(path.resolve(process.cwd(), 'test.fixture.js').replace('D:', 'd:'));
mocha.addFile(path.resolve(process.cwd(), 'test.fixture.js'));
console.log(mocha.files);

mocha.run(()=> {});

// output
$ node ./test
[ 'd:\\temp\\test.fixture.js', 'D:\\temp\\test.fixture.js' ]
d:\temp\test.fixture.js
D:\temp\test.fixture.js

  test suite
    √ test

  test suite
    √ test

  2 passing (4ms)
```

**Comment by lovettchris** [comment]
> Your repo is not working, `npm install` does not create the `index.js` file.

create `index.js`?  index.js is included in my `repro.zip` file?

**Comment by juergba** [comment]
> create index.js? index.js is included in my repro.zip file?

Yes, and only you know how this file has been built.
This isn't a mocha bug => closing.

**Comment by lovettchris** [comment]
It is  a mocha bug, the only thing on the stack is mocha code:

```
>>>>>>>>> testsRoot=d:\temp\repro
TypeError: Cannot read properties of undefined (reading 'describe')
    at exports.describe (d:\temp\repro\node_modules\mocha\lib\mocha.js:119:26)
    at Object.<anonymous> (d:\temp\repro\bug.test.js:15:19)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at D:\Temp\repro\node_modules\mocha\lib\mocha.js:436:36
    at Array.forEach (<anonymous>)

```

The code was originally typescript, I gave you the javascript because you wanted a minimal repro.  So I don't understand your comment "and only you know how this file has been built." ?  People write the index.ts or index.js by hand right?

**Comment by Alvarofg** [comment]
I think I'm getting an issue that might be related:

this works as expected:
`node ".\node_modules\mocha\bin\_mocha" -u tdd --timeout 999999 --colors D:\repo\test`

this doesn't work:
` node ".\node_modules\mocha\bin\_mocha" -u tdd --timeout 999999 --colors d:\repo\test`

Error message:
`TypeError: Cannot read property 'describe' of undefined
    at exports.describe (d:\repo\node_modules\mocha\lib\mocha.js:112:26)
    at file:///d:/repo/test/testfile.js:5:1
    at ModuleJob.run (internal/modules/esm/module_job.js:169:25)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async formattedImport (D:\repo\node_modules\mocha\lib\nodejs\esm-utils.js:7:14)
    at async Object.exports.requireOrImport (D:\repo\node_modules\mocha\lib\nodejs\esm-utils.js:48:32)
    at async Object.exports.loadFilesAsync (D:\repo\node_modules\mocha\lib\nodejs\esm-utils.js:103:20)
    at async singleRun (D:\repo\node_modules\mocha\lib\cli\run-helpers.js:125:3)
    at async Object.exports.handler (D:\repo\node_modules\mocha\lib\cli\run.js:374:5)`

the only difference is the capitalization of the D/d drive. I notice the capitalization changes in the error message.  I'm using windows 10

**Comment by lovettchris** [comment]
Yep looks like what I'm getting also.

**Comment by juergba** [comment]
> edit: This is probably my fault here, my test file was something like this: [...]

> Yep looks like what I'm getting also.

Perfect.
