### ISSUE TITLE
Make native Node ESM support configurable

### ISSUE THREAD

**Issue by tbranyen** [mochajs/mocha#4853]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**

Relates to: https://github.com/mochajs/mocha/pull/4038

Currently unable to use `"type": "module"` in my mono-repo package as then Mocha runs all tests assuming native node, instead of using the configured `@babel/register` extensions loader. There seems to be a conflation that because a package is designated as native Node ESM, that means the tests should run that way. There is a big distinction in my case.

I import my code using the extension-less form:

```js
import { innerHTML } from './inner-html';
```

(See build failure in Additional context below)

**Describe the solution you'd like**

I would like to see an option to be able to disable Mocha's Node interpretation, regardless of `.mjs` or `"type": "module"` in the root `package.json`.

Something like:

```
--disable-esm
```

**Describe alternatives you've considered**

- Disabling the feature to import Node ESM from the root of my project
- Converting all my imports to have an extension

**Additional context**

```sh
λ NODE_ENV=test+cov nyc -r=lcov mocha test/_setup test test/integration/*.js


Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/tim/git/diffhtml/packages/diffhtml/lib/util/types' imported from /home/tim/git/diffhtml/packages/diffhtml/lib/util/pool.js
    at finalizeResolution (internal/modules/esm/resolve.js:285:11)
    at moduleResolve (internal/modules/esm/resolve.js:708:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:798:11)
    at Loader.resolve (internal/modules/esm/loader.js:100:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:246:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36)
```

**Comment by juergba** [comment]
@tbranyen I haven't really understood your request, but it seems very weird to me to configure a project as ESM (via `.mjs` or `type: module`) and then instruct Mocha to do the opposite.

Have you noted this in Babel's docs?
> Note: @babel/register does not support compiling native Node.js ES modules on the fly, since currently there is no stable API for intercepting ES modules loading.

Have you tried this: [babel-register-esm](https://www.npmjs.com/package/babel-register-esm)?

@giltayar cc

**Comment by tbranyen** [comment]
@juergba ah I missed that in the babel register docs :+1:. This may be a non-issue for Mocha in that case.

**Comment by giltayar** [comment]
If you'd like to disable ESM, just don't put `"type": "module"` in the `package.json`, and all will be well. Putting that in the `package.json` signals to Node.js that you want all `.js` files to be ESM native.

But the ecosystem is slowly but inexorably moving to native ESM, so I would definitely investigate moving to ESM. If you need on the fly babel transpilation, like `@babel/register` does, then use the [babel-register-esm](https://www.npmjs.com/package/babel-register-esm) plugin, as @juergba suggested:

```shell
npm install babel-register-esm
mocha --loader babel-register-esm testfile.js
```

**Comment by tbranyen** [comment]
@giltayar @juergba I've been able to confirm my problem using plain Node and @babel/register as well (no mocha). Shame, because all my other tooling still works since they don't "shadow" the node process like Mocha does. I use the `"type": "module"` attribute value since I have some files in the root that re-export from a safe Node ESM directory:

```js
export * from './dist/es/lite.js';
```

The rest of the project is not necessarily "Node ESM". Given that this is not a uniquely Mocha problem, I think it's safe to close. I will investigate using a Node ESM loader to allow extension-less imports as that seems to be the only real blocker for ATM.

**Comment by tbranyen** [comment]
Looks like Node provides an option to support extension-less imports via https://nodejs.org/api/esm.html#customizing-esm-specifier-resolution-algorithm: `--experimental-specifier-resolution=node`.

I set the following config in `.mocharc.json`, but haven't had success yet. Will update if I can get it working as this would completely solve the original ask.

```js
{
  "node-option": [
    "experimental-specifier-resolution=node"
  ]
}
```
