### ISSUE TITLE
fail-zero property doesn't seem to be working

### ISSUE THREAD

**Issue by moT01** [mochajs/mocha#4858]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

The `fail-zero` property is supposed to allow you to make it so mocha doesn't throw an error if it doesn't find any test files. I have a need for this property, but it doesn't seem to be working. Maybe I'm not using it right, or I'm just missing something - I tried it quite a few different ways with no luck.

### Steps to Reproduce

I made a [test repo](https://github.com/moT01/mocha-test) where you can reproduce the problem. There's instructions in the readme.

**Expected behavior:** [What you expect to happen]
Tests to pass

**Actual behavior:** [What actually happens]
Tests fail, here's the output:
`Error: No test files found: "./test/2.test.js"`

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Versions
9.2.2

### Additional Information

I can provide more specs if necessary.

**Comment by juergba** [comment]
> The fail-zero property is supposed to allow you to make it so mocha doesn't throw an error if it doesn't find any test files.

No, this isn't correct.
The `--fail-zero` option can be useful eg. in a CI environment to fail a test script when no tests have been executed. This can happen by eg.:
- `--grep` option which is too restrictive
- dynamically created tests setup in a incorrect way
- browser tests with incorrect karma setup

`fail-zero` has nothing to do with test files or throwing/not throwing exceptions.

**Comment by moT01** [comment]
Thanks for responding and clarifying @juergba.

Do you think this would be a valid feature request? To have an option that allows the tests to pass when no test files are found? This sounds very similar to the use case of `fail-zero` and I don't think I see a way to make that happen. Basicially, I am loading test files from an external source and once in a while they don't load properly. I want it to default to passing and not failing.

I think I can work around this using `fail-zero` and `--grep` like you mentioned, but I would need to name all my tests. Not quite what I wanted, but I can work with it if I need to.

**Comment by juergba** [comment]
> Do you think this would be a valid feature request?

No, this is an edge case I don't wan't to cover by adding an extra option.

> I think I can work around this using fail-zero and --grep like you mentioned

No, you are messing up "test" and "test file" which are two completely different objects. `--grep` is applied to tests, not to test files.

> [...]  I don't think I see a way to make that happen [...]

You could switch to using Mocha programmatically and load your test files manually by [loadFilesAsync](https://mochajs.org/api/mocha#loadFilesAsync). Then catch a potential error if your external source fails.
