### ISSUE TITLE
mocha slow startup 42/s need help with understending mocha DEBUG* mocha:suite timeout 2000 +32s

### ISSUE THREAD

**Issue by ntedgi** [mochajs/mocha#4862]
hi can someone please provide me some details about the mocha debug output I am facing very slow startup time on my ci
and after adding DEBUG=mocha:* I saw this line

`mocha:cli:run:helpers single run with 70 file(s) +327ms
mocha:mocha set lazy load to true +312ms
[2022-03-31 07:16:13.314911] using filename cache <-- first line of application code
mocha:suite timeout 2000 +32s
`
[mocha-logs.txt](https://github.com/mochajs/mocha/files/8387213/mocha-logs.txt)

I am trying to figure out what's taking these 32 secs?

**Comment by juergba** [comment]
@ntedgi
Please note, this is a Mocha issue tracker, not a help forum => closing.
