### ISSUE TITLE
mochaHooks not detected if the base export is a function

### ISSUE THREAD

**Issue by MartinKolarik** [mochajs/mocha#4870]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

```js
// hooks.js
module.exports = () => {}; // mochaHooks not detected with this line present

module.exports.mochaHooks = {
    afterEach: () => console.log(1),
};
```

This seems like something that should work and probably just needs an updated `typeof` check somewhere. Use-case is a plugin that needs to register a hook but also exports some functions for the user.

### Versions

- The output of `mocha --version` and `node_modules/.bin/mocha --version`: 9.2.2
- The output of `node --version`:  v16.6.2

**Comment by juergba** [comment]
@MartinKolarik 

`module.exports` references per default an `Object`, which is returned when requiring a module.

With your `module.exports = () => {};` you have overwritten `module.exports` from type `Object` to `Function`.
```
[Function (anonymous)] {
  mochaHooks: { afterEach: [Function: afterEach] }
}
```
Mocha isn't searching for a property named `mochaHooks` on a `Function`, neither in an `Array` nor a `Map` etc. It expects an `Object` with a property `mochaHooks` and is also documented that way:  `exports.mochaHooks = { ... }`.

**Comment by MartinKolarik** [comment]
@juergba thanks for a quick response. Yes, by default `exports` is an `object` and this changes it to a `function` but that's a fairly common pattern in node to provide a default export as well as some named exports. Functions in JS are basically callable objects, so this shouldn't cause any issues. Also, `Array`, `Map` and almost everything else is just an `object` in JS, so all of them *do* work, as you can check:

```js
module.exports = new Map();

module.exports.mochaHooks = {
    afterEach: () => console.log(1), // works because typeof new Map() === 'object'
};
```

**Comment by sudapronsirima632** [comment]
module.exports = new Map();

module.exports.mochaHooks = {
    afterEach: () => console.log(1), // works because typeof new Map() === 'object'
};

**Comment by MartinKolarik** [comment]
This is still relevant.
