### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by GaoNeng-wWw** [mochajs/mocha#4875]
I using Mocha unit test. But report an error. This is my codes.

```typescript
import {expect} from 'chai';
describe('toOption', ()=>{
    it('toOption - useApi', ()=>{
        console.log(new URL('www.baidu.com'));  //TypeError [ERR_INVALID_URL]: Invalid URL
    })
})
```

I don't know why it error look like that. I want to unit test my framework with mocha. What should i do to fix this problem? Thank everyone have spent time read.

**Comment by juergba** [comment]
https://javascript.info/url#creating-a-url
https://nodejs.org/docs/latest-v16.x/api/url.html#new-urlinput-base
