### ISSUE TITLE
assertion inside a callback that was called by an async function silently fails

### ISSUE THREAD

**Issue by thoughtsunificator** [mochajs/mocha#4881]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Inside a ``it`` callback with the ``done`` parameter :
Any async function taking callback as parameter and calling this very callback makes the first assertion throws whenever it fails thus stopping the execution of the callback.

### Steps to Reproduce

- ``npm i mocha@10.0.0 -D``

- Setup test file :

```test/my.test.js```
```javascript
var assert = require('assert');

async function b(callback) {
	callback()
}

describe('mocha assert issue', function () {

	it('test', function (done) {
		b(function() {
			assert.equal(true, false);
			done()
		})
	})

})

```

- Run ``npm test``

**Expected behavior:** 

Test runner should tell me which assertion failed.

**Actual behavior:** 

The first assertion that fail throw an error and stop the execution of the callback, after a timeout the test runner then proceed  to tell me that the done function was not called without giving me information about the assertion that failed.

```bash
> mocha



  mocha assert issue
    1) test


  0 passing (2s)
  1 failing

  1) mocha assert issue
       test:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/romain/programming/mocha-assert-bug/test/my.test.js)
      at listOnTimeout (node:internal/timers:564:17)
      at process.processTimers (node:internal/timers:507:7)


```

**Reproduces how often:** always

### Versions

- The output of `mocha --version` and `node_modules/.bin/mocha --version`: 10.0.0
- The output of `node --version`:
- v18.1.0
- Your operating system
  - name and version:  5.17.4-arch1-1
  - architecture (32 or 64-bit): 64-bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh
- Your browser and version (if running browser tests): x
- Any third-party Mocha-related modules (and their versions): x
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): x

**Comment by juergba** [comment]
@thoughtsunificator Your test is written badly. Function `b` is `async`, but you don't handle it that async way.

- use `.then(done).catch(() => done(new Error('bum')))` to process the `promise` returned by function `b`.
- or refactor your test to an `async/await` pattern:
```js
it('test', async function() {
        await b(function() {
            assert.equal(true, false);
        })
    })
```

Mocha tries to get along with buggy tests like this one on best effort base. But throwing uncaught exceptions in an async context or trying to process an async function the sync way are mostly no-goes you should fix on your side.

**Comment by thoughtsunificator** [comment]
@juergba How does it relate in any way to the bug I just filled? Mocha not reporting the failed assertion ?

**Comment by thoughtsunificator** [comment]
I've since migrated to [avajs](https://github.com/avajs/ava). It works great.
