### ISSUE TITLE
Test is passing when it should fail

### ISSUE THREAD

**Issue by ZoharLiran** [mochajs/mocha#4883]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

a test is showing it's passing even though it is suppose to fail

### Steps to Reproduce

Example of code:
```
const securityCheck = ({ req, res, callback }) => {
  if (req.user) {
    callback();
  } else {
    console.log('fail');
  }
};

function mockTest(req, res) {
  securityCheck({ req, callback: processTheCode });

  async function processTheCode() {
    res.status(200).send({ success: true });
  }
}

export default mockTest;
```

Example of test file:
```
import User from '../../../../server/models/user';
import mockTest, {  __RewireAPI__ } from
  '../../../../server/routes/tradesRoutes/mockTest';

describe('#mockTest', () => {
  describe('when user exists', () => {
    it('returns success', async() => {
      const user = new User({ email: 'xy@gmail.com' });
      await user.save();

      const req = { user };
      const res = {
        status: (code) => ({
          send: (params) => {
            expect(code).to.eql(200);
            console.log(params);
            expect(params.success).to.eql(false);
          }
        })
      };

      mockTest(req, res);
    });
  });
});
```
**Expected behavior:** Since the success value is true and the log code prints `{ success: true }` I expect the line
`expect(params.success).to.eql(false);` to fail

**Actual behavior:**
```
#mockTest
    when user exists
{ success: true }
      ✔ returns success


  1 passing (571ms)
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions 
"mocha": "^10.0.0",
"chai": "^4.2.0",

- The output of `mocha --version` and `node_modules/.bin/mocha --version`:
- The output of `node --version`:
- Your operating system
  - name and version: 2019 Mac OSX Monterey 12.2.1
  - architecture (32 or 64-bit):
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh
- Your browser and version (if running browser tests):
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):
"@babel/core": "^7.8.7",
"@babel/register": "^7.14.5",

**Comment by juergba** [comment]
@ZoharLiran you declared `processTheCode` as an async function, but don't wait for the promise to get resolved. Your `it` function doesn't wait for the result of `mockTest`.

**Comment by ZoharLiran** [comment]
@juergba even when I do place `await` before calling `processTheCode` I still get `AssertionError` but the test is showing `1 passing (582ms)`
any idea how to make the test actually fail due to the assertion error?

**Comment by juergba** [comment]
You have to start with `if (req.user) { callback(); [...]` by changing it into ` [...] await callback() [...]`, and making `securityCheck` async as well. Then climbing up the call stack switching sync into async. Sync functions calling async ones doesn't make sense.

**Comment by ZoharLiran** [comment]
I've tried that. Same result.
just tried again with adding async/await to all the call stack and still getting the same result.
I thought that the `expect` just throws an error that's suppose to be caught but even if I place just the `expect` line inside a try/catch block it still doesn't catch it. 
I am missing something and wondering if someone else came across a similar issue

**Comment by juergba** [comment]
```js
var assert = require('assert');

const securityCheck = async ({ req, res, callback }) => {
	if (true) {
	  await callback();
	} else {
	  console.log('fail');
	}
  };
  
async function mockTest(req, res) {
	await securityCheck({ req, callback: processTheCode });

	async function processTheCode() {
		res.status(200).send({ success: true });
	}
}

describe('#mockTest', () => {
	describe('when user exists', () => {
	  it('returns success', async() => {
		// const user = new User({ email: 'xy@gmail.com' });
		// await user.save();
  
		const req = { };
		const res = {
		  status: (code) => ({
			send: (params) => {
			  assert.equal(code, 200); // expect(code).to.eql(200);
			  console.log(params);
			  assert.equal(params.success, false); // expect(params.success).to.eql(false);
			}
		  })
		};
  
		await mockTest(req, res);
	  });
	});
});
```

**Comment by ZoharLiran** [comment]
so are you saying that using `expect` is not compatible with await/async ?
