### ISSUE TITLE
Parallel console.log are being grouped together in reporter

### ISSUE THREAD

**Issue by jmo1012** [mochajs/mocha#4884]
When running in parallel, the `console.log`s in my test are being grouped together in the reporter and makes it difficult to know which test the log is coming from.

Here is an example of what I am experiencing:

```
// test-file.js

describe("My test example", function () {
  it("Test 1", function () {
    console.log("Console log Test 1");
  });
  it("Test 2", function () {
    console.log("Console log Test 2");
  });
  it("Test 3", function () {
    console.log("Console log Test 3");
  });
});
````

When `parallel: false` the spec reporter returns this:
```
  My test example
Console log Test 1
    ✔ Test 1
Console log Test 2
    ✔ Test 2
Console log Test 3
    ✔ Test 3
```

When `parallel: true`, the spec reporter returns this:
```
Console log Test 1
Console log Test 2
Console log Test 3

  My test example
    ✔ Test 1
    ✔ Test 2
    ✔ Test 3
```

**node version**: 16.13.0
**Mocha version**: 9.2.2
**Mocha options**:
```
mocha = new Mocha({
      parallel: true,
      exit: true,
      timeout: program.timeout || 60000,
      fullTrace: true,
    });
```

Is it possible to have parallel enabled, but keep the `console.log`s grouped with each test? Thank you.

**Comment by juergba** [comment]
No, this isn't possible. The events of a child process are buffered until the corresponding test file has been executed. Then the results are reported in one chunk. This is needed to prevent a confusing reporting mess when various child processes are used in parallel mode.

In contrast the stdio streams are directly piped through from child to parent process.
