### ISSUE TITLE
Mocha watch-files doesn't appear to be working...

### ISSUE THREAD

**Issue by pmechamatbercadia** [mochajs/mocha#4891]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description
Mocha watch-files option doesn't appear to be working when hosted in a docker container, any change to the tet file done inside or outside container does not trigger a retest.  
I've tried using various mocha parameter setting methods.  

Not sure what I'm doing wrong :)

### Steps to Reproduce
I've got a docker setup that should recreate the problem.

**Expected behavior:**
I would love for mocha to see that the file has changed and re-run the tests.

**Actual behavior:** Mocha just says, "[mocha] waiting for changes..." and no file changes notifications ever seem to be tirggered.

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version` and `node_modules/.bin/mocha --version`:

- node --version
v16.15.0

- mocha --version
10.0.0

- Your operating system
  Windows running docker: 

- architecture
  64bit:

- Your shell
bash

### Additional Information
Happy to help debug anytime.  801-362-9545

**Comment by pmechamatbercadia** [comment]
I've inserted a zip file that you can extract and then run:
docker-compose up

Which should do an npm install and then run the test in the test/services folder and leave mocha running in watch mode.

Then with and editor you can just edit the test/services/mocha.test.js file, by removing the second test comment and saving.

This is where I believe I'm seeing an issue because I expected mocha to rerun the tests.

[mochatest.zip](https://github.com/mochajs/mocha/files/8874648/mochatest.zip)

**Comment by pmechamatbercadia** [comment]
Any guidance or help would be appreciated.

**Comment by pmechamatbercadia** [comment]
This is what I see in the output and when I change a file, either inside or outside the docker container nothing happens:

~/dev/aggregators/mochatest$ docker-compose up
Starting mochatest_app_1 ... done
Attaching to mochatest_app_1
app_1  |
app_1  | > mochatest@0.0.0 test-watch
app_1  | > mocha --watch --watch-files 'test/**/*.test.js' --require @babel/register test/setup.unit 'test/**/*.test.js' test/index.unit
app_1  |
app_1  |
app_1  | WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
app_1  |
app_1  | You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:
app_1  |
app_1  |   npm install --save core-js@2    npm install --save core-js@3
app_1  |   yarn add core-js@2              yarn add core-js@3
app_1  |
app_1  | {"level":40,"time":1654821157890,"pid":17,"hostname":"76ebe1a38901","name":"mochatest","msg":"Server started!!!","v":1}
app_1  | {"level":40,"time":1654821157891,"pid":17,"hostname":"76ebe1a38901","name":"mochatest","msg":"Initializing","v":1}
app_1  | {"level":40,"time":1654821157981,"pid":17,"hostname":"76ebe1a38901","name":"mochatest","msg":"Initialization successful. Service is Ready.","v":1}
app_1  | {"level":40,"time":1654821158180,"pid":17,"hostname":"76ebe1a38901","name":"mochatest","msg":"Server started on http://0.0.0.0:5222","v":1}
app_1  |
app_1  |
app_1  |   Test case setup
app_1  | {"level":40,"time":1654821158184,"pid":17,"hostname":"76ebe1a38901","name":"mochatest","msg":"Setting log level to silent...","v":1}
app_1  |     ✔ MySql Migration should be completed before running the test cases.
app_1  |
app_1  |   mocha Tests()
app_1  |     ✔ #Simple test 1
app_1  |
app_1  |   Server a statup
app_1  |     #createApp
app_1  |       ✔ should create an express app
app_1  |
app_1  | {"level":40,"time":1654821158196,"pid":17,"hostname":"76ebe1a38901","name":"mochatest","msg":"Restoring log level to \"info\"...","v":1}
app_1  |
app_1  |   3 passing (16ms)
app_1  |
app_1  | ℹ [mocha] waiting for changes...
app_1  | {"level":40,"time":1654821159189,"pid":17,"hostname":"76ebe1a38901","name":"mochatest","msg":"waiting done!!!","v":1}

**Comment by pmechamatbercadia** [comment]
![image](https://user-images.githubusercontent.com/106122318/172967127-014d1738-f6ef-4dc3-ae2b-1fdd09b54db3.png)

**Comment by juergba** [comment]
I'm no docker expert. But I don't see how Mocha's watcher inside a container should be triggered while changing a test file outside of the container. This doesn't make sense to me.

> Then with an editor you can just edit the test/services/mocha.test.js file, by removing the second test comment and saving.

Have you done this inside the container? Is this possible at all? I know that containers can be run interactively by getting access to a shell. The relative paths you are using with `--watch-files` may be incorrect then? Try to manually re-run the tests by typing `rs<ENTER>`.

I'm not going to investigate or debug on this issue. I don't have time for this.

**Comment by KennethTrecy** [comment]
> Any guidance or help would be appreciated.

Have you tried defining the `CHOKIDAR_USEPOLLING` environment variable? By setting it to true, it is possible to watch tests from the container to a mounted directory where the tests exist.

Fortunately, I created a [repository] as an example. Here is an example output from my container:
![image](https://user-images.githubusercontent.com/33564322/209164632-ce6a0fa6-e48a-44b2-a4cb-e0b8e95d3dea.png)

I hope this helps :)

[repository]: https://github.com/KennethTrecy/docker_mocha

**Comment by JoshuaKGoldberg** [comment]
Looks like this was an issue with Docker magics. Closing as `type: question`. Someone please yell at me if I'm wrong and there actually is something to be fixed in Mocha. 🙂
