### ISSUE TITLE
Dependabot alert: glob-parent before 6.0.1 vulnerable to Regular Expression Denial of Service (ReDoS) 

### ISSUE THREAD

**Issue by yisong-li-myob** [mochajs/mocha#4902]
Hi team, 
        My project use mocha as the test framework, we found it has a dependabot alert about the glob-parent. When we try to upgrade it, it tell us : mocha@10.0.0 requires glob-parent@~5.1.2 via chokidat@3.5.3.
        Could you please check this alert and upgrade it?
Best regards

**Comment by paulmillr** [comment]
The alert is false, report this to GitHub: https://github.com/github/advisory-database/pull/531
