### ISSUE TITLE
Support tsconfig paths mapping similar to Jest's moduleNameMapper

### ISSUE THREAD

**Issue by ackvf** [mochajs/mocha#4904]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**

In a TypeScript project that uses custom `paths` aliases in `tsconfig.json`, it is not possible to import files using e.g. `@abi/something`, which is mapped in `tsconfig.json` like this

```
    "paths": {
      "@abi/*": ["abi/*"]
    }
```
**Describe the solution you'd like**
The custom paths are supported by jest using modulenamemapper

https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring

**Describe alternatives you've considered**
using hardhat plugins

**Comment by ackvf** [comment]
see https://www.npmjs.com/package/tsconfig-paths

**Comment by ackvf** [comment]
So, I actually think that the issue was caused not by the `@abi` path alias, but by the fact that I was importing a json file directly, which works in the project thanks to tsconfig `resolveJsonModule: true`, but it doesn't seem to work in mocha tests.

**Comment by ackvf** [comment]
Well, this is weird, I don't really understand what is going on.

this doesn't work
```
import AABI from '@abi/ExampleABI.json'
```

this works
```
import AABI from '../abi/ExampleABI.json'
```

However, this also seems to be working, although it might be that it is just a `type`.
```
import type { ExampleABI } from '@typings/abi'
```

What is going on? How can I use imports with path aliases and json files?

**Comment by JoshuaKGoldberg** [comment]
Sounds like this is a question more than anything else. Closing as questions should go in Discord or StackOverflow. Good luck!

**Comment by ackvf** [comment]
So, path aliases are supported by mocha, am I reading this right?

Because in my previous experiment, it was clear that

this doesn't work

```
import AABI from '@abi/ExampleABI.json'
```

and this works
```
import AABI from '../abi/ExampleABI.json'
```

**Comment by JoshuaKGoldberg** [comment]
(re-opening to put back in the triage queue)

**Comment by JoshuaKGoldberg** [comment]
Ok, yes, coming back to this now that I know more about Mocha: you're correct that Mocha doesn't natively support path aliases. Mocha directly runs JavaScript files. It doesn't set up fancy virtual environments with mapped names the way, say, [Jest's `moduleNameMapper`](https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring) does.

Mocha does support using Node.js-style loaders that can modify files on the fly - including rewriting import paths and/or transpiling TypeScript syntax to pure JavaScript. https://github.com/mochajs/mocha-examples/issues/75 -> https://github.com/mochajs/mocha-examples/pull/76 shows a couple examples of that.

If that examples repo & its open PRs doesn't include an example of using Mocha+TypeScript the way you're looking for, I'd suggest filing an issue on the repo. There's definitely a lot missing at the moment. Cheers! 🤎
