### ISSUE TITLE
"parallel" flag not working with 'command-line-args' library 

### ISSUE THREAD

**Issue by MrG360** [mochajs/mocha#4906]
I am creating a test script in Mocha where I need to take custom arguments from the terminal. I am using 'command-line-args' library in Node.js to define the custom arguments and take input from them.

Here is the program I am using:

```
  const commandLineOptionDefinitions = [
            {name: 'timeout', type: Number},
            {name: 'slow', type: Number},
            {name: 'reporter', type: String},
            {name: 'env', type: String}
        ];
    
  let options = commandLineArgs(commandLineOptionDefinitions);
```

This program runs before launching the chromedriver.

Now, when I run the script "mocha --arg1=x --arg2=y testDirectory/*.spec.js" it is working as expected and options object is returing the values from these definitions when passed.

But when I use the --parallel flag the variable options in the above code is empty i.e when i run
"mocha --arg1=x --arg2=y --parallel testDirectory/*.spec.js" is giving the options object empty irrespective of that I am passing the arguments.

Would appreciate some help as I am stuck.

**Comment by MrG360** [comment]
Any update on this, any help would be appreciated.

**Comment by juergba** [comment]
@MrG360 I don't really understand what you are trying to do.

Mocha does its own option parsing which is based on `process.argv`. Whatever you are trying to do, at the end you must call mocha with its reserved option names as `--timeout`/`--reporter`, not with your own invented option names. I don't see any difference in filling `argv` manually via CLI or by a script. 

Anyway this PR is out-of-scope, closing.

**Comment by yasaswiniparakala133** [comment]
i am facing the similar issue, while using the --parallel or parallel:true in mocharc.yml file, the cmdline args are not supported.

**Comment by yasaswiniparakala133** [comment]
@juergba @MrG360 pls help
