### ISSUE TITLE
Regular Expression Denial of Service (ReDoS) [High Severity -- SNYK] 

### ISSUE THREAD

**Issue by marcel-becker** [mochajs/mocha#4909]
SNYK is reporting a high severity vulnerability in Mocha version > 9.2.1
It is still present in Mocha 10.0.0. 
Here is the link to the vulnerability entry: https://security.snyk.io/vuln/SNYK-JS-MOCHA-2863123
This is a blocker for us. 
My organization uses SNYK as a security gate and will not allow deployment containing code with dependencies flagged with high severity vulnerabilities. 

Marcel

**Comment by Donglai-Zhang-asurion** [comment]
We occurred the same issue, and hope the community can help.

**Comment by ivanovSPvirtru** [comment]
Same here
