### ISSUE TITLE
Uncaught TypeError: hook.error is not a function MochaAllureReporter when run in parallel mode

### ISSUE THREAD

**Issue by darkallure** [mochajs/mocha#4915]
Describe the bug
Getting an error when parallel mode is on while using Mocha

To Reproduce

Set parallel mode to true in mocha.rc config or use "--parallel" flag
Run the tests
Tests fail due to the following error: Uncaught TypeError: hook.error is not a function
Expected behavior
The tests should run successfully in parallel mode with Mocha allure reporter

![image](https://user-images.githubusercontent.com/20166110/185618921-09115b3c-a1a0-4e4b-9a3a-ac77843b004a.png)
![image](https://user-images.githubusercontent.com/20166110/185618937-6c841126-200e-4d52-ab1b-b65e06e90005.png)

Additional context
the following version packages are used:
"allure-mocha": "^2.0.0-beta.19",
"mocha": "^9.2.1"

**Comment by darkallure** [comment]
Why did you close it?

**Comment by juergba** [comment]
https://github.com/mochajs/mocha/issues/4914#issuecomment-1219691986
