### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:

### ISSUE THREAD

**Issue by khteh** [mochajs/mocha#4916]
### Prerequisites

- [ x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ ] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [ ] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/src/Node.JSRestAPI/tests/fibonacci_tests.ts
require() of ES modules is not supported.
require() of /usr/src/Node.JSRestAPI/tests/fibonacci_tests.ts from /usr/src/Node.JSRestAPI/node_modules/mocha/lib/mocha.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from /usr/src/Node.JSRestAPI/package.json.

    at createErrRequireEsm (/usr/src/Node.JSRestAPI/node_modules/ts-node/dist-raw/node-internal-errors.js:46:15)
    at assertScriptCanLoadAsCJSImpl (/usr/src/Node.JSRestAPI/node_modules/ts-node/dist-raw/node-internal-modules-cjs-loader.js:584:11)
    at Object.require.extensions.<computed> [as .ts] (/usr/src/Node.JSRestAPI/node_modules/ts-node/src/index.ts:1610:5)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /usr/src/Node.JSRestAPI/node_modules/mocha/lib/mocha.js:414:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/usr/src/Node.JSRestAPI/node_modules/mocha/lib/mocha.js:411:14) {
  code: 'ERR_REQUIRE_ESM'
}
```
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

- The output of `mocha --version` and `node_modules/.bin/mocha --version`: 10.0.0
- The output of `node --version`: v18.7.0
- Your operating system
  - name and version: Ubuntu 22.04
  - architecture (32 or 64-bit): 64
- Your shell (e.g., bash, zsh, PowerShell, cmd): BASH
- Your browser and version (if running browser tests):
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): Typescript 4.7.4

**Comment by pjeby** [comment]
This issue is what happens when you use ts-node to run specs that are written in Typescript, when the overall package.json type is `module`.  However, you can add a section like this to tsconfig.json:

```json
    "ts-node": {
        "moduleTypes": {
            "*.ts": "cjs"
        }
    }
```

This tells ts-node to compile .ts files as CommonJS instead of ESM, allowing Mocha to load both the specs and module code  synchronously for testing.  But since this configuration is used only by ts-node, it should only affect your tests, not your build or distribution.

(It also has the benefit of allowing --watch to work correctly, which is not normally the case with ESM modules.)

It would probably be a good idea for this info to be part of the documentation somewhere.  I'm posting here because this is the last place I looked before I figured out a solution, so hopefully at least people searching for this problem will maybe find this comment.

**Comment by gvozdenkov** [comment]
@pjeby Do you have working example? I try your solution and maaaany other, but nothing work for `mocha --watch` :(
