### ISSUE TITLE
[Security] Consider making a version 10.0.1 release

### ISSUE THREAD

**Issue by josteink** [mochajs/mocha#4923]
When using a security-scanner in your CI pipeline, the latest stable mocha-release gets flagged as insecure:

An example of this can be seen below:
![image](https://user-images.githubusercontent.com/411338/190241387-b5710d4c-2761-4355-b460-128650413adc.png)

The suggestion to remedy this is to upgrade to an un-released git-revision of mocha (https://github.com/mochajs/mocha/commit/61b4b9209c2c64b32c8d48b1761c3b9384d411ea), something which is impractical for several reasons.

If you could push a release from current git master as 10.0.1 or whatever, that would make it easier for us to make all our security scanners go green :smile:

**Comment by mscheid-sf** [comment]
Is there any timeline for the security patch to be published?

**Comment by josteink** [comment]
Not to be *that guy*, and not to act entitled or anything (I'm a maintainer myself), but considering how what we're asking for here is a *security update*, not seeing any response at all from the maintainers is a bit disconcerting.

So just as a Jeremy Clarkson like "How hard can it be?", I decided to try to port my unit-tests from Mocha to Jest.

Aaand it really wasn't much work (30 minutes, including CI test-artifacts), and now my build is "clean", also from the security-scanner's point of view.

I guess Jest it is? :man_shrugging:

**Comment by AlenJoseph** [comment]
Will there be a version release anytime soon?
