### ISSUE TITLE
Upgrade yargs dependency to 17.x

### ISSUE THREAD

**Issue by apupier** [mochajs/mocha#4938]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
with npm audit:

```
ansi-regex  5.0.0
Severity: high
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix`
node_modules/mocha/node_modules/ansi-regex
```

```
└─┬ mocha@10.1.0
  └─┬ yargs@16.2.0
    └─┬ cliui@7.0.4
      └─┬ strip-ansi@6.0.0
        └── ansi-regex@5.0.0
```

**Describe the solution you'd like**

latest yargs 17.6.0 contains a more up to date version without the issue https://github.com/yargs/yargs/blob/6cd8e2d6a45bd4ed3521b196b14ef408b0222eee/package.json#L56

**Describe alternatives you've considered**

16.2.0 is the latest 16.x release and doesn't contian teh fix

**Additional context**

**Comment by juergba** [comment]
duplicate of #4903
