### ISSUE TITLE
🐛 Bug: RangeError: Invalid array length with Cypress version 10.8+

### ISSUE THREAD

**Issue by paulgrant** [mochajs/mocha#4943]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `mocha@10.1.0` for the project I'm working on.

Here is a link to the cypress issue: https://github.com/cypress-io/cypress/issues/24093 for further explanation.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/mocha/lib/reporters/spec.js b/node_modules/mocha/lib/reporters/spec.js
index 8497249..a3b34fb 100644
--- a/node_modules/mocha/lib/reporters/spec.js
+++ b/node_modules/mocha/lib/reporters/spec.js
@@ -42,6 +42,9 @@ function Spec(runner, options) {
   var n = 0;
 
   function indent() {
+    if(isNaN(indents)) {
+      indents = 0;
+    }
     return Array(indents).join('  ');
   }
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by JoshuaKGoldberg** [comment]
🤔 When I find-all-references on `indent` in the current `lib/reporters/spec.js`, it shows that the variable is only ever `++` incremented or `--` decremented:

```plaintext
lib/reporters/spec.js
  41, 7:   var indents = 0;
  45, 18:     return Array(indents).join('  ');
  53, 7:     ++indents;
  58, 7:     --indents;
  59, 9:     if (indents === 1) {
```

...so the only way this would be hit is if you're trying to indent `2 ** 32` times (the maximum array size in JS):

```plaintext
> new Array(2 ** 32 - 1)
(4294967295) [empty × 4294967295]

> new Array(2 ** 32)
Uncaught RangeError: Invalid array length
```

That points to a bug in code calling to Mocha. 

Thanks for filing though! 🤎
