### ISSUE TITLE
Mocha: Permission denied error occured in Jenkins while Integrating Playwright_Mocha with Jenkins via GItHub

### ISSUE THREAD

**Issue by RaviThippana** [mochajs/mocha#4955]
I am trying to run Playwright_Mocha through Jenkins, so I have created a Repository in Git Hub and the same is given in Jenkins Configuration (Source Code Management).

I have given the Build Step, to run my automation script which executes as shell command "npm run aboutPage" In which aboutPage has the script as below in package.json file.

```
 "scripts": {
"aboutPage": "mocha --timeout 800000 --config= ./.mocharc.js ./test/aboutPage.spec.js"
}
```
below are the dependencies which I have installed in my project.

```
{
  "dependencies": {
    "@supercharge/fs": "^3.4.0",
    "allure-commandline": "^2.18.1",
    "allure-mocha": "^2.0.0-beta.19",
    "chai": "^4.3.6",
    "chai-dom": "^1.11.0",
    "chai-jquery": "^2.1.0",
    "chai-visible": "^0.1.5",
    "fs-extra": "^10.1.0",
    "mocha": "^10.0.0",
    "mocha-allure-reporter": "^1.4.0",
    "mochawesome-report-generator": "^6.2.0",
    "mochawesome-screenshots": "^1.7.3",
    "mysql": "^2.18.1",
    "node-localstorage": "^2.2.1",
    "node-sessionstorage": "^1.0.0",
    "playwright": "^1.27.0",
    "prettier": "^2.7.1",
    "read-excel-file": "^5.5.3",
    "sessionstorage": "^0.1.0",
    "winston": "^3.8.2",
    "winston-daily-rotate-file": "^4.7.1"
  },
  "devDependencies": {
    "mochawesome": "^7.1.3"
  }
}
```
When I build Jenkins, below is the error displayed in the Console Output:

 npm run aboutPage

> playwright_mocha@1.0.0 aboutPage /home/qabot/data/jenkins_home/workspace/TestDemo_QA_Automation_QATAR
> mocha --timeout 800000 --config= ./.mocharc.js ./test/aboutPage.spec.js

sh: 1: mocha: Permission denied

npm ERR! Linux 4.15.0-1113-azure
npm ERR! argv "/home/qabot/.nvm/versions/node/v4.3.2/bin/node" "/home/qabot/.nvm/versions/node/v4.3.2/bin/npm" "run" "aboutPage"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! playwright_mocha@1.0.0 aboutPage: `mocha --timeout 800000 --config= ./.mocharc.js ./test/aboutPage.spec.js`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the playwright_mocha@1.0.0 aboutPage script 'mocha --timeout 800000 --config= ./.mocharc.js ./test/aboutPage.spec.js'.
npm ERR! This is most likely a problem with the playwright_mocha package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha --timeout 800000 --config= ./.mocharc.js ./test/aboutPage.spec.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls playwright_mocha
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/qabot/data/jenkins_home/workspace/TestDemo_QA_Automation_QATAR/npm-debug.log
Build step 'Execute shell' marked build as failure
Finished: FAILURE.
Please let me know what and where I am doing wrong.

Thanks in advance

**Comment by juergba** [comment]
@RaviThippana please note this is Mocha's issue tracker, not a help forum. Thank you.
