### ISSUE TITLE
Passing certain arguments after "npm test -- " skips all tests

### ISSUE THREAD

**Issue by jamietwells** [mochajs/mocha#4957]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Steps to Reproduce

- Create a simple test file, called `index.js`
- Set the contents to something simple like:
      
        it(`a`,()=>{});

- set the npm scripts block like this:
   
      "scripts": {
         "test": "mocha index.js"
      },

- run `npm test` from the command line and confirm you see

      ✔ a
    
      1 passing (3ms)

- run `npm test -- -f a` from the command line and confirm you see the same output
- run `npm test -- -f aa` from the command line

**Expected behavior:** I expect to see the same output as before

**Actual behavior:** I actually see

       
      
      0 passing (1ms)

**Reproduces how often:** Every time

### Versions

- The output of `mocha --version` and `node_modules/.bin/mocha --version`:
  
      mocha --version
      mocha : The term 'mocha' is not recognized as the name of a cmdlet, function, script file, or operable program. 
      Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
      At line:1 char:1
      + mocha --version
      + ~~~~~
          + CategoryInfo          : ObjectNotFound: (mocha:String) [], CommandNotFoundException
          + FullyQualifiedErrorId : CommandNotFoundException

      node_modules/.bin/mocha --version
      10.2.0
- The output of `node --version`: v16.14.2
- Your operating system
  - name and version: Windows 11
  - architecture (32 or 64-bit): 64 bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): PowerShell and cmd
- Your browser and version (if running browser tests): No
- Any third-party Mocha-related modules (and their versions): No
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): No

**Comment by juergba** [comment]
@jamietwells this is parsing by _npm_, not by _Mocha_. Using quotes, double-quotes or backtick quotes could evtl. help, PowerShell is sometimes behaving differentely than other shells.

I'm going to close this issue unless you have a pure Mocha sample with `node_modules/.bin/mocha`. Please also cross check you expectations against Mocha's / npm's docs.

**Comment by jamietwells** [comment]
Ah yes, I see, `-f` is already used by mocha internally to filter tests, so I need to pick something that doesn't clash. Ok, this can be closed. I'll use `-z` to pass my file name, it seem to be unused.
