### ISSUE TITLE
🚀 Feature: Explicitly programmatically fail test

### ISSUE THREAD

**Issue by dbrgn** [mochajs/mocha#4963]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**

For testing asynchronous network processing code, I wrote a small test framework. The code to be tested uses a so-called `Handle` interface. On that interface, there are `.write(data)` and `.read() -> Data` methods. During tests, I use a mock `Handle` which contains some assertions. For example, when the code to be tested calls `.read()` when we don't expect a read, an assertion is triggered.

If this assertion bubbles up, then the Mocha test fails, as intended.

However, if the code being tested has a try-catch block around this call, then the assertion error is inadvertently caught and the test does not fail.

To solve this, I'd like to have a mechanism to explicitly fail a test programmatically.

**Describe the solution you'd like**

Ideally there is a method on the test's `Context`. For example:

```ts
it('tests something', async function() {
    this.fail('The test failed');
});
```

I could then pass a reference to `this.fail` to the mocked handle, so that the test actually fails, no matter how deep down in the stack the assertion is triggered.

**Describe alternatives you've considered**

At first I thought I could use the `done` parameter:

```ts
it('tests something', async function(done: Mocha.Done) {
    done(new Error('The test failed'));
});
```

This _does_ fail the test. However, when I add the `done` parameter to an async test function, then I always must call `done()` at the end or the test fails. Without the parameter, that is not required (the async test function simply results in a promise, which is awaited by Mocha).

**Additional context**

n/a

**Comment by juergba** [comment]
@dbrgn why not simply return a rejected `Promise`, which is propagated up the call stack? Without a `done`callback.

I don't understand your scenario where you catch an error, but actually you intend the opposite.

> I could then pass a reference to `this.fail` to the mocked handle, so that the test actually fails, no matter how deep down in the stack the assertion is triggered.

I doubt this would work. The call stack isn't cleared when you fail a function on a higher level in the stack. All the pending async tasks/Promises will hang around and could lead to weird results on later tests.

**Comment by dbrgn** [comment]
The problem is that I'm mocking/injecting a certain component in a more complex system, so the failure happens deep down in the stack and there is no failed promise that I could return easily.

What I'm doing right now is setting a flag on that injected component, saying that "the assertion failed". In every test, I check for that flag at the end of the test, and explicitly fail the test if the flag is set. However, it would be nice if there were an option in mocha to fail the test even if the async test function itself resolved without an error.

(The workaround does work, so it would be fine to close this feature request. However, it would allow for more ergonomic project-specific test frameworks.)

**Comment by dbrgn** [comment]
Ah, and an example where propagating an exception (i.e. a failed rejection) through the stack is where errors are catched inside the code under test with a `try-catch` block and logged (and ignored). The code under test cannot differentiate between errors and test failures. In this case the error never reaches the top level.

**Comment by JoshuaKGoldberg** [comment]
> (The workaround does work, so it would be fine to close this feature request. However, it would allow for more ergonomic project-specific test frameworks.)

👍 

I think the fact that this hasn't been asked for a lot (only one upvote in a year) and doesn't exist in other popular frameworks that I can find (e.g. https://github.com/jestjs/jest/issues/11780#issuecomment-1056386158) is a good indication that it's out of scope for now. Closing out as wontfix.

But if someone has a strong desire to see something like `this.fail` happen, please do post back with your reasoning. We'd be happy to take another look. Cheers! 🤎
