### ISSUE TITLE
Getting Started still refers to ./node_modules/mocha/bin/mocha

### ISSUE THREAD

**Issue by mhchem** [mochajs/mocha#4966]
The Getting Started section in https://mochajs.org/ mentions
```
$ ./node_modules/mocha/bin/mocha
```

But this is not the right path anymore. #4880

**Comment by rextejiri** [comment]
fyi @juergba Hardik and I is working on this issue.

**Comment by JoshuaKGoldberg** [comment]
Fixed by #4927.
