### ISSUE TITLE
How to non-parallel testing by Mocha framework?

### ISSUE THREAD

**Issue by AlirezaEthDev** [mochajs/mocha#4967]
I'm using Mocha just like this:

```
.
.
.
const { describe } = require("mocha");
.
.
.
describe("Desciption1",function(){
   describe("Description2",function(){
      it("Description2'".function(){
               ...
      });
   });
.
.
.
   describe("Description10",function(){
      it("Description10'".function(){
               ...
      });
   });
});
```
As I experienced, Mocha takes tests in parallel. I mean it executes all of ```it()```s at the same time. How can I execute them one after another? I need to execute a ```it()``` so that it started after the previous ```it()``` done!

**Comment by Munter** [comment]
Mocha does not test in parallel unless you explicitly ask t to with `--parallel`.

If you still experience parallel execution you might be seeing a symptom of doing async work, but not properly awaiting it
