### ISSUE TITLE
Request to help: Tejiri and Hardik

### ISSUE THREAD

**Issue by rextejiri** [mochajs/mocha#4968]
Hello @juergba, Hardik Patel and I would like to help with anything that would be a good first issue. We have support from @joesepi, Here is a link to a new issue we ran into while trying to create a new issue in your forked mocha repo https://github.com/mochajs/mocha/issues/4966.
Can we help with this issue for a start?

**Comment by JoshuaKGoldberg** [comment]
Welp, coming across this 10+ months later: juergba isn't maintaining Mocha anymore. But if you folks are still interested in contributing to Mocha then great! Anything marked as `status: accepting prs` that doesn't yet have an open PR is fair game.
