### ISSUE TITLE
[Feature Request] Overloading consoleLog in reporters.Base for custom reporter

### ISSUE THREAD

**Issue by chengB12** [mochajs/mocha#4971]
When creating custom reporter, and to utilize reporters.Base functions, it is best to extends  reporter.Base function.

However, mocha doesn't provide type-safe (for typescript) way to overload consoleLog function, since many of reporter.Base functions are directly call Base.consoleLog function. it would be better to overload it if we don't want it print them to console

I found I can force overload it through
```typescript
(Mocha.reporters.Base as any).consoleLog = (...data: any[]) => {
    // do my own logging
}
```

However, I feel this is undocumented and unexposed to @types/mocha, so it is subjected to change and breaks code above

can we have declared way to overload that method, ideally like
```
class MyReporter extends Mocha.reporters.base {
    override consoleLog(... data) {
        // my own logging
    }
}
```

**Comment by JoshuaKGoldberg** [comment]
Good idea! I like it, and it seems reasonable given the API docs suggest `Base` as a good starter.

Right now, `Base.consoleLog` is the equivalent of a static property on the `Base` class:

https://github.com/mochajs/mocha/blob/11c45609b56dda11460b1f8e0d2a415cf8f9915d/lib/reporters/base.js#L548

...which is referenced as `Base.consoleLog` elsewhere:

https://github.com/mochajs/mocha/blob/11c45609b56dda11460b1f8e0d2a415cf8f9915d/lib/reporters/base.js#L235

That's going to be more difficult to refactor until `Base` gets refactored to a real class per #5025. Marking as blocked on that issue.

Once #5025 is done, we can re-evaluate to see if this would be feasible without major changes in the new class structure.

**Comment by JoshuaKGoldberg** [comment]
#5025 is done. Putting this back in triage! 🥳
