### ISSUE TITLE
npm run test wont run

### ISSUE THREAD

**Issue by mary446** [mochajs/mocha#4990]
would you please assist on this I get this error always$ npm run test

> js-basics-functions-lab@0.1.0 test
> mocha --timeout 5000 -R mocha-multi --reporter-options spec=-,json=.results.json

'\\wsl$\Ubuntu\home\mary\development\phase-1-functions-lab'      
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.

✖ ERROR: TypeError: Could not load reporter "mocha-multi":

 Error: Cannot find module 'C:\Windows\mocha-multi'
Require stack:
- C:\Users\johng\AppData\Roaming\npm\node_modules\mocha\lib\cli\run-helpers.js
- C:\Users\johng\AppData\Roaming\npm\node_modules\mocha\lib\cli\options.js    
- C:\Users\johng\AppData\Roaming\npm\node_modules\mocha\bin\mocha.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at exports.validateLegacyPlugin (C:\Users\johng\AppData\Roaming\npm\node_modules\mocha\lib\cli\run-helpers.js:237:25)
    at C:\Users\johng\AppData\Roaming\npm\node_modules\mocha\lib\cli\run.js:350:9 {      
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\johng\\AppData\\Roaming\\npm\\node_modules\\mocha\\lib\\cli\\run-helpers.js',
    'C:\\Users\\johng\\AppData\\Roaming\\npm\\node_modules\\mocha\\lib\\cli\\options.js',    'C:\\Users\\johng\\AppData\\Roaming\\npm\\node_modules\\mocha\\bin\\mocha.js'        
  ]
}
    at createInvalidReporterError (C:\Users\johng\AppData\Roaming\npm\node_modules\mocha\lib\errors.js:207:13)
    at createInvalidLegacyPluginError (C:\Users\johng\AppData\Roaming\npm\node_modules\mocha\lib\errors.js:341:14)
    at createUnknownError (C:\Users\johng\AppData\Roaming\npm\node_modules\mocha\lib\cli\run-helpers.js:220:5)
    at exports.validateLegacyPlugin (C:\Users\johng\AppData\Roaming\npm\node_modules\mocha\lib\cli\run-helpers.js:239:15)
    at C:\Users\johng\AppData\Roaming\npm\node_modules\mocha\lib\cli\run.js:350:9 {      
  code: 'ERR_MOCHA_INVALID_REPORTER',
  reporter: 'mocha-multi'
}

**Comment by plroebuck** [comment]
No idea what you did in the past so this is a shot-in-the-dark.
Here I'm assuming you're running Windows 10 and have installed the Ubuntu Linux distribution.
No experience using Windows Subsystem for Linux (WSL) though.

So let's start **WSL** (PS directory\> is the Powershell prompt). 

```powershell
PS C:\Windows\system32> wsl
```

**WSL** should start a **Bash** shell ($ is its prompt) which should be pretty close anyway

```bash
$ cd
$ pwd
/Ubuntu/home/mary   # HOPEFULLY AS I'VE NEVER USED THIS
$ cd development
$ REPO="phase-1-functions-lab"
$ REPO_URL="https://github.com/mary446/${REPO}"
$ NEW_REPO="my-assignment"
$ git clone ${REPO_URL} ${NEW_REPO}   # Make a new copy of repo
$ cd ${NEW_REPO} 
$ pwd
/Ubuntu/home/mary/development/my-assignment
$ npm install --save-dev  # install repo pieces parts here, including development
$ npm outdated  # make note just how badly this repo is out of date
$ npm test
$ exit  # return to Windows
```

Outside all the packages being hopelessly out of date (Mocha isn't 5.2.0 anymore), I don't
see any reason it shouldn't have worked (perchance `npm` assumed the wrong environment).
The error message said it couldn't find the `mocha-multi` package though where it was installed
is unclear -- it certainly couldn't find it from where the command was issued. Wasn't the WSL
viewpoint of the directory name supposed to start with '\\\wsl$'?

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaWRqMmJ0d3Y1MHlranVma3IyaXdscWt1anV4ZjN3ZHJnNDkzZ3h6OSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o72FiKtrMAjIb0Rhu/giphy.gif)
