### ISSUE TITLE
Use custom UI plugin with parallel execution

### ISSUE THREAD

**Issue by ostrovanka** [mochajs/mocha#4992]
Hello,

we are using our custom ui plugin and we enable it the following way in our code:

```
import { bddcustom } from './custom-bdd-ui';
require('mocha').interfaces['bddcustom'] = bddcustom;

 const mocha = new Mocha({
    ui: 'bddcustom',
 });
```

This works fine with sequential tests execution, but when I try to run the same with `parallel:true`, it will fail because mocha is not able to find this UI module.

As I understand the reason is because each worker has it's own Mocha instance and thus that additional interface is not available there.

If I explicitly add those 2 lines
```
const { bddcustom } = require('../../../../lib/src/mocha-ext/custom-bdd-ui');
require('mocha').interfaces['bddcustom'] = bddcustom;
```
to `node_modules/mocha/lib/nodejs/worker.js`, custom module is resolved successfully.

I have tried to add path to the file with custom plugin to `required` array in Mocha parameters - this doesn't work.

So what is the correct way to enable custom UI plugin with parallel execution?

TIA for any suggestions!

**Comment by juergba** [comment]
@ostrovanka  We had this issue some time ago, but I don't remember well. Have you checked #4659?

**Comment by juergba** [comment]
I'm closing this issue. Mixing `import` and `require` won't work anyway.

**Comment by ostrovanka** [comment]
hi @juergba , thanks for pointing me to [4659](https://github.com/mochajs/mocha/issues/4659)

I read carefully all the discussion and tried what you mentioned in one of the [comments](https://github.com/mochajs/mocha/issues/4659#issuecomment-865684938)

My code is very similar using bare minimum to validate this solution is working:

Test runner file:
```
const Mocha = require('mocha');
const { bddcustom } = require('./my-bdd');
Mocha.interfaces['mybdd'] = bddcustom;

const mocha = new Mocha({
  ui: 'mybdd',
  parallel: true,
});

mocha.addFile('./test.js');
mocha.run();
```
Custom inteface from 'my-bdd.js` file basically just copies default bdd.

Unfortunately this is not working for me.
Somehow added `interface` is lost when my code gets to `bootstrap` in the [worker.js file](https://github.com/mochajs/mocha/blob/master/lib/nodejs/worker.js#L46) and thus I am getting ` Could not load ui "mybdd"` error.

![image](https://github.com/mochajs/mocha/assets/9314788/74ee05ac-6616-4b90-ba1e-a886d20a1364)

I am using:

node: 16.18
mocha: 10.2.0

Would appreciate any help from your side on how to resolve this.

**Comment by juergba** [comment]
Probably it's incorrect to use a relative path, check your error message.
Resolve the path to `./my-bdd` before requiring it.
