### ISSUE TITLE
🚀 Feature: Improve error message "expected undefined to not equal undefined"

### ISSUE THREAD

**Issue by UlrichEckhardt** [mochajs/mocha#4996]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**

The error message is simply not helpful:

     AssertionError: expected undefined to not equal undefined

How would something ever be unequal to itself?

**Describe the solution you'd like**

I'd like to read something like this

     AssertionError: expected value to not equal undefined
     AssertionError: value is undefined

**Describe alternatives you've considered**

The workaround would be to use a custom error message, but I'd say the default should be usable already.

**Additional context**

None.

**Comment by JoshuaKGoldberg** [comment]
Could you please post a full reproduction showing how that error message was generated? It's not clear from just the brief plain text issue what libraries, if any, went into it. Does that error message even come from Mocha?

**Comment by JoshuaKGoldberg** [comment]
> would then mean it's from Chai

Precisely 🙂.

Closing out as not having a reproduction - but if you or anybody has one that shows Mocha giving an error message that should be improved, please do file a new issue with one of our new issue templates. They'll prompt for the info we need to triage. Thanks!
