### ISSUE TITLE
chore: add Node v20 to the CI test matrix

### ISSUE THREAD

**Issue by akashchouhan16** [mochajs/mocha#4997]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
The mocha workflow runs for Node 14, 16, and 18, and only recently has added ci checks for v19. It's nice to have the current Node v20 for the test matrix. 

**Describe the solution you'd like**
Addition of Node v20 to the test matrix.

**Additional context**
N/A

**Comment by JoshuaKGoldberg** [comment]
Fixed by #5020.
