### ISSUE TITLE
Inconclusive tests in mocha

### ISSUE THREAD

**Issue by blakevanlan** [mochajs/mocha#500]
Currently mocha and Nodejs do not have any concept of an inconclusive test (such as when an optional library is not installed). I ran into this problem with [Restless](https://github.com/blakevanlan/restless). Would this be something worth developing for mocha? I don't want to spend the time if it will just be rejected immediately.

**Comment by dmarcelino** [comment]
@blakevanlan, I've created a very simple node module for adding an `it.optional()` method to `it` which marks the test as pending if it would fail. I think that would fix your issue: https://github.com/dmarcelino/it-optional
