### ISSUE TITLE
Addressing Security Concerns in Our Package

### ISSUE THREAD

**Issue by davidz1337** [mochajs/mocha#5000]
Hello Team,

I hope this message finds you well. I'm writing to bring a critical issue to your attention. After conducting a vulnerability scan on our newly installed package using Vulert, it appears that there are over three potential vulnerabilities within our dependencies.

Given the magnitude of the risk that these vulnerabilities pose to our project, I am unsure of the best protocol for disclosing such issues responsibly. It's worth noting that even though some of these dependencies are only used in development, their existence in the lock file implies that they may end up in the vendor folder. Hence, addressing this is of utmost importance.

To gain a better understanding of the situation, I encourage you to review the vulnerability scan report of the package-lock file available at the following link: https://vulert.com/vuln-scan/list/329f78d9-ea29-4c6b-a459-0a2c96304a6e

I recommend that we prioritize taking decisive steps to rectify these vulnerabilities in order to safeguard our project. Should you need any further clarification or detailed insights, feel free to reach out to me.

Here's the link to the scanned lock file for your convenience: https://github.com/mochajs/mocha/blob/master/package-lock.json

Your immediate attention and swift action to this pressing issue are highly anticipated.

Best regards.

**Comment by JoshuaKGoldberg** [comment]
This looks like spam. We have other issues tagged as security.
