### ISSUE TITLE
🐛 Bug: `--(f)grep` causes `mochaHooks` to not run

### ISSUE THREAD

**Issue by JakobJingleheimer** [mochajs/mocha#5005]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

When a setup file is specified (`--require './test/mocha.setup.mjs`) that exports `mochaHooks` and `--(f)grep` is also specified, the setup file is run but `mochaHooks` are ignored.

I'm using the setup file (among other things) to set up global module mocks (courtesy of `testdouble`) in a beforeAll. When the mocks are not set, the tests explode (ex IndexedDB doesn't exist in node).

### Steps to Reproduce

1. Create a setup file with mochaHooks, like:
  ```mjs
exports const mochaHooks = {
  async beforeAll() {
    throw new Error('root beforeAll has run');
  },
};
```
1. Create a dummy test file with at least a describe + label ('example')
1. Run mocha with `--require` and `--(f)grep` (ex `npm run test:units -- --fgrep 'example'`
  1. Notice the error was not thrown.
1. Re-run the command without the `--(f)grep`
  1. Notice the error is thrown

**Expected behavior:** mochaHooks are run

**Actual behavior:** mochaHooks are ignored

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version` and `node_modules/.bin/mocha --version`: 10.2.0
- The output of `node --version`: 18.12.0
- Your operating system
  - name and version: macOS Ventura
  - architecture (32 or 64-bit): arm64
- Your shell (e.g., bash, zsh, PowerShell, cmd): bash?
- Your browser and version (if running browser tests): N/A
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): esbuild 0.18.12

**Comment by JakobJingleheimer** [comment]
Actually, it appears to be all CLI flags passed like `npm run foo -- --fgrep 'My Test'`

**Comment by JoshuaKGoldberg** [comment]
🤔 I can't reproduce this. Using the `hello-world` example from https://github.com/mochajs/mocha-examples/pull/73:

```plaintext
mocha-examples/packages/hello-world $ npm run test -- --require hooks.js --grep e

> example-browser@1.0.0 test
> mocha test.spec.js --require hooks.js --grep e

  1) "before all" hook: beforeAll in "{root}"

  0 passing (1ms)
  1 failing

  1) "before all" hook: beforeAll in "{root}":
     Error: root beforeAll has run
      at Context.beforeAll (hooks.js:3:11)
      at process.processImmediate (node:internal/timers:478:21)
```

```plaintext
mocha-examples/packages/hello-world $ npm run test -- --require hooks.js --fgrep e

> example-browser@1.0.0 test
> mocha test.spec.js --require hooks.js --fgrep e

  1) "before all" hook: beforeAll in "{root}"

  0 passing (1ms)
  1 failing

  1) "before all" hook: beforeAll in "{root}":
     Error: root beforeAll has run
      at Context.beforeAll (hooks.js:3:11)
      at process.processImmediate (node:internal/timers:478:21)
```

Could you provide a [standalone reproduction](https://antfu.me/posts/why-reproductions-are-required) please?

**Comment by JoshuaKGoldberg** [comment]
Closing out old issues. If someone does have a repro, please do post back - we'd be happy to take a look! 🤎
