### ISSUE TITLE
Executing async tests serially?

### ISSUE THREAD

**Issue by gukoff** [mochajs/mocha#5008]
I work on the project that has [many async unit tests](https://community.opengroup.org/osdu/platform/domain-data-mgmt-services/seismic/seismic-dms-suite/seismic-store-service/-/tree/master/app/sdms/tests/utest?ref_type=heads).
In the codebase, many dependencies are not explicitly passed to the classes, but are global variables or static properties on the classes.

Testing involves mocking/stubbing these global variables, and I need all unit tests to be executed serially, so that two tests running concurrently wouldn't overwrite/access each other's mocks and stubs. I wonder **how I can ensure my async tests are executed serially**?

Online resources are conflicted on this question.

The [mochajs docs](https://mochajs.org/#asynchronous-code) just describes the 3 ways of wriring acync tests but doesn't explain if any of the tests run concurtently by default.

Stackoverflow [suggests](https://stackoverflow.com/a/67046904/2116625) that one must pass the `done` callback version of the code to `it()`, then the tests will become sequential.

[This tutorial](https://masteringjs.io/tutorials/mocha/async) says that the `done` callback is archaic and only relevant for the old codebases.

**Comment by JoshuaKGoldberg** [comment]
This open question has existed for quite a while without a concrete answer. Per #5027 we've moved question-asking to Discord. If you're reading this and interested, please:

1. Search other issues for what you're trying to do
2. Ask there or StackOverflow

Cheers!
