### ISSUE TITLE
Update glob dependency to avoid minimatch@3.0.4 snyk vulnerability

### ISSUE THREAD

**Issue by tmbp95** [mochajs/mocha#5009]
Hello, I'm currently using the latest mocha version (10.2.0) which is still pointing [here](https://github.com/mochajs/mocha/blob/v10.2.0/package.json#L64) to glob 7.2.0.
Unfortunately, that version of glob still uses minimatch@3.0.4 which is being pointed out by Snyk as a vulnerability.

path: mocha@10.2.0 › glob@7.2.0 › minimatch@3.0.4

I see that the code that you currently have in the master branch is already using glob 8.1.0. Is there any timeframe for the new release?

Thank you!

**Comment by titomor-outsystems** [comment]
https://security.snyk.io/vuln/SNYK-JS-MINIMATCH-3050818

**Comment by JoshuaKGoldberg** [comment]
Duplicate of #4937.
