### ISSUE TITLE
Out of stack space error in IE

### ISSUE THREAD

**Issue by satazor** [mochajs/mocha#502]
Large amounts of tests often cause "out of stack space" errors in Internet Explorer (IE <= 9).
After analyzing the call stack when the error is thrown, it is huge!

If I let the tests "breath":

```js
  process.nextTick(function(){
    setTimeout(function () {
      next(0);
    }, 5);
  });
```
.. all is fine.

The project in which this is happening has 258 asserts and a total of 102 tests.

**Comment by jbnicolai** [comment]
I believe this is no longer an issue, with the current version of mocha.

If I'm mistaken, please comment and I'll re-open.
