### ISSUE TITLE
Any way to override or get the function from `it` block before it gets executed, using globalhooks like beforeEach

### ISSUE THREAD

**Issue by the-damarla** [mochajs/mocha#5026]
To elaborate my issue, We need to somehow get the function from `it` block and needs to execute in `nock` environment so that API calls get recorded and will be saved as fixtures, When executing the tests afterwards the responses will be played back, So is there any feature to override the it functionality from a global level.
[PreviouslyAsked](https://github.com/mochajs/mocha/issues/2737) isn't helping.

**Comment by JoshuaKGoldberg** [comment]
I don't believe there's a way to do that right now. #1457 might add it in.

Though, per #5027 we've moved question-asking to Discord. If you're reading this and interested, please:

1. Search other issues for what you're trying to do
2. Ask there or StackOverflow

Cheers!
