### ISSUE TITLE
Mocha cannot find the inherited tsconfig even though it is present in node_modules

### ISSUE THREAD

**Issue by mykola-mokhnach** [mochajs/mocha#5031]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ x Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Unit tests run by mocha stopped working after the recent minor package update with the error:

> ✖ ERROR: error TS6053: File '@appium/tsconfig/tsconfig.json' not found.

### Steps to Reproduce

1. Checkout the https://github.com/appium/appium-windows-driver project
2. Change the "typescript" devDependency version in the package.json to "~5.3"
3. Run `npm i`
4.  Run `npm run test`

**Expected behavior:** [What you expect to happen]

Unit tests are executed

**Actual behavior:** [What actually happens]

The above error message is shown. These tests were working properly before

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Versions

- The output of `mocha --version` and `node_modules/.bin/mocha --version`: 10.2.0/10.2.0
- The output of `node --version`: v20.5.1
- Your operating system
  - name and version: macOS 14.0
  - architecture (32 or 64-bit): arm64
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh
- Your browser and version (if running browser tests): -
- Any third-party Mocha-related modules (and their versions): -
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): TypeScript

### Additional Information

tsconfig:

```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "extends": "@appium/tsconfig/tsconfig.json",
  "compilerOptions": {
    "strict": false, 
    "outDir": "build",
    "types": ["node"],
    "checkJs": true
  },
  "include": [
    "index.js",
    "lib"
  ]
}
```

mocharc:

```js
module.exports = {
  require: ['ts-node/register'],
  forbidOnly: Boolean(process.env.CI)
};
```

ls node_modules/@appium/tsconfig 

```
LICENSE                 README.md               package.json            tsconfig.json           tsconfig.plugin.json
```

**Comment by mykola-mokhnach** [comment]
It looks like the issue started happening after bumping [typescript](https://www.npmjs.com/package/typescript) from v5.2 to v5.3

**Comment by davidsiu** [comment]
The problem went away after this recent change for us: https://github.com/TypeStrong/ts-node/pull/2091

**Comment by JoshuaKGoldberg** [comment]
This isn't an issue in Mocha. Mocha doesn't run any TypeScript-specific logic. It's "just" a general test framework. Mocha provides APIs/hooks for tools such as `ts-node`. Those tools are the ones that do fancy things like search for TSConfigs and transpile TypeScript code to JavaScript.

That's why, as @davidsiu kindly pointed out, the solution ended up being in `ts-node`. 💯
