### ISSUE TITLE
json reporter separator configuration

### ISSUE THREAD

**Issue by TheSnakeWitcher** [mochajs/mocha#5033]
Hi, I am building an adapter to integrate the hardhat framework(which use mocha) with neovim. To correctly do that I need a way to identify all path or sections in the `fullTitle` field from the json reporter output data or at least be capable to configure a separator between then.

Asumming the following structure

```typescript
describe("root describe block",function() {

    describe("depth1 describe block", function() {
        it("test case", async function() {
               /* assertions */
        });
    });
    
})
```

The json reporter will output something like
```json
{
    "title": "test case",
    "fullTitle": "root describe block depth1 describe block test case"
}
```

Because the separator is a space there is no pattern that allow to split in sections the `fullTitle` field. An option could be to make the user to manually insert those but I think that is a unnecesary mental overhead and could be very error prone.

Could be posible to define a `separator` field in the configuration ? Thanks in advanced.

**Comment by Uzlopak** [comment]
@TheSnakeWitcher 
Are you willing to provide a PR? :)

**Comment by TheSnakeWitcher** [comment]
I was already looking the json reporter code but I didn't see anything about how `fullTitle` is computed. Only that is obtained using `test.fullTitle()`.
About the PR I must say that I am not a js developer, I just have use it sometimes punctually when needed, but tell me what can I do to help.
