### ISSUE TITLE
Donating Funds to Mocha

### ISSUE THREAD

**Issue by Lfada** [mochajs/mocha#5079]
### Feature Request Checklist

- [X] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/master/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/master/.github/CONTRIBUTING.md)
- [X] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [ ] I want to provide a PR to resolve this

### Overview

Hi Mocha maintainers. I'm Lucas, a core contributor to the [Drips](https://www.drips.network/) project. I help recipients of donations through their learning and onboarding process.

[Ethers.JS](https://twitter.com/ethersproject) has been using https://github.com/mochajs/mocha. It's one of their most critical dependencies!

Ethers.JS core contributors appreciate the work you all do and want to make sure that you are all well-funded to keep doing it. For that reason, they have decided to donate some funds to your project through [Drips](https://www.drips.network/)

Who can I talk to about it?

cc: @tj , @boneskull , @juergba , @craigtaub 

### Suggested Solution

By talking to a core-team member 

### Alternatives

n/a

### Additional Info

Visit drips.network for more context.

**Comment by Uzlopak** [comment]
@JoshuaKGoldberg is doing the financial aspects.

**Comment by JoshuaKGoldberg** [comment]
Hey thanks for looking into this @Lfada - we really appreciate it! ❤️

Mocha has an Open Collective (https://opencollective.com/mochajs) you can direct funds to. It's linked by https://mochajs.org/#sponsors and natively on GitHub in [`.github/FUNDING.yml`](https://github.com/mochajs/mocha/blob/53a4bafbdeb32576440b0a21787f2525585411c0/.github/FUNDING.yml).

Note that a new round of maintainers recently joined: see pinned issue #5027. We're still ramping up and haven't yet started work on an invoicing/reimbursement system. The three of us new maintainers discussed informally that we'd like to send it to past maintainers based on work done, then reimburse ourselves. Details TBD.

**Comment by JoshuaKGoldberg** [comment]
Hey thanks for looking into this @Lfada - we really appreciate it! ❤️

Mocha has an Open Collective (https://opencollective.com/mochajs) you can direct funds to. It's linked by https://mochajs.org/#sponsors and natively on GitHub in [`.github/FUNDING.yml`](https://github.com/mochajs/mocha/blob/53a4bafbdeb32576440b0a21787f2525585411c0/.github/FUNDING.yml).

Note that a new round of maintainers recently joined: see pinned issue #5027. We're still ramping up and haven't yet started work on an invoicing/reimbursement system. The three of us new maintainers discussed informally that we'd like to send it to past maintainers based on work done, then reimburse ourselves. Details TBD.

If you want to talk to us more directly, you could email any of us (my email is in my GitHub bio), talk to us on the [new Mocha Discord](https://discord.gg/KeDn2uXhER), or DM us from finding us on the Discord. Whatever's easiest for you!

As an aside on funding: I hadn't yet seen Drip. Very interesting. I personally avoid cryptocurrencies on principle but would need to discuss with the other maintainers our stance on it.

**Comment by JoshuaKGoldberg** [comment]
Closing as this isn't an "issue" per se, only so that it doesn't show up on the queue. We can certainly keep talking here or privately! 😄

**Comment by Lfada** [comment]
Thanks for the response @Uzlopak and @JoshuaKGoldberg 🙏 Take this as a BIG THANK YOU on behalf of the Ethers.JS team :) 

We are in talks with Ben from OpenCollective to offer a joint solution, where they claim on the project's behalf. I suggest waiting for a bit to see if we can partner with OC. Then we would love to have a chat, to share a bit more about what we are doing, and hear your feedback.

The way Drips works, is that you can split to "dependencies". This means that you can all decide where the incoming funds are going. Parts of it could go to current or past maintainers, and also parts could go to your critical FOSS dependencies.

For Example, Ethers.JS decided to keep around 60% of the incoming funds and split 40%. You decide what percentage to split, it can also be 0% if all the incoming funds are needed.

**Comment by JoshuaKGoldberg** [comment]
> I suggest waiting for a bit to see if we can partner with OC.

👍 You got it! We'll be here. 🙂
