### ISSUE TITLE
📝 Docs: Nightly Netlify deploys are failing

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [mochajs/mocha#5098]
### Documentation Request Checklist

- [X] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/master/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/master/.github/CONTRIBUTING.md)
- [X] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [X] I want to provide a PR to resolve this

### Overview

Filing an issue for tracking & visibility: the site's nightly deploys are broken at the moment. We'll want to fix these:

```plaintext
7:19:05 PM: nps is executing `docs.postbuild` : buildProduction docs/_site/index.html --outroot docs/_dist --canonicalroot https://mochajs.org/ --optimizeimages --svgo --inlinehtmlimage 9400 --inlinehtmlscript 0 --asyncscripts && cp docs/_headers docs/_dist/_headers && node scripts/netlify-headers.js docs/_dist >> docs/_dist/_headers
7:19:05 PM: /bin/sh: 1: buildProduction: not found
7:19:05 PM: The script called "docs.postbuild" which runs "buildProduction docs/_site/index.html --outroot docs/_dist --canonicalroot https://mochajs.org/ --optimizeimages --svgo --inlinehtmlimage 9400 --inlinehtmlscript 0 --asyncscripts && cp docs/_headers docs/_dist/_headers && node scripts/netlify-headers.js docs/_dist >> docs/_dist/_headers" failed with exit code 127 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
7:19:05 PM: The script called "docs.production" which runs "nps docs && nps docs.postbuild" failed with exit code 127 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
7:19:05 PM: ​
7:19:05 PM: "build.command" failed                                        
7:19:05 PM: ────────────────────────────────────────────────────────────────
7:19:05 PM: ​
7:19:05 PM:   Error message
7:19:05 PM:   Command failed with exit code 127: npm start docs.production (https://ntl.fyi/exit-code-127)
7:19:05 PM: ​
```

### Additional Info

@voxpelli started looking into it today. Partial progress: #5095.

**Comment by voxpelli** [comment]
Yeah, the initial nps removal code is here, I need to break it out: https://github.com/mochajs/mocha/pull/5042
