### ISSUE TITLE
🛠 Repo: Remove `husky` for now

### ISSUE THREAD

**Issue by voxpelli** [mochajs/mocha#5124]
### Tooling Suggestion Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `master` branch of the repository.
- [X] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/master/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/master/.github/CONTRIBUTING.md)
- [X] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [X] I want to provide a PR to resolve this

### Overview

As mentioned in https://github.com/mochajs/mocha/pull/5042#issuecomment-1841175555, we decided to remove `husky` for now. Might re-add later.

**Comment by JoshuaKGoldberg** [comment]
Err, remove or fix? My preference would be to use it to enforce formatting on Git commit, and remove any linting.

**Comment by JoshuaKGoldberg** [comment]
Explaining why I'm not in favor of this: Husky makes it a lot harder (admittedly, not impossible) to make commits locally that aren't well-formatted.

Not every contributor uses a nicely set up editor like VS Code with format-on-save. They might be new to development, and/or using something like Nodepad++, and/or just running with odd settings. For those edge cases, it's inconvenient to have to be told by CI that your change has formatting issues. 

So from my perspective, there's very little downside to setting up formatting as a Git commit hook locally (`node_modules/` is already going to be large; Knip recognizes properly set up Husky situations). And the upside is we have a bit more consistent, reliable of a dev experience - especially for new folks.

Which brings up a question: why do you two want to remove it? Assuming we're sticking to _formatting_ on commit hooks and not _linting_ or other more intrusive and/or time-intensive tasks... why not?

**Comment by voxpelli** [comment]
I use husky on all of my own projects so I’m totally up for keeping it. I can’t remember exact reason why we discussed dropping it
