### ISSUE TITLE
🛠 Repo: Automate releases

### ISSUE THREAD

**Issue by voxpelli** [mochajs/mocha#5159]
### Tooling Suggestion Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `master` branch of the repository.
- [X] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/master/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/master/.github/CONTRIBUTING.md)
- [X] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [X] I want to provide a PR to resolve this

### Overview

We should automate the releases of Mocha.

Why?

* Lowers the threshold for releases
* Minimizes human errors
* Attestation of releases package

We could eg. do something similar to what I did in: https://github.com/neostandard/neostandard/commit/c9d442566833bf30cc1c7dc1117dc8de509d95ad

### Additional Info

The (granular) access token should be owned by a bot account. I wonder if eg. the OpenJSF account could do this?

**Comment by JoshuaKGoldberg** [comment]
+1 from me on this. It's definitely something we should do as a team (as opposed to an external contributor).
