### ISSUE TITLE
after is not getting called when the test process is interrupted by hitting Ctrl + C

### ISSUE THREAD

**Issue by c4milo** [mochajs/mocha#516]
@visionmedia what do you think about catching SIGTERM, SIGINT and SIGHUP, running the `after` callback function to clean things up in the test?

**Comment by jbnicolai** [comment]
Issue has been inactive for years, and I feel @tj was completely right in his doubt about adding the feature. Closing for now, happy to re-open if someone feels like this is still a problem.

**Comment by normanzb** [comment]
If looks like this issue still exist in mocha 6.
My use case for this is to make sure puppeteer launched chromium process gets shutted down correctly.
Now, because after() is not called, the chromium process is left in zombie state if ctrl+c is press.

**Comment by slavistan** [comment]
I'm launching docker containers inside `before()` which provide the environment for integration tests. `after()` is supposed to shutdown the ephemeral containers afterwards. This all works fine unless I terminate the tests prematurely via SIGINT, for example when something is stuck inside a loop or if I accidentally ran the wrong test suite. I then have to do the cleanup manully.

Being able to jump into `after()` on SIGINT would be a great feature.
