### ISSUE TITLE
build mocha esm module 

### ISSUE THREAD

**Issue by ZababurinSergei** [mochajs/mocha#5163]
### Bug Report Checklist

- [x] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/main/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md)
- [X] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [X] I have 'smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, my usage of Mocha, or Mocha itself.
- [X] I want to provide a PR to resolve this

### Expected

Hi.
I need to change the code in the project.

I know what I need to do, but I don't know how to build the es module for browser.

### Actual

When I use esbuild the project is not built correctly and does not run in the browser.

How can I build esm module in your project?

### Minimal, Reproducible Example

esbuild config

```
  const buildParams = {
        entryPoints: entryPoints,
        bundle: true,
        metafile: true,
        outfile: outfile,
        format: "esm",
        define,
        loader: { ".js": "jsx", ".json": "json", ".png": "file", ".jpeg": "file", ".jpg": "file", ".svg": "file", ".woff": "file" },
        color: true,
        minify: true,
        sourcemap: true,
        treeShaking: true,
        mainFields : [ 'module' , 'main' ],
        plugins: [
            glsl({
                minify: true
            }),
            aliasPlugin({
                '@src': path.resolve(__dirname, './src')
            }),
            polyfillNode({
                process: true,
                buffer: true,
                define
            }),
            cssModulesPlugin({
                v2: true,
                v2CssModulesOption: {
                    dashedIndents: true,
                    /**
                     * Optional. The currently supported segments are:
                     * [name] - the base name of the CSS file, without the extension
                     * [hash] - a hash of the full file path
                     * [local] - the original class name
                     */
                    pattern: `[name]_[local]__[hash]`
                }
            }),
            copy({
                // this is equal to process.cwd(), which means we use cwd path as base path to resolve `to` path
                // if not specified, this plugin uses ESBuild.build outdir/outfile options as base path.
                resolveFrom: 'cwd',
                assets: {
                    from: ['./src/assets/**/*'],
                    to: ['./dist/assets']
                },
                watch: false,
            })
        ]
    }

    let result = await esbuild.build(buildParams)
    console.log('BUILD: SUCCESS', result)
    console.timeEnd("⚡ [esbuild] Done")

```

### Versions

10

**Comment by JoshuaKGoldberg** [comment]
👋 this looks more like a support request question than an actual bug report. Per the [Contributing Guide](https://github.com/mochajs/mocha/blob/c43930cc6dc41980f4fcf054d506d780a28a72df/.github/CONTRIBUTING.md#-got-a-question) these kinds of questions should go on StackOverflow or in the Discord.

Aside: I'd been meaning to file #5168 -> #5169 to remove the mailing list reference, thanks for the reminder.
