### ISSUE TITLE
📝 Docs: Rephrase "New in ..." notices on versions to say "Since ..."

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [mochajs/mocha#5166]
### Documentation Request Checklist

- [X] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/main/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md)
- [X] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [X] I want to provide a PR to resolve this

### Overview

The docs on mochajs.org include a lot of notices like https://mochajs.org/#-watch-ignore-filedirectoryglob:

> New in v7.0.0

`v7.0.0` came out 4 years ago. We're on 10.x now. I don't think we need to keep any _"New in"_ notices prior to 10.

**Comment by voxpelli** [comment]
I like what Node.js does with their `Since: 7.0.0`, maybe keep them but change the wording to that?

**Comment by JoshuaKGoldberg** [comment]
Sure, works for me.

Out of curiosity: for versions > a few years old, what benefit do you see from keeping these around?

**Comment by voxpelli** [comment]
Same value as in Node, if one updates from an old version. Not very important to me though
