### ISSUE TITLE
TypeScript with `moduleResolution=nodenext` hits `error TS5110`

### ISSUE THREAD

**Issue by khteh** [mochajs/mocha#5171]
### Bug Report Checklist

- [X] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/main/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md)
- [X] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [X] I have 'smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, my usage of Mocha, or Mocha itself.
- [ ] I want to provide a PR to resolve this

### Expected

Successfully run mocha tests for my typescript project

### Actual

W.r.t https://github.com/mochajs/mocha-examples/tree/main/packages/typescript I tried `env TS_NODE_COMPILER_OPTIONS='{\"module\": \"commonjs\" }'` and hit the following error:
```
$ n run ts_test

> node.jsrestapi@1.0.0 ts_test
> export NODE_ENV=development && env TS_NODE_COMPILER_OPTIONS='{"module": "commonjs" }' ./node_modules/.bin/nyc --timeout 10000 --recursive --check-leaks --reporter=lcov --reporter=text --reporter=text-summary --reporter=html ./node_modules/.bin/mocha -r ts-node/register tests/**/*.ts --reporter mocha-junit-reporter --reporter-options mochaFile=test_reports/mocha/test-results.xml --exit

(node:150779) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:150779) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)

 Exception during run: error TS5110: Option 'module' must be set to 'NodeNext' when option 'moduleResolution' is set to 'NodeNext'.
```
No test is run at all.

### Minimal, Reproducible Example

Not minimal but here you go: https://github.com/khteh/Node.JSRestAPI

### Versions

Mocha: 10.6.0
Node: 22.2.0

### Additional Info

https://github.com/mochajs/mocha/issues/5156

**Comment by JoshuaKGoldberg** [comment]
> `error TS5110: Option 'module' must be set to 'NodeNext' when option 'moduleResolution' is set to 'NodeNext'.`

That error comes from TypeScript, and makes sense to me. If your TypeScript compiler option `'moduleResolution'` is `'NodeNext'` and you're manually specifying the TypeScript compiler `'module'` to something else, then TypeScript will give you that complaint.

> I tried `env TS_NODE_COMPILER_OPTIONS='{\"module\": \"commonjs\" }'`

Err, what? Is that part of the running command? What exactly did you try? As in, can you copy & paste the exact command you used, so I can try it on my end? I don't follow 😬. 

> Not minimal but here you go: https://github.com/khteh/Node.JSRestAPI

Neither minimal nor a reproduction from what I can see. 

---

As with #5156 -> https://github.com/mochajs/mocha/issues/5156#issuecomment-2209264922: I empathize that you're hitting some really tricky edge cases with Node.js, TypeScript, and general Mocha API endpoints. But without an _isolated minimal reproduction_ we can't help you here. We don't have the maintenance budget to go through such a large repository and isolate the _specific_ issue that _might_ be a Mocha thing vs. another misconfiguration.

https://antfu.me/posts/why-reproductions-are-required

I'm going to go ahead and close this as non-actionable. But if you can post a true isolated minimal reproduction, we'd be happy to take a look at it. 🤎

**Comment by khteh** [comment]
wr.t https://github.com/mochajs/mocha-examples/tree/main/packages/typescript
```
"ts_test": "export NODE_ENV=development && env TS_NODE_COMPILER_OPTIONS='{\"module\": \"commonjs\" }' ./node_modules/.bin/nyc --timeout 10000 --recursive --check-leaks --reporter=lcov --reporter=text --reporter=text-summary --reporter=html ./node_modules/.bin/mocha --loader=ts-node/esm -r ts-node/register tests/**/*.ts --reporter mocha-junit-reporter --reporter-options mochaFile=test_reports/mocha/test-results.xml --exit",
```
