### ISSUE TITLE
Generate HTML test results from Node?

### ISSUE THREAD

**Issue by caseywebdev** [mochajs/mocha#518]
I looked around a bunch for this and couldn't find what I was looking for, but maybe it's right under my nose. Is there a way to generate a page like http://visionmedia.github.com/mocha/example/tests.html (the final result) from node? Obviously the html reporter can only be run in-browser and the doc reporter seems close but it doesn't show the test run stats or pass/fail. Have I skipped over it somewhere or is this not implemented?

**Comment by danielstjules** [comment]
Closing for now since it's been a couple years. Let me know if you ended up creating that reporter though! :)
