### ISSUE TITLE
🐛 Bug: https://mochajs.org/api is now a 404

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [mochajs/mocha#5217]
### Bug Report Checklist

- [x] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/main/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md)
- [x] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [x] I have 'smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, my usage of Mocha, or Mocha itself.
- [x] I want to provide a PR to resolve this

### Expected

https://mochajs.org/api should exist. It's supposed to be a real website with the API docs for Mocha. Instead, right now it's the Netlify _"Page Not Found"_ default.

### Actual

We broke https://mochajs.org/api. 😬 It's supposed to be a real website with the API docs for Mocha. Instead, right now it's the Netlify _"Page Not Found"_ default.

### Minimal, Reproducible Example

Visit https://mochajs.org/api

### Versions

n/a

### Additional Info

Back in #5027, we noted:

> We don't intend to overhaul any currently-useful resources such as https://mochajs.org/ or https://github.com/mochajs/mocha/wiki. Though, we will happily accept issue reports if those resources need improvement.

That was before we had to deal with the ancient tech behind the website. It's a lot of old _stuff_ that hasn't been kept up-to-date, such as https://github.com/mochajs/mocha-docdash. #5207 tracks overhauling the website.

In the meantime, we really should fix the API docs. A workaround until then can be to visit it on the wayback machine (😬): https://web.archive.org/web/20240000000000*/https://mochajs.org/api -> https://web.archive.org/web/20240715030741/https://mochajs.org/api. Which doesn't seem to be preserving page styles. Lovely. https://github.com/mochajs/mocha/blob/main/docs/API.md is perhaps a better workaround for now.

**Comment by Nikshinde7** [comment]
Hey I would love to contribute to this! Can you elaborate more on what exactly is needed here?

**Comment by JoshuaKGoldberg** [comment]
Heya - I'm going to just overhaul the website all-up. So this is going to be a subset of #5207. Thanks though!

**Comment by JoshuaKGoldberg** [comment]
Hmm. #5240 fixed the site locally for me, but https://mochacanary.netlify.app/api and https://mochajs.org/api are still 404s... needs more investigation.

Looking through the Netlify deployments for them, the `docs/api` directory is still not generating `.html` files.

**Comment by JoshuaKGoldberg** [comment]
Aha! It's that we're deploying from the [`mochajs.org` branch](https://github.com/mochajs/mocha/tree/mochajs.org). I hadn't updated that branch to the latest. It's updated now and all is well! https://mochajs.org/api is back online. Hooray! 🥳
