### ISSUE TITLE
`mocha.css` contains `:is()` and broke in older browsers

### ISSUE THREAD

**Issue by danny0838** [mochajs/mocha#5225]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:is#browser_compatibility), `:is()` is supported since Chromium 88 and Firefox 78.

Not sure what browser versions do mocha intend to support. Our project currently targets Chromium >= 73 and Firefox >= 68, and this CSS issue prevents us from upgrading `mocha` library (from `v10.3.0`).

**Comment by JoshuaKGoldberg** [comment]
> Not sure what browser versions do mocha intend to support.

Good question. I filed #5226 just now to make this more explicit. The only explicit version indicator I could find was that Mocha 10 supports Node 14.

Some details on Node 14:
* It generally supports up through ES2020: https://compat-table.github.io/compat-table/es2016plus/#node14_6 
* It was released in April 21st, 2020: https://endoflife.date/nodejs > _Show more unmaintained releases_

For reference, equivalent browser versions end of April 2020 were:
* Chrome/Chromium 81 released April 7, 2020: https://developer.chrome.com/blog/new-in-chrome-81
* Firefox 75 released April 7, 2020: https://www.mozilla.org/en-US/firefox/75.0/releasenotes

I also asked in our Discord if anybody knows the explicit browser version support range of Mocha: https://discord.com/channels/1169379988978536528/1169381309144109177/1294295572852772887. cc @mochajs/maintenance-crew - surely this is documented somewhere?

For context, #5027 - there's a lot of info that's been lost to time & we need to pick up.

**Comment by JoshuaKGoldberg** [comment]
> prevents us from upgrading `mocha` library.

Can you be more specific, please? What's the actual visual bug that's preventing you? It'd be helpful for us as maintainers to triage this if you could provide, for example, screenshots showing the problem and/or a way for us to quickly reproduce the issue.

---

> Not sure what browser versions do mocha intend to support.

Good question. I filed #5226 just now to make this more explicit. The only explicit version indicator I could find was that Mocha 10 supports Node 14.

Some details on Node 14:
* It generally supports up through ES2020: https://compat-table.github.io/compat-table/es2016plus/#node14_6 
* It was released in April 21st, 2020: https://endoflife.date/nodejs > _Show more unmaintained releases_

For reference, equivalent browser versions end of April 2020 were:
* Chrome/Chromium 81 released April 7, 2020: https://developer.chrome.com/blog/new-in-chrome-81
* Firefox 75 released April 7, 2020: https://www.mozilla.org/en-US/firefox/75.0/releasenotes

I also asked in our Discord if anybody knows the explicit browser version support range of Mocha: https://discord.com/channels/1169379988978536528/1169381309144109177/1294295572852772887. cc @mochajs/maintenance-crew - surely this is documented somewhere?

For context, #5027 - there's a lot of info that's been lost to time & we need to pick up.

**Comment by danny0838** [comment]
> Can you be more specific, please? What's the actual visual bug that's preventing you? It'd be helpful for us as maintainers to triage this if you could provide, for example, screenshots showing the problem and/or a way for us to quickly reproduce the issue.

I think saying that all the issue is `:is()`-related is specific enough—simply replacing all `:is()` with a version without it will fix. FYI the current mocha version our project use is v10.3.0, and when using the current version (v10.7.3) there is no other CSS or script error besides this.

**Comment by danny0838** [comment]
PR provided. No matter what older browsers this project intend to support, removing `:is()` can at least fix the current downward compatibility issue and make the code more consistent with older existing code.
