### ISSUE TITLE
🐛 Bug: Custom describe block wrapper does not `await` for an internal process runs in mocha's `root hook`

### ISSUE THREAD

**Issue by 0xmaayan** [mochajs/mocha#5234]
### Bug Report Checklist

- [x] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/main/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md)
- [x] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [x] I have 'smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, my usage of Mocha, or Mocha itself.
- [ ] I want to provide a PR to resolve this

### Expected

I am using mocha to build a testing framework and wrapping mocha's describe block with a custom describe block function and injecting a custom internal instance to be used in tests suites by the end user.
```
import { describe as MochaDescribe } from "mocha";

export function describe(description: string, block: (customInstance: CustomInstance) => void) {
  MochaDescribe(description, function () {
    block(customInstance); 
  });
}
```

Everything was working as expected, until I added an internal process that runs as a root hook and when finishes assign the `customInstance` a value, that should be used in tests suites by the end user.

### Actual

Looks like the custom describe block doesnt await for the root hook to finish before assigning the new global value to be used in a test suite by the end user

### Minimal, Reproducible Example

```
// mochaConfig.ts file

const mochaConfig: CustomMochaOptions = {
    require: [path.join(__dirname, "rootHook.js")],
    parallel: true,
};

const mocha = new Mocha(mochaConfig);

// run mocha
await new Promise<number>((resolve) => {
    mocha.run(resolve);
});




// rootHook.ts file
export const mochaHooks: RootHookObject = {
  beforeAll: async function () {
    await new Promise((resolve) => setTimeout(resolve, 10000));
   // inject customInstance to the global object
   myGlobal.customInstance = {key:"value"};
  },
};





// api.ts file
export interface CustomGlobal extends NodeJS.Global {
  customInstance: {};
}

declare var global: CustomGlobal;

export var myGlobal: CustomGlobal = global;

import { describe as MochaDescribe } from "mocha";

export function describe(description: string, block: (customInstance: CustomInstance) => void) {
  MochaDescribe(description, function () {
    block(myGlobal.customInstance); 
  });
}




// test.ts file
import { describe } from "../api";

describe("my first test", (customInstance) => {
 
});
```

### Versions

```
"mocha": "^10.7.0",
node --version v21.6.2
```

**Comment by JoshuaKGoldberg** [comment]
> Minimal, Reproducible Example

This isn't an MRE 🙂 - could you please post one that we can get running quickly locally? We're a small maintenance team and don't have the time to piece stuff together.

https://antfu.me/posts/why-reproductions-are-required

Thanks!

**Comment by JoshuaKGoldberg** [comment]
👋 ping @0xmaayan, is this still something you'd like us to look at?

**Comment by JoshuaKGoldberg** [comment]
Closing as it doesn't have a MRE. If anybody has one they can post, please do - we'd be happy to take another look. Thanks!
