### ISSUE TITLE
Exclusive suites,specs

### ISSUE THREAD

**Issue by wclr** [mochajs/mocha#524]
There is the issue in Pivotal Jasmine repo that well describes the problem:
https://github.com/pivotal/jasmine/pull/181#issuecomment-7230466

what do you think is it worth to implement?

**Comment by szkrd** [comment]
iit and ddescribe is a better way to catch these keywords with lint, so while you could develop locally and ignore lint errors, the ci build tool would catch them. Is this clear?

I also find it weird that xdescribe and xit was fine, but ddescribe and iit wasn't
https://github.com/mochajs/mocha/issues/263

Would it be possible to reconsider this decision?
