### ISSUE TITLE
🛠 Repo: Cannot clone wiki repo (error: invalid path)

### ISSUE THREAD

**Issue by mark-wiemer** [mochajs/mocha#5247]
### Tooling Suggestion Checklist

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have pulled the latest `main` branch of the repository.
- [x] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/main/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md)
- [x] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [ ] I want to provide a PR to resolve this

### Overview

While proposing edits to https://github.com/mochajs/mocha/wiki/Third-party-reporters, I wanted to stage my changes for later review. I'm new to GitHub wikis, but I saw there was an option to clone at the bottom right of the page:

![Image](https://github.com/user-attachments/assets/827812d7-ecaa-4c56-8480-0818742760eb)

When cloning (on Windows, Linux untested), however, git failed to checkout, apparently because the files in the wiki contain colons in their names:

```
error: invalid path 'HOW-TO:-Correctly-stub-stdout.md'
```

As a workaround, I'm editing the wikis directly in GitHub, but it'd be nice to be able to propose changes in a more structured way.

<details><summary>Full logs</summary>

```
~/myStuff/repos/mochajs
$ git clone https://github.com/mochajs/mocha.wiki.git
2024-11-08 19:50:02
Cloning into 'mocha.wiki'...
remote: Enumerating objects: 891, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 891 (delta 0), reused 0 (delta 0), pack-reused 888 (from 1)
Receiving objects: 100% (891/891), 104.78 KiB | 1.18 MiB/s, done.
Resolving deltas: 100% (541/541), done.
error: invalid path 'HOW-TO:-Correctly-stub-stdout.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

[last: 1s]
~/myStuff/repos/mochajs
$ cd mocha.wiki
2024-11-08 19:50:55
[last: 0s]
~/myStuff/repos/mochajs/mocha.wiki (master)
$ git status
2024-11-08 19:50:57
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        deleted:    Developing-mocha.md
        deleted:    Development-environment-setup.md
        deleted:    HOW-TO:-Correctly-stub-stdout.md
        deleted:    HOW-TO:-Count-assertions.md
        deleted:    HOW-TO:-Find-a-specific-global-leak.md
        deleted:    HOW-TO:-use-environment-variables.md
        deleted:    Home.md
        deleted:    Mess-with-globals.md
        deleted:    Shared-Behaviours.md
        deleted:    Spies.md
        deleted:    Tagging.md
        deleted:    Third-party-UIs.md
        deleted:    Third-party-reporters.md
        deleted:    Using-Mocha-programmatically.md
        deleted:    Using-mocha-with-node-webkit.md
        deleted:    compilers-deprecation.md

[last: 1s]
~/myStuff/repos/mochajs/mocha.wiki (master)
$ git restore --source=HEAD :/
2024-11-08 19:51:12
error: invalid path 'HOW-TO:-Correctly-stub-stdout.md'
error: invalid path 'HOW-TO:-Count-assertions.md'
error: invalid path 'HOW-TO:-Find-a-specific-global-leak.md'
error: invalid path 'HOW-TO:-use-environment-variables.md'
[last: 0s]
~/myStuff/repos/mochajs/mocha.wiki (master)
$
```

</details>

### Additional Info

Ref #3104

**Comment by mark-wiemer** [comment]
Looks like running that recommended `git restore ...` command did copy most files, just not the ones with the colons in the name. But it's still unclear where the wiki is hosted--looks like an invisible repo linked to this one by GitHub magic! Ref [About wikis - GitHub Docs](https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis)

**Comment by JoshuaKGoldberg** [comment]
Yeah GitHub Wikis are an oddity. I don't know of any projects that have newly opted to use one in the last ... decade or so. The only ones I personally interact with ever are Mocha and the [TypeScript wiki](https://github.com/microsoft/TypeScript/wiki).

In the short term, I think this is unfortunately a wontfix. The wiki is _super_ old and we don't know what resources are linked to the current URLs with `:`s. We'll need to keep those URLs around.

Long term, I'm not convinced we should keep the wiki as a first-party resource. I do find it super unsettling that it's a classic wiki with no review process for edits. And we already have mochajs.org. Filed #5248.

Thanks for posting!
