### ISSUE TITLE
📌 Mocha 11 Release Plan

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [mochajs/mocha#5249]
**Edit (December 2nd, 2024): [`mocha@11.0.1`](https://www.npmjs.com/package/mocha/v/11.0.1) is released as `latest` on npm.**

---

We're working on a new major version of Mocha! 📦 

[Mocha 11](https://github.com/mochajs/mocha/milestone/65) will be the first new major version of Mocha in 3 years. It will contain **no new bug fixes or features** compared to v10. The only user-facing changes in Mocha 11 will be:

* #5148
* #5206

Our plan is to:
- [x] Monday, November 11th: release a "pre-release" version of Mocha 11 today to npm (_not_ as stable)
    * [`mocha@11.0.0`](https://www.npmjs.com/package/mocha/v/11.0.0) is published as `mocha@next` on npm 👍 
- [x] Wait a few business days to merge the two PRs, then >=1 business day after
- [ ] Release Mocha 11 as stable on npm

As mentioned in #5027, we're a new volunteer maintenance team and want to tread carefully with breaking changes to Mocha. We're holding off an adding any additional breaking changes until the next major version, Mocha 12, which we will not release until some time in 2025 at the earliest. We'll first learn see how the Mocha 11 release goes and learn from it. As careful as we are planning on being with Mocha 11, there is always some risk with publishing a new major version of a project. Mocha is depended upon by _thousands upon thousands_ of consuming projects, many of which are not open source or built in ways we're familiar with as a team. 

Alternating major versions between ones that purely raise engine targets and ones that add breaking feature changes is a strategy used by some other ecosystem projects, such as [typescript-eslint](https://typescript-eslint.io/blog/announcing-typescript-eslint-v7#breaking-changes).

> 👉 In the meantime, we're also working on a new docs site at **https://mocha-docs-next.netlify.app**.

**Comment by mark-wiemer** [comment]
>  It will contain no new bug fixes or features compared to the 11.

Sorry, what exactly does this mean?

**Comment by JoshuaKGoldberg** [comment]
Whoops, that should say "to 10". Fixed. Thanks :)

**Comment by jftanner** [comment]
> Wait a few business days to merge the two PRs

How're you feeling about merging #5148? It'd be nice to be able to kick the tires on `mocha@next` for a few days before a lot of US folk are away for the Thanksgiving week.

**Comment by kraenhansen** [comment]
For what it's worth, I upgraded [mocha-remote](https://github.com/kraenhansen/mocha-remote) to the v11.0.0 release and ran test without any issues 👍

**Comment by JoshuaKGoldberg** [comment]
[`mocha@11.0.1`](https://www.npmjs.com/package/mocha/v/11.0.1) is now published with the `latest` tag on npm. We're released! 🚀

**Comment by jftanner** [comment]
I've upgraded as well, and encountered no problems. Thanks!

**Comment by mark-wiemer** [comment]
@JoshuaKGoldberg sounds like we can close this one? ;) Congrats!

**Comment by JoshuaKGoldberg** [comment]
Haha I was thinking of keeping it open a bit for visibility. But every notification that comes up on it does strike fear of breakages in me... let's say next week I'll close it unless some big breakage happens.
