### ISSUE TITLE
Consider adopting the Open Test Reporting format

### ISSUE THREAD

**Issue by marcphilipp** [mochajs/mocha#5271]
**TL;DR** The JUnit team has defined a new [language-agnostic test reporting format](https://github.com/ota4j-team/open-test-reporting) and implemented a [CLI tool](https://github.com/ota4j-team/open-test-reporting/tree/d5e4e89c73d2a3286b68e715efc40cd92525fe6d#cli-tool) for validation, conversion, and HTML report generation. We're reaching out to well-known testing frameworks and reporting tools to ask for feedback and, ultimately, adoption, if you think this format provides value to your users.
### Motivation and Context
You've probably come across the "JUnit XML" format for test reporting. This format did not originate from the JUnit project but was initially introduced by the Ant build tool and then adopted by other Java build tools like Maven and Gradle. Many build servers know how to parse the XML-based format, and even non-Java tools often support it. However, it’s based on the concept of test classes and methods, so using it for frameworks and tools where those elements are not present is awkward at best. Moreover, it does not support nested structures beyond a simple parent-child relationship. Finally, it is not extensible: no additional attributes can be added without the risk of breaking existing tools.

For those reasons, many testing frameworks (for example, TestNG and Spock in the Java ecosystem) have defined their own reporting formats. This has given them the flexibility they need, but the number of tools that can parse, display, or transform their custom formats is very limited.

To overcome these limitations, the JUnit team is defining a new format for test reporting. Its goal is to be platform-agnostic so that as many testing frameworks as possible can benefit from it. Moreover, it is designed to be extensible so new data can be added as needed, without breaking consumers. However, all well-known attributes are properly defined so it remains consumable by downstream reporting tools.

Of course, it will take a while for downstream tools to support the new format. However, as the number of testing frameworks that have adopted it increases, the more likely downstream tools are to do so as well.
### Overview
The new format is based on XML because it provides more expressive ways to define schemas. Moreover, XML has typed extensions built-in via the use of multiple schemas. If a testing framework provides a listener mechanism, it should be possible to write an Open Test Reporting XML file from an extension.
### Benefits
- Easy to write [event-based XML format](https://github.com/ota4j-team/open-test-reporting/tree/d5e4e89c73d2a3286b68e715efc40cd92525fe6d?tab=readme-ov-file#event-based-format) (with optional [Java API](https://github.com/ota4j-team/open-test-reporting/tree/d5e4e89c73d2a3286b68e715efc40cd92525fe6d?tab=readme-ov-file#api-for-writing-event-based-format))
	- Supports infrastructure information, Git metadata, tags, data/file attachments
	- Custom data can be added by defining an [extension schema](https://github.com/ota4j-team/open-test-reporting/blob/main/README.adoc#schema-extensions)
- Language-agnostic
	- No Java-specific elements in the core schema
	- Not tied to the concept of test classes and methods
	- Full support for nested structures
- Extensible [HTML report generator](https://github.com/ota4j-team/open-test-reporting/tree/66b1f088b599eaecb982eb9a3ccaa15a29c1e3ec?tab=readme-ov-file#html-report)
### Next Steps
The JUnit team would be happy to get your feedback on this initiative. We can discuss here or you're welcome to [start a thread](https://github.com/ota4j-team/open-test-reporting/discussions) or [open an issue](https://github.com/ota4j-team/open-test-reporting/issues) in the Open Test Reporting repo. Should you consider adopting the new format, we'd be happy to provide guidance but we won't have the resources to actually contribute an implementation.

---
This is a bit of an unusual request so please forgive me for not picking a concrete issue template.

**Comment by JoshuaKGoldberg** [comment]
Thanks for the heads up @marcphilipp! Exciting to see a "successor" to the JUnit XML format come from the JUnit team. I'll take a look and post over on the ota4j-team/open-test-reporting side.

Per #5027, we're steering away from most feature additions to Mocha for the time being. That includes new core reporters which aren't already/yet commonplace in the JavaScript ecosystem. Given how new this format is, I'm going to close this issue for the time being. If it ends up being popular and used in other JS ecosystem projects we can certainly re-evaluate.

If you're looking to get more tread around JavaScript folks, I'd suggest looking at [Vitest](https://vitest.dev). Vitest is something like the JS ecosystem darling at the moment for unit tests. Other projects listed on https://2023.stateofjs.com/en-US/libraries/testing might be of interest to you as well.

Cheers! 🤎

**Comment by voxpelli** [comment]
It's possible to create third party reporters for Mocha, that's where I would start

**Comment by marcphilipp** [comment]
Thanks for the feedback and the pointers! 👍

**Comment by marcphilipp** [comment]
I opened https://github.com/vitest-dev/vitest/issues/7066 for Vitest.
