### ISSUE TITLE
Coverage based on uglify-js

### ISSUE THREAD

**Issue by haraldrudell** [mochajs/mocha#544]
I think it might be possible to use [bunker](https://github.com/substack/node-bunker) / [node-runforcover](https://github.com/chrisdickinson/node-runforcover) by the Oakland peeps for test coverage. Since these modules are based on uglify-js, that would remove the dependency on the node-external jscoverage command. External commands might be hard for people to install.

Good idea?

**Comment by boneskull** [comment]
closing as old.  this seems like a non-issue with the advent of istanbul and blanket, etc
