### ISSUE TITLE
JavaScript Source Maps Support

### ISSUE THREAD

**Issue by rjanicek** [mochajs/mocha#550]
Maybe it's possible to use source maps for better "view source" and doc reporter when testing with minified JS or languages that compile to JS.

http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/

Thank you.

**Comment by boneskull** [comment]
@dreampulse This is great information.  Care to post it in the wiki?

**Comment by liukun** [comment]
Agree with @dreampulse 
Better set the following option in coffeescript when `install`

        require('source-map-support').install
          handleUncaughtExceptions: false

Otherwise, function `handleUncaughtExceptions` in module `source-map-support` will call `process.exit(1)` and terminate mocha process without ending properly.

**Comment by corelgott** [comment]
@dreampulse  +1

**Comment by rosskevin** [comment]
FYI - `source-map-support` also supports chrome - lifesaver for debugging.

https://github.com/evanw/node-source-map-support#browser-support
