### ISSUE TITLE
Option to let exceptions propagate

### ISSUE THREAD

**Issue by joliss** [mochajs/mocha#553]
Mocha's browser runner always catches exceptions. I wish it could let them propagate so I can see the stack trace in the JS console.

The line numbers Mocha displays are useful when only (1) you have the file open in the editor, and (2) it's not compiled from CoffeeScript. When either of these conditions isn't met, they turn pretty useless, and you'd really prefer to have a linked stack trace like the console in Chrome or Firebug gives you.

See e.g. http://i.imgur.com/CQV37.png - that trace is not very usable, because now I have to go hunting for the offending line.

**Comment by berkerpeksag** [comment]
This is already fixed in https://github.com/mochajs/mocha/commit/23939a92849cf14d19aaa0a45670106cc41dbbc8 (see #1662) and can now be closed.

**Comment by danielstjules** [comment]
Good call, thanks! :)
