### ISSUE TITLE
docs for extending mocha

### ISSUE THREAD

**Issue by tj** [mochajs/mocha#56]
reporters, interfaces etc

**Comment by danielstjules** [comment]
@dkushner @TheLudd I think both https://github.com/mochajs/mocha/wiki/Third-party-reporters and https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically offer good examples of extending mocha. :) For full examples, you can try taking a look at some of the interfaces/reporters listed at https://github.com/mochajs/mocha/wiki#interfaces--reporters

**Comment by TheLudd** [comment]
@danielstjules Well, perhaps if there also had been a "Third party ui". I have written my own now anyway but it really required looking through the code for different uis and do a lot of experimentation. I would not say this is closed but perhaps "extending" is not clearly enough defined.

**Comment by danielstjules** [comment]
Oh, sorry! I can re-open this for now. I'll write something up on third party ui's as well. Thanks! :)

**Comment by danielstjules** [comment]
@TheLudd While it may have been more useful a while ago, I've added a page on extending mocha with Third Party UIs, which can be found here: https://github.com/mochajs/mocha/wiki/Third-party-UIs Sorry for the wait, and thanks for mentioning it!

**Comment by TheLudd** [comment]
Well thanks for creating it. Looks like a bit of work =)

**Comment by danielstjules** [comment]
Yup, but only if you want the full functionality! I updated [the page](https://github.com/mochajs/mocha/wiki/Third-party-UIs) to include a minimal example as well, which is hopefully less daunting:

``` javascript
var Mocha    = require('mocha');
    Suite    = require('mocha/lib/suite'),
    Test     = require('mocha/lib/test');

/**
 * A simple UI that only exposes a single function: test
 */
module.exports = Mocha.interfaces['simple-ui'] = function(suite){
  suite.on('pre-require', function(context, file, mocha){
    var common = require('mocha/lib/interfaces/common')([suite], context);

    context.run = mocha.options.delay && common.runWithSuite(suite);

    /**
     * Describes a specification or test-case  with the given `title`
     * and callback `fn` acting as a thunk.
     */
    context.test = function(title, fn){
      var test = new Test(title, fn);
      test.file = file;
      suite.addTest(test);

      return test;
    };
  });
};
```

**Comment by TheLudd** [comment]
I meant by you, creating this =)
