### ISSUE TITLE
an error in a beforeEach hook causes the test run to terminate prematurely

### ISSUE THREAD

**Issue by jfirebaugh** [mochajs/mocha#581]
Testcase: https://gist.github.com/3711350

As you can see from the output, only one example was executed. I would have expected the first example to fail, and then the second two to execute and pass.

**Comment by Apollon0701** [comment]
Uncaught TypeError: vue_router__WEBPACK_IMPORTED_MODULE_2__.default.beforeEach is not a function
what does this mean?
code is as follow
Router.beforeEach((to, from, next) => {
  // redirect to login page if not logged in and trying to access a restricted page
  const publicPages = ['/pages/login','/pages/register'];
  const authRequired = !publicPages.includes(to.path);
  const loggedIn = localStorage.getItem('auth_user');

  if (authRequired && !loggedIn) {
    return next('/login');
  }

  next();
})

**Comment by shridharkalagi** [comment]
i'm still seeing the same issue? any update on this issue?
