### ISSUE TITLE
Allow custom color scheme

### ISSUE THREAD

**Issue by balinterdi** [mochajs/mocha#590]
It should be possible to override the default color scheme defined in `lib/reporters/base.js`

The comment for the `color` function says this is possible:

```
/**
 * Color `str` with the given `type`,
 * allowing colors to be disabled,
 * as well as user-defined color
 * schemes.
 *
 */

var color = exports.color = function(type, str) {
  if (!exports.useColors) return str;
  return '\u001b[' + exports.colors[type] + 'm' + str + '\u001b[0m';
};
```

, but I haven't found a way to override the default colors (The types that are displayed in 90 are invisible on the Solarized Dark terminal theme).

**Comment by ekkis** [comment]
+1.  on my black terminal I find the specific shade of red used for errors very hard to read and would like to be able to change it

**Comment by ekkis** [comment]
incidentally, I changed the colour choices in `lib/reporters/base.js` but it didn't have any effect on the output so maybe there's some other location where this can be changed

**Comment by ekkis** [comment]
it's a pity to have to turn colours off but how would I do it? my tests are run from a `Gruntfile.js` via mocha-phantomjs and I have an entry like this:

    grunt.initConfig({
      mochaTest: {
        mocha_phantomjs: {
		all: ['tests/browser/*.html']
        }

**Comment by boneskull** [comment]
@ekkis that's a question for whatever grunt plugin you're using, but the option in mocha is `--no-colors`

**Comment by jellytux** [comment]
Still not fixed? I can't see mine at all, it's all black on black. :(

**Comment by nichtich** [comment]
Several solutions for solarized have been proposed in #802 but rejected as "not my problem" by mocha developers. Support of customizing colors with a config file would not change the default but allow users to decide.

**Comment by boneskull** [comment]
We could expend resources adding custom color support, OR the users with this problem could modify their terminal, which likely already has custom color support.

**Comment by brendanberg** [comment]
Solarized is a very common terminal theme and I'm sure this problem affects more than just the people on this thread.

The "not my problem" attitude alienates a community that **wants** to help out with maintenance and improvements. A little empathy goes a long way.

**Comment by boneskull** [comment]
> The "not my problem" attitude alienates a community that wants to help out with maintenance and improvements. A little empathy goes a long way.

I can't begin to tell you how profoundly mistaken you are.  So I won't; instead, I'll lock this issue so I don't forget I shouldn't.
