### ISSUE TITLE
Allow to skip() test  inside the function

### ISSUE THREAD

**Issue by wclr** [mochajs/mocha#591]
In my tests some times test need to run only if certain conditions are met, for example previous test passed (where not skipped like load and save consequent tests). 

It would be great if inside test function I could do something like that:

<code>

if (!this.fit) this.skip() // and mocha would skip the test.

</code>

**Comment by tematema** [comment]
Thx for:

(version > 3 ? it : it.skip)("should works with express.Router", function(done) {

**Comment by dark51** [comment]
This is can help. Not beauty, but working:
```coffeescript
self = null
index = 0
nextTestShouldBeSkipped = true
describe 'something: ', ->
  self = this
  it 'test1', ->
    index++
    if(nextTestShouldBeSkipped)
      self.tests[index].pending = true
      #You can modify test title if needed
      self.tests[index].title += " (skipped)." 

  it 'test2', (done)->
    done()
```

**Comment by cmbuckley** [comment]
@dark51 this has been addressed, and should have been closed by #946. (@davidsilvacontin can you close down?)

However, there is currently not a tagged version that contains that fix, so there hasn't been a build to the top-level `mocha.js` that contains the fix.

**Comment by dasilvacontin** [comment]
About the build, I'm not in charge of that. I guess both @boneskull and @travisjeffery are quite busy lately.

**Comment by cades** [comment]
+1
I use yadda, which brings gherkin to mocha. When a step fail, the following steps should be skipped. this can not be determined at first.

**Comment by flavioribeiro** [comment]
+1

**Comment by ifreecarve** [comment]
+1

I think I can provide a good use case for this.  Let's say that you are running an integration test -- hitting a real server.  

You want the test to actually log in, but it would be a bad idea to put user/password credentials in the repository, and for CI purposes you don't want them to appear on the command line.  So, you'd add them to an environment variable.

In this case, you'd want the test to conditionally skip if the environment variable was not present.  That use case could be covered by [slang800's comment](https://github.com/mochajs/mocha/issues/591#issuecomment-43154773).

However, the other reason you'd conditionally skip would be if your server couldn't be reached.  If that happens, you really can't say whether the code you're testing is working correctly or not; the only logical thing to do is abort the test *and* mark it as skipped.

**Comment by cmbuckley** [comment]
This is available as of [v2.2.0](https://github.com/mochajs/mocha/tree/2.2.0) (back in March)

**Comment by ifreecarve** [comment]
Aah, OK.  Your previous comment on this suggested that it hadn't yet made it into a tagged release.  

FYI, I got here from a google search, and none of the other docs that turned up in my searching made any mention of `this.skip()` inside tests.  The wiki doesn't seem mention this either.  So, if you have a link to the updated docs it would be valuable to post it in this thread.

**Comment by cmbuckley** [comment]
It looks like it was merged into a tag the day after my comment :-) The docs don't look to mention it, so maybe worth filing an issue on [mochajs/mochajs.github.io](https://github.com/mochajs/mochajs.github.io).

**Comment by ifreecarve** [comment]
So, I'm using v2.3.4 and got this when I tried the following:

```javascript
    it('authenticates services', (done) => {
        if (undefined === process.env.USER || undefined === process.env.PASSWORD) {
            console.log("Set environment variables for USER and PASSWORD to run network tests");
            this.skip("foo");
        }
```

`TypeError: _this.skip is not a function`

**Comment by cmbuckley** [comment]
Perhaps [mochajs/mochajs.github.io#14](https://github.com/mochajs/mochajs.github.io/pull/14) is relevant here?

**Comment by ifreecarve** [comment]
Very much so -- thanks!

**Comment by danday74** [comment]
thanks for ..

(version > 3 ? it : it.skip)("should works with express.Router", function(done) ....

which skips one test (or not) based on a condition

also works for ..

(version > 3 ? describe : describe.skip)("should works with express.Router", function(done) ....

if you want to skip an entire describe block

**Comment by jmls** [comment]
ok, so I need this ;) However, in my case `version` is gotten from an async call - which I tried to put in `before`. However, it looks like the "it" test is done before before returns . I think .. 

```
    describe('when testing seal ', () => {
        let vault;
        let status;

        before(async () => {
            vault = await connectVault();
            status = await vault.status;
            return;
        });

        (status.sealed ? it : it.skip)(
            'should seal an unsealed vault',
            async () => {
                // do the test
                return;
            }
        );
    });
```

I get the error `TypeError: Cannot read property 'sealed' of undefined` because `status` is undefined ;)

**Comment by d-adamkiewicz** [comment]
This is my try to write conditional test based on value set in async function callback
```javascript
describe("add admin account if it doesn't exist", function() {
       it("isAdmin()", function(done) {
               isAdmin(db, (value) => {
// true or false
                       this.admin = value;
                       done();
               });
       });
       it("create admin account or skip if it exists", function(done) {
               if (this.admin) {
                       this.skip();
               }
               createAccount(db, {
                       profileData
               }, {
                       validate
               }, (profile) => {
                       done();
               });
       });
});
```

**Comment by aMarCruz** [comment]
I'm using `describe.if` in node and sync tests with no issues:

```js
describe.if = function (condition, message, func) {
  (condition ? this : this.skip)(message, func)
}
```

Example of use:

```js
/* eslint-disable no-eval */
var gen1
var gen2
try {
  gen1 = eval('function* () { yield 1 }')
  gen2 = eval('function* () { yield 1 }')
} catch (ex) {
  console.log('    - Test for Generators skipped')
}
/* eslint-enable no-eval */

describe.if(gen1, 'Generators', function () {
  // ...
})
```

**Comment by aMarCruz** [comment]
Use this:

```js
describe.if = function (condition, message, func) {
  const run = condition ? this : this.skip
  run(message, func)
}
```
Example of use:

```js
var condition = false

describe.if(condition, 'Some test', function () {
  // test
})
```

**Comment by shirakaba** [comment]
Here are TypeScript typings for @aMarCruz 's approach in case anyone finds them useful.

```ts
/// <reference path="../node_modules/@types/mocha/index.d.ts" />
/* Note: this reference path may be in a different location for your project. */

declare module "mocha" {
    interface SuiteFunction {
        if: (condition: boolean, message: string, func: (this: Mocha.Suite) => void) => void;
    }
}

/* https://github.com/mochajs/mocha/issues/591#issuecomment-443841252 */
describe.if = function (condition: boolean, message: string, func: (this: Mocha.Suite) => void): void {
    const run: Mocha.PendingSuiteFunction = condition ? this : this.skip;
    run(message, func);
};
```

**Comment by PhABC** [comment]
@shirakaba Thanks for this! I get the intent, but can't get it working. Sorry if this is a novice question, where where am I supposed to add these declarations?

While typescript compiles fine when I use `describe.if` and VSCode shows me correctly the function definition, I get a `TypeError: describe.if is not a function` error. Any idea?

**Comment by shirakaba** [comment]
@PhABC Ah, yes – sorry to neglect.

You should have an entry file that always gets run first (e.g. `setup.spec.ts` or `index.spec.ts`) before any of your intended tests run. Add it all in there; think of it as a polyfill. You're getting the TypeError because a `describe.if()` block was run before the `describe.if` implementation was assigned.

Note: The "reference path" line needs to strictly be at the top of the file (no comments before it; can only be preceded by other reference paths), otherwise it'll be completely ignored.

**Comment by kot99a** [comment]
> jmls

Did you solve this issue (https://github.com/mochajs/mocha/issues/591#issuecomment-362203858)?
I faced with the same one. Maybe you can help, please.
