### ISSUE TITLE
mutation cov

### ISSUE THREAD

**Issue by tj** [mochajs/mocha#6]

**Comment by EvanHahn** [comment]
Any status on this? Seems like a long-lived issue that might not get addressed.

**Comment by jbnicolai** [comment]
@EvanHahn thanks for the interest. Seems that it's indeed a proposed feature of mocha, way back in it's early design days. I personally think the feature no longer corresponds with the goal of mocha, and would be something implemented as either a plugin or a wrapper around mocha - in any case, as a disctict and separate project.

If any of the other maintainers disagree, please reopen and let's discuss :)

// CC @mochajs/mocha

**Comment by boneskull** [comment]
@jbnicolai agreed. Sounds cool though.
