### ISSUE TITLE
add support for err.expected / err.actual

### ISSUE THREAD

**Issue by tj** [mochajs/mocha#65]
assertion libraries could opt-in allowing mocha to provide nicer formatting, diffs etc

**Comment by danielstjules** [comment]
Hope you don't mind if I close this - just going through old issues. You added support for this a few years back. :)

![screen shot 2015-03-07 at 2 47 55 pm](https://cloud.githubusercontent.com/assets/817212/6543645/fbbb0e0c-c4d8-11e4-84d3-5bc3867ba01b.png)
