### ISSUE TITLE
Expected/actual output is poor without color

### ISSUE THREAD

**Issue by p** [mochajs/mocha#702]
Example:

<pre>
% mocha --compilers coffee:coffee-script -C

  ���������

  ��� 1 of 3 tests failed:

  1) filterdata should work for nested hashes:
      
      actual expected
      
      1 | {
      2 |   "outer": {
      3 |     "middle": "value"
      4 |   }
      5 | }{}
</pre>

In this very simple example you should be able to tell that there is a non-empty hash and an empty hash. Looking at just this output you cannot tell which of the two is expected and which is actual.

Maybe you could do diff-style +/- when color is off.

**Comment by jbnicolai** [comment]
This should be much better nowadays.
