### ISSUE TITLE
Add option for passing a WriteableStream to Mocha on init for logging purposes

### ISSUE THREAD

**Issue by rquinlivan** [mochajs/mocha#732]
I'm interested in running a Mocha instance and capturing output in a WriteableStream. Right now Mocha uses `console.log` to echo all its messages. To accomplish this, I have to listen to stdout and do some extra work. This could be made easier with an optional stream that the user passes in and simply default to `console.log`. For example:

```coffeescript

myStream = fs.createWriteStream("path/to/my/file")

mocha = new Mocha
  ui: 'bdd'
  reporter: 'spec'
  stream: myStream  # defaults to console.log
```

**Comment by boneskull** [comment]
this is a fine idea, but is the responsibility of the reporters.  see #1457
