### ISSUE TITLE
How loop tests?

### ISSUE THREAD

**Issue by viniciuswebdev** [mochajs/mocha#738]
im doing:

  test_values = ["test1", "test2", "test3"]

  for value in test_values
    describe value, ->
      it value, ->
        console.log value

result:

one
      ◦ one: three
      ✓ one 
    two
      ◦ two: three
      ✓ two 
    three
      ◦ three: three
      ✓ three 

Thanks!

**Comment by ajouve** [comment]
Hi there, I have the same problem, why the test 1 and 2 are not failing ?
