### ISSUE TITLE
Please add support for running in d8

### ISSUE THREAD

**Issue by rafaelw** [mochajs/mocha#749]
d8 being the v8 console utility (https://code.google.com/p/v8/wiki/BuildingWithGYP).

This would be similar to running in node, except lacking all of the node standard libraries.

A bit of background: I'm a chromium/v8 developer and I'd like to switch unit tests for https://github.com/rafaelw/ChangeSummary over to mocha/chai, but I need to be able to run them in d8 for development purposes, as I use those tests to do performance work on Object.observe.

**Comment by danielstjules** [comment]
Closing as it looks like @rafaelw opted to use the stand-alone browser build for the project: https://github.com/Polymer/observe-js/blob/master/tests/index.html :)
