### ISSUE TITLE
Strange output when tests fail

### ISSUE THREAD

**Issue by wilsonpage** [mochajs/mocha#76]
**test/test.js**

```
describe('one', function(){
  it('should throw error', function(){

        [1,2,3].indexOf(1).should.equal(8);

  });
})


describe('two', function(){
  it('should pass', function(){

        [1,2,3].indexOf(4).should.equal(-1);

  });
})
```

**command:**

`mocha -r should`

**terminal output:**

  ..

←[91m  Ô£û←[0m←[31m 1 of 2 tests failed←[0m←[90m:←[0m

←[0m  0) one should do something: ←[0m←[31mAssertionError: expected 0 to equal 8

←[0m←[90m
  at Object.equal (C:\Users\Wilson\Documents\Sites\node_modules\should\lib\shoul
d.js:306:10)
      at Test.fn (C:\Users\Wilson\Documents\Sites\meshmesh-node\app\test\first.t
est.js:3:30)
      at Test.run (C:\Users\Wilson\Documents\Sites\node_modules\mocha\lib\test.j
s:80:29)
      at Array.<anonymous> (C:\Users\Wilson\Documents\Sites\node_modules\mocha\l
ib\runner.js:269:12)
      at EventEmitter._tickCallback (node.js:195:26)
←[0m

_I thought failed tests were supposed to simple show a red dot amongst green dots. This is on a windows machine. If my tests all pass, terminal output is pretty as in example screen shots._

**Comment by aa21** [comment]
Same issue for me (below), and I'm using Linux production server / Mac dev laptop:
(Maybe this post on stackoverflow can help to figure it out)[http://stackoverflow.com/questions/23687690/how-to-get-a-mocha-test-results-report-of-a-node-applicaton-in-html]

    Not Found
    404

    [0m[97m[41mError[0m[90m:[0m[37m [0m[97mNot Found[0m
    [0m  [0m
    [0m  [0m[90m-[0m [0m[93mapp.js[0m[90m:[0m[93m87[0m[37m [0m
    [0m  [0m  [0m[90m/Library/WebServer/Documents/seed2_backend/app.js:87:13[0m
    [0m  [0m
    [0m  [0m[90m-[0m [0m[93mlayer.js[0m[90m:[0m[93m95[0m[37m [0m[37mLayer.handle [as handle_request][0m
    [0m  [0m  [0m[90m[seed2_backend]/[express]/lib/router/layer.js:95:5[0m
    [0m  [0m
    [0m  [0m[90m-[0m [0m[93mindex.js[0m[90m:[0m[93m312[0m[37m [0m[37mtrim_prefix[0m
    [0m  [0m  [0m[90m[seed2_backend]/[express]/lib/router/index.js:312:13[0m
    [0m  [0m
    [0m  [0m[90m-[0m [0m[93mindex.js[0m[90m:[0m[93m280[0m[37m [0m
    [0m  [0m  [0m[90m[seed2_backend]/[express]/lib/router/index.js:280:7[0m
    [0m  [0m
    [0m  [0m[90m-[0m [0m[93mindex.js[0m[90m:[0m[93m330[0m[37m [0m[37mFunction.process_params[0m
    [0m  [0m  [0m[90m[seed2_backend]/[express]/lib/router/index.js:330:12[0m
    [0m  [0m
    [0m  [0m[90m-[0m [0m[93mindex.js[0m[90m:[0m[93m271[0m[37m [0m[37mnext[0m
    [0m  [0m  [0m[90m[seed2_backend]/[express]/lib/router/index.js:271:10[0m
    [0m  [0m
    [0m  [0m[90m-[0m [0m[93mapplication.js[0m[90m:[0m[93m232[0m[37m [0m
    [0m  [0m  [0m[90m[seed2_backend]/[express]/lib/application.js:232:9[0m
    [0m  [0m
    [0m  [0m[90m-[0m [0m[93mindex.js[0m[90m:[0m[93m618[0m[37m [0m
    [0m  [0m  [0m[90m[seed2_backend]/[express]/lib/router/index.js:618:15[0m
    [0m  [0m
    [0m  [0m[90m-[0m [0m[93mindex.js[0m[90m:[0m[93m256[0m[37m [0m[37mnext[0m
    [0m  [0m  [0m[90m[seed2_backend]/[express]/lib/router/index.js:256:14[0m
    [0m  [0m
    [0m  [0m[90m-[0m [0m[93mbooth.js[0m[90m:[0m[93m12[0m[37m [0m
    [0m  [0m  [0m[90m/Library/WebServer/Documents/seed2_backend/controllers/booth.js:12:3[0m
    [0m  [0m
    [0m  [0m[90m-[0m [0m[93mlayer.js[0m[90m:[0m[93m95[0m[37m [0m[37mLayer.handle [as handle_request][0m
    [0m  [0m  [0m[90m[seed2_backend]/[express]/lib/router/layer.js:95:5[0m
    [0m  [0m
    [0m  [0m[90m-[0m [0m[93mindex.js[0m[90m:[0m[93m312[0m[37m [0m[37mtrim_prefix[0m
    [0m  [0m  [0m[90m[seed2_backend]/[express]/lib/router/index.js:312:13[0m
    [0m  [0m
    [0m  [0m[90m-[0m [0m[93mindex.js[0m[90m:[0m[93m280[0m[37m [0m
    [0m  [0m  [0m[90m[seed2_backend]/[express]/lib/router/index.js:280:7[0m
    [0m  [0m
    [0m  [0m[90m-[0m [0m[93mindex.js[0m[90m:[0m[93m330[0m[37m     [0m[37mFunction.process_params[0m
    [0m  [0m  [0m[90m[seed2_backend]/[express]/lib/router/index.js:330:12[0m
    [0m  [0m
    [0m  [0m[90m-[0m [0m[93mindex.js[0m[90m:[0m[93m271[0m[37m [0m[37mnext[0m
    [0m  [0m  [0m[90m[seed2_backend]/[express]/lib/router/index.js:271:10[0m
    [0m  [0m
    [0m  [0m[90m-[0m [0m[93minit.js[0m[90m:[0m[93m33[0m[37m [0m[37mexpressInit[0m
    [0m  [0m  [0m[90m[seed2_backend]/[express]/lib/middleware/init.js:33:5[0m
    [0m  [0m
    [0m
