### ISSUE TITLE
Include also files in `spec` folder by default?

### ISSUE THREAD

**Issue by alexeypetrushin** [mochajs/mocha#778]
mocha.js supports both TDD and BDD styles. In BDD documents are called specifications, not tests. 

Putting "specifications" inside of folder called "test" looks a little strange, it would be nice if it would be possible to call that folder `spec` or `specs`. I.e. if mocha.js **by default** include not only files in `test` folder but also in `spec` folder.

What do you think?

**Comment by jbnicolai** [comment]
No thanks, the more versions the more confusing it would get.
