### ISSUE TITLE
--require expect.js doesn't work

### ISSUE THREAD

**Issue by juanolon** [mochajs/mocha#782]
hi, so when i include expect.js over the --require parameter, it doesn't work. i also tried putting this option on mocha.opts
--require expect.js
but i still getting "ReferenceError: expect is not defined"
does --require only work with should.js? or what do i missing?

**Comment by hoorayimhelping** [comment]
Thank you @schnittstabil :cake:

**Comment by mattc41190** [comment]
@schnittstabil where is the inject script called? Does mocha have an option for passing scripts? I thought it was only Mocha.opts. Feel free to tell me to RTFM if it is in there.
