### ISSUE TITLE
Add ability to add "comment" specs

### ISSUE THREAD

**Issue by tel** [mochajs/mocha#787]
Sometimes, especially when viewing test output in the browser or using the `spec` or `list` reporter, it'd be good for documentation to provide commentary on the stories being spec'd. For this reason, Id' like to be able to have a function `because` that could be used like

```javascript
describe('Some major feature', function () {
  it('ought to do this')
  because('but because sometimes X')
  it('ought to do this when X')
})
```

Or something to that regard. I can currently do that using a pending test case via `it`, but that's clearly the wrong semantics. Possible names/semantics are "because", "why", or "commentary".

**Comment by danielstjules** [comment]
Closing for now due to inactivity, and because there doesn't seem to have been much support/requests for this functionality since it was opened.
