### ISSUE TITLE
how to get test data in beforeEach() and afterEach()

### ISSUE THREAD

**Issue by jlipps** [mochajs/mocha#797]
I need to get the name of each test in `beforeEach` and the pass/fail status of each finished test in `afterEach`. I looked at using `this.test`, but from there the best thing I found was `this.test.parent`, which is the suite of tests. That's all well and good, but how do I know which of those tests is the one whose before/after block I'm in?

**Comment by bebraw** [comment]
@adamduffy You have probably solved this by now but you need to be very careful about scope when dealing with `this`. If you have inner functions there (no fat arrow, no explicit `bind`), they will have their own scope. You can either `bind` the scope to parent or set something like `var that = this` at root scope.

**Comment by ohadschn** [comment]
`this.currentTest.state` is great, but it's unclear exactly what are its possible values. A quick search through the [code](https://github.com/mochajs/mocha/blob/c7aec30eb4b3dbddc4564f5e6d02af8941f70eef/mocha.js) suggests it's either `failed` or `passed`.

**Comment by Visakeswaran** [comment]
How to get the state of previous test, in beforeEach hook?

**Comment by ORESoftware** [comment]
@Visakeswaran why would you want to do that? just curious? beforeEach only pertains to one test (the current test), not the previous test.

**Comment by lotosotol** [comment]
> @Visakeswaran why would you want to do that? just curious? beforeEach only pertains to one test (the current test), not the previous test.

I need to retrieve the status of the whole suite before closing the browser either before the .quit() method and pass those to BrowserStack (which accepts passed or failed only). My understanding is this would be something we cannot achieve in Mocha yet?! I've tried using the this.*** but couldn't really find a proper solution. Any thoughts?
