### ISSUE TITLE
Can mocha output the number of assertions?

### ISSUE THREAD

**Issue by dankohn** [mochajs/mocha#800]
I'm a refugee from jasmine-node to mocha, and am thrilled to have a working after function to clean up my test environment (see https://github.com/pivotal/jasmine/pull/56#issuecomment-15925846). The only thing I miss from jasmine is that it would output the number of assertions, like this:

```
Finished in 2.754 seconds
59 tests, 556 assertions, 0 failures
```

I understand that mocha decouples the assertion library (and I'm using expect.js), but does mocha have access to an assertion count that it can report? It's a nice positive feedback loop to see the number of assertions go up as we write more (and more thorough) tests.

**Comment by cameronwp** [comment]
I'm a little late to the party, but here's a non-hacky-ish way to get the number of tests. I'm using the [JSON reporter](https://mochajs.org/#json) to send stats to a python script as part of my precommit hook.

On the downside, I'm sure there's a more elegant solution - just look at that python script in the middle of a shell script.

On the plus side, the stats all come from JSON so you can trust them. Also, the JSON reporter isn't constantly printing to stdout so my precommit hook is noticeably faster!

```sh
#!/bin/bash

# Makes sure all tests are running and passing before committing.

# I tend to forget that I've got .only set somewhere. This script runs tests and then sanity checks the number of suites run.

export testing=true;
./node_modules/mocha/bin/mocha --recursive --retries 1 --reporter json > test.json && python -c "
import json
import sys

with open(sys.argv[1]) as file:
    data = json.load(file)

number_suites = data['stats']['suites']
number_failed = data['stats']['failures']
exit_code = 1

# assumes that if only one suite runs then .only is being used somewhere
if number_suites > 1 and number_failed == 0:
    exit_code = 0

if exit_code == 0:
    print('Success')
elif exit_code == 1:
    print(number_suites + ' suites run with ' + number_failed + ' tests failed')

sys.exit(exit_code)
" test.json;
rm test.json
```
