### ISSUE TITLE
Format errors in Git Bash

### ISSUE THREAD

**Issue by mcandre** [mochajs/mocha#801]
I'm happy to report that mocha's coloration and symbols display properly in Command Prompt terminals in Windows. However, I tend to code in a Cygwin/[Git Bash](http://msysgit.github.io/) terminal for better Unix support. Fortunately, mocha works very well in Git Bash, it's just that there are display glitches.

    > mocha test/email test/models test/routes test/routes/admin test/services test/unit te
    t/cron -t 4000

      ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
      ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
      ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
      ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
      ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
      ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
      ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
      ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
      ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
      ․․․․․․․․․․․․․․․․․․․․․․․․․․․

      ✔ 620 tests complete (24950ms)

On GitHub, this will display as periods. But they're not periods, they're special dots, which confuse Git Bash, displaying as rectangles. And the thing before `620 tests complete` also displays as a rectangle.

Could we add a terminal check for raw Command Prompt vs Cygwin/Git Bash, and correct the display accordingly?

**Comment by danielstjules** [comment]
@mcandre That's odd - Cygwin should support ANSI escape sequences. Do you still experience this issue?

**Comment by dasilvacontin** [comment]
If someone still experiences this issue, please tell and we will reopen this.

**Comment by chikamichi** [comment]
@dasilvacontin a friend of mine have been experiencing weird output from mocha when ran inside Git Bash:

```
←[0m  33 |       type←[1m:←[22m SWITCH_FACTION
  34 |     ←[32m}←[39m
> 35 |     le resultState ←[1m=←[22m reducer←[94m←[1m(←[22m←[39mundefined←[1m,←[22m dummyAction←[94m←[1m)←[22m←[39m←[1m;
←[22m
     |        ^
  36 |     expect←[94m←[1m(←[22m←[39mresultState←[1m.←[22misRadiant←[94m←[1m)←[22m←[39m←[1m.←[22mto←[1m.←[22meql←[94m←[1
m(←[22m←[39m←[36mfalse←[39m←[94m←[1m)←[22m←[39m←[1m;←[22m
  37 |   ←[32m}←[39m←[94m←[1m)←[22m←[39m←[1m;←[22m
  38 | ←[0m
```

Could it be related to a wrong unicode setting? The font used in Consolas.

**Comment by dasilvacontin** [comment]
@chikamichi That looks like color sequences not being interpreted correctly.

Can your friend try with `--no-colors`?

**Comment by chikamichi** [comment]
Thank you @dasilvacontin. I was able to find about [babel#1784](https://github.com/babel/babel/issues/1784) and fix the issue.
