### ISSUE TITLE
Watch files which are autocompiled using `--compilers`

### ISSUE THREAD

**Issue by utkarshkukreti** [mochajs/mocha#804]
File extensions which `--watch` watchers is currently hardcoded here - https://github.com/visionmedia/mocha/blob/master/lib/utils.js#L166

I use [Coco](/satyr/coco) language, which compiles fine with `--compilers co:coco`, but `--watch` doesn't watch `.co` files, which it should.

**Comment by jbnicolai** [comment]
Closed in favour of #1780
