### ISSUE TITLE
make --grep case insensitive?

### ISSUE THREAD

**Issue by eldargab** [mochajs/mocha#808]

**Comment by erezesk** [comment]
Hey,

Since grep is now regexp based, I tried sending ```/pattern/i``` but didn't seem to work
Is there a different way of getting the Grep to be case insensitive? 

Thanks :)

**Comment by boneskull** [comment]
Closed via 6126e38566abe2735491deb8b22b4ef88d50226c

**Comment by shanebdavis** [comment]
What was the conclusion on this issue? Case sensitivity plagues me daily - I miss tests when I'm greping because of case miss-match. Would a patch be accepted that adds a case-insensitive option for web-mocha and command-line mocha? --grep-ignore-case perhaps?

**Comment by boneskull** [comment]
@shanebdavis `--grep` accepts a regular expression, including a flag.  `--grep '/foo/i'` would find Foo and Foo and FOO etc.

**Comment by holm** [comment]
I would vote to change the default grep to be case-insensitive, when the grepped string is not "regex-like". This could be done in the next major version.

I think the vast majority would find case-insensitive more valuable, and for the edge-cases where that is not desired, they can specify a regex to get exactly what they want.

**Comment by boneskull** [comment]
Is `--fgrep` case-insensitive?  If not, that may be a better candidate.

**Comment by boneskull** [comment]
(`--fgrep` is a string-only search; if you want case-sensitive string searches, use `--grep <not-a-regex-string>`)
