### ISSUE TITLE
Support for asynchronous reporters ?

### ISSUE THREAD

**Issue by alexstrat** [mochajs/mocha#812]
I'd like to have a reporter that does an asynchronous task (reports test results to an external HTTP service) at the end of test run. However, mocha process ends as soon as [test runner ends](https://github.com/visionmedia/mocha/blob/master/bin/_mocha#L328), so any asynchronous actions is aborted..

While i know there might be some workaround with process piping, I'd prefer make that possible directly with a mocha reporter.

Would this feature make sense ? Any implementation suggestion ?

**Comment by danielstjules** [comment]
This should already be possible using `--no-exit` :)

``` javascript
$ cat test.js
it('test1');
it('test2');

after(function() {
  console.log(new Date());

  setTimeout(function() {
    console.log(new Date());
  }, 5000);
});


$ ./bin/mocha --no-exit test.js


  ․․Mon Mar 09 2015 00:35:02 GMT-0700 (PDT)


  0 passing (4ms)
  2 pending

Mon Mar 09 2015 00:35:07 GMT-0700 (PDT)
```
