### ISSUE TITLE
Truncated Stack Trace

### ISSUE THREAD

**Issue by machineghost** [mochajs/mocha#815]
When I run tests through the web-based runner, Mocha will take a stack trace like this:

    Uncaught Error: expected undefined to equal 'base:Sample' expect.js:99
    Assertion.assert expect.js:99
    Assertion.be.Assertion.equal expect.js:200
    Assertion.(anonymous function) expect.js:73
    (anonymous function) ConstraintSelectorTests.js:88
    jQuery.event.dispatch jquery.js:3332
    elemData.handle.eventHandle jquery.js:2941
    jQuery.event.trigger jquery.js:3210
    jQuery.fn.extend.triggerHandler jquery.js:3874
    func.apply.$.extend.__callback jquery.jstree.js:237
    $.jstree.plugin._fn.loaded jquery.jstree.js:539
    $.jstree._fn.(anonymous function) jquery.jstree.js:234
    (anonymous function) jquery.jstree.js:410
    (anonymous function) jquery.jstree.js:1653
    $.jstree.plugin._fn.load_node_json jquery.jstree.js:1724
    $.jstree._fn.(anonymous function) jquery.jstree.js:234
    $.jstree.plugin._fn.load_node jquery.jstree.js:1653
    $.jstree._fn.(anonymous function) jquery.jstree.js:234
    $.jstree._fn.(anonymous function) jquery.jstree.js:234
    $.jstree.plugin._fn.init jquery.jstree.js:410
    $.jstree._fn.(anonymous function) jquery.jstree.js:234
    (anonymous function) jquery.jstree.js:162

and reduce it to:

    Error: Uncaught Error: expected undefined to equal 'base:Sample' (file:///home/jeremy/workspace/syapse/src/syapse/static/js/ext/expect.js:99)
    at window.onerror (file:///home/jeremy/workspace/syapse/src/syapse/static/js/ext/mocha/mocha.js:5286:10)

Is this just an inherent limit of the fact that Mocha uses onerror to catch exceptions, or is there any way that Mocha could display the real stack trace instead?   Because while I can get the real trace from the console, having it in the browser window would be awfully convenient.

**Comment by danielstjules** [comment]
@andrew-luhring @keyvanfatehi Shorter stack traces were added in https://github.com/mochajs/mocha/pull/1564 :)

**Comment by dasilvacontin** [comment]
So the only problem left here is being able to log a `stack` in browser that don't have a `stack` on their errors. (?)

**Comment by jbnicolai** [comment]
I think this is no longer an issue, @dasilvacontin. Please correct me if I'm wrong.

**Comment by millerdev** [comment]
I still have this problem. If I'm understanding [the article](https://mikewest.org/2013/08/debugging-runtime-errors-with-window-onerror) linked in #958 correctly, it looks like [the latest version of mocha (2.3.3) does not use the fifth argument of `onerror`](https://github.com/mochajs/mocha/blob/v2.3.3/mocha.js#L12307). Incidentally, if I change it like so:
```
    global.onerror = function(err, url, line, col, errobj){
      fn(errobj || new Error(err + ' (' + url + ':' + line + ')'));
      return !mocha.allowUncaught;
    };
```
I get a full stack trace from Chrome, but not phantomjs. I'm not sure if it has something to do with the version of phantomjs or node I'm using? Or maybe I have something misconfigured? At any rate, here's a slightly less elegant solution that works:
```js
/**
 * Report full stack trace on async callback error
 *
 * Wrap async callback functions with this function
 * to report the full stack trace if they fail.
 *
 * Usage:
 *
 *  it("will always fail", function (done) {
 *      someAsyncFunction(asyncatch(function (arg) {
 *          doSomethingThatThrowsAnError();
 *          done();
 *      }));
 *  });
 */
function asyncatch(fn) {
    return function () {
        try {
            var args = Array.prototype.slice.call(arguments);
            return fn.apply(this, args);
        } catch (err) {
            throw err && err.stack ? new Error(err.stack) : err;
        }
    };
}
```

**Comment by mgiuffrida** [comment]
I've opened #2403 to address [the previous comment](https://github.com/mochajs/mocha/issues/815#issuecomment-152226789). Maybe discussion on this should continue in issue #958 as that one is specific to async errors.
