### ISSUE TITLE
Jenkins integration

### ISSUE THREAD

**Issue by podviaznikov** [mochajs/mocha#83]
It's more a questions then issue.
How to integrate mocha with Jenkins? Actually how to show mocha test results in Jenkins?

**Comment by yairEO** [comment]
@dhendo - What will be the commands for windows OS (not linux)? 10x

**Comment by dhendo** [comment]
You'll want to pipe the result of the mocha run into a file, so something like
`mocha -R xunit > $WORKSPACE/results/[name_under_test]_$BUILD_NUMBER.xml`

(I think)

**Comment by yairEO** [comment]
thanks, that's what I did and everything works well! thanks
