### ISSUE TITLE
Document root suite

### ISSUE THREAD

**Issue by tj** [mochajs/mocha#85]
https://github.com/visionmedia/mocha/commit/9585c00aa1c4876fa52bde3f232ec060e7d7928b

**Comment by danielstjules** [comment]
Closing as documentation was added for the root suite :)

![screen shot 2015-03-08 at 1 41 26 pm](https://cloud.githubusercontent.com/assets/817212/6547563/d74195ee-c598-11e4-8b32-8037967b316b.png)
