### ISSUE TITLE
-w option, i don't understand, or it's not working like expected

### ISSUE THREAD

**Issue by petershaw** [mochajs/mocha#857]
Hi, 
whenever i run mocha ion watch mode, the first run wokes great. All after then will bereportet with 0 tests complete. No tests are executed anymore. 

Lets assume i have a test like:
```javascript
var assert = require("assert")

describe('A Self Test', function(){
  describe('#indexOf()', function(){
    it('should return -1 when the value is not present', function(){
      assert.equal(-1, [1,2,3].indexOf(5));
      assert.equal(-1, [1,2,3].indexOf(0));
    })
  })
});
```

and run mocha with:
```bash
node_modules/mocha/bin/mocha -w test/aselftest.js 
```

the output after breaking the test is:
```bash
  A Self Test
    #indexOf()
      ✓ should return -1 when the value is not present 


  1 test complete (11 ms)

  0 tests complete (0 ms)
```

-V shows mocha Version 1.9.0

Is it a missunderstanding or something in the code? How can I use -w? How can i test continuously. 

Thanks, 
Peter Shaw

**Comment by jbnicolai** [comment]
Closing in favor of #1780
