### ISSUE TITLE
Display test's time in ms

### ISSUE THREAD

**Issue by tanx** [mochajs/mocha#863]
One killer feature of qunit, that prevents me from switching to mocha completely for my browser tests, is the display of required time in milliseconds. This allows me to abuse my unit tests for simple benchmarking/profiling and iterate quickly to tweek performance.

Mocha currently only displays the time for longer tests: http://whiteout-io.github.io/crypto-lib/test/index.html

What would be awesome if there was an option to always display runtime like so:
![bildschirmfoto 2013-05-23 um 13 16 54](https://f.cloud.github.com/assets/1374174/554018/5c67103a-c39a-11e2-9df7-caaf0e9374fe.png)

**Comment by kand** [comment]
@tj what would you recommend in place of test cases to provide a consistent platform for benchmarking?

Execution time acceptability is extremely relative to platform and use case, the testing framework shouldn't choose when and when not to display time, this option should be left up to the users of the framework.

**Comment by csvan** [comment]
+1, I agree with @tj that this does not have any real benchmark application, but it's an interesting metric all the same.

**Comment by dchambers** [comment]
This is already possible using the `-s` or `--slow` flag to set "'slow' test threshold in milliseconds", for example:

```bash
mocha test -s 0
```

**Comment by rash240719** [comment]
Why does timing appear only sometimes?
![test benchmark](https://user-images.githubusercontent.com/23238376/28946491-a468d2ee-7870-11e7-99ec-962ee90f947d.png)

**Comment by sangowen** [comment]
@rash240719 
It probably happened because those tests finished under 1ms and their durations were considered 0ms, which are not `slow` when `-s 0`.
I believe that this is the only case not being shown by the default reporter.

ref: [https://stackoverflow.com/a/32055699](https://stackoverflow.com/a/32055699)
