### ISSUE TITLE
Disable timeouts when running under the debug

### ISSUE THREAD

**Issue by kevindente** [mochajs/mocha#865]
Sometime's I'll be stepping through Node code in the debugger, which obviously draws out test execution time considerably, but Mocha still times out the test after 2 seconds. I've been getting around the problem by using .timeout(0), but it would be sweet if Mocha could detect that the code was running under the debugger (by checking the global.v8debug flag, at least in node) and disable timeouts in that case.

**Comment by netpoetica** [comment]
Worth noting, for anyone digging into this - the final decision was made to use

```
--no-timeouts
```
as the option name vs. `--disable-timeouts` in the linked commits

**Comment by ORESoftware** [comment]
don't know about you guys, but I can debug all my code in less than 2 seconds :)

**Comment by ORESoftware** [comment]
can someone explain here what --no-timeouts does and what it doesn't do? I have:

//package.json

  "scripts": {
    "start": "node ./bin/start.js",
    "test": "mocha test",
    "debug_mocha": "node-debug --no-timeouts _mocha"
  },

it still seems to show errors/warnings with the no-timeouts flag on, but perhaps it doesn't fail the tests before they all are attempted?

**Comment by zanemcca** [comment]
@ORESoftware I think you need to put the argument on the other side of the _mocha call

```
    "debug_mocha": "node-debug  _mocha --no-timeouts"
```

**Comment by rulatir** [comment]
These solutions are unsatisfactory. We absolutely positively do need an option to **automatically** disable timeouts if mocha is being run under a debugger.

**Comment by netpoetica** [comment]
> don't know about you guys, but I can debug all my code in less than 2 seconds :)

This is cute if you're thinking about run time and optimization - of course your functions should run quickly. However, if you are debugging, and for example, you are traversing some giant JSON and running find/filter functions on the data sets to poke around in things, then you may timeout. Now, of course, if it is like a response JSON, you can just copy paste into a JSON editor. But, if you are doing something where you are looking at 1 object, deeply, and based on that information, moving into another object somewhere else, deeply again, and following a complicated process like this, then even if your function runs in well under 2s, your debugging process can be quite long. AKA point is moot but nice humblebrag :)

**Comment by dhowe** [comment]
any update on this??

**Comment by mark-wiemer** [comment]
@dhowe what is your complaint, specifically? This issue is from 2013 and was closed, you're welcome to open a new bug with modern context of your issue

**Comment by cschot** [comment]
@dhowe 
It looks likes, at least in VS Code, mocha or VS Code still do not do this automatically for us. But there are ways to automate this a bit.
When using VS Code you can add a configuration in launch.json to use your normal test script and add --no-timeout at debug time.

Let's say you have this:
```jsonc
/*
 * package.json:
 * /
{
	/* ... */
	"scripts": {
		/* ... */
		"test": "mocha {/* options and files for automated tests */}"
	},
	/* ... */
}
```
And you want to append `--no-timeout` when debugging.
To configure this, go to the "Run and Debug" panel (CTRL/CMD + SHIFT + D) 
At the top of the panel, click on the selection box behind the green start button.
Click add configuration. Add this to the configurations array:

```jsonc
/*
 * launch.json configurations array:
 */
{
      "name": "Run tests",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "npm",
      "runtimeArgs": [
          "run-script", 	// tells NPM to run a script.
      	  "test",		// tells NPM which script to run from your package.json
       	  "--",			// this is crucial. It is a separator and will pass every value that comes after it to mocha instead of npm
          "--no-timeout"	// This parameter is pass to mocha
    ],
    "internalConsoleOptions": "openOnSessionStart"
}
```
Save `launch.json` and go the the "Run and Debug" panel again. Select the configuration name you just added, e.g. `Run tests`.
Click the green start button or press F5.
This will run `path/to/nodejs/npm.cmd --experimental-network-inspection run-script test -- --no-timeout`
Mocha should now run without timeouts.
