### ISSUE TITLE
Add a way to hint implementation-files to --watch

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [mochajs/mocha#870]
Currently, `--watch` only re-runs your tests when *the test files themselves* change. Obviously, that's somewhat less than ideal.

I'd love to see `--watch` take an optional *argument*, that being a glob of files or directories (other than the tests, which are already listed at the command-line) to subscribe to changes for.

Example:

    mocha --watch Source/ --reporter dot --watch Test/*.js

**Comment by jbnicolai** [comment]
Closing in favor of #1780
