### ISSUE TITLE
Add a key-press to re-run the specs under --watch

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [mochajs/mocha#871]
I love --watch. It's great. But there's a few situations where I need to re-run the tests, and it doesn't catch them (i.e. changing an implementation file, as opposed to a test-file, see #870); it'd be nice if hitting the spacebar with the Terminal focused (or something along those lines) forced a re-run of the tests.

Along the same lines, it might be nice to be able to configure a minimum timeout to re-run them *anyway*, so that the window is always up-to-date, even if it misses a change. (Obviously more tenable for small projects than big ones … but isn't that *already* the case with `--watch`?)

**Comment by al-the-x** [comment]
How hard would adding a system event listener be? Maybe `SIGINT` to the process to rerun, twice to quit (a la the node REPL)...?

**Comment by ELLIOTTCABLE** [comment]
(@al-the-x why SIGINT? There's plenty of other signals that don't stomp on a user's ⌃C expectations. `man signal`.)

**Comment by al-the-x** [comment]
I agree that a different signal would be more appropriate: `SIGINFO`, `SIGIO`, etc. I don't know to many folks that know how to send anything other than `SIGINT` via the keyboard... I usually wow them with `^D` and `^Z`, and I teach the stuff to professionals.

Maybe `^C` shows some info on which signals are supported and a hint to the control character... Wouldn't recommend trying to parse their `stty -a` or anything, but a reminder might help.

**Comment by ELLIOTTCABLE** [comment]
@al-the-x to most users, ⌃C isn't ‘send a signal to the program’, it's ‘get me out of this program to the place where I type other programs' names.’ And that's assuming they know that those two things are *different*. Hence my original suggestion of swallowing the space-bar or something; that's a more intuitive interface for the vast majority of users, than attempting to explain UNIX signals to them (or worse, stomping on possibly pre-existing expectations of being returned to the terminal, to do so)

**Comment by TimothyGu** [comment]
I have to agree with @ELLIOTTCABLE here. SIGINT means "interrupt," i.e. "mocha, f*ing die!"

`SIGUSR1` might be fit for this job, but it's impossible to type that on a keyboard.

`SIGINFO` means:

> A synonym for **SIGPWR**
>
> (`man 7 signal`)

Which is:

> Power failure (System V)
>
> (`man 7 signal`)

nodemon's approach might be best, i.e. typing `rs\n`.

**Comment by boneskull** [comment]
IMO "watch" should be killed.  There are other tools which do this sort of thing much better.

**Comment by dasilvacontin** [comment]
+1 to kill watch. I don't see the point of replicating the functionality of a watcher inside the project, when any watcher tool will do the job.
