### ISSUE TITLE
Support for branchData (or similar) in coverage

### ISSUE THREAD

**Issue by ckknight** [mochajs/mocha#886]
Some tools such as [JSCover](http://tntim96.github.io/JSCover/) allow instrumentation that includes branchData, to better accommodate for whether every branch within code is ran (based on the truthiness of the conditional). It could be nice to have support for it in mocha's cov runner.

I've written my own coverage instrumentation tool for [GorillaScript](http://ckknight.github.io/gorillascript), would like to implement branch coverage, but have no incentive to until mocha supports it.

**Comment by jbnicolai** [comment]
Unless you're going to introduce a PR for this yourself, I don't think it's going to happen anytime soon. 

As there's been no other activity on this thread for over a year I'm closing this for now.
