### ISSUE TITLE
add some shared behavior style docs

### ISSUE THREAD

**Issue by tj** [mochajs/mocha#90]
and add the wiki to the site

**Comment by danielstjules** [comment]
Wiki is linked to from the site, in the footer:
![screen shot 2015-03-08 at 1 43 16 pm](https://cloud.githubusercontent.com/assets/817212/6547581/47c671c2-c599-11e4-9702-c0d6c5f01612.png)

And the wiki contains a section about shared behavior: https://github.com/mochajs/mocha/wiki/Shared-Behaviours
