### ISSUE TITLE
Object diff doesn't show properties set to undefined, which may the difference

### ISSUE THREAD

**Issue by alFReD-NSH** [mochajs/mocha#905]
![screenshot from 2013-06-25 21 04 30](https://f.cloud.github.com/assets/822510/702634/d1e571f0-dd97-11e2-9307-7cbaff17614d.png)

As you in the picture, there seems to be no difference, but actually the difference is in that one object contains a property set to undefined and the other doesn't. Here's the code to replicate it. I expected to see at least a more helpful error message.

```javascript
require('should');
var _ = require('lodash');
it('Help full character diff', function () {
    var objA = {challenge : 'Can you tell me whats the difference between expected and actual?', 'good luck' : true };
    var objB = _.clone(objA);
    objB.a = undefined;
    (objA).should.eql(objB);
})
```

As for a solution, you fall back to printing the normal error message if the actual and expected are the same.

Again as I said in #903, a better solution is to use a module that is built to make object diffs from javascript like difflet.

**Comment by jbnicolai** [comment]
Closing, as #1357 has been merged :)
