### ISSUE TITLE
Allow users to specify ignored directories for the -w option or ignore all hidden directories

### ISSUE THREAD

**Issue by brodo** [mochajs/mocha#909]
Currently 'node_modules' and '.git' are excluded per default. It would be nice if the user could add more ignore paths. Alternatively, maybe all hidden directories should be ignored per default.

**Comment by jareware** [comment]
Something that `--watch` currently has going for it is *speed*. Especially if you have e.g. Babel doing transpilation, invoking `mocha` separately for each test run is *immensely* slower than the re-run watch mode does.

Ideas on how to work around this with an external watcher?
