### ISSUE TITLE
Object diff is shown as a string, new lines are '\n' characters and it's not readable.

### ISSUE THREAD

**Issue by alFReD-NSH** [mochajs/mocha#952]
![screenshot from 2013-08-15 12 16 07](https://f.cloud.github.com/assets/822510/966987/bb76e98e-0561-11e3-820c-0b445650dcfe.png)

The picture says it all. I remember object diffs were easy to read with new lines!

Using node@0.10.13, mocha@1.12.0, should@1.2.2

**Comment by jbnicolai** [comment]
I believe this issue is no longer present in the current version(s) of mocha.
