### ISSUE TITLE
highlight test codelines in stacktraces

### ISSUE THREAD

**Issue by tarjei** [mochajs/mocha#961]
I'm not sure if this is hard or easy, but here goes:

It would be great if there was a way to get the standard reporter to highlight the lines in the stacktrace that match a simple regexp.

This would be a great tool to quickly find the offending line when looking through a stacktrace of 40 - 50 lines and looking for the one line where you invoke a function - the rest of the lines are often just noise..

**Comment by danielstjules** [comment]
I'm gonna close this as I think the end goal was achieved in https://github.com/mochajs/mocha/pull/1564

For example
```javascript
$ cat example.js
it('test', function(done) {
  done(new Error('Something went wrong!'));
});

$ mocha example.js

  ․

  0 passing (5ms)
  1 failing

  1)  test:
     Error: Something went wrong!
      at Context.<anonymous> (example.js:2:8)
```

Neat, right :)
