### ISSUE TITLE
escaping error message content prevents displaying images in results

### ISSUE THREAD

**Issue by maliberty** [mochajs/mocha#968]
I'm new to Mocha but liking it so far.  I wanted to port over js-imagediff (https://github.com/HumbleSoftware/js-imagediff) to Mocha as it only provides a jasmine interface currently.  It nicely shows a graphical diff in its error output as can be seen at the example at http://humblesoftware.github.io/js-imagediff/test.html

The problem I've run into with mocha is that it html escapes the error messages preventing the embedding of images.  This makes a port impossible.  As far as I can see the issue lies in html.js

el.appendChild(fragment('<pre class="error">%e</pre>', str));

where the %e invokes escaping on the message.  Perhaps the framework could provide an option for the matcher to say the output shouldn't be escaped.  I image a flag on the test.err could serve this purpose.

If this seems reasonable I'm willing to work on such a change.

**Comment by boneskull** [comment]
possible to catch the errors and unescape them?

**Comment by boneskull** [comment]
closing as old
