### ISSUE TITLE
Ruby's RSpec let syntax

### ISSUE THREAD

**Issue by lucassus** [mochajs/mocha#971]
It would be nice to have the power of `let` syntax inside mocha specs.
There is a similar feature request for jasmine https://github.com/pivotal/jasmine/pull/101?source=cc

**Comment by stalniy** [comment]
One more implementation which doesn't use `this`: https://github.com/stalniy/bdd-lazy-var

**Comment by maboesanman** [comment]
I've also created a minimal implementation of this behavior called [givens](https://github.com/enova/givens)

**Comment by rkofman** [comment]
The *givens* interface is brilliant, thank you! The brilliance of being able to have code that is defined in a different order than it is run makes for *far* cleaner tests. No longer copy-pasting every `before` block in every test! Thank you.
