### ISSUE TITLE
When run programmatically, subsequent runs produce different results compared to the first run

### ISSUE THREAD

**Issue by vwong** [mochajs/mocha#972]
I've noticed that when running Mocha programmatically in node.js:

* A re-run of an originally failing test results in a timeout error subsequently.  This is fixed by deleting the test state in runner.js as attached.
* A re-run of an originally timed-out test results in Mocha hanging forever subsequently.  This is fixed by resetting the timedOut attribute to false in runnable.js as attached.

I expected the same results every time - failed and timed out respectively.  The patch below fixes these issues, but since I'm not that familiar with Mocha code, so I'm not sure if these are the best places in the code to make these changes, that's why I didn't do this as a pull request; the diff should help nonetheless.

This may be related to #435.

    diff --git a/lib/runnable.js b/lib/runnable.js
    index b34bf1e..06f0ada 100644
    --- a/lib/runnable.js
    +++ b/lib/runnable.js
    @@ -161,6 +161,7 @@ Runnable.prototype.run = function(fn){
       // timeout
       if (this.async) {
         if (ms) {
    +      self.timedOut = false;
           this.timer = setTimeout(function(){
             done(new Error('timeout of ' + ms + 'ms exceeded'));
             self.timedOut = true;
    diff --git a/lib/runner.js b/lib/runner.js
    index c42e449..a185321 100644
    --- a/lib/runner.js
    +++ b/lib/runner.js
    @@ -397,6 +397,7 @@ Runner.prototype.runTests = function(suite, fn){
         // execute test and hook(s)
         self.emit('test', self.test = test);
         self.hookDown('beforeEach', function(){
    +      delete self.test.state;
           self.currentRunnable = self.test;
           self.runTest(function(err){
             test = self.test;

**Comment by boneskull** [comment]
old.  please comment if this is still a problem

**Comment by tcoopman** [comment]
I'm not sure if it's the same problem, but when you want to rerun Mocha programmatically, you have to do the same thing `--watch` does. Deleting the `require.cache`. See here: https://github.com/mochajs/mocha/blob/3a718587115a8578c1d0a283bbe214d09a35831b/bin/_mocha#L364.

I've done this in a gulpfile myself: https://gist.github.com/tcoopman/243104e5df8cd99467c7#file-gulpfile-js-L43
