### ISSUE TITLE
Running tests asynchronously

### ISSUE THREAD

**Issue by ghost** [mochajs/mocha#98]
Is there a way for me to run the tests asynchronously.

I am testing my HTTP API for a database and each HTTP request takes 1-2 sec to finish and it would be really good if the tests are run asynchronously so each test doesn't have to wait for the test before to finish.

That would cut down the testing time to 1-2 sec instead of adding 1-2 sec for each test.

**Comment by kumar303** [comment]
There is a third party module ([mocha.parallel](https://github.com/danielstjules/mocha.parallel/)) where you can opt-in a suite of tests by replacing `describe()` with `parallel()`.  I think this should be pretty safe as long as you know your tests are not patching any shared objects. It can speed things up if the functions under test are IO bound.

**Comment by danielstjules** [comment]
Better async support is something that @boneskull is looking into for the mocha rewrite. mocha.parallel is a hack at best, and unfortunately, you'll almost certainly hit issues where it can't do what you want since you give up on most of the mocha API.
