### ISSUE TITLE
Progress logging inside a test

### ISSUE THREAD

**Issue by rassie** [mochajs/mocha#986]
When running UI tests with Mocha (e.g. with Selenium / Webdriver), tests can last a long time, especially with complex workflows being checked. In such cases, it'd be a tremendous help to output some kind of progress message ('Clicking on button', 'Form submitted', etc.) which could be rendered by more verbose reporters like `spec`. I probably could abuse pending tests for that, but it's very unclean.

**Comment by boneskull** [comment]
old
