### ISSUE TITLE
Support a scale factor as input to per-test slow() method, not just absolute values

### ISSUE THREAD

**Issue by bcronin** [mochajs/mocha#994]
First, thanks fixing issue #402.

An additional nicety would be to support the input as a multiplier / scale factor rather than an absolute value.

A scale factor may make more sense and be more future-proof.  For example, I may expect a computationally expensive test to be ~10x slower than the baseline limit, but in absolute terms the timeout might vary significantly between my 5-year old netbook and the my modern high-end workstation.  Furthermore, even a very high-end machine, there's still value in a warning that a test is more than 10x slower than the baseline -- even if it finished in an "ok" absolute amount of time.

This could likely be cleanly implemented via a "%" or "x" suffix on the input.

    it ("should do something slow", function() {
         this.slow("1000%");

         // The "x" suffix might be another option since the %'s
         // likely would often by very large numbers
         // this.slow("10x");   

         var n = callSomeSlowFunction();
         expect(n).to.equal(123);
    })

**Comment by boneskull** [comment]
can't you just do a little bit of math?

**Comment by boneskull** [comment]
old
