### ISSUE TITLE
Code coverage doesn't cover files without tests

### ISSUE THREAD

**Issue by jonursenbach** [mochajs/mocha#996]
Pretty self-explanatory. I have 20 or so files in app/ with zero coverage, and one test in test/. None of the files without tests are showing up in coverage.html

```
test:
	mocha --reporter spec

coverage: app-cov
	CODE_COVERAGE=1 mocha --reporter html-cov > coverage.html

app-cov:
	jscoverage app app-cov

.PHONY: test
```

**Comment by boneskull** [comment]
old; sounds like a jscoverage problem anyway
